### ISSUE TITLE
Identify and fix all developer console warnings and errors in Meshery UI

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#10002]
### Current Behavior
Presently there are so many warnings and errors coming in developer console, most of them are because of passing classNames and attributes in the wrong way.

### Expected Behavior
Developer console should contain fewer warnings and errors, which helps in to debug better

### Screenshots/Logs
![Screenshot 2024-01-18 at 12 55 00 AM](https://github.com/meshery/meshery/assets/71271069/d1945427-44f5-4d02-92e4-d994b38ed1e0)

### Acceptance test
- [ ] Identify all errors and write up in PR.
- [ ] Fixing these errors should not change the present behavior of UI.
- [ ] Remove all console.logs

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by alex-k-exe** [comment]
I'd like to work on this issue, could someone please assign it to me

**Comment by sudhanshutech** [comment]
hey @alex-k-exe , have you setup meshery successfully?

**Comment by dottharun** [comment]
Regarding the console log issue:

- So, I did a quick grep and found about 154 instances of console.log() in `meshery/ui`.
- Many of them are just there to display valid errors.
- Thinking, could we switch the ones handling valid errors to console.error() and get rid of the unused ones?

If this sounds good, I'd love to take this on as my first issue!

**Comment by sudhanshutech** [comment]
Thank you, @JyothiSwaroopReddy07, for the pull request! I appreciate your initiative. In the future, could you please make sure to ask and get assigned the issue before raising a pull request? This helps us ensure proper coordination.

**Comment by JyothiSwaroopReddy07** [comment]
sure @sudhanshutech
