### ISSUE TITLE
[Docs] Broken link in reference/rest-apis page in documentation

### ISSUE THREAD

**Issue by ASK-03** [meshery/meshery#10009]
### Current State
Link: https://docs.meshery.io/reference/rest-apis
Currently, the summary of the Authentication has a broken link (shown in the picture below)

![Docs  broken link providers](https://github.com/meshery/meshery/assets/98012930/420891e4-21f8-42eb-9173-c3061d0facfb)

### Desired State
It should point towards the [link](https://docs.meshery.io/extensibility/providers)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Raj100679** [comment]
@ASK-03 Can I work on this

**Comment by ASK-03** [comment]
Hello @Raj100679! I, too, am a contributor like yourself. While reviewing the documentation, I came across a bug. I'm currently awaiting approval/feedback from the maintainers for this issue.

P.S.: I've implemented all the necessary changes and, if approved, I'd like to create the pull request for this issue. Apologies for any inconvenience caused.
