### ISSUE TITLE
[Docs Meshery Architecture] - Figure Alignment and UI Fixes

### ISSUE THREAD

**Issue by shourya2002-geek** [meshery/meshery#10005]
### Current State

<img width="973" alt="Screenshot 2024-01-18 at 1 55 03 AM" src="https://github.com/meshery/meshery/assets/75240318/49283f77-edf7-484a-8560-79f3baccc653">

Link: https://docs.meshery.io/concepts/architecture#adapters-and-capabilities-registry

The "Meshery Adapter Operation Registration" figure is not aligned correctly, and the text from the paragraph above is misaligned as well.

### Desired State

The figure and the text can be aligned in the format as followed for the other sections on the page.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by amitamrutiya2210** [comment]
Hey @shourya2002-geek, can I work on this issue? I believe it's a great starting point for me to explore this repository.

**Comment by theavitw** [comment]
@shourya2002-geek oK ! I can see it. You can assign it to me.

**Comment by Anuragt1104** [comment]
<img width="863" alt="Screenshot 2024-01-21 at 3 30 19 AM" src="https://github.com/meshery/meshery/assets/113992608/880b0013-4f87-4d8b-ab32-a4ee5572818f">


not able to reproduce the issue.

**Comment by shourya2002-geek** [comment]
Hi @Anuragt1104 , do you have a macbook or a windows laptop ?

**Comment by Anuragt1104** [comment]
macbook air

**Comment by shourya2002-geek** [comment]
<img width="1509" alt="Screenshot 2024-01-21 at 4 05 47 AM" src="https://github.com/meshery/meshery/assets/75240318/cff0aed4-3b92-4052-90a6-72eb80d10259">

For me , it's still like this. Can someone else confirm ?

**Comment by ayushgml** [comment]
![Screenshot 2024-01-21 at 3 20 34 PM](https://github.com/meshery/meshery/assets/72748253/d0d209b3-2240-48b2-bae7-284f746239f8)

For me too it's looking misaligned.
