### ISSUE TITLE
[Playground Pop-Up] - Grammar adjustment

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#10004]
### Current Behavior

Currently, the text on the pop-up modal in the < i > tag reads as follows:  " Friends dont let friends GitOps alone. Visually design and collaborate in real-time with other MeshMap users. "

### Expected Behavior

To increase readability and user experience the sentence should read as follows: " Friends don't let friends GitOps alone. Visually design and collaborate in real-time with other MeshMap users. "

### Screenshots/Logs

![Screenshot 2024-01-17 210535](https://github.com/meshery/meshery/assets/19821445/3c78ed70-1860-4ee1-8974-03ddf06505ad)

### Requirement
For debugging purposes, it is suggested that the contributor taking on the task has a [MeshMap](https://meshery.layer5.io/) account.

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by amitamrutiya2210** [comment]
Hey @sandramsc, can I work on this issue? I believe it's a great starting point for me to explore this repository.

**Comment by sandramsc** [comment]
Hi @amitamrutiya2210 I have assigned this to you.
