### ISSUE TITLE
[Docs Importing Apps] - Grammar adjustment

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#10011]
### Current State
Link: [Meshery Docs](https://docs.meshery.io/guides/configuration-management/importing-apps)

Currently, the paragraph under 'Importing Applications' reads as follows: "Import your existing application definitions and your existing infrastructure configruations into Meshery Meshery supports a number of different application definition formats. You can import apps into Meshery using either the Meshery CLI or the Meshery UI." 

- The word **Meshery** is repeated twice in close succession. 
- Correct spelling 
#### Screenshots

![cddddccc](https://github.com/meshery/meshery/assets/19821445/b60e7ed3-cf4d-48ba-9e1d-dc6d1879bde6)

### Desired State
The paragraph can be rephrased for enhanced readability and a better user experience, taking the following form: "Import your existing application definitions and existing infrastructure configurations into Meshery. The platform supports a variety of application definition formats, and you can import apps using either the Meshery CLI or the Meshery UI."

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ayushgml** [comment]
@mentors can I be assigned this issue? I would like to work on this issue!

**Comment by Ankitmohanty2** [comment]
is this issue solved?? Can I Work on This Issue.

**Comment by ayushgml** [comment]
@Ankitmohanty2 I am working on this issue

**Comment by Ankitmohanty2** [comment]
Ok no worries thank you for letting me know
