### ISSUE TITLE
[Server] Unable to open published catalog item

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10010]
### Current Behavior
Downloading and importing this Design results in failure - https://meshery.layer5.io/catalog/66d4e848-fe7e-4baf-b8db-9ff54d0113d6

### Screenshots/Logs
<img width="580" alt="Screenshot 2024-01-18 at 3 30 53 AM" src="https://github.com/meshery/meshery/assets/7570704/95efaf37-c735-4d35-9ce3-c8b8354d77ca">

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by theBeginner86** [comment]
Its not a bug.

The issue is that the download operation in catalog is downloading Meshery Pattern and not PatternFile.

So when you upload the downloaded file it fails to evaluate the file and refuses to upload.

We need to update the download handler in cloud. // @senali-d @sudhanshutech 

Meshery Pattern (being downloaded)
```
id:...
name:....
user_id:....
pattern_file:....
location:....
visibility:....
catalog:....
created_at:...
updated_at:...
type:...
SourceContent:....
user:....
```

Patternfile to be downloaded
```
name:....
services:...
```

**Comment by theBeginner86** [comment]
_You may test by downloading and uploading the same published design from Meshery UI (or MeshMap). It would behave as expected._

**Comment by theBeginner86** [comment]
This has been fixed 👍
