### ISSUE TITLE
[CI] Fix failing MeshMap Screenshot service

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#10023]
### Current Behavior

https://github.com/meshery/meshery/actions/runs/7585590093

This failed due to recent update to POST handler to meshery patterns.

### Desired Behavior

Update the payload handler in snapshot service

### Acceptance Tests

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by leecalcote** [comment]
Thank you.

**Comment by leecalcote** [comment]
FYI:

https://github.com/meshery/meshery/actions/runs/7620324948/job/20754865239?pr=10053#step:5:829
```
parse error: Invalid numeric literal at line 1, column 5
```

**Comment by theBeginner86** [comment]
> FYI:
> 
> https://github.com/meshery/meshery/actions/runs/7620324948/job/20754865239?pr=10053#step:5:829
> 
> ```
> parse error: Invalid numeric literal at line 1, column 5
> ```


Fixed: https://github.com/meshery/meshery/pull/10066#issuecomment-1907594786
