### ISSUE TITLE
[Docs Tasks] - Missing list item description

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#10037]
### Current State
Link: [Meshery Docs](https://docs.meshery.io/tasks)
Currently each list item under "Meshery Functionality" has a description. However the item "Managing Events with Notification Center" does not have one.
#### Screenshot
![Screenshot 2024-01-20 190307](https://github.com/meshery/meshery/assets/19821445/16019e1d-1373-409f-b6bf-d2b78e0caabe)

### Desired State
Add a description for the list item "Managing Events with Notification Center".

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sandramsc** [comment]
CC: @iArchitSharma

**Comment by Raj100679** [comment]
@sandramsc If I know what description to add here, I would like to work on this

**Comment by Anuragt1104** [comment]
The link to the above item is not working properly. how to access the content of the page?

**Comment by iArchitSharma** [comment]
@RipulHandoo would you like to worknon this?

**Comment by Raj100679** [comment]
@iArchitSharma Can I work on this?
