### ISSUE TITLE
[Meshery-Cloud] [Share your design PopUp] - Grammar adjustment

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#10038]
### Current Behavior

Currently, the text on the "Share your design" pop-up modal reads as follows: " Invite your teammates to collaborate on a design. They don't even need a Meshery account to view your design! Designs set to public visibility by default. If you have a Team or Enterprise [subscription](https://meshery.layer5.io/account/subscriptions), you can create private of designs. "
### Expected Behavior

To increase readability and user experience the sentence could read as follows: " Invite your teammates to collaborate on a design – they don't even need a Meshery account to view it! Designs are automatically set to public visibility by default. With a Team or Enterprise subscription, you can also create private designs. "
### Screenshots/Logs

![Screenshot 2024-01-20 192008](https://github.com/meshery/meshery/assets/19821445/a8ca8e8f-4e46-46f1-b51a-f2bf884607ab)
### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Raj100679** [comment]
@sandramsc Can you assign this to me?

**Comment by Ayush-k-Shukla** [comment]
@sandramsc i would like to work on this can you please assign this to me ?

**Comment by cosmos1721** [comment]
if no one's working on this issue, can I work on it?

**Comment by hardikn13** [comment]
Is it still available? @sandramsc

**Comment by Mehulyadavv** [comment]
I'd love to work on this issue...

**Comment by narasimha-1511** [comment]
i'm also intrested to work on this issue ?

**Comment by 11happy** [comment]
Hello @sandramsc , I am interested to work on this issue can you please assign this to me.

**Comment by sandramsc** [comment]
@11happy I will assign this to you you (its been a couple months since other contributors have asked for assignment).

**Comment by 11happy** [comment]
Hello @sandramsc , I think I need to work on meshery-cloud, where can I find that repo?

**Comment by Aviral0702** [comment]
How to reproduce this issue?

**Comment by akshansh-modi** [comment]
Hi, I found this issue labeled as "good first issue." Is it still open? If so, could you please assign it to me? Thanks!

**Comment by sandramsc** [comment]
> Hello @sandramsc , I think I need to work on meshery-cloud, where can I find that repo? edit: Currently I unassigned myself, as meshery-cloud is invite only, but will love to work on this.

@sudhanshutech It appears as though the issue is in an invite only repo? How do you suggest we approach the solution to resolving it?
