### ISSUE TITLE
Two links for "Managing Events with Notification Center" one not working properly.

### ISSUE THREAD

**Issue by Anuragt1104** [meshery/meshery#10043]
<img width="1112" alt="Screenshot 2024-01-21 at 3 36 05 AM" src="https://github.com/meshery/meshery/assets/113992608/1124216c-b1ad-468f-b001-40119099760e">

### CurrentBehavior
On the [main page](https://docs.meshery.io/), there are two links  for "Managing Events with Notification Center" and one of the links is not redirecting to  the desired webpage 
<img width="1289" alt="Screenshot 2024-01-21 at 3 42 16 AM" src="https://github.com/meshery/meshery/assets/113992608/83dc5999-5434-49fa-bb61-b28c55602d70">

### Desired Behavior
fix the broken second link 

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by dottharun** [comment]
@Anuragt1104 My local setup is complete can i work on this issue?
