### ISSUE TITLE
[Extensions] Meshmap crashes on navigating to filters tab

### ISSUE THREAD

**Issue by aabidsofi19** [meshery/meshery#10040]
### Current Behavior

![image](https://github.com/meshery/meshery/assets/65964225/6c782ad8-ce5d-43c5-8d83-b7a3fa8f2caf)

Full error message 
![image](https://github.com/meshery/meshery/assets/65964225/200f9be4-7d89-4bda-b6ca-4021076480b3)

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MUzairS15** [comment]
![Uploading Screenshot 2024-01-22 at 7.43.01 PM 1.png…]()
