### ISSUE TITLE
[Extensions] Visualizer: Design link - Increase tooltip display speed

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10079]
### Current Behavior

Is this a client-side or server-side issue, @AjaxAueleke?

<img width="626" alt="Screenshot 2024-01-23 at 10 36 00 AM" src="https://github.com/meshery/meshery/assets/7570704/db00f9d7-353b-4de9-82b9-480b1057203d">

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by aabidsofi19** [comment]
@AjaxAueleke  any success there
