### ISSUE TITLE
[Server] Enhance Design Import Notification

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10071]
### Current Behavior and Desired Behavior
<img width="1686" alt="Screenshot 2024-01-23 at 3 27 15 PM" src="https://github.com/meshery/meshery/assets/7570704/60600910-6300-4e4f-8caf-4a460ee3e7e5">

### Implementation
1. Use [Meshery Server's Event Notification framework](https://docs.meshery.io/project/contributing/contributing-server-events) to enhance these types of messages.

### Acceptance Tests
1. Notification message has the filename of the imported file in double quotation marks.
2. Notification message has a hyperlink to the design file.

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ASK-03** [comment]
Hello @leecalcote! I'd like to take on this issue.

PS: I want to mention that I might require a bit more time as I'm new to Go. However, I am confident that I can successfully complete the task.

**Comment by leecalcote** [comment]
@ASK-03, good deal. @theBeginner86 is accountable for seeing this completed. If he delivers before you do, you can review his PR, which will be an excellent way for you to ramp up.

**Comment by ASK-03** [comment]
[UPDATE]
Hello, I've located the code and successfully completed the first acceptance test. I'm confident that I'll be able to tackle the second one soon as well. Although it's taking some time to navigate through things in GO, I'm gradually gaining a better understanding of it.

**Comment by ASK-03** [comment]
Hello, @leecalcote! In the second acceptance test, is the link in the notification for the design file that is imported or the design file generated for the user?

**Comment by ASK-03** [comment]
Hey @leecalcote @theBeginner86! I made the required changes and would appreciate your reviews. I included the user-provided design file link in the notification. I had to tweak the arguments for the `formatPatternOutput` function to make the feature work. So far, it seems fine, but I'm currently testing it to be sure. Let me know your thoughts!

**Comment by ASK-03** [comment]
Hey @leecalcote @theBeginner86! I made the required changes and would appreciate your reviews. I included the user-provided design file link in the notification. I had to tweak the arguments for the `formatPatternOutput` function to make the feature work. So far, it seems fine, but I'm currently testing it to be sure. Let me know your thoughts!

![Update Notification Format](https://github.com/meshery/meshery/assets/98012930/92c6abff-dc9b-4e7a-be3f-0ff06e5f475c)

**Comment by leecalcote** [comment]
@aabidsofi19 changes proposed to the `formatPatternOutput` function...

@ASK-03, instead of "saved", use "imported". Instead of "URL", use "from". Instead of two sentences, use a single sentence:

```
Design "<design-name>" imported from "<source-URI-either-filesystem-or-URL-path>". 
```

If the source location of the design file is a URL, then they `formatPatternOutput` or some other function should make this URL clickable in the event notification.

**Comment by ASK-03** [comment]
> @aabidsofi19 changes proposed to the `formatPatternOutput` function...
> 
> @ASK-03, instead of "saved", use "imported". Instead of "URL", use "from". Instead of two sentences, use a single sentence:
> 
> ```
> Design "<design-name>" imported from "<source-URI-either-filesystem-or-URL-path>". 
> ```
> 
> If the source location of the design file is a URL, then they `formatPatternOutput` or some other function should make this URL clickable in the event notification.

Thanks! The notification looks much better now 😄. I've implemented the changes and am planning to test all the related functionalities to ensure I don't break anything 😅. Regarding making the URL clickable, is there an existing solution in the backend for this? Also, are there any other notifications that include URLs, so that I can reference how they implemented it?

**Comment by ASK-03** [comment]
Hey @leecalcote! I have completed this task. I have made the link clickable in the notification. I am removing the extra code that I added for development. Will create a PR in sometime for review. Till then, please have a look at the video attached below of the functionality and share you reviews.

[Enhanced Notification Demo Video](https://github.com/meshery/meshery/assets/98012930/1b9f1270-e6dd-4c2f-b3c5-c22ec0f1414e)

**Comment by ASK-03** [comment]
@leecalcote, I've submitted the pull request for this issue. Kindly review it when you get a chance. 

PS: Two workflows are failing (Golangci-lint and Meshkit error codes), I am working on it to remove the issue.
