### ISSUE TITLE
[Extensions] comment mention highlighter getting misplaced on scroll.

### ISSUE THREAD

**Issue by captain-Akshay** [meshery/meshery#10110]
### Current Behavior

![image](https://github.com/meshery/meshery/assets/59491379/88c72390-dd2b-4750-a882-1def1b9ff4ee)

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Darshan174** [comment]
Hey @captain-Akshay, could you specify the location of this error.

**Comment by leecalcote** [comment]
@captain-Akshay fixed?

**Comment by leecalcote** [comment]
@captain-Akshay still an issue?

**Comment by Yashsharma1911** [comment]
This issue is fixed
