### ISSUE TITLE
[Docs] The link is broken in https://docs.meshery.io/concepts/logical/models

### ISSUE THREAD

**Issue by gyohuangxin** [meshery/meshery#10133]
### Current State

The link of [components examples](https://github.com/meshery/meshery/blob/20bbdb696a2587886b72138a3caa31723dd67197/docs/pages/concepts/logical/models.md?plain=1#L50) in https://docs.meshery.io/concepts/logical/models is broken (404).

### Desired State

We should find and link another model which have components definition.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by gyohuangxin** [comment]
cc @MUzairS15

**Comment by ASK-03** [comment]
Thank you, @RipulHandoo, for your contribution. My apologies, @leecalcote, I was unavailable at that time due to classes.
