### ISSUE TITLE
[Docs] Broken links on Meshery documentation home page

### ISSUE THREAD

**Issue by ASK-03** [meshery/meshery#10130]
### Current Behavior
Clicking on the drop-down heading for few options (namely **Installation**, **Extensions**, **Using the CLI**) are leading to Error 404 page.  

I tried to do it on localhost but it looks like it works fine there. I think for **Installation** & **Using the CLI**, on just removing the '/' in the end of the URL will do the job. For **Extensions**, the URL must be changed to the below mentioned link.

### Expected Behavior
It should lead to there respective pages.
- **Installation** should lead to [this link](https://docs.meshery.io/installation)
- **Extension** should lead to [this link](https://docs.meshery.io/extensions)
- **Using the CLI**  should lead to [this link](https://docs.meshery.io/guides/mesheryctl)

### To Replicate
1. Go to [Meshery Docs Home Page](https://docs.meshery.io/)
2. First click on the above mentioned headings on the page will open the drop-down
3. On second click on the heading, It will lead to Error page.

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by maunikms** [comment]
I would like to work on this can you please assign this to me ?

**Comment by vishalvivekm** [comment]
Thank you @maunikms

**Comment by leecalcote** [comment]
If this is affecting the live site, we’re gonna need this fixed quickly.

**Comment by leecalcote** [comment]
It is affecting the live website. This needs to be fixed as soon as possible.

**Comment by leecalcote** [comment]
Marking as Urgent. Assigning to whomever can get it fixed ASAP.
