### ISSUE TITLE
[Docs] Add two suggested reading links to Docs Contributing page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10145]
### Current State
The "Suggested Reading" section on https://docs.meshery.io/project/contributing/contributing-docs#suggested-reading is empty.

### Desired State
Two helpful resources:

1. Liquid Docs - https://shopify.github.io/liquid/
2. Jekyll Docs - https://jekyllrb.com/docs/

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by mgurrie** [comment]
I would like to be assigned this issue and help contribute. @leecalcote

**Comment by ShivamAhir** [comment]
I'm interested in working on this issue. Could you please assign it to me? Looking forward to contributing!

**Comment by leecalcote** [comment]
Hi @mgurrie, let's set a deadline for this issue to be resolved by this coming Sunday. Assuming that timeframe works for you, I'll expect a PR opened, reviewed, and merged before end of day on Sunday. If we aren't able to hit that deadline, let's open up this issue's assignment for another to tackle it... fair deal?

**Comment by mgurrie** [comment]
Sounds good thank you.
