### ISSUE TITLE
[Fix]: The images are not showing 

### ISSUE THREAD

**Issue by kanugurajesh** [meshery/meshery#10170]
### Current Behavior

when I am heading to integrations tab in meshery I am unable to see the images on the box elements
### Expected Behavior

I should be able to see the images on the box elements

### Screenshots/Logs

![Screenshot 2024-02-02 183627](https://github.com/meshery/meshery/assets/77529419/01c8defb-40ea-44d2-8a43-4933d437b65e)

you can see in the above one the white box elements do not have images

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by kanugurajesh** [comment]
can you assign me this issue I would like to work on this

**Comment by aabidsofi19** [comment]
Thanks for reporting the @kanugurajesh  , assigning to you .

**Comment by vishalvivekm** [comment]
fixed by : https://github.com/meshery/meshery.io/pull/1640
