### ISSUE TITLE
[Docs] Broken image on Models contributing page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10193]
### Current State
Broken image on [Models contribution](https://docs.meshery.io/project/contributing/contributing-models) page:

<img width="921" alt="Screenshot 2024-02-02 at 7 06 45 PM" src="https://github.com/meshery/meshery/assets/7570704/b1336f4b-c806-411b-9ece-6b5223d07e76">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by kanugurajesh** [comment]
@leecalcote I would like to work on it can you assign the issue to me
