### ISSUE TITLE
[Policy] Errant warning on design save

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10191]
### Current Behavior
I have two components in a design. I save the design. I receive:

```
WARN[2024-02-02T16:12:14-06:00] evaluation results are empty app=meshery code=11099 probable-cause="The policy query is invalid, see: https://github.com/open-policy-agent/opa/blob/main/rego/resultset.go (Allowed func)" severity=2 short-description="error evaluating policy for the given input" suggested-remediation="please provide a valid non-empty query"
```

### Expected Behavior
No warnings, because no policy evaluations should be invoked unless necessary.

### Environment

- **Host OS:** Mac 
- **Meshery Server Version:** stable-v0.7.15

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MUzairS15** [comment]
This isn’t a bug, for every design save we do policy eval to determine any possible relationships and if the evaluation results are empty we emit this log of severity warning.
It is nothing to worry about and doesn’t indicate any evaluation error.
The log is more for developers to track the evaluation behaviour, you can decrease the server’s log level. https://docs.meshery.io/project/contributing/contributing-server#configuring-log-levels-at-runtime
