### ISSUE TITLE
Support OCI export of Designs, Patterns, Filters

### ISSUE THREAD

**Issue by Althaf66** [meshery/meshery#10195]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

Presently Meshery UI supports exporting as OCI (Open Container Initiative), Using mesheryctl, export in OCI format for enhancing sharing and portability of design.

This is child issue of #6447

### Desired Behavior

Mesheryctl should support exporting Designs, Patterns, Filters in OCI format

### Acceptance Tests

- [ ] mesheryctl should support the export of Designs, Patterns, Filters
- [ ] Update documentation

### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

**Comment by MUzairS15** [comment]
MesheryUI supports exporting as OCI, that is server has the capability mesheryctl needs to utilise it.
