### ISSUE TITLE
[Docs] Adding steps to install setup nodejs and go during intallation in wsl2.

### ISSUE THREAD

**Issue by kanugurajesh** [meshery/meshery#10197]
### Current State

In the current meshery installation documentation there is no proper documentation to install node, go and gcc in wsl2.

### Desired State

I want to add steps to install latest node, go version along with wsl2. so that people do not find it difficult to install these dependencies.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thanks for raising this, @kanugurajesh.

@vishalvivekm, what guidance can you offer here? If @kanugurajesh is to move forward, in what manner should this be done?

**Comment by kanugurajesh** [comment]
@leecalcote do you want me to add the steps

**Comment by leecalcote** [comment]
Since this sky is blue, we’ll go ahead and close this out.
