### ISSUE TITLE
[UI] Global Navigation Menu Tooltip Enhancement

### ISSUE THREAD

**Issue by AjaxAueleke** [meshery/meshery#10203]
### Current Behavior

The tooltip lacks consistency with other tooltips in Meshery. Additionally, the tooltip for the GitHub icon incorrectly displays `github[#142]`, as shown in the screenshot. This should also be removed.
### Desired Behavior

1. Make the font size consistent across tooltips.
2. Aim for a consistent background color for tooltips, ensuring it complements the existing UI and does not create visual conflicts.

### Screenshots/Logs

<img width="397" alt="Screenshot 2024-02-04 at 12 39 33 AM" src="https://github.com/meshery/meshery/assets/62912869/beef9aeb-c261-44ee-a26b-b8194d6f97a6">
<img width="313" alt="Screenshot 2024-02-04 at 12 39 24 AM" src="https://github.com/meshery/meshery/assets/62912869/9246e65b-8215-418b-8770-3f6747dac2bd">
<img width="313" alt="Screenshot 2024-02-04 at 12 39 18 AM" src="https://github.com/meshery/meshery/assets/62912869/2334937e-9d23-463f-964b-b6b0c0452fcb">

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ChetanPatil12** [comment]
I would like to work on this. Please assign this issue to me.
