### ISSUE TITLE
[UI]  Increase Icon Sizes in Meshery Dashboard

### ISSUE THREAD

**Issue by AjaxAueleke** [meshery/meshery#10202]
### Current Behavior

The Meshery dashboard's icons are currently too small for effective interaction on mobile devices. This issue hinders usability and negatively impacts the user experience on mobile platforms.

### Desired Behavior

Increase the size of icons within the tabbed menu to ensure they are easily interactable on mobile devices.
### Screenshots/Logs

<img width="317" alt="Screenshot 2024-02-04 at 12 26 58 AM" src="https://github.com/meshery/meshery/assets/62912869/7de50d81-0054-4077-a54d-ab8ad91e467e">

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ksauravhash** [comment]
I would like to work on this. Can you assign me this issue?

**Comment by AjaxAueleke** [comment]
@ksauravhash go ahead. Best of luck.

**Comment by ksauravhash** [comment]
Thanks

**Comment by leecalcote** [comment]
@ksauravhash you've have built Meshery Server and Meshery UI and have a functional dev environment?

**Comment by leecalcote** [comment]
@AjaxAueleke the goal isn't to strictly make the icons larger. The goal is to make the Dashboard page responsive, specifically focusing on the Tabbed Menus and ensuring that the configuration of these Sistent components is done in such a manner as to be responsive to screen sizes as small as 375px in width. Please rename this issue and update the Desired State.

@LakshyaSatpal, do we have a site that lists all of the current Sistent components? // @nebula-aac @SudhanAruna is there a Tabbed Menu component in Sistent?

**Comment by LakshyaSatpal** [comment]
@leecalcote as of now, we don't have it.

**Comment by leecalcote** [comment]
Noting the screenshot in this issue, are the first two charts, not responsive?

**Comment by leecalcote** [comment]
> @leecalcote as of now, we don't have it.

FYI, @Rexford74

**Comment by ksauravhash** [comment]
> @ksauravhash you've have built Meshery Server and Meshery UI and have a functional dev environment?

Yes, I've built it on my machine and it's working as intended.

**Comment by ksauravhash** [comment]
![Uploading mesherySizeUpdate.png…]()
I've doubled the size on the mobile version.

**Comment by ksauravhash** [comment]
![meshery](https://github.com/meshery/meshery/assets/96964104/00cef244-c14d-4558-baf0-cdf73d2e9e8e)
![mesh2](https://github.com/meshery/meshery/assets/96964104/976e163b-cccd-4233-8884-635c7bf117a9)

How's this?

**Comment by ksauravhash** [comment]
@AjaxAueleke
