### ISSUE TITLE
[Extensions] Text and Text Alignment in Components

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10232]
### Desired Behavior

<img width="747" alt="Screenshot 2024-01-26 at 12 14 56 PM" src="https://github.com/meshery/meshery/assets/7570704/8ddce202-f145-407f-bbed-fe17d0a5f426">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by PATHAKAAKASH19** [comment]
hi @leecalcote  i would like to work on this issue.....

**Comment by leecalcote** [comment]
@PATHAKAAKASH19, great. This one is deceivingly difficult. Have you built Meshery Server and UI? If so, let's find you a more appropriate newcomer issue.

**Comment by PATHAKAAKASH19** [comment]
@leecalcote  it would be great if you assign me any good first issue. 
Also where can i connect will other developer of meshery...

**Comment by leecalcote** [comment]
Here - https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Here - https://slack.meshery.io

**Comment by PATHAKAAKASH19** [comment]
@leecalcote thanks you for helping me
