### ISSUE TITLE
[Extensions] Visualizer missing namespace count

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10233]
### Current Behavior

<img width="344" alt="Screenshot 2024-01-22 at 11 45 01 AM" src="https://github.com/meshery/meshery/assets/7570704/6188562e-0d01-4813-b023-26d87396d22b">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MUzairS15** [comment]
<img width="202" alt="Screenshot 2024-02-19 at 8 15 38 PM" src="https://github.com/meshery/meshery/assets/79860504/a5a0fb76-1a85-4c76-ae73-23324c591704">

This issue has been fixed.
