### ISSUE TITLE
[Docs Integrations & Extensions] - Missing list item description

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#10252]
### Current State
Link: [Meshery Docs](https://docs.meshery.io/)
Currently the majority of the list items under "Integrations & Extensions" --> sub-section "Extensions" have a description. However, there are items without one.
#### Screenshot
![Screenshot 2024-01-23 025514](https://github.com/meshery/meshery.io/assets/19821445/e36db822-8379-490b-982b-90cdf5deb6ef)

### Desired State
Add missing descriptions for items under "Extensions".

CC: @iArchitSharma 

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Raj100679** [comment]
@sandramsc Can you assign this to me
