### ISSUE TITLE
[Models]: Relationships with Argo CD, Argo Events, Argo Workflows

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10264]
### Current Situation
The OpenAPI specifications for Kubernetes provides taxonomy, but augmenting a graph data model with formalized ontologies enables any number of capabilities, one of the more straightforward is the inferencing requisite for natural language processing, and consequently, a human-centric query / response interaction becomes becomes possible. More importantly, more advanced systems can be built when a graph data model of connected systems is upgraded to be a knowledge semantic graph.

### Proposed Change
- Expected Outcome: YAML-formatted definition
- Recommended Skills: DevOps, Kubernetes Administration, Light familiarity with all of the CNCF projects and a desire to study each project and their operators/resources.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- [MeshModel Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)
- 🖥 [MeshModel Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

## Contributing to Meshery Models

!! See https://docs.meshery.io/project/contributing/contributing-models

### Instructions for Models

_Forthcoming_

### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes. 
1. Propose a specific shape, best-suited to visually represent the Component. _Example - Deployment as a pentagon._
1. Proposee a specific icon, best-suited to visually represent the Component. _Example - DaemonSet as a skull icon._

### Instructions for Relationships
1. Identify the relationship and any specific constraints to be enforced between the two specific components, their models or potentially other components, models, or environmental considerations.
1. Propose a specific visual representation for the relationship. See example on [Modeling Relationships.](https://docs.meshery.io/project/contributing/contributing-models)
1. Prospose the appropriate relationship type, using one of the predefined set of relationship types or suggest a new relationship where an existing type does not fit.
1. Create a Relationship Definition (yaml).
1. Create a policy for evaluation of the relationship (rego).

### Instructions for Policies
1. _Forthcoming_

**Comment by hznut** [comment]
@leecalcote I'd like to work on this. Started working on the proposal. I have some questions. Will reach out to folks on Slack channel.

**Comment by leecalcote** [comment]
@hznut excellent. 👍

**Comment by hznut** [comment]
@RipulHandoo  @pandeyshubham03 I've reached out to you over slack. Please let me know if I can sync up with either of you sometime today/tomorrow.

**Comment by hznut** [comment]
@leecalcote  Sincere apologies but due to scheduling conflicts I haven't been able to make much progress on this. Please feel free to reassign this task.

**Comment by leecalcote** [comment]
Understood. Thanks for sending word, @hznut 👍

**Comment by innocentrda** [comment]
Hi @leecalcote,
I am willing to work on this.
