### ISSUE TITLE
[mesheryctl] Support for consolidate mesheryctl app into mesheryctl pattern

### ISSUE THREAD

**Issue by Althaf66** [meshery/meshery#10275]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

There is commands like **mesheryctl app** and **mesheryctl pattern**. We didn't need two seperate command, so we consolidate **mesheryctl app** into **mesheryctl pattern**.

### Desired Behavior

We need to consolidate **mesheryctl app** into **mesheryctl pattern**.

### Acceptance Tests

- [ ] Consolidate app into pattern
- [ ] Update documentation

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Consolidation complete. // @alphaX86
