### ISSUE TITLE
[Meshery UI] Header Detaches When Scrolling Upward

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#10272]
### Current Behavior

At present, when a user scrolls all the way to the top where there is no more room to scroll, the header becomes detached from the top of the page.

### Desired Behavior

The desired behavior is for the header to remain fixed at the top of the page.

### Screenshots/Logs

https://github.com/meshery/meshery/assets/19821445/d1d802b1-e18b-4ff0-8765-ee3986b924fb

CC: @MUzairS15 
### Environment

- Browser: Microsoft Edge, Firefox

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by srujan0404** [comment]
@sandramsc please assign this issue to me, i would like to work on this

**Comment by saurabh100ni** [comment]
@sandramsc, I can't replicate this issue at my end anymore, I think we are good to close it.
Tested in: Edge and Chrome.

**Comment by srujan0404** [comment]
https://github.com/meshery/meshery/assets/140909375/ab326299-f23c-4583-ae92-b6b9d9a658c4

But I see this issue in my system

**Comment by leecalcote** [comment]
@dragon-slayer875 please confirm that this has been fixed and close, if so.

**Comment by dragon-slayer875** [comment]
This issue does not exist/has been fixed in the latest production build of Meshery UI.
