### ISSUE TITLE
[Models] Relationship: Need Edge support for all Annotation Components

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10278]
### Current Situation
The `meshery-flowchart` model is missing relationship definitions for its annotation components.

### Proposed Change
Each component should have the capability to form an annotation edge.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- [MeshModel Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)
- 🖥 [MeshModel Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

## Contributing to Meshery Models

!! See https://docs.meshery.io/project/contributing/contributing-models

### Instructions for Models

_Forthcoming_

### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes. 
1. Propose a specific shape, best-suited to visually represent the Component. _Example - Deployment as a pentagon._
1. Proposee a specific icon, best-suited to visually represent the Component. _Example - DaemonSet as a skull icon._

### Instructions for Relationships
1. Identify the relationship and any specific constraints to be enforced between the two specific components, their models or potentially other components, models, or environmental considerations.
1. Propose a specific visual representation for the relationship. See example on [Modeling Relationships.](https://docs.meshery.io/project/contributing/contributing-models)
1. Prospose the appropriate relationship type, using one of the predefined set of relationship types or suggest a new relationship where an existing type does not fit.
1. Create a Relationship Definition (yaml).
1. Create a policy for evaluation of the relationship (rego).

### Instructions for Policies
1. _Forthcoming_

**Comment by SammyBloom** [comment]
I am interested in this issue

**Comment by MeenuyD** [comment]
Hello @leecalcote I would like to work on this issue can you please assign it to me.
