### ISSUE TITLE
[Models] Relationships: Descriptions of how one component affects the other(s)

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#10287]
Fill in the descriptions please.

_Originally posted by @MUzairS15 in https://github.com/meshery/meshery/pull/10244#pullrequestreview-1878824473_

**Comment by MUzairS15** [comment]
// @RipulHandoo

**Comment by RipulHandoo** [comment]
> // @RipulHandoo

@MUzairS15 [PTAL.](https://github.com/meshery/meshery/pull/10308)

**Comment by leecalcote** [comment]
> > // @RipulHandoo
> 
> @MUzairS15 [PTAL.](https://github.com/meshery/meshery/pull/10308)

Good attempt, but it misses the point, @RipulHandoo

**Comment by RipulHandoo** [comment]
> > > // @RipulHandoo
> > 
> > 
> > @MUzairS15 [PTAL.](https://github.com/meshery/meshery/pull/10308)
> 
> Good attempt, but it misses the point, @RipulHandoo

Gotcha. I'll update the PR soon.
