### ISSUE TITLE
[Models][UX]: Design Icon for ArgoCD Component - Cron Workflow

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#10296]
### Description
Meshery is a powerful platform that contains over [200 integrations](https://layer5.io/cloud-native-management/meshery/integrations) for managing cloud-native applications. MeshMap is an extension of Meshery that visually represents these integrations and components. Currently, most of the icons used in MeshMap have the default shape of a circle. However, to improve visual clarity and consistency, we need to design custom icons for MeshMap components.

### Desired Behavior
A new Icon for  ** Cron Workflow** needs to be created. This issue calls for a volunteer to draft a new Icon.

### Instructions for Designing a Component Icon
1. Create two versions of the icon one is white and another one is colored
2. Provide the icon in SVG format
3. Make a PR after adding the icon inside the [new-icon folder](https://github.com/meshery/meshery/tree/master/ui/assets/new-icons) present in the meshery repository
4. Make sure the icon for the component is different from the Model icon

### How to check whether the icon you designed is the same as the Model icon or any other component icon?
1. Go to the [playground](https://playground.meshery.io/extension/meshmap) -> search for the component you are trying to design an icon for and check whether the icon that you are designing is already present for another component or not if not then you can make a PR.
7. If you don't have access to Playground then you have to fill out a [signup](https://play.meshery.io/) and get verified before you access the Playground by the time you get access, you can go to [integrations](https://layer5.io/cloud-native-management/meshery/integrations) page in layer5.io site and search for the component and see whether an icon is already present or not.

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- [MeshModel Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)
- 🖥 [MeshModel Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by srujan0404** [comment]
@ritiksaxena124 Can you please assign this issue to me ? I would like work on this

**Comment by ritiksaxena124** [comment]
sure  @srujan0404 go ahead, and let's see if you get this done then we can assign you other related issue

**Comment by ritiksaxena124** [comment]
Any update on this @srujan0404 ?

**Comment by srujan0404** [comment]
@ritiksaxena124 I have some doubts. Just getting an idea how should I do this.

**Comment by ritiksaxena124** [comment]
join our [slack channel](meshery.slack.com) to ask your questions or you can ask your doubts here
