### ISSUE TITLE
[UI] Change menu text

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10318]
:help-wanted: will someone change this from “Service Mesh” to “Adapters”?

[Slack Message](https://layer5io.slack.com/archives/C023QGMSH8D/p1708017774833449)

**Comment by sandramsc** [comment]
Can I have this issue assigned to me please?

**Comment by saurabh100ni** [comment]
Sure @sandramsc 🚀

**Comment by giteshsarvaiya** [comment]
just curious, what is the name of that sideBar component?

**Comment by leecalcote** [comment]
@giteshsarvaiya let's set a time limit of end of tomorrow for completion of this.

**Comment by giteshsarvaiya** [comment]
Navigator .js okk 🫡
