### ISSUE TITLE
Support KubeArmor's Operator and CRDs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10310]
### Current Behavior
Meshery doesn't have an integration defined with KubeArmor and doesn't currently model its resources out of the box.

### Desired Behavior
Definition of the Model, Components, and all feasible Relationships.

### Implementation
New additions in Meshery Integrations spreadsheet.
- [x] Color and white logos (SVGs), primary secondary color. @ritiksaxena124 
- [x] Default shape for the model: `shield`. @leecalcote 
- [x]  Model and Components imported. @MUzairS15 
- [x]  Relationships defined. @pandeyshubham03
- [x]  Relationships reviewed. @RipulHandoo 

Resource references:
1. https://github.com/kubearmor/KubeArmor
3. https://catalog.redhat.com/software/containers/kubearmor/kubearmor-operator/6458b1ee3f880286315e7cfb

### Acceptance Tests
- [x] KubeArmor components available as static components.
- [x] KubeArmor components deployable (configurable) by Meshery.
- [x] Both KubeArmor and Kubernetes model relationships considered.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by narasimha-1511** [comment]
i want to work on this issue.

**Comment by leecalcote** [comment]
Definition of relationships for KubeArmor’s resources is needed as well. // @pandeyshubham03

**Comment by leecalcote** [comment]
@narasimha-1511 here's one - https://github.com/meshery/meshery/issues/10304#issuecomment-1955267993

**Comment by pandeyshubham03** [comment]
@leecalcote Can you please assign me this issue?

**Comment by leecalcote** [comment]
“_Will_ you assign the issue _to_ me?”

**Comment by ritiksaxena124** [comment]
Color and white SVGs with primary and secondary color updated for KubeArmor in sheet

**Comment by leecalcote** [comment]
2 of 5 tasks completed: @leecalcote @ritiksaxena124

**Comment by MUzairS15** [comment]
This has been completed.
