### ISSUE TITLE
[mesheryctl] Encountering Response Status Code 404

### ISSUE THREAD

**Issue by yash37158** [meshery/meshery#10320]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
I am encountering a server error when attempting to view all patterns using the mesheryctl pattern view -a command. The command returns a response status code of 500, indicating a server-side issue.

### Desired Behavior
The command should successfully retrieve and display information about all available patterns.

### Screenshots/Logs

<img width="639" alt="Screenshot 2024-02-16 at 1 15 57 AM" src="https://github.com/meshery/meshery/assets/68152307/c84866ed-782c-4721-bd96-25463afb2037">

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Shiva953** [comment]
The status code is `404`(client-side) not 500, which means that the pattern provided by you probably does not exist in the server.

**Comment by yash37158** [comment]
@Shiva953, I have tried with multiple uuids and the issue remains the same.

**Comment by Jougan-0** [comment]
@yash37158 @leecalcote this particular issue too does not exist here is the video clip
[Screencast from 2024-04-12 16-11-30.webm](https://github.com/meshery/meshery/assets/99207534/38ace965-e806-494d-9d91-dc5002c50928)
hope this makes it clear if @yash37158 you need any help running in local ping me in slack 

Basic steps: 1. run make in mesheryctl directory
2.make sure you have auth.json in .meshery directory
3.run the command ./mesheryctl pattern view [ -a | {id} ]

**Comment by yash37158** [comment]
Great! The issue is resolved and we can close this now. Thanks for the update, @Jougan-0.
