### ISSUE TITLE
[Docs] Tutorial: Accessing Meshery with Gateway API add-on

### ISSUE THREAD

**Issue by pandeyshubham03** [meshery/meshery#10333]
### Current State
Meshery Docs are in need of new tutorials with hands-on labs. In this tutorial, we will explore how to access Meshery using Gateway API add-on in your local Kubernetes cluster and verify whether the traffic is routed correctly to Meshery.

#### 1. Verify your local Kubernetes Cluster Status
You can verify that Kubernetes is running by opening a terminal (or command prompt) and running the following command:
```sh
$ kubectl cluster-info
```
#### 2. Install and Run Meshery on your local machine using the Meshery CLI
You can use the following docs to install and run Meshery on your local machine using Meshery CLI: [Install](https://docs.meshery.io/installation/linux-mac)
To verify your installation, Run the below command. A service named ```Meshery``` must be present.
```sh
$ kubectl get services --namespace meshery
```

#### 3. Install an Ingress Controller
Choose an Ingress controller that supports the Gateway API. For this example, let's use Contour.Install Contour using the following kubectl command:
```sh
$ kubectl apply -f https://projectcontour.io/quickstart/contour-gateway-provisioner.yaml
```
This command creates:
- Namespace `projectcontour` to run the Gateway provisioner
- Contour CRDs
- Gateway API CRDs
- Gateway provisioner RBAC resources
- Gateway provisioner Deployment

#### 4. Create a GatewayClass and Gateway
GatewayClass:
```sh
kubectl apply -f - <<EOF
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: contour
spec:
  controllerName: projectcontour.io/gateway-controller
EOF
```
Gateway:
```sh
kubectl apply -f - <<EOF
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: contour
  namespace: projectcontour
spec:
  gatewayClassName: contour
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
EOF
```
The above creates:
- A ```GatewayClass``` named ```contour``` controlled by the Gateway provisioner (via the ```projectcontour.io/gateway-controller``` string)
- A ```Gateway``` resource named ```contour``` in the ```projectcontour``` namespace, using the contour ```GatewayClass```
- Contour and Envoy resources in the ```projectcontour``` namespace to implement the ```Gateway```, i.e. a Contour deployment, an Envoy daemonset, an Envoy service, etc

#### 5. Testing the Gateway API
_Note, for simplicity and compatibility across all platforms we’ll use kubectl port-forward to get traffic to Envoy, but in a production environment you would typically use the Envoy service’s address._

Port-forward from your local machine to the Envoy service:
```sh
$ kubectl -n projectcontour port-forward service/envoy-contour 9081:80
```
Now, make a request to the application via the forwarded port (Note, ```local.projectcontour.io``` is a public DNS record resolving to ```127.0.0.1``` to make use of the forwarded port):
```sh
$ curl -i http://local.projectcontour.io:9081
```
You should receive a 200 response code along with the HTML body of the Meshery Dashboard page.

You can also open [http://local.projectcontour.io:9081/](http://local.projectcontour.io:9081/) in a browser.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by SammyBloom** [comment]
I am interested in this issue.

**Comment by Syed-Shahidh-Ilhan** [comment]
Hey @leecalcote is this issue still open to work on? I would love to get assigned to this.

**Comment by leecalcote** [comment]
Sounds great, yes.

**Comment by Syed-Shahidh-Ilhan** [comment]
Is there something broken in the given instructions @leecalcote ? 
After port forwarding the service and curling the endpoint i kept getting a connection refused after doing some investigation it was because the targetport in service definition was set to 8080 but the pod's envoy container was listening on 8002 so i changed the targetport to 8002 by running kubectl edit command and now i dont get a connection refused instead i'm facing a 404.....could you please help me out, I'm super new to this project and an amateur at k8s?

**Comment by leecalcote** [comment]
@Syed-Shahidh-Ilhan, I don't know. I haven't read the instructions. Ask the person that wrote them. @pandeyshubham03?

**Comment by pandeyshubham03** [comment]
> Is there something broken in the given instructions @leecalcote ? After port forwarding the service and curling the endpoint i kept getting a connection refused after doing some investigation it was because the targetport in service definition was set to 8080 but the pod's envoy container was listening on 8002 so i changed the targetport to 8002 by running kubectl edit command and now i dont get a connection refused instead i'm facing a 404.....could you please tell me if i missed anything? I'm new to this project

Hello @Syed-Shahidh-Ilhan, I checked this now and its working as expected.
First of all, make sure you installed Meshery in your local cluster. You can make use of [https://docs.meshery.io/installation/linux-mac](https://docs.meshery.io/installation/linux-mac). 
Also, the services for contour and envoy are dynamically provisioned so they need not be altered. You may refer https://projectcontour.io/guides/gateway-api/ for more information

**Comment by Syed-Shahidh-Ilhan** [comment]
Heyy thanks for reaching out @pandeyshubham03 I followed the docs here but I'm still facing issues when I install meshery onto my mac 
I opened a topic here https://discuss.meshery.io/t/unable-to-deploy-meshery-to-minikube/4939

**Comment by leecalcote** [comment]
You might try using the Docker extension for Meshery on your Mac running Docker desktop

**Comment by aayushdhiman01** [comment]
can i work on this issue?

**Comment by aayushdhiman01** [comment]
hey @pandeyshubham03 i am getting error on making request.
E0618 14:12:28.741351   19459 portforward.go:413] an error occurred forwarding 9081 -> 8080: error forwarding port 8080 to pod 7f0d617cc3a00669f6bf40a0e157a054624f083b16df2fa285b7e0d440cd5e6f, uid : exit status 1: 2024/06/18 08:42:28 socat[20246] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
error: lost connection to pod

curl -i http://local.projectcontour.io:9081
curl: (52) Empty reply from server

**Comment by leecalcote** [comment]
@pandeyshubham03 is no longer participating in this project.
