### ISSUE TITLE
[meshercyctl] helpers.go: needs MeshKit style error

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10343]
@gyohuangxin @MUzairS15 I wonder if we should be using a MeshKit Error here. https://docs.meshery.io/project/contributing/contributing-error

_Originally posted by @leecalcote in https://github.com/meshery/meshery/pull/10280#discussion_r1488901680_

**Comment by hamza-mohd** [comment]
@gyohuangxin, I'm not sure, but this item might be aimed your direction.

Here is the MeshKit-style error code contributing guide - https://docs.meshery.io/project/contributing/contributing-error

**Comment by leecalcote** [comment]
Thank you, @hamza-mohd!

**Comment by Aijeyomah** [comment]
@leecalcote I'm Interested on working on this issue. Can you assign it to me.

**Comment by gyohuangxin** [comment]
@Aijeyomah Thanks for taking this issue.
