### ISSUE TITLE
[UI] Registry has broken images in the display of component details.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10340]
### Current Behavior

<img width="929" alt="Screenshot 2024-02-17 at 5 00 41 PM" src="https://github.com/meshery/meshery/assets/7570704/06a9c28f-29ad-4310-823e-ec953fd07a4c">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by narasimha-1511** [comment]
i want to work on this issue?

**Comment by kanugurajesh** [comment]
@leecalcote can you tell me how can i reproduce the issue

**Comment by leecalcote** [comment]
Yes: visit Settings-->Registry. Click on the Models tab. Click on a component.

**Comment by Yashsharma1911** [comment]
Thankyou @narasimha-1511 and @kanugurajesh for raising your hand to fix this isssue, this issue is already fixed in this PR https://github.com/meshery/meshery/pull/10171 how there are more issues to work on you can read more about those here https://github.com/meshery/meshery/issues/9775

**Comment by Yashsharma1911** [comment]
This issue is fixed
