### ISSUE TITLE
[Docs] Dark mode bug

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery#10351]
### Current State
Dark mode bug:
<img width="678" alt="image" src="https://github.com/meshery/meshery/assets/110674407/9731c464-9afa-4255-81ed-f316d3cf6323">

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ayush844** [comment]
i would like to work on this issue

**Comment by vishalvivekm** [comment]
There you go @ayush844 
Thanks for taking it up.

**Comment by ayush844** [comment]
hey @vishalvivekm, 

I've fixed the hover effect issues. i am not sure about color in dark mode.  Could you please advise the appropriate color that should be used here?

here is how it is looking:

![Screenshot from 2024-02-23 15-20-06](https://github.com/meshery/meshery/assets/113158635/ca0262a0-633e-4d1e-9e83-f4cf285be35a)

![Screenshot from 2024-02-23 15-20-35](https://github.com/meshery/meshery/assets/113158635/c5623c38-eb06-4702-b97a-3cec879ef463)

![Screenshot from 2024-02-23 15-20-48](https://github.com/meshery/meshery/assets/113158635/f09f41d2-fe07-4474-9c1d-99dc86665806)

![Screenshot from 2024-02-23 15-20-56](https://github.com/meshery/meshery/assets/113158635/383243be-4d46-45c1-b940-5912b91c2b61)
