### ISSUE TITLE
[UI] Enhance title and description of Environments

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10364]
### Desired Behavior
Affect the desired behavior as described in the mockup.

### Mockups
<img width="623" alt="Screenshot 2024-02-21 at 11 09 45 AM" src="https://github.com/meshery/meshery/assets/7570704/c18cb417-abbc-4cdf-8665-4405c775f228">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by izuca** [comment]
Hey there! @leecalcote can you assign me on this issue? I'd like to work on this

**Comment by leecalcote** [comment]
Thanks!

**Comment by sudhanshutech** [comment]
Have you built meshery @izuca successfully?

**Comment by izuca** [comment]
Not yet, @sudhanshutech . I am still reading all the materials so I don't make anything wrong hehe.

But as soon as I finish it, I will build it and start working on this problem

**Comment by izuca** [comment]
I'm still figuring out the build process, but I've been reading docs and reaching out for help on Slack. I'm committed to solving this and would love to keep the assignment. I'll keep you updated on my progress!
