### ISSUE TITLE
[mesheryctl]: Interactive Pagination for `mesheryctl filter list` command

### ISSUE THREAD

**Issue by RipulHandoo** [meshery/meshery#10366]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
![image](https://github.com/meshery/meshery/assets/107461226/9e0a0abd-64b5-45fc-915d-03ca97c7fb6c)

### Desired Behavior
Show pagination effect similar to `mesheryctl exp model list` command.

### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

**Comment by vpavankalyan** [comment]
Hi @RipulHandoo,
I would like to work on this issue. If it has not been assigned to anyone yet. 
Can you please assign this issue to me?

**Comment by RipulHandoo** [comment]
Here you go @vpavankalyan.

**Comment by Aijeyomah** [comment]
@RipulHandoo I'd like to work on this. Can you assign this issue to me? Thanks

**Comment by RipulHandoo** [comment]
@Aijeyomah Could you provide an update on the progress of the issue?

**Comment by Aijeyomah** [comment]
> @Aijeyomah Could you provide an update on the progress of the issue?

I started working on this till Vpavankylan referenced his PR. I didn't want to create a duplicate fix for it. I can raise a pull request for this over the weekend

**Comment by RipulHandoo** [comment]
Thanks for the update @Aijeyomah . Looking forward to the pull request over the weekend.
