### ISSUE TITLE
[Install] Bash: support for new Meshery Adapter for Nighthawk

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10372]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
A new Meshery Adapter is being created in the v0.8 release: https://github.com/meshery/meshery-nighthawk

### Desired Behavior
The bash installer should support this new adapter.

### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@hexxdump I wonder if this is an item that you're up for. It not, that's ok. We'll just want to slap a "help wanted" on it.

**Comment by hexxdump** [comment]
Hi @leecalcote,
Committed the changes via - https://github.com/meshery/meshery.io/commit/08026d72e9b096ce36d7254b73a022e5b19768e6

**Comment by leecalcote** [comment]
Oh, wonderful. Thanks for this, @hexxdump. It seem that I would have done better to open the issue against the repo that actually contains that script. 😉 Thank you!

FYI, @gyohuangxin
