### ISSUE TITLE
[DevOps] Create new Helm sub-chart for Meshery Adapter for Nighthawk

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10370]
### Current Behavior
A new Meshery Adapter is being created in the v0.8 release: https://github.com/meshery/meshery-nighthawk

### Desired Behavior
A new Helm chart similar to the other adapter home charts will need to be created for this new adapter: https://github.com/meshery/meshery/tree/master/install/kubernetes/helm/meshery/charts

### Implementation
1. Duplicate one of the existing adapter charts.
2. Replace all adapter specific references with references to `meshery-nighthawk` adapter.

Note: this adapter runs on port 10013/tcp by default.

### Acceptance Tests
1. `helm install meshery meshery/meshery -n meshery` deploys an instance of this adapter.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by leecalcote** [comment]
Thanks!

**Comment by hamza-mohd** [comment]
@MeenuyD this PR is being discussed in today's Meshery Build and Release meeting - https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit

**Comment by leecalcote** [comment]
@MeenuyD how's this coming along?

**Comment by AllenOps08** [comment]
I want to work on this issue..Can you assign me this..?

**Comment by MeenuyD** [comment]
Sorry @leecalcote due to some issue I was not able to do that
