### ISSUE TITLE
[mesheryctl] `system check` command mandates the requirement of an adapter to perform the check.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#10382]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

The `system check` command mandates the requirement of an adapter to perform the system health check. The presence of an adapter should not be a requirement for this command.

### Desired Behavior

1. Perform the health check without mandating the requirement of an adapter.
1. If adapters are present perform a check for those.
1. The command should return the status of each system (meshery server and all available adapters).
### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MUzairS15** [comment]
@anujamerwade Would you like to tackle this one?
Heads up, it is quite involved and may not be easy for newcomers.

**Comment by anujamerwade** [comment]
@MUzairS15 I am new to backend development in GO and mesheryctl altogether. So I was wondering if I could work on a goodfirstissue and get my hands dirty before jumping all in if that makes sense. What do you suggest?

**Comment by MUzairS15** [comment]
That's most appropriate to start with. Let's carry further on slack.

**Comment by anujamerwade** [comment]
Sounds good!

**Comment by leecalcote** [comment]
@RipulHandoo @vishalvivekm please note that the scope of this issue includes `mesheryctl system login`. See the recent Slack discussion on this.

**Comment by KunyueXing** [comment]
Hi @leecalcote and @MUzairS15,

I found the desired behaviors in this issue are already fulfilled. 

1. Perform the health check without mandating the requirement of an adapter.
   In `mesheryctl/internal/cli/root/system/check.go`, there's a command -- [`mesheryctl system check`](https://github.com/meshery/meshery/blob/c724034e28dbb51b500b626b0981bb0fa4431449/mesheryctl/internal/cli/root/system/check.go#L126) that checks for both pre and post mesh deployment scenarios on Meshery that doesn't need to mention about adapters.

3. If adapters are present perform a check for those.
   In `mesheryctl/internal/cli/root/system/check.go`, there're commands [`mesheryctl system check --adapters`](https://github.com/meshery/meshery/blob/c724034e28dbb51b500b626b0981bb0fa4431449/mesheryctl/internal/cli/root/system/check.go#L137) and [`mesheryctl system check --adapter [adapter-name]`](https://github.com/meshery/meshery/blob/c724034e28dbb51b500b626b0981bb0fa4431449/mesheryctl/internal/cli/root/system/check.go#L134), which check on all adapters, or a specific adapter, respectively. And there's func -- `runAdapterHealthChecks()` implemented accordingly.

5. The command should return the status of each system (meshery server and all available adapters).
   It seems that the log info is provided when running the components, adapters, and operators' health checks.


So could we close this issue? Please let me know if I missed anything. 

@leecalcote, 

from your comment above, the scope of this issue includes `mesheryctl system login`. I don't find any health checks in `mesheryctl system login`, does this need to be implemented?
