### ISSUE TITLE
[Server] Enhancements for Pattern API

### ISSUE THREAD

**Issue by Althaf66** [meshery/meshery#10392]
### Current Behavior

There are basically two issue in pattern api.
1. In /api/pattern, there is no params like pagesize=all for showing all the list of the patterns.
2. When we search for /api/pattern/<patternid> show 404 error, where the design created by other user, But This api show the response for the design created by same user with full pattern id (like f951faa2-5c7f-4836-8095-761df8f1bf76). Trimmed pattern id won't work (like f951faa2).

### Desired Behavior

1. Need to create api query params for showing all the patterns.
2. Shows the api response when user enters pattern id. 

It may fix this issue #10320 

### Screenshots/Logs

**Example**
![Screenshot 2024-02-23 235322](https://github.com/meshery/meshery/assets/114910365/4f6c5867-b1e0-4fbf-84cf-54a1ea0f4f61)

I created a design named as 'new-3' and giving it's pattern id, It shows the response.(only full pattern id is showing the response)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Jougan-0** [comment]
[Screencast from 2024-04-05 01-48-50.webm](https://github.com/meshery/meshery/assets/99207534/575283ae-6752-4def-9ca7-991cdac8f07f)
``` /api/pattern/``` their is no route named this the route is ```/api/pattern``` and the id with the user is working fine here is a attached video hope this explains it regarding the issue #10320 the token is inavlid when running the same command I am looking into that 
@leecalcote I guess we can close this issue and I am looking into #10320

**Comment by leecalcote** [comment]
Oh, ok. 

@Althaf66, do you agree?
