### ISSUE TITLE
[Models] Create a Template Model

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10396]
@pandeyshubham03 do we have a relationship_template.yaml? If not, will you create one and include the two sentence (or more) description under `description`? 

This and templates for components, credentials, connections and so on can be placed in a folder under `server/meshmodels/_model-template`.

_Originally posted by @leecalcote in https://github.com/meshery/meshery/pull/10380#discussion_r1501297928_

**Comment by pandeyshubham03** [comment]
Looking into it!
