### ISSUE TITLE
[Partners] Remove Service Mesh Interface entry from Partners page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10391]
:help-wanted: HELP WANTED: The entry for Service Mesh Interface needs to be removed from <https://layer5.io/partners> page.

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1708712373702989)

**Comment by paudelpr1** [comment]
Hi, I'd like to work on this.

**Comment by Satakshijain** [comment]
I would like to work on this issue

**Comment by leecalcote** [comment]
Apologies, I missed these messages. Assigning in chronological order...
