### ISSUE TITLE
[Docs] Response code UI not consistent in rest api doc

### ISSUE THREAD

**Issue by ShivamCoder23** [meshery/meshery#10422]
### Current State
Some places the response code ui looks like
![image](https://github.com/meshery/meshery/assets/160073697/b8be3f52-8180-426d-9ec2-a5a1751ba9c6)

and some places:
![image](https://github.com/meshery/meshery/assets/160073697/6dcd0880-9d9a-4afa-bb25-45ce7f02b444)

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vishalvivekm** [comment]
> Can I be assigned to this task? @ShivamCoder23

Hey @mgurrie, Thank you for showing your interest.
We'd be more than happy to assign this issue to you :)
Can you please confirm if you have set up Meshery Docs locally?

**Comment by mgurrie** [comment]
yes I do @vishalvivekm

**Comment by mgurrie** [comment]
Can I have more direction of these changes?
