### ISSUE TITLE
[UI] Registry: Registrants tab has improper count of registered Models

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10438]
### Current Behavior
See http://localhost:9081/settings?settingsCategory=Registry&tab=Registrants

### Screenshots/Logs

<img width="545" alt="Screenshot 2024-02-27 at 11 16 14 PM" src="https://github.com/meshery/meshery/assets/7570704/24e6193f-abe1-4efd-88f1-4606c60a3506">

### Environment

- Browser: Safari
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.24

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
Fixed
