### ISSUE TITLE
[UI] Registry: Cancel search button in wrong location

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10430]
### Current Behavior
On the Settings-->Registry page, the "x" button is in the wrong place during searches.

http://localhost:9081/settings?settingsCategory=Registry&tab=Models

### Screenshots/Logs
<img width="563" alt="Screenshot 2024-02-27 at 10 35 20 PM" src="https://github.com/meshery/meshery/assets/7570704/850ae232-0673-475a-922a-0f6efd32ceef">

### Environment

- Browser: Safari 
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.24

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Satakshijain** [comment]
I would like to work on this issue

**Comment by sudhanshutech** [comment]
go ahead @Satakshijain

**Comment by JenilLaheri** [comment]
i am fresher but i can try fixing this issue..

**Comment by Yashsharma1911** [comment]
@Satakshijain are you still working on this?

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911 can I work on this?

Thanks yes go ahead, also please update EOT here

**Comment by Aseem22** [comment]
> > @Yashsharma1911 can I work on this?
> 
> Thanks yes go ahead, also please update EOD here

Did you assign me this? @Yashsharma1911

**Comment by Yashsharma1911** [comment]
> 
> 
> > > @Yashsharma1911 can I work on this?
> > 
> > Thanks yes go ahead, also please update EOD here
> 
> Did you assign me this? @Yashsharma1911 
> 

Opps I missed

**Comment by Aseem22** [comment]
@Yashsharma1911 I have opened the PR. Please, have a look.
