### ISSUE TITLE
[UI] Registry: Relationship descriptions not displayed.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10436]
### Current Behavior
See http://localhost:9081/settings?settingsCategory=Registry&tab=Models

1. Relationship descriptions not displayed.
1. Why does the details pane show "Edge" as if that is the name of the relationship?

### Screenshots/Logs
<img width="1082" alt="Screenshot 2024-02-27 at 10 59 38 PM" src="https://github.com/meshery/meshery/assets/7570704/0de0acbe-df5f-4f84-9a47-55c85e2bc9cc">

### Environment

- Browser: Safari
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.24

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@RipulHandoo @MUzairS15 @pandeyshubham03 what should the name be?

When will we have a `kind`, `subtype` AND `type`?

**Comment by Yashsharma1911** [comment]
> @RipulHandoo @MUzairS15 @pandeyshubham03 what should the name be?
> 
> When will we have a `kind`, `subtype` AND `type`?

This issue is fixed in latest release for description, however please suggest what should be a name for relationship, I'll update client accordingly.

**Comment by leecalcote** [comment]
@dottharun, enhancement needed.

**Comment by Jougan-0** [comment]
> @dottharun, @Jougan-0 enhancement needed.

We could show the selector data. In my opinion that is what is unique in relationships.
