### ISSUE TITLE
[UI] Registry: Models not listed in alphabetical order (multiple times)

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10433]
### Current Behavior
See http://localhost:9081/settings?settingsCategory=Registry&tab=Models&selectedItemUUID=4761ed15-3ef5-5093-ab3e-9dbb80c80573&pagesize=93

### Screenshots/Logs
<img width="1089" alt="Screenshot 2024-02-27 at 10 49 10 PM" src="https://github.com/meshery/meshery/assets/7570704/ef16d633-8549-498a-94d9-a87a812b083a">
<img width="1085" alt="Screenshot 2024-02-27 at 10 49 44 PM" src="https://github.com/meshery/meshery/assets/7570704/f1d549d6-de32-41de-a8d7-3fca6e97dbeb">

### Environment

- Browser: Safari
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.24

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aijeyomah** [comment]
@leecalcote I'm Interested in working on this. I have completed the setup the development server and I dentified where this fix it to be made. Can you assign issue to me?

**Comment by Yashsharma1911** [comment]
Thanks @Aijeyomah for raising your hand this issue is fixed on client side, you can refer to other similar issues, please let us know if you need help in finding them
