### ISSUE TITLE
[UI] Registry: Broken component image

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10432]
### Current Behavior
Broken component image

See http://localhost:9081/settings?settingsCategory=Registry&tab=Models&selectedItemUUID=32cf554c-d964-5b19-b605-0d5af569b2b0.32cf554c-d964-5b19-b605-0d5af569b2b0.1.83c4cac2-e8ea-4be5-8e01-9dbac7fccd56&searchText=nighthawk&pagesize=65

### Screenshots/Logs
<img width="1079" alt="Screenshot 2024-02-27 at 10 43 24 PM" src="https://github.com/meshery/meshery/assets/7570704/b4c197ec-7c16-446c-8175-3e8ca047a3e1">

### Environment

- Browser: Safari
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.24

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
Fixed
