### ISSUE TITLE
[UI] Registrant: "Artifact Hub" is inappropriately hardcoded

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10437]
### Current Behavior

See http://localhost:9081/settings?settingsCategory=Registry&tab=Registrants

### Screenshots/Logs
<img width="267" alt="Screenshot 2024-02-27 at 11 13 18 PM" src="https://github.com/meshery/schemas/assets/7570704/b10c8188-920a-4026-9a3d-50d85520bf87">

### Environment

- Browser: Safari
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.24

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@MUzairS15 @Yashsharma1911

**Comment by Aseem22** [comment]
can you assign me this task? @leecalcote
