### ISSUE TITLE
[UI] Registry: Model search not working

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10431]
### Current Behavior
When entering a search term, the model list is not filtering on entries matching the search term

See http://localhost:9081/settings?settingsCategory=Registry&tab=Models

### Screenshots/Logs

<img width="563" alt="Screenshot 2024-02-27 at 10 38 18 PM" src="https://github.com/meshery/meshery/assets/7570704/fc41666c-94f3-4f88-927e-82d1f733e049">

### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.7.24

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@Yashsharma1911 fyi

**Comment by Yashsharma1911** [comment]
Search was working fine however we were missing an empty state in case search is not found, in above case "nighthawk" was not found on search which causes issue for RTK to use cached data, and causes confusion that search is not working

This issue is fixed in latest release
