### ISSUE TITLE
[Catalog] Publish Kubernetes apps to Meshery Catalog using `mesheryctl`

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery#10444]
## Current Situation
[Meshery Catalog](https://meshery.io/catalog) has a relatively small number of published designs.

## Desired Situation

Meshery Catalog is populated with a variety of published designs, representing any number of technologies in the designs and representing different categories of designs. 

## Difficultly Level: Beginner

This is a beginner-level issue designed to both help introduce you, the contributor, to additional Kubernetes concepts and DevOps practices, and to aid in creating a robust catalog full of cloud native design patterns and sample apps in the Meshery Catalog.

## Skills Needed

1. No coding skills needed.
2. Awareness of Kubernetes.

## Implementation

1. **Identify a Kubernetes sample app**
    1. Bring your own Kubernetes manifest or Helm Chart or Docker Compose file or...
    3. ...or identify a sample app from any available in public repos ([example 1](https://github.com/AdminTurnedDevOps/kubernetes-examples), [example 2](https://github.com/kubernetes/examples), [example 3](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples)).
    1. Attempt to identify resources that can benefit both newcomers and seasoned professionals.
1. **Import Kubernetes App**
    1. Import the sample application using `mesheryctl app import` command, [following this guide](https://docs.meshery.io/guides/configuration-management/importing-apps#import-apps-using-meshery-cli). 
1. **Publish Kubernetes App**
    1. Publish your sample app into the Meshery Catalog. Guides: Using Meshery UI or [Using MeshMap](https://docs.meshery.io/extensions/publishing-a-design).
1. **[Optional] Open App in Playground**
    1. Access [Meshery Playground](https://play.meshery.io) and open your app in [MeshMap](https://docs.meshery.io/extensions/meshmap).
1. **[Optional] Share your Kubernetes App**
    1. Be social and share your imported apps on twitter or linkedin and the Meshery project accounts will repost.
1. **Repeat**
    1. Import and publish five or more sample apps.

## Acceptance Criteria
1. Five or more new sample apps have been imported into Meshery and published into the Meshery Catalog.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vishalvivekm** [comment]
cc @Althaf66

**Comment by deepak4566** [comment]
Hey , @vishalvivekm i would like to work on this issue , could u assign it to me

**Comment by literalEval** [comment]
Hey @leecalcote please assign this issue to me if it is not being actively worked upon.

**Comment by leecalcote** [comment]
@literalEval, great. Let's get a new one created for you. Please duplicate this issue, making a slight change by identifying the specific app you'll be working with, and then, we'll get you assigned.

**Comment by literalEval** [comment]
Will do. Thanks.

**Comment by leecalcote** [comment]
@literalEval did you create an issue?

**Comment by literalEval** [comment]
@leecalcote I was searching for an that suits my interest for the issue. Will open the issue by latest. Thanks.

**Comment by literalEval** [comment]
This link [https://docs.meshery.io/guides/configuration-management/importing-apps#import-apps-using-meshery-cli](https://docs.meshery.io/guides/configuration-management/importing-apps#import-apps-using-meshery-cli) returns 404.

**Comment by leecalcote** [comment]
@literalEval thanks for pointing this out. Here's one that can be used - https://docs.meshery.io/guides/configuration-management/importing-designs // @deepak4566

**Comment by leecalcote** [comment]
There are a few that cover this topic - https://docs.meshery.io/search/?q=import%20design

**Comment by literalEval** [comment]
@leecalcote thanks.

**Comment by jayg2309** [comment]
@literalEval are you still working on this?
