### ISSUE TITLE
[Meshery UI] : Meshery UI encountering errors related to permissions while importing a file.

### ISSUE THREAD

**Issue by Adarsh-jaiss** [meshery/meshery#10449]
### Current Behavior
Users encounter permission errors when attempting to import files via Meshery UI. This issue disrupts the import process and prevents users from successfully uploading their files. Checkout the ongoing [discussion](https://discuss.layer5.io/t/unable-to-import-designs-docker-compose/4537) on the forum about the issue

### Desired Behavior
Users should be able to import files smoothly without encountering permission errors. Meshery UI should handle file imports seamlessly, ensuring a hassle-free experience for users.

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by betelgeuse-code** [comment]
Which command did you run @Adarsh-jaiss `make server` or `make server-local`? if `make server-local` uses local instance of Meshery cloud which is not present in you system and you are facing these issues, use instead `make server` which uses remote instance of Meshery cloud after that you will not get this issue

**Comment by leecalcote** [comment]
Thanks for posting this issue, @Adarsh-jaiss. 👍

**Comment by Adarsh-jaiss** [comment]
> Thanks for posting this issue, @Adarsh-jaiss. 👍

Hey @leecalcote , I have already fixed the issue, i just need to test it locally and then i'll create a PR by EOD :)

**Comment by leecalcote** [comment]
🏃 🏃

**Comment by Adarsh-jaiss** [comment]
@leecalcote I have raised the PR, kindly review it once :)

**Comment by Adarsh-jaiss** [comment]
Hey @leecalcote @yash37158 , I tested the issue and i think its resolved, since i tested it on my local machine, (using meshery cloud as a provider) and i was able to import the designs.yaml file and after refreshing the Ui, i was able to see it 

Here's the image : 
![Screenshot from 2024-04-07 19-13-46](https://github.com/meshery/meshery/assets/96974600/ca280520-c74c-453d-9833-bf7d268d1db2)

![image](https://github.com/meshery/meshery/assets/96974600/dcac8ea4-9444-4795-9bcf-42420ebc25f0)

and here's the server logs :  
![image](https://github.com/meshery/meshery/assets/96974600/2d738872-5373-4344-a0fc-c1d77dfeabce)
