### ISSUE TITLE
[DevOps] - Unable to Populate Meshery Catalog with Sample Apps using Meshery UI

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#10446]
### Current Behavior

[Meshery Catalog](https://meshery.io/catalog) has a relatively small number of published designs. 

**To address this I tried:**

1. Importing my own Docker Compose file
2. Identified sample apps from available public repos i.e [awesome-compose](https://github.com/docker/awesome-compose) and followed the steps to import the compose file using [Meshery UI](https://docs.meshery.io/guides/configuration-management/importing-apps#import-apps-using-meshery-cli), but this process was unsuccessful. 

Here is a link to an ongoing [discussion](https://discuss.layer5.io/t/unable-to-import-designs-docker-compose/4537) on the forum about this issue.

### Desired Behavior

Users should be able to import their apps into MeshMap via Meshery UI using Docker Compose. 

### Environment

- Host OS: Windows 11
- Meshery Client Version: stable-v0.7.25
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Adarsh-jaiss** [comment]
I think there could be two possibilties of this error :

1. Meshery Server Configuration: We need to check that Meshery server is correctly configured to handle Docker Compose imports.
2. Maybe there could be a possibilty of error from the Meshery Ui, we need to debug the import process within Meshery UI.
