### ISSUE TITLE
[DevOps] Populate Meshery Catalog with Sample Apps using `mesheryctl`

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10458]
## Current Situation
[Meshery Catalog](https://meshery.io/catalog) has a relatively small number of published designs.

## Desired Situation

Meshery Catalog is populated with a variety of published designs, representing any number of technologies in the designs and representing different categories of designs. 

## Difficultly Level: Beginner

This is a beginner-level issue designed to both help introduce you, the contributor, to additional Kubernetes concepts and DevOps practices, and to aid in creating a robust catalog full of cloud native design patterns and sample apps in the Meshery Catalog.

## Skills Needed

1. No coding skills needed.
2. Awareness of Kubernetes.

## Implementation

1. **Identify a Kubernetes sample app**
    1. Bring your own Kubernetes manifest or Helm Chart or Docker Compose file or...
    3. ...or identify a sample app from any available in public repos ([example 1](https://github.com/AdminTurnedDevOps/kubernetes-examples), [example 2](https://github.com/kubernetes/examples), [example 3](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples)).
    1. Attempt to identify resources that can benefit both newcomers and seasoned professionals.
1. **Import Kubernetes App**
    1. Import the sample application using `mesheryctl app import` command, [following this guide](https://docs.meshery.io/guides/configuration-management/importing-apps#import-apps-using-meshery-cli). 
1. **Publish Kubernetes App**
    1. Publish your sample app into the Meshery Catalog. Guides: Using Meshery UI or [Using MeshMap](https://docs.meshery.io/extensions/publishing-a-design).
1. **[Optional] Open App in Playground**
    1. Access [Meshery Playground](https://play.meshery.io) and open your app in [MeshMap](https://docs.meshery.io/extensions/meshmap).
1. **[Optional] Share your Kubernetes App**
    1. Be social and share your imported apps on twitter or linkedin and the Meshery project accounts will repost.
1. **Repeat**
    1. Import and publish five or more sample apps.

## Acceptance Criteria
1. Five or more new sample apps have been imported into Meshery and published into the Meshery Catalog.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
You bet!

**Comment by 11happy** [comment]
Hello @leecalcote I am interested to work on this issue can you please assign this to me.
Thank you

**Comment by 11happy** [comment]
Hello @leecalcote I was going through the docs for importing application https://docs.meshery.io/guides/configuration-management/importing-apps#import-apps-using-meshery-cli , there in step 2 it says `Step 2: Navigate to the Application section in the Configuration` however I cannot see any application section in the configuration tab , did I miss any step in my installation? or maybe the docs for this section are not up to date (if yes may I open an issue & would like to work on that as well)
![Screenshot from 2024-04-02 13-12-25](https://github.com/meshery/meshery/assets/76656712/25c6e446-a0fe-469a-bed4-8b3c8f914075)
Thank you

**Comment by 11happy** [comment]
I have currently uploaded 2 designs `nginx ingress` & `postgreSQL cluster` can you please take a look & tell if I am headed in correct direction?

**Comment by 11happy** [comment]
got 6 of the designs accepted! Excited to learn & contribute

**Comment by leecalcote** [comment]
You're on a roll, @11happy. 👏  Congratulations on your design patterns badge. 🎉 

<img src="https://meshery.io/community/recognition/assets/badges/patterns/patterns.png" width="200px" />

**Comment by 11happy** [comment]
Added 3 more designs to the catalog!

**Comment by leecalcote** [comment]
A total of 9 published designs so far. 🕺

https://meshery.layer5.io/user/1cb30087-3787-4aad-8da8-addcb556ae17

**Comment by SammyBloom** [comment]
If there's any design left I would love to hop on this @leecalcote and @11happy

**Comment by leecalcote** [comment]
@SammyBloom, yes, please pick one of these and import -- https://github.com/dapr/samples

**Comment by JAYANTJOSHI001** [comment]
@leecalcote  kindly assign this task to me

**Comment by leecalcote** [comment]
@JAYANTJOSHI001 I'll leave it unassigned so that you and others like @SammyBloom can move forward independently and so that other contributors that would like to dig in understand that the issue is available for them to work on. If you would like to make a copy of this issue and name a specific sample app in that issue, and have it assigned, you're welcome to do so.

**Comment by leecalcote** [comment]
@Shridhar2104, I'm not quite sure what else I can offer other than the lengthy description and itemized steps above. Let me know if if you have a specific question with any of those steps.

**Comment by abdulrafayl226825** [comment]
Hello @leecalcote I would like to work on this issue can you please assign it to me

**Comment by abdulrafayl226825** [comment]
hello @leecalcote https://docs.meshery.io/guides/configuration-management/importing-apps#import-apps-using-meshery-cli  I opened the link you mentioned for guide lines for importing application but there is no documentation available at this link

**Comment by leecalcote** [comment]
https://docs.meshery.io/guides/configuration-management/importing-designs
