### ISSUE TITLE
Error while fetching environemnts using `/api/environments`

### ISSUE THREAD

**Issue by RipulHandoo** [meshery/meshery#10498]
### Current Behavior

![Screenshot 2024-03-05 231500](https://github.com/meshery/meshery/assets/107461226/6a47524b-e931-488b-814b-3a88ece9a150)

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by RipulHandoo** [comment]
@Yashsharma1911

**Comment by Yashsharma1911** [comment]
Thanks for bringing up this issue I'll look

**Comment by RipulHandoo** [comment]
@Yashsharma1911 API is also not working for workspaces.
```https://playground.meshery.io/api/workspaces```


![image](https://github.com/meshery/meshery/assets/107461226/2a309a44-a0fe-4d5d-b527-96f57d3ccfd8)

**Comment by RipulHandoo** [comment]
> Please make sure you are providing orgId as param

Thank you for your input. However, for the 'mesheryctl workspace list' command, we list all workspaces associated with the user, regardless of the orgID parameter.

**Comment by RipulHandoo** [comment]
@Yashsharma1911 still getting error code 500 even by using ORG-ID.
![image](https://github.com/meshery/meshery/assets/107461226/1ed54fe1-2b16-49a3-bf0e-4d01a42ab167)
