### ISSUE TITLE
[mesheryctl] `registry` docs published under `exp` when command has been promoted already

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10503]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
Docs for `mesheryctl registry` are published at https://docs.meshery.io/reference/mesheryctl#experimental-features

### Desired Behavior

Should point to https://docs.meshery.io/reference/mesheryctl/system/registry

### Environment

- Host OS: Mac 
- Meshery Client Version: stable-v0.7.26

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by westcalcote** [comment]
I would like to help here, please.

**Comment by leecalcote** [comment]
Thanks!

**Comment by leecalcote** [comment]
@alphaX86 this issue persists despite some updates and this workflow running --> https://github.com/meshery/meshery/actions/runs/8163850432/job/22317958195#step:6:75

Do you know why `make docs-mesheryctl` (`cd mesheryctl/docs; go run docs.go`) doesn't pickup on the new location of `registry`?

**Comment by alphaX86** [comment]
> @alphaX86 this issue persists despite some updates and this workflow running --> [meshery/meshery/actions/runs/8163850432/job/22317958195#step:6:75](https://github.com/meshery/meshery/actions/runs/8163850432/job/22317958195#step:6:75)
> 
> Do you know why `make docs-mesheryctl` (`cd mesheryctl/docs; go run docs.go`) doesn't pickup on the new location of `registry`?

I just need to look at the `docs` script behavior to find the cause. I'll take this up now and fix this.

**Comment by alphaX86** [comment]
From the trial run I conducted in local, my observation is they are already made and present in the `docs/pages/reference/mesheryctl` path. Screenshot is attached below...
<img width="244" alt="image" src="https://github.com/meshery/meshery/assets/59508546/7cc85adf-46cd-4165-9026-efce503a6b56">

So, right now, the script is not causing issue. The issue is with the reference table we have which needs manual update often.
