### ISSUE TITLE
[mesheryctl] registry command help points to incorrect URL

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10502]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
```
$ mesheryctl registry import
Error: 'import' is an invalid command.  Use 'mesheryctl registry --help' to display usage guide.

See https://docs.meshery.io/reference/mesheryctl/system for usage details
```

### Desired Behavior

Should point to https://docs.meshery.io/reference/mesheryctl/system/registry for usage details

### Environment

- Host OS: Mac 
- Meshery Client Version: stable-v0.7.26

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by tico88612** [comment]
Hi @leecalcote

I'm interested in this issue. Can you assign it to me?
