### ISSUE TITLE
[UI] Better snackbar title on toggle of extensions

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#10514]
### Current Behavior
On toggle for extensions, it says Adapter processing but doesn't show success or failure for enabled extension

### Desired Behavior
Suggest better snackbar title

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by NAMANIND** [comment]
Hey @ritiksaxena124 , I want to work on this issue

**Comment by utsavll0** [comment]
@ritiksaxena124, I want to work on this issue if its still available

**Comment by ritiksaxena124** [comment]
Thank you for your interest folks. We assign issues on a first come first serve basis so @NAMANIND go ahead. y @utsavll0 we have couple of more good first issues on which you can work on. Just go to issues tab and filter based on good first issues.

**Comment by NAMANIND** [comment]
Hey @ritiksaxena124 kindly review my PR
