### ISSUE TITLE
[UI] Expose Remote Provider Capabilities in Settings page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10510]
### Current Behavior
As an extensible platform, Meshery has many different extension points. The Remote Provider extension point is one of those.

### Desired Behavior
Expose this API’s information in the existing “Remote Provider” tab of the Settings page - http://localhost:9081/api/provider/capabilities

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aseem22** [comment]
@leecalcote can I work on this, please?

**Comment by leecalcote** [comment]
A quick mockup would be good to gain alignment and set expectations.

**Comment by Aseem22** [comment]
![Meshery](https://github.com/meshery/meshery/assets/89309144/8dc09245-1be4-4859-8d8c-7cef80ac838b)



here's  a quick mockup. Need feedback here. @leecalcote @ritiksaxena124

**Comment by Aseem22** [comment]
> @Aseem22 Sure, we can start with this. We'll want to iterate a bit, but this gets the job done.

Should I, for now, open a PR for this?
