### ISSUE TITLE
[UI][Connections] GitHub App gets dev environment assigned multiple times

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#10512]
### Current Behavior
On the Connections screen, the GitHub App gets assigned a dev environment thrice, that form may take multiple non-unique values
![image](https://github.com/meshery/meshery/assets/51539117/44aa729e-b5bb-45b5-946d-d00ced42e2b1)

### Desired Behavior
Dev environment should get assigned once 

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ayush844** [comment]
I would like to work on this issue, you can assign it to me

**Comment by ayush844** [comment]
@yash37158, thanks for the whimsical encouragement! I've taken the plunge and successfully set up Meshery locally on my system! Let me know if there's anything specific you'd like me to try out!

**Comment by yash37158** [comment]
@ayush844 Here's your head start to get going: check out the Meshery contributing guide at https://docs.meshery.io/project/contributing. It's your roadmap to jumping into the world of Meshery dev!
