### ISSUE TITLE
Pop up Modals in Meshery UI [UI]

### ISSUE THREAD

**Issue by Rexford74** [meshery/meshery#10531]
### Current Behavior

The different modals for actions in MeshMap have some basic style and text content flaws that cause an inconsistent experience for users.

### Desired Behavior

All modals should not be verbose, should convey concise information, and be visually appealing as the user navigates our solution, using them for whatever intended purposes.
### Implementation

The modal component will be defined in Sistent, which will serve as a guide with proper documentation on what modals should look like and how to utilize them effectively.

### Acceptance Tests

Both the modal section in Sistent and the modals themselves will be reviewed for flaws and any lacking areas by both Meshery and Sistent maintainers, and upon being approved, they can now be implemented. A PR will also be opened to fix this issue.

### Mockups
There is none yet. It is currently a work in progress. A PR will be raised to resolve this issue.
---

### Modals to be updated

**Connections**
- [ ] Add cluster 
- [ ] Delete connection
- [ ] Transition of state 

**Environments**
- [ ] Create 
- [ ] Edit
- [ ] Delete
- [ ] Transfer list

**Workspaces**
- [ ] Create 
- [ ] Edit
- [ ] Delete
- [ ] Transfer list

**Designs**
- [ ] Import
- [ ] Publish/Unpublish
- [ ] Info
- [ ] Validate/Undeploy/deploy

**Filters**
- [ ] Import
- [ ] Publish/Unpublish
- [ ] Info
- [ ] Validate/Undeploy/deploy

**Performance**
- [ ] Add profile
- [ ] Edit/ Run test
- [ ] Delete

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
@aabidsofi19 i have added the modals list to be updated

**Comment by leecalcote** [comment]
Good write up here, @Rexford74
