### ISSUE TITLE
[Docs] Rearrange Logging Section in Meshery docs

### ISSUE THREAD

**Issue by yash37158** [meshery/meshery#10536]
### Current State
As of now, we have the Logging section below https://docs.meshery.io/project/contributing/contributing-server.

### Desired State
The current documentation for contributing to Meshery Server (https://docs.meshery.io/project/contributing/contributing-server) could be improved by reorganizing the sections to enhance clarity for contributors. Specifically, the section would be moved above the section Suggestion Reading.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thank you, @yash37158
