### ISSUE TITLE
`make docker` command fails when setting up dev environment for docs

### ISSUE THREAD

**Issue by sangramrath** [meshery/meshery#10542]
### Current Behavior
On running `make docker` or `make docs-docker` to serve the documentation code through docker there are requirement conflicts with the ruby version. 
The docker container never starts and fails with the following error:
```
Ruby (< 3.4.dev, >= 3.1), which is required by gem 'nokogiri (>= 1.13.6, <
2.0)', is not available in the local ruby installation
make: *** [Makefile:329: docs-docker] Error 6
```

### Expected Behavior
There is no error and docker container runs.

### Screenshots/Logs
![Screenshot 2024-03-12 at 5 39 49 PM](https://github.com/meshery/meshery/assets/6134395/8220b758-8c4e-40d4-bc79-8b11a8b7b08e)

### Environment

- **Host OS:** Mac
- **Platform:** Docker
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sangramrath** [comment]
### Cause
The `docker run` command in Makefile uses _jekyll:4.0.0_ image which uses ruby 2.7. Changing it to _jekyll:4.0_ (a newer image than 4.0.0) works which has ruby 3.1. (tested)

**Comment by leecalcote** [comment]
Thank you for reporting this, @sangramrath 👏
