### ISSUE TITLE
[UI] Enhance Connection Deletion confirmation modal

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10558]
### Current Behavior
On the Connections page (/management/connections), when Deleting a connection, a confirmation modal displays.

<img width="297" alt="Screenshot 2024-03-13 at 5 24 23 PM" src="https://github.com/meshery/meshery/assets/7570704/5d678048-58e5-4887-823a-18307de70c9a">

### Desired Behavior
The confirmation modal should be using the [Sistent design system](https://github.com/layer5io/sistent)'s standard modal and include the following four fixes.

<img width="745" alt="Screenshot 2024-03-13 at 5 21 30 PM" src="https://github.com/meshery/meshery/assets/7570704/e4d26fbf-c3fa-4a89-b1fa-570cfb727874">

### Environment
- Meshery Server Version: stable-v0.7.31

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by tico88612** [comment]
@leecalcote 

I am interested in this issue. Could you assign it to me?

**Comment by leecalcote** [comment]
Excellent. You bet.

**Comment by hariFED** [comment]
Is this issue still open? Happy to work on the issue.

**Comment by tico88612** [comment]
@hariFED I still working now.

**Comment by hariFED** [comment]
@tico88612 Ok.

**Comment by tico88612** [comment]
Hi @leecalcote 
I apologize in advance. I've been working on this for a few days, but I've realized that UI is not my strong suit, the local development environment is not well established, and I'm releasing this opportunity to other potential contributors.

**Comment by leecalcote** [comment]
@tico88612 I very much appreciate this note.

**Comment by psankhe28** [comment]
@hariFED Are you working on this issue? If not, can I work on this one?

**Comment by literalEval** [comment]
Hey @leecalcote since this issue is not being worked upon actively, please assign it to me. Thanks.

**Comment by leecalcote** [comment]
Batter-up, @literalEval 👍

**Comment by vidhihattar** [comment]
Hi, @leecalcote if this issue is still not completed, I would like to work on this.

**Comment by leecalcote** [comment]
Thanks, @vidhihattar. Will you confirm that you've built both Meshery Server and UI?

**Comment by vidhihattar** [comment]
@leecalcote Yes, I was able to set up both meshery server and UI, here is a screenshot of the same:
<img width="1440" alt="Screenshot 2024-06-14 at 3 14 30 PM" src="https://github.com/meshery/meshery/assets/84982665/57484a5d-8a26-40a1-980f-53a8fd4f3f13">

**Comment by leecalcote** [comment]
Thanks, @vidhihattar

**Comment by vidhihattar** [comment]
@leecalcote when i try to recreate this issue, i cant see any delete option in the dropdown menu:
<img width="1154" alt="Screenshot 2024-06-14 at 3 25 24 PM" src="https://github.com/meshery/meshery/assets/84982665/217b6185-08f6-468f-a6dd-f405150a3807">

**Comment by leecalcote** [comment]
@sudhanshutech do you mind offering direction here?

**Comment by sudhanshutech** [comment]
> @leecalcote when i try to recreate this issue, i cant see any delete option in the dropdown menu: <img alt="Screenshot 2024-06-14 at 3 25 24 PM" width="1154" src="https://private-user-images.githubusercontent.com/84982665/339724443-217b6185-08f6-468f-a6dd-f405150a3807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjE0NjAsIm5iZiI6MTcxODM2MTE2MCwicGF0aCI6Ii84NDk4MjY2NS8zMzk3MjQ0NDMtMjE3YjYxODUtMDhmNi00NjhmLWE2ZGQtZjQwNTE1MGEzODA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEwMzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0Y2RhMWMyYTgyMWM0Yzc3NmJiOTMwMTk0YTlmMmQxYmRlYmYzY2QyMzUzZjhkYTQ3NDQ0ZjVmZTE1YjU5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AEFO22pTiryR9VCwLE7_mSQn_U4qdpr5fqXV9rRC0jk">

@vidhihattar few things to ensure.
First you are not  connected to any kubernetes cluster so you are not seeing more then one connection.
To get few more connections follow this: https://docs.meshery.io/installation/kubernetes or a simple way is use docker-desktop.
Before running `make server` start your docker with kubernetes running. 

Now next only those connections you will see delete status that can be transitioned

**Comment by vidhihattar** [comment]
@leecalcote Please have a look at this. I have added the cross button and changed the position of the 'i' button. However, I would like some clarity on the 1st and 4th point. I'm not sure how to change this to a sistent modal and also do you have a specific connection icon in mind or should I use one from the internet.
<img width="400" alt="Screenshot 2024-06-21 at 4 06 45 PM" src="https://github.com/meshery/meshery/assets/84982665/57b0a779-2502-47e7-9dc7-d20184e725ff">

**Comment by leecalcote** [comment]
@vidhihattar here you are - https://github.com/meshery/sistent

**Comment by vidhihattar** [comment]
I have gone through that website but as I can see there are buttons and text input components only, by this do you mean that I should change the buttons to the sistent component buttons to make this into a sistent modal? Other than this, there is no information about sistent modals on this website: https://github.com/meshery/sistent. Am I missing something? any guidance would be appreciated! @leecalcote  @sudhanshutech
