### ISSUE TITLE
[UI] Import Design modal crashing

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10557]
### Current Behavior
On /configuration/designs page, the import design form crashes when the type selector is clicked.

### Screenshots/Logs

https://github.com/meshery/meshery/assets/7570704/6e94ad1c-25c9-45c2-8d9c-e8359d33869b

### Environment

- Browser: Safari
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.31

- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@meshery/meshery-ui-contributors @meshery/meshery-ui-maintainers

**Comment by kunal-511** [comment]
This is working fine in my device

https://github.com/meshery/meshery/assets/118254863/debb299b-1b7a-4a22-9e2b-2b8a2e3704a1

**Comment by sudhanshutech** [comment]
@Yashsharma1911 is this still a issue?
