### ISSUE TITLE
[Components] Inconsistent Fill Coloring

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10563]
Why are the fill colors for DaemonSet, CronJob, Event and other comopnents translucent and not 100% opaque? Why does their semi-opacity not match with that of the Deployment component?

[Slack Message](https://layer5io.slack.com/archives/C02F90W866T/p1710389831128049)

**Comment by leecalcote** [comment]
@ritiksaxena124 @captain-Akshay @aabidsofi19 has this been fixed?

**Comment by captain-Akshay** [comment]
Ok the issue was with the styleoverrides in the spreadsheet.Though I added the complete svg for them but @ritiksaxena124  can you check and add the square svg for some of them according to shapes please!
