### ISSUE TITLE
[mesheryctl]: New command exp workspace.

### ISSUE THREAD

**Issue by RipulHandoo** [meshery/meshery#10586]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Desired Behavior
Create an experimental command to interact with workspace functionality. For more details about workspaces, please refer to the [Workspace documentation](https://docs.meshery.io/concepts/logical/workspaces).

Tasks to be completed:
- [ ] Implement command to list workspaces
- [ ] Implement command to create new workspaces
- [ ] Develop test cases to ensure command functionality

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

**Comment by UncleWeeds** [comment]
@RipulHandoo, I would like to work on this issue.

**Comment by RipulHandoo** [comment]
@UncleWeeds Certainly, it's great to see your interest in contributing! At the moment, I've already raised a PR for this particular feature. However, I appreciate your willingness to help. There are some other issues similar to this.

**Comment by UncleWeeds** [comment]
@RipulHandoo , Ho ok
