### ISSUE TITLE
[mesheryctl] New command exp environment

### ISSUE THREAD

**Issue by RipulHandoo** [meshery/meshery#10583]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Desired Behavior
Develop an experimental command to manage environments within the system. Refer to the [Environment documentation](https://docs.meshery.io/concepts/logical/environments) for more details about environments.

Tasks to be Completed:
- [ ] Implement command to list existing environments
- [ ] Implement command to create new environments
- [ ] Implement command to delete existing environments
- [ ] Implement command to view details of a specific environment
- [ ] Develop comprehensive test cases to validate the functionality of the environment command

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

**Comment by luigimorel** [comment]
@RipulHandoo  can this be assigned to me?

**Comment by RipulHandoo** [comment]
@luigimorel Certainly, it's great to see your interest in contributing! At the moment, I've already started working on this particular feature. However, I appreciate your willingness to help. There are some other issues similar to this. I'll mention them below:
https://github.com/meshery/meshery/issues/10585
https://github.com/meshery/meshery/issues/10582
