### ISSUE TITLE
[mesheryctl]:  New command exp credential

### ISSUE THREAD

**Issue by RipulHandoo** [meshery/meshery#10585]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Desired Behavior
Develop an experimental command to manage credentials within the system. Refer to the [Credential documentation](https://docs.meshery.io/concepts/logical/credentials) for more information about credentials.

Tasks to be Completed:
- [ ] Implement command to list existing credentials
- [ ] Implement command to create new credentials
- [ ] Implement command to delete existing credentials
- [ ] Implement command to view details of a specific credential
- [ ] Develop comprehensive test cases to validate the functionality of the credential command

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

**Comment by singh1203** [comment]
@RipulHandoo Please assign me, Let me lend a hand with it. 
Thank You!

**Comment by RipulHandoo** [comment]
@singh1203 Could you please provide an update on the progress of this issue? 
Thank you.

**Comment by singh1203** [comment]
> @singh1203 Could you please provide an update on the progress of this issue? Thank you.

WIP, soon I'll be pushing commit for the `credential list`.
Thank you.
