### ISSUE TITLE
[mesheryctl] New command exp connection

### ISSUE THREAD

**Issue by RipulHandoo** [meshery/meshery#10582]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Desired Behavior

Create an exp connection command
- [x] List
- [ ] View
- [ ] Create
- [x] Delete

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

**Comment by luigimorel** [comment]
assign me this for the start

**Comment by RipulHandoo** [comment]
@luigimorel Could you please provide an update on the progress of this issue? 
Thank you.

**Comment by luigimorel** [comment]
@RipulHandoo  can i get a link to the meshery API with documentation? I have tried to find it to no success. I would like to look at the payload for the connection creation.

**Comment by leecalcote** [comment]
Reference:

- Connection schema - https://github.com/meshery/schemas/blob/master/schemas/constructs/v1alpha2/connection.yml
- REST API for Connections (needs improvement) - https://docs.meshery.io/reference/rest-apis#post-handle-post-request-for-creating-a-new-connection

**Comment by lekaf974** [comment]
thank you
