### ISSUE TITLE
Design page requires reload to reflect changes made in catalog data from info modal

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#10593]
### Current Behavior
Presently as I made changes in info modal it get's saved and I also got toaster notification however, after clicking on info modal again I don't see my changes, however after reloading the page it get's updated

https://github.com/meshery/meshery/assets/71271069/13789ff5-e26d-465d-9e0d-e3950605a356

### Expected Behavior
Make sure when we open info modal instead of using cache data we make new API request to make sure we are always updated in info modal

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Hbrehman** [comment]
can I work on this issue?

**Comment by dragon-slayer875** [comment]
Hello @Yashsharma1911.
I have managed to fix this issue on my fork and would like to request an assignment to make a PR for review.

**Comment by leecalcote** [comment]
Thank you, gents.

**Comment by Yashsharma1911** [comment]
Thankyou guys for picking this issue up, please any of you can make a PR and other one can help with making sure it get reviewed

**Comment by dragon-slayer875** [comment]
PR is up @Yashsharma1911 .
Would like to request a review.
