### ISSUE TITLE
[Docs] Include error code moniker in "search forum" URL

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10635]
### Current State
On the error code reference page, https://docs.meshery.io/reference/error-codes, the "Search Forum" link only has the numeric portion of the error code included and is missing the "Err....." portion of the error code.

<img width="143" alt="Screenshot 2024-03-28 at 2 22 40 PM" src="https://github.com/meshery/meshery/assets/7570704/902f4216-6c9b-477f-a2fb-2aa40a17d30f">

### Desired State
Please ensure that this search term has the moniker included in the query string.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by elasticspoon** [comment]
Howdy, can I take this?

Also just to clarify you would like the link to go from for example: `https://discuss.meshery.io/search?q=1010` to `https://discuss.meshery.io/search?q=ErrStreamEventCode-1010`?

**Comment by leecalcote** [comment]
Wonderful. Yes, @elasticspoon you nailed it. 👍
