### ISSUE TITLE
[mesheryctl]: lint checks failing 

### ISSUE THREAD

**Issue by RipulHandoo** [meshery/meshery#10631]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
Several lint checks are failing in the recent GitHub Actions run for mesheryctl. This issue is linked to the following GitHub Actions run: [link to the GitHub Actions run](https://github.com/meshery/meshery/actions/runs/8466661227/job/23195915176).
![image](https://github.com/meshery/meshery/assets/107461226/bdb7655d-0829-47ca-908d-4387d142e52a)

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by singh1203** [comment]
@RipulHandoo Maybe I can give it a try for it.
