### ISSUE TITLE
[UI] Accessibility enhancement of Sidebar Toggle

### ISSUE THREAD

**Issue by dragon-slayer875** [meshery/meshery#10630]
### Current Behavior
The sidebar collapse toggler, as it is right now, proves somewhat inaccessible when the sidebar is open due to it's transparency, making it difficult to distinguish it from the surrounding content. 
This can lead to confusion and decreased usability, especially for users with visual impairments or in low-light conditions.
![image](https://github.com/meshery/meshery/assets/59254790/f870ad3f-54ab-45e7-926f-2f46ecd8c53b)

### Desired Behavior
The component should have a distinct background color that contrasts with the surrounding content, ensuring it is clearly visible to all users.

### Implementation
Setting a more distinguishable background color (probably the bg color of the sidebar?)
Normal state
![image](https://github.com/meshery/meshery/assets/59254790/3d5e9760-b3d4-42af-b3b0-3249c686ebae)
Hover/Focus state
![image](https://github.com/meshery/meshery/assets/59254790/9ba05964-b18a-4636-bebe-7aa663c7a142)

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
This is a valid issue. The proposed solution isn't acceptable, however. @Rexford74, help?

**Comment by leecalcote** [comment]
The transparency works well when the tab is flipped on top of the Meshery menu, but you're right, @dragon-slayer875, not when the tab is on top of the rest of the page content.

**Comment by dragon-slayer875** [comment]
I agree @leecalcote. That is why I made sure to target code that is active when the sidebar is open.
As soon as Rex provides his suggestions, we can implement them immediately.
