### ISSUE TITLE
[UI] Unexpected Error logs and EOF, while starting meshery-ui server.

### ISSUE THREAD

**Issue by anmolchhabra21** [meshery/meshery#10645]
### Current Behavior

Currently, whenever trying to start the local server using `make server` or even when using the build command `make ui-server`, it throws a bunch of error logs. Needed to resolve that.
![image](https://github.com/meshery/meshery/assets/93809908/0d0d46ba-c1d5-4976-bc9d-9e05de7abd8f)

### Desired Behavior

No Error Logs.

### Screenshots/Logs

Logs:
`
ERRO[2024-03-30T15:29:27+05:30] UNIQUE constraint failed: keys.id             app=meshery code=meshery-server-1312 probable-cause="Record already exist.Database connection is not reachable" severity=2 short-description="Unable to create record" suggested-remediation="Delete the record or try updating the record instead of recreating.Rest the database connection"
`

Link to Similar discussion: https://discuss.layer5.io/t/404-page-while-running-meshery-locally/2448/2
### Environment

- Browser: Chrome 
- Host OS: Linux 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
@MUzairS15
