### ISSUE TITLE
[UI] Registry: Component search doesn't work

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10679]
### Current Behavior
Visit Settings-->Registry-->Components, enter the name of a known component.

No results are displayed despite components being registered with matching name.

### Desired Behavior
Matching results should be shown and should be case insensitive.

### Screenshots/Logs
https://github.com/meshery/meshery/assets/7570704/736e0564-90c1-489e-9020-a120fd4aed82

### Environment

- Browser: Safari 
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.42

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
// @Yashsharma1911

**Comment by Aryakoste** [comment]
Hello @leecalcote. I would like to work on this issue.

**Comment by leecalcote** [comment]
Sounds great. Thank you, @Aryakoste

**Comment by leecalcote** [comment]
Recognize that this may this may need to be fixed on the backend in Golang.

**Comment by Aryakoste** [comment]
Yes. I am comfortable with Go lang.

**Comment by Yashsharma1911** [comment]
This issue is coming because isAnnotation param is set to false in API call which should be true instead, @Aryakoste you will need to make ui changes

**Comment by Yashsharma1911** [comment]
@Aryakoste checkout - 

https://github.com/Yashsharma1911/meshery/blob/b4a5303fffbde299d8e8f52bd78a408b1f66a8a3/ui/components/MeshModelRegistry/MeshModelComponent.js#L141

**Comment by Aryakoste** [comment]
Ok. Thanks
