### ISSUE TITLE
[Extensions]Unable to import design of type Helm Chart

### ISSUE THREAD

**Issue by sangramrath** [meshery/meshery#10702]
### Current Behavior
I am unable to import design of type _Helm Chart_ using the URL for a .tgz file. Upon clicking import, it throws the following error "**Status Code: 500.could not send design to remote provider: yaml: control characters are not allowed**"

### Desired Behavior
I should be able to import design of type _Helm Chart_ using the URL for a .tgz file. 

### Screenshots/Logs
![Screenshot 2024-04-09 at 6 17 22 PM](https://github.com/meshery/meshery/assets/6134395/0a849097-0800-482b-a1d3-4a1ccd8ca0a5)

### Environment

- Host OS: Mac
- Meshery Server Version: v0.7.45
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sangramrath** [comment]
@yash37158 and @MUzairS15

**Comment by Adarsh-jaiss** [comment]
- Hey @sangramrath , can you please share the lURL for that .tgz file and a proper screenshot of the component where you are facing the issue!
- I'll take a look into it :)

**Comment by Yashsharma1911** [comment]
Hey @Adarsh-jaiss thankyou for raising your hand here, as this was urgent and high priority issue, I already took care of it, I would suggest you to help with other similar issues also, let us know if you not able to find them ^^
