### ISSUE TITLE
[Docs] Tables in references is not accessible in mobile view.

### ISSUE THREAD

**Issue by Aseem22** [meshery/meshery#10704]
### Current State

https://docs.meshery.io/reference/mesheryctl

![screenshot_2024-04-03-12-31-30-58_720](https://github.com/meshery/meshery/assets/89309144/acb77dfe-a76d-453f-beaa-30151e6ac7fd)

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aryakoste** [comment]
Hello @Aseem22 @leecalcote. I would like to work on this issue.

**Comment by Aseem22** [comment]
> Hello @Aseem22 @leecalcote. I would like to work on this issue.

Hi @Aryakoste, Thanks for reaching out and offering to take on this issue. I'm actually already working on this issue. Would you be interested in tackling another related task?

**Comment by Aryakoste** [comment]
Ok
