### ISSUE TITLE
[Artifact Hub] Official status for Meshery helm chart repo

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10712]
### Current Behavior
https://artifacthub.io/packages/helm/meshery/meshery is a verified repo, but not an official repo.

### Desired Behavior
Following [this guide](https://artifacthub.io/docs/topics/repositories/#official-status), see that the Meshery repo becomes an official repo (carries the official level badge).

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ctcarrier** [comment]
@leecalcote I created a ticket to start the process for getting `Official`: https://github.com/artifacthub/hub/issues/3759

**Comment by leecalcote** [comment]
Yessss. 👏

**Comment by ctcarrier** [comment]
@leecalcote One thing to note is that Artifact Hub seems to give some special consideration to repositories where every package is official. As opposed to a mix of official and non-official. Currently the meshery AH repo only has Meshery packages so the whole repo can be considered Official. But if we mix in designs from the catalog then it might get messier. I wonder if it would simplify to create a new AH repository specifically for "Meshery Catalog" to contain non-official designs. That way there could be 1 official repo and as many verified repos as we want with designs in them.

**Comment by leecalcote** [comment]
I hear what you're saying regarding the probable need for a dedicated repo Meshery Designs repo to segregate packages: Meshery Helm Charts and Meshery Designs. I'm digesting this...  I wonder if some experimentation might flush out this need a bit further, like a couple of artifacthub-pkg.yml files published alongside design files that are in the current Catalog repo (meshery/meshery.io).
