### ISSUE TITLE
[Docs] Component Dependencies: Operator deployments

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10730]
### Current State
Make sure you deploy operators as needed when designs that contain models and components are dependent upon them. 

### Desired State

Update this https://docs.meshery.io/guides/infrastructure-management/overview#meshery-internals-provisioning-process with information answering the question of: 

How does Meshery know what Operator to provision when provisioning components from a given Model?

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Haimantika** [comment]
Hi @leecalcote is this issue up for grabs?

**Comment by leecalcote** [comment]
Yes, thanks for asking, @Haimantika. Although, I'm afraid that you're going to hit a wall here where we don't have enough of the information needed internally available to deliver to you to properly document Meshery's behavior here. @MUzairS15 is familiar with this area and can offer the necessary insight, however, I don't know that he's available to do so. I'll let him answer...

**Comment by leecalcote** [comment]
@MUzairS15

**Comment by MUzairS15** [comment]
There’s a open PR for this
