### ISSUE TITLE
Responsiveness on 'Remote Provider' page.

### ISSUE THREAD

**Issue by Rexford74** [meshery/meshery#10743]
### Current Behavior
 Remote provider capabilities & extensions were recently included in the Meshery UI's preferences, however, there is a responsiveness issue that needs fixing, primarily in mobile view. See attached image.

### Expected Behavior
 A responsive site that accounts for the mobile view of this new page. Here's a possible solution [in Figma]. (https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=29694%3A19485&mode=design&t=mElCikdb8NjkLBBo-1)

### Screenshots/Logs
What we have: 
![Remote provider issue](https://github.com/meshery/meshery/assets/98197344/df71e375-0dcf-4936-88e5-fda190625820)

What we could have: 
![Figma remote provider page](https://github.com/meshery/meshery/assets/98197344/24156e04-12bf-4774-ad43-437e199bc14a)

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aseem22** [comment]
@Rexford74 please assign.

**Comment by Rexford74** [comment]
> @Rexford74 please assign.
Done! Please let me know when you have some time on your hands so I can point out the other issues on desktop that you have to fix. Thanks.

**Comment by hargunkaur286** [comment]
@leecalcote @Rexford74 Can I work on this issue?

**Comment by ChenemiKen** [comment]
Hello @Rexford74 I’ll like to work on this. Can you assign to me.

**Comment by AbhishekJ24** [comment]
Hello, I would also like to work on this!

**Comment by leecalcote** [comment]
Thank you! Assigning in chronological order...

**Comment by akshansh-modi** [comment]
found this in good first issue , hey can i work on this issue

**Comment by leecalcote** [comment]
No progress to date. Assigning to next volunteer: @ChenemiKen

**Comment by ChenemiKen** [comment]
Hi @leecalcote , @Rexford74 . Please help review my pull request for this issue. Thanks.

**Comment by shreycmd** [comment]
can i work on this?

**Comment by siddharthbaleja7** [comment]
@leecalcote Can you please assign this issue to me?

**Comment by leecalcote** [comment]
@shreycmd and @siddharthbaleja7 and I do a way to contribute here is to review the open PR listed above. Your comments in line in the PR…

**Comment by emmanuelhashy** [comment]
@leecalcote I'd love to work on this issue. Can you please assign this issue to me?

**Comment by emmanuelhashy** [comment]
Hi @leecalcote , @Rexford74 . Kindly review my pull request for this issue. Thanks

**Comment by VengefulSpartan** [comment]
@leecalcote Can i work on this issue? If it is still unresolved.

**Comment by Divyansh200102** [comment]
Is this issue resolved ? It seems to be looking fine on my end for mobile view? @Rexford74 @leecalcote 
![image](https://github.com/user-attachments/assets/a8ce4bb8-5844-4d01-98f0-a001d1fe98b6)

**Comment by leecalcote** [comment]
The low contrast issue needs to be addressed.

**Comment by eyeaadil** [comment]
@leecalcote Can i work on this issue? If it is still unresolved.

**Comment by eyeaadil** [comment]
@leecalcote @Rexford74 In my system , responsive is working well,In previous comment you talk about low contrast,can you specify which contrast you are talking about.
![image](https://github.com/user-attachments/assets/15444764-c939-4943-9faf-a066b2dd5600)
