### ISSUE TITLE
[Extension] Add feature of  auto rendered clickable links in meshery design description

### ISSUE THREAD

**Issue by deepak4566** [meshery/meshery#10745]
### Current Behavior

Currently published designs description  in meshery catlog doesn't have clickable links , they are not rendered 
![design](https://github.com/meshery/meshery/assets/122792652/7aa084b2-e3a1-47fe-a7a0-f5ecd3ef5d67)

### Expected Behavior

Need to have clickable links in description  of designs.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
This issue is now fixed
