### ISSUE TITLE
[Server] Priortization of crds while doing a design deployment

### ISSUE THREAD

**Issue by aabidsofi19** [meshery/meshery#10760]
### Current Behavior

Designs that declare use of given custom resource fail to deploy despite the fact that same design has the custom resource definition .

https://playground.meshery.io/extension/meshmap?design=d0e4928e-ec21-4cab-8320-de5cdbf9c421

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Fixed in v0.7.50
