### ISSUE TITLE
[Server] Meshery Server - ErrCompConfigPairsCode-1073:  Missing probable cause and suggested remediation

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10762]
### Current Behavior
<img width="1087" alt="Screenshot 2024-04-23 at 10 33 30 AM" src="https://github.com/meshery/meshery/assets/7570704/dd24b4f2-899e-4a9c-ba58-f3ed4e6be7e1">

### Expected Behavior
Description, cause and remediation are needed.

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v0.7.46
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by devashishroychowdhury** [comment]
#### Try to restart the server once again might work it worked in my machine..
