### ISSUE TITLE
[CI][meshery-docs-preview] failing Netlify checks in meshery-docs-preview

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery#10774]
### Current Behavior
Netlify checks are failing for PRs with `area/docs` label

### Desired Behavior
They should pass as before.

### Acceptance Tests

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by leecalcote** [comment]
@vishalvivekm assigned to you.

**Comment by leecalcote** [comment]
I have update the ruby env var in Netlify to specify 3.2.2.

**Comment by leecalcote** [comment]
That didn't help. I have updated the Gemfile.lock to include ruby-3.2.2. This seems to have helped.

**Comment by leecalcote** [comment]
Or maybe not...

**Comment by leecalcote** [comment]
@vishalvivekm we don't need the Netlify builds as we have a deployment preview solution already. Can you disable these?

**Comment by leecalcote** [comment]
I handled this.
