### ISSUE TITLE
[Docs] Integrations: Duplicate "Suggested Reading" links

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10784]
### Current State
on any of the integration pages, like https://docs.meshery.io/extensibility/integrations

<img width="916" alt="Screenshot 2024-04-25 at 8 09 59 AM" src="https://github.com/meshery/meshery/assets/7570704/8ca18054-8e0f-47aa-854f-bc3a7b2df865">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by RafaelJohn9** [comment]
hello @leecalcote can I be assigned this issue
