### ISSUE TITLE
[Extensions] Confirmation Model upon deleting designs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10783]
### Current Behavior
In the MeshMap Designer extension, users might accidentally delete their designs without confirmation.

### Desired Behavior
<img width="697" alt="Screenshot 2024-04-25 at 7 57 41 AM" src="https://github.com/meshery/meshery/assets/7570704/af9cca31-cfc0-414d-91be-932ca7e23c1f">

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by RafaelJohn9** [comment]
@leecalcote  I would like to work on this issue

**Comment by leecalcote** [comment]
@Rexford74

**Comment by Rexford74** [comment]
Thank you for notifying me, @leecalcote.
The confirmation modal will suffice in this case. This is a link to what [the modal](https://www.figma.com/design/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?node-id=6323-19026&t=i2tQQZzi8xqYKQGh-1) should look like and this is [the behaviour](
https://github.com/meshery/meshery/assets/98197344/8275ee2f-7513-4e00-a118-421f4175d176
) that can accompany the interaction.
The overlay background added has the hex code #000d12 at 50% opacity. When the trigger is clicked, the modal dissolves onto the page at a speed of 300ms. Let me know if you'd need any further information to complete this task, @surajgjadhav.

Have you been assigned the task yet, @surajgjadhav or are you just making enquiries?

**Comment by surajgjadhav** [comment]
Hi @Rexford74 ,
Thanks for confirming. No it's not yet assigned to me.
one more doubt: 
do we need to develop it in sisten repo first and then use it in ui
or we can create it directly in ui ?
Please suggest 
thanks

**Comment by Rexford74** [comment]
No, Suraj. It won't be necessary to create the modal from scratch. I understand that there is already one created in [Sistent](https://github.com/layer5io/sistent). Use that one instead and implement the necessary changes there. Do let me know if you have any more questions.

**Comment by akshansh-modi** [comment]
@leecalcote @Rexford74  I'm interested in working on this issue. Could you please assign it to me?
