### ISSUE TITLE
[Docs] Document Catalog publish flow

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10797]
### Desired State
Ensure that the docs page has SVGs of the sequence diagrams from the Meshery Arch deck (and Cloud deck).

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by deepak4566** [comment]
Can i know the  workflow path to work on this ??

**Comment by pandeyyyy** [comment]
Hi @leecalcote , I’m confident I can solve this issue. Could you please assign it to me? I’m eager to get started!
also if you elaborate more then it will easy for me

**Comment by Kevin222004** [comment]
Can I work on this?

**Comment by leecalcote** [comment]
Thanks, @Kevin222004. Given the work that you're already doing on this topic, this is most helpful.
