### ISSUE TITLE
Replace the repetitive logic for extracting `page, pagesize, search, offset` from API handlers to use  `getPaginationParams ` in `utils.go`.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#10825]
Replace the repetitive logic for extracting `page, pagesize, search, offset` from API handlers to use  `getPaginationParams ` in `utils.go`.

_Originally posted by @MUzairS15 in https://github.com/meshery/meshery/pull/10824#discussion_r1585605275_

**Comment by RyanCarlisle** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by MUzairS15** [comment]
Thanks for volunteering @RyanCarlisle , have you successfully setup Meshery at your local environment?

**Comment by nikzayn** [comment]
@RyanCarlisle, I have something in mind too. If you're working on this, do let me know. Thanks!!

cc: @MUzairS15

**Comment by RyanCarlisle** [comment]
Hi @nikzayn , I shall be working on this

**Comment by nikzayn** [comment]
> Hi @nikzayn , I shall be working on this

That’s why I asked first buddy.

**Comment by akshansh-modi** [comment]
found this in good first issue , if this issue is still open can I work on this ?
