### ISSUE TITLE
[UI] Add "Catalog" menu item under Configuration menu

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10822]
### Current Behavior
Missing Catalog menu item

### Desired Behavior
Ensure this item is displayed / not displayed when the extension is enabled vs not enabled.
Use the catalog icon for this menu item.

### Mockups

<img width="260" alt="Screenshot 2024-04-30 at 4 32 11 PM" src="https://github.com/meshery/meshery/assets/7570704/c6984d42-0417-4134-b654-303929d17deb">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by fazzy12** [comment]
hey, can I work on this issue?

**Comment by theavitw** [comment]
Can I work on this issue?

**Comment by leecalcote** [comment]
Thanks for volunteering!

**Comment by leecalcote** [comment]
@fazzy12 we're looking to have this completed by this coming Tuesday. Is that a feasible timeline? // @sudhanshutech

**Comment by leecalcote** [comment]
@fazzy12, I didn't hear back, so we'll push forward.

**Comment by fazzy12** [comment]
I apologize, I didn't mean to ignore you. I didn't just tract the
issue properly. Please can I pick another issue later, because I am not
kind of disposed at the moment.
i apologize once more, hope i get accepted to work on another issue?
