### ISSUE TITLE
[Docs] List name of model category in related section

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10867]
### Desired State
<img width="709" alt="Screenshot 2024-05-04 at 9 42 01 AM" src="https://github.com/meshery/meshery/assets/7570704/5eded4d9-235f-4478-98ec-13b3adf8338b">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by BarryByte** [comment]
@leecalcote Do we have to make the changes in the same line as the services is mentioned ?

And please confirm services and category names would be like this ...


- Azure Active Directory (AAD): Identity and Access Management
- Epam Delivery Platform (EDP) Admin Console: DevOps
- AMD GPU: Hardware
- Apisix: API Management
- Athenz: Security
- AWS Application Autoscaling: Cloud Services
- AWS Elastic Container Registry: Cloud Services
- AWS Elastic Container Service: Cloud Services
- AWS MemoryDB for Redis: Cloud Services
- AWS Node Termination Handler: Cloud Services
- Amazon Web Services (AWS): Cloud Services

**Comment by leecalcote** [comment]
Thanks for asking. This issue has been addressed. You can find the answers to your question and the current implementation.
