### ISSUE TITLE
[Docs] Need single line display of <code>

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10863]
### Current State
Some pages in Meshery Docs display an overly large, multi-line terminal only to show a single line command. Example: https://docs.meshery.io/installation/docker/docker-extension

<img width="920" alt="Screenshot 2024-05-03 at 3 54 24 PM" src="https://github.com/meshery/meshery/assets/7570704/a900ec01-65f6-4825-b709-5cca74dc6244">

### Desired State

1. Display these steps using the following code:
```
{% capture code_content %}RELACE ME. SPECIFIC COMMANDS GO HERE{% endcapture %}
{% include code.html code=code_content %}
```

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aryakoste** [comment]
Hello @leecalcote I would like to work on this issue.

**Comment by leecalcote** [comment]
Thank you, @Aryakoste
