### ISSUE TITLE
[mesheryctl] `registry publish` panic: interface conversion: error is *json.SyntaxError, not *errors.Error

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10875]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
With $CRED env var populated with token, `mesheryctl registry publish website $CRED 1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw` results in a panic.

### Screenshots/Logs
```
$ mesheryctl registry publish website $CRED 1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw docs/pages/integrations docs/assets/img/integrations -o md
panic: interface conversion: error is *json.SyntaxError, not *errors.Error

goroutine 1 [running]:
github.com/layer5io/meshkit/errors.GetCode({0x4eb8ae8?, 0xc000ab24c8?})
	github.com/layer5io/meshkit@v0.7.25/errors/errors.go:105 +0x7e
github.com/layer5io/meshkit/logger.(*Logger).Error(0xc000ab5938, {0x4eb8ae8, 0xc000ab24c8})
	github.com/layer5io/meshkit@v0.7.25/logger/logger.go:75 +0xc5
github.com/layer5io/meshery/mesheryctl/internal/cli/root/registry.init.func1(0xc000abb400?, {0xc0002ed490?, 0x4?, 0x4122a28?})
	github.com/layer5io/meshery/mesheryctl/internal/cli/root/registry/publish.go:96 +0x3ca
github.com/spf13/cobra.(*Command).execute(0x68446e0, {0xc0002ed420, 0x7, 0x7})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x683f660)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
	github.com/layer5io/meshery/mesheryctl/internal/cli/root/root.go:84 +0x45
main.main()
	github.com/layer5io/meshery/mesheryctl/cmd/mesheryctl/main.go:26 +0x13
```

### Environment

- Host OS: Mac 
- Meshery Client Version: stable-v0.7.53

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Jougan-0** [comment]
The issue is the $CRED env it should be populated by base64 value of google service account @leecalcote

**Comment by Jougan-0** [comment]
https://github.com/meshery/meshkit/pull/496
