### ISSUE TITLE
Remove the version toggler

### ISSUE THREAD

**Issue by iArchitSharma** [meshery/meshery#10885]
The version toggler no longer works because we have disabled it in the configuration. Therefore, the toggler button should also be removed or commented out.

### Current State
![image](https://github.com/meshery/meshery/assets/74408634/742396a6-e81e-4ce9-8e19-719bb37d3e45)

### Desired State
![image](https://github.com/meshery/meshery/assets/74408634/2fc240bf-1720-4936-99dc-a79f542eae9d)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by nikzayn** [comment]
@iArchitSharma Shall, I take this up?

**Comment by leecalcote** [comment]
@iArchitSharma, perhaps, there's some confusion here. We _do_ desire this version selector.
