### ISSUE TITLE
[Docs] Reduce font size in Meshery REST API page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10900]
### Current State
https://docs.meshery.io/reference/rest-apis uses overly large font sizes

<img width="1065" alt="Screenshot 2024-05-08 at 12 26 26 PM" src="https://github.com/meshery/meshery/assets/7570704/b9408522-bda6-4380-b099-e9ea0e9cf25e">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by jasonmokk** [comment]
Hi @leecalcote, can I work on this issue?

**Comment by leecalcote** [comment]
Sounds good. Thank you, @jasonmokk 👍
