### ISSUE TITLE
[Provider UI] Broken Meshery logo image

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10938]
@nebula-aac  there is a recently merged [PR #10919](https://github.com/meshery/meshery/pull/10919) on Provider UI that appears fine on the surface, but produces a broken image link. I’m wonder in you can help correct this. @dragon-slayer875  or you?

<img width="1237" alt="Screenshot 2024-05-13 at 3 13 17 PM" src="https://github.com/meshery/meshery/assets/7570704/25258377-b1db-4272-b162-34140295cd5d">

[Slack Message](https://layer5io.slack.com/archives/C023QGMSH8D/p1715631262031069?thread_ts=1715631262.031069&cid=C023QGMSH8D)

**Comment by dragon-slayer875** [comment]
Yes I will take this up.
Was about to raise a issue on it myself.
