### ISSUE TITLE
[Docs] Replace `mesheryctl app` and `onboard` commands

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10951]
### Current State
The Meshery [Catalog concept page](https://docs.meshery.io/concepts/catalog) lists an antiquated `mesheryctl` command:

> [Onboarding](https://docs.meshery.io/concepts/managing-applications-through-meshery-cli) an application. mesheryctl app onboard -f [file-path]

### Desired State

The `mesheryctl design` command should be listed.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by singh1203** [comment]
@leecalcote These changes align well with this pending PR #10603 
Thank you!
