### ISSUE TITLE
[mesheryctl] Issue Converting Helm Chart to Kubernetes Manifest when Importing Design via URL

### ISSUE THREAD

**Issue by singh1203** [meshery/meshery#10960]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

The error occurs importing design patterns via URL with `mesheryctl pattern import`. The issue arises during Helm Chart to Kubernetes Manifest conversion. Importing succeeds with local files.

File link: https://raw.githubusercontent.com/meshery/meshery.io/master/catalog/c40ae08b-deaa-4fc5-a1e8-8081907b64a3.yaml
### Screenshots/Logs

![Screenshot from 2024-05-15 11-32-33](https://github.com/meshery/meshery/assets/72030498/b2b454e8-67e9-41aa-9ef2-db5a1c6b4353)

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by singh1203** [comment]
@MUzairS15

**Comment by MUzairS15** [comment]
Add links/files that you are trying with.

**Comment by singh1203** [comment]
> Add links/files that you are trying with.

Added to the description.

**Comment by lekaf974** [comment]
@singh1203 I tested this issue and have the same behavior

**Comment by lekaf974** [comment]
After dig in it seems the server only return error 500 will continue investigate and grab more details to see if I could make a fix so that mesheryctl display an error more useful for end user

**Comment by MUzairS15** [comment]
@saurabh100ni You are using a design file but specifying helm as source type in imports.

**Comment by MUzairS15** [comment]
So @lekaf974 the issue is that meshsryctl is not handling sourcetype flag correctly. 
On local file import if source type specified is helm even then it should fail as we have provided a design file.

will you ensure source type is used correctly.

If source type is other than helm supported options are local imports and remote url imports.

otherwise for helm only remote url imports and if loval file ref is provided it should give appropriate error.

**Comment by MUzairS15** [comment]
As a next iteration we can support importing helm charts from local files with mesheryctl.
