### ISSUE TITLE
Create a Tutorial on how to get the first helm chart import into Meshery [Docs]

### ISSUE THREAD

**Issue by iArchitSharma** [meshery/meshery#10975]
### Current State
Meshery Docs are in need of new tutorials. In this tutorial, we will explore how to get the first helm chart import into Meshery. Meshery is a powerful tool that simplifies the adoption and operation of cloud and cloud native technologies. Meshery Playground provides a safe and isolated environment for learning and experimenting with these technologies.

### Desired State
The tutorial will go under tutorial section of Meshery docs
![image](https://github.com/meshery/meshery/assets/74408634/4c05ae77-621c-48c8-bbcb-54dbf36ea54a)

You can take our others tutorials as a reference here - https://docs.meshery.io/guides/tutorials

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Are you writing this, @iArchitSharma or is it missing a help wanted label? Missing standard issue description template.

**Comment by iArchitSharma** [comment]
updated*
