### ISSUE TITLE
Add ability to select namespace while deploying

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#10971]
### Current Behavior
While deploying a design, in the deployment modal we don't have the ability to allow users to select the namespace.

### Desired Behavior
Add ability allowing users to select namespace while deploying a design. 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@ritiksaxena124 the completion of the draft mockup is needed.

**Comment by leecalcote** [comment]
Competed and released.
