### ISSUE TITLE
[Docs] Eliminate duplication of tutorial listings

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10978]
### Current State
There is duplication between hands on labs section and the tutorials section on the docs homepage.

<img width="656" alt="Screenshot 2024-05-16 at 11 57 29 AM" src="https://github.com/meshery/meshery/assets/7570704/95e43ca2-c50a-454f-a543-3dc60cbfd457">

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Deepak0320Singhal** [comment]
Hey @leecalcote I would  like to work on this issue, can you please assign this issue to me.

**Comment by vishalvivekm** [comment]
## 🧑‍🔬 Hands-on Labs using Meshery Playground

**Comment by vishalvivekm** [comment]
> Hey @leecalcote I would like to work on this issue, can you please assign this issue to me.

Hi @Deepak0320Singhal, do you mind taking a look at this issue : https://github.com/meshery/meshery.io/issues/1744
