### ISSUE TITLE
[Docs] 404 Page not found error on changing version from latest > v0.6

### ISSUE THREAD

**Issue by anushas-dev** [meshery/meshery#10996]
### Current State:
https://docs.meshery.io/v0.6 - Says Page not found

### Desired State:
https://docs.meshery.io/v0.6 - Should contain docs relevant for v0.6 or selected release tag

<img width="1419" alt="Screenshot 2024-05-14 at 9 07 43 PM" src="https://github.com/meshery/meshery.io/assets/95580494/341e3808-b630-4a74-89db-bfd622280ba7">

**Comment by vishalvivekm** [comment]
@anushas-dev 
Thank you for reporting the issue.
On upcoming websites meeting on Monday, 5:30 PM IST ( https://meet.layer5.io/websites), a call for volunteers will be made to fix the bug.
Here's the meeting minutes: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#

**Comment by ashparshp1** [comment]
@vishalvivekm, Is it valid one or we can close it?

**Comment by Ashparshp** [comment]
@vishalvivekm, Is it valid one or we can close it?

**Comment by anushas-dev** [comment]
I can confirm this issue is resolved, I see version specific documentation now. 
thank you
apologies on late response
