### ISSUE TITLE
[Server] Extensions: API Support for proxying feedback/help requests

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11019]
Will you add an API in meshery server that proxies this support request to remote provider and then the provider (in the backend) handles this?

_Originally posted by @MUzairS15 in https://github.com/meshery/meshery/pull/11004#discussion_r1609860661_

**Comment by leecalcote** [comment]
@MUzairS15 is this need not covered by a wildcard after `/api/provider/extension/`?

**Comment by MUzairS15** [comment]
@leecalcote We are covered here, we already have a proxy handler.

**Comment by leecalcote** [comment]
Thank you, sir. For my own reference, is this covered under a wildcard or is this explicitly defined?
