### ISSUE TITLE
[Extensions] Remote Provider Preferences: "Pen" listed twice

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11010]
### Current Behavior
<img width="1182" alt="Screenshot 2024-05-21 at 6 53 10 PM" src="https://github.com/meshery/meshery/assets/7570704/45dd765c-c1a7-4b93-a84e-92d7c0352fbd">

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by himanshujaidka** [comment]
Hello @leecalcote kindly provide me access for the MeshMap extension so that I can detect this bug and start working on it
