### ISSUE TITLE
[CI] Label Commenter: Update UI label comment to point to new ui-test Meshery Docs page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11029]
### Current Behavior
A workflow for commenting based on label point to an old Meshery Docs page for e2e testing with Cypress.

See [example comment ](https://github.com/meshery/meshery/issues/11028#issuecomment-2127808680).

### Desired Behavior
Swap the hyperlink with the new Playwright page - https://docs.meshery.io/project/contributing/contributing-ui-tests

### Implementation
1. Update github workflow for label commenter config.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by krishantt** [comment]
Hey @leecalcote, I would like to work on this. Simply changing `.github/label-commenter-config.yml` might do the trick.
