### ISSUE TITLE
[Server] Design Import: Use filename as design name 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11026]
### Current Behavior
During design import (of any supported file type), when no name for the design is provided, "Autogenerated" is used as the design name.

### Expected Behavior
Using the filename of as the Design name is more descriptive and helpful.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by dusdjhyeon** [comment]
I'd like to work on this Issue!

**Comment by leecalcote** [comment]
Thank you, @dusdjhyeon 👍
