### ISSUE TITLE
[UI] Dashboard: Kubernetes data tables misaligned

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11032]
### Current Behavior
See any of the Kubernetes dashboards. Notice the data tables are ill-formatted.

e.g. https://playground.meshery.io/?resourceCategory=Network&resource=Ingress

### Screenshots/Logs
<img width="1430" alt="Screenshot 2024-05-23 at 5 10 20 PM" src="https://github.com/meshery/meshery/assets/7570704/f472c96f-19f5-414a-b62f-023e9fd698c9">

### Environment

- Browser: Safari
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.63

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Faisal-imtiyaz123** [comment]
@leecalcote  I want to work on this.

**Comment by Faisal-imtiyaz123** [comment]
I checked it. The formatting is correct.

**Comment by Faisal-imtiyaz123** [comment]
@aabidsofi19 I checked the table alignment. It is correct. Can u verify plz?

**Comment by aabidsofi19** [comment]
as you can see in the picture , the coloumns are not rendered properly which causes misalignment of data

**Comment by Faisal-imtiyaz123** [comment]
![Uploading Screenshot 2024-05-31 at 5.02.30 PM.png…]()

**Comment by Faisal-imtiyaz123** [comment]
<img width="1060" alt="Screenshot 2024-05-31 at 4 54 50 PM" src="https://github.com/meshery/meshery/assets/142205282/ef8be3a3-efd7-4bee-bd99-7d9706e82d06">

**Comment by Faisal-imtiyaz123** [comment]
As you can see @aabidsofi19 it is fine.

**Comment by aabidsofi19** [comment]
the issues happens on size > 1550   
![image](https://github.com/meshery/meshery/assets/65964225/50c7f450-500d-4f49-9fd4-762de1e59cce)

**Comment by leecalcote** [comment]
“As you can see”, @Faisal-imtiyaz123, it’s not fine.

**Comment by lovishduggal** [comment]
@leecalcote: May I take on the task related to this issue?"
