### ISSUE TITLE
[UI] Bifurcation of Actions button (model-click vs single-click)

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11055]
### Current Behavior
@dragon-slayer875 please verify whether this is a duplicate or not.

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by akshansh-modi** [comment]
I'm interested in working on this issue.

**Comment by sudhanshutech** [comment]
@dragon-slayer875 confirm please is this was completed?

**Comment by leecalcote** [comment]
@dragon-slayer875 is this complete?
