### ISSUE TITLE
[UI]Connections page has no information listed.

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11105]
### Current Behavior
![Screenshot from 2024-06-04 15-49-24](https://github.com/meshery/meshery/assets/99207534/91c97d6e-d123-4e8b-992d-89179cec9160)
Empty connections page.
### Desired Behavior
All connections should be listed here.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by yash37158** [comment]
@Jougan-0 Are the Meshery Operator and MeshSync components healthy?

**Comment by Jougan-0** [comment]
Yes, have a look at the playground meshery.

**Comment by yash37158** [comment]
![Screenshot 2024-06-05 at 3 02 53 AM](https://github.com/meshery/meshery/assets/68152307/ac988241-2de4-4ae4-9f04-9649c544ad74)

@Jougan-0 As I can check, I am able to access the connections.

**Comment by Jougan-0** [comment]
It's fixed.
