### ISSUE TITLE
While we deploy helm chart for KEDA through meshery UI this error event is sent.

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11104]
###Current behaviour 
![image](https://github.com/meshery/meshery/assets/99207534/7e42d32f-6a21-4544-88b6-6fb3fb49db7a)[Slack Message]
How old are MeshKit’s k8s libraries, I wonder?
(https://layer5io.slack.com/archives/CFGG6U10E/p1717455689361619?thread_ts=1717455689.361619&cid=CFGG6U10E)
###Desired behaviour 
Should be deployed.
[Screencast from 2024-06-04 15-46-36.webm](https://github.com/meshery/meshery/assets/99207534/e634f5fa-14e2-4042-a095-d040c4def472)

**Comment by Jougan-0** [comment]
@sangramrath Here  you go.

**Comment by Jougan-0** [comment]
The current Kubernetes version
```oot@c3-medium-x86-01-meshery:~# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by MUzairS15** [comment]
@Jougan-0 this is fixed by the pr in meshkit

**Comment by Jougan-0** [comment]
Closing this issue @MUzairS15.
PR Merged.
