### ISSUE TITLE
[Models] Split out relationships into indivitual files and respective model folders.

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11123]
### Current Situation

Currently, in the Meshery repository under the ```server/meshmodel``` directory, relationships between models are defined within the ```relationship.json``` file. This file contains all relationships in a centralized manner, which can make it challenging to manage and update specific relationships effectively.

### Proposed Change

To improve maintainability and clarity, it is proposed to split the data in ```relationship.json``` based on selectors and place them within their respective model folders.

---

### General Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Understanding Meshery Models

- 🖥 [Models Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 👨‍💻[Models Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)

### Contributing to Meshery Models

- https://docs.meshery.io/project/contributing/contributing-models

### Contributing to Meshery Relationships

- https://docs.meshery.io/project/contributing/contributing-relationships

  Review a prior pull request as an example of how to define a Relationships:   https://github.com/meshery/meshery/pull/9880/files

**Comment by leecalcote** [comment]
@Jougan-0 while doing this, you'll want to confirm that the internal generator/registrar is capable of sourcing relationships from any model (not just kubernetes).

**Comment by leecalcote** [comment]
Confirming: yes, it is.
