### ISSUE TITLE
[Server] Request for adding POST Capability to /api/events/

### ISSUE THREAD

**Issue by dragon-slayer875** [meshery/meshery#11120]
### Current Behavior

- Notifications in meshery's notificaiton center are generated as events from the server.
- The current /api/events/ REST API endpoint only supports the GET method. 
- There is no way to send UI-generated events to the Meshery notification center.

### Desired Behavior

There is a need for the support of the POST method for the same, as it will allow developers to send UI-generated events to the notification center through the server. 

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by dragon-slayer875** [comment]
// @leecalcote

**Comment by boku13** [comment]
hello @leecalcote, I think I can make this enhancement. Could you please assign me to this issue? :D

**Comment by leecalcote** [comment]
Thanks for asking, @boku13. @dragon-slayer875 is a good one to ask this question of. Responding on his behalf, I'll ask you to confirm 1) that you've built Meshery Server and UI, are able to run them locally and 2) share your proposed approach here.

**Comment by dragon-slayer875** [comment]
Hello @boku13. 
Please do answer Lee's questions so that we know that you can jump right into the task and if need help with your approach to prevent loss of effort. :smile:

**Comment by dragon-slayer875** [comment]
// @MUzairS15

**Comment by boku13** [comment]
hello, @dragon-slayer875
A) I've built both the UI and server on gitpod and have a working dev environment right now.
B) 1) As for the approach, it would be to edit the file at [handlers](https://github.com/meshery/meshery/tree/master/server/handlers)
/events_streamer.go to add a handler for the POST request with a signature similar to this : `func (h *Handler) CreateEvent(w http.ResponseWriter, req *http.Request, prefObj *models.Preference, user *models.User, provider models.Provider) {}`
3) Read the request body, create an `Event` object from it ( if it's an event already, then validate the body and build the object). 
4) Persist the event to store it in the database, and publish the event through the `EventBroadcaster` to a new goroutine.
5) I would then have to update the router with this new method, along with the documentation in a couple of places.

One thing I haven't yet figured out is where the changes on the client side would be, if at all.

**Comment by MUzairS15** [comment]
Perfect @boku13

**Comment by dragon-slayer875** [comment]
@boku13 Checking in.
Any progress?
We encourage you to communicate frequently so we can point out any mistakes along the way. :smile:

**Comment by boku13** [comment]
@dragon-slayer875 Will make a PR within 24 hours at the latest, I'm sorry for the wait. 

I'm almost done though, I've been taking things at a slower pace to better understand Meshery's architecture. I'll try to pick up the pace in my upcoming contributions. Sorry for the trouble 🙇
