### ISSUE TITLE
[UI] Filter fetching fails with 500 internal server error in local instance

### ISSUE THREAD

**Issue by DevRish** [meshery/meshery#11122]
### Current Behavior

On navigating to `Configuration > Filters` (or visiting `http://localhost:9081/configuration/filters` directly), the `GET` request sent to `http://localhost:9081/api/filter` for fetching existing filters fails with status code `500` with the response body as `strconv.ParseUint: parsing "undefined": invalid syntax`.

On uploading new filters they don’t appear in the table, even after refreshing the page, probably due to the same failing `GET` requests, which are unable to fetch the filters.

On examining the request it can be observed that `pagesize=undefined` is sent in the request query, which is expected to be a number. This might be causing the issue.

### Desired Behavior

Filters get fetched successfully on first render of the page and get re-fetched on importing new filters

### Screenshots/Logs

![filter_fetching_error](https://github.com/meshery/meshery/assets/78094670/39ec7b0f-903e-45c8-b9d1-55187e670f06)

### Environment

- Browser: Chrome
- Host OS: Linux
- Platform: Local
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aviral0702** [comment]
On reproducing the same I am not getting any errors and I tried to import a filter and on refreshing the page I got the new filter on the very first place of the list. Also it got deleted the second I clicked the unpublish button. Is this issue resolved ?

**Comment by DevRish** [comment]
@Aviral0702 On using the `Meshery` provider it is no longer happening and has been resolved. However, I am still getting this issue on using the `None` provider.

**Comment by Aviral0702** [comment]
Oh ok got it!

**Comment by Aviral0702** [comment]
Got it! Thanks
