### ISSUE TITLE
Update playground docker image in kubernetes deployment

### ISSUE THREAD

**Issue by milinddethe15** [meshery/meshery#11149]
### Current Behavior

https://github.com/meshery/meshery/blob/5ac5f4444b488544d3f4952897896b8d19f220c0/install/playground/kubernetes/meshery-playground-deployment.yaml#L29
Currently `layer5/meshery:playground-v0.6.35` image is used i.e. not latest for playgroundf deployment in k8s.
### Expected Behavior

Always latest version of playground should be installed.
By using `layer5/meshery:playground-latest` image this can be solved.
### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by deepak4566** [comment]
Hey  @milinddethe15 if know there is a practise in writing kuberentes manifests, that we shouldn't use latest tag , there are many reasons for it ,and i believe tags are for humans , you can always check this blog to learn more https://medium.com/@michael.vittrup.larsen/why-we-should-use-latest-tag-on-container-images-fc0266877ab5

**Comment by milinddethe15** [comment]
@deepak4566 Thanks for your reply. Didn't know about this.
