### ISSUE TITLE
[Docs] Broken link in mesheryctl installation minikube

### ISSUE THREAD

**Issue by lekaf974** [meshery/meshery#11169]
### Current State

While I was trying to read the installation steps https://docs.meshery.io/installation/kubernetes/minikube#installation-using-helm

I found that the link provided  is not working

![image](https://github.com/meshery/meshery/assets/6630779/59eb31e3-92a9-40c9-a48f-cb641f65229d)

Clicking result on 404 error

![image](https://github.com/meshery/meshery/assets/6630779/dc8d187a-5e86-426c-a138-5319e2f5399b)

### Desired State

The link provided should target the right resource
Current target: https://docs.meshery.io/installation/helm 
Should be: https://docs.meshery.io/installation/kubernetes/helm

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by csengineer1990** [comment]
Hi @lekaf974 I am new here and I think I can work on this issue with your guidance.

Could you please assign me to this issue?

**Comment by deepak4566** [comment]
Here you go @csengineer1990

**Comment by Aviral0702** [comment]
Can I work on this issue.

**Comment by MiirzaBaig** [comment]
Hi folks!
If the issue hasn't resolved, I'll give it a try in my free time then!!!
