### ISSUE TITLE
[CI] Edge releases are not getting deployed to `staging-playground`.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#11174]
### Current Behavior

The workflow for deploying edge releases on staging-playground.meshery.io is deploying stable releases.
<img width="1440" alt="Screenshot 2024-06-13 at 8 37 25 PM" src="https://github.com/meshery/meshery/assets/79860504/420a35b9-1ec1-4a3d-9e3f-fce8229e29a0">

### Desired Behavior

Ensure workflow deploys edge releases in the staging playground.
### Implementation

Switch the `channel` for `mesheryctl` from `stable to edge`.
### Acceptance Tests

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by cpepper96** [comment]
@MUzairS15 After looking into this, my suggestion would be to run `mesheryctl system channel set edge` on the staging cluster to update the current context rather than create a new context. If that sounds good I can do that if you grant me access.

**Comment by MUzairS15** [comment]
Yes @cpepper96, it can be done inside the workflow as well.
Or is there any issue doing in the workflow?

**Comment by cpepper96** [comment]
@MUzairS15 No issue with running it in the workflow... Actually I'm going to add it to the workflow so we can insure that each time the workflow is ran we are updating from `edge`.
