### ISSUE TITLE
[Extensions] Catalog: Invalid content count in filters and chart

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11184]
### Current Behavior

Both of these encircled components are missing data.
![Screenshot 2024-06-14 at 5 51 50 PM](https://github.com/meshery/meshery/assets/7570704/80cf67bb-cfc0-4829-8a07-8e82d1076e04)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
This issue is fixed now
