### ISSUE TITLE
[Docs] Uprading meshery CLI page not available

### ISSUE THREAD

**Issue by Aviral0702** [meshery/meshery#11206]
### Current State

Link for the webpage: https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli

![image](https://github.com/meshery/meshery/assets/134831178/bb97bbe8-68dd-4d36-bb39-392c9b33bd10)

### Desired State
Clicking on upgrading meshery cli should lead to a page containing steps and docs for upgrading meshery cli
 
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sangramrath** [comment]
@Aviral0702 "Clicking on upgrading meshery cli" from which page gives the 404? 

The page has moved to https://docs.meshery.io/installation/upgrades#upgrading-meshery-cli so this can be updated based on where the error is from.

**Comment by leecalcote** [comment]
The redirect_from can be used.

**Comment by singh1203** [comment]
@Aviral0702 Please provide the progress regarding this issue.

**Comment by singh1203** [comment]
> @singh1203 Yes the PR you provided solves this issue. Should I close this issue ?

Thank you @Aviral0702 Go ahead!
