### ISSUE TITLE
[Docs] Extension points link not working on FAQs Page

### ISSUE THREAD

**Issue by Aviral0702** [meshery/meshery#11207]
### Current State
The link attached to **extension points** is not working.

![image](https://github.com/meshery/meshery/assets/134831178/3d71f294-de0c-4562-9342-6c768579a8e9)

![image](https://github.com/meshery/meshery/assets/134831178/38616fd8-bb60-4013-a229-760e9ff7ee71)

![image](https://github.com/meshery/meshery/assets/134831178/4ce9878d-4ca8-4141-9b44-a9e19ebf2b4a)

How to reproduce:
1) [Go to https://docs.meshery.io/project/faq](https://docs.meshery.io/project/faq)
2) Go to FAQ section 
3) Click on the FAQ accordion tab which says "Why should I use Meshery?"

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sangramrath** [comment]
I assume it should now point to https://docs.meshery.io/extensions/. May be the core team can confirm this.

**Comment by leecalcote** [comment]
@sangramrath is right. 👍

**Comment by leecalcote** [comment]
@Aviral0702 there is no FAQs link on the docs.meshery.io/projects page.

**Comment by leecalcote** [comment]
> @leecalcote We can find the FAQ section under Overview and Installation tab on the sidebar Sir.

I see. The navigation sidebar has nothing to do with the specific page that you originally linked to.

**Comment by leecalcote** [comment]
Excellent! 😃 No sweat. 👍
