### ISSUE TITLE
[Docs] Link on FAQs Page not working. 

### ISSUE THREAD

**Issue by Aviral0702** [meshery/meshery#11203]
### Current State
In the subtopic of **How do I install Meshery?** there is a link attached to "number of platforms". Clicking on the link redirects  you to a Page which says "Page not found".

![image](https://github.com/meshery/meshery/assets/134831178/62af4fcf-dd96-44e4-b35d-be2bb300aca3)

![image](https://github.com/meshery/meshery/assets/134831178/b3b7b933-dbcf-4a4e-90fb-d5dcbab55036)

### Desired State
The desired link should be updated in the docs codebase or if there is no desired link it should be updated.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thanks!
