### ISSUE TITLE
[UI] Expose Registry-Logs to UI>Setting>Registry.

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11208]
### Current Behavior

There is no page to show the error logs in UI.
### Desired Behavior

In setting page under Registry expose logs.
Logs can be found under.
```./meshery/logs```

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Jougan-0** [comment]
I've assigned this task to you. Please ask any questions you might have, and let's work together to complete this PR quickly, as it will greatly benefit other contributors and users.

**Comment by Muhammed-Moinuddin** [comment]
Thanks, let's discuss this on slack

**Comment by Jougan-0** [comment]
> Thanks, let's discuss this on slack

Sure ping me whenever you are free.
