### ISSUE TITLE
[Docs] Integrations: Don't display "Components" section if no components are available

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11212]
### Current State

An empty Components section is displayed:

<img width="793" alt="Screenshot 2024-06-19 at 11 15 11 AM" src="https://github.com/meshery/meshery/assets/7570704/c5e056ce-9190-46ed-b40a-4ed1f97f41db">

Example page - https://docs.meshery.io/extensibility/integrations/artifact-hub

This logic isn't working - https://github.com/meshery/meshery/blob/master/docs/_layouts/integration.html#L11

### Desired State

If an integration doesn't have any components, don't show the component section.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@vishalvivekm [bug](https://github.com/meshery/meshery/blob/master/docs/_layouts/integration.html#L11)?

**Comment by Paras-245** [comment]
could i give a shot?
