### ISSUE TITLE
[UI] Failing Meshery UI ESLint in workflow

### ISSUE THREAD

**Issue by singh1203** [meshery/meshery#11226]
### Current Behavior

Meshery UI ESLint check is failing in workflow [here](https://github.com/meshery/meshery/actions/runs/9598756109/job/26470867475?pr=11217#step:3:36), it needed an audit for unused variable, looking at the log's [here]
### Desired Behavior

Make changes to remove unused variables and audit the package as well.
### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by dottharun** [comment]
fixed by #11228
