### ISSUE TITLE
[Models] Make Edge netwrok relationship Generic 

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11222]
### Current Situation

The relationship of kind edge and type network is rego policy evaluation should be  made generic and it is specific to Kubernetes model and it should not be.
![Screenshot from 2024-06-21 04-21-49](https://github.com/meshery/meshery/assets/99207534/d80d65a6-b203-437d-8e4e-6ec3680773de)

### Proposed Change

---

### General Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Understanding Meshery Models

- 🖥 [Models Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 👨‍💻[Models Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)

### Contributing to Meshery Models

- https://docs.meshery.io/project/contributing/contributing-models

### Contributing to Meshery Relationships

- https://docs.meshery.io/project/contributing/contributing-relationships

  Review a prior pull request as an example of how to define a Relationships:   https://github.com/meshery/meshery/pull/9880/files

**Comment by MUzairS15** [comment]
This has been addressed in the v1beta1 migration.
