### ISSUE TITLE
[Docs] Step to set up environment variables missing in the docs for contributing to end-to-end playwright tests

### ISSUE THREAD

**Issue by DevRish** [meshery/meshery#11230]
### Current State

The Meshery Docs Page for [Contributing to Meshery's End-to-End Tests using Playwright](https://docs.meshery.io/project/contributing/contributing-ui-tests) does not include the step to set the required environment variables before running the tests.

The environment variables required for the tests to run can be found in [this](https://github.com/meshery/meshery/blob/master/ui/tests/e2e/env.js) file. Presently, we compulsorily need these three variables to be set for the tests to run properly: 

- `REMOTE_PROVIDER_USER_EMAIL`: The user's layer5 account email 
- `REMOTE_PROVIDER_USER_PASSWORD` : The user's layer5 account password
- `PROVIDER_TOKEN`: A provider token for the user, that can be generated from [here](https://meshery.layer5.io/security/tokens)

For running the tests locally, one can use their own layer5 account credentials in the environment variables.

### Desired State

Add a step in the Meshery Docs page for contributing to end-to-end playwright tests, for setting required environment variables in the terminal (temporarily or permanently) before running the tests locally.

For Linux based environments, they can be temporarily set using the `export` command:
```bash
export REMOTE_PROVIDER_USER_EMAIL=<layer5 account email>
export REMOTE_PROVIDER_USER_PASSWORD=<layer5 account password>
export PROVIDER_TOKEN=<provider token>
```
Or, they can be permanently set in the `~/.bashrc` file

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by aayushdhiman01** [comment]
@DevRish can i work on this?

**Comment by shubhusion** [comment]
@DevRish please assign this issue to me
