### ISSUE TITLE
[Docs] Upgrading Meshery CLI is in a 404 state. 

### ISSUE THREAD

**Issue by dusdjhyeon** [meshery/meshery#11249]
### Current State
The Upgrading Meshery CLI, which is often mentioned in Related Reading, is in a 404 state. 
https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli

### Desired State
Load the page from the correct path. 

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by STAR-173** [comment]
Hey @dusdjhyeon,
Just looked through the code-base. It seems like it is nowhere mentioned in the docs but a few internal methods where it is getting printed when an error occured. 
Will push a PR soon regrading this

**Comment by dusdjhyeon** [comment]
> Hey @dusdjhyeon, Just looked through the code-base. It seems like it is nowhere mentioned in the docs but a few internal methods where it is getting printed when an error occured. If you have found this link in any docs, can you share it ?

https://docs.meshery.io/installation/mesheryctl
In here, we can see `Upgrading Meshery CLI` in Meshery CLI Guides
