### ISSUE TITLE
[mesheryctl] Panic error while running `mesheryctl filter list`

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11247]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
When we run `mesheryctl filter list` it returns a panic error instead of data.

![image](https://github.com/meshery/meshery/assets/99207534/38767774-4aa3-4f4b-8ab2-26deefc9fd40)

### Desired Behavior
It should return list of filters.

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Touriist** [comment]
@Jougan-0 I wanna work on this.

**Comment by Jougan-0** [comment]
> @Jougan-0 I wanna work on this.
Great, there are a couple of questions that would help me confirm we're on the same page:

1. Were you able to build and run Meshery locally?
2. Were you able to run mesheryctl locally?

**Comment by Touriist** [comment]
Hey @Jougan-0,
I have now mesheryctl running on my laptop.

Can I take other issues ?

**Comment by Jougan-0** [comment]
> Hey @Jougan-0, I have now mesheryctl running on my laptop.
> 
> Can I take other issues ?

That's great, if you find any other `mesheryctl` open issue ping me. I'll assign it to you.

**Comment by Touriist** [comment]
> > Hey @Jougan-0, I have now mesheryctl running on my laptop.
> > Can I take other issues ?
> 
> That's great, if you find any other `mesheryctl` open issue ping me. I'll assign it to you. I have noted that you can now fix mesheryctl issue's I'll ping you if I find one. In the meantime you can explore different commands.

Thank you.
I found one open and commented https://github.com/meshery/meshery/issues/11305#issuecomment-2206021972
