### ISSUE TITLE
[mesheryctl] New command `model export`

### ISSUE THREAD

**Issue by singh1203** [meshery/meshery#11252]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Desired Behavior

Develop a new subcommand `export` for `mesheryctl model` to export the model in OCI-compatible(tar.gz).

Refer to the documentation for [Models](https://docs.meshery.io/concepts/logical/models) and for architecture this [slide page](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g2b57e113ee8_3_68) gives high-level overview.

### Implementation

- [ ] Implement command to export selected Model 
- [ ] Develop comprehensive test cases to validate the functionality of the `model export`
### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ayushrakesh** [comment]
@singh1203 can you help, any resources, or how to go forward on this issue?

**Comment by singh1203** [comment]
This issue is already being tracked by #10165 hence closing this issue.
