### ISSUE TITLE
[mesheryctl] Rename `mesh` command to `adapter`

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11305]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
`mesheryctl mesh` is a command for interfacing with Meshery's adapters. Meshery's adapter vary in capability, extending Meshery's functionality and management reach. Adapters are a functionality agnostic extension point in Meshery and shouldn't be characterized by the word `mesh`.

### Desired Behavior
Rename the `mesh` command to `adapter`

### Acceptance Tests
1. All Meshery Docs references to `mesh` updated.
2. Meshery Docs CLI Reference updated.

### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Touriist** [comment]
@leecalcote 
I set up mesheryctl locally.
Can I take this task ?

**Comment by Jougan-0** [comment]
Here you go.

**Comment by sudhanshutech** [comment]
@Touriist any updates here?
