### ISSUE TITLE
[UI] Add Tabindex to Create Workspace modal

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11302]
### Current Behavior

https://github.com/meshery/meshery/assets/7570704/f12851e5-86fc-4568-8e10-2766be0010cf

### Implementation

This behavior may need to be addressed inside of the Sistent component or it may need to be addressed universe inside of the associated RJSF UI schema.

### Acceptance Tests
Users can press their TAB key to move through fields sequentially, rolling over to the start when they reach the bottom.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Muhammed-Moinuddin** [comment]
@leecalcote kindly assign me to try it.

**Comment by leecalcote** [comment]
Thanks, @Muhammed-Moinuddin

**Comment by Aady7** [comment]
@leecalcote  would like to contribute in solving the issue.

**Comment by Ashparshp** [comment]
@Muhammed-Moinuddin Any updates?

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin Any updates?

Still Working...
Just messaged something related to this issue via slack as well. Kindly check it, maybe you can help with it.

**Comment by Ashparshp** [comment]
@Muhammed-Moinuddin Can you pin me in that?

**Comment by Muhammed-Moinuddin** [comment]
This issue also exist with Environment Creation pop-up

**Comment by UtkarshAhuja2003** [comment]
Hi @Muhammed-Moinuddin ,

Are you still working on this issue? If not, I’d like to fix it. Please let me know!

**Comment by Ashparshp** [comment]
@Muhammed-Moinuddin Any updates to share?

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin Any updates to share?

No Updates. I'll unassign myself as I won't be able to look into it till 20th. You can assign it to someone else.
I'll work on it later and If I'll find the problem, I'll share it.
Important to note that this issue lies with other Modals as well.

**Comment by UtkarshAhuja2003** [comment]
Hi @leecalcote, could you please assign this issue to me? I'd like to work on it.

**Comment by Ashparshp** [comment]
@UtkarshAhuja2003, Thanks..

**Comment by Ashparshp** [comment]
Have you finished setting up the repo, @UtkarshAhuja2003?

**Comment by UtkarshAhuja2003** [comment]
> Have you finished setting up the repo, @UtkarshAhuja2003?

Yes
