### ISSUE TITLE
[mesheryctl] `filter list` logs endpoint remove it.

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11315]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

When we run `mesheryctl filter list` a log line stating the endpoint that is hit remove it.
### Screenshots/Logs

``` 
 ./mesheryctl filter list
http://localhost:9081/api/filter?pagesize=25&page=0
```
### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aviral0702** [comment]
I would like to take up this issue.

**Comment by amanreddy77** [comment]
I can do this ....

**Comment by BarryByte** [comment]
please assign me this issue @Jougan-0

**Comment by Jougan-0** [comment]
I am afraid this is fixed. There is an open PR for this. Tag me on any other issue I'll assign it to you. @BarryByte
