### ISSUE TITLE
[mesheryctl] `filter delete` returns 500 server error

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11318]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

`mesheryctl filter delete [id]` does not work and returns 500 error.
### Screenshots/Logs

```
./mesheryctl filter delete 910ed6f8-8edb-4427-849b-6661c4d56da9
Error: failed to delete filter 910ed6f8-8edb-4427-849b-6661c4d56da9
See https://docs.meshery.io/reference/mesheryctl/filter/delete for usage details
: Response Status Code 500, possibly Server error
```
### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ayushrakesh** [comment]
@Jougan-0 Please assign this issue to me. I am interested to work.

**Comment by Jougan-0** [comment]
> @Jougan-0 Please assign this issue to me. I am interested to work.

Surely, could you confirm that if you have setup mesheryctl locally?

**Comment by ayushrakesh** [comment]
Yes I have mesheryctl up and running locally.

**Comment by Jougan-0** [comment]
Here you go.

**Comment by aryan-py** [comment]
I would love to tackle this issue

**Comment by Shridhar2104** [comment]
@Jougan-0 Is this issue resolved? I tried to replicate the issue but it seems to be working fine

**Comment by Jougan-0** [comment]
No this issue is not resolved. It seems to be an user.Id issue @Shridhar2104 please have a look if you would and update here.

**Comment by SYSHIL** [comment]
Hey @Jougan-0 could I please take this up as my first issue? Thanks !

**Comment by Jougan-0** [comment]
Yes here you go

**Comment by JianMinTang** [comment]
I found the reason for this issue. It's happening because you deleted a filter created by another developer, which caused the "Invalid authentication and session" error. Therefore, this command work fine.

**Comment by SYSHIL** [comment]
Thank you @JianMinTang I wasn't able to reproduce the same on my machine ):
