### ISSUE TITLE
[mesheryctl] `exp connections` needs update in Long and short description.

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11311]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
Currently the Short,Long and example are not appropriate. They don't make the command clear to the end user.
### Desired Behavior
The text inside the long, short and example should  be more user facing and helpful.
Update `docs/mesheryctlcommands/cmds.yml` as well for the commands.

### Screenshots/Logs

![Screenshot from 2024-07-03 20-39-31](https://github.com/meshery/meshery/assets/99207534/e1ec20b9-e1b0-4d12-8c3e-f94c9e5abc76)

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ayushrakesh** [comment]
@Jougan-0 Please assign this issue to me.

**Comment by Jougan-0** [comment]
Assigned you [this](https://github.com/meshery/meshery/issues/11318) issue once you complete that. I will assign you this one.

**Comment by ayushrakesh** [comment]
@Jougan-0 Okay.

**Comment by shishir-11** [comment]
I wanted to start contributing to meshery and hope to get started with this issue , where can i learn more about this so I can properly update it at the required places ?

**Comment by Jougan-0** [comment]
In the issue itself you can find guides and documentation that can get you started.

**Comment by Hackmey** [comment]
I would like to solve this issue. Can you assign me this.

**Comment by Jougan-0** [comment]
@Hackmey @shishir-11 have been able to setup mesheryctl locally?

**Comment by Hackmey** [comment]
Yes. The commands are running. But the system start says unable to deploy on Kubrenetes.
Is this considered to be set up locally.
Everyother commands are working fine.
@Jougan-0

**Comment by Jougan-0** [comment]
If @shishir-11 hasn't been able setup mesheryctl locally you can take the issue but we go in chronological order here.
You can ping me under any other issue I'll assign it to you.

**Comment by Hackmey** [comment]
Okay. @Jougan-0

**Comment by shishir-11** [comment]
I was trying to set up the local dev environment but was running into an error 
```
$ ./mesheryctl system start
Error: Get "https://kubernetes.docker.internal:6443/api/v1/pods": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes").
The Kubernetes cluster is not accessible. Please confirm that the token is valid. See https://docs.meshery.io/installation/quick-start for additional instructions
```
I'd appreciate if someone could help me out with it. I'm using kubernetes that comes with docker desktop. I am able to resolve the fiirst error by allowing unsigned tls access on local but second line still persists.

**Comment by rahulrana701** [comment]
hi @Jougan-0 I would like to take up this issue , could you please assign it to me

**Comment by shishir-11** [comment]
@rahulrana701 can you help me setup the repo locally if you know how to resolve the error ?

**Comment by rahulrana701** [comment]
> @rahulrana701 can you help me setup the repo locally if you know how to resolve the error ?

you need to download the token from the application and paste it in the  folder where your meshery is installed

**Comment by rahulrana701** [comment]
@Ashparshp done
