### ISSUE TITLE
[mesheryctl] `relationships view` command unmarshall error.

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11313]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

When we run `mesheryctl exp relationship view [model-name]` command  there is json unmarshal error.

### Screenshots/Logs

```
./mesheryctl exp relationship view kubernetes
Error: json: cannot unmarshal object into Go struct field MeshmodelRelationshipsAPIResponse.relationships of type entity.Entity
```

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by alloydm** [comment]
Hi @Jougan-0 
This my first time contributing to this project, can I work on it?

**Comment by Jougan-0** [comment]
> Hi @Jougan-0 This my first time contributing to this project, can I work on this issue?

Surely. If you could confirm that you were able to run `mesheryctl` locally, I would assign it to you or else I would suggest you to run it locally and then as soon as you confirm. I'll assign it to you.

**Comment by alloydm** [comment]
Hello @Jougan-0 
my earlier comment got deleted bymistakely
Yes i do have the `mesheryctl` locally now.
do I need to fill the member form as well and do other prereqs?

**Comment by Jougan-0** [comment]
> Hello @Jougan-0 my earlier comment got deleted bymistakely Yes i do have the `mesheryctl` locally now. do I need to fill the member form as well and do other prereqs?

Yes please fill the members form and if you have any further doubt use `https://discuss.meshery.io/` or slack for your queries.
Here is you go I assgined the issue to you.
