### ISSUE TITLE
[UI]: Overflow Issue in Navbar

### ISSUE THREAD

**Issue by senthil-athiban** [meshery/meshery#11321]
### Current Behavior
Navbar does not ensure to stay on top of other elements, leading to a compromised user interface where the navbar is obscured by other page elements under certain conditions.

### Desired Behavior
The navbar should have a sufficient `zIndex` value to ensure it consistently stays on top of all other elements across the website, regardless of the user's actions or the page's state. 

### Possible Solution
Adjust the CSS for the navbar component, setting its `zIndex` to a high enough value (e.g., 1000 or higher) that ensures it will overlay all other page elements.

### Steps to reproduce

1) Navigate to the Lifecycle management dashboard.
2) Enable inspect mode by right-clicking on the page and selecting "Inspect" or pressing `Ctrl+Shift+I` (Windows/Linux) or `Cmd+Opt+I` (Mac).
3) Ensure the inspect mode tab is docked to the right side of the window.
4) Reduce the window size to mobile mode by shrinking the browser window.

### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker, Kubernetes

### ScreenRecording

https://github.com/user-attachments/assets/198618f9-cfc2-46d1-9415-ad8ad4e45f29

### Additional Resources
- [Contributor Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Ashparshp** [comment]
@senthil-k8s Thanks for bringing this up! However, please ensure to mention the steps to reproduce the issue and provide a working video for better clarity. Also, remember to get assigned to an issue before starting work to ensure smooth collaboration. 😊

**Comment by Ashparshp** [comment]
@senthil-k8s Available?

**Comment by senthil-k8s** [comment]
@Ashparshp, apologies for the delayed response. I've attached the demo and included the steps to reproduce the issue.

**Comment by Ashparshp** [comment]
@senthil-k8s Video is unplayable! Check again please.

**Comment by senthil-k8s** [comment]
@Ashparshp , Video re-uploaded.

**Comment by Ashparshp** [comment]
@senthil-k8s, Please check that out, still showing video can't play.

**Comment by senthil-k8s** [comment]
Video is playing smoothly on my side. Checked on different environments and platforms. @Ashparshp 

![Screenshot_20240713-181848_GitHub.png](https://github.com/user-attachments/assets/47305923-2ee0-4f4c-8935-dbfefea2ab09)
