### ISSUE TITLE
[Docs] Secrets list in Build and Release

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11331]
### Current State
This page is in need of an enhanced list of org-level secrets - https://docs.meshery.io/project/contributing/build-and-release#secrets

### Desired State
The following list contains valid secret names and secret name that, if present, need to be -removed-:

-AKS_PLAYGROUND_KUBECONFIG-
-AZ_PLAYGROUND_HOST-
-AZ_PLAYGROUND_KEY-
-AZ_PLAYGROUND_USERNAME-
-CYPRESS_RECORD_KEY-
DOCKER_PASSWORD
DOCKER_USERNAME
GH_ACCESS_TOKEN
-GH_ACCESS_TOKEN_POSTGRES_TEST-
GO_VERSION
INTEGRATION_SPREADSHEET_CRED
MAIL_PASSWORD
MAIL_USERNAME
MESHERY_PROVIDER_TOKEN
MESHERY_TOKEN
METAL_AUTH_TOKEN
METAL_SERVER1
METAL_SERVER2
METAL_SERVER3
NETLIFY_AUTH_TOKEN
NETLIFY_SITE_ID
NPM_TOKEN
PLAYGROUND_CONFIG
PROVIDER_TOKEN
RELEASEDRAFTER_PAT
RELEASE_NOTES_PAT
SLACK_BOT_TOKEN
-TWITTER_CONSUMER_API_KEY_MESHERY-
-TWITTER_CONSUMER_API_SECRET_MESHERY-

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Jacobojijo** [comment]
Hello @leecalcote, kindly assign this to me

**Comment by akshansh-modi** [comment]
Hi @leecalcote,  i would like to work on this

**Comment by Jacobojijo** [comment]
Hello @leecalcote, seeking a little clarification, do we still include secrets that are already in the official documentation/application but are missing on the above list i.e IMAGE_NAME
