### ISSUE TITLE
[Docs] Link not working

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [meshery/meshery#11349]
### Current State
Link navigating to Meshery UI docs not working in Contributing to Meshery UI - Notification Center page https://docs.meshery.io/project/contributing/contributing-ui-notification-center#contributing-to-meshery-ui-notification-center

![Screenshot from 2024-07-09 15-55-01](https://github.com/meshery/meshery/assets/54661456/f9721ca6-8d8c-4d7c-a094-246d583fceef)

### Desired State
Contribution to Meshery UI text should navigate to that page (i.e. https://docs.meshery.io/project/contributing/contributing-ui) on clicking.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Deepak0320Singhal** [comment]
@Muhammed-Moinuddin Thank you for your Cotribution.
Let's discuss this in Meshery Dev meeting. Adding this as an agenda item....
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#
Meeting link: https://meet.layer5.io/meshery

**Comment by Zopsss** [comment]
@Muhammed-Moinuddin can you assign this issue to me?

**Comment by Ashparshp** [comment]
@ashish0kumar Thanks for your initiative! Also, please note that we move in chronological order with issue assignments. Kindly wait to be assigned before working on an issue next time. We'll review your PR shortly. 🚀

**Comment by Shreshthaaa** [comment]
Hey @Muhammed-Moinuddin, i can see no one is currently assigned on this issue. I would like to work on it, could you please assign it to me?

**Comment by Muhammed-Moinuddin** [comment]
> Hey @Muhammed-Moinuddin, i can see no one is currently assigned on this issue. I would like to work on it, could you please assign it to me?

It's just a small thing. Kindly do it ASAP. If u need any help do let me know...

**Comment by Shreshthaaa** [comment]
Hey @Muhammed-Moinuddin, I have raised a [PR](https://github.com/meshery/meshery/pull/11451).  Kindly have a look at it.
