### ISSUE TITLE
[Docs] Have Related Design docs for integrations

### ISSUE THREAD

**Issue by rishabhsharma1997** [meshery/meshery#11342]
### Current State
We don't show related design for integration in docs like we do on layer5 site

### Desired State

https://layer5.io/cloud-native-management/meshery/integrations/kubernetes
<img width="1468" alt="Screenshot 2024-07-08 at 1 59 04 PM" src="https://github.com/meshery/meshery/assets/172536864/28a93500-c0d4-4dd5-9a31-aa73b35047ef">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaishnaviadhau** [comment]
@rishabhsharma1997  I would like to work on this issue

**Comment by vaishnaviadhau** [comment]
@leecalcote Apologies , I currently don't have bandwidth to do this task could you please unassign me
