### ISSUE TITLE
[UI] Hover issue with Kubernetes connection and notification icons 

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [meshery/meshery#11368]
### Current Behavior
On just hovering the icons (talking about only notification and kubernetes connection icons on header of meshery-playground), the respective sections(small part) pop-ups on the screen.  

### Desired Behavior
There should be not any pop-up of sections on hover (talking about only notification and kubernetes connection icons on header of meshery-playground)

### Screenshots/Logs
[Screencast from 11-07-2024 06:26:16.webm](https://github.com/meshery/meshery/assets/54661456/bf389511-b30e-4999-9124-a5755eafb1ff)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
This is a intentional and desired behaviour @Muhammed-Moinuddin that slight pop up because that give user a feeling yes something will pop up when we click over the icon

**Comment by Muhammed-Moinuddin** [comment]
> This is a intentional and desired behaviour @Muhammed-Moinuddin that slight pop up because that give user a feeling yes something will pop up when we click over the icon

Noted Thanks.
