### ISSUE TITLE
[Docs] Enhance Contributing to Meshery UI doc with use of Sistent theme

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11363]
### Current State
The [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui) doc is missing instructions with respect to use of the common theme and it's various uses (light/dark mode, components from Sistent, components from MUI) 

### Desired State

1. Brief explanation of Sistent and its use within Meshery UI
1. Instructions on its use
1. Examples of its use

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by NagaHarshita** [comment]
@leecalcote please assign this issue to me.

**Comment by 102vansh** [comment]
@leecalcote  can you assign this issue to me?

**Comment by sudhanshutech** [comment]
Hey @NagaHarshita @102vansh thanks for jumping in.
Have you worked with Meshery using Sistent or are you familiar with its theme and how tokens are used? If so, that's great! If not, it might be best to let someone with experience in area handle this issue and lets get you other issues to work on.

**Comment by leecalcote** [comment]
@NagaHarshita @102vansh, thanks so much for raising your hands. Excellent! Following on @sudhanshutech's counsel, I'll suggest that a way of arriving at a "yes" answer to his questions is by getting your hands on the [Sistent project](https://github.com/meshery/sistent).

Currently, that project is in need of having it developer guide and components directory fully populated. We're in need of new component pages on the [Sistent project site](https://meshery.io/projects/sistent). @sudhanshutech will ensure that there are "help wanted" issues on this topic and to point you to them.

**Comment by NagaHarshita** [comment]
Thank you @leecalcote @sudhanshutech for your response. Happy to work on any issue directed towards me related to Sistent project.

**Comment by sudhanshutech** [comment]
@NagaHarshita there are issues opened under https://github.com/meshery/meshery/issues with sistent tag , you can help with that😎

**Comment by leecalcote** [comment]
@sudhanshutech, offer a couple of links to specific issues, please. Also, offer a link that includes the sistent label.

**Comment by sudhanshutech** [comment]
Here is a unassigned issue: https://github.com/meshery/meshery/issues/5669
and all with sistent label: https://github.com/meshery/meshery/issues?q=is%3Aissue+is%3Aopen+sistent (you can also review and ask to work on if the already assigned person is not active)
I will be opening more so its great opportunity to work on.

**Comment by leecalcote** [comment]
Where’s one for @102vansh? Do we not have many many components that are needed of being published in the contributor guide for Sistent? Where is this list?

**Comment by sudhanshutech** [comment]
I have already tagged him in one of the issue.
Yes we have many components , i have opened more issues: https://github.com/meshery/meshery/issues?q=is%3Aissue+is%3Aopen+sistent
And also list can be found here which are not been published: https://docs.google.com/spreadsheets/d/1CzaDpYljSqA-kR0IXEH_g7rNJzVmojsZNyRbzyAjbRw/edit?gid=0#gid=0
