### ISSUE TITLE
[UI] Clarifying the Search placeholder in Lifecycle 

### ISSUE THREAD

**Issue by dusdjhyeon** [meshery/meshery#11389]
### Current Behavior
The placeholder for the search area in all subsections of the Lifecycle in the Meshery playground is "Search connections...". 
![image](https://github.com/user-attachments/assets/46a14fcf-45df-4042-8e51-a5897336d70f)

### Desired Behavior
Change each to a placeholder that clearly represents it. (Environments, Workspaces,,,,)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Hackmey** [comment]
Can you assign me this ?

**Comment by dusdjhyeon** [comment]
> Can you assign me this ?

Here you go :)

**Comment by sudhanshutech** [comment]
@Hackmey its a very small fix, what's the progress?

**Comment by Hackmey** [comment]
@Jougan-0 I am on it. Will be done by today itself.

**Comment by Jougan-0** [comment]
@sudhanshutech @dusdjhyeon //
