### ISSUE TITLE
[Docs] Adding multi-word filter name support documentation to filter command 

### ISSUE THREAD

**Issue by Aviral0702** [meshery/meshery#11395]
### Current State
New feature for viewing multi-word filter names has been added to filter view command.
Need for documentation on how to view filter names which have multiple words

Need an update here: https://docs.meshery.io/reference/mesheryctl/filter/view

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vishalvivekm** [comment]
Thank you @Aviral0702
