### ISSUE TITLE
Search Resources From Managed Cluster

### ISSUE THREAD

**Issue by innocentrda** [meshery/meshery#11401]
### Current Behavior

The search bar is not working. Unable to sort resources either through the search bar or table headers. 
![Screenshot from 2024-07-16 10-21-56](https://github.com/user-attachments/assets/819c54bf-a6b5-4791-aefc-f3d44f7fb3af)

### Desired Behavior

To be able to search by a keyword and be able to sort by column through any table header (Column Name)
### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by rahulrana701** [comment]
It is working fine for me

**Comment by senthil-k8s** [comment]
Yes @innocentrda , there is a delay in search bar. But the search functionality working fine. I would like to work on this issue, could you please assign this issue to me ?

https://github.com/user-attachments/assets/ed82c0bc-b80c-43fc-bb98-e246db04be0e

**Comment by sudhanshutech** [comment]
The search is working fine here. We need sort functionality from backend to support and for that issue is already opened.
