### ISSUE TITLE
[Docs] Link for Meshery documentation on SMP Github Actions not working

### ISSUE THREAD

**Issue by Aviral0702** [meshery/meshery#11412]
### Current State
The Meshery documentation link on the page https://docs.layer5.io/cloud/github-actions/#meshmap-snapshot-github-action under the subtopic **"Using Meshery’s Performance Testing GitHub Action"** is not working.

The  link attached to **"Performance Testing with Meshery"** under subtopic Meshery github actions is also not working.

![Screenshot from 2024-07-17 17-33-12](https://github.com/user-attachments/assets/af5e2bb4-c43a-45b9-892f-71970ec7b38c)

![Screenshot from 2024-07-17 17-32-07](https://github.com/user-attachments/assets/721f182e-32e1-424d-8de9-5ddeaf52f809)

### Desired State
It should point to this page : https://docs.meshery.io/guides/infrastructure-management/gitops-with-meshery

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by mon4our** [comment]
I was able to solve this issue by updating the outdated link in the [meshery/docs repository](https://github.com/meshery/docs). Can I be assigned this issue so that I can make a PR for it.

P.S. Wouldn't it be more appropriate to open it as a new issue in the [meshery/docs repository](https://github.com/meshery/docs)?
