### ISSUE TITLE
[mesheryctl] `mesheryctl` commands needs to return proper message while auth.json is not present

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11414]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

Whenever we run the `mesheryctl` command and the `auth.json` file is missing from the `/home/.meshery` directory, it returns an unclear error that lacks proper guidance for remediation. We need to refactor the centralized function responsible for this check to include a clear and helpful error message.

### Desired Behavior

Generate an error message and log it to the terminal in a way that clearly explains to the end user what the error is and provides steps for resolving it.
### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by hexxdump** [comment]
@innocentrda , can you pls attach the screenshot of the exact error ?

**Comment by Jougan-0** [comment]
![image](https://github.com/user-attachments/assets/4ea71a83-79a9-4269-803f-400f2253a87b)
To recreate just delete `auth.json` from `.meshery` directory and run `mesheryctl` commands.

**Comment by innocentrda** [comment]
> @innocentrda , can you pls attach the screenshot of the exact error ?

Here it is.

![Screenshot from 2024-07-15 19-27-33](https://github.com/user-attachments/assets/440b78ef-afef-47ae-acdc-ede3ff1afa6e)

**Comment by leecalcote** [comment]
@hexxdump, I just opened this related issue - https://github.com/meshery/meshery/issues/11420. Is this an item that you might investigate?

**Comment by hexxdump** [comment]
Planning to do a quickfix for this issue by adding user readable logs in auth.go.

**Comment by pranjalg1331** [comment]
@Jougan-0  will an error like this work?
![Screenshot 2024-09-25 185946](https://github.com/user-attachments/assets/ebc0d38d-2487-448d-8d60-c9aa4e36bbcd)

**Comment by pranjalg1331** [comment]
also please assign this issue on my name

**Comment by Jougan-0** [comment]
> @Jougan-0 will an error like this work? ![Screenshot 2024-09-25 185946](https://private-user-images.githubusercontent.com/121032858/370734375-ebc0d38d-2487-448d-8d60-c9aa4e36bbcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzExNTEsIm5iZiI6MTcyNzM3MDg1MSwicGF0aCI6Ii8xMjEwMzI4NTgvMzcwNzM0Mzc1LWViYzBkMzhkLTI0ODctNDQ4ZC04ZDYwLWM5YWE0ZTM2YmJjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxNzE0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTlkMTYxZWM1YzI4YWY1MzYyMjdmOTQyOWJhNWI2OWVhNDU4Nzg1Yjk3YzBjNTg4ZjZjODM3NTlkNWI3YjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P1U52OcvMzqpoVPHNN19CSyW66JAs0TFzY0AnPzH7ms)

Just mention to login if you could please remove the log line so it logs only once.

**Comment by lekaf974** [comment]
Could you also open a PR so we can see what changes were made

**Comment by pranjalg1331** [comment]
@Jougan-0 raised a pr
