### ISSUE TITLE
`VersionMeta` property in models exported as YAML

### ISSUE THREAD

**Issue by humblenginr** [meshery/meshery#11411]
### Current Behavior
`VersionMeta` is the struct used in golang to group `SchemaVersion` and `Version` properties, and the model is being exported with the `VersionMeta` field. 

### Expected Behavior
`VersionMeta` is not a part of the schema for model. It should not be a part of exported model. This is because we don't have struct tags defined for YAML in the struct definition, so by default, the `yaml.Unmarshal` uses the name of the embedded struct as its standalone property. 

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thanks. Affected version #? "model" label?

**Comment by leecalcote** [comment]
Need to add go-tag annotations to Meshery schemas.

**Comment by leecalcote** [comment]
> Thanks. Affected version #? "model" label?

**Comment by humblenginr** [comment]
Closing this because of https://github.com/meshery/meshkit/pull/540#issuecomment-2260555471
