### ISSUE TITLE
[Docs] "help-wanted label" hyperlink missing multi-org search for label

### ISSUE THREAD

**Issue by jameshorton2337** [meshery/meshery#11416]
### Current State

[This page](https://docs.meshery.io/project/contributing) has a description that includes a hyperlink in need of updating to be the same as found in the readme.

<img width="1108" alt="Screenshot 2024-07-17 at 4 40 50 PM" src="https://github.com/user-attachments/assets/cb93a65f-8270-4644-92d1-6f94ac6f84eb">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by SAHU-01** [comment]
@jameshorton2337 may I work on this?
