### ISSUE TITLE
[mesheryctl] `pattern import` command should have a proper log on successful import of pattern 

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11422]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

When you use `mesheryctl pattern import`, the response received is often unclear and fails to convey the proper meaning.
### Desired Behavior

Enhance the log to include more meaningful information and clearly convey the correct message.
### Screenshots/Logs

```
mesheryctl pattern import -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.11/config/master/aws-k8s-cni.yaml -s kubernetes
remote hosted pattern request success
pattern file imported successfully.
ID of the pattern: e0bf8082
```
### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by rahulrana701** [comment]
Hi @Jougan-0 I would like to work on this

**Comment by Jougan-0** [comment]
Just to confirm, have you successfully run `mesheryctl` locally?

**Comment by rahulrana701** [comment]
Yup

**Comment by Jougan-0** [comment]
Here you go sir.

**Comment by rahulrana701** [comment]
hi @Jougan-0 could you please help me a bit , I changed the log messages but when I am trying to use the above command you mentioned in this issue to import a design pattern I am still seeing the old log messages , I have tried to clear the cache and rebuild the code , but I am still encountering the same issue.

**Comment by Jougan-0** [comment]
Did you run `make` after doing the changes in mesheryctl directory?

**Comment by rahulrana701** [comment]
> Did you run `make` after doing the changes in mesheryctl directory?

yes

**Comment by Jougan-0** [comment]
The issue should not occur go though the docs again if you update exact log text `remote hosted pattern request success` and run make in the terminal while being in mesheryctl directory and use `./` followed by the command to use the latest mesheryctl which you build and not the global one.
You might be using the global mesheryctl. Run this command instead.
`./mesheryctl pattern import -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.11/config/master/aws-k8s-cni.yaml -s kubernetes`

**Comment by Shubhf** [comment]
Hey @Jougan-0 Can I take up this issue ??? Or can I help @rahulrana701 ??

**Comment by Jougan-0** [comment]
@rahulrana701 would be the right person to answer this imo.

**Comment by rahulrana701** [comment]
@Jougan-0,  I will submit the pr very soon , actually I am windows user , so there are couple of commands that were not working for me so I tried using wsl now it is working fine.
