### ISSUE TITLE
[mesheryctl] `model import` dysfunctional: Not contacting Meshery Server

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11433]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
Inconsistent mesheryctl behavior. The second response is the valid response. Meshery Server is actually available.

```
$ mesheryctl model import ../
Error: Meshery server is not reachable: dial tcp: lookup tcp///playground.meshery.io: unknown port

$ mesheryctl pattern list
The authentication token has expired or is invalid.
```

After I authenticate with mesheryctl system login, I’m able to run the pattern command:

```
$ mesheryctl pattern list

PATTERN ID	USER ID 	NAME                         	CREATED  	UPDATED
9a32b3d9  	7c176f74	aws-k8s-cni.yaml             	7-19-2024	7-19-2024
ff2db0b8  	7c176f74	aws-k8s-cni.yaml             	7-19-2024	7-19-2024
```

However, the model command fails to contact Meshery Server. 

```
$ mesheryctl model import ./workflow.yml
Error: Meshery server is not reachable: dial tcp: lookup tcp///playground.meshery.io: unknown port
```

### Desired Behavior
All contact with Meshery Server should be reusing the same central utility functions. 

### Environment

```
$ mesheryctl version
      	VERSION	GITSHA
Client	v0.7.83	6a8df8c0a6
Server	v0.7.83	6a8df8c0
```

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by alloydm** [comment]
Hi @leecalcote 
I tried reproducing the above issue, and I am not seeing the same error message as your's for `mesheryctl model import ./workflow.yml`

The above error command returns
`The authentication token has expired or is invalid.`

**Comment by rahulrana701** [comment]
@alloydm you need to authenticate yourself again , via this command mesheryctl system login through your cli.

**Comment by rahulrana701** [comment]
@leecalcote @Jougan-0 I would like to work on this issue

**Comment by rahulrana701** [comment]
@alloydm  No , I am encountering the same error as @leecalcote

**Comment by leecalcote** [comment]
@rahulrana701, perhaps, list the steps to reproduce, so that @alloydm might have a go at this.

**Comment by alloydm** [comment]
> @rahulrana701, perhaps, list the steps to reproduce, so that @alloydm might have a go at this.

Yes @leecalcote , @rahulrana701 could you share the steps to repro the issue

**Comment by rahulrana701** [comment]
hi @leecalcote ,I tried rebuilding my application, and I am no longer getting the earlier error message, "Meshery server is not reachable: dial tcp: lookup tcp///playground.meshery.io: unknown port." However, now I am getting a new error message when trying to import, which seems to be a server error. This indicates that our server is reachable, but the request handling the import is not working correctly. Could you please verify this?

<img width="590" alt="image" src="https://github.com/user-attachments/assets/d6c05f8f-95cb-4cc4-aabc-530a587aabef">

**Comment by alloydm** [comment]
> hi @leecalcote ,I tried rebuilding my application, and I am no longer getting the earlier error message, "Meshery server is not reachable: dial tcp: lookup tcp///playground.meshery.io: unknown port." However, now I am getting a new error message when trying to import, which seems to be a server error. This indicates that our server is reachable, but the request handling the import is not working correctly. Could you please verify this?
> 
> <img alt="image" width="590" src="https://private-user-images.githubusercontent.com/123585591/352429656-d6c05f8f-95cb-4cc4-aabc-530a587aabef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTcyODYsIm5iZiI6MTcyMTk5Njk4NiwicGF0aCI6Ii8xMjM1ODU1OTEvMzUyNDI5NjU2LWQ2YzA1ZjhmLTk1Y2ItNGNjNC1hYWJjLTUzMGE1ODdhYWJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxMjI5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWI1NjZlZTUxMmU5ZDhhZjIxZDAyMGU5ODkzYmMzYTU0YjE5YmRkNDRiNDM5ZjA2YWE2MDRiZjJmODNiYzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BHSbyKugiI6o7Z7gtPXzZ1py6XcExsxk8Ukcv6VwMDw">

Hey @leecalcote we have discussed the same on #meshery channel do check out the thread

**Comment by rahulrana701** [comment]
> > hi @leecalcote ,I tried rebuilding my application, and I am no longer getting the earlier error message, "Meshery server is not reachable: dial tcp: lookup tcp///playground.meshery.io: unknown port." However, now I am getting a new error message when trying to import, which seems to be a server error. This indicates that our server is reachable, but the request handling the import is not working correctly. Could you please verify this?
> > <img alt="image" width="590" src="https://private-user-images.githubusercontent.com/123585591/352429656-d6c05f8f-95cb-4cc4-aabc-530a587aabef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTcyODYsIm5iZiI6MTcyMTk5Njk4NiwicGF0aCI6Ii8xMjM1ODU1OTEvMzUyNDI5NjU2LWQ2YzA1ZjhmLTk1Y2ItNGNjNC1hYWJjLTUzMGE1ODdhYWJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxMjI5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWI1NjZlZTUxMmU5ZDhhZjIxZDAyMGU5ODkzYmMzYTU0YjE5YmRkNDRiNDM5ZjA2YWE2MDRiZjJmODNiYzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BHSbyKugiI6o7Z7gtPXzZ1py6XcExsxk8Ukcv6VwMDw">
> 
> Hey @rahulrana701 we have discussed the same on #meshery channel do check out the thread

sure

**Comment by humblenginr** [comment]
This is happening because of the [IsServerRunning](https://github.com/meshery/meshery/blob/master/mesheryctl/pkg/utils/auth.go#L451) utility function. This function expects meshery server address with the port, but the callers only provide the address without the port.

**Comment by rahulrana701** [comment]
@humblenginr I am getting this error message , could you please tell me why I am not getting the same error message 
![nwq](https://github.com/user-attachments/assets/e44938ac-ed79-41db-b1ec-d60af69bc2e1)

**Comment by Jougan-0** [comment]
Use this branch to use import and export 
https://github.com/meshery/meshery/pull/11354

**Comment by rahulrana701** [comment]
![Screenshot 2024-08-21 143500](https://github.com/user-attachments/assets/1a5b27df-b05f-4647-896c-d5742b52256b)
I'm still encountering the same error, although the status code is different this time
