### ISSUE TITLE
[UI] Submenu items do not open 

### ISSUE THREAD

**Issue by hargunkaur286** [meshery/meshery#11460]
### Current Behavior

In the sidebar of the [Meshery Docs](https://docs.meshery.io/), the subitems open only on clicking the toggle(arrow) button

### Expected Behavior

The menu should also open on clicking the menu item

### Screenshots/Logs

<img width="316" alt="Screenshot 2024-07-26 at 4 29 50 PM" src="https://github.com/user-attachments/assets/7d882228-468e-4094-b7b0-644028231b1d">

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by hargunkaur286** [comment]
I want to work on this issue.

**Comment by vaishnaviadhau** [comment]
I would like to work on this issue. Could you please assign it to me.

**Comment by yash37158** [comment]
Thanks @vaishnaviadhau for hopping in. are you able to run meshery doc locally ?

**Comment by vaishnaviadhau** [comment]
yes sir

**Comment by leecalcote** [comment]
Thanks for verifying, @yash37158 👏

**Comment by leecalcote** [comment]
Thanks for volunteering, @vaishnaviadhau. 👏
