### ISSUE TITLE
[UI] Convert Hamburger icon to cross icon after opening of Navbar 

### ISSUE THREAD

**Issue by upsaurav12** [meshery/meshery#11479]
### Current Behavior

Navbar in smaller width has toggle button but i want to convert that icon(``Hamburger``) to ``Cross`` after clicking to toggle button
![image](https://github.com/user-attachments/assets/d54a16c9-f3cf-4a39-bc7c-6dc8252ae97c)

 
### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by upsaurav12** [comment]
I want to work on this issue

**Comment by shivansh84ya** [comment]
Could you please assign this issue to me? I have experience working on similar UI tasks and would love to contribute.

**Comment by yash37158** [comment]
Here you go @upsaurav12

**Comment by upsaurav12** [comment]
thanks @yash37158

**Comment by Mandeep56Singh** [comment]
@upsaurav12  any progress, If you stuck somewhere maybe I can help you.

**Comment by Ashparshp** [comment]
@upsaurav12, since there hasn't been any progress from your side, I'm opening it up for volunteers.

**Comment by upsaurav12** [comment]
@Ashparshp sorry for late response i was not able to do it due to my college work.

**Comment by upsaurav12** [comment]
It would be great for new contributor to work on this issue

**Comment by Mandeep56Singh** [comment]
@Ashparshp I would be happy to do it

**Comment by aadarshx22** [comment]
If this issue is unassigned or vacant, I can work on it, please assign it to me

**Comment by Ashparshp** [comment]
@Mandeep56Singh, @aadarshx22, do you have your local setup ready?

**Comment by aadarshx22** [comment]
yes I do have the local setup ready

**Comment by Ashparshp** [comment]
Thank you @aadarshx22, assigned to u.

**Comment by upsaurav12** [comment]
@Ashparshp i think you made wrong issue invalid 
pls check may be i am wrong

**Comment by Ashparshp** [comment]
It shouldn't be open there as it's wrong place, you should move this issue to meshery/meshery.io.

**Comment by upsaurav12** [comment]
@Ashparshp sorry for misunderstanding, 
opening this issue on meshery.io .

**Comment by Ashparshp** [comment]
Thank you @upsaurav12..
