### ISSUE TITLE
[Server] Boottime: Model registration log missing registrant's name

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11475]
### Current Behavior

The following log is displayed at boot time of Meshery Server:

```
INFO[2024-07-28T14:50:43-05:00] For registrant   successfully imported 12 models 108 relationships  app=meshery
```

### Expected Behavior
The name of the registrant should be included between "registrant" and  "successfully" in the same fashion that registrant's names are included in similar log.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaishnaviadhau** [comment]
@leecalcote I would like to solve this issue.

**Comment by alloydm** [comment]
@leecalcote Here **GetRegistrants** function from meshkit/models/meshmodel/registry does not return any username
<img width="543" alt="Screenshot 2024-07-30 at 12 16 18 AM" src="https://github.com/user-attachments/assets/5faa30d4-1e90-4d77-a45f-f80d923e2c3a">

If as per the design, hostname is supposed to be present, I believe we might have to look into meshkit/models/meshmodel/registry query

**Comment by Jougan-0** [comment]
@alloydm This is generated from the handleError function you can look at the this [PR](https://github.com/meshery/meshery/pull/11385).

**Comment by leecalcote** [comment]
@humblenginr @Jougan-0 make sure that you are getting single model import as an atomic operation correct. Relationships cannot be imported out of context of a model. A model cannot be imported out of context of a registrant.
