### ISSUE TITLE
[UI]: List Item going outside navbar container in smaller width 

### ISSUE THREAD

**Issue by upsaurav12** [meshery/meshery#11477]
### Current Behavior

In smaller width, list-item(``Resource``) going outside when the ``sub-list`` of ``community`` is open. Also Getting started button has also the same problem. 
This is how it is looking 
![image](https://github.com/user-attachments/assets/9555a7b5-edb1-4629-a82e-d9b1942a7949)

### Desired Behavior

This can be fix by removing the ``max-height: 400px`` in ``nav-list`` class and it will fix the problem. 
This is how it will look
![image](https://github.com/user-attachments/assets/9a3cf1e3-c6f9-4049-8e08-adc530510684)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaishnaviadhau** [comment]
@upsaurav12 can you assign this to me ?

**Comment by upsaurav12** [comment]
i am not the maintainer

**Comment by vaishnaviadhau** [comment]
@upsaurav12 Have you solved this issue, or are you waiting for it to be assigned?

**Comment by upsaurav12** [comment]
I have Almost solved it . and i am waiting so that i can raise my PR

**Comment by upsaurav12** [comment]
I am waiting to get assigned then after i will start working on this issue

**Comment by aadarshx22** [comment]
Please assign me this issue, I can work on it

**Comment by upsaurav12** [comment]
@Ashparshp can you check this whether it is valid or.not.

**Comment by Ashparshp** [comment]
@upsaurav12, this is not the right place for the issue; it belongs in meshery.io. Also, what width size are you referring to? It looks good to me on my side.

**Comment by upsaurav12** [comment]
@Ashparshp sorry it was visible from my pov the time when i open the issue, 
I think it was fixed by someone's PR

**Comment by Ashparshp** [comment]
Closing as not valid anymore!
