### ISSUE TITLE
[Docs] Add documentation for contributor guide for `schema-driven` process in Meshery UI

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#11484]
Meshery has begun using JSON schema to define its constructs. We need to better benefit from the effort put into well-defined objects and specification-compliant constructs.

#### Issue for more context

- https://github.com/meshery/meshery/issues/6870			

#### The following principles are to be considered:
- Consistency around REST APIs structure for Meshery Cloud and Meshery Server.
- Consistency around APIs response and error messages.
- Complete and structured documentation.

*This need to be documented how other contributors can participate to achieve the goal*

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
@aabidsofi19

**Comment by akshansh-modi** [comment]
@sudhanshutech i would like to give it a try
