### ISSUE TITLE
Migrate APIs to be schema-driven

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#11495]
**Description**: Enhance Meshery’s APIs capability by migrating to a schema-driven approach, which will ensure consistency, validation, and easier integration. It involves versioning and defining API schemas using OpenAPI/Swagger at https://github.com/meshery/schemas and auto generating structs. You will be ensuring all Meshery APIs aligns with defined schemas and are consistent.

- Expected Outcome: Identifying APIs and updating them to conform these schemas. Enhance API documentation to reflect the schema-driven approach. Updating APIs to ensure they are consistent and doing validation against defined schemas.

- Recommended Skills: Golang, Kubernetes, Swagger, JSON schemas, familiarity with React, Nextjs would be helpful
- Mentor(s): Lee Calcote (@leecalcote, [leecalcote@gmail.com](mailto:leecalcote@gmail.com)), Yash Sharma (@Yashsharma1911, yashsharma2572@gmail.com)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by upsaurav12** [comment]
Hi @Yashsharma1911,

I am interested in working on the LFX project related to Meshery. I have a question regarding the project agenda:

Are all the APIs in the ``meshery`` repository going to be built from scratch using a schema-driven approach/Swagger.

Thank You.

**Comment by Omarabdul3ziz** [comment]
Hello, I am interested in contributing to this issue as part of the LFX mentorship program

**Comment by Ash-2k3** [comment]
Hey @Yashsharma1911, just wanted to know by when will the mentee be selected for this project ? Because I think the deadline was 27 Aug 5.00 AM PDT.

**Comment by leecalcote** [comment]
@Omarabdul3ziz @rahulbansal3005, great start participating.

@Ash-2k3 selection is based on supporting existing contributors. I encourage you to start participating today. The weekly Meshery Dev meeting starts in a few minutes...

**Comment by Ash-2k3** [comment]
Sure, thankks!!!

**Comment by prachinandi** [comment]
> Meshery’s APIs

From where can I find Meshery’s APIs documentations?

**Comment by leecalcote** [comment]
@prachinandi here - https://docs.meshery.io/extensibility/api

**Comment by leecalcote** [comment]
@prachinandi, in fact, that page needs a small update to include ``` or `<pre>` around the two API path references at the bottom of the page (e.g. `/api/perf`). Open a PR, if you'd like to fix it...

**Comment by prachinandi** [comment]
> @prachinandi, in fact, that page needs a small update to include ``` or `\<pre\>` around the two API path references at the bottom of the page (e.g. `/api/perf`). Open a PR, if you'd like to fix it...

Done! https://github.com/meshery/meshery/pull/12215
