### ISSUE TITLE
[UI] Submit Newsletter page ui issue

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery#11499]
### Current Behavior
When I submit the newsletter and verify the CAPTCHA, I get a confirmation page with dark text that is not easily visible. Some of the text is white and bold, which stands out.

### Desired Behavior
Ensure a consistent theme across the entire app. Make the text white or another color that is clearly visible.

### Screenshots/Logs
![image](https://github.com/user-attachments/assets/a4f7ca4c-a54c-47e6-82d4-89fe41beca83)
https://layer5.us15.list-manage.com/subscribe/confirm-captcha

### Environment

- Browser: Firefox
- Host OS: Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

### Additional Information
I can solve this issue. If you find it valid, I am happy to work on it.
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by iushdoescode** [comment]
hey i would like to work on this issue, can i get assigned to it?

**Comment by amitamrutiya** [comment]
Hey @iushdoescode,

Thanks for your interest in solving this issue. I am waiting for some confirmation from the mentor. Once I receive it, I will start working on this issue. So, you can find other issues to work on.

**Comment by asmit27rai** [comment]
I want to work on this issue.

**Comment by Ashparshp** [comment]
@amitamrutiya, It's in meshery.io not in this repo, right?
https://meshery.io/subscribe

**Comment by amitamrutiya** [comment]
Yeah @Ashparshp, Your are right.
