### ISSUE TITLE
End-to-End Testing with Playwright (Round 2)

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#11494]
**Description:** Meshery integrates with many other CNCF projects and technologies. Sustaining those integrations is only possible through automation. End-to-end testing with Playwright, GitHub Workflows, and self-documenting test reports is the means to the end of maintaining a healthy state of each of these [Meshery integrations](https://meshery.io/integrations). 
 
- Expected Outcome: 
  - Successful migration of E2E tests from Cypress to the Playwright test library within the Meshery project.
  - Implementation of robust and reliable test cases using Playwright to cover a wide range of Meshery's E2E scenarios.
  - Documentation detailing the migration process, and guidelines for future contributions to maintain test quality.
  - Integration of Playwright test suite into the Meshery CI/CD pipeline to ensure continuous testing and reliability of the platform.
- Recommended Skills: JavaScript, Playwright, GitHub Workflows, Jekyll, Markdown, familiarity with React or Nextjs would be helpful, CI/CD
  - Mentor Name: Aabid Sofi (@aabidsofi19, mailtoaabid01@gmail.com), Lee Calcote (@leecalcote, [leecalcote@gmail.com](mailto:leecalcote@gmail.com)),

Checkout - [How to setup e2e testing environment with playwright and docker for Meshery](https://discuss.layer5.io/t/how-to-setup-e2e-testing-environment-with-playwright-and-docker-for-meshery/5498) by Jeren

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by its-ChaTTy** [comment]
Hi, I would love to work on this. I have some past experience working with Playwright & writing E2E tests. Looking forward to it.

**Comment by yashpandey06** [comment]
Hey @Yashsharma1911 that's a great way to ensure the validity of functions via test coverage ...I would like to work on this project under LFX Mentorship .I have experience in writing tests and implementing  jobs in ci/cd pipelines .

Looking forward to too healthy contribution ahead.

**Comment by ShantKhatri** [comment]
Hi, I would like to work on this, is there any Pre-Test?

**Comment by leecalcote** [comment]
Yes, join the community and get started. There’s a newcomers call held every Thursday. Find details for joining here: https://meet.meshery.io

**Comment by ShantKhatri** [comment]
> Yes, join the community and get started. There’s a newcomers call held every Thursday. Find details for joining here: https://meet.meshery.io

Thanks @leecalcote !

**Comment by aialok** [comment]
Hello @Yashsharma1911!

I would love to work on this project. I have good experience in CI/CD and Testing. Currently, I am a GSoC contributor at JSON Schema org, and my project involves setting up CI/CD pipelines and testing infrastructure.

I have set up a CI/CD pipeline from scratch for the JSON Schema website, which involves checking code quality through formatting, ESLint, type checking, building, testing, and deploying to Cloudflare. Additionally, I have integrated GitHub apps for community operations and automated various workflows. I have also set up the testing infrastructure from scratch using Cypress and wrote end-to-end and component tests for the website.

I would love to work on this project, migrating from Cypress to Playwright. My experience will ensure a smooth transition and enhance our testing infrastructure.

Proof of work:

[My GitHub Pull Requests](https://github.com/json-schema-org/website/pulls?q=is%3Apr+author%3Aaialok+is%3Aclosed)

Thank you!

**Comment by manzil-infinity180** [comment]
Hello,
Currently, I am doing e2e testing with cypress, and javascript as GSOC Mentee, and I am also familiar with Jekyll and markdown that I have used to create my portfolio website. I would love to work on this project

Thank You
Rahul Vishwakarma

**Comment by Yashsharma1911** [comment]
Thankyou gents for raising your hand, I'll encourage you to join weekly development meetings to get started. You can find more info on meetings at [meet.meshery.io](https://meshery.io/community/calendar#meetings).

**Comment by SRIMANKS** [comment]
hi i would happy to contribute to this project as part of my linux foundation mentorship iam familiar with most of the technologies mentioned here. i also recently worked on  CI/CD piplines and End to End testing as part of my Internship at Deutsche Bank.

**Comment by SRIMANKS** [comment]
@leecalcote is there any pretest that i should mention in the cover letter ?

**Comment by leecalcote** [comment]
> @leecalcote is there any pretest that i should mention in the cover letter ?

Nope. I don't read cover letters or resumes or promises that a given individual knows what they are doing and will work hard and so forth. What I do see and what does count is action, not words. This issue and many like it have internships siting behind them. They are just waiting for a contributor to come by, join the community, start learning, contributing, helping others, doing so consistently and meaningfully.... and before you know it, that individual is learning and growing and being recognized and rewarded in all the ways that really count; in all the ways that they are conceptually looking to be as they seek out an internship: for the real value of experience and relationships, not stipends and acronyms on their resume. 

We have a number of open projects… any of which have internships available. My counsel is to engage in an area in which you think you can make an impact. And if you are being impactful and consistent, eventually we will bring the internship to you. Moreover you will take away exactly the same real value that an internship offers: experience and relationships (not stipend and letters on your resume - these are secondary).  Don’t do so and there’s not much for us to chat about. This is the best advice I can give you. It’s your career, though, not mine. The opportunity to engage takeaway experience and relationships is available to you. The choice to engage or not is yours.

The Meshery / Meshery internships are the most popular internship (many hundreds and hundreds of applicants each quarter) out of the entire Linux Foundation for a number of reasons, not least of which is that we couldn’t be more serious about accomplishing great things with interns both challenging them to grow, and them challenging the existing team to grow. Internships are awarded in support of work that a contributor is currently doing (impact that they are already making) and not awarded speculatively (in the hopes that they will be successful / impactful). Typically, it takes a contributor being engaged for a couple of months or more (depends on the skill level of engagement of the individual) to be contributing at a level deep enough to warrant internship being awarded. We have more internships to award than we have individuals qualified for assignment. As soon as an individual demonstrates their readiness (capability and dedication), we award an internship post-haste. Once awarded, interns are very well supported. We ensure their success - their failure is our failure and their success is our success. 

 We launch internships all the time. We started one intern last week and another this week. I encourage you to read the FAQs on this page (https://meshery.io/careers/programs) about how to best position your candidacy and to jump in here --> https://meshery.io/community/newcomers  .
 
 I want you to have that experience, those relationships, and accomplish amazing things here. I’ll support you, but it’s up to you to come get it.

**Comment by amitamrutiya** [comment]
Thanks so much @leecalcote for the straight talk and the advice! I truly appreciate it—it really motivates me.
