### ISSUE TITLE
[Models] Edge Network Relationship Between Services and Statefulsets

### ISSUE THREAD

**Issue by Alero-Awani** [meshery/meshery#11505]
### Current Situation

Currently, Edge Network relationships between Statefulsets and services are disabled.

### Proposed Change
This should be enabled because Statefulsets are controllers responsible for managing the lifecycle of Pods and Services route traffic to these pods.

---

### General Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Understanding Meshery Models

- 📚 [Models](https://docs.meshery.io/concepts/logical/models)
  - 📚 [Components](https://docs.meshery.io/concepts/logical/components)
  - 📚 [Relationships](https://docs.meshery.io/concepts/logical/components)
- 👨‍💻[Models Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)

 ### Contributing to Meshery Models
 - [Contributing Models](https://docs.meshery.io/project/contributing/contributing-models)
   - [Contributing Components](https://docs.meshery.io/project/contributing/contributing-components)
   - [Contributing Relationships](https://docs.meshery.io/project/contributing/contributing-relationships)

**Comment by akankshat05** [comment]
I would like to work on this.

**Comment by TomiwaAribisala-git** [comment]
Hi @Alero-Awani @MUzairS15 I am working on this issue; please find a draft of the Edge Network Relationship I was able to come up with below: 
`json
{
  "schemaVersion": "relationships.meshery.io/v1alpha2",
  "version": "v1.0.0",
  "kind": "Edge",
  "metadata": {
    "description": "A relationship that defines network edges between a StatefulSet and a Service",
    "animation": "marching-ants",
    "capabilities": {
      "designer": {
        "edit": {
          "style": true,
          "config": true,
          "label": false
        }
      }
    }
  },
  "model": {
    "schemaVersion": "models.meshery.io/v1beta1",
    "version": "v1.0.0",
    "name": "kubernetes",
    "model": {
      "version": "v1.25.2"
    },
    "displayName": "Kubernetes",
    "category": {
      "name": "Orchestration \u0026 Management",
      "metadata": null
    },
    "metadata": {}
  },
  "type": "Network",
  "subType": "Network",
  "evaluationQuery": "edge_network_relationship",
  "selectors": [
    {
      "allow": {
        "from": [
          {
            "kind": "Service",
            "model": "kubernetes"
          },
          {
            "kind": "Ingress",
            "model": "kubernetes"
          }
        ],
        "to": [
          {
            "kind": "Endpoints",
            "model": "kubernetes"
          },
          {
            "kind": "Pod",
            "model": "kubernetes"
          },
          {
            "kind": "StatefulSet",
            "model": "kubernetes"
          }
        ]
      },
      "deny": {
        "from": [
          {
            "kind": "Ingress",
            "model": "kubernetes"
          }
        ],
        "to": [
          {
            "kind": "Endpoints",
            "model": "kubernetes"
          },
          {
            "kind": "Pod",
            "model": "kubernetes"
          },
          {
            "kind": "StatefulSet",
            "model": "kubernetes"
          }
        ]
      }
    }
  ]
}
`
