### ISSUE TITLE
[UI]: Migrate Extension Page from Class to Functional Component

### ISSUE THREAD

**Issue by senthil-athiban** [meshery/meshery#11503]
### Current Behavior

Currently, the Extension Page is implemented as a class component, which can be more complex and harder to manage state and lifecycle methods compared to functional components.

### Desired Behavior

The Extension Page should be migrated from a class component to a functional component. This will simplify the codebase, make it more readable, and leverage modern React features like hooks for state and lifecycle management.

### Implementation

- Refactor the existing class component to a functional component.
- Use React hooks (e.g., useState, useEffect) to manage state and lifecycle methods.
- Ensure all functionalities of the class component are retained in the functional component.
- Update any related tests and documentation to reflect the changes.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by senthil-athiban** [comment]
@Yashsharma1911 @sudhanshutech, could you please assign this issue to me?

**Comment by akshansh-modi** [comment]
@ishankhare07  I think issue for this has been already created  #11493

**Comment by senthil-athiban** [comment]
Yes, But I mentioned the specific page that needs to be migrated.

**Comment by sudhanshutech** [comment]
@senthil-athiban you are already working on few areas so lets give other some oppurtunities.

**Comment by senthil-athiban** [comment]
@sudhanshutech, Already made PR for this issue, should I close it? . And for clarification, this migration is meant for Extension page only, still there are many components needs to be migrate to FC, which are not listed in the [tracker sheet](https://docs.google.com/spreadsheets/d/1RlUcr-iLtCFCsV1VZvWD0jBijPJAx-Rk-1GLLsL9sSI/edit?gid=0#gid=0) as well.

**Comment by aadarshx22** [comment]
Is this issue still open? If so, can I work on it
