### ISSUE TITLE
[Docker Desktop Extension] Make theming consistent in the UI

### ISSUE THREAD

**Issue by humblenginr** [meshery/meshery#11513]

**Comment by pandeyyyy** [comment]
hey, can i get assigned, i can make theming consistent for the desktop extension
@leecalcote @sudhanshutech

**Comment by sudhanshutech** [comment]
@humblenginr what are the other things required regarding theme?

**Comment by humblenginr** [comment]
This issue just outlines the requirement to use Sistent in Docker Desktop Extension. Nothing else should be needed for now since the migration should ensure consistency in theming.
