### ISSUE TITLE
[Local Provider] Not able to assign connection to environment

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#11525]
### Current Behavior
On the connections page in Meshery, after logging in as a local provider, the environments dropdown shows a success message when I assign an environment, but the dropdown doesn't get updated.

### Expected Behavior
You can see the expected behavior by logging in as a remote provider. Ideally, after the success message, the environment checkbox should be selected in the dropdown, and on refresh, it should show the assigned environments.

### Screenshots/Logs

https://github.com/user-attachments/assets/108f953e-e0f8-41b3-a158-9258e8f8fa03

### My investigation
I found that this issue occurs because the local provider API does not return assigned environments with the connection GET request API, whereas the remote provider does. That's why, local provider API needs to be updated to return the environments as well.

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vishalmishraa** [comment]
There is one more error , when it get selected , and try to unselect multiple at one time , it gives error. i think this is happening because of CreatableSelect from 'react-select/creatable' in multi-select-wrapper.js component . i might be wrong.
