### ISSUE TITLE
[Docs]: Weird text on header

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery#11545]
### Current Behavior
Currently, some weird text appears on this particular page: [link](https://docs.meshery.io/extensibility/adapters).

### Expected Behavior
Remove this text and ensure the header matches the format of other pages.

### Screenshots/Logs
![image](https://github.com/user-attachments/assets/57a6db5b-eada-4d9b-9745-de9fd0802236)

### Environment

- **Host OS:** Linux 
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

### To Reproduce
1. Go to '[link](https://docs.meshery.io/extensibility/adapters).'
3. See header

### If you find this issue valid I want to work on this

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by lokendra005** [comment]
i would like to work on this issue , Kindly assign this to me.

**Comment by amitamrutiya** [comment]
Hey @lokendra005 

Thanks for showing interest in solving this issue. I am currently waiting for confirmation from the maintainers. If they find this issue valid, I will start working on it. In the meantime, you can look for other issues to work on.

**Comment by yash37158** [comment]
Thanks for jumping in on this issue, @lokendra005! 🎉 Do you mind taking a peek at the other issues waiting for your touch?

**Comment by yash37158** [comment]
Here you go @amitamrutiya. 🚀
