### ISSUE TITLE
[mesheryctl] Support generating models by referencing the `Connection Definition`.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#11540]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

The only way to statically generate a model is via the `mesheryctl registry generate` command which references the Meshery Integrations spreadsheet. This is a hurdle for users trying to generate and import models.
### Desired Behavior

Support `mesheryctl model generate -f <path to connection definition>`, to generate models by referencing the connection definition.

### Implementation

Use the existing `generator` package from meshkit.

### Acceptance Tests

With the connection definition `github-connection.json` pointing to `github.com/GoogleCloudPlatform/k8s-config-connector`, the command should generate  `k8s-config-connector` model with 337 components.

`mesheryctl model generate -f github-connection.json`

Add mesheryctl test for the above scenario.
### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Kevin222004** [comment]
can i work on this

**Comment by leecalcote** [comment]
@Kevin222004, it'd be great if you did. Will you confirm your approach to solving the issue?

**Comment by Kevin222004** [comment]
@leecalcote 

so basically after learning and reading 
what I have understand is basically a Connection Definition
will look like
```
{
    "name": "k8s-config-connector",
    "filePath": "https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/crds",
    "branch": "main",
    "repository": "GoogleCloudPlatform/k8s-config-connector",
    "version": "v1.0.0",
    "source_url": "https://github.com/GoogleCloudPlatform/k8s-config-connector"
}
```

and then after extracting it I need to call this function from meshkit to generate the model. https://github.com/meshery/meshkit/blob/751b9fbf08ed00d13dcee92781f2c28505130430/generators/generator.go#L17

am I correct?
