### ISSUE TITLE
Certificate issue when using Minikube cluster.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#11546]
### Current Behavior

When using minikube, users are faced with the issue of 
`x509: certificate signed by unknown authority https-192-168-49-2-8443-version-timeout-32s-x509-certificate-signed-by-unknown-authority`.
To resolve the issue users have to manually flatten the kubeconfig file using the
` kubectl config view --minify --flatten > config_minikube.yaml` which is not the ideal flow.

### Expected Behavior

1. Resolve the reference while importing the kubeconfig. (The logic to flatten the config should be present in either the Mesheryctl or the Meshery server.)
2. Try skipping the certificates when connecting to the cluster by using the `skip-tls-verify` flag.
### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaishnaviadhau** [comment]
@MUzairS15  I would like to solve this issue. Could you pls assign this to me

**Comment by MUzairS15** [comment]
Thanks for volunteering @vaishnaviadhau. This is a bit involved issue and not suitable for newcomer's.

**Comment by jerensl** [comment]
@MUzairS15 I encountered this issue but after I added cert-manager on my local minikube it was discovered

The command to install cert-manager:
`kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml`

**Comment by MUzairS15** [comment]
Thanks @jerensl that’s a valid solution. Will you create a PR updating the docs?

Additionally, meshery server should be able to resolve the certificates as the certificates are valid and there is no issue when accessing minikube cluster via kubectl.

@Jougan-0 Can you address the second solution?

**Comment by jerensl** [comment]
Basically, there are two commands I run

1. [Enable Ingress](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#enable-the-ingress-controller) controller using NGINX
`minikube addons enable ingress`
2. Installing cert-manager, I'm not sure if it requires [more configuration](https://cert-manager.io/docs/tutorials/acme/nginx-ingress/#step-2---deploy-the-nginx-ingress-controller) but for now it's enough for ping and auto-discovery
`kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml`

Step one is required without it I can't connect to my own minikube but not sure about step 2 it may or not be needed

**Comment by leecalcote** [comment]
To be implemented in `mesheryctl system config minikube`
