### ISSUE TITLE
The dropdown list fails to update correctly

### ISSUE THREAD

**Issue by vaishnaviadhau** [meshery/meshery#11554]
### Current State
 The dropdown list fails to update correctly, showing 'latest' instead of the selected version (e.g., 'v0.6').
![Screenshot 2024-08-05 023026](https://github.com/user-attachments/assets/b0d0ed6a-0ec8-4b34-adfd-b6693f451243)

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by myspace20** [comment]
I will like to work on this issue

**Comment by vaishnaviadhau** [comment]
@myspace20 I am waiting for issue to be confirmed ,once it is then I'll start working on it

**Comment by myspace20** [comment]
Okay

**Comment by Ashparshp** [comment]
@myspace20, are you currently working on this issue? Any progress so far?

**Comment by myspace20** [comment]
@Ashparshp no I was told it wasn't approved and to hold on. Check the conversation.

**Comment by vaishnaviadhau** [comment]
@Ashparshp I am working on this

**Comment by Ashparshp** [comment]
Thank you @vaishnaviadhau,
Noticed an issue: selecting `v6` shows `latest`, and clicking `latest `again still stays on `v6`. Works fine with other versions. Otherwise, looks good to me.

Could you please fix this?

[Meshery Documentation _ Meshery.webm](https://github.com/user-attachments/assets/97f38e31-9b87-41a5-a174-a2fbe27f9f29)
