### ISSUE TITLE
[Docs] Sistent Page Bugs - Text and Link errors

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [meshery/meshery#11553]
### Current State

- On the Table of contents only the **usage** links work, the remaining two i.e. (How to use Sistent tokens/theme , Examples) not working
- The import code is **import {Button} from `@layer/sistent`**
- Button is having **variant="filled"**

### Desired State

- The remaining two links should also work.
-  The import code should be **import {Button} from `@layer5/sistent`**. Currently it is @layer/sistent (which is wrong) and it should be @layer5/sistent. Correct it in both places within page.
- In Button instead of having variant="filled", it should be **variant="contained"**. Which is present in the sistent:  https://github.com/layer5io/sistent/blob/master/src/base/Button/Button.tsx .Correct it in all three places within page.

https://github.com/user-attachments/assets/201a65b7-2bbb-467e-917a-6ca2d02fa5eb

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Vijaykv5** [comment]
I would like to work on this issue

**Comment by Muhammed-Moinuddin** [comment]
> I would like to work on this issue

Yes, go ahead.

**Comment by Muhammed-Moinuddin** [comment]
> Can I try it on??
> I was curious about the meshery project because it appeared on the recommended repository on the GitHub account.

@kmin-jeong thanks for the interest. Basically it is assigned in chronological order. I hope you'll find one soon. 😊

**Comment by kaushiktak19** [comment]
Hi @Muhammed-Moinuddin ,

I've been working on issue #11553 and have made the necessary updates to the import code, Button variant and "How to use Sistent tokens/theme" link. However, I’m unsure about the correct links for the "Examples" section in the Table of Contents. Could you please provide guidance on which examples should be linked there?

I’ve also prepared a video demonstrating the changes I’ve made. Since it appears that there hasn’t been progress from the initially assigned contributor, would you mind reviewing my work and letting me know if it's okay to proceed with a pull request after fixing example link ?

Video - 

Uploading meshery-sistent-docs-fix1.mp4…

Thank you!

Best regards,
Kaushik

**Comment by Muhammed-Moinuddin** [comment]
> Hi @Muhammed-Moinuddin ,
> 
> I've been working on issue #11553 and have made the necessary updates to the import code, Button variant and "How to use Sistent tokens/theme" link. However, I’m unsure about the correct links for the "Examples" section in the Table of Contents. Could you please provide guidance on which examples should be linked there?
> 
> I’ve also prepared a video demonstrating the changes I’ve made. Since it appears that there hasn’t been progress from the initially assigned contributor, would you mind reviewing my work and letting me know if it's okay to proceed with a pull request after fixing example link ?
> 
> Video -
> 
>  meshery-sistent-docs-fix1.mp4 
> Thank you!
> 
> Best regards, Kaushik

Thanks for the efforts but as it is assigned to @Vijaykv5 so we have to wait for his work. Kindly don't raise PR.

Just stay within community, join Meshery slack channel and I hope you'll find good issues to resolve. You'll find all the details over here: https://meshery.io/

**Comment by Muhammed-Moinuddin** [comment]
> Hi @Muhammed-Moinuddin ,
> 
> I've been working on issue #11553 and have made the necessary updates to the import code, Button variant and "How to use Sistent tokens/theme" link. However, I’m unsure about the correct links for the "Examples" section in the Table of Contents. Could you please provide guidance on which examples should be linked there?
> 
> I’ve also prepared a video demonstrating the changes I’ve made. Since it appears that there hasn’t been progress from the initially assigned contributor, would you mind reviewing my work and letting me know if it's okay to proceed with a pull request after fixing example link ?
> 
> Video -
> 
>  meshery-sistent-docs-fix1.mp4 
> Thank you!
> 
> Best regards, Kaushik

I'm not sure. @sudhanshutech What is the correct links for the "Examples" section in the Table of Contents

**Comment by kaushiktak19** [comment]
Hi @Muhammed-Moinuddin,

I see that this issue is currently assigned, but I've nearly completed my task and haven’t noticed any recent updates from the current assignee. If the current assignee is not actively working on it, I’d be happy to take over and ensure it gets addressed, if that's fine.

**Comment by Vijaykv5** [comment]
> Hi @Muhammed-Moinuddin,
> 
> I see that this issue is currently assigned, but I've nearly completed this task and haven’t noticed any recent updates from the current assignee. If the current assignee is not actively working on it, I’d be happy to take over and ensure it gets addressed, if that's fine.

I'm working on it. Will soon add a PR

**Comment by kaushiktak19** [comment]
Okay, got it @Vijaykv5 .

**Comment by sudhanshutech** [comment]
@Vijaykv5 ?

**Comment by Vijaykv5** [comment]
> @Vijaykv5 ?



got some issues while working over it, will soon drop a PR

**Comment by kaushiktak19** [comment]
Sure @Muhammed-Moinuddin, I would work on this issue and will try to fix it asap. Also, could you provide correct link for examples, as where shall the examples be directed when clicked ?
