### ISSUE TITLE
Security Vulnerabilities Table Not Fully Visible on Page

### ISSUE THREAD

**Issue by vaishnaviadhau** [meshery/meshery#11552]
### Current State

(https://docs.meshery.io/project/security-vulnerabilities)

![Screenshot 2024-08-05 010450](https://github.com/user-attachments/assets/28290cf8-41b0-47b3-89e8-d14ced0d5a49)

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aviral0702** [comment]
Please add the link for the page in the description for reference.
