### ISSUE TITLE
Playwright Tests for UI/Meshery-server Service Mesh Performance Management

### ISSUE THREAD

**Issue by yash37158** [meshery/meshery#11557]
### Current Behavior
As we are migrating our e2e tests to Playwright. In this migration, we will include comprehensive tests for the Service Mesh Performance Management component. This will ensure that functionalities such as running performance tests, viewing and editing performance profiles, deleting profiles, viewing and comparing test results, and scheduling tests are thoroughly tested and tracked in  [ Meshery Test Plan](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit?pli=1&gid=0#gid=0).

### Desired Behavior
Migrate the existing tests to Playwright to achieve a more robust and efficient testing framework. The new Playwright tests should cover the following scenarios:

- [x] `Run a performance test`

- [x]  `Run a performance test with a performance profile`

- [x]  `View/Edit the configuration of a performance profile`

- [ ]  `Delete a performance profile`

- [x]  `View results from a performance profile`

- [x] ` View detailed result of a performance profile (Graph Visualiser)`

- [ ] `Download, compare and schedule a performance test`

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by dsawwork** [comment]
This looks like an interesting project and seems like there might be multiple tasks that need contribution.  I have full stack dev experience in React, Jest and other frameworks including testing web apps so I can help in this if needed.
If possible, do you have a recommendation on how to gain familiarity in the domain to write performance tests?

**Comment by yash37158** [comment]
Thanks, @dsawwork, for showing interest in this issue. I've already made some progress and will be raising a PR by tonight. If you're still interested in contributing, you might want to check out this related issue: [Meshery Issue #11494](https://github.com/meshery/meshery/issues/11494). Additionally, you can refer to the [Meshery Test Plan](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit?pli=1&gid=0#gid=0) for more opportunities to contribute.
