### ISSUE TITLE
[Docs]: Issues with Meshery Metrics Guide: Content Inconsistencies and Duplicate Suggested Reading Section

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery#11562]
### Current State
Link: [Meshery Metrics Guide Page](https://docs.meshery.io/guides/performance-management/meshery-metrics)
I found several issues on this page:

- Content does not switch between dynamic and static boards.
- "Suggested Reading" appears twice.

### Desired State
- Different content for dynamic and static boards.
- "Suggested Reading" should appear only once.

![image](https://github.com/user-attachments/assets/263677ad-5977-4fc3-a913-08c78a631315)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by amitamrutiya** [comment]
If you find this issue valid, I would like to work on it.

**Comment by Vaibhav701161** [comment]
please assign this to me!

**Comment by amitamrutiya** [comment]
Yeah, @Vaibhav701161 go ahead.

**Comment by Vaibhav701161** [comment]
@amitamrutiya , Please check my pull request
