### ISSUE TITLE
Docs:  "getting started" link in contributing-cypress page directs to 404 page

### ISSUE THREAD

**Issue by dsawwork** [meshery/meshery#11580]
### Current State
In the Cypress contributing page, the link "getting started" is a dead link.
https://docs.meshery.io/project/contributing/contributing-cypress
![image](https://github.com/user-attachments/assets/71234482-9004-4d86-aaaa-7b036fcd2656)

![image](https://github.com/user-attachments/assets/16a2c28b-3902-4056-b1e2-00d4c7aefb5c)

### Desired State
Guess the getting started page should redirect to https://docs.meshery.io/installation.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Demon-Sheriff** [comment]
I would like to work on this issue.

**Comment by kaushiktak19** [comment]
Hey @dsawwork, 
Can you assign this to me, i have already setup meshery docs to my local machine and am ready to get started with this asap ?

**Comment by charanbhatia** [comment]
@kaushiktak19 I want to work on this issue. As I am a technical content writer, I can easily solve this and also, I will raise the issue as soon as possible

**Comment by dsawwork** [comment]
Hello. Unfortunately, I am not one of the maintainers so I am unable to do this. Maybe you can ping one of the maintainers to get the request done.
