### ISSUE TITLE
[CI] Update Go Unit & Integration GitHub Actions Workflow.

### ISSUE THREAD

**Issue by singh1203** [meshery/meshery#11591]
### Current Behavior

The current GitHub Actions [workflow](https://github.com/meshery/meshery/blob/master/.github/workflows/go-testing-ci.yml) for the Go Unit test & Integration test is using outdated versions of various actions.

Along with the missing Docker Compose install step.
### Desired Behavior

The workflow should be updated to use the latest versions of the GitHub Actions to ensure compatibility and access to the latest features.

Adding Install Docker Compose step.
### Acceptance Tests

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by leecalcote** [comment]
You haven't described why missing docker compose is a problem, @singh1203
