### ISSUE TITLE
Refactor Kubernetes Component Generation Logic 

### ISSUE THREAD

**Issue by humblenginr** [meshery/meshery#11590]
### Current Behavior
Whenever a kubernetes cluster is connected to Meshery, all the Kubernetes CRDs of the cluster are registered as Meshery components. It is handled here - https://github.com/meshery/meshery/blob/master/server/handlers/k8sconfig_handler.go#L299. Currently we have all the logic for generating Meshery components from Kubernetes CRDs in Meshery server. Also, this part of the code does not use the centralised registration logic in meshkit  - https://github.com/meshery/meshkit/pull/550. 

Because of this, we observe the following behaviour:
<img width="460" alt="Screenshot 2024-08-09 at 4 21 52 PM" src="https://github.com/user-attachments/assets/89273c42-e77a-4c7b-81f5-8336676a6b5c">

### Desired Behavior
Kubernetes components should always be registered in context of a Model. 

### Acceptance Tests
- [ ] Kubernetes component registration should use the centralised registration logic from meshkit
- [ ] The logic for generating Meshery components from Kubernetes API (through CRDs) should be moved to meshkit and should reside along Artifacthub and Github package generator logic. 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Shridhar2104** [comment]
can i work on this issue??

**Comment by Ashparshp** [comment]
@Shridhar2104, Still up to work on it?

**Comment by leecalcote** [comment]
This has been delivered in v0.7.100.
