### ISSUE TITLE
[UI] Previously Selected Theme Not Consistent Across Devices 

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery#11606]
### Current Behavior
When I log in with my account on a new device, my previously selected theme doesn't appear until I go to the preferences page.

### Desired Behavior
The theme should be consistent across all devices.

### Screenshots/Logs
[Screencast from 2024-08-10 20-20-36.webm](https://github.com/user-attachments/assets/a05f2966-8795-495b-b431-348b77cbf56f)

### Environment

- Browser: Chrome Firefox
- Host OS:  Linux 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by amitamrutiya** [comment]
My first guess is that this issue is happening because we're storing the theme in local storage, which is causing the inconsistency across devices. If you find this issue valid, I'll fix it—just a bit more debugging is required.

**Comment by amitamrutiya** [comment]
I tried in incognito and got the same issuem

**Comment by Deathnote45** [comment]
can I work on this issue?
