### ISSUE TITLE
Update `BuildArtifactHubPkg` to Ensure Proper Time Format

### ISSUE THREAD

**Issue by humblenginr** [meshery/meshery#11600]
Ideally, we would want this to be handled within the `BuildArtifactHubPkg` in Meshkit. The `BuildArtifactHubPkg` function should take `time` type as a parameter rather than `string`. And inside the `BuildArtifactHubPkg` function, we would try to parse it to RFC3339.

_Originally posted by @humblenginr in https://github.com/meshery/meshery/pull/11595#discussion_r1712306508_

**Comment by leecalcote** [comment]
Awesome, @humblenginr 🙌 .

I created one without knowing this was already filed. The appropriate repo for this issue is meshkit, yeah? And the appropriate labels are on https://github.com/meshery/meshkit/issues/556, I think. Please either mark that issue duplicate and close or this one.
