### ISSUE TITLE
[UI] Notification sidebar filter functionality issue

### ISSUE THREAD

**Issue by thisisharsh7** [meshery/meshery#11619]
### Current Behavior

On applying filter in notification sidebar, the filter does not appear to be applied correctly, resulting in notifications state not updating as expected.

Steps to Reproduce:

1. Navigate to the notification bar by clicking on the notification icon in meshery dashboard .
2. Apply various filter options.
3. Observe that the notifications do not reflect the selected filters.

### Desired Behavior

Filter should work properly

### Screenshots/Logs

![PHOTO-2024-08-11-13-16-52](https://github.com/user-attachments/assets/2df8c79a-4c1a-49d2-980a-38c63a721461)
![PHOTO-2024-08-11-13-30-16](https://github.com/user-attachments/assets/424dc3bc-6449-4fa7-b8e3-ee0ae9786fac)
![PHOTO-2024-08-11-13-30-44](https://github.com/user-attachments/assets/09a5a72d-e9e2-4268-8ca7-17827016cb09)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by thisisharsh7** [comment]
If you find this issue valid, I would be interested in working on it. Could you please assign it to me?

**Comment by Aviral0702** [comment]
@thisisharsh7  This is a duplicate of [issue](https://github.com/meshery/meshery/issues/11458), for which a pull request has been opened. You may open a different issue or work on another one.
