### ISSUE TITLE
Tables are not fully responsive on small screens, leading to content being cut off or not displayed properly.

### ISSUE THREAD

**Issue by vaishnaviadhau** [meshery/meshery#11622]
(https://docs.meshery.io/reference/mesheryctl)

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by akankshat05** [comment]
I can take up this task. Please assign me the task :)

**Comment by Tsu-kimi** [comment]
@vishalvivekm @acald-creator @leecalcote Can I be assigned to fix this

**Comment by leecalcote** [comment]
Thanks for calling out this issue, @vaishnaviadhau and for volunteering, @Tsu-kimi. 👏

**Comment by vaishnaviadhau** [comment]
@leecalcote I was waiting for this issue to be valid , so that I can work on this

**Comment by Tsu-kimi** [comment]
@leecalcote Please reassign it to her @vaishnaviadhau, She was waiting for the issue to be valid. Thank you

**Comment by ashparshp1** [comment]
@vaishnaviadhau, any luck?

**Comment by Ashparshp** [comment]
@vaishnaviadhau, any luck?

**Comment by vaishnaviadhau** [comment]
I am trying to solve this
