### ISSUE TITLE
[UI] Unable to unselect all in the Kubernetes context menu.

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery#11639]
### Current Behavior
In the Meshery Playground, on the Kubernetes context menu, the "Select All" button works perfectly, but the "Unselect" functionality is not working.

### Desired Behavior
Clicking "Select All" should also unselect all items.

### Screenshots/Logs
![image](https://github.com/user-attachments/assets/628cc16c-a2ee-4a2d-bb83-b9e0c89707dc)

### Environment

- Browser:  Firefox
- Host OS:  Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by amitamrutiya** [comment]
If you find this issue valid, I am ready to fix it.

**Comment by Himanshu-kiran** [comment]
![image](https://github.com/user-attachments/assets/85218cad-a3f8-4553-b9d4-9fabf54690e8)
@amitamrutiya can you pls tell how can I add more items I  am unable to do.

**Comment by sudhanshutech** [comment]
@amitamrutiya go ahead

**Comment by sudhanshutech** [comment]
@Himanshu-kiran those are the kubernetes connections . You need to either upload any kube config file from connections page or you can also conenct kubernetes from docker desktop. follow this doc: https://docs.meshery.io/installation/kubernetes
