### ISSUE TITLE
[UI] Add tooltip to the upload/import button on playground meshery

### ISSUE THREAD

**Issue by Utkarsh-NCI** [meshery/meshery#11688]
### Current Behavior
Tooltip is missing  when hovering over upload/import button. 

### Desired Behavior
It should display tooltip when mouse is hovered over on it.

### Screenshots/Logs
https://playground.meshery.io/configuration/designs
![image](https://github.com/user-attachments/assets/b78d5615-6920-485b-b6b8-3d3a02a61ef7)

### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Client Version: stable-v

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
@Utkarsh-NCI why it seems the tooltip is missing? Do we have anywhere tooltip when we hover over button?

**Comment by sparshagl** [comment]
@sudhanshutech I think this is what's being referred to.


![Recording 2024-08-20 022338](https://github.com/user-attachments/assets/318bd356-38c6-4778-b8d6-7f5dcd9f4656)

**Comment by TraXIcoN** [comment]
@sudhanshutech this seems like a valid issue. Can I work on it? I'm new to this project and I feel the functionality requested here is doable for a newcomer.

**Comment by helloworld-chhanda** [comment]
@sudhanshutech please assign me this issue. I can fix this issue.

**Comment by Vicolas11** [comment]
@sudhanshutech please assign me this issue. Thanks
