### ISSUE TITLE
[Server] Stop seeding sample Applications

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11714]
### Current Behavior
Meshery Server loads sample applications at boot time. Applications are no longer a concept in Meshery. Applications have been replaced by Designs.

### Desired Behavior
Stop seeding sample Applications:

```
INFO[2024-08-20T15:48:45-05:00] extracting Applications from /Users/lee/.meshery/content/applications  app=meshery
INFO[2024-08-20T15:48:45-05:00] seeding sample Applications                   app=meshery
DEBU[2024-08-20T15:48:45-05:00] seeding Application: bookinfo                 app=meshery
DEBU[2024-08-20T15:48:45-05:00] seeding Application: emojivoto                app=meshery
DEBU[2024-08-20T15:48:45-05:00] seeding Application: httpbin                  app=meshery
DEBU[2024-08-20T15:48:45-05:00] seeding Application: imagehub                 app=meshery
```

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaishnaviadhau** [comment]
Hi @leecalcote,
I’ve resolved the issue and wanted to check if it’s okay to raise a PR for it.
![Screenshot 2024-09-04 145150](https://github.com/user-attachments/assets/0a6a11de-731e-450c-afa3-872b951658d4)

**Comment by Ashparshp** [comment]
@vaishnaviadhau, please go ahead!
