### ISSUE TITLE
[Docs] New Page Needed: Installing Meshery on RKE2 (Rancher)

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11729]
### Current State
Meshery Docs has a number of installation instructions for individual Kubernetes distributions - https://docs.meshery.io/installation

While much of the installation process is the same across distribution, on occasion, there are small differences. There is no specific set of instructions for installing Meshery on RKE2 (https://docs.rke2.io).

### Desired State
Create a new page with instructions for installing Meshery on RKE2. Use the same format as other Kubernetes installation pages and use `include` to reuse common instructions.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@nunix, help wanted! 😄

**Comment by subho30666** [comment]
@leecalcote  I can help with writing the installation instructions for Meshery in Rancher Government (RKE2). If no one else is currently working on this, please feel free to assign it to me.

**Comment by MU5A** [comment]
@subho30666  Is this done?

**Comment by subho30666** [comment]
@MU5A it's currently on review.

**Comment by subho30666** [comment]
@Ashparshp I have closed the Pr related to this issue.

**Comment by leecalcote** [comment]
Thank you
