### ISSUE TITLE
[Extensions] Visualizer: add link to Meshery Operator installation instructions

### ISSUE THREAD

**Issue by khabdrick** [meshery/meshery#11728]
### Current Behavior
The [visualize page](http://localhost:9081/extension/meshmap?mode=visualize&view=default) for new user has the statement "Ensure that your Kubernetes cluster has Meshery Operator installed." with no link attached to find docs on how to install Meshery Operator.
![2024-08-20_18-26](https://github.com/user-attachments/assets/5d88738e-1b39-4b48-a85f-94ee4641e43a)

### Desired Behavior
Attach the link to install the meshery operator. 
https://docs.meshery.io/guides/troubleshooting/meshery-operator-meshsync

### Mockups
![image](https://github.com/user-attachments/assets/c9bc07e5-3f2a-4fb2-8741-20128c2a14a3)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@amitamrutiya can you wrangle this one?

**Comment by amitamrutiya** [comment]
Sure 👍
