### ISSUE TITLE
Meshery-Istio Adapter Connectivity Issue: 'rpc error: code = Unavailable desc = name resolver error: produced zero addresses'

### ISSUE THREAD

**Issue by yash37158** [meshery/meshery#11758]
### Current Behavior

I am currently running Meshery with Kubernetes and have deployed the Meshery-Istio adapter also deployed. However, I am encountering a persistent issue when attempting to access the adapter via the Meshery UI. The error message is:
`'rpc error: code = Unavailable desc = name resolver error: produced zero addresses.'`
Details:

Meshery Setup:

Meshery is running on Kubernetes.
The Meshery-Istio adapter is deployed as a Docker container.
Issue:

Error message: rpc error: code = Unavailable desc = name resolver error: produced zero addresses.
Mesheryctl is being used for interaction and management.
Logs:

The logs for the Meshery-Istio adapter show that it is up and running.
The logs from the Meshery operator indicate issues with reconciling resources related to the broker.

Steps Taken:

- Verified that the Meshery-Istio adapter container is running.
- Checked the Meshery operator logs for errors related to resource reconciliation.
- Attempted to verify connectivity and service configurations.

### Expected Behavior

The Meshery-Istio adapter should be accessible via the Meshery UI without any errors in local enviroment

### Screenshots/Logs

![image](https://github.com/user-attachments/assets/d0add010-1cad-4332-a2d4-a334433c1837)

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@KunyueXing would you like to tackle this one?

**Comment by KunyueXing** [comment]
Sure, thank you for assigning this issue to me. I'll keep you posted.
