### ISSUE TITLE
[UI] New Section for Connections inside tree view of registry

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#11760]
We support connections for some models like Prometheus, Github, Grafana... but there inside registry we don't show connections we only show components and relationships. Look up the image to add Connections 
![image](https://github.com/user-attachments/assets/f8d4422b-a1c5-4649-92c0-b71938c86307)

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by amitamrutiya** [comment]
I'll make PR soon.

**Comment by amitamrutiya** [comment]
@Jougan-0, could you please provide me with the API endpoint to get connection information?

**Comment by Jougan-0** [comment]
> could you please provide me the API endpoint to get connection information? That has a something like `find connection by model`

Did you get help here? Or are you still stuck?

**Comment by leecalcote** [comment]
Outside of the [REST API docs](https://docs.meshery.io/reference/rest-apis), this [spreadsheet format](https://docs.google.com/spreadsheets/d/1ABJCbfQRi0uN_YoP2kmHZ-lTI4S4QuvRk1_unomKNRE/edit?gid=1241442399#gid=1241442399) might be a helpful reference, @amitamrutiya

**Comment by amitamrutiya** [comment]
@Jougan-0, I'm unable to find an endpoint that lets me retrieve connections from a model name.

We have a this for components -> `api/meshmodels/models/amd-gpu/components?trim=false&search=&page=0&pagesize=all&version=0.12.0`

Can we have similar type of this for registry page ->` api/meshmodels/models/amd-gpu/connections?trim=false&search=&page=0&pagesize=all&version=0.12.0`
