### ISSUE TITLE
[Docs] Missing li tag in extension points

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery#11782]
### Current State
The `<li>` tag is missing in the [Extensions Point](https://docs.meshery.io/extensibility#types-of-extension-points) section.

### Desired State
Add the `<li>` tag there as well.

![image](https://github.com/user-attachments/assets/d6742891-d9c6-411a-85dd-92c694f3bdab)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MohdMusaiyab** [comment]
Can I work on this issue @amitamrutiya ?

**Comment by amitamrutiya** [comment]
Sure @MohdMusaiyab, go ahead. We’ll expect a PR from you soon.

**Comment by aadarshx22** [comment]
Can I work on this issue if its unassigned?

**Comment by MohdMusaiyab** [comment]
@amitamrutiya  

While investigating the issue, I discovered that customised CSS code is applied. Changing this CSS code can completely resolve the issue. Could you please confirm whether this customisation is intentional or if it could be a bug?
![Screenshot from 2024-08-27 19-03-31](https://github.com/user-attachments/assets/6821e0fd-05f7-40ec-96cd-487851a7f6d3)


Thank You!

**Comment by VengefulSpartan** [comment]
Can I be assigned this issue? If it is unassigned.

**Comment by leecalcote** [comment]
@MohdMusaiyab, any progress? Given the size of this issue, I'll assume not and allow @VengefulSpartan to take a crack.

**Comment by Parag003** [comment]
@leecalcote can i work on this issue

**Comment by MohdMusaiyab** [comment]
> @MohdMusaiyab, any progress? Given the size of this issue, I'll assume not and allow @VengefulSpartan to take a crack.

@leecalcote I was able to solve the issue but I didn't make a PR as no one replied to my doubt in the comments above, if you could please reply to that and can confirm that if its intentional or not , I will make the PR.
