### ISSUE TITLE
[Docs] Extra spacing on architecture table for two row

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery#11781]
### Current State
In [this table](https://docs.meshery.io/concepts/architecture#components-their-purpose-and-languages), the MeshSync and Broker rows have extra spacing on the left side.

### Desired State
Remove the extra padding to make it consistent with the other rows.

![image](https://github.com/user-attachments/assets/c9646144-3dc4-4d65-9350-15d0802e608d)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ChinoUkaegbu** [comment]
Hi, could I be assigned to this?
