### ISSUE TITLE
[Relationships] Namespaces should not contain other namespaces

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11801]
### Current Behavior
The relationship definition in the Kubernetes model allows a hierarchical relationship between namespaces.

### Expected Behavior
Namespaces can only be siblings.

### Screenshots/Logs
<img width="939" alt="Screenshot 2024-08-26 at 3 40 17 PM" src="https://github.com/user-attachments/assets/f4613f68-6140-40f7-9f9b-ce8a4a5ac35d">

### Environment

- **Host OS:** Linux
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v0.8.0-beta.1

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Nandika-A** [comment]
Hi @leecalcote! Can I work on this issue?
