### ISSUE TITLE
[CI] Add new PR labeler rule for *.rego files

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11849]
### Current Behavior
PRs opened with Rego code do not get an "opa" label assigned automatically.

### Desired Behavior
Ideally, the "opa" issue/pr label is automatically assigned to any pull request opened with files whose extension is `.rego`.

<img width="66" alt="Screenshot 2024-08-29 at 1 56 22 PM" src="https://github.com/user-attachments/assets/5fd8db07-d2c5-4eda-bed5-cea187f2731e">

### Implementation
Extend the existing PR labeler configuration to include this rule.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by rissh** [comment]
Hey,

I want to give it a try and work on this issue. Can you please assign me this issue?
Please don't hesitate to give me any suggestions or guidance as I work on this task. I'm open to feedback and would appreciate any insights you have.

Thank you!

**Comment by shinigami-777** [comment]
Hi @leecalcote , I'm just starting to get familiar with the Meshery repo and would like to contribute. This issue seems like a good fit for me. Could you please assign it to me?

**Comment by leecalcote** [comment]
Thanks for working on this @rissh.
