### ISSUE TITLE
List the Helm Plugin for Meshery Snapshots on the Meshery Extensions page

### ISSUE THREAD

**Issue by Aijeyomah** [meshery/meshery#11866]
### Desired Behavior
We need to add the Helm Plugin for Meshery Snapshots to the Meshery Extensions page on the website.

### Implementation
1. Reference https://helm.sh/docs/topics/plugins/
2. Reference https://docs.meshery.io/extensions/snapshot
3. Reference https://github.com/marketplace/actions/meshmap-snapshot
4. Design Spec [design spec](https://docs.google.com/document/d/1NdgLoOS3Xy1Z3vwB1dnZ9ETyKCrSinVgAzL8UO3UeQk/edit)

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aijeyomah** [comment]
@Aviral0702

**Comment by leecalcote** [comment]
@Aviral0702 ?

**Comment by Aviral0702** [comment]
> @Aviral0702 ?

I will add the helm plugin today.
