### ISSUE TITLE
Add Meshery-design-embed extension to Meshery-UI

### ISSUE THREAD

**Issue by Aviral0702** [meshery/meshery#11864]
### Desired Behavior

Add Meshery-design-embed extension card to Meshery-UI.
### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@Aviral0702 are you adding this to meshery.io/extensions, too?

**Comment by Aviral0702** [comment]
> @Aviral0702 are you adding this to meshery.io/extensions, too?

Yes Sir, already opened a PR for that.
