### ISSUE TITLE
The dropdown used for selecting the version in the documentation can be enhanced.

### ISSUE THREAD

**Issue by bhavya-D** [meshery/meshery#11876]
### Current State
If the selected version is v0.6 but the dropdown option text does not update to V0.6, even though the URL reflects that V0.6 is selected.
![image](https://github.com/user-attachments/assets/64b9b45f-0b37-423f-8aa8-a009265b8bd5)

### Desired State
It can be changed to this 
The version selector displays the same version that is present in the URL
![image](https://github.com/user-attachments/assets/9fb02f3b-b2d7-4c19-a18c-06fea2e37a7a)

I can work on this issue 
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaishnaviadhau** [comment]
hi @bhavya-D , this issue is already open as #11554

**Comment by leecalcote** [comment]
@vaishnaviadhau ETA on a fix?

**Comment by vaishnaviadhau** [comment]
@leecalcote I will definitely have this fixed by Tuesday.

**Comment by karthikeyan-v-max** [comment]
Hey, I also going through this issue, I will also work to close this issue

**Comment by karthikeyan-v-max** [comment]
Hi @bhavya-D  can you please assign this issue to me
