### ISSUE TITLE
[CI] `version` is a deprecated property of Docker Compose files

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11875]
### Current Behavior
Meshery users who deploy Meshery on Docker using `mesheryctl system start` as a platform see the following warning:

```
.../.meshery/meshery.yaml: `version` is obsolete
```

### Desired Behavior
Ideally, users don't see any warning message.

### Implementation
1. Remove the`version` property from Meshery's docker-compose files under the `/install` folder.

### Acceptance Tests
1. Users can still `system start` a Meshery deployment on Docker, but don't see this warning message.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by Raghav1783** [comment]
hi @leecalcote i would like to work on this
