### ISSUE TITLE
The documentation that is used for Guiding the steps to create a meshrey design can be enhanced 

### ISSUE THREAD

**Issue by bhavya-D** [meshery/meshery#11874]
### Current State
![image](https://github.com/user-attachments/assets/4bddec88-41c4-43b9-acec-a3c5d18ea37f)

### Desired State

My Suggestion
![image](https://github.com/user-attachments/assets/a6c2ee41-237d-4ec0-8742-1b710588f82a)

The subheading "Ways to Create a Meshery Design" can also be "Methods to Create a Meshery Design" or "Design Creation Approaches."

I can work on making this change

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by anishbista60** [comment]
@bhavya-D please assign it to me .

**Comment by bhavya-D** [comment]
I am waiting for it to get assigned to me
