### ISSUE TITLE
[Docs] Create Newcomer's meeting attendance folder for the week of 09/09/2024

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11929]
### Current Behavior
As a project, we track attendance to the weekly Newcomers meeting under the [_meetings directory](https://github.com/meshery/meshery/tree/master/docs/_meetings). It’s important that each newcomer both feel at ease in the community, and also, comfortable with the process of contributing (in this particular case, using git). 

### Desired Behavior
Each meeting attendee creates attendance record (a file with their name in the filename or their name in the content of the file) in the _meeting directory. The format of this file doesn't matter. What's important is that the attendee get into the groove of git-based contribution.

### Implementation
1. Create a new directory under the [_meetings directory](https://github.com/meshery/meshery/tree/master/docs/_meetings), entitled "week-of-<mm/dd/yyyy>", replacing mm/dd/yyyy the date for the start of the week. This new, empty directory will serve as the landing spot for attendance records.

### Acceptance Tests
1. A new directory is present and is NOT listed as dd/mm/yyyy, but as mm/dd/yyyy.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ENUMERA8OR** [comment]
Please assign me this issue @leecalcote .

**Comment by hridyesh-gupta** [comment]
Can I work on this if it is unresolved?

**Comment by 102vansh** [comment]
can i work on this issue
