### ISSUE TITLE
[Docs] Dead link in Contribute to Models page

### ISSUE THREAD

**Issue by lekaf974** [meshery/meshery#11928]
### Current State
Dead link in Contributing to Models page

If you click on `Model Schema` Link you are redirect to `File not found` current value https://github.com/meshery/schemas/blob/master/openapi/schemas/meshmodels.yml

### Desired State
Click on the link redirect on the right openapi schema file https://github.com/meshery/schemas/blob/master/schemas/constructs/openapi/meshmodels.yml

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Vijaykv5** [comment]
I would love to work on it :)

**Comment by lekaf974** [comment]
@Vijaykv5 here you go

**Comment by Vijaykv5** [comment]
@lekaf974 Added a PR ✅
