### ISSUE TITLE
[UI] Change the toast notification message

### ISSUE THREAD

**Issue by hargunkaur286** [meshery/meshery#11939]
### Current Behavior

When we click on "undeploy" and try to undeploy a design in meshmap, we receive a toast notification about the design being "deployed"

https://github.com/user-attachments/assets/6a9bd97e-b823-4707-bbbc-e50940b8ba28

### Expected Behavior

Since the design is being "undeployed", we would need a notification regarding the undeployment of the design. We can instead write the message like "Undeployed design '_name of the design_' ".

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by 102vansh** [comment]
I would like to solve this issue

**Comment by hargunkaur286** [comment]
Go ahead @102vansh 🚀

**Comment by hargunkaur286** [comment]
@102vansh any luck?

**Comment by Sumitsh28** [comment]
Hey @hargunkaur286 can I work on this issue?

**Comment by hargunkaur286** [comment]
Since we haven't heard back from @102vansh , I am assigning the issue to @Sumitsh28 . please go ahead 🚀

**Comment by theavitw** [comment]
@hargunkaur286  I will do this if there are not any...

**Comment by Sumitsh28** [comment]
@hargunkaur286 , @theavitw I have started working on this issue

**Comment by Raghav1783** [comment]
@hargunkaur286 how do i verify that on the backend it is getting undeployed.
