### ISSUE TITLE
[Extensions] Designs get renamed to "Autogenerated"

### ISSUE THREAD

**Issue by hargunkaur286** [meshery/meshery#11938]
### Current Behavior

In meshmap, whenever we try to import a design and try to give it a name, eg: "cassandra-service" in the below screenshot, it gets updated. But then, when we try to drag-and-drop that design onto the playground, it gets renamed to "Autogenerated".

<img width="1464" alt="Screenshot 2024-09-09 at 4 04 12 PM" src="https://github.com/user-attachments/assets/2557573d-c35e-4854-83f9-b0d1a475de11">

https://github.com/user-attachments/assets/9ce5323c-2ce4-4d57-8cfa-41fe1d8a249a

### Desired Behavior

Design's names shouldn't change to "Autogenerated"

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Nandika-A** [comment]
Hi @hargunkaur286 ! Can you confirm if you are working on this, otherwise can I work on this issue?

**Comment by Ashparshp** [comment]
@hargunkaur286, working on it?
