### ISSUE TITLE
[UI] [Bug] Add a link in the sidebar outline to one of the tutorials and make the sequence of tutorial topics consistent

### ISSUE THREAD

**Issue by KunyueXing** [meshery/meshery#11930]
### Current Behavior
When checking the tutorials on meshery.io, https://docs.meshery.io/guides/tutorials, in tutorials content it listed 4 sub-topics. But only 3 of them has a link in the side bar outline.

![meshery docs](https://github.com/user-attachments/assets/f4bf146f-a930-4c90-bdd4-ddcde4ff5ee0)

### Desired Behavior

1. show a link in the side bar outline to the tutorial -- [Deploying WordPress and MySQL with Persistent Volumes with Meshery](https://docs.meshery.io/guides/tutorials/wordpress-mysql-persistentvolume)
2. adjust the sequence of links in the side bar online, make it consistent to that is listed in tutorials content:

    Kubernetes 

    1. [Exploring Kubernetes CronJobs](https://docs.meshery.io/guides/tutorials/exploring-kubernetes-cronjobs)

    2. [Understanding Kubernetes ConfigMaps and Secrets with Meshery](https://docs.meshery.io/guides/tutorials/kubernetes-configmaps-secrets)

    3. [Exploring Kubernetes Pods with Meshery](https://docs.meshery.io/guides/tutorials/kubernetes-pods)

    4. [Deploying WordPress and MySQL with Persistent Volumes with Meshery](https://docs.meshery.io/guides/tutorials/wordpress-mysql-persistentvolume)

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thank you, @KunyueXing. Good eye.

**Comment by akankshat05** [comment]
@leecalcote Can i work on this issue?

**Comment by leecalcote** [comment]
@KunyueXing were you wanting to work on this?

**Comment by KunyueXing** [comment]
Hi @leecalcote, thanks for asking. I wasn't planning to work on this issue. Feel free to assign this issue to other volunteers. :)
