### ISSUE TITLE
[UI] [Bug] Add links in the side navigation bar to the tutorial pages, make the title and sequence of the topics consistent

### ISSUE THREAD

**Issue by KunyueXing** [meshery/meshery#11933]
### Current Behavior
In the section of Guides & Tutorials in docs.meshery.io, there're several pages lacking link in the side navigation bar:

![doc1](https://github.com/user-attachments/assets/a0cb111e-0c5e-4f70-9b80-33791e82694a)

![doc2](https://github.com/user-attachments/assets/87384f3c-e53f-45c1-864b-e8842ec7986a)

![doc3](https://github.com/user-attachments/assets/13f56879-aa22-49f0-8e4a-1e890ef45340)

Furthermore, some of the titles listed in the navigation bar is not consistent with the page's title. For example, in the Configuring Kubernetes Infrastructure section, it's listed as "Working with Designs" in the navigation bar, while named "Configuring your Cloud Native Infrastructure and Applications" on the page content.

The sequence of the title appeared in the navigation bar is also not consistent with that listed on the page.

This issue is similar to #11930, but with more tasks.

### Desired Behavior
1. Add links in the navigation bar:
   - link to [Envoy WASM Filter Management](https://docs.meshery.io/guides/configuration-management/filter-management), and [Push or Pull a Model Image](https://docs.meshery.io/guides/configuration-management/push-pull-model-image) in Configuring Kubernetes Infrastructure section
   - link to [Mesheryctl system commands](https://docs.meshery.io/guides/mesheryctl/system-commands), and [Upgrading Meshery CLI](https://docs.meshery.io/installation/upgrades#upgrading-mesheryctl-using-homebrew) in Meshery CLI Guides
2. Make the title in the navigation bar consistent with that is listed on the page content in Configuring Kubernetes Infrastructure,Meshery CLI guides, and Performance Management
3. Make the sequence of titles in the navigation bar consistent with that is listed on the page in Configuring Kubernetes Infrastructure,Meshery CLI guides, and Performance Management
4. Fix the problem mentioned in the [comment](https://github.com/meshery/meshery/issues/11933#issuecomment-2337155494) below by @Ashparshp. Make sure that when click on a sidebar link, it will be highlighted and show the selection.
   The pages need to be fixed in Guides & Tutorials sections are,
   - [home / guides / infrastructure management / infrastructure discovery](https://docs.meshery.io/guides/infrastructure-management/registering-a-connection)
   - [home / guides / configuration management / creating a meshery design](https://docs.meshery.io/guides/configuration-management/creating-a-meshery-design)
   - make sure the newly added links in task 1 highlights when clicked

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Nandika-A** [comment]
Hi @KunyueXing ! Can you assign me this issue?

**Comment by Ashparshp** [comment]
@KunyueXing, thanks for the detailed issue! Really appreciate your effort! 

On that note, I'm adding a few more screenshots to highlight an issue where clicking on a sidebar link moves the page but doesn't show the selection like the others. Could you please check for similar issues elsewhere as well?

## Ideal Behavior:
![Ideal](https://github.com/user-attachments/assets/a7f8c750-cbc9-4347-9cd3-ba3266301a32)

## Current Behavior:
![Navigte](https://github.com/user-attachments/assets/f0418e40-ec59-48cd-aed0-60f06794a2ab)

Also, thanks for showing up, @Nandika-A! Let's first confirm whether @KunyueXing is working on this.

@KunyueXing, please confirm working on fixing this, or should we assign someone else?

**Comment by KunyueXing** [comment]
Hi @Ashparshp, thanks for pointing out this problem and I add it to the issue. I'll check if there're similar problems elsewhere.

And thanks for asking, I was not planning to work on this issue. Feel free to assign this issue to others.

**Comment by KunyueXing** [comment]
@Ashparshp, I've checked this problem the whole site @ docs.meshery.io and filed a new issue separately, #11944 . 

I thought it would be better to start a new issue with all those new tasks. So that the volunteer working on this issue only need to worry about links under Guides & Tutorials. And all the other links in the website will be handled in #11944 . Please let me know if there need any adjustments. 

Feel free to assign these issues to other volunteers. :)
