### ISSUE TITLE
[UI] [Bug] Make the links in the sidebar highlighted and show the selection when clicked, and correct some of their path according to the logical order in the sidebar

### ISSUE THREAD

**Issue by KunyueXing** [meshery/meshery#11944]
### Current Behavior

In docs.meshery.io, some of the links in the sidebar won't be highlighted and show the selection when clicked. For example, when click on the [Broker](https://docs.meshery.io/concepts/architecture/broker) in the sidebar, it won't be highlighted and show the selection,
![doc4](https://github.com/user-attachments/assets/211d2896-e1bb-4811-908f-a19e278ebde4)

### Desired Behavior

Here shows an example of the link in the sidebar that is highlighted when clicked. It shows the selection.
![doc5](https://github.com/user-attachments/assets/51c2c7e5-401d-4be0-aa4e-8a6602b24311)

This issue is inspired by the [comment](https://github.com/meshery/meshery/issues/11933#issuecomment-2337155494) and discussed below [#11923](https://github.com/meshery/meshery/issues/11933) 

### Tasks
The links need to be fixed are,
- [home / installation / docker / docker extension](https://docs.meshery.io/installation/docker/docker-extension)
- All pages under `home / installation / kubernetes`
  - AKS
  - EKS
  - GKE
  - HELM
  - KinD
  - Minikube
  - KubeSphere
- All pages under `home / installation / linux Mac`
  - Bash
  - Brew
- [home / installation / windows / scoop](https://docs.meshery.io/installation/windows/scoop)

![doc6](https://github.com/user-attachments/assets/cabacac0-848a-45d6-8a4f-374e6acf5fbf)

- [home / concepts / architecture / broker](https://docs.meshery.io/concepts/architecture/broker), the path of this page should be "home / concepts / architecture **/ operator /** broker" and the selection should be highlighted.
- [home / concepts / architecture / meshsync](https://docs.meshery.io/concepts/architecture/meshsync), the path of this page should be "home / concepts / architecture **/ operator /** meshsync" and the selection should be highlighted.

- All pages under home / concepts / logical / models
  - Components
  - Relationships
  - Policies
  - Connections
  - Credentials
  
  The path of these links should also be "home / concepts / logical **/ models /** xxx" instead of "home / concepts / logical / xxx"

- [home / installation / compatibility matrix](https://docs.meshery.io/installation/compatibility-matrix), when this page is linked at home / extensibility / adapters
![doc7](https://github.com/user-attachments/assets/63311167-34d8-462f-9261-e78f3b5205fe)

- pages under home / project / contributing, as shown in the following pic
![doc8](https://github.com/user-attachments/assets/c7347f38-ed44-47e4-b93c-d4a4dcacc177)
Also need to make sure that their path is logically consistent with that is listed in the sidebar. For example, the End-to-End Testing page path should be in a sub dir of `build & release (ci)` under contributing
![doc9](https://github.com/user-attachments/assets/c8768939-d021-449a-b6c6-744d72ddf991)

- links circled below
![doc10](https://github.com/user-attachments/assets/6aa444fe-06e3-4a81-aaa5-830b415e6cef)

### Environment

- Browser: Chrome 
- Host OS: Mac 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Mandeep56Singh** [comment]
@Ashparshp  I would be happy to work on this issue

**Comment by Ashparshp** [comment]
Thank you, @KunyueXing, for opening this detailed and well-organized issue!

@Mandeep56Singh, this looks great for you to work on. Go ahead; I've assigned it to you.

**Comment by Sumitsh28** [comment]
Hey, @Ashparshp I want to work on this issue.

**Comment by Mandeep56Singh** [comment]
@Sumitsh28  can you wait for two days more, due to some urgent work I wasn't been able to work on it. But I am free now 
so I am going to work on it.

**Comment by Mandeep56Singh** [comment]
@Sumitsh28  have you setup the project ? on windows ? and this issue requires jekyll to be installed. I am having problem installing it.

**Comment by Mandeep56Singh** [comment]
@KunyueXing can you please clarify, this issue to related to meshery docs, so in labels it should have contained jekyll instead of react ?

**Comment by KunyueXing** [comment]
> @KunyueXing can you please clarify, this issue to related to meshery docs, so in labels it should have contained jekyll instead of react ?

Hi @Ashparshp, I'm not familiar with jekyll currently. For a quick reply to @Mandeep56Singh, should we include jekyll in the labels?

**Comment by Ashparshp** [comment]
@vishalvivekm //
