### ISSUE TITLE
[UI] Ensure consistent styling for menu items provided by user account extension

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11941]
### Screenshots/Logs

<img width="126" alt="Screenshot 2024-09-09 at 1 15 52 PM" src="https://github.com/user-attachments/assets/fecb00fa-0cb5-4413-af9a-8b45d2494338">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
fixed here: https://github.com/meshery/meshery/pull/11977
