### ISSUE TITLE
[UI] Support optional download of `Artifact Hub` package when a design is exported.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#11978]
### Current Behavior

Meshery design can be exported in multiple ways, eg: OCI/Meshery Design or in the original format in which the design was imported.
When a design is exported as OCI, along with the design file it also contains "Artifact Hub" package. Example of Artifact Hub [package](https://github.com/meshery/meshery.io/blob/master/catalog/0194ff83-0a43-4b83-9c75-b8f0f32da6b7/0.0.1/artifacthub-pkg.yml).

But when user wants to export the design as a "Meshery Design" but not necessarily in OCI format, the user doesn't have any way to get the "Artifact Hub" package (except for using the API directly).

### Desired Behavior

Meshery server already supports exporting the design with Artifact Hub package by bundling in a targz format, irrespective of format chosen, but Meshery UI doesn't expose the functionality.

Update the export modal, to allow user to choose whether the exported design should also include Artifact Hub pkg file.

If the option is checked, the UI should make a request to download endpoint including the query parameter `pkg=true`. (Refer the REST API docs for Meshery server).
### Implementation

1. Propose a mockup for updated "Export Modal".
2. Update the implementation for "Export Modal".
3. Update the callback function that gets invoked when a design is exported.
### Acceptance Tests

1. Add/update the playwright test for "Export" feature.
### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by akankshat05** [comment]
Can i work on this issue?

**Comment by Tharanishwaran** [comment]
I’d like to work on this issue if it’s still available.can i work on this issue ?

**Comment by theavitw** [comment]
I will do this

**Comment by MUzairS15** [comment]
@akankshat05 Read the description carefully, this requires a mockup for the revamped export modal. Do you have access to Figma?

**Comment by akankshat05** [comment]
> @akankshat05 Read the description carefully, this requires a mockup for the revamped export modal. Do you have access to Figma and mockup ready?

Yes, I have got the access to the figma and mockup.
