### ISSUE TITLE
[Models] Meshery-core: Comment component missing schema

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11981]
### Current Situation
<img width="756" alt="Screenshot 2024-09-11 at 3 56 00 PM" src="https://github.com/user-attachments/assets/6be8109b-c68f-414e-9973-aa7dfda6bd75">

### Proposed Change

---

### General Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Understanding Meshery Models

- 📚 [Models](https://docs.meshery.io/concepts/logical/models)
  - 📚 [Components](https://docs.meshery.io/concepts/logical/components)
  - 📚 [Relationships](https://docs.meshery.io/concepts/logical/components)
- 👨‍💻[Models Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)

 ### Contributing to Meshery Models
 - [Contributing Models](https://docs.meshery.io/project/contributing/contributing-models)
   - [Contributing Components](https://docs.meshery.io/project/contributing/contributing-components)
   - [Contributing Relationships](https://docs.meshery.io/project/contributing/contributing-relationships)

**Comment by Jougan-0** [comment]
@leecalcote Updated the sheet as well.
