### ISSUE TITLE
[CI] Update e2e test result comment formatting with Skipped indicator

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12004]
### Desired Behavior

<img width="1027" alt="Screenshot 2024-09-12 at 10 16 17 AM" src="https://github.com/user-attachments/assets/12be2c58-5880-4386-8569-32a2cce85f2e">

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by 102vansh** [comment]
can i work on this issue

**Comment by yash37158** [comment]
Sorry about the harshness, @102vansh 😅. Don’t let it get you down—there are plenty of other open issues waiting for you to tackle!

> can i work on this issue
