### ISSUE TITLE
Export Design to Helm Chart

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12015]
### Desired Behavior
During execution of deployment operation, Meshery's internal pattern engine has a stage in which is converts Designs to Manifests.

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Tharanishwaran** [comment]
Hi @leecalcote I’d like to work on this issue if it’s still available.can i work on this issue ?

**Comment by leecalcote** [comment]
@Tharanishwaran, sure, if you're able to do so, that'd be great. To verify that you're able to do so, confirm your intended approach to implementation.
