### ISSUE TITLE
Export Design to Kubernetes Manifest

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12016]
### Desired Behavior
During execution of deployment operation, Meshery's internal pattern engine has a stage in which is converts Designs to Manifests. We need to hook-in there and add the ability to export that artifact.

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Tharanishwaran** [comment]
Hi @leecalcote I’d like to work on this issue if it’s still available.can i work on this issue ?

**Comment by leecalcote** [comment]
@Tharanishwaran, I would very much so like it... if you're capable of doing so. Understand this is a moderately difficult issue, however.

**Comment by Tharanishwaran** [comment]
@leecalcote I understand the task may be challenging, but I'm motivated to learn and contribute. I'll dedicate about 14 hours a day to this, focusing on Go and Kubernetes. Any guidance on key areas or resources would be very helpful.

**Comment by Tharanishwaran** [comment]
@leecalcote can i work on this issue

**Comment by leecalcote** [comment]
@Tharanishwaran most certainly, yes. Until you've produced something meaningful, I'll leave the issue unassigned so that it isn't incidentally squatted upon.

**Comment by leecalcote** [comment]
The server API for this feature been delivered in Meshery v0.7.107. Exposure in the UI is needed.

**Comment by Tharanishwaran** [comment]
@leecalcote I'm still committed to this issue and ready to work on the UI implementation. Any specific guidelines for the manifest export feature UI? I'll start with a design proposal and keep you updated on progress.
