### ISSUE TITLE
[Docs] Publish Layer5 Release documents under Meshery Build and Release Strategy

### ISSUE THREAD

**Issue by Aviral0702** [meshery/meshery#12021]
### Desired State
We need to publish the [Layer5 release documents](https://docs.google.com/document/d/1JuegfkG-u1MU_xp_jtLyzCpZ_LzW5-Axb4fA-e6Hb_Y/edit) detailing the responsibilities of a Meshery Release Lead. 

The initial section will be included in the [Meshery Build and Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#heading=h.blih70a9hxp).

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Tharanishwaran** [comment]
can i work on this issue ?

**Comment by Ashparshp** [comment]
@Tharanishwaran, go ahead...

**Comment by Tharanishwaran** [comment]
@Ashparshp Thank you for assigning this to me, I'll start working on it and provide updates soon.

**Comment by Tharanishwaran** [comment]
i can't access to this  [Layer5 release documents](https://docs.google.com/document/d/1JuegfkG-u1MU_xp_jtLyzCpZ_LzW5-Axb4fA-e6Hb_Y/edit)  and  [Meshery Build and Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#heading=h.blih70a9hxp).

**Comment by Tharanishwaran** [comment]
@Aviral0702 @Ashparshp, could you please review PR #12082 addressing issue #12021? Your feedback would be greatly appreciated.
