### ISSUE TITLE
Docs:Documentation Unavailable for importing Design 

### ISSUE THREAD

**Issue by abdulrafayl226825** [meshery/meshery#12038]
### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vishalvivekm** [comment]
Hi @abdulrafayl226825 
Here're couple of docs pages on importing desings: 
- [Import designs to Meshery's extension]( https://docs.meshery.io/extensions/importing-a-design)
- [Import designs to Meshery using cli / ui ](https://docs.meshery.io/guides/configuration-management/importing-designs)

**Comment by abdulrafayl226825** [comment]
I just messed up while founding pages for importing design
