### ISSUE TITLE
Problem with ruby installation on Linux

### ISSUE THREAD

**Issue by Pratik-050** [meshery/meshery#12054]
### Current State
If we follow the current docs to install ruby on linux using rbenv we'll run into an issue "install command not found", while trying to use rbenv install 3.2.2 

We need to install a separate plugin of rbenv to solve this issue.

### Desired State
This plugin should be added to the existing documentation for convenience of the contributors.

OS: Ubuntu 22.04
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by 102vansh** [comment]
Can i do this issue

**Comment by 102vansh** [comment]
can i make pr on this issue

**Comment by Pratik-050** [comment]
Hello If this issue is valid then let me know. @leecalcote @amitamrutiya @yash37158 
We can make the ruby installation much easier with this.

**Comment by Pratik-050** [comment]
Please let me  know if this is a valid issue @hargunkaur286 @vishalvivekm 
It's quite easy to fix.

**Comment by yash37158** [comment]
Hey @Pratik-050, would you please open a post on discussion forum here -> https://discuss.meshery.io/latest[](url)

**Comment by Pratik-050** [comment]
Thanks Yash! sure @yash37158

**Comment by Deathnote45** [comment]
Can I work on this issue? @Pratik-050

**Comment by Pratik-050** [comment]
@Deathnote45 This is not a valid issue yet. You can find other issues meanwhile.
