### ISSUE TITLE
[Designs] Publish Sample Relationships

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12060]
### Current Behavior
Meshery supports many different types of [relationships](https://docs.meshery.io/concepts/logical/relationships) between components.

### Desired Behavior
Users are best served in their understanding of these relationships with examples.

### Implementation
1. Create one design for each type of relationship.
2. Create an all-in-one design with all relationship examples.
3. Publish each design to Meshery catalog.

Child issues need to be opened - one issue for each https://docs.meshery.io/concepts/logical/relationships

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by jamieplu** [comment]
I see that this is an epic issue. I will try to help by creating child issues.

**Comment by marblom007** [comment]
Tagging @Alero-Awani

**Comment by leecalcote** [comment]
@Alero-Awani this should be quick given the existing work that has been done.
