### ISSUE TITLE
[Docs] Adjust the size of the headings of the overview features.

### ISSUE THREAD

**Issue by jamieplu** [meshery/meshery#12077]
### Current State
The way that this page reads might be improved with smaller font - https://github.com/meshery/meshery/blob/master/docs/pages/project/project.md

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by marblom007** [comment]
I suppose that you're right. I think that you mean to point out how it looks on this overview page, right? https://docs.meshery.io/project/overview
