### ISSUE TITLE
[E2E]: Compare results of Performance Test

### ISSUE THREAD

**Issue by jerensl** [meshery/meshery#12085]
### Current Behavior
Currently, Meshery’s E2E tests do not include comprehensive scenarios for comparing performance test results across different runs. This limits the ability to automatically verify comparison on performance test results feature

### Desired Behavior
1. User goto [Performance Profiles](https://playground.meshery.io/performance/profiles) pages.
2. User run multiple performance test in one performance profile.
3. User view the performance test results.
4. User selected multiple performance test result in one performance profile.
5. User click comparison button in top right corner in test profile.
6. User see the comparison modal open.

### Implementation
The test cases will be made under this [file](https://github.com/meshery/meshery/blob/master/ui/tests/e2e/service_mesh_performance.spec.js)

### Acceptance Tests
Develop E2E tests to verify that the UI correctly displays performance comparison results.

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠  [Contributing to Meshery's End-to-End Tests](https://docs.meshery.io/project/contributing/contributing-ui-tests)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ArjuntheSreekumar** [comment]
Yes I can run And Build Mehshery UI and test it using Playwright @jerensl

**Comment by ArjuntheSreekumar** [comment]
I am unable to complete the project as I am unable to display UI results due to my inability please resassign this issue to someone I am sorry for spending three weeks and not providing any substantial results. I have unassigned myself to prevent furthur waste of time.

**Comment by ayushsawant464** [comment]
@jerensl I would like to work on this issue. I am able to build and run meshery and playwright.

**Comment by ayushsawant464** [comment]
hii @jerensl , while working on this issue i found certain test-ids being referenced, however i was unable to locate them by inspecting the page, can u tell me how should i find them or replicate the same behaviour.
