### ISSUE TITLE
Make the permission_constants.js file update automatically

### ISSUE THREAD

**Issue by dragon-slayer875** [meshery/meshery#12080]
### Current Behavior

Meshery UI uses [permission_constants.js](https://github.com/meshery/meshery/blob/3585668965c0d40e785f28c4b0bde379398e9029/ui/utils/permission_constants.js) as a record for accessing keys in code and make permission checks against.
Whenever a new key is added in the provider, this file needs to be manually updated so that the permission check can be implemented in code.

### Desired Behavior

This file should be updated automatically whenever new values are added to the provider so as to eliminate human errors and effort made in updating the file.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Abandoned.
