### ISSUE TITLE
[CI] Dependency: Sistent v0.14.93 - a newer package is available

### ISSUE THREAD

**Issue by ritzorama** [meshery/meshery#12096]
### Current Behavior
I would like to help update this package to the latest version.

### Desired Behavior
In Meshery UI

### Implementation
I won't change any code other than just the dependency.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by jamieplu** [comment]
I think this would be really helpful. I can't assign you to the issue, though, but thank you for volunteering to help, @ritzorama

**Comment by leecalcote** [comment]
I can assist...

**Comment by jamieplu** [comment]
I was just about to tag one of the teams...

**Comment by ritzorama** [comment]
Thanks!

**Comment by jamieplu** [comment]
I think this works, but I'm not sure, because usually the package-lock.json is changed, too.
