### ISSUE TITLE
Extensions for kubectl plugins

### ISSUE THREAD

**Issue by ritzorama** [meshery/meshery#12095]
### Current Behavior
I want to contribute to the kubectl plugin that has been discussed.

I think there are two kubectl plugins needed. I can help! 👋 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Ashparshp** [comment]
@ritzorama, That’s awesome! Please send a message in Slack, and we’ll catch up with you there.

**Comment by leecalcote** [comment]
Three new :meshery: repos created today:
https://github.com/meshery/helm-kanvas-snapshot
https://github.com/meshery/kubectl-kanvas-snapshot
https://github.com/meshery/kubectl-meshsync-snapshot

**Comment by ritzorama** [comment]
Thank you very much, @Ashparshp 👏 I'm in and the community is amazing (just like your help here).

**Comment by ritzorama** [comment]
I'm adding my stars to these repos now! ⭐
