### ISSUE TITLE
[Docs] Create Newcomer's meeting attendance folder for the week of 09/23/2024

### ISSUE THREAD

**Issue by hargunkaur286** [meshery/meshery#12104]
### Current State
As a project, we track attendance to the weekly Newcomers meeting under the [_meetings directory](https://github.com/meshery/meshery/tree/master/docs/_meetings). It’s important that each newcomer both feel at ease in the community, and also, comfortable with the process of contributing (in this particular case, using git).

### Desired State
Each meeting attendee creates attendance record (a file with their name in the filename or their name in the content of the file) in the _meeting directory. The format of this file doesn't matter. What's important is that the attendee get into the groove of git-based contribution.

### Implementation
Create a new directory under the [_meetings directory](https://github.com/meshery/meshery/tree/master/docs/_meetings), entitled "week-of-<mm/dd/yyyy>", replacing mm/dd/yyyy the date for the start of the week. This new, empty directory will serve as the landing spot for attendance records.

### Acceptance Test
A new directory is present and is NOT listed as dd/mm/yyyy, but as mm/dd/yyyy.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Tharanishwaran** [comment]
can i work on this issue ?

**Comment by Tharanishwaran** [comment]
@hargunkaur286 can i work on this issue . can you assign me this issue ?

**Comment by Tharanishwaran** [comment]
@hargunkaur286 can i work on this issue ?

**Comment by hargunkaur286** [comment]
Please go ahead @Tharanishwaran

**Comment by vishalvivekm** [comment]
@Tharanishwaran I see you've been working on other items as well.
Let's reserve this for first-timers.

**Comment by Tharanishwaran** [comment]
@vishalvivekm  I understand and fully respect reserving this issue for first-timers. I'll step aside to let them take it on.

**Comment by Tharanishwaran** [comment]
@vishalvivekm  I understand and fully respect reserving this issue for first-timers. I'll step aside to let them take it on.

**Comment by vishalvivekm** [comment]
> @vishalvivekm I understand and fully respect reserving this issue for first-timers. I'll step aside to let them take it on.

Thank you for your understanding @Tharanishwaran

**Comment by batmnnn** [comment]
@hargunkaur286 @vishalvivekm can i try this issue ?

**Comment by hargunkaur286** [comment]
@batmnnn May I know if you have the project setup locally?

**Comment by batmnnn** [comment]
@hargunkaur286 no but I can set it up by evening (maybe with a little help)

**Comment by hargunkaur286** [comment]
Have you referred the [Meshery](https://docs.meshery.io/project/contributing) contribution guide? Specifically [this](https://docs.meshery.io/project/contributing/contributing-ui#setup) page for instructions on setting up the repository?

**Comment by batmnnn** [comment]
Okay I'll do it asap, @hargunkaur286

**Comment by Deathnote45** [comment]
can I work on this issue @hargunkaur286 ?

**Comment by snehaio** [comment]
hi. i am first timer, can i work on this @hargunkaur286 ?

**Comment by snehaio** [comment]
09-23-2024 folder was already present so i added for the upcoming week 09-30-2024
