### ISSUE TITLE
[E2E]: Delete a connection from Meshery connection pages

### ISSUE THREAD

**Issue by jerensl** [meshery/meshery#12115]
### Current Behavior
Currently, Meshery’s E2E tests do not include test scenarios for deleting Kubernetes cluster connections.

### Desired Behavior
1. User goes to [Connection Page](https://playground.meshery.io/management/connections) pages.
2. The user checks Kubernetes clusters by name.
3. The user clicks the delete button on the top right corner of the connection table.
4. The user confirms the Kubernetes cluster has been deleted by notification and not appearing on the connection table.
5. The user clicks the comparison button in the top right corner of the test profile.
6. The user sees the comparison modal open.

### Implementation
The test cases will be made under this [file](https://github.com/meshery/meshery/blob/master/ui/tests/e2e/connections.spec.js)

### Acceptance Tests
Develop E2E tests to verify the deletion of Kubernetes cluster on connection pages.

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Contributing to Meshery's End-to-End Tests](https://docs.meshery.io/project/contributing/contributing-ui-tests)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ianrwhitney** [comment]
@jerensl I can try to take a stab at this one.

**Comment by jerensl** [comment]
Hi @ianrwhitney, thank you for first showing interest, are you able to build and run Meshery UI & Server, Playwright, and Kubernetes cluster accordingly?

**Comment by Deathnote45** [comment]
Can Work On this Issue?

**Comment by jerensl** [comment]
@Deathnote45 Thank you for showing interest. As this has already been assigned, feel free to contribute to other issues

**Comment by TylrDn** [comment]
@jerensl was this resolved? Can I take over if no PR has been made for this issue and its been a month?

**Comment by ianrwhitney** [comment]
Hey @TylrDn, thanks for your interest. PR is open and about to be merged. Look around and see if another issue needs help! Thanks!

**Comment by TylrDn** [comment]
@ianrwhitney Hey Ian thanks for the response. On another note, can you proofread this Meshery UI Template: (Meshery UI) and then grant me permission to publish to catalog per #12503? 

https://github.com/meshery/meshery/issues/12503

Please advise, I have another task I would like to complete today for an AWS template and will have a similar PR process to replicate.
