### ISSUE TITLE
[UI] Migrate Error Boundary to Functional Component and Use MUI v5 supported Sistent component

### ISSUE THREAD

**Issue by SAHU-01** [meshery/meshery#12118]
### Current Behavior

This [ErrorBoundary](https://github.com/meshery/meshery/blob/268c1667a6ab6a8bbdcbd960df20023d8ecbfb3a/ui/components/ErrorBoundary.js#L9) Component is a `class-based` component and it uses MUI v4's `Box` component. These need to be updated for improved performance and consistency.

### Desired Behavior

- [ ] migrate class-based component to a functional component
- [ ]  add a Sistent Button component needs to be used

### Acceptance Tests
 The component must be updated without introducing any breaking changes in functionality or theming across all instances where it is used.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Mandeep56Singh** [comment]
I want to work on this.

**Comment by Sumitsh28** [comment]
@SAHU-01 Please assign this to me

**Comment by Mandeep56Singh** [comment]
@leecalcote  I want to work on this, Please assign it to me.

**Comment by SAHU-01** [comment]
@Mandeep56Singh and  @Sumitsh28 could you confirm if you were successful in setting up the site locally, accordingly, I'll be able to break down the task and assign it to both of you? If not, please let me know as well.

**Comment by Ajay-singh1** [comment]
Hats Off to you @SAHU-01 🤩

**Comment by Mandeep56Singh** [comment]
@SAHU-01 yeah.., running in local

**Comment by SAHU-01** [comment]
> @SAHU-01 yeah.., running in local

That's great @Mandeep56Singh, as I've already assigned you and @Sumitsh28, 1 issue each once your current issue is closed and the PR is merged you can ask for an assignment to this issue.

For now I'd call upon other contributors who are interested to take this up, thanks!

**Comment by THEBOSS0369** [comment]
Hey @SAHU-01 ! Can i work on this issue? I have setted up the server locally. Please confirm that this is the correct repo. Thanks 
![image](https://github.com/user-attachments/assets/9bd58d9c-207b-40ba-9bdb-f0b5ead6bfb2)

**Comment by SAHU-01** [comment]
That's awsome @THEBOSS0369 , sure I'll assign it to you, let me know if you face any issue or need more clarification.

**Comment by THEBOSS0369** [comment]
Hey @SAHU-01 Update regarding this issue, i haven't actually started working on this issue due to my college exams. My exams will end on 9 Oct, so i will start working on this after 9 will that be fine? Thanks !

**Comment by SAHU-01** [comment]
Hey @THEBOSS0369 we have another contributor who has made a PR for this issue, I'll be opening a couple of more issues this week you can comment and get them assigned.

**Comment by THEBOSS0369** [comment]
Hey @SAHU-01 ! Got it can you give me more details like for this `ErrorBoundary` component only or for any other component or file.

**Comment by THEBOSS0369** [comment]
Hey @SAHU-01 ! I have created a PR for this issue #12354 , please review it and give the necessary feedbacks for this. Thanks!

**Comment by THEBOSS0369** [comment]
Hey @SAHU-01 ! Please review my PR #12439 for this issue , Also it has been already reviewed by ianrwhitney so please check it and then i can work on different issues. Thanks
