### ISSUE TITLE
Create Unit and Integration Tests for `mesheryctl exp relationships` Command

### ISSUE THREAD

**Issue by Aijeyomah** [meshery/meshery#12136]
### Description
We need to develop comprehensive unit and integration tests for the `mesheryctl exp relationships` command. This command is responsible for listing, viewing, and searching MeshModel relationships, as well as generating relationship documents.

The goal is to ensure the correctness of the core functionalities, error handling, and interaction with the Meshery server.

### Current Behavior
Currently, there are no automated tests covering the `mesheryctl exp relationships` command, which includes:
[] Listing relationships (`mesheryctl exp relationships list`)
- Viewing details of a specific relationship (`mesheryctl exp relationships view`)
- Searching for relationships (`mesheryctl exp relationships search`)
- Handling interaction with the Meshery server and command prerequisites (e.g., server running, version validation).

### Desired Behavior
Tests should cover the following aspects:

1. **Unit Tests**:
   - **Model Prompt Selection**: Verify that the `selectRelationshipPrompt` function correctly displays and returns a relationship when multiple options are available.
   - **Argument Validation**: Ensure that missing or invalid arguments (e.g., invalid model names) trigger the appropriate error messages.
   - **Subcommand Handling**: Verify that invalid subcommands trigger the appropriate error messages.
   
2 **Integration Tests**:
   - **Server Interaction**: Mock the Meshery server and verify that the command correctly interacts with it, including:
     - Validating that the server is running.
     - Handling failed connections or invalid credentials.
     - Properly fetching and displaying relationships data.
   - **Data Retrieval and Display**: Ensure that relationships data is correctly retrieved, parsed, and displayed in both JSON and YAML formats.
   
4. **Error Handling**:
   - Handle cases where the Meshery server is unavailable.
   - Handle invalid or missing credentials.
   - Handle improper arguments or subcommands.

### Checklist:
- [ ] Listing relationships (`mesheryctl exp relationships list`)
- [ ] Viewing details of a specific relationship (`mesheryctl exp relationships view`)
- [ ] Searching for relationships (`mesheryctl exp relationships search`)
- [ ] Handling interaction with the Meshery server and command prerequisites (e.g., server running, version validation).

### Implementation
- Use mock APIs to simulate interaction with the Meshery server and return test data for relationships.
- Use existing testing frameworks and patterns for `mesheryctl`.
- Follow Meshery's contribution guidelines for writing tests.

### Resources
- The file to be tested: `mesheryctl/internal/cli/root/exp/relationships.go`
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Deathnote45** [comment]
can I work on this issue @Aijeyomah

**Comment by pontusringblom** [comment]
@Deathnote45, awesome! @Aijeyomah, will you be breaking this down into smaller, child issues so that multiple contributors can work on these?

**Comment by Deathnote45** [comment]
> @Deathnote45, awesome! @Aijeyomah, will you be breaking this down into smaller, child issues so that multiple contributors can work on these?

yes please

**Comment by yaten2302** [comment]
@Aijeyomah @leecalcote , may I give this a try?

**Comment by lekaf974** [comment]
@thesujai what is current status for this issue, have already started working on it ?

**Comment by thesujai** [comment]
Yes I am working on it. Will raise a PR by tomorrow. Thank you

**Comment by yaten2302** [comment]
Since this issue has been inactive for 2 weeks, can this be assigned to me?
@leecalcote @vishalvivekm

**Comment by leecalcote** [comment]
@thesujai, any progress to report?

**Comment by thesujai** [comment]
Yes am working on it, I have opened a discussion for this as well where I was blocked by somethings. 

Still if someone wants to work on this please do submit a PR, my blocker should not block you to contribute:)
