### ISSUE TITLE
Relocate .regal to `/policies` directory.

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#12139]
**Current Situation***

`meshery/meshery`'s root directory contains a `.regal` folder.

***Desired Situation**

The `.regal` folder is relocated to  `/policies` folder.

**Acceptance Criteria**

1. Regal linter continues to work.

---
[Slack Message](https://layer5io.slack.com/archives/CDM0ACDM5/p1727363051300079?thread_ts=1727363051.300079&cid=CDM0ACDM5)

**Comment by moiz2405** [comment]
Hi, @Jougan-0 this is my first time contributing here so I started with a simple and easy Issue. I'd be happy if you can guide me through the process through reviews and suggestions for the future contributions.
