### ISSUE TITLE
[Server] Register latest model version only at boot

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12155]
### Current Behavior
Meshery tracks and supports many versions of its components and their models. Quite commonly duplicate components are not needed at all versions of a given model.

### Desired Behavior
By default,  Meshery Server will ideally only load the latest version of each model.

In addition to performance, lack of relationship duplication, this also has the added benefit of showing users an accurate model and component count upon boot and log into Meshery UI, not inflated numbers with duplicate components.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Jougan-0** [comment]
Completed
