### ISSUE TITLE
[Docs] Add Embedded Designs for Each Meshery Design Relationship in Meshery Doc 

### ISSUE THREAD

**Issue by Alero-Awani** [meshery/meshery#12166]
### Current State
The eight types of relationships described in the [Meshery Relationships Documentation](https://docs.meshery.io/concepts/logical/relationships) are currently represented as static SVG images. 

### Desired State
To enhance interactivity, these relationships should have Mehsery embedded designs, allowing users to explore them interactively instead of relying solely on static SVGs.

The eight types of relationships to visualize and embed are:

1. Hierarchical - Parent - Inventory
2. Hierarchical - Parent - Wallet
3. Hierarchical - Sibling - MatchLabel
4. Edge - Binding - Mount
5. Edge - Binding - Permission
6. Edge - Binding - Firewall
7. Edge - Non-binding - Network
8. Edge - Non-binding - Annotation

**Resources** 

1. [ How to Embed Meshery Designs ](https://docs.layer5.io/kanvas/designer/embedding-designs/)
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Deathnote45** [comment]
hi, can I work on this issue @Alero-Awani ?
