### ISSUE TITLE
[UI] Migrate Meshery Play Component to Functional Component with MUI v5 Styling and Sistent Component use

### ISSUE THREAD

**Issue by SAHU-01** [meshery/meshery#12169]
### Current Behavior
This [MesheryPlayComponent](https://github.com/meshery/meshery/blob/764d510d136d0e6640d7d5dc2f2e55c759c0be7c/ui/components/MesheryPlayComponent.js#L86) Component is a class-based component and it uses MUI v4's styling. These need to be updated for improved performance and consistency.

### Desired Behavior
- [ ]  migrate class-based component to a functional component
- [ ]  use [Sistent](https://github.com/layer5io/sistent) components for  MUI v4 to MUI v5 migration

Sistent is our design system that uses MUI v5, you can also refer to this [doc](https://docs.meshery.io/project/contributing/contributing-ui-sistent) to understand how to use Sistent.

### Acceptance Tests
The component must be updated without introducing any breaking changes in functionality or theming across all instances where it is used.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Deathnote45** [comment]
hi, can I work on this issue?

**Comment by SAHU-01** [comment]
Sure @Deathnote45 , you can send a PR regarding a fix for:

- [ ] use Sistent components
- [ ]  migrate MUI v4 styling to MUI v5 supported styling

In a single PR or two different PRs based on your comfort level, and let me know if you need anymore clarification on this.

**Comment by Pratik-050** [comment]
Hi @Deathnote45 are you still working on this? or else @SAHU-01 assign this to me.

**Comment by SAHU-01** [comment]
@Pratik-050, @Deathnote45 is working on the following: use Sistent components, migrate MUI v4 styling to MUI v5 supported styling.

IF you wish you can work on migrate class-based component to a functional component, I'll assign it to you!

**Comment by Pratik-050** [comment]
> @Pratik-050, @Deathnote45 is working on the following: use Sistent components, migrate MUI v4 styling to MUI v5 supported styling.
> 
> IF you wish you can work on migrate class-based component to a functional component, I'll assign it to you!
OK sure

**Comment by SAHU-01** [comment]
Could you confirm if you are able to run meshery locally, i.e. ia your setup ready?
Let me know if you need assistance.

**Comment by Pratik-050** [comment]
Yes my local setup is working fine.
