### ISSUE TITLE
This (meshery) code repository is really big. Is there any way to optimize it?

### ISSUE THREAD

**Issue by jinronga** [meshery/meshery#12174]
### Proposed Change

---
This (meshery) code repository is really big. Is there any way to optimize it?
![image](https://github.com/user-attachments/assets/b3ffb815-e8f7-4226-aeb2-6a89d0cf056c)

### General Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Understanding Meshery Models

- 📚 [Models](https://docs.meshery.io/concepts/logical/models)
  - 📚 [Components](https://docs.meshery.io/concepts/logical/components)
  - 📚 [Relationships](https://docs.meshery.io/concepts/logical/components)
- 👨‍💻[Models Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)

 ### Contributing to Meshery Models
 - [Contributing Models](https://docs.meshery.io/project/contributing/contributing-models)
   - [Contributing Components](https://docs.meshery.io/project/contributing/contributing-components)
   - [Contributing Relationships](https://docs.meshery.io/project/contributing/contributing-relationships)

**Comment by omgupta-iitk** [comment]
maybe you can try doing this, if you are not interested with the old commits data, this will reduce the size of the download and speeds up the cloning process by skipping older commits and history.
```
git clone --depth 1 <repo_url>
```
