### ISSUE TITLE
[Docs] API Reference: "How to get your token" section needs updated to clarify between Local and Remote Providers

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12184]
### Current State
See this section and it's lack of distinction between the two providers - https://docs.meshery.io/extensibility/api#how-to-get-your-token)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@ianrwhitney fyi...

**Comment by Deathnote45** [comment]
Hi, can I fix this issue?

**Comment by ianrwhitney** [comment]
@leecalcote thanks for raising this issue. I will follow and review. Since i dont have things squared away on my local depolyment, i am not sure i can contribute accurately yet to this document.
