### ISSUE TITLE
[UI] Theme was not change on the first click from preferences

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery#12218]
### Desired Behavior
Theme should be change on the first click

### Screenshots/Logs
[Screencast from 2024-10-02 20-27-24.webm](https://github.com/user-attachments/assets/d3040b3a-3b48-4afc-89b7-fd167008e6ff)

### Environment

- Browser: Firefox
- Host OS:  Linux 
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by dhananjay-Byte** [comment]
hey @amitamrutiya i would like to work on this issue.

**Comment by amitamrutiya** [comment]
@dhananjay-Byte thanks for showing interest. I want to know if you have set up the meshery locally before being assigned.

**Comment by dhananjay-Byte** [comment]
@amitamrutiya no i have not set up the meshery locally. can you please provide me the instructions?

**Comment by dhananjay-Byte** [comment]
@amitamrutiya do i have to run the meshery server to fix this issue?

**Comment by Tharanishwaran** [comment]
Hi @amitamrutiya I have successfully set up meshery locally and I'm ready to work on this issue. Please assign it to me.

**Comment by amitamrutiya** [comment]
Since I don't heard back from @dhananjay-Byte I will assign this issue to @Tharanishwaran. @dhananjay-Byte feel free to explore other issues that we had.

**Comment by Tharanishwaran** [comment]
@amitamrutiya Thanks for assigning me! I'll start working on it and update you soon

**Comment by shivang-tripati** [comment]
> @amitamrutiya Thanks for assigning me! I'll start working on it and update you soon

hey what is the progress ?? if you are not working on that let me know i would like to explore it...

**Comment by Tharanishwaran** [comment]
@shivang-tripati, I'm still working on this. I'll update soon.

**Comment by Ekam219** [comment]
may i work on this issue it will be my first contribution in open source.

**Comment by kingdarabahmad** [comment]
@amitamrutiya I have solved the issue Assign it to me .

**Comment by Divyansh200102** [comment]
> @amitamrutiya I have solved the issue Assign it to me .

How did you fix it?

**Comment by Tharanishwaran** [comment]
Hi @kingdarabahmad, I am the assigned for this issue and have already fixed it. I'll be submitting my PR soon.
