### ISSUE TITLE
[UI] Migrate Custom Toolbar Select Component to use MUI v5 Styling and Sistent Component

### ISSUE THREAD

**Issue by SAHU-01** [meshery/meshery#12219]
### Current Behavior
This [CustomToolbarSelect](https://github.com/meshery/meshery/blob/5e7e59a2de62d45f3ba9aa8e89a832dc4f09a059/ui/components/CustomToolbarSelect.js#L30) Component uses MUI v4's styling. This needs to be updated for improved performance and consistency.

### Desired Behavior
- [ ]  use [Sistent](https://github.com/layer5io/sistent) components for  MUI v4 to MUI v5 migration

Sistent is our design system that uses MUI v5, you can also refer to this [doc](https://docs.meshery.io/project/contributing/contributing-ui-sistent) to understand how to use Sistent.

### Acceptance Tests
The component must be updated without introducing any breaking changes in functionality or theming across all instances where it is used.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by SAHU-01** [comment]
@JAYANTJOSHI001 could you confirm if you were successful in setting up the site locally, accordingly, I'll be able to  assign it to of you? If not, please let me know as well.

**Comment by JAYANTJOSHI001** [comment]
@SAHU-01 i have successfully set repo in local host. Kindly assign it.

**Comment by Karan-Palan** [comment]
Hey @JAYANTJOSHI001 , if you are not working on the ticket, I'll pick it up

**Comment by JAYANTJOSHI001** [comment]
Hey @Karan-Palan , i working on this ticket currently.

**Comment by Karan-Palan** [comment]
Okay
