### ISSUE TITLE
[UI] Make the json data foramtted into design card

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery#12220]
### Current Behavior
When we click on the design card on the design page there is raw json data.

### Desired Behavior
Converted into formatted JSON data.

### Screenshots/Logs
![image](https://github.com/user-attachments/assets/6e6380bc-388b-41c1-95b9-e6c4618d18f4)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by NawinKumarSharma** [comment]
@amitamrutiya can you assign me? i want to work on this

**Comment by amitamrutiya** [comment]
@NawinKumarSharma  thanks for showing interest. I want to know if you have set up the meshery locally before being assigned.

**Comment by JAYANTJOSHI001** [comment]
@NawinKumarSharma is this issue available to assign as I want to work on it

**Comment by amitamrutiya** [comment]
> @NawinKumarSharma thanks for showing interest. I want to know if you have set up the meshery locally before being assigned.

@JAYANTJOSHI001 same question for you?

**Comment by moiz2405** [comment]
hi @amitamrutiya, I would like to be assigned and work on the issue, I have setup meshery locally and am able to run the build withoud problems at localhost

**Comment by sahilshityalkar** [comment]
Hi @amitamrutiya,

I’ve already forked the repository, set up Meshery locally, and reviewed the issue thoroughly. I’m confident that I can implement a clean solution to format the JSON data on the design card. This task fits perfectly with my skill set, and I’m eager to get started.

Could you kindly assign this to me? I’m ready to dive in.

**Comment by JAYANTJOSHI001** [comment]
> > @NawinKumarSharma thanks for showing interest. I want to know if you have set up the meshery locally before being assigned.
> 
> @JAYANTJOSHI001 same question for you?

@amitamrutiya i have forked this repo and i have contributed in meshery earlier also, so i have some sort of experience on how things work in meshery. Kindly assign it.

**Comment by amitamrutiya** [comment]
@JAYANTJOSHI001 Since you asked earlier, I will assign this issue to you. We'll expect a PR from you soon. @moiz2405 @sahilshityalkar @NawinKumarSharma feel free to explore the other issue that we had.

**Comment by kingdarabahmad** [comment]
@amitamrutiya  can you assign this to me .

**Comment by amitamrutiya** [comment]
@JAYANTJOSHI001 what's the progress? Are you stuck anywhere?

**Comment by JAYANTJOSHI001** [comment]
@amitamrutiya yeah having problem in doing it, kindly assign it to someone else as i am not able to figure it out.

**Comment by kingdarabahmad** [comment]
<img width="1400" alt="Screenshot 2024-10-15 at 6 58 26 PM" src="https://github.com/user-attachments/assets/b213a8cf-e1cd-4841-8468-f54f7b88b6c5">
<img width="1400" alt="Screenshot 2024-10-15 at 6 54 20 PM" src="https://github.com/user-attachments/assets/1c616fa9-e4bd-4109-9214-1a8e6a564b49">

@amitamrutiya  isn't it formated??

**Comment by amitamrutiya** [comment]
This is the yaml data. JSON data is not formatted. Go ahead @kingdarabahmad and come up with the fix.

**Comment by kingdarabahmad** [comment]
@amitamrutiya  i have formatted the data like this can you please confirm.

screenshot 1 : Not fullscreen
<img width="1421" alt="Screenshot 2024-10-15 at 11 33 00 PM" src="https://github.com/user-attachments/assets/b6e0d19a-ad88-4407-9a3a-a68988b7e879">

screenShot 2 : In fullscreen mode 
<img width="1421" alt="Screenshot 2024-10-15 at 11 33 18 PM" src="https://github.com/user-attachments/assets/3a237403-8d88-40c5-86b5-137f5efef9ad">

**Comment by leecalcote** [comment]
@amitamrutiya, this is a regression issue, yes? We previously displayed well-formatted JSON here. What change was made causing this regression and can that be reverted?

**Comment by amitamrutiya** [comment]
I am not sure if this is a regression issue or not @leecalcote. @sudhanshutech will you confirm that?

**Comment by eyeaadil** [comment]
hi @amitamrutiya, I would like to be assigned and work on the issue, I have setup meshery locally and am able to run the build withoud problems at localhost

**Comment by eyeaadil** [comment]
hi @amitamrutiya,If teh issue is not resolved I would like to be assigned and work on the issue, I have setup meshery locally and am able to run the build withoud problems at localhost.can you assign to me?
