### ISSUE TITLE
[Docs] rbenv installation not working properly following instructions

### ISSUE THREAD

**Issue by lekaf974** [meshery/meshery#12230]
### Current State

Following the instructions provided for linux https://docs.meshery.io/project/contributing/contributing-docs#for-linux

After installing rbenv there is an error

```bash
root@e0b53475f1d4:/# rbenv install 3.2.2
rbenv: no such command `install'
```

### Desired State

Add the proper step in the documentation to make it works

from rbenv official [documentation](https://github.com/rbenv/rbenv?tab=readme-ov-file#installing-ruby-versions) it required `ruby-build` installation

this can be done following this steps https://github.com/rbenv/ruby-build?tab=readme-ov-file#clone-as-rbenv-plugin-using-git

after you should have the following result 
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Tharanishwaran** [comment]
@lekaf974 can i work on this issue ?

**Comment by Pratik-050** [comment]
Hi @lekaf974 please assign this to me.

**Comment by lekaf974** [comment]
@Tharanishwaran assigned to you

**Comment by Tharanishwaran** [comment]
@lekaf974 Thanks for assigning me this issue

**Comment by Tharanishwaran** [comment]
@lekaf974 I fixed the issue, tested it, and submitted a PR.
