### ISSUE TITLE
[UX] Meshery Server:  Error code - Meshery-Server-1085 needs much better cause and remediations.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12233]
### Current Behavior
"413 Fall to send design to remote provider." Doesn’t make sense to users. 

1. Use the name of the remote provider.
2. State that design could be corrupt; to undo changes.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by shinigami-777** [comment]
@leecalcote i would like to work on this issue. What are the steps to reproduce this.
