### ISSUE TITLE
[Docs] Improving Meshery Extensibility Providers Docs

### ISSUE THREAD

**Issue by jerensl** [meshery/meshery#12265]
### Current State
Currently, when reading through [Meshery Providers Docs](https://docs.meshery.io/extensibility/providers), people tend to get lost in the middle of the documentation. At some point consider decoupling the documentation for example `Guides and Tutorial` and `Extensions`. The docs of explanation should explain for example what we do and why we do this in this way.

### Desired State
Identify which issues are on the page and provide better alternatives to make a boundary for example around Guides and Tutorial, Integration, and Extensions.

### Reference
[Meshery Docs Persona](https://github.com/meshery/meshery/blob/master/docs/README.md#integrations-and-extensions-all-personas)
[Writing a good explanation docs](https://diataxis.fr/explanation/#writing-good-explanation)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by kamnajain06** [comment]
@jerensl Can you assign me this?

**Comment by Tharanishwaran** [comment]
@jerensl can i work on this ?

**Comment by Tharanishwaran** [comment]
Hi @jerensl ,I already have Meshery built locally. I’ll Understand Meshery Providers.Split docs into Guides, Integrations, and Extensions.Add clear explanations for each section.
