### ISSUE TITLE
[Docs] libgdbm3 installation not working properly following instructions

### ISSUE THREAD

**Issue by omgupta-iitk** [meshery/meshery#12266]
### Current State
Following the instructions provided for prerequisites section of linux https://docs.meshery.io/project/contributing/contributing-docs#for-linux

There is an error for libgdbm3
```
(base) om@om:~$ sudo apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'
Note, selecting 'libncurses-dev' instead of 'libncurses5-dev'
E: Unable to locate package libgdbm3
```

### Desired State
Actually, latest versions of debian based os doesn't support libgdbm3

So depending upon the os version libgdbm5 or libgdbm6 can be used, following this https://github.com/rbenv/ruby-build/issues/1211

A note should we added after prerequisite section in the linux installation section of docs , explaining the above thing.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by omgupta-iitk** [comment]
Can I work on this issue??

**Comment by leecalcote** [comment]
Thanks!
