### ISSUE TITLE
[Docs] Readme: refresh images in readme with images from meshery.io

### ISSUE THREAD

**Issue by winkletinkle** [meshery/meshery#12264]
### Current State
These are slightly stale - https://github.com/meshery/meshery?tab=readme-ov-file#cloud-native-lifecycle-management

### Desired State
copy/paste from meshery.io.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by fitzergerald** [comment]
Good call. I agree.

**Comment by fitzergerald** [comment]
This needs a "help-wanted" label or no?

**Comment by csengineer1990** [comment]
Hi, I’m new here and would like to work on this issue. With your help, I believe I can solve it. Could you please assign this task to me?

Thank you!

**Comment by kamnajain06** [comment]
@winkletinkle hey, I would like to work on this. Can you assign me this?

**Comment by kamnajain06** [comment]
@winkletinkle Hey, just to clarify I need to copy the images from meshery.io and paste it here.

**Comment by ritzorama** [comment]
@kamnajain06, yes.

**Comment by ritzorama** [comment]
It's been two weeks and this issue hasn't moved forward.
