### ISSUE TITLE
[Server] Remove the hardcoding for kubernetes model

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#12276]
### Current Behavior

While seeding currently we use the old Kubernetes version remove the hard coding.
https://github.com/meshery/meshery/blob/1cbf070523bf8e11c1864c659f32c9957a219977/server/models/seed_models.go#L60-L62
### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Much needed.
