### ISSUE TITLE
[UI]Horizontal Scrollbar Bug: Components Break and Display White Line When Scrolled Right

### ISSUE THREAD

**Issue by subho30666** [meshery/meshery#12284]
### Current Behavior
When sliding the horizontal scrollbar to the right, certain components (e.g., labels inside pods/namespace) break and display a white vertical line across the page. This issue disrupts the visual integrity and functionality of the affected components.

### Desired Behavior
Components should maintain their structure and functionality when the horizontal scrollbar is used. There should be no white vertical line or visual disturbances, ensuring a seamless user experience.

### Screenshots/Logs

 
![9](https://github.com/user-attachments/assets/59e3dc73-def8-4191-9251-d09e34fe1bc5)

### Environment

- Browser: Chrome
- Host OS:Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker  @Kubernetes
- @Ashparshp @leecalcote 

I'd like to work on this if the issue is found valid.
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by kamnajain06** [comment]
@subho30666 Hey, I want to work on this issue. Can you assign me this?

**Comment by subho30666** [comment]
> @subho30666 Hey, I want to work on this issue. Can you assign me this?

Hey, I can't assign the project to you as I'm not a maintainer. But if I get assigned, I'll request to include you as an assignee too. This way, we can complete it faster together.
@Ashparshp  @leecalcote @Jougan-0

**Comment by kamnajain06** [comment]
@subho30666 Okay, thanks 👍

**Comment by sudhidutta7694** [comment]
Hey @leecalcote @SAHU-01 @sudhanshutech , I have setup meshery locally,  have understood this issue and want to work in it. Can this issue be assigned to me?

**Comment by eyeaadil** [comment]
Hey @leecalcote @SAHU-01 @sudhanshutech ,I have setup meshery locally,can you assign this issue to me

**Comment by leecalcote** [comment]
@sudhidutta7694, are you all good here / making progress?

**Comment by sudhidutta7694** [comment]
Yes, @leecalcote I have started working on the issue.

**Comment by leecalcote** [comment]
@subho30666 🙌
