### ISSUE TITLE
[Server] Late model Kubernetes components are missing namespace property

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12292]
### Current Behavior
Neither the Kubernetes model v1.31 Deployment nor the Pod (as examples) are recognized as namespaced components. This is a bug in the code for generating later versions of Kubernetes components. 

### Environment

- **Meshery Server Version:** stable-v0.7.117

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by divyansh2375** [comment]
can i work on this issue ?

**Comment by winkletinkle** [comment]
@Jougan-0 fixed this, I believe.

**Comment by leecalcote** [comment]
> @Jougan-0 fixed this, I believe.

Good eye, @winkletinkle. Yes, @Jougan-0 is getting it done.
