### ISSUE TITLE
Debug Mode for Notification Center Events

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12306]
### Current Behavior

1. Meshery has overabundance of design update (design save) event notifications, which are also lacking any detail pertaining to the specifics of what was updated. 
2. Relationship evaluation results are noisy enough and are more important. The Notification Center has an existing filter for relationships (action type: evaluation) with details of the eval results - details whose formatting is difficult to digest.
3. During normal use, both of these event types can be considered volumous and of little import until trouble arises and the need to debug is at-hand.

### Desired Behavior
1. Enhance the design update notifications to expose their details to make them meaningful and helpful.
2. Prettify the presentation of evaluation results with a high-level summary and the ability to expand the rest of the details.
3. Hide these event types from display (from retrieval) in the Notification Center by default, only exposing them when the user enables debug mode in their preferences.

### Acceptance Tests

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sahilshityalkar** [comment]
I would like to contribute by working on this issue. Could you please assign it to me? Let me know if there are any specific guidelines I should follow.

Thank you!

**Comment by Tharanishwaran** [comment]
@leecalcote can you assign me to this issue ?
