### ISSUE TITLE
[Models] Kubernetes Network Policy white icon missing

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12305]
### Current Situation

<img width="1045" alt="Screenshot 2024-10-07 at 11 44 01 AM" src="https://github.com/user-attachments/assets/5731f509-2dbe-4949-b54b-c1f76ba050ec">

### Desired Behavior
During registration, Model and Component SVGs are written to filesystem under their respective model version.

### Environment

- Meshery Server: v0.7.117-2

---

### General Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Understanding Meshery Models

- 📚 [Models](https://docs.meshery.io/concepts/logical/models)
  - 📚 [Components](https://docs.meshery.io/concepts/logical/components)
  - 📚 [Relationships](https://docs.meshery.io/concepts/logical/components)
- 👨‍💻[Models Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)

 ### Contributing to Meshery Models
 - [Contributing Models](https://docs.meshery.io/project/contributing/contributing-models)
   - [Contributing Components](https://docs.meshery.io/project/contributing/contributing-components)
   - [Contributing Relationships](https://docs.meshery.io/project/contributing/contributing-relationships)

**Comment by SAHU-01** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/5fa47c3a-837e-49a8-bba4-2d8ada5574d3">
@leecalcote the kubernetes: network policy white icon appears for me, without a bug.
Could you share more details about the error or the ask here?
