### ISSUE TITLE
[Local Provider] Old catalog designs getting empty design file after seeding during boot.

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#12334]
### Current Behavior
Old designs from catalog getting seed with empty design file because of schema validation.

### Expected Behavior
During seed it should convert it newer version of design file, we already have existing meshkit function for that which we will need to reuse

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by hustlernik** [comment]
Hello @Yashsharma1911, I would like to take this up.

**Comment by Yashsharma1911** [comment]
> Hello @Yashsharma1911, I would like to take this up.

Hi @hustlernik thanks for raising your hand however it is an urgent issue and requires knowledge of design workflow to fix, I'll suggest picking any good first issue and joining Slack community

If you are not able to find an issue to work on, let us know in Slack

**Comment by hustlernik** [comment]
Sure, thanks @Yashsharma1911
