### ISSUE TITLE
[Server] Debug relationship based on request from UI.

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#12355]
### Current Behavior

Currently the `/api/meshmodels/relationships/evaluate` has a field `trace` defined in schema but is not taken into consideration by the backend.
### Desired Behavior

Enhance the endpoint to support the debug based on the flag.
### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by devhiteshk** [comment]
Hi I would like to contribute this for hactoberfest can I pick it it?

**Comment by pranjalg1331** [comment]
@Jougan-0 Please assign this issue to me
