### ISSUE TITLE
[Docs] enhance Related Designs section on individual integration pages.

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery#12372]
### Current State
On Individual integration pages like https://docs.meshery.io/extensibility/integrations/amd-gpu, the designs containing that integration is just a list: 
![image](https://github.com/user-attachments/assets/a26b96e5-cd98-4569-9e08-53aa0226c6c5)

### Desired State
We could enhance the ui-ux and show Design Creator's name, version number and other details available : 
https://github.com/meshery/meshery/blob/master/docs/_catalog/deployment/328ceb3f-970c-4e70-93f9-61e987d7952c.md?plain=1

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Tharanishwaran** [comment]
@vishalvivekm can i work on this issue ?

**Comment by vishalvivekm** [comment]
Hi @Tharanishwaran, you're assigned ~ 5 issues that you're working on, let's give this one to some other first time contributor.
Thank you for chiming in.

**Comment by Tharanishwaran** [comment]
Hi @vishalvivekm,I’ve already raised PRs for 3 of the issues I’m working on, and the other 2 are about 50% complete. Could you help me get those PRs merged when you have a moment?

**Comment by NikhilJ2005** [comment]
Hi can you assign me this issue @vishalvivekm
