### ISSUE TITLE
[UI] Kubernetes context switcher pulls down too far

### ISSUE THREAD

**Issue by ritzorama** [meshery/meshery#12380]
### Current Behavior
See video.

### Desired Behavior
The panel should slide down, but not this far. There should not be a gap. The top of the panel should remain just underneath the nav bar.

### Screenshots/Logs

https://github.com/user-attachments/assets/bec594b2-bf6b-4dde-8cee-191e3729019f

### Environment

- Browser: Safari 
- Host OS: Mac
- Meshery Server Version: stable-v0.7.122

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by hymmns** [comment]
Hi @ritzorama, could you please assign this to me. 
PS: I am just trying the clone the repo.

**Comment by leecalcote** [comment]
Sounds great. Thanks much for jumping in and volunteering. In an effort to help guarantee your success in undertaking assignment of the issue, will you:

1. confirm that you're able to build the project, specifically, the components necessary to resolve this issue.
1. confirm the approach you intend to take to resolve the issue.

**Comment by hymmns** [comment]
Thanks @leecalcote 
Currently stuck on Docker showing Kubernetes is starting

**Comment by ritzorama** [comment]
@hymmns, send word if you get unstuck.

**Comment by hymmns** [comment]
Hi @ritzorama, just got back, will let you if anything changes.

**Comment by hymmns** [comment]
Hi @ritzorama , I've resolved the Kubernetes issue but currently facing issue on starting the application locally.

**Comment by hymmns** [comment]
Hi @ritzorama You might need to assign the issue to someone else. 
Still can't build locally but will send a word if anything changes

**Comment by Tharanishwaran** [comment]
Hi @ritzorama  I have set up meshery locally and I'm ready to work on this issue.

**Comment by eyeaadil** [comment]
Hi @ritzorama I have completely  set up meshery locally and I'm ready to work on this issue.Can you please assign to me.

**Comment by aadarshx22** [comment]
Hi @leecalcote @ritzorama, if the issue is unattained for now, can I work on it?
