### ISSUE TITLE
Rename file 'Test: Datadog agent on k8s' to 'Test - Datadog agent on k8s' 

### ISSUE THREAD

**Issue by Divyansh200102** [meshery/meshery#12389]
### Current Behavior

When attempting to clone the Meshery repository, the checkout fails due to an invalid path that includes special characters. The error message indicates the following:
`error: invalid path 'ui/tests/seed-data/Test: Datadog agent on k8s'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
`
### Expected Behavior

Rename file 'Test: Datadog agent on k8s' to 'Test - Datadog agent on k8s

### Screenshots/Logs

```powershell 
PS C:\Users\Divyansh\documents\github> git clone https://github.com/meshery/meshery
Cloning into 'meshery'...
remote: Enumerating objects: 713008, done.
remote: Counting objects: 100% (30500/30500), done.
remote: Compressing objects: 100% (6058/6058), done.
remote: Total 713008 (delta 21526), reused 30479 (delta 21522), pack-reused 682508 (from 1)
Receiving objects: 100% (713008/713008), 782.77 MiB | 8.00 MiB/s, done.
Resolving deltas: 100% (505809/505809), done.
error: invalid path 'ui/tests/seed-data/Test: Datadog agent on k8s'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@ianrwhitney, I believe that Windows contributors are experiencing a build failure when running `make ui-build` due to filesystem incompatibility with the `:` colon character in the test filename. You might be in a good position to wrangle this item, knowing that the filename _and_ any reference to it will need updated. // @jerensl

**Comment by ianrwhitney** [comment]
@leecalcote i can take a look. Thanks

**Comment by KniteenK** [comment]
I would like to work on this but not sure how to fix this other than manually renaming files with invalid characters. Can someone guide me? Thanks.

**Comment by jerensl** [comment]
> @ianrwhitney, I believe that Windows contributors are experiencing a build failure when running `make ui-build` due to filesystem incompatibility with the `:` colon character in the test filename. You might be in a good position to wrangle this item, knowing that the filename _and_ any reference to it will need updated. // @jerensl

I think this file is no longer used in meshery repo e2e testing
