### ISSUE TITLE
[UI] Hyperlink styling in notifications

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12396]
### Current Behavior
Ugliness and a regression of hyperlink styling, which is out of accordance with the Sistent design system:

### Desired Behavior
Revert recent changes that impacted hyperlink styling inside of notifications.

### Implementation

This might need to be driven through the [Sistent design system](https://github.com/layer5io/sistent).

### Screenshots/Logs
<img width="652" alt="Screenshot 2024-10-16 at 9 22 51 PM" src="https://github.com/user-attachments/assets/e24121d7-6240-4519-8aa6-3ed6961312fa">

### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.7.122

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@aabidsofi19 will you remark on the suggestion under "**Implementation**" in the description?

**Comment by Pratik-050** [comment]
Hello @leecalcote can you clarify what kind of design there should be? Like we can create a text and then embed the hyperlink onto it.

**Comment by leecalcote** [comment]
@Pratik-050, a good place to review is that of the Sistent component for notifications, assuming that there is one. Use Sistent's theme. Revert the change previously made.

@sudhanshutech, there are still only three published components on [this project site](https://meshery.io/projects/sistent)? What become of the promise made to see them all published? @nebula-aac, it's difficult to ask contributors to use Sistint components when they're not documented. From what I can see on the project site, there is no link to the GitHub repo. How are new contributors to find their way around? There is only an npm install command.

@Pratik-050 here is a link to Sistent design system repo - https://github.com/meshery/sistent/

**Comment by sudhanshutech** [comment]
> @Pratik-050, a good place to review is that of the Sistent component for notifications, assuming that there is one. Use Sistent's theme. Revert the change previously made.
> 
> @sudhanshutech, there are still only three published components on [this project site](https://meshery.io/projects/sistent)? What become of the promise made to see them all published? @nebula-aac, it's difficult to ask contributors to use Sistint components when they're not documented. From what I can see on the project site, there is no link to the GitHub repo. How are new contributors to find their way around? There is only an npm install command.
> 
> @Pratik-050 here is a link to Sistent design system repo - https://github.com/meshery/sistent/

Apologies @leecalcote , there is a pr which are adding few more components but a little work required then it will be good to go and you will see other components. There is challenge to add a meaningful content because there is no mockups we have for them so i had to research for them.

**Comment by sudhanshutech** [comment]
Thanks @Pratik-050 for jumping in , there was small update required through sistent to support style in notifications which is now fixed and updated. I will try to add other components to meshery soon.

**Comment by Pratik-050** [comment]
> Thanks @Pratik-050 for jumping in , there was small update required through sistent to support style in notifications which is not fixed and updated. I will try to add other components to meshery soon.

Thanks @sudhanshutech for resolving the issue so fast.
If there's any UI issue I can help with let me know!
