### ISSUE TITLE
[UI] Capabilities Section is not User Friendly

### ISSUE THREAD

**Issue by THEBOSS0369** [meshery/meshery#12404]
### Current Behavior

The Capabilities Section in the `Preferences/Remote-Provider` Page is not clearly visible , we cannot read what's written inside it. See the ss below.

### Desired Behavior

This Section should have been more dark friendly like the section above this.

### Screenshots/Logs

![image](https://github.com/user-attachments/assets/c5a43ec7-9f46-4480-ada1-9568c22a83db)

### Environment

- Browser: Brave, Chrome, Edge
- Host OS:  Windows, Linux
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Divyansh200102** [comment]
I would like to work on this.@THEBOSS0369

**Comment by sudhidutta7694** [comment]
Hi @leecalcote @sudhanshutech  , I have setup the project locally and have understood the issue. I would like to work on this issue. Would you please assign this issue to me?

**Comment by kingdarabahmad** [comment]
@THEBOSS0369 I have resolved the issue have a look on PR.

**Comment by THEBOSS0369** [comment]
Hey @kingdarabahmad ! You shouldn't create a PR for any issue before the assignment . @Divyansh200102 @manascb1344 @sudhidutta7694 Thanks for asking guys!! as @kingdarabahmad has already created a PR for this issue, the maintainers will be reviewing his PR. You guys can look at other issues. Thanks!

**Comment by kingdarabahmad** [comment]
@THEBOSS0369 appologies i will take care of this next time
