### ISSUE TITLE
[UI] Migrate DatabaseSummary Component to Sistient and MUI v5

### ISSUE THREAD

**Issue by Vaibhav701161** [meshery/meshery#12421]
**Description:** Meshery's `DatabaseSummary.js` component is using an outdated version of Material-UI (v4), which leads to increased maintenance and performance issues.

- **Expected Outcome:** Migrate the `DatabaseSummary.js` component from MUI v4 to MUI v5 and apply Sistient styling. This will simplify the code, improve maintainability, and ensure the component is responsive and accessible across devices.

- **Recommended Skills:** ReactJS, Material-UI v5, familiarity with Sistient.

- **Component Reference:** [DatabaseSummary Component](https://github.com/meshery/meshery/blob/a9d81c8099f3e9197337b90871ef0fc6a8437727/ui/components/DatabaseSummary.js#L203)

- **Mentor(s):** Lee Calcote (@leecalcote, leecalcote@gmail.com), Antonette Caldwell (@nebula-aac, pullmana8@gmail.com)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Vaibhav701161** [comment]
@SAHU-01 Please assign this issue to me

**Comment by leecalcote** [comment]
@Vaibhav701161 is this complete?
