### ISSUE TITLE
[UI] Convert meshery menu to sistent hamburger

### ISSUE THREAD

**Issue by amitamrutiya** [meshery/meshery#12435]
### Current Behavior
![image](https://github.com/user-attachments/assets/a1f67e78-9f53-454d-bd54-1c01253b62c4)

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Divyansh200102** [comment]
I would liek to work on this .i have set up meshery locally please assign this to me. @amitamrutiya

**Comment by leecalcote** [comment]
Thank you for making this reusable.

**Comment by Divyansh200102** [comment]
What exactly has to be done in this issue? @amitamrutiya
