### ISSUE TITLE
[Template] Create a Relationship Diagram template 

### ISSUE THREAD

**Issue by SAHU-01** [meshery/meshery#12453]
### Current Behavior
Currently for new users we do not have enough starter templates that they can use as introductory material.

### Desired Behavior
We want to create a Relationship diagram template to allow new users to understand how they can create a Relationship diagram with Kanvas. So we'd want contributors to not just create a template but also add tips or notes they think a new user would need if they are starting out with little to no context of the capabilities Kanvas offers.

### Implementation
Make sure you use [Kanvas](https://kanvas.new/extension/meshmap) to create this template and keep the template private.

- [ ]  Provide a brief overview of what this template does and can help with, maybe highlight a usecase
- [ ] Add a template that can be directly copied and used instantaneously
- [ ]  Add a step by step process to create this template
- [ ] Once the design is completed, publish it and share the private link with our team, or tag us in the comment component to receive feedback.

### Acceptance Tests
- Template has been submitted for publishing to the catalog and accepted; is published and available in the Meshery Catalog.
- We are in need of well annotated and described templates like [this](https://playground.meshery.io/extension/meshmap?mode=design&design=09150cb4-b6a2-4eff-87cd-8a35ba94787a) one.

### Mockups
This [FigJam](https://www.figma.com/community/file/1103389501670923983) template can be used for recreating the Relationship Diagram Template

### Perks
By contributing to this task, your efforts will have a lasting impact! Once published, your design will be cloned and used by countless users as a go-to starting point for creating Relationship diagrams in Kanvas. You'll not only help newcomers understand the platform but also see your work adopted widely by the community. Plus, as a token of appreciation, you'll receive a special shoutout, recognising your valuable contribution. Your effort won’t go unnoticed—you're directly helping shape the experience for future users!

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Gowtham3173** [comment]
Hello @leecalcote and @SAHU-01,
I'd like to contribute to this issue and believe I can help in creating a Meshery UI template for beginners. Could you please assign it to me?
Thank you!

**Comment by SAHU-01** [comment]
Hi @Gowtham3173 , sure!
Once you feel the design template is ready for review, do add a comment in the design by pressing a Ctrl/Cmd + M and tagging @Ankita Sahu in  the comments. I can review it and we can go ahead with publishing your design!

**Comment by Gowtham3173** [comment]
@SAHU-01 Thanks for the suggestion!
I'll make the mentioned changes and upload the updated template here once it's complete."

**Comment by Gowtham3173** [comment]
@SAHU-01, Could you please take a look at the template and let me know if there are any adjustments needed? 
Here’s the link: https://playground.meshery.io/extension/meshmap?mode=design&design=3fd06d85-e516-4eae-b7b6-474231b6d48d
Thank you!

**Comment by leecalcote** [comment]
Yay, @Gowtham3173! 🎈

**Comment by Gowtham3173** [comment]
@leecalcote ,
Thank you for your response and support!

**Comment by SAHU-01** [comment]
This looks awesome @Gowtham3173 🚀
You can follow [this](https://docs.meshery.io/extensions/publishing-a-design) docs to publish your design.

**Comment by Gowtham3173** [comment]
> This looks awesome @Gowtham3173 🚀
> You can follow [this](https://docs.meshery.io/extensions/publishing-a-design) docs to publish your design.

Thank you @SAHU-01 the design has been published.

**Comment by leecalcote** [comment]
@Gowtham3173 @SAHU-01 some excellent work here! 👏 

Please note this feedback:

<img width="838" alt="Screenshot 2024-10-28 at 12 25 29 PM" src="https://github.com/user-attachments/assets/a90dc92e-013b-4d9d-a322-ff7fb01a3fc0">
