### ISSUE TITLE
[Extensions] "v" and "h" hotkeys for select and hand tools

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12476]
<img width="470" alt="Screenshot 2024-10-24 at 8 42 56 AM" src="https://github.com/user-attachments/assets/34c414e5-a66c-4512-b9d3-1949e46e4993">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
@amitamrutiya this is completed right?
