### ISSUE TITLE
[Server] Crash: NATS goroutine deadlock

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12492]
### Current Behavior
Build Meshery Server on Linux. Sign in. Sit idle. Crash.

See log file.

### Screenshots/Logs
[server-logs.txt](https://github.com/user-attachments/files/17531637/server-logs.txt)

### Environment

- **Host OS:** Linux
- **Platform:** Server local
- **Meshery Server Version:** edge-v0.7.1.27

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Kevin222004** [comment]
Faced same issue yesterday.
