### ISSUE TITLE
[Models] Add Layer5 logo as a component in the Dev Icons model

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12509]
### Current Situation
The Dev Icons model has many icons for tools and tech companies. It does not have one for Layer5.

### Proposed Change

Use the attached Layer5 logo mark to create a new annotation-only component, adding it to the Dev Icons model.

[5-light-no-trim.svg.zip](https://github.com/user-attachments/files/17549132/5-light-no-trim.svg.zip)

_Copy of logo taken from https://layer5.io/brand._ 

---

### General Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Understanding Meshery Models

- 📚 [Models](https://docs.meshery.io/concepts/logical/models)
  - 📚 [Components](https://docs.meshery.io/concepts/logical/components)
  - 📚 [Relationships](https://docs.meshery.io/concepts/logical/components)
- 👨‍💻[Models Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)

 ### Contributing to Meshery Models
 - [Contributing Models](https://docs.meshery.io/project/contributing/contributing-models)
   - [Contributing Components](https://docs.meshery.io/project/contributing/contributing-components)
   - [Contributing Relationships](https://docs.meshery.io/project/contributing/contributing-relationships)

**Comment by tarunsinghofficial** [comment]
Can i work on this?

**Comment by NishantSinghhhhh** [comment]
@leecalcote  , Sir can you please assign this issue to me

**Comment by leecalcote** [comment]
@tarunsinghofficial @NishantSinghhhhh thank you for volunteering, gentlemen. This particular enhancement was recently completed.
