### ISSUE TITLE
[Models] Add Meshery logo as a component in the Dev Icons model 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12510]
### Current Situation
The Dev Icons model has many icons for tools and tech companies. It does not have one for Layer5.

### Proposed Change

Use the attached Meshery logo mark to create a new annotation-only component, adding it to the Dev Icons model.

[meshery-light-icon.svg.zip](https://github.com/user-attachments/files/17549137/meshery-light-icon.svg.zip)

_Copy of logo taken from https://meshery.io/brand._ 

---

### General Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Understanding Meshery Models

- 📚 [Models](https://docs.meshery.io/concepts/logical/models)
  - 📚 [Components](https://docs.meshery.io/concepts/logical/components)
  - 📚 [Relationships](https://docs.meshery.io/concepts/logical/components)
- 👨‍💻[Models Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)

 ### Contributing to Meshery Models
 - [Contributing Models](https://docs.meshery.io/project/contributing/contributing-models)
   - [Contributing Components](https://docs.meshery.io/project/contributing/contributing-components)
   - [Contributing Relationships](https://docs.meshery.io/project/contributing/contributing-relationships)

**Comment by tarunsinghofficial** [comment]
I can work on this issue. Please assign this to me!

**Comment by thiha-min-thant** [comment]
HI @leecalcote , could you please assign to me?

**Comment by leecalcote** [comment]
Hi All,  thank you for volunteering. This particular enhancement was recently completed.
