### ISSUE TITLE
[UI][Catalog] HTML Entities displaying inappropriately

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12538]
### Screenshots/Logs

<img width="826" alt="Screenshot 2024-10-31 at 11 03 38 PM" src="https://github.com/user-attachments/assets/3adec163-fea1-4be5-b662-c657720897cd">

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
This issue is now fixed
