### ISSUE TITLE
[UI] Design Info Modal displaying HTML entities

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12542]
<@U04K72AGYBW>, outside of the html entities that should not display, please correct the display order of the two textareas.

[Slack Message](https://layer5io.slack.com/archives/C023QGMSH8D/p1730434082422789?thread_ts=1730433892.057629&cid=C023QGMSH8D)

**Comment by Yashsharma1911** [comment]
This issue is now fixed
