### ISSUE TITLE
[Extensions] Getting Started panel and Catalog modal should be dichotomous 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12562]
### Current Behavior
<img width="589" alt="Screenshot 2024-11-02 at 2 32 26 PM" src="https://github.com/user-attachments/assets/d5dc5274-d502-4c86-b1a3-a12e2c49da48">

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Extension Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by amitamrutiya** [comment]
Fixed.
