### ISSUE TITLE
[UI] Deployment target environment connection

### ISSUE THREAD

**Issue by SAHU-01** [meshery/meshery#12579]
### Current Behavior

When a user clicks on an environment, inside the Action > Deployment section, the ping fails, as the connection_id is undefined [not getting passed]:

<img width="1295" alt="image" src="https://github.com/user-attachments/assets/82e304d6-7938-4f0b-a1d1-73f72754ce57">

### Desired Behavior
We wish to have a successful ping like below:
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/464b4473-234e-40b6-a29a-c4d31bccb7cc">

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.134
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
yay!
