### ISSUE TITLE
[UI] Failed to show Meshery UI on CLI Command Reference

### ISSUE THREAD

**Issue by JianMinTang** [meshery/meshery#12606]
### Current Behavior

![image](https://github.com/user-attachments/assets/69538388-5e4c-421c-9c8f-1248ce20d26c)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by gaurav-mehta19** [comment]
plz share the desired behavior would like to work on this

**Comment by JianMinTang** [comment]
> plz share the desired behavior would like to work on this

You can compare the differences between the two, [one](https://docs.meshery.io/reference/mesheryctl/registry/update) being correct and [the other](https://docs.meshery.io/reference/mesheryctl/registry/generate) having flaws?

**Comment by Divyansh200102** [comment]
> > plz share the desired behavior would like to work on this
> 
> You can compare the differences between the two, [one](https://docs.meshery.io/reference/mesheryctl/registry/update) being correct and [the other](https://docs.meshery.io/reference/mesheryctl/registry/generate) having flaws?

@JianMinTang I have fixed the issue.
