### ISSUE TITLE
[UI] Unable to delete designs on Design page in grid view.

### ISSUE THREAD

**Issue by shanukun** [meshery/meshery#12615]
### Current Behavior

Clicking the delete icon in grid view under Configuration -> Designs does not delete the design, even if a popup stating that the design was successfully deleted appears. 

### Desired Behavior

The design should be deleted when you click the delete icon on the design card in grid view.

### Screenshots/Logs

[Slack thread](https://layer5io.slack.com/archives/C019426UBNY/p1731085853833489).

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Divyansh200102** [comment]
@shanukun it doesn't seem to be deleting in neither list nor grid mode on my end?

https://github.com/user-attachments/assets/03f52ceb-2c81-4fde-abc4-6ae2c268a673

**Comment by shanukun** [comment]
@Divyansh200102 I suppose delete on popups isn't functioning. 
Create a new design and then try to delete after selecting it.

**Comment by sudhanshutech** [comment]
folks thanks for pointing, but the delete action is working but the UI is not reflecting asynchronously, need to trigger a refetch from rtk query.

**Comment by shanukun** [comment]
@sudhanshutech  I checked the server log and saw that there was nothing on the list of items that needed to be deleted.
Perhaps there is a problem with the delete request.

**Comment by sudhanshutech** [comment]
are you willing to work @shanukun on this issue?

**Comment by shanukun** [comment]
@sudhanshutech 
I can't work on this because I have other priorities and it's a UI problem. However, because the deletion is clearly broken, we shouldn't close the issue just yet.

As seen in this image, the pattern to be deleted list is empty when I try to delete in grid mode.
![no_design_list](https://github.com/user-attachments/assets/69db2d48-b37f-4845-86df-75e5c31fb69c)

And when I try to delete in list mode after selecting a design, everything works well.
![desgin_list](https://github.com/user-attachments/assets/81166ac2-d58f-4c30-8074-3f4f9d446d32)

Also you can see `POST /api/patterns/delete` returns `200` status code in both the case.

**Comment by sudhanshutech** [comment]
no worries @shanukun , i already fixed the issue. That's why i closed
