### ISSUE TITLE
Local Provider: Cannot enable Catalog extension

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12791]
<@U04K72AGYBW> the Meshery Catalog is not able to be enabled in the Local Provider.

[Slack Message](https://layer5io.slack.com/archives/C023QGMSH8D/p1732811172141079?thread_ts=1732811172.141079&cid=C023QGMSH8D)

**Comment by shanukun** [comment]
@leecalcote I believe this is a duplicate of #12329. I've also provided the solution for it [here](https://github.com/meshery/meshery/issues/12329#issuecomment-2418132924).

**Comment by leecalcote** [comment]
Thanks, @shanukun. Is there a PR up?
