### ISSUE TITLE
[UI] Generate Model: Mis-colored radio buttons

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12798]
### Current Behavior
The reddish radio button in this modal is not within the project's color scheme. This modal can be found by navigating to Settings --> Registry --> Models --> "+ Generate" button.

<meshery>/settings?settingsCategory=Registry&tab=Models

### Desired Behavior
Only Sistent components and theme should be used.

### Screenshots/Logs
<img width="641" alt="Screenshot 2024-11-29 at 12 02 54 PM" src="https://github.com/user-attachments/assets/7882baa9-26ac-438d-8b5c-1dd449a89c8d">

### Environment

- Browser: Safari 
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.166

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by kmin-jeong** [comment]
Can I try this issue??

**Comment by Vijaykv5** [comment]
I would love to work on it @leecalcote after @kmin-jeong's try

**Comment by sudhanshutech** [comment]
@apoorvapendse please wait to get the issue assigned first next time. It create conflicts between other contributors.

**Comment by Shreyc711** [comment]
Anyone working on it?
