### ISSUE TITLE
Upgrade Meshery Server and all Components to Golang 1.23.4

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12829]
### Current Behavior
Meshery and its components all use golang 1.21.8 currently. Some packages that Meshery relies upon are no longer compatible with 1.21, but require 1.22 or higher. For example.

```
go: downloading github.com/99designs/gqlgen v0.17.57
go: github.com/99designs/gqlgen@v0.17.57 requires go >= 1.22.5 (running go 1.21.8; GOTOOLCHAIN=go1.21.8)
go: github.com/99designs/gqlgen@v0.17.57 requires go >= 1.22.5 (running go 1.21.8; GOTOOLCHAIN=go1.21.8)
make: *** [graphql] Error 1
```

### Desired Behavior
All components within the Meshery project to support the latest version of Golang (1.23.4).

### Implementation
1. github workflows: Uniformly, upgrade Meshery Server and all its components workflows to Golang 1.23.4.
1. makefile variables
1. github repo secret (if applicable)

- [x] https://github.com/meshery/meshery-kuma/issues/441 @devhindo
- [x] https://github.com/meshery/meshery-linkerd/issues/586
- [x] https://github.com/meshery/meshery-adapter-library/pull/164 @devhindo
- [ ] meshery/meshkit @weilirs 
- [ ] meshery-istio
- [ ] meshery-consul
- [ ] meshery-cilium
- [ ] meshery/meshery server
- [ ] meshery/meshery ctl

### Acceptance Tests
1. Meshery Extension providers notified of impending upgrade.
1. Compatibility of new version confirmed with each component and with Meshery Extension providers.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by weilirs** [comment]
Can you assign this to me? @leecalcote

**Comment by eyeaadil** [comment]
@leecalcote ,can you assign this to me?

**Comment by leecalcote** [comment]
You bet. There are plenty of components in need of upgrade.

**Comment by devhindo** [comment]
Is there anyone working on this? If not, I'm happy to work on it

**Comment by weilirs** [comment]
> Is there anyone working on this? If not, I'm happy to work on it

Next I'll upgrade Meshkit and test it with the server, feel free to upgrade other components
