### ISSUE TITLE
[Models]

### ISSUE THREAD

**Issue by Richardallis411** [meshery/meshery#12855]
### Proposed Change

---

### General Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Understanding Meshery Models

- 📚 [Models](https://docs.meshery.io/concepts/logical/models)
  - 📚 [Components](https://docs.meshery.io/concepts/logical/components)
  - 📚 [Relationships](https://docs.meshery.io/concepts/logical/components)
- 👨‍💻[Models Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)

 ### Contributing to Meshery Models
 - [Contributing Models](https://docs.meshery.io/project/contributing/contributing-models)
   - [Contributing Components](https://docs.meshery.io/project/contributing/contributing-components)
   - [Contributing Relationships](https://docs.meshery.io/project/contributing/contributing-relationships)

**Comment by palSagnik** [comment]
hello @Richardallis411  I would like to contribute and start working on this, any tips on what you are looking for and what is expected?
