### ISSUE TITLE
[CI] Artifact actions v3 will be closing down by January 30, 2025

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12868]
### Current Behavior
v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) and [actions/download-artifact](https://github.com/actions/download-artifact) will no longer be supported by GitHub as of January 25, 2025.

### Desired Behavior
All GitHub Actions workflows across all repos using v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact) will need to be upgraded to v4 prior to January 25, 2025.

### Implementation
See this list of key differences between versions - https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by TusharMohapatra07** [comment]
I'd like to work on this.

**Comment by FilledEther20** [comment]
Hi @leecalcote , I would like to work on this issue. Could you please assign it to me? Thanks!

**Comment by TusharMohapatra07** [comment]
@leecalcote can you please check if this is what's intended ?

**Comment by TusharMohapatra07** [comment]
@leecalcote I just ran the ci/cd checks on my fork and noticed some errors. I'll fix them (the error says that there could be only one artifact on same workflow run)

**Comment by devhindo** [comment]
related to [this](https://github.com/meshery/meshery-kuma/actions/runs/12321306401/job/34392507108) failure

**Comment by TusharMohapatra07** [comment]
ohh so is that being fixed right now ? if not, i'll try fixing it  @devhindo

**Comment by devhindo** [comment]
@TusharMohapatra07 nah it's not fixed yet
