### ISSUE TITLE
[mesheryctl] Promote environment command from experimental

### ISSUE THREAD

**Issue by lekaf974** [meshery/meshery#12947]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

We need to promote environment subcommand

### Current Behavior

Command is available under experimental status

```bash
mesheryctl exp environment
```
### Desired Behavior

Should move as regular subcommand

```bash
mesheryctl environment
```

### Implementation

1. move subcommand under root
2. Update related documentation 

### Acceptance Tests

- command is available at root subcomands level
- documentation is updated

### Mockups

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Tharanishwaran** [comment]
@lekaf974 can i work on this issue ?
