### ISSUE TITLE
[Docs] `make docker` shouldn't produce the ruby version error

### ISSUE THREAD

**Issue by devhindo** [meshery/meshery#12952]
when trying to set up the docs environment using `make docker` it shouldn't produce this error `your ruby version is x.x.x but your Gemfile specified 2.7.x` mentioned in the docs [here](https://docs.meshery.io/project/contributing/contributing-docs)
![image](https://github.com/user-attachments/assets/561e26af-a121-42b8-aeb0-bd8d18af3964)
cause how can I access the container and install that specific ruby version using `rvm install 3.2.2`, `rvm use 3.2.2 --default` when the container can't even created? rather a `Dockerfile` should be implemented that contains the logic to run this command in advance to prevent this error from happening

**Comment by shinigami-777** [comment]
@devhindo I'd like work on this issue. I've faced this same problem earlier and changing the version on the gemfile works as a temporary solution.

**Comment by devhindo** [comment]
go ahead! @shinigami-777

**Comment by devhindo** [comment]
a successful `make docker` execution would mark your pr as successful @shinigami-777

**Comment by shinigami-777** [comment]
@devhindo Created a PR for this. Let me know if any changes are necessary.
