### ISSUE TITLE
[Docs] Improve `meshseryctl` docs UI

### ISSUE THREAD

**Issue by devhindo** [meshery/meshery#13008]
in [mesheryctl docs](https://docs.meshery.io/reference/mesheryctl)
![image](https://github.com/user-attachments/assets/39f2d6ed-ec66-4938-aa96-f95cd273c361)
each of these heading should be a hyperlink that takes me to the start of the table of this command (below)
for example, in the third line in the above image if  I click it, it should take me to https://docs.meshery.io/reference/mesheryctl#cloud-native-lifecycle-and-configuration-management instead of me scrolling all the way down to reach that

**Comment by makifyeginS** [comment]
Hi can i work on this ?

**Comment by makifyegin** [comment]
Hi, Can i work on this?

**Comment by rohan-choudharyy** [comment]
@devhindo i can work on this

**Comment by makifyegin** [comment]
Hi @devhindo @leecalcote ! I’ve just submitted a pull request (https://github.com/meshery/meshery/pull/13044) to address this issue. The changes add hyperlinks to headings, making it easier to jump straight to specific sections of the page—hope this improves navigation for everyone! Thanks so much for giving me the chance to work on this issue. I’m excited to contribute more and be part of this awesome community!

**Comment by devhindo** [comment]
Good work! @makifyegin I reviewed your pr

**Comment by makifyegin** [comment]
@devhindo Thank you I've fixed and submitted again

**Comment by leecalcote** [comment]
Yay! 🎈
