### ISSUE TITLE
Improve Text Contrast in Capability Section Table under /user/preferences in Meshery Playground

### ISSUE THREAD

**Issue by Vidit-Kushwaha** [meshery/meshery#13007]
### Current Behavior
The table in the Capability section under `/user/preferences` in the Meshery Playground has poor text-to-background contrast, making it difficult to read. 

### Expected Behavior
The table's text should have a higher contrast ratio with the background. Which maches with the Theme.

### Screenshots/Logs

![image](https://github.com/user-attachments/assets/28196237-6b9a-430c-a263-9b21d00d1344)

### Environment

- **Host OS:** Windows (Edge Browser)
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

### To Reproduce
1. Navigate to /user/preferences in the Meshery Playground.
1. Scroll down to the Capability section.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by rohithachandhaluru** [comment]
Solution to Improve Text-to-Background Contrast in the Capability Table:

To solve the issue of poor text-to-background contrast in the Capability section under /user/preferences, I suggest the following:

Adjust Background Color: Modify the table's background color to a lighter or more neutral shade, such as light gray or off-white, to improve contrast with the text.

Text Color Modification: Update the text color to a darker shade (e.g., dark gray or black) to make it stand out clearly against the background, improving readability.

Ensure Accessibility Standards: Ensure that the contrast ratio between text and background meets WCAG guidelines, specifically a ratio of at least 4.5:1 for normal text. Tools like the WebAIM Contrast Checker can help verify this.

Dynamic Theme Integration: If Meshery supports dynamic theming (e.g., light/dark mode), the table's styling should adapt to match the selected theme, maintaining consistency throughout the UI.

Cross-Device Testing: Test the table on different devices and browsers to ensure the updated contrast works effectively across various screen sizes and settings.

**Comment by anupriyakkumari** [comment]
Hi, I would like to take this issue up if it's available.

**Comment by Dev-Arhaan** [comment]
Hi I'd like to take this up.

**Comment by rohan-choudharyy** [comment]
can i work on this?

**Comment by rohan-choudharyy** [comment]
Hey, @Vidit-Kushwaha i tried this on server and client version both, in edge and other browser but the styling seems fine.
![image](https://github.com/user-attachments/assets/bd85a3ec-cb70-4676-a0be-b89be6d99445)

**Comment by Vidit-Kushwaha** [comment]
@rohan-choudharyy Thank you
