### ISSUE TITLE
[CI] deprecated link in `integrations-updater.yml`

### ISSUE THREAD

**Issue by devhindo** [meshery/meshery#13029]
in `.github/workflows/integrations-updater.yml` in line 14 thi instructions for setup link is deprecated 

 > See these instructions for setup - https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication

**Comment by Tushar240503** [comment]
Hey i would like to work on this issue

**Comment by devhindo** [comment]
thanks for your contribution @Tushar240503! 🎉 closing this as complete.
