### ISSUE TITLE
[Docs]: Add versioning support to the Meshery documentation 

### ISSUE THREAD

**Issue by chandrashritii** [meshery/meshery#1304]
**Description**

The current jekyll theme: [docsy](https://github.com/vsoch/docsy-jekyll) which is being used for the Meshery documentation does not support versioning. A more elaborate explanation can be found [here.](https://github.com/vsoch/docsy-jekyll/issues/23#issuecomment-656311752)

**Comment by tory-brown** [comment]
hello can I take this up what is expected?

**Comment by neotamias** [comment]
does anyone want to help with this? it should be easy enough to add versioning with branches and such, see my comment on the issue there

**Comment by chandrashritii** [comment]
Yes, your help would be very welcome here @neotamias I read your comment on the original docsy-jekyll repo as well. That sounds like a good way to do this. Let's get you started right away :) Please do let me know if you need any resources or help.
Also, most of our conversations happen on slack. You're very welcome to join in - [Layer5 Slack](https://join.slack.com/t/layer5io/shared_invite/zt-kq4v8kkz-Ebf8GalTx69zum2t3OzB~g).

**Comment by leecalcote** [comment]
Design considerations - https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#bookmark=id.dzqnisw51myu
