### ISSUE TITLE
[mesheryctl] Add oauth feature and store auth credentials for faster / simple command invocations

### ISSUE THREAD

**Issue by anirudhjain75** [meshery/meshery#1658]
**Current Behavior**

You have to pass in token path as flag arguments to perf / mesh commands

**Desired Behavior**

You get an auth req when you dont have auth credentials other you should be able to run any commands without having to pass in token which is manually generated.

---
**Implementation**

An overview or look into gh tool would be great. Should give a better idea on how to implement oauth and have a feel for it.

**Comment by KarenEfereyan** [comment]
@anirudhjain75 can i take this up? I

**Comment by leecalcote** [comment]
Hi @KarenEfereyan, that would be wonderful. I will note that this is a relatively challenging issue in terms of level of difficulty, which I suspect is why it doesn't carry a "help-wanted" label (not that help isn't wanted :) ). If you’re able to digest `gh`’s capabilities here and produce a design on it’s implementation in `mesheryctl` , yes, let’s do it. In the meantime, let's slap the `issue/design-required` label on this issue, pending a proposal. You can use the design spec template in the shared community drive to produce a spec. 👍

**Comment by anirudhjain75** [comment]
If you're up to the task sure. Let me know if you need any help or more context into the issue.

**Comment by KarenEfereyan** [comment]
@anirudhjain75 and @leecalcote I can tell that its a lot challenging. That's why I want to try working on it. I will learn a lot and I have you to help me. So yes, Ill start work on it soon

**Comment by leecalcote** [comment]
This is a desirable feature.

**Comment by leecalcote** [comment]
Implemented in `mesheryctl system login`
