### ISSUE TITLE
[mesheryctl] Create `mesheryctl system check`

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#1754]
Child Issue- [mesheryctl] [child] Create mesheryctl exp preflight to verify environment readiness for a Meshery deloyment #2607

**Current Behavior**
Users are able to run `mesheryctl system status` to check whether Meshery containers are running or not in their local Docker environment (using docker-compose). Users are not, however, able to perform to other types of checks in-depth:

1.  `check` - a sophisticated check encompassing current environment and current Meshery deployment health. Should include aspects of `system version` and of `system status`.
1. `preflight` - for verification of presence of dependencies and overall environment readiness for a Meshery deployment

**Desired Behavior**
`mesheryctl` should provide a utility to aid in the troubleshooting of Meshery deployments. This utility will need to run a number of health checks.

**Implementation**
1. As a subcommand of the `experimental` command, create `mesheryctl experimental system check`.
1. Invoke the collection of connectivity tests between Meshery server, its adapters, Kubernetes, and any connected add-ons like Grafana, Prometheus, Kubernetes permission verification, and Meshery version check.
1. This utility should support a `--preflight` flag like so: `mesheryctl system check --preflight`, which only runs the Docker and Kubernetes checks.

**Mockups**
```
➜  ~ mesheryctl system check

Docker
--------------
√ Docker is running
√ docker-compose is available

Kubernetes API
--------------
√ can initialize the client
√ can query the Kubernetes API
√ has required level of privileges

Kubernetes Version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

Meshery Version
---------------
√ server is up-to-date (stable-v0.x.x)
√ cli is up-to-date (stable-v0.x.x)

Meshery Adapters
---------------
√ meshery-istio adapter is reachable and running
√ meshery-consul adapter is reachable and running
√ meshery-linkerd adapter is reachable and running
.
.
.
√ meshery-nginx-sm adapter is reachable and running
√ meshery-octarine adapter is reachable and running
```

**Acceptance Tests**
1. _Meshery Preflight_
  - Users may or may not be installing to Docker, so failure of Docker being available should only be shown as a warning.

2. _Meshery Version_ 
  - To verify the Meshery server version and the Meshery client version, this check should first attempt to use the `/api/server/version` endpoint on Meshery server and should use the `mesheryctl system version` function to check on the client version. It should inform the user if a later version of either server or client is available. It should warn the user if the server and client are not at the same version number.

3. _Meshery Adapters_
  - To verify availability of Meshery adapters, this check should invoke the [`/api/mesh/adapter/ping` endpoint](https://github.com/layer5io/meshery/blob/master/handlers/mesh_ops_handlers.go#L268) on Meshery to run an ad-hoc connectivity tests for all known adapters.
  - A user may have disabled some or all of Meshery's adapters. Irrespective, all known adapters should be checked for availability. 

4. _Kubernetes_
  - Meshery requires "ClusterAdmin" role in order to be able to provide and manage service meshes. This check should verify that the Meshery ServiceAccount has the "ClusterAdmin" role assigned.

**Comment by nitishm** [comment]
worth splitting this into multiple issues so that folks can pick up sections of this?

**Comment by leecalcote** [comment]
Yes, most certainly.

**Comment by nitishm** [comment]
With that said I can look into this unless someone else wants to pick this up?

**Comment by leecalcote** [comment]
Yes, most assuredly.

**Comment by leecalcote** [comment]
Our conversation stopped just shy of me having reach down deep for another adverb.

**Comment by nitishm** [comment]
> Meshery Adapters
To verify availability of Meshery adapters, this check should invoke the `` endpoint on Meshery to run an ad-hoc connectivity tests for all known adapters.

What is the endpoint above? Just states ``

**Comment by leecalcote** [comment]
Here we are. Adapter ad-hoc ping test: `/api/mesh/adapter/ping`  - https://github.com/meshery/meshery/blob/master/handlers/mesh_ops_handlers.go#L268

URL Encoded Example:
`http://localhost:9081/api/mesh/adapter/ping?adapter=meshery-consul%3A10002` (%3A being a colon)

**Comment by kushthedude** [comment]
@leecalcote It will be better to have --pre-check too, so that it may tell if your system is able to install meshery and provision service-meshes or not.

**Comment by uds5501** [comment]
@leecalcote This issue seems interesting, once the meshery is setup in my local system and I am able to play around with the code, i would love to work on this issue.

**Comment by piyushsingariya** [comment]
Hey @leecalcote Can I try this?

**Comment by navendu-pottekkat** [comment]
@piyushsingariya @leecalcote This seems like a big task. We should consider splitting it up...

**Comment by navendu-pottekkat** [comment]
@leecalcote @piyushsingariya We can first start with implementing `preflight`. And `check` should run `preflight` plus ping the adapters. How does that sound?

**Comment by piyushsingariya** [comment]
@navendu-pottekkat Agreed, `preflight` should be implemented first.

**Comment by navendu-pottekkat** [comment]
@leecalcote @piyushsingariya I have moved the preflight checks to #2607
