### ISSUE TITLE
[Docs] Meshery Troubleshooting Guide

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2399]
**Current State:**
The [Meshery Documentation specification](https://docs.google.com/document/d/17guuaxb0xsfutBCzyj2CT6OZiFnMu9w4PzoILXhRXSo/edit?usp=sharing) identifies a full documentation set, including a TroubleShooting Guide.

**Desired State:**
1. Create an outline of the guide.
   - should include sections for each Meshery component
1. Create additional issues as needed to deliver sections of the guide relevant to individual Meshery components.

**Implementation:**
1. The Troubleshooting guide should be published under the docs.meshery.io/guides section.
1. It should include reference to the [Error Code Reference](https://github.com/layer5io/meshery/issues/2107).

**Related:**
- Error Code Reference https://github.com/layer5io/meshery/issues/2107

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by alceil** [comment]
I would like to take up this issue @leecalcote
