### ISSUE TITLE
[UI] Configuration Wizard

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2434]
#### Current Behavior
While Meshery is opinionated and assumes sensible defaults for users, some environments and some users will benefit from a multi-step configuration wizard that walks them through each of the areas of their Meshery deployment that they might need to initialize or change the configuration of.

#### Desired Behavior
Users are presented with an optional configuration wizard. The wizard and all of its steps should be idempotent. In many respects, the configuration wizard represents an assembly of existing functionality and settings that the user can configure. This multi-step form, however, provides a guide to successfully configuration a Meshery deployment.

Initial design should have four steps in the Configuration Wizard.

Step 1. Connect to Kubernetes.
Step 2. Deploy and Connect Meshery Operator (MeshSync).
Step 3. (Optional) Deploy or connect to one or more service meshes.
Step 4. (Optional) Deploy or connect to Prometheus and/or Grafana.

#### Implementation
- use and customize a react multi-stepper.
- partner with Golang-capable contributor (e.g. @Nikhil-Ladha or @navendu-pottekkat) new backend functionality might be needed. Create separate GH issue(s), if needed.
- partner with UX designer (@austinogiza)

#### Acceptance Tests
1. Users may pull up the configuration wizard during initial deployment of Meshery and anytime thereafter.
2. Users are allowed to skip steps that are marked as optional.
3. Configuration wizard should be accessible from the global navigation bar as a new icon (see screenshot with red arrow).

#### Mockups
- Configuration wizard icon location
  - <img width="206" alt="Screen Shot 2021-02-21 at 8 40 37 PM" src="https://user-images.githubusercontent.com/7570704/108650610-9093a680-7485-11eb-9058-4f00fcb147ff.png">

- Configuration wizard steps
  - See Figma (https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/?node-id=403%3A6811).

**Comment by Nikhil-Ladha** [comment]
I think the intention is to create a `product tour` kind of implementation, right?

**Comment by bartkalanski** [comment]
@Nikhil-Ladha I think that was the initial plan, but then it was decided that configuration wizard (something like this -> https://www.youtube.com/watch?v=ayU1Ds6npuQ&t=104s) would be more useful to the user. Correct me if I'm wrong @leecalcote ?

**Comment by navendu-pottekkat** [comment]
Being fixed in #2601

**Comment by leecalcote** [comment]
Still being developed. Team might have a demo for this week's Meshery Development meeting.
