### ISSUE TITLE
[Meshery Operator] Connect / Disconnect / Upgrade / Provision Test Scenarios

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2530]
#### Current Behavior
Meshery Operator should be deployed as early as possible to the user's Kubernetes' cluster(s). Various possible failure scenarios are involved in the lifecycle management of Meshery Operator. This issue identifies different scenarios and tracks the successful handling of each.

**Scenario: Cluster Disconnect**
When a user disconnects Meshery from a k8s cluster, Meshery will need to have the user confirm that the Operator should or should not be removed from the cluster. 

- Consideration for leaving the operator "on": A user may wish to temporarily switch K8s contexts, and so, leaving the Meshery Operator running facilitates multi-cluster support in Meshery.
- Consideration for removing the operator: A user may wish to uninstall the operator altogether.

_Scenario Acceptance Test_ 
- [x] Prompt user and execute in accordance with user's response.
- [x] Removing operator should reflect in the UI (even though MeshSync doesn't report this change).

**Scenario: Cluster Connect**
When a user connects Meshery to a k8s cluster, Meshery will automatically install the Operator in the cluster.

- Consideration when a new config is added: A user may wish to add or change the existing Kubernetes config to a new one. The Operator should be facilitated to the new one.
- Consideration when operator already exists: The Operator would have already been running in the newly configured cluster. In such cases, the operator should just be connecting to the broker endpoint and fetching the versions of these components.

_Scenario Acceptance Test_ 
- [x] Discover the components(Operator and its controllers) versions on every configure.
- [x] Install operator on boot/reconnect.
- [x] Connect to broker when operator already present.
- [x] Automatic invocation of rediscovery upon reconnection to existing broker.
- [x] Manual ad hoc rediscovery upon click of Operator chip.

**Comment by leecalcote** [comment]
@kumarabd what other scenarios are to be addressed? Please add them to this issue's description.

**Comment by kumarabd** [comment]
@leecalcote updated them

**Comment by leecalcote** [comment]
@kumarabd how is this being done? 

- [x] Removing operator should reflect in the UI (even though MeshSync doesn't report this change).

Can you confirm that the logic used here doesn't negatively affect a reinstall of the Operator?

**Comment by kumarabd** [comment]
@leecalcote  yes it won't. Im Positive(Tested).

**Comment by leecalcote** [comment]
@kumarabd please wrap this up this week. v0.5.0 was released some time ago.

**Comment by kumarabd** [comment]
- [] Orphaned meshery operator already in the cluster running, meshery gets deployed fresh. Meshery should still be able to use the running operator and get synced with the cluster state. 
- [ ] Meshery Operator running, but controllers are not. This should reflect in the UI.

**Comment by kumarabd** [comment]
@ramrodo We would want to consider the scenarios covered in this issue, to be automated as a part of CI process validation. Can you schedule a catchup to discuss on this regard?

**Comment by leecalcote** [comment]
Understanding that e2e here would likely be driven through GitHub workflows, note the mesheryctl action that @s1ntaxe770r is working on.

**Comment by ramrodo** [comment]
Sure. Do you want to discuss this in the next Meshery CI meeting @leecalcote @kumarabd? I just added to the [agenda](https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit#)

**Comment by leecalcote** [comment]
@kumarabd I added the following two Acceptance Tests:

- [ ] Automatic invocation of rediscovery upon reconnection to existing broker.
- [ ] Manual ad hoc rediscovery upon click of Operator chip.

**Comment by kumarabd** [comment]
@leecalcote All of the above scenarios covered. Let me know if I missed something. Im assigning myself from here.
