### ISSUE TITLE
[mesheryctl] Kubernetes deployments require Internet access

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2580]
#### Description
Users not connected to the Internet, who try to start Meshery on Kubernetes are unable to do so. They can an overly verbose error message instead.

#### Expected Behavior
1. `mesheryctl` should use cached k8s manifests when GitHub.com is not reachable (when remote manifests are not reachable).
1. Error message should be concise and handled gracefully with instructions provided to the user.

#### Screenshots/Logs
```
➜  ~ ➜  ~ mesheryctl system start
Error: failed to start Meshery
See https://docs.meshery.io/guides/mesheryctl/\#meshery-lifecycle-management for usage details
: failed to make GET request: failed to make GET request to https://api.github.com/repos/layer5io/meshery/git/trees/3ba314a0870d5291be6216b4d60d2bc9675a39b2: Get https://api.github.com/repos/layer5io/meshery/git/trees/3ba314a0870d5291be6216b4d60d2bc9675a39b2: dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:63927->[::1]:53: read: connection refused
Usage:
  mesheryctl system start [flags]

Flags:
  -h, --help          help for start
      --reset         (optional) reset Meshery's configuration file to default settings.
      --silent        (optional) silently create Meshery's configuration file with default settings.
      --skip-update   (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string    config file (default location is: /Users/lee/.meshery/config.yaml)
  -c, --context string   (optional) temporarily change the
```

#### Environment:
- Meshery Version: v0.5.0-rc-6
- No network connection in this environment.

**Comment by Maxgit3** [comment]
@leecalcote do you mind if I look at this?

**Comment by leecalcote** [comment]
Sounds real good, @Maxgit3

**Comment by Maxgit3** [comment]
@leecalcote 
under /meshery/mesheryctl/internal/cli/root/system/system.go I see manifestsURL points to the github location.  should we add another const pointing to the location of the locally stored manifests?

under /meshery/mesheryctl/pkg/utils/helpers.go, GetManifestURL function looks like a possible way to get local manifest location if one exists

looking at the code under /meshery/mesheryctl/internal/cli/root/system/stop.go it looks as though it deletes manifests 

under /meshery/mesheryctl/internal/cli/root/system/start.go the applyManifest function may also be an option

**Comment by navendu-pottekkat** [comment]
@Maxgit3 locally, the manifest files are stored in `.meshery/manifests` folder. This is shown in `platform.go` file-

```go
var (
	// ManifestsFolder is where the Kubernetes manifests are stored
	ManifestsFolder = "manifests"
)
```
So, what this fix would look like is that each command should check if the manifest files are present in this folder and only download from GitHub if they are not present and GitHub is reachable.

PS- You may need to update your fork to reflect the latest changes as some of the stuff you mentioned have been moved around.

**Comment by piyushsingariya** [comment]
@Maxgit3 any updates on this?

**Comment by Maxgit3** [comment]
@piyushsingariya yes, working on creating the function to fetch the cached manifests.  New to Golang but I am picking it up.

**Comment by piyushsingariya** [comment]
@Maxgit3 if you need any help, keep it posted here!

**Comment by Maxgit3** [comment]
@piyushsingariya it looks like Meshery doesnt save the manifest list to a file.  The manifest list that the Apply Manifest function uses.  would it be prudent to write another file to the local 
meshery folder

**Comment by piyushsingariya** [comment]
We shouldn't probably think about writing a new file, and the manifest list is more like a reference to the files downloaded in the .meshery folder.
Can I ask what is your exact strategy here?

**Comment by Maxgit3** [comment]
@piyushsingariya I was following the same flow of fetchmanifests function where the return was the manifest list that was being applied to the apply manifest function.  it looks like the apply manifest funtion is using the list to determine which adapters to apply

**Comment by Maxgit3** [comment]
@navendu-pottekkat @piyushsingariya 

I wanted to run this code past you:

```
	var manifests []Manifest
	var manifestsError error
	manifests, err = utils.GetCachedManifests(version)
	if manifestsError != nil {	
		manifests, manifestsError = utils.FetchManifests(version)
			if manifestsError != nil {
				return manifestsError
			}
		return manifestsError
	}
```
I am using the first function to fetch the local files and only fetch remotely if there is an error.  I get an error though declaring manifests.  it does not recognize the Manifest struct type even though it looks like Manifest.go is imported

**Comment by navendu-pottekkat** [comment]
@Maxgit3 Not sure what the error is... It would be best if you make a draft PR so that we can look into the code properly

**Comment by piyushsingariya** [comment]
I think this would work like this, @Maxgit3 
```
	var manifests []Manifest
	var manifestsError error
	manifests, manifestsError = utils.GetCachedManifests(version)
	if manifestsError != nil {	
		manifests, manifestsError = utils.FetchManifests(version)
			if manifestsError != nil {
				return manifestsError
			}
	}
```
It would be best if we could look into the exact code!

**Comment by Maxgit3** [comment]
@navendu-pottekkat ok will do

**Comment by Maxgit3** [comment]
@navendu-pottekkat I am getting the issue unable to discover endpoint with minikube also.  is it possible to try running the build in a cloud platform like google?

**Comment by Maxgit3** [comment]
@piyushsingariya @navendu-pottekkat I can't see anything in my code changes that should prevent it from finding endpoint.  maybe I missed something in the changes.

**Comment by navendu-pottekkat** [comment]
It may be because of some networking issue. Could you try using Kind with a loadbalancer locally? Even if it shows unable to discover endpoint, Meshery will still be deployed and you can look at your services to see where it is deployed.

**Comment by navendu-pottekkat** [comment]
It may be because of some networking issue. Could you try using Kind with a loadbalancer locally? Even if it shows unable to discover endpoint, Meshery will still be deployed and you can look at your services to see where it is deployed.

**Comment by navendu-pottekkat** [comment]
@NupurThakur27 assigning this to you...

**Comment by NupurThakur27** [comment]
> @NupurThakur27 assigning this to you...

Thanks @navendu-pottekkat

**Comment by NupurThakur27** [comment]
@navendu-pottekkat If this task is on priority then please assign it to somebody else, I wasn't able to work on it this week and weekend won't be possible for me either.

**Comment by piyushsingariya** [comment]
This issue isn't relevant anymore since we moved away from manifest to helm charts based installation which doesn't download/cache files in the system. 

Closing this for now!
