### ISSUE TITLE
[Docs] Release notes are no longer auto-publishing

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2612]
**Current State:**
Each time a release is made, the auto-generated release notes are to be published here - https://docs.meshery.io/project/releases. The CI workflow that published these notes is broken or not firing.

Workflow - https://github.com/layer5io/meshery/blob/master/.github/workflows/release-notes.yml

Reference - https://github.com/layer5io/meshery/issues/510

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@ramrodo this issue might need you to flex your muscles on it.

**Comment by ramrodo** [comment]
Sure! Let me take a look

**Comment by leecalcote** [comment]
Yes, sir. It’s hidden over here - https://github.com/meshery/meshery/blob/7829a94ce2700ea60e3e20f4386646e217bfe6a6/.github/workflows/release-drafter.yml#L26

**Comment by leecalcote** [comment]
There’s a section on automated release notes generation in the Meshery Build and Release strategy doc https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit. It’s short, but may be of help.

**Comment by leecalcote** [comment]
I haven't investigated, but I often wondered if the automation would fail based on use of unescaped characters in the title of the issues that are being documented. If I recall correctly, the workflow didn't necessarily account for backticks or other potential conflicts.

**Comment by ramrodo** [comment]
@leecalcote With this commit https://github.com/meshery/meshery/pull/2646/commits/b099910db8359ec64f99f1b43e69902d9eabb949 I validated that this workflow will be working well when it should. As an example, here is the PR for the latest release version: https://github.com/meshery/meshery/pull/2648

And with that PR, the workflow will be triggered only at creating Github Tags

**Comment by ramrodo** [comment]
I think this workflow works as you all can see in this PR closed: https://github.com/meshery/meshery/pull/2681

It will only be triggered at releasing a new version of meshery.

**Comment by leecalcote** [comment]
Drafting of release notes. ✅ 
Publishing of release notes. ❌ 

Right?

**Comment by ramrodo** [comment]
I don't think so. I think both are working.

- Drafting of release notes
![image](https://user-images.githubusercontent.com/2797052/116315981-ed0d8d80-a776-11eb-821e-79f6829056ff.png)

- Auto publishing of release notes to Meshery Docs. 
![image](https://user-images.githubusercontent.com/2797052/116316002-f39c0500-a776-11eb-8ca0-826cc797d202.png)

We don't have release notes from _v0.4.20_ to _v0.5.2_ because in those versions the CI workflow was not working, but after merging https://github.com/meshery/meshery/pull/2697 it should work.

Or maybe I've understood it wrong.

**Comment by leecalcote** [comment]
Oh, ok. I could be misunderstanding the state of the flows. I'm hopeful this is the case. :) We're ready to make a v0.5.3 release, I believe and should be able to prove this out.

**Comment by ramrodo** [comment]
Yeah! It's a good opportunity to prove this out 👍🏼

**Comment by ramrodo** [comment]
Reopening... this doesn't work yet

**Comment by ramrodo** [comment]
We would like to auto-publish the release notes at creating a new tag. Currently, there is always a PR that is being updated on every commit merged to master and we need to merge this PR first and then create a release. These steps are too manual and we need to remember the process. So, we need to auto-publish on every Github tag created.
