### ISSUE TITLE
[mesheryctl] Include `mesheryctl` in `system update`

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#2668]
#### Current Behavior
Currently `mesheryctl` doesn't include any command to update globally installed `mesheryctl`

#### Desired Behavior
Request to include a feature sub-command to update globally installed `mesheryctl` under `version` command such as `mesheryctl version update`

**Comment by leecalcote** [comment]
Thanks, @piyushsingariya. Good First Issue label removed. Design Required issue affixed.

**Comment by leecalcote** [comment]
Here are instructions on "[Creating a Functional Specification](https://docs.google.com/document/d/1RP3IWLc-MiQS-QYasqCoVuCH7--G87p5ezE5f_nOzB8/edit?usp=sharing)" to get you going.
