### ISSUE TITLE
[mesheryctl] `pattern apply -f` to support retrieval from GitHub

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2709]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`pattern apply -f` only supports local filesystem URIs.

#### Desired Behavior
`pattern apply -f` should also support retrieval of pattern files from GitHub.

#### Implementation
Using the endpoints created in PR https://github.com/layer5io/meshery/pull/2705 

#### Acceptance Tests
1. Users may provide reference to a single pattern file in a public GitHub repo, using this type of reference: `https://github.com/layer5io/meshery/blob/master/.goreleaser.yml`

#### Future 
1. Users can provide reference to a single pattern file using a generic HTTP reference like `https://raw.githubusercontent.com/layer5io/meshery/master/.goreleaser.yml` 
2. Users cannot provide reference to a folder containing multiple pattern files in a public GitHub repo.

---
#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by Kn99HN** [comment]
Can I try my hand at this feature?

**Comment by leecalcote** [comment]
That would be excellent, yes, @Kn99HN. 👍

**Comment by adithyaakrishna** [comment]
@Kn99HN Any Update on this? 👀
