### ISSUE TITLE
[CI] GitHub Action to run SMI conformance tests

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2711]
**Current Behavior**
Meshery is the Service Mesh Interface (SMI) conformance tool. It verifies the compatibility of any service mesh with that of SMI. Conformance tests can be invoked from either of Meshery's two clients: the UI or CLI. 

`mesheryctl mesh validate` command validates service mesh conformance to different standard specifications.

**Desired Behavior**

A GitHub Action/Workflow should be created that leverages this command to run conformance tests, so that users and service mesh projects alike can incorporate these conformance tests into their pipelines.

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by ramrodo** [comment]
@s1ntaxe770r can you put a comment here in order to assign you this issue. I don't know why Github don't allow without that u.u

**Comment by s1ntaxe770r** [comment]
sure :)

**Comment by DelusionalOptimist** [comment]
@leecalcote @s1ntaxe770r Let's close this? Since we have https://github.com/meshery/meshery-smi-conformance-action now :trumpet: :trumpet: :trumpet:

**Comment by s1ntaxe770r** [comment]
agreed
