### ISSUE TITLE
[Meshery] experimental/patternfile/import/github.com/ ref query

### ISSUE THREAD

**Issue by Kn99HN** [meshery/meshery#2728]
I think this would round out the import via GitHub feature!

#### Current Behavior
`experimental/patternfile/import/github.com/` supports import file via GitHub URL by supplying `path/to/patternfile` for query `path`

#### Desired Behavior

GitHub API for fetching [repository](https://docs.github.com/en/rest/reference/repos#get-repository-content) also supports `ref` query which allows user to refers to file on different branch. An user might be interested in referencing file on a different branch other than master

#### Implementation

- Add `ref` query to Meshery API

#### Acceptance Tests

- User can pass a GitHub URL to a different branch than master and can still import the file

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
Makes much sense. 👍

I suspect that before support for pattern import from GitHub moves out of experimental that the query string parameters will be shifted to POST data. This shift might affect the suggested implementation (which falls inline with the current implementation’s approach), but not materially affect the proposed functionally. 

// @utkarsh-pro

**Comment by leecalcote** [comment]
@Kn99HN if you keep this up, we’re going to have to extend your GitHub user an invitation to join the ‘meshery’ GitHub org. Your engagement here is excellent.
