### ISSUE TITLE
[mesheryctl] Versioned download of operator manifests

### ISSUE THREAD

**Issue by metonymic-smokey** [meshery/meshery#2758]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Currently, operator manifests for `mesheryctl` are downloaded the same way as adapters. The latest version is downloaded from a fixed URL and if a change is required, the user has to change it manually. 

#### Desired Behavior
Operator manifests should be downloaded based on version. The version should be specified prior to download.    
The version for operator manifests and the other manifests do not match currently since they are in different repos and versioned differently. 

---

#### Environment

- Platform: kubernetes

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by metonymic-smokey** [comment]
//adding @leecalcote @navendu-pottekkat @kumarabd to this thread.

**Comment by leecalcote** [comment]
Thank you

**Comment by navendu-pottekkat** [comment]
This is a little tricky. @leecalcote we decided that this should behave similar to how the users are able to modify the adapter docker images manually by modifying the meshery.yaml file. In that case, it could be done by just modifying the tag of the image.

But for the operator manifests, there is no way for the user to specify the version currently than modifying the mesheryctl source code.

Not sure how we can fix this issue other than tracking the version of the operator on mesheryctl.

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat @leecalcote is this issue important right now?  
There is a design spec for this in the community drive, which needs to have some points agreed upon.

**Comment by navendu-pottekkat** [comment]
@metonymic-smokey Could you link to the spec?

For normal users this would not be an issue if they are always pinned to the latest release.

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat here you go: https://docs.google.com/document/d/1sMSOSQNCxXzPrDfSyLMmmYb21X3EgZxdxlIdG_YuQNA/edit?usp=sharing    

We had to discuss in what way the `meshconfig` would have versions separately for both operators and general meshery version.
