### ISSUE TITLE
[Meshery] Meshmap static default configuration

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery#2822]
#### Description
Add a default static configuration for meshery extension when there is a failure with graphql plugin or MeshSync.

#### Expected Behavior
The default configuration needs to be displayed instead of re-rendering extension endpoint every time which is the current scenario.

#### Environment:
- Meshery Version: v.0.5.X
- Kubernetes Version: any
- Host OS: any
- Browser: any

**Comment by leecalcote** [comment]
@kumarabd @utkarsh-pro is this still valid?

**Comment by kumarabd** [comment]
@utkarsh-pro this is already present, correct  me if I am wrong, from our last conversation.

**Comment by leecalcote** [comment]
@utkarsh-pro, a reminder to evaluate this issue.
