### ISSUE TITLE
[Docs] Enhanced Error Code Reference Presentation

### ISSUE THREAD

**Issue by mgfeller** [meshery/meshery#2854]
Some possible enhancements that were discussed are:

* default sort by error code (int)
* sortable by error name
* sortable by severity
* filtering
* searching

Over time, more error codes will appear in this reference, from many more components, and with detailed information (Long Description, Probable Cause, Suggested Remediation).

_Originally posted by @mgfeller in https://github.com/layer5io/meshery/pull/2712#discussion_r618123955_

**Comment by mgfeller** [comment]
I think this should not be closed.

**Comment by Abhishek357** [comment]
currently, do we have any idea, plan on how to implement this searching and sorting feature?
