### ISSUE TITLE
[Meshery UI] Show only installed adapters on system dashboard

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#2855]
#### Current Behavior
In System Dashboard the adapter section is showing all adapters including active and inactive. 

#### Desired Behavior
Only installed adapters by the user should be visible on the system dashboard.

#### Implementation
Configuring shows the adapters component in the dashboard UI such that it sorts adapters and shows only the installed adapters.

#### Mockups
![image](https://user-images.githubusercontent.com/65453826/117354247-bfd78280-aece-11eb-8990-7845eaf781b1.png)

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Chadha93** [comment]
@leecalcote If my implementation approach is going in the wrong direction, please correct me.

**Comment by leecalcote** [comment]
@Chadha93 thats right. Any unregistered adapters should not have a corresponding menu item for its respective service mesh type.

**Comment by samirparhi-dev** [comment]
@Chadha93 : As a part of this issue , the left side pane also should show the service Mesh that is relevant for an organisation .

For Example : if i have Istio in my infra, then I should be able to see only `ISTIO` mesh on the left side pane.

**Comment by Chadha93** [comment]
> @Chadha93 : As a part of this issue , the left side pane also should show the service Mesh that is relevant for an organisation .
> 
> For Example : if i have Istio in my infra, then I should be able to see only `ISTIO` mesh on the left side pane.

In the navigator itself ?

**Comment by samirparhi-dev** [comment]
> > @Chadha93 : As a part of this issue , the left side pane also should show the service Mesh that is relevant for an organisation .
> > For Example : if i have Istio in my infra, then I should be able to see only `ISTIO` mesh on the left side pane.
> 
> In the navigator itself ?

yes in the , left pane of the meshery , it shows all the service mesh, which should be depending upon the service mesh that is installed in my K8S cluster. You can get this info may be from the `kube config` or some cloud provider config file (though i am not sure) but it should be part of some config file

**Comment by samirparhi-dev** [comment]
Any updates on this issue ?

**Comment by warunicorn19** [comment]
@Chadha93 has this issue been solved?

**Comment by Chadha93** [comment]
> @Chadha93 has this issue been solved?

Nope, not finding a proper context of the solution. @warunicorn19 would like to take this up?

**Comment by warunicorn19** [comment]
@Chadha93, don't know how much ill be able to get done, but I'll take a look 😅

**Comment by warunicorn19** [comment]
will deal with this when we switch to state management.

**Comment by Et-008** [comment]
I have made a fix for this issue, please check if it is the best approach.
New to this project, looking to forward to know about better approaches or feedbacks if any.
