### ISSUE TITLE
[Docs] Update the Docs with the list CloudEvents

### ISSUE THREAD

**Issue by Anita-ihuman** [meshery/meshery#2883]
**Current State:**
This issue is awaiting additional context / design spec material 

**Desired State:**
The  CloudEvents should be listed in the Docs.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by SAY-droid427** [comment]
Hello @Anita-ihuman! I wanted to work on this issue as an Open Source contributor. May I work on it if you provide more details on it? Thanks!

**Comment by Anita-ihuman** [comment]
Well, this issue just proposed and is yet to be confirmed, that's is why I cant assign this issue right now.

**Comment by afzal442** [comment]
still valid

**Comment by Anita-ihuman** [comment]
Well, yes it is available.
Although the issue is dependent on the community handbook. That’s where we will have this lists

**Comment by Anita-ihuman** [comment]
Well, yes it is available.
Although the issue is dependent on the community handbook. That’s where we will have this lists

**Comment by warunicorn19** [comment]
@Anita-ihuman are we good to put the `help wanted` label on this?

**Comment by Anita-ihuman** [comment]
Yes,  this should be on the community handbook
