### ISSUE TITLE
[mesheryctl] Unhandled error in `system logs` when Meshery is not running

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2884]
#### Description
With Meshery not running and the current context of meshconfig set to "platform: docker", `mesheryctl system logs` does not gracefully handle this situation (see logs).

#### Expected Behavior
- Docker platform: Prompt user with a question to start Docker.
- Kubernetes platform: Prompt user with a question to deploy Docker.

#### Screenshots/Logs
```
➜  ~ mesheryctl system logs
Starting Meshery logging...
Error: exit status 255
Usage:
  mesheryctl system logs [flags]

Flags:
  -h, --help   help for logs

Global Flags:
      --config string    config file (default location is: /Users/lee/.meshery/config.yaml)
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

#### Environment:
- Meshery Version: v0.5.11
- Context platform: docker

**Comment by navendu-pottekkat** [comment]
@leecalcote Could not reproduce the issue either. We do check if Meshery is running before we try to get the logs for both platforms.
![Screenshot from 2021-05-14 16-53-17](https://user-images.githubusercontent.com/49474499/118264446-53afdc80-b4d5-11eb-86fa-a6cbd2d9a872.png)

**Comment by leecalcote** [comment]
Regarding `system logs`, I will assume that I neglected to use `./mesheryctl` and used `mesheryctl` instead (or something like that). I have updated the test case status above.

**Comment by leecalcote** [comment]
Hmm. This is odd. The exit code above must have come from somewhere...

**Comment by navendu-pottekkat** [comment]
@leecalcote Still having this issue?

**Comment by leecalcote** [comment]
It would be nice not to show that logging is starting when Meshery isn't running (so, skip the first message, if Meshery isn't running.

```
$ mesheryctl system logs
Starting Meshery logging...
No logs to show. Meshery is not running.
```

**Comment by verma-kunal** [comment]
> It would be nice not to show that logging is starting when Meshery isn't running (so, skip the first message, if Meshery isn't running.
> 
> ```
> $ mesheryctl system logs
> Starting Meshery logging...
> No logs to show. Meshery is not running.
> ```

Hey @leecalcote , would love to help out here! Any guidance on how can i proceed would help? 🙂

**Comment by navendu-pottekkat** [comment]
@verma-kunal You have to just change the UX to what is mention in the comment.

**Comment by verma-kunal** [comment]
> @verma-kunal You have to just change the UX to what is mention in the comment.

Umm, i am actually not sure if i understood this right! It would really help if you could explain this a bit more, because I am new to the project & have not yet started using `meshery`  
Thanks 🙂

**Comment by verma-kunal** [comment]
I'll try & reproduce this issue! Would reach out if stuck anywhere! 🙂

**Comment by navendu-pottekkat** [comment]
@verma-kunal Instead of showing "Starting Meshery logging..." right away, wait to see if Meshery is running and then show it. Else, show that Meshery is not running and there are no logs to show.

It would be just moving the logging code after the check.

**Comment by verma-kunal** [comment]
I am not sure why, its been stuck here since 15min, after stopping Meshery 😅
![Screenshot 2022-02-07 at 2 10 28 PM](https://user-images.githubusercontent.com/72245772/152753436-7fd5d542-061d-47fe-a3f7-f672bb738779.png)

**Comment by navendu-pottekkat** [comment]
The way we check if Meshery is running might be shortsighted. It may not actually be an indicator of the running status of Meshery.

// @piyushsingariya @hexxdump

**Comment by piyushsingariya** [comment]
> I am not sure why, its been stuck here since 15min, after stopping Meshery 😅 ![Screenshot 2022-02-07 at 2 10 28 PM](https://user-images.githubusercontent.com/72245772/152753436-7fd5d542-061d-47fe-a3f7-f672bb738779.png)

@verma-kunal can you dig a little deeper where exactly the code get stuck??

**Comment by verma-kunal** [comment]
> @verma-kunal can you dig a little deeper where exactly the code get stuck??

Yeah, so when i view the `logs` when Meshery is up & running, its showing as soon as i run the command!
![Screenshot 2022-02-09 at 2 24 55 PM](https://user-images.githubusercontent.com/72245772/153160627-99c70351-73f0-41c1-abae-73815a026ff7.png)

But, when Meshery is stopped by `mesheryctl systerm stop` & then i try to view the logs, its taking a lot of time for me, to produce any result! (Like mentioned above)
Not sure if thats because of my system RAM (though its 8GB) or something else!

**Comment by piyushsingariya** [comment]
Nice, that's also a part of the issue that you need to fix now!

**Comment by verma-kunal** [comment]
> Nice, that's also a part of the issue that you need to fix now!

Oh, sure! Would love to help
So, as I am new to this project & the technologies and have just setup Meshery on my system, so some resources would definitely help me here to understand how to go about this. 
The [Meshery CLI guides](https://docs.meshery.io/guides/mesheryctl) may help here right? 
Any other suggestions would mean a lot

Thanks

**Comment by leecalcote** [comment]
Also - https://docs.meshery.io/project/contributing/contributing-cli

**Comment by verma-kunal** [comment]
Thanks for sharing! Will refer these

**Comment by verma-kunal** [comment]
Hey all, i am actually traveling to college right now, so it might take me a bit of time to set things up, before i start working on this issue! 

Would love to stick to this & work upon, but if you all feel to give a chance to any other folks from the community, i'll support that decision as well 🙂

Thank you!

**Comment by chinmaym07** [comment]
Hey Can I work on this ?

**Comment by verma-kunal** [comment]
Hey @chinmaym07 , thank you for doing this! 
it would be great if we could have a conversation on how you solved this issue, if thats alright with you. 
Really interested to know & would help me to gain more knowledge of `mesheryctl` 🙂

Let me know your thoughts!
