### ISSUE TITLE
[Docs] User Tokens: What they are and how to get yours

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2889]
**Current State:**
The Meshery REST API requires a valid user token for most of its endpoints, but not all.

**Desired State:**
Meshery docs should describe how users can download their token.

This page can be updated - https://docs.meshery.io/extensibility/api

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by srisatya1197** [comment]
Currently I have exams. I faced some issues while setup. I will ratify my mistakes with the help of community then after will start solving issues.
Thanks @adithyaakrishna for this.

**Comment by SirZeck** [comment]
Should this issue remain stale or open?

**Comment by leecalcote** [comment]
@khanjasir90 I completely missed your message. Yes, that would be great. Let me know if you would still like to do so.
