### ISSUE TITLE
[mesheryctl] `m` alias for `mesheryctl` in `system completion`

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#2890]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system completion` adds shell completion(automatic command completion).

#### Desired Behavior

It should also add an alias `m` for `mesheryctl` so that it will be easy for users to use `mesheryctl`.

`alias m='mesheryctl'`

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by samirparhi-dev** [comment]
From my point of view , We should not enforce the User Preference. It is should be up to the user how they want their alias to be. I think `kubectl` does not enforce the alias too.

**Comment by ankingcodes** [comment]
What about zsh users ? If the alias is added only to bashrc, it would be inaccessible to zsh users. Should we add to both bashrc & zshrc ?

**Comment by navendu-pottekkat** [comment]
@ankingcodes We do support `bash`, `zsh` and also `fish`. The user can actually pass in an argument when running the `system completion` command.

**Comment by bariqhibat** [comment]
Hi! Is it possible for me to look into this?

**Comment by warunicorn19** [comment]
Here you go! @bariqhibat

**Comment by leecalcote** [comment]
@bariqhibat, it would be great to arrive at something similar to https://github.com/ahmetb/kubectl-aliases

**Comment by bariqhibat** [comment]
> @bariqhibat, it would be great to arrive at something similar to https://github.com/ahmetb/kubectl-aliases

I see, should I create a CLI command to generate something like this aliases then?

**Comment by leecalcote** [comment]
@WLun001, do you have any thoughts on this subject?

**Comment by WLun001** [comment]
Seems like cobra completion doesn't support aliases out of the box. if we want `system completion` to create aliases, need to append it at the end of `GenBashCompletion` call

https://github.com/meshery/meshery/blob/036b9bc2cc81381892811504fe71290655ba391a/mesheryctl/internal/cli/root/system/completion.go#L67

I think another command would be better choice to generate aliases, instead of combining to `system completion`, because aliases is user preference kind of thing.

**Comment by navendu-pottekkat** [comment]
@leecalcote Can we close this? We can maybe write a blog post on tips to use Meshery faster with mesheryctl and suggest the user to add this manually.

**Comment by leecalcote** [comment]
@bariqhibat this is a great angle to cover in your upcoming mesheryctl blog post.
