### ISSUE TITLE
[API] Open API Specification and Documentation

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2902]
#### Current Behavior
Meshery's REST APIs are only documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1ABJCbfQRi0uN_YoP2kmHZ-lTI4S4QuvRk1_unomKNRE/edit#) and Meshery's REST API endpoints are defined in [server.go](https://github.com/layer5io/meshery/blob/master/router/server.go), but not well-commented or externally documented.

#### Desired Behavior
1. Autogenerated, Open API compatible specification of Meshery's REST APIs.
1. Using Swagger, Meshery's REST API documentation should be auto-generated and published. Ideally, published to the Meshery documentation site (https://github.com/layer5io/meshery/blob/master/docs).

#### Implementation
1. go-swagger to generate json from validation and serve as a local http endpoint for reference during development.
1. Create golang structs for each request and response.
1. Annotate each request with

Sample go file annotation:
```go
// Package handlers Meshery API.
//
// the purpose of this application is to provide an application
// that is using plain go code to define an API
//
// This should demonstrate all the possible comment annotations
// that are available to turn go code into a fully compliant swagger 2.0 spec
//
//
//     Schemes: http
//     Host: localhost:9081
//     BasePath: /
//     Version: 0.4.27
//     License: Apache-2.0 http://www.apache.org/licenses/LICENSE-2.0.txt
//
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//     Security:
//     - token:
//
//     SecurityDefinitions:
//     token:
//          type: JWT
//          name: token
//          in: cookie
//
//
// swagger:meta
package handlers

import "github.com/layer5io/meshery/models"

// swagger:route GET /api/server/version VersionAPI idversion
// Returns the version of the meshery server
// responses:
//   200: versionResponse

// Meshery version related metadata
// swagger:response versionResponse
type versionResponse struct {
	// in:body
	Body Version
}

// swagger:route GET /api/providers ProvidersAPI idprovider
// Returns the list of the available providers
// responses:
//   200: providersResponse

// List of avaialable providers and their metadata
// swagger:response providersResponse
type providersResponse struct {
	// in:body
	Body map[string]models.ProviderProperties
}

// swagger:route GET /api/config/sync ConfigSyncAPI idprovider
// Returns the list of the available providers
// responses:
//   200: prefResponse
//   401: errResp

// List of avaialable providers and their metadata
// swagger:response prefResponse
type prefResponse struct {
	// in:body
	Body models.Preference
}
```

#### Acceptance Tests
1. Rendered json, locally available API documentation for Meshery contributors

#### Future
1. Publish generated api docs on docs.meshery.io
   - https://towardsdatascience.com/setting-up-swagger-docs-for-golang-api-8d0442263641

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by piyushsingariya** [comment]
I want to give this a shot. I learning how to work with `go-swagger`.

**Comment by piyushsingariya** [comment]
@leecalcote swagger should be set up under the `./handlers` folder. right?

**Comment by utkarsh-pro** [comment]
@piyushsingariya I was also adding them under `handlers` package in file - docs.go. It would avoid merge issues as it is very likely that something may change while you work upon the docs. Also, it would be nice to have docs in a dedicated file, much cleaner I believe.

**Comment by piyushsingariya** [comment]
@utkarsh-pro to maintain that we can smaller pull-requests and mention the handlers/files we're currently working on here. Like I'm currently working on `performance` and `pattern`.

**Comment by utkarsh-pro** [comment]
> @utkarsh-pro to maintain that we can smaller pull-requests and mention the handlers/files we're currently working on here. Like I'm currently working on `performance` and `pattern`.

@piyushsingariya that's great however the convention in golang is to write package wide documentation in `doc.go`. Refer https://golang.org/src/fmt/doc.go if you would.
