### ISSUE TITLE
[CI] Notify Providers workflow should not run on mesheryctl or docs changes

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2905]
#### Description
The [Notify Providers workflow](https://github.com/layer5io/meshery/actions/workflows/notify-providers.yaml) is running too frequently.

#### Expected Behavior
The [Notify Providers workflow](https://github.com/layer5io/meshery/actions/workflows/notify-providers.yaml) should:

**Run when:**

- A tagged release (stable release) is made.
- Meshery Server or Meshery UI changes are merged to master.

**Not run when:**

- on merge of mesheryctl or docs changes.
- on pull request open.
- on push of commit to an open PR.

**Comment by leecalcote** [comment]
Mr. Martinez (@ramrodo) would you might taking a crack at this? The Meshery Cloud remote provider repo is running out of build time for the month.

**Comment by leecalcote** [comment]
@kumarabd

**Comment by ramrodo** [comment]
Sure, I'll take it.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue!

**Comment by DelusionalOptimist** [comment]
@ramrodo was a fix raised for this? If not, I think we can track this in #3413.

**Comment by ramrodo** [comment]
> @ramrodo was a fix raised for this? If not, I think we can track this in #3413.

@DelusionalOptimist is not addressed yet. Sure! We can track this issue there. Thanks for catching that!

**Comment by iamsdas** [comment]
I'd like to take up this issue

**Comment by DelusionalOptimist** [comment]
Sure @iamsdas. Go ahead :muscle:

**Comment by ramrodo** [comment]
Thanks, @iamsdas. I just assigned to you :)
