### ISSUE TITLE
[UI] Terminating `meshery-operator` through UI Terminates all meshery pods

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#2913]
#### Description
When a user terminates `meshery-operator` through UI-client, it triggers all meshery namespace pods to be deleted.

#### Expected Behavior
Only pods related to `meshery-operator` should be terminated.

#### Screenshots/Logs
```
>  kubectl get pods -A 
NAMESPACE            NAME                                         READY   STATUS        RESTARTS   AGE
kube-system          coredns-f9fd979d6-2b7fv                      1/1     Running       2          4d13h
kube-system          coredns-f9fd979d6-s8zrw                      1/1     Running       2          4d13h
kube-system          etcd-kind-control-plane                      1/1     Running       3          4d13h
kube-system          kindnet-cns2q                                1/1     Running       4          4d13h
kube-system          kube-apiserver-kind-control-plane            1/1     Running       4          4d13h
kube-system          kube-controller-manager-kind-control-plane   1/1     Running       18         4d13h
kube-system          kube-proxy-5l7jz                             1/1     Running       2          4d13h
kube-system          kube-scheduler-kind-control-plane            1/1     Running       22         4d13h
local-path-storage   local-path-provisioner-78776bfc44-gz4kf      1/1     Running       14         4d13h
meshery              meshery-54fc64ccfd-fmmgf                     1/1     Terminating   0          7m14s
meshery              meshery-broker-0                             2/2     Running       4          4d13h
meshery              meshery-consul-6c77dcd486-m6w6n              0/1     Terminating   0          7m1s
meshery              meshery-cpx-5bc6f8dddf-m82c5                 0/1     Terminating   0          6m45s
meshery              meshery-meshsync-f7678dbc5-5b4xr             1/1     Terminating   9          4d13h
meshery              meshery-nsm-6bb69cc498-pjf6p                 1/1     Terminating   0          6m58s
meshery              meshery-operator-549bf67565-w4ks6            2/2     Terminating   11         4d13h
meshery              meshery-osm-f4f7b47c6-fw9bb                  1/1     Terminating   0          6m37s
meshery              meshery-traefik-mesh-cd95d64b-bhmgb          1/1     Terminating   0          6m33s

```
#### Environment:
- Meshery Version: v0.5.12

**Comment by leecalcote** [comment]
Good eye, @piyushsingariya

**Comment by DantrazTrev** [comment]
I would like to work on this issue. And for a bit of clarity clarity can please someone confirm this issue is propagating from the Meshery-UI?

**Comment by piyushsingariya** [comment]
Yes, this is an issue from Meshery UI.

**Comment by piyushsingariya** [comment]
@DantrazTrev any updates?

**Comment by sudo-NithishKarthik** [comment]
Hey @piyushsingariya , I don't think it is an issue with the UI, because, from what i see, in the UI, it is just calling the graphql mutation and all the logic for what has to be deleted and all is handled by the graphql resolver. The only variable we are sending is the final state of the operator. So, i suspect it has something to do with the resolver, but, i didn't find anything wrong with that too 🤔 .
@DantrazTrev , what's your view on this ?

**Comment by DantrazTrev** [comment]
Yup @sudo-NithishKarthik sorry I've not been working on this lately . From what I could find There is no mutation for the meshery operator status solely .

**Comment by sudo-NithishKarthik** [comment]
> Hey @piyushsingariya , I don't think it is an issue with the UI, because, from what i see, in the UI, it is just calling the graphql mutation and all the logic for what has to be deleted and all is handled by the graphql resolver. The only variable we are sending is the final state of the operator. So, i suspect it has something to do with the resolver, but, i didn't find anything wrong with that too 🤔 .
> @DantrazTrev , what's your view on this ?

@dhruv0000  what's do you think ?

**Comment by leecalcote** [comment]
@dhruv0000 ?
