### ISSUE TITLE
Service mesh playground

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2931]
See https://layer5.io/programs/lfx for details.

**Comment by samirparhi-dev** [comment]
Just Curious , What exactly to be done here?

**Comment by leecalcote** [comment]
@samirparhi-dev, think: "labs.play-with-k8s.com" for service meshes using Meshery.

**Comment by Aniket118** [comment]
How can i contribute to this project?

**Comment by alphaX86** [comment]
I'd like to get an idea for this issue... Seems an intriguing one to take on! :)

**Comment by warunicorn19** [comment]
Wait, you want to work on this right😅😅?

**Comment by alphaX86** [comment]
Whoa @warunicorn19 I'm asking for ideas! xD since this is a part of upcoming LFX, I'm unassigning and asking for doubts before proceeding

**Comment by alphaX86** [comment]
> Wait, you want to work on this right😅😅?

Not yet! I want to know scope first and with permission from @leecalcote then only I would proceed

**Comment by warunicorn19** [comment]
Oops, sorry @alphaX86 😅

**Comment by CIPHERTron** [comment]
> I'd like to get an idea for this issue... Seems an intriguing one to take on! :)

+1 to @alphaX86

**Comment by MarcaWitt** [comment]
@wonderflow I would like apply for this project under the LFX . I have read the previous comments and the requirements you mentioned. Looking forward to it.

**Comment by leecalcote** [comment]
Mockup
![meshery-playground-alt-3](https://user-images.githubusercontent.com/7570704/147860528-a3d12f66-0a0e-4e02-8812-026c2f105cc7.png)

**Comment by SAEb-ai** [comment]
Hi @leecalcote. I am highly interested to do this under the LFX mentorship. I have also applied for the same. But I just have one concern regarding this like is this still being tracked in the Spring batch of LFX because I can now see that the application dates for the spring batch have been extended. 

I would be really grateful to you if you could please clarify my above concern. Thanks in advance!!!

**Comment by leecalcote** [comment]
We're announcing this quarter's four LFX interns this week and a couple other Layer5 interns as well. I encourage you to read these [FAQs](https://layer5.io/programs) and put them into action. You'll be most supported and encouraged when you do.

**Comment by SAEb-ai** [comment]
Ah, I see. Thanks for the response and from the next time I will put these [FAQs](https://layer5.io/careers/programs)  into action and be a part of this awesome community.

**Comment by leecalcote** [comment]
Initiated under https://play.meshery.io
