### ISSUE TITLE
[Docs] `mesheryctl system channel --switch` page missing

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2939]
#### Current State
No page exists for this command in the [mesheryctl Command Reference](https://docs.meshery.io/reference/mesheryctl).

#### Desired State
A docs page for this subcommand should be available.

#### Implementation
1. Create an entry for this subcommand in https://github.com/layer5io/meshery/tree/master/docs/_data/mesheryctlcommands/

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by DARK-art108** [comment]
Can I work upon this?

**Comment by adithyaakrishna** [comment]
Yes sure @DARK-art108 
Thanks for taking this up 🎉

**Comment by leecalcote** [comment]
@DARK-art108 please note the change in issue title and change in which command needs documented: `mesheryctl system channel --switch`. 

I accidentally created duplicative issues for `mesheryctl system status` and so, I'm updating this issue to another command flag that is missing documentation. // @umairnsr87

**Comment by umairnsr87** [comment]
@leecalcote  Thanks alot

**Comment by DARK-art108** [comment]
Hello, @leecalcote @adithyaakrishna I am finding a lot of difficulty in editing jinja of **mesheryctl-commands.md** , I have made some changes, should I raise a PR for it. for suggesting changes.

**Comment by adithyaakrishna** [comment]
Yes sure @DARK-art108

**Comment by adithyaakrishna** [comment]
@DARK-art108 Any Update Here?
