### ISSUE TITLE
[mesheryctl] Fails to retrieve manifests from the `.meshery/manifests` folder for Windows platform

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#2955]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Windows users are unable to start Meshery with `mesheryctl` as it is failing to create the manifests folder or not able to access the manifest folder.

#### Desired Behavior

Windows should have the same behaviour as Mac and Linux and a manifests folder should be created to store and retrieve the manifests.

#### Screenshots/Logs

@alphaX86 Please add the screenshot

#### Environment

@alphaX86 Please update the environment

- Host OS: Mac Linux Windows
- Meshery Version: stable-v
- Platform: Docker or Kubernetes

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
Sure @navendu-pottekkat

**Comment by alphaX86** [comment]
**Environment details:**
Host OS: Windows 10
Meshery version: Stable - v0.5.12
Platform: Docker with Minikube enabled

**Comment by piyushsingariya** [comment]
@alphaX86 Could you paste the output here?

**Comment by alphaX86** [comment]
> @alphaX86 Could you paste the output here?

I'm at lecture meet right now... Will post once I'm free

**Comment by alphaX86** [comment]
**Output screenshot**:
![image](https://user-images.githubusercontent.com/59508546/118471691-a67fd300-b725-11eb-963a-b5238adbdc05.png)

**Steps to reproduce**:
1. Go to $HOME and find `.meshery` folder
2. Delete the folder entirely as a reset wipe
3. Now, start the Meshery and accept if it asks to create config file

**Comment by alphaX86** [comment]
@piyushsingariya @navendu-pottekkat I have uploaded the pic as you guys requested. The info is also provided in above comments

**Comment by alphaX86** [comment]
> #### Desired Behavior
> Windows should have the same behaviour as Mac and Linux and a manifests folder should be created to store and retrieve the manifests.

Actually it fails to create, when a manifest folder is created and a yaml file is made, Meshery works fine without issues

**Comment by pottekkat** [comment]
This was actually a bug earlier, but I have fixed this in this PR https://github.com/meshery/meshery/pull/2914

Could you try this with the latest master branch and not with the current release? It was only fixed 4 days ago and was not released I guess.

**Comment by alphaX86** [comment]
Need to install make tools in windows then.... That's the sole reason I moved to Linux for development. Anyway will keep you posted

**Comment by alphaX86** [comment]
> Need to install make tools in windows then.... That's the sole reason I moved to Linux for development. Anyway will keep you posted

Well, actually never mind. I installed `make` via scoop. I'll try it now and edit details accordingly

**Comment by alphaX86** [comment]
Make returned an error in Windows 😞😑😑
![image](https://user-images.githubusercontent.com/59508546/118502855-b7d9d700-b747-11eb-9d83-7a8240843a8b.png)

**Comment by alphaX86** [comment]
![image](https://user-images.githubusercontent.com/59508546/118503179-012a2680-b748-11eb-9348-7ae274ba92de.png)

Sole reason why I don't trust Windows during development... 😑

**Comment by alphaX86** [comment]
@navendu-pottekkat we need another tester for Windows platform, I could not compile it in Windows for `make`

**Comment by kumarabd** [comment]
@navendu-pottekkat any final actions taken here?

**Comment by navendu-pottekkat** [comment]
This issue has not been reported since. Will test it again to confirm.

**Comment by navendu-pottekkat** [comment]
@alphaX86 Could you test this out and see if this is still an issue?

**Comment by alphaX86** [comment]
@navendu-pottekkat Rog' 👍

**Comment by alphaX86** [comment]
@navendu-pottekkat seems operator manifests is still an issue
![image](https://user-images.githubusercontent.com/59508546/134694929-ab56efa0-2bb0-49c4-bab8-2b44613bd61d.png)

Tested this recently in Windows

**Comment by alphaX86** [comment]
But in CMD client, it worked unlike the previous one I reported months back

**Comment by alphaX86** [comment]
Sorry for saying a wrong info, I configured it to use my kube cluster via manual upload of config file. It worked

**Comment by alphaX86** [comment]
Good to close this issue 🎉

**Comment by navendu-pottekkat** [comment]
Thank you for testing @alphaX86 !
