### ISSUE TITLE
[mesheryctl] Prevent mesheryctl from rewriting the meshery.yaml docker-compose file and allow users to specify version of the adapter

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#2956]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl` overwrites the **entire** configurations in the `meshery.yaml` after it is downloaded from GitHub on `system start`.

This prevents an advanced user from modifying the meshery.yaml file and use it. 

The users cannot now specify a version of the adapter required. They are stuck at the latest version.

#### Desired Behavior

Instead, `mesheryctl` should only modify the required configurations or values that are specified in the meshconfig in meshery.yaml and allow the users to edit the meshery.yaml if they need some advanced configurations. 

Users should also be able to specify the versions of the adapter required in the meshconfig file.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by navendu-pottekkat** [comment]
This issue needs to be worked on.

**Comment by nehaLohia27** [comment]
@navendu-pottekkat I can take this up

**Comment by suhaniii** [comment]
> @navendu-pottekkat I can take this up

I can participate as well.

**Comment by navendu-pottekkat** [comment]
Sure, thank you.

**Comment by nehaLohia27** [comment]
@navendu-pottekkat @leecalcote need help from someone who have idea and can help to understand the context ?

**Comment by suhaniii** [comment]
@navendu-pottekkat @leecalcote   I have setup mesheryctl using https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md. 

Able to see the UI as well on http://localhost:9081. 

Now I can't find meshery.yaml under /Users/<name>/.meshrey . Where can we find that. Any pointers? - Needed to understand issue properly. :)

**Comment by navendu-pottekkat** [comment]
@suhaniii You can run `mesheryctl system start` with "docker" platform and it should be created in the .meshery folder.

**Comment by navendu-pottekkat** [comment]
`mesheryctl system start -p docker` should create a new config file and download the docker-compose file (meshery.yaml).

**Comment by leecalcote** [comment]
Completed in a release prior to v0.6.0
