### ISSUE TITLE
[mesheryctl] `system start --reset` does not reset the meshconfig before starting Meshery

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#2957]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system start --reset` does not reset the meshconfig file for Kubernetes and resets the meshconfig after starting Meshery in Docker(which will fail if the user had modified the meshconfig).

#### Desired Behavior

`mesheryctl system start --reset` should first reset the meshconfig file and then restart Meshery for both the platforms.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by tushar912** [comment]
@navendu-pottekkat I am interested to work on this.Can you assign it to me.

**Comment by metonymic-smokey** [comment]
@tushar912 are you facing any blockers with this? Let us know if you need any help!

**Comment by chetak123** [comment]
Hey @navendu-pottekkat I see this issue is inactive for some time, I am new to mesheryctl and can I please collaborate on this issue ?.

**Comment by navendu-pottekkat** [comment]
Yes sure, @metonymic-smokey could you verify the issue?

**Comment by metonymic-smokey** [comment]
For me, it does not reset config with Kubernetes(since I think the k8s part of the codebase lacks a `reset` flag).   

I think this issue is still valid.  

(Having some laptop issues so can't verify docker immediately, I'll do it in a bit. Sorry for the delay!)

**Comment by metonymic-smokey** [comment]
@chetak123 have you been able to start working on this one?  
Any issues/blockers you're facing, do let us know!

**Comment by chetak123** [comment]
Actually I was having some issues in installing mesheryctl, I think I have resolved most of them and have started working on the actual issue.

**Comment by metonymic-smokey** [comment]
@chetak123 have you been able to work on this issue?

**Comment by amitech** [comment]
I would like to give it a try, also it is my first issue. Please assign to me.

**Comment by warunicorn19** [comment]
here you go @amitech !

**Comment by leecalcote** [comment]
Thanks for stepping up, @amitech 💪

**Comment by amitech** [comment]
Update: I am done with local meshery setup. Now I will start working on it.

**Comment by amitech** [comment]
@navendu-pottekkat or someone else, can you please help me to generate the problem?

What I understand is, on my local k8s(minikube) setup,  I need to modify ~/.meshery/config.yaml file by adding some invalid content and need to run  `./mesheryctl system start --reset` command to see if config.yaml is corrected and meshery is started successfully.

Please correct me if I am thinking in the wrong way.

**Comment by navendu-pottekkat** [comment]
Yes. Any change in the meshconfig would be replaced by the `--reset` flag. Basically this would involve invoking the `reset` function from `mesheryctl system reset`.

**Comment by navendu-pottekkat** [comment]
@amitech Any updates on this issue?

**Comment by amitech** [comment]
@navendu-pottekkat still on it, sorry it is taking time, will update soon.

**Comment by navendu-pottekkat** [comment]
Do you need any specific help for this issue?

**Comment by amitech** [comment]
As per my understanding, the function from `reset` sub-command is called [here](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/system/start.go#L235) in `start` sub-command. So it should work as expected. Not sure where it should be included.

When I run with `--verbose` flag, it is not even going to reset function.

**Comment by navendu-pottekkat** [comment]
@amitech Moving that function call to reset to outside of the platform check should do the trick I think.

**Comment by amitech** [comment]
It works, thanks. It now resets the config in the same way as `mesheryctl system reset`.

But I have a doubt:
Does mesheryctl config file mean `~/.meshery/config.yaml` file OR does it mean manifest files for respective platform (here k8s) in location `~/.meshery/manifests/`.
Because `mesheryctl system reset`  is resetting manifests files only, not the  `~/.meshery/config.yaml` file.

See the output for both cases:
```shell
./mesheryctl system reset
Meshery config file will be reset to system defaults. Are you sure you want to continue [y/n]? y
Meshery resetting...

Current Context: local
Channel: stable1
Version: latest
Platform: kubernetes

Fetching Meshery Server and Meshery Operator manifests for  local context...
downloading manifest files from https://github.com/meshery/meshery/tree/v0.5.56/install/deployment_yamls/k8s
...meshconfig has been reset to default settings.
```
and 

```shell
./mesheryctl system start --reset
Entered into the reset function
Meshery config file will be reset to system defaults. Are you sure you want to continue [y/n]? y
Meshery resetting...

Current Context: local
Channel: stable1
Version: latest
Platform: kubernetes

Fetching Meshery Server and Meshery Operator manifests for  local context...
downloading manifest files from https://github.com/meshery/meshery/tree/v0.5.56/install/deployment_yamls/k8s
...meshconfig has been reset to default settings.
downloading manifest files from https://github.com/meshery/meshery/tree/v0.5.56/install/deployment_yamls/k8s
Starting Meshery...
⣽ Deploying Meshery on Kubernetes
```
See I modified Channel from `stable` to `stable1` in `~/.meshery/config.yaml` but it didn't reset it.

Can you please confirm which file should be actually reset?

**Comment by navendu-pottekkat** [comment]
Hmm, this is confusing. Reset was used to reset the manifest files present in Meshery. The docker-compose file and the Kubernetes manifests. That was how it was used.

But resetting the meshconfig (Meshery Config, `.meshery/config.yaml`) makes sense to me. This can help when users have an invalid config and needs to reset it back.

@hexxdump @leecalcote @piyushsingariya @metonymic-smokey Could you check this?
