### ISSUE TITLE
[mesheryctl] Kubernetes platform does not consider skipUpdate flag

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#2961]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Adding the `--skip-update` flag on Docker platform will skip updating Meshery containers and does not do anything for platform Kubernetes.

#### Desired Behavior

Kubernetes platform should also take this flag into account and provide a consistent UX for both the platforms.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Maxgit3** [comment]
@navendu-pottekkat I could look into this

**Comment by leecalcote** [comment]
@Maxgit3 thanks for jumping in. As you consider this, @navendu-pottekkat, we would do well to specify the Acceptance Criteria or Acceptance Tests that defines the expected behavior.

**Comment by navendu-pottekkat** [comment]
@Maxgit3 Thank you for jumping in. I will update the acceptance criteria shortly.

**Comment by pottekkat** [comment]
@Maxgit3 This will also involve your https://github.com/meshery/meshery/pull/2807 PR

`skip-update` should skip checking for new manifest files and pulling them. This relates to having cached manifests on the user's machine

**Comment by navendu-pottekkat** [comment]
@Maxgit3 Could you update this?

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat #3285 has added the provisions for a `skip-update` flag for k8s too...

**Comment by metonymic-smokey** [comment]
Working on it...
