### ISSUE TITLE
[mesheryctl] Context parameter to control service type deployed

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery#2968]
#### Current Behavior
Currently meshery when deployed in kubernetes, is deployed as service type NodePort by default.

#### Desired Behavior
Moving forward, the service type needs to be dynamically configured based on the user's preference, adding a context paramter called `serviceType` would suffice this need.

- Host OS: Mac Linux Windows
- Meshery Version: all
- Platform: Kubernetes

#### Implementation
- Add a context parameter to support different service types.
- Change the service type in the manifest, based on the context parameter value.
- 
---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by vineethvanga18** [comment]
@abhishekkumkar A few clarifications regarding the issue

1. What should be the command for this?
2. By manifest, do you mean ~/.meshery/manifests/meshery-service.yaml?

**Comment by kumarabd** [comment]
@navendu-pottekkat Will you help @vineethvanga18  with the docs explaining what context is?

**Comment by navendu-pottekkat** [comment]
@vineethvanga18 The `config.yam`l will be modified to accommodate this. i.e Viper should properly read this config and get the `serviceType` parameter.

Then, as you mentioned, we should rewrite the manifest file to reflect this change.

`system context create` should have a flag which allows users to set this value. The default value should be decided if the user does not specify a value.

@abhishekkumkar one question I have here is that this parameter is redundant for docker platform right? How should we handle that? It might be confusing for the user.

// @leecalcote

**Comment by leecalcote** [comment]
@hexxdump @piyushsingariya @panyuenlau do you consider that this is needed?

**Comment by piyushsingariya** [comment]
> @hexxdump @piyushsingariya @panyuenlau do you consider that this is needed?

We always need a NodePort to access meshery out-of-cluster in k8s. Not sure why this issue was created?

**Comment by navendu-pottekkat** [comment]
@piyushsingariya Not necessarily, it could be a LoadBalancer which is the current default service type. We could definitely add a configuration here in the meshconfig. We should plan which command would handle modifying this. Should it be a system command or should it be a sub-command for context? We should give it some thought on how to proceed if we decide we are proceeding with this.

**Comment by navendu-pottekkat** [comment]
@piyushsingariya @hexxdump Did we reach a consensus on whether or not to add this feature?

**Comment by piyushsingariya** [comment]
> Did we reach a consensus on whether or not to add this feature?

The discussion was still on-going, maybe we should discuss this in the next dev meeting to grab attention from more people and we might get more views on this.
