### ISSUE TITLE
[mesheryctl] Error due to inability to execute browser command in WSL

### ISSUE THREAD

**Issue by anirudhjain75** [meshery/meshery#2972]
#### Description

Error occurs in WSL when trying to invoke browser operations when there is none. 

#### Expected Behavior

Not to execute browser command when none of the browsers are present. So no error will be displayed

#### Screenshots/Logs

```
➜  mesheryctl git:(master) ./mesheryctl system start                                                                                    
creating ~/.meshery/manifests folder...
downloading manifest files from https://github.com/layer5io/meshery/tree/v0.5.13/install/deployment_yamls/k8s
Starting Meshery...
...Meshery deployed on Kubernetes.
Opening Meshery in your browser. If Meshery does not open, please point your browser to http://localhost:32068 to access Meshery.
Error: failed to start Meshery
See https://docs.meshery.io/guides/mesheryctl/#meshery-lifecycle-management for usage details
: failed to exec command
See https://docs.meshery.io/guides/mesheryctl/#meshery-lifecycle-management for usage details
: exec: "xdg-open": executable file not found in $PATH
Usage:
  mesheryctl system start [flags]
Flags:
  -h, --help          help for start
      --reset         (optional) reset Meshery's configuration file to default settings.
      --skip-update   (optional) skip checking for new Meshery's container images.
Global Flags:
      --config string    config file (default location is: /home/anirudh/.meshery/config.yaml)
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

**Comment by leecalcote** [comment]
Thanks for this, @anirudhjain75. A change in this behavior to not open a browser when a browser isn't present is ideal (irrespective of whether the OS is WSL or other).

**Comment by alphaX86** [comment]
Ah one moment I also came across this...... @leecalcote and @anirudhjain75 this is caused by not installing `xdg-open` in WSL2. I also had it two days ago. After referring and installing the package, Meshery opened with no problems even in WSL2

**Comment by leecalcote** [comment]
Makes sense, @alphaX86. Thanks much. 👍

**Comment by alphaX86** [comment]
@anirudhjain75 did you try installing xdg-open and open Meshery? If yes, then we can safely close this issue

**Comment by leecalcote** [comment]
@alphaX86 good of you to follow up. Actually, the point of the issue is to not attempt to open a browser if any of the commands are missing (not to fix Anirudh’s environment).
