### ISSUE TITLE
Meshery Operator - Display status while it is Processing

### ISSUE THREAD

**Issue by ramrodo** [meshery/meshery#2983]
#### Description
When Meshery Operator is first activated, if the page is refreshed, the Meshery Operator switch and status will be deactivated besides it is processing the Operator.

#### Expected Behavior
Displays the real status while it is processing.

#### Screenshots/Logs

https://user-images.githubusercontent.com/2797052/118863046-0bf9ce00-b8a4-11eb-807a-0edf0e60348e.mp4

#### Environment:
- Meshery Version: v0.5.10
- Kubernetes Version: 1.19
- Host OS: Linux (Manjaro)
- Browser: Google Chrome

**Comment by leecalcote** [comment]
Great ask. Your feedback and thoughts will be most helpful here - [Messaging Framework and Notification Center](https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit) design spec

**Comment by Alenjojo** [comment]
Ca you assign me this. I will find and try to fix that bug, i'd love to work on it

**Comment by Alenjojo** [comment]
hey hi , i need some help to get started.
Pls if you can

**Comment by leecalcote** [comment]
Hi @Alenjojo, it’s great of you to jump in here. This particular issue is quite complex. It will require you to digest the spec listed in the comment above and implement operation tracking in golang with CloudEvents across multiple components along with a graphql subscription and React to deliver. How about we get you another one that sets you up for success?

**Comment by leecalcote** [comment]
@Alenjojo, here you are - https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+  These issue have the “help wanted” label. Also, look for those with the “good first issue” label.

**Comment by Alenjojo** [comment]
> 
> 
> @Alenjojo, here you are - https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+ These issue have the “help wanted” label. Also, look for those with the “good first issue” label.

Alright thx, i'll look into it. And thx for the help

**Comment by leecalcote** [comment]
@Alenjojo, you bet. I hope this only encourages you And since you onto an issue and path of higher success.

**Comment by Alenjojo** [comment]
awe thx, your so empowering 😀
