### ISSUE TITLE
[Docs] Document the drivers that are supported for minikube.

### ISSUE THREAD

**Issue by tushar912** [meshery/meshery#3009]
#### Current State
Currently there is no note regarding which drivers are supported for minikube.

#### Desired State
There should be a note regarding which drivers are supported for minikube.

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you, @tushar912 👍

**Comment by leecalcote** [comment]
@tushar912 given our Slack conversation, I assume that you would like to be assigned this issue, is that right?

**Comment by tushar912** [comment]
Sure I am working. I would make PR ASAP.

**Comment by leecalcote** [comment]
@tushar912 is this something that you would still like to complete?
