### ISSUE TITLE
[mesheryctl] (epic) Unit testing for mesheryctl commands

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#3016]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

Guide to start - [here](https://docs.google.com/document/d/1t8Ilb72gpvkLXjywSAkaUOxN6arObC_xOLih66ggCUk/edit#)

#### Current Behavior
Currently, we don't have any unit tests setup to test `mesheryctl` commands and their behaviour

#### Desired Behavior
Required to enable unit testing support for `mesheryctl` commands, to ensure the accuracy and robustness of each mesheryctl release.

**mesheryctl Unit Testing**
- Mark all possible situations for each `mesheryctl` command
- Write tests using Golang’s standard library
- A combination of CodeCov and GitHub Actions are to be used as mainstays in the approach to unit testing - https://github.com/codecov/codecov-action.

**Child Issues**
The following issues need to be closed to mark this feature as complete-

- [x] #3019 
- [x] #3407 
- [x] #3492 
- [x] #3833 
- [x] #3688 
#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by umairnsr87** [comment]
Can u please assign some subtasks to me ?
