### ISSUE TITLE
[Bash] Mesheryctl Installer: finding invalid platform

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3024]
#### Description
Following the instructions on meshery.io for running the bash script to install Meshery, the following issue occurs:

```
curl -L https://git.io/meshery | bash -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4282  100  4282    0     0   5273      0 --:--:-- --:--:-- --:--:--  5273
Enter a platform to deploy Meshery. Available platforms [docker, kubernetes]:
Invalid platform:
```

**Comment by leecalcote** [comment]
The docker and kubernetes instructions on meshery.io need to be updated like so

```
curl -L https://git.io/meshery | PLATFORM=kubernetes  bash -
```

**Comment by navendu-pottekkat** [comment]
@leecalcote Could you make a new release for Meshery? The bash script is out-dated

**Comment by navendu-pottekkat** [comment]
I have figured out the issue.

The issue is because in the bash script, we use `read` and it reads from the standard input. But, the standard input of the shell is already taken up. So, it would not read anything as the shell has already read the whole script.

We can change the one liner to make sure that we are able to have an interactive prompt.

**Comment by navendu-pottekkat** [comment]
This is what the command will look like without the flag-

![Screenshot from 2021-06-05 11-40-54](https://user-images.githubusercontent.com/49474499/120882054-f3531d00-c5f2-11eb-9d74-3746cf8eeb94.png)

This is what the command will look like with the flag-

![Screenshot from 2021-06-05 11-41-30](https://user-images.githubusercontent.com/49474499/120882082-1d0c4400-c5f3-11eb-921d-dc862de73f33.png)

**Comment by navendu-pottekkat** [comment]
If that is okay, then I will make changes to the docs.
