### ISSUE TITLE
[Docs] Document the Error Codes CLI utility tool

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3029]
#### Current State
A utility for automating the assignment of error codes and automatic generation of documentation of those error codes has been developed by @mgfeller 💪 . [Described here.](https://github.com/layer5io/meshkit/pull/48)

#### Desired State

A page under Contributing should providing contributors a description of the tool and instructions on how to ensure that when they are creating errors that they do so in _the Meshery way_ (in a way in which is compatible with this error code framework).

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@ramrodo we will look to integrate this utility into all workflows that build Meshery components that use the MeshKit library, so all of Meshery component repos and workflows. You're help here and understanding of the tool is most solicited.

**Comment by ramrodo** [comment]
@leecalcote Sure. I'll wait until that feature is merged to test it and implement it in the CI workflows.

I have some questions in the meantime:
1. This utility will create a log file with the error codes, right? So, a PR can not be merged if this file is not empty?
2. Do we plan to upload this file somewhere or it should be deleted on every CI workflow run?

**Comment by leecalcote** [comment]
It will produce a component-specific file (or files if the repo has multiple components) that need to be committed to the `_data` folder in the /docs directory. These datafiles are the source of the Error Codes reference - https://docs.meshery.io/reference/error-codes

// @alonsolopezr

**Comment by DelusionalOptimist** [comment]
> A page under Contributing should providing contributors a description of the tool and instructions on how to ensure that when they are creating errors that they do so in the Meshery way (in a way in which is compatible with this error code framework).

The page describing how to create errors has been created at https://docs.meshery.io/project/contributing-error. Would be great to receive feedback on this from one of the contributors cc @sayantan1413 : )
This also seems duplicate of https://github.com/meshery/meshery/issues/3206

The documentation on how the utility works is being tracked in https://github.com/meshery/meshery/issues/3208 and hasn't seen much progress.

**Comment by sayantan1413** [comment]
Hey @DelusionalOptimist the documentation on the meshkit error is well-written.But I have a little suggestion like I think we can also that after writing the functions we can run `make error` in the meshery repo and the error will get listed in the JSON files `errorutil_analyze_errors.json`, `errorutil_analyze_summary.json` and `errorutil_errors_export.json`. and after running `make error` a contributor can also list if some error code is duplicated or not and can change it accordingly. I think this can be added if needed otherwise the documentation is well written. 😃

**Comment by DelusionalOptimist** [comment]
That's a great suggestion @sayantan1413. We should surely add this to the docs. :white_check_mark:
Do you want to raise a PR for this? If not, no worries :D

**Comment by sayantan1413** [comment]
Yeah sure @DelusionalOptimist I will raise a PR for this.

**Comment by mgfeller** [comment]
Time flies. Let's keep this open for now.

**Comment by warunicorn19** [comment]
@DelusionalOptimist @sayantan1413 this is already done right?

**Comment by sayantan1413** [comment]
Yup, I guess it is already done!!
