### ISSUE TITLE
Add liveness probes to the Meshery K8s manifest

### ISSUE THREAD

**Issue by samirparhi-dev** [meshery/meshery#3030]
#### Current Behavior

Currently, the meshery pod is not restarting automatically when it crashes or dies due to several reasons. (For my use case when I try to install the istio add-on from the meshery UI, the image broke. This is because the Istio add-ons were already installed before)
#### Desired Behavior

The POD should be restarted Automatically if it faces any of such undesired scenario
#### Implementation

Please Add the liveness probe to the meshery manifest
#### Acceptance Tests

I can test the behavior once the feature is developed. 

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by vishal267** [comment]
I will take this issue

**Comment by leecalcote** [comment]
Thank you, @vishal267 💪

**Comment by vishal267** [comment]
@leecalcote  just to confirm, do we need to add liveness probe for all below charts ?

meshery-consul
meshery-cpx
meshery-istio
meshery-kuma
meshery-linkerd
meshery-nsm
meshery-operator
meshery-osm
meshery-traefik-mesh

**Comment by leecalcote** [comment]
+ @kumarabd

**Comment by samirparhi-dev** [comment]
> @leecalcote/ @samirparhi-dev  just to confirm, do we need to add liveness probe for all below charts ?
> 
> meshery-consul
> meshery-cpx
> meshery-istio
> meshery-kuma
> meshery-linkerd
> meshery-nsm
> meshery-operator
> meshery-osm
> meshery-traefik-mesh

Yes, As this would be applicable for all the mesh pods

**Comment by SirZeck** [comment]
@vishal267 are you still working on this issue? Seems inactive for quite long?

**Comment by SirZeck** [comment]
No updates @vishal267 ?

**Comment by rghdrizzle** [comment]
Hey is anybody working on this ???

**Comment by Efrat19** [comment]
This issue can be closed, all charts seem to have liveness and readiness probes in place

**Comment by leecalcote** [comment]
Thank you for confirming, @Efrat19.

Also: it is so absolutely lovely to see you participating here. Welcome! 🤗
