### ISSUE TITLE
[mesheryctl] Restart logic to be simplified/reconsidered

### ISSUE THREAD

**Issue by metonymic-smokey** [meshery/meshery#3032]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Currently, for platform: Kubernetes, `restart` logic deletes the pods and the system controller detects this and restarts these.  
But running `kubectl get pods -n meshery` shows no pods after restart if meshery was not running earlier.  

#### Desired Behavior

Irrespective of whether meshery was running earlier, `restart` should result in pods running at the end of the command.  

#### Environment

- Host OS: Mac Linux Windows
- Platform: Kubernetes

#### Implementation

Using `stop` and then `start` functions, similar to the implementation for docker. 

#### Acceptance Tests.    
Pods should be observed as running after `restart`, either using `system status` or `kubectl get pods -n meshery`.  

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by metonymic-smokey** [comment]
@DARK-art108 do you want to try working on this issue?

**Comment by DARK-art108** [comment]
Yes, I would like to work on it!

**Comment by metonymic-smokey** [comment]
@DARK-art108 how is this going? Any blockers you need help on?

**Comment by DARK-art108** [comment]
@metonymic-smokey will let you know for any help, working upon it! Thanks :)

**Comment by metonymic-smokey** [comment]
Closed via #3285
