### ISSUE TITLE
[CI] Open API Specification and Documentation workflow

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#3033]
#### Desired Behavior
Create a CI/CD workflow for Swagger documentation of Rest APIs

_Note: Issue created to track workflow for #2902_

Two workflows needed to track for REST APIs docs
- Needs to be triggered if changes are made in `./handlers` and `./models`
- One workflow to update `./swagger.yaml` with `make swagger-spec`
- Second workflow to update the data for docs.meshery.io i.e.`./docs/_data/swagger.yml` with `make swagger-docs`

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by piyushsingariya** [comment]
// @navendu-pottekkat What else should be updated here?

**Comment by amino19** [comment]
Hey, Can I know the work to-do here? ☺
