### ISSUE TITLE
`system start` does not check if Meshery pods are ready before trying to reach the Meshery server

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3034]
#### Description

`system start` on the Kubernetes platform does not wait for Meshery to be fully deployed and the pods running before trying to open Meshery on the browser.

#### Expected Behavior

`system start` should check for the status of the pods and only open it on the browser when Meshery is running

**Comment by leecalcote** [comment]
@hexxdump I wonder if you might have a look at this...

**Comment by hexxdump** [comment]
sure @leecalcote. Basically we need a watch kind of mechanism on the pod status and open the browser only when all pods are up, right?

**Comment by leecalcote** [comment]
Yes, ma'am, that's right. I'm trying to recall what detection mechanism was previously (or is currently used). This could be a readiness probe in the case of Kubernetes (and something similar that Docker might offer). Or this could be polling with HTTP GET to <endpoint:port>/provider and proceeding when a 200 is returned. Either of these would be a slight improvement (higher confidence that Meshery server is actually ready for use) beyond that of confirming the that container/pod is up.
