### ISSUE TITLE
[mesheryctl] `system dashboard` to open up Meshery UI

### ISSUE THREAD

**Issue by pottekkat** [meshery/meshery#3035]
#### Current Behavior

Users are presented with the endpoint to reach the Meshery UI when the initially run `system start` but it is not re-callable in any other subsequent commands.

#### Desired Behavior

A new subcommand `system dashboard` which will test the connection with the Meshery UI and if available, open it on the user's default browser.

If the UI is not accessible and the platform is Kubernetes, then initiate a kube proxy tunnel.

#### Acceptance Test

Running `mesheryctl system dashboard` should open up the Meshery UI providing a consistent UX for both Docker and Kubernetes platforms.

**Comment by DantrazTrev** [comment]
Hei @navendu-pottekkat , If no one else is working on it, Can you assign this issue to me ?

**Comment by navendu-pottekkat** [comment]
Sure, @DantrazTrev

**Comment by DantrazTrev** [comment]
Hei @navendu-pottekkat can you explain a bit more about the k8s case ?

**Comment by leecalcote** [comment]
@DantrazTrev, this particular feature is slated for a later release (v0.7.0), so let me insert @Aisuko here to engage with you.

**Comment by Aisuko** [comment]
Remove stale label

**Comment by leecalcote** [comment]
@hershd23 I wonder if you would be so kind as to confirm this behavior has been implemented to satisfaction. Do check the `experimental` portion of `mesheryctl` commands in case this functionality hasn't been exposed, yet.

**Comment by hershd23** [comment]
Sure @leecalcote
