### ISSUE TITLE
[mesheryctl] v0.7.0: Conventions on use of MeshKit Errors

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3043]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`mesheryctl` uses portions of MeshKit today. MeshKit Errors are is functionality that `mesheryctl` needs to inherit from MeshKit.

Alongside the use of MeshKit errors will be the benefit of use of the utility for error code generation and documentation.

#### Desired Behavior
As an objective of the v0.7.0 release, plan out use of MeshKit errors, providing these instructions within the mesheryctl coding conventions documentation - https://docs.meshery.io/project/contributing-cli

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by mgfeller** [comment]
Keep this open for the time being (an assignment that flew right past me :rocket: )

**Comment by sayantan1413** [comment]
Hey @mgfeller would you mind taking me with you if you are importing the meshkit error in mesheryctl ?

**Comment by mgfeller** [comment]
@sayantan1413 of course not, that would be nice :smile: It might take a while, though - it is free for anyone to pick.

**Comment by mgfeller** [comment]
Let's keep this open for now. 
There is work done in `mesheryctl` to convert the errors (in other issues), and there is e.g. some discussion here  https://github.com/meshery/meshery/issues/3986.
Eventually, amend https://docs.meshery.io/project/contributing-cli with a section about errors - including how Cobra handles them too, and how the stringified version of meshkit error is used.
Also add a reference to https://docs.meshery.io/project/contributing-error

// @piyushsingariya @DelusionalOptimist

**Comment by leecalcote** [comment]
@sayantan1413 @meshery/mesheryctl-contributors, any progress to report here?

**Comment by piyushsingariya** [comment]
I am mentioning packages where I can't see an `error.go` file
- app
- config
- pattern
