### ISSUE TITLE
Update "components" endpoints in Meshery server

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3048]
#### Description

The current endpoints for the "components" category in Meshery server should be updated.

The endpoints to be changed are-

Current Endpoint | Proposed Endpoint
-- | --
/system/graphql | CHANGE TO /graphql
/system/operator/status | CONSOLIDATE TO GRAPHQL
/system/operator | CONSOLIDATE TO GRAPHQL
/server/version | CHANGE TO /system/version
/config/sync | CHANGE TO /system/config
/mesh/manage | CONSOLIDATE TO /system/adapter/operation
/mesh/ops | CHANGE TO /system/adapter/operation
/mesh/ops/logflow | NO CHANGE
/mesh/adapters | CHANGE TO /system/adapter
/mesh/adapter/ping | CONSOLIDATE TO /system/adapter
/k8sconfig | CHANGE TO /system/kubernetes
/k8sconfig/contexts | CHANGE TO /system/kubernetes/contexts
/k8sconfig/ping | CHANGE TO /system/kubernetes/ping
/prometheus/scan | CHANGE TO /system/meshsync/prometheus
/promGrafana/scan | CHANGE TO /system/meshsync/grafana
/mesh/scan | CHANGE TO /system/meshsync/

**Changing this endpoint should be accompanied by changing the endpoints on the clients which use these endpoints (Meshery UI/ mesheryctl)**

#### Acceptance Test
All the endpoints in the Meshery server should be changed to the proposed endpoints.
The endpoints used by clients(Meshery UI and mesheryctl(if applicable)) should be updated.

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat 
This issue involves changing the endpoints in [`server.go`](https://github.com/layer5io/meshery/blob/master/router/server.go) right?  

What does 'consolidating' an endpoint mean?

**Comment by navendu-pottekkat** [comment]
Yes @metonymic-smokey you should change the endpoints in `server.go` and in all areas of UI and `mesheryctl` if these endpoints are used.

By "consolidating" we mean that we can combine two or more endpoints to a single one which can handle all the functions.

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat 
after changing endpoints, I ran `make build-ui` and then `make run-local`.   
How can I test these specific endpoints?

**Comment by navendu-pottekkat** [comment]
You can test out if these are working in the Meshery UI. Test all the features that use these endopoints?

Example you can ping Kubernetes and Adapter to see if it is working as expected.

@abhishekkumkar any thoughts on how to test this?
