### ISSUE TITLE
Host configuration step missing in documentation to setup Meshery locally

### ISSUE THREAD

**Issue by Ayush-Khandelwal-007** [meshery/meshery#3059]
#### Description
When ran Meshery locally the hosts are not configured properly due to which error shows up as
`Adapter was not configured due to an error`

#### Expected Behaviour
- Either we should have a script added to configure the etc/hosts file that could be ran with the make command
#### or Alternatively
- Add description for how to configure i.e. steps should be added in the docs telling to add the `127.0.0.1 mesherylocal.layer5.io` line in the file etc/hosts.

### Present Behaviour:
![screenshot_2021-05-28_at_11 05 37_pm](https://user-images.githubusercontent.com/59086855/120068503-a45f3200-c09e-11eb-8e84-6ae460a673be.png)
Error Appears something Like this

Expected changes:
After the configuration manually or by script etc/hosts file should contain line `127.0.0.1 mesherylocal.layer5.io`

#### Environment:
- Meshery Version: Any
- Kubernetes Version: Any
- Host OS: Any
- Browser: Any

**Comment by leecalcote** [comment]
We’ll stay away from automatically editing the user’s hosts file as it’s a little too invasive and individuals contributing to the project should be aware of networking considerations when working on Meshery.

We might change the default configuration away from mesherylocal.layer5.io, though, to just localhost.

**Comment by leecalcote** [comment]
Not a bug. Removing bug label.

**Comment by leecalcote** [comment]
@Ayush-Khandelwal-007 great alternative suggestion. Yes, minimally, we should add instructions in the contributing guide about this. In fact, they are right here - https://docs.meshery.io/project/contributing-ui#running-meshery-from-ide

**Comment by leecalcote** [comment]
I'll propose a third solution: change from mesherylocal.layer5.io to localhost as the default location for each adapter.

**Comment by Ayush-Khandelwal-007** [comment]
@leecalcote That would be grate!
