### ISSUE TITLE
[Docs] Feature: Data plane intelligence - Envoy-based WASM filter management

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3074]
#### Current State

Meshery has emergent support for filter management, but not documentation published on the set of functionality surrounding filter management.

#### Desired State

Create a new "Filter Management" page that describes this functionality area.

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sayantan1413** [comment]
Hey @leecalcote I would like to work on this issue.

**Comment by debjani1413** [comment]
Here you go :)
