### ISSUE TITLE
[CI] GraphQL API Documentation Workflow

### ISSUE THREAD

**Issue by dhruv0000** [meshery/meshery#3077]
#### Desired Behavior
Create a CI/CD workflow for automatic Document generation of `GraphQL APIs`
#### Implementation

- The workflow needs to be triggered when `internal/graphql/schema/schema.graphql` is changed.
- The workflow needs to run `bundle install ; bundle exec rake graphql:compile_docs` inside docs folder to updates the `docs/pages/extensibility/graphql-reference.md`.
- Create nessecory `make` commands.

#### Acceptance Tests

- In case of Invalid schema, the workflow should fail.
 Eg. More than one input in a mutation
  ```graphQL
  type Mutation {
	  # This mutation is invalid
	  changeAddonStatus(inputA: String, inputB: String ): String!
  }
  ``` 
#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by manishprivet** [comment]
Hi, could I work on this?

**Comment by debjani1413** [comment]
Sure, here you go!!

**Comment by amino19** [comment]
@manishprivet : Shall I work on this? :slightly_smiling_face:

**Comment by dhruv0000** [comment]
Sure @amino19 . Go ahead.
