### ISSUE TITLE
[Docs] Meshery UI: Additional Arch, framework and design principles need published

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3124]
#### Current State
This page describes the Meshery UI - https://docs.meshery.io/project/contributing-ui

#### Desired State
More of what is in this doc needs to be published - https://docs.google.com/document/d/1lSWjbxQ414DFnv-i_nBtbXa5cFV5MKbgwClpBjaLBro/edit#

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by hrishikeshnikam2000** [comment]
Could you please assign me this issue?
Also, the drive needs access, I have requested access.

**Comment by leecalcote** [comment]
Hi @hrishikeshnikam2000, yes. Please jump into the [community Slack](http://slack.layer5.io) and we'll get you setup.

**Comment by hrishikeshnikam2000** [comment]
Hello @leecalcote, I've joined the slack channel.

**Comment by Jordan-Rob** [comment]
@leecalcote @hrishikeshnikam2000 is this still being worked on? incase any assistance is needed I would be glad to help

**Comment by bariqhibat** [comment]
Hi! Just wanna up this issue whether this is still worked on or not. I can definitely help!

**Comment by leecalcote** [comment]
@Jordan-Rob @bariqhibat, thank you for asking. Yes, this effort is still much needed. // @dhruv0000 @sudo-NithishKarthik @Ayush-Khandelwal-007 @Nikhil-Ladha @jeantiston @Chadha93 @Abhishek-kumar09
