### ISSUE TITLE
[Security] Vulnerabilities in Meshery Docker Image

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3136]
#### Description
See this report for a list of known CVEs in Meshery and Meshery Adapter images - https://artifacthub.io/packages/helm/meshery/meshery?modal=security-report

#### Expected Behavior
The security score for Meshery and its adapters should be as high of grade as possible.

#### Screenshot

<img width="1142" alt="Screen Shot 2021-06-04 at 11 43 30 AM" src="https://user-images.githubusercontent.com/7570704/120835590-22518c00-c52a-11eb-98e7-2391487979c7.png">

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by debjani1413** [comment]
@leecalcote I would love to work on this issue, could you please guide me through it ??

**Comment by umairnsr87** [comment]
@leecalcote can I work on this issue?

**Comment by leecalcote** [comment]
Hi @umairnsr87, I had a brief chat with @debjani1413. I’ll let her recap my chat with you so that you and her might proceed eyes wide open. If you do move forward, it would be good to understand your plan of action for how to improve the security score.

**Comment by debjani1413** [comment]
Here you go @umairnsr87, good luck 👍

**Comment by leecalcote** [comment]
@debjani1413, are you deciding not to partner on this issue?
