### ISSUE TITLE
[UI] Toster notification shows `installed successfully` when we delete a configuration in Management.

### ISSUE THREAD

**Issue by dhruv0000** [meshery/meshery#3153]
#### Description
When we delete a configuration in an adaptor using the :wastebasket: icon, upon successful deletion it shows `[config] installed successfully`

#### Expected Behavior

It should show `[config] deleted successfully`

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/44001539/121042280-26530780-c7d1-11eb-86fd-363d0986586a.png)

#### Environment:
- Meshery Version: 0.5.19
- Kubernetes Version: 1.18
- Host OS: ubuntu
- Browser: Chrome

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by abhijeet007rocks8** [comment]
May I work on this issue ??

**Comment by dhruv0000** [comment]
sure, @abhijeet007rocks8

**Comment by dhruv0000** [comment]
@abhijeet007rocks8 Any blockers I can help you out with?

**Comment by abhijeet007rocks8** [comment]
> @abhijeet007rocks8 Any blockers I can help you out with?

Sir I am facing an issue to setup the backend server for meshery on local. I was not getting the meshes, to check the issue. 
I joined slack and try to fix someone told me. If that does'nt work. I'll contact you.

**Comment by yash112-lang** [comment]
Hello @dhruv0000, is this issue is still open? I wanted to work on this.

**Comment by dhruv0000** [comment]
Sure @yash112-lang .

**Comment by yash112-lang** [comment]
Sorry, for the delay but it was due to my exams, but now it's over so I will start working on this😀.

**Comment by yash112-lang** [comment]
I am unable to locate the file from which this issue is happening if anyone helps me on which file I have to work on?

**Comment by SirZeck** [comment]
Hey @yash112-lang are you still working on this issue? There haven't been any updates from your side?

**Comment by SirZeck** [comment]
No updates @yash112-lang ?

**Comment by yash112-lang** [comment]
@SirZeck I'm not working on this issue now. You can assign it to any other.

**Comment by SirZeck** [comment]
Sure @yash112-lang . You can go ahead and look for some other issue which you can work on. If you face any issue or have some doubt then ask in the slack channel after doing your homework though.

**Comment by khanjasir90** [comment]
@dhruv0000 can i give it a try?
