### ISSUE TITLE
[Patterns] Investigate Kube OpenAPI

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3158]
#### Current Behavior
An NPM package is being used to help transcribe custom resources into OpenAPI compatible specifications to satisfy Service Mesh Pattern requirements. We're in need of a Golang / Kubernetes native solution.

#### Desired Behavior
Explore and propose use or no use of https://github.com/kubernetes/kube-openapi

#### Implementation
- Write up your findings and incorporate the existing design specification, if needed.

#### Acceptance Tests
1. Maintainers weigh-in on whether to incorporate its use.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
Adding v0.7.0 milestone.

**Comment by utkarsh-pro** [comment]
@leecalcote, https://github.com/kubernetes/kube-openapi is a great tool however doesn't fits our use case right now. It takes in golang struct (with some annotations) and can generate openapi-spec as well as json schema from them.

Should we close this now?
