### ISSUE TITLE
CRUD for "application"

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3162]
#### Current Behavior

Meshery is going to support a new construct "application" which the users can use to configure and deploy their applications.

The application configuration will be declared in a YAML file.

#### Desired Behavior

Meshery Server should have API endpoints that support CRUD actions on these files.

#### Implementation

This would be an exact copy paste of the functionality in "pattern" and "filter".

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
The initial offering of functionality has been in delivered in v0.5.20.
