### ISSUE TITLE
[UI] Change the file name of Filters to MesheryFilters

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#3174]
#### Current Behavior
We are having two files with the same name Filters and filters in the UI which may cause confusion. 

#### Desired Behavior
Change the file name of Filters to MesheryFilters so they can be distinguished easily.

#### Implementation
Task - To change the file name of Filters.js to MesheryFilters.js
- Inside the Filter.js,filter.js, navigator.js (the filter under the configuration)
- In the above files update the import MesheryFilters from "../../components/Filters"; accordingly.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by ahcodes** [comment]
Hi Gaurav, I would like to work on this issue. Could you assign me, please? Thanks!

**Comment by Chadha93** [comment]
@ahcodes Have you joined our slack? If not let's get started http://slack.meshery.io/

**Comment by Chadha93** [comment]
@ahcodes Are working on this issue?

**Comment by ahcodes** [comment]
@Chadha93 Hey man, yeah. Had some personal stuff, apologies for the delay.

**Comment by ShivamSingh22** [comment]
Hey, please assign me this issue if it's available(or in future) else if @Chadha93 is working on it, then let it be. :)

**Comment by Chadha93** [comment]
> Hey, please assign me this issue if it's available(or in future) else if @Chadha93 is working on it, then let it be. :)

Hey @ShivamSingh22, @ahcodes is working on this issue you can look at other issues as well.

**Comment by saraswathy-krish** [comment]
Hello, I am a first-time contributor here and looking for a first-timers-only issue. I would be really glad if I could be helped in finding one. 
Thanks!

**Comment by stark255** [comment]
> #### Current Behavior
> We are having two files with the same name Filters and filters in the UI which may cause confusion.
> 
> #### Desired Behavior
> Change the file name of Filters to MesheryFilters so they can be distinguished easily.
> 
> #### Implementation
> Task - To change the file name of Filters.js to MesheryFilters.js
> 
> * Inside the Filter.js,filter.js, navigator.js (the filter under the configuration)
> * In the above files update the import MesheryFilters from "../../components/Filters"; accordingly.
> 
> **[Contributor Guide](https://docs.meshery.io/project/contributing)**

Hello there @Chadha93 , If this issue is not resolved yet then I would like to work on this issue.
