### ISSUE TITLE
New Notification Design implementation.

### ISSUE THREAD

**Issue by Ayush-Khandelwal-007** [meshery/meshery#3187]
#### Current Behavior
The present notification snack bars and alerts in notification drawer don't match the sigma designs as well as the present light theme.

In below image you could see the notification in the red box and you could open up the notification drawer form the icon in the top right marked with yellow.

![Screenshot 2021-05-28 at 1 41 57 PM](https://user-images.githubusercontent.com/59086855/121526793-5e4b8c00-ca17-11eb-926b-1e7bc5608405.png)

#### Desired Behavior
The notification snack bars and alerts in notification drawer should have the design as made in the figma.

#### Implementation
Look for the designs from the sigma 
[Figma Link](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=2328%3A7) 

From the below link you could find how to apply styling to the snackers easily.
- https://material-ui.com/api/snackbar/
- https://material-ui.com/customization/components/#overriding-styles-with-classes 

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by jeantiston** [comment]
Hi @Ayush-Khandelwal-007. I'm interested in helping with this. But I can't seem to access the Figma design.

**Comment by Ayush-Khandelwal-007** [comment]
Hi @jeantiston You can hop in our community by filling up the below form, then you could have access to figma and many other material that could be helpful. Also you would get few suggestions and helping hand in case of any issue you face.
[Form Link](https://meshery.io/community/newcomers)

**Comment by jeantiston** [comment]
Awesome! Thank you @Ayush-Khandelwal-007. I've filled out the form.

**Comment by Ayush-Khandelwal-007** [comment]
For any further requirements you could join us on slack.
