### ISSUE TITLE
[mesheryctl] Old meshconfig causes parsing failure

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3189]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
```
➜  ~ mesheryctl system start
Error: error processing config: 2 error(s) decoding:

* 'contexts[bob].token' expected type 'string', got unconvertible type 'map[string]interface {}'
* 'contexts[local].token' expected type 'string', got unconvertible type 'map[string]interface {}'
```

#### Meshconfig

- [config.yaml.zip](https://github.com/layer5io/meshery/files/6635530/config.yaml.zip)

#### Desired Behavior

Failure to parse is caught and gracefully handled by prompting the user to create a new config.

#### Environment

- Host OS: Mac
- Meshery Client Version: stable-v0.5.23

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by metonymic-smokey** [comment]
@leecalcote do you want to handle the error specifically when `token` types are mismatched?

**Comment by metonymic-smokey** [comment]
From what I understood in the `GetMesheryCtl` function in `config.go`, the only errors possible while un-marshalling are type mismatch errors?  Is that right or have I missed something?
