### ISSUE TITLE
[Compatibility] Meshery installer: PopOS

### ISSUE THREAD

**Issue by Shreyas220** [meshery/meshery#3200]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Was following guide to install meshery from [here](https://docs.meshery.io/installation/quick-start#install-meshery)
I need to be able to install meshery using `
 curl -L https://git.io/meshery | PLATFORM=docker bash - 
 `
but i am getting this 

![image](https://user-images.githubusercontent.com/55346934/121840962-005ec300-ccfb-11eb-81d2-b5ea8b753a1f.png)

#### Environment

- Host OS: Pop!_OS v20.10 
- Meshery Server Version: unavailable
- Meshery Client Version: v0.5.23
- Platform: Docker 
- Docker version: 20.10.2

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Abhishek-kumar09 how does your recent PR address this (or does it not)?

**Comment by Abhishek-kumar09** [comment]
It's a permission denied error.
Looks like there is some OS specific problem with movement of permission to user.
@Shreyas220 
Had you tried
 `sudo  mesheryctl system start --yes -p docker` 
 or if you want to deploy with k8s  `sudo  mesheryctl system start --yes -p kubernetes` 
My recent PR doesn't adress the permission related problems.

**Comment by Shreyas220** [comment]
update: had a conversation with Hussaina  mesheryctl is installed , 
used this `curl -L https://git.io/meshery -o meshery; export PLATFORM=docker; sudo bash meshery -`
the permission issue with yaml file is resolved with “sudo” as Lee and Hussaina  suggested 



now when i run `sudo mesheryctl system start --yes -p docker` or ` sudo mesheryctl system start --yes -p kubernetes`
i get 
![image](https://user-images.githubusercontent.com/55346934/122039446-54999e00-cdf4-11eb-93be-4cefe5dab8f2.png)
![image](https://user-images.githubusercontent.com/55346934/122039526-654a1400-cdf4-11eb-9ab6-57de1367d2ff.png)




i have a minikube cluster running and it shows that meshery is already deployed 
![image](https://user-images.githubusercontent.com/55346934/122039686-8ca0e100-cdf4-11eb-9d42-6b4f2783d40a.png)

**Comment by Abhishek-kumar09** [comment]
I had the same problem. It was fixed with fresh installation of minikube and kubectl. Maybe updating those could help.
