### ISSUE TITLE
[Docs] Contributor: Convention and examples for creating errors

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3206]
#### Current State

Instructions and examples of how to use the errors.newI() of MeshKit are needed.

#### Desired State

The [contributing docs](https://docs.meshery.io/project/contributing) on docs.meshery.io should have this information.

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@mgfeller or @kumarabd, will one of the two of you initiate this? This request (to provide succinct contributor instructions) is related to, but separate from #3208, which is the need to document the errorsutils utility itself.

**Comment by Maxgit3** [comment]
If need be.  I can help.
