### ISSUE TITLE
[Chore] Relocate errorutils files from root directory

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3207]
#### Current Behavior
Four new errorutils files have landed in the root directory of the Meshery repo (e.g. https://github.com/layer5io/meshery/blob/master/errorutil_errors_export.json, https://github.com/layer5io/meshery/blob/master/component_info.json).

#### Desired Behavior
Ideally, these files are located in a separate folder, like "helpers".

#### Implementation
Move the errorutils files into a directory (e.g. "helpers/errorutils/")

**Comment by leecalcote** [comment]
@mgfeller, assuming you're in agreement with this request, is this something that you might address?

**Comment by mgfeller** [comment]
@leecalcote I'm in agreement, and yes, I might. 
(also, I need a better way to filter out notifications that mention me... getting lost in all those emails...)

**Comment by mgfeller** [comment]
@leecalcote I think the best solution is to add a command line parameter `--output-dir` (could have a default value you suggested), also because there might be several components in one repository (meshery server and mesheryctl for example), corresponding to different root directories.

**Comment by mgfeller** [comment]
Probably least confusing to have `.` as default value.

**Comment by mgfeller** [comment]
Actually, I think `component_info.json` should be in the root directory of the component. It is not intended to be errorutils specific, but also to provide the component info to the component-info endpoints, to make sure that type and name are uniform.

I just add another command line flag that points to this file.

Also, there may be multiple components in the same repository, like this one here: Meshery server, and `mesheryctl`.

// @leecalcote

**Comment by mgfeller** [comment]
Error utils changes implemented here https://github.com/meshery/meshkit/issues/62

**Comment by mgfeller** [comment]
Default value of the new directory command line parameters that makes most sense is the same as rootDir, imho.

**Comment by DelusionalOptimist** [comment]
> Actually, I think component_info.json should be in the root directory of the component. It is not intended to be errorutils specific, but also to provide the component info to the component-info endpoints, to make sure that type and name are uniform.

oof my bad...
I completely missed this. For all the repos they've been moved away from the root dir. What now? :sweat_smile:

**Comment by mgfeller** [comment]
> > Actually, I think component_info.json should be in the root directory of the component. It is not intended to be errorutils specific, but also to provide the component info to the component-info endpoints, to make sure that type and name are uniform.
> 
> oof my bad...
> I completely missed this. For all the repos they've been moved away from the root dir. What now? 😅

@DelusionalOptimist no worries. I suggest we leave it where it is. It can be picked up from there, if that is how we want to implement it, or be moved later. First, we'd need to have a look at how components (only adapters for now, afaik) pick up type and name now, and how that possibly can be combined with how helpers like `errorutil` (might be several down the line, who knows) do that. Eventaully, there should be a single source of truth for information like that (or, if that is for whatever reason impractical to achieve, a workflow that verifies that multiple sources are in sync).
I guess the most important bit is that we are aware of the component concept with name and type, and use it consistently.

**Comment by mgfeller** [comment]
Actually, I think this issue can be closed. Various paths can be configured in `errorutil`, the CI workflows have been configured, common path `helpers` has been agreed upon, etc.

Agreed @leecalcote ?

**Comment by DelusionalOptimist** [comment]
> @DelusionalOptimist no worries. I suggest we leave it where it is. It can be picked up from there, if that is how we want to implement it, or be moved later. First, we'd need to have a look at how components (only adapters for now, afaik) pick up type and name now, and how that possibly can be combined with how helpers like errorutil (might be several down the line, who knows) do that. Eventaully, there should be a single source of truth for information like that (or, if that is for whatever reason impractical to achieve, a workflow that verifies that multiple sources are in sync).
I guess the most important bit is that we are aware of the component concept with name and type, and use it consistently.

Sounds cool @mgfeller :+1:

**Comment by mgfeller** [comment]
Closing as per earlier comment.
