### ISSUE TITLE
[mesheryctl] Activity Indicator: system start on Kubernetes

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3212]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
```
➜  ~ mesheryctl system start
downloading manifest files from https://github.com/layer5io/meshery/tree/v0.5.23/install/deployment_yamls/k8s
Starting Meshery...
```

Users may sit staring at an inactive terminal for some undetermined amount of time, while Meshery starts on a Kubernetes system. Users deploying Meshery to Docker have status indicators as to provisioning activity, however, K8s users do not.

#### Desired Behavior
An activity spinner can be quickly incorporated into this command to show the user that the system is busy working on their request.

#### Implementation

@navendu-pottekkat has recently used an activity spinner library. This same library could be used here.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by NagaHarshita** [comment]
@navendu-pottekkat Can you specify which library has been used?
@leecalcote Can you please assign this issue to me?

**Comment by navendu-pottekkat** [comment]
@NagaHarshita We actually did not merge the PR with the spinner. I am making a PR on a different issue which will have the spinner. I will ping you today when I make the PR.

**Comment by pottekkat** [comment]
@NagaHarshita FYI- https://github.com/meshery/meshery/pull/3227
