### ISSUE TITLE
[Docs]Add documentation of some features in the contributing docs

### ISSUE THREAD

**Issue by sayantan1413** [meshery/meshery#3222]
#### Current State

In the [contributor guide](https://github.com/layer5io/meshery/blob/master/docs/pages/project/contributing/contributing-docs.md) there is a documentation on the Clipboard feature but some of the features are missing like :
{toc}  - Used for the right-hand sidebar
{% if statement %} {% endif %} - To write a conditional if statement.
{% for condition %} {% endfor %} - To write a loop.
{% comment %} {% endcomment %} - Used for comment purpose.

Likewise I am providing some of the other features which need to be documented are:
{% include file.html %} 
{{ content }}
{% assign %} 

#### Desired State

These missing features should be there in the contributing docs which will help in understanding [meshery docs](https://docs.meshery.io/) better.

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)
- [Jekyll Documentation](https://jekyllrb.com/docs/) [This would be a good resource for this issue]
- [Liquid Documentation](https://shopify.github.io/liquid/) [This would be a good resource for this issue]

**Comment by debjani1413** [comment]
I would like to give it a try!
