### ISSUE TITLE
[mesheryctl] Support tailing logs in Kubernetes platform

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3234]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
mesheryctl users are able to fetch logs from Kubernetes-based deployments using:

```
$ mesheryctl system logs
```
Users are not able to tail logs, however.

#### Desired Behavior

Support following / tailing logs of any Meshery component deployed on Kubernetes.

```
$ mesheryctl system logs meshery -f
```

#### Implementation
Ideally, a `-f`/`--follow` flag would provide support following / tailing logs of any Meshery component deployed on Kubernetes.

#### Acceptance Tests
1. Users can use -f or --follow as a command to stream Meshery component logs to their terminal.
1. Users can use CTRL+C or CMD+C to stop following logs.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by divyanshugit** [comment]
Hi @leecalcote, Can you please assign this to me!! and suggest me some ways that will help me to get started and solve this issue as soon as possible.

**Comment by navendu-pottekkat** [comment]
@divyanshugit Are you working on this issue?

**Comment by divyanshugit** [comment]
@navendu-pottekkat I thought to work on this issue. But I got assigned another one. So, I am working on that

**Comment by muskankhedia** [comment]
@divyanshugit If you are overloaded, will it be fine if I take up this issue?

**Comment by divyanshugit** [comment]
@muskankhedia NP😀. But please explain it to me once you solve this issue!

**Comment by muskankhedia** [comment]
@divyanshugit Sure. Thank you🙂.

**Comment by muskankhedia** [comment]
@navendu-pottekkat I don't think I will be able to take it up anytime sooner. Anyone else willing to work on this, can please take it up.

**Comment by alphaX86** [comment]
@navendu-pottekkat I'd like to give a try

**Comment by leecalcote** [comment]
Please be aware: this issue is a nice-to-have feature, not strictly necessary. Support on its implementation from maintainers will be limited. Implementation will require use of the k8s go client.

**Comment by alphaX86** [comment]
I'll keep in mind 👍

**Comment by navendu-pottekkat** [comment]
@alphaX86 Are you working on this issue?

**Comment by alphaX86** [comment]
@navendu-pottekkat no. I didn't touch this issue. IK this issue needs exploring but due to some issues in front and some with design spec ones I didn't focus on this.

You can assign to someone else

**Comment by navendu-pottekkat** [comment]
Thank you for the update

**Comment by Meyazhagan** [comment]
@navendu-pottekkat @leecalcote Shall I work on this issue!
