### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by Maxgit3** [meshery/meshery#3238]
#### Current State
The Kubernetes documentation on the website doesn't have a section about port forwarding.  Port forwarding helped me with bringing up the UI since I didn't have an external IP and was just relying on localhost.   https://docs.meshery.io/installation/platforms/kubernetes

Also from what I read Kind kubernetes development cluster doesn't have load balance support and needs another application like Metallb to work. https://docs.meshery.io/installation/platforms/kind

#### Desired State
Add documentation about using port forwarding and about Kind's lack of load balance capability.
---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by adithyaakrishna** [comment]
@Maxgit3 Are there any docs regarding this, if so could you please share them here for reference? 👀

**Comment by Maxgit3** [comment]
@adithyaakrishna  I have some website references 
https://kind.sigs.k8s.io/docs/user/loadbalancer/
https://medium.com/pixelpoint/kubernetes-port-forwarding-simple-like-never-before-20a8ab16370f
