### ISSUE TITLE
[mesheryctl] Deploying Meshery on Docker requires Kubernetes

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3251]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

When deploying Meshery in Docker, the current pre-req check checks if Kubernetes is available and only proceeds to start Meshery if it is available.

This is so because even for Docker platform, mesheryctl will deploy the operator manifests to the cluster.

#### Desired Behavior

For platform Docker, Kubernetes should not be a necessary pre-req and the pre-req check could show that as a warning.

Then, if Kubernetes is not available, mesheryctl should skip deploying the operator manifests altogether.

Thus this will make Docker deployments independent of Kubernetes.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by piyushsingariya** [comment]
I'll include this in the PR with system check!

**Comment by navendu-pottekkat** [comment]
@piyushsingariya Also, consider for `system stop` in Meshery, if they do not have a Kubernetes cluster, do not try to delete the Kubernetes deployments, just stop Docker containers.
