### ISSUE TITLE
[UI] Feedback mechanism should be enhanced for custom addons

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3269]
#### Current Behavior
When a user thinks that he needs to have an addon and turns the `switch` on, and suddenly, he realises that he doesn't require it, he tries to turn off the `switch`. In this scenario, the only notification that is being shown is that of the operation being executed(twice)

#### Desired Behavior
There should be a clear feedback to the user that his input has been registered, he should not have to go out of Meshery to verify that his actions has been performed.

#### Visuals

https://user-images.githubusercontent.com/75248557/123375169-f2842a00-d5a5-11eb-8e5f-7604cc449af9.mov

#### Implementation
Some of the solutions to this problem can be, 

1. Keep the `switch` disabled while an operation is being executed
2. Show a notification that the operation he intended to abort has been aborted successfully

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by jeantiston** [comment]
Hi @sudo-NithishKarthik. Can I try working on this if no one else is already doing it?

**Comment by sudo-NithishKarthik** [comment]
Yes @jeantiston . Sure thing 😃 . Let me assign you

**Comment by jeantiston** [comment]
Thanks @sudo-NithishKarthik! :) I just a few questions regarding this:
- How/where can I see the list processes you showed in the vid?
- Do I need to install anything to be able to use the Addons (e.g. Grafana) ?

**Comment by sudo-NithishKarthik** [comment]
No @jeantiston , you don't have to worry about that. What you can do is, you can set the states of the `switch` based on the notifications that meshery receives, 

for eg. When you have switched on graffana for the first time,  you receive a notification that says 'operation executing' right, in that state, we can keep the switch disabled, and when we receive a notification for success or failure of that operation, we can re-enable that switch. does that make sense ? 

You have anything to add @leecalcote ?

**Comment by jeantiston** [comment]
@sudo-NithishKarthik yeah, that makes sense. I just thought I might need to test the 'success' case cause right now when I try turning on an add on it always fail.

I just want to confirm if I'm getting the states right, so it goes:
User clicks switch -> switch is still OFF and gets disabled -> operation executes -> success, switch turn ON and gets enabled
User clicks switch -> switch is still OFF and gets disabled -> operation executes -> failed, switch remains OFF and gets enabled

Is that how you see it happening?

**Comment by sudo-NithishKarthik** [comment]
Yes @jeantiston , you are absolutely right 👍🏽  For testing the success case, you will have to set up Istio, or you can just alter things in the frontend to simulate the success case and test it out 😉 . + if you have better suggestions for this, you are most welcome to share ✌🏽

**Comment by jeantiston** [comment]
Hello! Sorry I got busy and I only got back to this now. So I was trying out some solutions but I can't seem to make it work and I feel stuck.

So at first, the state that controls the switch is being changed immediately when the switch is clicked and then it submits the operation after the state is changed. So clearly it should be the other way around.
https://github.com/meshery/meshery/blob/master/ui/components/MesheryAdapterPlayComponent.js#L1027

I tried to look at how the operation is submitted (submitOp) and how I can detect if it succeeds or fails. Inside submitOp it does a dataFetch to "api/mesh/ops" and I think that is where I need to detect if it succeeds or fails.
https://github.com/meshery/meshery/blob/master/ui/components/MesheryAdapterPlayComponent.js#L407

The dataFetch takes a successFn and an errorFn but I can't seem to rely on that cause from what I'm seeing when I tried it, errorFn can be called before successFn. So if I made the switch state false in errorFn, successFn can still run and turn on the switch. 
https://github.com/meshery/meshery/blob/master/ui/lib/data-fetch.js#L27

Also, submitOps is being used elsewhere in the component so I don't think I can easily change it to set the state that controls the add ons switch. 

So I'm kinda stuck. If anyone has any suggestion on other solutions I can try? Or if you can tag someone who might have a suggestion? Feel free to do so.

**Comment by sudo-NithishKarthik** [comment]
Thank you very much @jeantiston 😄 . We will address this issue after bringing in Redux.
If you want to lean more about our messaging system spec - [Design Spec](https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit#heading=h.ebnhxa18sj7n)
