### ISSUE TITLE
[UI] Delete should be available for only those that can be deleted

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3270]
#### Current Behavior
User is now able to perform delete operation on things that are not deployed in the first place. Look at the video for clarity.

#### Desired Behavior
User should be able to delete only those things that are already running/created. 

#### Visual

https://user-images.githubusercontent.com/75248557/123377160-40e6f800-d5a9-11eb-99ec-bba74713e92d.mov

**NOTE:** This is a fresh cluster without Istio or any app.
#### Implementation
<img width="1440" alt="Screenshot 2021-06-25 at 11 26 34 AM" src="https://user-images.githubusercontent.com/75248557/123376636-7212f880-d5a8-11eb-8175-5a5b9397b427.png">

The same can be done for all the other cards.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by DantrazTrev** [comment]
Seems like an Icon mixup . I would like to try if someone else isn't already working on it

**Comment by adithyaakrishna** [comment]
@DantrazTrev This issue isn't being worked on by anyone else I think, would you like to take this up? 🚀

**Comment by DantrazTrev** [comment]
Hei @adithyaakrishna , I would like to take this one up. 
Also maybe a design change for the delete button . The card menu seems a bit unintuitive . What do you say ?

Ill take it up after i finish the rest of my issues .If no one is working at that time.

In mean while I'll add a proposal for the different UX for the delete button if that's ok ?

**Comment by adithyaakrishna** [comment]
@DantrazTrev Let's do one thing, even though it not exactly relatable to tomorrow's websites call, could you present your ideas regarding this?
Also I would suggest you to have a couple of examples for your idea 👀 

// @leecalcote

**Comment by leecalcote** [comment]
Sounds teal good, @adithyaakrishna, @DantrazTrev. Mockups are most helpful and can be done in the Meshery UI designfile in Figma.

**Comment by DantrazTrev** [comment]
@adithyaakrishna I'll try to update about the designs and changes to the UX today . I might not be able to present it in tomorrows meeting . I'll add the proposal on slack #meshery-ui if that's good ?

**Comment by adithyaakrishna** [comment]
Yess, absolutely 💯

**Comment by leecalcote** [comment]
Thanks for raising this issue, @sudo-NithishKarthik, in general, we need to shift to showing existing resources (things discovered by MeshSync) and showing those resources and their state through a GraphQL subscription.

Users can then take action on a resource under management or choose to provision something new. To get moving quickly, we can write a simple resolver or use an existing one (see @dhruv0000 @kumarabd if more information is needed)  and list all existing service mesh components and related workloads in a table similar to that of the control plane widget on the Dashboard page.

The sample workloads can now be listed in the Applications screen, @Chadha93
