### ISSUE TITLE
[Nighthawk] Handle `0` query testing

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery#3273]
#### Current Behavior
When the value of `Query` in the test page is set to `0`, nighthawk load test fails due to the fact that qps is set to `0`.

#### Desired Behavior
The load test should start with indefinite traffic when the `Query` parameter is set to `0`.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by bariqhibat** [comment]
Hey @kumarabd, I'm interested to handle this, but I don't know what is Nighthawk and where to ask. Could you guide me how to start the Nighthawk and replicate this behavior?

**Comment by leecalcote** [comment]
@DelusionalOptimist, an item to put on the list.
