### ISSUE TITLE
[Nighthawk] Test fails for public endpoints

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery#3274]
#### Description
The Nighthawk Load test does not run until the desired time specified for public endpoints. It does not throw an error but rather it gives a `null` response.

#### Environment:
- Meshery Version: latest
- Kubernetes Version: any
- Host OS: Mac
- Browser: chrome

---

**Contributor Resources:**
- [Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by leecalcote** [comment]
@anirudhjain75 help wanted
