### ISSUE TITLE
[CI] Notification to "update mesheryctl Command Tracker spreadsheet" if PRs and Issues are tagged with "component/mesheryctl" 

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3287]
#### Current Behavior

Pull Requests and Issues related to mesheryctl are tagged with the "component/mesheryctl" label.

The [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0) spreadsheet tracks the progress of the mesheryctl commands and contributors are sometimes unaware of updating it.

#### Desired Behavior

An automated action that comments on the PR and Issue tagging the user to update the [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0) spreadsheet.

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by muskankhedia** [comment]
@navendu-pottekkat I would like to take up this.

**Comment by navendu-pottekkat** [comment]
Sure @muskankhedia

**Comment by navendu-pottekkat** [comment]
@muskankhedia Any updates on this issue?

**Comment by muskankhedia** [comment]
@navendu-pottekkat Yes, I am working on it.

**Comment by alphaX86** [comment]
@navendu-pottekkat if suppose this issue is open, can I take up this?

**Comment by navendu-pottekkat** [comment]
@muskankhedia if you are working on anything else, @alphaX86 can take it up.

**Comment by muskankhedia** [comment]
@alphaX86 I am on it. Can you please take up some other issues?

**Comment by alphaX86** [comment]
@muskankhedia just checking on activity actually, don't worry I won't take it 😂. Oh and here's a tip, for this issue, you need to look the file named `label-commenter-config.yml` and make the changes

**Comment by alphaX86** [comment]
@navendu-pottekkat since this issue is open for long time, I will fix this

**Comment by muskankhedia** [comment]
@alphaX86 I am already looking into this issue. Can you please take up some other issues?

**Comment by alphaX86** [comment]
(Sigh) alright but make sure it's being fixed

**Comment by muskankhedia** [comment]
Your PR seems good. I was looking for an option to automate the task to update in the spreadsheet but yes informing contributors also works.

**Comment by alphaX86** [comment]
Oh ok I thought it's this way... If it's such the case, then this issue is all yours then to work on 👍

**Comment by muskankhedia** [comment]
It's completely fine. I guess I over estimated the issue.
