### ISSUE TITLE
Update Netlify to reflect "meshery" repo change

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3295]
#### Current Behavior

"layer5io/meshery" will be migrated to "meshery/meshery" as a part of being added to the CNCF sandbox.

This could break the Netlify builds.

#### Desired Behavior

Ensure that Netlify is configured so that we can make this change and still have it working.

**Comment by Nikhil-Ladha** [comment]
Only adding the new repo to Netlify will make things work.

**Comment by leecalcote** [comment]
@nehaLohia27 fyi

**Comment by Nikhil-Ladha** [comment]
Changes to Netlify are done to use this repo for previews.

**Comment by Nikhil-Ladha** [comment]
Closing this issue as the Netlify updates are done.
