### ISSUE TITLE
[Chore] Update filter, pattern, and oam handlers to use new Meshkit Errors

### ISSUE THREAD

**Issue by dhruv0000** [meshery/meshery#3303]
Note: This is a child issue of #3275 
#### Current Behavior
Meshery Server (and its other components, like Adapters) use a centralized library, MeshKit, to provide uniform utilities (e.g. raising and logging errors). Currently, Meshery Server uses a now antiquated style of error logging with logrus.

#### Desired Behavior
Ideally, all use of logrus is replaced with use of MeshKit-style error logging.

#### Implementation
Meshery Handlers needs to be:
 - Updated to use meshkit errors. 
 - Switch to handler Log instead of `logrus`

Handlers to update:

- [ ] meshery filter handler
- [ ]  meshery pattern handler
- [x]  oam handler

For reference, you can checkout  the [`grafana handler`](https://github.com/layer5io/meshery/blob/master/handlers/grafana_handlers.go) and [`prometheus handler`](https://github.com/layer5io/meshery/blob/master/handlers/prometheus_handlers.go) or the [docs](https://docs.meshery.io/project/contributing-error).
Define all Error functions for all the handlers to be written in the `handlers/error.go` file.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
@vijcheru, feel free to self-assign, if interested.

**Comment by vijcheru** [comment]
Sure, I'm working on it.

**Comment by vijcheru** [comment]
Lee, I've seen the assignment. Will get that done as quickly as I can.

**Comment by sayantan1413** [comment]
Hey @vijcheru are you interested in sharing on of your handler with @kaushambisharma then you can pair up with her.

**Comment by vijcheru** [comment]
Yes, I am interested.

**Comment by kaushambisharma** [comment]
@sayantan1413 happy to update the handlers if the issue still needs fixing.

**Comment by warunicorn19** [comment]
Hey, if no one is working on this, can I work on it?

**Comment by sayantan1413** [comment]
Yes @leecalcote these two handler file need to be updated to meshkit style error. I am making a fix to this today only.
