### ISSUE TITLE
[Chore] Update performance profile, provider, and schedule handlers to use new Meshkit Errors

### ISSUE THREAD

**Issue by dhruv0000** [meshery/meshery#3304]
Note: This is a child issue of #3275 
#### Current Behavior
Meshery Server (and its other components, like Adapters) use a centralized library, MeshKit, to provide uniform utilities (e.g. raising and logging errors). Currently, Meshery Server uses a now antiquated style of error logging with logrus.

#### Desired Behavior
Ideally, all use of logrus is replaced with use of MeshKit-style error logging.

#### Implementation
Meshery Handlers needs to be:
 - Updated to use meshkit errors. 
 - Switch to handler Log instead of `logrus`

Handlers to update:

- [ ] performance profiles handler
- [ ]  provider handler
- [x]  schedule handler

For reference, you can checkout  the [`grafana handler`](https://github.com/layer5io/meshery/blob/master/handlers/grafana_handlers.go) and [`prometheus handler`](https://github.com/layer5io/meshery/blob/master/handlers/prometheus_handlers.go) or the [docs](https://docs.meshery.io/project/contributing-error).
Define all Error functions for all the handlers to be written in the `handlers/error.go` file.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
@samirparhi-dev, feel free to self-assign, if interested.

**Comment by samirparhi-dev** [comment]
@leecalcote : Unfortunately, I am not a member of meshery Org yet. So not able to self-assign. Kindly assign it to me :-)

**Comment by Shreyas220** [comment]
Hey, @samirparhi-dev, I would like to pair up and work on the issue with you, any free tasks?

**Comment by samirparhi-dev** [comment]
> Hey, @samirparhi-dev, I would like to pair up and work on the issue with you, any free tasks?
> 
> 

Hey , I was bit occupied. So did not do much . Yes you are welcome to pairup

**Comment by Shreyas220** [comment]
Thank you @samirparhi-dev 
@leecalcote can you assign to me as well.

**Comment by samirparhi-dev** [comment]
Go ahead, now all yours
