### ISSUE TITLE
[Chore] Update server spec, session sync handlers to use new Meshkit Errors

### ISSUE THREAD

**Issue by dhruv0000** [meshery/meshery#3305]
Note: This is a child issue of #3275 
#### Current Behavior
Meshery Server (and its other components, like Adapters) use a centralized library, MeshKit, to provide uniform utilities (e.g. raising and logging errors). Currently, Meshery Server uses a now antiquated style of error logging with logrus.

#### Desired Behavior
Ideally, all use of logrus is replaced with use of MeshKit-style error logging.

#### Implementation
Meshery Handlers needs to be:
 - Updated to use meshkit errors. 
 - Switch to handler Log instead of `logrus`

Handlers to update:

- [ ] server spec handler
- [ ]  session sync handler

For reference, you can checkout  the [`grafana handler`](https://github.com/layer5io/meshery/blob/master/handlers/grafana_handlers.go) and [`prometheus handler`](https://github.com/layer5io/meshery/blob/master/handlers/prometheus_handlers.go) or the [docs](https://docs.meshery.io/project/contributing-error).
Define all Error functions for all the handlers to be written in the `handlers/error.go` file.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Chadha93** [comment]
Is this a `good first issue for  **Gophers**, if Yes, I would like to try this **I'm new to go**

**Comment by leecalcote** [comment]
![547-5473804_golang-gopher-clipart](https://user-images.githubusercontent.com/7570704/124023770-f7851700-d9b3-11eb-9afc-3e9a4b8335fe.png)

**Comment by dhruv0000** [comment]
May the Gopher be with you, @Chadha93. :zap:

**Comment by sayantan1413** [comment]
Hey @Chadha93 are you interested in sharing one of your handler with @chetak123 .

**Comment by Chadha93** [comment]
> Hey @Chadha93 are you interested in sharing one of your handler with @chetak123 then you can pair up with him.

Sure @sayantan1413

**Comment by chetak123** [comment]
Thanks @Chadha93 I would love to collaborate with you on this issue.

**Comment by Chadha93** [comment]
> Thanks @Chadha93 I would love to collaborate with you on this issue.

@chetak123  You can ping me on Slack will have a discussion on this.
