### ISSUE TITLE
[UI] Patterns: Action Enhancements

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3307]
#### Current Behavior
Users need the ability to deploy patterns from the Patterns table.

#### Desired Behavior
Users should see a Deploy button in each row of the table.

#### Implementation

In the table:
1. Add "Deploy" button (use Play icon or Lighting Bolt icon) to invoke the Pattern "deploy" endpoint.
1. Change "..." elipse icon to Pencil icon
1. Update name of column from "Details" to "Actions"

In the patternfile modal:
1. Change icon for Update Patterns action to a Save (disk) icon

#### Acceptance Tests

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Chadha93** [comment]
@leecalcote You can assign me here.
