### ISSUE TITLE
[CI] Move codecov.yml into .github directory

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3337]
**Description**
As a project, we are in need of minimizing the number of files in the root directory of Meshery.

The [codecov.yml](https://github.com/meshery/meshery/blob/master/codecov.yml) file is in need of being relocated.

---

According to this:
https://docs.codecov.com/docs/codecov-yaml#can-i-name-the-file-codecovyml

> Can I name the file .codecov.yml?
> Yes. However, the file must still be located in the root, dev/, or .github/ directories

So, it is possible to move it into `.github/` directory.

_Originally posted by @ramrodo in https://github.com/meshery/meshery/discussions/3210#discussioncomment-874626_

**Comment by suhaniii** [comment]
@ramrodo  Can I give it a try?

**Comment by ramrodo** [comment]
@suhaniii Sure! I just re-assigned this issue to you. Thanks! :)
