### ISSUE TITLE
[CI] Deploy Preview Failure

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3344]
#### Description
See https://github.com/meshery/meshery/actions/runs/990658287 for details.

#### Screenshots/Logs
<img width="946" alt="Screen Shot 2021-07-01 at 10 43 03 AM" src="https://user-images.githubusercontent.com/7570704/124152496-34efb000-da59-11eb-9cc8-22343be5dd05.png">

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by leecalcote** [comment]
@nehaLohia27 would you like to investigate?

// @Nikhil-Ladha

**Comment by nehaLohia27** [comment]
@leecalcote  Sure will take this up.

**Comment by Nikhil-Ladha** [comment]
I have opened PR #3338 for this which addresses a part of it and mentioned what else needs to be done, @leecalcote

**Comment by Nikhil-Ladha** [comment]
Fixed in #3338
