### ISSUE TITLE
[CI]Create a new label with called  issue/invite

### ISSUE THREAD

**Issue by Anita-ihuman** [meshery/meshery#3359]
#### Current Behavior
There is no label that  automatically sends out Invite to the Github Org

#### Desired Behavior
An action for the label `issue/invite` should be created to help us automatically send out Invite to the Github Org.

#### Screenshot of the issue
![Screenshot 2021-07-01 at 23 21 33](https://user-images.githubusercontent.com/62384659/124196120-ab28fc80-dac3-11eb-99da-b64f04cae1ee.png)

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by leecalcote** [comment]
Given the permission need to create a label, I went ahead and created the `issue/invite` label on the `meshery` repo: https://github.com/meshery/meshery/labels/issue%2Finvite

**Comment by leecalcote** [comment]
I also went ahead and created an `issue/remind` on the `meshery` repo as well.

**Comment by Anita-ihuman** [comment]
Thank you 😊.
Will go ahead and close this then.
