### ISSUE TITLE
[CI] Relocate netlify script to /docs directory

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3360]
@nehaLohia27 can we have this file https://github.com/meshery/meshery/blob/master/script.sh moved to the /docs directory? // @Nikhil-Ladha

_Originally posted by @leecalcote in https://github.com/meshery/meshery/discussions/3210#discussioncomment-944626_

**Comment by leecalcote** [comment]
Hi @nehaLohia27, will you consider taking assignment of this issue? // @Nikhil-Ladha

**Comment by nehaLohia27** [comment]
@leecalcote Can you give me write access to review PRs?

**Comment by nehaLohia27** [comment]
@includestdlibrary Thanks for the PR.

**Comment by Nikhil-Ladha** [comment]
> @leecalcote Can you give me write access to review PRs? PR #3365 is still open . I approved the changes also.

Write access is limited to Maintainers only :)

**Comment by nehaLohia27** [comment]
okay :)
