### ISSUE TITLE
[CI] Mesheryctl client version not being set in stable releases

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3391]
#### Description
Undoubtedly, related to the recent move of GitHub orgs and updates to goreleaser, the `mesheryctl` builds seem to no longer be including release tag and version information in there builds.

#### Screenshots/Logs
```
➜  ~ mesheryctl version
A new release of mesheryctl is available: Not Set → v0.5.31
https://github.com/layer5io/meshery/releases/tag/v0.5.31
Check https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli for instructions on how to update mesheryctl

      	VERSION	GITSHA
Client	Not Set	Not Set
Server	v0.5.31	258e3eb3

Checking for latest version of Meshery...

  Unable to check for latest version of Meshery.
```

** Release Workflow Logs**

<img width="1909" alt="Screen Shot 2021-07-05 at 2 56 25 PM" src="https://user-images.githubusercontent.com/7570704/124513797-372b7480-dda1-11eb-9160-0528416c10a9.png">

See https://github.com/meshery/meshery/runs/2992575154?check_suite_focus=true#step:4:25

#### Environment:
- Meshery Version: v0.5.31
---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by leecalcote** [comment]
@ramrodo fyi, an item to tee up for the CI Meeting, assuming it isn’t already addressed by then.

**Comment by nehaLohia27** [comment]
@Nikhil-Ladha I can take this up. can you please assign this to me

**Comment by Nikhil-Ladha** [comment]
Sure! @nehaLohia27 .

**Comment by nehaLohia27** [comment]
@leecalcote Can you help what needs to be done here ?

**Comment by nehaLohia27** [comment]
@leecalcote I think this issue is been addressed under this issue #3253 . can you verify

**Comment by nehaLohia27** [comment]
@leecalcote @navendu-pottekkat @Nikhil-Ladha We can close this issue as this issue is already fixed under issue #3253

**Comment by leecalcote** [comment]
I could be mistaken, but I don’t believe that it has been fixed.

I do consider that this issue is a duplicate filing of the same issue described in #3391, though.

**Comment by nehaLohia27** [comment]
@piyushsingariya Can you help to confirm is this issue is been fixed or not ?

**Comment by piyushsingariya** [comment]
@nehaLohia27 Yes, This has been covered by me under #3253

**Comment by leecalcote** [comment]
Specifics, @piyushsingariya?

**Comment by piyushsingariya** [comment]
@leecalcote https://github.com/meshery/meshery/pull/3253/files#r666384162

**Comment by leecalcote** [comment]
After the v0.5.34 release, this bug still persists.
