### ISSUE TITLE
[UI] Filters: Action Enhancements

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#3393]
#### Current Behavior
No current ability to deploy, bulk/individual delete filters from the Filter UI

#### Desired Behavior
Users need the ability to deploy, bulk/individual delete filters from the Filter UI from each row of the table

#### Implementation
1. Add the "Deploy" button (use the Play icon or Lighting Bolt icon) to invoke the Pattern "deploy" endpoint.
2. Change "..." elipse icon to Pencil icon
3. Update the name of the column from "Details" to "Actions"
4. Bulk/individual delete filters options from the UI (checkboxes)
Reference: https://docs.google.com/document/d/1gFVMlJtOjCaBbwnpB7KyfnQGoRGWtM-oZrpVd9oYSAQ/edit#heading=h.blih70a9hxp
---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Chadha93** [comment]
@leecalcote  Could you please add the relevant labels and assign me. 😊

**Comment by adithyaakrishna** [comment]
My bad @Chadha93 Assigned Myself by mistake. I Have assigned it to you now 🎉

**Comment by leecalcote** [comment]
@Chadha93 if we don't have the same functionality for Patterns, will you add these to Patterns as well?

**Comment by Chadha93** [comment]
> @Chadha93 if we don't have the same functionality for Patterns, will you add these to Patterns as well?

@leecalcote We do have this functionality in patterns, I have already added(merged) and demoed on meshery  call : )
