### ISSUE TITLE
[mesheryctl] [ci] `mesheryctl version` does not show the latest version available

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3399]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl version` does not show the latest available version after we moved the repo to a new org.

![Screenshot_20210707_003714](https://user-images.githubusercontent.com/49474499/124654317-0db33b80-debc-11eb-8369-ffffa9e8de33.png)

#### Desired Behavior

`mesheryctl version` should display the current and the latest available versions of mesheryctl.

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sayantan1413** [comment]
Hey @navendu-pottekkat can I give it a try?

**Comment by piyushsingariya** [comment]
I have fixed this in system check PR #3253

**Comment by sayantan1413** [comment]
Yeah @piyushsingariya I checked it. 😀
