### ISSUE TITLE
[CI] Add support for Apple Silicon/ M1/ARM64 in goreleaser

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3400]
#### Current Behavior

Builds for the new Apple M1 chips are not being made and released.

#### Desired Behavior

goreleaser now supports building for Apple M1 chips. We should also build and release for that architecture.

**Initially verify whether this support already exists right now.**

#### Implementation

Update https://github.com/meshery/meshery/blob/master/.goreleaser.yml

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by warunicorn19** [comment]
hey, should i take a look into this issue?

**Comment by debjani1413** [comment]
@warunicorn19 yes sure, should I assign it to you???

**Comment by warunicorn19** [comment]
yeah go ahead

**Comment by leecalcote** [comment]
I gorelaser only produces Darwin arm64 under golang 1.16

**Comment by warunicorn19** [comment]
yeah, so what would i have to change in the yml file?

**Comment by leecalcote** [comment]
I'll let you research that, @warunicorn19

**Comment by warunicorn19** [comment]
Closing this as the issue has already been solved
