### ISSUE TITLE
[mesheryctl] (child) `mesheryctl system` unit testing

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#3407]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

check Epic here #3016 

#### Current Behavior
Currently, we don't have any unit tests setup to test `mesheryctl system` commands and functions

#### Desired Behavior
Required to enable unit testing support for `mesheryctl system` commands and functions, to ensure the accuracy and robustness of each mesheryctl release.

**mesheryctl Unit Testing**
- Mark all possible situations for each `mesheryctl system` commands and functions.
- Write tests using Golang’s standard library.
- A combination of CodeCov and GitHub Actions are to be used as mainstays in the approach to unit testing - https://github.com/codecov/codecov-action.

#### Subcommands to cover

- [x] mesheryctl system start
- [x] mesheryctl system stop
- [x] mesheryctl system context
- [x] mesheryctl system channel
- [x] mesheryctl system token
- [x] mesheryctl system logs
- [x] mesheryctl system reset
- [x] mesheryctl system restart
- [x] mesheryctl system status
- [x] mesheryctl system update
- [x] mesheryctl system config

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by piyushsingariya** [comment]
This issue can be split-up further for sub-commands under `mesheryctl system` subcommands and can be picked up by multiple devs for each file/command.

**Comment by chetak123** [comment]
Hey @piyushsingariya can I take unit-test for system reset and restart please ?

**Comment by sayantan1413** [comment]
Hey @piyushsingariya can I take the system start one?

**Comment by piyushsingariya** [comment]
Yeah sure @chetak123, go ahead!
@sayantan1413 `start` and `stop` have been already covered.

**Comment by Revolyssup** [comment]
@piyushsingariya  You can assign me for system token and system context.

**Comment by piyushsingariya** [comment]
I have raised a PR for `mesheryctl system status`

**Comment by piyushsingariya** [comment]
@sayantan1413 @chetak123 any updates?

**Comment by chetak123** [comment]
Actually @piyushsingariya can I get some more time in it as my sem. exams are starting and I am little busy right now😅

**Comment by Shreyas220** [comment]
@piyushsingariya can i take mesheryctl system update

**Comment by piyushsingariya** [comment]
@Shreyas220 `update` is being handled by @sayantan1413. I think you can give a try to `restart` maybe.

**Comment by Shreyas220** [comment]
okay @piyushsingariya 
but I think @chetak123 was assigned restart, can I take this from you chetak?

**Comment by chetak123** [comment]
Yeah sure 🙌 , guess I have to only work on `system reset` then.

**Comment by Shreyas220** [comment]
> Yeah sure 🙌 , guess I have to only work on `system reset` then.

thank you  😊

**Comment by piyushsingariya** [comment]
@Shreyas220 @chetak123 any update?

**Comment by sayantan1413** [comment]
Hey @piyushsingariya can you please update which all commands are completed ?

**Comment by piyushsingariya** [comment]
Updated!

**Comment by sayantan1413** [comment]
Thanks @piyushsingariya 😃

**Comment by Shreyas220** [comment]
> @Shreyas220 @chetak123 any update?

got held up with some things, will make a PR soon

**Comment by chetak123** [comment]
> @Shreyas220 @chetak123 any update?

I was caught up with my exams and I am pretty new to golang 😅, will be making a pr soon.
