### ISSUE TITLE
[CI] checking on unnecessary workflow runs

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#3413]
#### Current Behavior

Some workflow runs are getting triggered when they actually should not. This is waste of CI resources.
#### Desired Behavior

They should be triggered according to the changes introduced.
#### Implementation

Analyze those workflows and update them to trigger on appropriate conditions.
#### References
https://github.com/meshery/meshery/pull/3296: Only updates a github workflow but still triggers all sorts of build checks and tests.

Comment more references as found

**Comment by DelusionalOptimist** [comment]
Take a look at the GraphQL workflow where we trigger the particular job only when the schema changes. See https://github.com/meshery/meshery/blob/988b8b6636de42c6f237e397c6c38f274a466c8e/.github/workflows/ci.yml#L271-L277

**Comment by warunicorn19** [comment]
@DelusionalOptimist is this good to close?
