### ISSUE TITLE
[Docs] Mobile view too wide

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3414]
#### Current State
Meshery Docs viewed on a mobile phone does not properly fit the screen. 

#### Screenshot

![FA7A87F7-BBCC-4867-A7BD-8F802C870DDC](https://user-images.githubusercontent.com/7570704/124998886-c7bcbb80-e012-11eb-9858-f7c5949f4539.png)

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
hey, should i work on this?

**Comment by sayantan1413** [comment]
Yeah sure @warunicorn19 go ahead.
