### ISSUE TITLE
perf: Delete the `apt-get` lists after installing something

### ISSUE THREAD

**Issue by iamrajiv** [meshery/meshery#3427]
## Description

Cleaning up the apt-cache and removing `/var/lib/apt/lists` helps keep the image size down. Since the `RUN` statement starts with `apt-get update`, the package cache will always be refreshed before `apt-get install`.

#### References:

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by iamrajiv** [comment]
@leecalcote I want to work on this.

**Comment by leecalcote** [comment]
@iamrajiv excellent. Thank you for filing this issue. 👍 I'm curious to know how much of an impact this improvement has on the image size. Do you know? The Meshery Docker image size is too large today.

**Comment by leecalcote** [comment]
@iamrajiv, where'd you go?! 😉
