### ISSUE TITLE
[CI] Skipping workflow runs on forks

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#3429]
_Originally raised by @samirparhi-dev in https://discuss.layer5.io/t/github-wf-issue-during-pull-request/125_
#### Current Behavior

When a contributor pushes to their fork, many workflows which should ideally run only on https://github.com/meshery/meshery also get triggered. They need some secrets to complete successfully but we don't provide secrets to our forks because it may have bad consequences. Thus the runs end up failing on forks which is annoying.

#### Desired Behavior

Recognize such workflows and add conditions to trigger them only when a commit is created in https://github.com/meshery/meshery.

#### Implementation

Example workflow https://github.com/meshery/meshery/blob/master/.github/workflows/build-and-release-edge.yml
Change the job
```yaml
    name: Docker build and push
    env:
```
to
```yaml
    name: Docker build and push
    if: github.repository == 'meshery/meshery'
    env:
```

**Comment by iamsdas** [comment]
I'd like to take up this issue

**Comment by sayantan1413** [comment]
Hey @iamsdas go ahead.🚀

**Comment by Nikhil-Ladha** [comment]
Much needed update. We need this in many of the workflows, the netlify preview workflow also needs to be updated.
