### ISSUE TITLE
[mesheryctl] Fix `IsMesheryRunning()` for locally running meshery

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#3434]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Currently many commands fail to execute because the function fails to detect if meshery is running locally or not.

#### Desired Behavior

It should detect, ofcourse!
Send a GET request to http://localhost:9081/api/version ? If the response is 200 then it is running and reachable or else it is not. and that means Meshery is might be running local

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
@piyushsingariya may I look on it? :)

**Comment by chetak123** [comment]
Hey @piyushsingariya I am new to golang and mesheryctl, can I collaborate on this issue please ?

**Comment by piyushsingariya** [comment]
Sure, you both could collaborate with each other. @alphaX86 @chetak123  !

**Comment by Revolyssup** [comment]
@piyushsingariya  http://localhost:9081/api/version is not the correct endpoint.
The correct endpoint is  http://localhost:9081/api/server/version.

**Comment by Revolyssup** [comment]
@chetak123  , @alphaX86 , Are you guys stilll working on it? 
It was just 10 lines of code and issue was pending for two days so I solved it, if you guys haven't worked on it, just tell me I will create the PR.

**Comment by chetak123** [comment]
Yeah sure @Revolyssup , actually I was having some difficulty in running the system locally, if you have solved the issue then go ahead!

**Comment by alphaX86** [comment]
Hey @Revolyssup I was held up with some other work.... So if you wish to fix it you can 👍 I'll look on some other issue in meantime

**Comment by alphaX86** [comment]
@piyushsingariya just a doubt, the GET request must be added as a new method and not remove existing ones right? Just add that request check and no refactor?

**Comment by alphaX86** [comment]
If so, can I just look and Simultaneously work on it separately? I'll look and get to you on Slack if any doubts arise

**Comment by piyushsingariya** [comment]
yes, With the current scenario we're able to catch meshery running on the platforms but we aren't able to grab meshery which is running with the source code so it will be an additional check which would check if we are running meshery from the source code.

**Comment by alphaX86** [comment]
Ok, I'm a bit clear now, will try to fix it
