### ISSUE TITLE
[Docs] Meshery release docs needs some update

### ISSUE THREAD

**Issue by alphaX86** [meshery/meshery#3435]
#### Current State
For now some release versions are not present in the doc site

#### Desired State
The doc must be updated with relevant release pages

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by adithyaakrishna** [comment]
@alphaX86 🎉
