### ISSUE TITLE
[CI] UI Build test fails to give proper feedback

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3438]
#### Current Behavior
while `UI Build test`, when it runs `make build-ui`, it attempts to build ‘meshery-ui’ and ‘provider-ui’. If ‘meshery-ui’ fails building and ‘provider-ui’ is successful, it considers the process to be successfully completed.

#### Desired Behavior
Current behaviour is deceiving. It should either run both of those as separate tests or it should break when an error occurs anywhere in the middle.

#### Screenshots
<img width="1440" alt="Screenshot 2021-07-09 at 12 30 47 PM" src="https://user-images.githubusercontent.com/75248557/125161019-7db41100-e19d-11eb-87dd-a1fe8c04fc94.png">

#### Acceptance Tests
`UI Build Test` should give proper feedback on completion of the test.

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by leecalcote** [comment]
While contributors enjoy a single, consolidated command, for purposes of CI, the suggested desired behavior makes sense to me. 👍

**Comment by iamsdas** [comment]
Can I take up this issue?
I am thinking of having a `build-meshery-ui` and `build-provider-ui` instead of (or along with) the  `build-ui` in the Makefile and then updating the github actions for them.

**Comment by sudo-NithishKarthik** [comment]
Sure @iamsdas , that sounds good, don't remove the existing `build-ui` since people are accustomed to it, you can add those other commands and use them in ci 👍🏽
