### ISSUE TITLE
[mesheryctl] Check for invalid platforms on system start

### ISSUE THREAD

**Issue by metonymic-smokey** [meshery/meshery#3444]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Currently specifying an invalid platform using the `-p` flag throws an error that the platform is an invalid after updating the platform in the `meshconfig`.  

#### Desired Behavior
If a platform other than docker or kubernetes is specified, it should throw an error message and not update the `meshconfig`

#### Screenshots/Logs
![image](https://user-images.githubusercontent.com/48997495/125170905-f41d3700-e1ce-11eb-8cc5-868dd3fbf726.png)

#### Environment

- Host OS: Mac Linux Windows

#### Implementation
Adding a check in `start.go` when updating the platform.  

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by chetak123** [comment]
Can I take this issue please ?

**Comment by nehaLohia27** [comment]
@chetak123  can i work with u on this issue ?

**Comment by chetak123** [comment]
Yeah sure 🙌
