### ISSUE TITLE
[UI] Enhancement in the Applications

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#3447]
#### Current Behavior
Currently, in Application UI, there is no apply button

#### Desired Behavior
An application button needs to be implemented

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Chadha93** [comment]
@navendu-pottekkat please do edit the issue if required and could you please guide where specifically we need the apply button -  in each row (associated in data) does it will possess some functionality for now? Please also share some more resources on the application.

**Comment by navendu-pottekkat** [comment]
@Chadha93 Yes, the apply function should work now. The endpoint `/deploy` has been added to the Meshery server. The apply button could be same as the patterns one IMO.

**Comment by Chadha93** [comment]
@navendu-pottekkat Thanks
