### ISSUE TITLE
[mesheryctl] Improperly handled unavailability of Meshery Server

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3462]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Improperly handled error. Error code 255 is displayed when Meshery Server is not running (when Docker is not running on a Docker-based deployment).

#### Desired Behavior
User should be informed that Meshery Server is not reachable. Display the current context's endpoint to the user.

#### Screenshots/Logs
```
➜  ~ mesheryctl system status
A new release of mesheryctl is available: Not Set → v0.5.36
https://github.com/layer5io/meshery/releases/tag/v0.5.36
Check https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli for instructions on how to update mesheryctl

Error: exit status 255
Usage:
  mesheryctl system status [flags]

Flags:
  -h, --help   help for status

Global Flags:
      --config string    config file (default location is: /Users/lee/.meshery/config.yaml) (default "/Users/lee/.meshery/config.yaml")
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

#### Environment

- Host OS: Mac
- Meshery Client Version: stable-v0.5.36
- Platform: Docker 

----

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by AnshMishra2001** [comment]
Can I work on this issue?

**Comment by navendu-pottekkat** [comment]
Sure @AnshMishra2001

**Comment by warunicorn19** [comment]
@AnshMishra2001 any updates on this?

**Comment by warunicorn19** [comment]
@navendu-pottekkat has this already been fixed?

**Comment by navendu-pottekkat** [comment]
@warunicorn19 I am not entirely sure, could you try replicating the issue as mentioned in the description?

**Comment by warunicorn19** [comment]
@navendu-pottekkat I have tried but not being to replicate this🤔.

**Comment by warunicorn19** [comment]
@leecalcote does this still persist?

**Comment by SirZeck** [comment]
@warunicorn19 this issue seems inactive for quite long, we should remove the assignee so that other contributors feel free to ask to work on this?

**Comment by warunicorn19** [comment]
@SirZeck we're still not sure if this issue persists or has it been solved.

**Comment by SirZeck** [comment]
oh! I just pointed it out.

**Comment by navendu-pottekkat** [comment]
@SirZeck You could try replicating this if you could. I haven't been able to do it.

**Comment by SirZeck** [comment]
> @SirZeck You could try replicating this if you could. I haven't been able to do it.

Okay, I'll work on it.

**Comment by warunicorn19** [comment]
@SirZeck just head's up, I think this issue doesn't persist because I have checked it twice, but I still might be wrong, so you're more than welcome to have a look.

**Comment by SirZeck** [comment]
> @SirZeck just a head's up, I think this issue doesn't persist because I have checked it twice, but I still might be wrong, so you're more than welcome to have a look. 

Um, there's no more exit status 255?

**Comment by navendu-pottekkat** [comment]
Let's keep this open for a while. I have marked it as invalid in any case.

**Comment by warunicorn19** [comment]
Sounds good @navendu-pottekkat

**Comment by leecalcote** [comment]
@navendu-pottekkat, not good that the stale bot closed this months ago and it was not explicitly addressed.
