### ISSUE TITLE
Meshkit Error migration for models package

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery#3468]
#### Current Behavior
Meshery Server (and its other components, like Adapters) use a centralized library, MeshKit, to provide uniform utilities (e.g. raising and logging errors). Currently, Meshery Server uses a now antiquated style of error logging with logrus.

#### Desired Behavior
Ideally, all use of logrus is replaced with use of MeshKit-style error logging.

#### Implementation
- Updated to use Meshkit errors.
- Switch to handler Log instead of logrus.

Files to update:
  - [x] #3469
  - [x] #3470
  - [x] #3471
  - [x] #3472
  - [x] #3473
  - [x] #3474
  - [x] #3475
  - [x] #3476
  - [x] #3477
  - [x] #3478
  - [x] #3479
  - [x] #3480
  - [x] #3481
  - [x] #3482
  - [x] #3483
  - [x] #3484
  - [x] #3485
  - [x] #3486
  - [x] #3487
  - [x] #3488

Ref: https://docs.meshery.io/project/contributing-error
---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by kumarabd** [comment]
@sayantan1413 @debjani1413 @vijcheru More help needed around the meshkit errors.

**Comment by Shreyas220** [comment]
ill start with the first one then 
bitcask_smiresults_persister.go

**Comment by kumarabd** [comment]
Sounds great @Shreyas220

**Comment by sayantan1413** [comment]
As there are a lot of Files to be solved so I think we can update only the respective files and the error.go and after all the files are done then we can work on the `JSON` files. And for the error codes we can use a placeholder string like `replace_me`. I think in this way we can reduce the conflicting files. So what's your view on this @kumarabd ?

**Comment by kumarabd** [comment]
> As there are a lot of Files to be solved so I think we can update only the respective files and the error.go and after all the files are done then we can work on the `JSON` files. And for the error codes we can use a placeholder string like `replace_me`. I think in this way we can reduce the conflicting files. So what's your view on this @kumarabd ?

That sounds perfect @sayantan1413

**Comment by sayantan1413** [comment]
Hey @kumarabd I got a doubt like in the handlers we were using h.log.error(..) but how do we log the errors in the models?

**Comment by Shreyas220** [comment]
> Hey @kumarabd @dhruv0000 @DelusionalOptimist I got a doubt like in the handlers we were using h.log.error(..) but how do we log the errors in the models?

@sayantan1413 we can define `log     logger.Handler`  in `HandlerConfig` struct in `handlers.go`
or just define it in any file 

and to use it we can do 

```
func (h *HandlerConfig) functionname{
        h.log.Error(ErrName())
}

```

**Comment by Shreyas220** [comment]
> Hey @kumarabd @dhruv0000 @DelusionalOptimist I got a doubt like in the handlers we were using h.log.error(..) but how do we log the errors in the models?

@sayantan1413 we can define `log logger.Handler` in `HandlerConfig` struct in `handlers.go`
or just define it in any file

and to use it we can do
```

func (h *HandlerConfig) functionname{
        h.log.Error(ErrName())
}

```

Mr Gfeller has made it easier for us as he define a interface for logger in meshkit  
for reference -> [here](https://github.com/layer5io/meshkit/blob/master/logger/logger.go)

not 100% this is the right way// @DelusionalOptimist  @kumarabd

**Comment by kumarabd** [comment]
> Hey @kumarabd @dhruv0000 @DelusionalOptimist I got a doubt like in the handlers we were using h.log.error(..) but how do we log the errors in the models?

we do not log in models. the idea is to send back errors to the handler in case of errors.

**Comment by vijcheru** [comment]
Sure, I will work on it.

**Comment by sayantan1413** [comment]
I think this issue is solved now so I am closing it for now.
