### ISSUE TITLE
meshery_results_persister.go

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery#3481]

**Comment by myhiccupsandglitches** [comment]
Hi! Can I take work on this ?

**Comment by debjani1413** [comment]
@myhiccupsandglitches hey, sure let me assign it to you 😊

**Comment by warunicorn19** [comment]
hey @myhiccupsandglitches, if you need help with this hit me up on slack

**Comment by dhruv0000** [comment]
@myhiccupsandglitches This issue and #3468  had become Priority and resolved in a recent PR (This happens in a rare case) 

Feel free to look into other issues which might interest you. If you feel like you can't find any issue that excites you, ping me in slack, we will find something which you might enjoy tackling.
