### ISSUE TITLE
[mesheryctl] (child) `mesheryctl pattern` unit testing

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#3492]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

check Epic here #3016 

#### Current Behavior
Currently, we don't have any unit tests setup to test `mesheryctl pattern` commands and functions

#### Desired Behavior
Required to enable unit testing support for `mesheryctl pattern` commands and functions, to ensure the accuracy and robustness of each mesheryctl release.

**mesheryctl Unit Testing**
- Mark all possible situations for each `mesheryctl pattern` commands and functions.
- Write tests using Golang’s standard library.
- A combination of CodeCov and GitHub Actions are to be used as mainstays in the approach to unit testing - https://github.com/codecov/codecov-action.

#### Subcommands to cover

- [ ] mesheryctl pattern apply
- [x] mesheryctl pattern list
- [ ] mesheryctl pattern delete
- [x] mesheryctl pattern view

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by nitinosiris** [comment]
I would like to take this issue!

**Comment by piyushsingariya** [comment]
Cool, @nitinosiris Let's start with `pattern view` and `pattern list` first.

**Comment by nitinosiris** [comment]
> Cool, @nitinosiris Let's start with `pattern view` and `pattern list` first.

could you provide some refrences where such test are implemented for another command ?

**Comment by piyushsingariya** [comment]
check `perf view` and `perf list` tests.

**Comment by piyushsingariya** [comment]
Hey @nitinosiris Here is a small guide which might help you in the way: [here](https://docs.google.com/document/d/1t8Ilb72gpvkLXjywSAkaUOxN6arObC_xOLih66ggCUk/edit#)

**Comment by nitinosiris** [comment]
> check `perf view` and `perf list` tests.

How to run new test ? I mean which command, I made new test file. dont know how to run it :(

**Comment by nitinosiris** [comment]
@piyushsingariya If this issue is priority, you can assign it to someone else, As I am new to golang, and hence I will take time to make PR

**Comment by bariqhibat** [comment]
Hi @piyushsingariya , I am also new to Golang (though I've watched Nic Jackson's videos), but I'm interested to learn them here to apply the knowledge!

**Comment by piyushsingariya** [comment]
Sure, @bariqhibat. Thanks for stepping up. Here is a small guide which might help you in the way: (https://docs.google.com/document/d/1t8Ilb72gpvkLXjywSAkaUOxN6arObC_xOLih66ggCUk/edit#)

Just mention in thread, what command you're exactly going to pick.
