### ISSUE TITLE
[mesheryctl] Add `mesheryctl app` sub-command to manage Meshery Applications

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3510]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Meshery has a new construct called "applications" which lets users define their applications/workloads in pattern files and use Meshery to store, and onboard these applications.

#### Desired Behavior

`mesheryctl` should also support these operations through a new `app` sub-command.

The following sub-commands should be added:

`app onboard` similar to `pattern apply`
`app offboard` similar to `pattern delete`
`app view` similar to `pattern view`
`app list` similar to `pattern list`

The current implementation of `pattern` sub-command can be copied and used here making the necessary changes. 

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by navendu-pottekkat** [comment]
@leecalcote Please check if the verbs used are okay.

**Comment by Jordan-Rob** [comment]
@navendu-pottekkat can I take this on

**Comment by suhaniii** [comment]
@navendu-pottekkat  How pattern and app different here?

**Comment by navendu-pottekkat** [comment]
In the implementation side, they are the same in mesheryctl. You will do the same operations. Only the endpoint to call in the Meshery server will change, that is pretty straightforward.

**Comment by suhaniii** [comment]
Okay. Then Can I give it a try?

**Comment by navendu-pottekkat** [comment]
Yes sure, I will assign this to you.

**Comment by suhaniii** [comment]
There is already 'application' under internal/cli/root, is it different from 'app' we will be creating?

**Comment by suhaniii** [comment]
There is already 'application' under 'internal/cli/root'. How it is different from 'app' we will be creating
