### ISSUE TITLE
[mesheryctl]: make command fails

### ISSUE THREAD

**Issue by nitinosiris** [meshery/meshery#3513]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

make command is giving error 
`go build -ldflags="-w -s -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.version=v0.5.37 -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.commitsha=0d75f9fd5f2fbb16f3b9133a135a663264106cb6 -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.releasechannel="edge"" -o mesheryctl cmd/mesheryctl/main.go
go: github.com/prologic/bitcask@v0.3.9: reading github.com/prologic/bitcask/go.mod at revision v0.3.9: unknown revision v0.3.9
make: *** [Makefile:8: make] Error 1`
Thanks **Muskan Khedia** for pointing out.

#### Desired Behavior

Make command should run without any error
#### Screenshots/Logs

![err](https://user-images.githubusercontent.com/55487443/125789880-5bb08d48-2fef-4540-ad6e-6967da429be3.png)

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker or Kubernetes

#### Mockups

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
@nitinosiris edit the issue title so that it's understandable :)
