### ISSUE TITLE
[mesheryctl] Design a command to update `mesheryctl`

### ISSUE THREAD

**Issue by alphaX86** [meshery/meshery#3517]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

So far, `mesheryctl system update` is used to update Meshery itself (Docker/k8s) but not the `mesheryctl` itself. This makes the user to manually update every time to update the CLI client

#### Desired Behavior

Create a command which will update the `mesheryctl` without the intervention of user to type further commands.

#### Implementation

TBD (will update soon)

#### Mockups

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
Design spec being created... Will let you know if it's done for review

**Comment by piyushsingariya** [comment]
There's already one [here](https://docs.google.com/document/d/1QHDFeFc3QC71YlfIy54g3D8xCrd_-m81veStgOhXeu8/edit)

**Comment by alphaX86** [comment]
Oh ok, will look on it then

**Comment by alphaX86** [comment]
🤦 you could've said it yesterday, by mistake another copy is made

**Comment by alphaX86** [comment]
Alright never mind, I'll ask drive maintainers to remove the duplicate one

**Comment by piyushsingariya** [comment]
I totally forgot. my apologies!

**Comment by alphaX86** [comment]
It's ok. I'll ask Lee to remove the copy

**Comment by alphaX86** [comment]
Hmm... We'd need to see on this too, won't we?

**Comment by piyushsingariya** [comment]
I don't think we need this now tbh, the script command is now too powerful and easy to use. may be in future we think back here again.

**Comment by alphaX86** [comment]
Good to close then?

**Comment by piyushsingariya** [comment]
Yup!
