### ISSUE TITLE
[UI] Change the settings button styling in notification bar

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3536]
**Current Behaviour**

When an adapter ping fails, we receive a notification showing the error and that has a button which takes us to the "Settings" page, but the 'Settings' button is not visually distinctive.

**Desired Behaviour**
Make the settings button feel like a 'button', right now it looks like a plain text

<img width="1440" alt="Screenshot 2021-07-16 at 7 44 36 PM" src="https://user-images.githubusercontent.com/75248557/125978335-34bb0e7b-c54e-402a-b024-4469c1dfebcf.png">

**Note**

Use colors from [Meshery UI colour palette](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=65%3A5)

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by Jordan-Rob** [comment]
can I take this up

**Comment by Anita-ihuman** [comment]
Sure you can.

**Comment by gravishpurohit** [comment]
Hi @sudo-NithishKarthik I want to work on that can I take this

**Comment by sudo-NithishKarthik** [comment]
@gravishpurohit , @Jordan-Rob is working on it, you can look if there are other open issues that you can work with ✌🏽

**Comment by sudo-NithishKarthik** [comment]
Hey @Jordan-Rob , are you facing any blockers ?

**Comment by CipherGirl** [comment]
Hello @sudo-NithishKarthik is this up for grab?

**Comment by sudo-NithishKarthik** [comment]
yup, go ahead @CipherGirl  😄

**Comment by CipherGirl** [comment]
Does this look okay?
![image](https://user-images.githubusercontent.com/37832457/127306070-52316ae1-472b-4c37-a4e4-b76c8c70b989.png)

**Comment by sudo-NithishKarthik** [comment]
Hmm 🤔 , it definitely looks better than before. But i feel that it can be improved. There is something about this which can be improved but i am not able to point at it 😕 .

// @leecalcote  @Nikhil-Ladha

**Comment by sudo-NithishKarthik** [comment]
@CipherGirl ,can you link the pr to this issue ?
