### ISSUE TITLE
[CI] Label commenter workflow failing

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3549]
#### Description
Label commenter workflow fails due to a problem with workflow configuration

#### Expected Behavior
Label commenter workflow should not fail because of an internal error with workflow configuration

#### Screenshots/Logs
<img width="1061" alt="Screenshot 2021-07-17 at 9 01 59 PM" src="https://user-images.githubusercontent.com/75248557/126041962-90d091d2-380b-4236-9482-a28307054a1d.png">
 
#### To Reproduce

1. Create a PR in meshery
2. Add `component/ui` label to it

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by alphaX86** [comment]
@sudo-NithishKarthik it's not the UI label alone, all labels have stopped working because of that indentation. Hopefully that you have solved it'll work now
