### ISSUE TITLE
[mesheryctl] Refactor mesheryctl

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3550]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

This issue is to track the refactoring process in mesheryctl. Multiple PRs related to refactoring mesheryctl will be tagged with this issue.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by umairnsr87** [comment]
@navendu-pottekkat do we have subtasks in this issue?

**Comment by navendu-pottekkat** [comment]
@umairnsr87 not really, I opened this issue to centralise and easily track the refactoring process. There a couple of other open issues that you can jump into if you are interested.

**Comment by umairnsr87** [comment]
Thanks @navendu-pottekkat
