### ISSUE TITLE
[mesheryctl] `system status` errors when platform dependency is missing

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3558]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
mesheryctl presents an error when executing `system status` when the system is missing prerequisite dependencies. The system being used in this scenario does not have Docker installed (does not have `docker` available.

#### Desired Behavior
mesheryctl should detect whether or not prerequisites of the platform are availablle (`docker` cli in this case) and capture this error gracefully, informing the user of the failed preflight check (of the specific missing dependency).

Preflight health check should identify the missing dependency.

#### Screenshots/Logs
```
➜  mesheryctl git:(master) ./mesheryctl system status
Missing Meshery config file.
Create default config now [y/n]? y
Default config file created at /Users/willcalcote/.meshery/config.yaml
Error: exec: "docker-compose": executable file not found in $PATH
Usage:
  mesheryctl system status [flags]

Flags:
  -h, --help   help for status

Global Flags:
      --config string    config file (default location is: /Users/willcalcote/.meshery/config.yaml) (default "/Users/willcalcote/.meshery/config.yaml")
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

#### Environment

- Host OS: Mac M1
- Meshery Client Version: stable-v0.5.37
- Platform: neither

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
I'd like to look on this... May I know what it needs to be done to fix that bug?

**Comment by umairnsr87** [comment]
@leecalcote Can we(@alphaX86 and me) combinely work on this issue ?

**Comment by piyushsingariya** [comment]
> I'd like to look on this... May I know what it needs to be done to fix that bug?

That's where you come into the game. :wink:

**Comment by alphaX86** [comment]
Oooh 😂 OK! We'll try to figure out then
