### ISSUE TITLE
[UI] Fetch grafana and prometheus scan data only if they are configured

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3566]
#### Description
Right now, Meshery UI client attempts to fetch grafana and prometheus data even when the user has not configured them.

For instance, 

<img width="1440" alt="Screenshot 2021-07-19 at 8 23 47 PM" src="https://user-images.githubusercontent.com/75248557/126180411-24f6fa0c-89bd-4c91-b354-94ac62e2563b.png">

^^ In this case, the user has not configured granafa and prometheus, but still, on every load, it attempts to connect to them, which may not be compelling for the user if he consciously retracted himself from configuring them.

<img width="1440" alt="Screenshot 2021-07-19 at 8 27 22 PM" src="https://user-images.githubusercontent.com/75248557/126181008-2629b74b-4b3e-4b4f-82d9-784bab41b695.png">

^^ When the user navigates to the **Settings** page, meshery UI client automatically tries to fetch grafana and prometheus scan data even when they are not configured.

#### Expected Behavior

It would be better if meshery UI client only tries to connect to grafana and prometheus only when the user has configured it and not show the errors that are not reasonable. 

Also, it should only try to fetch the grafana and prometheus scan data only if the user has configured them.

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by sudo-NithishKarthik** [comment]
@leecalcote , please confirm if this the desired behaviour. This is more of a decision to be taken in terms of user experience, because, by doing so, we are shifting the user's understanding from grafana and prometheus being a *default* element to something that is like a *plugin* in the context of meshery. 

So, finally, it will become such that, even if the cluster is configured with grafana and promethues, meshery UI client will try to connect and fetch data from them only if the user has turned the *switch* on. 

Is that it ?

**Comment by adithyaakrishna** [comment]
@manish-ai 👀

**Comment by bariqhibat** [comment]
Hey, I think I know the directions on how to tackle this. Could you assign me to this?

**Comment by sudo-NithishKarthik** [comment]
Reopening as it is not fully resolved..
