### ISSUE TITLE
[Docs] Error Codes Categories not Mobile Friendly

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#3568]
#### Current State
<img src="https://user-images.githubusercontent.com/53532328/126220064-f9c967e9-cc7c-41c7-a9ef-07f7b9fb3149.jpg" style="height:500px"> 

In mobile the categories table is getting cut off.

#### Desired State
The entire table should be visible

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by debo19** [comment]
Can I work on this issue?

**Comment by warunicorn19** [comment]
yeah sure! @debo19

**Comment by sayantan1413** [comment]
Sure @debo19 go ahead.

**Comment by leecalcote** [comment]
@debo19, you're no slo-poke. 

and apparently, neither is @warunicorn19 or @sayantan1413. 😁
