### ISSUE TITLE
[Docs] Open API Documentation for `/filter` endpoints

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#3570]
This is an issue under #2902 

#### Desired State
Add swagger docs for `/filter` endpoints in meshery server.

Guide - https://docs.google.com/document/d/1YnpJs6D_arzuE5ieqMyuJs3A3UYSVp9YZYhbc966sWg/edit?usp=sharing

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by amino19** [comment]
@piyushsingariya: Shall I work on this? :slightly_smiling_face:

**Comment by gravishpurohit** [comment]
@piyushsingariya can I work on this with @amino19.

**Comment by piyushsingariya** [comment]
@gravishpurohit Let's go! and @amino19 does writing Unit Tests interests you?

**Comment by gravishpurohit** [comment]
@piyushsingariya thanks

**Comment by amino19** [comment]
@piyushsingariya : I think you've to guide me, for sure! :slightly_smiling_face:

**Comment by gravishpurohit** [comment]
@piyushsingariya I tried, but I don't have any idea of Jekyll could please help

**Comment by piyushsingariya** [comment]
> @piyushsingariya I tried, but I don't have any idea of Jekyll could please help

It's a wild guess, but you didn't read the guide attached. right?

**Comment by gravishpurohit** [comment]
@piyushsingariya i tried a lot but don't know how to work on swagger.

**Comment by warunicorn19** [comment]
hey @piyushsingariya, if no one is doing this, could i give this a go? I've not worked on swagger before but would like to give it a shot

**Comment by piyushsingariya** [comment]
We have a meeting on this today, be sure to join that.

**Comment by amino19** [comment]
Yes, Obv, I will work with writing Unit Tests.
Seeking for a busy person attention! :slightly_smiling_face:

**Comment by piyushsingariya** [comment]
Hey @sayantan1413 would you like to overtake this issue?

**Comment by sayantan1413** [comment]
Yes @piyushsingariya I am working on it. Sorry somehow I missed to comment on this😓

**Comment by sayantan1413** [comment]
I have completed the Filter endpoint only waiting to create the PR till #3840 gets merged.
