### ISSUE TITLE
[Docs] Open API Docs for `/application/` endpoints

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#3571]
#### Desired State
Add swagger docs for `/application` endpoints in the meshery server.

Guide - https://docs.google.com/document/d/1YnpJs6D_arzuE5ieqMyuJs3A3UYSVp9YZYhbc966sWg/edit?usp=sharing

---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by nitinosiris** [comment]
I would like to work on this :)

**Comment by piyushsingariya** [comment]
@nitinosiris sure!

**Comment by sayantan1413** [comment]
Hey @nitinosiris can I pair up with you to solve this issue if you haven't already solved it completely.

**Comment by nitinosiris** [comment]
> Hey @nitinosiris can I pair up with you to solve this issue if you haven't already solved it completely.

Sure, ;)

**Comment by sayantan1413** [comment]
Hey @nitinosiris how many endpoint have you covered till now so that our work do not coincide.

**Comment by nitinosiris** [comment]
> Hey @nitinosiris how many endpoint have you covered till now so that our work do not coincide.

I haven't started the work yet, I am  currently busy with placement cycle, you can start your work. If I get time, I'll contribute to it

**Comment by warunicorn19** [comment]
Hey @sayantan1413 if @nitinosiris is busy can I team up with you instead?

**Comment by piyushsingariya** [comment]
IG there won't be much issue with that. @warunicorn19

**Comment by warunicorn19** [comment]
@piyushsingariya already started working on it 😅.

**Comment by sayantan1413** [comment]
Yeah @piyushsingariya all of them are covered here.

**Comment by warunicorn19** [comment]
yes all covered @piyushsingariya

**Comment by piyushsingariya** [comment]
Damn, I didn't even realise that. thanks guys @warunicorn19 @sayantan1413 :heart:
