### ISSUE TITLE
[UI] Settings: Change label on settings buttons

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3573]
#### Current Behavior
The Settings page (/settings) of Meshery UI, has a couple of buttons with labels not accurately representing their behavior.

#### Desired Behavior
The buttons should have more accurate descriptions of their functionality.

#### Implementation
1. On the http://localhost:9081/settings#performance page, change the text on the button from "Submit Preferences" to "Save".
1. On the http://localhost:9081/settings#service-mesh page, change the text on the button from "Submit" to "Connect".

#### Screenshot

Example:

<img width="1006" alt="Screen Shot 2021-07-20 at 12 32 27 PM" src="https://user-images.githubusercontent.com/7570704/126369713-de1df7c9-b1e5-495f-92f9-58c3e9cf8247.png">

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by sayantan1413** [comment]
Hey @leecalcote I want to try this good first issue for the front-end part

**Comment by sudo-NithishKarthik** [comment]
Great @sayantan1413 😄  🎉
