### ISSUE TITLE
[UI] Settings: Labels overlapping text in input fields

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3574]
#### Description

Field labels overlap with field input, specifically saved user preference input.

When a user changes the performance load test defaults from the system defaults, the UI will correctly save the user's preference, but will display their preferred settings as overlapping the label of the input field.

#### Expected Behavior
1. Move the field label out of the actual text field and move to a wrapping label (see the Duration field label(
2. User preference values should not overlap the field label.

#### Screenshots/Logs
<img width="955" alt="Screen Shot 2021-07-20 at 12 42 04 PM" src="https://user-images.githubusercontent.com/7570704/126371255-e3256210-723a-4a25-ac48-7e266477bbe4.png">

#### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.5.37

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by ishitakeshawani** [comment]
Can i take up please ? @leecalcote

**Comment by warunicorn19** [comment]
here you go @ishitakeshawani !

**Comment by ishitakeshawani** [comment]
It's already showing expected behavior.
OS : Ubuntu 20.04 
![Screenshot from 2021-07-21 20-58-05](https://user-images.githubusercontent.com/50510726/126516912-f1c570c6-f722-4001-9012-d79bd8875be8.png)

**Comment by warunicorn19** [comment]
Yeah it looks fine on my system too. @leecalcote has this issue already been fixed?

**Comment by sudo-NithishKarthik** [comment]
https://material-ui.com/components/text-fields/#limitations

This is a limitation in using React Material UI. It won't happen all the time.
we can apply the workaround that they suggest to get rid of this.

**Comment by leecalcote** [comment]
While we're in here, will you change "Submit Preferences" to "Save", and include on of these (non-fill) - https://react-icons.github.io/react-icons/search?q=save?

**Comment by sayantan1413** [comment]
Hey @leecalcote I think I have fixed this "Submit Preferences" to "Save" in this #3573

**Comment by sudo-NithishKarthik** [comment]
Yes @sayantan1413 is right, it is fixed 🚀

**Comment by sudo-NithishKarthik** [comment]
But we would still have to add the icon though

**Comment by warunicorn19** [comment]
Should I add the icon?

**Comment by sayantan1413** [comment]
Hey @warunicorn19 would you mind if I try that I am a bit newbie in frondend developement.

**Comment by warunicorn19** [comment]
😬already started to do it, but okay go ahead @sayantan1413

**Comment by sayantan1413** [comment]
Thanks a lot @warunicorn19 I will try it for a day if I fail it you can surely make the PR😅

**Comment by warunicorn19** [comment]
Sure, no problem 😂
