### ISSUE TITLE
[Server] MeshSync Lifecycle: Ad-hoc connectivity test

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3576]
**Current Behavior**
Once Meshery Operator, and subsequently, MeshSync is deployed, users will inevitably be in need of verifying connectivity to MeshSync in Settings and Connection Wizard.

Like other Meshery-connected components, users need the ability to verify connectivity to that component.

**Desired Behavior**
In the same fashion that users are allowed to perform ad-hoc connectivity tests to the Kubernetes and service mesh chips, users should be allowed to perform ad-hoc connectivity tests to verify Meshery's point-in-time ability to interact with MeshSync (therein retrieving MeshSync component details: version, health).

**Acceptance Criteria**
This enhancement is complete when:
- [x] Users are able to invoke an ad-hoc connectivity test with MeshSync.
- [ ] Connectivity test retrieves MeshSync version for display in a tooltip when the user hovers the mouse over the chip.
- [ ] Connectivity tests display either a success message: "MeshSync successfully pinged!" or a failure message: "Could not connect to MeshSync."

---

**Future**
- [ ] Users should be able to invoke an ad-hoc connectivity test with *each* connected MeshSync instance.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by kumarabd** [comment]
Unassigning and not closing this as frontend work is to be moved forward.

**Comment by Meghana-12** [comment]
Hi, I'd like to work on this.

**Comment by Meghana-12** [comment]
Hi, is this the chip you're talking about?
<img width="157" alt="Screenshot 2021-07-30 at 2 42 59 PM" src="https://user-images.githubusercontent.com/44519203/127630808-147f80cc-c7c5-4034-8699-0eeb52bfab23.png">

**Comment by Meghana-12** [comment]
Hi, should I add a chip for `MeshSync` here or add `tool-tip` for the operator `chip` in settings?
