### ISSUE TITLE
[Docs] Create a configurable {% include %} for "Suggested Reading" in Contributing.md

### ISSUE THREAD

**Issue by debjani1413** [meshery/meshery#3599]
#### Current State
We're in need of a configurable {% include %} created for a "Suggested Reading" snippet that allows the suggested reading topic to be configured. See the Contributing pages for examples.

#### Desired State
This {% include %} could then be added to a layout.
---

#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by bariqhibat** [comment]
Hi I can help check this out!

**Comment by debjani1413** [comment]
@bariqhibat would you like me to assign it to you??

**Comment by bariqhibat** [comment]
Sure @debjani1413

**Comment by bariqhibat** [comment]
Hi @debjani1413, what do you mean by configurable though? How exactly configurable is it? If I see from the code, it is iterating from the pages folder's files.

```javascript
{% assign sorted_reading = site.pages | sort: page.title | reverse %}

<ul>
  {% for item in sorted_reading %}
  {% if item.type=="project" and item.category=="contributing" and item.list!="exclude" -%}
    <li><a href="{{ site.baseurl }}{{ item.url }}">{{ item.title }}</a>
    </li>
    {% endif %}
  {% endfor %}
</ul>

```

**Comment by debjani1413** [comment]
@leecalcote

**Comment by debjani1413** [comment]
> Hi @debjani1413, what do you mean by configurable though? How exactly configurable is it? If I see from the code, it is iterating from the pages folder's files.
> 
> ```js
> {% assign sorted_reading = site.pages | sort: page.title | reverse %}
> 
> <ul>
>   {% for item in sorted_reading %}
>   {% if item.type=="project" and item.category=="contributing" and item.list!="exclude" -%}
>     <li><a href="{{ site.baseurl }}{{ item.url }}">{{ item.title }}</a>
>     </li>
>     {% endif %}
>   {% endfor %}
> </ul>
> ```

@leecalcote
