### ISSUE TITLE
Export perf test config and results in service-mesh-benchmark-spec format

### ISSUE THREAD

**Issue by girishranganathan** [meshery/meshery#36]

**Comment by leecalcote** [comment]
Will need to follow the format outlined in 
https://github.com/meshery/service-mesh-benchmark-spec

**Comment by leecalcote** [comment]
Currently, this import/export excludes test results; is restricted to the test, environment, and mesh configurations.

**Comment by leecalcote** [comment]
Feature is being worked on in this branch - https://github.com/meshery/meshery/tree/feature/export-load-test-results

**Comment by leecalcote** [comment]
Completed for single result export.

**Comment by leecalcote** [comment]
@kalradev  @kushthedude it's a good time to expand on the values exported.

**Comment by kushthedude** [comment]
Not stale

**Comment by leecalcote** [comment]
@navendu-pottekkat fixed?

**Comment by navendu-pottekkat** [comment]
This is partially fixed. We still need to pick up some values that are not exposed currently by the API. The results are formatted correctly currently but there are missing values. See PR #2605

**Comment by leecalcote** [comment]
// @bariqhibat

**Comment by leecalcote** [comment]
Completed.
