### ISSUE TITLE
Make the Layer5 a clickable link

### ISSUE THREAD

**Issue by Anita-ihuman** [meshery/meshery#3634]
#### Description
Currently, Layer5 logo in this section is not a clickable link. 

#### Expected Behavior
Add a link to the Layer5 logo directing to the Layer5.io website

#### Screenshots/Logs
![Screenshot 2021-07-23 at 12 00 19](https://user-images.githubusercontent.com/62384659/126809459-3bb3e671-2c00-461f-a140-81de5b9ba09f.png)

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker or Kubernetes

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by shahkushal38** [comment]
Hello @Anita-ihuman, I would like to work on this issue as I myself am a first-timer

**Comment by warunicorn19** [comment]
here you go! @shahkushal38

**Comment by adithyaakrishna** [comment]
Closed as it was fixed in PR #499

**Comment by adithyaakrishna** [comment]
@leecalcote Could you please transfer this issue to `meshery.io` repository? 👀

**Comment by warunicorn19** [comment]
Hey @adithyaakrishna, doesn't an issue get closed automatically after a linked PR is merged?

**Comment by adithyaakrishna** [comment]
Yes, it does but the issue is in one repository and the PR in another 😂
This issue needs to be transferred to `meshery.io` repo

**Comment by warunicorn19** [comment]
😂😂😂😂ohh okay

**Comment by Anita-ihuman** [comment]
Oooppss😅
Sure I will
