### ISSUE TITLE
[mesheryctl] Error in all the mesheryctl commands specific to Apple Silicon M1 chip

### ISSUE THREAD

**Issue by sayantan1413** [meshery/meshery#3637]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

When executing any mesheryctl command there is an error `ERRO[0000] failure getting variant            error="getCPUInfo for OS darwin: not implemented"` at the first line but after that the command performs its desired behaviour. This error is only showing on `Apple Silicon (M1 chip)`.

#### Desired Behavior

There shouldn't be any error in any of the mesheryctl commands.

#### Screenshots/Logs

<img width="571" alt="Screenshot 2021-07-23 at 11 51 32 PM" src="https://user-images.githubusercontent.com/64970095/126824949-4c40ca8d-f6cb-4e23-85b3-6dcfd62cc34a.png">

#### Environment

- Host OS: Mac (Apple Silicon M1 chip)
- Meshery Server Version: v0.5.38
- Meshery Client Version: stable- v0.5.38
- Platform: Docker

#### Mockups

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@sayantan1413 will you be working on this (self-assigning) or is this posted with the intention of others picking it up (to be labeled with "help wanted")?

**Comment by sayantan1413** [comment]
No @leecalcote I want other contributor to pick up this issue and work on it.

**Comment by navendu-pottekkat** [comment]
@sayantan1413 Where you able to investigate what the root cause of the issue is?

**Comment by navendu-pottekkat** [comment]
@sayantan1413 Were you able to find which of our dependencies is causing this issue? If it is a small fix we can try to fix this.

**Comment by navendu-pottekkat** [comment]
@sayantan1413 Could you also confirm this is not an issue anymore?
