### ISSUE TITLE
[Meshery] Notification for multiple clients

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery#3639]
#### Current Behavior
Meshery currently has endpoint `/api/events` which handles the notification messages. Currently they only send messages buffered to the UI.

#### Desired Behavior
We want the desired notifications to be published to all the connected clients (UI/cli etc).  This operates on stream protocol, thus any client that is subscribed to this endpoint should receive the notification. 

Ref: https://github.com/meshery/meshery/blob/master/handlers/events_streamer.go

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by umairnsr87** [comment]
@kumarabd Can I work on this enhancement?
