### ISSUE TITLE
[Meshery] Meshkit errors classification

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery#3640]
#### Current Behavior
Some of the meshkit custom errors defined are not public facing, meaning they are never shown up user facing. There needs to be a proposal to classify private errors (Non user facing) and user facing errors.

#### Proposal
While combining or wrapping two errors, we could account for merging all of the fields in the error object. Thus the final user facing error would be a set of error codes instead of a single error code.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by sayantan1413** [comment]
Hey @kumarabd can you give a little more explanation as what do I exactly need to do ?
