### ISSUE TITLE
[Meshery] Update Meshery Docs Link

### ISSUE THREAD

**Issue by Jashpatel1** [meshery/meshery#3651]
#### Description
The Signin error page of meshery has link to older site of Meshery Docs, i.e. https://meshery.layer5.io/docs/.

#### Expected Behavior
Update the link with current site for Meshery Docs, i.e., https://docs.meshery.io/.

#### Screenshots/Logs
![Screenshot from 2021-07-26 10-12-13](https://user-images.githubusercontent.com/43696490/126934529-0d49e7d0-7499-4224-b1f1-1d8cd39744b1.png)

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by debjani1413** [comment]
@Jashpatel1 I would like to work on this, may I??

**Comment by sayantan1413** [comment]
Yeah sure go ahead @debjani1413 .

**Comment by leecalcote** [comment]
Folks, the fix for this issue lands in Meshery Cloud, a private repo. I'll transfer the issue to that repo now.
