### ISSUE TITLE
mesheryctl instructs users to use `kubectl` to get the status of Meshery deployment

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3660]
#### Description

mesheryctl instructs the user to run `kubectl get pods --namespace="meshery"` to view the status of the pods instead of instructing the user to run `mesheryctl system status`.

```
Starting Meshery...

⡿ Deploying Meshery on Kubernetes

Meshery deployed on Kubernetes.

 

Some Meshery pods have not come up yet.

Please check the status of the pods by executing “kubectl get pods -—namespace=meshery” before using meshery.

Opening Meshery in your browser. If Meshery does not open, please point your browser to http://localhost:31409 to access Meshery.
```

#### Expected Behavior

Users should be instructed to use `mesheryctl system status`.

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by guptapriyanshu7** [comment]
Can I take this @navendu-pottekkat ?

**Comment by leecalcote** [comment]
Let's do this thing, @guptapriyanshu7!

_and by "let's", I mean "you" ;)_
