### ISSUE TITLE
Meshery Server should not attempt K8s communication when invalid/incomplete/non-flattened kubeconfig is passed

### ISSUE THREAD

**Issue by utkarsh-pro** [meshery/meshery#3661]
#### Current Behavior
Currently meshery server detects a kubeconfig and attempts to use that config to communicate with kubernetes. This results into "unhelpful" error messages when the kubeconfig is invalid/incomplete/non-flattened.

#### Desired Behavior
Meshery server should validate the kubeconfig before attempting to communicate with k8s cluster. If the kubeconfig is invalid then the user should be informed about the same and suggest a remediation.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
...specifically noting the requirement to have a minified kubeconfig as one of the suggested remediations: `mesheryctl system config <platform>`

**Comment by SirZeck** [comment]
Should this be closed?

**Comment by leecalcote** [comment]
Thanks for checking. Yes, this has been solved.
