### ISSUE TITLE
[mesheryctl] Investigate cli/browser package as a potential replacement of browser function

### ISSUE THREAD

**Issue by utkarsh-pro** [meshery/meshery#3662]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Meshreryctl currently uses custom function for opening browser which is an additional component to maintain.

#### Desired Behavior
The custom implementation can be replaced with [cli/browser](https://github.com/cli/browser)

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by CYBER-BRIX** [comment]
Hey I am a newbie and I would like to work on this issue could you help me in
 getting started with this issue?

**Comment by navendu-pottekkat** [comment]
Closing this out as it is already fixed here: https://github.com/meshery/meshery/pull/3682

@CYBER-BRIX You can checkout [these](https://github.com/meshery/meshery/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee) issues.
