### ISSUE TITLE
[Docs]Adding configurable {% include %}  to _layout

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#3668]
Description:
 We're in need of a configurable {% include %} created for a "Suggested Reading" snippet that allows the suggested reading topic to be configured. See the Contributing pages for examples.
> 
> This {% include %} could then be added to a layout.

_Originally posted by @leecalcote in https://github.com/meshery/meshery/issues/3587#issuecomment-884519375_

**Comment by debjani1413** [comment]
Hey @warunicorn19 I think this issue has already been created and @bariqhibat has been working on it, here #3599. Correct me if I'm wrong 😐, would you mind asking him out once??

**Comment by warunicorn19** [comment]
Oh right, I guess I completely missed this, thanks @debjani1413, ill ask him.

**Comment by debjani1413** [comment]
@warunicorn19 yeah, sure! I hope you didn't mind, cause if he would have done the work, then both of your works could have been wasted 🙂

**Comment by warunicorn19** [comment]
Of course not, I'll close this issue, because there's already an existing one.

**Comment by warunicorn19** [comment]
@leecalcote closing this issue because it has already been created.
