### ISSUE TITLE
[CI] Golint: specify certain revive lint checks to be ignored

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3670]
This silly lint issue is going to cause our error output to be harder to read. @sayantan1413 do you mind looking into how we might set certain lint checks to be ignored?

_Originally posted by @leecalcote in https://github.com/meshery/meshery/issues/3669#issuecomment-887814899_

**Comment by mgfeller** [comment]
Just copying my comment from the referenced issue to preserve it:

> I think it would be good to have a linter rule / config file template, e.g. in this repo, that can be used in other repos as well (or at least form the basis). That way, we don't have to consider and discuss silly and not-so-silly rules for each repo. I thought the previous set was quite good and appropriate, but as revive should up the config has to be adjusted. Also, as revive has more rules than golint, there might be overlap between revive and other linters in use.
> 
> Similar work is done in meshkit. meshery/meshkit#89
> 
> // @sayantan1413 @leecalcote @iamrajiv

**Comment by sayantan1413** [comment]
Yes @mgfeller I was going through the PR. I will update it soon and will make a PR here.

**Comment by leecalcote** [comment]
@sayantan1413 was this fixed?
