### ISSUE TITLE
Meshery:  `curl -L https://git.io/meshery | bash -` doesn't wait for input

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#3680]
#### Description

When we are installing or updating meshery with command ` curl -L https://git.io/meshery | bash -` the terminal is not waiting for  input but fills it with empty value (because of use of curl command) and fails at the end.
Screenshot below :point_down: 

![image](https://user-images.githubusercontent.com/48255244/127376293-a81074f2-bf56-4b7e-bff2-a7fc160ecef6.png)

#### Expected Behavior

It should prompt me for the platform input. It was also pointed out by @samirparhi-dev in today's meeting, i think.

#### Environment

- Host OS:  Linux 
- Platform: Docker and Kubernetes

---

**Comment by leecalcote** [comment]
Thank you, @Abhishek-kumar09 and @samirparhi-dev
