### ISSUE TITLE
mesheryctl system config panics when a minikube cluster doesn't exist

### ISSUE THREAD

**Issue by Shreyas220** [meshery/meshery#3683]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._
#### Current Behavior
`mesheryctl system config` panics instead of throwing an error when a `minikube` cluster doesn't exist.
#### Desired Behavior

Gracefully handle this and show an error.
#### Screenshots/Logs

```
 $ mesheryctl system config minikube -t ~/Downloads/auth.json
Configuring Meshery to access Minikube...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x19350e9]
goroutine 1 [running]:
github.com/layer5io/meshery/mesheryctl/internal/cli/root/system.glob..func8(0x2ce85a0, 0xc0003bc1b0, 0x1, 0x3)
        /Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/system/config.go:289 +0x389
github.com/spf13/cobra.(*Command).execute(0x2ce85a0, 0xc0003bc180, 0x3, 0x3, 0x2ce85a0, 0xc0003bc180)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2ce2920, 0x200a460, 0x2ec97a0, 0x0)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
        /Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/root.go:77 +0x56
main.main()
        /Users/runner/work/meshery/meshery/mesheryctl/cmd/mesheryctl/main.go:22 +0x25
```
#### Environment
- Host OS: Linux
- Meshery Server Version: edge
- Meshery Client Version: v0.5.41
- Platform: Docker Kubernetes
---
#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by metonymic-smokey** [comment]
@Shreyas220 could you tell me how to reproduce this?
I'm getting a clean error when I try to recreate this locally

**Comment by Shreyas220** [comment]
this occurs when we don't install minikube and try to run this command 
or when you don't create a minikube cluster (with `minikube start`)

**Comment by Shreyas220** [comment]
do you want to work on this issue?

**Comment by hexxdump** [comment]
@Shreyas220, I do not get a panic when minikube is not running. However the error message is not intuitive either.


```
$ minikube status
E0729 23:22:43.554238   18539 status.go:227] status error: host: state: unknown state "minikube": docker container inspect minikube --format={{.State.Status}}: exit status 1
stdout:


stderr:
Error: No such container: minikube
E0729 23:22:43.554848   18539 status.go:230] The "minikube" host does not exist!
minikube
type: Control Plane
host: Nonexistent
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent

$ ./mesheryctl system config minikube -t ~/Downloads/auth.json
A new release of mesheryctl is available: v0.5.40 → v0.5.41
https://github.com/meshery/meshery/releases/tag/v0.5.41
Check https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli for instructions on how to update mesheryctl

Configuring Meshery to access Minikube...
Get "https://127.0.0.1:59881/version?timeout=32s": dial tcp 127.0.0.1:59881: connect: connection refused

```

**Comment by Shreyas220** [comment]
I am so sorry,i have trying for the past 2 days and now even i am not to reproduce, it happened just once  
even so thank you @metonymic-smokey and @hexxdump for looking into it so quickly

**Comment by metonymic-smokey** [comment]
@Shreyas220 It's totally okay to raise issues this way, it's good in fact! This is exactly how we find bugs/edge cases in mesheryctl.
