### ISSUE TITLE
[Feature] Development of Meshery plug-in for Backstage

### ISSUE THREAD

**Issue by samirparhi-dev** [meshery/meshery#3690]
### This is a feature to be developed for Backstage plugin
What is Backstage?
https://backstage.io/docs/overview/what-is-backstage
How to create a plugin?
https://backstage.io/docs/plugins/
#### Desired Behavior

The plug-in should be compatible with Backstage.
#### Implementation

- Development of plugin
- Create PR to add it to Backstage repo
#### Acceptance Tests

- Once the feature is created, @samirparhi-dev will test it
#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
@samirparhi-dev as this stale issue close out, do you have any aspect of this effort to save off should this issue be re-opened in the future?
