### ISSUE TITLE
[CI] Broken org inviter workflow

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3699]
#### Current Behavior
Multiple `if` statements in this workflow have it not functioning: https://github.com/meshery/meshery/blob/5abc6bfbfc26211276a5f5ae261d5771c62ea267/.github/workflows/invitations.yml#L8-L9

#### Desired Behavior
Multiple `if` statements in this workflow need to be combined into a single statement.

https://github.com/meshery/meshery/blob/5abc6bfbfc26211276a5f5ae261d5771c62ea267/.github/workflows/invitations.yml#L8-L9

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)

**Comment by leecalcote** [comment]
@iamsdas would you like to take this one?

**Comment by iamsdas** [comment]
Sure 👍
