### ISSUE TITLE
[DOCS] Copy-to-Clipboard action required on each command section to make it easier for any user

### ISSUE THREAD

**Issue by afzal442** [meshery/meshery#3715]
#### Current Behavior

There is no Copy-to-Clipboard action on each command section of contributing guide. It is very hard to click around each section to copy and paste commands.
#### Desired Behavior

It will be easier for a user to clip any section while following the contributing guide and running through the commands in one click.
#### Implementation

Add Copy-to-Clipboard action on each command section.
#### Mockups

![c3](https://user-images.githubusercontent.com/11625672/127765502-dd0e8020-b9d5-480a-af8a-5c1b553fe4a8.JPG)

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by afzal442** [comment]
hi @warunicorn19, how to integrate that `Copy-to-Clipboard button`  in `.md file` built on top of `jekyll`. Any idea? I found this on google as [here](https://www.aleksandrhovhannisyan.com/blog/how-to-add-a-copy-to-clipboard-button-to-your-jekyll-blog/).

**Comment by warunicorn19** [comment]
@afzal442 yeah this should work, do you want to try?

**Comment by warunicorn19** [comment]
Also going through the document doesn't make it seem like a good first issue, more complicated than I though it is. What is your view on this @afzal442 ?

**Comment by afzal442** [comment]
Yep, exactly what you understood. It doesn't even seem `first-timers` as well. I put up this issue so y'all can suggest some solution. 
> yeah this should work, do you want to try?
I need your suggestions first. where and how to integrate? thanks.

Above, you can see the desired result, I added a screenshot as a use-case by which we might improve each page having instructions content.

**Comment by warunicorn19** [comment]
i think we should wait for @leecalcote to give his suggestion on this because integrating this is going to be a task i think, as there are a lot of code snippets in the docs, and if the copy feature is added it needs to be added to all. Also, if we do implement this we would want it to be similar to the screenshot that you have provided above.

**Comment by afzal442** [comment]
Yes, r8. It would be very helpful if we can achieve it though.

**Comment by warunicorn19** [comment]
I agree

**Comment by leecalcote** [comment]
Do the existing integrated “ Clipboard Feature” work —> https://docs.meshery.io/project/contributing-docs

**Comment by warunicorn19** [comment]
Nope, it doesn't copy the text.

**Comment by warunicorn19** [comment]
i was just playing around a little bit, this is how it looks for now. @leecalcote do we want to implement this?
https://user-images.githubusercontent.com/53532328/127773412-2296c521-2cc6-4c3b-9a7a-597f1d755548.mov

**Comment by leecalcote** [comment]
Yes, we do want a clipboard feature. I swear we already have one in the site somewhere. Do you mind searching the code base for “clipboard” to find it and evaluate use of the existing function?

**Comment by warunicorn19** [comment]
Yes, we use clipboard.js in some places but I couldn't understand the use of it, I'll look into it.

**Comment by afzal442** [comment]
hey Adi, I have found the logic of `clipboardjs` used on which pages. Here it is` https://docs.meshery.io/installation/platforms` for example https://docs.meshery.io/installation/platforms/docker.

**Comment by warunicorn19** [comment]
Yup @afzal442 , I found it too, some commands don't require the copy feature, that's why I have just added the documentation, as to how to add the copy feature if required, thanks!
