### ISSUE TITLE
[Meshery Server] use `localhost` in Makefile for adapter urls

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#3743]
#### Description

On starting meshery server from `make run-fast`,
Currently all the default urls for adapters in Meshery is pointed to `mesherylocal.layer5.io`. I think when we run adapters outside the meshery server and they are available through `localhost` only.  

This was originally suggested by @utkarsh-pro on [discuss page](https://discuss.layer5.io/t/service-mesh-adapters-are-not-found-on-running-meshery-server-locally/151).

The adapter connection is unsuccessful when going with the legacy makefile while trying to adapter ports on `mesherylocal.layer5.io`.

#### Environment

- Host OS: Linux
- Meshery Server Version: latest
- Meshery Client Version: latest
- Platform: Docker

---

**Comment by SirZeck** [comment]
Is this issue open? Can I work on it and can you guide me to where /etc/hosts file is?
