### ISSUE TITLE
Add option to import patterns via a URL

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3746]
Related issues: #3747 #3745

#### Current Behavior

Users are able to upload patterns through the "Patterns" page in the UI from their local storage. But Meshery also supports fetching files via a provided URL.

#### Desired Behavior

The UI should have an option for the user to fetch patterns by providing a URL. The design could be similar to how Google Docs handle importing images.

![Screenshot 2021-08-02 at 8 17 36 PM](https://user-images.githubusercontent.com/49474499/127880352-6556a125-aa93-420c-a4eb-74ad62ff836f.png)

#### Implementation

This consideration should be made consistent across filters, patterns and applications constructs.

[Nice to have] A design of how the UI would look like should be made prior to implementing this design.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
Due by Monday, August 30th.

**Comment by Meghana-12** [comment]
Need more info on the special case (github.com/).

**Comment by navendu-pottekkat** [comment]
@utkarsh-pro Could you provide some context here on importing patterns from GitHub?

**Comment by leecalcote** [comment]
Briefly, import from GitHub as a special treatment is a Meshery Remote Provider use case only, and currently, only one that applies if the user has auth'ed with their GitHub account. The UI flow that is needed here is akin to this:

- user clicks import and is presented with three options:
  - browse... filesystem import
  - url... generic, public, http endpoint
  - github - pick list of the user's orgs and repos to import from

**Comment by leecalcote** [comment]
We can consider that @Meghana-12 delivered as volunteered on this issue and close it out, first copying the contents of the last comment into a new issue, though.

**Comment by navendu-pottekkat** [comment]
Opened the other considerations as a separate issue: https://github.com/meshery/meshery/issues/4157

Closing this one out.
