### ISSUE TITLE
[Filters] Deploy: Display input components for configuring the deployment of a filter

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3749]
#### Current Behavior
Meshery's Filter UI doesn't present the user with enough inputs to truly configure a filter for deployment.

#### Desired Behavior
Display any number of additional input fields in a modal when the "deploy" button is pressed for any given single filter.

#### Implementation
1. Retrieve additional inputs from `/api/oam/workloads` REST API.
1. Use react-json-schema-forms to display input components for configuring the deployment of a filter.
1. Display toaster notification of success or failure to deploy filter.

#### Acceptance Tests
1.  Users can choose to Deploy their freshly configured filter.
2. Upon deployment, a toaster notification of success or failure to deploy filter is displayed to the user.

#### Future
1.  Users can choose to Save their configuration to Pattern.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
@Abhishek-kumar09 progress to report in today's meeting?

**Comment by Abhishek-kumar09** [comment]
Sure.

**Comment by Abhishek-kumar09** [comment]
The issue can be closed, since the initial iteration has been made and the form is active to configure the specs, More features and bugs are tracked here around this issue https://github.com/meshery/meshery/issues/4110
