### ISSUE TITLE
[mesheryctl] bash installer script fails when unzip command is missing on system

### ISSUE THREAD

**Issue by hexxdump** [meshery/meshery#3756]
#### Description
mesheryctl installer script fails when the system does not have unzip command installed.

#### Expected Behavior
Possible solutions:
1. move away from zip file format packaging - either just download mesheryctl command or move to tar package format. [Requires changes to CI/CD pipelines]
2. throw an user friendly error log to "install unzip command and rerun the installer script"

#### Environment

- Host OS: Ubuntu
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker or Kubernetes

---

**Contributor Resources:**
- [Contributing](https://docs.meshery.io/project/contributing)

**Comment by rzmudatr** [comment]
@hexxdump 
Issue still reproduces with version v0.5.43 for Linux...

```
ubuntu@somewhere-1:~$ curl -L https://git.io/meshery | PLATFORM=docker bash -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  6674  100  6674    0     0   5823      0  0:00:01  0:00:01 --:--:--  5823
Missing required utility: 'unzip'. Please install 'unzip' and try again.
```

**Comment by leecalcote** [comment]
@rzmudatr, good feedback. In this case, the goal was to handle the required dependency gracefully, displaying an informational message with instructions to the user. If you're not using `brew` to install (which you can on Linux and MacOS machines), you'll need to ensure that the host you're running the bash installation script on has `unzip` installed beforehand.

In case it helps - [Homebrew instructions](https://docs.meshery.io/installation/mesheryctl#homebrew)

**Comment by hexxdump** [comment]
@rzmudatr, there a plan to move away from meshery.zip file and have mesheryctl binary downloaded as a single file from meshery release page. I shall update you on the progress. In the meantime, pls use brew instructions shared by Lee.
