### ISSUE TITLE
[UI] Display More Info in Performance Results Tables

### ISSUE THREAD

**Issue by utkarsh-pro** [meshery/meshery#3760]
#### Current Behavior
When performance tests is run today, it shows histogram along with other useful information. This information is persisted but is **not** being shown at the moment in the tables.

#### Desired Behavior
Same info that is visible after test run should be visible from the table and grid view.

#### Acceptance Tests
Same info that is visible after test run should be visible from the table and grid view.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by utkarsh-pro** [comment]
@sudo-NithishKarthik want to take on this?

**Comment by sudo-NithishKarthik** [comment]
Sure

**Comment by warunicorn19** [comment]
I think we could close this issue.
