### ISSUE TITLE
[Docs] Minikube: Provide a helpful tip to users about the location of the flattened config file

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3761]
#### Current State
Flattened configuration files.

#### Desired State
Show users a tip on how to replace their kubeconfig with the same location.

---
#### Contributor Resources

- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by afzal442** [comment]
@piyushsingariya location of Flattened configuration files? https://docs.meshery.io/installation/platforms/minikube

**Comment by piyushsingariya** [comment]
This issue (it's just my guess though) ideally is looking for adding instructions on what to do after creating the flattened config file with kubectl.

**Comment by afzal442** [comment]
hey @piyushsingariya could u run this command `kubectl config view --minify --flatten > config_minikube.yaml ` and confirm the below desc?

`kubeconfig refers to a configuration file for meshery to use. Your kubeconfig file found at ~/.meshery/config_minikube.yaml.`

To replace kubeconfig file, has it any relation with `kubectl replace -f FILENAME`?

**Comment by piyushsingariya** [comment]
Nope it doens't have any relation with that command. What we mean to replace or add kubeconfig to Meshery is, Opening Meshery UI, route to Settings and upload the flattened config there.

**Comment by afzal442** [comment]
Yep r8 but dat is already given on docs file i.e. `Upload the generated config file by navigating to Settings > Environment > Out of Cluster Deployment in the Web UI and using the “Upload kubeconfig” option.`

**Comment by piyushsingariya** [comment]
My bad! I misunderstood the issue. @leecalcote enlighten us,

**Comment by afzal442** [comment]
**`config_minikube.yaml` refers to a generated flattened configuration file for meshery to use it for a Minikube cluster.
This file can be found in the `.meshery` folder where the `kubeconfig.yaml` will be written to.**

**You can also replace the `kubeconfig.yaml`  file found in ~/.meshery/kubeconfig.yaml with `config_minikube.yaml` file manually.**

// @leecalcote plz suggest

**Comment by afzal442** [comment]
Any update here plz?

// @leecalcote

**Comment by leecalcote** [comment]
In the time it takes to explain, I'll go ahead make the update. Thanks for looking into this @afzal442. Let me commandeer this issue.
