### ISSUE TITLE
[DOCS] Change broken links in Docs

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#3764]
#### Description
The link in the related reading section of the [Service Mesh Pattern Management](https://docs.meshery.io/functionality/pattern-management) docs is giving a 404 error due to a wrong link
and the 'using helm' link in [Quick start with Kubernetes](https://docs.meshery.io/installation/platforms/kubernetes#using-kubernetes-manifests) doesn't redirect to the 'using helm charts' part of the page.

#### Expected Behavior
The links need to be changed.
Consider using this for the Service Mesh Pattern Management link : https://docs.meshery.io/reference/mesheryctl/pattern

#### Environment

- Host OS: Mac 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker or Kubernetes

---

**Contributor Resources:**
- [Contributing](https://docs.meshery.io/project/contributing)

**Comment by Elmurzy95** [comment]
Help wanted

**Comment by leecalcote** [comment]
Hi @Elmurzy95, would you like to work on this issue?

**Comment by sgibson19** [comment]
I would like to work on this issue

**Comment by leecalcote** [comment]
Sounds great, @sgibson19 👍

**Comment by sgibson19** [comment]
Will work on it soon @leecalcote
