### ISSUE TITLE
[Docs] UX: Create better layout for Error Code Reference

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3765]
#### Current State
The current tabular layout of the [Meshery Error Code Reference](https://docs.meshery.io/reference/error-codes) can be difficult to read. 

#### Desired State
- Design and present a new layout for improved legibility and navigation.
- Present design, and once approved, implement.

---
#### Contributor Resources
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by shubham-tyagi** [comment]
@leecalcote , do I need figma to design it ?
