### ISSUE TITLE
[mesheryctl] `system context switch` to switch Meshery deployments 

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3768]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system context switch` switches the current context passively. The user has to stop Meshery --> switch context --> and restart Meshery to change deployments.

#### Desired Behavior

If meshery is running then `mesheryctl system context switch` will stop Meshery and start Meshery with the switched context internally.

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by metonymic-smokey** [comment]
This was referred to in another issue if I remember correctly.  That was
about channel switch. So maybe you can close that one?

**Comment by metonymic-smokey** [comment]
Invoking `restart` in context switch might be a bit of an issue due to import cycles. So that will have to be considered when designing a solution.

**Comment by piyushsingariya** [comment]
go ahead @suhaniii

**Comment by navendu-pottekkat** [comment]
Yes, if you are tracking the other open issue, we can close this one out.

**Comment by suhaniii** [comment]
> Yes, if you are tracking the other open issue, we can close this one out.

I am not aware about another

**Comment by navendu-pottekkat** [comment]
This is a related and possibly same issue. You can tackle that as well. https://github.com/meshery/meshery/issues/3896
