### ISSUE TITLE
[UI] button to expand the menu is not visible when the menu is minimised

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3769]
#### Current Behavior

The button to expand the menu is not visible when the menu is minimised as shown below.

The users have to scroll to find the button to expand the menu.

![Screenshot 2021-08-04 at 6 18 40 PM](https://user-images.githubusercontent.com/49474499/128183743-a88f081d-4241-4dc9-a4bb-b03d74bd5baf.png)

![Screenshot 2021-08-04 at 6 18 45 PM](https://user-images.githubusercontent.com/49474499/128183761-3ed84a21-831a-4cad-9c2a-9512b587109f.png)

#### Desired Behavior

The button to expand should be visible and users should be able to click it without having to scroll.

#### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Server Version: edge
- Meshery Client Version: edge
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik can I do this issue? Never done anything on meshery UI 😅

**Comment by sudo-NithishKarthik** [comment]
**IMPLEMENTATION:**
Make the _chevron_ fixed at the bottom right corner and increase the z-index

**Comment by warunicorn19** [comment]
alrighty @sudo-NithishKarthik
