### ISSUE TITLE
[meshery server] Installing the Prometheus and grafana from Prometheus community Helm Charts, instead of from istio addon

### ISSUE THREAD

**Issue by samirparhi-dev** [meshery/meshery#3770]
#### Current Behavior

Currently , we are installing prometheus and grafana from Istio add-on which is very limited and is dependent up on the istio.

#### Desired Behavior

We Should be able to install prometheus-grafana stack from  prometheus community helm chart, which has a lots of capability

#### Implementation

Use the kube-prometheus-stack from Community.

Link to prometheus community helm chart in git : https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

Helm Commands:
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install [RELEASE_NAME] prometheus-community/kube-prometheus-stack
```
#### Acceptance Tests
This can be tested once implemented 

---

**Comment by nehaLohia27** [comment]
@samirparhi-dev Can i work on this ?

**Comment by samirparhi-dev** [comment]
@nehaLohia27  : Here you go :-)

**Comment by nehaLohia27** [comment]
@samirparhi-dev @leecalcote need to understand the requirements and also what is current implementation. Is this only about installing prometheus and grafana stack ?

**Comment by samirparhi-dev** [comment]
Will connect over @nehaLohia27

**Comment by SirZeck** [comment]
@nehaLohia27 are still working on this issue?

**Comment by nehaLohia27** [comment]
Yes I am working on  this issue. I will start from next week as on vacation
this week.

**Comment by warunicorn19** [comment]
Sounds good @nehaLohia27.

**Comment by leecalcote** [comment]
Let's consider the Prometheus Operator with Node Exporter configuration an Application to embed (seed) in Meshery Server as out of the box content.

**Comment by nehaLohia27** [comment]
@leecalcote 
do you mean we need to remove prometheus from istio addon and seed into meshery server ? 
how do we seed content in meshery server. in which format ? . can you provide any code/ blogs to start with.. 

so do we need to drop helm chart idea for this ?

**Comment by leecalcote** [comment]
@nehaLohia27, no, the provisioning of Prometheus Operator with Node Exporter will be additive to any Prometheus provisioned as an add-on.

@Revolyssup demo'ed packaging and registering of seed content for wasm filters on today's call (just before this agenda item). There is a design spec "Packaging Seed Content in Meshery" in the community drive.

**Comment by utkarsh-pro** [comment]
@leecalcote I don't think we can represent Prometheus Operator + Node Exporter in an `Application` because `Application` is a construct with a very narrow scope.

Here are the things that we can do:
1. Create new Pattern components of type `Prometheus Operator` and `Node Exporter`. These components will be handled by meshery server.
2. Create a pattern file which handles the deployment of all of the components that will be required by Prometheus Operator and Node Exporter. _This approach is extremely fragile though_.

**Comment by nehaLohia27** [comment]
@leecalcote how to move forward on this . ? can we follow the approach suggested by @utkarsh-pro   ?
