### ISSUE TITLE
[UI] Pattern Deploy provides wrong progress output

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#3774]
#### Current Behavior

Pattern Deploy shows successful network result with status `200`, but UI is providing false errors. like this
![image](https://user-images.githubusercontent.com/48255244/128214836-aa811a4b-aa61-4137-823e-3523b783fe60.png)

The successful deploy can be checked by running: `kubectl get all -n test` or `kubectl get rolouts -n test`.

#### Possible Reason
> What you are seeing is a bug in the UI. `/api/patterns/deploy` returns a text response and not a JSON response but the UI still tries to parse it with `.then(res => res.json())` this parsing is failing.

suggested by  @utkarsh-pro 

#### Desired Behavior

The wrong error output from UI should be fixed, and it should show successful response in UI

#### Environment

- Browser: Firefox
- Host OS: Linux
- Meshery Server Version: stable-5.23
- Meshery Client Version: stable-5.23
- Platform: Docker

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Nice write up, @Abhishek-kumar09. Are you thinking of tackling this one?

**Comment by Abhishek-kumar09** [comment]
Sure, Will do that. Just seen the super power to self assign :smile:
