### ISSUE TITLE
[Docs] API: example of a pattern that was uploaded to Meshery from GitHub?

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3776]
Cool. These are looking good. Do you suppose that we could have an example of a pattern that was uploaded to Meshery from GitHub? // @Chadha93

_Originally posted by @leecalcote in https://github.com/meshery/meshery/pull/3754#r682179436_

**Comment by leecalcote** [comment]
@Chadha93

**Comment by Chadha93** [comment]
@leecalcote You are referencing the patterns which we had on Mehsery, persist in Github ??

**Comment by SirZeck** [comment]
@iamsdas you up on this issue?

**Comment by iamsdas** [comment]
Not really, the adding of examples for the docs didn't really work out in the end and I closed the PR.

**Comment by warunicorn19** [comment]
@iamsdas should we close this issue then?

**Comment by iamsdas** [comment]
I think we should
