### ISSUE TITLE
[mesheryctl] handle errors gracefully when unable to open up a browser

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#3778]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
After running `mesheryctl system start`, if mesheryctl is unable to open up a browser to display Meshery UI, it throws some errors for not being able to find a browser and another deceiving error saying `unable to start meshery` (meshery server does get started).

#### Desired Behavior
These errors should be handled gracefully keeping in mind that the use case of CI workflows. Also, the accurate issue and fix should be pointed out.

#### Screenshots/Logs

```
Opening Meshery (http://localhost:9081) in browser.
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links: not found
/usr/bin/xdg-open: 869: lynx: not found
/usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening 'http://localhost:9081'
Failed to open Meshery in browser, please point your browser to http://localhost:9081 to access Meshery.
Error: failed to start Meshery
See docs.meshery.io/reference/mesheryctl/system for usage details
: exit status 3
Usage:
  mesheryctl system start [flags]

Flags:
  -h, --help              help for start
  -p, --platform string   platform to deploy Meshery to.
      --reset             (optional) reset Meshery's configuration file to default settings.
      --skip-update       (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string    config file (default location is: /home/runner/.meshery/config.yaml) (default "/home/runner/.meshery/config.yaml")
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v0.5.42
- Meshery Client Version: stable-v0.5.42
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
@DelusionalOptimist  the errors from the browser package will be thrown anyhow if it fails to open in browser.
Maybe instead of returning error. We dont return error and just log the warning that `could not open in browser`. That way those extra misleading logs that `could not start meshery` can be avoided.

**Comment by DelusionalOptimist** [comment]
Sure @Revolyssup, this sounds good. :+1:
