### ISSUE TITLE
[mesheryctl] Latest Meshery release checks are too frequent; exceeding GitHub.com API rate limit

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3780]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
When a user runs `mesheryctl system logs`, the GitHub API is invoked to check for the latest version of Meshery. This causes GitHub's API request limit to be reached too quickly.

#### Desired Behavior
mesheryctl should check for the latest release only when `mesheryctl version` or `mesheryctl system start` or `mesheryctl system update` is invoked. This will reduce the number of API calls, avoid rate limiting, while ensuring that checks for the latest version happen on occasion.

#### Screenshots/Logs
```
time="2021-08-05T01:02:25Z" level=error msg="GET https://api.github.com/repos/meshery/meshery/tags: 403 API rate limit exceeded for 24.28.92.140. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 27m45s]" app=meshery code=2138 probable-cause= severity=2 short-description="failed to compare latest and current version of Meshery" suggested-remediation=
```

#### Environment

- Meshery Server Version: stable-v0.5.42

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
May I look on to this and tweak a bit? :)

**Comment by leecalcote** [comment]
Thank you, @alphaX86

**Comment by leecalcote** [comment]
@piyushsingariya is the individual to see about the behavior of these area of `mesheryctl`.

**Comment by alphaX86** [comment]
I got involved in other work till next week and I'm afraid that I can't do this for now... So I'm removing my assignment for now :(

Sorry for inconvenience caused

**Comment by leecalcote** [comment]
Oh, no. There's a prettier project out there. Should Meshery be jealous, @alphaX86?

**Comment by alphaX86** [comment]
@leecalcote 😅😂 no no it's not based on project, till next week Wed I have exams to get rid off, so I may be distracted for few days :( and I'll come back with clean mind 🙂

**Comment by leecalcote** [comment]
Whew! 😅

**Comment by Revolyssup** [comment]
@leecalcote  the function ValidateVersion is being called a lot of times which internally makes that API call. 
Changing other functions's signature which call ValidateVersion to introduce a boolean to allow skipping this call would require a lot of code change in a lot of places.
A better way can be to cache the version's validity in some metadata file in .meshery directory along with time when it was cached. If we are sure that a valid version doesn't get invalid very frequently.
So everytime ValidateVersion function is called,we can check if the time exceeds a given threshold, and if it does then we make that API call.
metadata can be stored in json maybe as
{
<versions>:[{<version>:{
  last-checked-on:<some number>
  status: <valid or invalid>
}
}]
threshold:<some number>
}
Now the reason I proposed something this messy and gross is because I didn't see any other way to make that skip without a whole lot of code change. Your input would be appreciated.

**Comment by leecalcote** [comment]
@Revolyssup alternatively, we can remove the calls to ValidateVersion, leaving them only for `mesheryctl version` and `mesheryctl system start`

**Comment by leecalcote** [comment]
I'm ok with your caching proposal as well. This setting can be added to the existing meshconfig as a global setting.

**Comment by leecalcote** [comment]
@Revolyssup while we're in there, let's have `mesheryctl` silently fail github.com requests, when user is working in an air-gapped environment. mesheryctl should used cached manifests to deploy in those cases.

// @metonymic-smokey @hexxdump

**Comment by Revolyssup** [comment]
> @Revolyssup while we're in there, let's have `mesheryctl` silently fail github.com requests, when user is working in an air-gapped environment. mesheryctl should used cached manifests to deploy in those cases.
> 
> // @metonymic-smokey @hexxdump @piyushsingariya
> 
> **In this scenario, my machine has no Internet connection:**
> 
> ```
> ➜  ~ mesheryctl system start
> Error: failed to start Meshery
> See https://docs.meshery.io/reference/mesheryctl/system for usage details
> : failed to make GET request to https://api.github.com/repos/meshery/meshery/releases/latest: Get "https://api.github.com/repos/meshery/meshery/releases/latest": dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:54373->[::1]:53: read: connection refused
> ```
@leecalcote  should i create an issue for ensuring cached manifests in air gap deployments?

**Comment by leecalcote** [comment]
Immediately, I'm looking for someone to limit the ValidateVersion function calls to the commands suggested in the issue description. Is there a volunteer for proceeding here?
