### ISSUE TITLE
[UI] Notification Center: Success notifications not displaying in correct filter

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3781]
#### Current Behavior
See the recording

https://user-images.githubusercontent.com/7570704/128276081-13d8e504-98ae-4232-92f3-fb9fae605a52.mov

#### Desired Behavior
Success notifications should display under "Success" filter.

#### Environment

- Browser: Safari
- Host OS: Mac 
- Meshery Server Version: stable-v0.5.42
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by afzal442** [comment]
I would like to try this. 

/assign

**Comment by sayantan1413** [comment]
Sure @afzal442 go ahead 🚀

**Comment by afzal442** [comment]
@sayantan1413 could u help me reproduce this issue? thanks

**Comment by afzal442** [comment]
for now I am getting null on my notification section as this 

![c5](https://user-images.githubusercontent.com/11625672/128606894-028a4984-07a7-4d63-ac80-e63ba5da09a6.JPG)

**Comment by leecalcote** [comment]
I believe that this has been fixed.
