### ISSUE TITLE
[Docs] Anchor for every unique error code

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3787]
#### Current State
Each entry in the [Error Code Reference ](https://docs.meshery.io/reference/error-codes)is unique. Having an anchor associated with each entry will aid in directing users to the specific error of interest.

#### Example

When a `mesheryctl` user sees an error with url, that url can include a specific reference to help for the specific error that they are experiencing.

So, instead of this:
```
➜  ~ mesheryctl system channel switch edge
Error: ctlK8sConnect1001: !! cannot query the Kubernetes API. See https://docs.meshery.io/reference/error-codes
```

Users will get this:
```
➜  ~ mesheryctl system channel switch edge
Error: ctlK8sConnect1001: !! cannot query the Kubernetes API. See https://docs.meshery.io/reference/error-codes#ctlK8sConnect1001
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by afzal442** [comment]
Do we have to add an anchor tag for each unique error code in a separate column? @leecalcote

**Comment by leecalcote** [comment]
No, not a separate column. An `a` tag with a `name` that isn't visible to the reader should do the trick. // @adithyaakrishna

**Comment by brodyf42** [comment]
It looks like there can be more than one instance of an error code on the page if it shows up in more than one section.  A couple of examples are ErrGetLatestReleasesCode  and ErrGetLatestReleaseNamesCode as seen in the images below.  Maybe the fact that they have different error code numerical values in each section is still enough to create unique entry points on the page, but I'm not sure if that will always be true. 

![image](https://user-images.githubusercontent.com/32661013/128617803-4e89a2cd-2a0b-424b-b952-84d72fb401ab.png)

![image](https://user-images.githubusercontent.com/32661013/128617814-b9c6168d-74d1-4c16-ac09-ab12d0ea168d.png)

**Comment by afzal442** [comment]
Thanks @brodyf42 for bringing up this here.

> Maybe the fact that they have different error code numerical values in each section is still enough to create unique entry points on the page

 If it is so, we can add an anchor associated with each entry in the Error Code Reference as below:

**Errror Name**                     ||                          **Error Code**
`ErrGetLatestReleaseCode        ||            ctlK8sConnect1001`

**Comment by adithyaakrishna** [comment]
@leecalcote Just a small doubt, is it that the users will see this in the CLI Tool itself with the link to the error code or only the documentation has to be updated as you mentioned in Users will get this

**Comment by awardnasc** [comment]
Looking through the page it looks like "Error Name || Error Code" wouldn't be unique either. 


![image](https://user-images.githubusercontent.com/15613449/136074446-ad16acd6-a267-4fd4-8911-a3f63674e53a.png)
![image](https://user-images.githubusercontent.com/15613449/136074507-8f69efba-2756-43d8-8feb-85b986d19ce6.png)


My proposal is that the anchor tags are built off of the adapter and error code as shown below. 
Adapter Name || Error Code
```consul || ErrGetLatestReleasesCode```

If this seems acceptable I can go ahead and put together a PR for it.

**Comment by leecalcote** [comment]
Great catch, @awardnasc. You're spot on regarding the scope of these error codes being that of per-component. 👍
