### ISSUE TITLE
[UI] Dashboard: Add hyperlink to version-specific release notes in release widget

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3792]
#### Current Behavior
Users are shown their Meshery deployment's currently running release version, but not given a link to the release notes for that version. 

#### Desired Behavior
All release notes are available at https://docs.meshery.io/project/releases. Release notes for specific versions are available https://docs.meshery.io/project/releases/vXX.XX.XX. 

#### Acceptance Tests
1. The hyperlink provided to users running on the Edge release channel should be non-specific: https://docs.meshery.io/project/releases
1. The hyperlink provided to users running on the Stable release channel should be specific: https://docs.meshery.io/project/releases/vx.x.x

#### Mockups
<img width="1845" alt="release notes link" src="https://user-images.githubusercontent.com/7570704/128401062-ed6955ec-633d-4472-9c97-57f660e6c1ce.png">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by CipherGirl** [comment]
I would like to work on this issue :)

**Comment by warunicorn19** [comment]
Here you go! @CipherGirl
