### ISSUE TITLE
[Docs] Releases: Broken link to release notes on github

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3793]
#### Current State
The link encircled in red is broken for each release notes page. Example here - https://docs.meshery.io/project/releases/v0.5.42

<img width="889" alt="Screen Shot 2021-08-05 at 1 35 43 PM" src="https://user-images.githubusercontent.com/7570704/128403306-cf7e7317-fc54-4b1f-a191-dcf2ec0b27ec.png">

#### Desired State
The link should direct users to the specific release on GitHub.com.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Rubix982, fyi, a fresh issue to the extent it interests you.

**Comment by Rubix982** [comment]
Looks awesome, would love to be assigned this. Thank you for the mention, @leecalcote.

**Comment by warunicorn19** [comment]
@Rubix982 , here you go!😄

**Comment by Rubix982** [comment]
@leecalcote the link to the [figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) shows "File not found". Can you take a look at it? Thank you. :smile: 

![image](https://user-images.githubusercontent.com/41635766/128406529-fe3ec144-a521-4c83-a6b9-63fa28234f91.png)

**Comment by warunicorn19** [comment]
hey @Rubix982, this requires access. @Tanuj22 can get you access to the figma files. Also, just so that we are on the right page😅, this issue doesnt require any figma designs.

IMPLEMENTATION:
Change the link to github logo in the release.html layout.

**Comment by Rubix982** [comment]
Yeah, I was just going through the above links - not related to the current issues - and I thought "this might be broken", so posted a comment over it.

**Comment by warunicorn19** [comment]
Alrighty, no problem at all😃.

**Comment by Rubix982** [comment]
Hi, @warunicorn19, I have been working on something else for the past few days. I'll try to follow up tomorrow with more updates.

**Comment by warunicorn19** [comment]
alrighty @Rubix982 , no sweat, just a routine check up, feel free to write in the slack channel if you need any help.
