### ISSUE TITLE
[mesheryctl] Global flag `-c` not honored in `system context view`

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3796]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Global flag `-c` not honored in `system context view`

```
➜  ~ mesheryctl system context view -c docker
Error: unknown shorthand flag: 'c' in -c
➜  ~ mesheryctl system context view --context docker

Current Context: docker

endpoint: http://localhost:9081
token: Default
token-location: auth.json
platform: docker
adapters:
- meshery-istio
- meshery-linkerd
- meshery-consul
- meshery-nsm
- meshery-kuma
- meshery-cpx
- meshery-osm
- meshery-traefik-mesh
channel: edge
version: latest
```

#### Environment

- Host OS: Mac 
- Meshery Client Version: stable-v0.5.42

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by afzal442** [comment]
In order to do that, I can add `c `flag into this line

https://github.com/meshery/meshery/blob/db86ef6a5a700d4016b087fc50321bb1c92d42b6/mesheryctl/internal/cli/root/system/context/view.go#L54

`viewContextCmd.Flags().StringVar(&context, "context", "c", "", "Show config for the context") `

// @leecalcote

**Comment by leecalcote** [comment]
Sounds great, @afzal442. Yep, that's about right.
