### ISSUE TITLE
[UI] Improve The Graph UI in Performance Profiles Page

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3798]
#### Current Behavior
The performance graphs that are being shown right now in meshery ui are looking cluttered with information which makes it difficult for the users to consume the data. 

<img width="1440" alt="Screenshot 2021-08-06 at 10 41 45 AM" src="https://user-images.githubusercontent.com/75248557/128459190-a0a46e3f-41e6-4913-a900-f2f6ae8b35d0.png">

#### Desired Behavior
Make the performace graph modal less cluttered so that the users can easily consume the information.

#### Implementation
The way the graph is presented cannot be improved, but the presentation of this data shown in the image below can be improved. 

<img width="1440" alt="Screenshot 2021-08-06 at 10 45 51 AM" src="https://user-images.githubusercontent.com/75248557/128459593-375ca0fc-ddc9-4249-bd3c-fc17cd448153.png">

### Acceptance Criteria
1. Extract the latency calculations and on either the left hand or right hand side of the histogram, vertically stack the P50, P90, P95, P99 results. // @Meghana-12 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik So, basically in this issue i need to represent the data that you have highlighted in a better way right?

**Comment by sudo-NithishKarthik** [comment]
yuop, @warunicorn19

**Comment by veerreshr** [comment]
If none is working on this, could I work on this issue?

**Comment by warunicorn19** [comment]
@veerreshr you can surely go ahead and try this out, I'm having a hard time to figure this out.
