### ISSUE TITLE
[UI] Performance: Performance Test Results Modal for individual calendar item

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3799]
#### Current Behavior
In the performance page calendar, clicking the items does not do anything.

https://user-images.githubusercontent.com/75248557/128460312-3e2e0bdd-904b-496e-9f63-cc07ce23c170.mov

#### Desired Behavior
On, clicking the items, it should take the user to that particular test result.

#### Implementation
Reuse the same modal being used for displaying performance graph with the data for that particular test.

#### Acceptance Tests

- [ ] Clicking on any item(test result) in the calendar should open the performance graph

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by CipherGirl** [comment]
Hi Nitish, Can you explain how can I reproduce this? I have an empty performance calendar page..

**Comment by sudo-NithishKarthik** [comment]
@CipherGirl , you can create a performance profile in `Profiles` tab and run a test, which will reflect in the calendar

**Comment by leecalcote** [comment]
@CipherGirl the test can be against any endpoint (like https://www.google.com).

**Comment by CipherGirl** [comment]
Thanks! I'll take up this issue, I need some help though. I am trying to figure out how to insert the modal in the calendar component. Maybe, we can discuss this in the slack channel.

**Comment by CipherGirl** [comment]
@sudo-NithishKarthik @leecalcote I've created a PR. Let me know if it needs improvement in any way. :)
