### ISSUE TITLE
[UI] Improve calendar placement in performance page

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3800]
#### Current Behavior
The placement of calendar is not very appealing. Some information is lost because of the calendar width being small.

<img width="1440" alt="Screenshot 2021-08-06 at 11 10 43 AM" src="https://user-images.githubusercontent.com/75248557/128461737-b95c3b89-bd5c-419f-95fc-d1e6b678c887.png">

<img width="1440" alt="Screenshot 2021-08-06 at 11 09 49 AM" src="https://user-images.githubusercontent.com/75248557/128461660-5e3ed0b0-1ca7-4666-afc1-b7bd7fb6a627.png">

#### Desired Behavior
The placement of calendar should be changed. 

#### Implementation
Move the calendar unto it's own card and make it span the entire width.

#### Acceptance Tests

- [ ] The card for `Service mesh metrics` should not be moved to the bottom.

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sudo-NithishKarthik** [comment]
@Abhishek-kumar09 , add your suggestions for implementation if you have any.

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik Do we want something like this?
<img width="1440" alt="Screenshot 2021-08-06 at 2 55 20 PM" src="https://user-images.githubusercontent.com/53532328/128489217-008d01b9-4712-4bcc-9084-ace1d3900039.png">

**Comment by sudo-NithishKarthik** [comment]
Yes @warunicorn19 , this will do, make sure that the calendar is moved down according to the height of the `service mesh metrics` card. I don't see any other way to place this calendar.

// @leecalcote

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik as in add more space between the `service mesh metrics` and the calendar?

**Comment by Abhishek-kumar09** [comment]
That is looking great
