### ISSUE TITLE
[Docs] Create a new page for configuration management

### ISSUE THREAD

**Issue by afzal442** [meshery/meshery#3812]
#### Current State
There is no docs page describing one of the meshery's management features about configuration management [here](https://docs.meshery.io/functionality).

_Originally posted by @leecalcote in https://github.com/meshery/meshery.io/pull/508#discussion_r684553731_

#### Desired State

Create a new page for configuration management on the docs itself
As described [here](https://meshery.io/features), you can have a look.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by josephmidura** [comment]
I'll work on this.

**Comment by afzal442** [comment]
plz go ahead @josephmidura !

**Comment by josephmidura** [comment]
After I create the page, is it also necessary to update docs.meshery.io?

**Comment by afzal442** [comment]
> After I create the page, is it also necessary to update docs.meshery.io?

Yes. We have to create a page e.g. how [Lifecyle management](https://docs.meshery.io/functionality/lifecycle-management) is created and described which is indirectly going to reflect docs.meshery.io.

> Create a new page for configuration management on the docs itself

You can take reference from [here](https://meshery.io/features) under configuration category what you want to deal with.

Let me know if that makes sense to you. Thanks

**Comment by josephmidura** [comment]
The information you gave makes sense, but I'll rephrase my original question: Does created the configuration management page for Meshery update docs.meshery.io as a result, or does that need to be updated separately?

**Comment by afzal442** [comment]
// @leecalcote plz?

**Comment by josephmidura** [comment]
Actually, it looks like the preview for my commit in the pull request I linked answers my question. The page "docs.meshery.io" updated as a result of the configuration management page I created.

**Comment by navendu-pottekkat** [comment]
Added pages here: https://docs.meshery.io/functionality
