### ISSUE TITLE
[UI] Chevron not visible on drawer close

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#3816]
#### Current Behavior
The chevron in the dashboard is getting pushed down when the drawer is closed.

#### Desired Behavior
The chevron should be visible to the user on closing of the drawer.

#### Implementation
The chevron is already sticky, but the space between the other icons seems to be causing, try decreasing that. 

#### Acceptance Tests

- [ ] Chevron should be visible when the drawer is closed.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sgibson19** [comment]
@warunicorn19 I would like to work on this

**Comment by warunicorn19** [comment]
Sure, go ahead @sgibson19

**Comment by warunicorn19** [comment]
This issue is fixed by #3890
