### ISSUE TITLE
[UI] Support accordion-style menu when Meshery menu drawer is collapsed.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3825]
#### Current Behavior
Meshery menu is perpetually expanded to show all menu items when the drawer is collapsed.

<img width="75" alt="Screen Shot 2021-08-09 at 1 27 19 PM" src="https://user-images.githubusercontent.com/7570704/128755795-b6800b64-00fe-4988-9099-e63a78e2c2ce.png">

#### Desired Behavior
Offer the same accordion-style behavior when the menu drawer is collapsed as when the menu drawer is fully open.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@leecalcote I think this will also solve #3816

**Comment by leecalcote** [comment]
> @leecalcote I think this will also solve #3816 

That sounds about right. 👍

**Comment by CipherGirl** [comment]
I'd like to look into this :)

**Comment by CipherGirl** [comment]
@sudo-NithishKarthik, @warunicorn19 I'm finding this issue a bit complicated. Maybe I can fix this if I start fresh, although that's a lot of work. Can I get some heads up here please, I can't figure out any simple solution to this.. :/

**Comment by warunicorn19** [comment]
im having a hard time explaining 😂, @CipherGirl did you understand😅?

**Comment by CipherGirl** [comment]
Oh yes, I did! I also thought of that too.. I think it'll look better on the right side.. Let me try to figure out If I can do that..
