### ISSUE TITLE
[Filters] Unable to delete a filter persisted in Remote Provider

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3826]
#### Description
Deleting filters stored in Remote Providers doesn't have the desired affect.

#### Expected Behavior
Filter record should be tombstoned by Remote Provider and no longer displayed in the UI.

#### Screenshots/Logs

<img width="1422" alt="Screen Shot 2021-08-09 at 9 27 58 AM" src="https://user-images.githubusercontent.com/7570704/128757206-9a931e1a-01c4-46e8-9c20-c96fc6a8ea05.png">

#### Environment

- Host OS: Mac 
- Meshery Server Version: stable-v0.5.42
- Meshery Client Version: stable-v0.5.42
- Platform: Docker 

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by navendu-pottekkat** [comment]
I just opened this issue on the provider. It should be a provider issue. Will look into it and fix it.

**Comment by leecalcote** [comment]
Sounds great. Thank you. I'll close this issue given that the other issue is tracking resolution.

**Comment by navendu-pottekkat** [comment]
@Chadha93 You can use this issue to track the bug.

**Comment by Chadha93** [comment]
@navendu-pottekkat  do we have the multiple endpoint functionality to handle bulk delete in one go in the filters because we have the single delete endpoint enabled/handled?

**Comment by navendu-pottekkat** [comment]
This is the handler that deletes the filters.

```go
// DeleteMesheryFilterHandler deletes a filter with the given id
func (h *Handler) DeleteMesheryFilterHandler(
	rw http.ResponseWriter,
	r *http.Request,
	prefObj *models.Preference,
	user *models.User,
	provider models.Provider,
) {
	filterID := mux.Vars(r)["id"]

	resp, err := provider.DeleteMesheryFilter(r, filterID)
	if err != nil {
		http.Error(rw, fmt.Sprintf("failed to delete the filter: %s", err), http.StatusInternalServerError)
		return
	}

	rw.Header().Set("Content-Type", "application/json")
	fmt.Fprint(rw, string(resp))
}
```

So, bulk deleting capability may need to be added to the backend.
