### ISSUE TITLE
[Provider] Remote Provider Plugin Directory Not Being Created

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3828]
#### Current Behavior
The Remote Provider's plugin directory for the currently running stable version of Meshery is not being created for the specific release.

#### Screenshots/Logs
```
➜  ~ ls -l ~/.meshery/provider/Meshery/
total 0
drwxr-xr-x  3 lee  staff   96 Jul 10 11:44 v0.5.15
drwxr-xr-x  3 lee  staff   96 Jun 22 12:59 v0.5.25
drwxr-xr-x  3 lee  staff   96 Jul 10 11:48 v0.5.35
drwxr-xr-x  3 lee  staff   96 Jul 25 14:27 v0.5.39
drwxr-xr-x  4 lee  staff  128 Aug  6 19:33 v0.5.42

➜  ~ mesheryctl version
      	VERSION	GITSHA
Client	v0.5.44	b21b566b
Server	v0.5.44	b21b566b

Checking for latest version of mesheryctl...

  Unable to check for latest version of mesheryctl.
```

Note: the "  Unable to check for latest version of mesheryctl." is due to an overblown rate limit on GitHub's APIs.

#### Environment

- **User:** lcalcote 
- **Host OS:** Mac
- **Platform:** Docker
- **Meshery Server Version:** stable-v0.5.44
- **Meshery Client Version:** stable-v0.5.44

#### To Reproduce
1. Open private browsing session.
2. Sign into Meshery Cloud with admin user.
3. See provider's specific extension listed in menu drawer ("meshmap")
4. Find no directory with the current version listed.

See logs: [meshery-logs.txt](https://github.com/meshery/meshery/files/6958073/meshery-logs.txt)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by utkarsh-pro** [comment]
@leecalcote https://github.com/layer5labs/meshery-extensions-packages/releases/tag/v0.5.44-1 this release does not have meshmap golang plugin
