### ISSUE TITLE
[Docs] Add `app` to mesheryctl documentation

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3829]
#### Current State
`app` is missing on the Using mesheryctl docs page - https://docs.meshery.io/guides/mesheryctl/using-mesheryctl and on the https://docs.meshery.io/reference/mesheryctl reference.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by afzal442** [comment]
// assign

**Comment by afzal442** [comment]
lemme align here FYI

**Using mesheryctl**   same as here **Command Reference**

`mesheryctl app` - Service Mesh Apps Management


<html>
<body>


Main Command | Arguments | Flag | Function
-- | -- | -- | --
<html>
<body>
<google-sheets-html-origin><meta name="sheets-banding" data-sheets-range="A109:Y119" data-sheets-banding-properties="{&quot;1&quot;:{&quot;1&quot;:{&quot;4&quot;:{&quot;1&quot;:2,&quot;2&quot;:6002169}},&quot;2&quot;:{&quot;4&quot;:{&quot;1&quot;:2,&quot;2&quot;:16777215}},&quot;3&quot;:1,&quot;4&quot;:{&quot;4&quot;:{&quot;1&quot;:2,&quot;2&quot;:15266046}},&quot;5&quot;:1}}">

  | file, f | (required) path to application file |  
-- | -- | -- | --
onboard |   | onboard application with application file | mesheryctl app onboard --file <path to application file>
offboard |   | offboard  application file | mesheryctl app offboard --file <path to application file>
list |   | displays a list of available applications | mesheryctl app list
  |   | displays the contents of a specific application file | mesheryctl app view [application-name\|application-id]
view| all, a | show all the appliction file content | mesheryctl app view --all
  | -o json | display the content of a application in json format | mesheryctl app view [pattern-name\|pattern-id] -o json


</body>
</html>


</body>
</html>

**Comment by warunicorn19** [comment]
here you go! @afzal442
