### ISSUE TITLE
[Docs] Update description of Hipster store sample app

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3830]
#### Current State
The Hipster sample application's description in Meshery Docs is out of date: https://docs.meshery.io/guides/sample-apps#hipster.

#### Desired State
This sample application, https://github.com/GoogleCloudPlatform/microservices-demo, has been renamed to Online Boutique

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by afzal442** [comment]
I would like to give it a try. 
// assign

**Comment by warunicorn19** [comment]
here you go @afzal442
