### ISSUE TITLE
[UI] Notification Center: Do not collapse notification card unless title bar is clicked

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3831]
#### Current Behavior
Users might want to copy part of any given notification's details. They are unable to, however, given the notification card collapses on click of the details area.

#### Desired Behavior
Do not collapse notification card unless title bar is clicked.

#### Screenshots/Logs

https://user-images.githubusercontent.com/7570704/128790781-68d7a865-5d99-4337-adba-562443289c22.mov

#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.5.44

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by NikhilSharma03** [comment]
Can I work on this issue?

**Comment by sudo-NithishKarthik** [comment]
Sure @NikhilSharma03 :)
