### ISSUE TITLE
[Docs] Update `mesheryctl` installation guide to include `ADAPTER`

### ISSUE THREAD

**Issue by suhaniii** [meshery/meshery#3834]
#### Current State
Currently docs are guiding user to deploy `meshery` with all the adapters available.
```
curl -L https://git.io/meshery | PLATFORM=kubernetes bash -
 ```
#### Desired State
Update docs , so that user can install list of adapters provided by them
Example - 
```
curl -L https://git.io/meshery | ADAPTERS=istio  PLATFORM=docker bash -
```
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)
-  Useful links
    https://docs.meshery.io/installation/mesheryctl
    https://docs.meshery.io/guides/mesheryctl/using-mesheryctl
    https://github.com/meshery/meshery/blob/master/meshery

**Comment by SirZeck** [comment]
@devansh42 are you still working on this issue? Seems inactive for quite long?

**Comment by devansh42** [comment]
No, I'm not working you can take this up

**Comment by siddhantprateek** [comment]
I would like to work on this issue.

**Comment by warunicorn19** [comment]
Sure @siddhantprateek, go for it.

**Comment by siddhantprateek** [comment]
This is what I know, These are the list of [Adaptors](https://docs.meshery.io/concepts/architecture/adapters) that Meshery use and I have to make changes in `quick-start.md` [ref page](https://docs.meshery.io/installation/quick-start) and `mesheryctl.md` [ref page](https://docs.meshery.io/installation/mesheryctl) right.

**Comment by leecalcote** [comment]
Adding to the list of questions on this page is desirable - https://docs.meshery.io/concepts/architecture/adapters

**Comment by siddhantprateek** [comment]
![Screenshot from 2021-09-16 17-26-44](https://user-images.githubusercontent.com/43869046/133608103-bae0aa88-b0e1-4dd4-90ec-b5419a484685.png)
@leecalcote, If such changes are acceptable. I have made some additional changes in the front matter of all the `_adapters`, I have added a new variable to the front matter so that can get all adapter-option keywords.

**Comment by leecalcote** [comment]
Thank you, @Yiyiyimu. 👍 closing this issue...
