### ISSUE TITLE
Create forked image for containrrr/watchtower to support ARM/M1 chips

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3853]
#### Current Behavior

containrrr/watchtower container crashes when running on M1/ARM machines. This is because the image pulled does not support the M1 chip.

#### Desired Behavior

Create a fork of https://github.com/containrrr/watchtower and build the image for M1/ARM platform and push the image to Docker Hub and use this forked image in Meshery.

This would need exploration to see if this is feasible.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by suhaniii** [comment]
@navendu-pottekkat How to recreate this issue?

**Comment by navendu-pottekkat** [comment]
@suhaniii You have to run Meshery in Docker platform on an Apple Machine with M1/ARM chip

**Comment by suhaniii** [comment]
@navendu-pottekkat RN we pull image from `v2tec/watchtower` after building new image where in docker hub do we want to push it?

**Comment by navendu-pottekkat** [comment]
Well, we have a docker hub account. We can maybe push it here if we are able to fix the issue on M1 chips.
