### ISSUE TITLE
[UI] Meshery Operator and MeshSync chips getting overlapped

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#3855]
#### Current Behavior
At a reduced screen size the meshery operator chip and meshsync chip overlap 

#### Desired Behavior
They should not overlap and be distinct

#### Screenshots/Logs
SAFARI-

<img width="988" alt="Screenshot 2021-08-11 at 11 30 04 PM" src="https://user-images.githubusercontent.com/53532328/129081378-fc178ff2-5014-48f6-93ec-1296e4de8b12.png">

CHROME-

<img width="970" alt="Screenshot 2021-08-11 at 11 34 02 PM" src="https://user-images.githubusercontent.com/53532328/129081588-32f6a293-2d8e-47ed-98ee-0605ca58ece9.png">

#### Environment

- Browser: Chrome Safari 
- Host OS: Mac 
- Meshery Server Version: stable
- Meshery Client Version: stable
- Platform: Docker 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by NikhilSharma03** [comment]
Can I work on this?
