### ISSUE TITLE
[UI] Display badge for beta features 

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3860]
#### Current Behavior
Right now, in meshery ui, there is no way to distinguish beta features from others.

#### Desired Behavior
We need to add a badge for beta features.

#### Implementation
The badge should be added as shown in the mockup for beta features.
For a whole page/component , the badge should be in the navigation bar along with the name.

Beta Components:
1. Meshmap
2. Applications
3. Filters
4. Patterns

#### Mockups
Assuming `Manage service meshes` to be a beta feature, the badge should look like, 

<img width="749" alt="Screenshot 2021-08-12 at 6 40 36 PM" src="https://user-images.githubusercontent.com/75248557/129202490-ab83c828-32f1-4dde-8ade-008e71b3d866.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ishitakeshawani** [comment]
Can I work on this issue? @sudo-NithishKarthik

**Comment by warunicorn19** [comment]
@ishitakeshawani here you go!

**Comment by ishitakeshawani** [comment]
Thank you. @warunicorn19

**Comment by ishitakeshawani** [comment]
It's asking for permission. I am not able to view wireframes in Figma.

**Comment by warunicorn19** [comment]
Could you give me your email?

**Comment by ishitakeshawani** [comment]
keshwaniishita054@gmail.com

**Comment by warunicorn19** [comment]
@ishitakeshawani you shouldve recieved an invite and will have access now, please check and confirm.

**Comment by ishitakeshawani** [comment]
Yes got it. Thanks.

**Comment by sudo-NithishKarthik** [comment]
@ishitakeshawani , do you have any updates on this ?

**Comment by ishitakeshawani** [comment]
I will do it by tonight. Sorry for the delay.

**Comment by sudo-NithishKarthik** [comment]
No issues, @ishitakeshawani , just wanted to know if you were facing any blockers ✌🏽

**Comment by ishitakeshawani** [comment]
Do I need to add the badge to the header or inside the card near the name eg. application? @sudo-NithishKarthik 
![Screenshot from 2021-08-22 18-06-10](https://user-images.githubusercontent.com/50510726/130355478-d8b24f21-d891-4db7-a82d-7371a974651e.png)

**Comment by sudo-NithishKarthik** [comment]
In this case, `Applications` page itself is a beta feature, so, the one is screenshot looks fine

**Comment by sudo-NithishKarthik** [comment]
But, can you try adding some colour, white doesn't look nice...

**Comment by ishitakeshawani** [comment]
yes, I will change it. I kept white to show it in screenshots, to ask questions.

**Comment by warunicorn19** [comment]
Also @ishitakeshawani please give a specific height and width to the beta icon so that it scales on safari.

**Comment by ishitakeshawani** [comment]
Ok, I will.
