### ISSUE TITLE
[UI] Help and Chevron not visible in mobile view

### ISSUE THREAD

**Issue by sayantan1413** [meshery/meshery#3862]
#### Current Behavior
The Help button and the Chevron are not visible in the Meshery's dasboard in the mobile view.

#### Desired Behavior
The Help button and the Chevron should be visible in the Meshery's dasboard in the mobile view too.

#### Screenshots/Logs
<img width="361" alt="Screenshot 2021-08-12 at 9 37 22 PM" src="https://user-images.githubusercontent.com/64970095/129230392-826fcb89-5198-40ae-81cc-be92e06cc3ee.png">

#### Environment

- Browser: Chrome Safari 
- Host OS: Mac 
- Meshery Server Version: v0.5.45
- Meshery Client Version: v0.5.45
- Platform: Docker 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by yagarwal1307** [comment]
anyone working on this issue or can I take it up?

**Comment by warunicorn19** [comment]
Go ahead @yagarwal1307
