### ISSUE TITLE
[mesheryctl] `mesheryctl mesh` subcommand for viewing SMI conformance test results

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#3868]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
There is no command to view SMI conformance results using meshery CLI.

#### Desired Behavior
We should have a subcommand for `mesheryctl mesh validate` for viewing the results by supplying the ID of a conformance test.
One, so as to create a similar experience as the `perf` commands. Two, to facilitate immediate display of results in GH action.

#### Implementation
Design spec: https://docs.google.com/document/d/1E0u9twIcHrnEa0NgytNxobQVRh6EnujfQU5Y0Ocvdq8/edit#

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by piyushsingariya** [comment]
@DelusionalOptimist this is a pending feature from a long time, because there's no api available to get a single Test Result.
