### ISSUE TITLE
[mesheryctl] system start throws an error if not able to open Meshery in the browser

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3870]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system start` will try to open up the Meshery endpoint in the browser after installing Meshery.

But it throws an error if it is not able to open the endpoint in the browser and says failed to start Meshery.

![Screenshot 2021-08-13 at 6 08 27 PM](https://user-images.githubusercontent.com/49474499/129358469-9c3b5fbc-6e36-4216-b364-98baaefc44f2.png)

#### Desired Behavior

This error should be suppressed and users should be directed to open the endpoint in the browser.

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
@navendu-pottekkat  this issue was already created by @DelusionalOptimist in issue #3778  and I have created a PR against it. A small fix.

**Comment by navendu-pottekkat** [comment]
Great, I was not sure if this issue was being tracked. Thank you @Revolyssup
