### ISSUE TITLE
[mesheryctl] enhance `mesheryctl mesh remove` 

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#3873]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`mesheryctl mesh remove` doesn't use the event streamer utility and thus doesn't wait for remove operation event to complete.

#### Desired Behavior
The command should watch for events and wait till receiving an event signalling service mesh was removed successfully. If it is not removed, then the command should throw an error. 

#### Implementation
The implementation should be similar to the `mesheryctl mesh deploy` command. For reference, see
https://github.com/meshery/meshery/blob/c8dd33ae4f8756b0f69f06edb27e6cda5b904498/mesheryctl/internal/cli/root/mesh/deploy.go#L122-L173

#### Acceptance Tests
Exit with proper exit codes when operation fails.

#### Mockups

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by umairnsr87** [comment]
Can I work on this issue @DelusionalOptimist ?

**Comment by warunicorn19** [comment]
For sure! @umairnsr87

**Comment by DelusionalOptimist** [comment]
Thanks @umairnsr87 :raised_hands: . Feel free to ask away any doubts you have.

**Comment by umairnsr87** [comment]
Sure @DelusionalOptimist , @warunicorn19  Thanks ....!

**Comment by alphaX86** [comment]
@DelusionalOptimist quick Q here which error code we need to use? I see a list of error codes in the `error.go` but I'm not sure which to use

**Comment by alphaX86** [comment]
@leecalcote do I need to create a error code for this? Or if any existing one is present, which I need to use it?

**Comment by DelusionalOptimist** [comment]
@alphaX86 feel free to make new error codes in https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/mesh/error.go.
They would be similar to that of `deploy`.
Also, you can look into if some error codes can be reused. For e.g.
https://github.com/meshery/meshery/blob/05a4985f86d3a628ef629a3d491e2ad06938f554/mesheryctl/internal/cli/root/mesh/error.go#L43
This can be used for all deploy, remove and validate with some changes, eliminating the need of declaring multiple error functions.

**Comment by alphaX86** [comment]
So you mean I can create an error code and reuse a function for ease?

**Comment by DelusionalOptimist** [comment]
Sorry @alphaX86 I was away :sweat_smile: 

> So you mean I can create an error code and reuse a function for ease?

Yes, precisely :heavy_check_mark:

**Comment by alphaX86** [comment]
Folks????? 👀👀

**Comment by leecalcote** [comment]
@alphaX86 I think your infusion stems from a lack of understanding of the error framework in MeshKit. Here is a contributing guide that will explain - https://docs.meshery.io/project/contributing/contributing-error

**Comment by alphaX86** [comment]
@leecalcote actually 😅 error codes are made in MeshKit and almost ready, what I need is reviewers to test my PR coz it's been.... a month and a week since last reply in that PR :')

**Comment by leecalcote** [comment]
@gr455, think that you are up to this challenge?

**Comment by gr455** [comment]
Sure @leecalcote. I can have a shot at this

**Comment by alphaX86** [comment]
It's all yours now @gr455 :) If you have any queries, you are welcome to refer previous PRs made to solve the issue. Good luck bro

**Comment by gr455** [comment]
> It's all yours now @gr455 :) If you have any queries, you are welcome to refer previous PRs made to solve the issue. Good luck bro

Thank you! I'll try my hand at this :D

**Comment by gr455** [comment]
I am trying out #4951, which will itself take me some time, so I am unassigning myself so someone else could take this one up in the meantime.

**Comment by alphaX86** [comment]
> I am trying out #4951, which will itself take me some time, so I am unassigning myself for now so someone else could take this one up in the meantime.

No issues @gr455 👍

**Comment by leecalcote** [comment]
@navendu-pottekkat will you work on this?

**Comment by navendu-pottekkat** [comment]
@leecalcote Sorry, I can't. @alphaX86 Could you take this up as you have previously looked into the issue?

**Comment by gr455** [comment]
> @leecalcote Sorry, I can't. @alphaX86 Could you take this up as you have previously looked into the issue?

Can I try this? Doing some playgrounds now to get a hang of meshery

**Comment by leecalcote** [comment]
@gr455, thanks for picking up the slack, yes.
