### ISSUE TITLE
[Perf] Constrain Display of Test Results to Specific Profile

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3876]
#### Current Behavior
<img width="1683" alt="Screen Shot 2021-08-13 at 3 20 25 PM" src="https://user-images.githubusercontent.com/7570704/129421174-f3fe496f-a28e-4601-9243-9e89664b33aa.png">

#### Expected Behavior
Only 2 results to be displayed in the table.

- **Meshery Server Version:** stable-v0.5.46

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Was this defect fixed, @utkarsh-pro?

**Comment by utkarsh-pro** [comment]
@leecalcote, yes this was fixed.
