### ISSUE TITLE
[Docs] Add list of reusable components - Meshery UI

### ISSUE THREAD

**Issue by humblenginr** [meshery/meshery#3884]
#### Current State
Meshery UI has a number of components that are designed to be reused over the codebase, but since we don't have a list of them in the docs, contributors are unaware of it and it results in them rewriting the same components again

#### Desired State
Add these list of reusable components to the meshery ui contributing docs so that people will be aware of the existence of such components.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by guptapriyanshu7** [comment]
@sudo-NithishKarthik Can I take this up?

**Comment by warunicorn19** [comment]
For sure! @guptapriyanshu7

**Comment by ShivamTyagi12345** [comment]
Can I help with this🙂. I am a beginner and I see all other issues taken up already

**Comment by warunicorn19** [comment]
Go for it @ShivamTyagi12345

**Comment by warunicorn19** [comment]
@ShivamTyagi12345 any updates on this?

**Comment by ShivamTyagi12345** [comment]
> @ShivamTyagi12345 any updates on this?

Unassigning myself due to prior commitments. Thanks a lot for the opportunity

**Comment by vaibhav135** [comment]
@leecalcote  can you assign this issue to me if no one else is working on it ?

**Comment by leecalcote** [comment]
The Sistent Design System has been created for this purpose --> https://github.com/meshery/sistent
