### ISSUE TITLE
[UI] Move the Performance tab in settings page to user preferences page

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3891]
#### Current Behavior
In settings page, we have a tab called _Performance_ which is supposed to set the default configs for load test for that particular user. It makes more sense for it to be in  user preferences page since the load test configs are specific to a user and not to a system.

<img width="1440" alt="Screenshot 2021-08-15 at 7 31 17 PM" src="https://user-images.githubusercontent.com/75248557/129481027-8a6991cc-9721-42e7-be9f-c6dc073b0aa5.png">

#### Desired Behavior
Performance tab in settings page should be completed moved to the user preferences page

<img width="1440" alt="Screenshot 2021-08-15 at 7 28 57 PM" src="https://user-images.githubusercontent.com/75248557/129481014-d7569561-a2e7-44c7-bda3-1e66e7e1e3a1.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by yagarwal1307** [comment]
I would like to give this issue a try if no one else is working on it.

**Comment by sudo-NithishKarthik** [comment]
Sure @yagarwal1307 !! go ahead 😄
