### ISSUE TITLE
[mesheryctl] failed to delete pattern

### ISSUE THREAD

**Issue by iamsdas** [meshery/meshery#3894]
#### Current Behavior

When trying to delete a pattern with a path of `./a.yml`, I am getting this error:
```
$ mesheryctl pattern delete -f ./a.yml
failed to delete resource with name "app" in namespace "test"
```
Link to the used pattern file: [a.yml](https://discuss.layer5.io/t/sample-service-mesh-pattern-files/115/4)
#### Desired Behavior

Successful deletion of pattern 
#### Environment

- Host OS: Linux
- Meshery Server Version: edge-latest
- Meshery Client Version: v0.5.46
- Platform: Docker

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by utkarsh-pro** [comment]
@iamsdas do you have "app" running in "test" namespace? Please attach output of `kubectl get deploy -n test`, it would be helpful to debug.

**Comment by iamsdas** [comment]
That line results in a `No resources found in test namespace.`
After some more digging I noticed that this error only occurs when we have applied the same pattern multiple times and try to delete the pattern for the second time. The delete pattern works perfectly when deleting the first time but does nothing for the next attempts.

**Comment by utkarsh-pro** [comment]
@iamsdas patterns are idempotent and engine is smart enough to figure out that you are requesting the same resource more than once that's why even after applying same pattern again and again, instead of throwing error engine is updating the resource on your behalf. Hence your cluster has only **one** resource. After applying `delete` first time, that resource is deleted from the cluster hence subsequent `delete` return error.

**Comment by iamsdas** [comment]
Okay so if I understand correctly, when we apply the same pattern multiple times it simply updates the original one. Then it should be a bug in `mesheryctl pattern list` which displays it multiple times (and keeps on displaying it even after the first deletion)?

**Comment by iamsdas** [comment]
Thank you for the clarification @utkarsh-pro 
Closing the issue as this was not a bug
