### ISSUE TITLE
[mesheryctl] editing pattern name causes panic when listing

### ISSUE THREAD

**Issue by iamsdas** [meshery/meshery#3895]
#### Current Behavior

If we edit the name of the  pattern file and save it, then running `mesheryctl pattern list` results in a panic.

* This only happens when the provider is set to `None`.
* Also the `created_at` is missing in the server response
 #### Desired Behavior

Patterns should be listed without any errors
#### Screenshots/Logs
Before and after editing pattern name:

![image](https://user-images.githubusercontent.com/26461855/129484814-a9348b48-ba68-4a48-a3a4-8c590c39b0d2.png)

#### Environment

- Host OS: Linux
- Meshery Server Version: edge-latest
- Meshery Client Version:  v0.5.46
- Platform: Docker

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by iamsdas** [comment]
cc @utkarsh-pro

**Comment by utkarsh-pro** [comment]
cc @piyushsingariya

**Comment by suhaniii** [comment]
@piyushsingariya  Can you paste API response here, where and when `created_at` was missing?

**Comment by piyushsingariya** [comment]
@iamsdas @suhaniii I checked with latest release, I don't know why but it's working fine!

**Comment by iamsdas** [comment]
@piyushsingariya its working for `meshery` provider, are you sure you tested it with `None`?

**Comment by piyushsingariya** [comment]
I checked for None provider! stable-latest.
