### ISSUE TITLE
[mesheryctl] `system channel switch` does not change the tag in the Kubernetes manifests

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3896]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system channel switch` on Kubernetes platform only sets the channel in the meshconfig file and restarts the pods in the cluster.

Where as in Docker platform, the channel is updated in the running deployment.

#### Desired Behavior

`mesheryctl system channel switch` should also restart Meshery with the newly set channel in Kubernetes platform.

#### Implementation

Stopping and Starting Meshery for Kubernetes would ensure this would happen. This would be the straightforward change.

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
@suhaniii  are you going to rewrite the restart function ?
@navendu-pottekkat  should @suhaniii first flatten the context as @metonymic-smokey  suggested so that restart function can be reused?

**Comment by suhaniii** [comment]
@navendu-pottekkat Stopping and Starting Meshery for Kubernetes in restart.go will overwrite the configurations by user, the issue which we are facing on system restart with docker?

**Comment by navendu-pottekkat** [comment]
@suhaniii I am not sure that it will. Change channels in meshconfig --> Stop Meshery --> Start Meshery. This should ensure that we start Meshery with the updated channel right?
