### ISSUE TITLE
[mesheryctl] `system stop` fails for Kubernetes platform if the manifest files are not present 

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3897]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`system stop` throws an error that the manifest file is missing if the `.meshery/manifests` folder is missing the manifests and stops executing.

#### Desired Behavior

If the files are missing, then fetch the corresponding version of the manifests as specified in the meshconfig(`.meshery/config.yaml`) file and stop Meshery.

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by nehaLohia27** [comment]
@navendu-pottekkat Please assign this to me

**Comment by nehaLohia27** [comment]
@navendu-pottekkat  can you show the manifest version in the config.yaml. I am not able to see it in the config.yaml
Also can you tell which manifest file to check for not available , there are lot of manifests file available in the .meshery/manifests folder corresponding to different adapters..

**Comment by navendu-pottekkat** [comment]
The `channel` and `version` in the meshconfig is the version I mentioned in the issue. Basically `system start`pulls all the manifests from GitHub at a particular version and it will be stored in the `.meshery` folder. But for some reason it is removed, then mesheryctl cannot stop Meshery as the manifest files are not present. If the files are not present, then we should re-download them and delete the Meshery deployments.

**Comment by navendu-pottekkat** [comment]
So, the manifest files would be all the manifest files that are applied during the `system start` operation, the Meshery + adapter manifests as well as the operator manifests.

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat In my cached manifests PR, I am checking for the presence of adapter and operator manifests. Maybe I could make that a separate function which Neha can then use here once that PR is merged?

**Comment by metonymic-smokey** [comment]
@nehaLohia27  another of my PRs depends on this issue being fixed.
It would be super helpful if you could fix this issue!
Thanks!

**Comment by nehaLohia27** [comment]
Sure @metonymic-smokey Will fix this issue.

**Comment by nehaLohia27** [comment]
@metonymic-smokey Working on this today. should be done soon. Thanks

**Comment by nehaLohia27** [comment]
@metonymic-smokey Does you cached manifest PR merged, can you point to the function which checks  for the presence of adapter and operator manifests.?

**Comment by metonymic-smokey** [comment]
https://github.com/meshery/meshery/blob/758329acfed7ecf1d3197cfffb136c606e702694/mesheryctl/pkg/utils/platform.go#L277 - this one is for k8s adapter manifests.
There is a similar one for operator manifests.

**Comment by suhaniii** [comment]
@nehaLohia27  is away  next week, I will be working on this issue.
