### ISSUE TITLE
[Filter] Request to persist additional filter metadata

### ISSUE THREAD

**Issue by tangledbytes** [meshery/meshery#3900]
#### Current Behavior
Currently meshery persists only the following data about a filter.
1. Filter - WASM binary
2. Filter name

#### Desired Behavior
Meshery should probably be persisting addtional metadata regarding a filter other than storing the binary and its name. Proposal is to store the following data:
1. Workload selection metadata - An object workload labels (as key - value pairs)
The structure may look like:
```json
{
    "workload_selector": {
        "labels": { 
            "ratelimit.filter.meshery.io": "enabled" 
        }
    }
}
```
2. Operation to be used to add the filter in the envoy filter chain.
The structure may look like:
```json
{
    "operation": "<values from https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-Patch-Operation >"
}
```
3. Config context location. Some filters maybe `SIDECAR` specific, some could be `GATEWAY` specific, etc. This should also store if the filter needs to be attached on the `INBOUND` traffic, `OUTBOUND` traffic or both. 
The structure may look like:
```json
{
    "apply_to": "<values from https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ApplyTo >",
    "match": "<values from https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-EnvoyConfigObjectMatch >"
}
```

The configuration captured above should be more than enough capture all the relevant information about the WASM filter. The proposal refers to the istio documentation for capturing the structure however other service meshes which do use envoy filter as data plane will be supported. The implementation of the Pattern workload will have to fill the _gaps_.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Completed. https://meshery.io/blog/partners/unlocking-the-power-of-webassembly-in-service-mesh-management
