### ISSUE TITLE
[UI] Unable to click "Settings" button in toaster notification 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3910]
#### Current Behavior

https://user-images.githubusercontent.com/7570704/129776659-254962c3-9eb3-47ef-9153-62a034a17b20.mov

#### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Server Version: stable-v0.5.47
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@NikhilSharma03 will you tackle this one?

**Comment by NikhilSharma03** [comment]
> @NikhilSharma03 will you tackle this one?

Sure sir. On it :rocket:
