### ISSUE TITLE
[UI] Service Mesh Dashboard: Malformed Open Service Mesh name

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3912]
#### Current Behavior
<img width="545" alt="Screen Shot 2021-08-17 at 1 00 11 PM" src="https://user-images.githubusercontent.com/7570704/129777266-3c34c41d-f021-456c-b00e-dd66cd522149.png">

#### Desired Behavior
Should read "Open Service Mesh"

#### Environment

- Browser: Chrome
- Host OS: Mac 
- Meshery Server Version: stable-v0.5.47

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by bariqhibat** [comment]
Fixed at [PR](https://github.com/meshery/meshery/pull/3922)
