### ISSUE TITLE
[UI] Ability to maximize the Application and Pattern Editor

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3914]
#### Current Behavior
Long pattern and application files are easier to edit when the user can maximize (and restore back to original modal size) the editor modal.

#### Implementation
1. choose one of the two matching sets of icons below (https://react-icons.github.io/react-icons/search?q=maxim)
1. place maximize/restore icon in upper right hand corner of modal

#### Acceptance Tests
1. When modal is orginal size show maximize button.
1. When modal is maximized show restore button.

#### Mockups
<img width="1222" alt="Screen Shot 2021-08-17 at 1 26 49 PM" src="https://user-images.githubusercontent.com/7570704/129781077-9d855a94-76d3-455b-9e16-3f84d2e5955d.png">
<img width="212" alt="Screen Shot 2021-08-17 at 1 34 16 PM" src="https://user-images.githubusercontent.com/7570704/129781653-405ca6a2-f415-4d08-adec-78c8488fb04c.png">
<img width="217" alt="Screen Shot 2021-08-17 at 1 34 08 PM" src="https://user-images.githubusercontent.com/7570704/129781674-e1558fb0-4b03-4c30-aba7-71f83a1d5a46.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@leecalcote can i work on this?

**Comment by leecalcote** [comment]
@Meghana-12 @Abhishek-kumar09 ... any takers?

**Comment by warunicorn19** [comment]
@leecalcote could I try this out?

**Comment by Chadha93** [comment]
Here you go @warunicorn19 :+1:

**Comment by warunicorn19** [comment]
Thanks @Chadha93

**Comment by warunicorn19** [comment]
Sorry to be a let down, but not being able to execute this. That's why unassigning. Also, the layout for patterns has changed, so this only needs to be executed in the application files and maybe filter? @Meghana-12 @Abhishek-kumar09 any takers?

**Comment by Abhishek-kumar09** [comment]
Oh that's okay @warunicorn19 
Can I give it a try?

**Comment by warunicorn19** [comment]
That would be great @Abhishek-kumar09 , 🙏 thanks
