### ISSUE TITLE
[UI] Connection Wizard: Change adapter logos

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3915]
#### Current Behavior
In `Meshery Adapters` step, currently, we use the same icon for all adapters.

#### Desired Behavior
We should be using the respective logos for each service mesh adapter.

#### Implementation
Follow the same strategy used in `Dashboard` component to render service mesh icons based on the name of adapter. If an adapter is unknown, use Meshery logo instead.

#### Acceptance Tests

- [ ] Respective service mesh icons are displayed for each adapter
- [ ] If an adapter is unknown, Meshery logo should be rendered instead

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik taking on this issue😃

**Comment by sudo-NithishKarthik** [comment]
Its all yours 🚀
