### ISSUE TITLE
[UI] Connection Wizard: Page layout shifts while hovering over carousel

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3916]
#### Current Behavior

https://user-images.githubusercontent.com/75248557/129845766-fa147736-4338-4db3-a9a5-ee86af27f6dd.mov

#### Desired Behavior
The shift in layout should not happen.

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by yagarwal1307** [comment]
I can pick this up if no one's working on this

**Comment by sayantan1413** [comment]
Yeah sure @yagarwal1307 go ahead!

**Comment by yagarwal1307** [comment]
In this issue it seems that I would have to set up grafana, kubernetes etc, which I dont have much idea of so far tbh and haven't even set them up. I couldn't even find a way to do it without them. So if someone can suggest a way to do it, that would be nice. Otherwise I think someone else who has set them up and has some idea about them would be able to solve the issue faster and therefore I would prefer being unassigned to the issue for now!

**Comment by sudo-NithishKarthik** [comment]
@yagarwal1307 , i think your problem is that you are not able to go to the 3rd step, is that right ?

**Comment by yagarwal1307** [comment]
@sudo-NithishKarthik yes. But if you are going to suggest enabling the next button just to fix the issue I guess I would still need to setup grafana to get that chip hovering on which is causing the issue. 
If you have some other suggestion or if I am wrong somewhere thoughts are welcome!

**Comment by sudo-NithishKarthik** [comment]
This issue is purely related to UI, doesn't matter if you have Grafana set up or not, you can just alter the code to make it display the chip, and debug.

**Comment by yagarwal1307** [comment]
hmmmm. Makes sense! Let me try doing it that way then! As I said if someone had grafana etc setup then he wouldnt have to make all those unnecessary ui changes and therefore I was saving myself from some extra efforts! XD But still let me try doing it that way!

**Comment by sudo-NithishKarthik** [comment]
Ahh, sure, it's up to you ✌🏽
