### ISSUE TITLE
[UI] Connection Wizard: Change Meshery logo color in slider

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3917]
#### Current Behavior
<img width="681" alt="Screen Shot 2021-08-17 at 10 35 46 PM" src="https://user-images.githubusercontent.com/75248557/129845961-705dd8dd-8f19-429f-afd2-9ed24ea4108f.png">

The teal colouring used for Meshery logo here does not look good.

#### Desired Behavior

The colour should be changed to ones in the [brand kit](layer5.io/brand)

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sayantan1413** [comment]
hey @sudo-NithishKarthik can I give this a try ?

**Comment by sudo-NithishKarthik** [comment]
Sure @sayantan1413 🎉

**Comment by sayantan1413** [comment]
Hey @sudo-NithishKarthik I think this issue is already fixed.

**Comment by sudo-NithishKarthik** [comment]
This occurs only in Safari @sayantan1413
