### ISSUE TITLE
[UI] Update the user on "Token" expire

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#3919]
#### Current Behavior
When tokens expire, we show things like “Unexpected error occurred” on the /performance page

#### Desired Behavior
The user needs to be informed that their token is expired and to log in again.

#### Screenshots/Logs
<img width="2520" alt="Screen Shot 2021-08-17 at 4 27 59 PM" src="https://user-images.githubusercontent.com/65453826/129847614-094dd5d2-7616-4413-95d1-591aefb14b4c.png">

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by yagarwal1307** [comment]
if no one's working on this one I can pick it up.

**Comment by sayantan1413** [comment]
Yeah sure @yagarwal1307 go ahead!

**Comment by yagarwal1307** [comment]
I am stuck on this issue because I could not reproduce the error!

**Comment by warunicorn19** [comment]
hey @yagarwal1307 any updates on this?

**Comment by yagarwal1307** [comment]
@warunicorn19 no i couldn't reproduce this error on my system. So I have no idea regarding this issue

**Comment by Chadha93** [comment]
> Hi @Chadha93 and @leecalcote I would like to take this up.

@RajGM are you able to reproduce this issue? What will be your approach for this issue?

**Comment by RajGM** [comment]
Hi @Chadha93 
So far I am unable to reproduce the issue but I am working on that.
There can be multiple ways to solve this but I am assuming that with each request we are sending the token to server with each request (private routes) and then on server side we are verifying the token.
So once the token expires while the user is on the /performance page I can redirect him to login page.
On the login page we can have a logic which check if the user is being redirected from performance page, if yes then after successful login we can redirect him to performance page.

**Comment by RajGM** [comment]
> Hi @Chadha93 So far I am unable to reproduce the issue but I am working on that. There can be multiple ways to solve this but I am assuming that with each request we are sending the token to server with each request (private routes) and then on server side we are verifying the token. So once the token expires while the user is on the /performance page I can redirect him to login page. On the login page we can have a logic which check if the user is being redirected from performance page, if yes then after successful login we can redirect him to performance page.

Hi @Chadha93 
What do you think about my approach?

**Comment by Chadha93** [comment]
// @piyushsingariya @warunicorn19 your thought on the above approach?

**Comment by piyushsingariya** [comment]
@RajGM nice approach. because it's a big UX change, we should discuss this over the Meshery Development call on Wednesday.

**Comment by RajGM** [comment]
ok @piyushsingariya 
Really excited to discuss this.

**Comment by navendu-pottekkat** [comment]
Related: https://github.com/meshery/meshery/pull/4956

**Comment by RajGM** [comment]
Hi @Chadha93 and @navendu-pottekkat 
I tried reproducing the issue by changing the cookie but it does not shows any error.
It just redirects me to the providers page.

**Comment by leecalcote** [comment]
Implemented by @MUzairS15

**Comment by ThePiyushAggarwal** [comment]
Shouldn't we close this issue?

**Comment by Ykumar1415** [comment]
I want to work on this issue can you assign this to me?

**Comment by Chadha93** [comment]
Thanks for volunteering @Ykumar1415, it's no more an issue. Feel free to take more issues.
