### ISSUE TITLE
[UI] [Performance] Remove overlay of cards

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#3920]
#### Current Behavior
In Meshery Performance, the cards are placed above another card.

#### Desired Behavior
Remove the overlay card and let's have the data on a single card itself.

#### Mockups
![WhatsApp Image 2021-08-18 at 12 36 15](https://user-images.githubusercontent.com/65453826/129853539-31df251f-edc6-4639-89a3-3b2e01626069.jpeg)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by mani9896** [comment]
@warunicorn19 Hey can i work on this issue ? new contributor here

**Comment by sayantan1413** [comment]
Yup sure @mani9896 go ahead 🎉🚀
