### ISSUE TITLE
[mesheryctl] add the ability to delete the filter from server

### ISSUE THREAD

**Issue by Shreyas220** [meshery/meshery#3929]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Desired Behavior

`mesheryctl filter delete` should be able to delete the filter from the server 

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
FYI - Current API reference - https://docs.meshery.io/reference/rest-apis#api-experimental-filter-get-handle-get-request-for-all-filters

**Comment by leecalcote** [comment]
@Shreyas220 Following up... has this been accomplished?

**Comment by Shreyas220** [comment]
from what i understand this is already been done 
i had to add the ability to delete a filter which already present [here](https://github.com/meshery/meshery/blob/1bf174bfc004b3f0d62c377374da240db55e61e9/handlers/meshery_filter_handler.go#L188)
u recommended that i take inspiration from application and pattern apis, after  looking i find that [DeleteMesheryFilterHandler](https://github.com/meshery/meshery/blob/1bf174bfc004b3f0d62c377374da240db55e61e9/handlers/meshery_filter_handler.go#L188)() is same as  [DeleteMesheryPatternHandler](https://github.com/meshery/meshery/blob/1bf174bfc004b3f0d62c377374da240db55e61e9/handlers/meshery_pattern_handler.go#L222)() and [DeleteMesheryApplicationHandler](https://github.com/meshery/meshery/blob/1bf174bfc004b3f0d62c377374da240db55e61e9/handlers/meshery_application_handler.go#L213) in pattern and application respectively 

please let me know if i have the wrong idea

**Comment by leecalcote** [comment]
@piyushsingariya will you offer us guidance here?

**Comment by piyushsingariya** [comment]
>  i had to add the ability to delete a filter which already present [here](https://github.com/meshery/meshery/blob/1bf174bfc004b3f0d62c377374da240db55e61e9/handlers/meshery_filter_handler.go#L188)

Yes, it is there, we have it already there. I think this issue was opened when I addressed it in a meeting about not having the ability to deploy and stop the deployment of filters. :thinking:

**Comment by Shreyas220** [comment]
so shall we close the issue ?

**Comment by piyushsingariya** [comment]
Yes we can close this, can you take out some time to open up an issue addressing the requirement of filter POST deploy and filter DELETE deploy?
