### ISSUE TITLE
[UI][Connection Wizard] Adapter card coincides with wrong adapter chip

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#3930]
#### Current Behavior
In the meshery adapters menu, the adapter on the cards coincide with wrong adapter chips.

#### Desired Behavior
The scroll should be set in such a way that the adapter on the card and chip are the same.

#### Screenshots/Logs

https://user-images.githubusercontent.com/53532328/129942798-4612954d-842a-49f1-b48e-10034ff0821c.mov

#### Environment

- Browser: Chrome, Safari 
- Host OS: Mac 
- Meshery Server Version: stable
- Meshery Client Version: stable
- Platform: Docker desktop

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sudo-NithishKarthik** [comment]
@sayantan1413 , any updates ?

**Comment by warunicorn19** [comment]
This issue has been fixed.
