### ISSUE TITLE
[Server] Multi-cluster Kubernetes: Contexts as system resources

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3932]
### Current Behavior
Contexts are treated as:
1. a single collection sourced from a single kubeconfig
1. being owned by a given user

### Desired Behavior
Contexts should be treated as:
1. individual resources
1. a system-wide setting, owned by a user, available to all.

See slide 10 of the Meshery Architecture deck for context.

### Implementation
1. Hash a combination of the server and cert data from kubeconfig to uniquely identify a context.
1. Provide CRUD operations for contexts.
1. The Connnection Wizard should not need to be updated and doesn't need to be concerned with advanced configuration of many contexts.

### Acceptance Tests

- [ ] Whether manually uploaded or read from file mount, contexts are treated idempotently.
- [ ] Users can manually uploaded any number of kubeconfigs and have unique contexts persisted by their chosen provider.
- [ ] Users can disconnect (delete) a context and have it not automatically rediscovered if that context is not available via file mount.
- [ ] Any loaded context is available to all users of that Meshery deployment.
- [ ] All contexts are shown to users irrespective of whether Meshery is able to connect to the representative K8s cluster (context chips have status).

### Future
1. Concerns of decommissioning users and resources that they own.
1. Concerns of authorization and sharing between users.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
_gasp_! Has it been this long?!

**Comment by utkarsh-pro** [comment]
Removing stale label. This is still very much active and in our roadmap...

**Comment by leecalcote** [comment]
@Revolyssup please confirm that each of the behaviors described in this issue have been completed.

**Comment by Revolyssup** [comment]
> @Revolyssup please confirm that each of the behaviors described in this issue have been completed.

Yes, we are at the desired behaviour.

**Comment by leecalcote** [comment]
Bug:
![Screen Shot 2022-04-10 at 1 03 14 PM](https://user-images.githubusercontent.com/7570704/162966599-60d52858-ae0c-4d94-ba90-fff60f49eef0.png)
