### ISSUE TITLE
[UI] Capture and Handle Expired Token

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3935]
#### Current Behavior
Users with expired tokens will see the following on the performance management page:

<img width="444" alt="Screen Shot 2021-08-18 at 6 49 50 PM" src="https://user-images.githubusercontent.com/7570704/129986368-885831d6-108f-436a-b7be-65e39c5fb47a.png">

#### Desired Behavior
Irrespective of the page, users should universally see the same message - a modal informing the user that they their session has expired and that they will be directed to login in 3... 2... 1..

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by yagarwal1307** [comment]
@leecalcote isn't this issue the same as #3919 ?

**Comment by leecalcote** [comment]
@14Richa I wonder if you have a perspective on how this should be addressed.

**Comment by 14Richa** [comment]
@leecalcote A universal modal regarding that the token has expired is the right way. Should we redirect them automatically or should we ask them to `login` again?

IMO we can have first have an alert/modal. Later we can redirect if required in a separate PR.

**Comment by leecalcote** [comment]
@14Richa, your iterative approach sounds real good. 👍

**Comment by leecalcote** [comment]
Setting UX aside, I'm curious for your thoughts how the approach to implementation.

**Comment by Anosh21** [comment]
Hey @leecalcote i would like to work on this issue , an you please assign it to me.

**Comment by leecalcote** [comment]
Sounds great, @Anosh21. Quick check: have you been able to setup your dev env for building and running Meshery?

**Comment by Anosh21** [comment]
@leecalcote no, I am facing some issues running it can you give me a guide/resource for it?

**Comment by Anosh21** [comment]
@leecalcote Yes I have setup meshery and it's running.

**Comment by leecalcote** [comment]
@Anosh21 excellent! Let's do this. :) I'm a bit tardy on seeing your reply. Will you have a look at this thread in Slack? https://meshery.slack.com/archives/C023QGMSH8D/p1641635118021600

**Comment by MUzairS15** [comment]
@leecalcote can you please assign me?

**Comment by Chadha93** [comment]
@leecalcote Are we good to go with this pr https://github.com/meshery/meshery/pull/4956 approved by @Abhishek-kumar09

**Comment by leecalcote** [comment]
@MUzairS15, help me understand what the difference between redirecting to `/user/login` and `/provider` is. If a token has expired, in concept the user should be directed to login again, and not necessarily have to choose their provider again given that they will have already made this choice.

I don't think that we have a system sophisticated enough for this nuance to matter, but will ask the question.

**Comment by leecalcote** [comment]
Thank you for prompting this review, @Chadha93

**Comment by MUzairS15** [comment]
@leecalcote,
 When the token has expired user is redirected to `/user/login`, which further redirects to cloud server `https://meshery.layer5.io/login?login_challenge=ada62597c6474a56b95ac1628c321249` this cloud server has `Access-Control-Allow-Origin` response header set to `*` i.e to allow requesting code from any origin to access the resource. But when this header is set to `*` (wildcard) it doesn't allow the use of credentials.

The incoming request from the client-side has credentials property set to `include` which is why the redirect to `/user/login` fails.

When we redirect to `/provider` there is no further redirection to any cloud server.
Since, we cannot change the cloud server response header to some set of allowed origins, the change in the PR is the only way.

**Comment by leecalcote** [comment]
Thank you, @MUzairS15. I appreciate this.

**Comment by MUzairS15** [comment]
https://github.com/meshery/meshery/pull/4956
// @leecalcote
