### ISSUE TITLE
[UI] User Prefs: Only display remote provider tab when user signs into a remote provider.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3936]
#### Current Behavior

This screenshot is of a user using the Local Provider (None). They should not see the Remote Provider tab.
<img width="1550" alt="Screen Shot 2021-08-18 at 7 30 22 PM" src="https://user-images.githubusercontent.com/7570704/129989268-e3caa15f-5c59-451c-a419-ae4d9e0b3c8d.png">

The labels on the tabs should be responsive and should not be cut off.

<img width="1186" alt="Screen Shot 2021-08-18 at 7 34 53 PM" src="https://user-images.githubusercontent.com/7570704/129989438-d303ee10-1d66-4539-a96a-29a60235c2c8.png">

#### Desired Behavior
In `/user/preferences`, the Remote Provider tab should only be shown when the user is connected to a Remote Provider.

#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.5.48

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@yagarwal1307 heads-up

**Comment by yagarwal1307** [comment]
sure @leecalcote. onto it!
