### ISSUE TITLE
[UI] Visual distinction in Meshery’s menu .

### ISSUE THREAD

**Issue by Krishna-Koustub** [meshery/meshery#3940]
#### Current Behavior
1. The current behavior of the meshery menu is lacking the distinction between the main topics and the sub topics present in the menu 

2.  There is "indentation issue "with respect to the menu when it changes after life cycle . 

3. When it comes to background of the sub topics below configuration, it can be of a lighter shade as the others are of the same.

![Screenshot (137)](https://user-images.githubusercontent.com/84068882/130040720-ee25dfa6-aa37-4ca5-aa92-3932d7de66dc.png)

#### Desired Behavior
 
1. There must be clear distinctions between the main menu and the sub menus .

2.  The error with the indentation should be changed "as expected to be in a row".

3.  Sub menus like Applications , Filter , Pattern mush have a lighter background and still continue with the hover effect .
  

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@Krishna-Koustub are you going to look into this one?

**Comment by Meghana-12** [comment]
Hi, I just wanted to know, Rn we only show it when hovered, right? Is there a reason for not showing the dropdown arrow in general?

**Comment by warunicorn19** [comment]
@Meghana-12 i dont think theres any particular reason🤔, but right now i think we're going to remove the dropdown arrow and make it extend when hovered on.

**Comment by Meghana-12** [comment]
It'll be better if the user knows if there are subdivisions or no right? 
something like in google drive: 
![Screenshot 2021-08-20 at 3 27 22 PM](https://user-images.githubusercontent.com/44519203/130216691-b6ab00ce-4bdd-49ee-8d95-7d7a7650ae8d.png)

> i think we're going to remove the dropdown arrow and make it extend on hover.

Oh, how does it work when there's complex nesting?

**Comment by warunicorn19** [comment]
That's something we could discuss in today's community call, why dont you put down in agenda today.

**Comment by Meghana-12** [comment]
> That's something we could discuss in today's community call, why dont you put down in agenda today.

Sure, will do that! :D

**Comment by warunicorn19** [comment]
@Krishna-Koustub any updates?

**Comment by Krishna-Koustub** [comment]
> @Krishna-Koustub any updates

Actually no because there was a screen crack in my pc so could not work once it s repaired i can , I am sorry for the delay but it is taking a lot of time for them to repair

**Comment by warunicorn19** [comment]
@Krishna-Koustub any updates on this?

**Comment by leecalcote** [comment]
Menu coloring has changed in the time that this issue has been opened. The submenus are now a different color.
