### ISSUE TITLE
[UI] User Prefs: Show some loader while remote provider tab fetches data

### ISSUE THREAD

**Issue by yagarwal1307** [meshery/meshery#3945]
#### Current Behavior
Currently while the remote provider tab fetches data nothing is rendered on the screen for that tab and causes a kind of blank screen for some time before the data is fetched and the component re rendered.

#### Desired Behavior
Before the data is fetched instead of rendering an empty screen show some kind of loader or placeholder.

#### Screenshots/Logs
Please refer to the following video to understand the issue

https://user-images.githubusercontent.com/49173018/130245299-04aa8de0-46e2-4f24-a537-d036cfdae7eb.mov

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by K-Kumar-01** [comment]
@warunicorn19 
Would like to take up this issue if still open.

**Comment by warunicorn19** [comment]
@K-Kumar-01 sure, go ahead!

**Comment by K-Kumar-01** [comment]
@warunicorn19 
I would like to know if there is any spinner or loader react component that is already created. I searched via keywords `spinner` & `Loader` but was unable to find any. It would be really helpful if you can clear whether there exists any such implementation

**Comment by sudo-NithishKarthik** [comment]
We do not have a custom spinner/loader as of now, we are using `CircularProgress` component from material-ui.

**Comment by K-Kumar-01** [comment]
@sudo-NithishKarthik 
I am thinking of using that to show the processing. Is it fine or shall I go with any other approach if you have in mind?

**Comment by sudo-NithishKarthik** [comment]
You can go ahead with using `CircularProgress` .
