### ISSUE TITLE
[Docs] Add dropdown arrows in docs Sidebar Menu

### ISSUE THREAD

**Issue by Meghana-12** [meshery/meshery#3946]
#### Current State
I think it'd be better to add dropdown arrows for Sidebar in https://docs.meshery.io/ too, like the one discussed for [ this issue](https://github.com/meshery/meshery/issues/3940). It's not clear which Menu items have submenus and which ones do not. 
![Screenshot 2021-08-21 at 1 50 41 PM](https://user-images.githubusercontent.com/44519203/130315702-b114d964-b39a-4d09-a3d1-d2cce2609456.png)
Here, the Menu item Contributing has sub-menu items, but the rest don't. But all look the same. 

#### Desired State

Have a clear distinction between the Menu items which have submenus and which don't. A dropdown arrow like the one below would make it clear. 

![Screenshot 2021-08-20 at 3 27 22 PM](https://user-images.githubusercontent.com/44519203/130315659-e4ab47f7-f5b5-4a59-9441-e585de73a05e.png)
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by NikhilSharma03** [comment]
Can I work on this?

**Comment by warunicorn19** [comment]
Sure @NikhilSharma03, that would be great! just to be clear we only want a dropdown arrow for `Contributing`, none of the others have a dropdown if I'm not wrong, please do check though😅.

**Comment by NikhilSharma03** [comment]
@warunicorn19 Just to get a clear understanding. The dropdown arrow is only needed at the `Contributing` tag i.e.

![Screenshot from 2021-08-21 19-25-57](https://user-images.githubusercontent.com/58226527/130324025-ad84ee96-f478-4f7a-a30c-7283b1a7add7.png)

**Comment by warunicorn19** [comment]
Yes. The others don't have a drop down, right?

**Comment by warunicorn19** [comment]
Also, let's go with a really tiny chevron so that it's doesn't mess with the design.

**Comment by NikhilSharma03** [comment]
> Also, let's go with a really tiny chevron so that it's doesn't mess with the design.

Oh, so the functionality is already in place. only the icon is needed right? Then I think it would be better to let a new contributor take this opportunity.

**Comment by harshit-dxt** [comment]
I would love to work on this. Current Progress: I got my repository setup, looking through the code base now.

**Comment by warunicorn19** [comment]
That great! Here you go @harshit-dxt

**Comment by warunicorn19** [comment]
@harshit-dxt might want to go through the [contributing to docs](https://docs.meshery.io/project/contributing-docs), to set up your environment

**Comment by SirZeck** [comment]
@harshit-dxt are you working on this? Seems inactive for quite long?

**Comment by iambami** [comment]
@navendu-pottekkat I'll work on it

**Comment by navendu-pottekkat** [comment]
@iambami Are you working on this issue? Are you facing any blockers?

**Comment by 14Richa** [comment]
Hey @navendu-pottekkat and @leecalcote , I would like to take this issue. Can you please assign it to me?

**Comment by warunicorn19** [comment]
Sure thing @14Richa, Thank you for taking a look.

**Comment by 14Richa** [comment]
Hey, I have tried some options regarding the dropdown icon. Attaching the screenshot.
Which of these do you think look better? Feel free to suggest other options.

**1. Dropdown arrow on the right**
![Screenshot from 2021-12-10 11-29-37](https://user-images.githubusercontent.com/41283476/145525688-ad531b7b-2793-4981-80f2-659282face17.png)
 
**2. Dropdown arrow on the left**
![Screenshot from 2021-12-10 11-31-46](https://user-images.githubusercontent.com/41283476/145525700-bf0940c2-d8fa-4826-bf1e-f176ac94e8c1.png)

**3. Right arrow on the right**
![Screenshot from 2021-12-10 11-34-34](https://user-images.githubusercontent.com/41283476/145525708-c9c11f29-b716-40b3-8678-947993b14924.png)

**Comment by warunicorn19** [comment]
@14Richa could you try finding one which is similar to the mock-up? If not then, let's go with the first one.

**Comment by 14Richa** [comment]
The above mock-up is actually a screenshot of google drive.

**Comment by warunicorn19** [comment]
Yes, i know. So we were thinking of something like that. A right chevron of sorts.
