### ISSUE TITLE
[chore] Proposal to setup Prettier as code formatter

### ISSUE THREAD

**Issue by CIPHERTron** [meshery/meshery#3952]
Currently, this codebase is using ES Lint for both linting & code formatting but people tend to use separate tools for these two jobs i.e. ES Lint for code listing & managing errors & Prettier for code formatting.

Prettier is a tool that automatically makes your code more readable and consistent with your project's style guide. It integrates with your editor, so your code is tidied up every time you save your changes.

#### References
https://prettier.io/

Why Prettier?
https://prettier.io/docs/en/why-prettier.html

How does it compare to ESLint/TSLint/stylelint, etc.?
https://prettier.io/docs/en/comparison.html#how-does-it-compare-to-eslinttslintstylelint-etc

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sudo-NithishKarthik** [comment]
@CIPHERTron , you can proceed with the implementation.

**Comment by CIPHERTron** [comment]
Thank you @sudo-NithishKarthik. I'm on it! 🚀

**Comment by CIPHERTron** [comment]
Heyy @sudo-NithishKarthik I'm so sorry for the inconvenience. Actually, I had opened this issue on meshery/meshery whereas I was planning to implement it in meshery/meshery 😅 
Really really sorry. Should I open the same issue in meshery/meshery?

**Comment by sudo-NithishKarthik** [comment]
Yes, please.
But wait for some time for people to express their views on it.

**Comment by sudo-NithishKarthik** [comment]
In case of Meshery UI, this is something that we have to do. So, if you are interested, do work on it, or add a `help-wanted` label to it.

**Comment by CIPHERTron** [comment]
> Yes, please.
> But wait for some time for people to express their views on it.

Sure thing!
