### ISSUE TITLE
[UI] Make the pod name and pod version in Control Plane Dashboard "pretty"

### ISSUE THREAD

**Issue by bariqhibat** [meshery/meshery#3955]
#### Current Behavior

The name of the control plane pods are not really pleasant. For example, `grafana-79adasdasd-aseasda`.
![image](https://user-images.githubusercontent.com/54849895/130347943-c41aa86f-bb5c-403c-8e29-1a13e12588de.png)

Some pod has "v" in front of its versions. Refer to pic above for non-"v" versioning pods.
![image](https://user-images.githubusercontent.com/54849895/130348003-caef5313-0846-4105-a5c4-7aebf25423f8.png)

#### Desired Behavior

There should be a way to show a "prettier" name for the pods. And also, for the version column, some version has "v" initially, some are not (refer to pic). It might be good to normalize this naming as well.

#### Implementation

Create a function to map this strings accordingly. 

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by bariqhibat** [comment]
Do you think this is needed? @sudo-NithishKarthik 
I've already created the functions if it is.

**Comment by warunicorn19** [comment]
Hey @bariqhibat, if you're ready with it can you put in a PR for it, then we could have a look.

**Comment by bariqhibat** [comment]
> Hey @bariqhibat, if you're ready with it can you put in a PR for it, then we could have a look.

Sure, just added it.

**Comment by sudo-NithishKarthik** [comment]
So, here are my thoughts, we can 

1. Display the information as it is
2. Prettify the information and display

In either of those cases, we should make it clear for the user what he is seeing, for instance, if we display it as it is, we should change the title to `Control Plane Pod Name` assuming we are showing the pod names, or, if we display the prettified data, we should make it clear by using an apt title or by any other means.
 
But for versioning, it is fine, we can remove the `v` ig.

**Comment by warunicorn19** [comment]
I sort of think that the 'v' looks nice, I get that it might be redundant by the fact that it's under a "version" column.

**Comment by warunicorn19** [comment]
The rest i do agree with nithish

**Comment by bariqhibat** [comment]
@warunicorn19 @sudo-NithishKarthik yeah that makes sense. Now, the question is, what view is the best for user to switch between the "detailed" and "prettied" version of the pod name? I personally think the default naming would be the "prettied" version, and if the user is more to the dev side, he can switch to the more nerdy naming.

**Comment by warunicorn19** [comment]
But it could go the other way around too🤔, like if the user needs the named to be prettied, then they can change it then. Something to think about ig.

**Comment by sayantan1413** [comment]
Yeah @bariqhibat I have a +1 with you.

**Comment by sudo-NithishKarthik** [comment]
Ok, let's discuss about this in any of the upcoming meetings then...

**Comment by warunicorn19** [comment]
Yup, meshery development call would be perfect.
