### ISSUE TITLE
[DOCS] Error codes in docs show up in random order

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#3966]
**Description**
The order of the error codes in docs.meshery.io seems to be different every time.

**Expected Behavior**
The order should remain the same.

<img width="336" alt="Screenshot 2021-08-21 at 7 17 01 PM" src="https://user-images.githubusercontent.com/64970095/130323796-9fcc8f8e-0d9d-4866-b883-2394e27dd67b.png">
Hey @leecalcote would it be a problem if this is not maintaining a proper order?

_Originally posted by @sayantan1413 in https://github.com/meshery/meshery/issues/3949#issuecomment-903118931_

**Comment by sayantan1413** [comment]
<img width="462" alt="Screenshot 2021-08-25 at 4 24 18 PM" src="https://user-images.githubusercontent.com/64970095/130778397-e76ff31b-8876-4acb-8543-fb5656f23ff1.png">

Hey @warunicorn19 I think the issue is solved right ?🤔

**Comment by warunicorn19** [comment]
seems to be fixed🤔, but how?

**Comment by sayantan1413** [comment]
Magic @warunicorn19 🦹‍♀️

**Comment by warunicorn19** [comment]
I would like to take credit because my PR was the last one merged for the 🤣😆.
