### ISSUE TITLE
[Docs] Missing docs for `mesheryctl system login` and `mesheryctl system logout`

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3970]
#### Current State

`mesheryctl system login` and `mesheryctl system logout` commands are missing entries in [Command Reference](https://docs.meshery.io/reference/mesheryctl) and individual pages as for other commands in the table.

#### Desired State

1. Add these commands to the docs.
2. Update these commands in the [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0).
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@navendu-pottekkat working on it😃.

**Comment by navendu-pottekkat** [comment]
@warunicorn19 Could you also add a guide with all the ways to authenticate mesheryctl? All the ways to get the token, where the token is fetched, why there is a need for authentication.

This is to be added to https://docs.meshery.io/guides#meshery-cli

Please track it with this issue as well.

**Comment by warunicorn19** [comment]
@navendu-pottekkat sure!

**Comment by warunicorn19** [comment]
hey @navendu-pottekkat, how about I create a different issue to track the authentication guide? It'll be easier to track that way.
