### ISSUE TITLE
[Docs] Create "Performance Management with Meshery" guide

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3972]
#### Current State
Users lack a holistic guide to use the performance management capabilities in Meshery.

This could be managed through the [UI](https://docs.meshery.io/guides/interpreting-performance-test-results), [CLI](https://docs.meshery.io/reference/mesheryctl/perf) and [GitHub Action](https://github.com/layer5io/meshery-smp-action).

#### Desired State
Create a new guide here: https://docs.meshery.io/guides

Add sections on performance management through UI, CLI as well as the GitHub action.

Refer: https://docs.meshery.io/guides/smi-conformance

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Anand-Theertha** [comment]
Hello @navendu-pottekkat , can you please assign me this issue?

**Comment by sayantan1413** [comment]
Here you go @Anand-Theertha 🚀

**Comment by navendu-pottekkat** [comment]
@Anand-Theertha Are you still working on this issue? I could take this up and get this done over the weekend.

**Comment by Anand-Theertha** [comment]
@navendu-pottekkat I'm still on it Navendu. I'll get it done.

**Comment by navendu-pottekkat** [comment]
Sure @Anand-Theertha . This would be a nice to have ASAP. We have been investing a lot on performance management and a lack of documentation really slows us down. Let me know if you need any help.

**Comment by Anand-Theertha** [comment]
Hello, sorry for the delay. Please find the pull request to this issue here - #4192
