### ISSUE TITLE
[mesheryctl] `utils` package unit testing

### ISSUE THREAD

**Issue by Shreyas220** [meshery/meshery#3982]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Desired Behavior

Required to enable unit testing support for mesheryctl `utils` package functions, to ensure the accuracy and robustness of each mesheryctl release, [here](https://github.com/meshery/meshery/tree/master/mesheryctl/pkg/utils)

#### Mesheryctl Unit Testing

-    Write tests using Golang’s standard library.
-    A combination of CodeCov and GitHub Actions are to be used as mainstays in the approach to unit testing - https://github.com/codecov/codecov-action.

#### Files to be covered 

- [ ] auth.go (Blakelist7 )
- [x] healthcheck.go
- [x] helpers.go (aayushmau5)
- [x] platform.go (krithikvaidya )
- [ ] script.go
- [x] sse-client.go (krithikvaidya )

---

#### Contributor Resources

   [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
   [Beginner's guide to contributing to Meshery and mesheryctl](https://www.youtube.com/watch?v=hh_kFLZx3G4&ab_channel=Layer5)
   [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
   [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.9jjevr1clxv0)
   [Layer5 Community Slack](https://layer5io.slack.com/ssb/redirect#/shared-invite/email)

**Comment by Shreyas220** [comment]
@aayushmau5  @Blakelist7 any update ?

**Comment by aayushmau5** [comment]
Making some progress on writing tests for `helpers.go`. I do have some doubts which I will query about in a little while(doing some research on them).

**Comment by aayushmau5** [comment]
Okay, so I'm having some doubts about testing certain function present in [`helpers.go`](https://github.com/meshery/meshery/blob/master/mesheryctl/pkg/utils/helpers.go) file.
- Some functions like [this](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L138) generate or are based on configs file. What strategy should I use to test them? (I have been thinking about generating some configs file locally and checking their content, but I'm not sure how this will work in case of automated tests)
- Some function like [this](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L161) generate random values every time they run. Should I test them? If so, how?
- Other than that, some functions [open a browser window](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L207), [work with docker compose file](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L280), [copy files](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L213), basically those that are a bit tricker to operate, how should I test? Should I even test them at all?

These are my doubts. Other than that, testing other "not so tricky" functions are on their way :)

**Comment by Shreyas220** [comment]
> Okay, so I'm having some doubts about testing certain function present in [`helpers.go`](https://github.com/meshery/meshery/blob/master/mesheryctl/pkg/utils/helpers.go) file.
> 
>     * Some functions like [this](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L138) generate or are based on configs file. What strategy should I use to test them? (I have been thinking about generating some configs file locally and checking their content, but I'm not sure how this will work in case of automated tests)
> 
not sure about this (@piyushsingariya what do you suggest?) 


>     * Some function like [this](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L161) generate random values every time they run. Should I test them? If so, how?
> 
No i don't think this need to tested 

>     * Other than that, some functions [open a browser window](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L207), [work with docker compose file](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L280), [copy files](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L213), basically those that are a bit tricker to operate, how should I test them? Should I even test them at all?
> 

i think we can avoid testing [navigate](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L207) function and for the other two maybe we can let the test pass if no errors are returned

**Comment by piyushsingariya** [comment]
> * Some functions like [this](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L138) generate or are based on configs file. What strategy should I use to test them? (I have been thinking about generating some configs file locally and checking their content, but I'm not sure how this will work in case of automated tests)

These functions can be tested by keeping config file in fixtures and then executing, and then conforming the backup file exists. one more step can be reading the files and matching the content



> * Some function like [this](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L161) generate random values every time they run. Should I test them? If so, how?

Functions like these have no point in testing but we need to add them to coverage, so test them like the string length should be equal to the arg passed, one test case is enough for such kind

> * Other than that, some functions [open a browser window](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L207), [work with docker compose file](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L280), [copy files](https://github.com/meshery/meshery/blob/7e41552b633a48738d3ba1dac9d6473ac00d22ca/mesheryctl/pkg/utils/helpers.go#L213), basically those that are a bit tricker to operate, how should I test them? Should I even test them at all?

Some can be tested as we didn't received any errors I mean if we can't confirm what happened we can definitely confirm that no errors actually occurred,
 
functions interacting with other softwares like docker, k8s comes under integration testing, in this case you can have a compose file in fixture and then execute and confirm no errors are received, one more step can be conforming if meshery is running on docker platform

Some functions are too out of scope(which I think are very few, countable I mean) for writing tests those can be skipped.

and do check if each function is being used everywhere or not, I mean there might be few functions which are not in use now and we can clean out the code.

**Comment by aayushmau5** [comment]
Got it. Thanks a lot @piyushsingariya @Shreyas220

**Comment by krithikvaidya** [comment]
Hey, I'd like to write some tests.. i'll start with platform.go and sse-client.go if that's okay

**Comment by Shreyas220** [comment]
sure @krithikvaidya go ahead :smile:

**Comment by piyushsingariya** [comment]
too many folks in the area, I'm loving it. Now let's see who will boost the code-coverage with highest percentage 😉 🚀

**Comment by piyushsingariya** [comment]
https://codecov.io/gh/meshery/meshery/tree/master/mesheryctl/pkg/utils Something that might help.

**Comment by leecalcote** [comment]
@Shreyas220 will you help drive to home?

**Comment by Shreyas220** [comment]
sure 

> @Shreyas220 will you help drive to home?

**Comment by leecalcote** [comment]
Thank you, @Shreyas220

**Comment by leecalcote** [comment]
@Shreyas220 help, help. 🙂
