### ISSUE TITLE
[meshkit] Meshkit Errors aren't being printed in the console.

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#3986]
#### Current Behavior

Meshkit errors aren't getting printed.
```
❯ ./mesheryctl system start -p invalid
Error: 
Usage:
  mesheryctl system start [flags]

Flags:
  -h, --help              help for start
  -p, --platform string   platform to deploy Meshery to.
      --reset             (optional) reset Meshery's configuration file to default settings.
      --skip-update       (optional) skip checking for new Meshery's container images.

```

#### Expected Behavior

We gotta do something about this. as you can read above there's no error or in other words it's missing!

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by mgfeller** [comment]
Adding the error code as well would allow users to find the error details in the error reference.
Adding `LongDescription` might also be helpful, or even necessary. There is at least one case afaics where `LongDescription` of a meshkit error contains the string of another meshkit error:

![image](https://user-images.githubusercontent.com/1214008/131213530-00935a96-0534-4d63-91f9-dd600b321211.png)

```
func ErrHealthCheckFailed(err error) error {
	return errors.New(ErrHealthCheckFailedCode, errors.Alert, []string{"Health checks failed"}, []string{err.Error()}, []string{}, []string{})
}
```

**Comment by piyushsingariya** [comment]
Cool, Thanks for the help @mgfeller. This needs to be implemented across all the files. I'm closing this issue now.

**Comment by mgfeller** [comment]
@piyushsingariya 

> Cool, Thanks for the help @mgfeller. This needs to be implemented across all the files. I'm closing this issue now.

:smile: not quite sure what you mean, though, I think `func (e *Error) Error() string`  in `meshkit` should be adjusted...

**Comment by piyushsingariya** [comment]
:sweat_smile: @mgfeller I actually meant that in all places we have added errors to short-description, so as you explained above, we need to actually add them to the long-description, then they'll work properly.

I tried fixing that in one of my PRs and now it's working as supposed. :smile_cat:

**Comment by piyushsingariya** [comment]
> The reason is that `LongDescription` is used to stringify error ( `func (e *Error) Error() string { return strings.Join(e.LongDescription[:], ".") }` in meshkit), but `LongDescription` is empty.
> Should `ShortDescription` be used instead?

LongDescription makes more sense to be used as error.

**Comment by piyushsingariya** [comment]
> Adding the error code as well would allow users to find the error details in the error reference.
> Adding `LongDescription` might also be helpful, or even necessary. There is at least one case afaics where `LongDescription` of a meshkit error contains the string of another meshkit error:
> 
> ![image](https://user-images.githubusercontent.com/1214008/131213530-00935a96-0534-4d63-91f9-dd600b321211.png)
> 
> ```
> func ErrHealthCheckFailed(err error) error {
> 	return errors.New(ErrHealthCheckFailedCode, errors.Alert, []string{"Health checks failed"}, []string{err.Error()}, []string{}, []string{})
> }
> ```

I'm sorry, I think I misunderstood your comment here. Are you saying to add the ErrorCode with the Error itself?(so that it would be printed in terminal)

**Comment by mgfeller** [comment]
> LongDescription makes more sense to be used as error.

Referring to https://docs.meshery.io/reference/error-codes the majority of errors that have some details have more often short description than long description. So IMHO it makes sense that this is included in the stringified version of an error.

> I'm sorry, I think I misunderstood your comment here. Are you saying to add the ErrorCode with the Error itself?(so that it would be printed in terminal)

What I was trying to say is we should consider to change the function in meshkit that stringifies the error to possibly include the error code, not that `ErrorCode` should be added to any error detail (`ShortDescription` or `LongDescription` ...). 

E.g. 
```
func (e *Error) Error() string {
	return fmt.Sprintf("%s: %s (%s)" , e.Code, strings.Join(e.ShortDescription[:], "."), strings.Join(e.LongDescription[:], "."))
}
```
Hope it is clearer now.

Empty `()` if `LongDescription` is empty might be a bit confusing, so the specific format would need some checks and though.

What do you think?

**Comment by piyushsingariya** [comment]
> E.g.
> 
> ```
> func (e *Error) Error() string {
> 	return fmt.Sprintf("%s: %s (%s)" , e.Code, strings.Join(e.ShortDescription[:], "."), strings.Join(e.LongDescription[:], "."))
> }
> ```
> 
> What do you think?

yup, this is good.

**Comment by mgfeller** [comment]
Created an issue for this: https://github.com/meshery/meshkit/issues/102
