### ISSUE TITLE
[mesheryctl] Increase code coverage in `mesheryctl` upto 80%

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#3988]
#### Current Behavior

The current code coverage is less than 30% check here https://app.codecov.io/gh/meshery/meshery

#### Expected Behavior

Increase this code coverage up to 80%, this time!

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by shikharvashistha** [comment]
Hey @piyushsingariya I would like to work on this.

**Comment by shikharvashistha** [comment]
### Current log for unit testing
?   	github.com/layer5io/meshery/cmd	[no test files]
?   	github.com/layer5io/meshery/handlers	[no test files]
?   	github.com/layer5io/meshery/helpers	[no test files]
?   	github.com/layer5io/meshery/internal/channels	[no test files]
?   	github.com/layer5io/meshery/internal/graphql	[no test files]
?   	github.com/layer5io/meshery/internal/graphql/generated	[no test files]
?   	github.com/layer5io/meshery/internal/graphql/model	[no test files]
?   	github.com/layer5io/meshery/internal/graphql/resolver	[no test files]
?   	github.com/layer5io/meshery/internal/sql	[no test files]
ok  	github.com/layer5io/meshery/internal/store	0.028s	coverage: 94.1% of statements
?   	github.com/layer5io/meshery/mesheryctl/cmd/mesheryctl	[no test files]
?   	github.com/layer5io/meshery/mesheryctl/internal/cli/root	[no test files]
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/app	0.405s	coverage: 48.8% of statements
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/config	0.034s	coverage: 0.6% of statements
?   	github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants	[no test files]
?   	github.com/layer5io/meshery/mesheryctl/internal/cli/root/experimental	[no test files]
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/filter	0.399s	coverage: 26.5% of statements
?   	github.com/layer5io/meshery/mesheryctl/internal/cli/root/mesh	[no test files]
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/pattern	0.405s	coverage: 47.9% of statements
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/perf	0.525s
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/system	5.230s	coverage: 9.2% of statements
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/system/context	0.339s	coverage: 58.6% of statements
?   	github.com/layer5io/meshery/mesheryctl/pkg/constants	[no test files]
ok  	github.com/layer5io/meshery/mesheryctl/pkg/utils	0.746s	coverage: 12.4% of statements
?   	github.com/layer5io/meshery/meshes	[no test files]
?   	github.com/layer5io/meshery/models	[no test files]
?   	github.com/layer5io/meshery/models/pattern/core	[no test files]
?   	github.com/layer5io/meshery/models/pattern/patterns	[no test files]
?   	github.com/layer5io/meshery/models/pattern/patterns/application	[no test files]
?   	github.com/layer5io/meshery/models/pattern/patterns/application/argo/v1alpha1	[no test files]
?   	github.com/layer5io/meshery/models/pattern/patterns/k8s/service	[no test files]
ok  	github.com/layer5io/meshery/models/pattern/planner	0.362s	coverage: 42.5% of statements
?   	github.com/layer5io/meshery/models/pattern/resource/selector	[no test files]
ok  	github.com/layer5io/meshery/models/pattern/stages	0.349s	coverage: 25.1% of statements
?   	github.com/layer5io/meshery/models/pattern/utils	[no test files]
?   	github.com/layer5io/meshery/models/walker	[no test files]
?   	github.com/layer5io/meshery/router	[no test files]

**Comment by shikharvashistha** [comment]
### Current log for Integration testing
?   	github.com/layer5io/meshery/cmd	[no test files]
?   	github.com/layer5io/meshery/handlers	[no test files]
?   	github.com/layer5io/meshery/helpers	[no test files]
?   	github.com/layer5io/meshery/internal/channels	[no test files]
?   	github.com/layer5io/meshery/internal/graphql	[no test files]
?   	github.com/layer5io/meshery/internal/graphql/generated	[no test files]
?   	github.com/layer5io/meshery/internal/graphql/model	[no test files]
?   	github.com/layer5io/meshery/internal/graphql/resolver	[no test files]
?   	github.com/layer5io/meshery/internal/sql	[no test files]
ok  	github.com/layer5io/meshery/internal/store	0.045s	coverage: 0.0% of statements [no tests to run]
?   	github.com/layer5io/meshery/mesheryctl/cmd/mesheryctl	[no test files]
?   	github.com/layer5io/meshery/mesheryctl/internal/cli/root	[no test files]
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/app	0.356s	coverage: 2.8% of statements [no tests to run]
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/config	0.028s	coverage: 0.0% of statements [no tests to run]
?   	github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants	[no test files]
?   	github.com/layer5io/meshery/mesheryctl/internal/cli/root/experimental	[no test files]
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/filter	0.402s	coverage: 2.6% of statements [no tests to run]
?   	github.com/layer5io/meshery/mesheryctl/internal/cli/root/mesh	[no test files]
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/pattern	0.392s	coverage: 3.0% of statements [no tests to run]
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/perf	0.372s	coverage: 3.2% of statements [no tests to run]
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/system	599.235s	coverage: 34.3% of statements
ok  	github.com/layer5io/meshery/mesheryctl/internal/cli/root/system/context	0.352s	coverage: 6.6% of statements [no tests to run]
?   	github.com/layer5io/meshery/mesheryctl/pkg/constants	[no test files]
ok  	github.com/layer5io/meshery/mesheryctl/pkg/utils	0.363s	coverage: 0.0% of statements [no tests to run]
?   	github.com/layer5io/meshery/meshes	[no test files]
?   	github.com/layer5io/meshery/models	[no test files]
?   	github.com/layer5io/meshery/models/pattern/core	[no test files]
?   	github.com/layer5io/meshery/models/pattern/patterns	[no test files]
?   	github.com/layer5io/meshery/models/pattern/patterns/application	[no test files]
?   	github.com/layer5io/meshery/models/pattern/patterns/application/argo/v1alpha1	[no test files]
?   	github.com/layer5io/meshery/models/pattern/patterns/k8s/service	[no test files]
ok  	github.com/layer5io/meshery/models/pattern/planner	0.440s	coverage: 0.0% of statements [no tests to run]
?   	github.com/layer5io/meshery/models/pattern/resource/selector	[no test files]
ok  	github.com/layer5io/meshery/models/pattern/stages	0.414s	coverage: 1.1% of statements [no tests to run]
?   	github.com/layer5io/meshery/models/pattern/utils	[no test files]
?   	github.com/layer5io/meshery/models/walker	[no test files]
?   	github.com/layer5io/meshery/router	[no test files]

**Comment by leecalcote** [comment]
Hi @shikharvashistha, checking in on the this issue. Do you have progress to report, by chance?

**Comment by shikharvashistha** [comment]
> Hi @shikharvashistha, checking in on the this issue. Do you have progress to report, by chance?

Thanks for asking @leecalcote . As of now I don't have any progress on this issue, but would like to continue with it if possible which I was unable to due to my offline exams schedule.

**Comment by Kumaravinash9** [comment]
Hi @leecalcote @piyushsingariya I would like to work on this issue. If anyone  else is working, I would like to collaborate with them. Thanks

**Comment by piyushsingariya** [comment]
assigning you @Kumaravinash9

**Comment by pk-218** [comment]
@piyushsingariya @alphaX86 can I assist with this issue? I can start with `mesheryctl filter` subcommands.

**Comment by leecalcote** [comment]
@nishi6verma @pk-218, this is great. // @alphaX86 @hexxdump

**Comment by Swathi-L** [comment]
Hi @nishi6verma @pk-218, are you guys taking a look at it

**Comment by nishi6verma** [comment]
Thanks sir.

**Comment by nishi6verma** [comment]
Yes, I am looking on it.

**Comment by Aisuko** [comment]
This is not a good news. Maybe I can help on this one.

**Comment by Aisuko** [comment]
#7631

**Comment by leecalcote** [comment]
Making good progress here, @Aisuko 👏

**Comment by Aisuko** [comment]
@Freedisch

**Comment by Freedisch** [comment]
@Aisuko , got it. For the outdated test cases in reference to this issue [7821](https://github.com/meshery/meshery/issues/7821) u created

**Comment by Aisuko** [comment]
I'd like to suggest you split test cases into several PRs, it will be more effective for us merging them.
