### ISSUE TITLE
[CI] Augment existing build workflows to affix appropriate labels to PRs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3992]
**Description:**
Meshery release notes are auto-generated by Release Drafter. Release Drafter uses PR labels to create release notes and place changelogs into specific categories (e.g. Features, Maintenance, Docs...)

Contributors can manually affix labels to PRs. These labels provide information to the release notes drafter, so that each item in the changelog is categorized under it appropriate section.

**Request:**
Augment existing build workflows to affix appropriate labels to PRs based on changes to files in specific paths (e.g. `file-path: /docs` --> label: `area/docs`.

**Example of Release Notes being categorized:**

<img width="599" alt="Screen Shot 2021-08-11 at 9 00 26 AM" src="https://user-images.githubusercontent.com/7570704/129042767-8b0aed66-c2b4-419a-8793-b7dd89fd5938.png">

_Originally posted by @leecalcote in https://github.com/meshery/meshery/issues/3851#issuecomment-897140731_

**Comment by leecalcote** [comment]
@amino19 this is a great opportunity to welcome and collaborate with a new contributor. @asubedy have you joined the Meshery community Slack workspace? If not, please do: http://slack.meshery.io. Perhaps, you and @amino19 can collaborate on this issue.

Let me know how you guys would like to proceed. There are many issues in need of assistance.

**Comment by amino19** [comment]
> I would like to give this issue a try. Thank you

Wanna take this issue? :slightly_smiling_face:

**Comment by asubedy** [comment]
Yes I would like to work on it. But I will be needing a lot of guidance for which I will definitely connect with @amino19 on slack.

Thank you @afzal442 and @leecalcote .

**Comment by amino19** [comment]
@asubedy : Yep for sure! Here you go. :rocket: 

@afzal442 : Thanks, hope you'll stay tuned here...

**Comment by SirZeck** [comment]
@asubedy any update on your work?
