### ISSUE TITLE
[Docs] Missing docs for running meshery on eks

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#3994]
#### Current State
There is no content in https://docs.meshery.io/installation/platforms/eks.

#### Desired State
It should guide how to install Meshery on an eks cluster.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
@DelusionalOptimist the links will also change right? For eg: Instead of Azure, AWS?

**Comment by alphaX86** [comment]
I finished the YAML refactor just now and I started to look this one

**Comment by DelusionalOptimist** [comment]
> @DelusionalOptimist the links will also change right? For eg: Instead of Azure, AWS?

Yes, they would.

**Comment by alphaX86** [comment]
Copy 👍
