### ISSUE TITLE
[Docs] Broken links of sample applications 

### ISSUE THREAD

**Issue by afzal442** [meshery/meshery#4010]
#### Current State

There are a few links that are broken due to current changes in the docs on [support for service-mesh-page](https://docs.meshery.io/service-meshes#support-for-service-meshes)

e.g. https://docs.meshery.io/service-meshes/adapters/istio
<img width="346" alt="c2" src="https://user-images.githubusercontent.com/11625672/131211544-96020212-bf37-4958-9aff-a2b0544ad0e1.PNG">

#### Desired State
You can find the links from here https://docs.meshery.io/guides/sample-apps

Add the correct links.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by iambami** [comment]
I will take this issue

**Comment by afzal442** [comment]
Sure @iambami, go ahead! thanks.

**Comment by benedictusdps** [comment]
Can I take this issue?
