### ISSUE TITLE
[UI] The SMP vertical divider is not aligned properly

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#4022]
#### Current Behavior

https://user-images.githubusercontent.com/48255244/131247409-d7006faa-9035-4a77-973a-cf1c6b9d5b34.mp4

#### Desired Behavior

It should behave responsively

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
@mani9896 would you like to fix it?

**Comment by Chadha93** [comment]
> @mani9896 would you like to fix it?
https://github.com/meshery/meshery/pull/3979

**Comment by Hardikag17** [comment]
@Abhishek-kumar09 @Chadha93 I would like to fix this issue!

**Comment by warunicorn19** [comment]
Go for it! @Hardikag17
