### ISSUE TITLE
[CI] Github Action bot should trigger on issue/remind label in PR

### ISSUE THREAD

**Issue by sayantan1413** [meshery/meshery#4034]
#### Current Behavior

The Meshery repository have a label commenter workflow but it does not trigger the github action bot when an issue/remind or issue/dco is marked.

#### Desired Behavior

The github action bot should trigger when an issue/remind or issue/dco label is marked in the PR

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by piyushsingariya** [comment]
@sayantan1413 you're diving deep in the CI stuff these days! 😀

**Comment by sayantan1413** [comment]
Yeah @piyushsingariya just got some interest in the CI stuffs so exploring it a bit.
