### ISSUE TITLE
[CI/DevOps] container image for mesheryctl

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#4050]
#### Current Behavior
We don't ship `mesheryctl` binary in a docker image.

#### Desired Behavior
There should be a docker image which ships with `mesheryctl` as the entrypoint. It would allow users to run commands by simply fetching the container image and executing commands using docker.
This also makes it easy to integrate Meshery in their pipelines.
For instance, something like would execute the `mesheryctl version` command:
```
docker run layer5io/mesheryctl:stable-latest version
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by suhaniii** [comment]
@DelusionalOptimist  Do we need to create a new image or add this to existing?

**Comment by s1ntaxe770r** [comment]
we need a new image

**Comment by DelusionalOptimist** [comment]
Yes @suhaniii, a new distroless image for `mesheryctl`. Different from existing meshery server image.

**Comment by suhaniii** [comment]
@DelusionalOptimist @s1ntaxe770r   Can we place `Dockerfile` under `meshery/mesheryctl/` ?
Also, Can you provide link to any existing similar process(if any) which can be referred for this task?

**Comment by s1ntaxe770r** [comment]
+1 on putting the Dockerfile under `meshery/mesheryctl` , while i don't have a link to an existing dockerfile here are some steps i would follow 
- grab a release of mesheryctl from https://github.com/meshery/meshery/releases/ using curl or get 
- unpack the zip file using tar or unzip and move it the users path 
- (additional but not high priority) have the user be able to specify the release of mesheryctl the want to run you could achieve this by using [docker args](https://docs.docker.com/engine/reference/builder/#arg)
@DelusionalOptimist  thoughts ?

**Comment by suhaniii** [comment]
@s1ntaxe770r  @DelusionalOptimist  Is there better way to fetch latest release in Dockerfile when release version not specified?

`https://github.com/meshery/meshery/releases/download/v0.5.56/mesheryctl_0.5.56_Linux_x86_64.zip`

**Comment by DelusionalOptimist** [comment]
@suhaniii I think it won't be ideal to fetch pre-released mesheryctl binaries. We should build it when we're building the docker image.

For e.g.:
Take the meshery image. We build meshery server's binary here: https://github.com/meshery/meshery/blob/9212aad73d840418fce17c0b0e80cb5ab5f20c83/Dockerfile#L10
So when you would run `docker build .` it would actually checkout the code in the current working directory and start building the image in steps. One of the steps would be building the binary.
The command for building mesheryctl binary: https://github.com/meshery/meshery/blob/986937b1a897ca4d7af2159ba22a3e14ff926e89/mesheryctl/Makefile#L7-L8.
Since this binary would be residing in a unix based docker container for sure. We don't need to take care of building it for platforms other than that.

We would be finally building the mesheryctl docker image in our build and release workflows. So it would look something like [this](https://github.com/meshery/meshery/blob/9212aad73d840418fce17c0b0e80cb5ab5f20c83/.github/workflows/build-and-release.yml#L24-L28). For specifying version, we would be using build args, similar to how we use this.

We'll also need to think about network here since mesheryctl (client) would need to talk with meshery (server). But let's talk about that once we have a docker image with mesheryctl. To test initially, the `version` command working and showing mesheryctl binary's version would be good. :slightly_smiling_face:.
