### ISSUE TITLE
[Build Error] Bitcask: panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4074]
#### Current Behavior
Unable to build Meshery Server.

#### Screenshots/Logs
```
WARN[0000] upgrading db version, might take some time....
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
git.mills.io/prologic/bitcask/scripts/migrations.read(0xc000115070, 0x7b226b38d6b2e3d7, 0xa4, 0x636f7465, 0x7b226b3873436f6e, 0x0, 0x0, 0x0)
	/Users/lee/code/go/pkg/mod/git.mills.io/prologic/bitcask@v0.3.14/scripts/migrations/v0_to_v1.go:147 +0x45
git.mills.io/prologic/bitcask/scripts/migrations.getSingleEntry(0xc000115070, 0x98, 0x20, 0x20, 0x20, 0x0, 0x0)
	/Users/lee/code/go/pkg/mod/git.mills.io/prologic/bitcask@v0.3.14/scripts/migrations/v0_to_v1.go:130 +0xbc
git.mills.io/prologic/bitcask/scripts/migrations.apply(0xc00017e5d0, 0x1d, 0xc00017e6c0, 0x30, 0x100000, 0x30, 0x0)
	/Users/lee/code/go/pkg/mod/git.mills.io/prologic/bitcask@v0.3.14/scripts/migrations/v0_to_v1.go:58 +0x13b
git.mills.io/prologic/bitcask/scripts/migrations.ApplyV0ToV1(0xc00017e5d0, 0x1d, 0x100000, 0x0, 0x0)
	/Users/lee/code/go/pkg/mod/git.mills.io/prologic/bitcask@v0.3.14/scripts/migrations/v0_to_v1.go:29 +0xec
git.mills.io/prologic/bitcask.checkAndUpgrade(0xc00017e630, 0xc00017e5d0, 0x29, 0x0, 0x0)
	/Users/lee/code/go/pkg/mod/git.mills.io/prologic/bitcask@v0.3.14/bitcask.go:940 +0xea
git.mills.io/prologic/bitcask.Open(0xc000342920, 0x1d, 0xc000470340, 0x2, 0x2, 0x0, 0xc0006c1c20, 0xc0006c1c20)
	/Users/lee/code/go/pkg/mod/git.mills.io/prologic/bitcask@v0.3.14/bitcask.go:873 +0x13b
github.com/layer5io/meshery/models.NewBitCaskPreferencePersister(0xc00012c9a0, 0x1a, 0x10, 0xc00012c9a0, 0x1a)
	/Users/lee/code/meshery/models/preference_bitcask_persister.go:36 +0x17d
main.main()
	/Users/lee/code/meshery/cmd/main.go:189 +0x172f
```

#### Environment

- **Host OS:** Mac

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@mgfeller we recently overcame an issue with bitcask. Is this related, do you think? // @DelusionalOptimist @utkarsh-pro

**Comment by mgfeller** [comment]
@leecalcote we updated to the latest version before version 1 and had an issue because we used an API call that became private (rightly so). Which version of bitcask started to auto migrate to v1 data format I have not looked into. There might be a bug there, your db might be corrupt, or the db might contain some data stored as a slice of something that is too long, or something else.

Does this happen when you build, or run the server? or does build run the server as part of a test?

Is `make docker` the correct build command?

**Comment by leecalcote** [comment]
@mgfeller thank you for this. This was happening with `make run-local` and `make run-fast`. I was able to build with `make docker`, which was slight hinderance given the additional build time.

You're right that a form of database corruption seemed to be occurring. After executing a `rm -rf ~/.meshery/config/db/`, I'm now able to successfully build locally. Thank you for examining this issue. I'll close it out now and add the troubleshooting step of deleting the database as a troubleshooting step in the Contributing guides.
