### ISSUE TITLE
[Enhancement] Split Nighthawk out of meshery docker image

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#4075]
#### Current Behavior
Nighthawk's load generation services are currently present in meshery's docker image. This is not good because:
* This limits us from exposing many advanced Nighthawk features.
* Bloats the Meshery image and makes it too heavy.
* Slightly affects the performance of both the tools.

#### Desired Behavior
Nighthawk should run as a separate container outside of Meshery's container. It should either be in the Kubernetes cluster or a docker container depending upon if Meshery is connected to a cluster or not.
This should be done by using `GetNighthawk` as a golang wrapper around Nighthawk's interface.

An outcome of this would also be opening up the scope of supporting distributed load generation with horizontally scaled Nighthawk deployments. :muscle:

**Comment by leecalcote** [comment]
We're making some good progress. @Revolyssup will ensure that the adapter (Meshery-perf) is in a building state. We're ready to move forward with defining perf test operations next, @gyohuangxin
