### ISSUE TITLE
[mesheryctl] enhance `mesh` subcommand flags

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#4076]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
* You need to specify port number while specifying the adapter name.
* It is not clear what would we specify as the adapter name. Is that the container instance name or the container image name?
* Usage example should cover us (it should be actually helpful keeping in mind the case user is unfamiliar) 

#### Desired Behaviour
* Remove dependency on adapter's port number.
* Use the adapter name for specifying the adapter.
* Improve the usage example.
`mesheryctl mesh validate -s smi -a meshery-osm:10009 -t <path-to-token>`

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by s1ntaxe770r** [comment]
@DelusionalOptimist  still working on this?

**Comment by DelusionalOptimist** [comment]
@s1ntaxe770r go ahead :+1:

**Comment by DelusionalOptimist** [comment]
@s1ntaxe770r checking in. Any problems here? Let's get this done by this week? (before the community call)
