### ISSUE TITLE
[UI] Performance Graphs

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4077]
#### Current Behavior
When Two or more performance graphs are compared, the text around the chart goes missing.

#### Expected Behavior
All the data should be visible.

#### Screenshots/Logs
<img width="1440" alt="Screenshot 2021-09-02 at 9 27 32 PM" src="https://user-images.githubusercontent.com/53532328/131877267-4d217d8f-a202-4b9c-973e-081de8474c6e.png">

#### Environment

- **Host OS:** Mac
- **Platform:** Docker
- **Meshery Server Version:** stable
- **Meshery Client Version:** stable
---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by veerreshr** [comment]
Hey could I have a look at this? as I am also working on a similar issue ?

**Comment by warunicorn19** [comment]
For sure!

**Comment by veerreshr** [comment]
Could someone help me?, been trying from past 4 hrs . I'm able to display the data ,but it's only showing up when I close the dialog. I'm attaching a slow motion video 🥲 for reference
(P.s. Ignore the accordion, which I added recently)

https://user-images.githubusercontent.com/59141533/131929179-3da2b2d6-b659-4a92-a9d1-301c6bc801c0.mp4

**Comment by K-Kumar-01** [comment]
@warunicorn19 
I am not seeing any activity on the issue from past 7 days. If the issue is still open, can I take it up?

**Comment by veerreshr** [comment]
I am having hard time figuring this out, I am only able to manage to get to previous changes I made (this doesn't include new table like structure)

https://user-images.githubusercontent.com/59141533/131409902-bd099317-2c33-4ba7-ad22-611e6020386d.mov

Mentioned in https://github.com/meshery/meshery/pull/4041
May be also assgin it to @K-Kumar-01 , so he can try

**Comment by warunicorn19** [comment]
A collaborative effort is always welcomed, good luck guys👍😄.

**Comment by veerreshr** [comment]
I think https://github.com/meshery/meshery/pull/4041#event-5280579864 solves this issue

**Comment by K-Kumar-01** [comment]
@veerreshr I apologise for late reply. Were you able to solve the issue? I am seeing a comment that you have mentioned so a little confusion here.

**Comment by veerreshr** [comment]
No, it lead to some other issue , please continue trying

**Comment by K-Kumar-01** [comment]
@warunicorn19 Can you please unassign me? I don't think I will be able to look at the issue due to some commitments. I apologize for the inconvenience caused.

**Comment by warunicorn19** [comment]
@K-Kumar-01 yeah, no problem. @utkarsh-pro your recent PR fixes this issue too right? Then we can close this issue.
