### ISSUE TITLE
Enforce es-lint in  UI component files

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#4078]
#### Current Behavior
Few files having the eslint issues which will cause an issue to pass the npm lint check at the time of commit

#### Desired Behavior
Enforce an eslint on that files

#### Files:
1.components/PrometheusComponent
2.MesheryAdapterPlayComponent
3. components/GrafanaComponent
4. ConnectionWizard/helpers/mesheryOperator
5. ConnectionWizard/Screens/ServiceMeshScreen
6. ConnectionWizard/Screens/MetricsScreen

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by K-Kumar-01** [comment]
@Chadha93 
I would like to work on this issue. Can this be assigned to me?

**Comment by warunicorn19** [comment]
sure @K-Kumar-01
