### ISSUE TITLE
[UI] use createTheme instead of createMuiTheme

### ISSUE THREAD

**Issue by K-Kumar-01** [meshery/meshery#4087]
#### Current Behavior

When `make run-ui-dev` is run, a log appears stating `Material-UI: the createMuiTheme function was renamed to createTheme.`

Below is an attached screenshot.

![Screenshot from 2021-09-04 20-36-14](https://user-images.githubusercontent.com/59891164/132099371-05995a24-f664-4b53-b568-e417d97b526e.png)

#### Desired Behavior

No such log should appear

#### Implementation

import and use `createTheme` instead of `createMuiTheme`.

Some [information](https://stackoverflow.com/questions/68543960/react-material-ui-core-v4-11-0-the-createmuitheme-function-was-renamed-to) regarding the log.
From above, it can be assumed that both functions are currently acceptable. However, there is an unnecessary log that appears which can be prevented.

#### Would you like to work on the issue?
Yes
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sudhay23** [comment]
Hello, Is this issue open for contribution? If so can I work on it?

**Comment by K-Kumar-01** [comment]
@sudhay23 Actually, I made the changes in a branch. I was not able to update the issue context as I was out of the station for the past 2 days. I apologize for the inconvenience caused due to this.
