### ISSUE TITLE
[UI] refactor: codebase

### ISSUE THREAD

**Issue by K-Kumar-01** [meshery/meshery#4088]
#### Description
Currently, the codebase contains many instances of commented-out code. Some of them are:
- components/CustomToolbarSelect.js
- components/DashboardComponent.js
- components/GrafanaCharts.js
- components/GrafanaCustomGaugeChart.js
- components/GrafanaDateRangePicker.js

The commented-out code may not be useful to us so I would propose the removal of such instances.

#### Wil you like to work on the issue?
Yes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@K-Kumar-01 if you're planning on moving forward with this, I propose we should discuss this in a call because some of the commented out code is of use.

**Comment by K-Kumar-01** [comment]
@warunicorn19 Yeah sure. I will hold in this for now and we can connect on a meeting day and sort this out. Is this fine?

**Comment by SirZeck** [comment]
Can I work on it? When's the meeting to discuss this?

**Comment by leecalcote** [comment]
+ @sudo-NithishKarthik who is currently stewarding such an effort. He gave an overview of it in today's Meshery Development Meeting. See the meeting minutes for details (and the recording when it is posted)>

**Comment by SirZeck** [comment]
Oh, okay. He said that he's working on the back-end integration and it will be done by 15th Sept. After that he'll ask the willing contributors to work on the required areas. So, this also comes into that, right?

**Comment by leecalcote** [comment]
Good question. I'll rely on @sudo-NithishKarthik's discretion to make the judgment call on this one.

**Comment by sudo-NithishKarthik** [comment]
Yes @SirZeck , the plan is to do the same thing, that is, to refactor the entire UI components, and, as I told in the meeting, we can start working on it from 15th September. So, please hold on till that.
