### ISSUE TITLE
[UI] Runtime Error in UI

### ISSUE THREAD

**Issue by K-Kumar-01** [meshery/meshery#4096]
#### Current Behavior

When the following command is run
```
make run-ui-dev
```

A server runs at `localhost:3000`.

When the following is done:
1. Go to `http://localhost:3000/performance/profiles` and click the icon shown in the image below
![fd23aa31-aa29-4a94-b700-26115dc7ada0](https://user-images.githubusercontent.com/59891164/132290630-cb0553d4-43c2-47cd-81d0-e3c4bd60396b.jpeg)

The error shown in the image below pos up:
![Screenshot from 2021-09-07 11-07-38](https://user-images.githubusercontent.com/59891164/132290258-edc166bc-d1d2-4417-ac57-e3384b77c2e4.png)

2.Visit `http://localhost:3000/smi_results`. The error in the image below will be shown:
![Screenshot from 2021-09-07 11-08-00](https://user-images.githubusercontent.com/59891164/132290262-98e2c081-b641-48ae-abc0-287faac29990.png)

#### Desired Behavior

Proper error handling should have been done and corresponding flash messages should be displayed.

#### Environment

- Browser: Brave
- Host OS: Zorin 15(Ubuntu-18)
- Meshery Server Version: Not sure
- Meshery Client Version: Not sure
- Platform: Didn't configure

I just ran `make run-ui-dev` as I was working with UI. Didn't run `make run-local`

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
@K-Kumar-01 Thanks for testing but I checked twice the issue does not exist. Could you please do some checks like 
1. login to 9081 before going to 3000.
2. Check the console/log and networks. If there some you can ask in slack with screenshots
![image](https://user-images.githubusercontent.com/65453826/132304149-517411e7-d7f7-4fa0-ac3d-9eec110f3a5c.png)

**Comment by warunicorn19** [comment]
Im working on the dev server right now, seems to work fine🤔.

**Comment by sudo-NithishKarthik** [comment]
> I just ran make run-ui-dev as I was working with UI. Didn't run make run-local
You guys missed this 😅 
This happens when meshery server is not running.
@K-Kumar-01 , most of the time, contributors won't run ui dev server without running meshery server, but still we have to handle the errors gracefully, will you create a PR for this ?

**Comment by K-Kumar-01** [comment]
@Chadha93 @warunicorn19 I didn't run the meshery server as @sudo-NithishKarthik mentioned in the comment.

@sudo-NithishKarthik 
Yeah, I will create a PR for this.

Also, should i do optional chaining additionally as an extra safety measure?

**Comment by warunicorn19** [comment]
Ohh 😅, I had no idea. Also, sometimes(for me) if I run the ui-server and then the Meshery server, the UI server just terminates itself, without any warning or even a proper error message, maybe we could track that in this issue itself? @sudo-NithishKarthik @K-Kumar-01

**Comment by sudo-NithishKarthik** [comment]
> Also, should i do optional chaining additionally as an extra safety measure?

Yes. Actually, we are working on re-implementing the UI according to this [proposal](https://docs.google.com/document/d/1sb7XZIczx9FqKA3Hpd1XgtpEjfj8qjqMbgKY68t9Sko), So, we will have a more robust implementation of Redux where the redirection will happen in a higher layer. So, this issue will be tackled along with that.

**Comment by sudo-NithishKarthik** [comment]
> Also, sometimes(for me) if I run the ui-server and then the Meshery server, the UI server just terminates itself, without any warning or even a proper error message, maybe we could track that in this issue itself? @sudo-NithishKarthik @K-Kumar-01

Yes, @warunicorn19 , can you open an issue for that ?

**Comment by warunicorn19** [comment]
Sure, I'll do.

**Comment by K-Kumar-01** [comment]
> > Also, should i do optional chaining additionally as an extra safety measure?
> 
> Yes. Actually, we are working on re-implementing the UI according to this [proposal](https://docs.google.com/document/d/1sb7XZIczx9FqKA3Hpd1XgtpEjfj8qjqMbgKY68t9Sko), So, we will have a more robust implementation of Redux where the redirection will happen in a higher layer. So, this issue will be tackled along with that.

@sudo-NithishKarthik Just a question, why are we not using context API? Ig what we need from redux can also be done via context API. Also, there won't be need to install extra dependencies like `react-redux` or `redux-middlewares`.

**Comment by K-Kumar-01** [comment]
> > Also, should i do optional chaining additionally as an extra safety measure?
> 
> Yes. Actually, we are working on re-implementing the UI according to this [proposal](https://docs.google.com/document/d/1sb7XZIczx9FqKA3Hpd1XgtpEjfj8qjqMbgKY68t9Sko), So, we will have a more robust implementation of Redux where the redirection will happen in a higher layer. So, this issue will be tackled along with that.

So currently, should I provide a basic logic check as someone may break the UI if they do no run the server. Later, that logic will get replaced by `redux`

**Comment by sudo-NithishKarthik** [comment]
We have solid use cases for Redux in our app, it might not be very obvious based on the current state of our system, but considering what we want to be able to do with Meshery UI in the future which would involve very complex state management , we will not be able to handle such level of complexity with React Context API effectively.

**Comment by sudo-NithishKarthik** [comment]
We have solid use cases for Redux in our app, it might not be very obvious based on the current state of our system, but considering what we want to be able to do with Meshery UI in the future which would involve very complex state management , we will not be able to handle such level of complexity with React Context API effectively.

**Comment by sudo-NithishKarthik** [comment]
> So currently, should I provide a basic logic check as someone may break the UI if they do no run the server. Later, that logic will get replaced by redux

Yes
