### ISSUE TITLE
[UI] Menu Drawer: collapsed chevron is slightly off-center

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4105]
When collapsed the chevron is slightly off-center, sticking to the left:

https://user-images.githubusercontent.com/7570704/132413080-b704aaa8-879b-4ad2-9e9e-ffc80743c326.mov

Zooming in, this you see the effect even more easily:

These recordings are done using Safari. When using Chrome the effect is lessened, although the chevron is still hugging the lefthand side some.

https://user-images.githubusercontent.com/7570704/132413234-16def6fc-bd51-4e64-b9d5-a607fa927a71.mov

_Originally posted by @leecalcote in https://github.com/meshery/meshery/issues/3890#issuecomment-914641870_

**Comment by leecalcote** [comment]
@CipherGirl would you like to follow up on this issue?

**Comment by debo19** [comment]
Can I work on this?

**Comment by warunicorn19** [comment]
Sure @debo19

**Comment by warunicorn19** [comment]
@debo19 I think this is more of a safari specific, considering you use windows, I'll tackle this one if that's alright for you?

**Comment by debo19** [comment]
@warunicorn19 yeah sure go ahead, it does look more prominent on safari

**Comment by warunicorn19** [comment]
Thanks @debo19
