### ISSUE TITLE
`meshery-nginx-sm-deployment.yaml` and `meshery-nginx-sm-service.yaml` not present in the manifest directory

### ISSUE THREAD

**Issue by pranav-bhatt** [meshery/meshery#4107]
#### Current Behavior

While trying to run `mesheryctl system start --platform=kubernetes`, mesheryctl spits out the error 
```shell
unable to read config ~/.meshery/manifests/meshery-nginx-sm-deployment.yaml | open ~/.meshery/manifests/meshery-nginx-sm-deployment.yaml: no such file or directory 
```
This is probably because the directory where the manifests are pulled from (https://github.com/meshery/meshery/tree/v0.5.53/install/deployment_yamls/k8s) doesn't contain the aforementioned files.

To Reproduce
1. Run `curl -L https://git.io/meshery | PLATFORM=kubernetes bash - `

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@jbyers19 fyi

**Comment by SirZeck** [comment]
Can I take this issue and work on it?

**Comment by leecalcote** [comment]
@SirZeck, sounds good. A quick copy/paste and replace of an existing adapter manifest should do the trick. 👍

**Comment by SirZeck** [comment]
Oh, thanks @leecalcote.

**Comment by pranav-bhatt** [comment]
@SirZeck could you rename the files to include "-sm"?

**Comment by SirZeck** [comment]
Does this work?
