### ISSUE TITLE
Failed to start meshery using `mesheryctl system start --platform=docker`

### ISSUE THREAD

**Issue by pranav-bhatt** [meshery/meshery#4108]
#### Current Behavior
The following error occurs on running `mesheryctl system start --platform=docker` :
```shell
Error: failed to start Meshery
See https://docs.meshery.io/reference/mesheryctl/system for usage details
: failed to apply manifests: no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

To Reproduce
1. Run `curl -L https://git.io/meshery | PLATFORM=docker bash -` 
 
---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by pranav-bhatt** [comment]
This bug is mentioned in #4101. Can I close this?

**Comment by leecalcote** [comment]
Thanks for filing this, @pranav-bhatt. Good of you to open this one as I don't think we completely squashed this bug in the other open issue. 👍
