### ISSUE TITLE
[CI] Auto Meshery Release Announcement  through github workflow

### ISSUE THREAD

**Issue by sayantan1413** [meshery/meshery#4111]
#### Current Behavior

Meshery have a Mailchimp Email Template through which we manually send our user about the new Meshery release everytime.
 
#### Desired Behavior

Meshery should have a Html email template which can be used by a github workflow so that everytime there is a new release for Meshery an email would be sent to the Meshery users group through the workflow. 

#### Screenshot of the current Email Template

<img width="187" alt="Screenshot 2021-09-08 at 8 17 10 PM" src="https://user-images.githubusercontent.com/64970095/132531977-351fbb1f-c9ac-46b4-b280-cf72b3b5c2e8.png">

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by jaimep01** [comment]
@leecalcote 
Hello Please assign this one to me I'll try my best to complete it.

**Comment by warunicorn19** [comment]
Sounds great! @jaimep01

**Comment by jaimep01** [comment]
@warunicorn19 Is there a way i can get my hands on the current template, so I do not have to reinvent the wheel?

**Comment by warunicorn19** [comment]
Hey @jaimep01 so the difficult part of this issue is to get the workflow in place, let's focus on that first and then we could work on the template later on.

**Comment by jaimep01** [comment]
Hi @warunicorn19,
So it seems that there is an already created  [Action](https://github.com/marketplace/actions/send-email) we could add to manage email sending, triggering it on push should not be an issue but there are some questions that need to be answered first:

Do we have an SMTP server? (GitHub as of today(09/18/2021) does not provide an smtp relay to send emails from the action)
How are we going to manage the email accounts? ( Based on the EU data protections laws [here](https://ec.europa.eu/info/law/law-topic/data-protection/data-protection-eu_en) we probably should not store them ourselves probably not even in a GitHub Secret.) 

@leecalcote and @warunicorn19 - In my opinion this issue might be better held off until GitHub has a built-in option or action to send emails to a distribution list. 
If you would like to continue with the implementation I can test the  [Action](https://github.com/marketplace/actions/send-email) mentioned above and send  PR once it has been tested with a mailing list based on a GitHub Secret and Gmail as a test SMTP server.

**Comment by warunicorn19** [comment]
@jaimep01 as far as I know we don't have an SMTP server, I think it's better if we hold off for now if we are in risk of doing something illegal. @leecalcote thoughts?
