### ISSUE TITLE
[Docs] Avoid port conflict with Meshery Adapter for NGINX SM and Tanzu SM

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4117]
#### Current State
Meshery Adapter for Tanzu SM lists port 10010 as its reserved port. This conflicts with the Meshery Adapter for NGINX SM reserved port.

#### Desired State
Bump Tanzu SM out to 10011. Update this file - https://github.com/meshery/meshery/blob/master/docs/_adapters/tanzu-sm.md

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by iambami** [comment]
can I take this too?

**Comment by SirZeck** [comment]
Hey @leecalcote , I made a PR for this in the Tanzu SM repo. @warunicorn19 reviewed it. Can you look into it?

**Comment by SirZeck** [comment]
> Hey @leecalcote , I made a PR for this in the Tanzu SM repo. @warunicorn19 reviewed it. Can you look into it?

Oh my bad, I didn't updated the README.md file.
