### ISSUE TITLE
[Docs]Add Traefik Mesh lab to docs

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4120]
#### Current State
The recently made Traefik Mesh lab is not in the Docs.
#### Desired State
Let's add that lab to the docs for Traefik Mesh adapter.
https://docs.meshery.io/service-meshes/adapters/traefik-mesh

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by iambami** [comment]
hey can I do this?

**Comment by warunicorn19** [comment]
sure @iambami

**Comment by iambami** [comment]
Thanks. On it
