### ISSUE TITLE
[UI] Performance Result Chart: Comparison data missing

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4121]
#### Current Behavior
Missing perf results data on graph comparison.

<img width="1501" alt="Screen Shot 2021-09-08 at 5 03 02 PM" src="https://user-images.githubusercontent.com/7570704/132593086-75ff70bc-53ca-4928-b7db-22aa2a537e4a.png">

#### Environment

- Meshery Server Version: stable-v0.5.54

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
Same as #4077
