### ISSUE TITLE
[UI] Performance Result Chart: Percentile data overlapping

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4122]
#### Current Behavior
Percentile data is overlapping.

<img width="2159" alt="Screen Shot 2021-09-08 at 5 02 11 PM 4" src="https://user-images.githubusercontent.com/7570704/132593242-01a6c398-67de-4518-98b9-f386500e3368.png">

#### Desired Behavior
Percentile data shown on the right hand side of the graph.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Meghana-12** [comment]
This https://github.com/meshery/meshery/pull/4170 should solve this issue too, right?

**Comment by warunicorn19** [comment]
@Meghana-12 could you just check once and then close this issue if the problem does not persist anymore.

**Comment by Meghana-12** [comment]
@warunicorn19 so PR [#4170](https://github.com/meshery/meshery/pull/4170) add the percentiles to the right of the graph. And I don't think any other entries would take up more than 1/3rd space so I think it's fine. Will this do?

**Comment by warunicorn19** [comment]
Yup i think it works fine now, closing this issue then.
