### ISSUE TITLE
[Application] Import: Failure to unmarshal yaml 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4123]
#### Current Behavior
Importing by URL, [this pattern](https://raw.githubusercontent.com/service-mesh-patterns/service-mesh-patterns/master/samples/bookInfoPattern) results in an error message.

Uploading from filesystem, this pattern imports successfully.

#### Expected Behavior
Pattern should import.

#### Screenshots/Logs
<img width="1631" alt="Screen Shot 2021-09-08 at 5 45 43 PM" src="https://user-images.githubusercontent.com/7570704/132595732-069d2307-5674-490e-910f-97da5867eb04.png">

```
DEBU[2665] retrieved session for user with id: meshery
DEBU[2665] session for user with id: meshery was read in tact.
ERRO[2021-09-08T17:45:36-05:00] yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `https:/...` into map[string]interface {}  app=meshery code=2042 probable-cause= severity=2 short-description="failed to .save.the application" suggested-remediation=
DEBU[2665] retrieved session for user with id: meshery
DEBU[2665] session for user with id: meshery was read in tact.
```

#### Environment

- **Provider:** Local
- **Host OS:** Mac
- **Platform:** locally built
- **Meshery Server Version:** edge (circa v0.5.54)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@mgfeller I wonder if this isn't the right opportunity to jump into patterns (applications)...

**Comment by mgfeller** [comment]
@leecalcote feels like a good opportunity and the right moment. I'll give it a go.
