### ISSUE TITLE
[Docs]Guide to authenticate Mesheryctl

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4125]
#### Current State

Currently there's no guide to authenticate mesheryctl [here](https://docs.meshery.io/guides#meshery-cli)
#### Desired State

Add a guide with all the ways to authenticate to mesheryctl, all the ways to get the token, where the token is fetched, why there is a need for authentication.
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@navendu-pottekkat could you give me some pointers on this, so that I can get this done fast.

**Comment by navendu-pottekkat** [comment]
So, there is the `login` command and then there is the UI --> Download token and then some explanation on the `token` command.

mesheryctl should have inbuilt docs on these.
