### ISSUE TITLE
[v0.6.0 Release Docs] Filters (beta)

### ISSUE THREAD

**Issue by Zain-Muiz** [meshery/meshery#4129]
As part of Release Blog for v0.6.0, we have created this issue belonging to epic [#4127] in order to organize and ensure the smooth release of the blog. Feel free to leave a comment if you would like to take up this respective blog or any section of it.

Some of the Areas to be covered for **Filters** :
- [ ] WebAssembly Envoy Filters
- [ ] The power of the data plane
- [ ] mesheryctl filters

---
#### Guides and Resources
- [v0.6.0 Docs ](https://docs.google.com/document/d/1d8deyqzgsRIGyZGH0gxo-lhspHAWCvdBtY2h1gwLakI/edit?usp=sharing)
- [v0.6.0 Milestone](https://github.com/meshery/meshery/milestone/3)
- [v0.6.0 RoadMap](https://github.com/meshery/meshery/blob/master/ROADMAP.md)
- [v0.5.0 blog](https://layer5.io/blog/announcements/announcing-meshery-v050)
- :hammer_and_wrench: [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by felixfaisal** [comment]
Hey, Can I work on this? @Zain-Muiz @navendu-pottekkat If this is still available to work on, Thanks!

**Comment by navendu-pottekkat** [comment]
@felixfaisal Sure. This would require some knowledge/exploration on Web Assembly, WASM Filters and capabilities of Envoy based data planes and would be required in a week.

**Comment by Zain-Muiz** [comment]
Heyy @felixfaisal , How is your work on this coming about ?
