### ISSUE TITLE
[v0.6.0 Release Docs] Patterns (beta)

### ISSUE THREAD

**Issue by Zain-Muiz** [meshery/meshery#4130]
As part of Release Blog for v0.6.0, we have created this issue belonging to epic [#4127] in order to organize and ensure the smooth release of the blog. Feel free to leave a comment if you would like to take up this respective blog or any section of it.

Some of the Areas to be covered for **Patterns** :
- [ ] What is a service mesh pattern?
- [ ] What patterns are available ? Can I bring my own ?
- [ ] Importing from GitHub.com
- [ ] Can I customize a pattern ? How do I design one ?
- [ ] mesheryctl pattern

---

#### Guides and Resources
- [v0.6.0 Docs ](https://docs.google.com/document/d/1d8deyqzgsRIGyZGH0gxo-lhspHAWCvdBtY2h1gwLakI/edit?usp=sharing)
- [v0.6.0 Milestone](https://github.com/meshery/meshery/milestone/3)
- [v0.6.0 RoadMap](https://github.com/meshery/meshery/blob/master/ROADMAP.md)
- [v0.5.0 blog](https://layer5.io/blog/announcements/announcing-meshery-v050)
- :hammer_and_wrench: [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Shatakshi0805** [comment]
Hi, I would like to work on this. Could you please tell how do I go ahead with it?

**Comment by Zain-Muiz** [comment]
Heyy @Shatakshi0805 ! How's this going !? Feel free to reach out when you need help.

**Comment by Shatakshi0805** [comment]
working on it. would make a pr soon.

**Comment by Meghana-12** [comment]
@Shatakshi0805  Any updates? Please feel to reach out if you need some help or want to get the blog reviewed!

**Comment by Shatakshi0805** [comment]
Hi, so sorry I forgot to inform that I got caught up in some other work. Maybe someone else can work on this issue.
