### ISSUE TITLE
[ UI-Patterns ] Extract Patterns component to it's own file

### ISSUE THREAD

**Issue by Zain-Muiz** [meshery/meshery#4137]
#### Current Behavior
Pattern function in is in MesheryPatterns.js . This issue is based on action item 1 in the epic. [#4110]. 

#### Desired Behavior
Have own file for Patterns Component.

#### Implementation
Extract out the patterns component into it's own file.
https://github.com/meshery/meshery/blob/d11e84b348b48fdfe80823549692640553ab0d85/ui/components/MesheryPatterns.js#L645-L650

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Abhishek-kumar09 is this needed any longer?

**Comment by Abhishek-kumar09** [comment]
Looking at, I have done refractoring in the Patterns form so not exactly required. But superb effort by @Zain-Muiz.
