### ISSUE TITLE
[UI] Performance: Relocate "Add Perf Profile" button

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4139]
#### Desired Behavior
On the http://localhost:9081/performance/profiles page, relocate the button to the top left hand corner, horizontally-aligned with the layout buttons.

#### Mockup
<img width="1618" alt="Screen Shot 2021-09-09 at 7 13 52 PM" src="https://user-images.githubusercontent.com/7570704/132778717-2b778108-5401-4a7b-94b2-599f287edb13.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by PuneetDabral** [comment]
sir can i do ? ....but i am new in open source can you please help me to solve this i all is need your support so i can learn more and more.....

**Comment by leecalcote** [comment]
@PuneetDabral, sounds real good. A few conditions:

1. If you get stuck, join the Meshery community and seek assistance in the #newcomer or #meshery-ui channels, if needed.
1. Join the community anyway. It'll be nice to have you.
1. If you're unable to complete before this coming Monday, just signal so that another contributor can deliver this and you can review their PR.
1. Do you homework first. Read the contributing docs --> http://docs.meshery.io/project/contributing-ui. It's ok to learn as you go and ask for assistance as you go, but don't place an unjust burden on the other community members without first doing (and showing) your homework.

Fair?

**Comment by PuneetDabral** [comment]
ok sir i will try

**Comment by leecalcote** [comment]
@PuneetDabral, unless I'm mistaken, you haven't executed on step 1, yet.

**Comment by warunicorn19** [comment]
Hey @PuneetDabral have you joined our [slack](https://join.slack.com/t/meshery/shared_invite/zt-rgbyt4kj-6PUUyqY9SfQGRSt_oZV9yQ) workspace?

**Comment by PuneetDabral** [comment]
are you on discord

**Comment by warunicorn19** [comment]
Nope just on slack for now.

**Comment by warunicorn19** [comment]
https://join.slack.com/t/meshery/shared_invite/zt-rgbyt4kj-6PUUyqY9SfQGRSt_oZV9yQ

here is the link.

**Comment by PuneetDabral** [comment]
ok sir now i am a member of your community

**Comment by PuneetDabral** [comment]
sir please assign it to other ....

**Comment by asubedy** [comment]
I would like to work on this issue. Thank you

**Comment by warunicorn19** [comment]
Sure @asubedy!

**Comment by warunicorn19** [comment]
@asubedy any progress on this?

**Comment by asubedy** [comment]
@warunicorn19 Yes I am working on it couldn't work on it for days because my laptop got crashed and was sent to repair. Will try to finish the task in these two days. Sorry for the delay.
