### ISSUE TITLE
[Docs]Add Lifecycle management for Traefik Mesh adapter

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4143]
#### Current State
The page for Traefik Mesh adapter doesn't have a completed Lifecycle Management portion.
#### Desired State
Add a the Lifecycle Management part for this Adapter.
<img width="1440" alt="Screenshot 2021-09-10 at 12 07 54 PM" src="https://user-images.githubusercontent.com/53532328/132810968-da7a095d-720b-46f9-9a8e-9f4e17099111.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by rajpratyush** [comment]
Can i take up this issue?

**Comment by warunicorn19** [comment]
Sure @rajpratyush

**Comment by StarTrooper08** [comment]
We have to do the documentation part for Traefik Mesh Adapter right!?
I m going through the resources and contributor guides.
