### ISSUE TITLE
[Docs]Broken Link

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4144]
#### Current State
The `check our progress` link on the adapters page is broken. [example](https://docs.meshery.io/service-meshes/adapters/tanzu-sm#lifecycle-management)
#### Desired State
Fix the broken link.
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Shatakshi0805** [comment]
Hi, I would like to work on this. Please assign this issue to me.

**Comment by warunicorn19** [comment]
Sure @Shatakshi0805!
