### ISSUE TITLE
[Docs] GitHub Action for SMP

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4148]
#### Current State
This GH action is not described in Meshery Docs - https://github.com/layer5io/meshery-smp-action.

#### Desired State
This page should have a section on the GH Action for SMP - https://docs.meshery.io/functionality/performance-management.

See [this page](https://docs.meshery.io/functionality/service-mesh-interface#reporting-conformance) for an example of docs for GH Action for SMI Conformance - https://github.com/layer5io/meshery-smi-conformance-action

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@s1ntaxe770r ?

**Comment by s1ntaxe770r** [comment]
on it

**Comment by leecalcote** [comment]
Thank you, @s1ntaxe770r. Understanding your current situation, let's reopen for another contributor to pick this one up.

**Comment by navendu-pottekkat** [comment]
I can work on this. It should be quick and it should be similar to the SMI Conformance docs.

We also need to update the general performance testing docs. I will finish this over the weekend.

**Comment by navendu-pottekkat** [comment]
This issue is also linked: https://github.com/meshery/meshery/issues/3972

**Comment by navendu-pottekkat** [comment]
This is closed since #3972 is fixed and the docs are here: https://docs.meshery.io/guides/performance-management#running-performance-benchmarks-in-your-pipelines
