### ISSUE TITLE
Generating pattern components at runtime for Kubernetes Native Resources

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#4149]
Use Case: Extracting metadata for pattern components from Kubernetes
Primary Actor: Meshery Server
Scope: A single Kubernetes cluster
Level: System-wide setting

Preconditions: 
Meshery has appropriate credentials to a Kubernetes cluster.

Acceptance Tests:
1. The following Kubernetes objects are registered as capabilities in Meshery.
2. Each capability is associated with the respective Kubernetes context.
3. The Kubernetes context has a version # (e.g. v1.22.0); consequently, every registered capability has an associated version number.

Behaviors:
1. Meshery should register duplicative capabilities of same object type and K8s version # between contexts. Deletion of one context and its registered capabilities should have no effect on another connected context.
2. Meshery Server does not extract service mesh pattern components - only Kubernetes pattern components.
3. Upon successful connection to Kubernetes context, but on failure to generate components, display Warning level event in Meshery UI Notification Center.
Include probable cause of insufficient service account / cert permissions.

Triggers:
1. Initial connection to Kubernetes cluster. Could be on Meshery Server boot or on user upload of one or more contexts.
2. Does not trigger when ad hoc connectivity tests are run.
Basic flow (actor: meshery server):
1. Upon initial connection to a Kubernetes context, retrieve K8s objects (json documents) from kube-api using client-go.
2. Use MeshKit function to create schemas and definitions from the json documents.
3. Use core.RegisterWorkload function to register these workloads in Meshery Server.

**Comment by leecalcote** [comment]
@Revolyssup will you capture this in Meshery Docs under the Server component in the Architecture section?
