### ISSUE TITLE
[Docs] Trubleshooting guide for `system check`

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#4154]
#### Desired State
Create a guide explaining the possible reasons and pointers to solve the issue behind failed environment checks from `system check`

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sgibson19** [comment]
I would like to work on this

**Comment by piyushsingariya** [comment]
Sure, @sgibson19 :smile:

**Comment by piyushsingariya** [comment]
```
$ mesheryctl system check

Docker 
--------------
✓ Docker is running
✓ docker-compose is available

Kubernetes API 
--------------
✓ can initialize Kubernetes client
✓ can query the Kubernetes API

Kubernetes Version 
--------------
✓ is running the minimum Kubernetes version
✓ is running the minimum kubectl version

Meshery Version 
--------------
!! server is not up-to-date
!! cli is not up-to-date (stable-v0.5.49)

Meshery Adapters 
--------------
✓ meshery-istio adapter is running and reachable
!! meshery-octarine adapter is not running
!! meshery-traefik-mesh adapter is not running
!! meshery-linkerd adapter is not running
!! meshery-consul adapter is not running
!! meshery-nsm adapter is not running
!! meshery-kuma adapter is not running
!! meshery-cpx adapter is not running
!! meshery-osm adapter is not running
```

many of the checks are unsuccessful in the example case, this issue focuses on writing a manual to tackle/list the possible reasons behind each failure.
that means listing possible reasons for a failed check and instructions to pass the checks

**Comment by piyushsingariya** [comment]
Closed via https://github.com/meshery/meshery/pull/4462
