### ISSUE TITLE
[mesheryctl] Slow response time from commands: background checks taking time

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4156]
#### Current Behavior
Slowness with background requisite checks, which can take ~10 seconds to execute.

#### Desired Behavior
faster response times on the Ctl commands. Faster health checking or reduced health checking.

#### Screen Capture

https://user-images.githubusercontent.com/7570704/132949537-7bf6c9a6-7707-4a4f-8a58-4e5d456628ae.mov

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by panyuenlau** [comment]
Hey @leecalcote, I just looked into the implementation of `mesheryctl system status`, it seems the slowness mainly coming from the [`docker-compose` command](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/system/status.go#L93) that gets run behind the scene every time `mesheryctl system status` is issued. With that said, higher CPU usage would cause a longer time for docker to respond and therefore slower response for our command.

The only way that I can think of to make the command "run faster" is to get the data and store them somewhere periodically, and then just output those values when the user uses the `mesheryctl system status` command, but this doesn't guarantee what the user sees is the most up-to-date state of the system

**Comment by Zanda256** [comment]
@panyuenlau  would it be healthy if we run the line 93 in a go routine and utilise a channel to wait for output?
