### ISSUE TITLE
[UI] Import pattern files from GitHub

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#4157]
#### Current Behavior

Users can import pattern/application/filter files via a URL through Meshery UI.

#### Desired Behavior

Users should be able to import pattern files from GitHub as well when logged in to Meshery Remote Provider via GitHub.

The new UI should reflect the following features:

- User clicks import and is presented with 3 options
  - "browse" for filesystem import
  - "url" for generic, public, HTTP endpoint
  - "GitHub" which will contain a two-level pick list of 1. the user's orgs and 2. the repos in that chosen org. The user will be allowed to select only one repo to import at a time.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by K-Kumar-01** [comment]
@navendu-pottekkat 
I would like to work on it.

**Comment by navendu-pottekkat** [comment]
Sure, FYI this might require some design and it may not be super straightforward. If you are starting out here, then there might be other good-first-issues. But if you are up for a challenge, feel free to take this on.

**Comment by navendu-pottekkat** [comment]
@l5io Testing

**Comment by navendu-pottekkat** [comment]
@l5io Testing

**Comment by Chadha93** [comment]
@navendu-pottekkat I will try to present some stuff on it, this week.

**Comment by leecalcote** [comment]
@Chadha93, let's ensure that this is intentionally closed and not due to lack of attention.

**Comment by Chadha93** [comment]
> @Chadha93, let's ensure that this is intentionally closed and not due to lack of attention.

yes, as from the past discussion and my previous PR we are not going with that separate fields for GH Import(implemented), we need a proper approach with some refinements in the backend also to achieve this with proper goals.
