### ISSUE TITLE
Deleting 10 patterns at once returns a warning

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4158]
#### Current Behavior
When a user bulk deletes ten patterns, the patterns seem to be deleted. The total number of patterns available dropped by ten, however, an error message is returned.

#### Expected Behavior
If the patterns are successfully deleted, the user should not be negatively notified.

#### Screenshots/Logs
<img width="1058" alt="Screen Shot 2021-09-11 at 10 33 18 AM" src="https://user-images.githubusercontent.com/7570704/132953289-6dcd7157-a85f-4984-b349-9078ed27c609.png">

#### Environment
- **Meshery Server Version:** stable-v0.5.56

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Chadha93 will you investigate this?

**Comment by Chadha93** [comment]
> @Chadha93 will you investigate this?

Sure

**Comment by leecalcote** [comment]
@Chadha93 this is a provider-specific issue with Meshery Cloud's use of API Gateway.

**Comment by Chadha93** [comment]
@lee I have just tested this but was not able to reproduce the error, working fine. adding a video with networks tab, all requests were madde successfully but the opertion felt a bit laggy in my system is it same for you ?

https://user-images.githubusercontent.com/65453826/133628793-6035d64c-1c9e-475d-b509-183984883b00.mp4
