### ISSUE TITLE
[v0.6.0 Release Docs] Pipelining Service Mesh Specifications

### ISSUE THREAD

**Issue by Meghana-12** [meshery/meshery#4179]
As part of Release Blog for v0.6.0, we have created this issue belonging to epic [[#4127](https://github.com/meshery/meshery/issues/4127)] in order to organize and ensure the smooth release of the blog. Feel free to leave a comment if you would like to take up this respective blog or any section of it.

Some of the Areas to be covered for Pipelining Service Mesh Specifications:
- [ ] GitHub Action for Service Mesh Performance #4203
- [ ] GitHub Action for Service Mesh Interface #4148

---

#### Guides and Resources
- [v0.6.0 Docs ](https://docs.google.com/document/d/1d8deyqzgsRIGyZGH0gxo-lhspHAWCvdBtY2h1gwLakI/edit?usp=sharing)
- [v0.6.0 Milestone](https://github.com/meshery/meshery/milestone/3)
- [v0.6.0 RoadMap](https://github.com/meshery/meshery/blob/master/ROADMAP.md)
- [v0.5.0 blog](https://layer5.io/blog/announcements/announcing-meshery-v050)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)

**Comment by navendu-pottekkat** [comment]
@DelusionalOptimist @Meghana-12 I am working on the docs for these as well as writing guides for these. I can take this up if it is not an issue. It should take less effort and could avoid having to duplicate content.

**Comment by DelusionalOptimist** [comment]
Thanks @navendu-pottekkat. :smile:

**Comment by navendu-pottekkat** [comment]
@Meghana-12 Draft for pipelining service mesh specs: https://docs.google.com/document/d/17Y54WCyJOvAKlFUb-VNB7x36kjru6TjDOWB2HY9AAM0/edit#

I have not added the images and I am waiting for this PR for some references to the docs: https://github.com/meshery/meshery/pull/4192

Please check and let me know if this would be enough.

**Comment by Meghana-12** [comment]
Thanks awesome! Thanks @navendu-pottekkat!
