### ISSUE TITLE
[v0.6.0 Release Docs] SMI Conformance

### ISSUE THREAD

**Issue by Meghana-12** [meshery/meshery#4180]
As part of Release Blog for v0.6.0, we have created this issue belonging to epic [[#4127](https://github.com/meshery/meshery/issues/4127)] in order to organize and ensure the smooth release of the blog. Feel free to leave a comment if you would like to take up this respective blog or any section of it.

Some of the Areas to be covered for SMI Conformance:
- [ ] What is the conformance program? How do I verify my service mesh’s conformance to SMI?
- [ ] What sample application is used?
- [ ] How many tests are there? What do they test? 
- [ ] Meshery UI and SMI Conformance Dashboard on the landscape: How to interpret the results? 
- [ ] `mesheryctl mesh validate`
---

#### Guides and Resources
- [v0.6.0 Docs ](https://docs.google.com/document/d/1d8deyqzgsRIGyZGH0gxo-lhspHAWCvdBtY2h1gwLakI/edit?usp=sharing)
- [v0.6.0 Milestone](https://github.com/meshery/meshery/milestone/3)
- [v0.6.0 RoadMap](https://github.com/meshery/meshery/blob/master/ROADMAP.md)
- [v0.5.0 blog](https://layer5.io/blog/announcements/announcing-meshery-v050)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)

**Comment by SirZeck** [comment]
I would like to contribute to this blog topic. Can you help me pointing out which docs should I refer to gain information about SMI Conformance?

**Comment by SirZeck** [comment]
I have made a draft of the 3 tasks but not sure about what to add in the 4th task. Can you review it and give some suggestions or feedback?

https://docs.google.com/document/d/19rSlPdKe08-RiB8jnj51XH5RU1NAFb_LyOX6FYgVrHQ/edit?usp=sharing

**Comment by navendu-pottekkat** [comment]
@SirZeck These two docs should cover everything related to SMI. You can also check the links referenced in those posts for more info.

https://docs.meshery.io/functionality/service-mesh-interface

https://docs.meshery.io/guides/smi-conformance

**Comment by SirZeck** [comment]
@navendu-pottekkat as it is mentioned in the task 4 that I have to explain what the red crosses and yellow crossed means mentioned on this dashboard, right?

https://meshery.io/service-mesh-interface

**Comment by navendu-pottekkat** [comment]
Yes. That is correct. You can check here: https://layer5.io/service-mesh-landscape#smi

**Comment by navendu-pottekkat** [comment]
You can also check this: https://smi-spec.io/blog/validating-smi-conformance-with-meshery/

**Comment by SirZeck** [comment]
> I have made a draft of the 3 tasks but not sure about what to add in the 4th task. Can you review it and give some suggestions or feedback?
> 
> https://docs.google.com/document/d/19rSlPdKe08-RiB8jnj51XH5RU1NAFb_LyOX6FYgVrHQ/edit?usp=sharing

Now the draft is completed, can you review it for any changes or additions?

**Comment by Meghana-12** [comment]
Awesome! Thank you so much @SirZeck! 

@navendu-pottekkat could you review this?

**Comment by navendu-pottekkat** [comment]
Yes sure.

**Comment by navendu-pottekkat** [comment]
Will this be a separate blog post or will it be added to the release blog?

**Comment by Meghana-12** [comment]
I'm not sure. @leecalcote?
