### ISSUE TITLE
[v0.6.0 Release Docs] Increased Platform Support

### ISSUE THREAD

**Issue by Meghana-12** [meshery/meshery#4181]
As part of Release Blog for v0.6.0, we have created this issue belonging to epic [[#4127](https://github.com/meshery/meshery/issues/4127)] in order to organize and ensure the smooth release of the blog. Feel free to leave a comment if you would like to take up this respective blog or any section of it.

Some of the Areas to be covered for Increased Platform Support:
- [x] Meshery CLI support for Linux, Windows, and macOS and Apple Silicon across all current commands
- [x] Pervasive Kubernetes support
- [x] System Health Checks 
   - [x] `mesheryctl system check` - pre and post-flight prereq check

---

#### Guides and Resources
- [v0.6.0 Docs ](https://docs.google.com/document/d/1d8deyqzgsRIGyZGH0gxo-lhspHAWCvdBtY2h1gwLakI/edit?usp=sharing)
- [v0.6.0 Milestone](https://github.com/meshery/meshery/milestone/3)
- [v0.6.0 RoadMap](https://github.com/meshery/meshery/blob/master/ROADMAP.md)
- [v0.5.0 blog](https://layer5.io/blog/announcements/announcing-meshery-v050)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)

**Comment by navendu-pottekkat** [comment]
@Meghana-12 Initial draft for this: https://docs.google.com/document/d/17Y54WCyJOvAKlFUb-VNB7x36kjru6TjDOWB2HY9AAM0/edit?usp=sharing

**Comment by navendu-pottekkat** [comment]
A pending doc that needed to be added to finish this: https://github.com/meshery/meshery/issues/4197
