### ISSUE TITLE
[helm] helm installation doesn't work for Meshery v0.5.54 and onwards

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#4185]
#### Current Behavior
When installing v0.5.54 and further versions using helm, installation fails.
Note that this is regardless of the target Kubernetes cluster's version.

#### Expected Behavior
Users should be able to install Meshery using helm.

#### Possible cause
Changes introduced to support k8s v1.21.0+ in v0.5.54 release might have brought in some errors in defined helm charts.

#### Screenshots/Logs
```
helm install meshery-1 meshery/meshery
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]
```

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v0.5.54+
- **K8s Version:** Any
- **Helm Version:** Any

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by panyuenlau** [comment]
Hey @DelusionalOptimist, can I give this a try?

**Comment by warunicorn19** [comment]
Sure @panyuenlau.
