### ISSUE TITLE
[Docs] Update mesheryctl using bash script without deploying Meshery

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#4187]
#### Current State

Users need to update mesheryctl occasionally when a new release is available. The docs to update in mesheryctl points to [this URL](https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli) which does not mention how to _only_ update mesheryctl without deploying Meshery.

![Screenshot 2021-09-14 at 8 19 23 PM](https://user-images.githubusercontent.com/49474499/133280885-35d42e10-5700-430a-a53b-33cd1f819f56.png)

#### Desired State

Users can run this one liner to update mesheryctl without deploying Meshery.

The command in the docs could be replaced with this:

```
curl -L https://git.io/meshery | DEPLOY_MESHERY=false bash -
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Shatakshi0805** [comment]
Hi, I would like to work on this. Could you please assign this issue to me?

**Comment by navendu-pottekkat** [comment]
Yes. That was blazingly fast @Shatakshi0805 🚀

**Comment by Shatakshi0805** [comment]
Yes, this project really interests me so kind of want to learn more about it. :)

**Comment by Shatakshi0805** [comment]
I think this issue can be a good start for someone who is just starting out in meshery. So unassigning myself. 😅
/unassign

**Comment by kartik1918** [comment]
Hi, Can I work on this?

**Comment by warunicorn19** [comment]
Sure @kartik1918.
