### ISSUE TITLE
Define Message types for Broadcasting

### ISSUE THREAD

**Issue by dhruv0000** [meshery/meshery#4195]
@dhruv0000 before we create message types, which we should, please see the Messaging Framework and Notification Center design spec.

---------

 @bariqhibat 8 hours ago
I saw that this Message field can be a boolean or an error. This will pose a problem in the future if we cast the variabel just like what we are doing, for example boolean/error but it turns out to be the other way around. Could we just define a new field just in case, like ok: boolean (and is always there true/false), then error is a null / error. What do you think? Hence, if we find ok = false -> we get the error field.

@bariqhibat bariqhibat 8 hours ago
this would also make it clearer if the response is bad or not in the switch case in your other file

@dhruv0000 dhruv0000 8 hours ago
I kept message as interface{} to keep it abstract, since it might be vary from different type of the broadcast. Not sure if it would make sense for other Broadcast type. Said that, I also dont like the idea of not knowing what the message type is.
One way might be to define individual struct for each type?
Although I dont want the overhead of defining a struct type in meshkit once again, in case we are using it to send data locally defined in meshery.
I think adding comments when defining broadcast type about what to expect in message should do for now.

_Originally posted by @leecalcote in https://github.com/meshery/meshery/issues/4191#issuecomment-920137850_

Doc: https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit

**Comment by mgfeller** [comment]
@dhruv0000 @bariqhibat 
This sounds like cloud events to me, doesn't it, the spec of which we should follow where we want to use events in meshery.
There is some info in the doc @leecalcote mentioned: https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit#heading=h.p1m1fiq40muq
at least the cloud event context structure would make sense to be defined in meshkit, wouldn't it?

**Comment by bariqhibat** [comment]
> @dhruv0000 @bariqhibat
> This sounds like cloud events to me, doesn't it, the spec of which we should follow where we want to use events in meshery.
> There is some info in the doc @leecalcote mentioned: https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit#heading=h.p1m1fiq40muq
> at least the cloud event context structure would make sense to be defined in meshkit, wouldn't it?

Ah yes, that's the word that I've been looking for! From the spec on the docs, we would definitely need the `source` field in order to filter out events that the subscription wishes to listen to in the goroutine, hence only triggers on specific events from specific sources. Does itmake sense if we implement it?

**Comment by mgfeller** [comment]
:smile: If this is about sending/handling events using NATS (now or later), then I'd say definitely yes. I think it is a good approach anyway. I haven't had the chance to have a closer look at the background of this issue, though.
It will pay off to follow the spec right from the start (incl all required fields). 
I added some more comments to the `source` attribute in the doc.

One thing we haven't discussed in the doc is what kind of queue etc architecture/setup we envisage. If we start with change in mind and have good message types then I think we can refine later. Some message type suggestions https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit#heading=h.opk9ipuzr6t6 .

What do you think?

**Comment by bariqhibat** [comment]
> What do you think?

Hey @mgfeller, the spec looks good. However, there might be a problem if we're trying to enable multiple clusters / client connected to one Meshery instance. We need some sort of identifier for each cluster/client, what do you suggest?

**Comment by mgfeller** [comment]
Hey @bariqhibat good point. The `component-instance-id` was a suggestion to handle multiple instances of the same component, and the component could possibly register itself with additional information (not quite sure where, though, the one Meshery instance?). But this was just an idea, not sure it is optimal, it needs some discussion. 

And/or: it could be useful/practical if the source contained the name/id of the cluster, i.e. that it is part of a fqdn of a component. 

Which Meshery component in a cluster would own the name/id of a cluster? Id's (as GUIDs) would be unique, but uniqueness of names is not necessarily easy to guarantee. Does a cluster have a fqdn that one could use?

Will there be potentially multiple instances of the same component in a cluster?

Not quite sure what you mean by "client"?

**Comment by bariqhibat** [comment]
Hey @mgfeller, 

One of the meshery component in a cluster that'd own the name/id of the cluster would be the all the pods/configmap/etc that is found by MeshSync. This is critical as user from cluster A would only want to subscribe to the detection of his own cluster, i.e. not notified of other cluster if there exists any.

I think putting it as one of the fqdn in the `Source` field is a good idea, what do you think if I put it before the `meshery`. So it'll be `urn:{cluster_identifier}:meshery:adapter:consul`. 

> Does a cluster have a fqdn that one could use?

I'm not sure about this, I might need to do more research.

> Will there be potentially multiple instances of the same component in a cluster?

That'll be a yes, but I think the name of the component should be unique, i.e. they put a randomly generated code after the component name.

> Not quite sure what you mean by "client"?

What I mean by client is exactly the same as cluster.

**Comment by mgfeller** [comment]
Hey @bariqhibat,

> One of the meshery component in a cluster that'd own the name/id of the cluster would be the all the pods/configmap/etc that is found by MeshSync. This is critical as user from cluster A would only want to subscribe to the detection of his own cluster, i.e. not notified of other cluster if there exists any.

Yes, agreed that the cluster name should be known to all Meshery resources sources, and be included in the events of all.  However, by "owner" I was referring to the  component that is the single source of truth of the cluster name (or id), possibly creates it (we haven't really determined where the name/id comes from). So the place resources/components go "look" for the cluster name, or the resource/component that hands it out. Maybe `meshsync` itself? Or the broker? Which Meshery component/resource is _always_ present?

> I think putting it as one of the fqdn in the `Source` field is a good idea, what do you think if I put it after the `meshery`. So it'll be `urn:meshery:{cluster_identifier}:adapter:consul`.

Yes, I think that looks good :+1:

> That'll be a yes, but I think the name of the component should be unique, i.e. they put a randomly generated code after the component name.

I think it would be preferable to add the ID like so: `urn:meshery:{cluster_identifier}:adapter:consul:{component-id}`, in a 'namespaced' way. That would make for easier parsing and grouping with a consistent separator. It would also make it consistent with the info in `component_info.json` and the `ComponentInfo` endpoint.
