### ISSUE TITLE
[UI] Refracting PPFA (pattern/performance/filters/application)

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#4198]
#### Current Behavior
Currently, in **PPFA** (pattern/performance/filters/application), there are many components that are being repeated and can be reused.

#### Desired Behavior
Refractor PPFA and add it to common components to make code much more efficient and easily readable.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
@Zain-Muiz As discussed on the WASM call will you track this?

**Comment by Zain-Muiz** [comment]
Yes @Chadha93 . Definitely !
