### ISSUE TITLE
[Docs]Add Open Service Mesh lab to docs

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4200]
Current State
The recently made Open Service Mesh lab is not in the Docs.

Desired State
Let's add that lab to the docs for Open Service Mesh adapter.
https://docs.meshery.io/service-meshes/adapters/osm

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by shreyaansjain** [comment]
Can i do this ? if yes please explain the work

**Comment by warunicorn19** [comment]
Sure @shreyaansjain, in the docs if you go to adapters, most adapters have a service mesh lab in them, the lab for OSM was just made, so you'll have to add it to the docs page, if you have a look at the other adapters, it's actually quite easy to do.

**Comment by warunicorn19** [comment]
https://github.com/meshery/meshery/pull/4141/files

It has to be done exactly like this.

**Comment by shreyaansjain** [comment]
Thanks @warunicorn19  for your reply i have made a pr please check it and if you want some changes please tell me
