### ISSUE TITLE
[v0.6.0 Release Docs] GitHub Action for SMI Conformance

### ISSUE THREAD

**Issue by Meghana-12** [meshery/meshery#4203]
As part of Release Blog for v0.6.0, we have created this issue belonging to epic [[#4127](https://github.com/meshery/meshery/issues/4127)] in order to organize and ensure the smooth release of the blog. This issue is to track the status of the blog post for GitHub Action for SMI Conformance (parent issue #4179). Feel free to leave a comment if you would like to take up this respective blog or any section of it. 

---

#### Guides and Resources
- [v0.6.0 Docs ](https://docs.google.com/document/d/1d8deyqzgsRIGyZGH0gxo-lhspHAWCvdBtY2h1gwLakI/edit?usp=sharing)
- [v0.6.0 Milestone](https://github.com/meshery/meshery/milestone/3)
- [v0.6.0 RoadMap](https://github.com/meshery/meshery/blob/master/ROADMAP.md)
- [v0.5.0 blog](https://layer5.io/blog/announcements/announcing-meshery-v050)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)

**Comment by Meghana-12** [comment]
@navendu-pottekkat Your blog related to #4179 covers this too, right?

**Comment by navendu-pottekkat** [comment]
Yes. I have yet to write the individual blogs for everything I've covered in the other blog.

**Comment by Meghana-12** [comment]
Assigning this to you then!

**Comment by leecalcote** [comment]
The blog post on this specific topic has us covered. :thu
