### ISSUE TITLE
[UI] Update UI of the confirmation prompts in the modals - Patterns 

### ISSUE THREAD

**Issue by Meghana-12** [meshery/meshery#4209]
#### Desired Behavior
The primary option on the right-hand side should have the current background color and the secondary option on the left should have a transparent background. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
Hey @Meghana-12 , did you get a chance to look at this? if not, we could push this for the next release😄.

**Comment by Meghana-12** [comment]
Oh sorry, didn't work on it yet.

**Comment by warunicorn19** [comment]
No problem 😄.
