### ISSUE TITLE
[mesheryctl] `system token create`shows unhelpful error when token name is missing

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#4214]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system token create` is used to create a new token in the meshconfig(.meshery/config.yaml) file. 

When the token name is not provided, it shows an unhelpful error:

![Screenshot 2021-09-20 at 2 59 42 PM](https://user-images.githubusercontent.com/49474499/133981676-ee53f8cd-5515-4887-8d1e-983828a080b4.png)

#### Desired Behavior

Mention that the token name is needed instead of just saying there is a missing argument.

#### Environment

- Host OS: Mac
- Meshery Server Version: edge-latest
- Meshery Client Version: edge-latest
- Platform: Docker

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Viper-M** [comment]
@navendu-pottekkat  Can I work on this issue?

**Comment by sayantan1413** [comment]
Sure @Viper-M go ahead! 🚀

**Comment by navendu-pottekkat** [comment]
@Viper-M You could also fix this issue with this: https://github.com/meshery/meshery/issues/4216

**Comment by navendu-pottekkat** [comment]
Assigning it you as well.

**Comment by navendu-pottekkat** [comment]
@Viper-M Could you also check the other subcommands in `system token` for the same issue as well?

**Comment by Viper-M** [comment]
> @Viper-M Could you also check the other subcommands in `system token` for the same issue as well?

Sure

**Comment by sayantan1413** [comment]
<img width="752" alt="Screenshot 2021-09-27 at 8 43 13 PM" src="https://user-images.githubusercontent.com/64970095/134936492-3d623af3-a9da-4ab1-be49-9c57056ae015.png">

Looks good @navendu-pottekkat ?

**Comment by Zanda256** [comment]
Can I take this up please ?@navendu-pottekkat .
