### ISSUE TITLE
[Docs] Typo Error in ADOPTERS.md file

### ISSUE THREAD

**Issue by khanjasir90** [meshery/meshery#4217]
#### Current State
![adp2](https://user-images.githubusercontent.com/53305380/133989542-d819bb77-4b77-404b-b449-3ad70d4ff3d2.JPG)
![adp1](https://user-images.githubusercontent.com/53305380/133989574-561ec77d-ee86-4893-8ec2-d58cf078551b.JPG)

#### Desired State
It should be something like this : 
We find Meshery to be the perfect "goto" tool to help us successfully operate our service mesh OR We find Meshery to be the perfect tool to help us successfully operate our service mesh
Our Complex, Dynamic, and Intelligent system demands leverage "of" different tools to efficiently manage service exchange and ecosystem at Global Scale

words in quote should represent the changes.
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by khanjasir90** [comment]
@leecalcote @warunicorn19  can i work on this issue if its a valid one!

**Comment by warunicorn19** [comment]
@navendu-pottekkat is this something we need to fix?

**Comment by navendu-pottekkat** [comment]
No I think. Because these were written by the adopters and we do not want to paraphrase them.

**Comment by khanjasir90** [comment]
Okay @navendu-pottekkat let's close this one!
