### ISSUE TITLE
[Docs] Add support for versions

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4232]
#### Current State
Meshery Docs are not currently versioned. The Jekyll theme that Meshery Docs uses is [docsy-jekyll](https://github.com/vsoch/docsy-jekyl), which does not support versioning ([see explanation](https://github.com/vsoch/docsy-jekyll/issues/23#issuecomment-656311752)).

#### Potential Solutions

--> See "[Versioning](https://docs.google.com/document/d/17guuaxb0xsfutBCzyj2CT6OZiFnMu9w4PzoILXhRXSo/edit#heading=h.mt3gxwcjx81k)" section of Meshery Documentation design specification for outline of approaches.

1. [Most Favored] Multiple site versions published and available on different paths; e.g. `docs.meshery.io/latest/`, `docs.meshery.io/v0.5`, `docs.meshery.io/v0.6`. Care needs to be taken with the final expected size of GitHub Pages. See [usage limits](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits).
    - Reference: https://github.com/justwriteclick/versions-jekyll
2. Multiple site versions published and available on different subdomains; e.g. `docs-v05.meshery.io`
3. [Least Favored] Multiple docs versions published using a plugin
    - Reference: https://github.com/rob-murray/jekyll-version-plugin 

Update solution proposal and notes in "[Versioning](https://docs.google.com/document/d/17guuaxb0xsfutBCzyj2CT6OZiFnMu9w4PzoILXhRXSo/edit#heading=h.mt3gxwcjx81k)" section of Meshery Documentation design specification.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by khanjasir90** [comment]
@leecalcote is this issue good for newcomers if yes then could u pls direct me to the resources that would help me do that! I will be more than happy to contribute

**Comment by leecalcote** [comment]
@khanjasir90 great question. In reality, no, it's large undertaking that will shift the foundational architecture of the way Meshery docs are published. I do encourage you to review the design spec linked in the issue description and study the problem, tryout solutions, comment, and work your way toward being able to take on this or this type of issue. 👍

**Comment by leecalcote** [comment]
Current docs size is ~96 MB.
