### ISSUE TITLE
[mesheryctl] Change the default platform to Kubernetes

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#4233]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

The default platform to which Meshery currently deploys is Docker.

#### Desired Behavior

For the v0.6.0 release, we need to switch the default platform to Kubernetes.

#### Implementation

- [ ] change the default platform in bash script
- [ ] change the default platform in mesheryctl
- [ ] using Helm charts in mesheryctl
- [ ] change docs to reflect this change

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
🙌

**Comment by navendu-pottekkat** [comment]
@l5io Track this please!

**Comment by navendu-pottekkat** [comment]
@l5io Test

**Comment by navendu-pottekkat** [comment]
@l5io  Test
