### ISSUE TITLE
[Docs] Deprecation of Meshery Deployments via Kubernetes manifests

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4235]
#### Current State
Meshery Docs provide instructions to users to install Meshery using Kubernetes manifests. As of v0.6.0, Meshery will no longer offer support for this style of deployment. #4103 calls for the deprecation of Kubernetes deployments via manifests. 

#### Desired State
All references to installation of Meshery using Kubernetes manifests should be displaced with alternative deployment methods. The most favored method is that of using `mesheryctl`.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by navendu-pottekkat** [comment]
Will make this change as https://github.com/meshery/meshery/issues/4103 is fixed.

**Comment by leecalcote** [comment]
@vedant-kakde will you confirm that this has been completed by reviewing the current docs?

**Comment by navendu-pottekkat** [comment]
I had made a PR that does this. Missed to link this issue.
