### ISSUE TITLE
Upgrade to MeshKit v0.2.27 Broadcast message type failure

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4250]
#### Current Behavior
Upgrading to MeshKit v0.2.27 produces this error on build:

```
➜  meshery git:(master) ✗ make run-fast
cd cmd; go mod tidy; \
        BUILD="v0.5.58" \
        PROVIDER_BASE_URLS="https://meshery.layer5.io" \
        PORT=9081 \
        DEBUG=true \
        ADAPTER_URLS="mesherylocal.layer5.io:10000 mesherylocal.layer5.io:10001 mesherylocal.layer5.io:10002 mesherylocal.layer5.io:10003 mesherylocal.layer5.io:10004 mesherylocal.layer5.io:10006 mesherylocal.layer5.io:10007 mesherylocal.layer5.io:10008 mesherylocal.layer5.io:10009 meshery-nginx-sm:10010" \
        go run main.go;
# github.com/layer5io/meshery/internal/graphql/model
../internal/graphql/model/helpers.go:83:5: cannot use broadcast.OperatorSyncChannel (type broadcast.BroadcastSource) as type string in field value
../internal/graphql/model/helpers.go:84:5: unknown field 'Message' in struct literal of type broadcast.BroadcastMessage
make: *** [run-fast] Error 2
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by bariqhibat** [comment]
Hey @leecalcote, this requires a change from the Meshkit repo as well, if you don't mind.
