### ISSUE TITLE
[Docs] Broken Image Links

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4280]
#### Current State
Images are broken on this page - https://docs.meshery.io/functionality/performance-management

<img width="1559" alt="Screen Shot 2021-09-30 at 9 32 48 AM" src="https://user-images.githubusercontent.com/7570704/135507700-9591a57e-bf0a-4efd-9fb1-73aaf59e74d0.png">

#### Desired State
Images should be displayed.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Rishi22-Coding** [comment]
Hi, 
I want to give it a try can you please assign me.

**Comment by warunicorn19** [comment]
@Rishi22-Coding sure!
