### ISSUE TITLE
[mesheryctl] Fully promote `mesh` command from experimental

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4312]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`mesheryctl mesh` is halfway between stable under `mesheryctl` directly and halfway in experimental under `mesheryctl exp mesh`.

#### Desired Behavior
Fully promote `mesh` from `exp` to `mesheryctl`. Verify all functionality.

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by piyushsingariya** [comment]
`mesh` command is already out of the experimental state. Closing this one!
