### ISSUE TITLE
[mesheryctl] No error output `mesheryctl system start -p gke`

### ISSUE THREAD

**Issue by anirudhjain75** [meshery/meshery#4319]
#### Current Behavior
No error output when running mesheryctl system start -p gke

#### Desired Behavior

It should state the reason as to why the command failed

#### Screenshots/Logs

```
➜  ~ mesheryctl system start -p gke
Error:
Usage:
  mesheryctl system start [flags]

Flags:
  -h, --help              help for start
  -p, --platform string   platform to deploy Meshery to.
      --reset             (optional) reset Meshery's configuration file to default settings.
      --skip-update       (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string    path to config file (default "/Users/cyna/.meshery/config.yaml")
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

#### Environment

- Host OS: Mac 
- Meshery Server Version: NA
- Meshery Client Version: stable-v0.5.62
- Platform: GKE

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by mgfeller** [comment]
This error error/bug was reported earlier, see https://github.com/meshery/meshery/issues/3986 and https://github.com/meshery/meshkit/issues/102.

**Comment by anirudhjain75** [comment]
Closing this issue as duplicate of #3986
