### ISSUE TITLE
[Docs] Inactivity: Maintainers list update

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4337]
#### Current State
One of Meshery's currently listed maintainers have been inactive for a period of two months, resulting in an automatic, assumed abandonment of role. Abishek Kumar will move to maintainer emeritus and revert to the contributor role. 

#### Implementation
Remove Abishek Kumar's name from [MAINTAINERS.md](https://github.com/meshery/meshery/blob/master/MAINTAINERS.md)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gravishpurohit** [comment]
Has this issue been fixed ?

**Comment by shubham-tyagi** [comment]
@gravishpurohit thanks for asking but I will be solving it today and if I get stuck somewhere I will surely contact you.
