### ISSUE TITLE
"using mesherctl" name on the side-bar creating confusion and sub-links not appearing on clicking the link.

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery#4339]
#### Current State
* As you can see in the below image the name of the page is "meshery CLI guide" and in the sidebar it is named "using mesheryctl", we already have a page named "using mesheryctl" which is the sub-link of "meshery CLI guides" hence the name creates confusion.
* The sublinks of "meshery CLI guides" doesn't appear on the side bar on clicking it.  

![](https://imgur.com/wPziYW8.png)

#### Desired State

* The name on sidebar should be changed to "Meshery CLI guides".
* Sublinks of it shoud appear on sidebar on clicking.
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by shubham-tyagi** [comment]
I would like to fix this.

**Comment by leecalcote** [comment]
The suggestion in your second bullet sounds good. Let's set aside the suggestion in your first bull yet point for the time being.

**Comment by shubham-tyagi** [comment]
sure @leecalcote, on it.
