### ISSUE TITLE
[Docs] update spanish home layout to match english docs site

### ISSUE THREAD

**Issue by alonsolopezr** [meshery/meshery#4346]
#### Current State
The layout of the spanish docs site has only one category, and doesn't match the layout of the english docs site
English page to translate: https://docs.meshery.io/
#### Desired State
The layout of the spanish docs site match the layout of the english docs site, with the same sections
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by KarishmaVanwari** [comment]
Can I work on this issue? @alonsolopezr
