### ISSUE TITLE
[UI] hide dialog after inserting pattern

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#4376]
#### Current Behavior

![image](https://user-images.githubusercontent.com/48255244/136671221-88439360-022c-4b5e-80ae-4f1f7ca93e74.png)
The dialog doesn't close even after inserting the pattern successfully

#### Desired Behavior

Dialog should be closed once insert button is clicked.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.meshery.io) and [Community Slack](http://slack.meshery.io)

**Comment by vedant-kakde** [comment]
I would like to work on this issue.
