### ISSUE TITLE
Failed to deploy any service mesh

### ISSUE THREAD

**Issue by gyohuangxin** [meshery/meshery#4392]
#### Current Behavior

After installing meshery with helm charts, I can not deploy any service mesh in my cluster. Take istio as an example, I tried to install istio mesh, but get errors: 
![image](https://user-images.githubusercontent.com/42127654/136912191-dcba836c-60dc-4acf-a065-0943ac71f765.png)
![image](https://user-images.githubusercontent.com/42127654/136912328-6ac98d21-5bb0-40c7-a953-ae7c8b9cedf3.png)
The pod of meshery istio will be killed, here is the log of this pod:
```
$ kc logs meshery-istio-88d8b6b4c-m5css -n meshery -f
time="2021-10-12T15:43:07Z" level=info msg="Adaptor Listening at port: 10000" app=istio-adaptor
time="2021-10-12T15:43:12Z" level=info msg="Creating instance" app=istio-adaptor
time="2021-10-12T15:43:33Z" level=info msg="Creating instance" app=istio-adaptor
time="2021-10-12T15:43:33Z" level=info msg="Applying operation istio" app=istio-adaptor
panic: runtime error: index out of range [0] with length 0

goroutine 71 [running]:
github.com/layer5io/meshery-istio/istio.(*Istio).ApplyOperation.func1(0xc000010ea8, 0xc00078eb78, 0x5, 0xc00078eb80, 0x7, 0xc00078eb87, 0x7, 0x0, 0x0, 0x0, ...)
        /build/istio/istio.go:51 +0x49a
created by github.com/layer5io/meshery-istio/istio.(*Istio).ApplyOperation
        /build/istio/istio.go:50 +0x9ba
```

#### Environment

- **Host OS:** Linux 
- **Platform:** Kubernetes v1.22.2
- **Meshery Server Version:** stable-latest
- **Meshery Client Version:** stable-latest

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@gyohuangxin is this an issue that you're experience with Meshery Istio adapter v0.5.23?
