### ISSUE TITLE
[Question] Lifecycle/istio is showing similar configurator for servish mesh.

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#4394]
#### Current Behavior

Following katakoda scenario from here: https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-istio
![image](https://user-images.githubusercontent.com/48255244/136950094-bd5325ba-8467-4145-bc3e-c2d58bdc7dfc.png)

I am seeing a lots of similar accordions doing similar things/setting up similar behaviour for istio. Is it normal?

#### Environment

- **Host OS:** Linux
- **Platform:** Docker
Client  v0.5.66  8aa1d17c
Server  v0.5.66  8aa1d17c

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Makes sense. Please see https://meshery.slack.com/archives/CLVT4TSG4/p1634039583368200?thread_ts=1634039447.367400&cid=CLVT4TSG4

**Comment by Abhishek-kumar09** [comment]
Need to verify this behaviour in the lifecycle is still exists.

**Comment by warunicorn19** [comment]
@Abhishek-kumar09 I faced this issue a couple of days back, I think it still persists

**Comment by leecalcote** [comment]
Fixed
