### ISSUE TITLE
[Docs] Online Boutique sample app link not working.

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery#4398]
#### Current State
* As you can see in the below image a link for the online boutique sample app is present.
* link is not present in the correct form, moreover when clicked it does not show anything just the screen gets blurry.
 
![](https://imgur.com/FTD8SlY.png)

#### Desired State
* fix the presentation of the link.
* fix the destination of the link.
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Zain-Muiz** [comment]
@shubham-tyagi , The image has been referenced from [here](https://github.com/meshery/meshery/tree/master/docs/assets/img/adapters/sample-apps) and has '.PNG' extension. Changing it to '.png' should fix the issue.

**Comment by shubham-tyagi** [comment]
Thanks for the suggestion, will do that @Zain-Muiz.
