### ISSUE TITLE
[Docs] Document ADAPTERS environment variable of meshery script

### ISSUE THREAD

**Issue by hexxdump** [meshery/meshery#4417]
#### Current State

While installing mesheryctl using bash installation script, we can choose which adapter to be loaded.
This is done by passing ADAPTERS environment variable to meshery bash script
Refer: https://github.com/layer5io/service-mesh-labs/issues/9
For e.g.  `curl -L https://git.io/meshery | ADAPTERS=consul PLATFORM=kubernetes bash -` installs mesheryctl and starts meshery server for kubernetes platform by loading consul adapter alone. Rest of the service mesh adapters are not loaded.
This behavior is not documented yet.

#### Desired State
Add an example of how to install only a select adapters while installing mesheryctl
https://docs.meshery.io/installation/mesheryctl
It could also be mentioned as part of the multiple adapters FAQ page
https://docs.meshery.io/guides/multiple-adapters

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by chetak123** [comment]
Can I take this issue please ?
