### ISSUE TITLE
[Docs] CNCF name in the Logo is not visible in Dark mode

### ISSUE THREAD

**Issue by ghulamyazdani** [meshery/meshery#4425]
#### Current State
In the readme.md file CNCF name in the logo is not visible while in Dark mode .
![image](https://user-images.githubusercontent.com/55938346/137483761-c37ba5dd-c6c5-4391-b3dd-e251f561c880.png)

#### Desired State
Add LOGO which has better visibility in Dark mode as well.
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by shreyaansjain06** [comment]
I want to do this can you assign this issue to me

**Comment by shreyaansjain06** [comment]
So should i start working on this?

**Comment by KarishmaVanwari** [comment]
Can I work on this issue? @ghulamyazdani
