### ISSUE TITLE
[UI][Doc] Broken Image In Meshery Docs

### ISSUE THREAD

**Issue by Zain-Muiz** [meshery/meshery#4435]
#### Current Behavior
The image at [Guides](https://docs.meshery.io/guides/sample-apps#online-boutique) at docs.meshery.io is broken.

#### Desired Behavior
Have the image fixed.

### Identified issue cause
The image has been referenced from [here](https://github.com/meshery/meshery/tree/master/docs/assets/img/adapters/sample-apps) and has '.PNG' extension. Changing it to '.png' should fix the issue.

#### Screenshots/Logs

![Screenshot (152)](https://user-images.githubusercontent.com/60746360/137577213-e248c943-ca18-411b-9a4f-a3545ce398c4.png)

#### Environment

- Browser: Chrome
- Host OS: Windows

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@Zain-Muiz already an open issue on this. https://github.com/meshery/meshery/issues/4398

**Comment by Zain-Muiz** [comment]
@warunicorn19 , Oh Okayy ! I think The solution to this issue wasnt updated over there. The actual issue is updated here in the description. Do I close this issue or close the other one and tag the assignee over here ?

**Comment by Zain-Muiz** [comment]
Thankyou for pointing out @warunicorn19 ! ♥
