### ISSUE TITLE
[mesheryctl] `channel switch` does not check the release channel of the current deployment

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#4444]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system channel switch stable` will switch the channel to `stable-latest` and redeploy Meshery even though there is a running deployment of Meshery with the `stable-latest` channel.

![Screenshot 2021-10-18 at 4 19 40 PM](https://user-images.githubusercontent.com/49474499/137717834-cdd1c7a4-c610-476b-a9c6-ddce358bbdb1.png)

#### Desired Behavior

`mesheryctl` should check the `/api/system/version` endpoint and check the current channel and version of the current running deployment and only proceed to deploy Meshery if the versions are different and should say something like "you are already running <channel-version> right now. Go to <Meshery endpoint> to access Meshery".

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by amino19** [comment]
@navendu-pottekkat: I would like to work on this issue!
At the same time, need all your guidance & support, as I just started with Golang, doesn't have much experience.

**Comment by navendu-pottekkat** [comment]
Sure @amino19 You can try this out.

**Comment by MUzairS15** [comment]
@navendu-pottekkat @leecalcote I would like to try.

**Comment by leecalcote** [comment]
@MUzairS15 thanks for raising your hand. Let’s close out this issue and leave the behavior as-is for now. :heavy_check_mark:
