### ISSUE TITLE
[UI] GraphQL subscription gives out undefined

### ISSUE THREAD

**Issue by bariqhibat** [meshery/meshery#4452]
#### Current Behavior

When loading the main dashboard, graphql subscription for control and dataplane states can be established. Data is transferred and it can confirmed by looking into the Network tab in Developer Tools in Chrome (or anything similar in other browsers) and even in GraphQL playground, data is successfully fetched. However, in the Relay graphql subscription, data is undefined.

#### Desired Behavior

Data is not undefined and able to update the states real time

#### Screenshots/Logs

https://user-images.githubusercontent.com/54849895/144454615-986d7277-32ff-4cbc-8123-cefafaf6dbbf.mp4

#### Environment

- Browser: Chrome 
- Host OS: Windows (WSL)
- Meshery Server Version: edge-latest
- Meshery Client Version: edge-latest
- Platform: Docker

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by bariqhibat** [comment]
Do you have any idea why this happens? @dhruv0000

**Comment by bariqhibat** [comment]
You might take a look here @sudo-NithishKarthik

**Comment by sudo-NithishKarthik** [comment]
Will do @bariqhibat
