### ISSUE TITLE
[mesheryctl] UX Regression: `system start` with helm-based deployment

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4460]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Let's give additional consideration to the user experience when someone attempts to start Meshery on a Kubernetes cluster that has a prior (helm-based) deployment.

```
➜  ~ mesheryctl system status
Meshery is not running. Run `mesheryctl system start` to start Meshery.
➜  ~ mesheryctl system start
Starting Meshery...
⣾ Deploying Meshery on Kubernetes Error: failed to start Meshery
See https://docs.meshery.io/reference/mesheryctl/system for usage details
: cannot start Meshery: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "meshery-operator" in namespace "meshery" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "meshery"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "meshery"
Usage:
  mesheryctl system start [flags]

Flags:
  -h, --help              help for start
  -p, --platform string   platform to deploy Meshery to.
      --reset             (optional) reset Meshery's configuration file to default settings.
      --skip-update       (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string    path to config file (default "/Users/lee/.meshery/config.yaml")
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

This experience is far removed from the previously, highly curated / guided experience.

#### Desired Behavior

1. There’s no specific Meshkit error code provided. Ideally, no error code is shown, however. We need to anticipate that users will start and stop clusters that have Meshery deployments.
2. system start’s behavior should be such that if a deployment existing, then that deployment should be reinitialized. 

#### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.5.67
- Meshery Client Version: stable-v0.5.67
- Platform: Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
This is similarly related to #4578
