### ISSUE TITLE
[Docs] - Incorrect version in Helm installation

### ISSUE THREAD

**Issue by lucj** [meshery/meshery#4467]
#### Current State

$ helm install my-meshery meshery/meshery --version 2.1.2
$ helm install --set key=value --set key=value my-meshery meshery/meshery --version 2.1.2

#### Desired State

$ helm install my-meshery meshery/meshery --version 0.5.67
$ helm install --set key=value --set key=value my-meshery meshery/meshery --version 0.5.67

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sayantan1413** [comment]
@leecalcote according to the conversation here https://meshery.slack.com/archives/CFGG6U10E/p1634917047004000 I guess @lucj wants the change in the docs.meshery.io only because I guess there is no version problem in the Github workflow for Helm chart. He actually faced an error while copy pasting these commands from Meshery Docs to install Meshery via Helm.

**Comment by leecalcote** [comment]
> @leecalcote according to the conversation here https://meshery.slack.com/archives/CFGG6U10E/p1634917047004000 I guess @lucj wants the change in the docs.meshery.io only because I guess there is no version problem in the Github workflow for Helm chart. He actually faced an error while copy pasting these commands from Meshery Docs to install Meshery via Helm.

@sayantan1413 thank you for clarifying. We shouldn't specify the version to install. The version installed should be presumed "latest". Any issue with this approach (not specifying the version number in the install instructions), @Aisuko?

**Comment by lucj** [comment]
This approach sounds better 👍

**Comment by Aisuko** [comment]
> > @leecalcote according to the conversation here https://meshery.slack.com/archives/CFGG6U10E/p1634917047004000 I guess @lucj wants the change in the docs.meshery.io only because I guess there is no version problem in the Github workflow for Helm chart. He actually faced an error while copy pasting these commands from Meshery Docs to install Meshery via Helm.
> 
> @sayantan1413 thank you for clarifying. We shouldn't specify the version to install. The version installed should be presumed "latest". Any issue with this approach (not specifying the version number in the install instructions), @Aisuko?

For sure, we released the version list here https://artifacthub.io/packages/helm/meshery/meshery, and the if here is not set a specific version, the `helm` would installs the latest version(current latest version is 0.5.67). As @leecalcote said, we already changed the process to the Github Action, and the doc may refer to the old process.
