### ISSUE TITLE
[Docs] Katacoda: "Interactive Lab for Meshery Adapter for Istio" enters vim mode in "Setup Meshery" section 

### ISSUE THREAD

**Issue by Dentrax** [meshery/meshery#4512]
#### Current State

https://docs.meshery.io/service-meshes/adapters/istio

![Screen Shot 2021-10-27 at 23 02 51](https://user-images.githubusercontent.com/16493751/139138553-882169ca-fb3a-4d26-b550-a4109f11304b.png)

#### Desired State

It should not enter Vim mode after run the following command:
```bash
$ curl -L https://git.io/meshery | ADAPTERS=istio PLATFORM=docker bash -
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@asubedy perhaps, something you might address...

**Comment by asubedy** [comment]
@leecalcote I thought that was normal, is it a bug? 🤔  Whenever I encountered it I open a new terminal and run the necessary commands.
