### ISSUE TITLE
[Docs] Functionality has wrong link 

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4525]
#### Current State
The big `Functionality` button leads to the Guides page.

<img width="1440" alt="Screenshot 2021-10-29 at 11 34 45 PM" src="https://user-images.githubusercontent.com/53532328/139482176-580d9a35-79f7-4b6f-917e-101da610d3db.png">
#### Desired State

The button should lead to the Functionality page. [link](https://docs.meshery.io/functionality)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by SusmithBarigidad** [comment]
I can take this
