### ISSUE TITLE
[UI] Selected row name change

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#4528]
#### Current Behavior
when selected a row from the table, it appears ()rows selected.

#### Desired Behavior
change that rows selected to configuration type, example: ()pattern(s) selected / ()filter(s) selected .....

#### Implementation
Implement this for patterns, filters, applications, and performance profiles

#### Mockups
![issuename](https://user-images.githubusercontent.com/65453826/139630581-b40397e5-d10a-40d3-b94c-825047b8bed3.jpg)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by theBeginner86** [comment]
I'd like to give it a shot. Can you please assign it to me?

**Comment by sayantan1413** [comment]
Sure @theBeginner86 go ahead 🚀

**Comment by theBeginner86** [comment]
Please have a look at the PR 😁😊
