### ISSUE TITLE
[Docs] Breadcrumbs routing issue

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery#4546]
#### Current State
Once we go to `home / reference / command reference`, and click on an argument of any main command, say `start` argument  of  `system` command, it takes you to `home / reference / mesheryctl / system / mesheryctl system start` .As of now we can't go back one step backward on `home / reference / mesheryctl / system` by clicking on `system` due to the routing issue .
 
![](https://imgur.com/Pb9VbMS.png)

We have such routing issues on almost all arguments of main commands on https://docs.meshery.io/reference/mesheryctl. 
#### Desired State
Redirect user to desired page.
#### How can it be solved ?
A similar issue has been solved using this PR #4476 . You can see this PR as a reference to solve this issue. If you still have any doubt, feel free to reach out.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@shubham-tyagi could you please give the link to the PR that you made instead of the issue.

**Comment by shubham-tyagi** [comment]
Yeah sure @warunicorn19

**Comment by adithyaakrishna** [comment]
@sidecodes This is a similar issue (#4561) but related to breadcrumbs, would you like to take this up? 👀

**Comment by sidecodes** [comment]
Sure, I will take this. @adithyaakrishna
