### ISSUE TITLE
[mesheryctl] `system update`: Error: cannot update Meshery: "meshery" has no deployed releases

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4549]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
While upgrading to v0.5.68 on a system with no active Meshery deployment, the following error is displayed when running `mesheryctl system update`.

#### Screenshots/Logs
```
Meshery is not running. Nothing to stop.
➜  ~ mesheryctl system update
A new release of mesheryctl is available: v0.5.67 → v0.5.68
https://github.com/layer5io/meshery/releases/tag/v0.5.68
Check https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli for instructions on how to update mesheryctl

Updating Meshery...
Error: cannot update Meshery: "meshery" has no deployed releases
Usage:
  mesheryctl system update [flags]

Flags:
  -h, --help         help for update
      --skip-reset   (optional) skip checking for new Meshery manifest files.

Global Flags:
      --config string    path to config file (default "/Users/lee/.meshery/config.yaml")
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

#### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.5.68
- Meshery Client Version: stable-v0.5.67
- Platform: Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by fallmor** [comment]
hello i can work on this issue

**Comment by leecalcote** [comment]
@fallmor, oh, no. I missed your message. Yes, please jump in. Will you first confirm that you can reproduce this issue?

**Comment by MarioArriaga92** [comment]
@leecalcote I just reproduced this issue, hoping this is of help to find repro steps **(it apparently stops happening with the `--skip-reset` flag for some unknown reason)**:
```
$ mesheryctl version
        VERSION         GITSHA      
Client  v0.6.8          931b5bbee  
Server  unavailable     unavailable
Unable to communicate with Meshery server.Get "http://localhost:9081/api/system/version": dial tcp [::1]:9081: connect: connection refused.See https://docs.meshery.io for help getting started with Meshery

Checking for latest version of mesheryctl...

  v0.6.8 is the latest release.
$ mesheryctl system update
Updating Meshery...
Error: cannot update Meshery: "meshery" has no deployed releases
$ mesheryctl system update --skip-reset
Updating Meshery...
Starting Meshery...

Meshery deployed on Kubernetes.
Meshery is starting...
Opening Meshery (http://localhost:9081) in browser.
... updated Meshery in the Kubernetes Cluster.
Meshery is now up-to-date
$ mesheryctl version
        VERSION GITSHA    
Client  v0.6.8  931b5bbee
Server  v0.6.8  931b5bbe 

Checking for latest version of mesheryctl...

  v0.6.8 is the latest release.
```

**Comment by MarioArriaga92** [comment]
I had upgraded from mesheryctl v0.6.4 before bumping into above error btw

**Comment by leecalcote** [comment]
Oh, right. In and respects all bets are off post `v0.6.7` as changes to the structure of the helm charts have been implemented. These changes have been implemented to circumvent issues like the one described above. I wonder if you run into any of the same challenge using the `v0.6.8` release.

**Comment by MarioArriaga92** [comment]
The issue stops reproducing after `mesheryctl system update --skip-reset` with v0.6.8, but if flag isn't used it keeps happening

**Comment by leecalcote** [comment]
Thanks for this. Allow me to close out this issue as I consider that the ROI diminishes for new users.

As a test, you could install v0.6.7, then `system update` to v0.6.8 and see if you have the same experience.
