### ISSUE TITLE
[Docs] Breadcrumbs routing issue

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery#4565]
#### Current State
Once we go to `home / reference / command reference`, and click on an argument of any main command say, `apply` argument  of  `perf` command, it takes you to `home / reference / mesheryctl / perf / mesheryctl perf apply`. As of now, we can't go back one step backward on `home / reference / mesheryctl / perf` by clicking on `perf` due to the routing issue on this page https://docs.meshery.io/reference/mesheryctl/perf/apply. Similarly we cant go to these:

-  `home / reference / mesheryctl / mesh` by clicking on `mesh` on this page
https://docs.meshery.io/reference/mesheryctl/mesh/validate.
-  `home / reference / mesheryctl / mesheryctl pattern` by clicking on `pattern` on this page https://docs.meshery.io/reference/mesheryctl/apps/onboard.
- `home / reference / mesheryctl / mesheryctl app` by clicking on `app` on this page https://docs.meshery.io/reference/mesheryctl/apps/onboard.

#### Desired State
Redirect user to desired page.

#### How can it be solved ?
A similar issue has been solved using this PR #4564 . You can see this PR as a reference to solve this issue. If you still have any doubt, feel free to reach out.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Et-008** [comment]
Can i work on this issue?

**Comment by leecalcote** [comment]
Sounds great, @Et-008 👍
