### ISSUE TITLE
[Pattern] Label name starts with whitespace

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#4567]
#### Current Behavior
The setting's name starts with whitespace which is creating problems with assigning keys to values in the pattern configurator.
See Destination Rule :arrow_double_down:  
![image](https://user-images.githubusercontent.com/48255244/140508286-e2944d87-7570-428e-87b4-ab793ef5e0aa.png)

#### Expected Behavior

The names/types should be trimmed

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ishitakeshawani** [comment]
I like to take it if no one is on it.

**Comment by warunicorn19** [comment]
Sounds good @ishitakeshawani.

**Comment by ishitakeshawani** [comment]
I got the idea to use trim but I do not know how to test it. I am able to run Meshery UI in local code editor. Can anyone guide me please?
I am using windows.

**Comment by Abhishek-kumar09** [comment]
You have to start local development for this. 
https://docs.meshery.io/project/contributing/contributing-ui
Did you tried it?
Steps:
1. make setup-ui-libs
2. make build-ui
3. make run-local  --> to start server on port 9081
4. make run-ui-dev --> to start UI on port 3000

**Comment by leecalcote** [comment]
@Revolyssup is this something that you can have addressed in the adapter library or MeshKit?

**Comment by Abhishek-kumar09** [comment]
This is Fixed with pull/585 in meshery-extensions
@leecalcote
