### ISSUE TITLE
[Bug] Meshery isn't starting when resource already exists in k8s cluster and namespace is deleted

### ISSUE THREAD

**Issue by alphaX86** [meshery/meshery#4578]
#### Current Behavior

Due to some issues, I had to remove Meshery by deleting namespace in my k8s cluster, plus the `.meshery` folder too. But when I reinstalled, the manifests got downloaded but couldn't start up because some resources (Clusterroles, Clusterrolebinding) already exists in the cluster.

Logs:
```bash
admin-pc@LAPTOP-RROSUK8P:/mnt/d/XCodes/meshery/mesheryctl$ ./mesheryctl system start
Starting Meshery...
⢿ Deploying Meshery on Kubernetes Error: failed to start Meshery
See https://docs.meshery.io/reference/mesheryctl/system for usage details
: cannot start Meshery: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "meshery-metrics-reader" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "meshery"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "meshery"
Usage:
  mesheryctl system start [flags]
.......
```

Do note that I deleted the namespace, turns out that some resources are left uninstalled. I had to remove them manually

#### Expected Behavior

An uninstall option should be present (just a suggestion), so that if users face problem they can reinstall Meshery without issues. Plus, this note must be considered as we're moving to Helm charts for install from version v0.6.0

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/59508546/140644722-1fa13a67-afb2-4150-9de8-5229dbaf6a58.png)

![image](https://user-images.githubusercontent.com/59508546/140644732-283e17ad-774f-466a-bd4e-584d0580fe0e.png)

#### Environment

- **Host OS:** Linux (Ubuntu 20.04) via WSL2
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v0.5.71
- **Meshery Client Version:** stable-v0.5.71

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by navendu-pottekkat** [comment]
@panyuenlau @Aisuko Another issue with deploying Meshery.

**Comment by Aisuko** [comment]
I wondering, did we already change the deployment function to meshery-operator while use `mesheryctl` command?

**Comment by leecalcote** [comment]
@DelusionalOptimist

**Comment by Aisuko** [comment]
Hi guys, Could we confirm this issue already be fixed?

**Comment by alphaX86** [comment]
IG this issue is sorted via the solution provided in the Discourse forum. So are we good to close this issue then?

**Comment by leecalcote** [comment]
@piyushsingariya, do you know?

**Comment by piyushsingariya** [comment]
This is solved with the recent addition in `stop` command via `--force` flag. Closing this one!
