### ISSUE TITLE
[Docs]Adapter earliest version not showing in individual pages

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4589]
#### Current State
The earliest version of the adapters are not getting printed on the individual adapter pages. 
<img width="1440" alt="Screenshot 2021-11-09 at 5 11 17 PM" src="https://user-images.githubusercontent.com/53532328/140917947-7bbfbbe0-51bc-4ba9-be9c-a9621939c69e.png">

#### Desired State
The earliest version of the adapters should get printed. 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Rahulkumar2002** [comment]
> #### Current State
> The earliest version of the adapters are not getting printed on the individual adapter pages. <img alt="Screenshot 2021-11-09 at 5 11 17 PM" width="1440" src="https://user-images.githubusercontent.com/53532328/140917947-7bbfbbe0-51bc-4ba9-be9c-a9621939c69e.png">
> 
> #### Desired State
> ## The earliest version of the adapters should get printed.
> #### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
> * 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
> * 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
>   
>   * Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
> * 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
> * 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

Hello can I take this issue . I think I sorted the issue there isn't any content inside the <td></td> tag of that page .
![Screenshot (172)](https://user-images.githubusercontent.com/88898222/141307525-03b5745d-7e87-4129-8fc8-367ef54cff92.png)
![Screenshot (173)](https://user-images.githubusercontent.com/88898222/141307558-2ede917e-a051-4bd8-84bc-962094070455.png)

**Comment by Rahulkumar2002** [comment]
Can you point me to this file's directory pls? Thank u

**Comment by theBeginner86** [comment]
hey @warunicorn19, may I work in this one?

**Comment by Mr-DG-Wick** [comment]
> Can you point me to this file's directory pls? Thank u

@Rahulkumar2002 if you use vs code, then the search feature is very handy in finding the files you desire :)

**Comment by theBeginner86** [comment]
I've made a PR. Please have a look 👍
