### ISSUE TITLE
[mesheryctl] `system config minikube` panic

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4592]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Failure to flatten minikube certs into meshconfig.

Please note the Meshery Server Version: edge-v0.5.61.

#### Screenshots/Logs
```
➜  meshery-extensions git:(heads/master) ✗ mesheryctl system config minikube
Configuring Meshery to access Minikube...
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/layer5io/meshery/mesheryctl/internal/cli/root/system.getContexts(0xc0001ac360, 0x23, 0xc0002036e0, 0x1d, 0xc000637ba0, 0x1, 0x1, 0x0, 0xc00043b660)
	/Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/system/config.go:77 +0x5a9
github.com/layer5io/meshery/mesheryctl/internal/cli/root/system.setToken()
	/Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/system/config.go:367 +0xf9
github.com/layer5io/meshery/mesheryctl/internal/cli/root/system.glob..func11(0x42db940, 0x44bd0b0, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/system/config.go:329 +0x545
github.com/spf13/cobra.(*Command).execute(0x42db940, 0x44bd0b0, 0x0, 0x0, 0x42db940, 0x44bd0b0)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x42d2fc0, 0x32ca5c0, 0x44bd0b0, 0x0)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
	/Users/runner/work/meshery/meshery/mesheryctl/internal/cli/root/root.go:68 +0x56
main.main()
	/Users/runner/work/meshery/meshery/mesheryctl/cmd/mesheryctl/main.go:22 +0x25
```

#### Environment

- Host OS: Mac 
- Meshery Server Version: edge-v0.5.61
- Meshery Client Version: stable-v0.5.71
- Platform: Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by hexxdump** [comment]
@leecalcote,
If flattening of the minikube config has failed, the below code would have gracefully exited.

```
                // Flatten the config file
		err = clientcmdapi.FlattenConfig(config)
		if err != nil {
			log.Fatal("Error flattening config:", err)
			return err
		}
```
Instead the failure is seen in setToken() -> getContext() function after unmarshalling the response of `GET /api/system/kubernetes/contexts`
Let me check try to reproduce this issue.

**Comment by hexxdump** [comment]
I have not seen this issue in my setup, however the exception needs to be gracefully handled.

**Comment by leecalcote** [comment]
Good, good, good.
