### ISSUE TITLE
[mesheryctl] `perf` examples are outdated

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4605]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Users of `mesheryctl perf` are presented with the following output:

```
➜  ~ mesheryctl perf
Error: requires at least 1 arg(s), only received 0
Usage:
  mesheryctl perf [flags]
  mesheryctl perf [command]

Examples:

// Run performance test
mesheryctl perf apply --profile test --name \"a quick stress test\" --url http://192.168.1.15/productpage --qps 300 --concurrent-requests 2 --duration 30s --token \"provider=Meshery\"

// List performance profiles
mesheryctl perf profile

// List performance results
mesheryctl perf result


Available Commands:
  apply       Run a Performance test
  profile     List performance profiles
  result      List performance test results

Flags:
  -h, --help                   help for perf
  -o, --output-format string   (optional) format to display in [json|yaml]
  -t, --token string           (required) Path to meshery auth config

Global Flags:
      --config string   path to config file (default "/Users/lee/.meshery/config.yaml")
  -v, --verbose         verbose output

Use "mesheryctl perf [command] --help" for more information about a command.
```

The first example doesn't work and returns an error about an unknown token. Removing the token causes a second error about an unspecified profile name. 

#### Desired Behavior
Users should be able to copy and paste these examples and run them successfully.

#### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.5.71
- Meshery Client Version: stable-v0.5.71
- Platform: Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
// @piyushsingariya

**Comment by alphaX86** [comment]
Taking this up now!
