### ISSUE TITLE
unable to download performance test result

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#4606]
#### Current Behavior
When working with the local provider and downloading result for a performance test, it fails with a 500. Probably because of being unable to read data from the database.

#### Expected Behavior
Be able to download performance test result.

#### Screenshots/Logs
Logs from meshery server:
```
time="2021-11-11T20:42:36Z" level=error msg="sql: Scan error on column index 5, name \"result\": unsupported Scan, storing driver.Value type []uint8 into type *map[string]interface {}"
```

#### Environment

- **Host OS:** Linux
- **Platform:** Kubernetes
- **Meshery Server Version:** edge-latest
- **Meshery Client Version:** edge-latest

#### To Reproduce
1. Sign in with the local provider
2. Go to performance management page
3. Create a performance test
4. Try downloading its result,
5. See error
![2021-11-12_02-17](https://user-images.githubusercontent.com/54525605/141366772-25ef2f96-e27e-4548-8a38-0e40a39e9512.png)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by DelusionalOptimist** [comment]
@Revolyssup guessing from the error, could this be because of the recent DB migration?

**Comment by Revolyssup** [comment]
> @Revolyssup guessing from the error, could this be because of the recent DB migration?

Performance tests were migrated to sqlite months ago. The recent migration was of smi results and preference. Looking into this now...

**Comment by Revolyssup** [comment]
@leecalcote  @DelusionalOptimist  Got the issue, it was due to an 8 month old change. I have no idea how @DelusionalOptimist  just caught it now, it was due to not converting into proper struct after retrieving from database. Creating the PR now
