### ISSUE TITLE
[UI] Performance test result count not updating upon test completion

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4607]
#### Current Behavior
When a performance test completes, the test result count for that performance profile should increase, too.

#### Screenshots/Logs

<img width="1022" alt="Screen Shot 2021-11-11 at 4 16 45 PM" src="https://user-images.githubusercontent.com/7570704/141377040-40106306-63f6-40bc-aaad-b15c6a41d352.png">

#### Environment

- Browser:  Safari 
- Host OS: Mac
- Meshery Server Version: stable-v0.5.71
- Meshery Client Version: stable-v0.5.71
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Mr-DG-Wick** [comment]
Hi @manav1403 👋🏽 
Did you find time to look into this one?

**Comment by manav1403** [comment]
I am looking into it.

**Comment by leecalcote** [comment]
@manav1403 @bariqhibat do we have a subscription for performance test results?
