### ISSUE TITLE
[Docs] Broken images

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4634]
#### Current State
The images on the page for [NSM](https://docs.meshery.io/service-meshes/adapters/nsm#2-vpp-icmp-application) have broken images.
<img width="1440" alt="Screenshot 2021-11-17 at 8 56 02 PM" src="https://user-images.githubusercontent.com/53532328/142229806-5e4665b2-bcdb-447c-ae42-564e59d309f3.png">

#### Desired State
They shouldn't be broken. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by shardulinamdar4** [comment]
Can I work on this?

**Comment by warunicorn19** [comment]
Sounds good @shardulinamdar4

**Comment by 7suyash7** [comment]
Hey, can I work on this?

**Comment by Mr-DG-Wick** [comment]
@7suyash7 this issue has recently been assigned to @shardulinamdar4 . You may look into other issues in the meanwhile :)

**Comment by 7suyash7** [comment]
That's fine, can you point me towards other beginner-friendly issues, I'm trying to complete the 5 PRs as I have applied for the LFX fellowship with Meshery.

**Comment by leecalcote** [comment]
@7suyasplease that's great. Please find the "help wanted" link in the readme.md of all of the ~70 repos between the projects of which Layer5 is a steward. 

Be sure to do your homework before asking for help.

**Comment by 7suyash7** [comment]
@leecalcote thanks for the help!!

**Comment by Mr-DG-Wick** [comment]
Any progress here ? @shardulinamdar4 😃

**Comment by 14Richa** [comment]
Is this issue solved? I can't see any broken images. Attaching the screenshot. 
![Screenshot from 2021-12-10 12-43-15](https://user-images.githubusercontent.com/41283476/145532765-6a56f70e-16bb-4ad9-9729-4fe505a64fd0.png)

**Comment by warunicorn19** [comment]
Yup @14Richa this is still an issue, I've provided the link in the issue.
 https://docs.meshery.io/service-meshes/adapters/nsm#2-vpp-icmp-application

Would you like to take a look at this?

**Comment by 14Richa** [comment]
Yes, I would like to take this.

**Comment by warunicorn19** [comment]
Sounds good.

**Comment by 14Richa** [comment]
Locally, I am able to see the image. Probably it is a resource error. Attaching the screenshot. Kindly help?
![Screenshot from 2021-12-10 18-26-26](https://user-images.githubusercontent.com/41283476/145577642-4898d884-d5f0-41ee-bdb1-dd7479ef0f31.png)
