### ISSUE TITLE
[UI] Create custom error page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4639]
#### Current Behavior
Users occasionally bump into "unexpected error" messages in Meshery UI. See example screenshot.

<img width="1237" alt="Screen Shot 2021-11-17 at 4 18 41 PM" src="https://user-images.githubusercontent.com/7570704/142291656-ecc5705c-9af5-4b41-9efd-0212b367ae33.png">

#### Desired Behavior
Akin custom 404 error pages on websites, it would be nice for Meshery UI to have custom error message that both captures some snark and offers a path to resolution with link to the [community discussion forum](https://discuss.layer5.io/c/meshery/5)

For examples of appropriate snark, visit any non-existing link on layer5.io (e.g. https://layer5.io/bad-link) and refresh the page a few times to see different messages.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by theBeginner86** [comment]
May I work on this one?

**Comment by Mr-DG-Wick** [comment]
Sounds great! @theBeginner86

**Comment by Mr-DG-Wick** [comment]
Any progress on this one ? @theBeginner86 :)

**Comment by theBeginner86** [comment]
> Any progress on this one ? @theBeginner86 :)

I was working on that only. At the moment I'm trying to figure our in what scenarios does Meshery throws that error. After that I would be creating a component (with the specification mentioned in the issue) to be rendered in place of that error message.
Will soon update with a mockup for the component that would be rendered 😃

**Comment by Mr-DG-Wick** [comment]
> > Any progress on this one ? @theBeginner86 :)
> 
> I was working on that only. At the moment I'm trying to figure our in what scenarios does Meshery throws that error. After that I would be creating a component (with the specification mentioned in the issue) to be rendered in place of that error message. Will soon update with a mockup for the component that would be rendered 😃

Sounds great @theBeginner86 😄

**Comment by warunicorn19** [comment]
@theBeginner86 it could be as simple as just a syntax error, you'd just have to add a custom error page when there's an empty state due to said error.

**Comment by theBeginner86** [comment]
Progress:

https://user-images.githubusercontent.com/73700530/143561049-fe3a727f-983a-49fd-8fa4-d1b800cac37c.mov

Since I was not good with graphics so I reused the ones which we are using on our Meshery website (404 page)

Any suggestion on UI?
@Mr-DG-Wick @warunicorn19

**Comment by warunicorn19** [comment]
This is looking good, though I'll still try to spend some time in coming up with a new graphic. One thing you could do is instead of putting a button for the discussion forum you could just add an (`<a>`) href to the word "discussion forum" in the above sentence.

**Comment by theBeginner86** [comment]
> This is looking good, though I'll still try to spend some time in coming up with a new graphic. One thing you could do is instead of putting a button for the discussion forum you could just add an (`<a>`) href to the word "discussion forum" in the above sentence.

Ok!! I'll add that in the sentence.

One doubt I had, this page is different from the 404 page on Meshery, right?
