### ISSUE TITLE
[UI] Change pointer to hand when hovering on release version link

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4647]
#### Current Behavior
The small external link arrow should displays an arrow pointer onhover.

#### Desired Behavior
The small external link arrow should display a "hand" pointer onhover.

#### Screenshots/Logs
On the main Meshery UI dashboard...

<img width="927" alt="Screen Shot 2021-11-19 at 8 22 47 PM" src="https://user-images.githubusercontent.com/7570704/142711232-f25296df-7845-46bc-b3b9-79ecbb70d3df.png">

The following issue can be seen...

https://user-images.githubusercontent.com/7570704/142711230-0b890b82-3e81-4ea9-b3c2-9447a63bff81.mov

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by chetak123** [comment]
Can I take up this issue please

**Comment by toth2000** [comment]
Sure @chetak123

**Comment by Mr-DG-Wick** [comment]
Any progress on this one ? @chetak123  :)

**Comment by chetak123** [comment]
Actually I was having some issues in creating meshery-ui development environment, have solved most of them 😅

**Comment by Mr-DG-Wick** [comment]
ohh got it 👍🏽

**Comment by arunkarthicknm** [comment]
Can anyone please tell me if this issue is solved??

**Comment by chetak123** [comment]
Hey @arunkarthicknm , I am actually a little bit busy right now (due to my sem exam), so if you want then please go for it otherwise I will get back to it if it's still available in future.

**Comment by arunkarthicknm** [comment]
Sure!!

**Comment by 14Richa** [comment]
Hi @Mr-DG-Wick  I went ahead and put a little fix for the issue. It looked like there wasn't any activity recently. Please take a look and approve the PR if it works for you.

**Comment by Chadha93** [comment]
https://github.com/meshery/meshery/pull/4757#pullrequestreview-829302613
