### ISSUE TITLE
[Docs] "Espanol" link on the docs home page not working.

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery#4652]
#### Current State
after clicking on **"Espanol"** which is on the top right corner, we cant go to the Spanish language page of our docs.
 
![](https://imgur.com/qporAD4.png)

#### Desired State
We should be able to go on the Spanish language page after clicking on it.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by varunsaral** [comment]
The 0.5 version of doc have this snippet (in github)
 <li class="nav-item mr-4 mb-2 mb-lg-0">
          <a
            class="nav-link"
            **href="/v0.5/es"**
            ><span>🇲🇽 Español</span></a
          >
        </li>

which is correct , if we visit  https://docs.meshery.io/es or https://docs.meshery.io/v0.5/es we get correct documentation 

but on the serving website ,

<li class="nav-item mr-4 mb-2 mb-lg-0">
            
            
              <a class="nav-link" **href="https://docs.meshery.io/"**>
            

            <span>🇲🇽 Español</span></a
                >
            </li>

the link is broken , that means it's not it sync with correct code. I'm new to jeykll but this is the issue i found

**Comment by varunsaral** [comment]
After learning about jeykll , i tried looking for the loop of navbar so i can correct the links , but it was not in index.md nor in layout folder(i thought it available on each page so it must be applied through layout) , if someone find it , please fix it . I'm trying to look for it for past 12 hours :)

**Comment by warunicorn19** [comment]
Hey @varunsaral, thanks for taking the time and looking into this, but you're looking in the wrong place😅, the header is actually an _includes file (since it is on every page). You might want to take a look at header.html that's where you'll find this. 

Also, if you have any other problems you could join our slack workspace and ask there: https://join.slack.com/t/meshery/shared_invite/zt-rgbyt4kj-6PUUyqY9SfQGRSt_oZV9yQ

**Comment by shubham-tyagi** [comment]
hey @varunsaral, thanks for your time, you will have to edit this file https://github.com/meshery/meshery/blob/master/docs/_includes/header.html to be able to solve the issue.
In this file under the for loop, you will find an if condition `{%- if link.url== 'es' -%}` under which you will have to modify the code. If you have more questions regarding anything related to meshery please join our slack workspace.

**Comment by warunicorn19** [comment]
Also, I just took a look, the code under `<!--Internal Links -->` is actually useless, it's complicated for no reason at all. We could change that entire portion to just be, 
```
{% for link in site.data.navigation %}
        <li class="nav-item mr-4 mb-2 mb-lg-0">
          <a
            class="nav-link"
            href="{% if link.url %}{{ site.baseurl }}/{{ link.url }}{% else %}{{ link.external_url }}{% endif %}"
            ><span>{{ link.title }}</span></a
          >
        </li>
        {% endfor %}
      </ul>
    </div>
```

**Comment by shubham-tyagi** [comment]
@warunicorn19 I agree, It is very complicated. To solve this issue I initially used a flag variable, making the code more complicated (though working) 😂

```
{% for link in site.data.navigation %} 
          {%- if link.url== 'es' -%} 
            {% assign urlSliced = site.url | split: "/" %} 

            {% assign pageUrl = page.url %}
            {% assign verString = "" %}
            {% assign flag = false %}
            {% comment %} get which version we are on {% endcomment %}
            {% for version in site.data.versions %}
              {% if page.url contains version.url %}
                {% assign verString = version.url %}
                {% comment %} get the sting with the version in the PAGE URL {% endcomment %}
                {% capture verString %}/{{verString}}/{% endcapture %}
                {% capture verStringEs %}{{verString}}/es/{% endcapture %}
                {% assign flag = true %}
              {% endif %}
            {% endfor %} 

            {% comment %} get the new url with the 'es' on it {% endcomment %}
            {% if flag == true %}
            {%- capture newPageUrl -%}{{ pageUrl }}/es{%- endcapture -%}
            {% else %}
            {%- capture newPageUrl -%}{{ pageUrl | replace: verString, verStringEs }}{%- endcapture -%}
            {% endif %}
```

**Comment by shubham-tyagi** [comment]
Hey @varunsaral, if you understood what exactly is needed to be done. would you like to submit a PR for this issue?

**Comment by warunicorn19** [comment]
yeah, this makes sense as well, but not really required, I think it'd be best if we remove it. I assume you have docs running could you please check what I wrote works or not? I haven't actually tested it out😅.

**Comment by shubham-tyagi** [comment]
yes, it does work. I just tested it @warunicorn19

**Comment by varunsaral** [comment]
> Hey @varunsaral, if you understood what exactly is needed to be done. would you like to submit a PR for this issue?

Yes i understood it now , submiting a PR right away

**Comment by shubham-tyagi** [comment]
@varunsaral Thanks for taking this up.
