### ISSUE TITLE
SMI Conformance failing with all service mesh

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#4655]
#### Expected Behavior

SMI Conformance Test should be seamless, error that occur is mentioned below
```
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:31273: connect: connection refused"
```
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by piyushsingariya** [comment]
CC @DelusionalOptimist @utkarsh-pro @navendu-pottekkat @leecalcote

**Comment by DelusionalOptimist** [comment]
@piyushsingariya did you have a load balancer available? :thinking: 
The SMI conformance deployment is exposed via a LoadBalancer service. You'll be able to successfully run tests only if you have one in your environment. If you didn't have one, try using `minikube tunnel` or metallb.
Note to self: Add this to docs if not present.

**Comment by navendu-pottekkat** [comment]
@DelusionalOptimist I do have a LB and the deployment exposed. Still it did not work.

**Comment by kumarabd** [comment]
@navendu-pottekkat @leecalcote Do you think this will help? https://github.com/meshery/meshkit/pull/137
