### ISSUE TITLE
[Docs] Add a link in Spanish home page

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery#4657]
#### Current State
under `Inicio Rapido` we don't have a link for this page https://docs.meshery.io/es/project/contributing

![](https://imgur.com/PnHhVzC.png)

#### Desired State
there should be a link to the mentioned page under `Inicio Rapido`. Like we have in the English page for `Contributing` under `Getting Started`. 

![](https://imgur.com/ZPjyylC.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by DARK-art108** [comment]
Can I work upon this issue? @shubham-tyagi

**Comment by shubham-tyagi** [comment]
sure @DARK-art108, thanks for taking this up.

**Comment by FidalMathew** [comment]
@DARK-art108 are you working on this issue? If not, I would like to take up the issue.

**Comment by warunicorn19** [comment]
Hey @FidalMathew looks like @DARK-art108 is busy with other work, it'd be great if you could take look at this. 😃 

Please feel free to ask on [slack](https://join.slack.com/t/layer5io/shared_invite/zt-rgbyt4kj-6PUUyqY9SfQGRSt_oZV9yQ) if you run into any blockers.

**Comment by FidalMathew** [comment]
> Hey @FidalMathew looks like @DARK-art108 is busy with other work, it'd be great if you could take look at this. 😃
> 
> Please feel free to ask on [slack](https://join.slack.com/t/layer5io/shared_invite/zt-rgbyt4kj-6PUUyqY9SfQGRSt_oZV9yQ) if you run into any blockers.

Sure! 👍

**Comment by 14Richa** [comment]
Hi, @shubham-tyagi I created a tiny PR for this issue, since I didn't see any activity on this issue in a while. Please take a look if that fixes the issue.

**Comment by shubham-tyagi** [comment]
sure @14Richa, Thanks for taking this up.
