### ISSUE TITLE
[UI]Change cursor to pointer in navigator chevron

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4659]
#### Current Behavior
When we hover on top of the chevron in the navigator there's no change in the cursor.

#### Desired Behavior
The cursor should switch to a pointer on the chevron to indicate that it's clickable.

#### Environment

- Browser:  Safari
- Host OS: Mac 
- Meshery Server Version: stable
- Meshery Client Version: stable
- Platform:  Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by varunsaral** [comment]
Can I take this

**Comment by Mr-DG-Wick** [comment]
Here you go @varunsaral :)

**Comment by warunicorn19** [comment]
Hey @varunsaral any progress on this so far? Please feel free to ask on slack if you feel like you're having trouble somewhere.

**Comment by varunsaral** [comment]
@warunicorn19 will submit a pr today .

**Comment by varunsaral** [comment]
@warunicorn19 Hey , can you unassign me from this task , as i having difficulty in seting up the enviornment and solving the issue , i tried contacting my mentor but no response , i have taken almost a week maybe someone else can do it and i want to focus on other ideas as suggested by @leecalcote in newcomers meeting . Thank you

**Comment by varunsaral** [comment]
> @warunicorn19 also the link to  Contributing to Meshery UI is broken on github action bot , it should be https://docs.meshery.io/project/contributing/contributing-ui instead of https://docs.meshery.io/project/contributing-ui

**Comment by sahilsuman933** [comment]
@varunsaral Then Can I take this task!?

**Comment by warunicorn19** [comment]
Thank you for letting us know @varunsaral, please go ahead @sahilsuman933. It's actually a one line change should take too much time.
