### ISSUE TITLE
[Enhancement] Avoid GitHub API Rate Limiting for Server Version Check

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4664]
#### Current Behavior
Meshery deployments face API rate limits. Meshery Server is invoking GH's API to check for the latest server version.

```
meshery-97565c89f-xsxr5	|	time="2021-11-23T19:39:38Z" level=error msg="GET https://api.github.com/repos/meshery/meshery/tags: 403 API rate limit exceeded for 70.121.90.111. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 40m50s]" app=meshery code=2138 probable-cause= severity=2 short-description="failed to compare latest and current version of Meshery" suggested-remediation=
```

#### Desired Behavior
Use https://github.com/meshery/meshery/releases/latest to determine latest Meshery Server release version instead.

#### Implementation
Remove all api.github.com requests.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@piyushsingariya do you have an example of this that has been recently implemented in `mesheryctl`?

**Comment by Revolyssup** [comment]
@leecalcote  How about a central function in meshkit which takes into parameter some set constant like(meshery, istio ,traefik mesh) etc and gives its latest release by web scraping method. I will implent that and make a PR in meshkit. That function can then be used across all the meshery components. And whenever we need to getLatestRelease of something else, instead of adding another function, we can just add that constant there an extra case statement for URL

**Comment by leecalcote** [comment]
Sounds great. The function can be used in mesheryctl, too.

**Comment by leecalcote** [comment]
`getLatestRelease` ready?

**Comment by Revolyssup** [comment]
> `getLatestRelease` ready?

Yes meshkit has this function now

**Comment by leecalcote** [comment]
Reopen if the propagation of that change has yet to be completed.
