### ISSUE TITLE
[mesheryctl] `system restart` tries to start Meshery as the deployments are being terminated

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#4665]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system restart` `stop`s and `start`s Meshery. This causes the command to try `start` when Meshery is still being stopped and shows this error.

```
mesheryctl system restart
Restarting Meshery...
Meshery deployments will be deleted from your cluster. Are you sure you want to continue [y/n]? y
Stopping Meshery...
Deleting Meshery Namespace...
Meshery is stopped.
Starting Meshery...
⣾ Deploying Meshery on Kubernetes Error: cannot start Meshery: create: failed to create: secrets "sh.helm.release.v1.meshery.v1" is forbidden: unable to create new content in namespace meshery because it is being terminated
```

#### Desired Behavior

`mesheryctl system restart` should wait for the entire Meshery deployment to be terminated before attempting to `start` Meshery.

This should be a fix of `mesheryctl system stop` and to wait for Meshery to be completely removed (as `mesheryctl system restart` calls `stop` and `start` inside).

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ibnjunaid** [comment]
@navendu-pottekkat Can you please assign this issue to me.

**Comment by leecalcote** [comment]
@ibnjunaid how are you coming along? Progress to report?

**Comment by ibnjunaid** [comment]
@leecalcote  Going through the kubernetes APIs. will report within this week.
