### ISSUE TITLE
[mesheryctl] Make `system start` intelligent

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#4666]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system start` asks the user to run `mesheryctl system status` to check the status of the pods that are spinning up.

#### Desired Behavior

`mesheryctl system start` should check the status of the pods continuously and see if they are ready.

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Uh-oh... this issue has gone stale.

**Comment by MUzairS15** [comment]
@hexxdump can I take on this?

**Comment by hexxdump** [comment]
sure @MUzairS15

**Comment by MUzairS15** [comment]
@navendu-pottekkat @hexxdump 
Approach: Add watch flag to `system status` and in `system start` execute system status with watch flag until all pods are ready.
Should I continue?

**Comment by piyushsingariya** [comment]
I feel this issue isn't relevant anymore, when the issue was opened mesheryctl wasn't able to poll till meshery starts, but now it can, so it removes the possible implementation of running `system status` with `system start`.

**Comment by piyushsingariya** [comment]
Closing this issue, feature has been already implemented
