### ISSUE TITLE
contributing-ui page link is broken in github issue reference section for contribution 

### ISSUE THREAD

**Issue by varunsaral** [meshery/meshery#4669]
#### Current State
when a UI issue is opened , it has a link for reference for contributing in UI
![issue1](https://user-images.githubusercontent.com/42253796/143297383-82e14e97-153c-429a-819c-5a97aaabd9d1.png)

and it result it 404 when clicked 

![broken_404](https://user-images.githubusercontent.com/42253796/143297659-5fa57094-dbff-49da-8c24-442210b3e306.PNG)

#### Desired State
The file is located under /project/contributing/contributing-ui 
![contributing](https://user-images.githubusercontent.com/42253796/143297891-388b85d6-5f4e-4b4e-89ad-3caa389ffca2.PNG)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@varunsaral will you be putting in a fix for this?

**Comment by varunsaral** [comment]
@warunicorn19 Everything is fine in docs , the best way in my opninion is fixing the link in issue template (which is not possible for me maybe) , if we change the location of file in docs , we have to update the other links too and it seems to be at right place now.

**Comment by warunicorn19** [comment]
Well the template is in the `.github` folder, you could just fork this repo, make the changes and make a PR.

**Comment by varunsaral** [comment]
okay @warunicorn19  , thank you for information . Please assign me this

**Comment by leecalcote** [comment]
@bariqhibat has some further guidance to offer here.

**Comment by bariqhibat** [comment]
We should use a decorator to wrap our whole React component to a error boundary. If there's any uncatched error happening in our application, then it'll be redirected to an error page, which acts as a default setback. More of the reference can be read here: https://reactjs.org/docs/error-boundaries.html
