### ISSUE TITLE
[Docs] Page not linked

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery#4681]
#### Current State
the highlights red part in the below image is not a link on this [page](https://docs.meshery.io/extensibility/adapters). 

![](https://imgur.com/PKfs8Z8.png)

#### Desired State
It should be a link to https://docs.meshery.io/project/contributing.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sahilsuman933** [comment]
@shubham-tyagi Can you assign this task to me.

**Comment by shubham-tyagi** [comment]
Sure @sahilsuman933. Thanks for taking this up.
