### ISSUE TITLE
[UI] Use recently added metadata to show pattern's current support status on UI

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#4707]
#### Current Behavior

Currently users do not have a context on what patterns are valid and what patterns are invalid, on the patterns page. (Defining "invalid" as "There is some typo","There is no adapter or something which has registered capabilities against that patternfile"). 
We need to use the metadata in patterns array returned by /api/pattern.
#### Desired Behavior

On each pattern returned by /api/pattern, there are two fields which are added, "canSupport"(bool) and "errmsg"(string).
If canSupport is true, they are to be treated as supported and we can ignore "errmsg"
If canSupport is false, they are to be treated as not supported,  and we can get more info at "errmsg"

From UX standpoint, we either need an extra column that says "Supported" or "Not supported". Or we can grey out the patterns which have "canSupport" set as false.
In case of "canSupport" as false, we can have a small question mark or something equivalent on that row, and when user clicks that we can display the text from "errmsg"

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Umoren** [comment]
Hi @Revolyssup I would like to give this a shot

**Comment by Chadha93** [comment]
@Umoren would you like to give it a  try?

**Comment by leecalcote** [comment]
@Chadha93, are you comfortable in taking this on?

**Comment by Chadha93** [comment]
@leecalcote @Revolyssup Sure I'll take and implement the solution for this issue, it's a very useful feature to add.
