### ISSUE TITLE
[UI] Navigator Collapse Chevron Position

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#4709]
#### Current Behavior
The chevron is not responsive with respect to the aspect ratio.

https://user-images.githubusercontent.com/65453826/144587094-626c1ed0-c999-4b59-93bb-2e919e837ce7.mp4

#### Desired Behavior
The chevron should also hide when the navigator is fully collapsed/hidden accordingly to the window aspect ratio.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
@sahilsuman933 Would you like to give this a shot?

**Comment by sahilsuman933** [comment]
@Chadha93 I would love to fix this issue. But it may take a few weeks to fix this issue cause this will be my first issue on Javascript. So if it isn't urgent, please assign me to this task.

**Comment by sahilsuman933** [comment]
@Chadha93 Can you please look into the video and tell me whether I have to make any other changes or not?

https://user-images.githubusercontent.com/34382211/144684068-a37cc231-059e-42f3-a089-65a97ac72e6f.mp4

**Comment by warunicorn19** [comment]
@sahilsuman933 almost there, basically what needs to be done is that the chevron should hide with the drawer itself, we don't want to remove the chevron all together.

**Comment by Chadha93** [comment]
Yess +1 with @warunicorn19, @sahilsuman933 you just need to make changes with the positioning and breakpoints of chevron, not hiding.

**Comment by sahilsuman933** [comment]
@warunicorn19 @Chadha93 
Yeah, I got your point. I need to do the following stuff:-

i) Hide that chevron in mobile.
ii) When the user clicks on the hamburger button, the chevron should be re-displayed with its functionality.

But I am not getting how I can hide the chevron when the user clicks on the outside (to close it) the navigation bar. That's the issue I am facing right now.

**Comment by sahilsuman933** [comment]
Sorry @Chadha93  and @warunicorn19  I am not able to solve this problem. I will learn to react after that I will solve this problem if someone didn't fix that issue till that time. Sorry once again.

**Comment by Prakhar-Agarwal-byte** [comment]
I would like to take this up

**Comment by warunicorn19** [comment]
Thanks for the heads up @sahilsuman933, Please go ahead @Prakhar-Agarwal-byte.
