### ISSUE TITLE
Broken link from CONTRIBUTING.md[Docs]

### ISSUE THREAD

**Issue by varunsaral** [meshery/meshery#4714]
#### Current State
Broken link in  CONTRIBUTING.md

https://user-images.githubusercontent.com/42253796/144661257-318e94f6-2d58-45f7-a86a-71d902d8cdf8.mp4

#### Desired State
It should point to a vaild page
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks, @varunsaral 👍

**Comment by varunsaral** [comment]
I was assigned to it :( , my PR was ready I was somewhere remote , anyways thank you Arun , you fixed my two issues
