### ISSUE TITLE
contributing-ui page link is broken in github issue reference section for contribution [Docs]

### ISSUE THREAD

**Issue by varunsaral** [meshery/meshery#4715]
#### Current State
Broken Link

https://user-images.githubusercontent.com/42253796/144662736-2ee0cbb0-0da1-47cf-b1df-249d05ca36db.mp4

#### Desired State
The link should point to https://docs.meshery.io/project/contributing/contributing-ui
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by arunkarthicknm** [comment]
Can I take this issue??

**Comment by shubham-tyagi** [comment]
Thanks @arunkarthicknm for taking this up.

**Comment by varunsaral** [comment]
@arunkarthicknm refer to  #4670 if you have any doubt , or you can ask me too

**Comment by arunkarthicknm** [comment]
Can you please tell me where exactly the link is broken?? @varunsaral
