### ISSUE TITLE
[CI] Need to have proper liveness/readiness checks with Helm deployments

### ISSUE THREAD

**Issue by hexxdump** [meshery/meshery#4726]
#### Current Behavior
Meshery server and operator deployments have moved to helm based deployments in release v0.6.0
However, we do see that some of the pods take time to come up and gives bad user experience.
We need to make sure that the pods for these deployments are coming up fine by adding some readiness checks.

#### Desired Behavior
Add custom logic to check whether the meshery pods are up and running after applying helm charts.

#### Implementation
some thoughts:
1. check whether the meshery server is up or not by hitting the version endpoint API
2. k8s library calls to check whether all the pods are in "running" state or not and wait till all the pods move to 'running' state.

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Go away stale bot!

**Comment by leecalcote** [comment]
@hexxdump is there hope yet for this one?
