### ISSUE TITLE
[UI] Need Search feature for Performance Profile

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#4728]
#### Desired Behavior

I as a user require a search box to search for a performance profile that I saved 1 month ago, and now I have hundreds of performance profiles. The search should support search with "Name", and "URL". 

#### Mockups

![image](https://user-images.githubusercontent.com/50979887/144788793-603c9a42-3d88-4193-be2d-a9f7703bc056.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by piyushsingariya** [comment]
CC @navendu-pottekkat @sudo-NithishKarthik @leecalcote @warunicorn19

**Comment by warunicorn19** [comment]
I agree, this is definitely a feature we should consider, best to add this in the refactoring.

**Comment by sudo-NithishKarthik** [comment]
<img width="1436" alt="Screenshot 2021-12-06 at 6 16 43 PM" src="https://user-images.githubusercontent.com/75248557/144848506-8a6a15a8-e755-4d50-a360-ab3408409d2c.png">

Although we have this in the tabular form, it doesn't hurt us to do the same in the card view.

**Comment by navendu-pottekkat** [comment]
Yes, it is not super obvious for the user to switch to the tabular view and find a search box...

**Comment by MUzairS15** [comment]
Hello, I would like to work on this.

**Comment by Chadha93** [comment]
yes, @navendu-pottekkat is right in terms of UX. Is this issue still required? If not lets close this @warunicorn19
