### ISSUE TITLE
[mesheryctl] System Start gives unfriendly message when K8s is not available

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4731]
#### Current Behavior
Can we go back to the drawing board on this:
```
$ mesheryctl system start
Error: !! cannot query the Kubernetes API. See https://docs.meshery.io/reference/error-codes
```

It is terribly unfriendly and not obvious what needs to be done.  Also, there is no error code given.

#### Desired Behavior
Provide user with a message that says what the issue is and what to do about it.

```
Your `$contextname` context is configured to run Meshery on Kubernetes using the `$tokenname` token. The Kubernetes cluster is not accessible. Please confirm that your cluster available and that the token is valid. See https://docs.meshery.io/installation/quick-start for additional instructions.
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ibnjunaid** [comment]
@leecalcote I want to work on this issue can you assign it to me.

**Comment by sayantan1413** [comment]
Yeah sure go ahead @ibnjunaid 🚀

**Comment by leecalcote** [comment]
Gents, please be aware that this issue needs to move quickly. It's a poor user experience for new users. @ibnjunaid message quickly if you get stuck, please.

**Comment by ibnjunaid** [comment]
@leecalcote Can you  review  the PR #4751 and please let me know if any changes are needed.
