### ISSUE TITLE
[UI] Profile icon and text not aligned properly

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [meshery/meshery#4733]
#### Current Behavior
The icon and text are not aligned vertically properly

![Screenshot from 2021-12-07 12-49-43](https://user-images.githubusercontent.com/17739006/144984328-788f1360-9e3d-4791-83ba-df6d1b0615bd.png)

#### Desired Behavior
They should be center aligned vertically

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Prakhar-Agarwal-byte** [comment]
I would like to fix this

**Comment by warunicorn19** [comment]
@Prakhar-Agarwal-byte Thanks for pointing this out but let's get some of the issues that you already have out of the way first.

**Comment by prakharagarwal-dev** [comment]
@warunicorn19 I have created PR for https://github.com/meshery/meshery/pull/2405 So can I now work on this?

**Comment by warunicorn19** [comment]
Okay, sure👍
