### ISSUE TITLE
[UI] Replace notistack with MaterialUI Snackbar 

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [meshery/meshery#4738]
#### Current Behavior
This issue is related to `meshery-ui-restructring` [branch](https://github.com/meshery/meshery/tree/meshery-ui-restructuring) 

The dev server crashes on start with the following log:
```
prakhar@prakhar-ubuntu:~/Documents/meshery$ make run-ui-dev
cd ui; npm run dev; cd ..

> meshery-ui-rebuiilt@0.1.0 dev
> npm run dev:proxy


> meshery-ui-rebuiilt@0.1.0 dev:proxy
> node ui_dev_server.js

warn  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /home/prakhar/Documents/meshery/ui/babel.config.js
error - ./node_modules/notistack/dist/notistack.esm.js:4:0
Module not found: Can't resolve '@material-ui/core/Slide'

Import trace for requested module:
./pages/_app.js

https://nextjs.org/docs/messages/module-not-found

```
This happens because currently we were using `notistack` previously which was dependent on mui v4 but since now we are using mui v5 and have to use the snackbar component provided by mui v5 (https://mui.com/components/snackbars/).

We will have to remove notistack from the list of dependencies and make sure this error does not exist.

#### Desired Behavior
All `notistack` toasts are replaced by new mui5 Snackbars

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Prakhar-Agarwal-byte** [comment]
I would like to solve this issue

**Comment by sudo-NithishKarthik** [comment]
Go ahead @Prakhar-Agarwal-byte .
