### ISSUE TITLE
[CI] Centralize Meshery Adapter Integration Test Results

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4741]
_This is a child issue of the larger epic for [Compatibility Matrix #2515](https://github.com/meshery/meshery/issues/2515)._

#### Current Behavior
Integrations are a key aspect of the value Meshery offers to users. Details of the compatibility of Meshery and its components are available in various places in Meshery Docs (in Jekyll datafiles). Bringing this information together into a single location in a compatibility matrix (maybe multiple tables) will benefit users.

#### Implementation
Centralize the results of integration tests in order to create a unified Meshery test and compatibility dashboard in Meshery Docs.

#### Implementation
1.  Create `/docs/_compatibility` folder under which .md files can store individual adapter integration tests.
2. Follow a naming convention to prevent overlap of test results; e.g. `meshery-linkerd-stable-v0.5.10.md`
3. Include the following information in the frontmatter of the results file:
```
---
component:
build: 
timestamp:
test-results:
 - <operation-name>: [pass|fail]
 - <operation-name>: [pass|fail]
 - <test-name>: [pass|fail]
 - <test-name>: [pass|fail]
---
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Progress: https://docs.meshery.io/project/compatibility-matrix

**Comment by leecalcote** [comment]
@Revolyssup with the pattern in place will you quickly finish by propagating the e2e tests across the rest of the adapters?

**Comment by Revolyssup** [comment]
> @Revolyssup with the pattern in place will you quickly finish by propagating the e2e tests across the rest of the adapters?

no probs. Will be done by today
