### ISSUE TITLE
meshery container crash

### ISSUE THREAD

**Issue by bboshiZ** [meshery/meshery#4753]
#### Current Behavior
meshery progress panic

#### Screenshots/Logs
panic: runtime error: index out of range [1] with length 1

goroutine 33 [running]:
github.com/layer5io/meshery/internal/graphql/model.GetControlPlaneState(0xc00c0c9100, 0xe, 0x10, 0x3cdb1b0, 0xc000267680, 0xc00c0c9100, 0x8, 0x10, 0xc00111a030, 0xc00107c000)
	/data/code/meshery/internal/graphql/model/control_plane_helper.go:43 +0xcef
github.com/layer5io/meshery/internal/graphql/resolver.(*Resolver).getControlPlanes(0xc000564200, 0x3c9b7e8, 0xc00111a0c0, 0x3cdb1b0, 0xc000267680, 0xc000010038, 0x1, 0x1, 0x10, 0x0, ...)
	/data/code/meshery/internal/graphql/resolver/control-plane.go:20 +0xe9
github.com/layer5io/meshery/internal/graphql/resolver.(*Resolver).listenToControlPlaneState.func1(0xc000564200, 0x3cdb1b0, 0xc000267680, 0x3c9b7e8, 0xc00111a0c0, 0xc000010038)
	/data/code/meshery/internal/graphql/resolver/control-plane.go:45 +0x238
created by github.com/layer5io/meshery/internal/graphql/resolver.(*Resolver).listenToControlPlaneState
	/data/code/meshery/internal/graphql/resolver/control-plane.go:34 +0x7c
#### Environment

- **Platform:** Kubernetes
- **Meshery Server Version:** v0.6.0-rc-2
- **Meshery Client Version:** v0.6.0-rc-2

#### reason
https://github.com/meshery/meshery/blob/master/internal/graphql/model/control_plane_helper.go#L38
```
				if len(strings.Split(objspec.Containers[0].Image, ":")) > 0 {   // this should "> 1"
					version = strings.Split(objspec.Containers[0].Image, ":")[1]
				}
```

**Comment by leecalcote** [comment]
Thank you for logging this, @bboshiZ 👍

**Comment by leecalcote** [comment]
@bariqhibat do comment when you've had a chance to investigate, if you would.

**Comment by leecalcote** [comment]
@bariqhibat has taken leave from the project...
