### ISSUE TITLE
[Docs] Extra copy icon in the Scoop installation guide

### ISSUE THREAD

**Issue by sayantan1413** [meshery/meshery#4760]
#### Current State

There is an extra copy icon in the [Scoop installation guide to download Mesheryctl ](https://docs.meshery.io/installation/platforms/scoop)the command line client for Meshery.

#### Desired State

There should not be any extra copy icon in the installation guide.

#### Screenshot

<img width="860" alt="Screenshot 2021-12-11 at 2 58 21 PM" src="https://user-images.githubusercontent.com/64970095/145671728-4cb55464-1164-4956-adb0-506f00df1b8c.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Deepansharora27** [comment]
I would like to fix this @Mr-DG-Wick

**Comment by sayantan1413** [comment]
It's all your's @Deepansharora27 .🎉

**Comment by sayantan1413** [comment]
Any updates here @Deepansharora27 ?

**Comment by Deepansharora27** [comment]
Hi @sayantan1413 
I am not able to get to the root of the issue, i.e. what is causing the issue in the First place 
Have debugged everything ranging from the CSS File Code to the mesheryctl.md code but everything seems to be be correct there 
Can you please have a look at this and tell me ?

**Comment by Deepansharora27** [comment]
Also, Tagging @warunicorn19 @leecalcote

**Comment by leecalcote** [comment]
@alphaX86

**Comment by warunicorn19** [comment]
@Deepansharora27 you'd have to take a look at the code in `scoop.md`. We use clipboard.js for this `copy-to-clipboard` feature, there's probably an incorrect class name or an opened `<div>`.  The class name is supposed to follow this convention. https://docs.meshery.io/project/contributing/contributing-docs#clipboard-feature

**Comment by alphaX86** [comment]
@Deepansharora27 check the markdown code as @warunicorn19 said. A tag maybe repeated in this case... or it may be due to misalignment... Let me know if you have any problems

**Comment by Deepansharora27** [comment]
Got the Issue 
Making the Pull Request Now 
@alphaX86 @warunicorn19 @leecalcote 
Thanks for the Help !!

I reinvestigated the Scoop.md Markdown file and the issue was present there.

**Comment by Deepansharora27** [comment]
I have made a Pull Request, you can have a look
