### ISSUE TITLE
[Docs]  Footer modification

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery#4767]
#### Current State

Changes required on https://docs.meshery.io/ :
- we don't have layer5 discuss icon in docs footer
- The slack icon needs to be changed.
- the calendar icon doesn't have a hover effect.

![](https://imgur.com/FGW2dZm.png)

#### Desired State

![](https://imgur.com/TZTB16B.png)

- add the layer5 discuss forum icon in docs footer.
- The slack icon needs to be modified to what we have on the [layer5](https://layer5.io/) website footer. You could checkout [#613](https://github.com/meshery/meshery.io/pull/613) to see how to add a hover effect to the slack icon.
- add a hover effect for the calendar icon.

**If there are still some doubts feel free to comment here or discuss it on slack.**

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Nik-09** [comment]
Hi @shubham-tyagi I want to contribute on this issue. I am just going through the [this doc](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit#) for knowing more about how to get start until then can you please assign this task to me.
Thank you

**Comment by msaini0r** [comment]
@sayantan1413 @shubham-tyagi  can I work on this?

**Comment by shubham-tyagi** [comment]
Hey @msaini0r, thanks for jumping in, but @Nik-09 is working on it. We need to ask @Nik-09 if he is still working or if he is caught up somewhere else before assigning it to you. Till then it would be great if you could check out some other issues we have opened on this repo or any other repo of layer5.

**Comment by shubham-tyagi** [comment]
hey @msaini0r, are you still working on it?

**Comment by Nik-09** [comment]
Yes I am working on it -- Thank you.

**Comment by adithyaakrishna** [comment]
@Nik-09 Yooo, Lmk if you have any doubts or issue, we can hop on a call regarding that :)
