### ISSUE TITLE
[Server][Filters][BUG] Filters are not getting fetched

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#4768]
#### Current Behavior
Filters are not getting fetting fetched from the server due to a bad response.
It seems an issue under Meshery cloud.

#### Expected Behavior
Server response API needs to be fixed.
Please do link the Meshery cloud PR here for reference. 

#### Screenshots/Logs
![Screenshot from 2021-12-08 10-38-18](https://user-images.githubusercontent.com/65453826/145942993-6c6c73ca-4ef1-46ed-a2c2-2d0918901744.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
This is an issue with meshery cloud right? @Revolyssup have you already put in a fix for this?

**Comment by Revolyssup** [comment]
> This is an issue with meshery cloud right? @Revolyssup have you already put in a fix for this?

Yeah, I did put the fix

**Comment by Chadha93** [comment]
https://github.com/layer5io/meshery-cloud/pull/147

**Comment by leecalcote** [comment]
@Revolyssup ready to close?
