### ISSUE TITLE
[Error] Unable to write MeshSync data to the Meshery Database

### ISSUE THREAD

**Issue by manav1403** [meshery/meshery#4771]
#### Screenshots/Logs

`Unable to write MeshSync data to the Meshery Database  app=meshery code=1002 probable-cause="Meshery Database is crashed or not reachable" severity=2 short-description="Error while writing meshsync data.no such table: objects" suggested-remediation="Restart Meshery Server.Please check if Meshery server is accessible to the Database"`

#### Environment

- **Host OS:** Linux 
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by manav1403** [comment]
// @mgfeller

**Comment by manav1403** [comment]
the code 1002 isn’t on this page, though - https://docs.meshery.io/reference/error-codes#meshery-server.

**Comment by Chadha93** [comment]
@manav1403 is this issue still valid?
