### ISSUE TITLE
[Docs] Option to go back to English from Espanol

### ISSUE THREAD

**Issue by sayantan1413** [meshery/meshery#4775]
#### Current State

When we go to the Espanol page there is no option to go back to the English version 

#### Desired State

When we are on the English version then there is a button at the top right corner to Espanol. So when we are on the Espanol page then the button should change to English to go back to the English version. Or maybe we can make a dropdown with two options which might be a better approach because in the future we might introduce docs in another language.

#### Screenshot
<img width="1440" alt="Screenshot 2021-12-16 at 6 52 02 PM" src="https://user-images.githubusercontent.com/64970095/146379862-990dbd5e-7cb8-4ed4-83f0-b7162fab6680.png">

<img width="1440" alt="Screenshot 2021-12-16 at 6 52 11 PM" src="https://user-images.githubusercontent.com/64970095/146379897-838dc77a-9a19-4254-8c1a-d3f2acfbcfc7.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by varunsaral** [comment]
i want to work on this

**Comment by adithyaakrishna** [comment]
@varunsaral Any updates on this?

**Comment by varunsaral** [comment]
@adithyaakrishna need some help , can i ping you on slack?

**Comment by Abhijay007** [comment]
@varunsaral are you still working on this issue?

**Comment by varunsaral** [comment]
@Abhijay007 let's talk on slack about this issue , i have some doubts

**Comment by Abhijay007** [comment]
> @Abhijay007 let's talk on slack about this issue , i have some doubts

okay :)

**Comment by vish-han** [comment]
@leecalcote I would love to work on this challenging issue if I got assigned 😀

**Comment by Ayan-thecodeking** [comment]
is this issue still open ?? if yes I would love to work on this

**Comment by Chadha93** [comment]
> @Chadha93 is this issue still open ?? if yes I would love to work on this

Sure @Ayan-thecodeking, just a quick check - are you able to build docs locally? If yes let's get you assigned.

**Comment by Ayan-thecodeking** [comment]
> dropdown wi

@Chadha93 can you please brief me, on what you mean by building docs locally.

**Comment by Chadha93** [comment]
> > dropdown wi
> 
> @Chadha93 can you please brief me, on what you mean by building docs locally.

building docs locally means - are you able to setup and run the project on your system? For this specific issue, you need to run the meshery docs locally to make changes accordingly and then make a pr. Hope this helps. 😃

**Comment by Ayan-thecodeking** [comment]
> > > dropdown wi
> > 
> > 
> > @Chadha93 can you please brief me, on what you mean by building docs locally.
> 
> building docs locally means - are you able to setup and run the project on your system? For this specific issue, you need to run the meshery docs locally to make changes accordingly and then make a pr. Hope this helps. 😃

Got it .. I'm beginner but I'll try my best and make a pr 🙌

**Comment by StarTrooper08** [comment]
The language translation link is removed !? 
![image](https://user-images.githubusercontent.com/72031540/172824317-f21b0f2f-20c4-48bd-aff8-9bfc65d14884.png)

**Comment by leecalcote** [comment]
Upkeep on the translated pages wasn’t happening and so I believe the limit to that translated pages has been removed. Let’s go ahead and close this issue.
