### ISSUE TITLE
[Docs] Add Meshery Adapter for Cilium Service Mesh as an Alpha adapter

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4778]
**Current State of the Meshery.io site**
The meshery/meshery readme has a table of supported service meshes.

**Desired State of the Meshery.io site**
The `meshery-cilium` adapter is in an alpha state currently and should be reflected in the readme

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Abhijay007** [comment]
I want to contribute to this issue, can you please assign this issue to me?

PS: Also contributing to this [issue](https://github.com/layer5io/layer5/issues/2418)
