### ISSUE TITLE
HIde console log in production build

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#4783]
#### Current Behavior
There are console logs, some with basic information about the function triggered, some with _data information_, some with _endpoints_  

#### Desired Behavior
Hiding them will benefit in security, clean production build, 

#### Implementation
Can be achieved with plugins [Link](https://babeljs.io/docs/en/babel-plugin-transform-remove-console)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
Just  an idea, more thoughts and some more reasons to implement this are welcomed

**Comment by adithyaakrishna** [comment]
@Chadha93 What about if we remove all the console logs? 👀

**Comment by Chadha93** [comment]
@adithyaakrishna No, this is not what I meant in this issue, we need _console. log_ in our codebase and is much required, what this is about is the console log won't be rendered at the time of production of Mesehry(abstracting all the console logs during build), the console logs still can be used locally for debugging or else purposes and yes removing one by one could be a solution but not a feasible one.

**Comment by adithyaakrishna** [comment]
Ohhh Acchaa, Thanks @Chadha93 :)
