### ISSUE TITLE
[Docs]Remove all instances of  `api.github.com` in docs

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4787]
#### Current State
There are a lot of commented out API calls in Meshery docs
#### Desired State
All these API calls should be removed. 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Prakhar-Agarwal-byte** [comment]
Should I take this? 😅

**Comment by warunicorn19** [comment]
@Prakhar-Agarwal-byte let's keep this for a beginner😂

**Comment by msaini0r** [comment]
I want to work on this @navendu-pottekkat

**Comment by ahmadateya** [comment]
Is this issue still open?

@msaini0r I saw your work man, will you finish it? or can I contribute to solving this issue?

**Comment by warunicorn19** [comment]
This is not an issue that we plan on looking into right now, let's close. Thank you @ahmadateya for pointing this out.
