### ISSUE TITLE
[Docs] Error codes are difficult to navigate.

### ISSUE THREAD

**Issue by shubham-tyagi** [meshery/meshery#4797]
#### Current State
The current, tabular formatting is difficult to navigate on https://docs.meshery.io/reference/error-codes.

#### Desired State
Tighten up the information architecture and presentation on the page.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by adithyaakrishna** [comment]
@shubham-tyagi How about if we add a search function in which if a user searches for a Error Code, he will be shown or taken to that specific part in the error-code docs?

**Comment by shubham-tyagi** [comment]
@adithyaakrishna you have a really good suggestion. The only problem with that is we dont have a unique error code for the whole page. We have same error code repeated lik 3,4 times in the same error codes page. We have unique error code for particular type of error. So while searching we would need both the error type as well as error code.

**Comment by shubham-tyagi** [comment]
duplicate issue #3765
