### ISSUE TITLE
Unable to read MeshSync data to the Meshery Database

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4802]
#### Current Behavior
Running Meshery Server locally produces this error when Meshery Operator connects.

#### Screenshots/Logs
```
WARN[2021-12-20T14:42:38-06:00] Unable to read MeshSync data to the Meshery Database  app=meshery code=1002 probable-cause="Meshery Database is crashed or not reachable" severity=2 short-description="Error while deleting meshsync data.table `key_values` already exists" suggested-remediation="Restart Meshery Server.Please check if Meshery server is accessible to the Database"
```

#### Environment

- **Host OS:** Mac 
- **Platform:** Kubernetes
- **Meshery Server Version:** edge

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by navendu-pottekkat** [comment]
@kumarabd Did you get a chance to look into this issue?

**Comment by kumarabd** [comment]
@navendu-pottekkat  I will need a little more detail on steps to reproduce. I tried running meshery and the operator seems to run just fine. Anything specific I need to ensure?

**Comment by navendu-pottekkat** [comment]
@leecalcote Could you mention the steps here?

**Comment by leecalcote** [comment]
Gents, yes, here is a server log to examine. This system is running Docker Desktop w/K8s. I removed my local .meshery/config database, then built and run Meshery Server locally. A Meshery Operator w/MeshSync was previously deployed to the cluster.
[mesher-server.log](https://github.com/meshery/meshery/files/7794606/mesher-server.log)
