### ISSUE TITLE
mesheryctl system config aks: Error getting context: could not read token:: open /Users/me/.meshery/auth.json: no such file or directory

### ISSUE THREAD

**Issue by bitsofinfo** [meshery/meshery#4805]
mesheryctl  `v0.6.0-rc-2`

Following this guide: https://docs.meshery.io/installation/platforms/aks

```
13:34 $ mesheryctl system config aks
Missing Meshery config file.
Create default config now [y/n]? y
Default config file created at /Users/me/.meshery/config.yaml
{
  "azure-cli": "2.24.1",
  "azure-cli-core": "2.24.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-batch-cli-extensions": "6.0.0",
    "storage-preview": "0.7.2"
  }
}
Configuring Meshery to access AKS...
Please enter the Azure resource group name:
me-rg
Please enter the AKS cluster name:
me-test-001-aks
Merged “me-test-001-aks" as current context in /Users/me/.meshery/kubeconfig.yaml
Error getting context: could not read token:: open /Users/me/.meshery/auth.json: no such file or directory
```

**Comment by leecalcote** [comment]
Thank you for reporting this, @bitsofinfo 👍

**Comment by piyushsingariya** [comment]
as you don't have the token, Can you try using `mesheryctl system login` to authenticate meshery cli.

**Comment by navendu-pottekkat** [comment]
@bitsofinfo Were you able to check this out?

The issue you are facing is likely because mesheryctl is not authenticated to the Meshery provider. As @piyushsingariya mentioned, you can run:

```
mesheryctl system login
```

to authenticate mesheryctl.

**Comment by navendu-pottekkat** [comment]
@piyushsingariya @hexxdump We should probably hand this within mesheryctl. If the token is not found, we can prompt the user to login through mesheryctl which will download the token and the user can continue executing the original command.

**Comment by navendu-pottekkat** [comment]
Although the inline docs in mesheryctl mention using a token, it is not super obvious on how to get the token.

```
Configure Meshery to connect to AKS cluster using auth token
mesheryctl system config aks --token auth.json
```

@Zanda256 had looked into fixing some of these UX.

**Comment by piyushsingariya** [comment]
> @piyushsingariya @hexxdump We should probably hand this within mesheryctl. If the token is not found, we can prompt the user to login through mesheryctl which will download the token and the user can continue executing the original command.

good idea.

**Comment by hexxdump** [comment]
> > @piyushsingariya @hexxdump We should probably hand this within mesheryctl. If the token is not found, we can prompt the user to login through mesheryctl which will download the token and the user can continue executing the original command.
> 
> good idea.

I liked the idea too, however, aren't we doing multiple things in the `config` subcommand flow, i.e., login+config?
Would not it be better to inform the user to use `mesheryctl system login` first and re-run the `mesheryctl system config aks` subcommand later?

**Comment by hexxdump** [comment]
> Although the inline docs in mesheryctl mention using a token, it is not super obvious on how to get the token.
> 
> ```
> Configure Meshery to connect to AKS cluster using auth token
> mesheryctl system config aks --token auth.json
> ```
> 
> @Zanda256 had looked into fixing some of these UX.

May be the documentation needs little bit tweaking. 
For e.g. `--token auth.json`  flag is optional, if its not provided, make sure that mesheryctl is authenticated to Meshery server using `mesheryctl system login` command.

**Comment by piyushsingariya** [comment]
#4810 opened to tackle this UX issue.

**Comment by leecalcote** [comment]
> #4810 opened to tackle this UX issue.

Thank you, @piyushsingariya. 👏

**Comment by piyushsingariya** [comment]
also I think implementing auto execution of login command across multiple packages/subcommands would result into import-cycle issues.
