### ISSUE TITLE
[mesheryctl] UX: Need helpful suggestion to user of `system context switch`

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4806]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
When no parameters are provided, this command returns an error message that is not helpful.

```
$ mesheryctl system context switch
Error: accepts 1 arg(s), received 0
```

#### Desired Behavior
1. Show user example usage.
1. Show user help text for `system context switch`.

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Nik-09** [comment]
@leecalcote can you please assign this issue to me. 
Thank you

**Comment by warunicorn19** [comment]
Thank you for taking a look @Nik-09

**Comment by bisakhmondal** [comment]
Hi, @Nik-09 are you still working on this issue?  Thanks.

**Comment by leecalcote** [comment]
@bisakhmondal, it's not clear that he is. You're welcome to pick it up.

**Comment by Nik-09** [comment]
Yes, I was unwell from last week. I am unassigning myself since I am already working now on issue [#4767](https://github.com/meshery/meshery/issues/4767)
Thank you & All the best.

**Comment by leecalcote** [comment]
Thank you, @Nik-09. Sounds real good. Get better soon!

**Comment by bisakhmondal** [comment]
Thanks, @leecalcote! Feel free to review the PR when you are free : )
