### ISSUE TITLE
[UI] Configurator: Unhandled exception

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4808]
#### Current Behavior
Browsing through the different service mesh configurations, I receive an "unexpected error".

#### Screenshots/Logs
<img width="1839" alt="Screen Shot 2021-12-22 at 7 45 34 AM" src="https://user-images.githubusercontent.com/7570704/147102343-7d3b9a68-6f9a-4b7f-a014-b42e1dbb9484.png">

#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: edge-latest
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
NGINX rate limit is an example

**Comment by leecalcote** [comment]
@Abhishek-kumar09, are both you and @Revolyssup addressing this issue?

**Comment by Abhishek-kumar09** [comment]
Have handled this on frontend, atleast UI is not breaking now. Need to change the schema coming from the backend to what we expect.

**Comment by Abhishek-kumar09** [comment]
It haas missing type field

**Comment by leecalcote** [comment]
@Revolyssup, I know that you've had a number of things going on this week, so don't stress yourself in getting to this immediately. I'm adding a comment here as a reminder that this area of the adapters needs your final conclusion.

**Comment by leecalcote** [comment]
@Abhishek-kumar09 @Revolyssup I think this issue has been addressed. Is that right?
