### ISSUE TITLE
[mesheryctl] Bad UX when invalid platform is passed to the mesheryctl installation bash script

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#4813]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

When a user passes in an invalid platform to deploy Meshery while using the bash script install, they are thrown this error.

```
➜  ~ curl -L https://git.io/meshery | PLATFORM=bob bash -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  6661  100  6661    0     0   3188      0  0:00:02  0:00:02 --:--:--  168k
Invalid platform: bob
```

This does not provide any useful information to the user.

#### Desired Behavior

The user should be notified that the platform entered is invalid and should be prompted to enter a new platform from the available platforms similar to the UX when no platform is entered.

```
➜  ~ curl -L https://git.io/meshery | bash -             
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  6661  100  6661    0     0   3331      0  0:00:01  0:00:01 --:--:--  3331
Enter a platform to deploy Meshery. Available platforms [docker, kubernetes]:
```
---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ibnjunaid** [comment]
Can you please assign this one to me.
