### ISSUE TITLE
[CI] [Cypress] Add E2E tests to Deploy Applications/Filters/Patterns Configuration through Meshery UI

### ISSUE THREAD

**Issue by MarioArriaga92** [meshery/meshery#4826]
Child issue of Umbrella Issue #4582

Current Behavior
No E2E tests that cover Meshery's Service Mesh Configuration Management functionality (Applications/Filters/Patterns) to **Deploy Configuration Changes.**

Desired Behavior
E2E tests should be written to cover Deploying Applications, Filters & Patterns Configuration Changes.

Implementation Notes
Grouping E2E tests by usecase / end user scenario + multiple pages is to focus on test code reusage to try to reduce maintenance efforts & enforce standard expectations & behavior across the three pages

Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by MarioArriaga92** [comment]
Working on it

**Comment by leecalcote** [comment]
yeah, back off, stalebot. ;)
