### ISSUE TITLE
[UI][v0.6.0-rc-2] Uploading pattern through "/configuration/patterns" UI route returns error "Failed to upload pattern file: failed to import pattern: parse {file content}...: net/url: invalid control character in URL"

### ISSUE THREAD

**Issue by MarioArriaga92** [meshery/meshery#4833]
#### Current Behavior

MesheryPatterns component does not include a ‘pattern_data.pattern_file’ property on Post request to upload pattern endpoint after clicking the “Upload Pattern” button and returns  error "Failed to upload pattern file: failed to import pattern: parse {file content}...: net/url: invalid control character in URL"

#### Desired Behavior

Pattern file should be uploaded without errors through Meshery UI's MesheryPatterns component

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/23443575/147589959-bccd9668-4712-4250-80df-43e2787913d2.png)

#### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Server Version: v0.6.0-rc-2
- Meshery Client Version: v0.6.0-rc-2
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you, @MarioArriaga92!
