### ISSUE TITLE
[Error] Segmentation fault bug

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#4834]
#### Current Behavior
Meshery suddenly stopped by showing this error :
```

signal: segmentation fault (core dumped)
make: *** [Makefile:111: run-16-fast] Error 

```
#### Expected Behavior
It should not happen. 
What could be the probable cause?

#### Screenshots/Logs
![Screenshot from 2021-12-28 23-03-18](https://user-images.githubusercontent.com/65453826/147592242-ad2a7a9d-b4f0-4015-881d-5bc64a14983a.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Chadha93 thanks for this. Additional, preceding logs from Meshery Server are needed in order to chase down the root of the issue here. Do you happen to have those?

**Comment by Chadha93** [comment]
> @Chadha93 thanks for this. Additional, preceding logs from Meshery Server are needed in order to chase down the root of the issue here. Do you happen to have those?

Oops No, I lost them but there were no errors before, just the normal logs.

**Comment by leecalcote** [comment]
Let's close for now and reopen when server logs can be captured at the same time. We definitely want to address any segmentation faults like this, but need more information to chase them down.

**Comment by Chadha93** [comment]
> Let's close for now and reopen when server logs can be captured at the same time. We definitely want to address any segmentation faults like this, but need more information to chase them down.

sounds good
