### ISSUE TITLE
[Lifecycle] Helm: New chart needed for Meshery Adapter for Cilium Service Mesh

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4837]
#### Current Behavior
Meshery Adapter for Cilium Service Mesh v0.1.0 is in pre-alpha.

#### Desired Behavior
Preparing a sub-chart for this adapter is necessary.

#### Implementation
See https://github.com/meshery/meshery/tree/master/install/kubernetes/helm/meshery

#### Acceptance Tests
1. This adopter should be an optional installation.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@vishal267 would you like to take this one?

**Comment by Aisuko** [comment]
We can build Helm charts after the CI process of automation build image work well.

**Comment by leecalcote** [comment]
Why wait, though? It's a copy and paste with the change of port # and name, more or less, right? The port has been predetermined (`10012`) and name identified "Meshery Adapter for Cilium Service Mesh" (long) and "meshery-cilium" (short).

**Comment by Aisuko** [comment]
@leecalcote yes. We need these information and now we got it.
