### ISSUE TITLE
[UX] Figma: Create information center component and prototype

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4839]
#### Current Behavior
Meshery UI has a small information center in its lower lefthand corner. See screenshot.
<img width="1497" alt="Screen Shot 2021-12-29 at 9 39 34 PM" src="https://user-images.githubusercontent.com/7570704/147720020-0db4e7ce-eff4-46c5-b5d8-a36662eccac9.png">

As a project, we're in need of having all aspects of Meshery UI designed in the project's shared Figma design file. The most recent information center changes are missing.

#### Desired Behavior

In the "[Design Language](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/?node-id=110%3A1)" page:

- Create a reusable Figma component to represent this information center.
- Create a prototype that follows the same behavior in the screen recording below.

#### Screen recording

https://user-images.githubusercontent.com/7570704/147720003-623858b9-3026-4abf-9908-8e25bfbc08c1.mov

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Swapnil-Bhabal** [comment]
Kindly assign this task to me @leecalcote

**Comment by leecalcote** [comment]
Thanks for giving this a shot, @Swapnil-Bhabal

**Comment by leecalcote** [comment]
Help wanted.

**Comment by YashKamboj** [comment]
@leecalcote can i give it a try

**Comment by leecalcote** [comment]
Yes, please. Assuming that you have experience with Figma, let's assign the issue to you. If you are still learning Figma, that's fine - you can still work on the issue like Swapnil will be. However, let's leave the issue unassigned so that another might pick it up at the same time that you're learning. Let me know where you're current at: have you create a component before? Have you created a prototype before?

**Comment by YashKamboj** [comment]
@leecalcote i have good knowledge of react but haven't used figma before, but as i googled ,it doesn't look that typical

**Comment by IMPranshu** [comment]
I am familiar with Adobe XD. I can try to translate the design of the recording that you provided in Figma. Please assign this to me.

**Comment by leecalcote** [comment]
Thanks, @IMPranshu. Be sure to fill in a community member form and ping @warunicorn19 for Figma access.

**Comment by IMPranshu** [comment]
Sure will do that @leecalcote

**Comment by IMPranshu** [comment]
@warunicorn19 Can I get the access ? I will get started on it

**Comment by IMPranshu** [comment]
@leecalcote I have already filled the form yesterday.

**Comment by YashKamboj** [comment]
@leecalcote  Tried for first time , can you tell if its good?? 

https://user-images.githubusercontent.com/75125203/147882352-69d8a166-2d3b-4fa7-9f96-d4376d06af99.mp4

**Comment by leecalcote** [comment]
@YashKamboj nice! Yes, this is hitting the mark. 👍

**Comment by leecalcote** [comment]
Let's be sure to have a review of this on the Websites meeting agenda.

**Comment by leecalcote** [comment]
@YashKamboj - https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W?node-id=3785:23499#136900062

**Comment by YashKamboj** [comment]
@leecalcote can you explain a little ???

**Comment by leecalcote** [comment]
@IMPranshu and @Swapnil-Bhabal, now is a good time to offer review of this work.

**Comment by IMPranshu** [comment]
@YashKamboj nice work. Would recommend increasing the time so that the transition will be smoother and will be more visible. Apart from that one thing I noticed is that after collapsing all the buttons should be hidden and only one button should be visible and that should be clicked to reveal the other buttons. You should work on implementing that now. That's all from my side.

**Comment by YashKamboj** [comment]
@IMPranshu Thnx , about the collapsing , i am not sure how to do that , could you help me with that

**Comment by IMPranshu** [comment]
@YashKamboj sure. dial me in your progress link. we will do it.

**Comment by YashKamboj** [comment]
@IMPranshu Progress link??😅

**Comment by IMPranshu** [comment]
the design link which you have made send me that link. we will carry it from there @YashKamboj

**Comment by YashKamboj** [comment]
@IMPranshu https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W?node-id=3785:23499#136900062

**Comment by IMPranshu** [comment]
@YashKamboj Thanx for sharing. will have a quick look and get back to you

**Comment by IMPranshu** [comment]
https://user-images.githubusercontent.com/43396684/148061274-512b3df9-89d6-4849-bee3-1db2a15fb072.mp4

I was trying to modify the animation but I think some issue is there. Whenever I change the animation the interaction is not getting selected.

**Comment by YashKamboj** [comment]
@IMPranshu Can't see the video

**Comment by IMPranshu** [comment]
Sorry @leecalcote @YashKamboj, I have to travel for 3 days, Will be continuing after that... @YashKamboj Please try downloading the video I am unable to upload the correct format.

**Comment by IMPranshu** [comment]
@YashKamboj did you take a look at the video?

**Comment by adithyaakrishna** [comment]
@IMPranshu @YashKamboj @leecalcote The way we are doing is not the correct way for creating a component in figma, as @leecalcote said, it has to be a reusable component. I have made some teeny tiny changes to the Information Center part of the figma file. 

You can refer this video, https://www.youtube.com/watch?v=hZd0s8yN0Io which I use whenever I need to create a collapsible component like the one required here

https://user-images.githubusercontent.com/23498248/150632932-a5b5b919-befe-41b0-a5a7-3a8d565b32de.mp4

**Comment by adithyaakrishna** [comment]
Created the Component and Prototype as there was one issue with the above method being, we wont be able to use that again and again  😶 

https://user-images.githubusercontent.com/23498248/150633348-0a2b4485-3292-49fa-8f13-be04850b66a5.mp4

@leecalcote Could you please check the above video and lmk if this is the desired option?

**Comment by adithyaakrishna** [comment]
Updated and made some animation changes here

![image](https://user-images.githubusercontent.com/23498248/150633664-b1ab6406-9f74-44a2-ac9e-d97a962953fb.png)

**Comment by adithyaakrishna** [comment]
@leecalcote @warunicorn19 Closing this issue (wrt https://github.com/meshery/meshery/issues/4839#issuecomment-1019133501) as it has been designed and completed :)
