### ISSUE TITLE
[Docs] Filter non-English pages from Operation Guides list

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4842]
#### Current State
This page has a list of related guides - https://docs.meshery.io/guides - that have different languages intermixed. 

![image](https://user-images.githubusercontent.com/7570704/147798670-b6b12f28-2c21-4473-91b3-b5500dbeb335.png)

#### Desired State
Show the list of guides for the currently selected language.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Abhijay007** [comment]
@leecalcote , and what do we need to do after filtration of non-English pages? 

are you talking about filter functionality or something?

**Comment by leecalcote** [comment]
Front matter: 

`language: en`

See @shubham-tyagi for assistance, if needed.

**Comment by Abhijay007** [comment]
> Front matter:
> 
> `language: en`
> 
> See @shubham-tyagi for assistance, if needed.

ok, so can you please assign this issue to me?

**Comment by shubham-tyagi** [comment]
hey @Abhijay007, If you face any difficulty while solving this issue, please feel free to ping me on slack. We could even hop on a call there if you want. Thanks for taking this up.

**Comment by Abhijay007** [comment]
> hey @Abhijay007, If you face any difficulty while solving this issue, please feel free to ping me on slack. We could even hop on a call there if you want. Thanks for taking this up.

thanks, @shubham-tyagi for asking, I will definitely ping you if I face any difficulty !!

**Comment by IMPranshu** [comment]
hello, @Abhijay007 are you still working on this?? Would be happy to join you in this.

**Comment by leecalcote** [comment]
@IMPranshu that would be nice. @Abhijay007 has many issues on his plate currently. 

The solution to this issue is really straight forward. Simply add the front matter value I mentioned previously. You might have to update the for loop to filer on language, depending on what ether it already does or doesn't.

**Comment by leecalcote** [comment]
@IMPranshu progress to report or confirmation of the approach to report?

**Comment by IMPranshu** [comment]
Sorry, I am going through the docs didn't get a chance, will try it soon.

**Comment by MUzairS15** [comment]
I have figured it, can I take up this issue?

**Comment by leecalcote** [comment]
Please.
