### ISSUE TITLE
[mesheryctl] Build check failure: Golang Unit Test

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4844]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
The Golang unit tests are failing in this build check - https://github.com/meshery/meshery/runs/4674993078?check_suite_focus=true

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by unnati914** [comment]
I can take this up @leecalcote 💯

**Comment by leecalcote** [comment]
This would be excellent, @unnati914. Let's give you a beat to tie-off other assignments currently on your plate, and then, get this one assigned straight-away.

**Comment by unnati914** [comment]
sure 🥇

**Comment by piyushsingariya** [comment]
Old issue, actions are passing now.
