### ISSUE TITLE
[Docs] Add Icon and Link to Discuss in Docs Footer

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4848]
#### Current State
<img width="417" alt="Screen Shot 2022-01-01 at 8 45 28 AM" src="https://user-images.githubusercontent.com/7570704/147853146-345ba81b-8bb8-4335-ac59-3edd404485b9.png">

Discuss icon and link is missing for https://discuss.layer5.io

#### Desired State

See layer5.io's footer for an example

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ahmadateya** [comment]
I am taking this issue, assign it to me please

**Comment by warunicorn19** [comment]
@leecalcote there's already an open issue on this and it is being worked on. @ahmadateya please have a look at some other open issues😃
