### ISSUE TITLE
[Docs] User Tokens: What they are and how to get yours 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4870]
**Current State:**
The Meshery REST API requires a valid user token for most of its endpoints, but not all.

**Desired State:**
Meshery docs should describe how users can download their token.

This page can be updated - https://docs.meshery.io/extensibility/api

---
#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by unnati914** [comment]
I can take this up, would love to help on this

**Comment by Mr-DG-Wick** [comment]
Thanks for taking this up! @unnati914
