### ISSUE TITLE
[UI] Navigator and Scrollbar style bug 

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#4875]
#### Current Behavior
Navigator and scrollbars in Meshery UI are not responsive and their position is not defined, for having a visual look see the picture attached below.
<img width="1440" alt="Screenshot 2022-01-02 at 11 42 21 AM" src="https://user-images.githubusercontent.com/65453826/147884338-fa25055d-1ed6-4820-bcc5-314146e7f6be.png">

#### Desired Behavior
The navigator should be aligned to its position. should not overflow out.

#### Issue perform/replicate
To replicate this issue you must try this on the Safari browser or can ask someone to test your changes(PR) over it. 

#### Test Case: 
- Try to eliminate the use of margins, extra padding, or any hard styles
- If req to give any size use rem not px or any other

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by YashKamboj** [comment]
@Chadha93 There is no issue in my device 🤔
![Screenshot (162)](https://user-images.githubusercontent.com/75125203/147884469-1f4ce7ad-7acd-448f-b8ea-e84cca14d27f.png)

**Comment by Chadha93** [comment]
@YashKamboj Yes it's a browser-specific issue, since you are on windows you can try to achieve the cases and see that if it works or not. @warunicorn19 will help you to test your changes to Safari or any other browser. 
Sounds good?

**Comment by YashKamboj** [comment]
There is a extra negative margin, which is used to cover the chrome's ugly scrollbar, so i think we can style a scrollbar , is there already a scrollbar or do we need a new one ? @Chadha93

**Comment by Chadha93** [comment]
@YashKamboj we don't have a scrollbar for now but we also don't want a scrollbar in the navigator. // @warunicorn19 your thoughts?

**Comment by YashKamboj** [comment]
@Chadha93 but we have to do something with the scrollbar, if we remove the margin

**Comment by Chadha93** [comment]
> 

hiding it particularly for the navigator could be one solution.

**Comment by Chadha93** [comment]
https://github.com/meshery/meshery/pull/4888 Thanks @Abhishek-kumar09 for this. Hide works 😉, Thanks @YashKamboj for engaging in this issue.
