### ISSUE TITLE
[Chore] Revisit dependabot reviewer assignments for Meshery Components

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4889]
#### Current Behavior
Stale or missing reviewer assignments in some of the components.

#### Desired Behavior
Identify ideal reviewer. Confirm assignment with them. Update assignment.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@meshery/adapter-maintainers let's divide and conquer the responsibilities here. Who would like to responsible for dependency updates on which adapter(s)?

**Comment by Aisuko** [comment]
Hi @Aisuko I'm responsible for linkerd2 and osm. And If there any other adapter need to support. You can assign me directly.

**Comment by leecalcote** [comment]
@Aisuko awesome. 💪

**Comment by Aisuko** [comment]
@leecalcote oh, right. If I remember right we can add the Owner file to the project and related the permission to the team name. Some like 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax

**Comment by leecalcote** [comment]
Right on. In this case, in dependabot.yml

**Comment by Aisuko** [comment]
Oh, `dependabot.yaml` looks the best for this situation.

**Comment by leecalcote** [comment]
@DelusionalOptimist will this continue to be you? https://github.com/meshery/meshery-operator/blob/master/.github/dependabot.yml

**Comment by leecalcote** [comment]
@navendu-pottekkat @hexxdump @piyushsingariya?

**Comment by Aisuko** [comment]
@leecalcote Please add me to the operator project. I'd like to add the `suit_test` for the operator project in this month.

**Comment by warunicorn19** [comment]
I can take any docs dependency updates or any jekyll related updates. For meshery, if @Nikhil-Ladha is okay with it, he and I can take that up.

**Comment by Nikhil-Ladha** [comment]
> I can take any docs dependency updates or any jekyll related updates. For meshery, if @Nikhil-Ladha is okay with it, he and I can take that up.

Sure Aditya, please do that.
