### ISSUE TITLE
[UI] Meshery Logo on Navigator response

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#4892]
#### Current Behavior
Currently, when clicked on Meshery Logo, it shows a pointer(hand) that depicts It should redirect or link to the dashboard.

#### Desired Behavior
It should redirect to the dashboard.
Note: Do check the comments before proceeding.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
@warunicorn19 what behavior on the Logo we are expecting here, I guess the redirect to the dashboard was removed earlier, please feel free to update the issue description.

**Comment by leecalcote** [comment]
The logo's hyperlink should land the user on the Dashboard.

**Comment by Vidyaa123** [comment]
Hi @Chadha93, Can I work on this, please?

**Comment by Vidyaa123** [comment]
Hi @Chadha93, Can I work on this, please?

**Comment by kranurag7** [comment]
Hey @Chadha93 I think we can use this style="cursor:default" and this will replace the Pointer(hand) with normal cursor. Please let me know what you think?

**Comment by Chadha93** [comment]
Sure @Vidyaa123 you can go ahead!

**Comment by Chadha93** [comment]
@kranurag7 no we just need to get the logo's hyperlink to land on the Dashboard. Issue description updated.

**Comment by leecalcote** [comment]
All, we need this completed within a week's timeframe. Good of @Vidyaa123  and @kranurag7 to jump in. If the addition of a hyperlink isn't completed within a week, @Chadha93, please complete and deliver before the next Meshery dev meeting.

**Comment by Nikhil-Ladha** [comment]
It's a one-line change, if you want I can send out a PR right away.

**Comment by Chadha93** [comment]
> It's a one-line change, if you want I can send out a PR right away.

@Nikhil-Ladha yes it's a one-line change, Thanks for jumping in to help, let's wait for @Vidyaa123 or @kranurag7.  @Vidyaa123 any blockers?
If yes @Nikhil-Ladha can make a pr then you may have a look to understand the fix. 🙂

**Comment by Nikhil-Ladha** [comment]
Oh, I just created a PR 😶 ..... If they are still around they can send one, and I will close out mine :)

**Comment by Chadha93** [comment]
No issues, it was a quick fix, @Vidyaa123 @kranurag7 you can have a look at the description of the PR provided by @Nikhil-Ladha

**Comment by Vidyaa123** [comment]
Thanks, @Chadha93  and Thanks for fixing it fast and description in PR  @Nikhil-Ladha. I am new to this, so figuring it out slowly.

**Comment by kranurag7** [comment]
Thanks @Nikhil-Ladha for fixing it out quickly. @Chadha93 I will go through the description.
