### ISSUE TITLE
[UI] Use version field returned in /api/system/adapters

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#4896]
#### Current Behavior

Currently after each adapter becomes reachable, we dont make use of version field i.e. the version of that adapter.
#### Desired Behavior

Display the version of each connected adapter by extracting that field from json.
#### Implementation

At this endpoint shown in screenshot , version field is "none". Maybe display this version, just above the adapter chip

![Screenshot_20220106_235422](https://user-images.githubusercontent.com/43276904/148437217-88960556-5f8c-420f-9d11-1cd46d46195e.png)

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Abhijay007** [comment]
I want to work on this issue, please assign this issue to me !!

**Comment by leecalcote** [comment]
@Abhijay007 can you demo this in this week's Meshery Dev meeting?

**Comment by Abhijay007** [comment]
> @Abhijay007 can you demo this in this week's Meshery Dev meeting?

I will try 😅 , I am still figuring out

**Comment by leecalcote** [comment]
@Abhijay007, I completely understand. @Nikhil-Ladha this might be a good to one to engage within.

**Comment by warunicorn19** [comment]
The version of the adapter is present in the Tooltip if I'm not wrong.

**Comment by warunicorn19** [comment]
Something like that @leecalcote ?
<img width="296" alt="Screenshot 2022-01-10 at 6 06 09 PM" src="https://user-images.githubusercontent.com/53532328/148852785-0c6efa0c-a991-4d8b-8587-b55376eb8e6b.png">

**Comment by Nikhil-Ladha** [comment]
Good pointer @warunicorn19 .
@Abhijay007 you can reach out to me offline in case you need any help.

**Comment by Abhijay007** [comment]
> Good pointer @warunicorn19 . @Abhijay007 you can reach out to me offline in case you need any help.

ok thanks, @Nikhil-Ladha for asking, I will reach out to you on slack !!

**Comment by leecalcote** [comment]
Oh, boy. I might have led us astray here in suggestion that the version wasn't presented in the UI, when in fact, it is available in the tooltip.

Let's close out this issue for now, understanding that we will have new UI designs for v0.7.0 in which the version number will be displayed differently.

**Comment by warunicorn19** [comment]
let's not close, let's label as `issue/willfix` and `ui-refactor`.

**Comment by leecalcote** [comment]
Fixed.
