### ISSUE TITLE
[UI] release page should open in new tab when clicked on new-tab icon

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#4909]
#### Current Behavior
The link `v0.6.0-rc-3`  in the bottom of the navigator (picture attached) opens the releases page on the same page itself, even after clicking the new-tab icon.

 

#### Desired Behavior
When clicked the new-tab icon the release page should open at a new tab.

#### Screenshots/Logs
<img width="219" alt="image" src="https://user-images.githubusercontent.com/51183483/148655325-4939f5fd-5dc6-4eb8-ace5-292e8d94457a.png">

#### Environment

- Browser: Brave, Safari
- Host OS: Mac
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you, @asubedy
