### ISSUE TITLE
[Docs] Add hyperlinks for each of the architectural components

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4911]
#### Current State
[This page](https://docs.meshery.io/concepts/architecture) has a couple tables listing architectural components. 

<img width="876" alt="Screen Shot 2022-01-08 at 12 48 58 PM" src="https://user-images.githubusercontent.com/7570704/148656061-68c454b7-5e95-4f7e-b803-4209c9969e40.png">

#### Desired State
Add a hyperlink for each component to its respective docs page.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by verma-kunal** [comment]
Hey @leecalcote , can I work on this one?

**Comment by asubedy** [comment]
Sure @verma-kunal. Here you go 🚀

**Comment by verma-kunal** [comment]
Thank you 🙂

**Comment by verma-kunal** [comment]
For contributing to the docs, i would have to setup a development environment, right? Like setting up Jekyll, Bundler!
Steps that are mentioned in the guide here: https://github.com/verma-kunal/meshery/tree/master/docs

**Comment by asubedy** [comment]
> For contributing to the docs, i would have to setup a development environment, right? Like setting up Jekyll, Bundler!
> Steps that are mentioned in the guide here: https://github.com/verma-kunal/meshery/tree/master/docs

Yes @verma-kunal. The readme mentions the steps to install the necessary components.

**Comment by verma-kunal** [comment]
> Yes @verma-kunal. The readme mentions the steps to install the necessary components.

Sure, thanks!

**Comment by verma-kunal** [comment]
Hey @asubedy @leecalcote , actually i had a few doubts here:

- for certain topics like "Meshery Server", I am not able to find a page with a definition or explaining the concepts of that particular topic. Would it be good to link the contributing guide of that topic instead?
Few topics, for example: Meshery Server, Meshery UI.

- the component **"Meshery Provider UI"** is pointing to the docs for the topic [Providers](https://docs.meshery.io/extensibility/providers) or would it be a different one?

- Just wanted to confirm whether all the **Meshery Broker** ( image below ) , points to the same topic "[Broker](https://docs.meshery.io/concepts/architecture/broker)" or its different for each case?

![Screenshot 2022-01-10 at 8 39 35 AM](https://user-images.githubusercontent.com/72245772/148714095-c7059a6e-95cd-464a-aa7f-7f09cec7a780.png)

**Comment by warunicorn19** [comment]
- We can skip the link to `Meshery Server` for now
- You mean `Meshery Providers` right? And not `Meshery Provider UI` if so then yes the link you shared works. if not you can skip `Meshery Provider UI` like at the table on top. 
- Yes all should lead to same link.

**Comment by verma-kunal** [comment]
Got it! Thanks @warunicorn19

**Comment by verma-kunal** [comment]
I've created an initial PR for this, as have added a few hyperlinks! 
We can add the rest ones, when further confirmed

Hope that sounds good!
