### ISSUE TITLE
[Docs] Link broken in contribution section 

### ISSUE THREAD

**Issue by varunsaral** [meshery/meshery#4916]
#### Current State
while clicking on navigation links on page , in contribuiting section , the trailing slash is not removed causing a 404 . Other pages seems to work fine

https://user-images.githubusercontent.com/42253796/148702645-799f09ca-35ca-4ab5-81f4-451df6b8daf5.mp4

#### Desired State

The trailing / should be removed automatically like all other pages

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks for filing this, @varunsaral. A `redirect_from` entry with trailing slash for this page needs to be added in the page's frontmatter. Is this something that you would like to do?

**Comment by varunsaral** [comment]
@leecalcote I think the <code>redirect_from</code> entry is missing from root contributing.md file and that's why when we land from contributing page from the paginator it gives us 404 . So this PR don't fix the issue but it resolved a future issue . Also <code>redirect_from</code> is missing from many places including in es pages too .

**Comment by leecalcote** [comment]
@varunsaral, great observations. I agree. Please engage on fixing these at-will. 👍
