### ISSUE TITLE
[Docs] Slack link broken in header

### ISSUE THREAD

**Issue by varunsaral** [meshery/meshery#4917]
#### Current State
The slack link points to 404

https://user-images.githubusercontent.com/42253796/148702759-95e03e1a-a350-430b-865b-b0babbe749a7.mp4

#### Desired State
It should point to our beloved slack workspace .

How to fix?

The navigation.yml file has slack not mentioned as external url , that's why this bug is occuring , to solve simply change url to external_url and it will work

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by amoghjalan** [comment]
Shall I work on it?

**Comment by leecalcote** [comment]
Assuming that @varunsaral isn't working on this, yes, @amoghjalan, that would be great.

**Comment by varunsaral** [comment]
@amoghjalan Thank you for taking it up , i have given the solution itself in the issue , still if you have problem you can ping me on slack.
