### ISSUE TITLE
[Docs][UI] Style the version component.

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#4921]
#### Current State
There is not much style on the version of the new docs dropdown component
![Screenshot from 2022-01-11 11-16-51](https://user-images.githubusercontent.com/65453826/148888130-fbc625c7-9cdb-45c2-8b1c-84894ae16f99.png)

#### Desired State
Add styles and make it look similar to the other tabs in the navbar, follow the same color scheme

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by msaini0r** [comment]
I would like to try this issue. @Chadha93

**Comment by Chadha93** [comment]
All yours @msaini0r 🎉

**Comment by varunsaral** [comment]
@msaini0r can we talk on slack , i have question regarding this .

**Comment by msaini0r** [comment]
> @msaini0r can we talk on slack , i have question regarding this .
> 

@varunsaral sure

**Comment by leecalcote** [comment]
This a good update to make.

**Comment by Chadha93** [comment]
@msaini0r how is this coming up? If you are having any issues/blockers you may ask on the #meshery or #meshery-ui channel in slack.

**Comment by AbhishekJamhoriya** [comment]
Hi, @Chadha93 please assign me this issue. let me give it a try.

**Comment by Akshit42-hue** [comment]
Can I work on this issue @Chadha93

**Comment by Chadha93** [comment]
@Akshit42-hue before getting assigning, lets confirm that you are able to build docs locally.

**Comment by Akshit42-hue** [comment]
Yes, I can build docs locally

**Comment by Chadha93** [comment]
> Yes, I can build docs locally

great, lets wait for @AbhishekJamhoriya 's response, if he is not available you can make a pr for this. :)

**Comment by AbhishekJamhoriya** [comment]
@Chadha93 I'm working on it .

**Comment by ashutosh887** [comment]
Should I help in this issue @AbhishekJamhoriya @Chadha93

**Comment by Chadha93** [comment]
This issue is still present on latest. Reopening this 
![image](https://user-images.githubusercontent.com/65453826/182149843-d57c1fdd-ce57-4a6e-8cd8-417c3a1b6f0b.png)

**Comment by rakshitgondwal** [comment]
Hey @Chadha93 
Which techstacks do I need to know about for taking up on this issue?

**Comment by leecalcote** [comment]
@rakshitgondwal see the first link in the contributor resources section. Ruby, Jekyll, Bundler. Ideally, macOS or Linux, or WSL2 on Windows.

**Comment by amRohitKumar** [comment]
@leecalcote  can I work on this issue?

**Comment by Chadha93** [comment]
@amRohitKumar Sure, are you able to run docs locally? If yes, let's assign you.

**Comment by aj-2000** [comment]
Hello @Chadha93, I want to work on this issue. Please assign it to me.

**Comment by Chadha93** [comment]
> Hello @Chadha93, I want to work on this issue. Please assign it to me.

Sure, are you able to run docs locally? If yes, let's assign you.

**Comment by aj-2000** [comment]
> > Hello @Chadha93, I want to work on this issue. Please assign it to me.
> 
> Sure, are you able to run docs locally? If yes, let's assign you.
Yeah! It's perfectly running fine on my local system. Here is a screenshot to support this.
https://ibb.co/KNKmDXZ

**Comment by aj-2000** [comment]
> > Hello @Chadha93, I want to work on this issue. Please assign it to me.
> 
> Sure, are you able to run docs locally? If yes, let's assign you.

**Yeah! It's perfectly running fine on my local system. Here is a screenshot to support this**
<img width="1440" alt="Screenshot 2022-09-15 at 1 04 03 AM" src="https://user-images.githubusercontent.com/97158497/190248661-338ba71c-9bb6-4d19-892b-cbc0cdf33c04.png">

**Comment by aj-2000** [comment]
@Chadha93 

Keppel Color Variant:
<img width="1438" alt="keppel green version selector" src="https://user-images.githubusercontent.com/97158497/190412430-7b7fabf2-ee62-4b8b-a9e7-93789bcc0369.png">
Carribean Color Variant:
<img width="1440" alt="carribean green version selector" src="https://user-images.githubusercontent.com/97158497/190412448-d1668e69-ca69-42e1-83fe-ebb4b55eb075.png">

can you give some feedback on the design or suggestion changes? or looks okay?
