### ISSUE TITLE
[Docs] Add all `mesheryctl` guides to bulleted collection

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4935]
#### Current State
This page category for mesheryctl guides (https://docs.meshery.io/guides/mesheryctl) is missing a number of mesheryctl guides.

<img width="1398" alt="Screen Shot 2022-01-12 at 8 45 32 PM" src="https://user-images.githubusercontent.com/7570704/149256809-f60b6d87-186b-4dc4-abd1-32508b9b9743.png">

#### Desired State

All of the mesheryctl guides should be listed on the page.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by verma-kunal** [comment]
Hey @leecalcote , can i work on this one or should this be left for a newcomer in the community? 

Anything works 🙂

**Comment by Vidyaa123** [comment]
Hi @leecalcote & @verma-kunal,
If this is for newcomers only,  I can take it up. Thanks.

**Comment by verma-kunal** [comment]
> Hi @leecalcote & @verma-kunal, If this is for newcomers only, I can take it up. Thanks.

absolutely @Vidyaa123 ! Go for it. 
Do ask any doubts you would have! Would be happy to help 🙂

**Comment by Vidyaa123** [comment]
> > Hi @leecalcote & @verma-kunal, If this is for newcomers only, I can take it up. Thanks.
> 
> absolutely @Vidyaa123 ! Go for it. Do ask any doubts you would have! Would be happy to help 🙂

👍

**Comment by Vidyaa123** [comment]
@verma-kunal & @leecalcote please review.
