### ISSUE TITLE
[UI] Design Configurator: "percentage" and "percent" as sliders

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4937]
#### Current Behavior
When rendering rjsf components, "percentage" and "percent" are treated as textfield inputs.

#### Desired Behavior
“percentage” and “percent” should be treated as keywords for Slider components.

#### Implementation
- Ignore `"type": "object"`. Always display a Slider component.
- Ignore `"format": "int32"` and `"format":"double"`. Always set to 0 to 100 for slider range.

#### Acceptance Tests
1. Validation of 0 to 100 value only.

#### Mockups
<img width="142" alt="Frame 1050" src="https://user-images.githubusercontent.com/7570704/149266929-42e0c2be-3f30-4496-89b2-52d823688fe9.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Abhishek-kumar09 did you recently complete this?

**Comment by Abhishek-kumar09** [comment]
Yeah here: https://github.com/meshery/meshery/pull/5304
With a case like this where it is hard to know the percent field: https://github.com/meshery/meshery/pull/5304#issuecomment-1083042378

**Comment by leecalcote** [comment]
@MUzairS15 @sudo-NithishKarthik this is an example of a piece of work that we'll want a new component generator (in cue) to take care of.

**Comment by leecalcote** [comment]
@Chadha93 @Abhishek-kumar09 @sudo-NithishKarthik was this completely finished?

**Comment by leecalcote** [comment]
Let’s ensure this is completely addressed.

**Comment by leecalcote** [comment]
@Abhishek-kumar09 yoy might have a look-see here.

**Comment by leecalcote** [comment]
> @Chadha93 @Abhishek-kumar09 @sudo-NithishKarthik was this completely finished?

**Comment by Abhishek-kumar09** [comment]
The update was merged based on parsing the textfield label and matching whether the label includes `percent` or `percentage`. There were some fields, which didnt have percent label but are expecting percentage from their parent's title, as far as I remember.
