### ISSUE TITLE
[UI] Design Configurator: "integer" as a "number" type textfield

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4939]
#### Current Behavior
In rjsf components, ` "type": "integer"` fields are displayed as string type textfields.

#### Desired Behavior
A numeric-only input.

#### Implementation

Use: 
```
<TextField
          id="outlined-number"
          label="<ideally, a label specific to the context of the input>"
          type="number"
```

#### Acceptance Tests
- Validation: Allowable range from 0 to 100

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by asubedy** [comment]
I would like to work on this.

**Comment by warunicorn19** [comment]
@Chadha93 we'll need another to create another custom component for this. We should be able to use a specific type of component based on the "type".

**Comment by Chadha93** [comment]
> @Chadha93 we'll need another to create another custom component for this. We should be able to use a specific type of component based on the "type".

Hmm, a new component could be a solution, then we need to define the where all we need to have that. 👍

**Comment by Chadha93** [comment]
@leecalcote do we want the above behavior as in the screenshot?

**Comment by leecalcote** [comment]
Yes, the input type pictured in the screenshot for Replicas is ideal.

**Comment by leecalcote** [comment]
@Abhishek-kumar09 knocked this one out with https://github.com/meshery/meshery/pull/5304
