### ISSUE TITLE
[Pattern Deployment] Unhandled error when missing Kubernetes connection

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4942]
#### Current Behavior
Meshery Server crashed when no Kubernetes cluster is connected and pattern deployment is attempted.

Scenario:

1. Built Meshery locally. No running or connected Kubernetes.
2. Signed into Meshery Cloud.
3. Imported pattern via URL.
4. Click to deploy pattern.
5. Meshery Server reports unhandled error below.

#### Screenshots/Logs

```
ERRO[8118] Unable to load default kubernetes config: Get "https://kubernetes.docker.internal:6443/version?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
22:13:54 http: panic serving [::1]:64540: runtime error: invalid memory address or nil pointer dereference
goroutine 2040 [running]:
net/http.(*conn).serve.func1(0xc000878be0)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:1824 +0x153
panic(0x6428e60, 0x7ebd920)
	/Users/lee/sdk/go1.16.4/src/runtime/panic.go:971 +0x499
github.com/layer5io/meshery/handlers.(*Handler).PatternFileHandler(0xc000971280, 0x6bd7e80, 0xc0007a02a0, 0xc00222d600, 0xc00213d0e0, 0xc00028ce10, 0x6c1fbe0, 0xc000b0e480)
	/Users/lee/code/meshery/handlers/oam_handler.go:96 +0x75c
github.com/layer5io/meshery/handlers.(*Handler).SessionInjectorMiddleware.func1(0x6bd7e80, 0xc0007a02a0, 0xc0022ba600)
	/Users/lee/code/meshery/handlers/middlewares.go:118 +0x61f
net/http.HandlerFunc.ServeHTTP(0xc000522cc0, 0x6bd7e80, 0xc0007a02a0, 0xc0022ba600)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2069 +0x44
github.com/layer5io/meshery/handlers.(*Handler).AuthMiddleware.func1(0x6bd7e80, 0xc0007a02a0, 0xc0022ba600)
	/Users/lee/code/meshery/handlers/middlewares.go:65 +0x129
net/http.HandlerFunc.ServeHTTP(0xc0014a6240, 0x6bd7e80, 0xc0007a02a0, 0xc0022ba600)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2069 +0x44
github.com/layer5io/meshery/handlers.(*Handler).ProviderMiddleware.func1(0x6bd7e80, 0xc0007a02a0, 0xc0022ba500)
	/Users/lee/code/meshery/handlers/middlewares.go:33 +0x1e7
net/http.HandlerFunc.ServeHTTP(0xc0014a6260, 0x6bd7e80, 0xc0007a02a0, 0xc0022ba500)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000191c80, 0x6bd7e80, 0xc0007a02a0, 0xc00222c600)
	/Users/lee/code/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc000a40540, 0x6bd7e80, 0xc0007a02a0, 0xc00222c600)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000878be0, 0x6bdf048, 0xc002757180)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:3013 +0x39b
```

Full log here: [server-log.txt](https://github.com/meshery/meshery/files/7867806/server-log.txt)

#### Environment

- **Host OS:** Mac
- **Platform:** Kubernetes
- **Meshery Server Version:** edge
- **Meshery Client Version:** n/a

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@utkarsh-pro is this something that you can address?

**Comment by utkarsh-pro** [comment]
Yes @leecalcote. This should be fixed (if needed) in a few hours. Addressing this today.

**Comment by leecalcote** [comment]
Thanks much. ✔️
