### ISSUE TITLE
[UI] zIndex issue with the switcher

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4945]
#### Current Behavior
The switcher in the pattern configurator goes below the title bar

#### Desired Behavior
it shouldn't. it's zIndex should be more than the title bar 

#### Screenshots/Logs
<img width="207" alt="Screenshot 2022-01-15 at 12 06 47 PM" src="https://user-images.githubusercontent.com/53532328/149631713-db9cdae9-8e30-426d-a702-060797d13d71.png">

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ShivamTyagi12345** [comment]
i would like to help with this
/assign

**Comment by asubedy** [comment]
Sure @ShivamTyagi12345, here you go 👍

**Comment by leecalcote** [comment]
@ShivamTyagi12345 let's make sure that you're setup for success. Is your a meshery development environment setup? Are you able to build and run Meshery UI?

**Comment by ShivamTyagi12345** [comment]
> @ShivamTyagi12345 let's make sure that you're setup for success. Is your a meshery development environment setup? Are you able to build and run Meshery UI?

Not at the moment, but I will start setting it up right now. Thanks for helping me get started

**Comment by Sunnyio** [comment]
Hey @ShivamTyagi12345,  are you working on this?

**Comment by Sunnyio** [comment]
If @ShivamTyagi12345 not working, can I take up this issue?

**Comment by warunicorn19** [comment]
Let's wait another day for @ShivamTyagi12345 to confirm his assignment, if not, you could take this forward.

**Comment by ShivamTyagi12345** [comment]
sorry for the unexpected delay ,Working on my PR ASAP

**Comment by warunicorn19** [comment]
Hey @ShivamTyagi12345 let's get you unblocked from this issue, please feel free to take a look at other open issues. @asubedy can pick this up.
