### ISSUE TITLE
[UI] label not aligned with icon

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#4946]
#### Current Behavior
The label of the text field is not aligned with the icon beside it in the pattern configurator. 

#### Desired Behavior
they should be aligned. 

#### Screenshots/Logs
<img width="245" alt="Screenshot 2022-01-15 at 12 45 44 PM" src="https://user-images.githubusercontent.com/53532328/149632290-8a412d2b-8243-479c-b151-d825191b234f.png">

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by pree-T** [comment]
May I work on it? Can someone help me as I am new to open source contribution?

**Comment by leecalcote** [comment]
Hi @pree-T, yes, although before you take assignment of the issue, let's ensure that you are able to setup you development environment and build Meshery UI so that you can potentially work on a fix for this issue. The instructions for building Meshery UI in the issue description. Send word when you are successfully building Meshery UI and have a proposed solution.

**Comment by adithyaakrishna** [comment]
@pree-T Lmk if you face any issues while trying to set-up your development environment, you can ping me in our community slack and we will help ya figure it out :)

**Comment by anirudh-bukka** [comment]
Hi all, may I work on this issue? This is my first time contributing to Meshery and Open source itself  (I've joined last week)

**Comment by pree-T** [comment]
> Hi all, may I work on this issue? This is my first time contributing to Meshery and Open source itself (I've joined last week)

I am already working on it.

**Comment by anirudh-bukka** [comment]
> I am already working on it.

👍 , I did not know only one person can work on it

**Comment by leecalcote** [comment]
No sweat, @anirudh-bukka. There are many more where this comes from. 👍 let's get you one of the open issues with "help wanted" labeled. Find the hyperlink in the main readme and dig in!

**Comment by leecalcote** [comment]
Of course, if @pree-T hasn't demonstrated the ability to build Meshery UI, yet, this issue is still open game...

**Comment by anirudh-bukka** [comment]
Thanks @leecalcote , I found another issue and I am currently working on it 👍

**Comment by Sonichigo** [comment]
@warunicorn19 Can i work on this?

**Comment by warunicorn19** [comment]
Sure go ahead @Sonichigo, if you run in to any issues setting up the dev environment please feel free to DM.
