### ISSUE TITLE
[Components] Kubernetes: Display name parsing for capitalization and whitespace

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4947]
#### Current Behavior
Meshery Server's registration of Kubernetes components contains errant whitespaces in their names.

<img width="387" alt="Screen Shot 2022-01-15 at 2 51 46 PM" src="https://user-images.githubusercontent.com/7570704/149637374-73540fb1-078a-4527-b6de-6d2c3bae90de.png">

#### Desired Behavior
Meshery Server's registration of Kubernetes components should use a standard library of string parsers from MeshKit.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
This issue has been solved in latest meshkit. Just meshkit upgrade is needed here

**Comment by leecalcote** [comment]
Perfect. Please get this done quickly.
