### ISSUE TITLE
[mesheryctl] `system restart` colliding with helm delete operation

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4951]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Meshery CLI users that execute `mesheryctl system restart` while using in-cluster deployments find that `system restart` fails to start Meshery due to a helm uninstall operation ongoing (initiated by the `system stop` included in `system restart`).

#### Desired Behavior
Mesheryctl to wait for `stop` to complete, then proceed with `start`.

#### Screenshot
```
 mesheryctl system restart
Restarting Meshery...
Meshery deployments will be deleted from your cluster. Are you sure you want to continue [y/n]? y
Stopping Meshery...
Deleting Meshery Namespace...
Meshery is stopped.
Starting Meshery...
⡿ Deploying Meshery on Kubernetes Error: cannot start Meshery: create: failed to create: secrets "sh.helm.release.v1.meshery.v1" is forbidden: unable to create new content in namespace meshery because it is being terminated
Usage:
  mesheryctl system restart [flags]

Flags:
  -h, --help          help for restart
      --skip-update   (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string    path to config file (default "/Users/lee/.meshery/config.yaml")
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.
```

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gr455** [comment]
Hi @leecalcote. I was able to reproduce this issue. Looks like mesheryctl is attempting to start the server back up while the meshery namespace is still being removed on Kubernetes. A solution that I can think of would be to poll the cluster asking if the delete is done. Is this right or is there a better way?

**Comment by leecalcote** [comment]
Looping in @piyushsingariya

**Comment by piyushsingariya** [comment]
I think the new changes in helm installation method from meshkit might solve it, it needs to be tested after a new release of meshkit.

**Comment by leecalcote** [comment]
@gr455 it'd be great to get you involved in testing the potentially already completed fix.

**Comment by leecalcote** [comment]
MeshKit v0.5.3 is a recent release with all PRs merged.

**Comment by gr455** [comment]
That's great! Sure, I will try to test the fix.

**Comment by leecalcote** [comment]
Awesome. Have you join the community Slack, yet?

**Comment by gr455** [comment]
Yep. I also plan on attending the upcoming Newcomers' meet

**Comment by gr455** [comment]
I am running into issues trying to run mesheryctl with meshkit v0.5.3. I changed the version in go.mod and ran `go mod tidy` and ran `make` to build the mesheryctl binary.

```
Starting Meshery...
⣷ Deploying Meshery on KubernetesError: failed to start Meshery
See https://docs.meshery.io/reference/mesheryctl/system for usage details
: cannot start Meshery: context deadline exceeded

```
It works just fine with the older meshkit v0.5.1.
Am I doing something wrong here?

**Comment by piyushsingariya** [comment]
Cool, thanks for checking if the feature worked, I thought it would, it didn't worked the way i thought it would.
Mesheryctl already has capability to wait for meshey to start but I couldn't found any implementation Strategy that would help me wait till deployments are deleted, so I thought we could do with helm SDK, that fails completely. So those changes will be reverted very soon.
that basically means it still needs to be resolved, @gr455 it's time to up your sleeves and get your hands meshy in this issue.

**Comment by gr455** [comment]
@piyushsingariya Can you brief me on what you tried with helm sdk?

**Comment by piyushsingariya** [comment]
https://github.com/meshery/meshkit/pull/147 Here you can take a look.

**Comment by gr455** [comment]
> [meshery/meshkit#147](https://github.com/meshery/meshkit/pull/147) Here you can take a look.

Great thanks!

**Comment by gr455** [comment]
@piyushsingariya Let's rethink the solution to this isse. The issue is that the `restart` operation starts before the namespace is terminated. So we do not need to poll for resources for the sake of this issue. All we need to do is poll for the namespace in `stop` operation if the namespace is set to be deleted. If the namespace is not set to be deleted (with the --keep-namespace flag), then there would be no polling and everything works just fine.

I think polling for resources is also adding unnecessary complexity. Let me know what you think about this.
