### ISSUE TITLE
[mesheryctl] adding a flag so that the the browser does not open after the setup

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#4953]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
As discussed in issue #4091, we can add a feature that does not open a browser automatically after the setup finishes. This might solve the the mentioned issue of getting a prompt on the Katacoda labs after the installation command. 

#### Desired Behavior
A flag that allows user to not open browser after `mesheryctl` installation is complete

#### Mockups

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by MUzairS15** [comment]
I would like to work on this.

**Comment by Abhijay007** [comment]
@MUzairS15 go ahead !! 🚀
