### ISSUE TITLE
[UI] Shift the Create pattern btn

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#4958]
#### Current Behavior
Currently, the pattern create button is at the bottom of the datable/

#### Desired Behavior
Relocate this button to the top in the line of other import options

#### Implementation

- We are using MUIDatable here, and a custom toolbar with custom options to add new import or any other feature to the table.
- Referring to the previous custom components under the custom toolbar will help.

#### Acceptance Tests

- Import should work as earlier.
- give a "+" to create a new pattern (just convert/replace the old create btn with an icon)

#### Mockups
Shift this to top(in table toolbar)
![Screenshot from 2022-01-19 00-09-38](https://user-images.githubusercontent.com/65453826/149998760-8694a652-c16e-48f7-8ae6-ac686a8336b7.png)
Here
![Screenshot from 2022-01-19 00-10-31](https://user-images.githubusercontent.com/65453826/149998814-6eb95f02-71ea-4715-a1f3-c6bc4d26fceb.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by asubedy** [comment]
I like to work on this.

**Comment by warunicorn19** [comment]
Sure @asubedy.
