### ISSUE TITLE
[Docs] Enhance git-flow docs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4964]
#### Current State

Instructions to sync a contributor's fork and local clone might need enhancement.

https://github.com/meshery/meshery/blob/master/CONTRIBUTING-gitflow.md

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@MarioArriaga92 any of your learnings are welcomed additions/changes to these instructions.

**Comment by MarioArriaga92** [comment]
Thanks @leecalcote I'll pour in some love on gitflow instructions, maybe even suggest some 3rd party links to point those in need to the right direction.

**Comment by MarioArriaga92** [comment]
To be honest difference between how Azure DevOps Git handles rebases versus Github is quite confusing at first, especially because repos aren't forked just merged through PR.

**Comment by leecalcote** [comment]
Ah, makes sense. Good, good.

**Comment by Nandani-Paliwal** [comment]
Hey @leecalcote 
Can I work on this issue, If no one is working on it !

**Comment by leecalcote** [comment]
@Nandani-Paliwal sounds great. I don't know that I have specific guidance as to what aspects to enhance, and so, I'll leave you in @MarioArriaga92's capable hands.

**Comment by Nandani-Paliwal** [comment]
Thanks @leecalcote !
