### ISSUE TITLE
[Docs] Examples of of OAM endpoints

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4968]
@utkarsh-pro thanks for clarifying. Examples of endpoints are ideal; a set of examples that provide something of a template such that a contributor could plugin the name of an object (by taking a guess) and hit the endpoint even though not all endpoints are exhaustively listed in the docs.

_Originally posted by @leecalcote in https://github.com/meshery/meshery/pull/4943#discussion_r786280208_

**Comment by leecalcote** [comment]
@utkarsh-pro little help here, please.

**Comment by utkarsh-pro** [comment]
@leecalcote on it...
