### ISSUE TITLE
[UI] Genie effect with drag and drop objects

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4971]
#### Current Behavior
The [MeshMap plugin](https://layer5.io/meshmap) to Meshery is in need of an enhanced user experience. The desired user experience involves both CSS animation and EventListeners with some DOM manipulation.

An example of the desired drag and drop user experience can be seen in the screen recording below.

https://user-images.githubusercontent.com/7570704/150463563-4af62203-e8fd-4012-9dd9-51ac6f07ddc5.mov

This screen recording is taken from FigJam (a relatively new tool from Figma). The main toolbar in FigJam has two elements that you can drag off of the toolbar. After the element is dragged off of the toolbar, that element is replenished with a new instance of the same element. The element is backfilled. There are two elements on the toolbar that have this behavior: a flat circle and a stack of sticky notes.

This user experience is desired behavior for elements that are drag and dropped from the MeshMap Designer drawer, which has a collection of various elements. To familiarize with the effect firsthand Open Figma, switch to FigJam and give it a try.

#### Desired Behavior
Prototype a set of CSS animations. 

With respect to the FigJam-like animation, a prototype can be created in two different phases: first phase can focus on CSS animation (multiple), while the second phase can focus on eventing and JavaScript. A contributor that is successful with the first phase, but not confident with the Javascript will be supported by other project contributors to complete the te drag and drop and disappear / reappear behavior.

#### Contributing
If you would like to try creating these animations - that's great. Please comment on the issue, if you would like it to be assigned to you. You will need to confirm your ability to complete the implementation, though, before assignment of the issue is made. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by asubedy** [comment]
I would like to try this.

**Comment by NikhilSharma03** [comment]
@leecalcote We can close this one.

**Comment by NikhilSharma03** [comment]
@leecalcote Closing this.

**Comment by leecalcote** [comment]
Great work. :)
