### ISSUE TITLE
[UX] Figma: Create Exclamation State for Notification Center and a Prototype

### ISSUE THREAD

**Issue by adithyaakrishna** [meshery/meshery#4977]
#### Current Behavior
Create a notification component like the one shown below.  Create a prototype for the same as well
![image](https://user-images.githubusercontent.com/23498248/150683798-c4fc10f8-7b82-4c8f-9625-fad878590a1a.png)

#### Desired Behavior
![image](https://user-images.githubusercontent.com/23498248/150682631-081b500e-ef6c-4cac-aebf-9d291a54d5c2.png)

#### Mockups
[](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=136%3A6325)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by adithyaakrishna** [comment]
**Final Component:**
![image](https://user-images.githubusercontent.com/23498248/150683984-2ddc2bb6-b984-42d6-849f-1eff8877500b.png)


**Final Prototype:**
https://www.figma.com/proto/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=4203%3A21457&scaling=min-zoom&page-id=136%3A6325&starting-point-node-id=4203%3A21457&show-proto-sidebar=1

**Screen Recording:**
https://user-images.githubusercontent.com/23498248/150683933-3fcc1bc0-2b34-4eff-a746-a38d02b701e0.mp4

**Comment by adithyaakrishna** [comment]
@warunicorn19 @Abhishek-kumar09 @leecalcote Could you please check this and let me know if this is what was required?

**Comment by Abhishek-kumar09** [comment]
How much should I praise for the transitional effect in figma. That is looking great to me.

**Comment by adithyaakrishna** [comment]
Thanks, man! @Abhishek-kumar09  I really appreciate it 🚀

**Comment by adithyaakrishna** [comment]
@leecalcote @warunicorn19 Closing this issue (wrt https://github.com/meshery/meshery/issues/4977#issuecomment-1019499706) as it has been fixed :)
