### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by Sayanta66** [meshery/meshery#4982]
#### Current State

The image in the documentation is not loading and showing an error 404, when the link is being redirected. The broken image url can be found by clicking [here](https://raw.githubusercontent.com/layer5io/meshery/master/assets/img/readme/meshery_lifecycle_management.png). The url for the doc can be found [here](https://github.com/meshery/meshery/edit/master/docs/pages/project/index.md).

#### Desired State

The doc should be updated with a fixed image url so that the image can be loaded properly in accordance with the UI.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Sunnyio** [comment]
I would like to work on this.

**Comment by Sayanta66** [comment]
The problem is solved. Hence, closing this issue.
