### ISSUE TITLE
[mesheryctl] system stop: does not remove meshery-broker (Meshery Server not present)

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4994]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`mesheryctl system stop` does not remove the meshery-broker custom resource despite one being present in the cluster.

_Note: Meshery Server is not running in this situation._

#### Screenshots/Logs

```
$ mesheryctl system stop
Meshery deployments will be deleted from your cluster. Are you sure you want to continue [y/n]? y
Stopping Meshery...
Error: failed to stop Meshery
See https://docs.meshery.io/reference/mesheryctl/system for usage details
: cannot delete CR meshery-broker: brokers.meshery.layer5.io "meshery-broker" not found
Usage:
  mesheryctl system stop [flags]

Flags:
  -h, --help             help for stop
      --keep-namespace   (optional) keep the Meshery namespace during uninstallation
      --reset            (optional) reset Meshery's configuration file to default settings.

Global Flags:
      --config string    path to config file (default "/Users/lee/.meshery/config.yaml")
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.

$ kubectl get pods -n meshery
NAMESPACE     NAME                                     READY   STATUS    RESTARTS        AGE
meshery       meshery-broker-0                         2/2     Running   2 (4h50m ago)   22h
meshery       meshery-meshsync-7d4b9bc75b-ns5q7        1/1     Running   6 (4h49m ago)   22h
```
#### Environment

- Host OS: Mac 
- Meshery Server Version: none
- Meshery Client Version: stable-v0.6.0-rc-4
- Platform: Kubernetes

#### Meshconfig

```
 mesheryctl system context view

Current Context: local

endpoint: http://localhost:9081
token: Default
token-location: auth.json
platform: kubernetes
components:
- meshery-app-mesh
- meshery-istio
- meshery-linkerd
- meshery-consul
- meshery-nsm
- meshery-kuma
- meshery-cpx
- meshery-osm
- meshery-traefik-mesh
- meshery-nginx-sm
channel: stable
version: latest
```

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by nishantwrp** [comment]
@leecalcote i wasn't able to reproduce this issue. Running `mesheryctl system stop` removed the namespace and  i get the following output.

```
➜ kubectl get pods -n meshery
No resources found in meshery namespace.
```

**Comment by alphaX86** [comment]
This issue was present if the `mesheryctl system stop` didn't perform fully (that is when interrupted in middle). This was one of the issues in Helm and it's fixed via `--force` flag I believe. @leecalcote is this issue still present?

**Comment by leecalcote** [comment]
@nishantwrp @alphaX86 thank you for confirming the behavior on this issue. Let's go ahead and close this one.
