### ISSUE TITLE
[UI] Apps, Filters, Patterns: Set cursor to pointer on row hover

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5006]
#### Current Behavior
For Applications, Patterns, and Filters tables, the mouse cursor should be set to pointer on hover.

Each table row is clickable.

#### Desired Behavior
```
cursor: pointer;
```

#### Screenshots/Logs
<img width="679" alt="Screen Shot 2022-01-27 at 2 45 27 PM" src="https://user-images.githubusercontent.com/7570704/151441100-bcad0966-4a6e-46cf-b4e5-2761cf63b28d.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Sunnyio** [comment]
I would like to do this
