### ISSUE TITLE
[Apps] Application deploy not working despite `name` field being supplied.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5008]
#### Current Behavior
User pastes a K8s manifest into an existing application entry and manually adds the `name` field.

#### Expected Behavior
Application fails to deploy. Empty pattern file is being sent for deployment. The pattern sent for deployment only contains a name field and is missing the rest of the k8s manifest.

#### Server Logs
Example:

```
map[string]interface {}{"name":"Book Info App"}
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Reminder...

**Comment by Swathi-L** [comment]
Hi @Revolyssup,
Is this addressed?
