### ISSUE TITLE
[UI] Create a pattern using Meshery UI Pattern configurator.

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#5014]
#### Implementation
Create a pattern from scratch using configurator in the Meshery UI taking a reference from the `bookinfo.yaml` manifest found [here](https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/platform/kube/bookinfo.yaml)

#### Mockups

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/51183483/151594182-e3c3c166-8b52-4a66-86d4-18efa5b692b1.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
@asubedy up for this? I guess yes 🙂

**Comment by asubedy** [comment]
Yes 😄

**Comment by Chadha93** [comment]
@Abhishek-kumar09 could you please provide some insights to proceed on this issue for @asubedy

**Comment by leecalcote** [comment]
@Zanda256 you might want to take this.

**Comment by Zanda256** [comment]
It looks interesting, but isn't it react.js?

**Comment by leecalcote** [comment]
It’s deceiving, but this issue is calling for a competent user to exercise this new UI and prove that it can be used to build Kubernetes workloads.

**Comment by Zanda256** [comment]
Let me take this on.

**Comment by leecalcote** [comment]
Excellent

**Comment by leecalcote** [comment]
Still tracking on this one?

**Comment by Chadha93** [comment]
@Zanda256 any update? cc @asubedy

**Comment by Zanda256** [comment]
I tested it. And it works. What is the deliverable here?
