### ISSUE TITLE
[UI] Duplicate snackbar in Meshery UI

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#5015]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._
Duplicate snackbars when there are no k8s config present

Adding prevent duplicate property to it will resolve this: 
like this: 
```js

const message = 'You only see me once.';
props.enqueueSnackbar(message, { 
    preventDuplicate: true,
});
```

#### Current Behavior

![image](https://user-images.githubusercontent.com/48255244/151596957-99a36c1b-f5dd-4e9d-83ae-28dd081d9a67.png)

#### Desired Behavior

No duplicate snackbar is desired, only one.
#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
Pushing fix for this 🐛
