### ISSUE TITLE
[Docs] Navbar enhancement

### ISSUE THREAD

**Issue by debo19** [meshery/meshery#5040]
#### Current State

The navbar on [Meshery Docs](https://docs.meshery.io/) and the navbar on [meshery.io](https://meshery.io/) have unequal width.

<img width="1440" alt="Screenshot 2022-02-03 at 2 29 52 AM" src="https://user-images.githubusercontent.com/85789734/152236578-0542843d-b31b-495d-a0b6-f9f38b4fffbb.png">
<img width="1440" alt="Screenshot 2022-02-03 at 2 29 24 AM" src="https://user-images.githubusercontent.com/85789734/152236592-35ca2c3a-e5dd-4ff8-b84c-aa7229eff1b5.png">

#### Desired State

Make the navbar on [Meshery Docs](https://docs.meshery.io/) the same width as the navbar on [meshery.io](https://meshery.io/) website. This will allow a more subtle transition from the website to the documentation.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Sunnyio** [comment]
I would like to work on this.

**Comment by debo19** [comment]
Go ahead @Sunnyio

**Comment by Akshit42-hue** [comment]
Can I work on this issue @debo19

**Comment by debo19** [comment]
@Akshit42-hue this issue has been fixed. You can take a look at any other [help-wanted](https://github.com/meshery/meshery/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues.
