### ISSUE TITLE
Meshery Server won’t connect to Adapters unless the Server has a connection to Kubernetes.

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#5046]
#### Current Behavior

![image](https://user-images.githubusercontent.com/48255244/152846034-7534789a-2bec-4a81-8798-c50662f5bd57.png)
If the kuberenetes cluster is down, you won't be able to show adapters on the list although the underlying adapter is running &  workloads and traits are registered with meshery. It's not showing in the UI.

#### Expected Behavior

Adapters should be visible if they are running irrespective of kubernetes connected or not.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
@Abhishek-kumar09 this issue relates to this previous issue, right? https://github.com/meshery/meshery/issues/2855

**Comment by warunicorn19** [comment]
Not exactly @Chadha93. Basically right now if you dont have kubernetes running you wouldn't be able to connect to the adapter. It'll show an error, something like `kubernetes config not configured`. That shouldn't be the case, irrespective of the fact if we have kubernetes running or not the adapter should connect. That's what this issue is for right @Abhishek-kumar09 ?

**Comment by leecalcote** [comment]
@Aisuko, @jbyers19, @Revolyssup this behavior needs to go away. Any takers on this one?

**Comment by Revolyssup** [comment]
Solved by multicontext // @leecalcote

**Comment by leecalcote** [comment]
Thank you, @Revolyssup
