### ISSUE TITLE
[CI] UI Integration Test: Update needed for Multi-context support

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5068]
#### Current Behavior
The incorporation of support for multiple Kubernetes clusters needs to be accounted for in the Cypress tests.

#### Expected Behavior
UI Integration tests should be passing and should account for multiple cluster changes.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@MarioArriaga92 fyi

**Comment by leecalcote** [comment]
@MarioArriaga92  something that you might look at?

**Comment by MarioArriaga92** [comment]
Sure @leecalcote

**Comment by leecalcote** [comment]
@Abhishek-kumar09 or @MarioArriaga92 are you able to create this?
