### ISSUE TITLE
[Docs] Trailing backslash not redirecting on Compatibility Matrix

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5082]
#### Current State
When a user navigates to https://docs.meshery.io/project/compatibility-matrix/ using the breadcrumb trail, a trailing slash is present in the URL, causing the user to land on a 404 page.
<img width="948" alt="Screen Shot 2022-02-16 at 10 10 42 AM" src="https://user-images.githubusercontent.com/7570704/154307384-82c5759d-54c1-4bc3-a826-3989f4f82046.png">

Source: https://github.com/meshery/meshery/blob/master/docs/pages/project/compatibility_matrix/compatibility.md

#### Desired State
The compatibility matrix page should include a `redirect` from `/` to the page without trailing slash.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Akshit42-hue** [comment]
Can I work on this issue @leecalcote

**Comment by asubedy** [comment]
@Akshit42-hue You can take reference to this issue, this is the same issue.

**Comment by leecalcote** [comment]
@Akshit42-hue the fix is a one line change. Let's wrap this up in 24 hours or kindly remove your assignment yourself so that another contributor can complete it.

**Comment by Akshit42-hue** [comment]
In https://github.com/meshery/meshery/blob/master/docs/pages/project/compatibility_matrix/compatibility.md file I have to add "redirect_from: /" that's the only change I want to make. Am I right? @leecalcote

**Comment by leecalcote** [comment]
Spot on. 👍

**Comment by asubedy** [comment]
@Akshit42-hue  this was the issue I was talking about. https://github.com/meshery/meshery/issues/4930

**Comment by Akshit42-hue** [comment]
Should I commit both issue and merge it in a single PR @asubedy

**Comment by asubedy** [comment]
Lets not do that, you can work on this issue separately, and we will look into that issue separately, if it is not being worked on you can work on that by making a new PR
