### ISSUE TITLE
[UI] Navigating Contexts

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#5087]
#### Current Behavior
The new dropdown selects any particular context and stores it in React state (in v0.7 Redux store) and passes around with props(this.props.activeContext) but this is not being used by the UI. For example, if we are on the Istio page and try to deploy it after selecting some context, that context will not be used(It will have to be passed in query parameters).

#### Desired Behavior
The selected context should be used. 

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Seems like we'll want Redux here, but can't wait that long. // @sudo-NithishKarthik

**Comment by sudo-NithishKarthik** [comment]
I'll implement a workaround for this.

**Comment by leecalcote** [comment]
Thank you, @Chadha93 👍
