### ISSUE TITLE
[Docs] Promote `oam` REST endpoint from experimental

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5092]
#### Current State
On https://docs.meshery.io/reference/rest-apis, the `oam` endpoint is listed as experimental, which is no longer the case.

#### Desired State
The swagger docs should reflect the new endpoint location and description.

| Old | New | Description |
|----------------------------|---------------|--------------------------------------------------------------------------------------|
| /experimental/oam/{type} | /oam/{type} | {type} being of either trait, scope, workload; registration of adapter capabilities. |
| /experimental/oam/trait | /oam/trait | {type} being of either trait, scope, workload; registration of adapter capabilities.
| /experimental/oam/workload | /oam/workload | {type} being of either trait, scope, workload; registration of adapter capabilities. |

Reference:
https://docs.google.com/spreadsheets/d/1ABJCbfQRi0uN_YoP2kmHZ-lTI4S4QuvRk1_unomKNRE/edit#gid=1241442399:

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by zahertalab** [comment]
I'm interested.

**Comment by alceil** [comment]
Hey @leecalcote  , I am Ashish Tom, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. And I would also like some pointers on how to get started.Thank you

**Comment by leecalcote** [comment]
Oh, my goodness. I missed your message, @zahertalab. My apologies. Is this an issue that is still of interest?

**Comment by leecalcote** [comment]
Hi @alceil, yes, if you'd like to give this a shot in the meanwhile in the event that @zahertalab doesn't respond...

**Comment by alceil** [comment]
Sure @leecalcote

**Comment by zahertalab** [comment]
> Oh, my goodness. I missed your message, @zahertalab. My apologies. Is this an issue that is still of interest? I would be fantastic if you were to tackle this one.

Of course, don't worry. For now, let @alceil make a shot until I finish some other things and come back.

**Comment by alceil** [comment]
Thanks @zahertalab

**Comment by alceil** [comment]
I have raised a pr could you please review it @leecalcote
