### ISSUE TITLE
[UI] All Contexts should be visible on the dashboard.

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#5099]
#### Current Behavior
Only the current context is visible on the dashboard. 

#### Desired Behavior
All configured kubernetes clusters should be visible.

#### Screenshots/Logs
<img width="688" alt="Screenshot 2022-02-21 at 10 37 02 AM" src="https://user-images.githubusercontent.com/53532328/154986593-74265512-c7c8-4545-9cd4-ac3ace928f6e.png">

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ShivamTyagi12345** [comment]
I will like to take up this issue👋🏻

**Comment by leecalcote** [comment]
@ShivamTyagi12345 good deal. Before taking assignment, will you propose a solution?

**Comment by heyanurag** [comment]
I would like to work on this issue... @warunicorn19 Can you please elaborate what is the expected behaviour? I am new to the project and still exploring...

**Comment by ShivamTyagi12345** [comment]
We would likely appreciate a solution before actually jumping on the issue :) I am currently working on finding one . But if u have one please let us know and go ahead with the PR @heyanurag

**Comment by heyanurag** [comment]
Absolutely! Could you point me to instructions on setting up the project locally :)

**Comment by leecalcote** [comment]
https://docs.meshery.io/project/contributing

**Comment by antariksh17** [comment]
@leecalcote  do i have to write out my solution before getting assigned to this?

**Comment by warunicorn19** [comment]
Yes a plan of action is necessary to get this issue assigned.

**Comment by asubedy** [comment]
One plan of action can be displaying all the contexts on the dashboard, but greying out the contexts, that has not been selected on the context switcher (making the chip not clickable)

**Comment by Harshit-Dandriyal** [comment]
@warunicorn19 I can work on this, Sending my action of plan as soon as possible, You can assign this issue to me.

**Comment by Harshit-Dandriyal** [comment]
@asubedy Yes, We can do this easily, It will also look good, I will soon send a prototype of this in meshery UI slack channel..
