### ISSUE TITLE
[UI] Current Context should be visible in the text field

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#5100]
#### Current Behavior
The Current Context Text field doesn't show the current context name. 

#### Desired Behavior
The Current context should be visible in the text field

#### Screenshots/Logs
<img width="498" alt="Screenshot 2022-02-21 at 10 34 20 AM" src="https://user-images.githubusercontent.com/53532328/154986929-d08c31aa-e277-4198-abf0-5d71ab69b320.png">

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Sonichigo** [comment]
Can i take this up?

**Comment by Akshit42-hue** [comment]
Can I work on the issue @warunicorn19

**Comment by warunicorn19** [comment]
@Akshit42-hue @Sonichigo since both of you have shown interest into this issue, let's hear a plan of action before proceeding to assign someone.

**Comment by Sonichigo** [comment]
@warunicorn19 My SOP would be first testing out the on local machine => trying to replicate the issue, then moving to the file where code is, trying few changes that could potentially solve the issue.

**Comment by warunicorn19** [comment]
okay sounds good, please give it a go @Sonichigo

**Comment by leecalcote** [comment]
@Sonichigo any progress to report?

**Comment by Harshit-Dandriyal** [comment]
@Sonichigo Great. If you need assistance on this, you can contact me at slack :)

**Comment by Sonichigo** [comment]
![image](https://user-images.githubusercontent.com/53110238/161667800-95a78e40-08e2-45f1-ac3d-a94abaab2e7c.png)

The KubeConfig File is also not showing the name, Tried by making a cluster on Azure and used it's kubeconfig file (in YML format)

**Comment by Sonichigo** [comment]
Please assign this issue to @Harshit-Dandriyal , i won't be able to continue on this forward

**Comment by Harshit-Dandriyal** [comment]
@warunicorn19 Yes, I can take this issue :)
