### ISSUE TITLE
[Docs] Page layout includes unnecessary margin

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5113]
#### Current State
Docs pages that use either the `default` or `page` [layout](https://github.com/meshery/meshery/blob/master/docs/_layouts/) seem to have an unnecessary margin included, wasting space that can be used for docs text.

<img width="1228" alt="Screen Shot 2022-02-23 at 10 47 27 AM" src="https://user-images.githubusercontent.com/7570704/155367337-4858b8df-e468-4d5a-a5a0-6ce258e39338.png">

#### Desired State
Recover the unused whitespace; eliminate the margin/padding in screenshot.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sidd-oo** [comment]
Can I take this issue?

**Comment by leecalcote** [comment]
Sounds real good, @sidd-oo 👍

**Comment by shubhangi013** [comment]
Is this issue still open?

**Comment by shubhangi013** [comment]
> > Is this issue still open?
> 
> @shubhangi013 I am working on it, It is almost done. I will be making a PR for this issue by EOD.

Ah cool. All the best !
