### ISSUE TITLE
[UI] Create a Card view for Designs

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#5115]
#### Current Behavior
There's only a table view to view Designs right now. 

#### Desired Behavior
Implement a card view for it. 

#### Mockups
https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=4525%3A26868

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
@asubedy it would be great if you'd take a look at this.

**Comment by warunicorn19** [comment]
@asubedy any updates to share on this? If so please add to the minutes of the meshery dev call.

**Comment by asubedy** [comment]
> @warunicorn19 Can I try this issue if no work has been done on this?
> But I don't have access to figma files

Hi @Harshit-Dandriyal I have been working on this for some time now its almost complete. Will make a PR by today.

**Comment by Harshit-Dandriyal** [comment]
@asubedy Ok nice ,have a happy PR :)

**Comment by leecalcote** [comment]
@Harshit-Dandriyal, that PR presents a good opportunity to offer review and feedback on this fix when it arrives.

**Comment by Harshit-Dandriyal** [comment]
@leecalcote yess, I think this will be quite a major upgrade, I am excited for this...😃

**Comment by leecalcote** [comment]
My excitement is right there with yours. :)
