### ISSUE TITLE
[CI] [Cypress] Fix commented out E2E tests to Deploy Applications/Patterns Istio-dependent Configs through Meshery UI

### ISSUE THREAD

**Issue by MarioArriaga92** [meshery/meshery#5117]
#### Current Behavior

E2E tests that cover Meshery's Service Mesh Configuration Management functionality (Applications/Patterns) to Deploy Configuration Changes are [commented out](https://github.com/meshery/meshery/blob/master/ui/cypress/integration/e2e/service_mesh_configuration_management_spec.js#L14-L30) because of missing steps to install istio ([ci.yaml workflow's L216-221](https://github.com/meshery/meshery/blob/master/.github/workflows/ci.yml#L216-221) just installs meshery-istio adapter) before test steps to attempt Istio-dependent Application/Pattern Configuration Deployments **(follow-up of contributions on issue #4717 and PR #4826)**

#### Desired Behavior

[E2E tests that cover Deploying Applications & Patterns Configuration Changes](https://github.com/meshery/meshery/blob/master/ui/cypress/integration/e2e/service_mesh_configuration_management_spec.js#L14-L30) should be uncommented and ensure any "dependencies" are present in the cluster before attempting deployment

#### Implementation

Include steps so Meshery handles installation of Istio or any other "dependency" on service mesh requirements to be present on the cluster before attempting deployment test steps, just as an end with context of configuration pattern file he/she is using would do. (through [Service Mesh Configuration Lifecycle Management functionality](https://docs.meshery.io/functionality/lifecycle-management#service-mesh-lifecycle-management))

#### Acceptance Tests

- [ ] Pattern Deploy Test with service-mesh-patterns-samples/IstioFilterPattern yaml config is uncommented and does not fail with `500 Internal Server Error with payload 'rpc error: code = Unknown desc = no matches for kind "EnvoyFilter" in version “networking.istio.io/v1alpha3”\n`
- [ ] Application Deploy Test with service-mesh-patterns-samples/bookInfoPattern yaml config is uncommented and does not fail with `500 Internal Server Error Incorrect/incomplete request payload to POST /api/application/deploy endpoint instead of actual yaml file content` nor  `500 Internal Server Error with payload 'invalid workload of type: Application\n'`

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by MarioArriaga92** [comment]
Working on this

**Comment by MarioArriaga92** [comment]
Will work on this right away.

**Comment by leecalcote** [comment]
Uh-oh. Stale bot police have arrived. 🚨

**Comment by legendarykamal** [comment]
@MarioArriaga92 I think you have been busy in a while, I will dig in this meanwhile :)
