### ISSUE TITLE
[UI] Replicate Imports for Filters and Application

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#5121]
#### Current Behavior
The file import buttons are in the table toolbar for filters and applications
![Screenshot from 2022-02-25 12-56-59](https://user-images.githubusercontent.com/65453826/155673105-ac010531-1ed9-45ff-b651-338bc4ce03cb.png)

#### Desired Behavior
Change it accordingly to the patterns UI import buttons to have a smooth user experience across all configurations
![Screenshot from 2022-02-25 12-57-18](https://user-images.githubusercontent.com/65453826/155673367-b9d9384e-3217-4ace-9a44-753a814a4a58.png)

#### Implementation
Refer to the current implementation of import buttons in patterns UI

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Akshit42-hue** [comment]
Can I work on this issue @Chadha93

**Comment by SAEb-ai** [comment]
@Chadha93 Can I please take up this issue in case @Akshit42-hue is not working on this? 

P. S. I have approxiametely implemented the solution locally.

**Comment by Akshit42-hue** [comment]
Go ahead @SAEb-ai . I am unassigning myself
