### ISSUE TITLE
[UI] `make build-ui` gives error in Node.js v17.6.0

### ISSUE THREAD

**Issue by adi611** [meshery/meshery#5125]
#### Current Behavior

While using Node.js v17.6.0 (which is the latest version as of now) if we run `make build-ui` we will get some errors.

#### Desired Behavior

`make build-ui` should not produce errors in Node.js v17.6.0

#### Screenshots/Logs

![Screenshot from 2022-02-25 15-10-55](https://user-images.githubusercontent.com/50960175/155694220-7f03380e-ab51-4b46-a7d6-fb89a0759219.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac **Linux** Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by chinmaym07** [comment]
Hey @adi611 this issue is not specific to meshery . Please refer to [this](https://github.com/facebook/create-react-app/issues/11708)

**Comment by adi611** [comment]
> Hey @adi611 this issue is not specific to meshery . Please refer to [this](https://github.com/facebook/create-react-app/issues/11708)

Ok so should I close it?
