### ISSUE TITLE
[CI] golangci-lint for Meshery Server

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5162]
#### Current Behavior
Running golanci-lint on Meshery Server codebase produces a number of failed checks. See https://github.com/meshery/meshery/runs/5345735293?check_suite_focus=true

#### Desired Behavior
No failed checks when running against Meshery Server.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by navendu-pottekkat** [comment]
Invalid issue. See comments starting from: https://github.com/meshery/meshery/pull/5131#pullrequestreview-897823439

**Comment by navendu-pottekkat** [comment]
Opened issue to track related change: https://github.com/meshery/meshery/issues/5163
