### ISSUE TITLE
[CI] Evaluate linters for Golang CI checks

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#5163]
#### Current Behavior

Meshery currently uses [golangci-lint](https://github.com/golangci/golangci-lint) to run lint checks for Golang code in mesheryctl and Meshery Server.

The linters used are configured in [.golangci.yml](https://github.com/meshery/meshery/blob/master/.golangci.yml) configuration file.

We are only using a few of the available linters right now.

#### Desired Behavior

Evaluate and use [other available linters](https://golangci-lint.run/usage/linters/) and run these in Meshery CI.

#### Implementation

1. Uncomment the needed linters from the [.golangci.yml](https://github.com/meshery/meshery/blob/master/.golangci.yml) file.
2. Run `golangci-lint` locally with this new configuration file.
3. Fix the new lint errors that show up.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by navendu-pottekkat** [comment]
@meshery/ci-release-maintainers @meshery/mesheryctl-maintainers Suggestions?

**Comment by leecalcote** [comment]
Do you have suggestions on new linters to use? Let's get Meshery Server listing started, even if its the same linters used for `mesheryctl`

**Comment by leecalcote** [comment]
Assuming @navendu-pottekkat is not taking this forward, @sourikghosh is this an issue that you can carry forward?

**Comment by navendu-pottekkat** [comment]
@leecalcote I will look into this and report here.

**Comment by leecalcote** [comment]
A missed commitment.
