### ISSUE TITLE
[CI] Change workflow names

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#5165]
#### Current Behavior

The current workflow names does not follow any conventions and is difficult to track.

#### Desired Behavior

Change the test names as proposed in the [Master Test Strategy](https://docs.google.com/document/d/14vbwnKafqxrr-cJOmLWEvvj75MFrxFKiUdfPwZRhg64/edit#heading=h.rb6fnqxhzk4d).

This will be the first step in moving towards the newly proposed test scenarios.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by SAEb-ai** [comment]
@navendu-pottekkat @leecalcote May I please be assigned to this? Thanks!

**Comment by leecalcote** [comment]
@SAEb-ai thanks for asking. This isn’t a desired change, though. Let’s find you another one.
