### ISSUE TITLE
[Server] Preferences: User preference setting change causing fault

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5174]
#### Current Behavior
Meshery Server faults on change of user preferences. This fault occurs whether the user is signed into the Local or Remote Providers.

#### Expected Behavior
User preference should be updated without fault.

#### Screenshots/Logs

```
14:54:46 http: panic serving [::1]:57053: runtime error: invalid memory address or nil pointer dereference
goroutine 352 [running]:
net/http.(*conn).serve.func1(0xc000c2ce60)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:1824 +0x153
panic(0x64adf60, 0x7f915a0)
	/Users/lee/sdk/go1.16.4/src/runtime/panic.go:971 +0x499
github.com/layer5io/meshery/handlers.(*Handler).UserPrefsHandler(0xc000a90100, 0x6c77550, 0xc00056c620, 0xc001739900, 0xc0016eac60, 0xc000572ec0, 0x6cc0b10, 0xc000270640)
	/Users/lee/code/meshery/handlers/user_handler.go:67 +0x199
github.com/layer5io/meshery/handlers.(*Handler).SessionInjectorMiddleware.func1(0x6c77550, 0xc00056c620, 0xc001739500)
	/Users/lee/code/meshery/handlers/middlewares.go:168 +0x8d9
net/http.HandlerFunc.ServeHTTP(0xc0005d46a8, 0x6c77550, 0xc00056c620, 0xc001739500)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2069 +0x44
github.com/layer5io/meshery/handlers.(*Handler).AuthMiddleware.func1(0x6c77550, 0xc00056c620, 0xc001739500)
	/Users/lee/code/meshery/handlers/middlewares.go:65 +0x129
net/http.HandlerFunc.ServeHTTP(0xc00069c920, 0x6c77550, 0xc00056c620, 0xc001739500)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2069 +0x44
github.com/layer5io/meshery/handlers.(*Handler).ProviderMiddleware.func1(0x6c77550, 0xc00056c620, 0xc001739400)
	/Users/lee/code/meshery/handlers/middlewares.go:33 +0x1e7
net/http.HandlerFunc.ServeHTTP(0xc00069c940, 0x6c77550, 0xc00056c620, 0xc001739400)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000b30180, 0x6c77550, 0xc00056c620, 0xc001738700)
	/Users/lee/code/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc0002f2a80, 0x6c77550, 0xc00056c620, 0xc001738700)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000c2ce60, 0x6c7e888, 0xc000572000)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:3013 +0x39b
```

#### Environment

- **Host OS:** Mac
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v0.6.0-rc-5b
- **Meshery Client Version:** stable-v0.6.0-rc-5b

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sourikghosh** [comment]
can I pick this issue ?

**Comment by leecalcote** [comment]
@sourikghosh thanks so much for asking. The fix for this issue will span multiple code bases. It's a relatively involved and moderately difficult issue. Let me help you find another golang-based issue in which it will offer an easier, and therefore more successful, ramp into the project.

**Comment by leecalcote** [comment]
@sourikghosh, I see you open PR now. That's great. Will you confirm that this fix works in the following scenarios:

1. When signed in under the Local "None" Provider, User preferences can be saved in our persisted for the lifetime of the Meshery Server deployment
1. When signed in under the Remote "Meshery" Provider, user preferences can be saved and are persisted in between user sessions and in between Meshery Server deployments.

I had a call with @theBeginner86  yesterday to review these different scenarios and the expected behavior, So he is a good individual with which to collaborate to the extent that help is needed.
