### ISSUE TITLE
[Server] K8s component generation failure

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5180]
#### Current Behavior
Meshery Server deployed in-cluster is having difficulty generating k8s components.

#### Screenshots/Logs
```
meshery-97565c89f-sj8gq	|	Looking for kubeopenapi-jsonschema in  /home/appuser/.meshery/bin
meshery-97565c89f-sj8gq	|	time="2022-03-07T20:36:49Z" level=error msg="fork/exec /home/appuser/.meshery/bin/kubeopenapi-jsonschema: exec format error" app=meshery code=2177 probable-cause="component generation was canceled due to deletion or reload of K8s context.Invalid kubeconfig.Filters passed incorrectly in config.Could not fetch API resources from Kubernetes server" severity=2 short-description="failed to register/create kubernetes components for contextID 9630b296aa4c37a9363acedc9a04ebe1" suggested-remediation="If there is the log \"Starting to register ...\" for the same contextID after this error means that for some reason the context was reloaded which caused this run to abort. In that case, this error can be ignored..Make sure that the configuration filters passed are in accordance with output from /openapi/v2"
```

#### Environment

- **Host OS:** Mac 
- **Platform:**  Kubernetes
- **Meshery Server Version:** stable-v0.6.0-rc-5b
- **Meshery Client Version:** stable-v0.6.0-rc-5b

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
It is using the wrong binary, it should have used `kubeopenapi-jsonschema-darwin` for mac.
Can you exec into the meshery pod and give me output of the command `go env`
