### ISSUE TITLE
[Docs] Content misaligned in the main readme file.

### ISSUE THREAD

**Issue by ghulamyazdani** [meshery/meshery#5184]
#### Current State
Content misaligned in the main readme file.
![image](https://user-images.githubusercontent.com/55938346/157293556-9b6639ec-7757-44fa-ae29-9210a7b2fc97.png)

#### Desired State
Content should be aligned properly so that it would be more readable and also would look better.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by RakeshPotnuru** [comment]
@leecalcote 
Can I take this issue?

**Comment by leecalcote** [comment]
Sounds good, @RakeshPotnuru. You're not working this, are you, @ghulamyazdani?

**Comment by ghulamyazdani** [comment]
No @leecalcote , I think we can label this as good first issue
