### ISSUE TITLE
[UI] Design Configurator: Component dropdown should open downwards

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5187]
#### Current Behavior
In the Design Configurator (http://localhost:9081/configuration/patterns), the component list opens upwards.

<img width="652" alt="Screen Shot 2022-03-08 at 2 56 12 PM" src="https://user-images.githubusercontent.com/7570704/157323665-0af5b1fc-bbb8-43b9-8c13-06860508f713.png">

#### Desired Behavior
This list should open downwards.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sidd-oo** [comment]
Can I work on this issue? @leecalcote

**Comment by leecalcote** [comment]
Sounds real good.

**Comment by Chadha93** [comment]
@sidd-oo Any updates? Need help with this?

**Comment by sidd-oo** [comment]
> @sidd-oo Any updates? Need help with this?

Sorry for the delay, I am on it.  @Chadha93

**Comment by Chadha93** [comment]
@sidd-oo any progress or blockers here?

**Comment by Harshit-Dandriyal** [comment]
@Chadha93 you can assign this to me

**Comment by Chadha93** [comment]
> @Chadha93 you can assign this to me

Sure, thanks for heads up  @Harshit-Dandriyal
