### ISSUE TITLE
[Helm] Two Chart sets should use same networking; Broker should use LoadBalancer as default networking

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5195]
The original issue description was invalid. Please see this comment for a description of the issue: https://github.com/meshery/meshery/issues/5195#issuecomment-1204316582

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by CyrineG** [comment]
Hello @leecalcote! Can I work on this issue? It will be my first issue, but I've been reading up on how Meshery works and I think it will be interesting to dig into what's causing this

**Comment by Chadha93** [comment]
Assigning this to you @CyrineG. Do catch up with @Revolyssup if you get any queries regarding this issue.

**Comment by leecalcote** [comment]
CLARIFICATION:

What's needed is to reconcile any differences between the two sets of Helm Charts. Whether the Operator and Broker are
using different networking is inconsequential. What is important is that both sets of Helm Charts have Meshery Broker set to LoadBalancer by default, but as an overridable configuration.

**Comment by leecalcote** [comment]
In terms of the fact that we have two sets of Helm Charts, this is not ideal. Ideally, Meshery project has:

- 1 set of charts
- mesheryctl and Meshery Server both need to deploy Meshery Operator and Adapters. Meshery Server doesn’t need to deploy itself, though.
- Adapter deployments are optional.
- Meshery Server deployment is optional.
- Meshery Operator is mandatory.

**Comment by CyrineG** [comment]
> What's needed is to reconcile any differences between the two sets of Helm Charts. Whether the Operator and Broker are
> using different networking is inconsequential. What is important is that both sets of Helm Charts have Meshery Broker set to LoadBalancer by default, but as an overridable configuration.

I think this is already the case. When I use meshery CLI or the meshery server the Broker service is LoadBalancer. Since the service type is set to LoadBalancer in both parent charts for Broker ([meshery](https://github.com/meshery/meshery/blob/master/install/kubernetes/helm/meshery/values.yaml#L55) and [meshery-operator](https://github.com/meshery/meshery/blob/master/install/kubernetes/helm/meshery-operator/values.yaml#L65)), the Broker is already set to LoadBalancer by default.

**Comment by leecalcote** [comment]
@CyrineG ok, good deal. Thank you. So, now that we're on this wild goose chase...

Let's close this issue as a successful investigation and open a new one to consolidate the two Helm Chart sets or at least investigate their possible consolidation.

**Comment by leecalcote** [comment]
@CyrineG given our chat and the notes above, would you like to create this second issue?

**Comment by CyrineG** [comment]
@leecalcote Okay!
