### ISSUE TITLE
[UI] Multi Cluster Context Switcher Enhancement

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#5209]
#### Current Behavior
Make mentioned changes to context-switcher 
![image](https://user-images.githubusercontent.com/65453826/158032564-ae3add26-52ee-4ec6-bfa3-a6a3e805c232.png)

#### Desired Behavior
1. Make this pullout menu under the shadow of the Meshery title bar.
2. Make the search field text breathable. (add some padding)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Ardent10** [comment]
I would like to work on this as a OpenForce22 participant.

**Comment by Harshit-Dandriyal** [comment]
I would like to work on this issue

**Comment by leecalcote** [comment]
@Ardent10, yes, see the two "Contributing to Meshery UI" links above. 

@Harshit-Dandriyal excellent. 

Please confirm when you have Meshery UI building and running in your local environment and we'll get the issue assigned to you. 👍

**Comment by leecalcote** [comment]
The select checkbox and the Kubernetes chip need to be horizontally aligned, too.

**Comment by Harshit-Dandriyal** [comment]
@leecalcote Can you assign this issue to me, will be back with PR in few days. :)

**Comment by Chadha93** [comment]
All yours @Harshit-Dandriyal
