### ISSUE TITLE
[UI] Support for Cilium

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5227]
#### Current Behavior
Meshery Adapter for Cilium Service Mesh v0.1.0 is in alpha, readying for beta.

#### Desired Behavior
Support this new adapter in the client: Meshery UI.

#### Implementation
Prepare logo, menu item, chip and so on for Meshery Adapter for Cilium.

#### Acceptance Tests
1. This adapter should be an optional installation.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@MUzairS15 will you ensure that Cilium service mesh deployments show in the Meshery UI Dashboard?

**Comment by MUzairS15** [comment]
On it

**Comment by Chadha93** [comment]
@MUzairS15 I guess you made a fix for this right? Cilium is available/shown in the Meshery UI dashboard.

**Comment by leecalcote** [comment]
I haven't seen a screenshot... it would be great to see one.

**Comment by leecalcote** [comment]
<img width="702" alt="Screen Shot 2022-06-10 at 3 59 12 PM" src="https://user-images.githubusercontent.com/7570704/173150392-7a45ae45-3891-4b82-95a2-1775beab2bb0.png">

Good to go.
