### ISSUE TITLE
[Docs] Error Code Reference: Formatting

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5231]
I wonder how this reflects in the Error Code Reference Guide. We might need to swap `\n` for `<br />`. @shubham-tyagi, will you confirm this?

_Originally posted by @leecalcote in https://github.com/meshery/meshery/pull/5230#pullrequestreview-912188033_

**Comment by leecalcote** [comment]
@shubham-tyagi working on this?

**Comment by shubham-tyagi** [comment]
yeah @leecalcote , I have not yet looked into it. Will look into it today.

**Comment by leecalcote** [comment]
Good.

**Comment by Akshit42-hue** [comment]
Hey @leecalcote can I work on this issue
