### ISSUE TITLE
[UI] Add Cilium Service Mesh

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5232]
#### Current Behavior
The [Meshery Adapter for Cilium Service Mesh](https://github.com/meshery/meshery-cilium) is supported as a generic adapter currently without support for logo and default port reservation.

#### Desired Behavior
- [x] 1. The Adapter should be visible in the navigation menu, dashboard, settings.
- [x] 2. The Adapter's components should show inside of the Designer.
- [ ] 3. The Adapter's operations should show inside of Lifecycle menu.

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
The first portion of this issue is completed.

@MUzairS15, the second portion remains.

**Comment by MUzairS15** [comment]
@leecalcote reolved by https://github.com/meshery/meshery-cilium/pull/34
<img width="1440" alt="Screenshot 2022-03-24 at 10 45 28 AM" src="https://user-images.githubusercontent.com/79860504/159847420-94a952e0-6cd7-4d56-98c6-78faedcf1097.png">
