### ISSUE TITLE
Failed to get the file 404 

### ISSUE THREAD

**Issue by m9rco** [meshery/meshery#5244]
#### Current Behavior

```bash
 mesheryctl system start
```

```bash
Starting Meshery...
⣷ Deploying Meshery on KubernetesError: failed to start Meshery
See https://docs.meshery.io/reference/mesheryctl/system for usage details
: cannot start Meshery: failed to get the file 404 status code for https://meshery.github.io/meshery.io/charts/meshery-v0.6.1.tgz file
```

#### Expected Behavior

Successful

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
<img width="772" alt="image" src="https://user-images.githubusercontent.com/18391791/159401462-d0a45385-5513-4f72-8b56-5d6e588c069d.png">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Oh, no! This release was just retracted (an accidentally pre-release). Thank you for filing this bug. This is a high priority issue.

**Comment by m9rco** [comment]
hhhh , thanks leecalcote, 

```
curl -L https://git.io/meshery
```

`git.io`  Download will also fail, where is the source of this bash file?

**Comment by leecalcote** [comment]
Oof. That's unfortunate. Here is the source of the bash file - https://github.com/meshery/meshery/blob/master/meshery

**Comment by leecalcote** [comment]
@m9rco a new release of Meshery was just made: `stable-v0.6.0-rc-5f`, which might fix the missing package issue seen when running`mesheryctl system start`...

**Comment by m9rco** [comment]
I tried again. still prompt exception @leecalcote 

```bash
 curl -L https://github.com/meshery/meshery/blob/master/meshery | PLATFORM=kubernetes bash -
```

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/18391791/159404239-b5ee5a0b-ea8a-4694-9936-2e3bb8a7894e.png">

 cannot start Meshery: failed to get the file 404 status code for https://meshery.github.io/meshery.io/charts/meshery-v0.6.1.tgz file

**Comment by leecalcote** [comment]
☹️ Ok, thank you for testing this again. I'm digging into this deeper. We're in need of removing an errant release of `v0.6.1` that should never have been made. Need to be rid of this from the helm chart.

**Comment by m9rco** [comment]
Thank you for your effort. 🤩  @leecalcote

**Comment by leecalcote** [comment]
Absolutely, @m9rco. 🤝 OK, both the `v0.6.0` and the `v0.6.1` erroneous releases have been removed from the helm chart index, which seems to be working. Meshery's entry on [Artifact Hub](https://artifacthub.io/packages/helm/meshery/meshery) shows `v0.6.0-rc-5f` as being the latest release now (which is accurate). I'll keep my 🤞 that `mesheryctl system start` works for you now...

**Comment by leecalcote** [comment]
@m9rco fyi, there's an upcoming, private beta of [MeshMap](https://meshery.io/meshmap) that might interest you. Be sure to join the waiting list, if so.

**Comment by m9rco** [comment]
ok, hhhh,  I'm looking forward to it  🤝

**Comment by leecalcote** [comment]
@m9rco I _think_ that we're good to go here (that this issue is fixed). When you have a moment, will you confirm? 🙏 

I encourage you to join the community Slack workspace: http://slack.meshery.io - it'd be good to get you introduced to others in the community and to MeshMap.

**Comment by m9rco** [comment]
OK，I run it on my private cluster and the following happens

```bash
mesheryctl system start
```

<img width="829" alt="image" src="https://user-images.githubusercontent.com/18391791/159604858-98abce01-9186-40ba-8711-88ec322df77f.png">

<img width="482" alt="image" src="https://user-images.githubusercontent.com/18391791/159604944-1b56052c-4e1a-4b2a-b846-575fa3e6aac3.png">


<img width="1204" alt="image" src="https://user-images.githubusercontent.com/18391791/159605086-46f27779-40d7-48d5-abd3-689e3bb48769.png">

**Comment by m9rco** [comment]
Loadbalancer was finally used and there are no exceptions

<img width="921" alt="image" src="https://user-images.githubusercontent.com/18391791/159605213-664afc45-b528-4023-a930-b3e94d025deb.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/18391791/159605269-f0d61fcf-9ac3-43fe-9ee8-a4506122d98f.png">

**Comment by leecalcote** [comment]
yay! 🎈 😄
