### ISSUE TITLE
[Docs] Add top margin so that in-page anchor tags align with menu bar

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5249]
#### Current State
Users that visit a hyperlink with table of contents anchor like this: https://docs.meshery.io/reference/mesheryctl#service-mesh-pattern-configuration-and-management, land on the page at the appropriate place, but the menu bar covers up the section header.

<img width="1419" alt="Screen Shot 2022-03-22 at 2 51 08 PM" src="https://user-images.githubusercontent.com/7570704/159564174-389058de-1768-4a1f-80ee-05780e659ee6.png">

#### Desired State
Add a top margin or other to ensure that users can still read the section heading.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Harshit-Dandriyal** [comment]
yes, It's happening in every side link of docs. I would like to work on this issue

**Comment by karnatisrinivas** [comment]
Hello @leecalcote , If this issue haven't assigned to anyone, I would like to work on this.
