### ISSUE TITLE
Meshery Application Support for Docker Compose 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5250]
#### Current Behavior
Meshery users can import Kubernetes manifests into Meshery Applications. These applications can be then be configured and managed through Meshery's various features.

#### Desired Behavior
Allow users to bring Docker Compose applications and ingest them as Meshery Applications.

#### Implementation
1. Incorporate `kompose` as a Meshery Server capability behind the `/application` endpoints. 
1. Use the file descriptors / schema of each type of application manifest to intelligently discern whether the user is importing K8s manifests or Docker Compose files.
1. Consider future support of Helm Charts under this same use case.
1. Do not store the original Docker Compose file.

#### Acceptance Tests
1. Users can import either Kubernetes Manifests or Docker Compose files as Meshery Applications.
1. Users can open their Applications in Design Configurator or in extensions, like MeshMap.
1. Users can import using either Meshery UI or `mesheryctl pattern apply`.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
This package looks promising - https://github.com/kubernetes/kompose/blob/master/pkg/transformer/transformer.go

**Comment by 4molybdenum2** [comment]
https://github.com/meshery/meshery/blob/7c636a94729665e4a94e761b7b501935e198fc91/handlers/meshery_application_handler.go#L126-L135

@leecalcote isn't this what this is doing?

**Comment by leecalcote** [comment]
Yes, @4molybdenum2. The Acceptance Criteria defined in this issue needs to be verified prior to closing the issue.

**Comment by leecalcote** [comment]
@4molybdenum2 will you run a quick check and confirm that each the three Acceptance Tests are passing now? I think this issue is complete.

**Comment by 4molybdenum2** [comment]
I will look into it

**Comment by leecalcote** [comment]
Thank you, @4molybdenum2

**Comment by 4molybdenum2** [comment]
LGTM
