### ISSUE TITLE
[Server] Unable to load kubeconfig

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5260]
#### Current Behavior
Not able to connect to Kubernetes. Please see logs.

#### Screenshots/Logs

attached.
[server-log.txt](https://github.com/meshery/meshery/files/8338590/server-log.txt)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Revolyssup any initial analysis?

**Comment by leecalcote** [comment]
ping

**Comment by Revolyssup** [comment]
> ping

The logs point to some networking problem at that time. Meshery could not talk to kubenetes. Did you get this again?
