### ISSUE TITLE
[mesheryctl] Failing pattern delete command

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#5262]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

The pattern delete command is failing for any URL. Although the same URL works for pattern apply command
#### Screenshots/Logs

![Screenshot_20220324_213200](https://user-images.githubusercontent.com/43276904/159959704-8e8941d9-8e24-4e31-bfa1-853dcfc063e9.png)

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gr455** [comment]
@Revolyssup @piyushsingariya Mind if I try this out?

**Comment by piyushsingariya** [comment]
> @Revolyssup @piyushsingariya Mind if I try this out?

sure!
