### ISSUE TITLE
[Server] Remove extraneous kubeopenapi-json related error log

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5281]
#### Current Behavior
The following error should not be logged while kubeopenapi-json is running and in the process of generating components. 

```
ERRO[2022-03-27T09:48:18-05:00] Kubernetes config is not initialized with Meshery  app=meshery code=1001 probable-cause= severity=2 short-description="Kubernetes client not initialized" suggested-remediation="Upload your kubernetes config via the settings dashboard. If uploaded, wait for a minute for it to get initialized"
```

#### Acceptance Tests
1. This error is not logged while `kubeopenapi-json` is actively running.
1. This error should not continue to be logged after kubeopenapi-json has completed its task.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Ping, ping.

**Comment by leecalcote** [comment]
@Revolyssup was this removed? Point to the PR?

**Comment by Revolyssup** [comment]
> @Revolyssup was this removed? Point to the PR?

https://github.com/meshery/meshery/pull/5698
