### ISSUE TITLE
[Server] Duplicate Error Codes

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5282]
#### Current Behavior
Meshery Server has a number of duplicate error codes to be resolved.

#### Expected Behavior
Running `make error` produces no errors.

#### Screenshots/Logs
```
....
ERRO[0001] duplicate error code '2156', name: 'ErrGetFilterCode'
ERRO[0001] duplicate error code '2156', name: 'ErrMesheryInstanceIDCode'
ERRO[0001] duplicate error code '2156', name: 'ErrCreatePatternServiceCode'
ERRO[0001] duplicate error code '1006', name: 'ErrAddonSubscriptionCode'
ERRO[0001] duplicate error code '1006', name: 'ErrAddonSubscriptionCode'
....
````

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Dups. Who needs 'em?

**Comment by leecalcote** [comment]
@gr455 have you worked with Meshery Errors before?

**Comment by gr455** [comment]
@leecalcote absolutely. I'll clean this one up

**Comment by leecalcote** [comment]
@gr455 oh, that's excellent. Thank you. 👍
