### ISSUE TITLE
[Docs] Improve help docs for Error Code 2177 in Meshery Server

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5300]
#### Current State
```
time="2022-03-29T03:21:58Z" level=error msg="exit status 127" app=meshery code=2177 probable-cause="component generation was canceled due to deletion or reload of K8s context.Invalid kubeconfig.Filters passed incorrectly in config.Could not fetch API resources from Kubernetes server" severity=2 short-description="failed to register/create kubernetes components for contextID d79db675bc70f45b3fb62bd7efad56e7" suggested-remediation="If there is the log \"Starting to register ...\" for the same contextID after this error means that for some reason the context was reloaded which caused this run to abort. In that case, this error can be ignored..Make sure that the configuration filters passed are in accordance with output from /openapi/v2"
```

#### Desired State
More docs for exit code 127.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Akshit42-hue** [comment]
Can you please explain more about this issue @leecalcote

**Comment by leecalcote** [comment]
@Revolyssup  needs to finish his assignment here.
