### ISSUE TITLE
[mesheryctl] `system context switch`: Failure to switch when Meshery deployment has been removed

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5301]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
While switching a context using `platform: kubernetes` to a context using `platform: docker`, when Meshery Server and Adapters (when the Helm release) is not running in the Kubernetes platform, `mesheryctl system stop` logic results in error.

#### Desired Behavior
The `system switch` and the `system stop` should fail forward.

#### Screenshots/Logs
```
$ mesheryctl system context switch docker
Meshery deployments will be deleted from your cluster. Are you sure you want to continue [y/n]? y
Stopping Meshery...
Error: Failed to stop Meshery before switching context
See https://docs.meshery.io/reference/mesheryctl/system for usage details
: cannot stop Meshery: uninstall: Release not loaded: meshery: release: not found
```

#### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.6.0-rc-5g
- Meshery Client Version: stable-v0.6.0-rc-5g
- Platform: Docker Kubernetes - both

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gr455** [comment]
Seems to be fixed with https://github.com/meshery/meshery/pull/5429
