### ISSUE TITLE
[UI]Unhandled Runtime Error on opening kubernates nav and any button together

### ISSUE THREAD

**Issue by Harshit-Dandriyal** [meshery/meshery#5306]
#### Current Behavior

Unhandled Runtime Error on opening kubernates nav and slider button together

https://user-images.githubusercontent.com/56961488/160894639-e3942239-462c-4c3e-9701-01f97eed6077.mp4

#### Desired Behavior

No Error like this should occur while opening these navs together
#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
Optional chaining should fix this issue.

**Comment by Harshit-Dandriyal** [comment]
hmm.. Intresting , Trying to implement. will make a PR soon, Thanks :)

> Optional chaining should fix this issue.
