### ISSUE TITLE
meshery-perf pod in `ImagePullBackOff`

### ISSUE THREAD

**Issue by jtaleric** [meshery/meshery#5342]
#### Current Behavior
```
meshery       meshery-perf-76fd599f4c-zptdq                           0/1     ImagePullBackOff   0               2d23h
```

#### Expected Behavior
Pod to be up and running. 

#### Environment
Deployed with Cilium-adapater. 

The issue seems to be a missing container image tag in the dockerhub repo. 

```
jtaleric at rook-mobile in ~/dev/cilium-service-mesh-beta/kubernetes-ingress on main $ k describe pod/meshery-perf-76fd599f4c-zptdq -n meshery | grep image
  Normal  BackOff  60s (x18851 over 2d23h)  kubelet  Back-off pulling image "layer5/meshery-perf:stable-latest"

```

However, I don't see that tag -
https://hub.docker.com/r/layer5/meshery-perf/tags 

![Selection_033](https://user-images.githubusercontent.com/3965163/161563977-b44c7a57-2417-41fa-8151-703afce51102.png)

**Comment by leecalcote** [comment]
@gkarthiks, I wonder if this is an item that you'd like to have a look at...
