### ISSUE TITLE
[UI] Current Upload File should be visible

### ISSUE THREAD

**Issue by Sonichigo** [meshery/meshery#5345]
#### Current Behavior

The Current Upload File field doesn't show the current Upload File.

#### Desired Behavior

The Current File name should be visible in the respective field

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/53110238/161726047-c03b0e38-1d50-470c-aa9d-c404846ac701.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by SAEb-ai** [comment]
@leecalcote May I please be assigned to this? Thanks!!

**Comment by Nikhil-Ladha** [comment]
@SAEb-ai sure, go ahead with it.
