### ISSUE TITLE
[Docs] Write the doc for Meshery Extension point and custom component

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#5376]
#### Where to add: 
https://docs.meshery.io/extensibility/ui
From here: https://github.com/meshery/meshery/pull/5372

### What To Add: 
# Writing Custom Components for Meshery Extension Point

The Meshery extension points are the way to extend meshery and derive the more custom use-cases out of it. We already have an extension point called MeshMap. 
Meshery can provide the extension point in various ways by providing the feature of custom-components. One of the example where these custom components are used is RJSF forms in meshery-extension

### Extensibilty: RJSF Custom Component
RJSFWrapperComponent are the customizations done on RJSF forms overriding the default behaviour of meshery-ui rjsf forms.
The [Rjsf forms are wrapped](https://github.com/meshery/meshery/blob/0bc68d1cd0ba80a565afa68bce80899c22db9a2e/ui/components/MesheryMeshInterface/PatternService/RJSF.js#L66) under these component to receive the custom-props from Meshery-extension.
```jsx
<RJSFWrapperComponent {...props}>
      <RJSFForm
        isLoading={isLoading}
        schema={schema}
        data={data}
        onChange={(e) => {
          setData(e.formData)
        }}
        jsonSchema={jsonSchema}
      />
 </RJSFWrapperComponent>
```
These props are received in the RJSF forms like this: [RJSF Component](https://github.com/meshery/meshery/blob/0bc68d1cd0ba80a565afa68bce80899c22db9a2e/ui/components/MesheryMeshInterface/PatternService/RJSF.js#L91) 

#### Passing new custom prop to forms:

 1. Pass the new prop from the Meshery Extension in the RJSF Wrapper component used like this:
example:
 ```js
function RJSFWrapperComponent(props) {
  // Clone the child to pass in additional props
  const children = React.cloneElement(props.children, {
    ...(props.children?.props || {}),
    customComponent: YOUR_NEW_CUSTOM_COMPONENT_OR_PROP
  });

  return children
} 
 ```
Extract the props in the [RJSFForm Component](https://github.com/meshery/meshery/blob/0bc68d1cd0ba80a565afa68bce80899c22db9a2e/ui/components/MesheryMeshInterface/PatternService/RJSF.js#L91)

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Abhishek-kumar09** [comment]
The markdown version: 
<pre>
# Writing Custom Components for Meshery Extension Point

The Meshery extension points are the way to extend meshery and derive the more custom use-cases out of it. We already have an extension point called MeshMap. 
Meshery can provide the extension point in various ways by providing the feature of custom-components. One of the example where these custom components are used is RJSF forms in meshery-extension

### Extensibilty: RJSF Custom Component
RJSFWrapperComponent are the customizations done on RJSF forms overriding the default behaviour of meshery-ui rjsf forms.
The [Rjsf forms are wrapped](https://github.com/meshery/meshery/blob/0bc68d1cd0ba80a565afa68bce80899c22db9a2e/ui/components/MesheryMeshInterface/PatternService/RJSF.js#L66) under these component to receive the custom-props from Meshery-extension.
```jsx
<RJSFWrapperComponent {...props}>
      <RJSFForm
        isLoading={isLoading}
        schema={schema}
        data={data}
        onChange={(e) => {
          setData(e.formData)
        }}
        jsonSchema={jsonSchema}
      />
 </RJSFWrapperComponent>
```
These props are received in the RJSF forms like this: [RJSF Component](https://github.com/meshery/meshery/blob/0bc68d1cd0ba80a565afa68bce80899c22db9a2e/ui/components/MesheryMeshInterface/PatternService/RJSF.js#L91) 

#### Passing new custom prop to forms:

 1. Pass the new prop from the Meshery Extension in the RJSF Wrapper component used like this:
example:
 ```js
function RJSFWrapperComponent(props) {
  // Clone the child to pass in additional props
  const children = React.cloneElement(props.children, {
    ...(props.children?.props || {}),
    customComponent: YOUR_NEW_CUSTOM_COMPONENT_OR_PROP
  });

  return children
} 
 ```
Extract the props in the [RJSFForm Component](https://github.com/meshery/meshery/blob/0bc68d1cd0ba80a565afa68bce80899c22db9a2e/ui/components/MesheryMeshInterface/PatternService/RJSF.js#L91)







</pre>

**Comment by karnatisrinivas** [comment]
Hello @Abhishek-kumar09 , I would like to work on this issue.
