### ISSUE TITLE
[UI] Misalignment in Kubernetes Context Switcher

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5377]
#### Current Behavior
When multiple contexts are loaded, misalignment of the context chips occurs. See screenshot.

#### Desired Behavior
All chips should be of equal length irrespective of length of the name of the context  (use `text-decoration:ellipsis` to truncate) and should be in alignment.

#### Screenshots/Logs
![Screen Shot 2022-04-10 at 1 03 14 PM](https://user-images.githubusercontent.com/7570704/163253219-b3918bba-24a5-40a9-9e8b-2c8168ccef7e.png)

  
#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.6.0-rc-5l
- Meshery Client Version: stable-v0.6.0-rc-5l
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by StarTrooper08** [comment]
It's a Front-end task. Can I work on this issue?

**Comment by leecalcote** [comment]
Sounds good, @StarTrooper08. I'm trying to recall: have you been able to build and run Meshery's UI previously?

**Comment by StarTrooper08** [comment]
I have done with cloning the repository and now configuring the project.

**Comment by Harshit-Dandriyal** [comment]
@leecalcote Actually, I already made PR on this Issue.. :)

**Comment by Harshit-Dandriyal** [comment]
Sorry @StarTrooper08

**Comment by StarTrooper08** [comment]
No problem I will find another issue😄

**Comment by aman-raza** [comment]
@leecalcote Is this issue still open?

**Comment by Ayan-thecodeking** [comment]
is this issue is already open ?
