### ISSUE TITLE
[Helm] Meshery as an addition to the KubeSphere App Store

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5386]
#### Current Behavior
KubeSphere App Store is a Helm-based store for application lifecycle management on the back of [OpenPitrix](https://github.com/openpitrix/openpitrix), an open-source web-based system to package, deploy and manage different types of apps. 

Meshery is not available as an application in this App Store.

#### Desired Behavior
Meshery available as an application in this App Store.

#### Implementation
_@pengfei to advise._
Meshery Charts - https://meshery.io/charts/
KubeSphere Helm chart repo - https://github.com/kubesphere/helm-charts/tree/master/src/stable

#### Acceptance Tests
1. Meshery is available and deployable as an app in KubeSphere's catalog.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@pengfei, new versions of Meshery Charts are being published with each Meshery release. In terms of implementation, should we consider dynamically pushing to the KubeSphere App Store or do you recommend that this be a manual procedure?

**Comment by FeynmanZhou** [comment]
Hi @leecalcote and Meshery team,

There are two ways that KubeSphere users could install Meshery with ease. 
1. Import the Meshery Helm repo to KubeSphere and then install it from the KubeSphere App template (See an example)
2. Submit the Helm chart of Meshery to the KubeSphere Helm repo then it could be loaded into the KubeSphere App Store by default. 

As for Meshery, option 2 is more convenient and visible to KubeSphere users since it could be available from the built-in App Store in KubeSphere. But it requires a manual upgrade to the Helm chart since the dynamic upgrade is not supported in KubeSphere so far. The dynamic upgrade will be supported in the future release. 

So I recommend you to submit the Meshery Helm chart to [KubeSphere Helm repo](https://github.com/kubesphere/helm-charts/tree/master/src/stable) as the first step, then we could collaborate to add the installation guide to [KubeSphere documentation](https://kubesphere.io/docs/application-store/) and promote it in the community.

**Comment by kethavathsivanaik** [comment]
We can write a GitHub action job to push helm chart to KubeSphere repository after helm chart published in Artifact Hub.


Actions file to append the job:
https://github.com/meshery/meshery/blob/master/.github/workflows/helm-chart-releaser.yml

 KubeSphere Helm chart repository where to do PR:  https://github.com/kubesphere/helm-charts/tree/master/src/stable

 
**Universal Solution**

- Contribute a GitHub action in GitHub Marketplace to publish helm charts to KubeSphere Repository 

Create Custom GitHub action for KubeSphere.
https://github.com/kubesphere/kubesphere/issues/4886

**Comment by Aisuko** [comment]
As @kethavathsivanaik mentioned above. I beleive this is a good idea. But I have a consideration here, may we add Helm chart of meshery to it's Helm repo first. I mean we can finish this short-term task first then the further feature would be warm welcome.

**Comment by kethavathsivanaik** [comment]
@Aisuko I worked on the short term goal to publish the chart to KubeSphere but it's majorly written in bash. So, I converted it into github action in this weekend. I will shortly do the PR with the feature..

**Comment by Aisuko** [comment]
Thank you @kethavathsivanaik .

**Comment by FeynmanZhou** [comment]
Hi team,

I see Meshery has been added to the KubeSphere App Store. 
![image](https://user-images.githubusercontent.com/40452856/171589629-083af22f-babc-4c73-99bf-10834374f412.png)

**Comment by leecalcote** [comment]
Assuming that Kubesphere users put this Meshery entry to use, we'll set about automating the process of getting any changes to the helm charts pushed to update the KubeSphere App Store. 👍

**Comment by leecalcote** [comment]
@karnatisrinivas, your help here would be fantastic.

**Comment by karnatisrinivas** [comment]
Yep Sure @leecalcote, I'll open an issue in the Kubesphere repo regarding the same.

**Comment by karnatisrinivas** [comment]
Opened a PR in KubeSphere for the Meshery Installation guide from Kubesphere App store

https://github.com/kubesphere/website/pull/2530

**Comment by debo19** [comment]
> Opened a PR in KubeSphere for the Meshery Installation guide from Kubesphere App store
> 
> [kubesphere/website#2530](https://github.com/kubesphere/website/pull/2530)

@karnatisrinivas will you share this update on the websites call today?
