### ISSUE TITLE
[mesheryctl] Add quiet mode for mesheryctl

### ISSUE THREAD

**Issue by cpepper96** [meshery/meshery#5389]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
There is currently no quiet mode option for mesheryctl. 

#### Desired Behavior
Quiet mode option should be implemented for silent installers and programmatic use. 

#### Implementation

Quiet mode should exclude any existing interactive menus and instead offer a script-friendly alternative for making a selection. All perpetual loops should be exited eventually.

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by viveksahu26** [comment]
Hey, I would like to work on this issue.

**Comment by leecalcote** [comment]
@viveksahu26  sounds Task good. I’m labeling this with “design-needed”.
