### ISSUE TITLE
[Docs] Service Meshes update

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#5393]
#### Current State
Octarine project is shutdown.

#### Desired State
Remove Octarine Service Mesh from the table. here: https://docs.meshery.io/service-meshes

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by karnatisrinivas** [comment]
Hello @leecalcote , @Chadha93 , I would like to work on this issue and would you please elaborate the issue? Thanks
