### ISSUE TITLE
Service Meshes are associated with hard-coded namespaces

### ISSUE THREAD

**Issue by jbyers19** [meshery/meshery#5395]
#### Current Behavior
If a namespace is not deployed in one of the namespaces [here](https://github.com/meshery/meshery/blob/master/internal/graphql/model/helpers.go#L26), then it will not be displayed in the Dashboard, even if it is running correctly. 

#### Expected Behavior
Meshery should be able to detect a mesh deployed in any namespace in the cluster.

#### Screenshots/Logs
Despite NGINX Service Mesh running successfully in the `nginx-mesh` namespace, the dashboard shows that no mesh is deployed:
![Screen Shot 2022-04-15 at 3 25 58 PM](https://user-images.githubusercontent.com/50845045/163649326-c588c0f6-f9c5-42b4-83cd-77568eb8e3ae.png)

If I deploy NGINX Service Mesh in the `nginx-system` namespace it will show up in the dashboard:
![Screen Shot 2022-04-15 at 3 32 53 PM](https://user-images.githubusercontent.com/50845045/163649747-b3ff6116-00fe-44db-843e-0113fe1dfda2.png)

This issue would likely require some work across the adapters as well. At least one adapter (Istio) [is hard-coding the namespace](https://github.com/meshery/meshery-istio/blob/2cbb0225955d4de8a7cef5724eddb652a30e453a/istio/install.go#L105) to the expected namespace (`istio-system`). While this works, it's a poor user experience because regardless of the namespace they select, the mesh will always be deployed in `istio-system`.

#### Environment
- **Host OS:** Mac Linux Windows
- **Platform:** Kubernetes
- **Meshery Server Version:** edge-latest
- **Meshery Client Version:** edge-latest

**Comment by leecalcote** [comment]
Related https://github.com/meshery/meshery/issues/5357

**Comment by abhinay99190** [comment]
Can I work on it..

**Comment by jbyers19** [comment]
This is still an issue.
