### ISSUE TITLE
Meshery crash  runtime error for v0.6.0-rc.5m latest without kubernetes 

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#5405]
#### Current Behavior
Meshery on latest is crashing on server and local Logs attached
![image](https://user-images.githubusercontent.com/65453826/163809086-0ea3fc1c-87c9-45c4-9618-2347e214975d.png)

#### Expected Behavior
Error should be handled/fixed.

#### Screenshots/Logs
[crash-log.log](https://github.com/meshery/meshery/files/8505686/crash-log.log)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by asubedy** [comment]
Is this behaviour with `mesheryctl` or `make server`?

**Comment by Chadha93** [comment]
> Is this behaviour with `mesheryctl` or `make server`?

make server and make run-local

**Comment by asubedy** [comment]
Hmm thats strange I just ran the latest pull with `make server` . Did you make sure your docker is running?

**Comment by Chadha93** [comment]
> Hmm thats strange I just ran the latest pull with `make server` . Did you make sure your docker is running?

It should work without docker also as earlier... Just to up the local server at 9081

**Comment by Chadha93** [comment]
Closing this as there was an issue with my docker instance, it was stale. It's working now.
