### ISSUE TITLE
[mesheryctl] Add Cilium adapter to default meshconfig context

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5409]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Meshery Adapter for Cilium isn't included in the default context created by `mesheryctl`.

#### Desired Behavior
This adapter is ready to be included in the default Meshery deployment.

`system reset` and `system context create <name>` should be incorporate `meshery-cilium` into the default context.

#### Screenshots/Logs
```
$ mesheryctl system reset
Meshery config file will be reset to system defaults. Are you sure you want to continue [y/n]? y
Meshery resetting...

Current Context: local
Channel: stable
Version: latest
Platform: kubernetes

Fetching Meshery Server and Meshery Operator manifests for  local context...
downloading manifest files from https://github.com/meshery/meshery/tree/v0.6.0-rc.5m/install/deployment_yamls/k8s
...meshconfig has been reset to default settings.
$ mesheryctl system context view

Current Context: local

endpoint: http://localhost:9081
token: Default
token-location: auth.json
platform: kubernetes
components:
- meshery-app-mesh
- meshery-istio
- meshery-linkerd
- meshery-consul
- meshery-nsm
- meshery-kuma
- meshery-cpx
- meshery-osm
- meshery-traefik-mesh
- meshery-nginx-sm
channel: stable
version: latest

```

#### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.6.0-rc.5m
- Meshery Client Version: stable--v0.6.0-rc.5m
- Platform: Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@piyushsingariya @hexxdump

**Comment by piyushsingariya** [comment]
@leecalcote meshery-cilium has been added already to the mesh-config.

**Comment by leecalcote** [comment]
Will you double-check on its inclusion when using the `system reset` command. The cli output above is copied from a terminal session.

**Comment by leecalcote** [comment]
Oh, I see what it is: `system reset` isn't actually reseting the current context's component list. You can repro by removing any adapter (component) from your current context, executing `system reset`, then `system context view`.

**Comment by gr455** [comment]
> Oh, I see what it is: `system reset` isn't actually reseting the current context's component list. You can repro by removing any adapter (component) from your current context, executing `system reset`, then `system context view`.

This seems to be the case. Let me try and fix this
