### ISSUE TITLE
[UI] Appbar overlapping with breadcrumbs navigation

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#5422]
#### Current Behavior
![image](https://user-images.githubusercontent.com/65453826/164710884-be1bed5b-2f12-43d1-9151-1efd5a9943d0.png)

#### Desired Behavior
Appbar should not overlap with breadcrumbs navigation, it should remain under it, attached with the form.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Akshit42-hue** [comment]
Can I work on this issue @Chadha93

**Comment by Chadha93** [comment]
> Can I work on this issue @Chadha93

Sure @Akshit42-hue

**Comment by Akshit42-hue** [comment]
Hey @Chadha93, can you please share the steps to reproduce the issue

**Comment by Chadha93** [comment]
> Hey @Chadha93, can you please share the steps to reproduce the issue

@Akshit42-hue 

1. go to http://localhost:9081/configuration/patterns
2. click the designs button
3. expand the form to three or more levels and scroll, you'll get the issue. :)

**Comment by Akshit42-hue** [comment]
Thanks @Chadha93  :)

**Comment by Akshit42-hue** [comment]
Can't able to fix it, so unassigning myself

**Comment by subhradwip01** [comment]
@Chadha93 if you explain the desired behavior briefly
....i would like to look into that issue..Actually i am unable to understand the desired behavior

**Comment by Chadha93** [comment]
> @Chadha93 if you explain the desired behavior briefly ....i would like to look into that issue..Actually i am unable to understand the desired behavior

In designs, The Pattern service form has an appbar which is overlapping with the breadcrumbs navigation(a bar to toggle between pages) right above it. Can be seen when scrolled down by opening the form to deep levels. Follow steps from the previous comment https://github.com/meshery/meshery/issues/5422#issuecomment-1108105983

This is a Z-index issue.

@Akshit42-hue @subhradwip01 are you not able to find the component in the codebase? If not I can send a link to that particular component but I suggest searching the codebase first which will help you to understand the project and code better. :)

**Comment by Harshit-Dandriyal** [comment]
@Chadha93 you can assign it to me

**Comment by Harshit-Dandriyal** [comment]
or @Akshit42-hue issue will be solved if you just change the z-index value, find that particular component in the codebase, and change z-index

**Comment by Chadha93** [comment]
> @Chadha93 you can assign it to me

Sure, please do tag @subhradwip01 and @Akshit42-hue when you make a pr, it will be helpful for them.

**Comment by Harshit-Dandriyal** [comment]
> > @Chadha93 you can assign it to me
> 
> Sure, please do tag @subhradwip01 and @Akshit42-hue when you make a pr, it will be helpful for them.

Sure :smile:

**Comment by Akshit42-hue** [comment]
Hey @Chadha93, thanks for pushing us, I really want to learn the meshery code base

**Comment by Harshit-Dandriyal** [comment]
@Akshit42-hue @subhradwip01 #5468
