### ISSUE TITLE
[MeshSync] Connection check returns false positive

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5426]
#### Current Behavior
MeshSync is not running
#### Screenshots/Logs

_Not Running_
```
kubectl get pods -n meshery
NAME                                READY   STATUS    RESTARTS      AGE
meshery-operator-7f86696d85-sjlbv   2/2     Running   8 (15h ago)   2d19h
```

_Custom Resource Status_

#### Environment

- **Host OS:** Mac 
- **Platform:** Docker 
- **Meshery Server Version:** stable-v0.6.0-rc.5p
- **Meshery Client Version:** stable-v0.6.0-rc.5p

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by MUzairS15** [comment]
@leecalcote Ok to close??

**Comment by leecalcote** [comment]
Ok, yes.
