### ISSUE TITLE
[MeshSync] Connection check returns false positive

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5427]
#### Current Behavior
MeshSync is not running, but it's ad-hoc connectivity test returns the following:

<img width="369" alt="Screen Shot 2022-04-25 at 8 32 10 AM" src="https://user-images.githubusercontent.com/7570704/165111744-5fa26775-1c01-4df5-ab03-2c75b15402a1.png">

#### Screenshots/Logs

_Not Running_
```
kubectl get pods -n meshery
NAME                                READY   STATUS    RESTARTS      AGE
meshery-operator-7f86696d85-sjlbv   2/2     Running   8 (15h ago)   2d19h
```

_Custom Resource Status_
```
➜  meshery-consul git:(master) ✗ k get meshsyncs -n meshery
NAME               AGE
meshery-meshsync   2d19h
➜  meshery-consul git:(master) ✗ k describe meshsyncs -n meshery
Name:         meshery-meshsync
Namespace:    meshery
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: meshery
              meta.helm.sh/release-namespace: meshery
API Version:  meshery.layer5.io/v1alpha1
Kind:         MeshSync
Metadata:
  Creation Timestamp:  2022-04-22T19:21:05Z
  Generation:          1
  Managed Fields:
    API Version:  meshery.layer5.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
      f:spec:
        .:
        f:broker:
          .:
          f:native:
            .:
            f:name:
            f:namespace:
        f:size:
    Manager:      main
    Operation:    Update
    Time:         2022-04-22T19:21:05Z
    API Version:  meshery.layer5.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
    Manager:      manager
    Operation:    Update
    Subresource:  status
    Time:         2022-04-22T19:21:12Z
    API Version:  meshery.layer5.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:publishing-to:
    Manager:         main
    Operation:       Update
    Subresource:     status
    Time:            2022-04-24T23:21:49Z
  Resource Version:  15411
  UID:               c875bab0-8b94-4bac-8c68-9ecac248c95f
Spec:
  Broker:
    Native:
      Name:       meshery-broker
      Namespace:  meshery
  Size:           1
Status:
  Publishing - To:  10.99.84.227:4222
Events:             <none>
```

#### Environment

- **Host OS:** Mac 
- **Platform:** Docker 
- **Meshery Server Version:** stable-v0.6.0-rc.5p
- **Meshery Client Version:** stable-v0.6.0-rc.5p

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gr455** [comment]
Mind if I try this out @MUzairS15? Or we could share our findings if you are working on this.

**Comment by MUzairS15** [comment]
https://github.com/meshery/meshery/blob/78456b7c94effc7679c1ff3fdd270f304d9768d3/internal/graphql/model/operator_helper.go#L117

Fix for this should involve using k8s clientset to get meshsync pod in `meshery` namespace instead of using generated clientset for custom controller (that we are using now).

**Comment by gr455** [comment]
> https://github.com/meshery/meshery/blob/78456b7c94effc7679c1ff3fdd270f304d9768d3/internal/graphql/model/operator_helper.go#L117
> 
> Fix for this should involve using k8s clientset to get meshsync pod in `meshery` namespace instead of using generated clientset for custom controller (that we are using now).

Thanks for the nudge!

**Comment by MUzairS15** [comment]
@leecalcote Recent changes from https://github.com/meshery/meshery/pull/5480/commits/2c24abb04e585eb0c694f6bf0b8bec595838cad5
seems to fix this issue.

**Comment by leecalcote** [comment]
Good, good.

**Comment by leecalcote** [comment]
I tried to reach you a few hours ago, @MUzairS15, but couldn't raise you on Slack.

**Comment by leecalcote** [comment]
Let's close this issue, then.
