### ISSUE TITLE
[Docs] git.io deprecation

### ISSUE THREAD

**Issue by utkarsh-pro** [meshery/meshery#5430]
#### Current State
Meshery uses `git.io` shortened URLs in its docs. `git.io` service has been deprecated and the redirections are supposed to stop working from 29th April.

More info: https://github.blog/changelog/2022-04-25-git-io-deprecation/

#### Desired State
Replace `git.io` based links.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Whoa. Short notice. Very good of you to call this out, @utkarsh-pro
