### ISSUE TITLE
[Docs] Change the style of docs version selector to match with the Navbar 

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#5434]
#### Current State
Currently, the docs version selector in safari looks something like this
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/51183483/165553405-22d0491a-5ba6-4f84-8f49-15b5ade5185e.png">

#### Desired State
Remove the glassy styling and implement stylings similar to that  shown on other browser:
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/51183483/165553603-b06a0aa5-156e-4a20-ad32-a3545f32659a.png">

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by abhinay99190** [comment]
Can I work on it.

**Comment by asubedy** [comment]
Sure @abhinay99190, before assigning I wanted to confirm you have access to safari right?

**Comment by abhinay99190** [comment]
No @asubedy

**Comment by asubedy** [comment]
This is a safari specific issue without access to safari it will be difficult for you to actually see the changes you made.

**Comment by abhinay99190** [comment]
Can you tell me the process to get access in safari.

**Comment by leecalcote** [comment]
But a Mac or run macOS virtually - use a Cloud provider or borrow from a friend, @abhinay99190. In the meantime, please seek out another issue.

**Comment by karnatisrinivas** [comment]
Hello @leecalcote @asubedy , If the issue is unassigned, can i work on this?

**Comment by leecalcote** [comment]
@karnatisrinivas, yes, start by answering @asubedy's question above.

**Comment by karnatisrinivas** [comment]
Yes, I use macOS and I have access to safari browser. 

Reproduced the issue on Safari

<img width="1439" alt="Screenshot 2022-04-29 at 2 55 33 PM" src="https://user-images.githubusercontent.com/52213014/165918759-e87cc6ca-8160-40d8-9a37-9acc56c9d883.png">
,

**Comment by asubedy** [comment]
Great @karnatisrinivas, please go forward

**Comment by karnatisrinivas** [comment]
Hello @leecalcote  @asubedy , I believe there's change in the version selector in the docs. 

-> In Safari
<img width="1439" alt="Screenshot 2022-05-08 at 8 58 24 AM" src="https://user-images.githubusercontent.com/52213014/167280489-2181e02e-3512-4d7f-a8bf-699d14cea963.png">
-> In Mozilla
<img width="1440" alt="Screenshot 2022-05-08 at 8 59 37 AM" src="https://user-images.githubusercontent.com/52213014/167280518-b0fb26ec-4962-4266-b004-c5246ec75bab.png">

**Comment by asubedy** [comment]
@karnatisrinivas yes I think @leecalcote changed it to previous stylings. No worries you can work from here also. The styling should be similar in all the browser, and it should sit well with the background. You can take example of version selector of MUI docs

**Comment by asubedy** [comment]
Closing this issue since it is tracked here https://github.com/meshery/meshery/issues/4921

**Comment by abhinay99190** [comment]
Ok
