### ISSUE TITLE
[Docs]Our Doc is saying to install ruby 2.5.1 but We are using ruby 2.7.5

### ISSUE THREAD

**Issue by Harshit-Dandriyal** [meshery/meshery#5459]
#### Current State

Our Doc is saying to install ruby 2.5.1 but We are using ruby 2.7.5 It's creating an issue of Your ruby version being 2.5.1 but your Gemfile specified 2.7.5. 

![Screenshot from 2022-05-02 00-29-02](https://user-images.githubusercontent.com/56961488/166160571-25858329-99f6-4f06-a38d-852480499ddf.png)

![Screenshot from 2022-05-02 00-28-50](https://user-images.githubusercontent.com/56961488/166160573-b8af6cc7-ba9e-49d4-8da9-518c15ab5a95.png)

#### Desired State
Docs should be written with correct installation version of ruby

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Akshit42-hue** [comment]
Should I go ahead and fix it @Harshit-Dandriyal @Chadha93

**Comment by Harshit-Dandriyal** [comment]
@Akshit42-hue Go ahead :smile:

**Comment by Chadha93** [comment]
Assigning @Akshit42-hue . Thanks for opening the issue @Harshit-Dandriyal
