### ISSUE TITLE
[Docs] Add Cilium Service Mesh to table of contents (menu)

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5472]
#### Current State
The current table of contents does not have Cilium Service Mesh listed.
<img width="229" alt="Screen Shot 2022-05-03 at 5 43 38 PM" src="https://user-images.githubusercontent.com/7570704/166585058-f30ac5bf-e233-4cce-b999-4d5db1387392.png">

#### Desired State
Add an entry for Cilium Service Mesh pointing to `/service-meshes/adapters/cilium`

(https://docs.meshery.io/service-meshes/adapters/cilium)

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by rohith-cmd** [comment]
@leecalcote  I would like to take up this issue

**Comment by leecalcote** [comment]
Sounds great

**Comment by xmulligan** [comment]
@rohith-cmd let me know if you need any help 🐝

**Comment by rohith-cmd** [comment]
Hi, so I used **make** and **docker** to serve the site but ran into the following problem:

Could not locate Gemfile


```
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
             Fatal: The configuration file '/srv/jekyll/_config.yml' could not be found.
/usr/gem/gems/jekyll-4.0.0/lib/jekyll/configuration.rb:181:in `rescue in read_config_file': The Configuration file '/srv/jekyll/_config.yml' could not be found. (LoadError)
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/configuration.rb:165:in `read_config_file'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/configuration.rb:198:in `block in read_config_files'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/configuration.rb:195:in `each'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/configuration.rb:195:in `read_config_files'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll.rb:115:in `configuration'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:44:in `configuration_from_options'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:83:in `block (2 levels) in init_with_program'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /usr/gem/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
        from /usr/gem/bin/jekyll:23:in `load'
        from /usr/gem/bin/jekyll:23:in `<main>'
/usr/gem/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `initialize': No such file or directory @ rb_sysopen - /srv/jekyll/_config.yml (Errno::ENOENT)
        from /usr/gem/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
        from /usr/gem/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/configuration.rb:129:in `safe_load_file'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/configuration.rb:167:in `read_config_file'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/configuration.rb:198:in `block in read_config_files'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/configuration.rb:195:in `each'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/configuration.rb:195:in `read_config_files'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll.rb:115:in `configuration'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:44:in `configuration_from_options'
        from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:83:in `block (2 levels) in init_with_program'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /usr/gem/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
        from /usr/gem/bin/jekyll:23:in `load'
        from /usr/gem/bin/jekyll:23:in `<main>
make: *** [Makefile:16: docker] Error 1
```
I've made sure that the **Gemfile** is present too

![image](https://user-images.githubusercontent.com/55309324/166870727-ec778f01-5644-45ee-a50f-0215b1f44cd6.png)

**Comment by rohith-cmd** [comment]
The command mentioned in the docs  [https://docs.meshery.io/project/contributing/contributing-docs#using-docker](url) and the command in the makefile don't seem to match. Unless I'm missing something 😃
![image](https://user-images.githubusercontent.com/55309324/166871403-98a68ba5-7025-4111-a907-b22191765fb7.png)
![image](https://user-images.githubusercontent.com/55309324/166871471-4203625a-6d75-4cac-9161-30ec4271f8a4.png)

Shouldn't it be `make docker` instead of `make docker-docs` ?

**Comment by karnatisrinivas** [comment]
yes! `make docker` should serve the site locally.  There's already an issue opened #5433 for the changes in the make file.
