### ISSUE TITLE
[Docs] Add description of and install instructions for Docker Extension for Meshery

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5473]
#### Current State
A Docker Extension for Meshery has been created and will be publicly available at DockerCon 2022.  A description of the extension and how to install it are needed. See https://layer5.io/docker-extension-meshery and https://hub.docker.com/r/meshery/docker-extension-meshery for details.

#### Desired State
Add Docker Extension as an option on:

- https://docs.meshery.io/installation/quick-start
- https://docs.meshery.io/installation/platforms/docker-extension (a new page)

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by karnatisrinivas** [comment]
Hello @leecalcote , If this is unassigned can I work on this?

**Comment by leecalcote** [comment]
Sounds good, @karnatisrinivas

**Comment by karnatisrinivas** [comment]
Hello @leecalcote , Created a PR for the issue. Would you kindly review and let me know if any changes required.
