### ISSUE TITLE
[UI] Update the namespace width

### ISSUE THREAD

**Issue by Akshit42-hue** [meshery/meshery#5478]
#### Current Behavior

In the dashboard the namespace width is too long 

#### Desired Behavior

Namespace width need to be decrease and make it responsive

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Akshit42-hue … all finished with feedback received?
