### ISSUE TITLE
[UI] Add a modal when Reset Database button is clicked on settings page

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#5479]
#### Current Behavior

Currently when we click the `Reset Database` button we don't get any warning or some sort of modal, that confirms our choice. 

#### Desired Behavior

When the button is clicked a modal should be appearing on the UI confirming the user choice of resetting the database.
The modal should describe what the button does and  the modal should have checkboxes that signify different kind of resets that the user wants to perform
 - Reset database completely
 - Just Flush Meshsync
 
 and then two action buttons which close the modal (sort of cancel button )and confirm my choices button.

<img width="1436" alt="Screen Shot 2022-05-05 at 19 17 16" src="https://user-images.githubusercontent.com/51183483/166937280-814f0d02-d271-4039-b27e-5dd060aab99c.png">

#### Implementation

Look for modals implemented on the Meshery UI and try to reuse that.

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Harshit-Dandriyal** [comment]
I can work on this :)

**Comment by Harshit-Dandriyal** [comment]
@asubedy I am suggesting that we should have two checkboxes if one or both of them is not checked, Our Reset Database Button should be disabled, So, we will not need an extra cancel button.

**Comment by leecalcote** [comment]
@Harshit-Dandriyal will you create a wireframe for clarity? Nothing pretty, but let's get the rest of the user experience clarified.
