### ISSUE TITLE
[UI] Cloud Native Design Configurator

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5504]
#### Overview
Integrate a new user experience into Meshery: a cloud native design configurator. This project involves presentation of Kuberenetes core resources and any custom resource (CRD) as a configurable component in a React-based user interface in which users design (in great detail) and deploy their cloud native infrastructure. Interns will familiarize with concepts of content lifecycle management.

#### Implementation
ReactJS, OpenAPI, JSON Schema.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Harshit-Dandriyal** [comment]
sounds great :smile: , Excited for this one..

**Comment by Taiwrash** [comment]
> #### Overview
> Integrate a new user experience into Meshery: a cloud native design configurator. This project involves presentation of Kuberenetes core resources and any custom resource (CRD) as a configurable component in a React-based user interface in which users design (in great detail) and deploy their cloud native infrastructure. Interns will familiarize with concepts of content lifecycle management.
> 
> #### Implementation
> ReactJS, OpenAPI, JSON Schema.
> 
> #### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
> * 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
> * 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
> * 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.meshery.io) and [Community Slack](http://slack.meshery.io)

Hi @leecalcote I am very excited to participate in this, please how can I get started?

**Comment by Sukriti-sood** [comment]
> #### Overview
> Integrate a new user experience into Meshery: a cloud native design configurator. This project involves presentation of Kuberenetes core resources and any custom resource (CRD) as a configurable component in a React-based user interface in which users design (in great detail) and deploy their cloud native infrastructure. Interns will familiarize with concepts of content lifecycle management.
> 
> #### Implementation
> ReactJS, OpenAPI, JSON Schema.
> 
> #### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
> * art Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
> * desktop_computer [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
> * 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

Hey @leecalcote , Please provide access for figma file.

**Comment by Taiwrash** [comment]
Does t

> Checking in... it has been awhile since we've heard from you on this issue. Are you still working on it? Please let us know and please don't hesitate to contact a [MeshMate](https://meshery.io/community/meshmates/) or any other [community member](https://meshery.io/community/members) for assistance.
> 
> > Be sure to [join the community](http://slack.meshery.io), if you haven't yet and please leave a ⭐ [star on the project](../stargazers) 😄

Does this means, nobody is working on this? If yes, can I get paired to a mentor to kickstart something?

Thanks
