### ISSUE TITLE
[CI] Make existing pod assertions more general in adapter e2e tests

### ISSUE THREAD

**Issue by gr455** [meshery/meshery#5508]
#### Current Behavior
Currently the core workflow for end to end tests for adapters only asserts pods

#### Desired Behavior
We would want the workflow to assert for any type of resource

#### Implementation
We get rid of `expected_pods` and use `expected_resource` of type `expected_resource_type` arrays to input expected resources.

For backwards compatibilty, we will still keep the `expected_pods` array until the change is propagated across all the adapters.

Side effect: Also would need to change the docs generation workflow in each adapter

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gr455** [comment]
// cc: @Revolyssup

**Comment by leecalcote** [comment]
Excellent

**Comment by leecalcote** [comment]
A change will be needed in the Meshery Docs queries, I believe. Small, but needed.

**Comment by gr455** [comment]
> A change will be needed in the Meshery Docs queries, I believe. Small, but needed.

Yes, we'll need to change that a bit too
