### ISSUE TITLE
[Docs] Highlight current tab on scroll in table of content in navigation

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#5525]
#### Current State
In the table of navigation, on the right side, the current context is not highlighted.
![image](https://user-images.githubusercontent.com/65453826/169594802-f5bc45b9-34f8-4ebc-80c5-929a7a070e14.png)

#### Desired State
It should highlight the current tab context and change accordingly on scroll.
See the example here https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by karnatisrinivas** [comment]
Hello @Chadha93 , Can I give it a try?

**Comment by Akshit42-hue** [comment]
Go ahead @karnatisrinivas

**Comment by arya-vats** [comment]
@Chadha93 May I give it a try?

**Comment by Chadha93** [comment]
> @Chadha93 May I give it a try?

@arya-vats this issue is already assigned, comment on any other free assignment issue, and I'll assign it, Thanks for jumping in, and keep contributing. :)

**Comment by karnatisrinivas** [comment]
Hello @Chadha93 , I'm unassigning myself from this. 

@arya-vats , please go ahead.

**Comment by manikmmalhotra** [comment]
@Chadha93 can i work on this issue if it's still open
