### ISSUE TITLE
[CI] Update adapters' E2E tests to newer core workflow

### ISSUE THREAD

**Issue by gr455** [meshery/meshery#5529]
#### Current Behavior
Currently we use the [testadapters.yaml](https://github.com/meshery/meshery/blob/master/.github/workflows/testadapters.yaml) workflow as a core workflow for the adapters' end to end tests. This core workflow is limited because it only lets us check if the mentioned pods have spun up. The updated workflow, [test_adapters.yaml](https://github.com/meshery/meshery/blob/master/.github/workflows/test_adapters.yaml) lets us specify what kind of resource we are expecting. The job is to port all the adapters to this new core workflow.

A core workflow is a common workflow that is called by each individual adapters' own e2e test workflow. For example the Linkerd adaper references the core workflow [here](https://github.com/meshery/meshery-linkerd/blob/master/.github/workflows/e2etests.yaml#L44).

#### Desired Behavior
All the adapters should be ported to the new core workflow.
- [x] [meshery-istio](https://github.com/meshery/meshery-istio)
- [x] [meshery-linkerd](https://github.com/meshery/meshery-linkerd)
- [x] [meshery-consul](https://github.com/meshery/meshery-consul)
- [x] [meshery-kuma](https://github.com/meshery/meshery-kuma)
- [x] [meshery-osm](https://github.com/meshery/meshery-osm)
- [x] [meshery-traefik-mesh](https://github.com/meshery/meshery-traefik-mesh)
- [x] [meshery-nginx-sm](https://github.com/meshery/meshery-nginx-sm)
- [x] [meshery-cilium](https://github.com/meshery/meshery-cilium)

#### Implementation
Each adapter is in its own repository `meshery/<adapter-name>`. Each repository is very similar, the e2e test workflow is at `.github/workflows/e2etests.yaml`. We need to make the following changes to this file for all the adapters:

1. Change the `uses` section for each of the jobs which references `testadapters.yaml` to `test_adapters.yaml`
2. Change the `expected_pods` input field to `expected_resources`. Also change `expected_pods_namespaces` to `expected_resources_namespaces`
3. Add an input field called `expected_resources_types` between `expected_resources` and `expected_resources_namespaces` and set its value to <`pod` for the number of elements in `expected_resources` field>.
For example, if you have 
```yaml
expected_resources: linkerd-destination,linkerd-identity,linkerd-proxy-injector
``` 
(3 elements). 

Then the `expected_resources_types` should look like
```yaml
expected_resources_types: pod,pod,pod
``` 
(`pod` 3 times)
  
4. Change the occurences of `pods_status` to `resources_status` (similar to [these 3 lines](https://github.com/meshery/meshery-linkerd/blob/master/.github/workflows/e2etests.yaml#L105-L107))

5. Change the name of the resource in the above 3 lines to `pod/<name of the resource>`
So those lines should look like this
```yaml
pod/linkerd-destination: $(jq '.resources_status."pod/linkerd-destination"' data.json)
pod/linkerd-identity: $(jq '.resources_status."pod/linkerd-identity"' data.json)
pod/linkerd-proxy-injector:  $(jq '.resources_status."pod/linkerd-proxy-injector"' data.json)
```
Example PR for Istio: https://github.com/meshery/meshery-istio/pull/427
#### Acceptance Tests
Make sure all the tests (especially the e2e tests) pass in the PR

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gr455** [comment]
Wow that's a lot of text. Just read the `Implementation` part for a TL;DR :laughing:

**Comment by Chever-John** [comment]
Let me try the meshery-consul project, the booking deadline is June 5th. If it goes beyond that, other brothers in the community can continue to work on it.

**Comment by viveksahu26** [comment]
Hey @gr455 , I would love to go for `meshery-linkerd`.

**Comment by gr455** [comment]
> Hey @gr455 , I would love to go for `meshery-linkerd`.

Go ahead!

**Comment by Chadha93** [comment]
Nice explanation in the issue @gr455, I'll cover the [meshery-cilium](https://github.com/meshery/meshery-cilium).

**Comment by gr455** [comment]
> Nice explanation in the issue @gr455, I'll cover the [meshery-cilium](https://github.com/meshery/meshery-cilium).

Thank you @Chadha93!

**Comment by karnatisrinivas** [comment]
I'll cover the `meshery-nsm`

**Comment by Akshit42-hue** [comment]
I'll cover the [meshery-traefik-mesh](https://github.com/meshery/meshery-traefik-mesh)

**Comment by tapanhalani** [comment]
@gr455 I would like to take up meshery-kuma

**Comment by 4molybdenum2** [comment]
I would like to take up [meshery-app-mesh](https://github.com/meshery/meshery-app-mesh)

**Comment by gr455** [comment]
> I would like to take up [meshery-app-mesh](https://github.com/meshery/meshery-app-mesh), if nobody is working on it...

Yep sure, Thanks!

**Comment by Akshit42-hue** [comment]
Hey @gr455, Should I take [meshery-osm](https://github.com/meshery/meshery-osm)

**Comment by gr455** [comment]
> Hey @gr455, Should I take [meshery-osm](https://github.com/meshery/meshery-osm)

Sure, thanks

**Comment by tapanhalani** [comment]
@gr455 as meshery-kuma is already done (https://github.com/meshery/meshery-istio/pull/427), can I take up the last remaining one i.e. meshery-nginx-sm ?

**Comment by Revolyssup** [comment]
> @gr455 as meshery-kuma is already done ([meshery/meshery-istio#427](https://github.com/meshery/meshery-istio/pull/427)), can I take up the last remaining one i.e. meshery-nginx-sm ?

Sure, go ahead.

**Comment by gr455** [comment]
Closing because done :tada:
