### ISSUE TITLE
[Docs] Add service mesh components' schema to docs

### ISSUE THREAD

**Issue by gr455** [meshery/meshery#5534]
#### Current State
The JSON Schema for each service mesh for each version are located inside `templates/oam/workloads/<version>`. These are automatically generated by a github action and meshery uses these to validate patterns.

#### Desired State
Implement docs specifying the components and their properties for each version of each service mesh supported by meshery.
Implement a github action that updates these docs everytime a new schema is generated.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gr455** [comment]
// @Revolyssup

**Comment by KrishAryan** [comment]
@gr455  can I work on this?

**Comment by gr455** [comment]
> @gr455 can I work on this?

Sure. Have a look at the Build and Release recording from today, we discussed this a little bit (It will show up here: https://www.youtube.com/c/Mesheryio/videos)

**Comment by karnatisrinivas** [comment]
Hello @KrishAryan, Are you working on this?
