### ISSUE TITLE
[Docs] Integration Test Details: Wrong color and missing pass/fail icons

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5535]
#### Description
This page, https://docs.meshery.io/project/compatibility-matrix/meshery-traefik-mesh-past-results, needs to be updated to use the same colors defined on https://docs.meshery.io/project/compatibility-matrix and to use the same icons from https://docs.meshery.io/project/compatibility-matrix

<img width="1472" alt="Screen Shot 2022-05-24 at 10 15 50 AM" src="https://user-images.githubusercontent.com/7570704/170079637-fbd01a89-d5ac-48d5-803f-2fd82f74d88e.png">

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by karnatisrinivas** [comment]
hello @leecalcote , if this is unassigned. Can I give it a try?
