### ISSUE TITLE
[Docs] Support light vs dark mode display of CNCF logo in Meshery README

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5538]
#### Current State

This repo's readme has a CNCF logo with dark text, which has low contrast when viewed in dark mode browsers.

<img width="922" alt="Screen Shot 2022-05-25 at 10 28 50 AM" src="https://user-images.githubusercontent.com/7570704/170300179-254268b3-8593-45d5-bb47-d56bb102660c.png">

#### Desired State
Use [new feature of GitHub](https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/) to display theme appropriate CNCF logo. Find other CNCF logos here: github.com/cncf/artwork

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by subhamgcon** [comment]
Can I work on this issue @leecalcote ?

**Comment by KrishAryan** [comment]
@leecalcote I have made changes please look into it

**Comment by KrishAryan** [comment]
@leecalcote  made some changes please review it

**Comment by leecalcote** [comment]
@subhamgcon apologies - I missed your comment.
