### ISSUE TITLE
[Bot] Fix welcome bot image

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#5542]
#### Expected Behavior

It should show up as it used to be.
<img width="934" alt="Screenshot 2022-05-26 at 1 33 46 PM" src="https://user-images.githubusercontent.com/73700530/170445580-2346c92a-b65f-4cf5-9d11-fc839e08d3cc.png">

#### Screenshots/Logs

Currently it looks like:
<img width="926" alt="Screenshot 2022-05-26 at 1 26 41 PM" src="https://user-images.githubusercontent.com/73700530/170444866-c86684c2-f37e-47dd-8d42-bdb4ddfa1559.png">

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Santosh1176** [comment]
Hi, Can I work on this.

**Comment by Akshit42-hue** [comment]
Go ahead @Santosh1176

**Comment by Santosh1176** [comment]
@Akshit42-hue Thank you!
