### ISSUE TITLE
[CI] Modify core E2E workflow to accommodate multiple k8s versions

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#5547]
#### Current Behavior

Currently we only allow users to pass one k8s version and run e2e tests on that. But we need to be able to check our compatibility with latest as well as older versions of kubernetes.
#### Desired Behavior

Allow users to pass comma separated values of versions in `k8s_versions` inside the test_adapters.yaml workflow. Use those to run tests for each of the passed version
#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by 4molybdenum2** [comment]
@Revolyssup workflow inputs don't support arrays I think...Can we pass the k8s value as a matrix under strategy instead of as an input?

**Comment by Revolyssup** [comment]
> @Revolyssup workflow inputs don't support arrays I think...Can we pass the k8s value as a matrix under strategy instead of as an input?

Yeah that sounds good
