### ISSUE TITLE
[mesheryctl] User Friendly Error Message

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#5572]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

1. `mesheryctl` doesn't explicitly tells the missing arguments or gives examples of correct usage of commands.

<img width="491" alt="Screenshot 2022-06-06 at 11 23 52 PM" src="https://user-images.githubusercontent.com/73700530/172221564-8908b105-ca9c-4b86-b42b-6caf8281313f.png">

2. While using an incorrect sub command, `mesheryctl` always points to the docs for `mesheryctl system` command. But ideally it should always refer to the docs of that particular command. Like in the below case, it should be pointing to `mesh` command [docs](https://docs.meshery.io/reference/mesheryctl/mesh) and `pattern` command [docs](https://docs.meshery.io/reference/mesheryctl/pattern) but it always points to system command.

<img width="611" alt="Screenshot 2022-06-07 at 12 03 49 AM" src="https://user-images.githubusercontent.com/73700530/172225418-9ea0e498-cb8d-4d87-9518-26366a7ab774.png">

>  Or possibly should give the correct usage in the command line itself rather than pointing to a link that might distract the user

#### Desired Behavior

`mesheryctl` should give out correct error message, that should include better error message(more user friendly message) and some examples usage of a given command.

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by theBeginner86** [comment]
Take inspiration from similar ctls, like `kubectl`
1. <img width="482" alt="Screenshot 2022-06-07 at 12 08 38 AM" src="https://user-images.githubusercontent.com/73700530/172225045-24fbde02-0bd2-4b7b-96ee-dc468d2d19d1.png">


2. <img width="352" alt="Screenshot 2022-06-07 at 12 08 17 AM" src="https://user-images.githubusercontent.com/73700530/172225137-5e4d184a-9368-4eb2-b490-525e8e6bda43.png">

**Comment by Kanika637** [comment]
Hey @theBeginner86 , I would like to work on this issue, could you please guide a little on how to get started with this one.

**Comment by leecalcote** [comment]
@Kanika637, have you read the contributing guides in docs.meshery.io? Are you able to compile mesheryctl?

**Comment by Kanika637** [comment]
Yes I am reading the documentation and going to compile it on my system.

**Comment by leecalcote** [comment]
Be sure to join the Meshery development meeting in which mesheryctl and its UX are discussed. That will help you familiarize a good bit as well.

**Comment by harkiratsm** [comment]
@theBeginner86 Can I work on this issue .

**Comment by leecalcote** [comment]
@harkiratsm, good of you to ask. Have you read the contributing guides in docs.meshery.io? Are you able to compile `mesheryctl`?

**Comment by harkiratsm** [comment]
@leecalcote Yeah I have the understanding & I can take this issue .

**Comment by harkiratsm** [comment]
Still Working 😃
