### ISSUE TITLE
[Server] Use same Golang logger and log format

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5579]
#### Current Behavior
Running Meshery Server, using `make server` produces stdout logs that vary in format. 

#### Desired Behavior
The same Golang logger and log format should be used consistently.

#### Example
```
➜  meshery git:(master) ✗ make server
cd cmd; go1.17.8 mod tidy; \
	BUILD="v0.6.0-rc.5t" \
	PROVIDER_BASE_URLS="https://meshery.layer5.io" \
	PORT=9081 \
	DEBUG=true \
	ADAPTER_URLS="localhost:10000 localhost:10001 localhost:10002 localhost:10004 localhost:10005 localhost:10006 localhost:10007 localhost:10008 localhost:10009 localhost:10010 localhost:10012" \
	APP_PATH="../install/apps.json" \
	go1.17.8 run main.go;
INFO[0000] Local Provider capabilities registered
INFO[0000] Meshery Server release channel is: Not Set
INFO[0000] Meshery Database is at: /Users/lee/.meshery/config
INFO[0000] Using kubeconfig at: /Users/lee/.kube
INFO[0000] Log level: debug
INFO[2022-06-07T18:38:21-05:00] extracting Applications from /Users/lee/.meshery/content/applications  app=meshery
INFO[2022-06-07T18:38:21-05:00] seeding sample Applications                   app=meshery
INFO[2022-06-07T18:38:21-05:00] extracting Filters from /Users/lee/.meshery/content/filters/binaries  app=meshery
INFO[2022-06-07T18:38:21-05:00] seeding sample Filters                        app=meshery
INFO[2022-06-07T18:38:21-05:00] extracting Patterns from /Users/lee/.meshery/content/patterns  app=meshery
INFO[2022-06-07T18:38:21-05:00] seeding sample Patterns                       app=meshery
INFO[0001] Starting Server listening on :9081
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
There is one logger that is intialized in main routine. https://github.com/meshery/meshery/blob/4002c88ed3935addeedc316bea0646f8881b3062/cmd/main.go#L56 
This has to be used everywhere

**Comment by haanhvu** [comment]
I would like to work on this, if no one has been assigned^^

**Comment by Chadha93** [comment]
Sure @haanhvu

**Comment by haanhvu** [comment]
comment to remove stale status
