### ISSUE TITLE
[Docs] Quick Start: Need link to Installation Troubleshooting

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5598]
#### Current State
The bottom of the Quick Start (https://docs.meshery.io/installation/quick-start) page ends without links to additional Guides.

#### Desired State
The bottom of the Quick Start (https://docs.meshery.io/installation/quick-start) page could use a Resources section with link to https://docs.meshery.io/guides/troubleshooting/installation and https://docs.meshery.io/reference/error-codes

and could use a description of or pointer to `mesheryctl system check`

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by abhiyant-10** [comment]
I would like to work on this task.

**Comment by Manish-Rawat-1186** [comment]
I'm also interested

**Comment by leecalcote** [comment]
@abhiyant-10 and @Manish-Rawat-1186 thanks for raising your hands. 👍 

@abhiyant-10, let's get this one onto your plate (given that you messaged first) and be sure that @Manish-Rawat-1186 is tagged to review your pull request when it comes through.

**Comment by abhiyant-10** [comment]
Thank you very much ! 
The additional guide section should contain those links in bullet list format?
![image](https://user-images.githubusercontent.com/71189932/173179309-ffe80175-83bc-4f62-9d9f-b43992fba23f.png)

**Comment by leecalcote** [comment]
@abhiyant-10 yes, that would be good.

**Comment by Manish-Rawat-1186** [comment]
> @abhiyant-10 and @Manish-Rawat-1186 thanks for raising your hands. 👍
> 
> @abhiyant-10, let's get this one onto your plate (given that you messaged first), and be sure that @Manish-Rawat-1186 is tagged to review your pull request when it comes through.

thank you sir...

**Comment by Manish-Rawat-1186** [comment]
> Thank you very much! The additional guide section should contain those links in bullet list format? ![image](https://user-images.githubusercontent.com/71189932/173179309-ffe80175-83bc-4f62-9d9f-b43992fba23f.png)

that look nice ...

**Comment by abhiyant-10** [comment]
Should I decrease the size of "Additional guides " or is it okay . (Blank space is for video)
I am sorry but I didn't understand  what to do in  "could use a description of or pointer to mesheryctl system check" . Do I have to provide a link  to https://docs.meshery.io/reference/mesheryctl/system/check?
![image](https://user-images.githubusercontent.com/71189932/173230512-73ad6cbe-7e7c-472b-802b-5a894605b57f.png)
