### ISSUE TITLE
[UI] Cursor remains as a text pointer in Dropdown

### ISSUE THREAD

**Issue by Rohith-Raju** [meshery/meshery#5599]
#### Current Behavior
When hovered on namespace dropdown cursor remains in its "Text pointer" state

https://user-images.githubusercontent.com/55309324/173113116-faf89454-d392-4230-80cf-d3e018cc6623.mp4

#### Desired Behavior
The cursor should change to a pointer when it is hovered on Drop-down 

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks, @Rohith-Raju. Good 👁️

**Comment by Rohith-Raju** [comment]
I have overridden mui styles by adding a hover selector in index.css 

https://user-images.githubusercontent.com/55309324/174224394-e2d91430-202e-4235-874f-48cfacfa9e83.mp4
