### ISSUE TITLE
[CI] Duplicative token used in e2e workflow?

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5605]
#### Current Behavior
Please see https://github.com/meshery/meshery/runs/6850181455?check_suite_focus=true#step:5:424 as an example.

#### Logs
```
Error: Could not create specified token to config: error adding token: a token with same name already exists
[424](https://github.com/meshery/meshery/runs/6850181455?check_suite_focus=true#step:5:425)
Error: Could not create specified token to config: error adding token: a token with same name already exists
[425](https://github.com/meshery/meshery/runs/6850181455?check_suite_focus=true#step:5:426)
Error: accepts 1 arg(s), received 0
[426](https://github.com/meshery/meshery/runs/6850181455?check_suite_focus=true#step:5:427)
Error: accepts 0 arg(s), received 1
[427](https://github.com/meshery/meshery/runs/6850181455?check_suite_focus=true#step:5:428)
FAIL
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gr455** [comment]
@leecalcote that looks like a part of the tests. See [this](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/system/token_test.go#L137) and [this](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/system/token_test.go#L36)
The failures are coming from whitespace / tab discrepancy

**Comment by leecalcote** [comment]
I miss you come in earlier. If this is an intentional failure, OK. It seems that I grabbed the wrong one.
