### ISSUE TITLE
[Docs] Cilium integration test not showing the latest test

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#5607]
#### Current State
The test results for cilium service mesh is not updating to the latest test results.

<img width="896" alt="Screen Shot 2022-06-13 at 17 37 19" src="https://user-images.githubusercontent.com/51183483/173347748-499dfa37-68f6-4855-ac9e-13ca92da0433.png">

The table shows test result from `2022-05-10 12:32:04 UTC Tue` which is not the latest one which can be seen in the past results page:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/51183483/173348078-004fb2c2-54a9-4bcb-8a10-ca5bb866c89c.png">

#### Desired State

Change the logic for Cilium service mesh such that it shows the latest test results in the https://docs.meshery.io/project/compatibility-matrix page.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by karnatisrinivas** [comment]
Hello @asubedy , Can I work on this?

**Comment by asubedy** [comment]
Sure @karnatisrinivas

**Comment by karnatisrinivas** [comment]
Hello @asubedy, I've tried to analyze the issue but I haven't found any leads. 

-> Currently, we are sorting stable channels based on their " Meshery-component-version", (This approach is working except for Cilium)
-> I tried to change the Sort condition to "timestamp" from " Meshery-component-version". By this approach, the results are showing only for 3 Adapters. 
-> Cilium only has stable versions.

**Comment by asubedy** [comment]
@karnatisrinivas any updates here? were you able to solve the issue?

**Comment by Aisuko** [comment]
I reopen this issue because the PR which was related to this issue is still on draft status.

**Comment by asubedy** [comment]
This issue has been solved, Closing it.
