### ISSUE TITLE
[Docs] Logic for calculating the percentage for compatibility matrix need to be changed

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#5608]
#### Current State

Right now when calculating the percentage for individual Meshery component in the compatibility matrix in https://docs.meshery.io/project/compatibility-matrix, we use this formula: `number of passing test/total number of test`

This needs to be changed.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/51183483/173349862-8c932146-a2d6-4390-9cdc-3cb9cbed3c18.png">

#### Desired State
Change the formula to calculate the percentage in such a way.:
- Check only for the latest test of a particular Meshery-component,
- Then evaluate % on the basis of successful tests run for the latest test of that individual service mesh.

Example: These are the test run on the Istio Service mesh, so if we take this as an example the percentage would be set to 100%.
<img width="886" alt="image" src="https://user-images.githubusercontent.com/51183483/173349559-353c7368-7a6a-40f5-b5af-d9aa903cf8ca.png">

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@asubedy _cough_

**Comment by leecalcote** [comment]
@asubedy I couldn't wait any longer and updated the logic. Have a look, please.

**Comment by leecalcote** [comment]
Fixed.
