### ISSUE TITLE
[Docs] Propose a design to add compatible service mesh version on the compatibility matrix

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#5609]
#### Current State
Right now we are showing compatibility on the basis of Docker version only:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/51183483/173350628-c7706a93-451f-493d-be96-0b968eac85e0.png">

#### Desired State
Propose a design to show latest service mesh version compatible for a particular Meshery-component on the compatibility matrix.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Ahmadkashif** [comment]
Hi, I would like to work on this

**Comment by leecalcote** [comment]
Sounds great, @Ahmadkashif 👍
