### ISSUE TITLE
[UI] Multi-context settings error

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5613]
#### Current Behavior

Meshery deployments that are not connected to k8s display the error below in the Settings page.

<img width="818" alt="Screen Shot 2022-06-14 at 1 04 24 PM" src="https://user-images.githubusercontent.com/7570704/173658808-96e69dc8-16bc-4a7e-9000-859091ac6c30.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by MUzairS15** [comment]
https://github.com/meshery/meshery/pull/5611
