### ISSUE TITLE
Sortable Columns on the Integration Test Results pages

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#5618]
#### Current Behavior

[This](https://docs.meshery.io/project/compatibility-matrix/meshery-linkerd-past-results) page currently doesn't have proper sorting on columns.
#### Desired Behavior

Add proper sorting on each column.
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@asubedy done?
