### ISSUE TITLE
[REST API] Update all Application's Endpoints 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5628]
#### Current Behavior
A REST API docs update is needed to clarify undeploy behavior.

- Update application endpoints wrt to types and download.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Chadha93 perhaps, you can take this on.

**Comment by Chadha93** [comment]
> @Chadha93 perhaps, you can take this on.

Sure
