### ISSUE TITLE
[Docker Extension] Empty State needed for “Deploy a Service Mesh”

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5658]
#### Current Behavior
When no Meshery Adapters are present, the “Deploy a Service Mesh” section is empty, leaving users potentially confused.

<img width="526" alt="Screen Shot 2022-06-22 at 9 57 58 AM" src="https://user-images.githubusercontent.com/7570704/175062527-6c4cac16-0321-40c1-8126-61d1ae29f6f6.png">

#### Desired Behavior
Show an empty state message, providing information to the user.

#### Implementation
See https://github.com/meshery/meshery/tree/master/install/docker-extension

#### Mockups
Show an empty state message, like:

```
<h4>No Meshery Adapters Detected</h4>
<i>Connect one or more Meshery adapters to manage service meshes</i>
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by harkiratsm** [comment]
@leecalcote Can I work on this issue

**Comment by leecalcote** [comment]
Thanks, @harkiratsm
