### ISSUE TITLE
[Docs] Reflect the number of supported components of each version in meshery docs

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#5660]
#### Current State
We do not show the number of supported components for each adapter. These can be found in templates/oam/workloads in each adapter. 

#### Desired State
Use those versioned directories to reflect the number of supported components in docs per service mesh

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@gr455 from the REST API (or other) do we have a "count" for each set of registered capabilities?
