### ISSUE TITLE
[Docs] Releases: v0.6.0" should not be a published release.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5663]
#### Current State
"v0.6.0" should not be a published release. I believe this is an orphaned artifact of an accidental release.

#### Desired State
This docs page should be deleted.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@kanika637, would you like to try this one?

**Comment by Kanika637** [comment]
Well @leecalcote , I would love to give it a try!
