### ISSUE TITLE
[Chore] Minimizing the number of files in the root directory of Meshery

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5667]
### Discussed in https://github.com/meshery/meshery/discussions/3210

<div type='discussions-op-text'>

<sup>Originally posted by **leecalcote** June 14, 2021</sup>
Proposal to restructure the top-level folder structure of `meshery/meshery` by major architectural component, for example:
```
/docs
/install
  docker-compose.yaml (from /)
  meshery (from /)
/mesheryctl
/provider-ui
/server
  /cmd
  /handlers
  /helpers
  /internal
  /models (from /oam)
  /meshes
  /router
/ui
```
</div>

**Comment by leecalcote** [comment]
@Revolyssup

**Comment by Kanika637** [comment]
Hey @leecalcote, can you give me a little more exposure to how can I work on this one?

**Comment by EleisonC** [comment]
Hey @leecalcote I can take on this one on if it's still availble

**Comment by Chadha93** [comment]
@Kanika637 still up for this issue? If not let's get @EleisonC to take this assignment? Do join the Meshery Dev call or ask doubts on https://discuss.meshery.io/ or slack(relevant channel).

**Comment by Kanika637** [comment]
Sure @EleisonC  go ahead!

**Comment by EleisonC** [comment]
Alright thank you @Chadha93
