### ISSUE TITLE
[UI] "Deploy" icon not scaling on zoom in

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5669]
#### Current Behavior
In the Applications page, the "Deploy" checkmarks button doesn't scale properly when web browser is zoomed in.

This same behavior is likely to be found in the Filters and Designs pages. These, too, should be verified.

#### Screenshots/Logs
<img width="259" alt="Screen Shot 2022-06-23 at 12 35 51 PM" src="https://user-images.githubusercontent.com/7570704/175407921-bfb04eec-d399-442f-b847-8e19298a28df.png">

#### Environment

- Browser: Safari
- Host OS: Mac 
- Meshery Server Version: stable-v0.6.0-rc.5z

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Santosh1176** [comment]
Hey, can I work on this?

**Comment by leecalcote** [comment]
Sounds real good, @Santosh1176. Please be aware of the fact that this issue is seen on Safari (and maybe other browsers). If you don't have access to a Mac, you'll need to identify another contributor in the community to assist in verifying your fix.

**Comment by Santosh1176** [comment]
@leecalcote This looks good on chrome. I should have checked the Environment section before asking. Please unassign me for further process.
![un-deploy](https://user-images.githubusercontent.com/91916466/175561649-76456f60-07f8-49a9-99d9-31a0afeca22d.png)

**Comment by Chadha93** [comment]
https://github.com/meshery/meshery/pull/5670
