### ISSUE TITLE
[CI] Update The Tests To Avoid Use Of Display Text.

### ISSUE THREAD

**Issue by Rohith-Raju** [meshery/meshery#5675]
#### Current Behavior
Cypress tests are failing because the content was updated recently 
![image](https://user-images.githubusercontent.com/55309324/175767747-e992a10b-64bb-4c68-a139-521e0d24cd9a.png)

#### Desired Behavior
Update the test cases. 

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Pritishchugh22 good to have you here. Have you worked with Cypress before?

**Comment by Pritishchugh22** [comment]
Hi @leecalcote 
I have worked a little with Cypress but I'll go through the issue and try to fix it as soon as possible. Could you please explain me a little about this issue

**Comment by Rohith-Raju** [comment]
@Pritishchugh22 if you haven't joined the Cypress-testing channel on slack, please do.

**Comment by Pritishchugh22** [comment]
Also @leecalcote , I recently applied for mentorship program under Linux foundation. I am not quite aware of the process required for me to get selected as a mentee in the same. Could you please guide me regarding how can I contribute to it and also what is the process for getting shortlisted.

**Comment by Rohith-Raju** [comment]
@Pritishchugh22 Here's the link to slack channel [slack]( http://slack.layer5.io/). Also please make sure you fill out the [newcomer's](https://layer5.io/community/newcomers) form

**Comment by Pritishchugh22** [comment]
@Rohith-Raju Thank you so much 😄

**Comment by Pritishchugh22** [comment]
Done :)
