### ISSUE TITLE
[Bug] Can't start Meshery with mesheryctl when Meshery extesnion is installed 

### ISSUE THREAD

**Issue by Rohith-Raju** [meshery/meshery#5682]
#### Current Behavior
Meshery was running fine locally before installing the Meshery extension. After which it bugged out 
```
Error response from daemon: driver failed programming external connectivity on endpoint meshery-meshery-osm-1 (79001ff00fe7b18367e5924564a716ef4b750dd5cd6a9f2f716ad074c8bed022): Bind for 0.0.0.0:10009 failed: port is already allocated
Error: Failed to start Meshery
See https://docs.meshery.io/reference/mesheryctl/system for usage details
: failed to run meshery server
See https://docs.meshery.io/reference/mesheryctl/system for usage details
: exit status 1
```
#### Expected Behavior
Meshery should start without bugging out  
#### Screenshots/Logs
![image](https://user-images.githubusercontent.com/55309324/175802296-668118a0-5c80-460d-b1bc-8756e82396d3.png)
![image](https://user-images.githubusercontent.com/55309324/175802366-e40b8959-2cfe-4dee-9f39-5d4a056d6c91.png)

#### Environment

- **Host OS:**  Windows
- **Platform:** Docker or
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

#### To Reproduce
1. Install the Meshery docker extension
2. Start meshery with `mesheryctl  system start` make sure the platform is docker

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
This isn't a bug, one of the servers would have to stop since they both run on the same port. 

Hence the message `port already allocated`

**Comment by leecalcote** [comment]
Running two Meshery Servers in the same host will require that one of the servers listen to a port other than 9081. You can customize one of the deployments to do this, or you can shut down one of the deployments and only run one Meshery Server instance at a time.

**Comment by Rohith-Raju** [comment]
Ahh knew it !!, thanks guys
