### ISSUE TITLE
[UI]Meshery Extension logout button not alligned 

### ISSUE THREAD

**Issue by Rohith-Raju** [meshery/meshery#5683]
#### Current Behavior
Meshery Extension's logout button  is not aligned after a user is logged in 

![image](https://user-images.githubusercontent.com/55309324/175802458-aae0efdd-e8ff-4954-ab1c-d35dff3c0c97.png)

#### Desired Behavior
The logout button should be aligned  

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by StarTrooper08** [comment]
Hey @Rohith-Raju are you working on this issue!?

**Comment by Rohith-Raju** [comment]
Yes,@StarTrooper08

**Comment by StarTrooper08** [comment]
Ok👍

**Comment by Rohith-Raju** [comment]
@leecalcote @warunicorn19 
![image](https://user-images.githubusercontent.com/55309324/175874477-c77d67f5-ff33-4704-b743-73c3652e00ac.png)
