### ISSUE TITLE
[Server] Kubernetes: Cannot delete the last cluster

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#5687]
#### Current Behavior

Meshery server has a logic which checks if there are any k8s contexts available and if not then it assumes that it must be users first request and loads the kubeconfig
#### Expected Behavior

The other possible assumption is that user has voluntarily deleted the last context and there are none left. Currently that case is not considered and Meshery server loads all the contexts again. 
Some thought needs to be given as to when to load all contexts and when not to, in order to allow for deletion of last context
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by nishantwrp** [comment]
@Revolyssup, I researched a little bit on this issue. My initial thought is that there could be two ways to tackle this.

- Since our Kubernetes middleware automatically loads all the contexts again when there are none left, we need to store somewhere that are contexts were loaded already once (probably in the database).
- Or, we can just load all the contexts when the server starts once, and remove that logic from middleware altogether. (Probably in this file: https://github.com/meshery/meshery/blob/0b8f2b575cb594ab74661d53f3f1aefce84fb5ac/cmd/main.go#L190)

Thoughts?

**Comment by gr455** [comment]
> @Revolyssup, I researched a little bit on this issue. My initial thought is that there could be two ways to tackle this.
> 
> - Since our Kubernetes middleware automatically loads all the contexts again when there are none left, we need to store somewhere that are contexts were loaded already once (probably in the database).
> - Or, we can just load all the contexts when the server starts once, and remove that logic from middleware altogether. (Probably in this file: https://github.com/meshery/meshery/blob/0b8f2b575cb594ab74661d53f3f1aefce84fb5ac/cmd/main.go#L190)
> 
> Thoughts?

How about we have a Discover Clusters button which triggers discovery instead of doing it automatically?

**Comment by Revolyssup** [comment]
> * etes middleware automatic

Loading contexts is a provider specific operation and cannot be performed until a user has logged in with a provider. Therefore, we can't do it on startup.

**Comment by Revolyssup** [comment]
> > @Revolyssup, I researched a little bit on this issue. My initial thought is that there could be two ways to tackle this.
> > 
> > * Since our Kubernetes middleware automatically loads all the contexts again when there are none left, we need to store somewhere that are contexts were loaded already once (probably in the database).
> > * Or, we can just load all the contexts when the server starts once, and remove that logic from middleware altogether. (Probably in this file: https://github.com/meshery/meshery/blob/0b8f2b575cb594ab74661d53f3f1aefce84fb5ac/cmd/main.go#L190
> >   )
> > 
> > Thoughts?
> 
> How about we have a Discover Clusters button which triggers discovery instead of doing it automatically?

Hmmm. There are pros and con to it.

**Comment by nishantwrp** [comment]
> > * etes middleware automatic
> 
> @nishantwrp Loading contexts is a provider specific operation and cannot be performed until a user has logged in with a provider. Therefore, we can't do it on startup.

Oh okay, got it.

**Comment by nishantwrp** [comment]
> > @Revolyssup, I researched a little bit on this issue. My initial thought is that there could be two ways to tackle this.
> > 
> > * Since our Kubernetes middleware automatically loads all the contexts again when there are none left, we need to store somewhere that are contexts were loaded already once (probably in the database).
> > * Or, we can just load all the contexts when the server starts once, and remove that logic from middleware altogether. (Probably in this file: https://github.com/meshery/meshery/blob/0b8f2b575cb594ab74661d53f3f1aefce84fb5ac/cmd/main.go#L190
> >   )
> > 
> > Thoughts?
> 
> How about we have a Discover Clusters button which triggers discovery instead of doing it automatically?

So, even the first time the user will have to click on discover clusters?
