### ISSUE TITLE
[UI] Settings: Upload K8s Config - Swap position of two buttons

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5689]
#### Current Behavior
When adding a cluster, users are presented with this modal (screenshot) on the http://localhost:9081/settings Settings page.

<img width="640" alt="Screen Shot 2022-06-27 at 4 28 28 PM" src="https://user-images.githubusercontent.com/7570704/176038796-ae9da3c3-82c7-47ce-b7b4-a62fe5002591.png">

#### Desired Behavior
1. "Cancel" should be on the right side while "Upload" is on the left.2. 
1. Rename "Upload" to "Import"2. 
1. "Cancel" should be using the light gray background color, while "Import" uses the charcoal-ish color.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.meshery.io) and [Community Slack](http://slack.meshery.io)

**Comment by Rohith-Raju** [comment]
@leecalcote, I would love to work on this

**Comment by leecalcote** [comment]
Sounds great. Thanks, @Rohith-Raju

**Comment by Santosh1176** [comment]
@Rohith-Raju while you are working on this, also consider correcting the spelling as shown in the pic.
![D1628881-E66D-4361-8FA0-EBDFD08DC6BB](https://user-images.githubusercontent.com/91916466/176313295-b386c30f-35dd-4c0c-9ee3-c35dec780ed0.jpeg)

**Comment by leecalcote** [comment]
Good eye, @Santosh1176

**Comment by Santosh1176** [comment]
@Rohith-Raju The config file upload functionality seems to be broken. Could you check at your end.
