### ISSUE TITLE
[Applications] Capture and display source type

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5703]
#### Current Behavior
Users can import Docker Compose, K8s Manifest, or Helm Chart as a Meshery Application. The Applications UI doesn't indicate Application source type. 

#### Desired Behavior
Add column to the “Applications" table that signifies the original form of the App (Docker Compose, K8s Manifest, Helm Chart).

#### Implementation
1. Ensure that `source-type` is captured as an attribute on import (whether specified by user or programmatically discerned. 
1. Expose details in UI.

#### Acceptance Tests
1. Application table view offers distinguishment of application source type.
1. Application grid view offers distinguishment of application source type.
1. Users can filter applications on source type.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by harkiratsm** [comment]
Can I work on this issue @leecalcote

**Comment by leecalcote** [comment]
Thanks for asking, @harkiratsm. Apologies, this one has been earmarked for @theBeginner86.
