### ISSUE TITLE
Docs: Broken link for Install sample application

### ISSUE THREAD

**Issue by Santosh1176** [meshery/meshery#5704]
#### Current State
The link to the Install sample application on the [lifecycle-management section](https://docs.meshery.io/functionality/lifecycle-management#workload-lifecycle-management) of the docs is broken.

#### Desired State
The link should redirect to the appropriate page.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you, gents. 👍

**Comment by arunkarthicknm** [comment]
Can I take up this issue please? :)

**Comment by legendarykamal** [comment]
@Santosh1176 please assign this issue to me , I would like to work on this :)

**Comment by arunkarthicknm** [comment]
That issue is closed :) @legendarykamal

**Comment by leecalcote** [comment]
Thank you, gents.
