### ISSUE TITLE
[Docs] Add Docker Extension installation instructions via Extension Marketplace

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5709]
#### Current State
The [Docker Extension docs page](https://docs.meshery.io/installation/platforms/docker-extension) describes how to use `docker` cli to install the Meshery Extension.

#### Desired State
The docs should also describe how to use the Extension Marketplace inside of Docker Desktop. Screenshot(s) should be included.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by harkiratsm** [comment]
Can I work on this issue .

**Comment by leecalcote** [comment]
Sounds real good. I wasn't sure if @Rohith-Raju was going to jump in or not, but yes, please carry this forward, @harkiratsm

**Comment by Rohith-Raju** [comment]
@leecalcote i was gonna jump into it but i don't want to steal all the good first issues 😆. @harkiratsm please feel to ask me if you run into any problems 😄 .

**Comment by leecalcote** [comment]
> 

😎
