### ISSUE TITLE
[Docs] Add KubeSphere App Store as a supported platform for Meshery

### ISSUE THREAD

**Issue by debo19** [meshery/meshery#5711]
#### Current State
The [Supported Platforms docs page](https://docs.meshery.io/installation/platforms) does not have an entry for the integration of Meshery into the KubeSphere App Store. Refer #5386 

#### Desired State
Create an entry for the recent addition of Meshery into the KubeSphere App store. Follow this [PR on KubeSphere Documentation](https://github.com/kubesphere/website/pull/2530) for the installation guide.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by codrAlxx** [comment]
Hello, @leecalcote  @debo19 I would like to work on this issue.

**Comment by codrAlxx** [comment]
I have made the PR @leecalcote @debo19 . It would be nice of you if you could review it.
