### ISSUE TITLE
[UI] Add deployment modal for Grid view

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#5714]
#### Current Behavior

Add Deployment modal that is seen in Lifecycle page when a un/deploy action is performed in Grid View of Filter, Applications and Patterns.
#### Implementation

Reference: https://github.com/meshery/meshery/blob/b99f80e42b8dbbf14b8a72ff28bd2ab48d095188/ui/components/MesheryApplications.js#L736
#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Let's keep the person implementing this (@MUzairS15), so that the UX is consistent.

**Comment by legendarykamal** [comment]
@leecalcote  if you could pls add some issues to the good first issues , it would be quite helpful as there are just 4 that too assigned !

**Comment by leecalcote** [comment]
@legendarykamal be sure that you are looking across I’ll the Meshery GitHub orgs.

**Comment by MUzairS15** [comment]
https://github.com/meshery/meshery/pull/5765
