### ISSUE TITLE
[UI] Navigator Active Tab Enhancement

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#5715]
#### Current Behavior
Currently, The active tab is not highlighted/representing that it is active/opened. 
![Not-Active](https://user-images.githubusercontent.com/65453826/176761075-b2584887-575f-45d3-a196-96c55a7006be.png)

#### Desired Behavior
Let's have it highlighted to represent that the particular tab is active/opened. 
![Active](https://user-images.githubusercontent.com/65453826/176761464-8240c54f-cc06-4161-a29e-6d3e8166354f.png)

#### Implementation
Highlight it with the hover color on the active tab. 
More suggestions are welcomed for better UX. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by manikmmalhotra** [comment]
hey @leecalcote i would love to work on this issue.

**Comment by hs-07** [comment]
> This issue has been labeled with 'component/ui'. 🧰 Here are docs on [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui). 🎨 Here is the [Meshery UI Figma File](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=4%3A0) File. Lastly, here are docs on [Contributing to Meshery's End-to-End Tests Using Cypress](https://docs.meshery.io/project/contributing/contributing-cypress).
> 
> > Be sure to [join the community](http://slack.meshery.io), if you haven't yet and please leave a ⭐ [star on the project](../stargazers) 😄

hey, the mentioned figma file is currently unavailable, is there any other link of figma file?

**Comment by sumitshinde2608** [comment]
hey @Chadha93 I would like to take up this issue

**Comment by Chadha93** [comment]
@leecalcote UX views/suggestions on this issue?

**Comment by leecalcote** [comment]
There are a few mockups on this that are worth reviewing - https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=3785%3A23504

**Comment by Chadha93** [comment]
// @manikmmalhotra

**Comment by manikmmalhotra** [comment]
@Chadha93 thanks
