### ISSUE TITLE
[UI] Settings: Disallow upload of image files in kubeconfig file browser

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5738]
#### Current Behavior
In the **Settings** page, when a user uploads a doc PNG file, they received the following notification - 

#### Desired Behavior
The file browser component should disallow upload of images.

#### Screenshots/Logs
<img width="455" alt="Screen Shot 2022-07-01 at 10 55 44 AM" src="https://user-images.githubusercontent.com/7570704/176952310-d36775d2-ac58-4eee-a042-d4ffb10e5dc2.png">

#### Environment

- Browser: Chrome Safari Firefox
- Meshery Server Version: stable-v0.6.0-rc.6

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Santosh1176** [comment]
Hey @lee, can I work on this?

**Comment by Akshit42-hue** [comment]
Go ahead @Santosh1176

**Comment by Santosh1176** [comment]
> Go ahead @Santosh1176

Thank you!
