### ISSUE TITLE
[UI] Docker Extension Upload of image in browse compose app 

### ISSUE THREAD

**Issue by harkiratsm** [meshery/meshery#5747]
#### Current Behavior

In Docker Extension , when user upload any other file type like png it still show the message uploaded. 

#### Desired Behavior

Disallow the upload of images .  

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/71957674/177030193-9bf8ff36-e994-47f9-ac95-90f055339788.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by manikmmalhotra** [comment]
@harkiratsm i would like to solve this issue
