### ISSUE TITLE
[mesheryctl] Misleading error on invalid meshconfig

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#5752]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

If I have an ill-formatted config.yaml inside .meshery directory and I try to execute any mesheryctl command, it results in the error shown below which is misleading as the actual issue the invalid yaml
<img width="820" alt="Screenshot 2022-07-04 at 9 58 49 PM" src="https://user-images.githubusercontent.com/43276904/177192762-c21913b4-381d-4a27-a9b8-ecd03cc4fd3c.png">
<img width="1323" alt="Screenshot 2022-07-04 at 9 59 32 PM" src="https://user-images.githubusercontent.com/43276904/177192781-b0c0de1d-f3c9-43d7-bca2-e26b2a2e340e.png">

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Santosh1176** [comment]
Hey @Revolyssup Can I work in this?

**Comment by Pritishchugh22** [comment]
@Revolyssup Please assign this issue to me

**Comment by leecalcote** [comment]
@Santosh1176 @Pritishchugh22 thanks for jumping in. Please confirm that you've read the style guide for Meshery CLI in the Meshery Docs Contributing section and that you're able to build and run `mesheryctl` and Meshery Server.

**Comment by Santosh1176** [comment]
@leecalcote Yes, I've gone through the Docs for contributing to Meshery CLI and almost resolved this issue. I'll confirm, if this is the desired outcome and raise a PR.

**Comment by Pritishchugh22** [comment]
@leecalcote Yes I have also gone through the required documents and would like to work on this.

**Comment by manikmmalhotra** [comment]
@Revolyssup i would like to work on this issue

**Comment by Revolyssup** [comment]
@Pritishchugh22  , Sorry I missed this chat. @manikmmalhotra  grabbed this issue in today's dev call. You can find some other good first issues around. I will assign you on the next one.
