### ISSUE TITLE
[Extension] Docker: Change order of screenshots

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5755]
#### Current Behavior
This screenshot is displayed first in the details view of Meshery in the Docker Extension Marketplace:
<img width="1047" alt="Screen Shot 2022-07-04 at 2 25 19 PM" src="https://user-images.githubusercontent.com/7570704/177208803-8c2f7bd7-82f7-48c7-b0fd-51178aac6082.png">

#### Desired Behavior
Let's change the order so that the more intriguing screenshot of MeshMap is shown.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by harkiratsm** [comment]
Can I work on this @leecalcote

**Comment by leecalcote** [comment]
That’d be great, @harkiratsm 👍
