### ISSUE TITLE
[Server] Sample application deployment failure: k8s handler

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5757]
#### Current Behavior
Using Local Provider, deploying any Application fails with the following error log:

```
DEBU[0251] retrieved session for user with id: meshery
DEBU[0251] session for user with id: meshery was read in tact.
ERRO[2022-07-04T17:24:21-05:00] failed to find k8s handler                    app=meshery code=2012 probable-cause= severity=2 short-description="unable to Create Comp Config..failed to find k8s handler" suggested-remediation=
```

<img width="502" alt="Screen Shot 2022-07-04 at 5 24 17 PM" src="https://user-images.githubusercontent.com/7570704/177221855-92c0c455-a070-456c-b1dc-e7ca89a7d46c.png">

#### Environment

Meshery has active connection to Kubernetes and Meshery Operator deployed with MeshSync connected.

- **Host OS:** Mac 
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v06.0.rc-6
- **Meshery Client Version:** stable-v06.0.rc-6

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
@leecalcote  This is not specific to provider. This issue is caused by missing middleware for `/api/application/deploy`

// fyi @sudo-NithishKarthik  you missed this endpoint. No sweat, I am adding it

**Comment by sudo-NithishKarthik** [comment]
Thank you @Revolyssup 😄
