### ISSUE TITLE
[UI] No request being sent when application is saved or deleted from Applications page

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#5760]
#### Current Behavior

Currently if you edit any application and try to save it, a loading snackbar appears but no API call is made to the backend. 
The same issue persists when somone clicks on delete for that application.
#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by harkiratsm** [comment]
Can I work on this issue @Revolyssup

**Comment by Pritishchugh22** [comment]
@Revolyssup Please assign this issue to me
