### ISSUE TITLE
[Docs] Pattern Management Through Meshery CLI can't apply file directly

### ISSUE THREAD

**Issue by AugustasV** [meshery/meshery#5771]
#### Current State
Command give different output, I can't attach file locally via mesheryctl
```
mesheryctl pattern apply -f bookInfoPattern.yaml 
Error: only github urls are supported
```

#### Desired State
applied pattern

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by AugustasV** [comment]
If I use command `mesheryctl pattern apply -f ./bookInfoPattern.yaml`  it works

**Comment by afzal442** [comment]
We need to rm pattern cmd declared twice https://docs.meshery.io/functionality/pattern-management

**Comment by leecalcote** [comment]
@alphaX86 will you qualify / validate @afzal442’s last suggestion?

**Comment by alphaX86** [comment]
Checking it up....

**Comment by alphaX86** [comment]
Found it... @afzal442 is right... 2 instances are found in the above docs page... the first one can be made as syntax though
