### ISSUE TITLE
[UI] Design Configurator: Only Meshery version displaying for Kubernetes components

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5774]
#### Current Behavior
<img width="389" alt="Screen Shot 2022-07-07 at 4 55 11 PM" src="https://user-images.githubusercontent.com/7570704/177878062-7b51d45d-885a-4ce9-9693-6812292ef928.png">

#### Desired Behavior
Kuberenetes version should be displayed.

#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.6.0-rc.6b
- Platform: Local

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sumitshinde2608** [comment]
@leecalcote I would like to work on it

**Comment by leecalcote** [comment]
@Abhishek-kumar09 I left the "help wanted" label off of this PR, knowing that this isn't a simple fix. 

@sumitshinde2608 thanks for signing up for this issue. If you don't have progress or fix by the end of today, let's get this resigned to @Abhishek-kumar09 and @Revolyssup, who have this longstanding backlog item on their to-do lists, and get you another issue less deceivingly difficult.

**Comment by sumitshinde2608** [comment]
Sure @leecalcote. @Abhishek-kumar09 put a message in the slack that he would be working on it the day I was assigned the issue. Nevertheless will look for other issues

**Comment by Revolyssup** [comment]
@sumitshinde2608  There is a multi step process and will require changes across all adapters before making changes here. 
This PR is the first in line https://github.com/meshery/meshery-istio/pull/447
