### ISSUE TITLE
[UI] Different color for the "undeploy" checkmarks on the Applications page

### ISSUE THREAD

**Issue by subhradwip01** [meshery/meshery#5783]
#### Current Behavior

Currently, it has the same blue/green color as other elements in the UI.
#### Desired Behavior

 Since it is a delete action, it would be good if this was using the same red color as used by the undeploy button is using in the grid-based view on the applications page.
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by subhradwip01** [comment]
@leecalcote Is this color okay? 
![Screenshot from 2022-07-10 16-32-45](https://user-images.githubusercontent.com/88609894/178142215-59b33fd2-22d7-4e16-99d5-c6fae8167fed.png)

**Comment by leecalcote** [comment]
If it is the same color as the Undeploy button in grid view, yes. You can also confirm in Figma.

**Comment by subhradwip01** [comment]
> If it is the same color as the Undeploy button in grid view, yes. You can also confirm in Figma.

Yes it is the same color as in the grid undeploy button
