### ISSUE TITLE
Repetition in table of contents in Docs

### ISSUE THREAD

**Issue by manikmmalhotra** [meshery/meshery#5785]
#### Current Behavior

In documentation table of content  for some headings are repeating their content

#### Expected Behavior

there shouldn't be repetition in table of content which affect the scroll highlight view too.
#### Screenshots/Logs

Overview
![Screenshot from 2022-07-09 16-28-35](https://user-images.githubusercontent.com/63007399/178102814-75bd4097-05b8-44ad-9959-5fedeaf10ba0.png)

Concepts
![Screenshot from 2022-07-09 16-29-23](https://user-images.githubusercontent.com/63007399/178102852-1a34e780-612b-438f-8faa-ecd62a58021a.png)

Guides
![Screenshot from 2022-07-09 16-30-33](https://user-images.githubusercontent.com/63007399/178102875-03061727-8d4d-4f04-a7f7-e56661cb53f1.png)

Refrence
![Screenshot from 2022-07-09 16-31-06](https://user-images.githubusercontent.com/63007399/178102896-7650317c-6275-425a-825a-5996baa35afb.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

i'd be happy to solve this bug.

**Comment by warunicorn19** [comment]
Will you be working on this @manikmmalhotra ?

**Comment by manikmmalhotra** [comment]
@warunicorn19 i would like to work on this issue.

**Comment by leecalcote** [comment]
Thanks!
