### ISSUE TITLE
[mesheryctl] running version command shouldn't require config file

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#5786]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
After doing a fresh installation of `mesheryctl` and running `mesheryctl version`, I get the following output.

```
Missing Meshery config file.
Create default config now [y/n]?
```

#### Desired Behavior
Seeing the version of cli shouldn't require any config file to be present. I understand that it may need the config file to fetch the version of the meshery server but there should be a way to know the version of only the cli too which doesn't require any config file.

#### Screenshots/Logs
N/A

#### Environment

- Host OS: Mac 
- Meshery Server Version: N/A
- Meshery Client Version: `stable 0.6.0-rc.6a`
- Platform: N/A

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Good catch, @nishantwrp

**Comment by nishantwrp** [comment]
@leecalcote i'd like to work on this issue.
