### ISSUE TITLE
[Docs] Typos in architecture.md

### ISSUE THREAD

**Issue by bishal7679** [meshery/meshery#5788]
#### Current State
The spelling is `Aapters` now

![Screenshot (182)](https://user-images.githubusercontent.com/70086051/178153789-a209e84a-b8af-4667-b7ce-f7d87ad4de71.png)

#### Desired State
This should be `Adapters`

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by bishal7679** [comment]
@leecalcote Can I fix this?

**Comment by Akshit42-hue** [comment]
Go ahead @bishal7679
