### ISSUE TITLE
[UI] Session Expired: Use warning colors for modal

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5795]
#### Current Behavior
This new Expired Session modal should be a warning not informational.

![Untitled](https://user-images.githubusercontent.com/7570704/178359075-fcccc5ef-c5d6-4516-9c30-28dbf5995ca7.png)

#### Desired Behavior
Use Warning sign, not Info sign:

- [warning sign](https://github.com/meshery/meshery/files/9087585/alert.svg.zip)

 Use the following colors:

- Dark yellow: #F0A303
- Light yellow: #F0D053

#### Screenshots/Logs
<img width="440" alt="Screen Shot 2022-07-11 at 4 09 07 PM" src="https://user-images.githubusercontent.com/7570704/178358874-46f63fe0-240f-4956-ad15-184b07bd9c5b.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by kingebere** [comment]
I would love to work on this

**Comment by leecalcote** [comment]
@kingebere very good! That would be great. Will you give quick confirmation that you're able to successfully build Meshery UI (https://docs.meshery.io/project/contributing/contributing-ui)? Let's get you rolling in this item, thereafter.

**Comment by kingebere** [comment]
ok . Thank you

**Comment by legendarykamal** [comment]
Hi @leecalcote I confirm that I am able to run Meshery successfully on my system, 
If @kingebere you are facing any problem, then pls pass this to me, I am interested in working on this. Thanks 🙂

**Comment by leecalcote** [comment]
in the meantime that @kingebere works through getting `make` onto his Windows machine or starts using WSL2 or the npm commands directly, let’s allow @legendarykamal to proceed with this issue and get another issue assigned to @kingebere when he’s ready.
