### ISSUE TITLE
[UI] Design Configurator: Overlapping text in code view

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5811]
#### Current Behavior
Yaml/text overlapping in the code viewer of the Design Configurator - http://localhost:9081/configuration/patterns

#### Screenshots/Logs
<img width="690" alt="Screen Shot 2022-07-13 at 6 49 53 AM" src="https://user-images.githubusercontent.com/7570704/178732056-012c65fd-4e49-4b5c-90b2-dbb3ccb0549d.png">

#### Environment

- Browser: Safari 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by subhradwip01** [comment]
Can  I work on that issue?

**Comment by Chadha93** [comment]
> Can I work on that issue?

Sure @subhradwip01
