### ISSUE TITLE
[Docs] tools section gets hidden in many components of docs

### ISSUE THREAD

**Issue by manikmmalhotra** [meshery/meshery#5812]
#### Current State
Tools Section gets hidden behind header in many components
1. Concepts (https://docs.meshery.io/concepts)
2. Functionality (https://docs.meshery.io/functionality)
3. Guides (https://docs.meshery.io/guides)
4. Reference (https://docs.meshery.io/reference)
![Screenshot from 2022-07-13 17-59-26](https://user-images.githubusercontent.com/63007399/178734029-2c40ca35-3422-4df3-bc19-7fa4a692de89.png)

#### Desired State
Tools should be shown properly like in normal components
![Screenshot from 2022-07-13 18-01-47](https://user-images.githubusercontent.com/63007399/178734137-98da3b38-d2ac-4622-97f4-5887855ed885.png)

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

i would like to solve this issue

**Comment by legendarykamal** [comment]
HI, can i work on this @manikmmalhotra ?

**Comment by manikmmalhotra** [comment]
@leecalcote any suggestions here ??

**Comment by Chadha93** [comment]
@manikmmalhotra it works fine for me? Did you encounterd this on any specific aspect ratio or browser?

**Comment by manikmmalhotra** [comment]
@Chadha93 i'm using brave browser and it shows error at every aspect ratio, for : 
1. Concepts
2. Functionality
3. Guides
4. Reference
these content have this issue,except this all are working fine

**Comment by Chadha93** [comment]
> @Chadha93 i'm using brave browser and it shows error at every aspect ratio, for :
> 
> 1. Concepts
> 2. Functionality
> 3. Guides
> 4. Reference
>    these content have this issue,except this all are working fine

I'm also on brave. :)
![image](https://user-images.githubusercontent.com/65453826/179965730-1cab8d50-827a-462e-acad-3dd86d13af18.png)

**Comment by manikmmalhotra** [comment]
@Chadha93 the issue is on every browser 

on specific components only which i listed above you can see clicking on this link: https://docs.meshery.io/concepts

**Comment by manikmmalhotra** [comment]
@Chadha93 sure i'll update the description and thanks for the assign
