### ISSUE TITLE
[UI] Update Patterns to Designs in Delete Modal and Toaster

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#5815]
#### Current Behavior
Patterns are now updated to Designs, delete modal and snackbar is still showing patterns
![Screenshot from 2022-07-14 00-08-45](https://user-images.githubusercontent.com/65453826/178807380-3274e1f4-bf7f-4794-b321-28d5b6ff4330.png)
![Screenshot from 2022-07-14 00-08-55](https://user-images.githubusercontent.com/65453826/178807536-23b6bb5d-d08b-4291-a967-6bca55dc8cfe.png)

#### Expected Behavior
Change Patterns to Designs in both places.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
Ok so the modal should disappear right? As soon as we delete

**Comment by legendarykamal** [comment]
I would like to work on this @Chadha93 🙂

**Comment by Chadha93** [comment]
> Ok so the modal should disappear right? As soon as we delete

No, it is disappearing now also, that's not the issue. Just change the text form Patterns to Designs in Delete Modal and Toaster notification(Snackbar)

**Comment by Chadha93** [comment]
> I would like to work on this @Chadha93 slightly_smiling_face

@legendarykamal A quick check, are you able to build meshery locally? If Yes let's get you assigned.
