### ISSUE TITLE
[UI] Adding details for Applications / Filter

### ISSUE THREAD

**Issue by harkiratsm** [meshery/meshery#5819]
#### Current Behavior

Currently If we don't have any application or filter present .

![image](https://user-images.githubusercontent.com/71957674/178997310-c0768d62-4c6f-4965-bffd-d055fd95ca2e.png)

#### Desired Behavior

We should tell the user about it  ```No Application found``` / ```No Filter Found``` , and also have a ```Import``` button from where user can import the ```application``` / ```filter``` under grid view.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
@harkiratsm Thank you for opening this issue, you can refer to the empty state detail for grid view from Designs.
