### ISSUE TITLE
[UI] Designs: Actions Buttons Not Responsive

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5822]
#### Current Behavior
Action buttons (deploy, undeploy, design) escape their card in grid view on the Designs page.

#### Desired Behavior
High text label on smaller window sizes.

#### Screenshots/Logs
<img width="744" alt="Screen Shot 2022-07-14 at 10 28 30 AM" src="https://user-images.githubusercontent.com/7570704/179019622-4cf51ed1-4024-42f0-b087-da3a816bace2.png">

#### Environment

- Browser: Safari 
- Meshery Server Version: stable-v0.6.0-rc.6b

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Pritishchugh22** [comment]
Hi @leecalcote 
Please assign me this issue. It would be a good first issue for me.  
Thanks

**Comment by leecalcote** [comment]
Sounds great, @Pritishchugh22

**Comment by Pritishchugh22** [comment]
Hey @leecalcote 
I am unable to access Figma

**Comment by leecalcote** [comment]
Send your email address in the Websites Slack channel to Nikhil Ladha, Gaurav Chadha…

**Comment by a-muk** [comment]
Hello! If this issue is still available, can I work on it?

**Comment by leecalcote** [comment]
Yes, please, @a-muk

**Comment by Devansu-Yadav** [comment]
@leecalcote Can I take up this issue if it is still open?

**Comment by leecalcote** [comment]
@Devansu-Yadav, yes, still open in that neither @Pritishchugh22 or @a-muk have PR'ed it. 

I believe that @Chadha93 saw these assignments as abandoned and might have fixed just now in PR #6046. I'll let him confirm.

**Comment by Chadha93** [comment]
> @Devansu-Yadav, yes, still open in that neither @Pritishchugh22 or @a-muk have PR'ed it.
> 
> I believe that @Chadha93 saw these assignments as abandoned and might have fixed just now in PR #6046. I'll let him confirm.

Yes, this one is fixed, I actually saw this issue https://github.com/meshery/meshery/issues/5990, not this one, Oh we have duplicate issues. 
You can have a look at the video in the pr description. Fixed now.

**Comment by Devansu-Yadav** [comment]
> > @Devansu-Yadav, yes, still open in that neither @Pritishchugh22 or @a-muk have PR'ed it.
> > 
> > I believe that @Chadha93 saw these assignments as abandoned and might have fixed just now in PR #6046. I'll let him confirm.
> 
> Yes, this one is fixed, I actually saw this issue https://github.com/meshery/meshery/issues/5990, not this one, Oh we have duplicate issues. 
> You can have a look at the video in the pr description. Fixed now. 

Cool, no worries! I can take up another issue then 😄🙌

**Comment by leecalcote** [comment]
@Devansu-Yadav that would be great. Let us know if an issue doesn’t jump out at you.
