### ISSUE TITLE
[UI] Database Reset: Use dark red button color

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5825]
#### Current Behavior
The database reset action carries the high severity of data loss and should be visually represented in this way to the user.

<img width="520" alt="Screen Shot 2022-07-14 at 6 34 02 PM" src="https://user-images.githubusercontent.com/7570704/179126734-6fe413f7-4b7c-4cb9-be73-016fcb4bd739.png">

#### Implementation
1. Use the dark red theme color for the "PROCEED" button. See design language in Figma (or the color of the Undeploy button).
1. Use "RESET" as the button text, not "PROCEED".

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by bhavyastar** [comment]
I want to work on this issue, please assign this issue to me. 😀

**Comment by leecalcote** [comment]
Sounds good, @bhavyastar. If for any reason you are unable to complete this assignment within one week, please do unassign, so that another contributor may pick it up.

**Comment by bhavyastar** [comment]
Thanks @leecalcote for assigning this issue to me. 😀
