### ISSUE TITLE
[mesheryctl] System Dashboard: Prompt user when multiple contexts are available

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5827]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
When a the kubeconfig's current-context is unreachable, and multiple contexts are present in the kubeconfig, this is the behavior of `mesheryctl system dashboard`:

```
➜  meshery git:(leecalcote/ci/chore) mesheryctl system dashboard
Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

#### Desired Behavior
Ideally, `mesheryctl system dashboard` will prompt the user to identify the desired cluster to use.

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by amit-62** [comment]
Hi @leecalcote, I want to work on this issue, please assign it to me, it will be first issue for me.

**Comment by leecalcote** [comment]
Thanks for volunteering, @amit-62

**Comment by measutosh** [comment]
Hi @leecalcote , as the issue is in stale, I want to pick this up but I am completely new to code contribution, have done a lot doc contribution
so is it possible for you to assign someone who has already done code contribution, then I will be collaborating with them to understand how this works out
