### ISSUE TITLE
[UI] K8s Context Switcher: eliminate whitespace in context chip

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5828]
#### Current Behavior
Unnecessary whitespace exists between the K8s logo and the context name.

#### Screenshot
<img width="261" alt="Screen Shot 2022-07-15 at 3 07 07 PM" src="https://user-images.githubusercontent.com/7570704/179303194-618ca114-2ad7-4078-b113-e275097ba3ed.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by nishantwrp** [comment]
@leecalcote, i'd like to work on this issue.
