### ISSUE TITLE
[mesheryctl] cli doesn't handle incorrect commands correctly

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#5831]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

**Without any args**

```
➜ mesheryctl
Meshery is the service mesh management plane, providing lifecycle, performance, and configuration management of service meshes and their workloads.

Usage:
  mesheryctl [command]

Examples:

// Base command
mesheryctl

// Display help about command/subcommand
mesheryctl --help
mesheryctl system start --help

// For viewing verbose output
mesheryctl -v [or] --verbose
	

Available Commands:
  app         Service Mesh Apps Management
  completion  Generate the autocompletion script for the specified shell
  exp         Experimental commands for mesheryctl
  help        Help about any command
  mesh        Service Mesh Lifecycle Management
  pattern     Service Mesh Patterns Management
  perf        Performance Management
  system      Meshery Lifecycle Management
  version     Version of mesheryctl

Flags:
      --config string   path to config file (default "/Users/nishantwrp/.meshery/config.yaml")
  -h, --help            help for mesheryctl
  -v, --verbose         verbose output

Use "mesheryctl [command] --help" for more information about a command.
```

**Incorrect args**

```
➜ mesheryctl abc
Meshery is the service mesh management plane, providing lifecycle, performance, and configuration management of service meshes and their workloads.

Usage:
  mesheryctl [command]

Examples:

// Base command
mesheryctl

// Display help about command/subcommand
mesheryctl --help
mesheryctl system start --help

// For viewing verbose output
mesheryctl -v [or] --verbose
	

Available Commands:
  app         Service Mesh Apps Management
  completion  Generate the autocompletion script for the specified shell
  exp         Experimental commands for mesheryctl
  help        Help about any command
  mesh        Service Mesh Lifecycle Management
  pattern     Service Mesh Patterns Management
  perf        Performance Management
  system      Meshery Lifecycle Management
  version     Version of mesheryctl

Flags:
      --config string   path to config file (default "/Users/nishantwrp/.meshery/config.yaml")
  -h, --help            help for mesheryctl
  -v, --verbose         verbose output

Use "mesheryctl [command] --help" for more information about a command.
```

**Correct command**
```
➜ mesheryctl version
Missing Meshery config file.
Create default config now [y/n]? 
```

#### Desired Behavior

**Without any args**

```
➜ mesheryctl
Meshery is the service mesh management plane, providing lifecycle, performance, and configuration management of service meshes and their workloads.

Usage:
  mesheryctl [command]

Examples:

// Base command
mesheryctl

// Display help about command/subcommand
mesheryctl --help
mesheryctl system start --help

// For viewing verbose output
mesheryctl -v [or] --verbose
	

Available Commands:
  app         Service Mesh Apps Management
  completion  Generate the autocompletion script for the specified shell
  exp         Experimental commands for mesheryctl
  help        Help about any command
  mesh        Service Mesh Lifecycle Management
  pattern     Service Mesh Patterns Management
  perf        Performance Management
  system      Meshery Lifecycle Management
  version     Version of mesheryctl

Flags:
      --config string   path to config file (default "/Users/nishantwrp/.meshery/config.yaml")
  -h, --help            help for mesheryctl
  -v, --verbose         verbose output

Use "mesheryctl [command] --help" for more information about a command.
```

**Incorrect args**

```
➜ mesheryctl abc
Some error saying that the command is incorrect.
```

**Correct command**
```
➜ mesheryctl version
Missing Meshery config file.
Create default config now [y/n]? 
```

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by nishantwrp** [comment]
@leecalcote can you please assign me this issue. I researched on this a bit and found some possible ways to show the error. Broadly there are two ways to handle this.

**Let cobra handle it**
```
➜ mesheryctl systema
Error: unknown command "systema" for "mesheryctl"

Did you mean this?
	system

Run 'mesheryctl --help' for usage.
```

**Custom handling**
```
➜ mesheryctl systema
Error: invalid command: "systema"
See https://docs.meshery.io/reference/mesheryctl for usage details
```

IMO the first one would be better because it also shows some alternative commands if it's a slight misspell. The only benefit of going with the second approach is that we can give the user a custom resolution (Example - `See https://docs.meshery.io/reference/mesheryctl for usage details` in this case) but `mesheryctl --help` also seems a good resolution for the user.

I'd also like to see what do others think.

**Comment by gr455** [comment]
> @leecalcote can you please assign me this issue. I researched on this a bit and found some possible ways to show the error. Broadly there are two ways to handle this.
> 
> **Let cobra handle it**
> ```
> ➜ mesheryctl systema
> Error: unknown command "systema" for "mesheryctl"
> 
> Did you mean this?
> 	system
> 
> Run 'mesheryctl --help' for usage.
> ```
> 
> **Custom handling**
> ```
> ➜ mesheryctl systema
> Error: invalid command: "systema"
> See https://docs.meshery.io/reference/mesheryctl for usage details
> ```
> 
> IMO the first one would be better because it also shows some alternative commands if it's a slight misspell. The only benefit of going with the second approach is that we can give the user a custom resolution (Example - `See https://docs.meshery.io/reference/mesheryctl for usage details` in this case) but `mesheryctl --help` also seems a good resolution for the user.
> 
> I'd also like to see what do others think.
> 

The first one seems great!

**Comment by leecalcote** [comment]
I agree with @gr455 and acknowledge that the URL to the reference guide can still be offered when `-h` Is used.

**Comment by harkiratsm** [comment]
@leecalcote I already had an open [pr](https://github.com/meshery/meshery/pull/5661) related to user friendly error, I can add this functionality to ```mesheryctl``` command as well, only if you and @nishantwrp allow me to do so.

**Comment by nishantwrp** [comment]
Sure @harkiratsm. Go ahead, I don't mind.

**Comment by leecalcote** [comment]
Teamwork. 🙌

**Comment by harkiratsm** [comment]
Completed by #5661
