### ISSUE TITLE
[UI] Replace Confirmation Modal's Undeploy Color

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#5840]
#### Current Behavior
The confirmation modals undeploy button color is not the same as the color used in designs/applications.
![Undeploy-btn-color](https://user-images.githubusercontent.com/65453826/179613871-09dd49dd-4d3a-4008-9bc7-edfac0f409c1.png)

#### Desired Behavior
Relace the confirmation modal's undeploy button color with    `background-color: #B32700; `. You could also refer to the designs/applications grid view UI.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by manikmmalhotra** [comment]
@Chadha93 i can work on this

**Comment by legendarykamal** [comment]
hi @manikmmalhotra the issue has been resolved in my latest commit thanks

**Comment by Chadha93** [comment]
@legendarykamal Please do ask for an issue assignment before making a PR for it. Do follow open source best practices. :)

**Comment by legendarykamal** [comment]
Ok sure @Chadha93 👍
