### ISSUE TITLE
[UI] Unavailable, previously connected Kubernetes clusters causes unexpected error

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5845]
#### Current Behavior
Measure UI crashes with an unexpected error when previously previously connected communities customers are no longer available. 

**Situation:**

3 clusters connected. 3 clusters turned off. Meshery UI refreshed on System--> Environment page

#### Screenshots/Logs
<img width="1988" alt="Screen Shot 2022-07-19 at 11 50 36 AM" src="https://user-images.githubusercontent.com/7570704/179806331-f385d2a1-c17d-435a-a2f2-1b2705c4aa19.png">

#### Environment

- Browser: Chrome 
- Host OS: Mac 
- Meshery Server Version: stable-v0.6.0-rc.6b
- Platform: local build

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@MUzairS15 FYI

**Comment by subhradwip01** [comment]
Is anyone working on that issue?..If not can I?
