### ISSUE TITLE
[Server] Multi-Cluster: Context listed twice

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5849]
#### Current Behavior
Minikube running with `--driver=vm` shows up twice in Environments when the same kubeconfig is uploaded more than once. See screenshot and Meshery Database attached below.

#### Screenshots/Logs

<img width="1043" alt="Screen Shot 2022-07-19 at 5 45 41 PM" src="https://user-images.githubusercontent.com/7570704/179860900-39f135f8-6685-4dee-a471-afb913df61b5.png">

[mesherydb.zip](https://github.com/meshery/meshery/files/9145143/mesherydb.zip)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
// @Revolyssup

**Comment by gr455** [comment]
I can take this up

**Comment by leecalcote** [comment]
Thanks you, @gr455
