### ISSUE TITLE
[UI] Performance Test: Endpoint field does not accept backslashes `/`

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5851]
#### Current Behavior
Users can paste, but not type the `/` character into the. endpoint field in performance tests.

See the modal under http://localhost:9081/performance --> "Run Test" button.

#### Desired Behavior
Users should be allowed to type this character in order to aid in protocol specification for the endpoint under test.

#### Screenshots/Logs
<img width="968" alt="Screen Shot 2022-07-19 at 6 47 11 PM" src="https://user-images.githubusercontent.com/7570704/179866753-861369ab-3695-40bc-83ff-8f18c98f49dc.png">

This issue is not present in Chrome, but is present in Safari.

#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.6.0-rc.6b

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
But things will work without the slash too in safari right ? @leecalcote pls elaborate little on the need of it .

**Comment by leecalcote** [comment]
Input field validation is likely preventing entry of `/`. I already depicted the need to identify the correct protocol for the performance test.

**Comment by legendarykamal** [comment]
Yes seeing the code I also feel so. 
Mostly work in chrome, Let me download safari nd see then will get back to u.

**Comment by manikmmalhotra** [comment]
@leecalcote i can work on this one

**Comment by leecalcote** [comment]
Thanks, @legendarykamal. I think you’ll find that Safari is unavailable for download, which will make it difficult for you to take this issue without access to Safari.

**Comment by legendarykamal** [comment]
Ok @leecalcote in that case @manikmmalhotra can go ahead pls assign to him 🙂

**Comment by leecalcote** [comment]
Thanks, gents. @manikmmalhotra is this one making sense so far?

**Comment by warunicorn19** [comment]
This issue is actually happening due to the hotkeys in the MeshMap, let's close this issue down here and track it elsewhere. @legendarykamal @manikmmalhotra please feel free to look at other open issues.
