### ISSUE TITLE
[UI] Environment: Change kubeconfig import button color

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5857]
#### Description
The color of the IMPORT button on the http://localhost:9081/settings page should be the theme color #607d8b.

#### Screenshots/Logs
<img width="590" alt="Screen Shot 2022-07-20 at 5 15 21 PM" src="https://user-images.githubusercontent.com/7570704/180092409-5469d221-f651-4502-be54-a3f4e9ccee8f.png">

See https://github.com/meshery/meshery/blob/master/ui/components/MeshConfigComponent.js

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by a-muk** [comment]
Hello! Can I work on this issue?

**Comment by bhavyastar** [comment]
Hey, @leecalcote, I want to work on this issue and it has been done from my side just need 1 day to make a Pull request. Please assign this to me.

**Comment by Chadha93** [comment]
Thank you for the heads-up @bhavyastar. You can make a quick fix here since you know where those changes have been made by you.🙂

**Comment by Chadha93** [comment]
@a-muk Great you showed interest in this issue, will make sure to get you another issue.

**Comment by heysujal** [comment]
@nishantwrp Can you guide me on how to fix this issue ?
I am not able to find where the color of the IMPORT button is set

**Comment by Chadha93** [comment]
> Hey, @leecalcote, I want to work on this issue and it has been done from my side just need 1 day to make a Pull request. Please assign this to me.

@bhavyastar We are counting. :) It's day 9. Any update on this issue? @muskankhedia would you like to wrap this up?

**Comment by bhavyastar** [comment]
Sorry to update you about this, Actually the color IMPORT Button and RESET
Button contains same CSS. Changes are done from my side but it reflects on
RESET Button too.
Can we have tomorrow regarding this? Because I have an exam.

**Comment by Chadha93** [comment]
@bhavyastar Since we have reached the ETA on this issue. Let's assign this to someone else and move the ball forward. 

Feel free to take on new issues in the future.

**Comment by a-muk** [comment]
If this issue hasn't been solved yet , can I take this up?

**Comment by bhavyastar** [comment]
Hey @Chadha93, I mentioned above the issue is solved, but the CSS file is the same for IMPORT and RESET Button. So, changing CSS for import will affect the CSS for RESET. That's why I did not make PR. If you want, I can share the image with you. 
CC @leecalcote @Chadha93

**Comment by leecalcote** [comment]
@bhavyastar, yes, if you would. There might be some confusion or the issue might have been separately addressed. It'd be good to clarify. 👍

**Comment by attreyee-muk** [comment]
It's okay if @bhavyastar makes the PR. I have taken up another issue of the Meshery repository. Thank You:)

**Comment by warunicorn19** [comment]
Pushed to master
