### ISSUE TITLE
[UI] Use of make server                                                                                                                                   

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery#5861]
#### Current Behavior

Its clearly mentioned in the docs about running make server command to serve the prebuilt components.
But it always responds with ERROR 127 command not found.
#### Desired Behavior

Either the working of the command should be improved or the neccessary changes should be done in the docs.

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/95926324/180211808-a4934986-a001-49ab-b51d-407fa566d47b.png)

#### Environment

- Browser: Chrome 
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
@leecalcote if changes in the docs are needed for this part, then I will like to do them

**Comment by leecalcote** [comment]
Fill-in the **Environment** section in your description, please.

**Comment by leecalcote** [comment]
Your system is missing golang1.17.8. Please see https://discuss.meshery.io/t/getting-an-error-while-running-make-run-command-in-meshery-consul-as-a-adapter/919/2
