### ISSUE TITLE
[UI] Explicitly set UTF-8 encoding for SVG images

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5872]
#### Current Behavior
UTF8 formatting is needed for SVG image capability with specific UI libraries used in Meshery.

#### Desired Behavior
All SVGs within the `/ui` directory should be explicitly set to use `utf-8` encoding.

#### Implementation

```
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<svg>...</svg>
```

or

```
'background-image': 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg)
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by manikmmalhotra** [comment]
@leecalcote can i work on this

**Comment by leecalcote** [comment]
Thanks, @manikmmalhotra!
