### ISSUE TITLE
[UX] Multi-Cluster: Improve cluster connection showback

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5873]
#### Current Behavior
Upon uploading kubeconfig(s) in Meshery UI, Meshery Server will attempt to connect to contexts within the kubeconfig. Users are shown a snackbar upon successful addition of a cluster, but without any context-specific details.

#### Desired Behavior
Ideally, users get one snackbar per context added or ignored. Each notification should include the context name and address.

#### Acceptance Tests
1. "Upload" confirmation snackbar is changed to Informational (blue-colored) message.
1. One success (green) notification is displayed per new context added.
1. One warning (yellow) notification is displayed per context ignored (not added).
1. User sees confirmation of the number of contexts added and number of contexts ignored.

_More Context:_

> Yes, so in that case we fall back to not flattening. This is included

For users, this will be in almost all cases. We need two things:

1. Further instructions in the modal on how to prepare your kubeconfig.
1. Additional snackbar notifications containing details of the context(s) that was just added and/or details of context(s) that were skipped over.

_Originally posted by @leecalcote in https://github.com/meshery/meshery/issues/5867#issuecomment-1192817843_

<img width="402" alt="Screen Shot 2022-07-22 at 4 53 41 PM" src="https://user-images.githubusercontent.com/7570704/180573880-b7e40577-f942-4ddc-ba78-cbfd0d30efbc.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by AakashRaj20** [comment]
hi @leecalcote I would like to try this issue, can you assign me this issue

**Comment by leecalcote** [comment]
@AakashRaj20 thanks for raising your hand. Yes, let's check with @gr455, who recently started working on this and see if collaboration is feasible or not. Collaboration is always desired, just not always feasible, though, depending upon the issue at-hand. I'll let @gr455 assess.

**Comment by AakashRaj20** [comment]
> @AakashRaj20 thanks for raising your hand. Yes, let's check with @gr455, who recently started working on this and see if collaboration is feasible or not. Collaboration is always desired, just not always feasible, though, depending upon the issue at-hand. I'll let @gr455 assess.

OK no problem.

**Comment by gr455** [comment]
Ah I've made some progress on this on the backend. If you don't mind @AakashRaj20 can you help with the UI part of this?

**Comment by AakashRaj20** [comment]
> Ah I've made quite a bit progress on this on the backend. If you don't mind @AakashRaj20 can you help with the UI part of this?

Sure sure
