### ISSUE TITLE
[UI] Empty profile in the K8s context switcher

### ISSUE THREAD

**Issue by YashKamboj** [meshery/meshery#5875]
#### Current Behavior

<img width="167" alt="Screen Shot 2022-07-22 at 3 34 44 PM" src="https://user-images.githubusercontent.com/75125203/180592076-1989a4d4-194f-4e52-8eaf-5cd2ca344362.png">

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
@YashKamboj  i am interested to work on this , please assign to me :)

**Comment by Devansu-Yadav** [comment]
@YashKamboj @legendarykamal I would like to take up this issue if this hasn't been addressed yet. Could you please clarify what the desired behavior should be (as in what profile information is missing in this case)? 😅
