### ISSUE TITLE
[mesheryctl] installing mesheryctl via the script shouldn't require unzip

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#5881]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
When `mesheryctl` is installed via our bash script it requires `unzip` to be present so that the script can uncompress the released cli binary. 

https://github.com/meshery/meshery/blob/df9eb35b8d45d1b1899b29111c80eeaed423d57b/meshery#L120-L123

#### Desired Behavior
This shouldn't be the case because linux by default doesn't have support for `zip` but has for `tar.gz`. The plan is to
- Publish the release artifact in both `tar.gz` and `zip` formats.
- Update the bash script to use the `tar.gz` file if possible.

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by heysujal** [comment]
Hi @nishantwrp  i want to work on this issue , can you guide me how do I get started ?
I am very new to this project and tried to gain some familiarity but I am not able to understand terms like Mesh and so forth.

**Comment by hexxdump** [comment]
@leecalcote, meshery bash script is used only by the unix based operating systems, so if I modify the script to switch to tar.gz, it would be enough, right ? I dont need to make any windows specific differentiation in the meshery script, right?

**Comment by nishantwrp** [comment]
Hi @heysujal, this issue was already assigned. Can you instead look for unassigned issues with labels `good first issue` or `help wanted` across the repositories mentioned [here](https://meshery.io/handbook/repository-overview)?

**Comment by nishantwrp** [comment]
Fixed by #5888 and #5911
