### ISSUE TITLE
[CI] Configure Meshery for Codespaces

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5904]
#### Current Behavior
Later this year, GitHub Codespaces will be made available to the general public. In the meantime, select open source organizations may engage with Codespaces early to both benefit from the tool and offer feedback on its experience and functionality.

#### Desired Behavior
The ability to open Meshery and it's components in Codespaces via a button like this:
![image (9)](https://user-images.githubusercontent.com/7570704/181630679-892ff651-dd33-473e-af3c-5539fb5aec3b.png)

#### Implementation
The instructions to make Meshery's repos work with Codespaces looks something like this: [customize your Codespace with a development container](https://docs.github.com/en/codespaces/customizing-your-codespace) ([an example](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/.devcontainer/devcontainer.json)).

#### Acceptance Tests
A single click to get Meshery and its components up and running in Codespaces.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by cpepper96** [comment]
👀 this sounds pretty interesting. Can I take this up @leecalcote?

**Comment by Smille02a** [comment]
Are we (as GitHub members & meshery/Meshery) automatically members to this "hidden" CodeSpace?

**Comment by sivanaikk** [comment]
I already worked on a similar issue. Love to work on this.

**Comment by craiglpeters** [comment]
Great to see the interest! I have enabled Codespaces for the meshery and meshery GitHub Organizations which means that organization members will have access when working on repos in those organizations.

A few key documents when getting started:

- The video and intro are good places to start https://docs.github.com/en/codespaces
- Customizing the Codespaces https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers
- Example devcontainers https://github.com/microsoft/vscode-dev-containers
- The newly open development containers specs https://containers.dev/

**Comment by leecalcote** [comment]
@cpepper96 @sivanaikk, two brains are better than one on this. I anticipate some collaboration will help drive the effort forward and help you overcome potential hurdles. Thanks for raising your hands. 🙌

**Comment by sivanaikk** [comment]
@cpepper96 Let's pair and work on the issue. I read the documents shared before by @craiglpeters

**Comment by sivanaikk** [comment]
Meshery UI is not coming up over HTTPS from codespaces #5973

**Comment by sivanaikk** [comment]
Propose plugins and suggested settings that align with the projects’ lint-enforced coding conventions to add in codespace #6056
