### ISSUE TITLE
[mesheryctl] Failure to recognize valid meshconfig

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5905]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
```
$ mesheryctl system channel switch stable
Valid context is not available in meshconfig
Error: failed to initialize healthchecker: Valid context is not available in meshconfig
```
```
$ mesheryctl system context view
Error: current context not set
```
```
$ mesheryctl system start
Valid context is not available in meshconfig
Error: Valid context is not available in meshconfig
```
```
$ cat ~/.meshery/config.yaml
contexts:
    local:
        endpoint: http://localhost:9081
        token: Default
        platform: kubernetes
        components:
            - meshery-app-mesh
            - meshery-istio
            - meshery-linkerd
            - meshery-consul
            - meshery-nsm
            - meshery-kuma
            - meshery-osm
            - meshery-traefik-mesh
            - meshery-nginx-sm
            - meshery-cilium
        channel: edge
        version: latest
current-context: local
tokens:
    - location: auth.json
      name: Default
```

#### Environment

- Host OS: Mac 
- Meshery Server Version: stable-v0.6.0-rc.6d
- Meshery Client Version: stable-v0.6.0-rc.6d
- Platform: Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment]
Might be something coming from this PR. https://github.com/meshery/meshery/pull/5877

**Comment by alphaX86** [comment]
Something related to path referencing... I'll take this up and resolve quick today
