### ISSUE TITLE
[UI] Designs: Rearrange buttons on cards in grid view

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5912]
#### Description
In the Designs page in Meshery UI, there are two changes desired. See screenshots.

#### Mockups
First Change:
<img width="550" alt="Screen Shot 2022-07-29 at 11 21 53 AM" src="https://user-images.githubusercontent.com/7570704/181802983-d880f8c5-9a25-4d31-827e-12c33d490d6f.png">

Second Change:
<img width="543" alt="Screen Shot 2022-07-29 at 11 25 22 AM" src="https://user-images.githubusercontent.com/7570704/181803255-06a870f6-6748-40e3-8ede-a5a20c8f31a4.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by subhamgcon** [comment]
Can I work on it? @leecalcote

**Comment by leecalcote** [comment]
That’d be great, @subhamgcon. If you run into trouble or have questions: https://discuss.meshery.io.

**Comment by leecalcote** [comment]
@subhamgcon checking in... how's it coming along?

**Comment by leecalcote** [comment]
Let's get this timely item reassigned and @subhamgcon onto another item. Just signal when ready @subhamgcon.

**Comment by subhamgcon** [comment]
Hi @leecalcote, thank you for giving me a chance to solve this issue. Actually I couldn't figure it out but I got a lot of help from the meshery slack community and i would like to start off with a documentation issue if possible. Thanks again

**Comment by leecalcote** [comment]
@subhamgcon, no sweat at all. Some items are more timely than others. There's plenty more where this comes from. Great job on reaching out to the rest of the community for assistance. I encourage you to use discuss.meshery.io for both the benefit of others who come after you and so that your inquiries don't get lost in the noise.

Take your pick: https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

If you see one that's interesting, but someone else is assigned to it, then look to see how much time is transpired between when they were signed in now. Don't hesitate to comment on the issue and ask if they are actively working on it or if you can help.
