### ISSUE TITLE
[UI] Remove the hardcoding of edge in edge-latest

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#5914]
#### Current Behavior
The `edge-` is hardcoded with edge-latest in the navigator.

<img width="258" alt="Screen Shot 2022-07-28 at 10 51 03 AM" src="https://user-images.githubusercontent.com/65453826/181830710-85962f92-b928-4d9f-b13b-80a9940bb655.png">

#### Desired Behavior
Remove the hardcoded `edge-`

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
well, I checked the Navigator file but I didnt find any hardcoded thing, 
```
 if (release_channel === "edge") return `${release_channel}-latest`;
```
can you confirm @Chadha93 ?

**Comment by leecalcote** [comment]
Another spot to check: `http://localhost:9081/api/system/version`

**Comment by legendarykamal** [comment]
```
{"build":"v0.6.0-rc.6f","latest":"v0.6.0-rc.6f","outdated":false,"commitsha":"9489a9ae","release_channel":"stable"}
```
so for me its returning the stable version automatically, is there a way to run the edge version manually?

**Comment by leecalcote** [comment]
Yes - https://docs.meshery.io/reference/mesheryctl/system/channel

**Comment by legendarykamal** [comment]
thanks @leecalcote for that link , @Chadha93 please review.
