### ISSUE TITLE
[Docs] Formatting of search results includes an extra bullet

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5915]
#### Current State
Search results on https://docs.meshery.io/search/ display an extraneous bullet.

#### Screenshot
<img width="711" alt="Screen Shot 2022-07-29 at 2 31 47 PM" src="https://user-images.githubusercontent.com/7570704/181831479-34f09016-a0a3-441a-a5c0-e19b59faf253.png">

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by beingnoble03** [comment]
Hi @leecalcote, I am unable to reproduce this issue.

**Comment by leecalcote** [comment]
I might have been using Safari. I can’t recall.

**Comment by beingnoble03** [comment]
Hmm... It's in the safari.

**Comment by karnatisrinivas** [comment]
It's happening in Safari,

**Comment by manikmmalhotra** [comment]
@leecalcote should i try ??

**Comment by leecalcote** [comment]
@manikmmalhotra yes, just as soon as your other 4 open assignments are complete.

**Comment by leecalcote** [comment]
I don't get the bullet point over the search field, but do get it overlapping with the heading anchor in Chrome:

<img width="419" alt="Screen Shot 2022-08-04 at 6 15 58 AM" src="https://user-images.githubusercontent.com/7570704/182834192-02b498a9-5a41-465e-a4ae-842142cdf81f.png">

**Comment by mharshita** [comment]
I am getting the bullet point over the search field only in Safari. Bullet points are overlapping with heading anchor in all three - Chrome, firefox and safari.

**Comment by mharshita** [comment]
@leecalcote Can I work on this issue?

**Comment by mharshita** [comment]
@manikmmalhotra are you working on this issue?

**Comment by manikmmalhotra** [comment]
@mharshita you can ask @leecalcote to assign i'm not working on this currently

**Comment by nik132-eng** [comment]
if this issue is open I want to contribute

**Comment by mharshita** [comment]
Yes @nik132-eng I am not working on this currently

**Comment by nik132-eng** [comment]
@leecalcote  @mharshita  is this issue only for mac users in safari? I didn't find it in the chrome browser

![image](https://user-images.githubusercontent.com/77881638/191000124-e6b19a3a-b6b7-4f2b-86ba-56b33d7b8861.png)

**Comment by franklinekoh** [comment]
@leecalcote can take this up? I will need a bit of time to bring my self up to speed with things as this is my first time. But More than happy to jump on this ASAP. Thanks

**Comment by leecalcote** [comment]
@franklinekoh yes, this would be good. Have you been successful in building and running the Meshery Docs site?

**Comment by franklinekoh** [comment]
@leecalcote no ,not yet. I just found out about your project yesterday and I think it is really cool. I am still finding my way around things. I will DM you on slack or right here if I find any challenges with local setup. I expect to get to that point tomorrow. Thanks

**Comment by leecalcote** [comment]
Ok, sounds good. Let’s put a time limit on this assignment of a week out from today. Two suggestions:

1. If you’re not able to resolve the issue in a week, let’s free up the assignment so that another contributor might carry forward as you work toward conclusion.
2. While I’m happy to help, my DMs overflow. I will only hold you back. Also, others are not afforded the opportunity to learn or collaborate in a DM. Your best bet is to openly message in a public channel with others in the community, who can help move you forward.

thanks for picking up this issue. 👏
