### ISSUE TITLE
[UI] Meshery UI is not responsive on mobile view

### ISSUE THREAD

**Issue by Sinha1994** [meshery/meshery#5916]
#### Current Behavior
On opening Meshery UI on mobile, it's not responsive, and adding a horizontal scrollbar at the bottom

#### Desired Behavior
UI should be compatible with each device type mobile, tablet, or desktop, and adjust content according to the device width.

#### Screenshots/Logs
<img width="161" alt="image" src="https://user-images.githubusercontent.com/28135546/181879323-05992255-c0a6-4074-9a06-c3b84138fbe8.png">

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
@Sinha1994 Would you like to take this?

**Comment by legendarykamal** [comment]
@Chadha93  I would love to work on this 

I have checked this for standard dimension  480*853 (view port) and found the menu hiding away
![Screenshot from 2022-07-31 10-39-46](https://user-images.githubusercontent.com/95926324/182011212-fe4db330-5306-47f4-b7d1-04573ad8bcaf.png)

**Comment by YashKamboj** [comment]
@Sinha1994 This issue is listed in the wrong repo, open this issue in [meshery/meshery.io](https://github.com/meshery/meshery.io) repo
