### ISSUE TITLE
[UI] Overlapping of icons on search result page

### ISSUE THREAD

**Issue by Sinha1994** [meshery/meshery#5917]
#### Current Behavior
On hovering over the bullet point of the list of results shown in search results [page](https://docs.meshery.io/search/) one extra attachment icon is coming and it's overlapping with the bullet points. 

#### Desired Behavior
Either the attachment icon can be removed and just showing the underline border below the heading of the list item would look sleek, or we can add some spacing between the attachment icon and bullet points so that they don't overlap. 

#### Screenshots/Logs
<img width="845" alt="Mashery_1" src="https://user-images.githubusercontent.com/28135546/181879790-4f02758e-501e-48c3-b050-76d2ffe7226f.png">

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
@Chadha93 I think it looks good only in this case.
clicking on  it moves it at the top of the page.
![image](https://user-images.githubusercontent.com/95926324/181886514-5a8b25ba-b51c-4140-9bec-869d5d6b9010.png)

are changes needed to be made as suggested by @Sinha1994 ?

**Comment by leecalcote** [comment]
Thanks for opening up this issue, @Sinha1994. Another potential solution is to place the link icon on the right side of each search result heading.

I’m on my mobile at the moment and can’t tell what the hover behavior of headings is on the other docs pages. It would be good to be consistent with them.

**Comment by legendarykamal** [comment]
@leecalcote I can confirm that on other pages of the docs it shows at the left side of the links 
like this 
![image](https://user-images.githubusercontent.com/95926324/181906994-6a506431-87e6-4643-8dbe-72830bbe8f16.png)

Also I have noticed that the top headings in cases gets hidden behind the scroll 
![image](https://user-images.githubusercontent.com/95926324/181907661-626d7b27-956b-42bb-8ca6-b1ac4f96b9f3.png)

So yeah @Sinha1994 has got a good point.

**Comment by legendarykamal** [comment]
I would like to work on this one.

and we can discuss a bit about the consistentency on the left/right side regarding the link in one of the meets :).

**Comment by janvi01** [comment]
I would like to work on this issue if available. @leecalcote

**Comment by legendarykamal** [comment]
Yes you may, good luck 🍀 @janvi01 

I wonder if nishiverma had any update.
