### ISSUE TITLE
[UI] Deployment Modal: Search dysfunctional

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5922]
**Description**
Search doesn't seem to work with the Deployment modal. This screenshot w what is taken from the Designs page.

**Screenshots**

<img width="465" alt="Screen Shot 2022-07-28 at 2 16 56 PM" src="https://user-images.githubusercontent.com/7570704/181619826-2e820968-b6ac-4fac-b4ac-0a9b631d9979.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by harkiratsm** [comment]
I can take this up 👍

**Comment by leecalcote** [comment]
Thank you, @harkiratsm
