### ISSUE TITLE
[mesheryctl] Add a loader on `mesheryctl pattern apply`

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#5925]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

When a user applies a pattern using `mesheryctl pattern apply` , no progress or loading is shown to user and after a long time the command exits with success or failure.
#### Desired Behavior

While the command is executing, log `Applying pattern <pattern name>` followed by a loader.
#### Mockups

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by EleisonC** [comment]
Hey @Revolyssup I would like to pick this up

**Comment by karnatisrinivas** [comment]
Hello @Revolyssup , If this is in open can I work on this?

**Comment by pk-218** [comment]
Hi @Revolyssup! Can I work on this issue? 

I have identified the changes that are to be made from this [line](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/pattern/apply.go#L224). I also have a fair idea about implementing a loader. 

However, I had a doubt - How can we figure out the `pattern name` before the pattern is created? We send the `patternFile` to the server which has the name field. Are we supposed to parse this name from YAML? Else we would have to wait for response from server, unmarshal it according to `models.PatternAPIResponse` and then obtain the pattern name.

**Comment by Revolyssup** [comment]
> Hi @Revolyssup! Can I work on this issue?
> 
> I have identified the changes that are to be made from this [line](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/pattern/apply.go#L224). I also have a fair idea about implementing a loader.
> 
> However, I had a doubt - How can we figure out the `pattern name` before the pattern is created? We send the `patternFile` to the server which has the name field. Are we supposed to parse this name from YAML? Else we would have to wait for response from server, unmarshal it according to `models.PatternAPIResponse` and then obtain the pattern name.

Before sending the yaml to the server,you can take out the `Name` from yaml as it's a top level field.

**Comment by pk-218** [comment]
Got it! I will unmarshal with the following struct and get the `Name`:
```
type Pattern struct {
			Name     string   `yaml:"name"`
			Services []string `yaml:"services"`
}
```

**Comment by Revolyssup** [comment]
> 

Yes

**Comment by leecalcote** [comment]
Please get this issues assigned to one of the contributors that has volunteered unless this issue is already being addressed elsewhere.
