### ISSUE TITLE
[Docs] Adding support to ```system channel```

### ISSUE THREAD

**Issue by harkiratsm** [meshery/meshery#5929]
#### Current State
Currently the [docs](https://docs.meshery.io/reference/mesheryctl/system/channel) for the ```system channel``` command is outdated.

#### Desired State
Docs for ```system channel``` should be updated, you can take look at [system context](https://docs.meshery.io/reference/mesheryctl/system/context) docs, to get a overview of what changes are required. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
Yes I had also noticed this @harkiratsm 
May I work on this?
