### ISSUE TITLE
[UI] Overlapping text in component configuration fields

### ISSUE THREAD

**Issue by harkiratsm** [meshery/meshery#5950]
#### Description 

When we use the ```Istio Mesh```  component, there is a overlapping/unwanted texts.

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/71957674/182524277-5d1102c3-746c-4d98-be83-efe913c1f175.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks for this, @harkiratsm

**Comment by Abhishek-kumar09** [comment]
Okay, Okay, Okay. I get it now. Its not peculiar with @Revolyssup env. The tabs are somwhat in broken state now. Here is the code to check out @harkiratsm https://github.com/meshery/meshery/blob/master/ui/components/MesheryMeshInterface/PatternServiceForm.js

**Comment by a-muk** [comment]
Is this issue still open?
