### ISSUE TITLE
[UI/Eslint] Enable important eslint checks

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#5953]
#### Current Behavior

The eslint is a great complement with JS to catch the errors in front during parse time. But some important checks being on `off` state introduces bugs in the code and failures that can be otherwise rectified in advance. Such checks are jsx keys and "no-dupe-keys". 

#### Desired Behavior
```
 "react/jsx-key" : "off",
 "no-dupe-keys" : "off",
```

WARN on "react/jsx-key"
Error on "no-dupe-keys"

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
Haven't yet tried hands on eslint checks, should I try to implement it? :)

**Comment by Abhishek-kumar09** [comment]
yeah, the same thing is done here: https://github.com/meshery/meshery/pull/5947
 start with changing eslintrc.js then, run eslint by `npm run lint:fix` and later make code changes that follows the new rules.

**Comment by legendarykamal** [comment]
thanks for providing insights Yes 👍 will do it,  
pls assign me .

**Comment by Abhishek-kumar09** [comment]
This is enforcing the check in provider-ui and not meshery-ui: See link below.
https://github.com/meshery/meshery/pull/5997

We need to enable it on meshery-ui, See the eslint file here: https://github.com/meshery/meshery/blob/master/ui/.eslintrc.js#L75-L76
Which still has the no-dupe keys and jsx-keys off.

**Comment by Abhishek-kumar09** [comment]
cc @legendarykamal

**Comment by legendarykamal** [comment]
ok @Abhishek-kumar09 I will update this in the meshery-ui :+1:

**Comment by legendarykamal** [comment]
update->  got many errors so It will take a little time to fix all of them @Abhishek-kumar09 
![image](https://user-images.githubusercontent.com/95926324/187477568-53284efa-2ea9-4cf2-956e-32c0ffc8d313.png)
