### ISSUE TITLE
[UI] Add eslint github actions to check the code and impose lint errors

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#5954]
#### Current Behavior

There are no eslint github actions, to know in advance which line of code has problems. We require some checks and github actions in the area. The eslint is available in github marketplace to be used as-is.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by karnatisrinivas** [comment]
Hello @Abhishek-kumar09 , Can I work on this?

**Comment by Abhishek-kumar09** [comment]
Yeah, there should be a github action marketplace avaiable for eslint. You have to create a new github-workflow adding the support.

**Comment by Nikhil-Ladha** [comment]
@adithyaakrishna have you confirmed with @karnatisrinivas before sending the PR?

I still see him as the first assignee of the issue.

**Comment by KinzaaSheikh** [comment]
Can I work on it?

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha Apologies for the delay regarding this as I was OOO for the long weekend, yes I have confirmed with @karnatisrinivas regarding this

**Comment by segunjkf** [comment]
hello can i be assigned to this?

**Comment by leecalcote** [comment]
@adithyaakrishna @Abhishek-kumar09 Is this completed? https://github.com/meshery/meshery/actions/workflows/eslint-gh.yml

**Comment by segunjkf** [comment]
Hello please let me know if this is completed.

**Comment by segunjkf** [comment]
@leecalcote Hello, it appears that this issue has already been resolved.

**Comment by leecalcote** [comment]
Oh, I see. Thank you much for this, @segunjkf.

@Abhishek-kumar09, based on @segunjkf's feedback shall we close this (do you concur) or are their any residual items?

**Comment by leecalcote** [comment]
bump, poke, slap, pinch, smack

**Comment by mohit-marathe** [comment]
Hello @Abhishek-kumar09 , can I work on this issue?

**Comment by acald-creator** [comment]
We have some checks in place for eslint, but with the recent changes to Next.js been upgraded to `v12/v13`, given how Next.js has built-in support for `eslint`, we will need to revisit this to ensure that eslint is doing what it's supposed to do in the CI.

**Comment by acald-creator** [comment]
Actually, we can close this for now. My last comment will be purely research. We can revisit if there are issues about Eslint check
