### ISSUE TITLE
[UI] Delete modal not functional for Designs

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#5958]
#### Current Behavior

1. Delete modal is not working for designs when a pattern/design is deleted via table row. 
2. Table header typography is set to Patterns change it to Designs. 

#### Desired Behavior
Fix the bug with the Delete modal, and test it on http://localhost:3000/configuration/patterns
Table header typography is set to Patterns change it to Designs. 

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
// @legendarykamal

**Comment by legendarykamal** [comment]
Ok I will take this up @Chadha93

**Comment by legendarykamal** [comment]
@Chadha93 it is functioning take a look 

https://user-images.githubusercontent.com/95926324/183118741-04b8e7ca-9a2b-4710-b5ab-61156c46f4ef.mp4

I am on the stable-v0.6.0-rc.6f version, m i missing something?

**Comment by Chadha93** [comment]
> @Chadha93 it is functioning take a look
> 
>  Screencast-from-05-08-22-09_39_04-PM-IST.mp4 
> I am on the stable-v0.6.0-rc.6f version, m i missing something?

A delete modal should come up see this https://github.com/meshery/meshery/pull/5891
