### ISSUE TITLE
[Docs] Ensure OpenGraph image for all Meshery Docs pages

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5960]
#### Current State
Meshery Docs doesn't have an [opengraph image](https://ogp.me/) defined across each of its pages.

#### Desired State
Modifying an existing `include` and `layout`, ensure that every page defines https://github.com/meshery/meshery/blob/master/docs/assets/img/meshery.png as the image.

https://cards-dev.twitter.com/validator can be used to help verify implementation.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
hi @leecalcote I would love to work on this one.

**Comment by leecalcote** [comment]
Sounds great, @legendarykamal
