### ISSUE TITLE
[Provider UI] Vertical scrollbar should be hidden.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5966]
#### Current Behavior
Recently, the vertical scrollbar shows in the Provider UI. The body/div background seems to be no longer full bleed.

#### Desired Behavior
The off-white background should cover the entire page. The scrollbar should not be visible.

#### Screenshots/Logs
<img width="1307" alt="Screen Shot 2022-08-04 at 5 12 02 PM" src="https://user-images.githubusercontent.com/7570704/182963364-df8eea5b-d01b-48fe-b966-a7655513c15f.png">

#### Environment

- Browser: Chrome and Safari

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
Hi @leecalcote i would like to work on this

**Comment by adarsh500** [comment]
Hey, @leecalcote I'm new here @meshery, can I please take this up as my first issue?

**Comment by Chadha93** [comment]
Thank you all for engaging here, this needs to be addressed urgently. I'm taking it forward. 

Feel free to jump on other issues. Happy contributing.
