### ISSUE TITLE
[UI] Database Reset Button: Reverse coloring

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5969]
#### Current Behavior

https://user-images.githubusercontent.com/7570704/182973293-49b71fd8-fd6b-4cef-b3bf-da24e129d943.mov

#### Desired Behavior
Should be dark red when not in focus and light red on hover.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by kumarvikramshahi** [comment]
hey @leecalcote 
Is this the desired behavior ?

https://user-images.githubusercontent.com/63746254/182996200-f3598c23-3bab-4590-9ad9-c876b8389636.mp4

**Comment by Prathamesh-Shanbhag** [comment]
Of the 2 recent UI issues I would like to have any one of them assigned to me if possible @leecalcote !
Thank you.

**Comment by 03amir** [comment]
@leecalcote  Can I work on this issue?

**Comment by legendarykamal** [comment]
@Prathamesh-Shanbhag please confirm that  have you set up locally?

**Comment by bhavyastar** [comment]
Hey @leecalcote, Actually, Because there is the same CSS file for the one which is for IMPORT and that's why this hovering effect reflects here. 
I would like to solve this issue. Would you please assign this to me?

**Comment by Chadha93** [comment]
Hey All, since we have lots of contributors here to take this issue, let's use the best algorithm here. "FCFS". First come first serve.

@kumarvikramshahi You are up first here. Answer to your above question - yes that's the desired behavior.
