### ISSUE TITLE
[UI] Database Reset: Confirmation Modal - Make Reset button red

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5970]
#### Current Behavior
<img width="635" alt="Screen Shot 2022-08-04 at 6 42 50 PM" src="https://user-images.githubusercontent.com/7570704/182973539-b57c35e2-59b7-4130-aa91-fe0ac4ff070b.png">

#### Desired Behavior
The Reset button in the screenshot should be dark red (using the color from Meshery's design language).

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by kumarvikramshahi** [comment]
hey @leecalcote  If no one is working on, i would like to fix this.

**Comment by asubedy** [comment]
Hi @kumarvikramshahi, sure you can work on this, before assigning I would like to confirm you have Meshery set up locally right?

**Comment by kumarvikramshahi** [comment]
yes, perfectly.
