### ISSUE TITLE
[UI] Meshery UI not working over HTTPS from CodeSpaces 

### ISSUE THREAD

**Issue by sivanaikk** [meshery/meshery#5973]
#### Current Behavior

![meshery-issue](https://user-images.githubusercontent.com/60335740/183082575-09e217c1-63e1-419d-974b-b4a2b7383bc1.png)

#### Desired Behavior

Meshery UI has to work after the port is forwarded by GitHub Codespaces. 
#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@sivanaikk will you open a sibling issue in the form of an enhancement for Meshery to support HTTPS?
