### ISSUE TITLE
[UI] overflow of buttons in docker desktop

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery#5990]
#### Current Behavior

![image](https://user-images.githubusercontent.com/95926324/183282755-f0083e0d-631b-4f42-8bce-56a49eefeb83.png)

#### Desired Behavior

Avoid overflow of buttons 
#### Environment

- Location: Docker desktop with meshery extension
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
@leecalcote , @warunicorn19 or @Chadha93 could you tell me since this is related to the docker desktop's Meshery extension, where the code can be accessed to remove this bug?

**Comment by leecalcote** [comment]
While it's viewable in the Docker Extension, the code is still within Meshery UI. The Docker Extension UI is the single page that you see before logging into Meshery (inside of Docker Desktop).

**Comment by Chadha93** [comment]
> @leecalcote , @warunicorn19 or @Chadha93 could you tell me since this is related to the docker desktop's Meshery extension, where the code can be accessed to remove this bug?

@legendarykamal This issue doesn't seem to be specific for DDE, it can be viewed in Meshery UI locally also, use breakpoints 
![image](https://user-images.githubusercontent.com/65453826/183497591-0149b5da-2622-4ef9-acdb-ada2a09dfcae.png)

**Comment by legendarykamal** [comment]
ok @leecalcote @Chadha93 got it , thanks for the clearance.

**Comment by adarsh500** [comment]
Well, it looks like a responsiveness bug. Can I work on this @leecalcote?

**Comment by Chadha93** [comment]
https://github.com/meshery/meshery/pull/6046

**Comment by legendarykamal** [comment]
great @Chadha93 👍
