### ISSUE TITLE
[CI] Move to latest version of golangci-lint

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#5993]
Move to the latest version of golangci-lint after https://github.com/golangci/golangci-lint-action/issues/535 is fixed. https://github.com/meshery/meshery/pull/5991 rollbacks the version of golangci-lint due to the given bug.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
@nishantwrp is this completed? If so, can we safely close this issue?

**Comment by nishantwrp** [comment]
Hi @alphaX86, no it's not. We need to start using `latest` version of golangci-lint again, which will only be possible after https://github.com/golangci/golangci-lint-action/issues/535 is fixed.

**Comment by alphaX86** [comment]
Ok understood. Thanks for clearing this

**Comment by nishantwrp** [comment]
https://github.com/golangci/golangci-lint-action/issues/535 is still not fixed. We can only work on this after the issue in `golangci-lint` gets fixed.

**Comment by acald-creator** [comment]
I will be working optimizing the GitHub Actions workflows.

There are several different workflows, and one of the suggestion is to create a separate workflow specifically for `golangci-lint` so that when it comes to reviewing PRs, we can work faster on the PR specific to `ui` or anything else that is not `Go`.

**Comment by leecalcote** [comment]
Hopefully, we'll get a bird's eye view assembled in the Meshery Test Plan spreadsheet with an overview of the workflows included.

**Comment by segunjkf** [comment]
can i work on this?

**Comment by leecalcote** [comment]
@segunjkf that'd be great, yes.

**Comment by segunjkf** [comment]
@leecalcote Golangci-lint, in my opinion, should have its own link workflow. I looked around and discovered it in the build-ui-and-server.yaml workflow.

**Comment by nishantwrp** [comment]
Hi, I'm not sure if this issue can be fixed until https://github.com/golangci/golangci-lint-action/issues/535 is fixed.

**Comment by acald-creator** [comment]
I already have a branch working on the `golangci-lint` GitHub Actions workflow as well as trying out the different linting settings. I will submit a PR today.

As for the open issue, I haven't encountered this with Go 1.19, since we're not using Go 1.18

**Comment by acald-creator** [comment]
For your reference, here is my branch in progress. The only reason why I haven't submitted the PR yet because of the linting settings which will cause the workflow to instantly fail.

https://github.com/meshery/meshery/compare/master...acald-creator:meshery:enhance-golangci-lint

I am also working on a separate branch as well with just the workflow.
