### ISSUE TITLE
[mesheryctl] Bash Installer: invalid compressed package reference

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery#5994]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

1>Unable to download meshery.zip file .from https://github.com/meshery/meshery/releases/download/v0.6.0-rc.6fc/mesheryctl_0.6.0-rc.6fc_Linux_x86_64.zip 
2> The latest version releases are not being installed on the system.
#### Desired Behavior

The file says not found when visited at https://github.com/meshery/meshery/releases/download/v0.6.0-rc.6fc/mesheryctl_0.6.0-rc.6fc_Linux_x86_64.zip 

*> These need to be fixed urgently.
#### Screenshots/Logs

![Screenshot from 2022-08-07 19-34-08](https://user-images.githubusercontent.com/95926324/183301434-ca82a72d-2fd7-4b7d-9189-16593ed7cfb2.png)

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you, @legendarykamal 👍

**Comment by legendarykamal** [comment]
Wow superquick actions ⚡  thankyou @leecalcote @nishantwrp

**Comment by leecalcote** [comment]
Hats off to @nishantwrp 👨‍💻
