### ISSUE TITLE
[mesheryctl] Installation command not working

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery#6000]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

mesheryctl command still has some bugs when a new user tries to install it.
![image](https://user-images.githubusercontent.com/95926324/183486644-f6865213-0a48-41f3-93e5-b0c356519027.png)

#### Desired Behavior

Right functioning of the command is required.
#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
@leecalcote 's speed :zap:

**Comment by nishantwrp** [comment]
Weird, the latest version is `v0.6.0-rc.6fc`, wondering why it's detecting `v0.6.0` for you.

**Comment by legendarykamal** [comment]
seems I had manually set it due to earlier problem
but on updating to latest version , It worked 
![image](https://user-images.githubusercontent.com/95926324/183562292-1c22bf78-d548-422d-b5ed-051658bc35a6.png)

Maybe we could have a warning sign when user tries for v0.6.0 ?

**Comment by legendarykamal** [comment]
Also , a new error surfaced 
Though no containers are running 
![image](https://user-images.githubusercontent.com/95926324/183563502-13bc3309-4dbe-42f3-bc00-b5a83ca4832c.png)
still it gives error 
![image](https://user-images.githubusercontent.com/95926324/183563678-59019e55-401f-4e3f-bd85-8681dd347a39.png)

**Comment by nishantwrp** [comment]
The installation script fails when user tries an incorrect version. What additional warnings can we show?

**Comment by legendarykamal** [comment]
Yes a mention of it with asking to upgrade to latest version should work 💪 fine , 
right @leecalcote ?

**Comment by nishantwrp** [comment]
As far as I understand, `MEHSERY_VERSION` is to be used as a fallback when the script itself is unable to find out the latest version.

**Comment by legendarykamal** [comment]
@nishantwrp ok then, looks good we can close this 🔨 now :)
