### ISSUE TITLE
[Docs] fix links to meshery adapters

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6003]
#### Current State
All the links present [here](https://docs.meshery.io/project/compatibility-matrix) to various meshery adapters point to `meshery-istio`. 

#### Desired State
They should point to their own respective github link. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by subhamgcon** [comment]
Hey, Can i work on this issue?

**Comment by nishantwrp** [comment]
Sure, thank you @subhamgcon.

**Comment by subhamgcon** [comment]
@nishantwrp Can you please explain me the issue?

**Comment by nishantwrp** [comment]
Hi @subhamgcon,

The compatibility matrix in that page has links to various adapters as below.

<img width="824" alt="Screenshot 2022-08-09 at 10 52 16 PM" src="https://user-images.githubusercontent.com/36989112/183717844-e2c6dbe1-4b69-46aa-b973-7140786305e5.png">

The problem is that when we click to any of these adapters i.e. `meshery-istio`, `mehsery-linkerd`, `meshery-kuma`, .... and so on. We're redirected to `meshery-istio` [github repo](https://github.com/meshery/meshery-istio). Instead, all of these should point to their respective repos. 

Btw, it's generally a good idea to ask for assignment once you understand the issue.

**Comment by subhamgcon** [comment]
> Hi @subhamgcon,
> 
> The compatibility matrix in that page has links to various adapters as below.
> 
> <img alt="Screenshot 2022-08-09 at 10 52 16 PM" width="824" src="https://user-images.githubusercontent.com/36989112/183717844-e2c6dbe1-4b69-46aa-b973-7140786305e5.png">
> 
> The problem is that when we click to any of these adapters i.e. `meshery-istio`, `mehsery-linkerd`, `meshery-kuma`, .... and so on. We're redirected to `meshery-istio` [github repo](https://github.com/meshery/meshery-istio). Instead, all of these should point to their respective repos.
> 
> Btw, it's generally a good idea to ask for assignment once you understand the issue.

Thanks for explaining, actually I understood the issue but couldn’t find the broken link. Sorry for the misunderstanding.

**Comment by subhamgcon** [comment]
> Hey @nishantwrp @subhamgcon , mind if I take a crack at it?

Hey, I have almost solved it, sorry

**Comment by Sanyam-Garg** [comment]
> > Hey @nishantwrp @subhamgcon , mind if I take a crack at it?
> 
> Hey, I have almost solved it, sorry

Oh great!

**Comment by sarthakkathpalia** [comment]
Hey @nishantwrp , can I work on this issue? I am new to open source and I think this would be a great start :)

**Comment by sarthakkathpalia** [comment]
Thanks @leecalcote for giving me chance. I have made the necessary changes. Kindly review.
