### ISSUE TITLE
[Docs] Interactive Istio lab demo doesn't work

### ISSUE THREAD

**Issue by ipuustin** [meshery/meshery#6004]
#### Current State

For the interactive demo at https://docs.meshery.io/service-meshes/adapters/istio, clicking on the curl command for meshery installation leads to a 404 error message:

```
controlplane $ curl -L https://git.io/meshery | ADAPTERS=istio PLATFORM=kubernetes bash -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:-  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:-  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    14  100    14    0     0     27      0 --:--:-- --:--:-- --:--:--    27
bash: line 1: 404:: command not found
```

#### Desired State

No error, meshery installation works.

**Comment by hexxdump** [comment]
> #### Current State
> For the interactive demo at https://docs.meshery.io/service-meshes/adapters/istio, clicking on the curl command for meshery installation leads to a 404 error message:
> 
> ```
> controlplane $ curl -L https://git.io/meshery | ADAPTERS=istio PLATFORM=kubernetes bash -
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:-  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:-  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100    14  100    14    0     0     27      0 --:--:-- --:--:-- --:--:--    27
> bash: line 1: 404:: command not found
> ```
> 
> #### Desired State
> No error, meshery installation works.

I believe, git.io references should be replaced with meshery.io reference.
