### ISSUE TITLE
Improvement in Meshery UI dashboard

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#6015]
#### Current Behavior

Meshery does discovery different workloads in K8s cluster on which Meshery Operator is deployed but that info is not shown on the UI. Which makes it hard for new users to understand their environment more deeply.

#### Desired Behavior

Meshery should have a separate card for K8s workload on dashboard page of Meshery UI. It should tally no of nodes, namespace, services, workloads, deployments, pods etc.

**Comment by leecalcote** [comment]
https://github.com/meshery/meshery/pull/6038#pullrequestreview-1076311238
