### ISSUE TITLE
[UI] Meshery docs terminal heading icons and copy button on mobile view move with horizontal scrolling 

### ISSUE THREAD

**Issue by sourav-sharma7** [meshery/meshery#6025]
#### Current Behavior

Copy to clipboard button and bash heading text of terminal in meshery docs mobile view scrolls in horizontal scrolling
#### Desired Behavior

The buttons should be static.
#### Screenshots/Logs

![meshery docs issue](https://user-images.githubusercontent.com/78010922/184476980-224fdc4f-f24a-47ff-af3e-e9da26edb379.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by adarsh500** [comment]
Hey @sourav-sharma7 can I work on this issue?

**Comment by sourav-sharma7** [comment]
Hi @adarsh500 ,
All yours ,Thanks for volunteering. Fell free to reach out to me on slack if you need any help.

**Comment by YashKamboj** [comment]
@adarsh500 Go Ahead!!

**Comment by adarsh500** [comment]
https://user-images.githubusercontent.com/73278151/184549614-4db010d5-0e0f-4bf3-a538-ce7d21e7c7f7.mov

<img width="494" alt="Screen Shot 2022-08-14 at 11 44 47 PM" src="https://user-images.githubusercontent.com/73278151/184549673-ac2d5bff-a98f-4b4b-8931-2154ab761f1d.png">

I've implemented a neat solution for this, could you please take a look?

**Comment by YashKamboj** [comment]
@adarsh500 Please open a PR for it
