### ISSUE TITLE
Mesheryctl errors after saving a application yaml from UI

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6032]
#### Current Behavior
Mesheryctl errors after saving a application yaml from UI

```
➜ mesheryctl app list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103fbaf88]

goroutine 1 [running]:
github.com/layer5io/meshery/mesheryctl/internal/cli/root/app.glob..func2(0x105f7de20?, {0x106173650?, 0x0?, 0x0?})
	github.com/layer5io/meshery/mesheryctl/internal/cli/root/app/list.go:105 +0x1b28
github.com/spf13/cobra.(*Command).execute(0x105f7de20, {0x106173650, 0x0, 0x0})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x105f7d6a0)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
	github.com/layer5io/meshery/mesheryctl/internal/cli/root/root.go:81 +0x58
main.main()
	github.com/layer5io/meshery/mesheryctl/cmd/mesheryctl/main.go:24 +0x1c
```

#### Screenshots/Logs
Reproduction of the issue

https://user-images.githubusercontent.com/36989112/184516253-51f0ab9e-a065-4785-ae37-02d7b2d69914.mov

#### Environment

- **Host OS:** Mac 
- **Platform:** Kubernetes
- **Meshery Server Version:** edge-latest
- **Meshery Client Version:** v0.6.0-rc.6fd

#### To Reproduce
1. Go to meshery ui
2. Go to applications page
3. Import an application. (Example - [emoji.yaml](https://layer5io.slack.com/files/U0300H32G6R/F03SB8CLD2A/emoji.yaml))
4. Click on application card and then the save button. (Without changing anything)
5. Run `mesheryctl app list`
6. See Error

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by nishantwrp** [comment]
**Additional debugging info**

The issue arises because in the following line.

https://github.com/meshery/meshery/blob/33ca9cbcc9a2af39c3a33be4e240950202a20875/mesheryctl/internal/cli/root/app/list.go#L105

The value of v.CreatedAt is nil.

**Comment by leecalcote** [comment]
@EleisonC I wonder if this is an issue that you'd like to take on.

**Comment by EleisonC** [comment]
> @EleisonC I wonder if this is an issue that you'd like to take on.

Yes would like to work on this @leecalcote

**Comment by leecalcote** [comment]
@nishantwrp I'm adding the `willfix` label to ensure this is fixed.

**Comment by acald-creator** [comment]
I was just testing this out, and I didn't get this at all. Perhaps this was fixed sometime ago, and we missed this?

Here is the output from importing the Kubernetes manifest file through a local file and a url.

```bash
./mesheryctl app list
APP ID  	USER ID                             	NAME          	CREATED  	UPDATED   
afc0be10	66738663-5a53-445d-b873-91a9be9c6533	nginx-app.yaml	2-17-2023	2-17-2023	
e9ae07cc	66738663-5a53-445d-b873-91a9be9c6533	nginx-app.yaml	2-17-2023	2-17-2023	

   TOTAL                     2
```

**Comment by leecalcote** [comment]
Thank you for this, @acald-creator. @alphaX86, do you concur?

**Comment by acald-creator** [comment]
Is the user id intended to show UUID, instead of the user who is logged in?

**Comment by alphaX86** [comment]
> Is the user id intended to show UUID, instead of the user who is logged in?

@acald-creator yes, it is intended

**Comment by leecalcote** [comment]
Fixed.
