### ISSUE TITLE
[CI] Temporarily remove K8's version 1.24.3 from end to end test core workflow

### ISSUE THREAD

**Issue by Zanda256** [meshery/meshery#6041]
#### Current Behavior
The github action we use to create cluster in not supporting k8s version 1.24.3 right now causing the workflow to fail with [this](https://github.com/meshery/meshery-istio/runs/7756551899?check_suite_focus=true#step:2:219) error.

#### Desired Behavior
Passing end to end tests.

#### Implementation
Temporarily remove 1.24.3 version from core workflow.

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Good call, @acald-creator. 👍
