### ISSUE TITLE
[UI] grid view of configuration/design section don't have any import or create button 

### ISSUE THREAD

**Issue by kumarvikramshahi** [meshery/meshery#6049]
#### Current Behavior

Grid view of configuration/design section don't have any import or create button when there is no data to show on screen.

#### Desired Behavior

There should be "Create design" and "Import Pattern" button as like in list view when there is no data to show.

#### Screenshots/Logs

Grid View
![Screenshot (202)](https://user-images.githubusercontent.com/63746254/184977560-7b3d5bef-7d73-4a01-9218-9185494c8ee8.png)

List View
![Screenshot (206)](https://user-images.githubusercontent.com/63746254/184977572-5ee62631-c18d-4e33-b8fb-3f1437de0a31.png)

#### Environment

- Browser: Firefox
- Host OS: Windows
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by adarsh500** [comment]
Hey, can i take up this issue?

**Comment by pk-218** [comment]
Hey @kumarvikramshahi! I would like to contribute to this issue.

**Comment by legendarykamal** [comment]
yes sure @adarsh500 go ahead !

@pk-218 let us find you another good one.

**Comment by Chadha93** [comment]
Thank you everyone for engaging here, since I already had a PR related to UI enhancements and bug fixes I fixed this issue in that PR. You all can provide your reviews on it. It would be very helpful.

Feel free to comment on more issues, I'll assign. Keep contributing. : )

**Comment by Chadha93** [comment]
https://github.com/meshery/meshery/pull/6046
