### ISSUE TITLE
[UI] Add Icons to meshery dashboard- Recources div

### ISSUE THREAD

**Issue by Rohith-Raju** [meshery/meshery#6055]
#### Current Behavior
The current iteration of the dashboard doesn't have icons.

#### Desired Behavior
Add icons 

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by anirudhp26** [comment]
Can i help out on this issue
I am new here and looking for getting started

**Comment by Rohith-Raju** [comment]
Sure @anirudhp26 , that would be great

**Comment by legendarykamal** [comment]
Is this issue done @Rohith-Raju ?

**Comment by Rohith-Raju** [comment]
https://discuss.meshery.io/t/how-to-expose-nats-server-and-load-balancer/1150?u=rohith

**Comment by Rohith-Raju** [comment]
@legendarykamal would you like to pick this up...I have exams coming up

**Comment by Rohith-Raju** [comment]
> https://discuss.meshery.io/t/how-to-expose-nats-server-and-load-balancer/1150?u=rohith

Here's my progress, as i ran into some issues.
