### ISSUE TITLE
Propose plugins and suggested settings that align with the projects’ lint-enforced coding conventions

### ISSUE THREAD

**Issue by sivanaikk** [meshery/meshery#6056]
#### Desired Behavior

Propose plugins and suggested settings that align with the projects’ lint-enforced coding conventions to add to codespaces.
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@sivanaikk this is an item that you'll implement or should we close out the issue?
