### ISSUE TITLE
[Docs] Merge Build and Releases page inside Contributing section

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#6057]
#### Current State
We have a different section for build and releases, Since this is something particularly needed by developers, putting it inside the Contributing would be useful

<img width="220" alt="Screen Shot 2022-08-18 at 12 31 54" src="https://user-images.githubusercontent.com/51183483/185326376-33e9f1b2-ad5e-4952-a80e-57ac952cbb90.png">

#### Desired State
<img width="230" alt="Screen Shot 2022-08-18 at 12 34 52" src="https://user-images.githubusercontent.com/51183483/185329602-c443b526-00be-4d9b-ae70-614b3ddd9852.png">

NOTE: Please take care of the URL, it should be similar to other sections present inside contributing.
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sambit-sankalp** [comment]
Hey, can I work on this issue?

**Comment by asubedy** [comment]
Hi @sambit-sankalp, sure you can work on this. Before assigning though I would like to confirm, have you locally setup Meshery Docs in your system?

**Comment by abhiyant-10** [comment]
I have meshery docs setup ready as I have previously contributed to docs and would love to take this if sambit is facing any issue

**Comment by sambit-sankalp** [comment]
Hey @asubedy , I am new to this project and currently exploring it therefore, I haven't setup it up locally. But I want to contribute to this project and explore more about it.

**Comment by abhiyant-10** [comment]
@sambit-sankalp you can it's easy setup refer https://docs.meshery.io/project/contributing/contributing-docs  . If you face any issues you can share with me or in public channels in slack

**Comment by mharshita** [comment]
Hi @asubedy! I have locally set up Meshery Docs in my system and looking for some good-first-issue to start contributing. Can I please work on this issue?

**Comment by asubedy** [comment]
@sambit-sankalp You may proceed with the task, since this is an easy issue and needs to be done relatively quickly lets put a deadline of 24 hours,  failing which @abhiyant-10 can knock this out. @mharshita Thank you for your interest but since @sambit-sankalp and @abhiyant-10 mentioned their interest early I have to give them the chance. But feel free to review the changes they made, I will be tagging you as a reviewer once a PR is made

**Comment by abhiyant-10** [comment]
@sambit-sankalp were you able to setup the repo locally? In case you need some help please ask.

**Comment by sambit-sankalp** [comment]
Hey @abhiyant-10 , I tried setting up the repo locally, but faced issues and again, I have asked those issues in the discussion forum and trying to solve it one by one.

**Comment by abhiyant-10** [comment]
Well have you tried the other method of installing dependencies rather than running docker file .  Please give it a try too.

**Comment by sambit-sankalp** [comment]
Hey @abhiyant-10 , thanks for cooperating, I have successfully done the task. Just wanna ask one question.
While setting up the project locally, the [Gemfile.lock](https://github.com/meshery/meshery/blob/master/docs/Gemfile.lock) has been changed. Should I commit it or not?

**Comment by abhiyant-10** [comment]
No not the gemfile only push the YAML  file that you changed . Btw it's written in contibuting to meshery docs page 😅

**Comment by sambit-sankalp** [comment]
Hey @asubedy, I have updated the sidebar of the docs. Kindly review my PR and suggest the necessary changes if required. I would love to resolve them.
