### ISSUE TITLE
[Docs] Document Meshery Catalog in Meshery Docs

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#6058]
#### Current State
Currently there is no documentation pointing to the Meshery Catalog (https://meshery.io/catalog).

#### Desired State
We need to have a page dedicated to Meshery Catalog, with all the relevant content and links.

The issue requires you to document the Meshery Catalog on the Meshery documention website. You need to curate a content on but not limited to 
1. what is catalog 
2. what is its functionality
3. how the user can use the catalog
4. how copy link imports work
5. what work are we doing on Meshery UI to facilitate the catalog
6. how user can add content to catalog. 

These needs to be explained briefly with appropriate images and links.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sarthakkathpalia** [comment]
@asubedy can you please explain the issue in more detail. Maybe I will be able to help with this.

**Comment by asubedy** [comment]
@sarthakkathpalia, please join today's Meshery Website Call  will explain it there.

**Comment by Kanika637** [comment]
I want to work on this issue, can you explain a little bit more maybe @asubedy

**Comment by asubedy** [comment]
@Kanika637 I updated the Issue description please have a look

**Comment by Kanika637** [comment]
I would like to work on this @asubedy

**Comment by sarthakkathpalia** [comment]
Thanks @asubedy for assigning this issue. Would be great working with @Kanika637 😊

**Comment by UtkarshMishra12** [comment]
@sarthakkathpalia Please update (last chance)

**Comment by sarthakkathpalia** [comment]
Extremely sorry. Got busy in college stuff 🥲 . I have unassigned myself for this one.
