### ISSUE TITLE
[Docs] Make compatibility matrix easily accessible on the Meshery Docs

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#6063]
#### Current State
Currently to view the compatibility matrix user has to enter this URL (https://meshery.docs.io/projects/compatibility-matrix) or They have to click on the supported Platform and then click on the Compatibility Matrix Link. Since now the compatibility matrix is in a state to show relevant information, we would like it to be visible easily.

#### Desired State
Propose a design to make the compatibility matrix visible. We would want it to be shown inside the Supported platform section. https://meshery.docs.io/installation/platforms/

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by DivineOrji** [comment]
Would be working on this soon, anyone interested to join can hit me up for progress updates 👋

**Comment by asubedy** [comment]
Solved #6509
