### ISSUE TITLE
[Docs] Update REST docs and spreadsheet for Apps source type

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#6064]
#### Current State
We don't have the correct reference for API endpoints for the application source type, update all.

#### Desired State
1. Create a new column in the spreadsheet for PUT
2. Remove POST request id and endpoint, and change it to PUT endpoint.
3. Give an appropriate, example for its use.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks! Updates look good. 👍
