### ISSUE TITLE
[Docs] README: Add Docker Extension to the supported platforms table

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6082]
#### Current State
This repo's [readme](https://github.com/meshery/meshery/blob/master/README.md) is missing an entry for the Meshery Docker Extension.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Devansu-Yadav** [comment]
Hey @leecalcote I would love to take up this issue as my first contribution to Meshery! 😄

**Comment by leecalcote** [comment]
Excellent. 😀

**Comment by legendarykamal** [comment]
Awesome @Devansu-Yadav I was waiting for a newcomer  to pick this up. Best of luck :+1:
