### ISSUE TITLE
[mesheryctl] Unable to apply WASM filter `meshery exp filter apply`

### ISSUE THREAD

**Issue by pk-218** [meshery/meshery#6088]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Unable to apply WASM filter after following example command given in the documentation.
```
mesheryctl exp filter apply --file https://github.com/layer5io/wasm-filters/tree/master/http-auth
```
![image](https://user-images.githubusercontent.com/53428217/186406829-1e05ddb6-8b96-48d2-9631-dfe0e07ba7ed.png)

Also tried pointing to the raw URL, but fails.

![image](https://user-images.githubusercontent.com/53428217/186407241-ecfded99-758c-4cf1-84d5-c789e0a3dee0.png)

#### Desired Behavior

The required WASM filter is successfully applied.
It would be great to also log an error message for better user experience.

#### Screenshots/Logs

Added above.

#### Environment

- Host OS: Windows running Windows Subsystem for Linux (WSL2) for Ubuntu 20.04
- Meshery Server Version: stable-v0.6.0-rc.6fe
- Meshery Client Version: stable-v0.6.0-rc.6fe
- Platform: Minikube local Kubernetes cluster

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
Thanks for raising the issue @pk-218 👍

**Comment by lavakush07** [comment]
Can I take up this issue ?

**Comment by pk-218** [comment]
Related issue #6273

**Comment by rakshitgondwal** [comment]
I'd like to take this one up. Can you please assign me this? @alphaX86

**Comment by alphaX86** [comment]
All yours @rakshitgondwal

**Comment by rakshitgondwal** [comment]
Not being able to recreate this issue. Someone else can take this up!

**Comment by pk-218** [comment]
Following the changes made in PR #6434 by @SufyaanKhateeb, this issue doesn't exist anymore. 
Closing this issue @rakshitgondwal
