### ISSUE TITLE
Failing lint checks - [Fix ] Add logic to modify component scheme regarding inconsistent naming

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6098]
See [Fix ] Add logic to modify component scheme regarding inconsistent naming | CU-2jp390j #6095

#### Example:
<img width="547" alt="Screen Shot 2022-08-27 at 3 19 10 PM" src="https://user-images.githubusercontent.com/7570704/187046682-19a67331-0f37-49a3-b894-3a7fc2ff8922.png">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@sudo-NithishKarthik please fix as this shows as failed test on every freshly opened PR.

**Comment by leecalcote** [comment]
@pk-218, I'm failing to institute a habit of lint checking with @sudo-NithishKarthik. I wonder if you might be so good as to pick up the slack here.

**Comment by pk-218** [comment]
Yes, up for it! @leecalcote

**Comment by leecalcote** [comment]
Excellent. Thank you. @pk-218 🙂
