### ISSUE TITLE
[CI] `mesheryctl` unit test failing as `docker-compose.yaml` path is incorrect

### ISSUE THREAD

**Issue by pk-218** [meshery/meshery#6106]
#### Current Behavior

Unit test for `github.com/layer5io/meshery/mesheryctl/internal/cli/root/system` fails due to incorrect URL to download `docker-compose.yaml`. Thus, GitHub Actions job _Golang Unit and Integration Tests / Unit tests (pull_request)_ fails for every `mesheryctl` related change

![image](https://user-images.githubusercontent.com/53428217/186976466-b5dc4d91-2e9f-4c1d-aaf4-2f97660d16d2.png)

#### Desired Behavior

Unit test for `github.com/layer5io/meshery/mesheryctl/internal/cli/root/system` passes

#### Implementation

Update path to `docker-compose.yaml` at [platform.go#332](https://github.com/meshery/meshery/blob/master/mesheryctl/pkg/utils/platform.go#L332) and [platform.go#352](https://github.com/meshery/meshery/blob/master/mesheryctl/pkg/utils/platform.go#L352)

"docker-compose.yaml" to "docs/docker-compose.yaml"

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Good find and fix, @pk-218. We have another issue here: the compose file should be under /install/docker, not /docs. that location was probably an oversight in the recent folder restructuring changes. 

As you set about making this change, note that updating its location will likely mean a change in areas other than platform.go.

**Comment by pk-218** [comment]
Sure @leecalcote, will take care of that
