### ISSUE TITLE
[UX] [UI] Offer Social Sharing of User Milestones

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6112]
#### Current Behavior
Meshery UI is in need integrating a few social (e.g. twitter, linkedin) share options for when a user accomplishes a milestone like completing a performance test or deploying a design pattern or deploying a service mesh.

#### Desired Behavior
Provide user with mechanism to share these milestones:

1. Successful run of a performance test with a test result chart.
1. Successful deployment of a service mesh.
1. Successful deployment of a design or application.

#### Implementation
1. UX: User experience design needed for these _three_ areas.
1. UI: First, seek a reusable React social package with Twitter, LinkedIn and (optionally) Facebook supported.

#### Acceptance Tests
1. Users may share their successful milestone on Twitter or LinkedIn.2. 
    1. It would be nice if users can share on Facebook, too, but not a hard requirement.

#### Mockups
[An initial mockup](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=3780%3A20909) has started for the 2nd and 3rd scenarios of successful deployments using the Notification Center, but is incomplete.

<img width="641" alt="Screen Shot 2022-08-27 at 3 47 15 PM" src="https://user-images.githubusercontent.com/7570704/187047469-d5e3e7b9-f0fb-48dd-bef0-7320a661d6bf.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by adarsh500** [comment]
Hey Lee, this seems like an interesting issue to work on. Can i take this up?

**Comment by leecalcote** [comment]
Hi @adarsh500 thanks for asking. Given that @DivineOrji is on UX and @MUzairS15 is on implementation, it's not clear to me. I'll let @MUzairS15 chime-in as to whether there's a clean break on one of the three use cases.

**Comment by DivineOrji** [comment]
Currently working on this Issue 

Here is the figma link https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=2%3A5814

**Comment by leecalcote** [comment]
Mission accomplished. Thanks for getting this feature completed, @MUzairS15. 👍
