### ISSUE TITLE
[Docs] Wrong url for meshery client architecture svg

### ISSUE THREAD

**Issue by vaibhav135** [meshery/meshery#6115]
When clicked on the meshery architecture svg it opens the old svg url (maybe). 

#### Current State

url: https://raw.githubusercontent.com/meshery/meshery/master/assets/img/readme/Meshery-client-architecture.svg

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/39329182/187067455-627666ab-6ec4-465a-96d0-6f4a8240587c.png">

#### Desired State

url: https://raw.githubusercontent.com/meshery/meshery/master/docs/assets/img/architecture/Meshery-client-architecture.svg

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/39329182/187067553-50fba938-90e0-4731-86b2-1636c6cc2111.png">

---

**Comment by vaibhav135** [comment]
@leecalcote  can I take this issue?

**Comment by deveshXm** [comment]
I would like to work on this.

**Comment by leecalcote** [comment]
Thanks, @vaibhav135
