### ISSUE TITLE
Enhance Meshery performance to account for multi-cluster deployments

### ISSUE THREAD

**Issue by gr455** [meshery/meshery#6119]
#### Current Behavior

Currently Meshery performance tests require you to have a kubernetes cluster running. The behaviour of the tests is also undefined in case the user has multiple clusters running

#### Desired Behavior

If the user has no K8s clusters running, skip retrieving cluster info in tests. But still run the tests
If the user has multiple clusters running, retrieve enviroment information about all the clusters.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Good, good.
