### ISSUE TITLE
[Docs] Search should show results only in English

### ISSUE THREAD

**Issue by mharshita** [meshery/meshery#6120]
#### Current State
Currently, the search show results in both English and Spanish.

#### Desired State
The search results should be shown in English only.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by mharshita** [comment]
@leecalcote Please assign me this issue.

**Comment by leecalcote** [comment]
Thanks for filing this issue, @mharshita 👍

**Comment by mharshita** [comment]
@leecalcote I have made a PR. Please review.
