### ISSUE TITLE
[Docs] Incorrect image naming convention and broken image links.

### ISSUE THREAD

**Issue by vaibhav135** [meshery/meshery#6123]
#### Broken links
  | old link   | new link      |
  |    :----:   |    :----:        |
  | https://raw.githubusercontent.com/meshery/meshery/master/meshes/meshops.proto       |  https://raw.githubusercontent.com/meshery/meshery/master/server/meshes/meshops.proto  |
  | https://raw.githubusercontent.com/meshery/meshery/master/install/docker-extension/docs/img/meshmap-docker-extension-for-meshery.png/       |  just remove slash at the end    |
| https://raw.githubusercontent.com/layer5io/meshery/master/assets/img/readme/meshery_lifecycle_management.png|  https://raw.githubusercontent.com/meshery/meshery/master/docs/assets/img/readme/meshery_lifecycle_management.png  |
| https://raw.githubusercontent.com/meshery/meshery/master/assets/img/readme/meshery_multi_mesh.png| https://raw.githubusercontent.com/meshery/meshery/master/docs/assets/img/readme/meshery_multi_mesh.png| 

#### Incorrect naming convention.

| incorrect convention | correct convention |
 |    :----:   |    :----:        |
| https://raw.githubusercontent.com/meshery/meshery/master/install/docker-extension/docs/img/Docker Desktop Extension for Meshery.png | https://raw.githubusercontent.com/meshery/meshery/master/install/docker-extension/docs/img/docker-desktop-extension-for-meshery.png |

Just do a root level search for all these links (fzf, vscode etc) and you can replace them with the correct one.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vaibhav135** [comment]
@leecalcote  please assign this to me.

**Comment by legendarykamal** [comment]
@vaibhav135 even on the correct convention, I am seeing a 400 invalid request error .

**Comment by vaibhav135** [comment]
No it means that you have to rename the incorrect one to the correct one. The incorrect convention link is correct it's just the way it is named.

**Comment by legendarykamal** [comment]
Ok  @vaibhav135 go ahead :+1:
