### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by lavakush07** [meshery/meshery#6136]
#### Current State
- In the docs of **Meshery overview** there is a small typo mistake in the word kubernetes. 

#### Desired State

- It should be changed to Kubernetes.

#### Image
- A beginner friendly issue to take up.

![Screenshot 2022-08-31 173535](https://user-images.githubusercontent.com/70131581/187675146-42336762-632c-4778-9dd6-3aa46306a99c.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Himanshu664** [comment]
I want to take this issue

**Comment by lavakush07** [comment]
> I want to take this issue

Great ✅
