### ISSUE TITLE
Styling Top Right Button on Meshery's Documentation Navbar

### ISSUE THREAD

**Issue by anirudhp26** [meshery/meshery#6160]
#### Styling of Button Required

Making it Relevent to Meshery's Blue-white theme
![image](https://user-images.githubusercontent.com/107875381/188000195-d5f7d27e-d8d0-4e52-824e-722ae362be1f.png)

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
@anirudhp26 please mention how do you plan to style a bit in the description section.

Also, hope you can now find the apt doc file to work into ? :sweat_smile:

**Comment by anirudhp26** [comment]
@legendarykamal i am really sorry but still haven't figured it out

**Comment by anirudhp26** [comment]
@legendarykamal ok found it, thanks for guiding me out

**Comment by legendarykamal** [comment]
No sweat go ahead ! @anirudhp26 :100:

**Comment by anirudhp26** [comment]
> No sweat go ahead ! @anirudhp26 💯

Is it in the docs folder which is at the root dir

**Comment by legendarykamal** [comment]
> > No sweat go ahead ! @anirudhp26 100
> 
> Is it in the docs folder which is at the root dir

yes it is and you should probably comment here that you want to work on this to get assigned .

**Comment by anirudhp26** [comment]
@legendarykamal but i created this issue still i have to comment for getting assigned this work?

**Comment by anirudhp26** [comment]
Well ig the work is done and i made a pull request, i'll make sure i get assigned to any work before doing it. Sorry for that

**Comment by leecalcote** [comment]
@anirudhp26 thanks for jumping into the project. It's good to have you engaged.
