### ISSUE TITLE
[UI] Applications: Helm logo missing / broken link

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6161]
#### Current Behavior
<img width="686" alt="Screen Shot 2022-09-01 at 3 04 52 PM" src="https://user-images.githubusercontent.com/7570704/188002363-7cd66a41-ed16-4757-9ba4-a6305cd7634c.png">

#### Desired Behavior
Display Helm logo.

#### Environment

- Browser: Safari
- Host OS: Mac 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Himanshu664** [comment]
I wanna try this please assign

**Comment by Chadha93** [comment]
@leecalcote This should not be the case. Seems your components were not registered properly. I just uploaded a help chart and it's working. 
`https://github.com/prometheus-community/helm-charts/releases/download/alertmanager-0.18.3/alertmanager-0.18.3.tgz`
![image](https://user-images.githubusercontent.com/65453826/188005828-ccc7ba8e-e840-482b-9f42-b12e05af6e96.png)

**Comment by Chadha93** [comment]
The `ap3 `application doesn't seem to have any helm release items.

**Comment by warunicorn19** [comment]
There should probably be an error handler or a default handler here.

**Comment by leecalcote** [comment]
I was on the phone while filing this bug. I should note that this screenshot is from a deployment to the `platform: docker` using the `v0.6.0-stable` release version and channel.

**Comment by leecalcote** [comment]
@warunicorn19 you're right. It's safe to say that a broken image is never a good thing. The default "image" could be no image at all. Better yet, the default image can be the Meshery Application icon, which can be found in either the Figma file or in the community drive under Assets --> Meshery - https://drive.google.com/drive/folders/19iW2BJly3YEwpQt9TQnmXI63HmknOkKY?usp=sharing

**Comment by leecalcote** [comment]
@Chadha93 I see what you mean. That makes sense: a defunct entry.

**Comment by legendarykamal** [comment]
ok so cut short  if there is no release  yet or no img -> then  display a default img (Meshery Application icon)

Should I fix this @leecalcote ?

**Comment by leecalcote** [comment]
If there's no application type defined or one defined, but that is not supported (e.g. " "), yes, please incorporate a default icon.

**Comment by deepeshaburse** [comment]
@legendarykamal Kindly update your PR according to requested changes.

**Comment by leecalcote** [comment]
I'm applying the "wontfix" label as this issue was transient and a fix is no longer desired.

**Comment by leecalcote** [comment]
Thanks for your help, @legendarykamal

**Comment by legendarykamal** [comment]
ok @leecalcote , happy to help .
