### ISSUE TITLE
[UI] Having ellipsis text property in Cards 

### ISSUE THREAD

**Issue by harkiratsm** [meshery/meshery#6172]
#### Current Behavior

![Screenshot from 2022-09-04 15-47-30](https://user-images.githubusercontent.com/71957674/188308759-97c073d8-8ba8-4df1-8285-f33a54fd6de1.png)

#### Desired Behavior

 Add text ellipsis property for text in the Card.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Himanshu664** [comment]
Hey please assign I want to do this

**Comment by leecalcote** [comment]
Thank you, @harkiratsm

**Comment by rakshitgondwal** [comment]
Hey @Himanshu664 ! 
Are you still working on this issue?

**Comment by Himanshu664** [comment]
@rakshitgondwal I am unable to locate the code can you help me out

**Comment by harkiratsm** [comment]
@Himanshu664 It's [here](https://github.com/meshery/meshery/blob/master/ui/components/MesheryPatterns/MesheryPatternCard.js#L82), Good luck.

**Comment by harkiratsm** [comment]
@Himanshu664 How is it coming along, feel free to ask question https://discuss.meshery.io/

**Comment by Devharal** [comment]
If issue is still open can it be assigned to me?

**Comment by Himanshu664** [comment]
@Devharal Please go ahead I am quite busy with my exams.All the best, it is very easy issue

**Comment by NikhilSharma03** [comment]
Can I work on this? // @harkiratsm

**Comment by JayKania** [comment]
Can I also work on this ? @harkiratsm

**Comment by leecalcote** [comment]
> Hey @harkiratsm , I am not being able to setup the meshery-ui locally. Can you help me out?

Here you are, @rakshitgondwal - https://docs.meshery.io/project/contributing/contributing-ui

**Comment by harkiratsm** [comment]
@JayKania there are various [open issues](https://github.com/meshery/meshery/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22), where you can help. :smile:

**Comment by rakshitgondwal** [comment]
> > Hey @harkiratsm , I am not being able to setup the meshery-ui locally. Can you help me out?
> 
> Here you are, @rakshitgondwal - https://docs.meshery.io/project/contributing/contributing-ui

Thanks for this @leecalcote but I've already gone through this, but I'm still getting an error.
I have raised a new topic in Layer5's discuss section regarding this.
Here - https://discuss.meshery.io/t/error-while-setting-up-meshery-ui-on-my-local-machine/1517

**Comment by leecalcote** [comment]
@NikhilSharma03 are you still chasing this one down?

**Comment by Chadha93** [comment]
No longer an issue: 
![image](https://user-images.githubusercontent.com/65453826/202559031-d4dd0e33-4e84-4338-9525-b9d91ff68d56.png)
