### ISSUE TITLE
A small typo mistake in Cloud native catalog page

### ISSUE THREAD

**Issue by lavakush07** [meshery/meshery#6175]
#### Current State

- Correct the word **compatibilty** . While I am reading the docs I came to this one.
![image](https://user-images.githubusercontent.com/70131581/188363695-8d8f7105-173f-4127-b06b-6f3f6f16ec73.png)

#### Desired State
 
- Change it to **compatibility** 
- A beginner friendly issue. Any new comer can take this one 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by abhiyant-10** [comment]
I can do this :)

**Comment by Chadha93** [comment]
Hi @lavakush07. This repository is for Meshery only, will you please open this issue here https://github.com/meshery/meshery.io for site updates?

**Comment by lavakush07** [comment]
> Hi @lavakush07. This repository is for Meshery only, will you please open this issue here https://github.com/meshery/meshery.io for site updates?

Yeah sure @Chadha93, Done

**Comment by Chadha93** [comment]
> > Hi @lavakush07. This repository is for Meshery only, will you please open this issue here [meshery/meshery.io](https://github.com/meshery/meshery.io) for site updates?
> 
> Yeah sure @Chadha93, Done

Thank you
