### ISSUE TITLE
Logo missing 

### ISSUE THREAD

**Issue by lavakush07** [meshery/meshery#6176]
#### Current Behavior

There is a missing of logo in the repository overview.
![image](https://user-images.githubusercontent.com/70131581/188364582-9936b118-9797-47e1-8b4b-b7cc5bcaf3b8.png)

#### Expected Behavior

- Logo should be seen just like other repos.
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Himanshu664** [comment]
Hey I want to work on this

**Comment by lavakush07** [comment]
Can I please take this issue up , Thank you for asking.

**Comment by Himanshu664** [comment]
@lavakush07 Sure Go Ahead

**Comment by legendarykamal** [comment]
This is opened in the wrong repo , hence closing it .
Please open in layer5 not here .
