### ISSUE TITLE
[UI] cluster settings interface: Add onclick row expansion + modify cursor on hover

### ISSUE THREAD

**Issue by CyrineG** [meshery/meshery#6191]
#### Current Behavior

In the cluster settings interface page, in order to display the cluster details the user must click on the small arrow '>' , this will then expand the row and show more details. 

This is not intuitive, as the arrow is very small and there is no indication that it should be clicked (cursor remains the same on hover, and clicking the row merely selects it). 
![image](https://user-images.githubusercontent.com/25556789/189111174-36ac5532-a98b-4d74-ab8b-3f75ab58cf3a.png)

#### Desired Behavior

It is more intuitive to triggering the row expansion through an onclick event. Changing the cursor when it is hovering over the row, will even more so stimulate the user's curiosity to click on the row.

#### Implementation

This issue suggests two changes:
- row expand on click,
- and the mouse changing  when its hovering over a row
#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment]
Hii @CyrineG I would love to work on this.

**Comment by leecalcote** [comment]
A UI mockup is needed.

**Comment by leecalcote** [comment]
@CyrineG please open a separate issue on the "in cluster" versus "out of cluster". Do, also, confirm that you've opened up the other 6 or so tasks/issues we recently covered.

**Comment by CyrineG** [comment]
>@CyrineG please open a separate issue on the "in cluster" versus "out of cluster".

@leecalcote already [done](https://github.com/meshery/meshery/issues/6192)!
