### ISSUE TITLE
[UI] Cluster settings interface: discrepancy between cluster context and type of deployment

### ISSUE THREAD

**Issue by CyrineG** [meshery/meshery#6192]
#### Current Behavior

Deployment context is 'in cluster' (correct) but the type of deployment is displayed as 'out of cluster' (wrong)
![image](https://user-images.githubusercontent.com/25556789/189124501-dbb79e1a-8d2b-45f0-802d-b6fb01325783.png)

#### Desired Behavior

Deployment context and type of deployment should be similar.
#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment]
Hii @CyrineG I'll love to work on this.

**Comment by CyrineG** [comment]
Awesome, I'm assigning this issue to @sam1code then

**Comment by sam1code** [comment]
Here it is not getting value for inClusterConfig so I used outclusterconfig to check it is out of cluster... Taken reference from Meshery MesherySettings...

**Comment by sam1code** [comment]
For now I'm not going to create any PR to meshery till 29th september!
I'll try to create on 30 if it is still assigned to me!
Still I'll create the last PR for meshery today then I'll start again from 295h september!

**Comment by legendarykamal** [comment]
@sam1code how far have you been here?

**Comment by sam1code** [comment]
@legendarykamal I was tried but not getting a proper solution as of now ..

**Comment by sam1code** [comment]
And to be honest I forgot about this issue after my exams!
