### ISSUE TITLE
[CI] Integration tests failing

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#6193]
#### Current Behavior
When you run the integration test, this command below will fail via GitHub Actions workflow and local development because the version is not updated to reflect the latest `mesheryctl` version which is now at `v0.6.6`. Integration test is showing version `v0.5.10`

`go test -run Integration ./... -race -coverprofile=coverage.txt -covermode=atomic -timeout 40m`

#### Expected Behavior
Integration test should run successful at the testing of `mesheryctl` tool

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/18711313/189359501-e1221b1b-c6ea-4d6b-87ec-4f75aa3a5483.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
I wonder if https://github.com/meshery/meshery/pull/6243 fixes this issue or not.

**Comment by acald-creator** [comment]
@leecalcote

Yes, for now. I did bring up in one of the meetings that I believe we should create a way to automatically update the version without manual work, because each time there is a release, you also need to update the test as well.

The option could be via CLI from `mesheryctl` or through BASH scripting.

But yes, this can be closed.

**Comment by leecalcote** [comment]
Oh, right. Yes, the tests will become stale over time. Let's do track this as an enhancement whether in a rewrite of this issue or in a new issue. That would be great.
