### ISSUE TITLE
[Golang] Failed lint check in server/models/package_manager.go

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6198]
#### Current Behavior
The return value of `ap.UpdatePackageData` needs checked. See screenshot.

#### Screenshots/Logs

<img width="728" alt="Screen Shot 2022-09-09 at 3 49 26 PM" src="https://user-images.githubusercontent.com/7570704/189441912-e3b595b7-a768-4d8c-8da3-1d3e18283eac.png">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by khanjasir90** [comment]
@leecalcote I would love to work on this

**Comment by rakshitgondwal** [comment]
Hey @leecalcote 
I would love to try solving this issue. Can you give me a brief about how this issue can be solved?

**Comment by legendarykamal** [comment]
Thank you gents for showing interest on this issue, assigning based on FCFS .
@khanjasir90 :+1:

**Comment by rakshitgondwal** [comment]
Hey @khanjasir90 !!! 
Would you like to work on this issue together? As this is a good first issue, I think it would bring me some good learnings and I really want to give it a try. What say?

**Comment by khanjasir90** [comment]
Yep sure!

**Comment by rakshitgondwal** [comment]
you got discord or slack? @khanjasir90

**Comment by acald-creator** [comment]
// @leecalcote This issue has been fixed via this commit https://github.com/meshery/meshery/commit/04e6dab2cd67a5bbf174ffeb971d771a7b8aaedb and it's already on master, we can close this issue.

**Comment by leecalcote** [comment]
Thank you, @acald-creator 👍
