### ISSUE TITLE
[UX] Brainstorm new Figma layout for meshery settings interface

### ISSUE THREAD

**Issue by CyrineG** [meshery/meshery#6199]
#### Current Behavior

This is the current settings interface
![image](https://user-images.githubusercontent.com/25556789/189465091-8f4d16d1-4c97-4c56-bf28-b6bf0af14eda.png)

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by CyrineG** [comment]
Awesome, I'll assign it to you then! @joanamadasun

**Comment by Sinonaif** [comment]
Hey, would love to work on this too
