### ISSUE TITLE
[Docs] Add websocket port to list of ports in meshery documentation

### ISSUE THREAD

**Issue by CyrineG** [meshery/meshery#6200]
#### Current State
Websocket port needs to be added to the meshery architecture [network ports table](https://docs.meshery.io/concepts/architecture#network-ports)

#### Desired State

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vishnus17** [comment]
Hi @CyrineG . I've fixed this issue along with #6204 and made PR which was approved by you and @hershd23. Can you/someone with write access approve the changes as other PRs are being committed into the repo which would need me to update the branch again.
Thanks
