### ISSUE TITLE
[Docs] Google docs: get rid of deprecated documentation

### ISSUE THREAD

**Issue by CyrineG** [meshery/meshery#6201]
#### Current State
The community google docs folder contains deprecated documentation that needs to be cleaned up. 

#### Desired State

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
@CyrineG I dont think everyone has the permission to do so, maybe the admins @leecalcote , @Chadha93 ..etc can do it. 
+ @CyrineG can you mention the docs that are the depreciated ones ?

**Comment by CyrineG** [comment]
@legendarykamal you are right, only a few people have permissions to do this task. I will be closing this issue since it's not something a community member can execute.

**Comment by legendarykamal** [comment]
Exactly
