### ISSUE TITLE
[mesheryctl] While deploying on docker , Docker compose is requiring permission for auto installing

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery#6206]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

This is a dependency to #2652

#### Current Behavior

 This issue persists due to auto-install of docker-compose and mesheryctl not having moved to the golang-integration.

Installed mesheryctl via docker 
but recieved error of kubernetes which is not as expected. 
#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/95926324/189543432-eccea594-492a-4c69-aacf-274abc820a4e.png)

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
To clarifying, currently, `mesheryctl` should / does auto-install `docker-compose`. It seems that an edge case surrounding permissions isn't accounted for in this install process. While a temporary fix can be made, the overarching goal is to move away from use lib-compose as an external executable to use of docker-compose as a golang library.

**Comment by legendarykamal** [comment]
update I had put this up on the meshery dev meeting call today and got some suggestions by @Revolyssup would be implementing them .
