### ISSUE TITLE
[E2E] Fix Filters configuration tests for Meshery UI

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#6209]
#### Current Behavior
Recently the REST API requests were updated to GrahQL one due to which the request/intercept calling in cypress filters needs to be refactored. Currently, they are disabled.

#### Desired Behavior
Enable the Filters E2E and Integration tests again with the new GraphQL request implementation.

#### Implementation
Initial GraphQL utils for queries and mutations that will be required are added to utils in Meshery Codebase https://github.com/meshery/meshery/tree/master/ui/utils/cypress-gql

#### Acceptance Tests
All the Cypress tests should pass including filters and configuration.

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
@MarioArriaga92 Will you make a fix for this?

**Comment by MarioArriaga92** [comment]
Working on this right now @Chadha93, thanks!

**Comment by MarioArriaga92** [comment]
This was never actually fixed

**Comment by MarioArriaga92** [comment]
Related tests: https://github.com/meshery/meshery/blob/master/ui/cypress/e2e/e2e/service_mesh_configuration_management_spec.js
