### ISSUE TITLE
[Helm] Restructure Meshery and Meshery operator helm charts

### ISSUE THREAD

**Issue by CyrineG** [meshery/meshery#6211]
#### Current Behavior

Following https://github.com/meshery/meshery/pull/6005 we've come to the conclusion that as long as we are trying to install/uninstall operator under two different releases (`meshery` and `meshery-operator` releases) there will always be conflicts. 
#### Desired Behavior

As such our new goal is to completely separate out meshery  and meshery-operator. And in order to manage their lifecycles independently and without conflicts, clients like mesheryctl need to expressly deploy meshery in the meshery release and meshery-operator in the meshery-operator release.

#### Implementation

There are the steps that need to be done: 
- [x] Restructure helm charts
- [x] Make appropriate changes in mesheryctl
- [x] Make appropriate changes in meshery server
- [ ] update Meshery.io 
- [ ] update docs.meshery.io

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@CyrineG @Revolyssup, please add Meshery.io and docs.meshery.io to the checklist.

**Comment by CyrineG** [comment]
@leecalcote done!

**Comment by CyrineG** [comment]
@leecalcote I opened issues for the needed changes in Meshery.io (https://github.com/meshery/meshery.io/issues/840) and  docs.meshery.io (https://github.com/meshery/meshery/issues/6236)
