### ISSUE TITLE
[UI] Adding a tooltip for the Cards 

### ISSUE THREAD

**Issue by harkiratsm** [meshery/meshery#6215]
#### Desired Behavior

Add tooltip for the cards i.e ```applications/filters/patterns``` 

![image](https://user-images.githubusercontent.com/71957674/190159280-adbf66c8-11c6-44ce-8a6a-60a15e16176f.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
@harkiratsm can you please elaborate on what that tooltip should contain?

**Comment by dara-soji** [comment]
Please can I be assigned to this issue

**Comment by harkiratsm** [comment]
Thank you @dara-soji , if you have problems or questions https://discuss.meshery.io/

**Comment by harkiratsm** [comment]
@dara-soji how is it coming along.

**Comment by dara-soji** [comment]
@harkiratsm sorry I didn't reach out sooner, I was trying to get a hang on Go. I am working on the UI but I haven't been able to test my updates. I have set up the UI but setting up the server is where I'm having a challenge. 

Please can you help me out with the server or can I see my updates without running the server just the UI?

**Comment by legendarykamal** [comment]
without running server it isn't possible to see the updates :sweat_smile:

**Comment by dara-soji** [comment]
@legendarykamal yea it wasn't 😅, @harkiratsm I have been able to run the server and I'm working on my changes now

**Comment by JayKania** [comment]
Hi can I also work on this issue ? @harkiratsm
