### ISSUE TITLE
Readme, docs: update Meshery logo

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6216]
#### Current Behavior
The Meshery logo with tagline is antiquated.

#### Implementation
Swap out all instances of the tagline logo with a version sans tagline.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by tinniaru3005** [comment]
Hey I would like to work on it

**Comment by tinniaru3005** [comment]
Can you please assign it to me?

**Comment by leecalcote** [comment]
@tinniaru3005 

- Anywhere that you see Meshery logos with the “The Service Mesh Company” tagline, please take a note and let’s see that is replace with a logo without the tagline.
- Anywhere that you see a Meshery logo with the “Multi-Mesh Manager” tagline, please take  a note and let’s see that is replace with a logo without the tagline.

Find copies of logos in the Community Drive under the Assets folder or on [meshery.io/brand](http://meshery.io/brand)

**Comment by tinniaru3005** [comment]
Hey @leecalcote Do I need to change the logo here also?
![meshery-logo](https://user-images.githubusercontent.com/62856848/197997404-795c7c4e-b1db-42c9-9077-c04eb3bbc396.png)

**Comment by leecalcote** [comment]
Yes, please
