### ISSUE TITLE
Upgrade Go 1.17 to 1.19, fallback to 1.18 if issues arise

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#6220]
#### Current Behavior

Currently, we are developing under Go 1.17 across almost all projects that is a Go project. Go 1.17 is currently at EOL, here is the reference to the EOL chart:

https://endoflife.date/go

#### Desired Behavior

We should start the process to upgrade to Go 1.19, but we can fall back to Go 1.18 if issues/concerns arise.

#### Implementation

This raised issue will remain as the way to track the upgrade to Go 1.19/1.18

TODO: will add the list of repos that will need the upgrade
⛔ Not yet, init'ed. - https://github.com/meshery/meshery-tanzu-sm
⛔ Deprecated - https://github.com/meshery/meshery-octarine

IN PROGRESS:

⚠️ AWAITING REVIEW AND PARTIALLY DONE:
 
✅  DONE
- https://github.com/layer5io/meshery-cloud | `go.1.19`
- https://github.com/meshery/meshery-consul | `go1.19`
- https://github.com/meshery/meshkit | `go1.19`
- https://github.com/meshery/meshsync | `go1.19`
- https://github.com/meshery/meshery-istio | `go1.19`
- https://github.com/meshery/meshery-nginx-sm | `go1.19`
- https://github.com/meshery/meshery-traefik-mesh | `go1.19`
- https://github.com/meshery/meshery-adapter-library | `go1.19`
- https://github.com/meshery/meshery-osm | `go1.19`
- https://github.com/meshery/meshery | `go1.19`
- https://github.com/meshery/meshery-operator | `go.1.19`
- https://github.com/meshery/meshery-app-mesh | `go.1.19`
- https://github.com/meshery/meshery-kuma | `go1.19`

#### Acceptance Tests

None at the moment, but will edit as time goes by.

#### Mockups

None

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Status updated. I love the level of organization that you've brought to bear here, @acald-creator. I hope that @Revolyssup has shared the Adapter spreadsheet with you...

**Comment by leecalcote** [comment]
@Revolyssup please link to the spreadsheet.

**Comment by leecalcote** [comment]
@Revolyssup did you introduce the spreadsheet to @acald-creator?

**Comment by Revolyssup** [comment]
> @Revolyssup did you introduce the spreadsheet to @acald-creator?

I have updated the go1.19 status in the spreadsheet. 
@acald-creator  Here is the spreadsheet that we use in order to track the status of adapters. https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit#gid=0

**Comment by leecalcote** [comment]
Done!
