### ISSUE TITLE
Remove meshery-perf from Helm charts

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6227]
#### Current Behavior
<img width="585" alt="Screen Shot 2022-09-21 at 8 58 36 AM" src="https://user-images.githubusercontent.com/7570704/191524304-714dacac-d7d9-4503-aad0-f283f63e8289.png">

#### Expected Behavior
Artifact Hub is still trying to scan our meshery-perf image/app (of which there isn’t any). Will you ensure that this component is completely segregated or removed from our helm charts?

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by acald-creator** [comment]
From the error, it seemed to be looking for `meshery-operator:0.6.0-rc.6ff` not `meshery-perf`?

// @leecalcote

**Comment by leecalcote** [comment]
Rather, it's looking over the contents of the `Meshery-operator` chart and not able to access the `meshery-perf` image described in that chart. 

I'm just seeing the older release number here. If this isn't an issue in the latest release, we can safely close this issue knowing that it has already been resolved.

**Comment by CyrineG** [comment]
Meshery-operator's values file still contains references to meshery-perf and others despite helm charts restructuring so I will clean that up.

**Comment by alphaX86** [comment]
Fixed via #6232
