### ISSUE TITLE
[UI] Allow user to delete all K8s cluster

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#6228]
#### Current Behavior

When user tries to remove last remaining (or only available K8s cluster), user gets the below message and user is not able to delete the cluster.
<img width="483" alt="Screen Shot 2022-09-20 at 11 27 23 AM" src="https://user-images.githubusercontent.com/79860504/191525295-dc3cf7a7-9cab-4681-b5dc-20c19f4f5e7d.png">

#### Desired Behavior

Allow user to delete all connected K8s cluster.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
Hi @MUzairS15 may I take on this :)

**Comment by MUzairS15** [comment]
@legendarykamal Any updates on this??

**Comment by legendarykamal** [comment]
Sorry  @MUzairS15 , My semester exams are going on but I fill try to finish this as soon as possible .

**Comment by nik132-eng** [comment]
can I get this issue? if @legendarykamal don't have any problem
