### ISSUE TITLE
[Docs] update the helm charts installation steps

### ISSUE THREAD

**Issue by CyrineG** [meshery/meshery#6236]
#### Current State
In https://docs.meshery.io/installation/platforms/kubernetes#using-helm-charts,  the helm installation steps are :
```
helm repo add meshery https://meshery.io/charts/
helm install meshery meshery/meshery
```
#### Desired State
update them to be :
```
helm repo add meshery https://meshery.io/charts/
helm install meshery-operator meshery/meshery-operator 
helm install meshery meshery/meshery
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by XDRAGON2002** [comment]
Hi @CyrineG, I want to work on this.

**Comment by CyrineG** [comment]
Awesome! It's yours @XDRAGON2002 !

**Comment by XDRAGON2002** [comment]
> helm install meshery-operator meshery/meshery-oerator

@CyrineG Should it be meshery-operator instead of meshery-oerator?

**Comment by CyrineG** [comment]
@XDRAGON2002 yes! Sorry for the typo

**Comment by leecalcote** [comment]
@CyrineG, @Revolyssup, @XDRAGON2002, please know that the `meshery-operator` should always be installed first.

**Comment by CyrineG** [comment]
Okay, I updated the issue description to reflect that

**Comment by leecalcote** [comment]
Oh, thank you much, @CyrineG
