### ISSUE TITLE
[mesheryctl] improve the error messages in each command

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6248]
Improve the error messages in each command from the point of user experience. Here is the complete list of commands from which you can claim a command to work on.

- [ ] `mesheryctl`
- [ ]  [`mesheryctl system`](https://docs.meshery.io/reference/mesheryctl#meshery-lifecycle-management-and-troubleshooting)
- [ ]  [`mesheryctl system channel`](https://docs.meshery.io/reference/mesheryctl#meshery-lifecycle-management-and-troubleshooting)
- [ ] [`mesheryctl system context`](https://docs.meshery.io/reference/mesheryctl#meshery-lifecycle-management-and-troubleshooting)
- [ ] [`mesheryctl mesh`](https://docs.meshery.io/reference/mesheryctl#service-mesh-lifecycle-and-configuration-management)
- [ ] [`mesheryctl perf`](https://docs.meshery.io/reference/mesheryctl#service-mesh-performance-management)
- [ ] [`mesheryctl app`](https://docs.meshery.io/reference/mesheryctl#service-mesh-application-management)
- [ ] [`mesheryctl pattern`](https://docs.meshery.io/reference/mesheryctl#service-mesh-pattern-configuration-and-management)
- [ ] `mesheryctl exp`
  - [ ]  [`mesheryctl exp filter`](https://docs.meshery.io/reference/mesheryctl#data-plane-intelligence-experimental-feature)
 
We need to make sure of the following things
- There are proper error messages when users
  - Give more args than required
  - Misspell a command
  - Do not give the required input via flags or args
  - Use the command without any arguments or flags.
- The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
  - "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
  - "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."

**Comment by 17sushmita** [comment]
Hi @nishantwrp may I work on this?

**Comment by XDRAGON2002** [comment]
@nishantwrp I would like to work on this as well.

**Comment by RotimiFreq** [comment]
I would like to work on this issue.

**Comment by nik132-eng** [comment]
@nishantwrp if not assigned to anyone I want to contribute to this issue. Thank you

**Comment by XanderWatson** [comment]
I'd like to take up this issue.

**Comment by leecalcote** [comment]
Please breakdown this parent issue into many child issues.

**Comment by nishantwrp** [comment]
I've created individual issues for each command (#6265 - #6274). @17sushmita @XDRAGON2002 @RotimiFreq @nik132-eng @XanderWatson please comment on one of these issues.
