### ISSUE TITLE
[Eslint-Fix] Fix eslint warnings around key props

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#6252]
#### Current Behavior

Fix the eslint errors with key prop check:
All the map elements should have unique "key" prop: reference: https://stackoverflow.com/questions/28329382/understanding-unique-keys-for-array-children-in-react-js
![Screenshot 2022-09-26 at 9 06 48 PM](https://user-images.githubusercontent.com/48255244/192319904-f8a884f9-0fc5-421a-93f0-8ed65dfe1432.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by lavakush07** [comment]
Can I take this issue.

**Comment by XanderWatson** [comment]
I'd like to take up this issue.

**Comment by nik132-eng** [comment]
hello @Abhishek-kumar09, can I take this issue?

**Comment by Abhishek-kumar09** [comment]
@XanderWatson @nik132-eng I'll find some newer beginner first issue meanwhile you can setup the developer environment and get on slack to learn more about the community.

**Comment by siddheshJungade** [comment]
@Abhishek-kumar09 like we have to add "key" attribute with unique id for each component.Id will automatically generated using parameter passed ?

**Comment by siddheshJungade** [comment]
should I give it a try?

**Comment by Abhishek-kumar09** [comment]
@nik132-eng join the slack new comers to see some.

**Comment by Harshit-Dandriyal** [comment]
@lavakush07 Thank you for your enthusiasm, But we didn't get any response from you. So, we are removing this assignment, All the best :smile:  .

**Comment by Harshit-Dandriyal** [comment]
@XanderWatson will you like to work on this?

**Comment by XanderWatson** [comment]
@Harshit-Dandriyal Yeah sure!

**Comment by legendarykamal** [comment]
I would also like to fix some of them, 
As I get those errors on my every PR 😅.

**Comment by Harshit-Dandriyal** [comment]
@XanderWatson We will be desperate for your PR, I hope you will do your best, All the best :smile:

**Comment by legendarykamal** [comment]
@XanderWatson I have fixed some of the key errors in the above PR, lets see how that integrates .

**Comment by legendarykamal** [comment]
Reopening as not all of them were fixed by me.

@XanderWatson will you please confirm if you are on this or should I go ahead and finish this head to tail ?

**Comment by XanderWatson** [comment]
@legendarykamal I guess you should go ahead with this.
