### ISSUE TITLE
[Docs] HTML error in Compatibility Matrix

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6259]
#### Current State
This table on the https://docs.meshery.io/project/compatibility-matrix page has broken HTML: 

<img width="411" alt="Screen Shot 2022-09-27 at 11 42 09 AM" src="https://user-images.githubusercontent.com/7570704/192607225-77d848b2-4c48-4f66-ad1d-84c756b863f7.png">

#### Desired State
This table shouldn't have any broken HTML. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by XDRAGON2002** [comment]
Hi @leecalcote I would like to work on this.

**Comment by legendarykamal** [comment]
@XDRAGON2002 super fast entry, go on 💯
