### ISSUE TITLE
[mesheryctl] improve the error messages shown to users for "mesheryctl" 

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6265]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._ For additional context, see https://github.com/meshery/meshery/pull/5661.

#### Current Behavior
Responses from `mesheryctl` commands don't always have the best user experience in mind. 

#### Desired Behavior
Improve the error messages in mesheryctl commands from the user's perspective. 
1. Ensure that there are proper error messages when users:
    1. Give more arguments to a command than required
    1. Misspell a command
    1. Do not give the required input via flags or args
    1. Use the command without any arguments or flags.
1. The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
    1. "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
    1. "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."

#### Implementation
The commands in scope of this issue are:

- [ ] `mesheryctl` 
- [ ] `mesheryctl version`
- [ ] `mesheryctl completion`

#### Acceptance Tests
1. Contributor adhered to the [Meshery CLI Style Guide](https://docs.meshery.io/project/contributing/contributing-cli#meshery-cli-style-guide).

 --- 
  #### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)
  📚 For the **Reference** head over to this [pr](https://github.com/meshery/meshery/pull/5661).

**Comment by XDRAGON2002** [comment]
Hey @nishantwrp I would like to take this up.

**Comment by nishantwrp** [comment]
@XDRAGON2002 sounds great. Can you please confirm that you are able to build and run mesheryctl locally.

**Comment by legendarykamal** [comment]
hi since this needs some experience , @XDRAGON2002 would you like to collaberate with me on this one?

**Comment by RahulSurwade08** [comment]
Hey @leecalcote , I would love to contribute to this issue under Hacktoberfest. How can I get started?

**Comment by XDRAGON2002** [comment]
Hi @RahulSurwade08 I'm actually already working on this issue.

**Comment by legendarykamal** [comment]
No worries @RahulSurwade08 pick another one, there are many. 👍
