### ISSUE TITLE
[mesheryctl] improve the error messages shown to users for "mesheryctl system" (1)

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6266]
**Description**: Improve the error messages in mesheryctl commands from the user's perspective. 
**Commands in scope of this issue**: `mesheryctl system config`, `mesheryctl system logs`,  `mesheryctl system login`, `mesheryctl system logout`, `mesheryctl system check`, `mesheryctl system dashboard`, `mesheryctl system token`

---

We need to make sure of the following things
- There are proper error messages when users
  - Give more arguments to a command than required
  - Misspell a command
  - Do not give the required input via flags or args
  - Use the command without any arguments or flags.
- The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
  - "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
  - "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."
  
 --- 
  
   📚 For the **Reference** head over to this [pr](https://github.com/meshery/meshery/pull/5661).

**Comment by 17sushmita** [comment]
Can I take this up?

**Comment by nishantwrp** [comment]
@17sushmita sounds great. Can you please confirm that you are able to build and run mesheryctl locally?

**Comment by 17sushmita** [comment]
@nishantwrp I've just setup the project and able to run the mesheryctl commands and also the UI development server

<img width="601" alt="image" src="https://user-images.githubusercontent.com/42088159/192845519-c4995ea3-4dc4-4b10-b39b-fa93a29597c0.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/42088159/192845841-972a416d-d837-4fcb-98b4-a094f3928b7e.png">


Let me know if I need to setup anything else?

**Comment by nishantwrp** [comment]
Looks like you're all set. Assigning you!

**Comment by siddhikhapare** [comment]
@17sushmita @nishantwrp  I would like to work on this issue.

**Comment by kernelpanic77** [comment]
Hey @nishantwrp ! I want to work on this. I am new here. Looks like this is something I can start with. :smile:

**Comment by nishantwrp** [comment]
Sure, @siddhikhapare @kernelpanic77. Assigning you both to this issue, since this issue has many subcommands. Please collaborate among yourselves to avoid working on the same subcommand.

**Comment by kernelpanic77** [comment]
Thanks @nishantwrp ! Will colaborate on this issue with @siddhikhapare

**Comment by kernelpanic77** [comment]
@nishantwrp does cobra provide suggestion support for subsubcommands. I tried on multiple binaries of mesheryctl, but suggestion doesn't seem to work for subsubcommands. 
For instance: 
running
```
   mesheryctl pattern aply  
```
does not suggest "did you mean ? apply". 
I have made some changes to make error messages more meaningful. Will send a PR soon ?
