### ISSUE TITLE
[mesheryctl] improve the error messages shown to users for `mesheryctl system start`

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6267]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._ For additional context, see https://github.com/meshery/meshery/pull/5661.

#### Current Behavior
Responses from `mesheryctl` commands don't always have the best user experience in mind. 

#### Desired Behavior
Improve the error messages in mesheryctl commands from the user's perspective. 
1. Ensure that there are proper error messages when users:
    1. Give more arguments to a command than required
    1. Misspell a command
    1. Do not give the required input via flags or args
    1. Use the command without any arguments or flags.
1. The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
    1. "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
    1. "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."

#### Implementation
The commands in scope of this issue are:

- [ ] `mesheryctl system start`
- [ ] `mesheryctl system start --skip-update`
- [ ] `mesheryctl system start --skip-browser`
- [ ] `mesheryctl system start --skip-reset`
- [ ] `mesheryctl system start --platform`

#### Acceptance Tests
1. Contributor adhered to the [Meshery CLI Style Guide](https://docs.meshery.io/project/contributing/contributing-cli#meshery-cli-style-guide).

 --- 
  #### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)
  📚 For the **Reference** head over to this [pr](https://github.com/meshery/meshery/pull/5661).

**Comment by XanderWatson** [comment]
I'd like to take this up.

**Comment by nishantwrp** [comment]
@XanderWatson sounds great. Can you please confirm that you are able to build and run mesheryctl locally?

**Comment by XanderWatson** [comment]
Yes, I am able to build and run locally.

**Comment by XanderWatson** [comment]
Thanks @nishantwrp

**Comment by leecalcote** [comment]
@XanderWatson Please note the updated scope of this issue.

**Comment by rakshitgondwal** [comment]
Hey!! I would like to work on this issue if @XanderWatson is not working on this right now.

**Comment by leecalcote** [comment]
Thanks, @rakshitgondwal 👍

**Comment by leecalcote** [comment]
@devkapilbansal would you like to take this on?

**Comment by rakshitgondwal** [comment]
Hey @leecalcote! Is this issue still open for grabs? So sorry for being inactive earlier, was busy with college and exams, but now I am free now. I am learning Golang right now and I think this issue would be a perfect way to understand it better.

**Comment by ujju20** [comment]
@leecalcote Can I work on this issue?

**Comment by leecalcote** [comment]
> Hey @leecalcote! Is this issue still open for grabs? So sorry for being inactive earlier, was busy with college and exams, but now I am free now. I am learning Golang right now and I think this issue would be a perfect way to understand it better.

Thank you, @rakshitgondwal. Please do signal early and often in terms of setting and resetting expectations about both availability, feasibility, comfort level, and so on. Yes, let's get you assigned.

Let's also get @ujju20 assigned given that there are a number of these same types of concerns across the mesheryctl commands.

**Comment by rakshitgondwal** [comment]
> > Hey @leecalcote! Is this issue still open for grabs? So sorry for being inactive earlier, was busy with college and exams, but now I am free now. I am learning Golang right now and I think this issue would be a perfect way to understand it better.
> 
> Thank you, @rakshitgondwal. Please do signal early and often in terms of setting and resetting expectations about both availability, feasibility, comfort level, and so on. Yes, let's get you assigned.
> 
> Let's also get @ujju20 assigned given that there are a number of these same types of concerns across the mesheryctl commands.

Sure! @leecalcote. I'll ensure this from the next time.
