### ISSUE TITLE
[mesheryctl] improve the error messages shown to users for "mesheryctl system context"

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6268]
**Description**: Improve the error messages in mesheryctl commands from the user's perspective. 
**Commands in scope of this issue**: `mesheryctl system context `, `mesheryctl system context create`, `mesheryctl system context delete`, `mesheryctl system context view`, `mesheryctl system context switch`

---

We need to make sure of the following things
- There are proper error messages when users
  - Give more arguments to a command than required
  - Misspell a command
  - Do not give the required input via flags or args
  - Use the command without any arguments or flags.
- The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
  - "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
  - "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."
  
 --- 
  
   📚 For the **Reference** head over to this [pr](https://github.com/meshery/meshery/pull/5661).

**Comment by RotimiFreq** [comment]
I have carefully gone through the description of this issue and i would like to be assigned to it.

**Comment by leecalcote** [comment]
@RotimiFreq sounds great. Quick check - have you had a chance to compile mesheryctl just yet? It would be good to confirm that your dev environment is ready just before taking on the issue.

**Comment by devkapilbansal** [comment]
Hi @leecalcote I want to look into this issue
