### ISSUE TITLE
[mesheryctl] improve the error messages shown to users for "mesheryctl perf"

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6269]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._ For additional context, see https://github.com/meshery/meshery/pull/5661.

#### Current Behavior
Responses from `mesheryctl` commands don't always have the best user experience in mind. 

#### Desired Behavior
Improve the error messages in mesheryctl commands from the user's perspective. 
1. Ensure that there are proper error messages when users:
    1. Give more arguments to a command than required
    1. Misspell a command
    1. Do not give the required input via flags or args
    1. Use the command without any arguments or flags.
1. The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
    1. "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
    1. "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."

#### Implementation
The commands in scope of this issue are:

- [ ] `mesheryctl perf`
- [ ] `mesheryctl perf apply`
- [ ] `mesheryctl perf profile`
- [ ] `mesheryctl perf result`

#### Acceptance Tests
1. Contributor adhered to the [Meshery CLI Style Guide](https://docs.meshery.io/project/contributing/contributing-cli#meshery-cli-style-guide).

 --- 
  #### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)
  📚 For the **Reference** head over to this [pr](https://github.com/meshery/meshery/pull/5661).

**Comment by pratul20** [comment]
Hi @nishantwrp can I work on this?

**Comment by nishantwrp** [comment]
@pratul20 sounds great. Can you please confirm that you are able to build and run mesheryctl locally?

**Comment by pratul20** [comment]
@nishantwrp Yeah I am able to run mesheryctl locally

**Comment by nishantwrp** [comment]
Hi @pratul20, just wanted to check in. Were you able to make any progress on this issue?

**Comment by gopivaibhav** [comment]
Haii @leecalcote I am interested to work on this issue, Can you assign me this issue?

**Comment by nishantwrp** [comment]
Yes @gopivaibhav, please go ahead. Looking forward to your pull request.

**Comment by gopivaibhav** [comment]
Hi @nishantwrp I am facing an error while setting up meshery in my local system. Can you help me out with it?
I have posted in discussion form about the [error](https://discuss.meshery.io/t/facing-an-error-in-setting-up-meshery-locally/1733) I am facing with

**Comment by gopivaibhav** [comment]
Sorry for the delay, I almost forgot that I used to work on this issue after getting assigned to different issues. I will start working on this issue again.

**Comment by rjsanghamitra** [comment]
Hello @leecalcote @nishantwrp. Can I work on this issue if it is still open?

**Comment by gurpreet-legend** [comment]
Is anyone working on this issue, I would like to work on this.
As far as my understanding of the issue, we need to implement custom error messages for the cli whenever the user enters any wrong or misspelled command. This issue is very similar to the issue #6272. I could work on both and get to know more about the codebase on the go :)

@nishantwrp @leecalcote
