### ISSUE TITLE
[mesheryctl] improve the error messages shown to users for "mesheryctl mesh"

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6270]
**Description**: Improve the error messages in mesheryctl commands from the user's perspective. 
**Commands in scope of this issue**: `mesheryctl mesh`, `mesheryctl mesh validate`, `mesheryctl mesh deploy`

---

We need to make sure of the following things
- There are proper error messages when users
  - Give more arguments to a command than required
  - Misspell a command
  - Do not give the required input via flags or args
  - Use the command without any arguments or flags.
- The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
  - "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
  - "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."
  
 --- 
  
   📚 For the **Reference** head over to this [pr](https://github.com/meshery/meshery/pull/5661).

**Comment by gaurav879** [comment]
I would like to work on this @nishantwrp .

**Comment by nishantwrp** [comment]
@gaurav879 sounds great. Can you please confirm that you are able to build and run mesheryctl locally?

**Comment by leecalcote** [comment]
@gaurav879 you'll find the [Meshery CLI Style Guide](https://docs.meshery.io/project/contributing/contributing-cli) most helpful and required reading material.

**Comment by gaurav879** [comment]
@nishantwrp I am working on it if I get I'll definitely let you know.
@leecalcote I'll surely go through the guide!

**Comment by debasishbsws** [comment]
I wanna work on this. I have successfully build and run mesheryctl locally

**Comment by leecalcote** [comment]
@PratikforCoding @debasishbsws thanks for raising your hands. There are plenty of these issues to resolve. I'm assigning to both of you to address the good many commands that need UX improvement.
