### ISSUE TITLE
[mesheryctl] improve the error messages shown to users for "mesheryctl pattern"

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6271]
**Description**: Improve the error messages in mesheryctl commands from the user's perspective. 
**Commands in scope of this issue**: `mesheryctl pattern`, `mesheryctl pattern list`, `mesheryctl pattern apply`, `mesheryctl pattern view`, `mesheryctl pattern delete`

---

We need to make sure of the following things
- There are proper error messages when users
  - Give more arguments to a command than required
  - Misspell a command
  - Do not give the required input via flags or args
  - Use the command without any arguments or flags.
- The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
  - "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
  - "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."
  
 --- 
  #### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

For additional context, head over to this [pr](https://github.com/meshery/meshery/pull/5661).

**Comment by nik132-eng** [comment]
@nishantwrp can you please assign me this issue? I want to work on it

**Comment by leecalcote** [comment]
@nik132-eng plesse confirm that you have mesheryctl built and that you’ve read the uX CLI considerations in Meshery Docs by showing output of you locally built CLI and dropping a copy of on of the UX guidelines in a comment.

**Comment by leecalcote** [comment]
@nishantwrp I updated the description to include the issue template's original resources in addition to your custom note.

**Comment by legendarykamal** [comment]
since I see no updates , I am here to confirm that I have my setup ready . Can I go on with this @nishantwrp @leecalcote ?

**Comment by nishantwrp** [comment]
Yeah sure @legendarykamal!
