### ISSUE TITLE
[mesheryctl] improve the error messages shown to users for "mesheryctl app"

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6272]
**Description**: Improve the error messages in mesheryctl commands from the user's perspective. 
**Commands in scope of this issue**: `mesheryctl app`, `mesheryctl app onboard`, `mesheryctl app offboard`, `mesheryctl app list`, `mesheryctl app view`

---

We need to make sure of the following things
- There are proper error messages when users
  - Give more arguments to a command than required
  - Misspell a command
  - Do not give the required input via flags or args
  - Use the command without any arguments or flags.
- The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
  - "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
  - "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."
  
 --- 
  
   📚 For the **Reference** head over to this [pr](https://github.com/meshery/meshery/pull/5661).

**Comment by sam1code** [comment]
I would love to work on this @nishantwrp

**Comment by nishantwrp** [comment]
@sam1code sounds great. Can you please confirm that you are able to build and run mesheryctl locally?

**Comment by leecalcote** [comment]
Let's be aware of all of the flags associated with the these commands and consider UX surrounding flags, too.

**Comment by leecalcote** [comment]
@sam1code I'll unassign, pending your confirmation with output of a locally-built mesheryctl.

**Comment by sam1code** [comment]
Ohh sorry It is giving me some errors I'll try to ask someone for the help then I'll back.. Sorry I've not seen the message till now..

**Comment by leecalcote** [comment]
@sam1code, from your local fork of `meshery/meshery`, try `cd mesheryctl; make`.

**Comment by sam1code** [comment]
Ohh thankyou I'll try soon and will ask you here for this at morning today thankyou

**Comment by sam1code** [comment]
Ohh yes @leecalcote  It is running now

I can use the commands of mesheryctl on my local by ./mesheryctl hope I can do this also....

**Comment by sam1code** [comment]
yes @leecalcote  it is running now and I can use mesheryctl commands on my local maching now (with path)...
Hope I can now start with this issue!
Thankyou

**Comment by sam1code** [comment]
yes @leecalcote it is running now and I can use mesheryctl commands on my local maching now (with path)...
Thankyou

**Comment by leecalcote** [comment]
@devkapilbansal interested?

**Comment by devkapilbansal** [comment]
Sure @leecalcote 
I will try to look into it by next week

**Comment by leecalcote** [comment]
@devkapilbansal excellent. 🙂

**Comment by loyaltytrooper** [comment]
@nishantwrp I was looking to start with a good first issue for go codebase. While surfing through the code, I found that this issue ahs been handled. Maybe close this or point out which parts are still not implemented?
CC @leecalcote

**Comment by nishantwrp** [comment]
Hi @loyaltytrooper, I don't see any PR that is open/merged for this issue. You can raise a PR improving the error messages. Thanks!

**Comment by loyaltytrooper** [comment]
@nishantwrp for which subcommands would you like the error to be displayed when no flag is set?
Similarly please specify the scope of the other bullet points as well.
Also misspelling a command is already handled by cobra. I tried misspelling some commands, personalized suggestions for the command to be used came in the terminal output.

**Comment by gurpreet-legend** [comment]
Is anyone working on this issue, I would like to work on this. 
As far as my understanding of the issue, we need to implement custom error messages for the cli whenever the user enters any wrong or mis-spelled command. Also, I'm new to mesheryctl would really appreciate if someone would guide me through this issue, this would really help me understand the codebase more :)

@nishantwrp @leecalcote

**Comment by Gauravjadhav22** [comment]
Is anyone Working on this issue, i would like to work on this issue

**Comment by gurpreet-legend** [comment]
> Is anyone Working on this issue, i would like to work on this issue

Yes, I'll be making a PR soon, this PR is related to one another issue I have been working on and both the solutions require the a common change, one have already been implemented, will push the changes for this one too @Gauravjadhav22 

You can make further changes for this issue after my PR, as this issue might require some other tune ups :)
