### ISSUE TITLE
[mesheryctl] improve the error messages shown to users for "mesheryctl exp filter"

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6273]
**Description**: Improve the error messages in mesheryctl commands from the user's perspective. 
**Commands in scope of this issue**: `mesheryctl exp`, `mesheryctl exp filter`, `mesheryctl exp filter apply`, `mesheryctl exp delete`, `mesheryctl exp list`, `mesheryctl exp view`

---

We need to make sure of the following things
- There are proper error messages when users
  - Give more arguments to a command than required
  - Misspell a command
  - Do not give the required input via flags or args
  - Use the command without any arguments or flags.
- The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
  - "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
  - "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."
  
 --- 
  #### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

For additional context, head over to this [pr](https://github.com/meshery/meshery/pull/5661).

**Comment by sam1code** [comment]
Hii @nishantwrp I would like to work on this

**Comment by Akshit42-hue** [comment]
Working on it. Have been able to build and run mesheryctl locally. @nishantwrp :)

**Comment by leecalcote** [comment]
@SufyaanKhateeb checking-in... have you been successful in building `mesheryctl` thus far?

**Comment by SufyaanKhateeb** [comment]
> [r](https://github.com/meshery/meshery/pull/5661).

Yes, I was able to build mesheryctl, but I am still trying to figure out what the commands do. The resources mentioned are very helpful. I will continue working on it.

**Comment by SufyaanKhateeb** [comment]
> @SufyaanKhateeb checking-in... have you been successful in building `mesheryctl` thus far?

Yes, I was able to build mesheryctl, but I am still trying to figure out what the commands do. The resources mentioned are very helpful. I will continue working on it.

**Comment by SufyaanKhateeb** [comment]
@nishantwrp The 'mesheryctl exp filter apply' command is not working. I checked with the web interface the 'filterUrl' is "http://localhost:9081/api/filter" whereas in mesheryctl it is "http://localhost:9081/api/experimental/filter", which is not working. What should I do about this? And did you mean `mesheryctl exp filter delete`, `mesheryctl exp filter list` & `mesheryctl exp filter view`?

**Comment by leecalcote** [comment]
@SufyaanKhateeb it seems that this API endpoint was promoted from experimental to stable. Its time to move to the stable endpoint.

**Comment by SufyaanKhateeb** [comment]
How do I go about pushing the code? Do I simply create a pull request?
