### ISSUE TITLE
[mesheryctl] improve the error messages shown to users for "mesheryctl system channel"

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#6274]
**Description**: Improve the error messages in mesheryctl commands from the user's perspective. 
**Commands in scope of this issue**: `mesheryctl system channel`, `mesheryctl system channel set`, `mesheryctl system channel switch`, `mesheryctl system channel view`

---

We need to make sure of the following things
- There are proper error messages when users
  - Give more arguments to a command than required
  - Misspell a command
  - Do not give the required input via flags or args
  - Use the command without any arguments or flags.
- The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
  - "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
  - "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."
  
 --- 
  
   📚 For the **Reference** head over to this [pr](https://github.com/meshery/meshery/pull/5661).

**Comment by devkapilbansal** [comment]
Hi @nishantwrp 
I would like to look into this issue

**Comment by nishantwrp** [comment]
@devkapilbansal sounds great. Can you please confirm that you are able to build and run mesheryctl locally?

**Comment by sanyamgandhak** [comment]
Hey I am interested to work on this

**Comment by devkapilbansal** [comment]
Hi @nishantwrp Yes now I setup mesheryctl locally 😀

**Comment by leecalcote** [comment]
@devkapilbansal excellent. Let's shoot for a PR within 7 days or less. 👍

**Comment by devkapilbansal** [comment]
@leecalcote sorry for being late. I opened #6430 in a hope that all required changes are addressed

**Comment by ujju20** [comment]
Is this issue still opened for working?
