### ISSUE TITLE
[UI] Making chips consistent with component version number 

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#6277]
#### Current Behavior
The chips in the settings dashboard of Meshery UI on hover shows inconsistent component version number for k8s, MeshSync and Broker

#### Expected Behavior
The chips should show consistent component version number for k8s, MeshSync and Broker 

#### Screenshots/Logs
<img width="1157" alt="Screenshot 2022-09-28 at 9 51 17 PM" src="https://user-images.githubusercontent.com/75248557/192833308-02bc85ca-d238-4307-b519-88e1008e2eae.png">

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@sudo-NithishKarthik, if I recall correctly, you're taking this assignment, right? Or was @MUzairS15?

**Comment by sudo-NithishKarthik** [comment]
@MUzairS15 it was

**Comment by Udit-takkar** [comment]
<img width="1440" alt="Screenshot 2022-11-21 at 2 28 26 PM" src="https://user-images.githubusercontent.com/53316345/203007926-5d92ffac-5ffb-41fc-b109-6a3df86fad06.png">

hey @Chadha93  i don't understand what is meant by "inconsistent component version number for k8s, MeshSync and Broker" in the issue description. can you elaborate a bit more ?

**Comment by leecalcote** [comment]
@Udit-takkar try hovering on each chip and examine the text included in the tooltips.

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/209548565-093ba719-4528-4e92-9b11-982b657da0c2.mov

@leecalcote this is what i see after hovering over them. is there something else that that should be displayed by the tooltips?

**Comment by leecalcote** [comment]
@MUzairS15 ^^

**Comment by leecalcote** [comment]
@Udit-takkar great question. I'll let @MUzairS15 chime-in as I believe this is less of a UI consideration and more of a backend consideration of reconciling the different values being used.
