### ISSUE TITLE
[UI] Display Kubernetes Context Name in MeshSync Flush Data confirmation modal

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6278]
#### Current Behavior
In the Settings page under the Environments tab, users can click to flush the MeshSync data for a specific Kubernetes context that they have connected to Meshery. When they click to flush this data, only the data for that context is removed, but the confirmation model that shows displays to the user does not show the name of the Kubernetes context. 

#### Desired Behavior
The confirmation model should display the Kubernetes cluster name in quotation marks, so that the user is confident that only MeshSync data for the specific (currently selected) Kubernetes cluster will be deleted.

#### Acceptance Tests
1. Confirmation title bar should be: 
```Flush MeshSync data for "<k8s cluster name">?```
2. Detailed message shown should be: 

```
Are you sure that you want to remove MeshSync data for the "<k8s cluster name>"? 

Fresh MeshSync data will be repopulated for this context, if MeshSync is actively running on this cluster.
```

#### Screenshot
Here's a screenshot of the current implementation that is missing the cluster name.

<img width="1033" alt="Screen Shot 2022-09-28 at 12 15 22 PM" src="https://user-images.githubusercontent.com/7570704/192846885-9e9d0528-560d-4775-8e96-af01a0d8ec86.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
hello @leecalcote in 2 days  , as my exams come to a halt . I will be back here to finish this one 💯 . 

PS:- I am missing this place.

**Comment by NikhilSharma03** [comment]
Can I work on this?

**Comment by legendarykamal** [comment]
hi @leecalcote I am on this now can you please assign?
