### ISSUE TITLE
[Docs] Consolidate Supported Platforms and Compatibility Matrix into single page

### ISSUE THREAD

**Issue by DivineOrji** [meshery/meshery#6280]
#### Current State
Meshery Documentation has two independent pages:
- [Supported Platforms](https://docs.meshery.io/installation/platforms)
- [Compatibility Matrix](https://docs.meshery.io/project/compatibility-matrix)

These independent pages make it difficult to sift through all of the information in one view. Currently, the Compatibility Matrix is buried under Supported Platforms page and is not readily accessible.

Screenshot of current link to Compatibility Matrix page:

![image 1](https://user-images.githubusercontent.com/58899148/192860603-3f8e352a-6f60-4de9-973a-460cf7c953fa.png)

#### Desired State
Meshery Documentation has two independent pages:
- [Supported Platforms](https://docs.meshery.io/installation/platforms)
- [Compatibility Matrix](https://docs.meshery.io/project/compatibility-matrix)

#### Implementation
1. Combine these two pages into a single page under Compatibility Matrix. 
2. Move Compatibility Matrix up one level in the site hierarchy; expose a link to it on in the navigation menu.

#### Mockup
![Meshry Documentation mockup](https://user-images.githubusercontent.com/58899148/193146518-c0958a8d-ac09-4aa8-a733-1fd059ed69b7.png)

We need help and suggestions on how to improve the accessibility of the platform compatibility matrix, I have attached an image of the current progress. your contributions are welcomed.

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you, @DivineOrji. I updated the description a little. Looks great.

**Comment by DivineOrji** [comment]
> Thank you, @DivineOrji. I updated the description a little. Will you please revise the mockup by removing the section under the red ❌ and re-export, updating the screenshot under the Mockups section? A mockup with draft annotations is unnecessarily confusing otherwise.

Thanks @leecalcote for helping out with the description, this is much more explanatory, I have also updated the mockup

**Comment by ronitblenz** [comment]
Can you assign me with this issue? I would like to work on it

**Comment by leecalcote** [comment]
Thanks, @ronitblenz. Let's give this a shot. // @asubedy

**Comment by ronitblenz** [comment]
@leecalcote Please give me some time to understand the project, I am new here, so I am trying to figure out the docs.
I will make a PR asap

**Comment by asubedy** [comment]
@ronitblenz , could you please share your progress? Where are you stuck at? If it's a bit difficult for you right now we might want other contributor to have a go at this issue.
