### ISSUE TITLE
[UI] Meshery Catalog Extension enable/disable setting not remembered on refresh

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6282]
#### Current Behavior
<img width="940" alt="Screen Shot 2022-09-28 at 6 02 54 PM" src="https://user-images.githubusercontent.com/7570704/192904822-3e841b98-2039-40a9-ab3f-4df1dc2ef07c.png">

This setting is not honored beyond the user refreshing the browser.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by JayKania** [comment]
Hi can I get work on this issue ? @leecalcote

**Comment by leecalcote** [comment]
Hi @JayKania, thanks for asking. I would like of your to do so, but alas, this one will take the special talents of @gr455 in order to complete.

Don't be shy with [these](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+), though.

**Comment by JayKania** [comment]
No worries @leecalcote. I would love the opportunity to work on this project, can you guide me on which issues I could work on?

**Comment by leecalcote** [comment]
Yes, I recommend picking from the link above or getting paired with a MeshMate - https://meshery.io/community/meshmates.

**Comment by JayKania** [comment]
Thank you @leecalcote

**Comment by leecalcote** [comment]
Absolutely, @JayKania. Let me know if you don't get a foothold.

**Comment by leecalcote** [comment]
Fixed or no, @gr455?

**Comment by Chadha93** [comment]
https://github.com/meshery/meshery/pull/6450
