### ISSUE TITLE
[mesheryctl] Improve user experience for `mesheryctl system` lifecycle commands

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6286]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._ For additional context, see https://github.com/meshery/meshery/pull/5661.

#### Current Behavior
Responses from `mesheryctl` commands don't always have the best user experience in mind. 

#### Desired Behavior
Improve the error messages in mesheryctl commands from the user's perspective. 
1. Ensure that there are proper error messages when users:
    1. Give more arguments to a command than required
    1. Misspell a command
    1. Do not give the required input via flags or args
    1. Use the command without any arguments or flags.
1. The error messages being displayed to users are meaningful from user's perspective. And if applicable, a potential fix for the problem should be shown too.  For example
    1. "failed to unmarshal response body" could be modified to "couldn't process JSON response from server"
    1. "manifest not found" could be modified to "manifest not found. Please provide the path to the app manifest."

#### Implementation
The commands in scope of this issue are:

- [ ] `mesheryctl system`
- [ ] `mesheryctl system stop`
- [ ] `mesheryctl system update`
- [ ] `mesheryctl system reset`
- [ ] `mesheryctl system status`
- [ ] `mesheryctl system restart`

#### Acceptance Tests
1. Contributor adhered to the [Meshery CLI Style Guide](https://docs.meshery.io/project/contributing/contributing-cli#meshery-cli-style-guide).

 --- 
  #### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)
  📚 For the **Reference** head over to this [pr](https://github.com/meshery/meshery/pull/5661).

**Comment by legendarykamal** [comment]
Hi Is this open to assignment @leecalcote ?

**Comment by leecalcote** [comment]
Yes, although, I thought that you were already collaborating with someone on a similar issue. No? 

Do you have output from having locally built and run mesheryctl?

**Comment by legendarykamal** [comment]
yes we are doing . I felt this is similar so asked upon. I will finish that first 👍  

yes this is the output 
![image](https://user-images.githubusercontent.com/95926324/193459660-4439303f-0f7d-47e9-975e-1af7eb7a0b90.png)

**Comment by morelmiles** [comment]
hey @leecalcote 
could this be assigned to me?

**Comment by hamees-sayed** [comment]
Hello, this is my first time contributing to meshery, can I take this issue up?   
Here's the output after building it locally -> 
![image](https://user-images.githubusercontent.com/98336593/196431340-245ee807-e5cd-4686-8f33-332334599adf.png)

**Comment by leecalcote** [comment]
Thank you for confirming that you're able to build and run the project @hamees-sayed.

**Comment by hamees-sayed** [comment]
@leecalcote this issue seems to be a little outside my scope for the time being so I'll unassign it, take a step back, familiarize myself more with the project and hopefully return to it later. @legendarykamal can take this issue

**Comment by leecalcote** [comment]
@hamees-sayed, no sweat. Thank you for resetting expectations. Let's be sure to find another issue that fits. 👍

**Comment by devkapilbansal** [comment]
@leecalcote I would like to work on it

My last PR #6430 is ready for review

**Comment by leecalcote** [comment]
Oh, very good, @devkapilbansal. ✅
