### ISSUE TITLE
[UI] MeshSync Status Enhancement

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6305]
@MUzairS15 there is an opportunity here to say that MeshSync is NOT publishing to Meshery Broker and to show this as a Warning (yellow) snackbar instead. Is this feasible?

_Originally posted by @leecalcote in https://github.com/meshery/meshery/pull/6276#discussion_r982708208_

**Comment by legendarykamal** [comment]
// @MUzairS15

**Comment by MUzairS15** [comment]
@leecalcote Handled this case here https://github.com/meshery/meshery/pull/5866/files#diff-9514a9ef762e5d87704d59bd30ae5c0a1744322ddcc1bda1a51034bacf4ff690R999

**Comment by leecalcote** [comment]
Thank you, @MUzairS15
