### ISSUE TITLE
[mesheryctl] Fix `mesheryctl pattern delete`

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#6310]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

DELETE is sending request to the wrong endpoint.
DELETE works when an ID is passed like /api/pattern/<ID> along with DELETE request.
#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by harkiratsm** [comment]
will be fixed by #6174

**Comment by partik03** [comment]
@leecalcote I this issue open currently. I wanted to take up this one

**Comment by harkiratsm** [comment]
Already Fixed by https://github.com/meshery/meshery/pull/6174

**Comment by harkiratsm** [comment]
@partik03 you pick up another open issue https://github.com/meshery/meshery/issues?q=is%3Aopen+is%3Aissue+label%3Acomponent%2Fmesheryctl

**Comment by partik03** [comment]
@harkiratsm ok.Thank you.
