### ISSUE TITLE
[mesheryctl] Authentification via CLI doesn't work

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery#6316]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system config --token [File Path] ` results in an error.
#### Screenshots/Logs

for reference -> https://app.slack.com/client/TDL4L01AR/threads
#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
@legendarykamal could you mention the scenario you've encountered so that it'd be easier to debug

**Comment by legendarykamal** [comment]
@alphaX86 please click on to see the reference .

**Comment by alphaX86** [comment]
@legendarykamal this command requires a k8s cluster to be mentioned before `--token/-t` flag 

Usage: `mesheryctl system config [aks|eks|gke|minikube] -t <path>`

**Comment by alphaX86** [comment]
So, just mentioning -t won't work in this case

**Comment by legendarykamal** [comment]
ok I took the ref from the official docs here https://docs.meshery.io/guides/mesheryctl/authenticate-with-meshery-via-cli

**Comment by alphaX86** [comment]
Ah! I see, then in this case, you'd need to update the docs

**Comment by legendarykamal** [comment]
haha yes for sure :)

**Comment by alphaX86** [comment]
Great! 🔥
