### ISSUE TITLE
[Database] Add table size/record count to System Reset screen

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6333]
#### Description
Users who are considering a system reset, which is an archival of the current Meshery Database and a reinitialization of an empty Meshery Database, would benefit from a summary of the current table sizes of their existing database.

This information will also help as people are trying to troubleshoot whether or not MeshSync and GraphQL subscriptions are all working or not. 

#### Implementation
1. Meshery Server REST API enhancement to /api/system/database: GET returns summary: list of table names and number of records for each table.

#### Acceptance Tests
1. Meshery UI displays a summary of the current database with a list of table names and number of records per table.
1. [Meshery API Endpoints spreadsheet](https://docs.google.com/spreadsheets/d/1ABJCbfQRi0uN_YoP2kmHZ-lTI4S4QuvRk1_unomKNRE/edit#gid=1241442399) is up-to-date.
1. Meshery Docs has updated REST API details for /system/database.

#### Current screen
<img width="1020" alt="Screen Shot 2022-10-05 at 2 43 35 PM" src="https://user-images.githubusercontent.com/7570704/194148652-9c2c69af-f42c-4d03-bd31-45bcea641934.png">

#### Proposed screen
<img width="1312" alt="Environment Settings" src="https://user-images.githubusercontent.com/7570704/194152704-cc2c5b58-0e3f-4e3f-9467-c181979034de.png">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
Hi, I would love to take up on this.

**Comment by Meyazhagan** [comment]
@leecalcote If no body working on this, shall I work on this ?

**Comment by leecalcote** [comment]
@Meyazhagan thats sounds great. I’m not sure if these counts are readily available from the respective APIs, yet, and so completion of this issue might involve golang to enhance the APIs, too. Are you comfortable with golang of would you this to partner with another contributor, which can fulfill the backend portion? // @UsmanDev09

**Comment by Meyazhagan** [comment]
@leecalcote I am comfortable with golang also ! I already went through the code, but unable to figure out database access. Will get help from @UsmanDev09 on this

**Comment by UsmanDev09** [comment]
@leecalcote @Meyazhagan count is not yet available from the API's.

**Comment by Meyazhagan** [comment]
@UsmanDev09 
> count is not yet available from the API's.

Yes, I added endpoint to return record counts. I created the PR, check it out.

**Comment by UsmanDev09** [comment]
Thanks for your PR @Meyazhagan .

@abdullah1308 did you work on this in your PR #7685?

**Comment by abdullah1308** [comment]
> Database summary - Add table size/record count to System Reset screen #7686

@UsmanDev09 No I didn't work on this. This issue involved creating a new endpoint. @Meyazhagan's PR looks good.
