### ISSUE TITLE
[Server] REST API: Rename `/system/reset` endpoint

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6334]
#### Current Behavior
The REST API endpoint,`/api/system/reset`, refers to Meshery's Database, non-obviously.

#### Desired Behavior
Move this endpoint from `/system/reset` to `/system/database/reset`

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by con-mark** [comment]
Hi @leecalcote  I would like to take a look might not be able to complete until weekend so if you wish to give elsewhere that is ok also

**Comment by XDRAGON2002** [comment]
I would be willing to pick this up if in case @con-mark is not assigned.

**Comment by dalbarracin** [comment]
Hi @leecalcote

Any possibility to start working on this as first-issue? 

Thanks 😊

**Comment by legendarykamal** [comment]
Interesting , I could find some doc instances for this .

**Comment by sarkartanmay393** [comment]
@legendarykamal Can you kindly tell me a little more about this issue ? How should I approach or something ?

**Comment by leecalcote** [comment]
Hi All, thank you for engaging on this issue. I’m only now seeing each of these comments. I did have an exchange with @dalbarracin in the community Slack regarding this issue ~a couple days ago. Given that conversation and @gr455 as a collaboration partner, I’ll go ahead and get @dalbarracin assigned. 

As always, if the issue isn’t PR’ed and merged within a reasonable timeframe, or if the assignee signals otherwise, we’ll get the issue reassigned in a first-come, first-serve fashion according to comment timestamps.

**Comment by gr455** [comment]
@leecalcote Although this endpoint is in the API endpoints spreadsheet, I don't see it used anywhere; nor do I see any code implementation of `/system/reset`. The actual database reset happens via a graphql query not the reset endpoint.

Let me know if I am missing something

**Comment by dalbarracin** [comment]
It seems to be a documentation changes only, as @gr455 mentioned before, there's no route API definition and instead it calls a  graphql function to execute database reset.

Could you confirm this @leecalcote or we are missing something else?

**Comment by progmatic-99** [comment]
@leecalcote can you confirm the comments by @dalbarracin @gr455 ??

cc: @legendarykamal

**Comment by loyaltytrooper** [comment]
@leecalcote is there any fix that has to be done in this issue?

**Comment by deepto98** [comment]
@leecalcote If this is unassigned, can I work on this?

**Comment by Ridhvisaikasam** [comment]
@leecalcote If this is not completed, can I work on this?

**Comment by Aritra8438** [comment]
Hey @leecalcote, can I work on this issue?

**Comment by EraKin575** [comment]
Can I work on this?

**Comment by leecalcote** [comment]
Thanks, @Aritra8438

**Comment by leecalcote** [comment]
@Aritra8438 here's a helpful reference for the [Meshery API Endpoints](https://docs.google.com/spreadsheets/d/1ABJCbfQRi0uN_YoP2kmHZ-lTI4S4QuvRk1_unomKNRE/edit#gid=1241442399), which will help in our discussion. // @MUzairS15

**Comment by Aritra8438** [comment]
> Meshery API Endpoints

It seems like I need the permission to view this file, I have requested the access.

**Comment by Aritra8438** [comment]
> access is promptly granted upon submission.

Yaay, I got the access. Thanks.
