### ISSUE TITLE
[CI] The variable for goversion needs to be updated to 1.19.1 for the makefile.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery#6337]
#### Current Behavior
The GOVERSION variable is set to 1.17.8

#### Desired Behavior
Needs to be updated to 1.19.1

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
hello @Krishna2323 thank you for the heads up, we have recently updated it in the contributing docs and will subsequently update in Makefile too, But not instantly.

**Comment by sarkartanmay393** [comment]
@leecalcote I would like to work on this issue.

**Comment by legendarykamal** [comment]
here you go 🚀

**Comment by sarkartanmay393** [comment]
But @legendarykamal I see it is already updated.

<img width="1440" alt="Screenshot 2022-10-08 at 1 13 38 PM" src="https://user-images.githubusercontent.com/84321236/194696279-f960aacd-bc5d-4432-9460-ca2420377eb7.png">

**Comment by legendarykamal** [comment]
oh I see @sarkartanmay393  , then why did you ask for assignment 😆 . 

this must have been updated by maintainer already , closing this in the lie of that.
