### ISSUE TITLE
hardcoding an `s` at the end seems rather hacky

### ISSUE THREAD

**Issue by harkiratsm** [meshery/meshery#6340]
Although I have no major issues with it, hardcoding an `s` at the end seems rather hacky, would it be feasible to change something in the payload we get?

If you think what I suggested is unnecessary you can ignore it.
If you think that it makes sense but isn't urgent, you can add a TODO comment and create an issue ticket at an appropriate time
Else you can make this change in this PR

_Originally posted by @hershd23 in https://github.com/meshery/meshery/pull/6174#discussion_r988211287_

**Comment by debasishbsws** [comment]
Can I work with this issue.

**Comment by leecalcote** [comment]
@harkiratsm this issue needs rewritten as it is difficult for a would-be contributor to understand.
