### ISSUE TITLE
[Server] The kubernetes contexts are not updated

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#6349]
#### Current Behavior

- I had two clusters in my docker-dekstop, one docker-desktop other minikube
- The stopped the docker-dekstop
- Even after multiple refreshes and after multiple minutes coming to the UI, it still shows two contexts.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by rghdrizzle** [comment]
Hey i would like to work on this . Pls do guide me too

**Comment by leecalcote** [comment]
Meshery won’t remove an entry for a Kubernetes cluster connection unless you tell it to delete the connection. 

There is an open request for comment on proposed enhancements in this area - https://discuss.meshery.io/t/meshery-v0-7-0-connection-states-kubnernetes-design-review/958

**Comment by leecalcote** [comment]
Fixed in v0.7.0 with Connection States - https://docs.meshery.io/concepts/logical/connections#states-and-the-lifecycle-of-connections
