### ISSUE TITLE
[CI] MeshKit Error Util: duplicate errors causing failures

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6352]
#### Current Behavior
See https://github.com/meshery/meshery/actions/runs/3208187765/jobs/5243819262#step:6:48

#### Acceptance Tests

`make error` should execute without duplication errors.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by paularah** [comment]
Is there a pattern or range  to how the error codes are assigned or just sequentially?

**Comment by leecalcote** [comment]
> Is there a pattern or range to how the error codes are assigned or just sequentially?

@acald-creator ^^

**Comment by leecalcote** [comment]
Sounds great, @paularah. Thanks for raising your ✋. I'll connect you with @acald-creator, who can offer a few pointers, including this post written by @mgfeller - https://meshery.io/blog/meshery/introducing-meshkit-and-the-meshery-adapter-library and the [Messaging Framework and Notification / Operation Center](https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit) design spec.

**Comment by suhail34** [comment]
Relates to #8238
