### ISSUE TITLE
Error while configuring meshery with minikube

### ISSUE THREAD

**Issue by yash37158** [meshery/meshery#6359]
#### Current Behavior

Unable to setup minikube cluster neither dashboard is auto-detecting the cluster nor importing the kubeconfig is responding
#### Expected Behavior

The expected behavior was the dashboard should automatically detect the kubeconfig file or importing should work.

#### Screenshots/Logs
1. Before getting an error unmarshal error into go value of type map
<img width="1440" alt="Screenshot 2022-10-07 at 2 06 03 AM" src="https://user-images.githubusercontent.com/68152307/194798555-6c4cfc37-20cc-473c-87aa-0b7f94990e12.png">
2. invalid character '<' looking for beginning of the value
<img width="1440" alt="Screenshot 2022-10-07 at 2 44 57 PM" src="https://user-images.githubusercontent.com/68152307/194798606-06676f09-64ea-493c-b19c-8778510ab03f.png">

#### Environment

- **Host OS:** MacOS Monterey
- **Platform:** Docker
- **Meshery Client Version:** stable-v0.6.10

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you for opening this issue, @yash37158
