### ISSUE TITLE
[Docs] Dark mode for meshery documentation

### ISSUE THREAD

**Issue by Kanika637** [meshery/meshery#6372]
**Current State:**
Right now the documentation for meshery is available in light mode only

![image](https://user-images.githubusercontent.com/84350895/187164173-89aa7d0b-7ed3-4a1b-b1b6-c530c17e32c5.png)

**Desired State:**
An option for a dark theme in the documentation would be more useful and practical as most developers love dark mode.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by simrangupta234** [comment]
Hey @leecalcote! Can u assign this to me?

**Comment by chirag0002** [comment]
Is this issue still relevant??
If yes, I do like to work on this issue.

**Comment by leecalcote** [comment]
yes, it is, @chirag0002. That sounds good.

**Comment by UtkarshMishra12** [comment]
@chirag0002 Please update

**Comment by leecalcote** [comment]
Does this PR include dark mode? https://github.com/meshery/meshery/pull/6639

**Comment by UtkarshMishra12** [comment]
> Does this PR include dark mode? #6639

@leecalcote , I think this can be closed as the other PR is in progress. Your thoughts?

**Comment by leecalcote** [comment]
@UtkarshMishra12, yes, I agree, so long as the other PR has dark mode included. Even better, though might be to reassign this issue to both @GaganpreetKaurKalsi and @avikt18

**Comment by avikt18** [comment]
Ready to take this challenge 🫡. I haven't contributed to meshery yet :sweat_smile: so I will go through the repo on this weekend. I will need your help on this @GaganpreetKaurKalsi :smile:

**Comment by GaganpreetKaurKalsi** [comment]
Sure @avikt18, let's do this.
