### ISSUE TITLE
[UI] Meshery Catalog toggle behavior

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6373]
#### Current Behavior
This feature is able to be toggled in 3 places in the UI. When turned on or off in one area, this setting does not seem to be persisted properly.

<img width="466" alt="Screen Shot 2022-10-12 at 6 29 22 AM" src="https://user-images.githubusercontent.com/7570704/195331720-54ed77e1-a129-4891-947a-a7f38ac1bd93.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@gr455 what's the good word here?

**Comment by hs05june** [comment]
@leecalcote I was working on this issue. I figured out that this feature can be toggled at /extensions and /configuration/patterns. Which is the third place.

**Comment by leecalcote** [comment]
@gr455 @harkiratsm has this issue been fixed?

**Comment by harkiratsm** [comment]
@Chadha93 I guess this was fixed by your PR, right ?
