### ISSUE TITLE
[Docs] Deprecated package in CONTRIBUTING.md

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#6378]
#### Current State

Under 'Writing a Meshery Adapter' the protoc plugin for go package listed is [deprecated](https://pkg.go.dev/github.com/golang/protobuf/protoc-gen-go).

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/76054921/195442451-ed70795c-1d84-40e7-ad6b-efd413d13125.png">

Running `go get -u github.com/golang/protobuf/protoc-gen-go` gives the following output

<img width="934" alt="image" src="https://user-images.githubusercontent.com/76054921/195443483-8534673a-541c-40fc-a102-6a126cc0fec1.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by XDRAGON2002** [comment]
I would like to work on this.

**Comment by leecalcote** [comment]
Thanks for filing this, @abdullah1308. A quick check: were you wanting first dibs on the assignment of this issue?

**Comment by abdullah1308** [comment]
Yep @leecalcote, please assign the issue to me. I would appreciate it if you would add the `hacktoberfest` tag to this.
