### ISSUE TITLE
Meshery: API documentation for endpoints in server.go

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#638]
**Current Behavior**
Meshery's REST API endpoints are defined in [server.go](https://github.com/layer5io/meshery/blob/master/router/server.go), but not well-commented or externally documented.

**Desired Behavior**
Using Swagger, Meshery's REST API documentation should be auto-generated and published. Ideally, published to the Meshery documentation site (https://github.com/layer5io/meshery/blob/master/docs), if feasible.

---
**Resources**
- https://towardsdatascience.com/setting-up-swagger-docs-for-golang-api-8d0442263641

**Comment by gunjanmimo** [comment]
@leecalcote sir, I want to try to solve this issue.

**Comment by kushthedude** [comment]
@nupur-thakur Any updates over here ?

**Comment by nupur-thakur** [comment]
@kushthedude I wanted to learn about swagger when i assigned this task to myself and I searched a bit but got stuck and then I forgot about this issue, sorry for that.
But if recently when @leecalcote mentioned it in #780 It got my attention so I will start working on it again.
If you already know about swagger could you please help me with this?

**Comment by kushthedude** [comment]
@nupur-thakur I thing swaggo will be better for us, as it is a lot simpler and lighter than go-swagger. Also, @leecalcote Where are we planning to host the API documentation. Do we need auto-deploy with every commit ?

**Comment by kushthedude** [comment]
Also, will we need [dredd](https://github.com/apiaryio/dredd) after setting up API documentation?

**Comment by chandrashritii** [comment]
@leecalcote If this hasn't been resolved yet, I'll like to work on this. I have looked into using Swagger and as @kushthedude said, swaggo will be a better option to use here.

**Comment by leecalcote** [comment]
Green light here. Yes, Swaggo supports both net/http and Gorilla, which is great.

**Comment by Documentus** [comment]
Is there space for a newbie to jump in for learning purposes and a portfolio item please?

**Comment by PluckyPrecious** [comment]
Hi @Documentus sure there’s more than enough space👏🏽, I hope it’s not too late?  I welcome you to join the Meshery community here - http://slack.meshery.io to collaborate with other contributors.

**Comment by leecalcote** [comment]
Related to #2902

**Comment by piyushsingariya** [comment]
Is this supposed to close now?

**Comment by leecalcote** [comment]
@piyushsingariya, yes, quite possibly so. I'll leave this call to you.
