### ISSUE TITLE
[Docs] Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Sanket1308** [meshery/meshery#6381]
#### Current State
CONTRIBUTING.md isn't present in the Repository

#### Desired State
Add CONTRIBUTING.md file
- CONTRIBUTING.md is a must read file for a new contributor in any repository before starting to work.
- Add general good practices while starting to work with this specific project.
- Add standard Github workflow commands in the CONTRIBUTING.md (opening issues, get assigned, fork, create clone, add, commit, creating PRs).
- It will provide new potential project contributors with a short guide to how they can help with your project.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks, @Sanket1308. Are you referring to the `meshery/meshery` repo? If so, please see - https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md

**Comment by Sanket1308** [comment]
Thank for clarifying!✔
