### ISSUE TITLE
[CI] Makefile target update for protobuf

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6391]
There will need to be another PR to update the Makefile to the right package since `protoc-gen-go` has been moved to `google.golang.org/protobuf`.

For right now, this looks good to me.

_Originally posted by @acald-creator in https://github.com/meshery/meshery/issues/6380#issuecomment-1277842302_

**Comment by leecalcote** [comment]
@abdullah1308, would you like to pick this up?

**Comment by dipankardas011** [comment]
Can I give it a shot?

**Comment by abdullah1308** [comment]
@leecalcote Sure, assign the issue to me

**Comment by AbhishekTiwari23** [comment]
I would also like to contribute to this as my first issue from meshery. If it is still open, please let me know.
