### ISSUE TITLE
Fix 5 Key prop warn in MesheryAdapterPlayComponent.js

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery#6393]
#### Current Behavior

Fix 5 Key prop warn in meshery/ui/components/MesheryAdapterPlayComponent.js :

All the map elements should have unique "key" prop: reference: https://stackoverflow.com/questions/28329382/understanding-unique-keys-for-array-children-in-react-js

Run `npm run lint` to check the warnings and fix them , all others have been fixed .

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment]
Hii @legendarykamal I would like to work on this.

**Comment by PranshuSrivastava** [comment]
Hey, can I work on this?

**Comment by legendarykamal** [comment]
@sam1code @PranshuSrivastava which one of you has the setup done ?

**Comment by sam1code** [comment]
I've done my full setup of both provider and ui as well as the go lang... Also I can tun local meshery ctl

**Comment by legendarykamal** [comment]
Ok then going by First Come basis, I am assigning it to @sam1code .

Thank you @PranshuSrivastava if @sam1code is unable to get back with updates  for any reasons, Then I will assign you ✔️  .

**Comment by sam1code** [comment]
Thank you @legendarykamal
