### ISSUE TITLE
[UI] Options list overlaps the input box.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery#6394]
#### Current Behavior
[UI] Options list overlaps the input box.
![Screenshot 2022-10-17 010603](https://user-images.githubusercontent.com/85894871/196054610-a00d268c-1c37-4a29-ae37-5b3653185725.png)

#### Desired Behavior
![Screenshot 2022-10-17 010516](https://user-images.githubusercontent.com/85894871/196054619-74d8d2f7-fd0f-4740-8c6f-ba0cfda3aed2.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by siddheshJungade** [comment]
He I would like to give it a try

**Comment by AbhishekTiwari23** [comment]
Please let me know if I can contribute.
