### ISSUE TITLE
[Docs] Github tags are not fetched by just cloning. 

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery#6403]
#### Current State
The GitHub tags are not fetched by just cloning the repository and that causes errors while downloading packages from GitHub.

#### Desired State
Must add that we should fetch from Upstream URL(https://github.com/meshery/meshery) after cloning the repo.

####Screenshots 
![Screenshot 2022-10-19 014708](https://user-images.githubusercontent.com/85894871/196536095-ad64abd8-e3ab-42e5-ba77-4c8a02220ca0.png)
![Screenshot 2022-10-19 014832](https://user-images.githubusercontent.com/85894871/196536143-f1dc9b4c-c02b-4dd3-a2eb-94a5dba60fcc.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
![Screenshot 2022-10-19 014832](https://user-images.githubusercontent.com/85894871/196536106-915f0a8b-3994-4ec2-a563-75cee51e6993.png)

**Comment by leecalcote** [comment]
@theBeginner86 is this due to a recent change (or lack thereof)? // @Abhishek-kumar09

**Comment by leecalcote** [comment]
Is this still an issue?

**Comment by UtkarshMishra12** [comment]
@leecalcote @Abhishek-kumar09  @theBeginner86  ^^
