### ISSUE TITLE
[CI] Fix wrong docker release tags in adapters

### ISSUE THREAD

**Issue by gr455** [meshery/meshery#6408]
#### Current Behavior
Due to being incorrectly sorted, the `git ls-remote --tags` command returned the release tags in unwanted order, which resulted in the automation script tagging the adapters' image with the wrong version.

#### Desired Behavior
Sort the versions in an unambiguous way and get the latest version for tagging.

#### Implementation
The changes from [this PR](https://github.com/meshery/meshery/pull/6396/files) have to be propagated accross all adapters.

**Steps to propagate**
1. Go to the adapter repository
2. Navigate to `.github/workflows/multi-platform.yml`
3. Within the yaml file, navigate to the job called `docker-build`
4. Within that job, navigate to the 'Identify Release Values' step
5. In the `run` field of the job, change the tag variables by replicating the changes of the above linked PR.

(See the exact lines to change in the Istio adapter as an example [here](https://github.com/meshery/meshery-istio/blob/c4b58fa3593b165c4280800dae8791e7212f8375/.github/workflows/multi-platform.yml#L65-L68))

To be done for all the adapters:
- [x] [meshery-istio](https://github.com/meshery/meshery-istio)
- [x] [meshery-linkerd](https://github.com/meshery/meshery-linkerd)
- [x] [meshery-consul](https://github.com/meshery/meshery-consul)
- [x] [meshery-kuma](https://github.com/meshery/meshery-kuma)
- [x] [meshery-osm](https://github.com/meshery/meshery-osm)
- [x] [meshery-traefik-mesh](https://github.com/meshery/meshery-traefik-mesh)
- [x] [meshery-nginx-sm](https://github.com/meshery/meshery-nginx-sm)
- [x] [meshery-cilium](https://github.com/meshery/meshery-cilium)
- [x] [meshery-nsm](https://github.com/meshery/meshery-nsm)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by abdullah1308** [comment]
Can I work on this ?

**Comment by aditi5050** [comment]
@gr455 can you please assign this task to me

**Comment by Emranshaikk** [comment]
Can you please assign me the task

**Comment by erzohrakhan** [comment]
Can I work on this issue?

**Comment by bishal7679** [comment]
@gr455 already raised

**Comment by gr455** [comment]
Folks, one of the most important goals of good first issues is to familiarize people with the code and get their first contribution in to build a momentum. Please do only a few of these and move on to more difficult issues.

Also please mention below the issue what part of the issue you will be working on **before** actually starting to work on it to avoid duplications.

**Comment by abdullah1308** [comment]
Cool I'll pick up meshery-linkerd as I already have it locally.

**Comment by SD-13** [comment]
Hi @gr455, I am new here. Is this issue still available? I saw the issue description but still asking to double-check. Thanks,

**Comment by gr455** [comment]
@SD-13 As a matter of fact, yes! There is one more adapter remaining, can you help with that one? (meshery-nsm)

**Comment by SD-13** [comment]
@gr455 yes, I will be more than happy to do that. Thanks,

**Comment by PratikforCoding** [comment]
@gr455 hey can i try to fix the last one please?

**Comment by segunjkf** [comment]
Hello can i be assigned to this issue?
