### ISSUE TITLE
[UI] Tooltip for action buttons in Table View

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#6410]
#### Current Behavior

Table View of Patterns Tab in Configuration:
<img width="380" alt="Screenshot 2022-10-19 at 8 37 11 PM" src="https://user-images.githubusercontent.com/79860504/196731067-83f01b1e-5728-4116-a17c-52cbf5e6c48f.png">

No Tooltip on hover on one of the action buttons.

#### Desired Behavior
<img width="641" alt="Screenshot 2022-10-19 at 8 36 51 PM" src="https://user-images.githubusercontent.com/79860504/196731091-253be9a3-de88-4122-8fa9-f82b92449b7e.png">

User should see a tooltip describing the action to be performed, similar to what is shown above (Grid View of Patterns in Configuration)

I see a delay (too long) before tooltip is shown in GridView, possibly reduce this delay.
#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by neeraj-2** [comment]
can I take it @MUzairS15

**Comment by MUzairS15** [comment]
@neeraj-2 any updates??

**Comment by leecalcote** [comment]
@Udit-takkar is fixing.
