### ISSUE TITLE
[UI] Improving the notifications in the stackbar.

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery#6413]
#### Current Behavior

![image](https://user-images.githubusercontent.com/95926324/196764720-5c7ac578-9a00-4209-8300-a4b188f70528.png)
2> Don't capitalize every second letter as it gives a bad feel. Update the notifications as neccessary in the UI. 

#### Desired Behavior

1> Remove the exclamation marks '!' in the stackbar. 
One such place is when the user clones his design.

2> Don't capitalize every second letter as it gives a bad feel. Update the notifications as neccessary in the UI. 

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by rakshitgondwal** [comment]
I would like to work on this issue @legendarykamal

**Comment by legendarykamal** [comment]
here you go @rakshitgondwal .

**Comment by rakshitgondwal** [comment]
@legendarykamal https://discuss.meshery.io/t/error-while-setting-up-meshery-ui-on-my-local-machine/1517/6

**Comment by rakshitgondwal** [comment]
Hey @legendarykamal !! I just got done with the setting up of meshery UI on my local environment. A big thanks to the Meshery Community Forum. Now I wanted to get started with this issue, so can you guide me on how I should start with this issue, or how do I get started with the file structure of meshery-ui?
