### ISSUE TITLE
[UI] Designer: Filter for "public" catalog items

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery#6414]
#### Current Behavior

Currently the user can only view either public , private both or just private.

https://user-images.githubusercontent.com/95926324/196763326-8854a426-18fc-4172-94a6-358e39b15675.mp4

As you can see initially both public and private designs are available.

On clicking the filter only private designs are available.

But no way for the user to view only public catalog items,

#### Desired Behavior

To add a filter for the user to  view only public catalog items too.

#### Implementation

1. Either a new UI button could be used to view only public catalog items.
2. Or some other good UI approach could be suggested .

#### Acceptance Tests

User is able to view only public catalog items.
#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@legendarykamal please fill-in the section headings in the issue description.

**Comment by legendarykamal** [comment]
@leecalcote done.

**Comment by rakshitgondwal** [comment]
We can have a drop-down button allowing us to choose from either public or private designs.

**Comment by siddheshJungade** [comment]
Yes @rakshitgondwal should we collaborate ?

**Comment by leecalcote** [comment]
@legendarykamal will you switch from "1> " to "1. "? I'm not sure what ">" is meant to signify.

**Comment by legendarykamal** [comment]
> @legendarykamal will you switch from "1> " to "1. "? I'm not sure what ">" is meant to signify.

Switched 👍 , It meant to signify the possible solutions .

**Comment by rakshitgondwal** [comment]
> Yes @rakshitgondwal should we collaborate ?

Yeah sure!!

**Comment by Udit-takkar** [comment]
@leecalcote  can i work on this issue ?

**Comment by leecalcote** [comment]
@Udit-takkar sounds great. 👍

**Comment by Udit-takkar** [comment]
@leecalcote i think some changes in the backed api is required first.  on clicking the catalog filter button (as shown in the above video) we make an api request to "/api/user/prefs" with catalogContent ( either true or false) in the body which returns  the response either private or public catalog items.  instead of boolean we should pass something like "PUBLIC", "PRIVATE", "BOTH".  what do you think?
