### ISSUE TITLE
[Helm](Meshery) Image Version

### ISSUE THREAD

**Issue by dipankardas011** [meshery/meshery#6416]
#### Current Behavior

https://github.com/meshery/meshery/blob/e0a3a0c26362c5351697d8bf049eb9f3ef26d737/install/kubernetes/helm/meshery/values.yaml#L20

https://github.com/meshery/meshery/blob/e0a3a0c26362c5351697d8bf049eb9f3ef26d737/install/kubernetes/helm/meshery/Chart.yaml#L40

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by dipankardas011** [comment]
# Same with Meshery-Operator helm chart

https://github.com/meshery/meshery/blob/d1a17a10b392a0637c01e89c0537b95fb3a0b65b/install/kubernetes/helm/meshery-operator/templates/deployment.yaml#L31

https://github.com/meshery/meshery/blob/d1a17a10b392a0637c01e89c0537b95fb3a0b65b/install/kubernetes/helm/meshery-operator/Chart.yaml#L40

**Comment by dipankardas011** [comment]
@leecalcote can I work on this and what all things do I need to know?

**Comment by leecalcote** [comment]
@dipankardas011 you're most welcome to work on this, yes.

**Comment by dipankardas011** [comment]
@leecalcote what should be the helm chart version ?

**Comment by dipankardas011** [comment]
https://github.com/meshery/meshery/blob/e0a3a0c26362c5351697d8bf049eb9f3ef26d737/install/kubernetes/helm/meshery/Chart.yaml#L5

why this is left blank?

**Comment by dipankardas011** [comment]
> @leecalcote what should be the helm chart version ?

talking about this
https://github.com/meshery/meshery/blob/e0a3a0c26362c5351697d8bf049eb9f3ef26d737/install/kubernetes/helm/meshery/Chart.yaml#L41

**Comment by dipankardas011** [comment]
Here in deployment template of meshery-operator
https://github.com/meshery/meshery/blob/d1a17a10b392a0637c01e89c0537b95fb3a0b65b/install/kubernetes/helm/meshery-operator/templates/deployment.yaml#L31

but the value provided in the values.yaml
https://github.com/meshery/meshery/blob/d1a17a10b392a0637c01e89c0537b95fb3a0b65b/install/kubernetes/helm/meshery-operator/values.yaml#L10

**Comment by Revolyssup** [comment]
> 

This is an optional field used to define constraints on which kubernetes version the helm chart is compatible with. Meshery has no such constraints so its left blank.

**Comment by Revolyssup** [comment]
> https://github.com/meshery/meshery/blob/e0a3a0c26362c5351697d8bf049eb9f3ef26d737/install/kubernetes/helm/meshery/Chart.yaml#L5
> 
> why this is left blank?

This is an optional field used to define constraints on which kubernetes version the helm chart is compatible with. Meshery has no such constraints so its left blank.

**Comment by pratik2315** [comment]
Hey there! Can i work on this issue?
