### ISSUE TITLE
[UI] Console errors on hover navigator hover and dashboard icon disappearing

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#6424]
#### Current Behavior
Console errors on hover navigator hover and dashboard icon disappearing on click sometimes. (Do give it a test multiple ways)

#### Desired Behavior
There should not be any console log errors and the dashboard icon should not disappear. 

#### Screenshots/Logs

https://user-images.githubusercontent.com/65453826/197021866-9e96189e-70d0-4668-9eff-9e99edd94667.mp4

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
@Harshit-Dandriyal @sahilsuman933 @legendarykamal Could one of you please take this issue?

**Comment by legendarykamal** [comment]
verified it, yes it occurs on mine system too.

**Comment by sahilsuman933** [comment]
It doesn't occur in my system on the latest branch. 

https://user-images.githubusercontent.com/34382211/197043154-77f793b5-b2ef-4fe6-804b-c5209489193d.mp4

**Comment by moki1202** [comment]
@Chadha93 is this issue still up for grabs?

**Comment by sahilsuman933** [comment]
Go, Ahead! @moki1202

**Comment by Harshit-Dandriyal** [comment]
@moki1202 This item is urgent, If possible, Try to wrap this item as soon as possible, I believe in you for this, All the best, Please communicate if you will not be able to resolve this. ✌

**Comment by moki1202** [comment]
@Harshit-Dandriyal Apologies, was really busy for a couple of weeks. Also had some troubles setting up meshery's UI but its all done now. Will try to open a PR today if its fine ?

**Comment by Harshit-Dandriyal** [comment]
Go ahead @moki1202, we will wait for your PR :smiley:

**Comment by Chadha93** [comment]
Thank you for the headsup @moki1202. 
@Harshit-Dandriyal you can go ahead and make a fix for this.

**Comment by moki1202** [comment]
@Chadha93 Apologies! Couldn't get the Dev server up and running in time.

**Comment by Chadha93** [comment]
> @Chadha93 Apologies! Couldn't get the Dev server up and running in time.

No worries, you can look for solutions or post your bugs on https://discuss.meshery.io/

**Comment by moki1202** [comment]
Already opened one yesterday. Just need some input there

**Comment by leecalcote** [comment]
@Harshit-Dandriyal @moki1202 progress?

**Comment by moki1202** [comment]
@leecalcote Took me a sweet amount of time just to replicate the error. However now that it's done, I've tested a simple "wrap the child components in <div> tag" and it seems to have fixed the issue. I can open a PR if allowed.

**Comment by Chadha93** [comment]
@Shivam-AfA It's not completed. There is still an issue with the dashboard icon.

**Comment by Shivam-AfA** [comment]
Thanks @Chadha93 for pointing this out. I'll reopen this issue or else create a new one. And I'll also ensure that this issue is resolved ASAP.

**Comment by Shivam-AfA** [comment]
I guess I don't have the required permissions to reopen the issue @Chadha93
