### ISSUE TITLE
[Docs] Enhance docs for /api/user/token

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6436]
#### Current State
The functionality of this API endpoint is not well-described.

#### Desired State
Provide details as the the behavior and purpose of this endpoint.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
How does this endpoint relate to this UI menu item, "Get Token"?

<img width="258" alt="Screen Shot 2022-10-25 at 5 17 06 PM" src="https://user-images.githubusercontent.com/7570704/197894385-223484c5-6124-4830-b1cb-1d3fa7b80941.png">

**Comment by leecalcote** [comment]
@meshery/maintainers

**Comment by 0x-chaitu** [comment]
Hi, 
I am new to open source, I would like to work on this issue.

**Comment by EraKin575** [comment]
I would like to work on this

**Comment by leecalcote** [comment]
Thanks, @0x-chaitu

**Comment by 0x-chaitu** [comment]
Hi, @thisiskaransgit 
I have some confusion about this issue according to my findings.

```
/api/user/token => This api validates the token and gets the capabilities for corresponding token.
If token is not present or invalid we are redirected to /provider
```
While the UI item get token calls the below api
```
/api/token  => This api extracts the token from request and returns
		"meshery-provider": l.Name(),
		tokenName:          tokenString,
```
![image](https://github.com/meshery/meshery/assets/139210677/4c254d0d-30ff-4f04-a2f3-b92cb2e86f51)

I would like some clarification as I am new to mesheries code base.

**Comment by leecalcote** [comment]
@zakisk @suhail34

**Comment by coder12git** [comment]
@leecalcote I want to work on this issue :)

**Comment by coder12git** [comment]
Hey @leecalcote, just want to confirm that I have to work on this part of docs which states how to get your token via Meshery UI or CLI, basically I have to enhance this doc so that user can better understand that how by clicking on get token in Meshery UI, a file will be downloaded in their local system from where they can copy their auth token.
![Screenshot 2023-09-28 094608](https://github.com/meshery/meshery/assets/108334168/1bfe342e-59a5-4998-a58b-d772c2eed5c5)
