### ISSUE TITLE
[UI] Improve Environment UI

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#6443]
#### Current Behavior
1. The placement of **Add Cluster** doesn't feel right considering other buttons like `Create Design` on the Designer page.

![Screenshot 2022-10-26 at 8 46 14 PM](https://user-images.githubusercontent.com/73700530/198065993-7fd1d00a-6b9e-4673-852c-352486f2dbc8.png)

2. Better styles for **Delete** cluster button. It doesn't go well with other buttons in Meshery UI.

![Screenshot 2022-10-26 at 8 48 54 PM](https://user-images.githubusercontent.com/73700530/198066648-3d9469e4-3494-486a-8084-a53b8f83cafc.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by kumarvikramshahi** [comment]
hey @theBeginner86, if no one is working on this. I would like to work on this issue.

**Comment by theBeginner86** [comment]
> hey @theBeginner86, if no one is working on this. I would like to work on this issue.

Sure! 🙌

**Comment by kumarvikramshahi** [comment]
Hey @theBeginner86 to be precise:
1. Is this the desired design you want to **Add Cluster** button be like **Create Design** button i.e seperated from card.

![image](https://user-images.githubusercontent.com/63746254/200598112-6a6a838a-cc64-4351-96a0-a4024b12d91c.png)

2. And also i'm not being clear about styles for Delete cluster button, can you please show it by some pic, that will be very helpful for me.

**Comment by theBeginner86** [comment]
> Hey @theBeginner86 to be precise:
> 
> 1. Is this the desired design you want to **Add Cluster** button be like **Create Design** button i.e seperated from main card.
> 
> ![image](https://user-images.githubusercontent.com/63746254/200598112-6a6a838a-cc64-4351-96a0-a4024b12d91c.png)
> 
> 2. And also i'm not being clear about styles for Delete cluster button, can you please show it by some pic, that will be very helpful for me.

@kumarvikramshahi 
Those are some spot-on questions... 😎

Today we would be having our Meshery Dev call, would you please take this as an agenda item?
You can add this item in the [Meeting Minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit).

We can discuss this item with other members in the community so that you can get holistic feedback/ideas on this area 👍


> Please check [Community Calendar](https://layer5.io/community/calendar) for the meeting schedule and link. It is scheduled for 9-10am Central | 8:30-9:30pm IST

**Comment by kumarvikramshahi** [comment]
sure 🤝

**Comment by leecalcote** [comment]
@kumarvikramshahi where did we land on the approach to take?

**Comment by kumarvikramshahi** [comment]
Hey @leecalcote  I'm on it, sorry for being late.

**Comment by leecalcote** [comment]
Thanks for confirming. If this one doesn’t work out for some reason, let’s get you want to another Meshery UI issue.

**Comment by kumarvikramshahi** [comment]
Hey @leecalcote , I'm not able to edit "delete" button. As mui-datatables is used everywhere and as far as i have searched and read documentations of mui-datatables, i didn't get any props/something else to edit delete button. Thus unassigning myself. Again, sorry for too much delay.

**Comment by leecalcote** [comment]
@kumarvikramshahi thanks for sending word. I recommend inquiring in the #meshery-ui Slack channel just before you toss in the towel.

**Comment by Hardik29** [comment]
hey @theBeginner86, could I take this up ?

**Comment by leecalcote** [comment]
@Hardik29 please note the solution needed is one of UX. If Figma and user interface design is an area of competence / interest, yes, please do draft a design.

**Comment by leecalcote** [comment]
> yeah, would love to.

Great. A link to the Figma design file is above (request access).  If you haven't joined the [community Slack](http://slack.meshery.io), yet, I invite you to jump in.

**Comment by Hardik29** [comment]
requested access, plz review. 
Done joining slack.

**Comment by Mayaleeeee** [comment]
Hey @leecalcote 
I would love to work on this

**Comment by partik03** [comment]
@leecalcote I have added the pr for this issue kindly review it.

**Comment by leecalcote** [comment]
@partik03, thanks. Does the Add Cluster button only show when the Environment tab is selected?

**Comment by partik03** [comment]
> @partik03, thanks. Does the Add Cluster button only show when the Environment tab is selected?

Yes
