### ISSUE TITLE
[UI] Increase Istio logo size.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery#6446]
#### Current Behavior
[UI] Increase Istio logo size.
![current](https://user-images.githubusercontent.com/85894871/198155088-b0ad2fad-46e7-4462-a740-088614058ab2.png)

#### Desired Behavior
![expected](https://user-images.githubusercontent.com/85894871/198155100-5ee4a161-2e03-4bec-b3e4-364ce5e61fa0.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Which browser are you seeing this in, @Krishna2323?

Thanks for filing this issue. Is your zoom level 100% or is it larger?

**Comment by Krishna2323** [comment]
@leecalcote ,I am using Brave browser and the zoom level is 100%.

**Comment by leecalcote** [comment]
Ok, thanks for confirming. And for filing this issue. It’ll be nice to have this fixed.

**Comment by parthn2** [comment]
I would like to take up this issue.
