### ISSUE TITLE
Failure during installation in Kubernetes

### ISSUE THREAD

**Issue by obaranov1** [meshery/meshery#6449]
#### Current Behavior
Installation of Meshery in Kubernetes cluster is Failing.

#### Expected Behavior
I expect meshery deployment to be installed in the cluster.

#### Screenshots/Logs
Please check the status of the pods by executing “mesheryctl system status” and Meshery-UI endpoint with “mesheryctl system dashboard” before using meshery.
bash: line 260: syntax error near unexpected token `newline'
bash: line 260: `<!doctype html>'

#### Environment
- **Host OS:** Ubuntu 20.04
- **Platform:** Kubernetes node (Ubuntu 20.04.3 LTS, container runtime containerd://1.5.4)
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
mesheryctl-v0.6.18

bash: line 260: syntax error near unexpected token `newline'
bash: line 260: `<!doctype html>'

**Comment by leecalcote** [comment]
@obaranov1 thanks for filing this. The error occurs while executing `mesheryctl system dashboard`, is that right? // @hexxdump @piyushsingariya @alphaX86 @pk-218 @harkiratsm

**Comment by obaranov1** [comment]
no, when I execute `curl -L https://meshery.io/install | PLATFORM=kubernetes bash -`

**Comment by leecalcote** [comment]
@hexxdump, is this an item that you can pick up? Please note the urgency behind this issue. // @harkiratsm @nishantwrp

**Comment by hexxdump** [comment]
Will take a look @leecalcote

**Comment by hexxdump** [comment]
> curl -L https://meshery.io/install | PLATFORM=kubernetes bash -

@obaranov1,
I am not able to hit this exact issue on my ubuntu m/c.
Will it be possible to share the output from `curl -L https://meshery.io/install | PLATFORM=kubernetes bash -x -` ?

**Comment by pk-218** [comment]
I am not able to reproduce the issue as well.

On inspection of the logs, it comes from [mesheryctl/system/start](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/system/start.go#L385) and not from the installation script.

Given the input `curl -L https://meshery.io/install | PLATFORM=kubernetes bash -`, the command that is run is `mesheryctl system start --yes --platform $PLATFORM` where `PLATFORM=kubernetes`

This error occurs because the `meshery` pod doesn't go up soon as expected and fails the readiness health check.

**Comment by hexxdump** [comment]
> I am not able to reproduce the issue as well.
> 
> On inspection of the logs, it comes from [mesheryctl/system/start](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/system/start.go#L385) and not from the installation script.
> 
> Given the input `curl -L https://meshery.io/install | PLATFORM=kubernetes bash -`, the command that is run is `mesheryctl system start --yes --platform $PLATFORM` where `PLATFORM=kubernetes`
> 
> This error occurs because the `meshery` pod doesn't go up soon as expected and fails the readiness health check.

yes, the meshery installation script does not have 260 lines of code. 
"syntax error near unexpected token" issue could be related to golang versioning.
ref - https://github.com/golang/go/issues/31225
// @acald-creator

**Comment by acald-creator** [comment]
Researching

**Comment by leecalcote** [comment]
> I am not able to reproduce the issue as well.
> 
> On inspection of the logs, it comes from [mesheryctl/system/start](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/system/start.go#L385) and not from the installation script.
> 
> Given the input `curl -L https://meshery.io/install | PLATFORM=kubernetes bash -`, the command that is run is `mesheryctl system start --yes --platform $PLATFORM` where `PLATFORM=kubernetes`
> 
> This error occurs because the `meshery` pod doesn't go up soon as expected and fails the readiness health check.

Thank you for looking into this, @pk-218 👏

**Comment by obaranov1** [comment]
@hexxdump, @leecalcote, @pk-218, Hello! I am not sure what happened, but the problem is no longer appears. All Meshery pods in running state now. I think it had smth to do with my environment setup. I think we can close the issue. Thanks for fast reply and involvement :)

**Comment by leecalcote** [comment]
@obaranov1, you bet. 🙂 We certainly appreciate you taking time to file this issue. Don't hesitate to reopen this issue if you bump into it again.
