### ISSUE TITLE
[UI] Pop-up: cutoff on smaller width screens

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6488]
#### Current Behavior
Meshery UI has a recently added popup (see https://github.com/meshery/meshery/pull/6479), which is cutoff of on smaller screen sizes.

#### Desired Behavior

1. The popup should be absolutely positioned in reference to the browser.
2. The popup title should be in bold.
3. The caption should have a reduced line-height.
4. The graphic should have slightly more top and bottom padding.

#### Screenshots/Logs
<img width="1134" alt="Screen Shot 2022-11-03 at 4 28 13 PM" src="https://user-images.githubusercontent.com/7570704/199837958-c2ecbd29-8aae-464d-999a-a69c830e20f7.png">

#### Environment

- Browser: Safari
- Host OS: Mac 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
Hi, I would like to fix this.

**Comment by kayceeDev** [comment]
Hi, @legendarykamal are you already working on this? if not please allow @chiomaT to take this up. She may also need your guidance while working on it too. Thanks in advance.

**Comment by legendarykamal** [comment]
@chiomaT Let's help you and  make sure you are successfull ,
Inorder to qualify that if you could just confirm me with a screenshot that you have your project setup done of `meshery ui` ?

sure @kayceeDev in any/ every ways.

**Comment by franklinekoh** [comment]
Can I take this up @leecalcote

**Comment by leecalcote** [comment]
@kayceeDev @legendarykamal thanks much for your guidance offered to @chiomaT. @chiomaT, let's find another open issue quickly. To start, the "help wanted" hyperlink in the readme.md of this repo has a multi-org search that is quite helpful.

**Comment by chiomaT** [comment]
@legendarykamal project setup done
<img width="1511" alt="Screenshot 2022-11-09 at 21 29 51" src="https://user-images.githubusercontent.com/98219927/200936349-61466832-3092-4652-8619-03d3fbc6bcb3.png">

**Comment by chiomaT** [comment]
@legendarykamal 
<img width="1512" alt="Screenshot 2022-11-09 at 21 36 26" src="https://user-images.githubusercontent.com/98219927/200936651-cef3c681-274e-4a76-8354-bf43b55f882f.png">

**Comment by legendarykamal** [comment]
@chiomaT looks good , why is the popup not showing on your screen 🤔  ? 

Since @franklinekoh has already been assigned to this , If you are passionate in completing this one , I encourage you to collaberate and work and finish it up :) .
@franklinekoh is very nice with collaberating (from my experience) just to ensure that you both don't end up duplicating the work.

For eg : 4 things listed in the issue desc pick 2 -2 each one of you sleek if it sounds good to your ears 👂 .

**Comment by chiomaT** [comment]
that's okay I can collaborate with @franklinekoh on this.
