### ISSUE TITLE
[mesheryctl] Improve `pattern list` Error Message

### ISSUE THREAD

**Issue by Ebi27** [meshery/meshery#6497]
#### Current Behavior
The mesheryctl pattern list error response currently displays as ;

```
➜  meshery git:(master) ✗ mesheryctl pattern list
Error: Get "http://localhost:9081/api/pattern": dial tcp [::1]:9081: connect: connection refused
➜  meshery git:(master) ✗
```
#### Expected Behavior
The mesheryctl pattern list error response should be “Unable to reach Meshery Server at ….. Please confirm that Meshery Server is available.”

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Ebi27** [comment]
Thank you. I'll be sure to do that.

**Comment by leecalcote** [comment]
Checking in... how are things progressing?

**Comment by Ebi27** [comment]
Struggling a bit with understanding and navigating the entire code base to a point where I figure out where my target error is coming from, but I'm spending some time tracking each function to determine it's output and just taking time to learn while at it.

**Comment by Ebi27** [comment]
Please leave this particular issue to me. I'll keep trying until I get It.

**Comment by ayushthe1** [comment]
hey @leecalcote ,i found out that the codeline which returns the error (and needs to be changed) is [this](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/pattern/list.go#:~:text=(req)-,if%20err%20!%3D%20nil%20%7B,return%20err,-%7D). 
Would it be a good idea to replace it with something like : 
```
res, err := client.Do(req)
if err != nil {
	return errors.New("Unable to reach Meshery Server at port 9081. 
               Please make sure that meshery is running by using command 'mesheryctl system start' ")
```

**Comment by leecalcote** [comment]
@ayushthe1, yes, that's pretty close, however:

1. The port # should not be hardcoded, but taken from mesheryctl's central config/struct.
2. Always capitalize Meshery.
3. Not `system start`, but `system status` is how you verify if Meshery is running.
4. Don't say "Please", even though it is polite, it's inappropriate tone.
5. First suggest `system check`, which is what I was telling you previously, not `system start`

**Comment by Ebi27** [comment]
Hey @ayusha and @leecalcote 

I actually already did this back in december and came up with this 
```
res, err := client.Do(req)
		if err != nil {
    return fmt.Errorf("Unable to reach Meshery Server at %s. Please confirm that Meshery Server is available", mctlCfg.GetBaseMesheryURL())
}
```
however, I think it's something with my system. I'm unable to run everything needed to test it. That's why I haven't committed it yet.

**Comment by Ebi27** [comment]
I also was going to try defining a new error message as a constant and using it in the return statement like this;
```

const mesheryServerError = "Unable to reach Meshery Server at ….. Please confirm that Meshery Server is available"

if err != nil {
    return fmt.Errorf(mesheryServerError)
}
```

But again, I've been unable to test them out due to my laptop shutting when I try to run the needed softwares.

**Comment by ayushthe1** [comment]
Thanks for the feedback @leecalcote . Is this a correct way .

```
res, err := client.Do(req)
		if err != nil {
			return errors.Errorf("Unable to reach MESHERY server at %s. Verify your environment's readiness for a MESHERY deployment by running `mesheryctl system check`. ", mctlCfg.GetBaseMesheryURL())
```

**Comment by leecalcote** [comment]
Only capitalize the “M” in Meshery. Don’t yell at users.

**Comment by ayushthe1** [comment]
> Only capitalize the “M” in Meshery. Don’t yell at users. 

Ok ,I will do that . Should I open a pr with these changes?

**Comment by leecalcote** [comment]
Someone should do something.

**Comment by Ebi27** [comment]
I'm on it.

**Comment by ayushthe1** [comment]
Done @leecalcote :+1: . Could you please review it.

**Comment by Nikhil-Ladha** [comment]
I see that @Ebi27 has been assigned the issue, but didn't make a PR for a long time and the issue went stale.
Thus, @ayushthe1 takes over from there. I am considering the PR made by @ayushthe1 , hope you understand the situation here @Ebi27
