### ISSUE TITLE
[Server] Remote provider session not expiring on logout

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6503]
#### Current Behavior
When a user logs out of the Meshery remote provider, they seem to go in circles with the session remaining active.

_Note: PROVIDER_BASE_URL is set to staging-meshery.layer5.io._

Related issue: https://github.com/meshery/meshery/issues/1442

#### Expected Behavior
Session is expired.

#### Screenshots/Logs

https://user-images.githubusercontent.com/7570704/200410288-2db20106-84ef-40f1-9aa7-5679e0679f63.mov

#### Environment

- **Host OS:** Mac 
- **Browser**: Safari

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@theBeginner86, you might want to have a look at this.

**Comment by theBeginner86** [comment]
> @theBeginner86, you might want to have a look at this.

Sure, I'll fix this.
