### ISSUE TITLE
The search bar is colliding with the Navbar from 768px to 988px

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery#6512]
#### Current Behavior

The search bar is colliding with the Navbar from 768px to 988px

#### Expected Behavior

Give a margin to the Search bar (From the top)

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/67385503/200907665-aa51fc20-deb0-4860-acea-d46779b08591.png)

#### Environment

- **Host OS:** Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue.

**Comment by chiomaT** [comment]
@UtkarshMishra12 I would like to fix this issue.
