### ISSUE TITLE
[UI] 'Upload kubeconfig' label colliding with file name in input

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#6513]
#### Current Behavior
When the input is selected
<img width="547" alt="image" src="https://user-images.githubusercontent.com/76054921/201073289-0a6bbccf-110d-445b-8c66-7b239c422683.png">

When the input is not in focus
<img width="629" alt="image" src="https://user-images.githubusercontent.com/76054921/201073432-5d9a488e-c810-4feb-b0b2-264ffad58e05.png">

#### Desired Behavior
Input label should not collide with file name

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac
- Meshery Server Version: stable-v0.6.22
- Meshery Client Version: stable-v0.6.22
- Platform: Docker

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by abdullah1308** [comment]
@leecalcote Can I work on this ?

**Comment by leecalcote** [comment]
Thank you for filing this issue, @abdullah1308 💪

**Comment by leecalcote** [comment]
@abdullah1308 How's it coming along?

**Comment by sidmohanty11** [comment]
Hey @leecalcote and @abdullah1308 do you mind if I take this up?

**Comment by leecalcote** [comment]
A bit of collaboration goes a long way, yes, that'd be great, @sidmohanty11

**Comment by sidmohanty11** [comment]
@leecalcote Thanks a lot. While exploring the codebase a bit, I found out some approaches that I thought about sharing and asking what should be our approach from the UI standpoint?

1. By adding InputLabelProps={{ shrink: true }} to the TextField, it will work as expected.
```jsx
// ui/components/MeshConfigComponent.js - line 900
<TextField
                id="k8sfileLabelText"
                name="k8sfileLabelText"
                className={classes.fileLabelText}
                label="Upload kubeconfig"
                variant="outlined"
                fullWidth
                onClick={() => {
                  document.querySelector("#k8sfile")?.click();
                }}
                margin="normal"
                InputProps={{
                  readOnly : true,
                  endAdornment : (
                    <InputAdornment position="end">
                      <CloudUploadIcon />
                    </InputAdornment>
                  ),
                }}
                InputLabelProps={{
                  shrink: true,
                }}
              />
```

but when there will be no value it will still be shrunken.
![Screenshot 2022-11-18 at 2 40 23 AM](https://user-images.githubusercontent.com/73601258/202569468-9a008749-eaed-4d8d-9705-b6676fd4ee3c.png)

2. I found that most of the state (formdata) is uncontrolled, so we could try to control it while handling modal and with that we can have a state which can help us achieve an accurate shrinking. But I am not sure, if it's required.

3. We could add a placeholder to the textfield component, it will work as expected while not changing the UI completely,
![Screenshot 2022-11-18 at 3 36 33 AM](https://user-images.githubusercontent.com/73601258/202570424-01ccc3fb-4880-4bfd-bba9-122d869ba496.png)

Please let me know your thoughts. Thank you

**Comment by abdullah1308** [comment]
> @abdullah1308 How's it coming along?

Sorry, I was busy with examinations and unable to work on it. 

@sidmohanty11 I like number 3. Removing the label entirely and having only the placeholder would look clean as well.

**Comment by sidmohanty11** [comment]
@abdullah1308 can i make a PR based on that approach?

**Comment by abdullah1308** [comment]
> @abdullah1308 can i make a PR based on that approach?

@sidmohanty11 yep, go ahead.

**Comment by leecalcote** [comment]
// @Nikhil-Ladha fyi

**Comment by partik03** [comment]
@leecalcote I created my pr for this issue
