### ISSUE TITLE
[UI][Navigator] Chevron disabled in navigator in normal mode as well

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#6528]
#### Current Behavior
The chevron in the navigator is disabled in normal mode as well, this leaves the drawer open-close function disabled.

#### Desired Behavior
Chevron should only be disabled in playground mode.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Uh-oh.

**Comment by leecalcote** [comment]
Is someone working on this?

**Comment by warunicorn19** [comment]
@Abhishek-kumar09 has already fixed it.
