### ISSUE TITLE
[Server] Misspelling in error logs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6540]
#### Current Behavior

<img width="996" alt="Screen Shot 2022-11-15 at 10 17 40 PM" src="https://user-images.githubusercontent.com/7570704/202083105-c65d7e6c-d49f-4a74-b86e-52400fa743bd.png">

#### Screenshots/Logs
Other examples have been sent in Slack.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by paularah** [comment]
@gr455 can I take on this? it's good first issue

**Comment by gr455** [comment]
> @gr455 can I take on this? it's good first issue

Absolutely, thanks!
