### ISSUE TITLE
[Docs] Each adapter page should source the adapter version number from datafile/collection

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6542]
#### Current State
The Meshery Adapter version numbers are out of date and statically defined.

e.g. https://docs.meshery.io/service-meshes/adapters/istio

#### Desired State
Each adapter page should source the adapter version number from datafile/collection

#### Acceptance Criteria
1. All Adapter pages source their version number dynamically.
2. The [main Adapters page](https://docs.meshery.io/concepts/architecture/adapters) sources supported service mesh version numbers dynamically.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
// @asubedy

**Comment by ayushthe1** [comment]
hey @leecalcote ,can i work on this issue ?

**Comment by leecalcote** [comment]
Yes. Sounds great, @ayushthe1. 👍

**Comment by AgniveshChaubey** [comment]
Hey @leecalcote @ayushthe1, I am looking for my first contribution to Layer5. If possible, can I be a part of this issue someway?

**Comment by ayushthe1** [comment]
hey @leecalcote ,where do i find datafile/collection ?

**Comment by leecalcote** [comment]
@ayushthe1 you'll find them here - https://github.com/meshery/meshery/tree/master/docs/_adapters. This data isn't being updated, though, but should be updated along with its sibling data in https://github.com/meshery/meshery/tree/master/docs/_compatibility

@asubedy will you see that the adapters collection is being updated, too?

**Comment by leecalcote** [comment]
@ayushthe1 still working on this? Need help?

**Comment by ayushthe1** [comment]
hey @leecalcote  ,i have setup the documentation development server locally but having trouble understanding what to do.

I can see that in each adapter page's metadata eg: [istio.md](https://github.com/meshery/meshery/blob/master/docs/_adapters/istio/istio.md) ,adapter version has been defined statically which is out of date. Here [/compatibility/meshery-istio](https://github.com/meshery/meshery/tree/master/docs/_compatibility/meshery-istio) ,we have many files regarding istio adapter which contains the various compatibility information about it. 

Out of all these files, [12-01-2022-20-52-12_c14a63f8.md](https://github.com/meshery/meshery/blob/master/docs/_compatibility/meshery-istio/12-01-2022-20-52-12_c14a63f8.md#:~:text=edge-,v0.6.30,-minikube) is the latest file in the folder which has `meshery-server-version = v0.6.30`.
So ,i guess the task here is to make `adapter_version` in  [istio.md](https://github.com/meshery/meshery/blob/master/docs/_adapters/istio/istio.md) take the value == `meshery-server-version ` from the latest file uploaded ;dynamically; (like currently from latest file mentioned above the value assigned would be v0.6.30).

can you please suggest how this can be done .

**Comment by leecalcote** [comment]
Close. That’s not quite the value assignment that is needed. I’ll let you sync with @asubedy. Good write up, @ayushthe1

**Comment by leecalcote** [comment]
@AgniveshChaubey, I missed you inquiry above. I think collaboration is helpful, although, I’ll let @ayushthe1 respond. 

@asubedy can point you to any number of other open issues, @AgniveshChaubey. See the “help wanted” issue label (for all our GitHub orgs).

**Comment by ayushthe1** [comment]
Thanks for the review @leecalcote .I would love to collaborate here but i think this issue is very small to do that .
Looking forward to more discussions on this @asubedy . :+1:

**Comment by asubedy** [comment]
Hi @ayushthe1 , you are close but `meshery-server-version` is not what needs to be dynamically updated on the adapters page. 
So when you go through those files inside [/compatibility/meshery-istio](https://github.com/meshery/meshery/tree/master/docs/_compatibility/meshery-istio) there is a field called `meshery-component-version`. This is the version that needs to be shown dynamically on the adapters page. 

You might face one issue here that there are files that have `meshery-component-version` value as `edge` this is called edge version and some few files that have a actual version specified i.e (v0.5.22.. etc) this is a stable version. So your task would be to filter the latest stable file that have these version mentioned from the `/compatibility/meshery-istio` and then take the `meshery-component-version` and use this value on the adapters page.

You can refer to [this code](https://github.com/meshery/meshery/blob/416427ee7447b72b6587190395d289f12dbc80af/docs/pages/project/compatibility_matrix/compatibility.md?plain=1#L276), on how to get the latest stable version of each adapter.

**Comment by ayushthe1** [comment]
hey @leecalcote ,i made a pr for this issue .Could you please review it .
Also ,currently i just made the change for istio adapter and it was working correctly on my local server .Once you approve this ,i will add more commits for changes in all other adapters.
