### ISSUE TITLE
Type errors in code base.

### ISSUE THREAD

**Issue by Udit-takkar** [meshery/meshery#6553]
#### Current Behavior

There are many components with type errors like CatalogFilter in /components/MesheryPatterns.js.
Property 'hideCatalog' is missing in type.  we can make this property optionals using proptypes which should fix this.

similarly there are few more components with similar issue.

#### Expected Behavior
There should not be any type error in the code base.

#### Screenshots/Logs
<img width="820" alt="Screenshot 2022-11-20 at 1 41 20 PM" src="https://user-images.githubusercontent.com/53316345/202892175-0aab9b96-05ae-4210-aaeb-25304cf95d17.png">

#### Environment

- **Host OS:** Mac
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

**Comment by Udit-takkar** [comment]
@leecalcote   i would like to work on this if you can assign me.

**Comment by leecalcote** [comment]
Thanks for filling this, @Udit-takkar. That’d be great.
