### ISSUE TITLE
Typo error in Meshery documentation

### ISSUE THREAD

**Issue by AgniveshChaubey** [meshery/meshery#6554]
#### Current State
In this [section](https://github.com/meshery/meshery/blob/master/docs/pages/installation/quick-start.md#select-a-provide), there is a typo in the line - Select from the list of Providers in order to login to Meshery. Authenticate with your chosen your Provider.

#### Desired State
The sentence should be - Select from the list of Providers in order to login to Meshery. Authenticate with your chosen Provider.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
![Screenshot (21)](https://user-images.githubusercontent.com/113545196/202919845-1008fe2e-c649-4f68-a061-a15df991d36b.png)

**Comment by AgniveshChaubey** [comment]
I wanna work take over this issue.

**Comment by asubedy** [comment]
Hi @AgniveshChaubey , thank you for raising this issue, could you please add a proper title and a screenshot of the issue that would be helpful

**Comment by AgniveshChaubey** [comment]
> Hi @AgniveshChaubey , thank you for raising this issue, could you please add a proper title and a screenshot of the issue that would be helpful

Yeah, sure!

**Comment by AgniveshChaubey** [comment]
hey @asubedy, can you please look over the pull request I have made?

**Comment by leecalcote** [comment]
> hey @asubedy, can you please look over the pull request I have made?

Please link your PR.

**Comment by leecalcote** [comment]
@AgniveshChaubey do you have a link to your PR?

**Comment by AgniveshChaubey** [comment]
> @AgniveshChaubey do you have a link to your PR?

The above is the one I am referring to! Sorry for the late reply; I was off the court due to semester exams.

**Comment by AgniveshChaubey** [comment]
.
