### ISSUE TITLE
Change the icon for clearing the notification.

### ISSUE THREAD

**Issue by Krishna2323** [meshery/meshery#6560]
#### Current Behavior
Change the icon for clearing the notification.
![Screenshot 2022-11-22 193914](https://user-images.githubusercontent.com/85894871/203345080-b11c4d00-e085-4e38-b82e-f7bce8fd31c8.png)

#### Desired Behavior
![Screenshot 2022-11-22 194322](https://user-images.githubusercontent.com/85894871/203345101-43adf945-78ed-44c8-bffd-99cd2bdafb7c.png)

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by suhail34** [comment]
Hey I would like to work on this issue to get started with the project

**Comment by leecalcote** [comment]
Sounds great, @suhail34. When you engage here, please know what Meshery UI favors use of SVGs vs use of built-in MUI icons/fontawesome/other. This is to help guarantee the icons scale on zoom in browsers like Safari. // @asubedy

**Comment by suhail34** [comment]
I think using @fortawesome/react-fontawesome as it has wide collection of svg icons according to this [blog](https://nextjsdev.com/svg-icons-libraries-that-you-can-use-in-reactjs-andnextjs-projects). I also tested it using lambdatest on safari browser too and it was working

**Comment by leecalcote** [comment]
@suhail34 apologies for leading you astray in terms of the icons used. The project has shifted to direct use of SVGs now.

**Comment by suhail34** [comment]
So i need to use svgs now and no built-in libraries needed

**Comment by leecalcote** [comment]
@suhail34, yes, correct.

**Comment by leecalcote** [comment]
@suhail34, like this - https://github.com/meshery/meshery/pull/6578/files. In fact, we need all icons replace in this manner.
