### ISSUE TITLE
[UI] [Safari] SVGs are not scaling in various plaes in UI

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#6564]
#### Current Behavior
SVGs are not scaling in various places in UI such as:
1. Design configurator
2. I icon in the navigator.
3. icons inside buttons and many more

#### Desired Behavior
SVG's should be scaled in every browser.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
From Designs page: 
<img width="1626" alt="Screenshot 2022-11-24 at 11 58 33 AM" src="https://user-images.githubusercontent.com/7570704/203844692-1116370d-09ef-4c3b-a7e3-344699993ece.png">

**Comment by Chadha93** [comment]
@Abhishek-kumar09 This is complete wrt to your recent update right?
