### ISSUE TITLE
[Event] Change Kubernetes component registration event information

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6566]
#### Current Behavior
When Meshery Server generates and registers components for a connected Kubernetes cluster, it subsequently sends an event for display in the Notification Center (see screenshot).

<img width="443" alt="Screenshot 2022-11-23 at 5 59 28 PM" src="https://user-images.githubusercontent.com/7570704/203665831-61568feb-ce7d-4183-b3af-125e1adfe558.png">

#### Desired Behavior
1. Send / show users the context name, not the cluster ID. 
1. Spell out "Kubernetes" properly. Don't abbreviate.
1. Provide details of notification in the DETAILS section, like 1) the total number of components registered, 2)  the context ID, 3) the version of Kubernetes (e.g v1.25.3), 4) whether or not any of these components duplicate existing components in the registry. 

#### Implementation

All of this can be accomplished with Golang-only (not Meshery UI changes needed).

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by rghdrizzle** [comment]
Hey I would like to work on this . Can you tell me which file or folder does this issue exist in?

**Comment by karnatisrinivas** [comment]
Hello @leecalcote, I would like to work on this. (if this is unassigned)

**Comment by leecalcote** [comment]
@rghdrizzle @karnatisrinivas I'll assign both of you, understanding that you might collaborate or that one of you might not be able to complete it. 

Here, let me google that for you - https://github.com/meshery/meshery/blob/b72d8ee8d8a75d1865aa0b7b8af3a586f5c2810a/server/models/k8s_components_registration.go#L80

**Comment by leecalcote** [comment]
@rghdrizzle @karnatisrinivas progress? Any help needed?

**Comment by leecalcote** [comment]
@rghdrizzle @karnatisrinivas not hearing back from you by end of day on Tuesday, let's unassign you so that other contributors can carry this forward.

**Comment by rghdrizzle** [comment]
Hey @leecalcote sorry for not answering , I was having issues with running the server locally , anyways how do we reproduce that notification ?

**Comment by leecalcote** [comment]
@rghdrizzle connect Meshery to Kubernetes.

**Comment by karnatisrinivas** [comment]
Hello @leecalcote , I have reproduced the issue and tried to fix the Ctx.ID used. But I wasn't able to fix the issue. Unassigning me so that @rghdrizzle or other contributors can go forward with it.

**Comment by leecalcote** [comment]
Thanks, @karnatisrinivas, @rghdrizzle. I’ll fix it.

**Comment by suhail34** [comment]
I would like to work on this issue can you help me out to get started with the issue @leecalcote

**Comment by leecalcote** [comment]
@suhail34 its as simple as this - https://github.com/meshery/meshery/issues/6566#issuecomment-1326805132. PR it, at-will.

**Comment by EleisonC** [comment]
Hey @leecalcote could you assign me to this issue

**Comment by EleisonC** [comment]
Hey @leecalcote I think this was fixed by @Chadha93

**Comment by leecalcote** [comment]
Oooh, assuming that’s right, @Chadha93, I’ll close out the issue. Thank you much , @EleisonC.
