### ISSUE TITLE
Windows instructions to be added in contributing docs

### ISSUE THREAD

**Issue by rghdrizzle** [meshery/meshery#6592]
#### Current State
Since there are problems while running the application locally in windows by following the instructions mentioned in contribution guide , It would be helpful if there are instructions for setting up in windows  .  

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
@leecalcote I think this issue has already been solved (we have special instructions for running it on windows devices). [PR](https://github.com/meshery/meshery/pull/6764)

**Comment by leecalcote** [comment]
Thank you for confirming, @UtkarshMishra12
