### ISSUE TITLE
[Docs] Add FOSSA badge to repo readme

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6596]
#### Current State
Open source license scanning is being performed by FOSSA on the Meshery GitHub org.

#### Desired State
Display the FOSSA badge with scan result status adjacent to other badges in readme.md.

This badge should look like all the other badges (similar styling).

Relevant:
- https://github.com/badges/shields/issues/1529
- How to create a FOSSA badge - https://docs.fossa.com/docs/quick-import#getting-a-badge-pull-request-githubcom-only
- https://badges.pages.dev/?q=fossa
- Meshery Report - https://app.fossa.com/reports/a433093d-5e24-45d6-8063-1ce2a62c205a

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by jaypee-0** [comment]
I’ll like to work on this 
Twitter - @Jay9ee_

**Comment by leecalcote** [comment]
Sounds real good, @jaypee-0 👍

**Comment by hs05june** [comment]
Hey @leecalcote there hasn't been any activity on this issue. Can I work upon it.
