### ISSUE TITLE
[CD] Transition playground deployment VM-based to K8s-based

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6610]
#### Current Behavior
Meshery Playground deployments are VM-based.

#### Desired Behavior
Transition Meshery Playground deployments to k8s-based.

#### Implementation
1. Using GH Action - https://github.com/marketplace/actions/deploy-to-kubernetes-cluster, displace existing step - https://github.com/meshery/meshery/blob/265c3191d81f48e78d6563e33be0773ca40999c3/.github/workflows/deploy-meshery-playground.yml#L29
2. Update or remove org-level secrets for VM-based deployment.

#### Acceptance Tests
1. A new Playground version is deployed with each new, stable channel release of Meshery.
2. The [GitHub Process document](https://docs.google.com/document/d/1FzX-C_xy9hZ3Eu9dcCE0unhFV5LRUrb5YLn_MGYuG6Y/edit?ts=6039100f) has relevant secret names documented and their purpose listed.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by RishiKumarRay** [comment]
@leecalcote @Revolyssup can i go for this ?

**Comment by Revolyssup** [comment]
> i go for this ?

This issue has already been assigned and being actively worked on. I suggest you take up another. There are a whole bunch of open issues.
