### ISSUE TITLE
[Docs] Add details of the two GitHub Actions to Meshery Docs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6611]
#### Current State
https://docs.meshery.io is missing documentation of these actions and how they work.

1. https://github.com/layer5io/meshery-smp-action
2. https://github.com/layer5io/meshery-smi-conformance-action

#### Desired State
Use https://layer5.io/blog/service-mesh-specifications/pipelining-service-mesh-specifications as reference.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by BabyElias** [comment]
Hey! Can I work on this issue?
Quick question :<br> Does this information needs to be added on their respective pages<br> https://docs.meshery.io/guides/performance-management<br>https://docs.meshery.io/functionality/service-mesh-interface
OR <br>Add a separate section for Github Actions within Functionality section.

**Comment by mohit-marathe** [comment]
Hello @leecalcote , can I work on this issue?

**Comment by leecalcote** [comment]
@BabyElias oh, no. I completely missed your message. My apologies.

@mohit-marathe, yes, that'd be great.

**Comment by mohit-marathe** [comment]
@leecalcote, I have made a PR here:https://github.com/meshery/meshery/pull/7110. Can you please review it?
