### ISSUE TITLE
[CI] Setup GitHub Action to tweet when `issue/tweet` label is applied

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6612]
#### Current Behavior
Many new and existing issues can benefit from being posted on Twitter for broader reach of potential contributors and for recognizing the efforts of existing contributors.

#### Desired Behavior
1. Upon application of the `issue/tweet` label, tweet link to issue from [mesheryio](https://twitter.com/mesheryio) account.

#### Implementation
1. Use https://github.com/marketplace/actions/send-tweet-action.
    1. `status:` should include the title of the [issue | pull request] - link-to-issue-or-pr #opensource 
    2. e.g. "[CI] Setup GitHub Action to tweet when `issue/tweet` label is applied - https://github.com/meshery/meshery/issues/6612 #opensource"
1. Request or create each necessary GitHub secret at the organization level.

#### Acceptance Tests
1. All `meshery` repos have `issue/tweet` label, which has color of #eee.
1. The [GitHub Process document](https://docs.google.com/document/d/1FzX-C_xy9hZ3Eu9dcCE0unhFV5LRUrb5YLn_MGYuG6Y/edit) is updated.
1. Label should work on both issues and pull requests.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by PratikforCoding** [comment]
@leecalcote I will learn about github action and give it a try.

**Comment by leecalcote** [comment]
@PratikforCoding, that sounds most excellent. Let's leave this unassigned until such time as you're feeling quite comfortable. Do be sure to attend the Meshery CI meeting every other week on Thursdays. You'll find helping hands readily available there.

**Comment by PratikforCoding** [comment]
yeah sure @leecalcote , I have started learning github action, if I get comfortable I will try this otherwise if someone approaches I will learn form him.

**Comment by RishiKumarRay** [comment]
@leecalcote can i go for his ? I have done some similar to conifguring tweet for a open source project earlier

**Comment by PratikforCoding** [comment]
Hey @RishiKumarRay I wanna take some time and try it. After that you can do that.

**Comment by leecalcote** [comment]
@PratikforCoding the point of not assigning the issue to you until you're ready is to prevent the issue from being squatted on and not progressing. There are three or four of these same issues open across our orgs. Yes, @RishiKumarRay go for it.

**Comment by RishiKumarRay** [comment]
@leecalcote Sure , Please assign it to me.

**Comment by leecalcote** [comment]
@RishiKumarRay, sounds good. We have a high number of well-intended contributors to sign up for issues and are woefully under-qualified to complete them. We want to set each contributor up for success. Prior to receiving assignment, will you please outline your proposal solution?

**Comment by RishiKumarRay** [comment]
So As I did earlier for another OS Project , Firstly we will be needing to create a application through which we can get the access keys , then we just need to add the keys to org level so that you can use this in other projects as well, Now once this is done we just need to add this action in our template and add a condition by which it will check the label and once it verifies the label. This Will run and tweet automatically to whatever message we want (We can customize the message ).

**Comment by RishiKumarRay** [comment]
@leecalcote Here's how i completed a setup just now 
![Screenshot from 2022-12-02 20-10-30](https://user-images.githubusercontent.com/87641376/205318089-648fd1f2-d416-4a2a-b741-b0b5c07ec584.png)

**Comment by RishiKumarRay** [comment]
@leecalcote  I believe the action you provided has some errors , it is not working so we can try with this action

**Comment by gopivaibhav** [comment]
Hey @leecalcote I explored about this issue and got some result but I didn't tweet as I don't have twitter details of [mesheryio](https://twitter.com/mesheryio).

Results after I have added Github Actions :
- Before Adding the label of "issue/tweet" -
![Screenshot from 2022-12-12 16-24-55](https://user-images.githubusercontent.com/78922463/207028926-96612d6b-edde-44ab-b076-f4acfe92d3a6.png)
- After adding the label -
![Screenshot from 2022-12-12 16-25-41](https://user-images.githubusercontent.com/78922463/207028974-af6e159f-e638-4d9a-ad00-5bb86a885766.png)

Feel free to verify the [issue](https://github.com/gopivaibhav/SPARK-website/issues/20) I have created to test this feature

If this sounded good, then please assign me this issue to implement this :) 
Thank you!!

**Comment by gopivaibhav** [comment]
> If this sounded good, then please assign me this issue to implement this :) Thank you!!

Greetings @leecalcote Can you please let me know if I am missing something with this issue so that I can change it out and start working on it?
Thank you!!

**Comment by siddhikhapare** [comment]
@leecalcote  I have tried to resolve this issue. Please go through it once.

**Comment by leecalcote** [comment]
@gopivaibhav @siddhikhapare @Revolyssup, please add this issue to the agenda of today's Meshery CI meeting.

**Comment by siddhikhapare** [comment]
Sure

**Comment by leecalcote** [comment]
Here is suggested text for the content of the tweets:

```
Help wanted: "<issue title>" - <issue link> #opensource
```

**Comment by leecalcote** [comment]
@RishiKumarRay, you've left some great comments above. I wasn't able to keep up with various activities, including those on this issue. In that time, @gopivaibhav and @siddhikhapare have both opened PRs. Will you take a moment to review those? Let's ensure that each of the orgs that the Meshery community stewards (https://meshery.io/handbook/repository-overview) has a copy of the #6770 workflow.

**Comment by siddhikhapare** [comment]
@leecalcote  I am going to unassign myself from this issue because I have not access my own twitter api keys and tokens to test my setup. I have faced issue of adding my phone number to create developer twitter account.   I guess  @gopivaibhav have resolved this issue. Thank you.

**Comment by siddhikhapare** [comment]
I apologize for doing this but there is no point to proceed further if I can't  test my work
