### ISSUE TITLE
[CI] User Preferences and User Settings e2e tests failing

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6618]
#### Current Behavior
Example - https://github.com/meshery/meshery/actions/runs/3603563645/jobs/6072027411#step:14:502

```
✖  e2e/settings_spec.js 
✖  e2e/userpreference_spec.js
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@theBeginner86 the user preferences plugin is failing to load in Meshery UI, causing a 404.

**Comment by theBeginner86** [comment]
@leecalcote @gr455 

I'm able to see the user_prefs extension. 🤔
I had a fresh build in which packages for `v0.6.31-1` were downloaded from the meshery-extension-packages repo

![Screenshot 2022-12-03 at 1 51 45 PM](https://user-images.githubusercontent.com/73700530/205431683-fac5179a-8cfc-4c71-9d34-6de0dc09d94a.png)
