### ISSUE TITLE
Link to verify email address does not work (not clickable)

### ISSUE THREAD

**Issue by bluedog13** [meshery/meshery#6619]
#### Current Behavior

When you signup for an account and are asked to verify the email via the link provided in the email, the link is not clickable.

#### Expected Behavior

Should be able to click on the link

#### Screenshots/Logs

<img width="726" alt="Screen Shot 2022-12-02 at 2 36 05 PM" src="https://user-images.githubusercontent.com/11997472/205381335-5adec280-730e-4cd4-abf4-6249e73bcfc6.png">

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you for raising this issue, @bluedog13!

**Comment by theBeginner86** [comment]
We're investigating now. Do you mind sharing which mail client you're using (and operating system would be helpful). Thanks, @bluedog13!

**Comment by leecalcote** [comment]
Let's consider inclusion of the raw URL as an address to copy/paste in the event the button isn't clickable.

**Comment by bluedog13** [comment]
I am using Hotmail in Chrome browser on Mac. I also tried using the Outlook app on Android - but that also resulted in the same behavior.

**Comment by leecalcote** [comment]
It would appear that Hotmail, specifically, has a bone to pick with these verification emails. Please do click "It's not junk":

![Untitled 2](https://user-images.githubusercontent.com/7570704/205458084-0c0cb309-b199-417f-b905-e65411d77534.png)

Given some quick work by @Nikhil-Ladha and @theBeginner86, a raw URL is now included in the verification emails:

<img width="805" alt="Screenshot 2022-12-03 at 1 04 54 PM" src="https://user-images.githubusercontent.com/7570704/205457662-ce79c72f-2119-443b-bd26-3b8f47503951.png">

If you don't mind resending your user account's verification email one more time, you should be good to go from there. Our apologies for this hassle. Thanks much for reporting this issue, @bluedog13. This is most helpful. 👍

**Comment by bluedog13** [comment]
I am not able to find the page where I can ask the verification mail to be sent again.

**Comment by theBeginner86** [comment]
> I am not able to find the page where I can ask the verification mail to be sent again.

https://meshery.meshery.io/verification

**Comment by bluedog13** [comment]
Thanks. Both the button and the link are now clickable and I was able to click on them.

Unfortunately, I see the below error - not sure if it's part of the same above ticket or not. 

<img width="1792" alt="Screen Shot 2022-12-06 at 2 56 42 PM" src="https://user-images.githubusercontent.com/11997472/206021340-c5bec15c-2274-442d-9dcc-8f793407f217.png">

**Comment by bluedog13** [comment]
Worked the next time.  I was able to verify.  Thanks.

**Comment by bluedog13** [comment]
But I see more errors after I login as well.  In case if this helps for other issues or tickets

<img width="1684" alt="Screen Shot 2022-12-06 at 3 00 01 PM" src="https://user-images.githubusercontent.com/11997472/206021809-be8b111a-03f1-4433-9298-5dd1c893edd4.png">
