### ISSUE TITLE
[mesheryctl] Improve debugging logs

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#6628]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

When mesheryctl fails to perform a particular action then it doesn't provide helpful debugging logs to overcome the challenges with the Meshery setup.

Examples used in this [issue description](https://github.com/meshery/meshery/issues/6621#issue-1473481252).

```
mesheryctl system login                         
authentication failed: Get "http://localhost:31611/api/providers": dial tcp [::1]:31611: connect: connection refused
```

#### Desired Behavior

`mesheryctl` should improve logs for seamless Meshery setup for new users.

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by amit-62** [comment]
Hello @theBeginner86 I was going through this issue. Do we have to improve log only for `mesheryctl system login`.

**Comment by theBeginner86** [comment]
> Hello @theBeginner86 I was going through this issue. Do we have to improve log only for `mesheryctl system login`.

Yes. That is one of the examples.
The basic idea is to improve the debug log and give intuitive logs so users can understand the issue for the failed response. Like in the above example its not very clear of how to fix that `connection refused` problem.

**Comment by amit-62** [comment]
Hello @theBeginner86 I want to work on this issue. I want to learn more about the issue and how can I solve it.
Thank you.

**Comment by theBeginner86** [comment]
> Hello @theBeginner86 I want to work on this issue. I want to learn more about the issue and how can I solve it.
> Thank you.

Great! 
Joining the [Meshery development call](https://meshery.io/community/calendar) is the best way to get answers to your questions. Moreover, Meshery has a [discussion forum](https://discuss.meshery.io) where you can ask your doubts.

**Comment by ayushthe1** [comment]
i am working on this issue.

**Comment by amit-62** [comment]
Hii @ayushthe1 I am still working on this issue.

**Comment by leecalcote** [comment]
@amit-62, it's been a month. Giddy-up. Let's move this along.

**Comment by amit-62** [comment]
I am having hard time running mesheryctl command. Due to docker daemon.
