### ISSUE TITLE
[Docs] Improve Setup Installation 

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#6629]
#### Current State

Currently, meshery docs don't tackle all the different use cases that a user might get into while starting Meshery for the first time. Some challenges include network challenges with the K8s cluster of `minikube` and `kind` which require loadbalancer setup for the Meshery Services to be exposed successfully.

#### Desired State

Improve Meshery Docs for better setup instructions. 
Eg: Improve Meshery installation with K8s clusters of type [Minikube](https://docs.meshery.io/installation/platforms/minikube) and [KinD](https://docs.meshery.io/installation/platforms/kind)

Related to: https://github.com/meshery/meshery/issues/6621

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Ideally, example / suggested use of `mesherctl system dashboard`, too.

**Comment by gurpreet-legend** [comment]
Can I work on this? This might as well help me understand the documentation more :)

**Comment by leecalcote** [comment]
> Can I work on this? This might as well help me understand the documentation more :)

Two birds, one stone. 🙂
