### ISSUE TITLE
[UI] Configurations navigation icon is not having arrow and fix tooltip position 

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#6636]
#### Current Behavior
1. The new configuration icon in the Navigator is not showing a dropdown arrow on hover like other items under navigator.
2. The tooltip should not overlap with the navigator.
3. See the video for issue details:

https://user-images.githubusercontent.com/65453826/205725451-c378e2c2-2352-4963-a624-b59f4d8da8bf.mp4

#### Desired Behavior
Make the behavior consistent like other icons.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by hs05june** [comment]
Please Assign this to me

**Comment by hs05june** [comment]
Please assign this issue to me.

**Comment by hs05june** [comment]
[Screencast from 06-12-22 10:10:25 PM IST.webm](https://user-images.githubusercontent.com/103871275/205973281-d3f2cc1b-8555-4eb2-a984-9880c0384b2b.webm)
Should I make a PR?
