### ISSUE TITLE
[Docs] Replace Google Doc link with link to web page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6653]
#### Current State
The Layer5 repository overview doc (https://docs.google.com/document/d/1brtiJhdzal_O6NBZU_JQXiBff2InNtmgL_G1JgAiZtk/edit#) is linked to in various places (readmes, docs, and so on).

#### Desired State
1. Replace the Gdoc link with this web page link - https://layer5.io/community/handbook/repository-overview.
2. Remove "Layer5" in the link description, changing it to "Layer5 Repository Overview".

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by BabyElias** [comment]
Hey! Can I work on this issue?

**Comment by BabyElias** [comment]
Done with the required changes after going through all the mentioned repositories. @leecalcote
