### ISSUE TITLE
[UI] Create a MeshModel Registry explorer

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#6665]
#### Current Behavior

In order to explore available MeshModel components while debugging or some verification, users have to hit particular API endpoints to retrieve JSON
#### Desired Behavior

Create a MeshModel registry explorer from where we can navigate all available MeshModel components, policies as well as any entities that are added in the registry.
#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Vaani-pathariya** [comment]
can i work on this ??

**Comment by siddhikhapare** [comment]
@Revolyssup I would like to work on this issue but can you help me with some pointers?

**Comment by hamza-mohd** [comment]
Initial implementation complete.
