### ISSUE TITLE
[CI] Update ubuntu-latest to ubuntu-22

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#6666]
Currently, github actions workflows are issuing a warning that `ubuntu-latest` which is `ubuntu-20` will be deprecated.

```bash

Pull Request Labeler: .github#L1
ubuntu-latest workflows will use ubuntu-22.04 soon. For more details, see https://github.com/actions/runner-images/issues/6399
```

We will need to update `ubuntu-latest` to `ubuntu-22.04` across all projects that uses this image.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by acald-creator** [comment]
@StarTrooper08 Sure, this is a good first issue and easy task to work on.

**Comment by StarTrooper08** [comment]
Hey @acald-creator 
I've gone through a few meshery projects
And here are my observations

A list of workflows using ubuntu latest and a few action yml files are using ubuntu 18v(mentioned below)

Checked the following directory of the below projects
`.github/workflows`

1. meshery/meshery	
2. meshery/meshery.io
(label-commenter.yml uses ubuntu18.04)
3. meshery/meshery-operator
4. meshery/meshkit
5. meshery/meshery-istio   
6. meshery/meshery-linkerd
7. meshery/scoop-bucket
(label-commenter.yml uses ubuntu-18.04)

And meshery/meshsync project GH workflow yml files are up-to-date with ubuntu-22.04


So do we have to make changes in GH workflows that are using ubuntu-18.04?

**Comment by acald-creator** [comment]
@StarTrooper08 Any of the workflows that currently uses `ubuntu-latest` (`ubuntu-20.04`) or lower such as `ubuntu 18.04` will needs to be updated to `ubuntu-22.04`

**Comment by StarTrooper08** [comment]
Hey, @acald-creator I've made the required changes in meshery/meshery GitHub actions workflows. Can you please review it.

Now I'm working on Meshery.io repository, will link PR to this issue here as I complete my work

**Comment by StarTrooper08** [comment]
@acald-creator I've created PR for the following issue for meshery-istio project.
Can you please review it
