### ISSUE TITLE
Not able to clone the repository  or pull latest changes on Windows 11

### ISSUE THREAD

**Issue by deepakdinesh1123** [meshery/meshery#6669]
#### Current Behavior
Cloning the repository or pulling the latest changes on windows leads to an error
```
Cloning into 'meshery'...
remote: Enumerating objects: 114324, done.
remote: Counting objects: 100% (4368/4368), done.
remote: Compressing objects: 100% (1143/1143), done.
remote: Total 114324 (delta 3021), reused 4306 (delta 2989), pack-reused 109956
Receiving objects: 100% (114324/114324), 247.78 MiB | 1.90 MiB/s, done.
Resolving deltas: 100% (80462/80462), done.
error: invalid path '.github/scripts/pub?gid=0&single=true&output=csv'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

I was able to clone the repo by running the command 
```
git config core.protectNTFS false
```
but the files whose paths were shown as invalid were deleted and it showed up in the changes
```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    .github/scripts/pub?gid=0&single=true&output=csv
        deleted:    .github/scripts/pub?gid=0&single=true&output=csv.1
        deleted:    .github/scripts/pub?gid=0&single=true&output=csv.2
```
#### Environment

- **Host OS:**  Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks for filing this. And for sharing the details of how are you have overcome the situation with filename in file system and compatibility. This is a straightforward fix.

**Comment by cloudier1337** [comment]
hey @leecalcote can I ask what the straightforward fix is/was?

**Comment by Yh010** [comment]
@deepakdinesh1123 you can try 
```
git restore --source=HEAD :
``` 

this will restore all the deleted files.

the error "warning: Clone succeeded, but checkout failed." means files in the repository were successfully copied to your local machine, but the process of setting the correct version of the files in your working tree failed. I am not sure how to resolve this though

**Comment by leecalcote** [comment]
Fixed by removal of Windows-incompatible filenames.
