### ISSUE TITLE
[UI] Add Sidebar Peek on hover of Notification Center bell

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6683]
### Current Behavior
Global menu controls are too subtle, not interactive enough.

### Desired Behavior
1) **K8s context switcher**
Increase the range of the downward peek effect.

2) **Notification Center Sidebar** 
Add an on hover effect to have the Notification Center sidebar peek out from the right edge of the screen when the bell icon is hovered over, behaving the same way as the hover effect for the k8s context switcher.

### Implementation
1. k8s context switcher: translateY(1.25rem)
1. Notification Center sidebar: same distance as the k8s context switcher, but sliding horizontally, not vertically. 

### Mockups
See screen recording below.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by partik03** [comment]
@leecalcote I am not able to understand what exactly we have to do in this issue.Can you tell me briefly??

**Comment by leecalcote** [comment]
@partik03, I thought that @theBeginner86 might have this completed before I could explain, and so I held off. There are two asks here:

1) Increase how far down the Kubernetes Context switcher peeks downward on hover. It's too subtle at the moment. Using `translateY(1.25rem)` feels about right.


https://user-images.githubusercontent.com/7570704/208197694-d24231d1-c750-4ae9-91da-d094522946f0.mov

**Comment by leecalcote** [comment]
@partik03 I have updated this issue's description with more details.
