### ISSUE TITLE
[CI] Cleanup old, unused make targets

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6685]
#### Current Behavior
Meshery's makefile has a number of deprecated targets that need to be cleaned up.

#### Desired Behavior
Ideally, only active make targets are documented and present in the makefile.

#### Implementation
1. Update contributing.md
2. Update https://docs.meshery.io/project/contributing/contributing pages that have `make`

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@UtkarshMishra12 fyi

**Comment by leecalcote** [comment]
@Anand-Theertha fyi

**Comment by ayushthe1** [comment]
hey @leecalcote ,i would like to work on this issue. Could you suggest more about this issue and how i should start solving it.

**Comment by leecalcote** [comment]
I'll let @acald-creator speak to this.

**Comment by Anand-Theertha** [comment]
Can I take up this issue?

**Comment by Anand-Theertha** [comment]
I have removed a few obvious deprecated targets that handles meshery-ui but there's a section to build meshery-ui in contributing.md. My question is - should make server be replaced with make ui-server  readme.md for meshery-ui.

**Comment by ayushthe1** [comment]
hey @acald-creator @Anand-Theertha , i made a draft pr for this issue. Could you please review it and give some suggestions .
Also i have a doubt that there are many targets in the makefile like `server-without-k8s ,docker-local-cloud ,etc.` in the makefile which aren't used anywhere in the repo .Should these targets also be removed ?

**Comment by Anand-Theertha** [comment]
I think the changes in the Makefile you've made are right, but there are a few more commands that you may have missed (like the `build ui` and the `build meshery-ui` to name a few). Also, there might be a few changes in the contributing.md and readme.md file as well.

Let's see if @leecalcote has some feedback? 😁

**Comment by ayushthe1** [comment]
Thanks @Anand-Theertha for the feedback. The reason i've left some targets which were alias of others (like `build-ui`) bcoz i found them being used elsewhere in many files .I've only removed aliases which are not used anymore .Mainly i'm confused what to do for targets which aren't some aliases but are also not used anywhere in the repo (like `server-without-k8s` mentioned above)
