### ISSUE TITLE
Failed to install Linkerd via Meshery UI

### ISSUE THREAD

**Issue by clin4** [meshery/meshery#6687]
#### Current Behavior
Failed to install Linkerd via Meshery UI for a in-cluster k8s

#### Expected Behavior
Linkerd can be installed (which works for me a few days ago from another meshery on another k8s)

#### Screenshots/Logs
log from lmeshery-linkerd
time="2022-12-13T01:16:04Z" level=info msg="network-authentication.yaml registered" app=linkerd-adapter
time="2022-12-13T01:16:04Z" level=info msg="Component creation completed for version stable-2.12.3" app=linkerd-adapter
time="2022-12-13T01:16:04Z" level=info msg="Registering workloads with Meshery Server for version stable-2.12.3" app=linkerd-adapter
time="2022-12-13T01:16:04Z" level=info msg="Latest workload components successfully registered for version stable-2.12.3" app=linkerd-adapter
time="2022-12-13T01:18:24Z" level=info msg="Listing Operations" app=linkerd-adapter
time="2022-12-13T01:19:38Z" level=info msg="Listing Operations" app=linkerd-adapter
time="2022-12-13T01:20:21Z" level=info msg="Applying operation linkerd" app=linkerd-adapter
time="2022-12-13T01:20:21Z" level=info msg="Requested install of version: edge-22.4.1" app=linkerd-adapter
time="2022-12-13T01:20:21Z" level=info msg="Requested action is delete: false" app=linkerd-adapter
time="2022-12-13T01:20:21Z" level=info msg="Requested action is in namespace: linkerd-system" app=linkerd-adapter
time="2022-12-13T01:20:22Z" level=error msg="chart \"linkerd2\" version \"22.4.1\" not found in https://helm.linkerd.io/edge repository" app=linkerd-adapter code=1003 probable-cause= severity=2 short-description="Error with Linkerd operation: " suggested-remediation=
time="2022-12-13T01:20:22Z" level=info msg="Attempting manifest installation..." app=linkerd-adapter
time="2022-12-13T01:20:22Z" level=info msg="Looking for linkerd in the path..." app=linkerd-adapter
time="2022-12-13T01:20:22Z" level=info msg="Looking for linkerd in/root/.meshery/bin..." app=linkerd-adapter
time="2022-12-13T01:20:22Z" level=info msg="linkerd not found in the path, downloading..." app=linkerd-adapter
time="2022-12-13T01:20:22Z" level=info msg=Installing... app=linkerd-adapter
time="2022-12-13T01:20:23Z" level=info msg=Done app=linkerd-adapter
time="2022-12-13T01:20:23Z" level=error msg="exit status 2" app=linkerd-adapter code=1003 probable-cause= severity=2 short-description="Error with Linkerd operation: " suggested-remediation=
time="2022-12-13T01:20:23Z" level=error msg="exit status 2" app=linkerd-adapter code=1003 probable-cause= severity=2 short-description="Error with Linkerd operation: " suggested-remediation=
time="2022-12-13T01:20:23Z" level=info msg="Event stored and sent successfully" app=linkerd-adapter

#### Environment
fresh instal 
- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** v0.6.34
- **Meshery Client Version:** v0.6.34

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Yh010** [comment]
This is probably due to an issue with the version specified or the repository specified not being correct.
You can check the documentation of Linkerd to determine which version is compatible with your K8s cluster and the features you require. You should also verify the availability of the version in the corresponding Linkerd repository before trying to install it.
this is the repo : https://helm.linkerd.io/edge
