### ISSUE TITLE
[UI] Settings-->Metrics: Support GraphQL subscription

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6701]
#### Current Behavior
When MeshSync discovers a Grafana or Prometheus instance, they will be listed in the dropdown fields in the Settings page under Metrics if the user refreshes their browser to GET those entries.

#### Desired Behavior
The Settings-->Metrics-->Grafana page and the Prometheus pages are in need of using a subscription in order to expose discovered Grafana and Prometheus endpoints for selection without requiring that the user refresh their browser.

#### Implementation
Create GraphQL Subscription for these connections.

#### Acceptance Tests
The list of discovered Graf and Prom instances populate without page refresh.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Vaani-pathariya** [comment]
Can i work on this one ??

**Comment by acald-creator** [comment]
I've been working on GraphQL, I can take a look and see if I can make something out of this.

**Comment by acald-creator** [comment]
Was there an open PR for this? Not sure I saw one, but I haven't made headway with this item since I've been working on the Next.js upgrade. You can take this one on, @MUzairS15

**Comment by leecalcote** [comment]
No, there hasn't been a PR on this item, yet. Still an open need.

**Comment by leecalcote** [comment]
> Can i work on this one ??

Hi @Vaani-pathariya! Thanks for asking. I would like for the answer to be "yes". Just before we get this issue (or another issue) assigned, will you take a moment to confirm that you've be able to build and run Meshery Server and Meshery UI? Let's set you up for success. As you confirm this, will you also mention your thinking in terms of the approach to solving this issue?

Again, we would love for you to take this one (or if not this one another one). Let's get you ramped up and ready to go. Signal when ready.
