### ISSUE TITLE
[Docs]- UI Contributing guide and CONTRIBUTING.md have slightly different information

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery#6708]
#### Current State
[Docs]- UI Contributing guide and CONTRIBUTING.md have slightly different information

#### Desired State
Making both the information the same and correct

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by deepakdinesh1123** [comment]
@UtkarshMishra12 you might likely have already changed it, but the ```CONTRIBUTING.md``` file mentions that npm@7 and node@14.8.0 are required but the ```.nvmrc``` has v18.12.1 in it, please update the ```CONTRIBUTING.md``` and UI contributing guides to reflect this.

**Comment by VedRatan** [comment]
hey, I think that the issue is already been resolved as it is mentioned that one should have latest version of node and npm, you can close this now.

**Comment by VedRatan** [comment]
@UtkarshMishra12  where is the specific change have to be made? I have gone through contributing.md but didn't able to make out where to make specific changes.
