### ISSUE TITLE
[UI] "Verify" on Public content and "Verify" on cloned Public content doesn't work.

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#6715]
#### Current Behavior
<img width="1167" alt="Screenshot 2022-12-15 at 11 34 15 AM" src="https://user-images.githubusercontent.com/65453826/207944489-14ac8ef8-a3d2-4959-968f-2b800cb1c09e.png">

#### Desired Behavior
It should validate as private content. 

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
// @gr455 @harkiratsm @Chadha93

**Comment by siddheshJungade** [comment]
Should I go for it ?

**Comment by partik03** [comment]
@Chadha93 can you elaborate this issue a little bit??

**Comment by Chadha93** [comment]
> @Chadha93 can you elaborate this issue a little bit??

@partik03 Click validate on public designs, It won't work, Clone it then again click validate it won't work. Run Meshery in Dev server to check the exact error. The issue is with how the validate is passed in the public designs. (To see public designs use the eye button)

**Comment by partik03** [comment]
@Chadha93 I was working on this issue,did some changes but I am facing an error constantly can you help me figure it out??

**Comment by Chadha93** [comment]
> @Chadha93 I was working on this issue,did some changes but I am facing an error constantly can you help me figure it out??

Sure, Let's connect over slack. Tagging @harkiratsm to provide more context.
