### ISSUE TITLE
[UI] Change the order of tabs in confirmation modal. 

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#6719]
#### Current Behavior
The current order is Deploy --> Undeploy --> Validate
![image](https://user-images.githubusercontent.com/65453826/208052944-059170ba-fc3f-4e86-a60f-a8956c5fa3e4.png)

#### Desired Behavior
Change the order to Validate --> Undeploy --> Deploy. Make sure the tab content is also mapped accordingly. 

#### Acceptance Tests
Please do provide a video or screenshot of the changes in the PR description. 

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by partik03** [comment]
@Chadha93 can I work on this issue??

**Comment by Chadha93** [comment]
> @Chadha93 can I work on this issue??

Great @partik03
