### ISSUE TITLE
[Docs] Create a new page on meshery documentation site on how dark mode works.

### ISSUE THREAD

**Issue by Musab1258** [meshery/meshery#6736]
#### Current State
There is no guide on how dark mode works on the meshery docs site 

#### Desired State
Create a new page on how dark mode works, in: https://docs.meshery.io/project/contributing

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Musab1258 you're writing this up for the meshery.io site first, right?

**Comment by Musab1258** [comment]
> @Musab1258 you're writing this up for the meshery.io site first, right? // @Krishna2323

Yea @leecalcote .

**Comment by leecalcote** [comment]
Completed.
