### ISSUE TITLE
[UI] Add Space between mesh Adapters 

### ISSUE THREAD

**Issue by siddheshJungade** [meshery/meshery#6739]
#### Current Behavior

no space or margin between Mesh adapters 
#### Desired Behavior

Their should be space between all Mesh adapters

### Screenshots/Logs

![Screenshot from 2022-12-18 21-29-37](https://user-images.githubusercontent.com/32316726/208307988-d271d1bb-7bc6-47d3-b3e6-9641f688a5ea.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Rahilsiddique** [comment]
hey can you assign this issue to me, I have understood what need to be done

**Comment by Vaani-pathariya** [comment]
hello , i am willing to contribute to this issue . Also i am new to open source and devops , so i'll be highly greatful if you can provide me with some resources to understand the project more.
Thank you !

**Comment by Chadha93** [comment]
@Vaani-pathariya You can start with the [Newcomers' journey](https://meshery.io/community/newcomers) and do join the newcomers' meeting https://meet.meshery.io/ to know about projects and resources.

**Comment by leecalcote** [comment]
@Vaani-pathariya what do you think?

**Comment by leecalcote** [comment]
@Vaani-pathariya, we didn't see you on today's Newcomers meeting. Perhaps, next week?

**Comment by Vaani-pathariya** [comment]
> @Vaani-pathariya, we didn't see you on today's Newcomers meeting. Perhaps, next week?

yes ill definitely attend the next meeting without fail

**Comment by Udit-takkar** [comment]
Fixing this issue
