### ISSUE TITLE
[Docs] List version of Node required for UI development

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6742]
#### Current State
This page does not list the required version of node (or other frameworks used). Contributors are unaware of which node version to use with the project, so that their dev environment is compatible.

#### Desired State
Document required version of node (and ideally, other frameworks) in a prominent location toward the top of the doc.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Abhishek-kumar09** [comment]
The Node version with which the UI is tested and proven is:
node 16 LTS
node 18 LTS

Although, the script support other node versions as well like node17, node 15.
It is recommended to use node version above 15 and mainly the  use of LTS versions like 16 and 18 are recommended the most.

**Comment by VedRatan** [comment]
@leecalcote can I work on this issue?

**Comment by leecalcote** [comment]
Sounds real good. We should be dictating one Mode version and only one Node version a given point in time (for with a specific Meshery version).  @acald-creator @MarioArriaga92

**Comment by acald-creator** [comment]
bump, will review this again.

The docs include README.md in `ui` and CONTRIBUTING.md will needs to be updated accordingly.
