### ISSUE TITLE
[UI] Selected Items disappear in Table view, Even when deletion denied in modal

### ISSUE THREAD

**Issue by hs05june** [meshery/meshery#6754]
#### Current Behavior

Currently at /configuration/filters, /configuration/applications, /configuration/patterns. On clicking the delete icon all the selected items get disappeared. Even when NO is selected in the delete modal.

https://user-images.githubusercontent.com/103871275/208772597-e638472e-c9f0-47f7-9fb4-1ecbb1d6288e.mp4

#### Desired Behavior

Items should appear after NO is selected in the delete modal.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by hs05june** [comment]
Hey @mentors. I figured out that items disappear from the frontend due the delete icon of the mui data table. If we add the functionality to reload the page if NO is selected. The things will work.

**Comment by leecalcote** [comment]
Hi @hs05june, are you in the community slack workspace already? Will you say "hi", if so? 

Thanks for filing this.

**Comment by leecalcote** [comment]
@hs05june good eye. Thanks for filing this issue. We don't to force a page reload, but instead prevent the removal of these items from the data table in the first place.

**Comment by hs05june** [comment]
@leecalcote Yes I am there in the slack community.

**Comment by hs05june** [comment]
https://user-images.githubusercontent.com/103871275/208922890-10e2841c-27e8-42df-8cfe-09d501a9f1de.mp4

Hey @leecalcote. It was due to the default behaviour delete button in thr toolbar select of MUI Data Table. So I have overidden it with customised toolbar select

**Comment by hs05june** [comment]
Hey @leecalcote I have opened a PR #6758 in which I have solved this issue for design page. Kindly review it

**Comment by leecalcote** [comment]
@hs05june thanks. Three others are assigned to review.

**Comment by hs05june** [comment]
Hey @leecalcote . I have received review for the PR made to solve this issue on /configuration/patterns. I will be making a PR for /configuration/filters, /configuration/applications also.

**Comment by leecalcote** [comment]
@hs05june ok, that’s great. Do update the name of your PR to be represent the specific work.

**Comment by harkiratsm** [comment]
@Chadha93 fyi
