### ISSUE TITLE
[CI] Docs: Create workflow to refresh list of discussion forum posts

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6774]
#### Current Behavior
Meshery Docs displays the most recent 10 discussion forum posts by tag name. Currently "mesheryctl" and "meshery" are the two supported tags. See this related PR https://github.com/meshery/meshery/pull/6773 and this discussion https://discuss.layer5.io/t/proposal-and-call-for-participation-building-the-community-leaderboard/1712/2

#### Desired Behavior
A scheduled (cron) workflow should refresh the multiple lists of related discussion data files (json) on a daily basis.

#### Implementation
1. Checkout repo
1. Pull fresh list of related posts from:
    1. http://discuss.layer5.io/tag/mesheryctl.json
    1. http://discuss.layer5.io/tag/meshery.json
1. Deposit data files here - https://github.com/meshery/meshery/tree/master/docs/_data/discuss
1. Autocommit fresh data files.

#### Acceptance Tests
1. Fresh list of related posts display in the Recent Discussions with "<tag>" Tag (e.g. https://docs.meshery.io/guides/mesheryctl)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by deepakdinesh1123** [comment]
@leecalcote Can I work on this?

**Comment by gopivaibhav** [comment]
Hi @leecalcote I am good to go with this !!

**Comment by leecalcote** [comment]
Thank you, gents. Proceeding with first come, first serve, acknowledging that if after ~a week there isn't progress, we'll move down the list.
