### ISSUE TITLE
[Docs] Small images in Meshery Readme.

### ISSUE THREAD

**Issue by chinu-anand** [meshery/meshery#6777]
#### Current State
The images in the readme of Meshery are very small that a user/viewer has to click on them to view what it is. Some open on GitHub while some redirects to meshery doc website and the GIF one directly gets downloaded. Some alignment issues are also there leading to an inconsistent reading experience.

#### Desired State
All images should be of equal size and big enough so that it serves their purpose directly. Paragraph and image alignment should be consistent throughout the doc.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks, @chinu-anand. Sounds good. Would you like this issue assigned to you?

**Comment by chinu-anand** [comment]
Yes @leecalcote, I am already working on this improvement.
