### ISSUE TITLE
[UI] No model for updating an application in the applications page.

### ISSUE THREAD

**Issue by partik03** [meshery/meshery#6798]
#### Current Behavior
No model is shown while updating any application in grid view.

https://user-images.githubusercontent.com/99184676/209821234-315fb532-5c40-4d3c-9def-76a57a541359.mp4

#### Desired Behavior
A modal should appear before the user so that the chances of the application getting edited accidentally could be minimized.

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by partik03** [comment]
@leecalcote @Chadha93 Please  review this issue and the pr for this issue as well.

**Comment by leecalcote** [comment]
Marking issue invalid. Please see explanation given on PR.
