### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by sassukeuchiha** [meshery/meshery#6805]
#### Current State
https://docs.meshery.io/concepts/architecture/operator

In the current page if i try to go back to architecture via the above links present on the page for architecture it gives a 404

#### Desired State
the path must be properly set for the architecture page so that it does not redirects to 404

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sassukeuchiha** [comment]
![mesh1](https://user-images.githubusercontent.com/116432455/209850457-b043c679-fea9-49ee-a838-f6c345b964b8.png)
![mesh2](https://user-images.githubusercontent.com/116432455/209850466-38d403da-a4f8-4b16-bb21-83957f491a70.png)

**Comment by UtkarshMishra12** [comment]
Thanks @sassukeuchiha 😄 . Do you want to work on this issue?

**Comment by sassukeuchiha** [comment]
Yes would love to :)

**Comment by UtkarshMishra12** [comment]
Here you go @sassukeuchiha 🚀

**Comment by sassukeuchiha** [comment]
hey @UtkarshMishra12 can you guide me through this ,
I have to make following changes
![arch1](https://user-images.githubusercontent.com/116432455/209875192-ebd32e02-e49a-4735-bcd2-c27a173742b3.png)
Need to change this as
<a href="/concepts/architecture">architecture</a>

I tried finding out this in out github meshery docs and was not able to found where that custom meshery part is there 
So after reading docsy jenkyll i found out that the issue that i pointed out is a part of breadcrumb issue

https://www.docsy.dev/docs/adding-content/navigation/

here in the breadcrumb navigation it states that we can just turn on or off the navigation.

**Comment by leecalcote** [comment]
Are you suggesting to remove the breadcrumbs? If so, this isn't the answer.

**Comment by sassukeuchiha** [comment]
No no god no😂
I was just asking where we are keeping the custom meshery(meshery custom begin) paths as seen in the above image because I wasn't able to find those...and in the docs of jenkyll only information on sidebar was present...so if anyone knows where we are keeping the custom paths they can help me through this

**Comment by sassukeuchiha** [comment]
Hey , this issue is present in multiple places , if we navigate to 4th page in a hierarchy lets say https://docs.meshery.io/es/concepts/architecture/broker and if you click on architecture or es on top navigation bar it gives 404 
I think we might have to update the breadcrumbs.html file

https://github.com/sassukeuchiha/meshery/blob/master/docs/_includes/breadcrumbs.html

I am still trying to figure out how should we update this

**Comment by UtkarshMishra12** [comment]
@sassukeuchiha  I'm not able to reproduce the same error, It's working fine for me. 
Want to say anything? 🤔  else I'm closing this issue.

**Comment by sassukeuchiha** [comment]
Hey @UtkarshMishra12 
I got this fixed in another PR, It was merged today morning
https://github.com/meshery/meshery/pull/6906#issuecomment-1386397492
Will close this issue
