### ISSUE TITLE
[UI] New Filter does not appear in list after being imported

### ISSUE THREAD

**Issue by hs05june** [meshery/meshery#6809]
#### Current Behavior

Once the filter has been imported, It does not appear in the filters list on the filters page. It appears after refreshing the page.

#### Desired Behavior

Imported should appear in the list just after being imported.

#### Screenshots/Logs

https://user-images.githubusercontent.com/103871275/209958641-f9dbe32a-9571-4c7e-86db-253ca967bba7.mp4

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by hs05june** [comment]
Hey @leecalcote . I would like to work upon this.

**Comment by leecalcote** [comment]
@hs05june thanks much. To resolve this, you'll be moving to use of one of the [existing GraphQL subscriptions](https://docs.meshery.io/reference/graphql-apis), yes?
