### ISSUE TITLE
[MeshModel] Server: Support multi-zone use of capability registry assets

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6814]
#### Current Behavior
Currently, integrated systems that Meshery allows users to configure have their individual system (e.g. Kubernetes) components (e.g. Pod) registered into Meshery’s Database (into the Capabilities Registry tables) upon boot. Part of this registration process includes a depositing of component-specific icons (as light and dark mode SVGs) onto Meshery’s filesystem here - https://github.com/layer5io/meshery/tree/master/server/meshmodel/components.
This path isn’t accessible by Meshery UI as a client of the Nextjs “web server” under its exposed path, /ui/public/static here - https://github.com/layer5io/meshery/tree/master/ui/public/static - where other images are made available.

#### Desired Behavior
Rather than replicating the SVG files (or splitting them out from their respective component packages), ideally, we can configure Nextjs to also expose the images under the /server/meshmodel/components folders.

#### Implementation
Use Nextjs's [multi-zones](https://nextjs.org/docs/advanced-features/multi-zones) capability to expose capability registry assets.

#### Acceptance Tests
1. `/server/meshmodel` directory contents are accessible over http under `<meshery-server-host>`/static/meshmodel`

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by acald-creator** [comment]
Currently working through this, hopefully will have a solution ASAP.

**Comment by acald-creator** [comment]
Closing this as we decided to do a different route.

May revisit this in the future.
