### ISSUE TITLE
[Docs] Meshery UI Icons: Always include this XML header in each SVG image

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6846]
#### Current State

```3. Always include this XML header in each SVG image```

#### Desired State

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by hs05june** [comment]
Please assign it to me @leecalcote

**Comment by Shivam-AfA** [comment]
For this issue, we require a confirmation that do we need to add the XML header for all SVG files or just the files other than the integration icons?

**Comment by leecalcote** [comment]
Apologies for the poorly described issue. This one turns out to only require a docs update in the Meshery Integrations spreadsheet. Update was just made by @Abhishek-kumar09
