### ISSUE TITLE
Issue in README.md

### ISSUE THREAD

**Issue by VedRatan** [meshery/meshery#6847]
#### Current State
The link to **Meshery Contributors Welcome Guide** is redirecting towards the deleted docs link.

#### Desired State
The link should redirect to the correct docs link or the link should be removed from the text.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
Here you go 🚀 @VedRatan. Please replace the current link with this link https://meshery.io/handbook/repository-overview.

**Comment by VedRatan** [comment]
Sure @UtkarshMishra12.

**Comment by VedRatan** [comment]
@UtkarshMishra12  there are some other places in README.md which redirects to the same deleted docs link. Should I attach a commit to this PR only, fixing those places, or do I create a new branch for those changes?

**Comment by UtkarshMishra12** [comment]
Please update all the occurrences in this PR only @VedRatan

**Comment by VedRatan** [comment]
Alright, @UtkarshMishra12 will update in a while.

**Comment by VedRatan** [comment]
@UtkarshMishra12, done with the assigned task. You can check it once.
