### ISSUE TITLE
[Docs] Make file command update

### ISSUE THREAD

**Issue by gurpreet-legend** [meshery/meshery#6850]
#### Current State
Currently in `README.md` of `meshery/docs` the command to serve the code locally is `make site`, shown here:
![image](https://user-images.githubusercontent.com/75157493/211316355-7cbd4211-4323-4113-9c1c-4342b799a4cc.png)

#### Desired State
The current command is `make docs` as per the `Makefile`:
https://github.com/gurpreet-legend/meshery/blob/0deff4995db098f221ff092aa3bb2dc8d0069c25/docs/Makefile#L3

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by gurpreet-legend** [comment]
I was going through the `meshery/docs` documentation when I noticed it, I can fix this, can you assign this to me @leecalcote

**Comment by leecalcote** [comment]
@gurpreet-legend, thanks. Will you change this make target to `make site` and search the rest of the codebase for any `make docs` references, replacing them with `make site`?

In the future, best to tag @meshery/meshery-docs-contributors so that I don't slow you down.

**Comment by gurpreet-legend** [comment]
Sure @leecalcote, will replace all the `make site` references to `make docs`
