### ISSUE TITLE
Issue in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by VedRatan** [meshery/meshery#6856]
#### Current State
The link to **newcomers welcome guide** is redirecting towards the deleted docs link.

#### Desired State
The link should redirect to the correct docs link or the link should be removed from the text.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by VedRatan** [comment]
@leecalcote @UtkarshMishra12  can I work on this one?

**Comment by VedRatan** [comment]
@leecalcote  any updates?

**Comment by UtkarshMishra12** [comment]
Here you go @VedRatan 🚀
