### ISSUE TITLE
[Docs] livereload not working for documentation site

### ISSUE THREAD

**Issue by gurpreet-legend** [meshery/meshery#6859]
#### Current Behavior
The LiveReload is getting connected to the browser but not able to reload the page whenever there is a change in the code and does not reflect the code changes on the development server.

**System specs:**
Host OS: Windows 10
Tier 2 virtualized OS being used in `wsl`: Ubuntu 22.04 
IDE: VS Code

#### Expected Behavior
The site should reload on every code change and the changes should reflect on the running development server.

#### Screenshots/Logs
![image](https://user-images.githubusercontent.com/75157493/211424467-1219e135-9b43-4e36-9faa-85e28441c84f.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by gurpreet-legend** [comment]
@meshery/meshery-docs-contributors, is everyone facing this issue? If yes, can I fix this?

**Comment by gurpreet-legend** [comment]
@meshery/meshery-docs-contributors, I think this is a `wsl` specific issue.

**Comment by leecalcote** [comment]
@gurpreet-legend will you update the issue description to only list the "Host OS:" that you're using. I assume that this is Windows.
