### ISSUE TITLE
[UI] Inconsistency in the sidebar icons

### ISSUE THREAD

**Issue by hs05june** [meshery/meshery#6860]
#### Current Behavior

Only few icons in the sidebar  get blue, when user has selected them.
#### Desired Behavior

All icons in the sidebar shold get blue, when user has selected them. So that, user can know where he is.
#### Screenshots/Logs

https://user-images.githubusercontent.com/103871275/211491333-f2b90467-b52c-4c8e-9566-416d2b2acb07.mp4

#### Environment

- Browser: Firefox
- Host OS:Linux 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by hs05june** [comment]
Hey @leecalcote I would like to work upon this

**Comment by Chadha93** [comment]
Thank you for the issue @hs05june.
