### ISSUE TITLE
[Docs] Compatibility Matrix: Proper sorting by Kubernetes versions (descending)

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6873]
#### Current State
The Kubernetes version column is not sorting correctly on the [Compatibility Matrix page](https://docs.meshery.io/installation/platforms).

<img width="552" alt="Screenshot 2023-01-12 at 12 13 14 PM" src="https://user-images.githubusercontent.com/7570704/212146447-13e292ee-11ad-4057-94ef-117c91d9ca64.png">

#### Desired State
The compatibility table should be sorted in descending order of Kubernetes version #.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Abiey2579** [comment]
Hello @lee I think I know how to fix this

**Comment by rudrakshkarpe** [comment]
I guess we can try it with the ```sort_by``` filter instead of ```group_by```.  The ```sort_by``` filter will sort the items in a collection based on a specified key.

**Comment by rudrakshkarpe** [comment]
> I guess we can try it with the `sort_by` filter instead of `group_by`. The `sort_by` filter will sort the items in a collection based on a specified key.

Here's the PR associated these changes #6923
