### ISSUE TITLE
[UI] Notification Center: Doesn't always fully open on click

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6896]
#### Current Behavior
While the Notification Center is to peek out on hover of the Notification Center button (usually a bell, but sometimes can exclamation mark icon), it should always fully open when are use her clicks on the button. In the attached video, you can see that despite being clicked on the sidebar, never fully opens. This behavior might differ (but shouldn't) between when notification messages are present vs when they are not.

#### Desired Behavior
Sidebar open and remain open on click.

#### Screenshots/Logs

https://user-images.githubusercontent.com/7570704/212572486-8a4d9ac8-825e-427a-89be-ef7198d9592b.mov

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: edge

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by deepakdinesh1123** [comment]
@leecalcote  Can I work on this?

**Comment by leecalcote** [comment]
@deepakdinesh1123, yes, that would be great. 👍

**Comment by ajaysinghpanwar2002** [comment]
@leecalcote i would like to work on this issue, can you assign me this.

**Comment by leecalcote** [comment]
@ajaysinghpanwar2002 thanks for volunteering. I encourage you to review @deepakdinesh1123's PR - https://github.com/meshery/meshery/pull/6905
