### ISSUE TITLE
[UI] Visibility of the dashboard button in the left menu is toggled by clicking on it

### ISSUE THREAD

**Issue by deepakdinesh1123** [meshery/meshery#6907]
#### Current Behavior
The dashboard button's visibility in the left menu tray(when it is minimized) is toggled by the click on the button

#### Desired Behavior
The button should always be visible

#### Screenshots/Logs

[2023-01-17 22-51-16.webm](https://user-images.githubusercontent.com/52698821/212969615-8aa80626-1364-4e06-8a6f-cb4769cb07bd.webm)

#### Environment

- Browser: Chrome
- Host OS:  Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by deepakdinesh1123** [comment]
I am working on this and I'll have a PR by tomorrow or the day after tomorrow.

**Comment by Chadha93** [comment]
Thank you for this one, will you also make this issue in your PR https://github.com/meshery/meshery/issues/6424. It's the same one, just closed due to stale marking.
