### ISSUE TITLE
[UI] Configuration option does not turn blue on selection

### ISSUE THREAD

**Issue by Shivam-AfA** [meshery/meshery#6914]
#### Current Behavior
The Configuration option text does not turn to blue when selected, unlike the other options.

https://user-images.githubusercontent.com/88040318/213297090-6923308d-db84-4e62-bd24-07fa7dc88f85.mp4

#### Desired Behavior
The Configuration options text should turn to blue on selection.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by mohd-aman** [comment]
@Shivam-AfA, I would love to resolve this. can you please assign it to me?

**Comment by Shivam-AfA** [comment]
Go ahead @mohd-aman

**Comment by Shivam-AfA** [comment]
Any updates @mohd-aman

**Comment by mohd-aman** [comment]
Hi shivam, just noticed this yesterday that i have been assigned this
issue. Will get back to you by tomorrow EOD.

**Comment by mohit-marathe** [comment]
Hello @mohd-aman, are you still working on this issue?

**Comment by Shivam-AfA** [comment]
@mohd-aman any updates?

**Comment by Shivam-AfA** [comment]
Since @mohd-aman has been inactive for quite a while, @mohit-marathe would you like to work on this? Have you set up meshery-ui locally?

**Comment by mohit-marathe** [comment]
Yes @Shivam-AfA, I would like to work on this and yeah I have already set up meshery-ui locally
