### ISSUE TITLE
Design and Docs for API Versioning

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6922]
#### Current Behavior
Meshery's two [GraphQL API](https://docs.meshery.io/reference/graphql-apis) and [REST API](https://docs.meshery.io/reference/rest-apis) APIs are in need of more robust versioning. 

#### Desired Behavior
The following questions need to considered and addressed:

- Will clients need to upgrade?
- Will the entire API be versioned or specific routes?
- What happens when clients send a v2 request to a v1 endpoint? Vice versa?

Document the following:
1.  Convention used to identify whether an API change will be backward compatible.
    1. Set expectations with API clients on breaking changes (this is fairly standard practice of pre-1.0 the APIs being loose).
    1. Will v2 endpoints accept v1 requests?
1. Document the API deprecation policy. 
    1. How long should users expect a deprecated API to be available before it is completely unsupported? 
    1. What label / identifier should clients look for as the signal that an API is deprecated?

Implement the following:
1. All endpoints of either the REST or the GraphQL API will be versioned as a complete collection.
    1. The REST API will carry its own version number. 
    1. The GraphQL API will carry its own version number. 
1. Use semantic versioning as the version number style (as opposed to date); e.g. `v1`
1. Define API version in the endpoint path. e.g. `/api/v1/....`

#### Acceptance Tests
1. Documentation updated.
6. Conventions defined.
7. Practices put into place.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@b0id this make or may not interest...

**Comment by b0id** [comment]
Yeah, I am.  I have some ideas based on the long term road map regarding this.

**Comment by rav121** [comment]
@rav121 pining myself :D for 2023 first half milestone

**Comment by b0id** [comment]
@leecalcote would you tag a few of the senior engineers, here or by PM, it is something I am up for, but will definitely need a senior meshmate to tackle.  This will obviously require deliberate planning and dialogue.  Reviewing architectural details as of 1/23 for proposals.

**Comment by b0id** [comment]
The community could also mention features that would be desirable, could be a thread on the discuss board as well. Working on a write up.
