### ISSUE TITLE
[UI] Bug in customize addons toggle buttons of lifecycle page

### ISSUE THREAD

**Issue by hs05june** [meshery/meshery#6924]
#### Current Behavior

At '/management?adapter=localhost:10000'
Even when the operations fail, buttons get toggled. In the video operation failed, but grafana button toggled.  

#### Desired Behavior

Buttons must take their value as per the operations.

#### Screenshots/Logs

https://user-images.githubusercontent.com/103871275/213932464-de662d06-fbca-4773-86f4-bd4a20c21ab9.mp4

#### Environment

- Browser: Firefox
- Host OS: Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by hs05june** [comment]
Hey @leecalcote Please review the PR that has been made.

**Comment by leecalcote** [comment]
Oh, good one, @hs05june!
