### ISSUE TITLE
Grammatical Mistake in README.md

### ISSUE THREAD

**Issue by ShivangShandilya** [meshery/meshery#6931]
# Current State

![Layer 5](https://user-images.githubusercontent.com/101946115/214623674-c07f4d53-32cb-4d1f-a960-2651c5136ba4.png)

# Desired State

<h3>While going through the README.md, I came across Cloud Native Lifecycle Management para where in its second line it says- "While supporting hundreds of different type so cloud native---" which should have been - "different types of cloud native--"</h3>
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks, @ShivangShandilya 👍

**Comment by ShivangShandilya** [comment]
I'll start working on it right away. Thanks @leecalcote
