### ISSUE TITLE
[Applications] Support jsonnet files as Meshery Applications

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6940]
#### Current Behavior
A Meshery Application can be generated using Meshery's Designer features or can be imported (and further customized) as a Helm Chart, Docker Compose, or Kubernetes Manifest - each of these are importable application types.

#### Desired Behavior
Ideally, [jsonnet](https://jsonnet.org/) files are also supported application import type.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Aditya-150** [comment]
I want to work on this issue! Please assign it to me.
