### ISSUE TITLE
[UI] Add cluster button in environment settings is not visible

### ISSUE THREAD

**Issue by deepakdinesh1123** [meshery/meshery#6947]
#### Desired Behavior
Add the button
![image](https://user-images.githubusercontent.com/99184676/207076835-9d8f54fd-5601-4569-af8f-47d53670645c.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by VIKAS0264** [comment]
Can i work on this ?

**Comment by Chadha93** [comment]
https://github.com/meshery/meshery/pull/6949

**Comment by Chadha93** [comment]
> Can i work on this ?

@VIKAS0264 Thank you for the heads-up. This is already fixed but there are more unassigned issues to take up. Feel free to comment.
