### ISSUE TITLE
[UI] Snackbar not closing on clicking the cross icon in it

### ISSUE THREAD

**Issue by anshkush92college** [meshery/meshery#6954]
#### Current Behavior

1. The Cross Icon in the Snackbar does not close the Snackbar 
2. The enabled and disabled Snackbar colour is the same

 
#### Desired Behavior

1. Cross Icon should close the Snackbar
2. Ideally, enabled and disabled should have different colour 

#### Screenshots/Logs
https://user-images.githubusercontent.com/78142732/215525410-3115a153-ffc5-4a94-be71-2ea81ebe8cc0.mp4

#### Environment

- Browser: Chrome, Safari, Firefox 
- Host OS: Debian GNU/Linux 11 (bullseye) on Windows 10 x86_64
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by suyashvsingh** [comment]
Hi, can I work on this issue?

**Comment by leecalcote** [comment]
Thanks for highlighting this, @anshkush92college 👍
