### ISSUE TITLE
[UI] Settings inconsistent with the UI,dashboard icon disappearing

### ISSUE THREAD

**Issue by partik03** [meshery/meshery#6956]
#### Current Behavior
The UI of the settings page is not consistent with the UI also the dashboard icon was disappearing with the click.

#### Desired Behavior
The UI must be consistent for all pages.

#### Screenshots/Logs
![Screenshot from 2023-01-31 01-12-24](https://user-images.githubusercontent.com/99184676/215579493-7b0bf212-da87-46e8-96e2-4970406efe6f.png)
![Screenshot from 2023-01-31 01-12-31](https://user-images.githubusercontent.com/99184676/215579504-c0a7c0e5-d96f-48c5-8c91-65a2b9401
![Screenshot from 2023-01-31 01-12-40](https://user-images.githubusercontent.com/99184676/215579520-e6a00a99-8fa9-4485-8d61-ade50c29ff64.png)
a7d.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by partik03** [comment]
@leecalcote Can you assign this one to me??

**Comment by leecalcote** [comment]
Thank you for calling this out, @partik03
