### ISSUE TITLE
[Bug Fix] Fix SVG scaling Problem in Folder: MesheryMeshInterface

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#6966]
Fix the problems with SVG in MesheryMeshInterface
Folder: https://github.com/meshery/meshery/tree/master/ui/components/MesheryMeshInterface

All the files here should be incorporating the changes, described below.

---

When an icon is used directly from the libraries like MUI or font-awesome or something else, always specify the height and width prop.

---

There are some set of SVG styles [specifying common height and width](https://github.com/meshery/meshery/pull/6690/files#diff-06f61349be806f176b8c47957b6dc8f701835c0ba8ef8313106488a361833aa8)

All the icons imported from any library, could be either small, or medium, or large, or xl. One of these styles based on icon demand should be applied to all those svgs.

Examples of how to do it: 
- https://github.com/meshery/meshery/pull/6690/commits/ecc260461b6015ca680d6969e01bfa9565f373f2
- https://github.com/meshery/meshery/pull/6690/commits/4b000e07a2eeb70c402085cdf86544783bcc939c

Files Done:

1. ui/components/CatalogFilter.js
2. ui/components/ConfirmationModal.js
3. ui/components/Content.js
4. ui/components/CustomTableFooter.js
5. ui/components/DashboardComponent.js
6. ui/components/ErrorHandling.js
7. ui/components/Filters.js
8. ui/components/Header.js
9. ui/components/MeshAdapterConfigComponent.js
10. ui/components/MesherySettings.js
11. ui/components/MeshConfigComponent.js
12. ui/components/MesheryAdapterPlayComponent.js
13. ui/components/MesheryApplications.js
14. ui/components/MesheryMetrics.js
15. ui/components/MesheryNotification.js

_Originally posted by @Abhishek-kumar09 in https://github.com/meshery/meshery/issues/6690#issuecomment-1384202999_

**Comment by thisiskaransgit** [comment]
Hey @Abhishek-kumar09, I would like to work on this issue!

**Comment by Abhishek-kumar09** [comment]
https://github.com/meshery/meshery/issues/7035
