### ISSUE TITLE
[Docs] Add "How to Authenticate" to the GraphQL API docs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6993]
#### Current State
Developers using Meshery's GraphQL API are not provided authentication instruction and example.

#### Desired State
The start of the [GraphQL API docs](https://docs.meshery.io/reference/graphql-apis) should have a section on how to retrieve and use Meshery API tokens to interact with the GraphQL API.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by b0id** [comment]
@leecalcote same here, assign me here.

**Comment by yashtandon019** [comment]
Hey @leecalcote  are there any pending tasks to close this issue, if there is i can maybe contribute to that

**Comment by b0id** [comment]
This issue is resolved.
