### ISSUE TITLE
[Docs] Add "How to Authenticate" to the REST API docs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6994]
#### Current State
Developers using Meshery's REST API are not provided authentication instruction and example.

#### Desired State
The start of the [REST API docs](https://docs.meshery.io/reference/rest-apis) should have a section on how to retrieve and use Meshery API tokens to interact with the REST API.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by b0id** [comment]
Put me on this one @leecalcote , I need a list of things to do in my API doc/updates framework I am working on.

**Comment by b0id** [comment]
@leecalcote For both this issue and the GraphQL docs token issues, would a link, with description of link to "authenticate-with-meshery" page be sufficient or do you want a complete reprint (with pictures?) of that information on the API reference page?

**Comment by b0id** [comment]
@Revolyssup this is what I was mentioning in CI today

**Comment by vishalvivekm** [comment]
@leecalcote this issue can be closed now, right ? // @Chadha93
