### ISSUE TITLE
[UI] Dark mode toggle should work on clicking whole menu item just like other item (Get Token, Preferences, Logout)

### ISSUE THREAD

**Issue by anshkush92college** [meshery/meshery#6996]
#### Current Behavior

1. Dark mode toggles only when we click on the checkbox after clicking on avatar  

#### Desired Behavior
1. Dark mode should toggle when whole menu item is clicked instead of checking the the checkbox 

#### Screenshots/Logs
https://user-images.githubusercontent.com/78142732/216673125-f48f86b1-f8dc-4b59-8762-417836879d66.mp4

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Pop!_OS 22.04 LTS x86_64
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by AdityaPote** [comment]
Hi, can I work on this issue??
