### ISSUE TITLE
Error: unknown flag: --adapter in mesheryctl command

### ISSUE THREAD

**Issue by bluedog13** [meshery/meshery#6997]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Error: unknown flag: --adapter.   

```
$ mesheryctl system check --adapter meshery-istio:10000

Error: unknown flag: --adapter
```

#### Desired Behavior
--adapter is supposed to be a valid command based on the official documentation.  

Link to the official documentation:  https://docs.meshery.io/reference/mesheryctl/system/check.  

#### Screenshots/Logs
![Screenshot 2023-02-03 at 11 57 32 AM](https://user-images.githubusercontent.com/11997472/216673899-cb832f8b-a59d-4d48-8589-4bf47ccf3da8.png)

#### Environment

- Host OS: Mac 
- Meshery Server Version: v0.6.47	4c357f30
- Meshery Client Version: v0.6.49	460e9bd43
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
Thanks for opening the issue @bluedog13

**Comment by deepakdinesh1123** [comment]
@alphaX86 It seems like the only flags that are taken into account while running the command are `--pre` and                      
 `--components`, I know a possible fix, Can I work on this?

**Comment by alphaX86** [comment]
Sure @deepakdinesh1123 I'll assign this issue to you

**Comment by bluedog13** [comment]
Just out of curiosity, the document says "--adapter" is a valid flag. Is the code not tested before it gets released for such major errors?  Also is  the documentation not verified while writing it?
