### ISSUE TITLE
[UI] MeshModel summary does not change in dark mode

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#6998]
#### Current Behavior

When navigating to Settings, the part where you look at the MeshModel summary, the UI doesn't change in Dark Mode.

The styles for this section will need to include the Dark Mode toggle.

#### Screenshots/Logs

![Screenshot_20230203_120242](https://user-images.githubusercontent.com/18711313/216675120-fb0aa813-296c-4832-a5c3-96a404ceed2d.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by AgniveshChaubey** [comment]
Hey @acald-creator, can you please elaborate a bit more about this issue?

**Comment by deepakdinesh1123** [comment]
@acald-creator I looked at this and it seems like the issue is that the `MUIDataTable` component does not take into account the `ThemeProvider` used in `_app.js`, one possible fix was to take the theme from the local storage and return a style based on it but it would either require a lot of conditionals for all the individual components of the MUI DataTable or a lot of lines like this. Are there any other possible fixes for this? 

```javascript
getMuiTheme = () => {
  if (localStorage.getItem("Theme") === "dark") {
    return createTheme({
      shadows: ["none"],
      overrides: {
        MUIDataTable: {},
        MuiInput: {
          underline: {
            "&:hover:not(.Mui-disabled):before": {
              borderBottom: "2px solid #FFF",
            },
            "&:after": {
              borderBottom: "2px solid #FFF",
            },
          ...
          ...
    });
  }
  return createTheme({
    shadows: ["none"],
    overrides: {
      MUIDataTable: {},
      MuiInput: {
        underline: {
          "&:hover:not(.Mui-disabled):before": {
            borderBottom: "2px solid #222",
          },
          "&:after": {
            borderBottom: "2px solid #222",
          },
        },
        root: {
          color: "white",
        },
      },
      MUIDataTableSearch: {
        searchIcon: {
          color: "#607d8b",
          marginTop: "7px",
          marginRight: "8px",
        },
        clearIcon: {
          "&:hover": {
            color: "#607d8b",
          },
        },
      },
      MUIDataTableSelectCell: {
        checkboxRoot: {
          "&$checked": {
            color: "#607d8b",
          },
        },
      },
      MUIDataTableToolbar: {
        iconActive: {
          color: "#222",
        },
        icon: {
       .....
       .....
  });
};

```

**Comment by theBeginner86** [comment]
> @acald-creator I looked at this and it seems like the issue is that the `MUIDataTable` component does not take into account the `ThemeProvider` used in `_app.js`, one possible fix was to take the theme from the local storage and return a style based on it but it would either require a lot of conditionals for all the individual components of the MUI DataTable or a lot of lines like this. Are there any other possible fixes for this?
> 
> ```js
> getMuiTheme = () => {
>   if (localStorage.getItem("Theme") === "dark") {
>     return createTheme({
>       shadows: ["none"],
>       overrides: {
>         MUIDataTable: {},
>         MuiInput: {
>           underline: {
>             "&:hover:not(.Mui-disabled):before": {
>               borderBottom: "2px solid #FFF",
>             },
>             "&:after": {
>               borderBottom: "2px solid #FFF",
>             },
>           ...
>           ...
>     });
>   }
>   return createTheme({
>     shadows: ["none"],
>     overrides: {
>       MUIDataTable: {},
>       MuiInput: {
>         underline: {
>           "&:hover:not(.Mui-disabled):before": {
>             borderBottom: "2px solid #222",
>           },
>           "&:after": {
>             borderBottom: "2px solid #222",
>           },
>         },
>         root: {
>           color: "white",
>         },
>       },
>       MUIDataTableSearch: {
>         searchIcon: {
>           color: "#607d8b",
>           marginTop: "7px",
>           marginRight: "8px",
>         },
>         clearIcon: {
>           "&:hover": {
>             color: "#607d8b",
>           },
>         },
>       },
>       MUIDataTableSelectCell: {
>         checkboxRoot: {
>           "&$checked": {
>             color: "#607d8b",
>           },
>         },
>       },
>       MUIDataTableToolbar: {
>         iconActive: {
>           color: "#222",
>         },
>         icon: {
>        .....
>        .....
>   });
> };
> ```



@deepakdinesh1123 yeah, you are correct. Having several conditionals is usually not the right option.
I haven't seen the code around dark mode much, so I can't comment. But I do see dark mode being applied on similar MUI data tables, like the one on the dashboard.

![Screenshot 2023-02-09 at 6 04 44 PM](https://user-images.githubusercontent.com/73700530/217814182-b11df8dd-10b6-427a-a65f-57d157fc88cc.png)

@deepakdinesh1123 Would you like to explore that and see how that is working? And apply learnings from it to fix this issue?

Tagging @Harshit-Dandriyal for help. // @Chadha93

**Comment by deepakdinesh1123** [comment]
@theBeginner86 I checked out the code for the dashboard component, and there 2 different methods are used to provide dark and light themes, I will implement the same and create a PR soon.

**Comment by Harshit-Dandriyal** [comment]
@deepakdinesh1123 Yes, you are absolutely right, Just put the ThemeProvider tag and add the dark theme of the data table in it that we used in the dashboard.
