### ISSUE TITLE
[UI] Meshery Designs - Catalog show/hide still show Public item

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#6999]
#### Current Behavior

In Meshery Designs, when you would like to look at the Design items, selecting Catalog to show or hide public/private items, still show the one Public item that, after research, does not belong to me, but it still shows in the Private display.

#### Desired Behavior

It should only show through Public, not Private, and if the item does not belong to the user, indicate that it isn't, either by Tootltip or a short description of the Design item.

#### Screenshots/Logs

![Screenshot_20230203_121043](https://user-images.githubusercontent.com/18711313/216676682-62b0d8aa-fae6-4f61-8c1e-a9ecb14d1ca7.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by mak2002** [comment]
Hey @acald-creator, I would like to work on this issue. Can you please assign this to me?

**Comment by acald-creator** [comment]
@mak2002 Even though I have not assigned this to you, but I will, have you made any progress since then?

**Comment by mak2002** [comment]
Yes @acald-creator, I have successfully set up the meshery on my machine. And I am learning about Kubernetes and Meshery. To recreate the issue, can you point out how should I create a public design that does not belong to me?

**Comment by Mayaleeeee** [comment]
@acald-creator, is this project still available?

**Comment by om2137** [comment]
@acald-creator I tried to reproduce this issue in dev env, on my local machine. but the catalog button was working fine. is there anything specific I should do to reproduce the issue?

![1](https://user-images.githubusercontent.com/33827410/235374255-36b2e8fc-508c-43d9-a115-a0c3dc3c007d.PNG)
![2](https://user-images.githubusercontent.com/33827410/235374259-3b68434a-b410-4312-8937-d7aff1c0e56f.PNG)
