### ISSUE TITLE
mkdir ../../ui/public: permission denied

### ISSUE THREAD

**Issue by bluedog13** [meshery/meshery#7002]
#### Current Behavior
When I check for meshery logs, I see the below in the logs numerous times
```
mkdir ../../ui/public: permission denied
```

#### Expected Behavior
The error should not exist?

#### Screenshots/Logs

![Screenshot 2023-02-03 at 4 22 17 PM](https://user-images.githubusercontent.com/11997472/216722103-f6eace72-4c03-465e-9ba0-5088719cda83.png)

#### Environment

- **Host OS:** Mac 
- **Platform:**  Kubernetes
- **Meshery Server Version:** v0.6.49	460e9bd4
- **Meshery Client Version:** v0.6.49	460e9bd43

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
Hey @bluedog13 , Thank you for reporting this error. There is a migration going on currently internally and this log is from one of those features which is currently not available to users. It will be fixed by the PR above.
