### ISSUE TITLE
[UI]: MUI Datatable pagination and Rows Per Page is not working 

### ISSUE THREAD

**Issue by anshkush92** [meshery/meshery#7006]
#### Current Behavior

1. Wrong count of the rows in the data table
2. Pagination is not working
3. Rows Per Page changing feature is not working  

#### Desired Behavior

1. Count of the rows in the table should be shown correctly (90 instead of 2 in the below video)
2. Pagination should change the pages in the table 
3. Rows Per Page should change the number of rows in the table 

#### Screenshots/Logs
https://user-images.githubusercontent.com/78142732/216770745-9b61ceae-1707-444a-b985-ab6db97f18c2.mp4

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Pop!_OS 22.04 LTS x86_64
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by anshkush92college** [comment]
@leecalcote, Can you assign this to me? And I have a question regarding this 

1. Do we need to show the designs with private visibility only or both public and private? The count of private visibility only is taken in the table.

**Comment by anshkush92college** [comment]
More changes 
- [ ] Fix table pagination in the configuration/application page
- [ ] Change the patterns to design text in the table after selecting the items in the table

**Comment by arunavabasu-03** [comment]
Can I work on this?
