### ISSUE TITLE
[Server] Designs: New designs not being persisted/created

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7012]
#### Current Behavior
When user creates a new design in the Design Configurator in Meshery UI, their new design is not persisted.

#### Environment

- **Host OS:** Mac
- **Meshery Server Version:** stable-v0.6.49

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
It was a search issue where designs were getting created but not displayed correctly. Fixed in remote provider.
