### ISSUE TITLE
[Docs] Platform Compatibility Matrix: Test Summaries with N/A should not display -100%

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7015]
### Current State
On https://docs.meshery.io/installation/platforms, entries in the Platform Compatibility Matrix with "N/A" test summaries display a tooltip with"-100%".

<img width="346" alt="Screenshot 2023-02-06 at 12 10 09 PM" src="https://user-images.githubusercontent.com/7570704/217051653-6c56462f-68da-451f-9a82-ee527557a2b1.png">

## Desired State
These should display a tooltip with the text "Not Applicable" instead.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ayushthe1** [comment]
Hey @leecalcote I'll take up on this.

**Comment by vishalvivekm** [comment]
Done @leecalcote  
PR #7144  does the job.
