### ISSUE TITLE
[UI] Input fields are not background-aware.

### ISSUE THREAD

**Issue by harkiratsm** [meshery/meshery#7021]
#### Current Behavior

- Input fields are little bit off with respect to background for ```/settings``` page.

![image](https://user-images.githubusercontent.com/71957674/217217738-360516c0-8a81-48e6-aa49-2a6a5d28d4c9.png)

#### Desired Behavior

Tune the input fields, just make it look good on that settings page.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Savio629** [comment]
@harkiratsm Can you explain a bit more regarding the issue?

**Comment by acald-creator** [comment]
There is an open PR already that should fix this.

https://github.com/meshery/meshery/pull/6957

**Comment by acald-creator** [comment]
Fixed based on https://github.com/meshery/meshery/pull/6957
