### ISSUE TITLE
[UI] The text isn't visible properly in dark mode in the catalog section

### ISSUE THREAD

**Issue by Savio629** [meshery/meshery#7025]
#### Current Behavior
If you open the catalog section in the meshery website and then open any of the catalog in the new tab, the "updated and version" text isn't properly visible in dark mode but it work fine in light mode. 
### Dark Mode : 
<img src="https://user-images.githubusercontent.com/91362589/217281326-6bfb7572-1880-4d5a-b9db-e65eacc9394a.jpg" width ="600">

### Light Mode :
<img src="https://user-images.githubusercontent.com/91362589/217281945-5c154ccf-486e-46c1-b23e-92904d99c312.png" width="600">

#### Desired Behavior
Change the text to white in dark mode for better visibility.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Yashsharma1911** [comment]
Hey @Savio629 you can raise issues related to meshery website on its repo [github/meshery.io](https://github.com/meshery/meshery.io)

**Comment by Savio629** [comment]
Oh my bad, sorry for mentioning it in this repo.
