### ISSUE TITLE
[UI] Actions not visible in light mode due to color update in dark mode.

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#7028]
#### Current Behavior
Actions are not visible in light mode due to color updates in dark mode.
![Screenshot from 2023-02-07 23-30-31](https://user-images.githubusercontent.com/65453826/217328466-0184a88a-c3a3-4408-b335-026c3e46a7e5.png)

#### Desired Behavior
Update the colors of the icons so it's visible to the user. 

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment]
// @Harshit-Dandriyal

**Comment by akankshat05** [comment]
I can fix this issue. Please assign.

**Comment by sudhanshutech** [comment]
hey @Chadha93 and @leecalcote if no one is working on this one I could work on this issue

**Comment by sudhanshutech** [comment]
Since it's a small issue i can make it asap

**Comment by anshkush92college** [comment]
Yes you can take it, right now I am not working on it due to exams
Please unassign me

**Comment by sudhanshutech** [comment]
Hey, @leecalcote I made the necessary changes.

**Comment by Nithin1728** [comment]
Hi, If no one is working on this Can I try to fix it?

**Comment by sudhanshutech** [comment]
hey @Nithin1728 I have already fixed it and raising the pr

**Comment by Gauravjadhav22** [comment]
hey @Chadha93,
I want to work on this issue, is anyone already working on this or it has resolved?

**Comment by sudhanshutech** [comment]
> hey @Chadha93, I want to work on this issue, is anyone already working on this or it has resolved?

Hey @Gauravjadhav22 its already an approved pr
