### ISSUE TITLE
[UI] Unwanted artifacts in K8s cluster switcher

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7044]
#### Current Behavior

https://user-images.githubusercontent.com/7570704/217912915-35e8db3a-0cdd-493e-a755-0a5daa115d13.mov

#### Desired Behavior
The k8s logo should always be displayed in its normal form.

#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: edge-v0.6.49
- Platform: Local

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Yashsharma1911** [comment]
Hey @leecalcote I would like to work on this issue

**Comment by Yashsharma1911** [comment]
It looks like it is normal in safari in my local environment

https://user-images.githubusercontent.com/71271069/218045381-82a176f7-2d30-4c0e-8684-8953ca36f4ea.mov

**Comment by ThePiyushAggarwal** [comment]
@Yashsharma1911 
Lee is talking about some other page here. K8s cluster switcher. The icons below the navbar are different as well in his image.
I don't have a KubeConfig file. Going to look into that to be able to find this.

**Comment by ThePiyushAggarwal** [comment]
Hey Lee!

I am not able to find this issue. I installed docker and one K8s cluster is running form docker desktop.
How do I get to the screen that you have shared?
Please help out.

![image](https://user-images.githubusercontent.com/27003616/218261217-7c3a3fd7-8d23-425b-81ed-6d4aaee84e2c.png)

**Comment by ThePiyushAggarwal** [comment]
@leecalcote Please include steps as to how to get to the K8s cluster switcher

**Comment by leecalcote** [comment]
The K8s cluster switcher is the button in the upper right corner with a kubernetes logo on it.
