### ISSUE TITLE
[Docs]"Meshery UI" and "UI" links direct to path `/concepts/architecture/ui` -> returns 404

### ISSUE THREAD

**Issue by b0id** [meshery/meshery#7048]
#### Current State

"Meshery UI" and "UI" links direct to path `/concepts/architecture/ui` -> returns 404 (See attached SS)

![image](https://user-images.githubusercontent.com/115111701/218012005-720ea3ec-b66a-4731-997d-579035959b0e.png)

![image](https://user-images.githubusercontent.com/115111701/218012292-1bc16958-37ed-4204-bbe8-9667e8886dc8.png)

![image](https://user-images.githubusercontent.com/115111701/218012817-13a21af5-86d3-42e5-8456-4f17ba185def.png)

#### Desired State

Unknown.

Quick fix, would be easy for new contributor.

Paths easily pound in meshery docs.

@Chadha93 say where UI link needs to point. 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Sairaviteja27** [comment]
I would like to work on this issue

**Comment by pratik2315** [comment]
Hey there! I'm new to the Meshery community and looking forward to getting involved. Is there any way I could help with this issue?

**Comment by drishtipeshwani** [comment]
I would like to work on this issue

**Comment by vishalvivekm** [comment]
Hi @leecalcote @Chadha93 
can you please assign this issue to me?
