### ISSUE TITLE
[Docs]Dark mode issue in Error code page.

### ISSUE THREAD

**Issue by Harshit-Dandriyal** [meshery/meshery#7049]
#### Current State

![Screenshot from 2023-02-10 20-51-02](https://user-images.githubusercontent.com/56961488/218129075-b3251118-8a87-48c5-9bb0-798002531dc9.png)

#### Desired State

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by shivaams** [comment]
I would like to work on this issue

**Comment by drishtipeshwani** [comment]
Hello, I am interested in working on this issue. I am new to the Meshery community and looking forward to contributing on issues related to ui and documentation.

**Comment by Avi-88** [comment]
Hi, along with the darkmode change, please also look into fixing the label in the table header that is breaking for the error codes column, thanks
