### ISSUE TITLE
[Docs] Rectify Misspelling

### ISSUE THREAD

**Issue by deepakdinesh1123** [meshery/meshery#7057]
#### Current State
In the User Experience ( GUI vs CLI) section in the [docs - contributing to mesheryctl page](https://docs.meshery.io/project/contributing/contributing-cli#user-experience-gui-vs-cli), `mesheryctl` is misspelled as `mesherctl`.

#### Desired State
It should be `mesheryctl`.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by pratik2315** [comment]
Hey there! I would like to work on this issue if its okay

**Comment by leecalcote** [comment]
Thank you, gents.
