### ISSUE TITLE
[Docs] Typo in CONTRIBUTING.md. `ui-setup` needs to change to `ui-build`

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [meshery/meshery#7061]
#### Current State
Go to this link to see the incorrect command mentioned.
https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#build-and-export-ui
![image](https://user-images.githubusercontent.com/27003616/218268288-d63b9734-09f0-4010-9b64-9a59101c0424.png)

#### Desired State
The command should be:
```
make ui-build
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by acald-creator** [comment]
Closing as the appropriate steps are correct.

**Comment by ThePiyushAggarwal** [comment]
![image](https://user-images.githubusercontent.com/27003616/218961325-9ddbdba1-868d-4b0b-bcd6-46f7b22000d2.png)

![image](https://user-images.githubusercontent.com/27003616/218961410-29b65f5e-7328-4c66-b01f-59bbc26d0829.png)

The PR was wrong. The issue isn't.
