### ISSUE TITLE
[Docs] Error code title overflow

### ISSUE THREAD

**Issue by chinu-anand** [meshery/meshery#7063]
#### Current Behavior

The title "Error code" overflows from the table on page https://docs.meshery.io/reference/error-codes

#### Expected Behavior

No overflow.

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/66985303/218291967-30d5e8fc-db47-47e5-a295-40426cdcf371.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Google Chrome
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by chinu-anand** [comment]
I would like to fix this overflow issue.

**Comment by leecalcote** [comment]
Thanks, @chinu-anand
