### ISSUE TITLE
[UI] Dark Mode: Footer styling is incompatible with dark mode

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7070]
#### Current Behavior
<img width="1149" alt="Screenshot 2023-02-12 at 9 05 12 PM" src="https://user-images.githubusercontent.com/7570704/218361365-cdbdded2-a50e-464c-83ca-fd282a835602.png">

#### Desired Behavior
This footer's background should be dark in color when dark mode is enabled.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by pratik2315** [comment]
Hey @leecalcote! Can I work on this issue?

**Comment by leecalcote** [comment]
@pratik2315 sounds good. Will you please confirm:

1) you're able to build and run Meshery UI
2) your proposed approach to conditional logic for light and dark mode styles

**Comment by Yashsharma1911** [comment]
Hey @leecalcote I would like to take this issue

**Comment by pratik2315** [comment]
Hey @leecalcote I am currently having some problems setting up the meshery ui on my machine. I think @Yashsharma1911 would be a better option atm🙂
Will take up some other UI issue once my problem is resolved👍

**Comment by thisiskaransgit** [comment]
Is this what we are looking for?
So I figured out the way to solve it and,  would like to work on this one    

 
 ![Screenshot from 2023-02-15 21-33-53](https://user-images.githubusercontent.com/92504666/219083348-46c13ad0-a025-405c-9666-b632a1c0c536.png)

**Comment by leecalcote** [comment]
Moving through the comments in a FIFO fashion...

**Comment by Yashsharma1911** [comment]
Yes @thisiskaransgit something like this
![Screenshot 2023-02-15 at 10 00 29 PM](https://user-images.githubusercontent.com/71271069/219090040-2b2a5ed7-1a3b-4aa6-8bb6-c63ad765496e.png)
