### ISSUE TITLE
[Docs] Unnecessary scroll bars in code snippets

### ISSUE THREAD

**Issue by chinu-anand** [meshery/meshery#7072]
#### Current Behavior

Scroll bars in code sections even if not needed.

#### Expected Behavior

No scroll bars should be there unnecessarily.

#### Screenshots/Logs

![Screenshot from 2023-02-13 10-46-47](https://user-images.githubusercontent.com/66985303/218376946-3253c9d0-bb9a-4955-afdf-905402aa86bd.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Any
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by chinu-anand** [comment]
@leecalcote Please assign this issue to me, I am willing to solve this. 😄

**Comment by leecalcote** [comment]
@chinu-anand good eye. You're right.
