### ISSUE TITLE
[Docs] Expired link in the docs "guides/mesheryctl/authenticate-with-meshery-via-cli"

### ISSUE THREAD

**Issue by pratik2315** [meshery/meshery#7076]
#### Current State

When we go on the following [page](https://docs.meshery.io/guides/mesheryctl/authenticate-with-meshery-via-cli) and click on "provider":

![image](https://user-images.githubusercontent.com/77961530/218487069-100a67a2-627e-40e0-b959-34cf892f5e1b.png)

The result is the following page:
![image](https://user-images.githubusercontent.com/77961530/218487729-7d3bde58-7957-4e7a-a478-93672ecc8700.png)

Don't know if it's a docs related issue or a UI related one

#### Desired State

Should be redirected to the correct page

#### Environment

- Browser: Chrome
- Host OS: Windows
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by pratik2315** [comment]
I would love to work on this issue if approved😀

**Comment by leecalcote** [comment]
Thanks, Pratik. You'll update to https://docs.meshery.io/extensibility/providers, I'm hoping.

**Comment by pratik2315** [comment]
Extremely sorry for the extra PR @leecalcote. I was unable to solve DCO conflicts in the first one😅 I have added the correct link in the next PR. Thanks a lot for your patience.
