### ISSUE TITLE
[Docs] How to create a new Meshery integration

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#7081]
#### Current State
Meshery, as an extensible tool, is in process to support multiple integration points for external systems with their own credentials, type, subtype, etc

#### Desired State
Document the process for any system to be plugged into Meshery as an integration.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Kasambx** [comment]
Hello kindly assign me to this one.

**Comment by 123Vasu** [comment]
I would like to work on this @leecalcote

**Comment by money8203** [comment]
@Chadha93
