### ISSUE TITLE
[UI] Dashboard layout not quite right.

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#7086]
#### Current Behavior

Previously, the Dashboard had a fairly even layout that showcase the Workloads and the Connection Status.

Right now, it is a bit off in these sections.
![offwhite](https://user-images.githubusercontent.com/18711313/218898090-07b1af9a-7ba6-4988-a242-5670cf34a031.png)

Also the footer seemed to be larger than normal.
![full](https://user-images.githubusercontent.com/18711313/218898578-46b8fdb4-d22b-4a46-aec2-0ae3bc082633.png)

#### Desired Behavior

This needs to be changed to what it was before, if it was changed, or updated to reflect the correct background color in the div areas for Workloads / Connection Status.

The footer area needs to be fixed as well.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
This is a fairly recent bug. Thank you for opening this issue.

**Comment by KlausMikhaelson** [comment]
Hey @leecalcote can I work on this issue ?

**Comment by acald-creator** [comment]
I'm going to work on this, as there are some small issues that needs to be fixed in the same PR.

**Comment by Yashsharma1911** [comment]
Hey @acald-creator this is also causing problems in meshMap and it turns out it is because the background-color property is set to body `#fafafa` which should be `#eaeff1`

**Comment by leecalcote** [comment]
We're in need of having this issue resolved quickly. @acald-creator, I wonder if you have identified the root cause, yet?

**Comment by leecalcote** [comment]
@KlausMikhaelson, please do offer a helping hand, if you can.

**Comment by acald-creator** [comment]
Currently working on this, hope to have something asap.
