### ISSUE TITLE
[Docs] Styles not applied to search bar 

### ISSUE THREAD

**Issue by VIKAS0264** [meshery/meshery#7106]
#### Current State
styles are not applied to search field
![Screenshot from 2023-02-17 09-57-19](https://user-images.githubusercontent.com/71399937/219608091-9a93dabc-9b7d-40a0-a348-a1d7878dedc5.png)

#### Desired State

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by VIKAS0264** [comment]
the search form styles were present in main.css but it was not linked so i linked it there are more issues in this page i'm currently working on them.

**Comment by deepakdinesh1123** [comment]
@VIKAS0264 Could you please update the title of the issue to describe what the problem is?
