### ISSUE TITLE
[provider-ui] Meshery provider missing in the drop down menu in Docker image

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#7114]
#### Current Behavior

When I was building the Meshery docker image, I wasn't seeing the Provider's drop down menu showing Meshery.

After running `npm run lint`, there is a lint error that came up regarding the placement of `<title>` in `_document.js`.

This title is already placed in `_app.js` as suggested from at this link: https://nextjs.org/docs/messages/no-document-title

The lint error message returns this message: `<title> should not be used in _document.js's <Head>`

The error message and suggested remediation from Next.js states the following:

[Why This Error Occurred](https://nextjs.org/docs/messages/no-document-title#why-this-error-occurred)

Adding <title> in pages/_document.js will lead to unexpected results with next/head since _document.js is only rendered on the initial pre-render.

#### Desired Behavior

We should remove this altogether, or possibly ignore this rule.

As a reminder, `provider-ui` is setup to ignore `eslint` linting during `npm run build` so this stage will ignore linting and will continue building as if there are no linting errors.

Removing this line in `_document.js` and leaving as is in `_app.js` ran successfully. 

However there is still issues, so I'm researching on what else can be fixed to make sure that it runs properly via Docker, instead of locally. Locally, it was successfully ran to pull in Meshery as the provider in the drop down menu.

#### Screenshots/Logs

Here is the screenshot after build docker image.

![Screenshot from 2023-02-18 14-39-59](https://user-images.githubusercontent.com/18711313/219897889-ceba3a02-645a-4974-98e2-8739e82e0463.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Nikhil-Ladha** [comment]
Huh, the title tag was added recently by me in mh last PR. I didn't know that was incorrect. Removing the title from the _document.js file is a good idea.
