### ISSUE TITLE
[Docs] Incorrect link usage in Build and release docs

### ISSUE THREAD

**Issue by pratik2315** [meshery/meshery#7126]
#### Current State

The following link in [Build & release docs](https://docs.meshery.io/project/contributing/build-and-release) is incorrect/inactive:

![image](https://user-images.githubusercontent.com/77961530/220191497-39728eb8-dc24-4dab-8514-40d9e97dab9e.png)

#### Desired State

If I'm correct, the link must be replaced with the link that leads to the following page:
![image](https://user-images.githubusercontent.com/77961530/220191599-d76fb97b-c8d1-4d01-bbdf-d2b90bc30ebc.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by pratik2315** [comment]
Hello there everyone! I would love to work on this issue if approved by maintainers😀
Thanks a lot.

**Comment by leecalcote** [comment]
Thank you, @pratik2315 👍
