### ISSUE TITLE
[UI] Notification Center button only actives on click of icon, not on click of button

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7132]
#### Current Behavior
Please see the screen recording for a demonstration of the behavior.

#### Desired Behavior
The entire button should be clickable and activate the notification center sidebar.

#### Screenshots/Logs

https://user-images.githubusercontent.com/7570704/220229090-50487b2a-2bcd-4425-bedc-0667e87ebe91.mov

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by TheOjasSingh** [comment]
Hi, @leecalcote I want to work on this issue can you assign this issue to me?

**Comment by rinkuhasija** [comment]
@leecalcote  In the local env, it's working absolutely fine. There might be some issue with the currently deployed version of playground.

See Here  ⬇️⬇️

https://user-images.githubusercontent.com/52361778/220479027-f4ba2a85-192d-41d8-94e1-6a607e949166.mp4

**Comment by sidtohan** [comment]
@rinkuhasija yeah I also saw that, but the settings button still seems to have this issue. Try checking that. Apparently only the icon responds to clicks in case of the settings button.
