### ISSUE TITLE
[Docs] Some links redirect to deleted google docs document

### ISSUE THREAD

**Issue by pratik2315** [meshery/meshery#7138]
#### Current State

These two links in the [community docs](https://docs.meshery.io/project/community#getting-involved-in-the-community) lead to a deleted google docs document:

![image](https://user-images.githubusercontent.com/77961530/220339883-f5468728-6301-4ffa-818d-2a725fabcf8e.png)

The result is:

![image](https://user-images.githubusercontent.com/77961530/220340052-3c546b1d-7f5c-44ca-aba6-c26d9189c83c.png)

#### Desired State

The page should be redirected to a valid link/google docs document
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by pratik2315** [comment]
Hello @leecalcote! I was not able to find the correct document link for this issue. Can you please provide the link, or if there's some issue with the previous document, I would love to work on creating a new document for this issue😃

**Comment by pratik2315** [comment]
Hey @UtkarshMishra12! Can you provide the correct me the correct document for this issue. Thanks

**Comment by UtkarshMishra12** [comment]
Hey @pratik2315 you can replace it with this [link](https://layer5.io/community/newcomers)

**Comment by vishalvivekm** [comment]
done by #7169
