### ISSUE TITLE
[UI] page not found page does not support dark mode

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#7140]
#### Current Behavior

page not found page does not support dark mode 

![Screenshot 2023-02-21 at 5 53 50 PM](https://user-images.githubusercontent.com/71271069/220349270-c4c29076-9884-4503-94d9-006d6ac46c9a.png)

#### Desired Behavior
It should contain dark theme background color and text

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by yash37158** [comment]
I would like to work on this issue

**Comment by Yashsharma1911** [comment]
sure that would be great @yash37158 
// @Chadha93

**Comment by yash37158** [comment]
can you please share on which page you are getting this error?

**Comment by Yashsharma1911** [comment]
Hey @yash37158 I just randomly clicked on something I didn't know and got this error

**Comment by yash37158** [comment]
@leecalcote @Chadha93  can you elaborate on this issue ?

**Comment by Yashsharma1911** [comment]
@yash37158 we got this not found error page whenever we go to an unexpected route like this one in below image 
![Screenshot 2023-02-22 at 3 29 39 PM](https://user-images.githubusercontent.com/71271069/220586837-8aba8552-d7e2-4bc7-9c56-ce4ca187cba9.png)

**Comment by yash37158** [comment]
is the endpoint we are trying to reach is correct?

**Comment by Yashsharma1911** [comment]
I put the wrong path intentionally because the issue here is not about whether we are reaching the correct path or not but it is about the error page that it should be dark mode compatible which it is currently not as you can see `white` background in error page

**Comment by yash37158** [comment]
Ohkay make more sense, I'll look into that

**Comment by yash37158** [comment]
do we have any Figma design for the error page in dark mode ?

**Comment by leecalcote** [comment]
We don't. It wouldn't hurt to have one. With that said, the background of this component/section should be set to use the dark mode theme color just like other components and so should the "Page does not exist" font.

**Comment by yash37158** [comment]
okay Thanks @leecalcote

**Comment by yash37158** [comment]
Is this look good? @leecalcote @Yashsharma1911 <br>
<img width="500" alt="Screenshot 2023-02-24 at 12 22 40 AM" src="https://user-images.githubusercontent.com/68152307/221003036-9a20df4e-b73a-4916-bea0-9639fe9a4dbc.png">
