### ISSUE TITLE
[UI] Consecutive clicks on the K8sContextMenu icon and Settings icon respectively breaks the UI

### ISSUE THREAD

**Issue by krishna9304** [meshery/meshery#7145]
#### Current Behavior

Consecutive clicks on the `K8sContextMenu` icon and `Settings` icon respectively breaks the UI.

#### Desired Behavior
Clicking onto the `Settings` icon when `K8sContextMenu` is open, `K8sContextMenu` should close by capturing "Outside Click" mouse event.

#### Screenshots

https://user-images.githubusercontent.com/71918441/220446445-9b21b24f-2397-4d6e-a6d1-5b5b335c76d9.mov

#### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by krishna9304** [comment]
@leecalcote I'd like to work on this.

**Comment by leecalcote** [comment]
Thanks for documenting and volunteering, @krishna9304 👍
