### ISSUE TITLE
[Docs][Dark Mode] Copy icon is not visible in code snippets in dark mode

### ISSUE THREAD

**Issue by VIKAS0264** [meshery/meshery#7150]
#### Current State
# copy icon in lite mode
![Screenshot from 2023-02-22 17-53-04](https://user-images.githubusercontent.com/71399937/220619360-affc0dfd-89c2-4c66-8ca3-cc1dfd35e064.png)
# copy icon in dark mode
![Screenshot from 2023-02-22 17-52-48](https://user-images.githubusercontent.com/71399937/220619304-1f27a783-4404-4dff-ba7b-ec7c048708fc.png)

#### Desired State
# it should be visible in dark mode

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by rinkuhasija** [comment]
@deepakdinesh1123 I have already found a fix for this, can I issue a pull request If you don't mind @VIKAS0264

**Comment by VIKAS0264** [comment]
Hey @rinkuhasija if you have found the fix already then go ahead, if not please let me know i'm working on it.

**Comment by chinu-anand** [comment]
@VIKAS0264 Don't create duplicate issues. Issue #7120 already addresses this problem. You should close this one.
