### ISSUE TITLE
[UI] Footer Snackbar uses dark image in the dark mode 

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery#7154]
#### Current Behavior

 - Steps to Reproduce 
 1. Enable Dark mode 
 2. Click on the Footer content  `Built with 🤍 by layer5 community`
 
 Here the image used is for the light theme and doesn't go well in the dark mode.

#### Desired Behavior

The image should be changed with the respect to the theme used and also the color of the hyperlink used in dark mode can be changed to something light.

#### Screenshots/Logs

![Screenshot from 2023-02-22 17-34-37](https://user-images.githubusercontent.com/92504666/220659524-5e46ade5-d0a4-4d98-853f-2935b280efc4.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS:  Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by TheOjasSingh** [comment]
Hi, @thisiskaransgit can you share the link where you are facing the issue.

**Comment by thisiskaransgit** [comment]
@TheOjasSingh if you have set up the development environment, follow the steps that I have mentioned to reproduce the bug

**Comment by Shivam164** [comment]
Hey @thisiskaransgit, I want to work on this issue.

**Comment by Yashsharma1911** [comment]
closing this issue as it has solved
