### ISSUE TITLE
[UI] Extensions: Enhance logic to include user's/provider's capabilities

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7155]
#### Current Behavior
Whether users have access to a particular extension or not, they are shown the same message to "sign up".

<img width="510" alt="Screenshot 2023-02-22 at 9 23 05 AM" src="https://user-images.githubusercontent.com/7570704/220743066-30897446-1c7f-4f84-a181-74b953c878a6.png">

#### Desired Behavior
If the remote provider for the currently logged in user offers the extension/the capability, (if the user has already signed up and has access), then the "Sign Up" button should be disabled.

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by krishna9304** [comment]
@leecalcote Please assign me this issue.
