### ISSUE TITLE
[UI] - Version table misaligned cells

### ISSUE THREAD

**Issue by gurpreet-legend** [meshery/meshery#7158]
#### Current Behavior
In this version table, each cell is misaligned [page](https://docs.meshery.io/project/releases)

#### Desired Behavior
Each cell should be center aligned
#### Screenshots/Logs
![image](https://user-images.githubusercontent.com/75157493/220776788-b27671e5-f5ad-4bc6-8563-428bd0ffbe07.png)

#### Environment

- Browser: Chrome
- Host OS: Windows

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks, @gurpreet-legend

**Comment by sudhanshutech** [comment]
If no one is working on this issue, can I @leecalcote  @gurpreet-legend?

**Comment by gurpreet-legend** [comment]
> If no one is working on this issue, can I @leecalcote  @gurpreet-legend?

I'll be soon raising a PR for this @sudhanshutech
