### ISSUE TITLE
[UI] - Content field is empty 

### ISSUE THREAD

**Issue by gurpreet-legend** [meshery/meshery#7159]
#### Current Behavior
In the top right corner, the tools card has content section empty.

#### Desired Behavior
Either it should be removed or some other links could be added.

#### Screenshots/Logs
![image](https://user-images.githubusercontent.com/75157493/220777718-78e24d6e-083d-47b7-97e0-be81a608268b.png)

#### Environment

- Browser: Chrome
- Host OS: Windows

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
In the event a page doesn't have internal headings (and no links to display under "Content"), the "Content" heading in this intra-page navigation sidebar can be hidden from view.

**Comment by gurpreet-legend** [comment]
> In the event a page doesn't have internal headings (and no links to display under "Content"), the "Content" heading in this intra-page navigation sidebar can be hidden from view.

Yeah sure, will fix this

**Comment by money8203** [comment]
@gurpreet-legend any update on the issue ?

**Comment by gurpreet-legend** [comment]
> @gurpreet-legend any update on the issue ?

This issue has already been solved by #7307

**Comment by money8203** [comment]
@vishalvivekm can you please close this issue as completed!!

**Comment by vishalvivekm** [comment]
done by #7307
