### ISSUE TITLE
[UI] meshmap troubleshooting guide incomplete in dark mode

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#7161]
#### Current Behavior

Currently, if you were having an issue with MeshMap plugin not loading, you will get the troubleshooting guide.

The dark mode is still incomplete and will need to be fixed.

#### Screenshots/Logs

![Web capture_22-2-2023_212153_localhost](https://user-images.githubusercontent.com/18711313/220814683-952334a8-6ca0-4aeb-82e3-6ae14cb40ddc.jpeg)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by MohitBansal321** [comment]
> #### Current Behavior
> Currently, if you were having an issue with MeshMap plugin not loading, you will get the troubleshooting guide.
> 
> The dark mode is still incomplete and will need to be fixed.
> 
> #### Desired Behavior
> #### Screenshots/Logs
> ![Web capture_22-2-2023_212153_localhost](https://user-images.githubusercontent.com/18711313/220814683-952334a8-6ca0-4aeb-82e3-6ae14cb40ddc.jpeg)
> 
> #### Environment
> * Browser: Chrome Safari Firefox
> * Host OS: Mac Linux Windows
> * Meshery Server Version: stable-v
> * Meshery Client Version: stable-v
> * Platform: Docker Kubernetes
> 
> #### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/handbook)
> * 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
> * 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
> * 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.meshery.io) and [Community Slack](http://slack.meshery.io)

can you provide the ways to reproduce it
