### ISSUE TITLE
[UI] - Architecture Components table misaligned cells

### ISSUE THREAD

**Issue by MohitBansal321** [meshery/meshery#7164]
#### Current Behavior
Some cells are misaligned

#### Desired Behavior
All cells are aligned to the same pattern 

#### Screenshots/Logs

![Screenshot 2023-02-23 130113](https://user-images.githubusercontent.com/78220157/220844649-99744413-14c0-42d2-9dd1-c3302f00e8e9.png)
https://docs.meshery.io/concepts/architecture
#### Environment

- Browser: Edge
- Host OS: Windows

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Anand-Theertha** [comment]
Hello @Chadha93 @MohitBansal321 I would like to work on this!

**Comment by MohitBansal321** [comment]
yes you can work on it

> Hello @Chadha93 @MohitBansal321 I would like to work on this!

**Comment by leecalcote** [comment]
@MohitBansal321 thanks for this issue, but the indented items under Meshery Operator is intentional. These are sub-components and meant to be indented.
