### ISSUE TITLE
[UI]-Issue with Dark mode

### ISSUE THREAD

**Issue by parmishh** [meshery/meshery#7167]
#### Current Behavior
**on clicking the logo at bottom made with love its fine. 
But under dark mode the Meshery text seems to like mixed with background**

<img width="451" alt="2" src="https://user-images.githubusercontent.com/91942072/220915466-fdb9472e-e147-4231-abf7-f07302633f51.PNG">

#### Desired Behavior
**The text color must be changed  to make it more visible**

it seems I can solve this issue. so I need to be assigned for that @leecalcote 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks, @parmishh

**Comment by parmishh** [comment]
This issue was solved
