### ISSUE TITLE
Search bar UI should improve and text not visible in dark mode in doc

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#7172]
#### Current Behavior

Text input is not visible under dark mode and the UI of the search bar should be improved.
#### Expected Behavior

The text should be black in color in dark mode and the UI of the search bar should look similar like 
![image](https://user-images.githubusercontent.com/90546692/220968978-f44c3f02-6176-48cc-bdba-79779852dfe9.png)
as it is in the sidebar because it would be attractive

#### Screenshots/Logs

Current behavior
![image](https://user-images.githubusercontent.com/90546692/220968493-5bc4a0bb-2ea6-4443-8fc5-dcbd514a5db3.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by rinkuhasija** [comment]
@sudhanshutech  I am working on this Issue. Can you assign this to me please ? I'll fix this ASAP.

**Comment by rinkuhasija** [comment]
Looks like this issue is already discussed in #7106 .
Should I close my PR.
If so, please delete this issue. I can create conflict.

@sudhanshutech 
@leecalcote

**Comment by VIKAS0264** [comment]
hey @sudhanshutech I've already created this issue here #7106 could you please close this issue.

**Comment by sudhanshutech** [comment]
ok, @VIKAS0264 and @rinkuhasija since this issue has been already discussed so I am closing this issue.
