### ISSUE TITLE
[mesheryctl] mesheryctl system check command does not support the operator flag

### ISSUE THREAD

**Issue by deepakdinesh1123** [meshery/meshery#7178]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Desired Behavior
Support running operator health checks across different clusters

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by deepakdinesh1123** [comment]
@MUzairS15 @Revolyssup

**Comment by leecalcote** [comment]
Thank you, @deepakdinesh1123

**Comment by gurpreet-legend** [comment]
@leecalcote @deepakdinesh1123 can I work on this issue?
I have gone through the meshery setup and can start working on it, just I need some light on the issue itself as there is very minimal description on it.

**Comment by suhail34** [comment]
The unmarshalling issue is due to this endpoint /api/system/kubernetes/contexts as this returns {"page_size":10} [reference](https://pkg.go.dev/github.com/meshery/meshery/server/models#MesheryApplicationPage)

**Comment by alphaX86** [comment]
@suhail34 you're cleared to engage in this issue

**Comment by leecalcote** [comment]
@abdullah1308 fyi
