### ISSUE TITLE
[Docs] Publish the table in the spreadsheet to Meshery Docs.

### ISSUE THREAD

**Issue by mpratham216** [meshery/meshery#7179]
Publish the table in the [spreadsheet](https://docs.google.com/spreadsheets/d/1VQuhCVgSZ8hqrfVBFCpjnkBAojrgJTe_Hp0EBuBcQWw/edit#gid=0) into the Meshery [Docs](https://docs.meshery.io/concepts/architecture).

**Comment by vishalvivekm** [comment]
shall I go ahead with this @mpratham216 @leecalcote
