### ISSUE TITLE
[Docs] Set dark mode as the default Meshery Docs theme

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7190]
#### Current State
Currently, light mode is the default.

#### Desired State
Dark mode, baby. Dark mode.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sudhanshutech** [comment]
I would like to work on this @leecalcote

**Comment by 123Vasu** [comment]
I would like to work on this @leecalcote

**Comment by leecalcote** [comment]
Sounds real good, @sudhanshutech

**Comment by leecalcote** [comment]
Thank you, @123Vasu

**Comment by sudhanshutech** [comment]
@leecalcote I have made the necessary changes. You can have a look

**Comment by vishalvivekm** [comment]
Can you please assign this issue to me @leecalcote
