### ISSUE TITLE
Icons not aligned properly in readme

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#7195]
#### Current Behavior

The community icon and  slack icon are not aligned properly in the readme as per other readmes
#### Expected Behavior

The icons could be aligned like
![image](https://user-images.githubusercontent.com/90546692/221376382-c508ab6b-9266-4fa2-b604-a35de2ccb14e.png)

#### Screenshots/Logs

The problem is 
![image](https://user-images.githubusercontent.com/90546692/221376334-a2506462-401a-4471-bd3b-f3f128ddfbab.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sudhanshutech** [comment]
I can work in this issue

**Comment by Yashsharma1911** [comment]
sure go ahead @sudhanshutech
