### ISSUE TITLE
[UI] Cannot see selected adaptor in dark mode

### ISSUE THREAD

**Issue by Shivam164** [meshery/meshery#7197]
#### Current Behavior
After choosing one of the adaptors from the drop-down, we cannot see the selected adaptor in dark mode.

To see this, go to settings and then to the adapter section.

#### Desired Behavior
The color of the text should be changed in order to make it visible.

#### Screenshots/Logs
![Screenshot from 2023-02-26 09-27-06](https://user-images.githubusercontent.com/77626594/221391649-0761ec4c-05dd-488b-a02c-7b171496a35b.png)

#### Environment

- Browser: Chromium
- Host OS: Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by melsonic** [comment]
I want to work on this one. Please assign me.

**Comment by Yashsharma1911** [comment]
Yes, this needs a fix @Shivam164 would you like to work on this?

**Comment by Shivam164** [comment]
@Yashsharma1911 yeah sure I would love to work on it.

**Comment by Yashsharma1911** [comment]
go ahead @Shivam164 and thanks for raising your hand @melsonic we have other dark-mode related issues where you can help
