### ISSUE TITLE
[Docs]Dark mode icon in docs in dark mode

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#7208]
#### Current State
In dark mode, the icon is the same as in light mode (the sun icon)
![image](https://user-images.githubusercontent.com/90546692/221476520-b9c6400f-0752-44c3-954b-17f31e62c9cb.png)

#### Desired State
The icon in dark mode should be the dark mode icon as in other websites
![image](https://user-images.githubusercontent.com/90546692/221476840-d569a917-794f-4f2f-9bd6-ddbe82a55cb3.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by akarsh-jain-790** [comment]
@sudhanshutech  I would like to work on this issue.

**Comment by adityakanu** [comment]
@sudhanshutech which page has the issue?

**Comment by MathurUtkarsh** [comment]
@sudhanshutech I would like to work on this issue.

**Comment by sudhanshutech** [comment]
> @sudhanshutech which page has the issue?

Its in meshery docs

**Comment by vishalvivekm** [comment]
closed this as completed in #7248
