### ISSUE TITLE
[Docs] Change color on hover for hyperlinks.

### ISSUE THREAD

**Issue by rinkuhasija** [meshery/meshery#7226]
#### Current State
There is no color change hover property set for hyperlinks. 

#### Desired State
Should display Caribbean green (#00D3A9) color on hover for hyperlinks.

keep the following in mind : 

1. There is a light-mode appropriate color used.
2. Other tag classes like those used for the sidebar menu and global nav menu and so on, should not be affected.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@vishalvivekm

**Comment by rinkuhasija** [comment]
@leecalcote  I would like to work on this issue. Please assign it to me.

**Comment by leecalcote** [comment]
@rinkuhasija, ha! I thought this was the PR for the change, so I tagged, @vishalvivekm for a review.
