### ISSUE TITLE
[Docs]Position of icons in codeblock of docs

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#7229]
#### Current State
Currently when opening the side bar the icons of codeblock are above the side bar like [page](https://docs.meshery.io/installation/quick-start) and also scrolling as we move down.

https://user-images.githubusercontent.com/90546692/222105208-f2fb818d-b71b-4a52-9e7b-0a8dc7a749b3.mp4

![image](https://user-images.githubusercontent.com/90546692/222105762-3bada640-07f0-4d96-92ec-66dc5a80358e.png)

#### Desired State
The icons should be below the sidebar

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by rinkuhasija** [comment]
hey @sudhanshutech, does this issue also exist on any other page, or does only the page you mentioned here (https://docs.meshery.io/installation/quick-start) has the issue?

**Comment by sudhanshutech** [comment]
Hey @rinkuhasija, I am working on this issue.

**Comment by sudhanshutech** [comment]
Hey @leecalcote can you please assign it to me

**Comment by leecalcote** [comment]
@sudhanshutech you might have been hasty in your reading of @rinkuhasija question, which is helpful and valid. I'll let you re-respond prior to issue assignment. When you do respond, please include your propose aproach to solving this issue. The answer to @rinkuhasija's question bears much weight on the approach.

**Comment by sudhanshutech** [comment]
Oh okay I misunderstood that @leecalcote and @rinkuhasija my mistake, so @rinkuhasija I found this bug as of now only in the **Quick start page** rest pages have another UI of the clipboard. So in this clip board the 3 dot and copy icons should have position relative to the side bar.

**Comment by sudhanshutech** [comment]
@leecalcote I want to work on this

**Comment by leecalcote** [comment]
@sudhanshutech will you confirm whether this bug persists or has already been resolved?

**Comment by sudhanshutech** [comment]
> @sudhanshutech will you confirm whether this bug persists or has already been resolved?

yes it still persist, but it won't if get this [PR](https://github.com/meshery/meshery/pull/7264) merged

**Comment by SoumyadeepOSD** [comment]
Can I work on this issue?

**Comment by sudhanshutech** [comment]
Thanks @SoumyadeepOSD but the issue have been resolved , so closing this one
