### ISSUE TITLE
Add ability to disable the operator for a given meshconfig context

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#7233]
#### Current Behavior

Currently the support is added for disabling the operator at Meshery server boot time. There are no other nobs and dials for it as of now.
#### Desired Behavior

Add support to make it configurable from meshconfig per kubernetes context that Meshery detects.
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Revolyssup I have added the appropriate labels.
