### ISSUE TITLE
[Docs] New Link: "Create a new child page"

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7252]
#### Current State
Meshery Docs is missing a hyperlink that allows contributors to conveniently create a new docs page based on their current location in the docs.

#### Desired State

Ideally, a new link "Create new page" is available on each docs page like in the screenshot.

<img width="501" alt="Screenshot 2023-03-01 at 10 30 47 PM" src="https://user-images.githubusercontent.com/7570704/222331904-ea814088-9679-4a9f-923e-edea1fba2afa.png">

Use the following hyperlink format to create a dynamic link that will create a new docs file:

```
https://github.com/meshery/meshery/docs/<path to current file>?filename=change-me.md&value=---%0Atitle%3A+%22Long+Page+Title%22%0AlinkTitle%3A+%22Short+Nav+Title%22%0Aweight%3A+100%0Adescription%3A+%3E-%0A+++++Page+description+for+heading+and+indexes.%0A---%0A%0A%23%23+Heading%0A%0AEdit+this+template+to+create+your+new+page.%0A%0A%2A+Give+it+a+good+name%2C+ending+in+%60.md%60+-+e.g.+%60getting-started.md%60%0A%2A+Edit+the+%22front+matter%22+section+at+the+top+of+the+page+%28weight+controls+how+its+ordered+amongst+other+pages+in+the+same+directory%3B+lowest+number+first%29.%0A%2A+Add+a+good+commit+message+at+the+bottom+of+the+page+%28%3C80+characters%3B+use+the+extended+description+field+for+more+detail%29.%0A%2A+Create+a+new+branch+so+you+can+preview+your+new+file+and+request+a+review+via+Pull+Request.%0A
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sanyamjain036** [comment]
I can to work on it, May you give me one example of it?

**Comment by leecalcote** [comment]
@sanyamjain036 tha me for volunteering. If you’re not able to do a functional hyperlink, given the example above, then there’s little chance that you will be able to figure out the rest of what is needed to implement this feature. I encourage you to try, though, despite the issue not being assigned to you.

**Comment by vishalvivekm** [comment]
@leecalcote submitting a PR real quick for this!
