### ISSUE TITLE
[UI] meshmodel summary still uses white background in dark mode, hiding the heading as well

### ISSUE THREAD

**Issue by sidtohan** [meshery/meshery#7258]
#### Current Behavior

Right now, if you enable dark mode and go to the meshmodel summary tab, it appears to use white background and that causes the heading(which is also in white) to be hidden. The report overall also looks out of place.

#### Desired Behavior

The background should be some shade of gray or black, which can be decided via discussion.

#### Screenshots/Logs

![issue](https://user-images.githubusercontent.com/82583557/222454159-a7b54488-d2d7-4186-a4f7-0837e9893da3.png)

#### Environment

- Browser: Firefox
- Host OS: Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sidtohan** [comment]
@leecalcote if its alright, can I work on this?

**Comment by soham4abc** [comment]
According to the latest build the screen looks like this for me:
![image](https://user-images.githubusercontent.com/63705023/222456208-88bd63c1-e925-4a20-8379-585d983b659c.png)

**Comment by sidtohan** [comment]
That's strange. May I ask what browser you are using @soham4abc ?

**Comment by soham4abc** [comment]
> That's strange. May I ask what browser you are using @soham4abc ?

I am using Firefox in a Linux enviornment

**Comment by sidtohan** [comment]
I see. It may be a cache issue on my side. I'll try using chrome.

**Comment by sidtohan** [comment]
I still face this issue even on chromium. I double checked and my local branch is up to date. I guess there is some issue on my side. Just to be double sure, can you please share the commit checksum of your local branch? I will try changing HEAD for confirming this. @soham4abc.

**Comment by sidtohan** [comment]
@soham4abc in your screenshot you seem to be using v0.5.15, whereas the version on my repo is 0.6.59, which is the latest. Can you double check your branch? Sorry for disturbing.

![ss](https://user-images.githubusercontent.com/82583557/222461564-0fe70029-ffc7-4314-9481-006ee69b00fa.png)

**Comment by soham4abc** [comment]
I am currently in master branch and the latest commit is : 531a17a10c77444060fdffb558bc04456764a81b

@sidtohan

**Comment by sidtohan** [comment]
> I am currently in master branch and the latest commit is : [531a17a](https://github.com/meshery/meshery/commit/531a17a10c77444060fdffb558bc04456764a81b)
> 
> @sidtohan

Hmm so we are indeed on the same commit. But the version on yours is different(the website I mean, it shows something else). I am somewhat new here, so I wanna ask does that version(0.5.15) actually matter for the UI, or is it for something internal?

**Comment by soham4abc** [comment]
> > I am currently in master branch and the latest commit is : [531a17a](https://github.com/meshery/meshery/commit/531a17a10c77444060fdffb558bc04456764a81b)
> > @sidtohan
> 
> Hmm so we are indeed on the same commit. But the version on yours is different(the website I mean, it shows something else). I am somewhat new here, so I wanna ask does that version(0.5.15) actually matter for the UI, or is it for something internal?
@leecalcote  Would you please look into this issue??

**Comment by acald-creator** [comment]
Mine is showing the latest build with the Dark Mode affecting the MeshModel summary.

My version is showing `edge-latest` from the Docker build.

![image](https://user-images.githubusercontent.com/18711313/222548448-8c718fb4-5d8a-41ef-b153-e27a43ce771a.png)

**Comment by acald-creator** [comment]
I'm comparing the difference between `master` and tag `v0.6.59` as there may be some differences.

**Comment by sidtohan** [comment]
@acald-creator it seems to have gotten fixed now. I suppose it was an issue on my side. I recently cloned my fork again and after making another static build it worked fine. Now, it works fine for both the UI dev server and the server, so I'd like to close this issue if it's alright with you.
Thanks.

**Comment by acald-creator** [comment]
Sure!
