### ISSUE TITLE
[UI]-Hyperlink under dark mode not visible 

### ISSUE THREAD

**Issue by parmishh** [meshery/meshery#7265]
#### Current Behavior
The Hyperlink is not properly visible under dark mode.
<img width="505" alt="raw" src="https://user-images.githubusercontent.com/91942072/222648138-046dcae1-a1cf-4265-9497-555ebd4ed0f2.PNG">

#### Desired Behavior
Color should be changed to make it visible
<img width="752" alt="update" src="https://user-images.githubusercontent.com/91942072/222648146-b83da19e-5120-43c4-b2f0-ced53fd1efc1.PNG">

I have sucessfully made the changes @leecalcote just need your permission to PR can you please assign me.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by parmishh** [comment]
@Chadha93 I have made a PR and it looks good and matching with the theme both in dark and light mode so I have not made further changes could you review.
<img width="752" alt="update" src="https://user-images.githubusercontent.com/91942072/222653557-82fa7079-f034-472c-9259-b5b006447144.PNG">

<img width="461" alt="update2" src="https://user-images.githubusercontent.com/91942072/222653769-8c4458c4-b230-421d-82d0-aa73398a138f.PNG">

**Comment by Chadha93** [comment]
> @Chadha93 I have made a PR and it looks good and matching with the theme both in dark and light mode so I have not made further changes could you review. <img alt="update" width="752" src="https://user-images.githubusercontent.com/91942072/222653557-82fa7079-f034-472c-9259-b5b006447144.PNG">
> 
> <img alt="update2" width="461" src="https://user-images.githubusercontent.com/91942072/222653769-8c4458c4-b230-421d-82d0-aa73398a138f.PNG">

@parmishh Please post this under the PR, let's follow up there.
