### ISSUE TITLE
[UI] improve the positon and spacing of icons in the UI

### ISSUE THREAD

**Issue by sidtohan** [meshery/meshery#7269]
#### Current Behavior

While most of the icons are placed perfectly fine in the UI, there are some which are aligned in the wrong way, or have wrong amount of spacing.

#### Desired Behavior

The icons should be aligned properly and also have proper spacing to ensure the UI looks clean and polished.
For example:
Current: 
![i2](https://user-images.githubusercontent.com/82583557/222787925-67291747-937f-4f40-a3a6-4b313fda2a9a.png)

Possible Improvement:
![i3](https://user-images.githubusercontent.com/82583557/222787967-24dd1329-ac26-4468-9691-70cefc90cc3f.png)

#### Implementation

1. Identifying the icons which are wrong( already few examples are here, like the "heart" shape of the footer)
2. Applying styles that make the icons properly spaced and aligned.

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Yashsharma1911** [comment]
thanks for opening up the issue @sidtohan yes you can go ahead
