### ISSUE TITLE
[Docs] Update alignment of icon in Meshery Operator page 

### ISSUE THREAD

**Issue by Ambareen09** [meshery/meshery#7279]
#### Current State

![Screenshot from 2023-03-05 13-59-22](https://user-images.githubusercontent.com/64471630/222950153-5422aac5-b001-4a0a-9ff8-2c3220a2c6b6.png)

#### Desired State
![Screenshot from 2023-03-05 14-00-25](https://user-images.githubusercontent.com/64471630/222950177-5c94fd10-a7b0-4c4e-9aad-9c9e165fc36d.png)

(Icon to be visible beside heading)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Yashsharma1911** [comment]
@Ambareen09 would you like to work on this

**Comment by Ambareen09** [comment]
> @Ambareen09 would you like to work on this

Yes, please assign it to me.

**Comment by Yashsharma1911** [comment]
Here you go @Ambareen09
