### ISSUE TITLE
[UI] Tab Headings of Troubleshoot Guide in Dark Mode

### ISSUE THREAD

**Issue by hs05june** [meshery/meshery#7280]
#### Current Behavior
The tab headings have a light background  when their content is being displayed.

#### Screenshots/Logs

https://user-images.githubusercontent.com/103871275/222959961-407a4340-9c2c-4bfa-b479-846a62aa3cd2.mp4

#### Environment

- Browser: Firefox
- Host OS: Linux 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by aryans1319** [comment]
I want to work on this can you assign this to me?

**Comment by hs05june** [comment]
Sounds Great !! @aryans1319

**Comment by aryans1319** [comment]
Hey, @hs05june can you provide me access to the Figma file?
Email - aryan4p130202@gmail.com

**Comment by hs05june** [comment]
> Hey, @hs05june can you provide me access to the Figma file? Email - [aryan4p130202@gmail.com](mailto:aryan4p130202@gmail.com)

@leecalcote

**Comment by hs05june** [comment]
@aryans1319 Figma access is with community members only. Really Sorry, I will be assigning you another issue.
