### ISSUE TITLE
[Docs] Add "language: en" to the frontmatter of all Docs pages that are in English

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7283]
#### Current State
A Spanish translation of Meshery's docs exists. In order to facilitate a separation between viewing the dark speak in different languages, it would be good to have all pages containing a `language` frontmatter setting. Currently, not all of the English pages have this setting.

Example of a page missing this setting - https://github.com/meshery/meshery/blob/master/docs/pages/reference/rest-api-reference.md?plain=1

Example of a page having this setting - https://github.com/meshery/meshery/blob/master/docs/pages/reference/troubleshooting/installation.md?plain=1

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by tcchawla** [comment]
Hey @leecalcote, I would like to work on this issue.

**Comment by nishantminerva** [comment]
So I have to add "language: en" in every documentation page which is in english. I am new here.

**Comment by hirentimbadiya** [comment]
by adding line  language: en to the docs should solve this @leecalcote can i work on this issue , please assign me.

**Comment by Chadha93** [comment]
@hirentimbadiya, @nishantminerva. @tcchawla Has asked for the assignment first, since @hirentimbadiya had added commits let him take this one, but @hirentimbadiya next time please get an issue assigned before making a direct PR/commit. 

@tcchawla @nishantminerva let's get you on some more good first issues.

**Comment by hirentimbadiya** [comment]
thank you gaurav , yes I will take care of that for sure!!
