### ISSUE TITLE
[UI] Colour of tabs does not change based on Theme

### ISSUE THREAD

**Issue by soham4abc** [meshery/meshery#7284]
#### Current Behavior
In `user/preferences` page the colour of tabs does not change based  on dark and light theme.

Dark theme:
![image](https://user-images.githubusercontent.com/63705023/223030142-61f0c015-aac3-4876-8633-b094521f52a5.png)

Light Theme:
![image](https://user-images.githubusercontent.com/63705023/223030212-e477f55f-9612-4e93-b4ed-a66c1436f119.png)

#### Desired Behavior
Colour should change in accordance with the Save button for better visibility in Dark Mode

#### Environment

- Browser: Firefox
- Host OS: Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Source

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by parmishh** [comment]
@soham4abc are U working on it or if not I am interested to work on this.

**Comment by soham4abc** [comment]
I have already completed the work for this @parmishh :-)

If I find any similar issue like this I will mention you!!

**Comment by parmishh** [comment]
@soham4abc Thanks😊
