### ISSUE TITLE
[UI] Color of Metrics Tab when selected

### ISSUE THREAD

**Issue by hs05june** [meshery/meshery#7290]
#### Current Behavior

At /settings#metrics,
In dark mode, selected Grafana or Prometheus tabs have #607d8b color. As per the color scheme, It should be #00B39F.

https://user-images.githubusercontent.com/103871275/223193722-b9c38203-5037-4e5a-af3b-74e5fe1e382c.mp4

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by soham4abc** [comment]
Can I work on this issue? @hs05june

**Comment by LakshyaSatpal** [comment]
Can you assign this issue to me? @hs05june

**Comment by hs05june** [comment]
@soham4abc has made a PR. @LakshyaSatpal I would love if you review the PR made by him.
