### ISSUE TITLE
[UI] Alignment issue between hamburger icon and menu text

### ISSUE THREAD

**Issue by IshitaPathak** [meshery/meshery#7291]
#### Current Behavior

<img width="250" alt="Meshery" src="https://user-images.githubusercontent.com/75848598/223204301-e4e332de-e21a-4d85-906e-2a27926e26d9.png">

#### Desired Behavior
To fix the alignment of the hamburger icon and menu text in meshery.io website

### Environment
Browser: Firefox
Host OS: Linux
Meshery Server Version: stable-v
Meshery Client Version: stable-v
Platform: Source

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Sumer312** [comment]
Can I work on this issue?

**Comment by leecalcote** [comment]
Thanks for filing this issue, @IshitaPathak. @tinniaru3005, are we still having an issue with the mobile menu?

**Comment by IshitaPathak** [comment]
Thanks for your response @leecalcote.

 I have already done with the CSS work need for this @Sumer312. I will mention you if I find any similar issues.

 However, before proceeding further, let @tinniaru3005 check the changes. I just checked that she made some changes regarding menu text in the meshery.io repo, but it seems like there might be some issues with the alignment.

**Comment by tinniaru3005** [comment]
> Thanks for filing this issue, @IshitaPathak. @tinniaru3005, are we still having an issue with the mobile menu?

Yes @leecalcote. The issue still exists in the meshery.io website. Here is the [link to the issue](https://github.com/meshery/meshery.io/issues/1035) that was already raised and @sudhanshutech is working on it.

**Comment by tinniaru3005** [comment]
@IshitaPathak the issue exists in the meshery.io website and not Meshery. Am I right? You can raise issues related to the website in [this repo](https://github.com/meshery/meshery.io)

**Comment by IshitaPathak** [comment]
> @IshitaPathak the issue exists in the meshery.io website and not Meshery. Am I right? You can raise issues related to the website in [this repo](https://github.com/meshery/meshery.io)

Yes @tinniaru3005 I will take care to raise an issue in appropriate repo.
Should I close this issue now?

**Comment by tinniaru3005** [comment]
> > @IshitaPathak the issue exists in the meshery.io website and not Meshery. Am I right? You can raise issues related to the website in [this repo](https://github.com/meshery/meshery.io)
> 
> Yes @tinniaru3005 I will take care to raise an issue in appropriate repo. Should I close this issue now?

Yes you can close this issue. :)
