### ISSUE TITLE
[Docs] Table of contents is not being generated

### ISSUE THREAD

**Issue by chinu-anand** [meshery/meshery#7293]
#### Current State
![image](https://user-images.githubusercontent.com/66985303/223316903-52a505bd-4086-4046-9ec9-8b48d2025488.png)

#### Desired State
Table of contents to be generated automatically and add auto-scroll also so that when the user scrolls the main section the table of contents also scrolls to indicate which section they are in.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by chinu-anand** [comment]
Please assign me this issue.

**Comment by vishalvivekm** [comment]
There you go @chinu-anand

**Comment by leecalcote** [comment]
Thank you, @chinu-anand
