### ISSUE TITLE
[UI] Settings: Metrics background should be white

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7303]
#### Screenshots/Logs
<img width="912" alt="Screenshot 2023-03-07 at 4 40 13 PM" src="https://user-images.githubusercontent.com/7570704/223570471-a880960f-885d-4ed6-8cb1-a7e7542d0e1b.png">

<img width="924" alt="Screenshot 2023-03-07 at 4 39 35 PM" src="https://user-images.githubusercontent.com/7570704/223571272-4ad23ea7-c6a6-43eb-8216-2acd8feac196.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by error9098x** [comment]
Is this issue still open ? maybe I can work on this.

**Comment by sudhanshutech** [comment]
> Is this issue still open ? maybe I can work on this.

I will soon raise a pr @error9098x

**Comment by niranjan-kurhade** [comment]
Is this issue still open? I can try fixing it!

**Comment by sudhanshutech** [comment]
> Is this issue still open? I can try fixing it!

Go ahead
