### ISSUE TITLE
[UI] Settings: Page title not being updated

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7304]
#### Current Behavior
When a user navigates to the Settings page, the page title should read "Settings", but doesn't. Instead the previously visited page title is used.

#### Desired Behavior
When a user navigates to the Settings page, the page title should display "Settings".

#### Screenshots/Logs
<img width="922" alt="Screenshot 2023-03-07 at 4 40 06 PM" src="https://user-images.githubusercontent.com/7570704/223571015-5afb868a-8a0e-4d7f-a111-be1ebc5923a0.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI
](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Shivam164** [comment]
Hey @leecalcote, I would like to work on this.

**Comment by leecalcote** [comment]
Thank you, @Shivam164. This would be very helpful.

**Comment by himanshu1221** [comment]
hey, @Shivam164 any update on this?

**Comment by sebzz2002** [comment]
Hii @leecalcote ,
Is this issue still open. If yes can you assign it to me.
Thankyou

**Comment by sebzz2k2** [comment]
Hey @leecalcote 
Is this issue still open. I would like to give it a try.
Thankyou

**Comment by leecalcote** [comment]
Thank you, @sebzz2k2

**Comment by sebzz2k2** [comment]
Hii @leecalcote i am unassigning myself 

I tried working on it but i couldn't make any progress.

Here are a few pointers for who might take this up after me
There is Header.js file in /ui/components
This file is called from _app.js and layout.js /ui/components

As the Header is called from _app.js I checked the props being passed. i found the props title is undefined.

Thank You

**Comment by Meyazhagan** [comment]
@leecalcote I fixed the issue
