### ISSUE TITLE
[Server] Deregister Meshery Server from unavailable remote provider

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7305]
#### Current Behavior
On turn down of a Meshery Server instance that can't reach it's assigned remote provider, an unhandled exception occurs.

#### Expected Behavior
While Meshery Server will not be able to successfully de-register, it should gracefully handle this situation by handling the exception.

#### Screenshots/Logs
```
INFO[0104] session not found
^CINFO[2023-03-07T17:11:10-06:00] Doing seeded content cleanup...               app=meshery
INFO[2023-03-07T17:11:10-06:00] De-registering Meshery server.                app=meshery
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1020a70c9]

goroutine 1 [running]:
github.com/layer5io/meshery/server/models.(*RemoteProvider).DeleteMesheryConnection(0xc000c056c0)
	/Users/lee/code/meshery/server/models/remote_provider.go:3204 +0x6c9
main.main()
	/Users/lee/code/meshery/server/cmd/main.go:395 +0x280b
exit status 2
make: *** [server-local] Error 1

```

#### Environment

- **Host OS:** Mac 
- **Meshery Server Version:** stable-v0.6.62

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by theBeginner86** [comment]
I'll fix this.
