### ISSUE TITLE
[UI] When creating new pattern, not all supported integrations are displayed

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#7312]
#### Current Behavior
`Designs > Create Design` when creating a new pattern the mesh selector is not showing all supported integrations

![Screenshot 2023-03-08 at 9 53 30 PM](https://user-images.githubusercontent.com/71271069/223773612-2c7122f2-eea8-4db0-b5b3-c1a915883f8f.png)

#### Desired Behavior
it should something look like this

![Screenshot 2023-03-08 at 10 00 52 PM](https://user-images.githubusercontent.com/71271069/223773785-7c121a62-57c1-4f99-9435-a4f3d0b70281.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.meshery.io) and [Community Slack](http://slack.meshery.io)

**Comment by weilirs** [comment]
I am new here but it looks just fine on my end.
![image](https://user-images.githubusercontent.com/62249815/224907963-6a3b3e15-c630-4ced-aefe-5b2b536febc9.png)

**Comment by Yashsharma1911** [comment]
thanks for raising your hand @senali-d but before working on it I need to discuss it, @Abhishek-kumar09 is anyone working on it?

**Comment by ciradu2204** [comment]
Hi @Yashsharma1911 , can I work on this?

**Comment by ciradu2204** [comment]
Hi @Yashsharma1911, I would really appreciate it if can help me find one. Thanks
