### ISSUE TITLE
[UI] Metrics & Adapters not visible in dark mode.

### ISSUE THREAD

**Issue by Sarfraz-droid** [meshery/meshery#7313]
#### Current Behavior
Components are not responsive for Dark Mode in metrics/adapters
#### Screenshots/Logs
![Wjm4Ec1KOm](https://user-images.githubusercontent.com/73013838/223782126-5ab85217-38e8-4013-b4ae-fa64cbf29a6f.gif)

#### Environment

- Browser: Chrome
- Host OS: Windows(WSL)
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Yashsharma1911** [comment]
Hey @Sarfraz-droid this issue has been solved previously and it is also not showing in my local dev environment can you retry by fetching the latest updates and then rebuild Meshery

**Comment by Sarfraz-droid** [comment]
Okay! Closing the comment for the same
