### ISSUE TITLE
[UI]-kubernetes notification drop down is cut from the left side in mobile mode!

### ISSUE THREAD

**Issue by parmishh** [meshery/meshery#7328]
#### Current Behavior
kubernetes notification drop down is cut from the left side in mobile mode!

#### Desired Behavior
should be visible properly
@Chadha93 you can assign me this issue I have figured out some ways.😊

#### Screenshots/Logs
![Inkedissue1](https://user-images.githubusercontent.com/91942072/224110869-db8c32cc-f30d-46b3-9944-8a0fa1eb436e.jpg)

https://user-images.githubusercontent.com/91942072/224111008-90f6fc86-8b79-4a93-82b8-2bd71bb48ddb.mp4

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by parmishh** [comment]
@Chadha93 I have made some modifications now it looks like this shall I do a PR?

https://user-images.githubusercontent.com/91942072/224112418-1110bef8-1a98-4c02-a228-6f2184eba4d1.mp4

**Comment by parmishh** [comment]
@leecalcote @Chadha93 does this issue needs to be addressed or else I will close this issue?

**Comment by leecalcote** [comment]
> @leecalcote @Chadha93 does this issue needs to be addressed or else I will close this issue?

I completely missed this, @parmishh. Yes, let's get this fixed. Thank you for calling it out. Signal if you're available to and capable of fixing...

**Comment by parmishh** [comment]
@leecalcote please assign it to me
