### ISSUE TITLE
[Docs]Table headers are not visible when clicked in dark mode

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#7332]
#### Current State
When clicked in table headers (as we can see in the video) they are not visible under the dark mode in https://docs.meshery.io/project/compatibility-matrix#integration-tests

https://user-images.githubusercontent.com/90546692/224314171-2a6a32e3-4d38-4ca7-9c36-be31ac89bb2e.mp4

#### Desired State
The text should be visible in dark mode. Remove the white background when clicked

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by rinkuhasija** [comment]
@Chadha93 I have found a fix for this. Can you assign this Issue to me ?

**Comment by rinkuhasija** [comment]
@sudhanshutech On clicking any table row element, the dark mode properties are not applied to them also. I found a fix for that also, so, should I include that in this Issue or create a new Issue for that ? @Chadha93 

See below SS : 
![Screenshot 2023-03-10 195354](https://user-images.githubusercontent.com/52361778/224341304-bb7b87bc-36f7-4190-993d-b955e5c5c376.png)
