### ISSUE TITLE
Connection state machine implementation

### ISSUE THREAD

**Issue by Azanul** [meshery/meshery#7336]
#### Current Behavior

Missing state machine implementation for tracking all connections to meshery server

#### Desired Behavior

common state machine implementation for tracking states across all connection to meshery server

#### Implementation

TBD

#### Acceptance Tests

TBD

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by yash37158** [comment]
I would like to work on this issue

**Comment by Azanul** [comment]
> I would like to work on this issue

I'm already on it @yash37158. Please look into other open issues.
