### ISSUE TITLE
[UI]-MeshMap pop up on playground doesn't disappear on clicking the cross button on pop up.

### ISSUE THREAD

**Issue by pingu-73** [meshery/meshery#7337]
#### Current Behaviour
When I open [playground](playground.meshery.io) I see a pop up of MeshMap. On clicking the cross button on that pop-up it doesn't disappear. 

#### Desired Behaviour
On clicking the cross button the MeshMap pop up should go away.

#### Screenshots/Logs

<img width="1470" alt="Screenshot 2023-03-11 at 7 45 37 AM" src="https://user-images.githubusercontent.com/121669947/224460184-f41c8bd4-e87a-4af0-9974-a70ae1f47aa7.png">

#### Environment

- Browser: Safari 
- Host OS: Mac 
- Meshery Playground

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by pingu-73** [comment]
@leecalcote @Chadha93 does this issue needs to be addressed or else I will close this issue?

**Comment by leecalcote** [comment]
@pingu-73 thanks for raising this issue. This behavior is bey design. Yes, this issue can be closed.
