### ISSUE TITLE
[Docs] Update contribution docs for Meshery-UI

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#7338]
The Meshery UI contribution docs needs to be updated given the number of queries around it, that should have answered by the doc itself.

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by goldfishdolphin** [comment]
I would like to help with the issue. As a newcomer, I came across a few problems like installing the ruby version and inadequate information on the docs.

**Comment by Abhishek-kumar09** [comment]
Hey @goldfishdolphin Would you clarify your problems?
https://discuss.meshery.io/ is the best place to include everyone when someone could miss here.
