### ISSUE TITLE
[Docs] Replace Meshery API doc generation with ReDocly

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#7340]
#### Current State
Currently, API docs, for Meshery are generated using Swagger.

#### Desired State
1. Move the API docs generation process with [ReDocly](https://redocly.com/docs/cli/installation/).
2. A GitHub workflow which automates doc generation (updating release version, bundling.....)
Deployment guide:  https://redocly.com/docs/redoc/deployment/html/ 

Reference OpenAPI spec: https://github.com/meshery/meshery/blob/6ab5abf1118a190b80cd4fb7226b2b20bb165a29/docs/_data/swagger.yml

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by akarsh-jain-790** [comment]
@MUzairS15 can you assign this to me

**Comment by MUzairS15** [comment]
@akarsh-jain-790 Thank you for jumping in 😄.
Before you start working, can you please describe how you would proceed?

**Comment by Freedisch** [comment]
@MUzairS15 hello I would like to work on this issue, here is my following implementation
First, we need to set the openAPI spec and import it into our Redocly, and then create a workflow to automatically update the docs whenever a change is made. If there is anything that is missed or needs to consider let me know what you think. thanks

**Comment by leecalcote** [comment]
Good, @Freedisch. We'll want to include an update to the existing `make` target (`make swagger`, I think) as well.

**Comment by Freedisch** [comment]
> Good, @Freedisch. We'll want to include an update to the existing `make` target (`make swagger`, I think) as well.

oh see I have to update the current swagger.yml to be able to deploy it on Redocly. So, I will start digging into it.
