### ISSUE TITLE
[UI] Navbar Menu Butoon is not properly aligned 

### ISSUE THREAD

**Issue by himanshu1221** [meshery/meshery#7346]
#### Current Behavior

Menu is not aligned properly while checking the responsiveness

#### Desired Behavior

menu should be aligned properly 

#### Screenshots/Logs

![Screenshot_20230314_110236 (1)](https://user-images.githubusercontent.com/32031706/224906052-6c4dd685-ecc2-4213-bf8b-d2122a2147fc.jpg)

#### Environment

- Browser: Chrome 
- Host OS: Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sudhanshutech** [comment]
Hey @himanshu1221 there is already an issue opened regarding this https://github.com/meshery/meshery.io/issues/1035 in meshry.io so you can follow up there and see what issues are occurring regarding this

**Comment by sudhanshutech** [comment]
So we can close this issue as it may create ambiguity
