### ISSUE TITLE
[Docs] Improve REST API Docs Legibility

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7365]
#### Current State
A bit of CSS here would go a long way on legibility and usefulness of the [REST API docs](https://docs.meshery.io/reference/rest-apis).

#### Desired State

1. - [ ] [@senali-d] Improve [mockup of these API docs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=2191%3A12342) to use brand-appropriate colors.
1. - [ ] [@senali-d] Improve information architecture in the Description (too much bold text, not enough bullets, no `<code>` markup, no hyperlinks, and so on).
1. - [ ] Add a table of contents.
1. - [ ] Sort endpoints alphabetically.
1. - [ ] Grouping endpoints by path hierarchy; e.g. all /api/meshmodel endpoints adjacent to one another

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vishalvivekm** [comment]
I can go ahead with the rest @leecalcote , I'd want a bit more clarity or say details about the third one,
Thanks @senali-d for collaborating on this.

**Comment by leecalcote** [comment]
@vishalvivekm "contents" was misspelled in the third item: "add a table of contents"

**Comment by vishalvivekm** [comment]
> @vishalvivekm "contents" was misspelled in the third item: "add a table of contents"

I see it now, ohkay so in the existing table of content that we have on [Rest API Docs](https://docs.meshery.io/reference/rest-apis) page currently, as you can see in the image below it just ends with the "Endpoints" with no further listing, by the 3rd item  "Add a table of contents" we want to have all the endpoints being listed below the "Endpoints" in the existing TOC, did i get that right @leecalcote  ?

<img width="176" alt="Screenshot 2023-03-17 215702" src="https://user-images.githubusercontent.com/110674407/225963820-ab6ce56a-23c8-4635-91e2-555e667e1ff8.png">

**Comment by leecalcote** [comment]
@vishalvivekm unless doing so makes the page unusable. Or potentially an index or summarization at the top of the page or a show/hide toggle for each section.... something to make the api more browsable and digestible.

**Comment by goldfishdolphin** [comment]
Please assign me this issue.

**Comment by vishalvivekm** [comment]
> Please assign me this issue.

Would like to go with the third issue item @goldfishdolphin ? 
: https://github.com/meshery/meshery/issues/7365#issuecomment-1474185075

**Comment by goldfishdolphin** [comment]
> Sure. I can work on adding table of contents.

**Comment by vishalvivekm** [comment]
> > Sure. I can work on adding table of contents. May I have the access to the figma file as well please.

Yeah, sure, you'll soon have it

**Comment by goldfishdolphin** [comment]
@leecalcote, @senali-d, @vishalvivekm 
Please guide me regarding the setup of the env which guide needs to be followed.  I have tried https://docs.meshery.io/project/contributing/contributing-ui and https://docs.meshery.io/project/contributing/contributing-docs.  But no success :(

**Comment by vishalvivekm** [comment]
@goldfishdolphin any issues setting up docs locally in your system?

**Comment by vishalvivekm** [comment]
> let's focus on the docs for now, you need to follow these [instructions for setting up jekyll on macOS](https://docs.meshery.io/project/contributing/contributing-docs#for-macos) in the given sequence, if you are stuck or face any issues, do lemme know, let's get the docs running locally on your system @goldfishdolphin

**Comment by goldfishdolphin** [comment]
I have different versions of ruby.

**Comment by leecalcote** [comment]
> I have different versions of ruby.

rvm.io is highlighted in the setup guide as a helpful tool (for Linux and macOS). Docker is another option.

**Comment by senali-d** [comment]
> I have different versions of ruby.

@goldfishdolphin You can easily switch the ruby version when you use a ruby version manager like [`rvm`](https://rvm.io/) or [`rbenv`](https://github.com/rbenv/rbenv).

**Comment by vishalvivekm** [comment]
follow, the instructions ( that i pointed above) in the given sequence @goldfishdolphin, and trust me you'll be good to go. 

what @senali-d is talking about ruby version manager rvm is that you can check all the versions of ruby you've installedj, by <code>rvm list</code> command, and what amazing part is that let's say you've multiple versions of ruby, so as soon as you go to the /meshery/docs folder, it automatically switches to the required ruby version that is 2.7.5, not to mention you yourself too can switch the version,

**Comment by goldfishdolphin** [comment]
Thank you @leecalcote ,  @vishalvivekm  and @senali-d , I can confirm that I have done the setup using rvm and the project is running on my server.

**Comment by vishalvivekm** [comment]
> Thank you @leecalcote ,  @vishalvivekm  and @senali-d , I can confirm that I have done the setup using rvm and the project is running on my server. 

That's great to hear Naureen 🎉🎉😎
