### ISSUE TITLE
OPA Integration with `meshery`

### ISSUE THREAD

**Issue by pkbhowmick** [meshery/meshery#7366]
This is an epic for OPA integration.

Use cases:
- User Authorization for `meshery map`
- Take decisions based on rego policy evaluation for user capabilities

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by yash37158** [comment]
Are you still working on this issue ? @pkbhowmick

**Comment by pkbhowmick** [comment]
Yes @yash37158

**Comment by pkbhowmick** [comment]
Sorry, I can't progress with it.

**Comment by suhail34** [comment]
May i try this one

**Comment by vishalvivekm** [comment]
> May i try this one

Sure go ahead @suhail34

**Comment by suhail34** [comment]
So we need a new api endpoint which will evaluate the rego policy and send whether the user is authorized to access meshmap and other usercapabilites

**Comment by vishalvivekm** [comment]
> So we need a new api endpoint which will evaluate the rego policy and send whether the user is authorized to access meshmap and other usercapabilites

@suhail34 Let's discuss this on Development call, add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#), if you would :)
