### ISSUE TITLE
[Docs] Mark all OAM REST APIs as deprecated

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7373]
#### Current State
OAM support is being deprecated. MeshModal supplants it.

#### Desired State

In the [REST API Reference](https://docs.meshery.io/reference/rest-apis), each of the `oam` API endpoints need to marked with a "Deprecated" label.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vishalvivekm** [comment]
<img width="491" alt="Screenshot 2023-03-22 032604" src="https://user-images.githubusercontent.com/110674407/226750603-e7e0e863-8c8d-4237-956d-29893320ea39.png">

looks good @leecalcote ?

**Comment by leecalcote** [comment]
Looks great to me, @vishalvivekm 👍
