### ISSUE TITLE
[UI]Move the dark mode option under preferences section

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#7377]
#### Current Behavior

Currently, dark mode option is in the dropdown section under the profile
![image](https://user-images.githubusercontent.com/90546692/226895774-cfebdfb2-2337-4bfe-829a-60cc93f74eb0.png)

#### Desired Behavior

The dark mode option could be moved to the preference section under the general category maintaining proper ui
![image](https://user-images.githubusercontent.com/90546692/226896728-244adc78-cb5b-474c-ba77-850547a38a17.png)

#### Implementation

Move the dark mode component from the User.js file under the preferences section

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sudhanshutech** [comment]
Assigning in chronological order @Cvr421

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by Akshaybagai52** [comment]
@leecalcote Hey if it is still open can you assign this to me ?

**Comment by leecalcote** [comment]
@Akshaybagai52 you can offer review on the open Pr.

**Comment by Akshaybagai52** [comment]
@leecalcote yeah it's looking good and developer also followed the instructions given by the maintainers
