### ISSUE TITLE
[UI] Make UI/UX consistent for Publishing catalog content.

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#7379]
#### Current Behavior

A publish button is available currently that sends a publish request for publishing content. But there are a lot of UI/UX inconsistencies
#### Desired Behavior

1. Content like design have a `visibility` field set to `Public` `Private` and `Published`
2. Currently both `Public` and `Published` are shown as `Public`, which shouldn't be the case.
3. Have different UX for different visibility
        a. For `public`/`private` designs, have a `publish` button.
        b. For `public`/`private` designs which already have been requested to get published will result in an error. Handle the error gracefully with an error message describing that the request has been submitted and will be approved. And to prompt users to check their mail.
        c. For the already Published content, add an `unpublish` button for the owners and admins of the content to unpublish the catalog item.
5. Change server to send 202 `Accepted` when a publish request is submitted.
#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by thisiskaransgit** [comment]
Hey @Revolyssup, with respect to the following point 
> Change server to send 202 Accepted when a publish request is submitted.

this is the file where I should be making changes right?
```go

		if res.StatusCode != 200 {
			// failsafe for the case when a valid uuid v4 is not an id of any pattern (bad api call)
			return errors.Errorf("Response Status Code %d, possible invalid ID", res.StatusCode)
``` 
[meshery/mesheryctl/internal/cli/root/pattern/view.go](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/pattern/view.go)

if not,  a little guidance on how to proceed with it will be helpful. 

- And other than that I've changed the snackbar dialog from "**Design Published!**" to "**Design sent for review, check your email for further updates** "

**Comment by Revolyssup** [comment]
> little guidance on how to proceed with it will be helpful.

Nope, this is mesheryctl. The change would be in Meshery cloud as well as Meshery server code. I will do that. Create another issue and assign it to me.
