### ISSUE TITLE
Potential panic (skipped nil checks) in meshery server handlers

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#7380]
#### Current Behavior

There are instances in the code where response is not nil checked before accessing properties on it, which might cause panics.
Example- https://github.com/meshery/meshery/blob/70dcb02100709c486ea261337371db5d61676b69/server/models/remote_provider.go#L1881
#### Expected Behavior

Use [ErrUnreachableRemoteProvider](https://github.com/meshery/meshery/blob/master/server/models/error.go#L348) MeshKit error to handle nil response from remote provider.

Checkout this [example](https://github.com/meshery/meshery/blob/master/server/models/remote_provider.go#L3238) use case for reference.
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by theBeginner86** [comment]
I handled this error with a new MeshKit [error](https://github.com/meshery/meshery/blob/master/server/models/error.go#L348). Which can be reused to fix this issue.
Example use: https://github.com/meshery/meshery/blob/master/server/models/remote_provider.go#L3235

> _Adding this info here to the extent that it might help the contributor taking up this issue_

**Comment by theBeginner86** [comment]
> > I handled this error with a new MeshKit [error](https://github.com/meshery/meshery/blob/master/server/models/error.go#L348). Which can be reused to fix this issue. Example use: https://github.com/meshery/meshery/blob/master/server/models/remote_provider.go#L3235
> > > _Adding this info here to the extent that it might help the contributor taking up this issue_
> 
> Thank you @theBeginner86 . Will you edit the description of the issue with this reference.

updated 👍

**Comment by Azanul** [comment]
@theBeginner86 @Revolyssup  in the example use, the `resp == nil` and `err != nil` practically mean the same thing other than this one [special case](https://cs.opensource.google/go/go/+/refs/tags/go1.20.2:src/net/http/client.go;drc=acce3abb7e1c39bc867d6e6dd2277451bd41d53a;l=709) which I don't think we care about. 
Meaning the latter of the conditions is stale code. Either of the conditions would suffice.

**Comment by Ambareen09** [comment]
I'd like to work on this issue.

**Comment by Ambareen09** [comment]
There's an open PR @leecalcote by someone else, I think it fixes this issue but hasn't been merged yet due to lint issues.

**Comment by leecalcote** [comment]
@Ambareen09, if that contributor is unresponsive, will you checkout their branch and fix the lint issues on their behalf?
