### ISSUE TITLE
[UI] Permissions Framework

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7382]
#### Current Behavior
Meshery UI lacks a permissions framework. The existing internal implementation is extremely simple and fragile and is “does user have a role with this name assigned?“. So, it must be completely set aside / rewritten.

#### Prologue
We’re about to go headlong into definition of permissions and their enforcement in Meshery with an aim for it to be quite dynamic in terms of each input component carrying a unique permission key id. Each key is then put into a group of keys in a keychain, keychains assigned to user roles, in turn, roles assigned to users. With users having the ability to create own custom roles, the framework will be dynamic based on the associated server-side permissions for the currently auth’ed user.

Its the library / framework that we’re interested in. We’re in need of an extensible framework in which permissions to for any given user to see or to interact with a UI component can be dynamically discerned based on that users’ assigned permissions and not hardcoded into the UI.

This code snippet offers the appropriate mindset to have when considering the needs at-hand - https://isamatov.com/react-permissions-and-roles/#maps-for-roles-and-permissions

Meshery UI's approach needs to be extensible. This framework will be an extension point for Remote Providers to supply their own permissions.

#### Permissions via Extension Point

Each “Key” here will be a combination of a UI input field / component ID + action, so for example: `<input type="text" id="settings-adapter-uri" />`

`id` is the unique identifier of the field. Separately, the key would then contain four different composites: `key-id` + `action`

Example: `settings-adapter-uri `+ `edit`

#### Research
Investigate available frameworks. We’re just looking for an existing permission framework to use as an internal library. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by niranjan-kurhade** [comment]
I did some research and found -
1. CASL- It is a JavaScript library that provides a simple and flexible way to define and manage user permissions in web applications. It allows for the creation of permissions based on user roles and actions and can be used to create dynamic permissions that are not hardcoded into the UI.

2. React Permissions- It is a permission management library for React applications that provides a simple and intuitive way to manage user permissions and access control. It allows for the creation of dynamic permissions based on user roles and actions.

Both frameworks can be used to create a dynamic and flexible permissions framework for Meshery UI that allows for the creation of unique permission keys for each UI component and the assignment of those keys to user roles.

**Comment by Saksham294** [comment]
I also did some research and I will put my approach using CASL.js.
So we want to create a permissions framework for Meshery UI which will give users their roles and each role will have different permissions. 

1. We can create permissions for each UI component and define roles accordingly. 

2. Based on the role, the user will have access to different parts of the UI, this can be implemented using simple conditionals/ternary operator in the frontend. Say, the admin wants to delete some users so a 'DeleteUser' button is available to him but for a user (not having admin role) no such functionality will be available. 

3. Each component can have a different or share the same permission keys based on the requirement. The component finally just has to import the permission keys and userCan function from CASL.js and pass a 'user' object as one of its parameters. 
Based on the role assigned and permissions available each functionality of the component will be available accordingly.

This implementation will also involve changes in the backend. I found out that  we could then use CASL.js to generate an Ability instance on the server side based on the user's role and any other relevant factors, and use this instance to check permissions as needed.

**Comment by Chimise** [comment]
Hi @leecalcote , I am Chisom Promise, a full-stack developer and has worked extensively with React, Next.js and Typescript. I am interested in working on this project under the LFX mentorship program.
I would love to share my ideas and better understand the project. I am unable to join the slack channel, it says the link is has expired and would really love to join.

**Comment by leecalcote** [comment]
@Chimise thanks much for pointing out this expired link. This is no good. The open invitation has been refreshed and should be once again available at https://slack.meshery.io. It'd be great to have you jump into the community. The weekly Newcomers meeting held every Thursday offers an [overview of the community](https://layer5.io/community/calendar) and projects. It’s an ideal place to start. Here’s a very quick perspective on the [tech involved in the projects](https://meshery.io/handbook/repository-overview).
