### ISSUE TITLE
[CI] Send out email in case of meshmodel component generation/updater failure.

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#7383]
#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ayushthe1** [comment]
hey @vishalvivekm ,are you still working on this issue ? I will be happy to take up on this.

**Comment by vishalvivekm** [comment]
> hey @vishalvivekm ,are you still working on this issue ? I will be happy to take up on this.

@ayushthe1 I didn't start working on it was involved in some other issue, Ashish has said it's not that urgent of a task and asked for some progress over a week, so lemme try and if i m not able to make some quick progress ( by tmrw) I'll happily pass this on to you mate!

**Comment by ayushthe1** [comment]
What's the status on this issue @vishalvivekm

**Comment by vishalvivekm** [comment]
> What's the status on this issue @vishalvivekm

awaiting response from Ashish
