### ISSUE TITLE
[Docs] Outdated Contributing.md file  

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery#7390]
#### Current State

The File lacks the updated version of the steps necessary for contributing to UI.

1. At: https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#meshery-contribution-flow 

 - No Distinction is made between, Building the static assets for the UI and Building & running the server code 
2. At: https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#contributing-ui

- It doesn't mention running the Server 
- Wrong command is mentioned for building and exporting the code 

reference: https://docs.meshery.io/project/contributing/contributing-ui
 
#### Desired State

The file should be updated with the appropriate commands.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Ambareen09** [comment]
I'd like to work on this issue.

**Comment by vishalvivekm** [comment]
> I'd like to work on this issue.

you have docs running locally right ?

**Comment by Ambareen09** [comment]
Yes
