### ISSUE TITLE
[Docs] Outdated Prerequisites mentioned in Meshery Docs

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery#7392]
#### Current State
Steps to Reproduce: 
1. Go to: https://docs.meshery.io/project/contributing
2. Scroll Down to `Prerequisites for building Meshery in your development environment`

Here you will see that the prerequisites mentioned are wrong and should be updated 
- Wrong Meshery Repository link mentioned.
- Right now Node version 19 is not supported 
- Golang version 1.20 is not supported
![Screenshot from 2023-03-26 02-33-46](https://user-images.githubusercontent.com/92504666/227742490-44217209-8c07-42cb-a0b6-636a03f7ca03.png)

#### Desired State

The instructions should be updated with the supported versions of the required prerequisites.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by hirentimbadiya** [comment]
I would like to work on this issue

**Comment by sid-008** [comment]
Hey there @hirentimbadiya @thisiskaransgit was this issue fixed? If not can it be assigned to me?

**Comment by hirentimbadiya** [comment]
Hey @sid-008 , I am working on it and it will be done by Monday.

**Comment by sid-008** [comment]
Oh okay, no issue thanks for the response!

**Comment by hirentimbadiya** [comment]
@thisiskaransgit , node version 19 is not supported and Golang version 1.20 is not supported then can you please provide which versions are supported currently ? , @leecalcote  , @Chadha93 , @Nikhil-Ladha

**Comment by thisiskaransgit** [comment]
@hirentimbadiya, it's been a week, kindly complete the PR asap or if you are unable to do so let us know.
node version 19 or higher are not supported right now is not supported right now 
Go version 1.19 must be installed

**Comment by hirentimbadiya** [comment]
Sure , @thisiskaransgit I just make PR by today.
