### ISSUE TITLE
[Docs]-broken "Build and Release" link

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery#7394]
#### Current State
On [project/release](https://docs.meshery.io/project/releases) page the "Build and Release" link gives error404

#### Desired State
It should point to this [page](https://docs.meshery.io/project/contributing/build-and-release)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by adarshrajpathak** [comment]
I want to work on this issue, can you please assign me @vishalvivekm

**Comment by vishalvivekm** [comment]
There you go @adarshrajpathak
