### ISSUE TITLE
Link is not properly placed in README.md

### ISSUE THREAD

**Issue by ShivangShandilya** [meshery/meshery#7416]
#### Current State
I was going through README.md and found this link issue which makes documentation look unpresentable

![image](https://user-images.githubusercontent.com/101946115/228583408-022d94f5-0530-4e73-8e7d-17fbfdeeb0a1.png)

![image](https://user-images.githubusercontent.com/101946115/228584526-142ecabd-c1e1-4026-b2b7-ae1312ac8bec.png)

#### Desired State

Basically, just properly place the link so it looks presentable.
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ShivangShandilya** [comment]
I would like to work on this and close this small issue ASAP

**Comment by ShivangShandilya** [comment]
We can also close issue #7454 while working on this

**Comment by Mithil05** [comment]
Hey @ShivangShandilya , Is this issue solved? If not then I would like to take up on this

**Comment by ShivangShandilya** [comment]
Hey @Mithil05, I'm waiting for a member to assign this issue first before working on this. If by any chance I'm not able to work on this, I'll gladly pass this over to you

**Comment by Mithil05** [comment]
Oh okay, no issue thanks for the response! @ShivangShandilya
