### ISSUE TITLE
Active hover tab on meshery docs

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#7419]
#### Current Behavior

Currently in sidebar of meshery docs there is no active tab while we are particular section of meshery docs. It creates difficulties while surfing through docs

https://user-images.githubusercontent.com/90546692/228678646-7cc34ccf-cdeb-4d99-96b7-2091120cd97e.mp4

#### Desired Behavior

Implement  a active hover link while we are in particular section or page of meshery docs. Set the current hover color active or fixed when you are still on that page of meshery docs redirected through sidebar.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Mithil05** [comment]
Hey @sudhanshutech, I would like to work upon this issue. Can you assign me this task

**Comment by sudhanshutech** [comment]
Sure @Indira-kumar , go ahead. Need any help then let me know

**Comment by Indira-kumar** [comment]
Hi @sudhanshutech, Thank you so much.
I am new to open source, so I need a bit of time for learning the flow. But I will definitely submit the PR within a week. If I need any help I will let you know.

**Comment by rijusougata13** [comment]
hi, are you still working on? 
if not can I take the issue?

**Comment by vishalvivekm** [comment]
any update @Indira-kumar ?
have you docs setup locally @rijusougata13 ?

**Comment by rijusougata13** [comment]
<img width="428" alt="Screenshot 2023-04-06 at 11 48 30 AM" src="https://user-images.githubusercontent.com/52108435/230288130-37189ccc-5cd8-4e4a-876d-b5cb3d662c1f.png">
For this I have a specific doubt. I see we are using same sidebar code in 20+ files. If I have to make changes do I have to replace all the files? 
or do we have a single file source which I can reuse?
@vishalvivekm

**Comment by vishalvivekm** [comment]
> <img alt="Screenshot 2023-04-06 at 11 48 30 AM" width="428" src="https://user-images.githubusercontent.com/52108435/230288130-37189ccc-5cd8-4e4a-876d-b5cb3d662c1f.png">
> 
> For this I have a specific doubt. I see we are using same sidebar code in 20+ files. If I have to make changes do I have to replace all the files? or do we have a single file source which I can reuse? @vishalvivekm


Look for docs/_includes/sidebar.html @rijusougata13
docs<code>v0.4</code> and <code>v0.5</code> are burried in time, no changes are to be made there. // @sudhanshutech

**Comment by Indira-kumar** [comment]
> any update @Indira-kumar ? have you docs setup locally @rijusougata13 ?

Hi, I am a Windows user, so I am facing an issue ((rvm installation in WSL/Ubuntu)[https://github.com/rvm/rvm/issues/5263]) while setting up the project locally. And I realised that Ubuntu/Linux platforms are more suitable to set up Open Source projects than Windows, so I was considering moving to Ubuntu as the default OS, which might take time. In the meantime, I was trying to set up the meshery workspace in the cloud, so that I can contribute quickly. But was facing issues with that as well.

So @rijusougata13 shall go ahead, as he has already set up the docs locally.

**Comment by TheOjasSingh** [comment]
Is anyone still working on this issue?

**Comment by vishalvivekm** [comment]
> Is anyone still working on this issue?

Hi, thanks for commenting @TheOjasSingh, 
would you like to go ahead & take up this issue? in case yes, will you please confirm if you have docs set up locally.

**Comment by TheOjasSingh** [comment]
yes but I have not set up docs locally. Can you help me set up the docs locally?

**Comment by vishalvivekm** [comment]
> yes but I have not set up docs locally. Can you help me set up the docs locally?

Sure @TheOjasSingh 
Find the Contributing Guides : [Here ](https://docs.meshery.io/project/contributing)
for contributing to docs refer to this : [Meshery-Docs contribution guide](https://docs.meshery.io/project/contributing/contributing-docs)

In case you face any difficulty head over to [Discuss Forum](https://discuss.layer5.io/) and feel free to ask for help ( Do check out the forum for similar questions as yours, as It might be possible that your question is already answered)

Once you are done setting up the docs locally, signal here will assign this issue to you.
Happy Contributing!

**Comment by TheOjasSingh** [comment]
Thank you so much 😊

**Comment by TheOjasSingh** [comment]
@vishalvivekm I have completed the setup of the docs locally.

**Comment by rijusougata13** [comment]
hi @vishalvivekm , just have a question so what happens when we click the link in the sidebar. It actually reloads the page. So even if I add an separate class when click it reloads and remove the class.
Any other approach you suggest for this?

**Comment by vishalvivekm** [comment]
> hi @vishalvivekm , just have a question so what happens when we click the link in the sidebar. It actually reloads the page. So even if I add an separate class when click it reloads and remove the class. Any other approach you suggest for this?

@rijusougata13  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by rijusougata13** [comment]
> > hi @vishalvivekm , just have a question so what happens when we click the link in the sidebar. It actually reloads the page. So even if I add an separate class when click it reloads and remove the class. Any other approach you suggest for this?
> 
> @rijusougata13 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

sure I added there.

**Comment by vishalvivekm** [comment]
@TheOjasSingh @rijusougata13 any progress folks? 
Please sound off on what are the blockers on this one.
Please add this as an agenda item in the websites call's [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#)

**Comment by rijusougata13** [comment]
hey!! I added that in previous meeting minutes.

**Comment by ChaudharyRaman** [comment]
Hii !! Is there any progress, I would like to work on this issue.

**Comment by rijusougata13** [comment]
hey @sudhanshutech , @ChaudharyRaman  I faced the blocker earlier. In the above comment I put my understanding and explained the issue. Also I added this in meetings note. But not sure about whats the update.

**Comment by codesmith25103** [comment]
Hey, If this issue is still open. Can I work on it?

**Comment by vaibhav135** [comment]
@sudhanshutech please assign this to me.

**Comment by ashutosh887** [comment]
@vaibhav135 @sudhanshutech 

Is this issue resolved? I wanted to work if not :)

**Comment by vaibhav135** [comment]
@ashutosh887 There is a PR raised for this issue. So I suggest that you look for some other issue.
