### ISSUE TITLE
[Docs] Documentation on uninstalling meshery

### ISSUE THREAD

**Issue by Ambareen09** [meshery/meshery#7430]
#### Current State
As of now, the documentation on the uninstallation of Meshery does not exist.

#### Desired State
We need a documentation page (or section) on "Uninstalling Meshery"

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you for filing this, @Ambareen09 👍

**Comment by souravpy** [comment]
Hello There! can I be assigned to this issue?

**Comment by vishalvivekm** [comment]
@souravpy any update ?

**Comment by souravpy** [comment]
Started working on it, might get delayed. Will send PRs in a couple of days.

**Comment by leecalcote** [comment]
> Started working on it, might get delayed. Will send PRs in a couple of days.

What do you have thus far?

**Comment by leecalcote** [comment]
> Started working on it, might get delayed. Will send PRs in a couple of days.

What do you have thus far?

**Comment by vishalvivekm** [comment]
@souravpy did you make any progress here?

**Comment by vishalvivekm** [comment]
> Hey, Can I get this issue assigned? would love to take it forward and close this.

Thanks @Loknath-Das

**Comment by Ghat0tkach** [comment]
@Loknath-Das any progress?
