### ISSUE TITLE
[Docs] uninstallation method for each installation method

### ISSUE THREAD

**Issue by Ambareen09** [meshery/meshery#7431]
#### Current State
There are no uninstallation methods provided in the documentation for respective installations.

#### Desired State
A new central page (or section) and for each installation method, we need an uninstallation method.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Ghat0tkach** [comment]
hello , May i know that are we supposed to create tha page using this [template](https://github.com/meshery/meshery/new/master/docs/pages/index.md?filename=change-me.md&value=---%0Atitle%3A+%22Long+Page+Title%22%0AlinkTitle%3A+%22Short+Nav+Title%22%0Aweight%3A+100%0Adescription%3A+%3E-%0A+++++Page+description+for+heading+and+indexes.%0A---%0A%0A%23%23+Heading%0A%0AEdit+this+template+to+create+your+new+page.%0A%0A%2A+Give+it+a+good+name%2C+ending+in+%60.md%60+-+e.g.+%60getting-started.md%60%0A%2A+Edit+the+%22front+matter%22+section+at+the+top+of+the+page+%28weight+controls+how+its+ordered+amongst+other+pages+in+the+same+directory%3B+lowest+number+first%29.%0A%2A+Add+a+good+commit+message+at+the+bottom+of+the+page+%28%3C80+characters%3B+use+the+extended+description+field+for+more+detail%29.%0A%2A+Create+a+new+branch+so+you+can+preview+your+new+file+and+request+a+review+via+Pull+Request.%0A) and if yes , may i get some resources to write about uninstallation.

Thank You

**Comment by EraKin575** [comment]
if this issue is still there, I would like to work on it

**Comment by Srishtihere** [comment]
if this issue is still there, I would like to work on it @leecalcote @Ambareen09

**Comment by vishalvivekm** [comment]
> if this issue is still there, I would like to work on it @leecalcote @Ambareen09

Thanks for jumping in @Srishtihere 
Would you please say which uninstallation guide you'll be drafting for review?

**Comment by ShailikaS** [comment]
I would like to work on it @leecalcote @Ambareen09

**Comment by Srishtihere** [comment]
> > if this issue is still there, I would like to work on it @leecalcote @Ambareen09
> 
> Thanks for jumping in @Srishtihere Would you please say which uninstallation guide you'll be drafting for review?

i can write for windows and linux

**Comment by Srishtihere** [comment]
just a doubt the issue is asking for un

> 

i am a bit confused with this question, actually i am a beginner, i though the issue was asking about an uninstallation of meshery section as its not mentioned in the documentation website

I can write it how to install using - meshery CLI mesheryctl - docker extension

**Comment by Srishtihere** [comment]
@vishalvivekm hey I feel their is some issue, I am trying to run the doc file using docker's jekyll extension, the home page opens up but the sub pages don't, can anyone help what seem to be the problem ?

**Comment by nick2432** [comment]
can i work on this?
