### ISSUE TITLE
[UI] Research: Assess CASL for Authz in Meshery UI

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7436]
#### Current Behavior
Meshery UI is missing extensible hooks for defining and enforcing permissions.

#### Desired Behavior
Research use of https://casl.js.org for this purpose.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ishaan812** [comment]
Can i be assigned this issue?

**Comment by acald-creator** [comment]
Researching this and see if I can get it working within `provider-ui` as it is already in the plans to migrate `provider-ui` as an auth wrapper.

**Comment by sambhavgupta0705** [comment]
Hey ,I would like to collaborate on this issue✋

**Comment by Pranjal7852** [comment]
Hello! I'm Pranjal Goyal from the National Institute of Technology, Hamirpur, and I'm a pre-final year undergraduate student studying electronics and communication engineering. I'm from New Delhi, and I love to learn about new technology and work on challenges that affect the actual world. I have worked on UI/UX design in the past, but my current area of specialisation is full stack web development in MERN stack. I am good at making stuff that people say I can't. The thing that drives me the most is my curiosity and my eagerness to learn as much as I can.

I want to work with meshery on this project for the summer, as I think I have the required skills to bring this project to its completion, and I am comfortable in learning things on the fly. I have already started discussing the objectives of the project with the community and started learning the preliminaries for the project. I can assure you that if I get selected to work with Layer5 this summer, I will definitely try my level best to make this project successful.

Looking forward to working with you :)

**Comment by narel1** [comment]
@leecalcote Hello sir, I would like to work on this issue sir, so anything I can right now do sir?

**Comment by leecalcote** [comment]
@UsmanDev09, will you take a moment to consider how contributors might engage? Design spec review or Meshery UI implementation or other?

**Comment by smartdev09** [comment]
Contributors can review the PR for ongoing integration of CASL 
https://github.com/meshery/meshery-cloud/pull/894/
or maybe suggest permissions to make them more granular
https://github.com/meshery/meshery-cloud/blob/master/permissions.md
