### ISSUE TITLE
Changes in README.md

### ISSUE THREAD

**Issue by ShivangShandilya** [meshery/meshery#7454]
#### Current State

The option below the Meshery logo in README.md i.e License when clicked redirects users back to the repository itself.

![image](https://user-images.githubusercontent.com/101946115/229371910-a36dca4a-81e4-44f7-bac9-6519a68b3efb.png)

#### Desired State

The change will redirect users to the particular file location

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ShivangShandilya** [comment]
If possible we can also add the contributors option along with the others just like layer5

**Comment by ShivangShandilya** [comment]
> @ShivangShandilya, we don't need this now, right?

I didn't get what you are trying to say @thisiskaransgit. Can you please elaborate?

**Comment by thisiskaransgit** [comment]
@ShivangShandilya Since you mentioned this issue in a referenced one, you'll be implementing it all together, so thus we can close this one, right?

> We can also close issue 7454 while working on this

**Comment by ShivangShandilya** [comment]
Oh yeah yeah we sure can. Thanks
