### ISSUE TITLE
[Docs] Add Details/Summary for General Contribution Flow

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7455]
#### Current State
Some Meshery Docs pages have more information displayed upon page load than is immediately necessary. 

https://docs.meshery.io/project/contributing is an example. Both the https://docs.meshery.io/project/contributing#general-contribution-flow and the https://docs.meshery.io/project/contributing#meshery-contribution-flow sections could be collapsed by default.

#### Desired State
Use `<details>` and `<summary>` to provide the reader with a show/hide toggle. Only the summary should be shown on page load.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Mithil05** [comment]
Hey @leecalcote, I would like to take upon this issue, could you assign me this

**Comment by Mithil05** [comment]
Hey @leecalcote, I would like to take upon this issue, can you assign me this

**Comment by leecalcote** [comment]
Sounds good. Thanks, @Mithil05

**Comment by vishalvivekm** [comment]
@Mithil05 what's the status over this issue? 
Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Mithil05** [comment]
Hey @vishalvivekm, these days I am busy with my academic exams so will it be ok if I continue on this after 2 weeks? If not then you can assign this to any other contributor, thanks.

**Comment by vishalvivekm** [comment]
Will take it up.

**Comment by vishalvivekm** [comment]
Will take it up.

**Comment by vishalvivekm** [comment]
Will take it up.

**Comment by ankur0904** [comment]
Hey @vishalvivekm I would like to work on this issue.

**Comment by vishalvivekm** [comment]
> Hey @vishalvivekm I would like to work on this issue.

Oh yes, @ankur0904 
go ahead and let's see your work tomorrow on development call 🚀 : [minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)

**Comment by ahtishamkhan5678** [comment]
Hi @leecalcote could you please assign this task to me  I will  try to complete

**Comment by leecalcote** [comment]
@ankur0904 how are you progressing here?

**Comment by ankur0904** [comment]
@leecalcote I am currently setting up the repository locally but I am facing some errors, I am talking about this error in Slack. Hope to fix it and make the PR soon.

**Comment by ankur0904** [comment]
@leecalcote I set up the repository locally and made the required changes. 

Adds Details/Summary tags 
![Screenshot from 2023-06-07 14-58-21](https://github.com/meshery/meshery/assets/98346896/a367d337-4e2f-4b11-80f8-0b7775802d33)


![Screenshot from 2023-06-07 14-58-26](https://github.com/meshery/meshery/assets/98346896/3bd4efb3-c967-400a-bfce-f9ec6cb4ec3c)
![Screenshot from 2023-06-07 14-58-41](https://github.com/meshery/meshery/assets/98346896/8c8d483e-1132-413b-a3ba-11ceb2b85bba)

**Can I raise the PR?**

**Comment by vishalvivekm** [comment]
> @leecalcote I set up the repository locally and made the required changes. 
> 
> Adds Details/Summary tags 
> ![Screenshot from 2023-06-07 14-58-21](https://github.com/meshery/meshery/assets/98346896/a367d337-4e2f-4b11-80f8-0b7775802d33)
> 
> 
> ![Screenshot from 2023-06-07 14-58-26](https://github.com/meshery/meshery/assets/98346896/3bd4efb3-c967-400a-bfce-f9ec6cb4ec3c)
> ![Screenshot from 2023-06-07 14-58-41](https://github.com/meshery/meshery/assets/98346896/8c8d483e-1132-413b-a3ba-11ceb2b85bba)
> 
> **Can I raise the PR?**
> 
> 

@ankur0904 Let's discuss it in development call. Add this as an agenda item in the meeting [minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)

**Comment by ashutosh887** [comment]
@leecalcote @ankur0904 

Is this issue resolved? I would like to work on this

**Comment by ashutosh887** [comment]
@leecalcote @ankur0904 
Is this issue resolved?
