### ISSUE TITLE
[UI] Use linear gradient version of App Definition and Development category icon

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7460]
#### Current Behavior
<img width="280" alt="Screenshot 2023-04-03 at 12 56 21 PM" src="https://user-images.githubusercontent.com/7570704/229589240-1ac12a98-02ac-4cb6-acd9-60fbfc2df7ec.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by yash37158** [comment]
Can i work on this issue ?
