### ISSUE TITLE
deploy/undeploy adapter from docker extension

### ISSUE THREAD

**Issue by Azanul** [meshery/meshery#7468]
#### Current Behavior
Docker extension lacks the feature to deploy/undeploy adapters, recently implemented for Meshery server ([reference PR](https://github.com/meshery/meshery/pull/7378)).

#### Desired Behavior
Adapters to be deployable from docker extension UI

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Ambareen09** [comment]
Can I take up this issue?

**Comment by Udit-takkar** [comment]
@Ambareen09 just DM me on slack of you are stuck somewhere

**Comment by Ambareen09** [comment]
Sure thing. Will create it.

**Comment by vishalvivekm** [comment]
> Sure thing. Will create it.

have we made any progress on this @Ambareen09 ?

**Comment by Ambareen09** [comment]
> > Sure thing. Will create it.
> 
> have we made any progress on this @Ambareen09 ?

 Related issue #6255 , and waiting for the reference PR to get merged
