### ISSUE TITLE
[UI] Add hyperlink in snackbar to open Notification Center

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7478]
#### Current Behavior
When a user sees a snackbar with a summary of what is otherwise detailed information, they are intrigued to click to find out more information. Currently, the snackbar for Kubernetes component registratio is not clickable which leaves the user hunting for where to find additional details.

<img width="478" alt="Screenshot 2023-04-04 at 9 20 03 PM" src="https://user-images.githubusercontent.com/7570704/229966771-ccca1846-6d63-4834-bc49-b95dacd07e4e.png">

#### Desired Behavior
Ideally, the user can click on the snack bar to open up the respective message inside of notification Center

#### Acceptance Tests
- Users can click on the notification causing the Notification Center to open and the corresponding notification to be expanded and in focus.

#### Mockups
The notification highlighted in red should be expanded and in focus on click of the snackbar.

<img width="448" alt="Screenshot 2023-04-04 at 9 20 36 PM" src="https://user-images.githubusercontent.com/7570704/229966630-01abc214-b5dd-414a-9c3d-34d37b87abb6.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by therajatrai** [comment]
@leecalcote would love to work on this .

**Comment by 0xSaksham** [comment]
@leecalcote I want to work on this issue. Please direct to me any other resources needed.

**Comment by leecalcote** [comment]
Thank you for raising your hands, gents.

MdSahil-oss, I'll hold this issue for your for another 6 hours or so...

**Comment by MdSahil-oss** [comment]
@leecalcote I'd like to work on it, Please assign it to me :)

**Comment by leecalcote** [comment]
@0xSaksham and @therajatrai, let's get you onto another one: https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by therajatrai** [comment]
sure 👍🏼
