### ISSUE TITLE
[Docs] Fix links to be hyperlinked

### ISSUE THREAD

**Issue by goldfishdolphin** [meshery/meshery#7479]
#### Current State
<img width="1139" alt="Screenshot 2023-04-05 at 10 20 21 am" src="https://user-images.githubusercontent.com/98129474/230041458-8555793e-aa26-4f40-8d6a-82fcf6ae295e.png">

<img width="759" alt="Screenshot 2023-04-05 at 10 06 06 am" src="https://user-images.githubusercontent.com/98129474/230041483-2c33c066-db1d-4f98-86e3-5f7fac2d1d21.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks for raising this up, @goldfishdolphin

**Comment by goldfishdolphin** [comment]
@leecalcote can you please confirm for me if the DNS link is https://docs.meshery.io instead of https://meshery.meshery.io/docs.

**Comment by goldfishdolphin** [comment]
> hi @goldfishdolphin , can I work on this?

I have fixed the links.
