### ISSUE TITLE
 Error from the daemon saying it is unable to find manifest for layer5/meshery

### ISSUE THREAD

**Issue by shaikahmadnawaz** [meshery/meshery#7480]
#### Current Behavior
 Error from the daemon saying it is unable to find manifest for layer5/meshery

![meshery-error](https://user-images.githubusercontent.com/96189881/230045462-3ab0d0c5-2693-4bbc-a64f-c704ce954a23.png)

#### Expected Behavior

![Screenshot (594)](https://user-images.githubusercontent.com/96189881/230046125-f42f696d-8a6c-47f1-8fcc-42cbcadf067f.png)

#### Screenshots/Logs
Before
![Screenshot (593)](https://user-images.githubusercontent.com/96189881/230046749-dc0a9a4d-ff50-45d3-a4ad-39271cba6d77.png)

After
![Screenshot (595)](https://user-images.githubusercontent.com/96189881/230046965-3696866b-3fbe-435d-a8f0-9503bbacfbff.png)

#### Environment

- **Host OS:** Windows
- **Platform:** Docker

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by shaikahmadnawaz** [comment]
Shall I start working on this issue?

This issue can be solved by changing the image for meshery service in docker-compose.yaml

**Comment by leecalcote** [comment]
@Azanul

**Comment by Azanul** [comment]
@shaikahmadnawaz use `mesheryctl` for best experience. Other than that the officially supported deployment methods are listed [here](https://meshery.io/#getting-started).

**Comment by shaikahmadnawaz** [comment]
Thank you @leecalcote and @Azanul, shall I close this issue now?

**Comment by Azanul** [comment]
> Thank you @leecalcote and @Azanul, shall I close this issue now?

Yes please. Do check out the open issues and keep an eye for such issues while using meshery. I'm sure you'll stumble upon a screw that needs tightening.
