### ISSUE TITLE
[Docs] Feature Description Needed: Importing Docker Compose Apps

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7481]
#### Current State
Users can import their Docker Compose apps into Meshery as Meshery Apps. A description of this feature, how to use it in both Meshery clients, and a characterization of its behavior is needed.

#### Desired State
New page / section in Meshery Docs

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Mithil05 thanks for volunteering. Based on your previous unfinished attempt to incorporate two HTML tags into a docs page, I'm not sure that assignment here appropriately aligns you or the completion of this issue for success.

**Comment by Mithil05** [comment]
@leecalcote I have made changes in that, you can review it, I have updated contributors.md file

**Comment by vishalvivekm** [comment]
Let's discuss this on the Websites call. I'll add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#)

**Comment by vishalvivekm** [comment]
> @leecalcote I have made changes in that, you can review it, I have updated contributors.md file

https://github.com/meshery/meshery/issues/7455#issuecomment-1510095031 @Mithil05

**Comment by thisiskaransgit** [comment]
@leecalcote @Chadha93, kindly look at the section material, [docs link](https://docs.google.com/document/d/11Hz9uFMk6uNtyRmP4TFUOX0UjS5FxBRtcaeTCduH3ng/edit?usp=sharing)

**Comment by vishalvivekm** [comment]
> @leecalcote @Chadha93, kindly look at the section material, [docs link](https://docs.google.com/document/d/11Hz9uFMk6uNtyRmP4TFUOX0UjS5FxBRtcaeTCduH3ng/edit?usp=sharing)

@thisiskaransgit Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)
