### ISSUE TITLE
[Docs] Replace old Meshery logos

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7491]
#### Current State
Many of the Meshery design specs have a deprecated version of the Meshery logo (with multi-mesh manager tagline). Here's an [example](https://docs.google.com/document/d/1b8JAMzr3Rntu7CudRaYv6r6ccACJONAB5t7ISCaPNuA/edit?userstoinvite=alexander.gorskih@gmail.com&actionButton=1#heading=h.blih70a9hxp).

#### Desired State
1. Check each [Meshery design spec ](https://drive.google.com/drive/u/0/folders/1onnxOnVmTCEjAfaCnocBWCzB8E_fq_1T)and remove / replace old logos with a tagline-less version:
    1. https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/meshery-logo-dark-text.png
    1. https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/meshery-logo-dark-text-side.png

1. Check each repository's readme.md and replace across all repos in github.com/meshery
1. Check for all reference to these files and replace across all repos in github.com/meshery
    1. https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/meshery-logo-tag-dark-text-side.png
    1. https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/meshery-logo-tag-light-text-side.png

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@goldfishdolphin is this an item that you would like to undertake?

**Comment by goldfishdolphin** [comment]
@leecalcote , don’t you think we need light logos for task 1? 
![](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/meshery-logo-dark-text.png)

**Comment by leecalcote** [comment]
I had originally written this issue with the Google Docs update  in mind. All Google Docs have a white background. I had later expanded the issue to include, readmes and other references in repos, though. So, there are two updates needed to this issue's description:

1) use of SVGs is preferred over PNGs in almost every case. Neither Google Slides nor Google Docs supports SVGs, though.
2) Other logo versions:

Horizontal:
  - [meshery-logo-dark-text-side.png](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-dark-text-side.png)
  - [meshery-logo-dark-text-side.svg](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-dark-text-side.svg)
  - [meshery-logo-light-text-side.png](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-light-text-side.png)
- [meshery-logo-light-text-side.svg](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-light-text-side.svg)

Stacked:
 - [meshery-logo-light-text.png](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-light-text.png)
  - [meshery-logo-light-text.svg](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-light-text.svg)
 - [meshery-logo-dark-text.png](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-dark-text.png)
  - [meshery-logo-dark-text.svg](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-dark-text.svg)

**Comment by goldfishdolphin** [comment]
I have edited the logos on following pages:
https://docs.google.com/document/d/1f7mGHtjHiywbN9UzwuldOX8x_Lpv2Ss8i4b045Np9OM/edit#heading=h.e9czs1wom8wl

https://docs.google.com/document/d/1QHBb3TRhlYDTvcwodnY-KX2v73RYNclL8UPlGE5U2Y8/edit#


Documentation

https://docs.google.com/document/d/1rIGxrT4rjpJ2sOi6yswkbUd-ryn0Le8iu-tKMBX9z9k/edit?usp=share_link

https://docs.google.com/document/d/1Ou__vQlnWm7MYmI_vw7hQLLtFo2l8OzDKe-FhsjBDJs/edit#

https://docs.google.com/document/d/1hlTwD139De4yvhJDPabY0pu2r8X5nnPmN3DUj7m7_n8/edit#heading=h.blih70a9hxp


https://docs.google.com/document/d/1l-JoBWm6jzT3DuffmZAMPHwOUuyhXw0aMC_RLB7F8bM/edit?usp=share_link

https://docs.google.com/document/d/1YnpJs6D_arzuE5ieqMyuJs3A3UYSVp9YZYhbc966sWg/edit#

https://docs.google.com/document/d/17guuaxb0xsfutBCzyj2CT6OZiFnMu9w4PzoILXhRXSo/edit#heading=h.q8ttkf83b5ru

https://docs.google.com/document/d/1t8Ilb72gpvkLXjywSAkaUOxN6arObC_xOLih66ggCUk/edit#heading=h.blih70a9hxp

Functional and Architecture
https://docs.google.com/document/d/1GFnh6R1W3HoqYGbtkO692wNhRv3eXuQZ8iI1MP9tgsA/edit#

https://docs.google.com/document/d/1v_wQgNmLa0riibd5Gq4A7TSF4-h-DkEueXiqjK870yY/edit#
https://docs.google.com/document/d/1b8JAMzr3Rntu7CudRaYv6r6ccACJONAB5t7ISCaPNuA/edit# 

https://docs.google.com/document/d/1nBCrPg967euGyjSIfaAnfKXByhbTNUpBKQBzdamdJUU/edit#

https://docs.google.com/document/d/13Z5QTbKkViKUweGXhCqhttq54wHmwjQoQtOodi7NT7s/edit#heading=h.xi6m9msq5hfn

Env
https://drive.google.com/drive/folders/1mJKTq97ZmH13xRb_3CL_P8RAD6Pxeo2F?usp=sharing

Extensibility
https://drive.google.com/drive/folders/1rLfNAyIVO0rlPysE787jLAxzOE1yT98u

**Comment by leecalcote** [comment]
This is a healthy list. These are looking good. Not a crucial concern, but I wonder if the version of the Meshery PNG that we're embedding doesn't need to be a higher resolution version as they have the faintest appearance of fuzziness on the letter edges. I find this a bit Odd, since the [meshery-logo-dark-text-side.png](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-dark-text-side.png) should be large enough that the effects of its rasterization shouldn't be noticeable. Hmpf. Go figure.

**Comment by goldfishdolphin** [comment]
I have used the image given in task list 
![](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/meshery-logo-dark-text-side.png)

**Comment by goldfishdolphin** [comment]
I ll replace them with 
[meshery-logo-dark-text-side.png](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-dark-text-side.png)

**Comment by leecalcote** [comment]
No more fuzziness around the edges of the logo. Perfecto. 👌

**Comment by goldfishdolphin** [comment]
I have opened a pr [https://github.com/meshery/meshery-cpx/pull/105](https://github.com/meshery/meshery-cpx/pull/105) to change meshery-cpx repo logo.

**Comment by goldfishdolphin** [comment]
@leecalcote I have updated logos in [meshery-nginx-sm](https://github.com/meshery/meshery-nginx-sm) and [meshery-cpx](https://github.com/meshery/meshery-cpx) and created pull requests [meshery-cpx/pull/105](https://github.com/meshery/meshery-cpx/pull/105) , [meshery-nginx-sm/pull/224](https://github.com/meshery/meshery-nginx-sm/pull/224)
