### ISSUE TITLE
OpenAPI Schema for Meshery Design

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7494]
#### Current Behavior
Definition of this file has shifted with the move from OAM to MeshModal.

#### Desired Behavior
Fresh definition and publication of a Meshery Design schema is needed.

#### Implementation
1. OpenAPI schema published to meshery/meshery.

#### Acceptance Tests
1. Same schema published to [json](https://www.schemastore.org/json/)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by 123Vasu** [comment]
Hey @leecalcote do let me know how I can help out on this issue

**Comment by leecalcote** [comment]
> Hey @leecalcote do let me know how I can help out on this issue

Thank you for showing interest, @123Vasu. This one will require a [design spec](https://github.com/meshery/meshery/issues/7494#issuecomment-1499401907). I choose not to label it with "help wanted" knowing that it'll require a deep understanding of Meshery's internals. I'm not quite sure how to empower you on this one or I would.
