### ISSUE TITLE
[Docs] Wrap words around images in readme.md

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7496]
#### Current State
In this repo's readme.md two images are set to block display and not allowing words to wrap around them. 

<img width="940" alt="Screenshot 2023-04-06 at 6 01 00 PM" src="https://user-images.githubusercontent.com/7570704/230509343-38e90c62-7f91-4ddb-bf9c-27ce08d2bed7.png">

#### Desired State
Have them wrap like the “Find your MeshMate” section does. Here is another example - https://github.com/layer5io/layer5#-community-and-contributions

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by HetviSoni** [comment]
Hey I would like to work on this issue. Please assign me this issue @leecalcote

**Comment by akshatvirmani** [comment]
Hi! 
I would also like to work on this issue if possible.

**Comment by akshatvirmani** [comment]
Hi @leecalcote 
I have made some changes, should I make the pr after the changes? 
![image](https://user-images.githubusercontent.com/77536248/230555578-a2f2628b-2f22-4553-b788-29d663712810.png)
