### ISSUE TITLE
[UI] Show information blue snackbar on Events info level events not indicating success.

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#7504]
#### Current Behavior

Events sent by server which are not error are shown in a green snackbar.
#### Desired Behavior

Use blue informational snackbar for events which do not indicate success.
#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Saksham294** [comment]
Hey @Revolyssup I would like to work on this

**Comment by MdSahil-oss** [comment]
@leecalcote Please assign it to me :)

**Comment by leecalcote** [comment]
Thanks, @Saksham294. It was nice chatting about SEO with you on today's Websites meeting. 

Thanks, @MdSahil-oss. Here you are.

**Comment by SoumyadeepOSD** [comment]
Hey Can I work on it?

**Comment by ShivangRawat30** [comment]
@Revolyssup can I work on this issue ?

**Comment by Revolyssup** [comment]
> @Revolyssup can I work on this issue ?

// @leecalcote @Chadha93

**Comment by leecalcote** [comment]
Thank you for this ping, @Revolyssup. If @ShivangRawat30 is to work on this, he'll need a mechanism to use to determine whether a notification is to be considered Informational (blue) or other. This will need to be structured data (i.e. an event severity), not an unstructured string search.

**Comment by leecalcote** [comment]
@Revolyssup, contributors like @ShivangRawat30 are inquiring, but unable to move forward without the issue description offering a mechanism to identify or determine event severity.
