### ISSUE TITLE
[UI] Use white Helm logo in Applications for source type in dark mode

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#7506]
#### Current Behavior
The Helm logo is not appealing at all in dark mode.

#### Desired Behavior
Use a light (white) helm SVG only for Dark Mode. 

#### Screenshots/Logs
![image](https://user-images.githubusercontent.com/65453826/230675724-42f1b69b-d74a-4218-87d1-0f725353bdea.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by HarshAg90** [comment]
Hey @Chadha93
I would like to work on this issue, can I?

**Comment by vishalvivekm** [comment]
> Hey @Chadha93 I would like to work on this issue, can I?

will you confirm if you have meshery set up locally ? @HarshAg90

**Comment by HarshAg90** [comment]
@vishalvivekm not yet, i am new here and was thinking of starting with a good first issue

**Comment by vishalvivekm** [comment]
> @vishalvivekm not yet, i am new here and was thinking of starting with a good first issue

Great @HarshAg90, You're very welcome :)
Find the  [Contributing Guides ](https://docs.meshery.io/project/contributing) here.
for contributing to UI refer to this :  [Meshery-UI contribution guide](https://docs.meshery.io/project/contributing/contributing-ui)

In case you face any difficulty head over to [Discuss Forum](https://discuss.layer5.io/) and feel free to ask for help ( Do check out the forum for similar questions as yours, as It might be possible that your question is already answered)

Once you set up the UI, signal here will assign this issue to you.
Happy Contributing!

**Comment by HarshAg90** [comment]
thanks, @vishalvivekm ill fix this and update ASAP

**Comment by HarshAg90** [comment]
hey, @Chadha93 @vishalvivekm, can one of you tell me where can I find this component in either webpage or code base

> sorry to be late

**Comment by vedant-jain03** [comment]
@Chadha93 I would like to work on this issue, could you tell me steps to reproduce the bug!

**Comment by Sudheendra-varam** [comment]
Hey @Chadha93 i would like to contribute

**Comment by vedant-jain03** [comment]
> hey, @Chadha93 @vishalvivekm, can one of you tell me where can I find this component in either webpage or code base
> 
> > sorry to be late

Hey @HarshAg90 you can find the code for this [here](https://github.com/meshery/meshery/blob/c08a700a08f579775737b78654a48cfb78c17d1e/ui/components/MesheryApplications/ApplicationsCard.js#L86)

**Comment by Sudheendra-varam** [comment]
Hey @Chadha93 I would like to contribute, Can you please assign it to me

**Comment by Chadha93** [comment]
I missed lots of comments here, @HarshAg90 given you are progressing on building meshery, Let's assign this item to the next contributor. @vedant-jain03, are you comfortable taking this item? Visit the application page and upload a helm chart to see an app with the Helm logo. Helm chart logo - https://github.com/meshery/meshery/raw/master/.github/samples/robot-shop-1.1.0.tgz

Meanwhile, @sudheendra-varam You can setup meshery locally using - https://docs.meshery.io/project/contributing/contributing-ui

**Comment by vedant-jain03** [comment]
> I missed lots of comments here, @HarshAg90 given you are progressing on building meshery, Let's assign this item to the next contributor. @vedant-jain03, are you comfortable taking this item? Visit the application page and upload a helm chart to see an app with the Helm logo. Helm chart logo - https://github.com/meshery/meshery/raw/master/.github/samples/robot-shop-1.1.0.tgz
> 
> Meanwhile, @sudheendra-varam You can setup meshery locally using - https://docs.meshery.io/project/contributing/contributing-ui

Sure @Chadha93

**Comment by souravpy** [comment]
Hey there @Chadha93 ! I'm just a PR far from getting the issue done, done setting up Meshery locally, made a perfect white Helm logo as prescribed

**Comment by DarrenDsouza7273** [comment]
can i work on this issue

**Comment by vishalvivekm** [comment]
@duckling69 @DarrenDsouza7273 How about collaborating with @souravpy who already has a open PR #7598  and certainly needs some help : https://github.com/meshery/meshery/pull/7598#issuecomment-1542378742
Review his PR and offer your feedback, if you would :)

**Comment by DarrenDsouza7273** [comment]
Yeah that would be fun @vishalvivekm

**Comment by souravpy** [comment]
> @duckling69 @DarrenDsouza7273 How about collaborating with @souravpy who already has a open PR #7598  and certainly needs some help : https://github.com/meshery/meshery/pull/7598#issuecomment-1542378742
> Review his PR and offer your feedback, if you would :)

This would be so great 🤗

**Comment by duckling69** [comment]
> @duckling69 @DarrenDsouza7273 How about collaborating with @souravpy who already has a open PR #7598 and certainly needs some help : [#7598 (comment)](https://github.com/meshery/meshery/pull/7598#issuecomment-1542378742) Review his PR and offer your feedback, if you would :)

sounds good

**Comment by leecalcote** [comment]
Reassigning to @duckling69...

**Comment by aminoxix** [comment]
@Chadha93 I think this issue needs to be close!
