### ISSUE TITLE
[UI] strict equality/inequality operators are not used

### ISSUE THREAD

**Issue by Udit-takkar** [meshery/meshery#7512]
#### Current Behavior
strict equality/inequality operators are not used. 

https://github.com/meshery/meshery/blob/master/install/docker-extension/ui/src/components/ExtensionComponent/ExtensionComponent.js#L136

https://github.com/meshery/meshery/blob/master/install/docker-extension/ui/src/components/ExtensionComponent/ExtensionComponent.js#L115

#### Desired Behavior
we should use strict inequality/equality to prevent bugs. refer here https://eslint.org/docs/latest/rules/eqeqeq

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Good suggestion
