### ISSUE TITLE
[mesheryctl] mesheryctl showing error but installing components

### ISSUE THREAD

**Issue by harsh-del** [meshery/meshery#7521]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

while setuping meshery on google kubernetes engine using mesheryctl and script mentioned in the official document, mesheryctl was showing error but install's all the components behind the scene

#### Desired Behavior

if mesheryctl is showing the error then it should not setup the meshery components in cluster and if it is installing the components then it should not show error

#### Screenshots/Logs

![meshery-issue](https://user-images.githubusercontent.com/64789547/230868716-593e45c3-0809-46c2-921a-25f330b79818.png)
![output-01](https://user-images.githubusercontent.com/64789547/230868724-1e15473e-34a7-4d75-b4b5-0937d27130c4.png)
![output-02](https://user-images.githubusercontent.com/64789547/230868729-924c6ae8-03ff-4d62-bd59-924a2335497d.png)
![output-03](https://user-images.githubusercontent.com/64789547/230868731-7bcb44ed-d106-4601-8232-1eb258e88ea6.png)

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by yash37158** [comment]
I would like to work on this issue if it still persists

**Comment by ShivangShandilya** [comment]
hey @harsh-del, I would like to work on this
