### ISSUE TITLE
Replace the Logo of Layer5 with Meshery in config.yml workflow

### ISSUE THREAD

**Issue by anshgoyalevil** [meshery/meshery#7526]
### Description

Currently, we are using the Logo of Layer5 instead of Meshery. This repository is under the organization Meshery, so, there should be the image of Meshery.

**How to resolve this?**
- Go to .github and replace this welcome image with the new one: 

- Make sure to display the images conditionally, based on the theme selected by user.
Here's the sample code:

```
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/w.png">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/b.png">
  <img alt="Meshery Logo" src="">
</picture>
```

New images are:

![Meshery-celebration-Light](https://user-images.githubusercontent.com/94157520/231786445-45bf80c4-d214-40ab-a98f-c7a5f42015c5.svg)
![Meshery-celebration-Dark](https://user-images.githubusercontent.com/94157520/231786474-cafb4373-52ee-4b02-b06e-87376721c74a.svg)

- Download these images, and upload with an appropriate name. Make sure to use conditional rendering as described above.

- After uploading the image, and removing the previous image, go to .github/config.yml folder and update the reference to previous image to the new image in the following part:

```
firstPRMergeComment: >
  Thanks for your contribution to the Layer5 and Meshery community! :tada:
   
  ![Congrats!](https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Layer5-celebration.png)
  &nbsp; &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9; :star: Please leave a [star on the project](../stargazers). :smile:
```
Here, replace ```![Congrats!](https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Layer5-celebration.png)``` with the code
```
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/w.png">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/b.png">
  <img alt="Shows a black logo in light color mode and a white one in dark color mode." src="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
</picture>
```
make sure to change the image sources with the path to image in the folder where you upload it.

- That's it.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by anshgoyalevil** [comment]
Please assign this issue to me.

**Comment by leecalcote** [comment]
@anshgoyalevil, thanks for opening this. @goldfishdolphin can recommend use of a horizontal version of the Meshery logo that includes both the mark (icon) and the text (meshery) in SVG format.

**Comment by anshgoyalevil** [comment]
@leecalcote 

Thanks Sir. Waiting for his response. In the meantime, I would try finding one myself.

**Comment by goldfishdolphin** [comment]
These are recommended Meshery logos. 

[meshery-logo-dark-text-side.svg](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-dark-text-side.svg) 
[meshery-logo-light-text-side.svg](https://github.com/meshery/meshery/blob/master/.github/assets/images/meshery/full%20logo/meshery-logo-light-text-side.svg)

**Comment by leecalcote** [comment]
Much appreciated, @goldfishdolphin

**Comment by souravpy** [comment]
Can I be assigned with the issue, I'm almost done

**Comment by anshgoyalevil** [comment]
@souravpy 

Thanks for taking out your time in trying solving the issue.

I just checked your PR, and it doesn't solve the issue mentioned.

Meanwhile, I have raised a PR for the same.

**Comment by souravpy** [comment]
I was about to add more prs, one at a time, your pr is good tho, you can self assign the issue I guess?

**Comment by anshgoyalevil** [comment]
@souravpy 

> I was about to add more prs, one at a time

More PRs? I guess you mean more commits.

> you can self assign the issue I guess?

Nah buddy, I am also a contributor just like you. I was assigned to the issue by a maintainer.
