### ISSUE TITLE
Change in meshery/install/docker-extension/README.md

### ISSUE THREAD

**Issue by ShivangShandilya** [meshery/meshery#7533]
#### Current State

If we click on License below Meshery logo in README.md of docker-extension, it redirects the user back to Meshery repo

![image](https://user-images.githubusercontent.com/101946115/231466901-df750d04-e617-4e21-a227-a7a9e6dbb868.png)

#### Desired State

We simply want it to redirect to Meshery License file instead of the repo

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ShivangShandilya** [comment]
> Hey @ShivangShandilya I would like to work on it.

Sure @Freedisch, a maintainer will soon assign this issue to you. Hang tight 😁

**Comment by Sudheendra-varam** [comment]
Hey @ShivangShandilya @leecalcote i want to contribute this

**Comment by leecalcote** [comment]
@ShivangShandilya would you like to point out other similar unassigned issues?

**Comment by ShivangShandilya** [comment]
Yeah sure @leecalcote, @Sudheendra-varam this issue has already been assigned but you can check out some similar issues in other repositories. I'll mention them here:
- [Meshkit - Issue #296](https://github.com/meshery/meshkit/issues/296)
- [Meshsync - Issue #193](https://github.com/meshery/meshsync/issues/193)
- [Homebrew - Issue #37](https://github.com/meshery/homebrew-tap/issues/37)
- [Scoop - Issue #17](https://github.com/meshery/scoop-bucket/issues/17)

These are some really good issues, to begin with, check them out 😁

**Comment by Freedisch** [comment]
> also @Freedisch, what's the progress on this issue?

I was on another PR but I'm working on it I'll soon open a PR for this one. 👍🏾
