### ISSUE TITLE
[UI] Adapter details are not visible in settings

### ISSUE THREAD

**Issue by Azanul** [meshery/meshery#7545]
#### Current Behavior
Chips for adapters in settings do not show details about the adapter whereas the same for the chips in dashboard is visible as tooltips.

#### Desired Behavior
A tooltip on the chip for the connected adapter listing details about that adapter.

#### Screenshots/Logs

Current:
<img width="494" alt="Screenshot 2023-04-14 at 11 13 41 AM" src="https://user-images.githubusercontent.com/42029519/231952272-d289b3fd-202e-43a2-bd3c-e29f636b9f4c.png">

Desired:
![Screenshot 2023-04-13 at 11 55 51 PM](https://user-images.githubusercontent.com/42029519/231951498-e2fcd93c-535c-412d-8c08-c921dc5750e6.png)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sajdakabir** [comment]
@Azanul I would like to work on this issue. Can you please assign it to me?

**Comment by Azanul** [comment]
@sajdakabir There you go

**Comment by Azanul** [comment]
@sajdakabir any progress?

**Comment by sajdakabir** [comment]
Yes, working in it. But stack in setup. My server is not running properly it's giving me index error.  I am looking into it.

**Comment by Azanul** [comment]
> Yes, working in it. But stack in setup. My server is not running properly it's giving me index error. I am looking into it.

Feel free to ask for help in the community slack, [join the community](http://slack.layer5.io/).

**Comment by Azanul** [comment]
@sajdakabir When can we expect for this to be completed?

**Comment by sajdakabir** [comment]
I will make the PR by tonight.

**Comment by Azanul** [comment]
@sajdakabir Have you created a PR and not linked it?

**Comment by sajdakabir** [comment]
Hey,@Azanul please give me some more time. My laptop is hanging every time I am running the meshery server🥲.

**Comment by UsmanDev09** [comment]
@Azanul Can i work on this?

**Comment by sajdakabir** [comment]
Hey, @UsmanDev09 You can work on this. Please @Azanul Assign this issue to @UsmanDev09 . My laptop is unable to take the 
meshery server load.
