### ISSUE TITLE
[UI] : Notification modal appearance is laggy

### ISSUE THREAD

**Issue by vedant-jain03** [meshery/meshery#7546]
#### Current Behavior
Notification modal appearance animation seems little laggy.

https://user-images.githubusercontent.com/76901313/231986117-b0ce8803-a6cf-4d90-a54d-7e586093a691.mov

#### Desired Behavior
It could be smooth.

#### Implementation
A simple css animation.

#### Acceptance Tests
N/A

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vedant-jain03** [comment]
cc @Chadha93 should I go for the issue(if you find this valid)

**Comment by vedant-jain03** [comment]
cc @leecalcote if you find this valid, I would like to work on this!

**Comment by vedant-jain03** [comment]
cc @leecalcote @Chadha93  if you find this valid, I would like to work on this!

Also I have one more suggetion:

Why do we need that "bell" icon button to show "All notification" when we already have one tab button for that
<img width="494" alt="Screenshot 2023-04-14 at 1 49 16 PM" src="https://user-images.githubusercontent.com/76901313/231986862-328c98cc-5fde-4aa1-a892-ffb47b937e18.png">

**Comment by MdSahil-oss** [comment]
@leecalcote Please assign it to me.

**Comment by Chadha93** [comment]
@MdSahil-oss. @vedant-jain03 Is already assigned and has created a PR for it. Let's have your review on the PR. Will you review the above linked PR?
