### ISSUE TITLE
[UI] Update deprecated property "scrollFullHeight" from MUI Datables responsive options

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#7556]
#### Current Behavior
The Mui datable is using a responsive option - scrollFullheight which is now deprecated. The MUI datatables are used throughout Meshrey UI. 
![image](https://user-images.githubusercontent.com/65453826/232234066-42d964ca-1c57-4502-b410-c1010a58e951.png)

#### Desired Behavior
Update the value of the property `responsive` according to the latest version of MUI datable. Make sure the behavior of the datable should not change. 

#### Implementation
Check release notes of MUI Datables, and new responsive property values here - https://github.com/gregnb/mui-datatables

#### Acceptance Tests
The behavior of the datable should not change. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by MdSahil-oss** [comment]
@leecalcote I would like to work on it.
