### ISSUE TITLE
Docs: Breadcrumb link returns 404

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#7557]
#### Current State

 In the page at https://docs.meshery.io/getting-started/overview the `getting started` breadcrumb leads to a 404
<img width="1435" alt="Screenshot 2023-04-15 at 9 09 15 PM" src="https://user-images.githubusercontent.com/76054921/232234716-8d5a9b01-5d3d-469d-994b-c966ac3e1f89.png">

#### Desired State
The breadcrumb should be made un clickable or a relevant page should be shown.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Saksham294** [comment]
I would like to work on this, however I think we should first decide if we want to display any page or disable this link.
I think disabling could be one idea but usually when we have pages linked using these slashes '/' it usually refers to links, disabling it may not look good on the UI part. Maybe we should rather redirect to another page

**Comment by shubham-singh-748** [comment]
This issue seems quite interesting to me, i can take this issue, if no one solving it.

**Comment by withgaurav** [comment]
@leecalcote Should I add the docs here for getting started, So that it will directly redirect to the "getting started" page

**Comment by abdullah1308** [comment]
> I would like to work on this, however I think we should first decide if we want to display any page or disable this link. I think disabling could be one idea but usually when we have pages linked using these slashes '/' it usually refers to links, disabling it may not look good on the UI part. Maybe we should rather redirect to another page

@Saksham294 A good approach would be to remove `getting started` from the breadcrumb, so that the breadcrumb becomes `home/overview`. Have you built and run the Meshery docs locally ?

**Comment by abdullah1308** [comment]
Issue closed due to #7591
