### ISSUE TITLE
Unable to Login into meshery extension in Docker Desktop

### ISSUE THREAD

**Issue by AakashRaj20** [meshery/meshery#7572]
#### Current Behavior

When trying to Login into the meshery through the meshery extension getting error this site cant be reac

https://user-images.githubusercontent.com/103671752/233075384-43082aca-d04a-45a8-9181-46117692a842.mov

hed, local host refused to connect.

#### Expected Behavior

It should allow me to login into my mesh

#### Environment

- **Host OS:** MacOs Montery
- **Platform:** Docker Desktop

#### To Reproduce
1. Go to extensions on docker desktop
2. Click on install on meshery extension
3. click login on the meshery account login from github account on chrome

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@AakashRaj20 i haven't come across another user who is unable to sign in. @senali-d can you confirm that you're able to sign in and confirm your OS?

**Comment by senali-d** [comment]
@leecalcote Yeah I have been able to login.

OS: ubuntu 20.04
Docker Desktop: 4.19.0

// @AakashRaj20

**Comment by anirudhjain75** [comment]
Im not facing this issue but there is a stale tab open. I think it should be closed automatically after updating docker desktop.

Stale tab screenshot

<img width="1512" alt="Screenshot 2023-06-05 at 3 40 42 PM" src="https://github.com/meshery/meshery/assets/14249589/29ff70ec-6dc7-4353-b63a-299670bbb878">

**Comment by leecalcote** [comment]
> Im not facing this issue but there is a stale tab open. I think it should be closed automatically after updating docker desktop extension
> 
> Stale tab screenshot
> 
> <img alt="Screenshot 2023-06-05 at 3 40 42 PM" width="1512" src="https://user-images.githubusercontent.com/14249589/243322899-29ff70ec-6dc7-4353-b63a-299670bbb878.png">

Yes, you're right, @anirudhjain75. It would be great if we can get this window to close.
