### ISSUE TITLE
[UI] Add Support for Credentials within the Settings UI.

### ISSUE THREAD

**Issue by harkiratsm** [meshery/meshery#7575]
#### Desired Behavior

Using the existing endpoints to query credentials, integrate the schema-driven approach to credentials within the Settings UI.

#### Implementation

TBW

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Akshaybagai52** [comment]
@harkiratsm can you assign this issue to me ?

**Comment by harkiratsm** [comment]
#7634

**Comment by ranjanmangla1** [comment]
if nobody is working on this issue, please assign me this issue, i would love to work on it!

**Comment by harkiratsm** [comment]
Fixed by #7634
