### ISSUE TITLE
[DevOps] Redeploy https://demo.meshery.io in AKS

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7579]
#### Current Behavior
A deployment of the Meshery Playground is in AKS under demo.meshery.io. This deployment needs reworked.

#### Desired Behavior
Users should be able to visit this environment just like they visit and use the playground.meshery.io environment.

#### Implementation
1. Ensure that each Meshery release deploys a new version of the demo.meshery.io environment with a `playground` image.
1. Ensure that SSL termination is configured correctly.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by elle-Bee** [comment]
Hey @leecalcote  is this issue still up for grabs?
