### ISSUE TITLE
[Designs] Support Design-action on Grid as well as table View consistently

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#7584]
I can't save or delete in grid card view, but can do so in table view. 

## Grid View

<img width="662" alt="Screenshot 2023-04-20 at 3 14 48 PM" src="https://user-images.githubusercontent.com/7570704/233478053-4d1418e1-c622-43a9-8326-166ca4fac908.png">

## Table View

<img width="980" alt="Screenshot 2023-04-20 at 3 14 58 PM" src="https://user-images.githubusercontent.com/7570704/233478047-a0699e1e-b8a1-4ec9-905a-9aa01207f8d9.png">

_Originally posted by @leecalcote in https://github.com/meshery/meshery/issues/7578#issuecomment-1516892271_

**Comment by leecalcote** [comment]
@Abhishek-kumar09 if you're taking this on, great. If not, you'll need to add more context for another contributor to be able to address it.

**Comment by MdSahil-oss** [comment]
@Abhishek-kumar09 If you're not working on this please explain this issue a little bit more & assign it to me, I'd like to work on it :)

**Comment by leecalcote** [comment]
There should be a trashcan icon and a save icon in the lower right hand corner of the "Edit Design" model when you're in the grid view on the Designs page.

Grid view: 
<img width="111" alt="Screenshot 2023-04-21 at 2 45 31 PM" src="https://user-images.githubusercontent.com/7570704/233722238-b71defd6-ccc6-4ab4-aca8-2e261c9aa835.png">
