### ISSUE TITLE
[Docs] Replace contents of Meshery Overview

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#7591]
#### Current State
Currently the pages https://docs.meshery.io/getting-started/overview and https://docs.meshery.io/project are redundant. The 'project' page however is more comprehensive and contains additional links. 

#### Desired State

1. Change `Meshery Overview` at https://docs.meshery.io to link to https://docs.meshery.io/project

<img width="1410" alt="Screenshot 2023-04-22 at 2 12 46 AM" src="https://user-images.githubusercontent.com/76054921/233730999-38ba2f7d-5dfa-4cbc-9fbc-1cb1c145548f.png">

2. Fix the table headers at  https://docs.meshery.io/project

Currently they look like the following -

<img width="917" alt="image" src="https://user-images.githubusercontent.com/76054921/233731653-e1d57554-b3ce-421c-8511-10b5d10731df.png">
 
Instead they should look like the ones at https://docs.meshery.io/getting-started/overview

<img width="919" alt="image" src="https://user-images.githubusercontent.com/76054921/233731844-df96239b-5ebe-49f8-a9ac-0a48484e7e17.png">

3. Make sure that all content at https://docs.meshery.io/getting-started/overview is contained in https://docs.meshery.io/project

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Vee339** [comment]
Hi, I want to work on this issue.

**Comment by abdullah1308** [comment]
@Vee339 Have you built and run the docs locally ?

**Comment by rijusougata13** [comment]
hi @abdullah1308 , i have already setup docs in my local. Can I work on this?

**Comment by rijusougata13** [comment]
hi @abdullah1308 , I have fixed the issue. Here it looks like. Let me know if I can send a PR or not. 
Thank you
<img width="1080" alt="Screenshot 2023-04-23 at 3 12 41 AM" src="https://user-images.githubusercontent.com/52108435/233807814-24574dbb-798c-4a29-922d-fc9ff79184e3.png">

**Comment by Vee339** [comment]
> @Vee339 Have you built and run the docs locally?

No, I haven't. Please assign this issue to @rijusougata13. I think he is already working on that.

**Comment by abdullah1308** [comment]
@rijusougata13 yes put up a PR linked to this issue to be reviewed.

**Comment by rijusougata13** [comment]
@abdullah1308 please have a look.
