### ISSUE TITLE
[Docs] Update Naming Convention 

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery#7606]
#### Current State
Usage of Service Mesh at several instances can be found 
![image](https://user-images.githubusercontent.com/92504666/234400282-e09fea44-13cd-46dc-abb7-510e673386b4.png)

#### Desired State
Replace `Service Mesh` with `Cloud Native` at [ reference/mesheryctl](https://docs.meshery.io/reference/mesheryctl) and its related components

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by souravpy** [comment]
Can I take it up, and can you provide a link to resources on how to setup docs locally?
