### ISSUE TITLE
[Docs] Add a Catalog page

### ISSUE THREAD

**Issue by ayushthe1** [meshery/meshery#7618]
#### Desired State
A new page should be created on docs describing Meshery Catalog.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by dancemonkey007** [comment]
I would like to work on this issue. Is there any reference or example of what content should i write ?

**Comment by yash37158** [comment]
I would like to work on this issue @ayushthe1

**Comment by vishalvivekm** [comment]
> I would like to work on this issue. Is there any reference or example of what content should i write ?

please refer to https://meshery.io/catalog.

**Comment by vishalvivekm** [comment]
would you be on today's websites call @dancemonkey007 @yash37158 : [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#)

**Comment by yash37158** [comment]
Yes

**Comment by yash37158** [comment]
Hey, @dancemonkey007 are you working on the issue?

**Comment by yash37158** [comment]
Hey @leecalcote thanks for assigning this, i m sorry i couldn't check the update. Do we have design requirements for the catalog page ?

**Comment by leecalcote** [comment]
I'll let @ayushthe1 point you to them.

**Comment by leecalcote** [comment]
Tagging @senali-d @goldfishdolphin for awareness

**Comment by yash37158** [comment]
Hey @senali-d @goldfishdolphin, lets get connect on slack to proceed

**Comment by vishalvivekm** [comment]
what's the status @yash37158 ?

**Comment by yash37158** [comment]
yes I have created a page, just caught up with college assignments right now. I have few queries regarding the information need to be feeded.
should i create a draft pull request

**Comment by senali-d** [comment]
> yes I have created a page, just caught up with college assignments right now. I have few queries regarding the information need to be feeded. should i create a draft pull request ?

@yash37158 Yes go ahead. It will help to get the feedback from community.

**Comment by vishalvivekm** [comment]
> Hey @vishalvivekm @senali-d @leecalcote @ayushthe1, can you please give me some suggestions on what should I add more

@yash37158 
Glad that you are back in action 😃 
please check these out:
- a new page added on layer5.io : https://layer5.io/catalog
- Meshery catalog description by the Legend @leecalcote himself:  https://github.com/layer5io/layer5/pull/4161#issuecomment-1547892457

**Comment by yash37158** [comment]
Yeah sure

**Comment by yash37158** [comment]
should I also add how to deploy catalogs in meshery ?

**Comment by goldfishdolphin** [comment]
> meshery ?

Yes, @yash37158 that will be great.

**Comment by yash37158** [comment]
can you please me in gathering the steps to create a catalog or can point to some reference @leecalcote @senali-d @goldfishdolphin

**Comment by vishalvivekm** [comment]
> can you please me in gathering the steps to create a catalog or can point to some reference @leecalcote @senali-d @goldfishdolphin

[Add your content to the cloud native catalog.](https://github.com/meshery/meshery.io/blob/master/README.md#add-your-content-to-the-cloud-native-catalog) - this much should be enough for now, Yash.

@yash37158 Please push your updates and let's wrap it up before next websites call on monday.
I'm adding this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.7hys5m5156u1), let's get it reviewed please.
