### ISSUE TITLE
[UI] Create a dropdown to show mesh model summary

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#7620]
#### Current Behavior
For now, the mesh model summary only shows component's, and relationship's name and count. 

#### Desired Behavior
We want to show JSON of the clicked component having the same **Model** and clicked relationship having the same **Kind** in a drop down menu. 

#### Implementation
Use `/api/meshmodels/models/{model}/components/{name} ` to fetch model summary and display it in a MUI dropdown component. 

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sarkartanmay393** [comment]
@UsmanDev09 I'd like to take it over.

**Comment by Yashsharma1911** [comment]
Hey @sarkartanmay393 thanks for raising your hand we have other issues with which you might like to help and let me know if you need help in finding them as @UsmanDev09 already started working on it so assigning it to him

**Comment by sarkartanmay393** [comment]
@Yashsharma1911 Ohh sure
