### ISSUE TITLE
[Cypress] Failing E2E tests in User Preference. 

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#7622]
#### Current Behavior
Currently, E2E tests for User Preferences are failing - https://github.com/meshery/meshery/actions/runs/4822176767/jobs/8589252885?pr=7621#step:16:241 
![image](https://user-images.githubusercontent.com/65453826/234942889-d944fc11-2cfb-4ba5-8aef-0afe3309ac5b.png)

#### Expected Behavior
All the tests should pass, logs can be checked from any failing PR. 

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Freedisch** [comment]
@Chadha93 I will check that out
