### ISSUE TITLE
[Docs] Typo issue in meshery Rest API

### ISSUE THREAD

**Issue by senali-d** [meshery/meshery#7625]
#### Current State
Word "specific" repeat.

![documentation](https://user-images.githubusercontent.com/52546856/235177374-3ec52199-c799-4c0d-8f20-005a34383f45.png)

#### Desired State
"Handle GET request for getting meshmodel components of a specific model."

![doc-updated](https://user-images.githubusercontent.com/52546856/235215507-1936f050-1679-4da9-831c-271a1c56cbff.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by suhasamaresh** [comment]
I would like to work on this issue. Can you please walk me through the process

**Comment by UsmanDev09** [comment]
@senali-d Shouldn't it be` specific model` rather than just `specific`

**Comment by senali-d** [comment]
@UsmanDev09 Yeah it should be. Thank you

**Comment by shivamganwani** [comment]
Raised PR - https://github.com/meshery/meshery/pull/7628

**Comment by shivamganwani** [comment]
This has been merged https://github.com/meshery/meshery/pull/7628

**Comment by vishalvivekm** [comment]
done by #7628
