### ISSUE TITLE
Chat Feature in Meshmap design section

### ISSUE THREAD

**Issue by 0904-mansi** [meshery/meshery#7661]
#### Current Behavior

There is not any option for chatting between users who are active or designing in a group while designing MeshMap.

#### Desired Behavior

We can add a normal chat feature so that users can communicate or discuss while designing MeshMap.

#### Mockups

<img width="386" alt="Chat" src="https://github.com/meshery/meshery/assets/7570704/35b8ac6c-3bb6-4cf5-869f-7dd7e04e5654">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by 0904-mansi** [comment]
I want to work on this issue.

**Comment by 0904-mansi** [comment]
\assign

**Comment by itsarraj** [comment]
we can use sockets

**Comment by leecalcote** [comment]
Mockup added.

**Comment by leecalcote** [comment]
> we can use sockets

Yes, MeshMap uses sockets currently.

**Comment by itsarraj** [comment]
okay
