### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#7666]
#### Current State
The document at https://github.com/meshery/meshery/tree/master/ui states that node version 14.8.0 is to be used. 
![version](https://github.com/meshery/meshery/assets/31584129/cc546a11-3376-41d0-9122-acd16dd7235c)

#### Desired State
Node version 18 should be used. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by duckling69** [comment]
Hey @UsmanDev09 @leecalcote i'd like to work on this issue

**Comment by UsmanDev09** [comment]
Thank you @duckling69 . You can work on this.
