### ISSUE TITLE
[UI] CTA for Meshmap

### ISSUE THREAD

**Issue by duckling69** [meshery/meshery#7669]
#### Current Behavior

No current CTA for Meshmap

#### Desired Behavior

Make a stylish CTA for Meshmap for https://layer5.io/cloud-native-management/meshmap

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by duckling69** [comment]
Hey @leecalcote @vishalvivekm @Chadha93 can anyone assign this issue to me

**Comment by Chadha93** [comment]
@duckling69 You have opened the issue in the wrong organisation's repository. Please open this in `meshery/meshery`
