### ISSUE TITLE
[Server] Cluster ping test enhancement

### ISSUE THREAD

**Issue by Azanul** [meshery/meshery#7671]
#### Current Behavior
There is a 1 second timeout (soon to be increased to 5 seconds) on pinging the k8s cluster. 

#### Desired Behavior
After the timeout the connectivity attempt shouldn't be dropped immediately, it should continue and the user should be notified that the cluster did respond but it responded late.

#### Implementation
Using a `context` with a timeout is desirable although any other approach can also be discussed.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by RickDeb2004** [comment]
I think I should make separate file, but in which directory I have to add the file confusing in that

**Comment by 8rxn** [comment]
Hey @Azanul , 
I would like to try on this issue. Would you mind helping me around?

**Comment by Azanul** [comment]
> Hey @Azanul , I would like to try on this issue. Would you mind helping me around?

Sure thing.

**Comment by Azanul** [comment]
The changes are to be made in `func (kc K8sContext) PingTest() error` in `server/models/k8s_context.go`.

**Comment by Chadha93** [comment]
@8rxn Thank you for opening a PR, I'm opening a new Issue let's link your PR to it.
