### ISSUE TITLE
Replace in-cluster kubeconfig in Playground environment with an external cluster

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery#7703]
#### Current Behavior

Currently Meshery server running in playground.meshery.io has access to the cluster it is deployed to. 
Since [User]->can control->[Meshery]->can control->[Cluster which Meshery is running on]. In absence of finer RBAC controls to Meshery and user level deployment policies, this makes the playground Meshery server vulnerable to a degree that it can potentially undeploy itself.
#### Desired Behavior

- [ ] Add support for passing a parameter on build time which disallows automatic cluster detection. So that playground Meshery server doesn't have access to the cluster it is deployed on.
- [ ] Modify helm charts to add this flag in values.yaml
- [ ] perform a one-time helm upgrade by adding that flag through --values. 
- [ ] Add an extra step [here](https://github.com/meshery/meshery/blob/58b9cf04b1248116231f7f592209998798e74822/.github/workflows/cncf-playground-deploy-meshery.yaml#L16) which uploads the kubeconfig of secondary cluster(whose kubeconfig will be stored in secrets) to Meshery with proper auth token.
- [ ] Create and get ready the secondary cluster for use. 
- [ ] Modify the workflow [here](https://github.com/meshery/meshery/blob/master/.github/workflows/cncf-playground-reset.yaml) to reset the secondary cluster and not primary.
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Azanul - - #1 in this list would have been delivered by the connection state management feature.

**Comment by leecalcote** [comment]
@Revolyssup will you consider adding a checkbox here for adding this flag in meshconfig?

**Comment by anshuhtwt** [comment]
@leecalcote I want to work on this issue, please assign it to me...

**Comment by anshuhtwt** [comment]
@leecalcote 5/10, I know all the concepts but didn't tried any development yet but looking at the % of go used in the project I should start learning more...

**Comment by leecalcote** [comment]
Ok, understood. If you don't get this PR'ed in a week, please unassigned yourself to avoid squatting on an issue that another contributor can carry forward.

**Comment by Revolyssup** [comment]
@leecalcote Since the deployment pattern was changed to a docker based deployment (last I remember), can we close this issue?

**Comment by leecalcote** [comment]
@Revolyssup, yes, in context of the Meshery Playground, this issue has been circumvented. 👍  In context of features that Meshery needs, fine-grained RBAC is on the roadmap; is a necessity.
