### ISSUE TITLE
dead link for 'Suggested reading' in Meshery doc

### ISSUE THREAD

**Issue by sayyedarib** [meshery/meshery#7708]
### Description
There's a section for "Suggested Reading" but there's no content in it, also it has a dead link
It seems that the section is still under development, until it's get ready , this section can removed or hidden in production
![problem_2](https://github.com/layer5io/layer5/assets/90370535/4d16441a-4c12-4308-920d-cf39b399fdbe)

### Expected Behavior

- [ ] remove or hide the "Suggested Reading" section

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sayyedarib** [comment]
@leecalcote please assign me this issue

**Comment by sayyedarib** [comment]
Ok, can we discuss this too in the meet.

**Comment by sayyedarib** [comment]
@thisiskaransgit what else should I do other than comment, can you please suggest?

**Comment by iArchitSharma** [comment]
The issue doesn't seem to exist anymore.
