### ISSUE TITLE
[UI] Fix the Alignment of Layer5 logo with other logos

### ISSUE THREAD

**Issue by Mohith234** [meshery/meshery#7716]
#### Current Behavior

The layer5 logo image doesn't align with the other logos in heroes section of meshery.io

#### Desired Behavior

The logos must be aligned in order to maintain a good UI

#### Screenshots/Logs

![image](https://github.com/meshery/meshery/assets/88539464/9d0e9b5d-f879-4e56-b41f-1fe9d151ffc8)

#### Environment

- Browser: Chrome 
- Host OS: Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Mohith234** [comment]
I can work on this issue! Please assign me

**Comment by Akshaybagai52** [comment]
Hey can you assign this issue to me ?

**Comment by AryanSharma9917** [comment]
Heyy @Mohith234 I would like to contribute to this project could you please assign this issue to me?

**Comment by Yashsharma1911** [comment]
Hey @Mohith234 thanks for mentioning that but this issue is related to meshery.io for that please create issue on [github/meshery/meshery.io](https://github.com/meshery/meshery.io)

**Comment by 0xt3j4s** [comment]
@Yashsharma1911 I have created the [issue](https://github.com/meshery/meshery.io/issues/1175) there. You can close this one.

**Comment by Yashsharma1911** [comment]
Thanks for mentioning this @0xt3j4s
