### ISSUE TITLE
[cypress] Fix e2e tests in Meshery-UI

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#7733]
#### Current Behavior

Current User-preferences tests are failing which needs research for reason till then, those tests are skipped to give green signal to PRs that arent dependedent. Meanwhile, we should take time to fix it.
<img width="695" alt="Screenshot 2023-05-25 at 12 43 58 AM" src="https://github.com/meshery/meshery/assets/48255244/315d543e-a504-427a-94ad-29b585620f5d">

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vaibhav135** [comment]
@Abhishek-kumar09 can you assign this to me. I will take a look into it.

**Comment by Abhishek-kumar09** [comment]
@vaibhav135 While this issue is opened, I think this isn't a good issue first you should work on, given there should be some research here to identify the cause of the problem and one or more systems are directly or indirectly connected with this issue.

But hey, I think you can still take a look, and give your inputs.

**Comment by vaibhav135** [comment]
@Abhishek-kumar09 yes sure I will take a look into it for sure.

**Comment by Abhishek-kumar09** [comment]
Yeah the tests should be passing. These tests passes on local environment but fails in ci.
