### ISSUE TITLE
[CI] [Testing] Meshery Test plan link & guidelines for using it to "Continuous Integration / DevOps" template (.github/ISSUE_TEMPLATE/ci.md)

### ISSUE THREAD

**Issue by MarioArriaga92** [meshery/meshery#7738]
#### Current Behavior
“Continuous Integration / DevOps - Improve or update workflows or other automation” issue template does not include links nor guidelines on how to work with Meshery Test Plan Google Docs spreadsheets

#### Desired Behavior
Any contributor using the “Continuous Integration / DevOps - Improve or update workflows or other automation” issue template [.github/ISSUE_TEMPLATE/ci.md](https://github.com/meshery/meshery/blob/master/.github/ISSUE_TEMPLATE/ci.md?plain=1) from the [New issue template list](https://github.com/meshery/meshery/issues/new/choose) should see:
- Link to [Meshery Test Plan - v0.7.0 sheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)
- Link to [Meshery Test Plan - Automated Tests/Builds sheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=1214153102) Google sheet
- Some guidelines for using them, keeping them updated, etc.

#### Implementation
@Revolyssup, @theBeginner86, @Abhishek-kumar09, @leecalcote, myself, and any other contributors are welcome to update this section or enter issue comments making suggestions but here are some initial thoughts:
1. Add new row to v0.7.0 sheet in case a new Test Scenario **(Combination of Test Group, Component Under Test, Platform, Service Mesh, Action and/or Expected Outcome)**: 
   - Started existing recently as per implemented **(merged PR targeting 'master' branch)**
   - Will exist as per upcoming New Features/Enhancements being discussed/implemented. **(New Test Group, Component Under Test, Platform, etc.)**
2. Update existing row to v0.7.0 sheet in case an existing Test Scenario **(see point 1 for definition)**:
   - Has changed in a significant/relevant way **(different Component, , etc.)**
   - "Actual Outcome" and/or "Additional Remarks" should be updated when an issue, abnormal or unexpected behavior has occurred during usage with Meshery UI, Mesheryctl CLI, Meshery Docker Extension, a specific Meshery adapter and/or Meshmap extension as a user through a recent release (or when building from source).

#### Acceptance Tests
"Continuous Integration / DevOps" issue template's **Contributor [Guides]** section is updated with a new bullet with link and guidelines mentioned above:
![CleanShot 2023-05-25 at 13 00 34](https://github.com/meshery/meshery/assets/23443575/1180360f-7073-41f2-8078-fc0a205d7220)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Ghat0tkach** [comment]
I would like to work on this issue 
i have already made the desired changes but i am completely clueless about speicifying guidlines to keep them updated or to use them

below is the screnshot of desired changes
![image](https://github.com/meshery/meshery/assets/59855919/37e43242-d36b-4abd-ab75-86860a1afb33)

**Comment by MarioArriaga92** [comment]
@Ghat0tkach hi, in the Issue description there's an "Implementation" section, can you please take a look? There are a couple of guidelines that should also be added.

Feel free to create a PR and associate it to this issue so we can move forward with these changes please. 🙏 

Thanks!
- Mario

**Comment by ashutosh887** [comment]
@Ghat0tkach @MarioArriaga92 

Please assign this issue to me if still not resolved :)

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach @MarioArriaga92 
> 
> Please assign this issue to me if still not resolved :)

I'm already working on this issue right now , looking forward for @MarioArriaga92 review to draft the final PR.😄.
However you are free to suggest desired changes 🙂

**Comment by ashutosh887** [comment]
Please go ahead @Ghat0tkach 
If you need any help let me know 😄

**Comment by Ghat0tkach** [comment]
> Please go ahead @Ghat0tkach 
> If you need any help let me know 😄 

Thank you @ashutosh887 , I'll suggest you to join slack channel for better communication and good-first issues.
(Slack)[https://join.slack.com/t/layer5io/shared_invite/zt-1wx0a3486-XRkghVSnv7ejTE5vWMutWA]

**Comment by MarioArriaga92** [comment]
@Ghat0tkach can you please create PR and associate it to this issue so it can be reviewed please? Thanks!

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach can you please create PR and associate it to this issue so it can be reviewed please? Thanks!

Was waiting for your feedback! Thank you will raise a PR soon.
