### ISSUE TITLE
[CI] Find root cause for `[data-cy="istio"]` element's parent `div` visibility is set to `hidden` causing UI  "Test Lifecycle Paths With None Provider > Visit Istio by button Click" e2e test to fail

### ISSUE THREAD

**Issue by MarioArriaga92** [meshery/meshery#7741]
#### Current Behavior
While investigating #7740, re-running PR checks described there returned a [UI e2e test failure](https://github.com/meshery/meshery/actions/runs/5084120742/jobs/9136134367#step:16:126) in [ui/cypress/e2e/e2e/lifecyclecheck_spec.js](https://github.com/meshery/meshery/blob/master/ui/cypress/e2e/e2e/lifecyclecheck_spec.js)'s "Test Lifecycle Paths With None Provider > Visit Istio by button Click" e2e test:
![CleanShot 2023-05-25 at 14 49 23](https://github.com/meshery/meshery/assets/23443575/954fef6d-1dbd-4253-a732-0c58eb251621)

The test tried to run the commands `cy.get('[data-cy="istio"]').click();` after clicking the `'[data-cy="lifecycle"]'` element in Meshery UI.

The returned error is `CypressError: Timed out retrying after 4050ms: cy.click() failed because this element is not visible` and the additional output is `This element '<div.MuiButtonBase-root.MuiListItem-root.jss75.jss57.jss61.MuiListItem-gutters.MuiListItem-button>' is not visible because its parent '<div>' has CSS property: 'visibility: hidden'`

#### Desired Behavior
The reason why the `[data-cy="istio"]` element's parent `div` element visibility is set to `hidden` is identified and [ui/cypress/e2e/e2e/lifecyclecheck_spec.js](https://github.com/meshery/meshery/blob/master/ui/cypress/e2e/e2e/lifecyclecheck_spec.js) test code (and Meshery UI app code, if needed) is modified so test is green again.

#### Implementation
To investigate test failures that happen during e2e tests:
1. Run Meshery server locally by cd'ing into Meshery repo root folder and run `make server` **(refer to [Contributing to Meshery Server](https://docs.meshery.io/project/contributing/contributing-server) as needed)**
2. In a 2nd terminal, in order to get meshery istio adapter running locally:
   - Pull and open [meshery-istio repo](https://github.com/meshery/meshery-istio)
   - cd into its root folder and run `make run`
3. In a 3rd terminal, in order to run e2e tests locally:
   - cd into `/ui` folder
   - run `npm i`
   - run `npm run cy:dev:open`
   - Explanation: Prior npm script starts Meshery UI dev server, waits for it to respond and starts cypress in [open mode](https://docs.cypress.io/guides/getting-started/opening-the-app#cypress-open) for you.
   - Wait for cypress desktop app to open and select [ui/cypress/e2e/e2e/lifecyclecheck_spec.js](https://github.com/meshery/meshery/blob/master/ui/cypress/e2e/e2e/lifecyclecheck_spec.js) to make the tests run
   - Make the tests run several times, observe Cypress Command Log & Meshery UI inside Cypress runner and try to reproduce the same issue described above locally.
4. Use [Layer5 #cypress-testing slack channel](https://layer5io.slack.com/archives/C02Q44SSCH4) to ask for help and refer to [Contributing to Meshery's End-to-End Tests using Cypress / How to manually run end-to-end tests](https://docs.meshery.io/project/contributing/contributing-cypress#how-to-manually-run-end-to-end-tests) and [Contributing to Meshery's End-to-End Tests using Cypress / References](https://docs.meshery.io/project/contributing/contributing-cypress#references) as needed.

#### Acceptance Tests
Mentioned e2e test passes, the root cause **(whether it's an issue in test code or app code)** is identified and remediated and a postmortem is produced to prevent this kind of incident from occurring in the future!

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by suhail34** [comment]
I tried runnig the test locally and it passed all the test

**Comment by MarioArriaga92** [comment]
Hi @suhail34, thanks for helping out with this. Can you please try re-running the tests several times? 

Sharing screenshots of the test run is very helpful too just paste the image in the GitHub comment box please.

Goal is to see it fail and identify what's causing the failure and enhance test or app code to avoid intermittent failure **(I suspect it's the Meshmap modal that appears occasionally but we need visual confirmation)**

**Comment by suhail34** [comment]
![image](https://github.com/meshery/meshery/assets/77241166/85bcfe26-db57-4f9d-8d25-70e60672a852)
![image](https://github.com/meshery/meshery/assets/77241166/fc3fe23d-8d30-49ae-a634-c9a17ffd375e)
![image](https://github.com/meshery/meshery/assets/77241166/e3a41ca5-2fa6-405e-a16a-f35aab577646)
![image](https://github.com/meshery/meshery/assets/77241166/0631b292-1fa2-470d-b5b8-0a8fbd7e2626)

Hi @MarioArriaga92 This are the test that fails if i don't deploy both that adapters from meshery settings adapters tab but after deploying it from the settings adapters tab all the test gets passed

**Comment by suhail34** [comment]
Hi @MarioArriaga92 are my points valid

**Comment by MarioArriaga92** [comment]
> Hi @MarioArriaga92 are my points valid

They are valid @suhail34, although I'd suggest waiting for all the spinning icons in the left-side pane on the cypress runner to disappear before taking screenshots.

Also, consider there's a top-left indicator of passing (green checkmark icon) & failing (red cross icon) tests so by seeing no numbers besides those icons it means the test hadn't finished running, try waiting for tests to finish that way we can see if the error message(s) we get locally are the same as the ones we get in CI runs.

Remember we're trying to reproduce the error `CypressError: Timed out retrying after 4050ms: cy.click() failed because this element is not visible` locally to find the root cause and thus avoid intermittent failures
