### ISSUE TITLE
[DevOps] Playground: Configure NGINX to upgrade HTTP to HTTPS (Kubernetes deployment)

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7744]
#### Current Behavior
http://playground.meshery.io does not auto upgrade to https://playground.meshery.io, but should.

#### Implementation
1. Modify the `/install/playground` configuration for NGINX container - https://github.com/meshery/meshery/blob/master/install/playground/kubernetes/nginx.conf

#### Acceptance Tests
1. Insecure connections on port 80 are automatically upgraded to secure connections on 443.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by anshuhtwt** [comment]
Hello @leecalcote, Could you please assign this issue to me.?? I'm eager to contribute and believe I can make a positive impact.
