### ISSUE TITLE
[DevOps] Playground: Expose Grafana and Prometheus ports

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7764]
#### Current Behavior
We’re in need of configuring connectivity between the Meshery host and the Kubernetes cluster in the Playground for Grafana and Prometheus services running in cluster. Otherwise, metrics and dashboards will be perpetually unavailable in the Playground environment.

#### Desired Behavior
Meshery Server should be able to connect with port 9000 and port 3000 as exposed from the Playground's cluster.

#### Implementation
See [Playground deployment diagram](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g214519dc4ed_0_10).

#### Acceptance Tests
1. Users can see metrics in performance dashboards.
 
---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Freedisch** [comment]
Hi @leecalcote , I want to work on it

**Comment by leecalcote** [comment]
The two server are running Ubuntu 20.04
