### ISSUE TITLE
Meshery UI crashes when clicked on any Service Mesh

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#7768]
#### Current Behavior

When going over https://playground.meshery.io/ , in dashboard when clicked on any service mesh dropdown the UI crashes until clicked anywhere

https://github.com/meshery/meshery/assets/90546692/f9bddacd-4822-4c19-a906-46423cb61f18

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ashutosh887** [comment]
@sudhanshutech @senali-d @SainiAditya1 

Should I work on this now?

**Comment by SainiAditya1** [comment]
hey @ashutosh887 , I am doing it and will make a PR as early as possible.

**Comment by ashutosh887** [comment]
Let me work on this @sudhanshutech

**Comment by yashpandey06** [comment]
can i work on this issue

**Comment by Shaman20** [comment]
@ashutosh887 Are you working on this if not @sudhanshutech Can you assign me this issue?

**Comment by ashutosh887** [comment]
Working on it @Shaman20 
Creating PR soon

**Comment by Shaman20** [comment]
Yep Thanks for the update!! @ashutosh887

**Comment by EraKin575** [comment]
If this issue is still there, I would like to work on this

**Comment by Yashsharma1911** [comment]
@sudhanshutech is this issue still valid?
