### ISSUE TITLE
[Docs] Add a section in Meshmap Developer guide about git tags

### ISSUE THREAD

**Issue by ayushthe1** [meshery/meshery#7769]
A section about updating your git tags when building Meshery UI to avoid error should be added in [Meshmap Developer guide](https://docs.google.com/document/d/1y-LHhOcQGA9fiUbN5CR42CXvjaPxKAJHftGrLgxJPTo/edit#). This [discuss post](https://discuss.layer5.io/t/getting-meshery-deployment-incompatible-message-on-running-meshery-ui/2771) can be used for reference

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by aku1310** [comment]
Hi, I am interested in working on this issue, but I do have a doubt. Since I don't have access to the google doc, are the changes supposed to be made in the docs section of the repo or in the google doc file only?

**Comment by vishalvivekm** [comment]
> Hi, I am interested in working on this issue, but I do have a doubt. Since I don't have access to the google doc, are the changes supposed to be made in the docs section of the repo or in the google doc file only?

@aku1310 
Would you confirm if you've filled the [Newcomers' form](https://layer5.io/newcomers) ?

**Comment by aku1310** [comment]
> @aku1310 Would you confirm if you've filled the [Newcomers' form](https://layer5.io/newcomers) ?

Hi, yes, I've filled the form more than a month ago.
