### ISSUE TITLE
[UI] Prometheus: unable to manual enter URL

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7790]
#### Current Behavior
Users are unable to manually enter the URL to their Prometheus instance. Pressing enter has no effect.

<img width="1043" alt="Screenshot 2023-06-04 at 9 10 32 PM" src="https://github.com/meshery/meshery/assets/7570704/485f6e5d-d67d-4dff-a05c-64f3734123f4">

You can reproduce this issue in the Meshery Playground, which has a Prometheus instance running on http://10.65.18.1:30107

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by MUzairS15** [comment]
@leecalcote We always discovered telemetry components exposed endpoints and provided option to choose one, and never had an option to manually enter.

I can confirm the discovery still works
<img width="1141" alt="Screenshot 2023-06-07 at 7 03 58 AM" src="https://github.com/meshery/meshery/assets/79860504/e12673f0-2e89-4ea0-b4d0-4559f20fcfba">

**Comment by MUzairS15** [comment]
Though for the playground, Prometheus is not discovered.  🤔

**Comment by Freedisch** [comment]
> Though for the playground, Prometheus is not deployed, right?? Or it was removed??

For Prometheus, it's actually running on the k8s [cluster](https://github.com/meshery/meshery/blob/master/install/playground/kubernetes/prometheus.yaml)

**Comment by leecalcote** [comment]
The nightly script might have deleted the `istio-system` namespace, where prometheus and grafana were deployed. @Revolyssup we're in need a `monitoring` namespace in which we have a permanent prometheus and grafana deployment with services exposed to Meshery Server (to the Docker host)...

**Comment by Revolyssup** [comment]
> 

We did have prometheus deployed in monitoring namespace but I think thats no longer the case as the cluster was bootstrapped from scratch.
