### ISSUE TITLE
[Docs] Update Meshery Architecture Page 

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery#7791]
#### Current State
- Figures used in the following sections are outdated and are in need to be updated 
  https://docs.meshery.io/concepts/architecture
  https://docs.meshery.io/guides/upgrade

- Does not include the Docker Extension Architecture description in  [architecture](https://docs.meshery.io/concepts/architecture) page  
  
#### Desired State

- Update the figures with the help of the Meshery Architecture Slide  
- Add Docker Extension architecture sub section

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Ghat0tkach** [comment]
I would like to work on this issue .
Could you please give me the link of those figma files which are required to be updated.

**Comment by thisiskaransgit** [comment]
@Ghat0tkach sure go ahead 🚀 
You can find the slides (Meshery Architecture ) in the community drive, download them as SVG and replace them with current ones

**Comment by Ghat0tkach** [comment]
> 
> Since you don't have access, I'll take care of this issue, thanks for volunteering though 😄 

Oh no worries , Will look for other issues . Thank you

**Comment by ashutosh887** [comment]
@thisiskaransgit I would like to work on this
