### ISSUE TITLE
[Docs] Tidying Up Meshery documentation 

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery#7792]
#### Current State
There are little issues in the Docs that have to be addressed
1. All content under the guide is not indexed in the sidebar
2.  Broken link under for[ mesheryctl command reference](https://docs.meshery.io/reference/mesheryctl) under [configuration-management](https://docs.meshery.io/guides/configuration-management)
3. App [import](https://docs.meshery.io/reference/mesheryctl/app/import) subcommand is not indexed in the reference page 
4.  Update the link for [installation methods ](https://docs.meshery.io/installation) under [quick start](https://docs.meshery.io/installation/quick-start), currently it directs to supported platforms
5.  Correct the command for setting up the env variable for [Windows](https://docs.meshery.io/installation/platforms/windows#4--install-a-kubernetes-cluster) 
 from `export KUBECONFIG="$(k3d kubeconfig get 'k3s-default')"` to the following 
` $env:KUBECONFIG = "$(k3d.exe kubeconfig get 'k3s-default')"`

#### Desired State

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by SimardeepSingh1450** [comment]
@thisiskaransgit I'd like to work on this issue, please assign me this issue, also please elaborate issue-2 , rest i was able to explore, but facing problems searching the broken-link in issue-2.

**Comment by thisiskaransgit** [comment]
@SimardeepSingh1450, sure go ahead :rocket:
 the link used in the mentioned page is redirecting to the markdown file resulting in 404, which should have been redirecting us to the page.
![Screenshot from 2023-06-06 12-38-48](https://github.com/meshery/meshery/assets/92504666/f61bf6fe-05a7-44f9-baee-8d97e635bae9)

**Comment by SimardeepSingh1450** [comment]
@thisiskaransgit so in issue-2 i have to redirect to this page : https://docs.meshery.io/reference/mesheryctl right ?

**Comment by thisiskaransgit** [comment]
@SimardeepSingh1450  solve the improper redirection issue

**Comment by vaibhav135** [comment]
@thisiskaransgit @leecalcote   I have looked at the documentation and yes it needs a lot of refactor. But my question is, Are there any plans to move from jekyll to new frameworks (like gatsby or astro) since I believe they will be better options (although migrating will be a huge pain -_-). But I guess In the long run it will be a better option in terms of maintainability and ease of use. Would appreciate an opinion on this.

**Comment by ashutosh887** [comment]
@thisiskaransgit I would like to work on this

**Comment by thisiskaransgit** [comment]
@SimardeepSingh1450, What's the status of the PR?

**Comment by SimardeepSingh1450** [comment]
@thisiskaransgit will raise a pr soon

**Comment by vishalvivekm** [comment]
> @thisiskaransgit will raise a pr soon

@SimardeepSingh1450 
Layer5 Websites ( every Monday at 5:30 PM IST) call is a great place to talk about your docs contributions.

**Comment by SimardeepSingh1450** [comment]
@thisiskaransgit in th issue-1 I want to know what things are supposed to be under the guides in sidebar that are already missing? , rest issues i have resolved and sorry for the delay (was travelling from past 4 to 5 days 😅 ).

**Comment by thisiskaransgit** [comment]
@SimardeepSingh1450, Click on "guides(all)", to see the index and match them with the sidebar. Kindly Create a PR to show your current Progress.

**Comment by SimardeepSingh1450** [comment]
@thisiskaransgit i have raised a pr stating the current changes at #7890 .

**Comment by thisiskaransgit** [comment]
Closed as completed via #8128
