### ISSUE TITLE
[meshery]: Increasing the code coverage for meshery

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery#7804]
#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Freedisch** [comment]
I can help on that

**Comment by Aisuko** [comment]
Hi @Freedisch Which one do you want to work on?

**Comment by Aisuko** [comment]
@Freedisch Ok, I will assign it to you. Please write some useful and simple cases.

**Comment by Aisuko** [comment]
remove

**Comment by gopivaibhav** [comment]
Hi @Aisuko  Can you please assign me this issue to work on?
Thank you!!

**Comment by Aisuko** [comment]
@gopivaibhav Sorry to reply so late. Please trying to work on increase `mesheryctl` first.

**Comment by gopivaibhav** [comment]
Thank you @Aisuko I need some time to analyse this issue and work on it as I am packed with 4-5 issues assigned to me.

**Comment by Aisuko** [comment]
Hi @gopivaibhav Noticed and thanks.

**Comment by Aisuko** [comment]
remove
