### ISSUE TITLE
[playground] Add workflow to Update K8s Cleanup Script

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#7818]
#### Current Behavior

Recently a new script was added to ensure that k8s cluster is cleanup nightly.
Though the script inside VM is not set to automatically update when a change is made to https://github.com/meshery/meshery/blob/master/.github/scripts/playground-cleanup.sh 

#### Desired Behavior

When a change is made in https://github.com/meshery/meshery/blob/master/.github/scripts/playground-cleanup.sh then ensure that a new workflow is used to update the `playground-cleanup.sh` script places in c3-medium-x86-01-meshery VM at the root directory.

#### Implementation

1. Add a new workflow that watches for `/.github/scripts/playground-cleanup.sh`
2. SSH into c3-medium-x86-01-meshery
3. Update the script in `/playground-cleanup.sh` of root dir of c3-medium-x86-01-meshery with the new change in the master branch `/.github/scripts/playground-cleanup.sh`

#### Acceptance Tests

Reference:
1. Original post: https://github.com/meshery/meshery/pull/7799#issue-1743439241
2. https://github.com/meshery/meshery/blob/master/install/playground/readme.md

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by theBeginner86** [comment]
// @Revolyssup

**Comment by Revolyssup** [comment]
> I can create this workflow . May i work on this one

Yeah sure go ahead. Join today's CI call for more context

**Comment by leecalcote** [comment]
[Reference diagram](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g214519dc4ed_0_10):

<img width="1354" alt="Screenshot 2023-06-08 at 1 09 21 PM" src="https://github.com/meshery/meshery/assets/7570704/c8d677f2-cf6d-404e-9585-dc316afcc7cd">
