### ISSUE TITLE
wrk2 soak-tests doesnt have `last_run` property

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#7828]
#### Current Behavior

The fortio has the last_run property correctly set, but the wrk2 doesn't have `last_run` property.
<img width="574" alt="Screenshot 2023-06-09 at 1 50 36 AM" src="https://github.com/meshery/meshery/assets/48255244/c52a4b06-b841-41a6-860c-e6c55cd7b9bd">

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by kumanik5661** [comment]
Hi, if it isn't an issue, can have a go at it?
If yes, would you be kind enough to provide further details on reproducing the bug and how to approach this.
Thanks

**Comment by MUzairS15** [comment]
Are you able to run test with `wrk2`? I am getting erros

**Comment by Abhishek-kumar09** [comment]
@MUzairS15 Check the results of the automated tests coming generated from "l5io" via automated workflow.
