### ISSUE TITLE
Remove Meshery's Performance Gql Resolvers

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#7845]
#### Current Behavior

The Performance profile and result subscriptions were removed with this [commit:9154b353bb081b2927c99c366e12de90c4ebec7c](https://github.com/meshery/meshery/pull/7830/commits/9154b353bb081b2927c99c366e12de90c4ebec7c)

So now the go-resolvers and grapqhQL's schema has to be removed as well.

**Why removed:**
The reason for removal is because the table data was fetched as the graphQL query and the same query was subscribed to changes, this suffices our use case. 

Also, the two gql resolvers are not pumping any performance related data. The relay's browser environment doesn't receive any data as well.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by suhail34** [comment]
Is this whole file needed to be removed ?
https://github.com/meshery/meshery/blob/master/server/internal/graphql/resolver/performance.go

**Comment by Abhishek-kumar09** [comment]
@suhail34 Actually that was a mistake removing the grapqhQL subscription from frontend, infact it was helping in fetching the latest release on time. So this issue is no longer relevant and thus closing it.
