### ISSUE TITLE
[mesheryctl] system check doesn't work as expected

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#7848]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl system check --adapters`

```
!! Meshery Adapter for meshery-linkerd is running but not reachable
!! Meshery Adapter for meshery-osm is running but not reachable
!! Meshery Adapter for meshery-nsm is running but not reachable
!! Meshery Adapter for meshery-app-mesh is running but not reachable
!! Meshery Adapter for meshery-traefik-mesh is running but not reachable
!! Meshery Adapter for meshery-cilium is running but not reachable
!! Meshery Adapter for meshery-istio is running but not reachable
!! Meshery Adapter for meshery-nginx-sm is running but not reachable
!! Meshery Adapter for meshery-consul is running but not reachable
```
The adapters can be pinged from the UI, and I confirmed that they were deployed on the K8s cluster

`mesheryctl system check --operator`

```

Meshery Operators 
--------------
Error: Operator not working Get "https://10.96.0.1:443/apis/apps/v1/namespaces/meshery/deployments/meshery-operator": dial tcp 10.96.0.1:443: i/o timeout
```

Meshery Operator can be pinged from the UI, and I confirmed that it was deployed on the K8s cluster

#### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.6.91
- Meshery Client Version: mesheryctl built locally from master
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by alphaX86** [comment]
> @alphaX86 Issue reopened because `mesheryctl system check --operator` doesn't work.

Copy
