### ISSUE TITLE
[CI] Enhance Edge Release Channel with Versioning

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7850]
#### Current Behavior
Of the two Meshery release channels the only the stable channel has version numbers. The edge release channel only has latest.

#### Desired Behavior
Support version of the edge releases, just like versioning of stable releases.

#### Implementation
1. Add version to seed version by updating https://github.com/meshery/meshery/blob/master/.github/workflows/build-and-release-edge.yml#L29 edge release workflow and replace with GIT_VERSION=${GITHUB_REF/refs\/tags\//}. 
1.  Add version to docker tags. This change won’t affect docker tagging. 

#### Acceptance Tests
1. `mesheryctl system version` functions as expected while running an edge release.
2. `mesheryctl system login` using the `meshery` provider works.
3. `mesheryctl system channel` able to set / pin to a version number for an edge release.
4. Meshery UI: Ability to use Meshery as the remote provider when running edge release.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by suhail34** [comment]
Hi, So whenever a new tag is pushed we need a versioning of edge release is that like that as currently whenever new changes are pushed to master edge release is done

**Comment by leecalcote** [comment]
// @theBeginner86
