### ISSUE TITLE
[UI Feature] - MeshModel Browser

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#7851]
#### Desired Behavior

1. How many of each of the MeshModel objects are registered?
2. ~~What version of the models are present?~~
3. How many components are registered delicately? The same components from different Kubernetes clusters have been registered. The API should provide this.

Phase 2 Use Cases:

1.  (MeshSync integration) What are the most popular components present in the currently connected Kubernetes clusters?
2. (Connection/Credential integration) Which models are are not currently supported by a missing connection or missing credential?
3. Import and Export of Models
4. (Meshery Catalog integration) For each component, how many designs reference this component? The Meshery Catalog has this need as well.
6. (Meshery Catalog integration)What are the most popular components referenced in Designs?

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@UsmanDev09 @Udit-takkar how's this coming along?

**Comment by smartdev09** [comment]
1. [PR](https://github.com/meshery/meshery/pull/8053) is up for review to display counts in the meshmodel browser.
2. For duplicate components, @abdullah1308 is looking into the endpoint. 

After this, phase 1 will be complete. We are not aware of the details of phase 2 of the meshmodel browser. It would be helpful if we can discuss those. We listed the points [here](https://meshery.slack.com/archives/C023QGMSH8D/p1683059933010469?thread_ts=1682702526.020549&cid=C023QGMSH8D)

**Comment by sudhanshutech** [comment]
https://github.com/meshery/meshery/issues/9775
