### ISSUE TITLE
[UI] - Responsiveness of profiles card

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#7861]
#### Current Behavior

You can find these cards at https://playground.meshery.io/performance/profiles

**Smaller Screens:**

![cards2](https://github.com/meshery/meshery/assets/31584129/615d5ad1-0027-4ca6-900f-b8c2e87f4729)

**Larger Screens:**

![cards](https://github.com/meshery/meshery/assets/31584129/09038c95-17f0-4504-a821-cbe490507619)

#### Desired Behavior

The cards should be responsive front and back. Also, they should fit content on smaller screens. 

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by samyakshah3008** [comment]
I would like to work on this issue ticket! can I please be assigned?

**Comment by UsmanDev09** [comment]
Thank you @samyakshah3008

**Comment by samyakshah3008** [comment]
Cheers @UsmanDev09 !

**Comment by samyakshah3008** [comment]
This marks the completion of this issue ticket and PR has been merged. 
Can you go ahead to close this ticket as a successful completion? @UsmanDev09 as I don't have permissions to close. 
Cheers @UsmanDev09 👌
