### ISSUE TITLE
Meshery UI Dark Theme Report:

### ISSUE THREAD

**Issue by samyakshah3008** [meshery/meshery#7863]
## Description
I was assigned with a task to test the Meshery UI Dark Theme. I have prepared a detailed report by testing each and every page and with all components present in it. 

Tested Pages: 

- [X] Dashboard 
- [X] Preferences
- [X] Settings
- [X] Lifecycle
- [X] Configuration
- [X] Performance
- [X] Conformance
- [X] Extensions 

### General Report: 

1. Dropdown input component:
- **Current Behavior**: On hover and legend, currently border and legend text is of white color. **Expected Behavior**: Oh hover, border and legend should be of "Keppel #00B39F" color as they are **action Items**.
- On selecting anything from input component dropdown, the label automatically gets to green and on off-focus, it will go back to gray color. Instead, Expected Behavior: On hover, border and legend should be of "Keppel #00B39F" color as they are **action Items**.
 
**Current Behavior screenshot:** 

![image](https://github.com/meshery/meshery.io/assets/86982322/52af9a52-63af-458b-b4b1-32094556597c)

2. Input type radio button component: 

**Current Behavior:** As the component is an action item, current behavior is the color of selected radio button component is dark gray-ish. **Expected behavior** is it should have "Keppel #00B39F" color as they are **action Items**.

Current Behavior Screenshot: 

![image](https://github.com/meshery/meshery.io/assets/86982322/ec38aa56-c4e6-48e7-b9b4-6d61284d512d)

3. Unexpected icon behavior: 

On hover, both cross and check mark icon are of gray-ish color and cursor is not pointer. For better User Experience, we can make cross and check mark icon should be of "Keppel #00B39F" color as they are action items. 

![image](https://github.com/meshery/meshery.io/assets/86982322/1911edf7-cc57-46de-bf06-11ad93ef3af3)

4. Switch component: 

On turning on switch, the current color is dark gray

![image](https://github.com/meshery/meshery.io/assets/86982322/7b748870-002f-4f4c-aa69-eba90dd1f45a)

### Navbar Report: 

- On hovering to extension icon, it is not working properly
- On hovering notifications icon, it is not working properly
- Inconsistency between font colors on hovering on profile icon 
![image](https://github.com/meshery/meshery.io/assets/86982322/b6ae77e6-46e8-4f6e-88b8-b63b94197d36)
- Suppose we are on Dashboard, the title of navbar will be dashboard currently. But now user goes to preferences page, then navbar title is not getting updated. Is it intentional or a bug? 

![image](https://github.com/meshery/meshery.io/assets/86982322/8806ac21-891f-4758-b2e9-11c287dfb7b3)

### Dashboard Report: 

- Search input and search button are action items and should be of "Keppel #00B39F" color but currently they are blue. 

![image](https://github.com/meshery/meshery.io/assets/86982322/2fae73cf-9c97-48c9-9731-4d3cc4b55ed1)

### Management Page Report: 

- Why we have "." on right hand side with dropdown icon? 

![image](https://github.com/meshery/meshery.io/assets/86982322/00591a42-38fd-47dc-b3d5-1d170ad41719)

### Configuration Page Report: 

- Icon is not properly visible 

![image](https://github.com/meshery/meshery.io/assets/86982322/77c11039-bbc5-45ab-bb31-6d02d41f4057)

### Performance Page Report: 

- For better User Experience, can we add Modal Title, Cross/Close button to close the modal? 

![image](https://github.com/meshery/meshery.io/assets/86982322/ee6df016-3d6c-4294-9b75-1110366a1336)

### Meshmap Page Report: 

- Checkmark button is action item so the color should be Keppel

![image](https://github.com/meshery/meshery.io/assets/86982322/018cf65c-ba74-48c2-958c-eac5549cece9)

- On hovering the icons, when we hover over div, icons should go of keppel color but current behavior is when someone hovers on div, icons will not go of keppel color but when hovered over icons, they will be of keppel color. 

![image](https://github.com/meshery/meshery.io/assets/86982322/59284344-99f7-4a65-aab8-a7982b005cf5)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by samyakshah3008** [comment]
@Yashsharma1911 can you please check and share your feedback on this detailed report? 
As you have already told me to fix them, I have started my work fixing them. 
Cheers.

**Comment by leecalcote** [comment]
1, 2, 3, and 4 are all bugs. Good to go on fixing these, @samyakshah3008. Others might weigh-in the rest before I circle back to do so.

**Comment by samyakshah3008** [comment]
Cheers for assigning me the task @leecalcote 🚀 
I'll raise a PR to the soonest! 

Cc: @Yashsharma1911

**Comment by leecalcote** [comment]
@samyakshah3008, regarding: 

> "For better User Experience, can we add Modal Title, Cross/Close button to close the modal?" 

Yes, please. Ideally, all modals have this feature.

**Comment by samyakshah3008** [comment]
Acknowledged @leecalcote 😄

**Comment by samyakshah3008** [comment]
Update: 

#7982 will be the last milestone now before we close this issue ticket. 
On recent discussion with @Yashsharma1911 we decided to create issue ticket #7982 or else this issue was about to close.

**Comment by leecalcote** [comment]
Super. That's good.

**Comment by Yashsharma1911** [comment]
Closing this as these issues are covered
