### ISSUE TITLE
[UI] Clicking on NATS chip does not show Meshery broker status

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#7866]
#### Current Behavior
Clicking on the NATS chip gives the following error -

<img width="1177" alt="image" src="https://github.com/meshery/meshery/assets/76054921/a07b181d-248e-41be-9b6f-70895a00a55d">

#### Desired Behavior
Connectivity status to be shown similar to when MeshSync/Operator chip is clicked -

<img width="1138" alt="image" src="https://github.com/meshery/meshery/assets/76054921/837ef68f-c254-4006-a3bd-3b77c36afd59">

#### Environment

- Browser: Chrome
- Host OS: Mac
- Meshery Server Version: stable-v0.6.92
- Meshery Client Version: stable-v0.6.92
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by MUzairS15** [comment]
Was `Meshery Broker` publishing data back to `server`?? 
Status is deployed so it wasn't hence you didn't get green scnakbar

**Comment by abdullah1308** [comment]
> Was `Meshery Broker` publishing data back to `server`?? Status is deployed so it wasn't hence you didn't get green scnakbar

@MUzairS15 how would I check if `Meshery Broker` was publishing data back to the server ?

**Comment by MUzairS15** [comment]
<ExternalIp of broker>:8888/connz , check whether meshery is listed. Or else try changing resources in your cluster i.e create / modify resources and check if you get logs in server indicating updates

**Comment by Ykumar1415** [comment]
I want to work on this issue can you assign this to me ?.

**Comment by abdullah1308** [comment]
@MUzairS15 creating a resource in the cluster results in a log being printed in meshery server, but I'm still unable to connect to the Broker using the chip.
