### ISSUE TITLE
[UI] Remove connection status section in the dashboard

### ISSUE THREAD

**Issue by vaibhav135** [meshery/meshery#7867]
#### Current Behavior
As discussed with @leecalcote the connection status section is showing redundant information which are either already present in other sections or could be in a separate section itself. 

#### Desired Behavior
Remove the connection status section and make the workspace and service-mesh section wider (expand  with respect to the whole dashboard).

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by aabidsofi19** [comment]
i would live to work on this ..

**Comment by aabidsofi19** [comment]
thanks :)

**Comment by aabidsofi19** [comment]
@leecalcote  should we put the removed  components in setting page or left for a separate issue.  create some  some proper mockups and redesign

**Comment by leecalcote** [comment]
> @leecalcote should we put the removed components in setting page or left for a separate issue to create some mockups for redesign

@aabidsofi19 immediately, simple delete them, please. More designs and issues to follow.
