### ISSUE TITLE
[UI] Add all Meshery Adapters to the Extensions page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7869]
Related - https://github.com/meshery/meshery/issues/7867

#### Desired Behavior
Every Meshery Adapter should be represented as a card on the extensions page. Each card should have a switch that will invoke the adapter deployment operation.

#### Implementation
1. Card descriptions: "Deploy the Meshery Adapter for <NAME> in order to enable deeper lifecycle management of <NAME>."  - - replace `<NAME> `with appropriate adapter name.
2. Adapter docs - https://docs.meshery.io/concepts/architecture/adapters

#### Acceptance Tests
1. Ensure Adapters deploy when Meshery is running on the docker platform.
3. Ensure Adapters deploy when Meshery is running on the Kubernetes platform.

#### Mockups
<img width="1485" alt="Screenshot 2023-06-15 at 12 22 07 PM" src="https://github.com/meshery/meshery/assets/7570704/576517e4-f365-4d50-85a2-9a9353ea2552">

[Figma link](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=15172-38125&t=a0Rb7p8Hd5reAoMn-4)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vaibhav135** [comment]
@leecalcote  Can you please assign this to me.

**Comment by Yashsharma1911** [comment]
Go ahead @vaibhav135

**Comment by Pranjal7852** [comment]
can I also work on this issue @Yashsharma1911?

**Comment by vaibhav135** [comment]
@Pranjal7852 you can look for another issue? I am currently working on this.
