### ISSUE TITLE
[UI] Extensions: Add GitHub Action for MeshMap Snapshot

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7880]
### Current Behavior
An early release of a Meshery extension as a GitHub Action, [MeshMap Snapshot](https://github.com/marketplace/actions/meshmap-snapshot), is publicly available and ready to be listed in the Meshery UI Extensions page.

### Desired Behavior
Every Meshery GitHub Action should be represented as a card on the extensions page. Each card should have an enable that will invoke the GitHub deployment operation.

### Implementation
1. Create Card. Add description: "Connect MeshMap to your GitHub repo and see changes pull request-to-pull request.Get snapshots of your infrastructure directly in your PRs."
1. Create "Enable" button. "Enable" button should link to https://cloud.meshery.io/connect/github/new/

### Acceptance Tests
1. Ensure "Enable" button opens GitHub Action connection wizard on click.

### Mockups
<img width="462" alt="Screenshot 2023-06-16 at 11 59 40 AM" src="https://github.com/meshery/meshery/assets/7570704/85c706db-bd86-44eb-b0af-16b199e998d2">

Link to design - https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=6671-28631&t=ktzjesEfBrsTeEOT-4

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Saksham294** [comment]
Hey @leecalcote I'd like to work on this issue

**Comment by leecalcote** [comment]
> Hey @leecalcote I'd like to work on this issue

Excellent. Are you able to build and run Meshery UI?

**Comment by aabidsofi19** [comment]
@leecalcote  i would love to take this issue .
