### ISSUE TITLE
[mesheryctl] Fix delete operation for WASM filters

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#7905]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Currently, when a user tries to delete a filter then they observe following error

![image](https://github.com/meshery/meshery/assets/73700530/448eb39e-92da-4d0d-8f52-762bc17836e5)

#### Desired Behavior

Meshery users should be able to delete filters using mesheryctl.

#### Acceptance Test
1. Fix the behavior of delete operations for filters
2. Improve error messages incase of unexpected behavior while deleting filters

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@alphaX86 done?

**Comment by leecalcote** [comment]
@abdullah1308 can you knock this out today?

**Comment by Freedisch** [comment]
This issue should be closed now that `exp` is no more used and the `delete` has been updated to use name or Id
