### ISSUE TITLE
[mesheryctl] relative path cannot be parsed correctly for `mesheryctl pattern apply --file `

### ISSUE THREAD

**Issue by gyohuangxin** [meshery/meshery#7908]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

When use relative path for `mesheryctl pattern apply --file `, the path will be parsed as a URL:
```
$ mesheryctl pattern apply -f CryptoMB-TLS-handshake-acceleration-for-Istio-v2.yaml
Error: only github urls are supported
``` 
It works when I change the relative path to absolute one.

#### Desired Behavior

It should work to parse file path whenever I use relative path or absolute path.

#### Screenshots/Logs

After investigation of meshery code, I don't think this function can parse relative path correctly and so it parsed the path as a URL:

https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/pattern/apply.go#L120

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by suhail34** [comment]
Hi I can help to resolve this issue
