### ISSUE TITLE
UI doesn't look proper of Quick start guide

### ISSUE THREAD

**Issue by helloakash1701** [meshery/meshery#7912]
#### Current Behavior
The dots looks very congested
![image](https://github.com/meshery/meshery/assets/80618499/6fe2838d-6da6-4045-85c0-71f9a9756849)

#### Expected Behavior
They should have some margin above. I have edited them in my browser but I dont know how to edit them in the website. If you can help me solve this issue, that would be great.
![image](https://github.com/meshery/meshery/assets/80618499/9930e41e-dc3c-4a7a-8729-8b22e9d06163)

#### Environment

- **Host OS:** Mac /Linux /Windows

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
It’s not that the dots need margin. It’s that the copy icon needs to be positioned in the upper right corner.
