### ISSUE TITLE
[UI]: Dropdown input component

### ISSUE THREAD

**Issue by samyakshah3008** [meshery/meshery#7916]
## Description: 

- I prepared a detailed Meshery Dark theme UI Report, this is a sub-issue ticket of it to fix a small bug. 
- You can checkout the report here: #7863 (Please refer general report -> item number 1) 

### Current Behavior of Dropdown input component: 

- On hover and legend, currently border and legend text is of white color. **Expected Behavior**: Oh hover, border and legend should be of "Keppel #00B39F" color as they are **action Items**.
- On selecting anything from input component dropdown, the label automatically gets to green and on off-focus, it will go back to gray color. 

### Expected Behavior: (Two Milestones) 

- On hover, border and legend should be of "Keppel #00B39F" color as they are **action Items**.
- On selecting any item from drop-down, after selecting, the color of legend should not turn to Keppel color. 
 
**Current Behavior screenshot:** 

![image](https://github.com/meshery/meshery.io/assets/86982322/52af9a52-63af-458b-b4b1-32094556597c)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by HarshDobariya79** [comment]
I would like to work on this issue. Can I get assigned please?

**Comment by samyakshah3008** [comment]
@Yashsharma1911 @Shivam-AfA can anyone please go ahead and assign the task to Harsh as he commented first?
