### ISSUE TITLE
text not visible in dark mode

### ISSUE THREAD

**Issue by ranjanmangla1** [meshery/meshery#7918]
#### Current Behavior
The text 01 & 02 are not clearly visible
![image](https://github.com/meshery/meshery/assets/93506927/fa3b2d0f-57a4-479a-80b6-7b84de42b991)

here too:
![image](https://github.com/meshery/meshery/assets/93506927/dff1bc0e-f267-4f5c-9a25-de1680e1c71f)

#### Expected Behavior
The 01 & 02 should be green /black  in color or any other color

Please assign me this issue

**Comment by Ykumar1415** [comment]
i want to work on this issue can you assign this to me ?

**Comment by AryanSharma9917** [comment]
Heyy @ranjanmangla1 so you want the color of the index same as that of the text in front?

**Comment by ranjanmangla1** [comment]
closing this, already opened on meshery.io
