### ISSUE TITLE
Icons not visible in Dark Mode [UI]

### ISSUE THREAD

**Issue by ranjanmangla1** [meshery/meshery#7919]
#### Current Behavior
GItHub Icons are not visible in Dark Mode, icons specifically for dark mode should be, also from an asthetic point of view their alignments are not correct

#### Desired Behavior
Specific icons should be used for dark mode

#### Screenshots/Logs
![image](https://github.com/meshery/meshery/assets/93506927/ace6f13a-fc9f-40bf-900a-bb68d033d1c4)

Please assign me this issue

**Comment by anshgoyalevil** [comment]
@ranjanmangla1 Thanks for creating the issue. Would you like to work on it?

**Comment by ranjanmangla1** [comment]
yes, absolutly love to, mentioned in the issue too @anshgoyalevil

**Comment by anshgoyalevil** [comment]
Here you go @ranjanmangla1 🚀

**Comment by ranjanmangla1** [comment]
hey @anshgoyalevil, I think the issue should be assigned at meshery.io repo, na? Can you assign me there :https://github.com/meshery/meshery.io/issues/1215#issue-1771815558
