### ISSUE TITLE
[Docs]Integration of Redocs into Meshery Documentation Pages

### ISSUE THREAD

**Issue by Freedisch** [meshery/meshery#7950]
#### Current State
We want to change the layout of the Redocly API docs using a custom template. The custom template is based on handlebars, which is a templating language that allows me to insert variables and expressions into HTML. We want to use the custom template to modify the {{{ redocHTML }}} variable that contains the Redocly API docs in HTML format.
You can see the custom template and the {{{ redocHTML }}} variable format below. 

[Current sample of Redocs in Meshery docs](https://drive.google.com/drive/folders/1aBxJtUU9XqFzEgf4JoLuaHvqpzuY09m-?usp=sharing)
[REDOC current format ](https://drive.google.com/file/d/1yGlM_gm9uxZgRdHNxY00INzuE6xQGT1-/view?usp=sharing)
[CustomTemplate](https://drive.google.com/file/d/1Up84QkIgjsdPb09THRXhAnW3Eg_tEwJd/view?usp=sharing)
[PR](https://github.com/meshery/meshery/pull/7534)
#### Desired State
 Redocs should fit better inside the Meshery's API reference page

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Shorla** [comment]
Hi @Freedisch, I would love to work on this. 
can I get assigned to it?
