### ISSUE TITLE
Add support to upload certificates in performance profile.

### ISSUE THREAD

**Issue by gyohuangxin** [meshery/meshery#7952]
#### Current Behavior

Right now, there isn’t a support to upload cert files in performance profile, but it's a common test case to send HTTPS request with a self-signed certificate.

#### Desired Behavior

Add support to upload certificates in performance profile.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by MUzairS15** [comment]
@gyohuangxin Can you describe how you are using `fortio` (outside meshery) to use certs as part of performance testing?

**Comment by gyohuangxin** [comment]
@MUzairS15 Sure, for example, we use command like `fortio load --cacert /path/to/certs https://fortio.com`

**Comment by gyohuangxin** [comment]
@MUzairS15 Can we add a title "SSL certificates"?
<img width="396" alt="image" src="https://github.com/meshery/meshery/assets/42127654/d7dfc25a-22ac-4e0f-893e-1d0031bf06ab">

**Comment by gyohuangxin** [comment]
@MUzairS15 I tried upload the certificates from Meshery UI, but it seems that the certificate was not used: 
<img width="1137" alt="image" src="https://github.com/meshery/meshery/assets/42127654/6b29b4a9-4bd9-40ca-81ab-d66546c663fb">
But it worked when I used curl with certificate:
<img width="429" alt="image" src="https://github.com/meshery/meshery/assets/42127654/58b2ede9-2507-418c-9c48-b5a0975c7331">
