### ISSUE TITLE
[CI] Job to update REST and GraphQL docs

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#7956]
#### Current Behavior
The Meshery REST API docs obtains information to be displayed from `docs/_data/swagger.yml`, which is built using the following make command 

```
## Build Meshery REST API documentation
swagger-docs-build:
	swagger generate spec -o ./docs/_data/swagger.yml --scan-models; \
	swagger flatten ./docs/_data/swagger.yml -o ./docs/_data/swagger.yml --with-expand --format=yaml
```

GraphQL docs are built using the following make command 

```
## Build Meshery GraphQL API documentation
graphql-docs-build:
	cd docs; bundle exec rake graphql:compile_docs
```

#### Desired Behavior
These commands should be run in a build workflow and auto-committed, to ensure that both the REST and GraphQL docs are always upto date 

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by suhail34** [comment]
Is it open for contribution? Then i can work

**Comment by Hs809** [comment]
@abdullah1308 While investigating this issue, I discovered that the Makefile contains commands for updating the REST and GraphQL API documentation. I have a question regarding the execution of the Makefile during the build process. If the Makefile is executed every time during the build, it may not be necessary to include the commands in the build workflow. However, if the Makefile is not executed automatically, I would like to know in which build workflow it should be added.

Thanks, Regards 
Hitesh

**Comment by abdullah1308** [comment]
@suhail34 @Hs809 This issue is open for contribution. The changes have to be added to the **Meshery Build and Releaser** (stable and edge) workflows.

**Comment by suhail34** [comment]
Aren't we doing the same thing here only thing we aren't doing is not authocommiting the changes and have to update the path for filters to work
https://github.com/meshery/meshery/blob/0bebcb79aacde419a376b4a424ff9796f912481f/.github/workflows/build-ui-and-server.yml#L290-L343

**Comment by abdullah1308** [comment]
@suhail34 Hey take a look at these workflows -
https://github.com/meshery/meshery/blob/0bebcb79aacde419a376b4a424ff9796f912481f/.github/workflows/redocly.yml#L1

https://github.com/meshery/meshery/blob/0bebcb79aacde419a376b4a424ff9796f912481f/.github/workflows/graphql.yml#L1

We would want to add these with appropriate filters to the `build-and-release` workflows as we would want to update the docs on a release. The workflow that you've mentioned is the `build-ui-and-server` workflow which runs on every PR to ensure that both Meshery UI and server are built.
