### ISSUE TITLE
[Docs] REST API docs do not contain response examples

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#7958]
#### Current State

None of the swagger based REST API references contain response / body / parameter examples. For example -  

##### [REST API Reference](https://docs.meshery.io/reference/rest-apis) 

<img width="934" alt="image" src="https://github.com/meshery/meshery/assets/76054921/fd64adeb-876f-4877-89b3-c50965b957dc">

##### Redocly docs

<img width="1421" alt="image" src="https://github.com/meshery/meshery/assets/76054921/87a0894d-198d-487f-8d90-156b33504706">

##### `swagger serve ./server/helpers/swagger.yaml`

<img width="1408" alt="image" src="https://github.com/meshery/meshery/assets/76054921/18c407bc-8716-4992-8adc-ccfb74f3afc7">

#### Desired State

The REST API references should contain information about the following for the various status codes and use cases for all APIs - 

- Available Parameters
- Example Body
- Example Reponses

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by codepley** [comment]
Hey, can I work on this issue?

**Comment by abdullah1308** [comment]
Hey @codepley, @Freedisch is working on this, you can join our Slack and assist him in this effort - https://meshery.io/community/newcomers

**Comment by Srishtihere** [comment]
hey I would like to work on this issue, can you assign me this ? @abdullah1308

**Comment by ShatilKhan** [comment]
I'd like to work on this issue @abdullah1308
