### ISSUE TITLE
[UI] Rows per page is not working in meshmodel tabs in settings

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#7971]
#### Current Behavior
In tabs `Models`, `Components` Rows per page is not working

https://github.com/meshery/meshery/assets/71271069/7143b00d-e2d4-4409-b111-ffc1eb6a9050

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by HarshDobariya79** [comment]
I would like to work on this issue, can I get assigned, please?

**Comment by Meyazhagan** [comment]
@HarshDobariya79 you got it!

**Comment by HarshDobariya79** [comment]
@Yashsharma1911 @Meyazhagan
 **page size** for all **mesh model components** APIs is hard coded to **25** from the back-end. So let's say user selects page size as 100, should we call the API **multiple** times (4 times in this case) or should we provide an **optional argument** in API itself for page size? or we can do something else. Please give your inputs.

**Comment by Meyazhagan** [comment]
@HarshDobariya79 You can pass pagesize in query. ref: https://github.com/meshery/meshery/blob/820f14eb7ffe52e60fc8b0fa24bd043f054f4330/server/handlers/component_handler.go#L175

**Comment by HarshDobariya79** [comment]
> @HarshDobariya79 You can pass pagesize in query. ref:
> 
> https://github.com/meshery/meshery/blob/820f14eb7ffe52e60fc8b0fa24bd043f054f4330/server/handlers/component_handler.go#L175

Oops I missed that. Thank you for pointing out.

**Comment by HarshDobariya79** [comment]
I'm not able to understand why we need to perform AND operation. Can anyone please assist?
https://github.com/meshery/meshery/blob/820f14eb7ffe52e60fc8b0fa24bd043f054f4330/ui/components/MeshModelComponent.js#L306
