### ISSUE TITLE
[WASM Filters] Issues in the post of WASM filters

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#7972]
#### Current Behavior

![Screenshot 2023-06-28 at 7 36 55 PM](https://github.com/meshery/meshery/assets/48255244/79fae6e1-3839-4872-a393-b1f675fd2d24)
![Screenshot 2023-06-28 at 7 37 22 PM](https://github.com/meshery/meshery/assets/48255244/7e003ffb-49e5-4974-9d47-a410adce441f)

The WASM filters when uploaded via URL is most likely walking all the files in the directory and posting it to WASM filters database. The uploaded files don't even classifies as a WASM filter.

#### Expected Behavior

There should be expectations for WASM filters
1.The file uploaded should end with `.wasm` or `webasm`
2. The intelligence is required to not post everything
3. It should have a sort of validation process, that request when received should return a "!ok" response.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Meyazhagan** [comment]
I look into the issue !
@Abhishek-kumar09 can you point me, where to get some sample wasm filter

**Comment by Abhishek-kumar09** [comment]
@theBeginner86 What do you think the status here? We just decided to remove walker, so this issue might be no longer valid, is it true?

**Comment by theBeginner86** [comment]
> @theBeginner86 What do you think the status here? We just decided to remove walker, so this issue might be no longer valid, is it true?

Yes, this is no longer true.

**Comment by thisiskaransgit** [comment]
Is this issue still relevant? @Abhishek-kumar09 @theBeginner86
