### ISSUE TITLE
[MeshModel]: Identify relationships for K8s ConfigMap

### ISSUE THREAD

**Issue by 0xt3j4s** [meshery/meshery#7973]
### Proposed Change

- Identify the possible relationship type for `ConfigMap`.
- Identify the related resource. 
- Define the constraints for that relationship.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- [MeshModel Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)
- 🖥 [MeshModel Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### Instructions for Models
1. _Forthcoming_

### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes. 
1. Propose a specific shape, best-suited to visually represent the Component. Example - Deployment as a pentagon.
1. Proposee a specific icon, best-suited to visually represent the Component. Example - DaemonSet as a skull icon.

### Instructions for Relationships
1. Identify the relationship and any specific constraints to be enforced between the two specific components, their models or potentially other components, models, or environmental considerations.
1. Propose a specific visual representation for the relationship. Visual representation examples:
1.1. [Hierarchical](https://github.com/meshery/meshery/blob/master/.github/assets/images/hierarchical_relationship.png)
1.1. [Sibling](https://github.com/meshery/meshery/blob/master/.github/assets/images/sibling_relationship.png)
1.1. [Binding](https://github.com/meshery/meshery/blob/master/.github/assets/images/binding_realtionship.png)
1. Prospose the appropriate relationship type, using one of the predefined set of relationship types or suggest a new relationship where an existing type does not fit.
1. Create a Relationship Definition (yaml). See the [Relationship Schema](https://github.com/meshery/meshery/tree/master/server/meshmodel/schemas) in MeshModel and [examples]([url](https://github.com/meshery/meshery/tree/master/server/meshmodel/relationships)).
1. Create a policy for evaluation of the relationship (rego). See examples.

### Instructions for Policies
1. _Forthcoming_

**Comment by Boombag0607** [comment]
@0xt3j4s I want to work on this.

**Comment by 0xt3j4s** [comment]
@Boombag0607 Here you go! 🚀

**Comment by hamza-mohd** [comment]
Should apply to Deployments among other resources....

**Comment by leecalcote** [comment]
In Kubernetes, ConfigMaps are a versatile resource that can be referenced by various other resources to provide configuration data to applications. The set of possible resources that benefit from a ConfigMap reference includes:

1. **Pods:**
   - ConfigMaps can be mounted as volumes in Pods, allowing applications to read configuration files or environment variables from these volumes.

2. **Deployments:**
   - Deployments can reference ConfigMaps to inject configuration data into the Pods they manage. This is useful for maintaining consistent configuration across replica sets.

3. **StatefulSets:**
   - StatefulSets can use ConfigMaps to provide configuration data to their pods in a similar way to Deployments.

4. **DaemonSets:**
   - DaemonSets, which ensure that a copy of a pod runs on each node, can utilize ConfigMaps to supply configuration data to their pods.

5. **ReplicaSets:**
   - ReplicaSets, like Deployments, can benefit from ConfigMap references to manage configuration data for their replicated pods.

6. **Jobs and CronJobs:**
   - Jobs and CronJobs can reference ConfigMaps to provide configuration to the pods they create, especially useful for one-off or periodic tasks.

7. **Init Containers:**
   - ConfigMaps can be used in init containers within a Pod to provide initialization or configuration data before the main application containers start.

8. **Custom Controllers:**
   - Custom controllers or operators can be designed to use ConfigMaps to dynamically configure resources they create or manage.

9. **Horizontal Pod Autoscalers (HPA):**
   - HPA configurations may reference ConfigMaps to adjust the desired number of replicas based on changing configuration parameters.

10. **Service configurations:**
    - ConfigMaps can store configurations for services, such as Nginx or HAProxy, that are used to configure routing, load balancing, or other settings.

11. **Database configurations:**
    - Databases or database-related components can reference ConfigMaps for connection strings, tuning parameters, or other configurations.

12. **Ingress controllers:**
    - ConfigMaps can be used to store configurations for Ingress controllers, helping to manage routing rules, SSL certificates, and other settings.

13. **Application Configurations:**
    - Any application running in a containerized environment can benefit from ConfigMap references for managing its configurations.

By referencing ConfigMaps in these various contexts, you can centralize and manage configuration data more efficiently, allowing for easier updates, versioning, and maintenance of configurations in a Kubernetes environment.
