### ISSUE TITLE
[UI] Handle API requests efficiently

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#7976]
#### Current Behavior

The issue pertains to all pages that utilize cards and tables, such as "`filters`," "`applications`," "`designs`," and "`profiles`." When we navigate to another page quickly through pagination, there is a bug that occurs due to the timing of the response from the previous page.

Currently, when we swiftly move to the next page before the response from the previous page arrives, it leads to an undesired behavior. The bug arises because the system is not able to handle this rapid navigation properly, resulting in incorrect or unexpected results.

https://github.com/meshery/meshery/assets/90546692/5e8eae2b-b163-4d22-8015-48954f2356ff

#### Desired Behavior

It should handle requests efficiently.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sudhanshutech** [comment]
// @HarshDobariya79

**Comment by HarshDobariya79** [comment]
I would like to work on this issue.

**Comment by sudhanshutech** [comment]
@HarshDobariya79 this is a urgent item

**Comment by HarshDobariya79** [comment]
> @HarshDobariya79 this is a urgent item

Thank you for assigning @sudhanshutech. Already working on it.
