### ISSUE TITLE
[Docs]  Logo center issue  

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery#7979]
#### Current State
Logo is not centered respective to their text at https://docs.meshery.io/

#### Desired State
logo should be centered

<img width="220" alt="image" src="https://github.com/meshery/meshery/assets/122862213/22dd6b86-9075-46b7-b83d-f7b033fe0575">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by VishwaRaval247** [comment]
I would like to work on this issue. Could someone please assign it to me?

**Comment by Rajivkumawat3** [comment]
@VishwaRaval247 I am working on it

**Comment by Rajivkumawat3** [comment]
@ thisiskaransgit please review  this pr
