### ISSUE TITLE
[Docs] Video height issue at mobile devices

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery#7980]
#### Current State
when we visit  there are some issue at mobile devices in media queries we have to change height of vedio because after start the video most of the spaces did not in use , so i am showing some pictures current and desired behaviour , first 2 pictures are current behavior in mobile devices and last two are expected behaviour in mobile devices

#### Desired State

<img width="196" alt="image" src="https://github.com/meshery/meshery/assets/122862213/3fbab230-aed4-4b8c-8ac8-e8a8042c800c">
<img width="199" alt="image" src="https://github.com/meshery/meshery/assets/122862213/cc2fefaa-9226-4e94-b6a0-7fe32c093281">
<img width="187" alt="image" src="https://github.com/meshery/meshery/assets/122862213/1d038c9c-c6e8-49f6-8bb4-91712252a49e">
<img width="194" alt="image" src="https://github.com/meshery/meshery/assets/122862213/9ed5dd6c-22bb-4552-8d00-25951b5446af">

--
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Rajivkumawat3** [comment]
can someone assign this issue to me , i want to work on it

**Comment by Rajivkumawat3** [comment]
@thisiskaransgit this problem is solved by someone else , so now there is no problem with this page , I think we should close this issue

**Comment by thisiskaransgit** [comment]
@Rajivkumawat3  what's your progress on this one?

**Comment by Rajivkumawat3** [comment]
@thisiskaransgit sir I will fix it , today.

**Comment by deepchauhan2002** [comment]
Should I work on this issue?

**Comment by Rajivkumawat3** [comment]
@deepchauhan2002 you can work on it . @thisiskaransgit assign this issue to deepchauhan

**Comment by vishalvivekm** [comment]
> @deepchauhan2002 you can work on it . @thisiskaransgit assign this issue to deepchauhan

@deepchauhan2002 There you go.

**Comment by Debjyoti0404** [comment]
Can I work on this issue?

**Comment by Debjyoti0404** [comment]
Here is the video of the current state.

[Screencast from 2023-07-30 00-12-56.webm](https://github.com/meshery/meshery/assets/103656712/711137b4-3339-4ee5-a19d-4ab5c26e30b3)
