### ISSUE TITLE
[Docs]Dark mode logo issue for Meshery Adapter of Kuma

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery#7981]
#### Current State
logo of Meshery Adapter for Kuma not visiable in dark mode at https://docs.meshery.io/
logo of meshery adapter for kuma not visiable in dark mode at /service-meshes/adapters/kuma/

#### Desired State
logo should be visiable

<img width="213" alt="image" src="https://github.com/meshery/meshery/assets/122862213/6c27e2ce-d435-493f-94de-0818e2268953">
<img width="217" alt="image" src="https://github.com/meshery/meshery/assets/122862213/7da3c0e5-a4f7-417c-90d5-912e244e9e42">

<img width="88" alt="image" src="https://github.com/meshery/meshery/assets/122862213/4329798d-3b03-4d40-afb3-81416a00dd06">
<img width="107" alt="image" src="https://github.com/meshery/meshery/assets/122862213/60c2ec7a-0411-4ac3-9c0b-4057ef285d59">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Rajivkumawat3** [comment]
I want to work on this issue

**Comment by thisiskaransgit** [comment]
@Rajivkumawat3  How's the progress on your PR? If you're not actively working on it, please let us know. We're here to help, if you're not working on it do signal.

**Comment by Rajivkumawat3** [comment]
@thisiskaransgit sir i am working on it , today i will fix this isssue .

**Comment by vishalvivekm** [comment]
@Rajivkumawat3 Please let us know if you're still committed to this effort. 
We can reassign if you're not.

**Comment by Rajivkumawat3** [comment]
@vishalvivekm  i tried to fix it , but after refreshing the page it goes it initial state . yes you can reassign it

**Comment by Rajivkumawat3** [comment]
@vishalvivekm sir you can assign this issue to someone else

**Comment by sagniksantra** [comment]
If the issue still persists, can I please work on it?

**Comment by abhinandanudupa** [comment]
@Rajivkumawat3 I don't think we will be able to fix this issue as there is no version of the logo adapted to the dark mode.
