### ISSUE TITLE
[UI]: Fix Search Input Field 

### ISSUE THREAD

**Issue by samyakshah3008** [meshery/meshery#7982]
### Current Behavior
Current behavior of input field, the color when we focus or type in it is not as expected for keppel color. This issue ticket is sub-ticket of #7863 

### Desired Behavior

Expected behavior of every input field should be when we focus or type something, the color should be of keppel as it is action item. 

### Current behavior screenshot: 

![image](https://github.com/meshery/meshery/assets/86982322/0f46dfe1-bf3d-41a0-92c7-301706ac18a7)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by samyakshah3008** [comment]
@Yashsharma1911 I would like to work on this, 
Please note that this will be the last milestone to fix the #7863 Report. Rest all fixes are done 👌

**Comment by HarshDobariya79** [comment]
I've worked on a similar issue in this report itself. If @Yashsharma1911 is not ready, I would like to work on it.

**Comment by Yashsharma1911** [comment]
Hey @HarshDobariya79 thanks for raising your hands let's assign this to @samyakshah3008 as he asked first though we have other similar issues where you can help ^^

**Comment by HarshDobariya79** [comment]
Oh sorry, I thought he asked if you want to work on it. Go ahead @samyakshah3008 :)

**Comment by ranjanmangla1** [comment]
if no body is working on this issue, can you assign me?

**Comment by deepchauhan2002** [comment]
I want to work on this issue too, if possible?

**Comment by samyakshah3008** [comment]
Since I am occupied with some other issue ticket, I have a load to share. 
Thanks for raising your hands @ranjanmangla1 and @deepchauhan2002  
Assigning in chronological order, please go ahead @ranjanmangla1

**Comment by priyanshu-kun** [comment]
@ranjanmangla1  are you working on this issue?

**Comment by ranjanmangla1** [comment]
@priyanshu-kun yes

**Comment by samyakshah3008** [comment]
How are we progressing on this issue ticket, @ranjanmangla1 ? Any blockers you are facing?

**Comment by HarshDobariya79** [comment]
If no one is working on this issue. I can take it up.

**Comment by ranjanmangla1** [comment]
@samyakshah3008 sending pr in a hour

**Comment by hemantmm** [comment]
Hi, @Ghat0tkach can I work on this issue?

**Comment by Yashsharma1911** [comment]
@hemantmm can you confirm two things

1) have you able to run meshery locally
2) If yes then is this issue still persist, if it persist then please raise PR and you can inform here

**Comment by palash018** [comment]
@Yashsharma1911 can i get this assigned

**Comment by arunavabasu-03** [comment]
can I work on this @Yashsharma1911 !!
