### ISSUE TITLE
[CI] Enhance Edge Release Channel with Support for `mesheryctl` binaries.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7984]
### Current Behavior:
The Meshery Edge release channel was recently enhanced to include git tags so that those releases are versioned (previously, they weren't). A workflow is failing because the goreleaser portion for `mesheryctl` needs to be updated.

### Desired Behavior:
Ensure that `mesheryctl` is supported; upload mesheryctl binaries as a release artifact.

[Slack Message](https://layer5io.slack.com/archives/CFGG6U10E/p1688073835640879?thread_ts=1688073667.105349&cid=CFGG6U10E)

**Comment by utkarsh-1905** [comment]
Hey @leecalcot, I checked out the Slack thread; if you all still need help with this, I can try to help you (pass me the baton 😄 )

**Comment by VaibhavMalik4187** [comment]
@leecalcote Looks like this one is also fixed.

**Comment by leecalcote** [comment]
@VaibhavMalik4187, not quite yet, no. The binaries should be uploaded as artifacts in the edge release workflow or, better yet, we need to define a new GitHub release type of "edge", not just a Docker tag of "edge".

**Comment by VaibhavMalik4187** [comment]
> 

Alright then, I'll keep this one under my radar and will try working on it once I'm free.
