### ISSUE TITLE
[mesheryctl] Remove - Apply a filter: mesheryctl exp filter apply 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7989]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
This experimental feature to apply a filter: `mesheryctl exp filter apply` has been determined to no longer be necessary.
 
#### Desired Behavior
Remove this subcommand.

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Boombag0607** [comment]
@leecalcote I would like to work on this.

**Comment by leecalcote** [comment]
Thank you, @Boombag0607
