### ISSUE TITLE
[mesheryctl] Filter: List subcommand dysfunctional

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7994]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
```
$ mesheryctl exp filter list
Error: Error processing JSON response from server.
invalid character '<' looking for beginning of value
```

#### Desired Behavior
Returns a list of filters by name and ID

#### Environment

- Host OS: Mac 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v0.6.99 	33ece5d95

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by suhail34** [comment]
I would like to go ahead with this

**Comment by leecalcote** [comment]
Thank you, @suhail34!
