### ISSUE TITLE
[mesheryctl] Filter: View not accepting name; requiring ID?

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7999]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Experimental command `filter view` is having the following issue:

```
$ mesheryctl exp filter view "test filter"
Error: Response Status Code 400, possible invalid ID
```

#### Desired Behavior
```
$ mesheryctl exp filter view "test filter"
No filter found matching the name "test filter"
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by VaibhavTalkhande** [comment]
hey @leecalcote  I want to work on this issue 
if I am right on this issue we have to create a condition in function, where we have to check if the filter exist or not  if not display error 
This changes need to be done in view.go
if I am wrong please tell

**Comment by VaibhavTalkhande** [comment]
It olllli would like to work on it
Assign me the issue
