### ISSUE TITLE
[Docs]Responsiveness issues

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshery#8029]
I have been spending my time reading about meshery and have encountered a few issues  . The more I'll dive deep about project , the more issues shall be listed here😆

#### Current State

- [x]  [Responsive issue of announced vulnerabilities](#second_issue)
- [x]  Responsive issue in supported platforms
- [x] [Incomplete navigation components](#third-issue)
- [x] [The calender in the footer doesn't turns to blue on hover as expected](#last_issue)
- [x]  [Missing grafana boards svg]

## 
<img src="https://github.com/meshery/meshery/assets/59855919/3bb8bb26-2a69-414d-a536-a59e846acf5c"
width="220px" ><img src="https://github.com/meshery/meshery/assets/59855919/6d3d8747-42c2-4496-af48-f6cfc28e898f" width="220px">

The current sidebar components headings have incomplete subheadings (for example in concepts) [I dont know its a bug or feature]
| Shown Subheadings | Complete subheadings |
| --- | ----------- |
|<img src="https://github.com/meshery/meshery/assets/59855919/bec3006b-682f-4ec7-807e-46e036324dc5" width="250px"> |<img src="https://github.com/meshery/meshery/assets/59855919/50912eb3-e43e-47b7-8fac-60fa0d2ba3f9" width="250px">|
##
#last_issue

#### Desired State

<img src="https://github.com/meshery/meshery/assets/59855919/29fff77b-f686-4c03-8979-84291715c5ee" width="300px">
<img src="https://github.com/meshery/meshery/assets/59855919/1905ec02-85e0-4bc1-8d90-9368a172c490" width="300px">

##
The headings should have complete subheadings
##
<img src="https://github.com/meshery/meshery/assets/59855919/fc1ef62a-9ca8-4145-916a-d120bcc7c440" width="200px">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Ghat0tkach** [comment]
I would like to work on these issues 📃

**Comment by vishalvivekm** [comment]
Thanks @Ghat0tkach.
There you go :rocket:

**Comment by vishalvivekm** [comment]
Please sound off with you progress so far @Ghat0tkach

**Comment by Ghat0tkach** [comment]
> Please sound off with you progress so far @Ghat0tkach 

I have already checked the boxes which I have done , just need to make sure for the navigation part . I have already asked on slack  , if the issue is valid . I'll raise my PR. 
Thank you  for the concern vishal
