### ISSUE TITLE
[UI] Fix public tag in filters configurations

### ISSUE THREAD

**Issue by HarshDobariya79** [meshery/meshery#8031]
#### Current Behavior

- The text color of the `public` tag is not visible in dark mode.

#### Desired Behavior

- Text color should be adjusted just like **Designs configurations** page.

#### Screenshots/Logs

**Current**
![public-tag-current](https://github.com/meshery/meshery/assets/29772969/aaf4748b-4f35-4e63-8958-34afe9af4cd8)

**Desired**
![public-tag-expected](https://github.com/meshery/meshery/assets/29772969/46905a50-dda8-40dc-9f89-3948a6a38916)

#### Environment

- Browser: Chrome
- Host OS: Linux
- Meshery Server Version: v0.6.99

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by VishwaRaval247** [comment]
I would like to work on this issue. Could someone please assign it to me?

**Comment by utkarsh-1905** [comment]
Hey, I can fix this. Can you please assign this to me @HarshDobariya79 ?

**Comment by HarshDobariya79** [comment]
> Hey, I can fix this. Can you please assign this to me @HarshDobariya79 ?

Thank you for asking @utkarsh-1905 :rocket:. But since we follow first come first serve and @VishwaRaval247 commented first, let's go with her.

**Comment by ranjanmangla1** [comment]
if nobody is working on this issue, can someone assign me this issue?

**Comment by VishwaRaval247** [comment]
> if nobody is working on this issue, can someone assign me this issue?

I'm working on it. I'll open a PR by tonight.
