### ISSUE TITLE
[mesheryctl] Updating Meshery using mesheryctl system update

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery#8039]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`
A new release of mesheryctl is available: v0.6.98 → v0.6.104
https://github.com/layer5io/meshery/releases/tag/v0.6.104
Check https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli for instructions on how to update mesheryctl
Updating Meshery...
Error: cannot update Meshery: could not install meshery server: open /home/user/.meshery/manifests/meshery-v0.6.104.tgz: no such file or directory
could not install meshery-operator: open /home/user/.meshery/manifests/meshery-operator-v0.6.104.tgz: no such file or directory
`
Unable to fetch installation manifests 
#### Desired Behavior
`mesheryctl system update` should fetch installation manifests in the absence of any local manifests.

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Philip-21** [comment]
i came across this issue today, how do we go about this ?

**Comment by yash37158** [comment]
I would like to work on this issue @thisiskaransgit

**Comment by Freedisch** [comment]
👀
Feel like it's more of an error during the initial installation...
But `update` should check first the presence of the manifests depending on the platform then fetch it in case it's missing
