### ISSUE TITLE
[Docs] Add Build and Release Meeting time and minutes link

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8048]
#### Current State
This page, https://docs.meshery.io/project/contributing/build-and-release, doesn't immediately offer information about the community meetings dedicated to Meshery CI.

#### Desired State
This page, https://docs.meshery.io/project/contributing/build-and-release, could use with an info box calling out the bi-weekly meetings. 
Details: https://meshery.io/calendar and minutes: https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit#

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ranjanmangla1** [comment]
I would love to work on this issue, please assign me this issue

**Comment by iampaandey** [comment]
I would like help in here..Please assign this to me @leecalcote and this time for sure please ..!

**Comment by sudhanshutech** [comment]
assigning in chronological order
