### ISSUE TITLE
[Docs] Build and Release: Edge Channel now includes versioned releases

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8049]
#### Current State
Meshery's Edge Release Channel now includes versioned releases. See this week's [Meshery CI meeting minutes](https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit#) for an example with screenshot. 

#### Desired State
The description of the Edge Release Channel needs to be updated to reflect this change - https://docs.meshery.io/project/contributing/build-and-release#edge-channel

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vaibhav-xt** [comment]
@leecalcote I'll be happy 😀 if get a chance to work on this issue.

**Comment by leecalcote** [comment]
Excellent. 👌

**Comment by vishalvivekm** [comment]
@vaibhav-xt Please let us know about your progress with the issue.

**Comment by parth721** [comment]
@vaibhav-xt can I work with you on this issue?

**Comment by vaibhav-xt** [comment]
@parth721 I am working.

**Comment by vishalvivekm** [comment]
> @parth721 I am working.

What's the status @vaibhav-xt ??
