### ISSUE TITLE
[Docs] Build and Release: Stable Release Channel now includes automated release notes mailer

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8050]
#### Current State
See this recent announcement for a description what has recently changed in the stable release channel - https://discuss.layer5.io/t/automated-release-notes-announcement-on-stable-release-channel/3004

#### Desired State
This page, https://docs.meshery.io/project/contributing/build-and-release, needs to be updated to include this description of how the release process works.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ranjanmangla1** [comment]
I would love to work on it, please assign me this issue

**Comment by iampaandey** [comment]
Please assign this to me @leecalcote

**Comment by hirentimbadiya** [comment]
I'd love to contribute to this @leecalcote
