### ISSUE TITLE
[MeshModel] Istio Base, incorrect icon generation for istio-base model

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#8051]
#### Current Behavior

[Integration Spreadsheet](https://docs.google.com/spreadsheets/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit#gid=0)

The spreadsheet has the correct icon and metadata set, but the component generator is creating wrong icon for the component.
The endoint, where the component and its metadata is visible: http://localhost:9081/api/meshmodels/models/istio-base/components

<img width="1790" alt="Screenshot 2023-07-04 at 2 47 35 AM" src="https://github.com/meshery/meshery/assets/48255244/fc788278-736f-403a-aa03-90e7eb224191">

URL to check for SVG: http://localhost:9081/ui/public/static/img/meshmodels/istio-base/color/wasmfilter-color.svg

#### Expected Behavior

The component generator should correctly scrape the component metadata.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@MUzairS15 ...

**Comment by MUzairS15** [comment]
<img width="1440" alt="Screenshot 2023-07-09 at 11 35 15 AM" src="https://github.com/meshery/meshery/assets/79860504/3c64f248-8784-4d02-8bbe-6494bc65d2e2">
This was fixed.
It happened since WASMFilter was under the `istio-base` model and just displayed `WASM FIlter` in istio-base.

**Comment by Abhishek-kumar09** [comment]
Good to close?
