### ISSUE TITLE
[CI] Integration tests are failing in firefox

### ISSUE THREAD

**Issue by vaibhav135** [meshery/meshery#8052]
#### Current Behavior

Currently the indexui_spec.js and settings_spec.js are failing in firefox but working fine in chrome.

#### Desired Behavior

Tests should work in all the intended browsers.

Please check this [post](https://discuss.layer5.io/t/meshery-ui-integration-test-are-failing-in-local/3020) for more info.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by MarioArriaga92** [comment]
Thanks for opening this issue @vaibhav135, we'll get it prioritized in next Meshery Build & Release Meeting
