### ISSUE TITLE
[e2e Tests] Meshery UI: Failing e2e tests on adapter management

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#8054]
#### Current Behavior

Failing Tests: https://github.com/meshery/meshery/actions/runs/5432305372/jobs/9879289314
Button Click events are failing, likely there are some timeout issues to look into as they sometime s pass. The contributor might require to extend the timeout amount to get things done.

#### Expected Behavior

All e2e tests should pass.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vaibhav135** [comment]
@Abhishek-kumar09 I will take a look at it.
