### ISSUE TITLE
[UI] Refactor: move search option out of the table

### ISSUE THREAD

**Issue by vaibhav135** [meshery/meshery#8059]
#### Current Behavior

Currently the search is residing in the table. Which should be out of the table. So you can search for both grid and list view.

<img width="1143" alt="image" src="https://github.com/meshery/meshery/assets/39329182/681a8b75-c06f-4624-8319-0e419fb88320">

#### Desired Behavior

The options should be a part of table iself 

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by MohammadAzhari** [comment]
it can be assigned to me

**Comment by vaibhav135** [comment]
@leecalcote you can assign it to me.

**Comment by ShivangRawat30** [comment]
I can take this one

**Comment by vaibhav135** [comment]
@ShivangRawat30 but there is already a PR raised for this by @sudhanshutech https://github.com/meshery/meshery/pull/8157
