### ISSUE TITLE
[Meshery-Server] No search response for catalogs in filter page 

### ISSUE THREAD

**Issue by vaibhav135** [meshery/meshery#8070]
#### Current Behavior

Currently in the filter page there is no response for when you search with catalogs visible.

#### Expected Behavior

You should get response for what you searched (if the searched result exists).

#### Screenshots/Logs

![image](https://github.com/meshery/meshery/assets/39329182/4313cb9a-76ce-4386-9771-4ed4abeac18c)

![image](https://github.com/meshery/meshery/assets/39329182/7a219aad-cec7-4329-be21-c9363cc6b249)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@vaibhav135, in your assessment, this is a backend issue, right?

**Comment by vaibhav135** [comment]
> @vaibhav135, in your assessment, this is a backend issue, right?

Aaah yes also talked to @yash37158 regarding he suggested the same. Seems like a backend issue.

**Comment by MUzairS15** [comment]
@vaibhav135 Good to close right? The issue was your user account didn't had any filters.

**Comment by vaibhav135** [comment]
@MUzairS15,  @sudhanshutech has raised an MR for this.

**Comment by vaibhav135** [comment]
@MUzairS15 No actually this was for catalogs. I mean the search only works when you have your filters. Not for catalog filters.
