### ISSUE TITLE
[Server] Overwriting Remote Provider User Preferences

### ISSUE THREAD

**Issue by senali-d** [meshery/meshery#8071]
#### Current Behavior

User preferences get request override any preferences set by meshery cloud. (`/api/user/prefs`)

#### Expected Behavior

Update user preferences without affect to existing items.

#### Screenshots/Logs

![1](https://github.com/meshery/meshery/assets/52546856/6281a187-a8f6-458c-9114-83fee3750366)

![2](https://github.com/meshery/meshery/assets/52546856/37c6adb7-5328-41ec-9e4a-0d08f0bcbd8f)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by yash37158** [comment]
Can you elaborate on this issue @senali-d

**Comment by naveen8801** [comment]
Hey @ritiksaxena124, I'd really like to work on this, can you please assign this to me
