### ISSUE TITLE
[Docs]  Responsiveness issue of footer

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery#8072]
#### Current State
        footer is not in it's right position in these two pages  
<img width="393" alt="image" src="https://github.com/meshery/meshery/assets/122862213/d8c09cb3-2549-46bd-8b13-5b3254c4f4cd">
<img width="250" alt="image" src="https://github.com/meshery/meshery/assets/122862213/270afe3a-dc26-4a45-8d21-140324735695">

#### Desired State
   footer should be below of the page 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Satarupa22-SD** [comment]
@thisiskaransgit  I would like to work on this issue.

**Comment by saaagarsingh** [comment]
Hey @thisiskaransgit if no one has been assigned to this issue I would like get it.

**Comment by Shashwat-srivastav** [comment]
hello i am new to opensource and i think this issue is perfect for me and 
here  i have to move the div containing the text below the footer icon div in the footer section
![Screenshot 2023-07-07 042001](https://github.com/meshery/meshery/assets/37861820/3f74383a-3e19-4c38-9aa1-79475f41aae5)

**Comment by thisiskaransgit** [comment]
@saaagarsingh, go ahead and fix this 🚀

**Comment by vishalvivekm** [comment]
@saaagarsingh Updates?

**Comment by saaagarsingh** [comment]
@vishalvivekm I was little busy due to some household issues from last couple of days. I'll have to re setup the meshery in the meanwhile you can assign this to someone who has already setup locally. Sorryy for the inconveniences from my side.😔

**Comment by AdityaRaimec22** [comment]
@vishalvivekm @thisiskaransgit Can you assign this issue to me. Thanks!

**Comment by vishalvivekm** [comment]
Thanks @saaagarsingh for letting us know.
There you go @AdityaRaimec22

**Comment by Yashsharma1911** [comment]
@AdityaRaimec22 is this issue resolved?

**Comment by thisiskaransgit** [comment]
closed as completed via #8352
