### ISSUE TITLE
[UI] Update MeshMap logo in Meshery UI

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#8077]
#### Current Behavior
The MeshMap logo is not correct

![issue](https://github.com/meshery/meshery/assets/51539117/4ada9a61-f0a1-49c3-b824-99b7e18c79b2)

#### Desired Behavior
Update the MeshMap logo with correct one
![MeshMap logo](https://github.com/meshery/meshery/assets/51539117/2f2452c6-068c-4a06-b7a4-34692fdcc070)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@duckling69 ...

**Comment by vaibhav135** [comment]
@leecalcote u can assign this to me.

**Comment by thisiskaransgit** [comment]
Since it's fetched by the API, the change would be needed in the extensions.

**Comment by leecalcote** [comment]
Perfect, @vaibhav135. Very true, @thisiskaransgit.

**Comment by duckling69** [comment]
I checked extensions repo and icon is already updated there could it be because we didn't have any releases in a while? @leecalcote
 we can just update the icon manually instead of fetching @vaibhav135

**Comment by duckling69** [comment]
![image](https://github.com/meshery/meshery/assets/85884487/80af02d0-eb5c-47b5-8448-c693f4362d1c)

closing as its been fixed
