### ISSUE TITLE
[UI] Update Performance icon in Meshery UI

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#8078]
#### Current Behavior
The Performance icon uses the stacked version of the SMP logo

![issue](https://github.com/meshery/meshery/assets/51539117/ed8a4097-ae63-4829-835d-bd0d9bee4c75)

#### Desired Behavior
Update the Performance icon

![smp-white (1)](https://github.com/meshery/meshery/assets/51539117/33082bca-9b5e-42b6-a0e1-473afe27ba4d)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vednp** [comment]
Hey @ritiksaxena124, I would like to work on this

**Comment by ritiksaxena124** [comment]
Go ahead @vednp, if you find any difficulty make sure to toss your doubt into our [slack channel](https://slack.layer5.io) or to our [discussion forum](https://discuss.layer5.io/)

**Comment by vednp** [comment]
Do I need to change all occurrences of logo or any specific one?

**Comment by leecalcote** [comment]
@vednp just this one. Seeing your questions in Slack, let's put a deadline of this Sunday on this assignment or free it up for another contributor.

**Comment by vednp** [comment]
Yeah sorry for such questions Initially I had some doubts but now it's all good

**Comment by vishalvivekm** [comment]
@vednp Updates?

**Comment by vednp** [comment]
@vishalvivekm I am sorry for the delay but I can't find the where the performance icon is in the website I am beginner and sometimes it get really overwhelming to go through the codebase therefore I apologize for disturbing you and would be really helpful if you could help me

**Comment by Player256** [comment]
I am too a beginner but maybe it is here https://github.com/meshery/meshery/blob/master/ui/public/static/img/drawer-icons/performance-icon_svg.js

**Comment by vednp** [comment]
@Player256 Thanks I also followed using the same link but was unable to get the svg. Can you tell me how you navigated?

**Comment by Player256** [comment]
In the navigator file https://github.com/meshery/meshery/blob/50f5e1669735cb1383ad8cf995a48746bf2ed328/ui/components/Navigator.js#L23C19-L23C19 found the performance icon's location

**Comment by vednp** [comment]
> In the navigator file https://github.com/meshery/meshery/blob/50f5e1669735cb1383ad8cf995a48746bf2ed328/ui/components/Navigator.js#L23C19-L23C19 found the performance icon's location

Okk Thanks
