### ISSUE TITLE
[Unit Tests] Writing more Unit tests for mesheryctls  Packages

### ISSUE THREAD

**Issue by Philip-21** [meshery/meshery#8087]
#### Current Behavior
Not much unit test for the [packages](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root) in mesheryctl 
#### Desired Behavior
Adding more Unit tests to test the units and individual components of the codes in [mesheryctl's  packages](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root) to improve ci coverage

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by Philip-21** [comment]
@leecalcote , @alphaX86 i would like to get started on this issue . To help improve our code coverage

**Comment by leecalcote** [comment]
Good deal, @Philip-21. // @nebula-aac @hexxdump

**Comment by Philip-21** [comment]
@leecalcote  , we still have to write more test for some packages and make some adjustments to some unit test files. 
Can this issue be be reopened ?
