### ISSUE TITLE
[Extensions] Model Typical K8s Deployment in MeshMap

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8093]
#### Current Behavior
Additional sample designs are needed for the Meshery Catalog (meshery.io/catalog).

![1688454567442](https://github.com/meshery/meshery/assets/7570704/2fb05883-52e2-45c8-8b3b-95d358e0ad8e)

#### Desired Behavior
1. Model the following diagram (as closely as possible) using MeshMap.

#### Acceptance Tests
1. Design is published in Meshery Catalog

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ranjanmangla1** [comment]
would love to work on this, can you assign me this issue?

**Comment by codingmickey** [comment]
Hi @ranjanmangla1 I am failrly new to devops as well as to this repo.. I looked at this issue but couldn't think I would be able to do it. But do you mind if we can collaborate? (Not exactly collaborating but can we discuss while you implement the stuff) that would really help me learn more! What's your thought
