### ISSUE TITLE
[MeshModel] Stateful Set Missing Icon

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8095]
#### Current Behavior
<img width="434" alt="Screenshot 2023-07-07 at 2 51 02 PM" src="https://github.com/meshery/meshery/assets/7570704/9050e6f9-1d75-4e0c-872a-f149d18d5cbc">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Is this a bug in Meshery Integrations sheet or in the UI? @Yashsharma1911 will you confirm?

**Comment by kumarankit999** [comment]
Should I work on this issue @leecalcote

**Comment by ranjanmangla1** [comment]
can I work on this issue @leecalcote?

**Comment by leecalcote** [comment]
Here's the thing: it sounds like an easy fix, but it isn't.
