### ISSUE TITLE
[UI] : Enhancement Request: Icon Representation for Light and Dark Mode Themes

### ISSUE THREAD

**Issue by abhiraj-ku** [meshery/meshery#8109]
#### Current Behavior
I would like to propose an enhancement for the icon representation of light and dark mode themes on our website. Currently, we are using the sun icon to indicate the light and the moon icon for dark mode.

#### Desired Behavior
when the theme is light, the theme toggle icon should be of moon icon which can serve as a recognizable visual cue for users to switch the theme and the same for light mode. 

This update will enhance user experience by ensuring the icons accurately convey the available themes and assist users in easily identifying and switching between light and dark modes.
#### Screenshots/Logs

![meshry-sun-icon](https://github.com/meshery/meshery/assets/113116498/04cb32ad-b9a0-4f46-8b6f-adf7227a014c)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by saaagarsingh** [comment]
Thats an amazing observation and It's a really good issue. @leecalcote @thisiskaransgit  what are your thoughts about this? Also I would love to resolve the issue.

**Comment by abhiraj-ku** [comment]
Thanks, @saaagarsingh but I want to work on this issue if you don't mind

**Comment by thisiskaransgit** [comment]
@abhiraj-ku, Thank you for the enhancement proposal, move this item to [meshery/meshery.io](https://github.com/meshery/meshery.io/issues/), since this concerns the website. We can discuss it in the Websites Meeting.

**Comment by abhiraj-ku** [comment]
Ok @thisiskaransgit so now I have to open the issue here: https://github.com/meshery/meshery.io/issues/ ?

**Comment by thisiskaransgit** [comment]
@abhiraj-ku, Yes, close this one, it was meant to be raised there.

**Comment by abhiraj-ku** [comment]
ok sure @thisiskaransgit

**Comment by leecalcote** [comment]
In the future, we can transfer the issue to the other repo...
