### ISSUE TITLE
[mesheryctl] Add command to register dynamic k8s components.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#8125]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Desired Behavior

Please refer to [issue](https://github.com/meshery/meshery/issues/8124) for additional details.
Add support for mesheryctl accordingly.
#### Mockups

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by codingmickey** [comment]
Hi, @MUzairS15 I would like to work on this issue! But would have many doubts to ask .. as this would be my first DevOps issue, Can I start?
