### ISSUE TITLE
[UI] Remove Conformance from navigation and fix meshmap icon alignment 

### ISSUE THREAD

**Issue by aabidsofi19** [meshery/meshery#8126]
#### Current Behavior
The Meshmap menu item is currently idented to right of other menu items .

#### Desired Behavior
Make alignment of meshmap menu item consistent with other links ..

![image](https://github.com/meshery/meshery/assets/65964225/29d98f7a-2f49-4053-bb2b-cad591a1d272)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ranjanmangla1** [comment]
I would love to work on it, can somebody assign me this isssue?
