### ISSUE TITLE
[UI] Designs: Publish to Catalog

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8143]
#### Current Behavior
The current publish to catalog modal lacks description, formatting, validation, and expectation setting with the user.

#### Form Fields
Here are the fields - https://meshery.io/catalog/deployment/1c9a988a-02fa-4d94-826f-a4cf4b8d1bc9/ These same fields are in [meshery.io/catalog](http://meshery.io/catalog) and should be the same fields in Meshery Cloud https://meshery.layer5.io/catalog/9268856a-57e4-41e0-a18c-03f714f1c023 

Field: patten_info
- [x] Display Title: Description
    - [x] Use textarea as the input type

Field: pattern_caveats
- [x] Display Title: Caveats and Considerations
- [x] Use textarea as the input type

Field: compatibility
- [x] Display Title: Technology
    - [x] Use checkboxes as the input type. Pull the list of values for this field dynamically from /api/meshmodels/models

Field: pattern_type
- [x] Display Title: Type
    - [x] Use dropdown/select as the input type - a that provides the same predefined selections as the Meshery Cloud Catalog does - that same that [meshery.io/catalog](http://meshery.io/catalog) does.

#### Form Format and Validation
1. Ensure that input components that have field labels.
1. Use prettified field labels (see "Display Title") above.
1. Use the word "design", not "pattern" (or don't use either).

- [x] Format: Put Technology and Type adjacent to one another 50% of column width.  
- [ ] Format: Put an “i” button adjacent to the "Submit for Approval" button and include a link to the [Approval flow docs in Meshery Docs](https://docs.meshery.io/concepts/catalog)

- [ ] Validation: Ensure that the Design name is not "Untitled Design", nor does it include "LFX".
- [x] Validation: Require values for all fields.

#### Acceptance Tests
1. Validation is enforced.
2. User expectations are set via docs link.
3. Form is RJSF-based.
4. Design schema / form schema is persisted in meshery/meshkit.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by aayush6200** [comment]
I would be happy to work on this project , If I could get assignment

**Comment by xiaor2** [comment]
Hi, I can help with this.
