### ISSUE TITLE
[Server] Meshery Adapter Deployments

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8150]
#### Current Behavior
Meshery Server is unable to undeploy Meshery Adapters.

#### Screenshots/Logs
```
time="2023-07-12T17:04:32Z" level=info msg="Undeploying Adapter" app=meshery
changing adapter status of meshery-osm on port 10009 to status DISABLED
time="2023-07-12T17:04:32Z" level=info msg="Failed to Undeploy adapter" app=meshery
time="2023-07-12T17:04:32Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" app=meshery code=2259 probable-cause= severity=3 short-description="Unable to create new kube client" suggested-remediation=
```

#### Environment

- **Host OS:** Linux (Ubuntu)
- **Platform:** Docker 
- **Meshery Server Version:** stable-v0.6.107

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Shaman20** [comment]
Hey @leecalcote I am know basics of golang, docker and kubernetes and was looking for meshery server issues. Can I work on this issue as my first

**Comment by leecalcote** [comment]
I very much appreciate this request @Shaman20. However, no, this is not a beginner issue and you need more support than you realize. The lack of "help wanted" label is intentional, because of the nature of this.

**Comment by leecalcote** [comment]
@nebula-aac it's showtime.

**Comment by nebula-aac** [comment]
still researching, i saw the error popped up, testing some changes

**Comment by leecalcote** [comment]
It's good to be aware of `docker context` @nebula-aac

**Comment by nebula-aac** [comment]
Yes the error occurred when in the Kubernetes context. I'm testing to check for docker versus kubernetes platforms before the deployment happens

**Comment by leecalcote** [comment]
We're still chasing down the goal of a slim default profile.
