### ISSUE TITLE
[UI] MeshModel: Import model package

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8156]
#### Current Behavior
Meshery UI users have a way of browsing the capabilities registry, but no mechanism to import new models.

#### Desired Behavior
Allow user to import a folder containing a model, which consists of one or more components, relationships, and policies.

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Meyazhagan** [comment]
@leecalcote is backend API implemented?

**Comment by ShivangRawat30** [comment]
@leecalcote can you please provide some more details about where the problem is, it would be very helpful for me to solve it.

**Comment by AdityaRaimec22** [comment]
@leecalcote Can you provide little more information about this issue.

**Comment by leecalcote** [comment]
Folks, understanding that, generally speaking, new contributors will lack the necessary context to make a positive impact here, the lack of `help wanted` and `good first issue` labels is intentional. Please note the use of the `design-required` label and the comment above about the necessity of a design spec needing to be written prior to implementation. If you'd like to draft the design spec, please do.

**Comment by leecalcote** [comment]
Thank you for volunteering. If writing this design spec isn't an area of comfort, let's get another issue assigned to you. Here's a very helpful search that lists all issues with the "[help wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+)" label assigned. I encourage to you inquire on issues even if they are assigned, if this issues don't have recent activity. A well-intended contributor might be accidentally squatting on an issue that they are no longer working on.

**Comment by AdityaRaimec22** [comment]
@leecalcote I think I have found the issue. The issue persists in the meshery docs page In `docs/pages/index.md` file where different sections are displayed statically like direct heading of the section are written and then links are embedded there. In this way introducing a new section from backened is not possible for now. I think you want to make this dynamic like user can Introduce a new section from backend or user will be allowed to import a folder containing model.

**Comment by leecalcote** [comment]
No, @AdityaRaimec22 , this issue has nothing to do with docs.
