### ISSUE TITLE
Unable to load dashboard from profile 

### ISSUE THREAD

**Issue by yash37158** [meshery/meshery#8158]
#### Current Behavior

The dashboard in Meshery is not loading when selected from the profiles dropdown menu.
#### Expected Behavior

Whenever a request has been made for the dashboard it should work perfectly fine.
#### Screenshots/Logs

<img width="700" alt="Screenshot 2023-07-13 at 2 37 37 AM" src="https://github.com/meshery/meshery/assets/68152307/ef6bc87d-639a-4bf2-a704-b948d82bfd72">

#### Environment

- **Host OS:** Mac os
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v0.6.107
- **Meshery Client Version:** stable-v0.6.107

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by theBeginner86** [comment]
Thank @yash37158 for opening this issue.
Would confirm a couple of question:
1. Are you running Meshery Server locally?
2. Did you see any error log in your server: `[Initialize Provider]: Failed to get capabilities ....`?
3. What do you see under `~/.meshery/provider/Meshery/v0.6.107-1`?

**Comment by theBeginner86** [comment]
Currently, it looks like you are running locally and had a network error due to which remote components weren't downloaded properly from https://github.com/layer5labs/meshery-extensions-packages and hence Meshery Server is not able to load those components when you try to navigate to those UI pages.

**Comment by theBeginner86** [comment]
This is what I see in https://playground.meshery.io environment which is running latest Meshery Server:

![Screenshot 2023-07-13 at 3 23 51 AM](https://github.com/meshery/meshery/assets/73700530/ec9726d2-9bd3-415c-a69f-bb53d454788f)

**Comment by theBeginner86** [comment]
Ideally, your locally ~/.meshery/provider/Meshery/v0.6.107-1 should look like as follows:

```
➜  v0.6.107-1 tree
.
└── provider
    ├── account
    │   └── profile
    │       ├── account.js
    │       ├── dashboard.js
    │       ├── events.js
    │       ├── identity.js
    │       └── security.js
    ├── navigator
    │   ├── img
    │   │   └── meshmap-icon.svg
    │   └── meshmap
    │       ├── graphql
    │       │   └── plugin.so
    │       └── index.js
    └── userpref
        └── meshmap_userpref
            └── index.js

10 directories, 9 files

```

**Comment by yash37158** [comment]
@theBeginner86  So I am not running meshery locally, it is being deployed in the Kubernetes cluster. 

* I don't see any error logs for the provider as the provider is set.
here is the ref:
<img width="900" alt="Screenshot 2023-07-13 at 3 43 24 PM" src="https://github.com/meshery/meshery/assets/68152307/df2b08b4-8d21-4dd8-b74c-4babe5d620da">
when a user clicks on the profile and tries to access the dashboard it returns an Unkown HTTP response

**Comment by theBeginner86** [comment]
> @theBeginner86 So I am not running meshery locally, it is being deployed in the Kubernetes cluster.
> 
> * I don't see any error logs for the provider as the provider is set.
>   here is the ref:
> 
> <img alt="Screenshot 2023-07-13 at 3 43 24 PM" width="900" src="https://user-images.githubusercontent.com/68152307/253244535-df2b08b4-8d21-4dd8-b74c-4babe5d620da.png"> when a user clicks on the profile and tries to access the dashboard it returns an Unkown HTTP response

Please, consider giving a complete set of your logs. 
And I'd be looking for your input on 3rd point in https://github.com/meshery/meshery/issues/8158#issuecomment-1633265465

**Comment by yash37158** [comment]
Here is the set of logs: 
<img width="700" alt="Screenshot 2023-07-14 at 12 57 17 AM" src="https://github.com/meshery/meshery/assets/68152307/6862589c-3499-4458-9a01-52d28f980b2d">

also i am unable to run `~/.meshery/provider/Meshery/v0.6.107-1` it gives an error `cd: no such file or directory: /Users/yashsharma/.meshery/provider/Meshery/v0.6.107-1`
