### ISSUE TITLE
Update Meshery UI Theme: Replace Roboto Font with Qanelas Soft Font

### ISSUE THREAD

**Issue by yash37158** [meshery/meshery#8159]
#### Current Behavior

The Roboto font needs to be displaced at a root MUI level in the Meshery UI theme with the Qanelas Soft font.
#### Desired Behavior

Need a consistent font Qanelas Soft for Meshery UI
#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v0.6.107
- Meshery Client Version: stable-v0.6.107
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by saaagarsingh** [comment]
Hey @yash37158 I would love to make the necessary changes, if you allow me.

**Comment by yash37158** [comment]
Hi @saaagarsingh, i am already working on this issue.

**Comment by priyanshu-kun** [comment]
@yash37158  @saaagarsingh  are you guys still working on this issue?

**Comment by yash37158** [comment]
Yes @priyanshu-kun, I have paused this issue as our gameplan involves migrating to MUI v5.

**Comment by leecalcote** [comment]
It'd be nice to get this done in the meantime, though...

**Comment by yash37158** [comment]
Sure @leecalcote

**Comment by leecalcote** [comment]
Wasn’t the PR reverted?

**Comment by leecalcote** [comment]
@Chadha93
