### ISSUE TITLE
[CI] Global fix for intermittent "ESOCKETTIMEDOUT CI run cypress test failures

### ISSUE THREAD

**Issue by MarioArriaga92** [meshery/meshery#8167]
#### Current Behavior

See #7740 (which wasn't fixed globally across al test suites), this error keeps happening intermittently when app takes more than the 30 seconds default timeout to finish compiling the client and server on first visit of page(s) - see this one, took 36.5 seconds just to finish next.js compile when test tried t o visit http://localhost:3000/settings page:
![image](https://github.com/meshery/meshery/assets/23443575/c119904b-6d1d-42ed-8aaf-49d4da6b866c)

#### Desired Behavior

According to [this issue comment](https://github.com/cypress-io/cypress/issues/7062#issuecomment-752458819), `responseTimeout` can be increased and in [Cypress Configuration Docs / Timeouts](https://docs.cypress.io/guides/references/configuration#Timeouts) clearly state this same option can be overwritten globally instead of on a case-by-case basis.

#### Implementation

Set `responseTimeout` to `50_000` milliseconds to reduce chance of such occurrences from producing test failures during CI runs.

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by JayKay24** [comment]
@MarioArriaga92 I'd like to give this a try. You can assign it to me.

**Comment by MarioArriaga92** [comment]
Hey @JayKay24, sure feel free to go ahead. Its been some time, do you happen to have a PR for this?

**Comment by JayKay24** [comment]
Hi @MarioArriaga92 will begin looking into this issue.
