### ISSUE TITLE
[CI] Enhance Meshmodel Component Updater

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#8173]
#### Desired Behavior

1. Enhance the [MeshModel Component Updater](https://github.com/meshery/meshery/tree/master/scripts/component_updater) to:
 i. Accept a configurable input to identify the file path for outputting Model SVGs.
ii. Output only Models and Categories, not Components, too.
iii. Deduplicate Model names (output only unique Model names).
iv. Replace any reference to "updation" with "updater".

2.  Enhance currently dispatch-able GitHub Workflow for Component Updater to:
i. Accept a configurable input to identify the file path for outputting Model SVGs.
ii. Replace any reference to "updation" with "updater".

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by parth721** [comment]
@abdullah1308 I want to work on this issue.
