### ISSUE TITLE
[meshkit] Move meshmodel generator and updater to Meshkit

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#8174]
#### Current Behavior

Various Meshery components require knowledge of and specifics of MeshModel models, components, and categories. A spreadsheet of centralized information about MeshModel components and their metadata like color, icon, and so on is available. The [Component Updater script](https://github.com/meshery/meshery/tree/master/scripts/component_updation) is used to update both components that are registered in the Meshery Server Capabilities Registry and on websites.

#### Desired Behavior

Enhance the extensibility of the component updater script to include the ability for configurable update destinations in support of Remote Providers (in addition to Meshery Server Capabilities Registry and websites).

#### Implementation
Move Meshmodel generator and updater to [MeshKit](https://github.com/meshery/meshkit).

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EleisonC** [comment]
Hello @abdullah1308 could i take on this task
