### ISSUE TITLE
[meshery server] Restructure server/meshmodel directory structure

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#8175]
#### Desired Behavior
Restructure `server/meshmodel` directory structure to support #8130

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by parth721** [comment]
@abdullah1308 I want work on this issue. Will you assign it to me .

**Comment by nakulbh** [comment]
@abdullah1308 @leecalcote is this issue still open ?. I would like to work on it

**Comment by Jougan-0** [comment]
@leecalcote can i work on this issue

**Comment by leecalcote** [comment]
@nakulbh @Jougan-0 that would be great, yes. Prior to assigning, it would be most helpful if you would give a brief description of your proposal to solve the issue. There's a bit of consideration needed in terms of how this affects other sub-systems.

**Comment by Jougan-0** [comment]
@leecalcote #8130 the components updater script is not present can u emphasize on the desired structure as it is not clear just by the #8130  issue

**Comment by Jougan-0** [comment]
From what i have understood if we can classify them as :
Operators(126)
Controllers(25)
Servers(3)
and other sub categories as well 
then out of 336 we can segregate 150+
These can be checked as the current directory ends with these so we can get them from the Model.name last word

**Comment by Jougan-0** [comment]
We can segregate the folders as their last word like operators controllers and these segregation. 
This can be achieved if we use another loop and just go through each and display them .
There are a total of 126 operators , 26 controllers and other directories too .
```for _, model := range models ```
and the model can go through each files and inside which every model is present

**Comment by Jougan-0** [comment]
@leecalcote may I work on this issue??

**Comment by leecalcote** [comment]
I would _really_ like for you to. There is more to this than is readily evident. How about this: join tomorrow's Meshery Dev meeting and let's get the other areas of concern pointed out for your consideration into how you're accounting for this change holistically. Details on that meeting here --> https://meshery.io/calendar. Feel free to drop a comment suggesting this as an agenda item.

**Comment by Jougan-0** [comment]
I would really like to but i am travelling tomorrow I guess I wont be able to make it in the meeting but i'll see the recording as soon as I reach home 
@leecalcote
