### ISSUE TITLE
[mesheryctl] Add mesheryctl system model

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#8176]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Implementation
1. Enhance `mesheryctl` to expose component generator and component updater functionality in binary form and available in new `mesheryctl` releases.
1. Use new MeshKit libraries. 
1. Create `mesheryctl system model`
    1. Create `mesheryctl system model list` - Use `/api/meshmodels/models` to retrieve and display list of the names of all registered models, using a single column format with just "model" name. 
    1. Create `mesheryctl system model view [model-name]` 
        1. Reusing the logic from `mesheryctl perf` retrieve and display the contents of the model record matching the [model-name]. If multiple models match the name, display list of matches and ask the user to select one for display. 
        1. In a key:value format (one key per line), display all model information, using yaml as the default style of output.
     1. Create `mesheryctl system model update` - supporting the following parameters:
**Usage:**

```
    mesheryctl system model update --source [path-to-spreadsheet] [--output-dir] [relative path persist assets/icons] 
```

**Example:**

```
$ mesheryctl system model update --source https://docs.google.com/spreadsheets/d/e/2PACX-1vSgOXuiqbhUgtC9oNbJlz9PYpOEaFVoGNUFMIk4NZciFfQv1ewZg8ahdrWHKI79GkKK9TbmnZx8CqIe/pub\?gid\=0\&single\=true\&output\=csv --system meshery-server --output-dir /docs/assets/images/models
```

_Future:_
     _1. Create `mesheryctl system model gen` - supporting the following parameters:_

#### Mockups

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by zakisk** [comment]
@abdullah1308 hey I want to go with it.

**Comment by zakisk** [comment]
@abdullah1308 /api/meshmodels/models returns all models if [version is not specified](https://github.com/meshery/meshery/blob/352f4a8ed98db36cbf9c32d3a1748bff2f561e35/server/handlers/component_handler.go#L165) so do I return all models's name or specify version?

**Comment by abdullah1308** [comment]
Hey @zakisk means does not filter models by version number. You can perhaps have a flag in this command to filter by version number.

**Comment by zakisk** [comment]
@abdullah1308 hi, in `mesheryctl system model view [model-name]` command if I got 2 Models in reponse e.g Jenkin Operator then I will show a prompt to let user select one of them, since [Model.Displayname](https://github.com/meshery/meshkit/blob/2f2de37dee6017b58afa1a47322c66df271a932c/models/meshmodel/core/v1alpha1/models.go#L39) fields are same, in order to differenciate between them which do I append to it, at the moment it will prompt as this:
```
Select a model:
> Jenkin Operator
  Jenkin Operator
```
what I am considering it is to append version to name as this:
```
Select a model:
> Jenkin Operator, version: 1
  Jenkin Operator, version: 2
```
tell me how to do it. thank you

**Comment by abdullah1308** [comment]
@zakisk I like the second approach.

**Comment by zakisk** [comment]
@leecalcote @abdullah1308 when I'm showing output of `mesheryctl system model view {model-name}` command, output may contain an unicode e.g:
```
{
  "name": "kubernetes",
  "version": "v1.25.4",
  "displayName": "Kubernetes",
  "category": {
    "name": "Orchestration \u0026 Management",
    "metadata": null
  },
  "metadata": {
    "svgColor": "ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg",
    "svgWhite": "ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg"
  }
}
```
`\u0026` unicode is for `&` but it is printing its unicode, I searched for solution and was suggested `strconv.Unquote` but didn't work and other solutions as well, do you know of any solution?

**Comment by zakisk** [comment]
@leecalcote I've completed implementation of `mesheryctl system model view [model-name]` command but I'm having an issue here is output in both format:
JSON:
```
{
  "name": "ps-db",
  "version": "0.4.0",
  "displayName": "Percona Server for MySQL",
  "category": {
    "name": "App Definition and Development",
    "metadata": null
  },
  "metadata": {
    "svgColor": "ui/public/static/img/meshmodels/ps-db/color/perconaservermysql-color.svg",
    "svgWhite": "ui/public/static/img/meshmodels/ps-db/white/perconaservermysql-white.svg"
  }
}
```
YAML:
```
id: 00000000-0000-0000-0000-000000000000
name: ps-db
version: 0.4.0
displayname: Percona Server for MySQL
category:
  id: 00000000-0000-0000-0000-000000000000
  name: App Definition and Development
  metadata: {}
modelMetadata:
  svgColor: ui/public/static/img/meshmodels/ps-db/color/perconaservermysql-color.svg
  svgWhite: ui/public/static/img/meshmodels/ps-db/white/perconaservermysql-white.svg
```

in YAML output id is shown as `000-..` I want to omit this, so do I create an issue in meshkit for this?, I want to ignor [ID field](https://github.com/meshery/meshkit/blob/2f2de37dee6017b58afa1a47322c66df271a932c/models/meshmodel/core/v1alpha1/models.go#L36) for YAML as it is at the moment for json.

**Comment by leecalcote** [comment]
@zakisk this is looking good so far. We should have prior art in areas like the `perf` commands for UUID shortening. In fact, we have an open need for shortening in the new `filter list` command in which one column displays a shortened UUID and another column shows the full UUID. 

In this case, we'll leave it to the client, not the server to shorten the UUID, leaving the server to respond with full length UUIDs.

**Comment by abdullah1308** [comment]
@zakisk Create a PR in meshkit changing the tag you've specified to `json:"-" yaml:"-"`

**Comment by zakisk** [comment]
@abdullah1308 @leecalcote plese share details for `system model update` and `system model gen`.

**Comment by theBeginner86** [comment]
cleaning up assignments

**Comment by AHB102** [comment]
@theBeginner86 Hi there 👋, I'm looking forward to work on this issue for lfx 2024 term 1, are there any prerequisites/ pre tasks that I should be aware of ?

**Comment by Eeshu-Yadav** [comment]
@Yashsharma1911 hello sir,i want to contribute in Expand CLI capabilities for registry management, i have also applies through lfx program of upcoming march session , can u assign it to me

**Comment by literalEval** [comment]
Hey @theBeginner86 @abdullah1308 

I am really interested in working on this project for the upcoming LFX term. can you please update the pretest, so that we can do the same ? Thanks.

**Comment by hanshal101** [comment]
Hey @abdullah1308 
I am looking forward to taking part in this project for the upcoming LFX term. I have significant experience building a CLI application. [LOL-CLI (A kubectl clone)](https://github.com/hanshal101/lol-cli) This is just a sample CLI to get a better understanding of the Go and Kubernetes APIs.

**Comment by leecalcote** [comment]
This feature has been delivered as `mesheryctl model`.
