### ISSUE TITLE
[Docs] Enhance "Authenticate with Meshery via CLI" to include configuration of `token` property in meshconfig

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8178]
#### Description
[This page](https://docs.meshery.io/guides/mesheryctl/authenticate-with-meshery-via-cli) needs enhanced with a description of the `token` property in mesheryctl `config.yaml`.

For additional context, see https://discuss.layer5.io/t/can-we-login-using-mesheryctl-without-opening-browser-with-token-or-something-similar/3132/3

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by codingmickey** [comment]
Hey @leecalcote can I try this out? This will help me dive deeper into the documentation as well as resolve the issue and learn new things relating to it!!

**Comment by parth721** [comment]
Hi @codingmickey I am a beginner. can I assist you on this issue. (I thought `help wanted` means need someone to assist)

**Comment by Yana-Gupta** [comment]
@leecalcote, I would like to volunteer to this issue.

**Comment by vishalvivekm** [comment]
Following fcfs, will have to assign this to @codingmickey .
@parth721 @Yana-Gupta Be sure to review the PR by @codingmickey

**Comment by vishalvivekm** [comment]
Any updates @codingmickey ?

**Comment by codingmickey** [comment]
Sorry for the delay as well as the inactiveness.. I faced some issues regarding the local setup of the docs.. I needed help regarding it. Should I ask my doubt at https://discuss.meshery.io?

**Comment by codingmickey** [comment]
Hi, I was able to run the repo but to be honest.. I felt isn't the instructions mentioned on the token property sufficient. what is it that should be specified more?

**Comment by codingmickey** [comment]
@leecalcote @vishalvivekm :

> Hi, I was able to run the repo but to be honest.. I felt isn't the instructions mentioned on the token property sufficient. what is it that should be specified more?
