### ISSUE TITLE
[Docs] Add example to use authenticated REST endpoints with curl

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#8179]
#### Current State
The current [REST API docs](https://docs.meshery.io/reference/rest-apis) do not contain an example on how to access authenticated endpoints using the `curl` command.

#### Desired State
Add an example of how to use a token in a `curl` command to access Meshery server's authenticated endpoints.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by spacemc2** [comment]
I would like to work on this issue. #8179

**Comment by leecalcote** [comment]
Sounds great, @spacemc2. 👍

**Comment by abhijeetgauravm** [comment]
I want to contribute!

**Comment by abdullah1308** [comment]
@spacemc2 This is what needs to be added

```
curl --location 'localhost:9081/api/<endpoint>' \
--header 'meshery-token: <mytoken>\
--header 'Cookie: meshery-provider=Meshery; meshery.meshery.io_ref=/;token=<mytoken>
```

**Comment by vishalvivekm** [comment]
Hey @spacemc2 
would you like to let us know of your progress here?
