### ISSUE TITLE
[mesheryctl] It takes very long to register MeshModel Components while running Meshery with `mesheryctl`

### ISSUE THREAD

**Issue by asubedy** [meshery/meshery#8181]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
While running Meshery using `mesheryctl` it takes really long time to to register MeshModel Components, compared to just few minutes when running Meshery using `make server`
```
2023-07-15 00:06:16 time="2023-07-14T18:21:16Z" level=info msg="Registration of in-cluster components started for contextID: 345ab1b7073bb119aeecc0d65bcf22f2" app=meshery
..
..
..
2023-07-15 00:40:16 time="2023-07-14T18:55:16Z" level=info msg="in-cluster components for contextID:345ab1b7073bb119aeecc0d65bcf22f2 registered" app=meshery
```
You can see here it took around 36 minutes to register the MeshModel components. 

#### Desired Behavior
The MeshModel Components shouldn't take this much time to register.

#### Environment

- Host OS: Mac 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker-Desktop Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by suhail34** [comment]
I will try to debug this

**Comment by asubedy** [comment]
@suhail34 how long did it take for the message to appear when running through `mesheryctl`?
