### ISSUE TITLE
Meshery: Unnecessary Kubernetes connection dependency

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#819]
**Description**
In more than one example, Meshery is unnecessarily dependent upon having a healthy connection to an active Kubernetes cluster. This issue documents an example with Grafana connections, however, there are other examples of this unnecessary dependency.

**Expected Behavior**
Users should be able to connect Grafana to Meshery without dependency on Meshery being connected to Kubernetes.

**Screen Capture**
Video describing issue - 
[![](https://img.youtube.com/vi/HEKBIujHwGg/sddefault.jpg)](https://youtu.be/EFeHhOsB-3w)

**Comment by leecalcote** [comment]
@Aisuko or @vijcheru would you like to look into this?

**Comment by Aisuko** [comment]
> @Aisuko or @vijcheru would you like to look into this?

I will take a look and  @vijcheru  you can do this first, I have another chart PR and `godoc` issue of `meshery-common-library` on my schedule.

**Comment by leecalcote** [comment]
I think we have eliminated each of these issues...
