### ISSUE TITLE
The connect button doesn't work

### ISSUE THREAD

**Issue by ShivangRawat30** [meshery/meshery#8193]
#### Current Behavior

when we try to connect the meshery account to google or github it gives a 404 error 

#### Expected Behavior

it should allow user to connect the meshery account to google account or github account.
#### Screenshots/Logs

<img width="1031" alt="Screenshot 2023-07-17 at 8 29 50 PM" src="https://github.com/meshery/meshery/assets/114716075/c71ad57a-5a02-475c-a999-538d64b3714a">

<img width="1017" alt="Screenshot 2023-07-17 at 8 30 49 PM" src="https://github.com/meshery/meshery/assets/114716075/7f72d2f3-3391-43e9-891d-101b6106a2a9">

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
If this issue is still pending, I wish to work on it :)
