### ISSUE TITLE
[mesheryctl] `filter list`: Search support

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8199]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
I am presented with 198 total filters, but seem to be unable to search for a specific filter like I can with `mesheryctl perf profile <search-term>` and don't see to be able to scroll through more results from the `list` command.

```
➜  ~ mesheryctl filter list
FILTER ID	USER ID                             	NAME               	CREATED           	UPDATED
8976e934 	b6467d0a-f11e-4614-9eb2-ab80c4f1c58d	Test Filter        	7-17-2023 15:23:46	7-17-2023 15:23:46
2f104efc 	a551897f-da39-4d4d-812e-6b299e82c457	Test Filter        	7-16-2023 22:7:34 	7-16-2023 22:7:34
9cf9703b 	efbdda42-67a0-4cb8-a968-4ef321eb6369	Unitled Filter File	7-14-2023 20:36:2 	7-14-2023 20:36:2
a7e703fd 	349b7693-7fee-488d-92e2-107ccdea8d93	http-trace         	7-14-2023 18:59:16	7-14-2023 18:59:16
ba0cfec8 	e0124940-8941-4adc-a57c-3a3c22b73eaf	Test Filter (Copy) 	7-14-2023 17:29:20	7-14-2023 17:29:20
76a77bf0 	e0124940-8941-4adc-a57c-3a3c22b73eaf	Test Filter (Copy) 	7-14-2023 17:27:13	7-14-2023 17:27:13
9efc8cf6 	e0124940-8941-4adc-a57c-3a3c22b73eaf	Test Filter (Copy) 	7-14-2023 17:26:41	7-14-2023 17:26:41
6577a8a2 	e0124940-8941-4adc-a57c-3a3c22b73eaf	Test Filter (Copy) 	7-14-2023 17:4:41 	7-14-2023 17:4:41
a746c10f 	e0124940-8941-4adc-a57c-3a3c22b73eaf	Test Filter (Copy) 	7-14-2023 17:3:18 	7-14-2023 17:3:18
4f652f31 	e0124940-8941-4adc-a57c-3a3c22b73eaf	Test Filter (Copy) 	7-14-2023 16:58:39	7-14-2023 16:58:39

    TOTAL                    198
```

#### Desired Behavior
Support search in the same fashion that `mesheryctl perf profile <search-term>` does.

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by narharim** [comment]
Hey @leecalcote, I would like to work on this.

**Comment by leecalcote** [comment]
@narharim sounds great.

**Comment by abdullah1308** [comment]
@narharim any updates ?

**Comment by suhail34** [comment]
> Hey @leecalcote, I would like to work on this.

If you aren't able to go ahead i can help with this

**Comment by narharim** [comment]
@suhail34 Yes sure. So far I have changed the structure of Filter API in mesherctl to accept query parameters (pageSize, pageNumber) . I am looking into the Meshery Server side implementation. If I need any help will message you in slack
