### ISSUE TITLE
[UI] Kubernetes Service Accounts: Formatting of Automount / Service Account Token field.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8202]
#### Current Behavior

@harkiratsm will you investigate the formatting and display of this field?

Screenshot:

<img width="644" alt="Screenshot 2023-07-17 at 6 23 25 PM" src="https://github.com/meshery/meshery/assets/7570704/e107ede7-f592-4298-b6cf-e6ed3a6a091d">

#### Environment

- Meshery Server Version: stable-v0.6.108

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by harkiratsm** [comment]
#8222 8222
