### ISSUE TITLE
[Docs] Update command reference for mesheryctl filter

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#8207]
#### Current State
https://docs.meshery.io/reference/mesheryctl#data-plane-intelligence-experimental-feature
<img width="915" alt="image" src="https://github.com/meshery/meshery/assets/76054921/c1573a0c-a77b-43a4-a1bd-9ef69c152ba4">

#### Desired State
1. Remove `(experimental feature)`
2. Add `mesheryctl filter import` subcommand
3. Currently the subcommands are linked to `home/reference/mesheryctl/exp/filter/<subcommand>`. Since `mesheryctl` filter has been removed from under`exp` (experimental feature), the subcommand should now be linked to the pages `home/reference/mesheryctl/filter/<subcommand>`
<img width="936" alt="image" src="https://github.com/meshery/meshery/assets/76054921/db37e477-823b-4809-aacc-401f8bac35dc">
<img width="937" alt="image" src="https://github.com/meshery/meshery/assets/76054921/6237b6db-cb11-4460-910a-c8fa9ac1f081">
4. Reflect any changes in [mesheryctl filter](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0&range=A123:A131) to the docs.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Yana-Gupta** [comment]
@abdullah1308 I want to work on this issue. Will you assign me.
