### ISSUE TITLE
[dashboard] Unresponsive MeshModel Dashboard

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#8211]
Currently, when a user hovers over MeshModel charts then the page becomes unresponsive and leads to flickering of chart.

This behavior is unexpected and should be resolved for better UX for Meshery users.

**Comment by theBeginner86** [comment]
Check recoding and screenshot for reference:



https://github.com/meshery/meshery/assets/73700530/cb6e4fc9-1b62-4020-bcb6-ef864d436f3f

![image](https://github.com/meshery/meshery/assets/73700530/ed2c31ae-a0a0-4927-8f6c-98939570f338)

**Comment by pranay-0512** [comment]
Hey @aabidsofi19, do you have any progress with the issue? I would like to give it a try
