### ISSUE TITLE
[Server] MeshModel: Support for retrieval of Registrants 

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#8224]
### Current Behavior

No API available to ascertain who the registering entity is for any given model/component/relationship/policy. None of the MeshModel APIs currently return registrant details.

### Desired Behavior
Users can readily view details of the registering entity at any point while browsing MeshModel resources.

### Implementation
1. Enhance the following existing APIs:

- [ ] 1. `/api/meshmodels/models`
- [ ] 2. `/api/meshmodels/models/components`
- [ ] 3. `/api/meshmodels/models/relationships`

2. Ensure that they each return the registrant id and registrant hostname.

- [ ] 1. Return Registrant `ID` from `hosts` table.
- [ ] 2. Return Registrant `hostname` from `hosts` table.
_3. Future: Return Registrant `name` from `connections` table._

### Acceptance Tests
1. Users are able to see the name of the registrant for any given component, model, or relationship.
_2. Future: for any policy._

2. Please add documentation of this api enhancement to the [docs](https://docs.meshery.io/reference/rest-apis)

### Mockups
 The following UI improvement will be tracked under a different issue #, but is included here for reference and conceptual understanding.

<img width="1935" alt="Screenshot 2023-07-19 at 1 25 14 PM" src="https://github.com/meshery/meshery/assets/7570704/48d21c35-75f2-49f4-8c30-fc7e2c3a684c">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UsmanDev09** [comment]
@abdullah1308

**Comment by Freedisch** [comment]
Issue solved
