### ISSUE TITLE
[UI] - Display registrants for models, components and relationships

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#8225]
#### Current Behavior

We do not show the registrants of meshmodels. 

#### Desired Behavior

<img width="1935" alt="registrant" src="https://github.com/meshery/meshery/assets/31584129/fd145eae-2c9b-4f1f-b3eb-c4eade7e64ee">

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ShivangRawat30** [comment]
Hey @UsmanDev09 I would also like to work on this.

**Comment by leecalcote** [comment]
@UsmanDev09 do you have an open PR on this?

**Comment by leecalcote** [comment]
I see that this issue is pending https://github.com/meshery/meshery/pull/8257 being completed by @Freedisch.

**Comment by Chadha93** [comment]
@Freedisch Assigning to you.....

**Comment by Freedisch** [comment]
> @Freedisch Assigning to you.....

Sure

**Comment by arunavabasu-03** [comment]
Can I work on this ?
