### ISSUE TITLE
[mesheryctl] mesheryctl perf apply command hangs until Performance Profiles page is opened in UI

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#8226]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
Running `mesheryctl perf apply <profile-name>` command causes it to hang indefinitely until the **Performance Profiles** page is opened in Meshery UI

#### Desired Behavior
`mesheryctl perf apply <profile-name>` should work as expected instead of getting stuck

#### Screenshots/Logs

https://youtube.com/clip/Ugkx-VAO8BRyOfDbYA48SnMaVsKw0YS8ZWbf

#### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.6.108
- Meshery Client Version: stable-v0.6.108
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sivasathyaseeelan** [comment]
Hi @abdullah1308, I would like to work on this issue. Can you please assign it to me?
