### ISSUE TITLE
[Server] - Endpoint to return keys mapped to a user

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#8227]
#### Current Behavior

We have an endpoint in meshery cloud that returns keys associated with a user. `api/identity/users/keys`. This api is not supported in meshery ui. 

![keys](https://github.com/meshery/meshery/assets/31584129/4366c781-37be-4e8e-b582-0f28ddf60a47)
![api](https://github.com/meshery/meshery/assets/31584129/92e5d037-ca14-4392-bf81-bcb01a8b8643)

#### Desired Behavior

We want the same api to be supported inside meshery ui so that the permissions framework [PR](https://github.com/meshery/meshery/pull/7859) can be merged 

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ShivangRawat30** [comment]
@UsmanDev09 you want to call the api `gMux.Handle("/api/identity/users", h.ProviderMiddleware(h.AuthMiddleware(h.SessionInjectorMiddleware(h.GetUsers), models.ProviderAuth))).
		Methods("GET")` from the UI to get user info ? 

I am new to the community, would love to help.

**Comment by UsmanDev09** [comment]
@ShivangRawat30 you can post your queries in #meshery channel on slack. Someone from backend team will get back to you
