### ISSUE TITLE
[Server] MeshModel API: New registrants Endpoint

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#8228]
#### Current Behavior

Currently, we have 3 tabs inside mesh models summary [page](https://playground.meshery.io/settings#meshmodel-summary) namely Components, Models and Relationships. 

![meshmodel](https://github.com/meshery/meshery/assets/31584129/ea302b1a-e058-46d4-b88c-1835327ef486)

#### Desired Behavior

We need a 4th tab named **Registrants** to display information of the registrant. 

We need to display the: 
1. Hostname
2. Port
3. ContextID
4. Endpoint
5. Summary of how many components, models and relationships are registered by the registrant

#### Implementation

Please create a new endpoint `api/meshmodels/registrant` that would return all this information. 

Refer to this [issue](https://github.com/meshery/meshery/issues/8224) for more contextual information.

#### Acceptance Tests

1. Refer to [API Endpoints Documentation](https://docs.meshery.io/reference/rest-apis) and add documentation for the new endpoint. 

2. Please add support for pagination, search, and filter for it to be accepted.  

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Freedisch** [comment]
@UsmanDev09 , will check it

**Comment by Freedisch** [comment]
@UsmanDev09 , please can u be more explicit when about returning the registrant endpoints, below are the fields returned by a registrant...
{
            "Hostname": "kubernetes",
            "Port": 0,
            "ContextID": ""
  },

**Comment by muhammmadusman3211** [comment]
@Freedisch please look at this [object model diagram](https://docs.google.com/drawings/d/1_qzQ_YxvCWPYrOBcdqGMlMwfbsZx96SBuIkbn8TfKhU/edit) to understand the relationship between tables. 

Regarding your question to "What should you return from the registrants endpoints?" 

Hostname, Port, ContextID, Endpoint (as contained in the host table) 

Other than this, you should return count of components, relationships and models registered by each registrant and the respective components, relationships and models. (count and their details)

![hosts](https://github.com/meshery/meshery/assets/109918724/a85b0066-ff19-4b17-bac5-225964a362dd)

**Comment by Freedisch** [comment]
@muhammmadusman3211  I can't access the diagram

**Comment by UsmanDev09** [comment]
@Freedisch any updates on your progress?

**Comment by Freedisch** [comment]
@UsmanDev09 , This will be available when my PR for Meshkit will be merged, still have one thing to enhance there

**Comment by Jougan-0** [comment]
Can i take this issue .

**Comment by Freedisch** [comment]
@Jougan-0 , here it is

**Comment by Jougan-0** [comment]
@Freedisch I didn't get it.
Have you pushed it to the changes or may I work on this issue

**Comment by Freedisch** [comment]
@Jougan-0, u can know start

**Comment by Jougan-0** [comment]
Okay thank you will finish it soon

**Comment by Jougan-0** [comment]
@Freedisch can you confirm that the context id and context name is from 
```api/meshmodels/models```
context id is host id and can you please explain the 5th point
Summary of how many components, models and relationships are registered by the registrant

**Comment by Jougan-0** [comment]
And how do i get the endpoint and port number are they in the same json file or any other url @Freedisch

**Comment by Jougan-0** [comment]
@Freedisch what i understood is that we have hostname and hostid in the json files of components models and relationship 
so we have to display them along with port and endpoint if any but what is the 5th one the summary we have the display the metadata ??

**Comment by leecalcote** [comment]
@Jougan-0, Immediately, I can confirm that Artifact Hub is an expected registrant of most of the components.

**Comment by Jougan-0** [comment]
The  localhost of istio is also showing but the endpoint is not visible .

**Comment by theBeginner86** [comment]
> @UsmanDev09 can you clarify this just finished up the endpoint can you double check if it is correct
> ![image](https://user-images.githubusercontent.com/99207534/269134224-7719aa1b-e0d6-4d8f-9538-017081c14c4d.png)

@Jougan-0 would you please link your PR with existing progress? So that it becomes easier for review.

**Comment by theBeginner86** [comment]
Also, we don't have to separately return different registrants of components, relationships, models... etc.
This would add heavy load on UI for filtering and grouping.

Would you please consider consolidating to the extent that you each entry  of response returns the number of components, models, relationships.
Example:
```
{
"page": <>,
"page_size": <>,
"total_count: <>,
"registrants" [
{"id": <>, "hostname": <>, "port": <>,  "endpoint": <>, "summary": {"components": <>, "models": <>, "relationships": <>, "policies": <>}}
...
...
]:
}

```

**Comment by Jougan-0** [comment]
The new endpoint just works on getting the is and hostname and other details of models apart from summary and endpoint everything is returned . I am travelling as of now will send a pr as soon as I can for review

**Comment by Jougan-0** [comment]
> @muhammmadusman3211 

Can i get the access to the object model
