### ISSUE TITLE
[CI] Code Report Analysis for Mesheryctl's filter package

### ISSUE THREAD

**Issue by Philip-21** [meshery/meshery#8241]
### Current Behavior
From the codecov report some files have low code coverage

### Desired Behavior
Increase the code coverage of the files in the filter package

![codecov](https://github.com/meshery/meshery/assets/73377830/13e891e3-bf0f-47c8-b0a9-0a4d50467d11)

### Details
definitions of each field in the [codecov](https://app.codecov.io/gh/meshery/meshery/tree/master/mesheryctl%2Finternal%2Fcli%2Froot%2Ffilter) report
- Tracklines: These are the individual lines of code in your software project that are being analyzed for code coverage. Each line can be marked as either covered or not covered.

- Covered: These are the lines of code that have been executed or reached during the execution of your tests. In other words, these lines have been tested, and the test suite has touched or executed them.

- Partial: These lines of code have been partially covered, meaning that only a portion of the line was executed during the tests. For example, if an if-statement has multiple conditions, and only one of those conditions was tested, it would be considered partially covered.

- Missed: These lines of code have not been executed during the tests. They were not touched by the test suite, and there is no information about their behavior under test conditions.

- Coverage: This represents the percentage of lines in the codebase that have been covered by your tests.

The [codecov](https://app.codecov.io/gh/meshery/meshery/tree/master/mesheryctl%2Finternal%2Fcli%2Froot%2Ffilter) report as of 21/7/2023

#### delete.go:
  Coverage: 0.00%
  Tracked lines: 37
  Covered: 0
  Partial: 0
  Missed: 37
- file seems to have no code coverage at all, meaning that none of the lines were executed during the tests. There are 37 tracked lines, and all of them are missed by the test suite. This indicates that there are no tests that exercise the code in this file.

#### error.go:
  Coverage: 0.00%
  Tracked lines: 8
  Covered: 0
  Partial: 0
  Missed: 8
- Similar to delete.go, this file also has zero code coverage. It contains 8 tracked lines, but none of them were executed during the tests.

#### filter.go:
  Coverage: 38.46%
  Tracked lines: 13
  Covered: 5
  Partial: 0
  Missed: 8
- This file shows a coverage of 38.46%. Out of the 13 tracked lines, 5 were covered (executed) during the tests, while the remaining 8 lines were not executed. This file has better coverage compared to the previous two files.

#### import.go:
Coverage: 4.17%
Tracked lines: 72
Covered: 3
Partial: 0
Missed: 69
- This file has a coverage of 4.17%, indicating very low test coverage. Out of the 72 tracked lines, only 3 were covered during the tests, while 69 lines were not executed.

#### list.go:
  Coverage: 2.27%
  Tracked lines: 88
  Covered: 2
  Partial: 0
  Missed: 86
- The file list.go also has a very low coverage of 2.27%. Out of 88 tracked lines, only 2 were executed during the tests, and 86 lines were not covered.

#### view.go:
  Coverage: 3.85%
  Tracked lines: 78
  Covered: 3
  Partial: 0
  Missed: 75
- View.go has a coverage of 3.85%. Out of the 78 tracked lines, only 3 were covered by the tests, and 75 lines were not executed.

#### Final Analysis
 - From the analysis,` filter.go` has the best code coverage with 38.46%, meaning that 5 out of 13 tracked lines were executed during the tests. On the other hand, , `list.go` has a very low coverage with only 2.27%, indicating that only 2 out of 88 tracked lines were executed during the tests, so as `import.go` and `view.go`,  `error.go` and `delete.go ` have the lowest coverage, with no trackedlines covered and executed. 
 -  Overall, the analysis shows that most of the files in this filter package have very low or no code coverage. This means that the test suite does not sufficiently exercise these files, and there may be potential issues or bugs in the untested code paths
---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by sivasathyaseeelan** [comment]
Hi @Philip-21, I would like to work on this issue. Can you please assign it to me?

**Comment by Philip-21** [comment]
> Hi @Philip-21, I would like to work on this issue. Can you please assign it to me?

Its just a ci report

**Comment by leecalcote** [comment]
@sivasathyaseeelan, however, we do need help in increasing code coverage. I encourage you to jump in by creating new unit tests. That would be most helpful.

**Comment by Philip-21** [comment]
> @sivasathyaseeelan, however, we do need help in increasing code coverage. I encourage you to jump in by creating new unit tests. That would be most helpful.

@sivasathyaseeelan yh we can work on these together, we can discuss more on slack
