### ISSUE TITLE
[mesheryctl] mesheryctl system check checks wrong platform 

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#8246]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

In the following example, running `mesheryctl system check` to check the health of an active Meshery deployment results in Docker being checked when Meshery is deployed on Kubernetes as per the current config context
```
mesheryctl system check

Docker
--------------
Error: Meshery is not running locally, please ensure that the appropriate Docker context is selected for Meshery endpoint: https://playground.meshery.io/. To list all configured contexts use `docker context ls`: exit status 1
➜  meshery git:(master) mesheryctl system context view

Current Context: playground

endpoint: https://playground.meshery.io/
token: default
token-location: auth.json
platform: kubernetes
components:
- meshery-istio
- meshery-linkerd
- meshery-consul
- meshery-nsm
- meshery-kuma
- meshery-osm
- meshery-traefik-mesh
- meshery-nginx-sm
channel: stable
version: latest
provider: Meshery
```

#### Desired Behavior

`mesheryctl system check` should check the correct platform to determine the health of Meshery. 

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by zakisk** [comment]
@abdullah1308 please assign it to me I will check this

**Comment by sivasathyaseeelan** [comment]
Hi @abdullah1308, I would like to work on this issue. Can you please assign it to me?
