### ISSUE TITLE
[mesheryctl] Shorten USER ID in mesheryctl filter list

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#8250]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

```
abrafi@AbMacAir mesheryctl % ./mesheryctl filter list   
FILTER ID       USER ID                                 NAME            CREATED         UPDATED  
5bed675f        0bd1161b-2add-4ac7-a627-cde597514b45    envoy.yaml      7-7-2023        7-7-2023
096f2030        0bd1161b-2add-4ac7-a627-cde597514b45    envoy.yaml      7-7-2023        7-7-2023
832638cb        0bd1161b-2add-4ac7-a627-cde597514b45    envoy.yaml      7-7-2023        7-7-2023

    TOTAL                     3                                                      

abrafi@AbMacAir mesheryctl % ./mesheryctl filter list --verbose
FILTER ID       USER ID                                 NAME            CREATED                 UPDATED           
5bed675f        0bd1161b-2add-4ac7-a627-cde597514b45    envoy.yaml      7-7-2023 16:58:47       7-7-2023 22:15:35
096f2030        0bd1161b-2add-4ac7-a627-cde597514b45    envoy.yaml      7-7-2023 16:53:7        7-7-2023 17:28:7 
832638cb        0bd1161b-2add-4ac7-a627-cde597514b45    envoy.yaml      7-7-2023 16:48:25       7-7-2023 16:48:25

    TOTAL                     3                                                                        
```

#### Desired Behavior

Shorten the USER ID to the segment before the first hyphen when the `--verbose` flag is not passed, for example -

```
FILTER ID       USER ID       NAME            CREATED         UPDATED  
5bed675f        0bd1161b    envoy.yaml      7-7-2023        7-7-2023
096f2030        0bd1161b    envoy.yaml      7-7-2023        7-7-2023
832638cb        0bd1161b    envoy.yaml      7-7-2023        7-7-2023
```

#### Mockups

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by zakisk** [comment]
@abdullah1308 I want to pick this up

**Comment by EraKin575** [comment]
Please assign me this issue

**Comment by AryanSharma9917** [comment]
Hey @abdullah1308 , I would like to work on this issue. Could you please assign this to me?

**Comment by premkirank** [comment]
@abdullah1308 I would like to pick this up. Please assign this to me

**Comment by abdullah1308** [comment]
Assigning issue to @EraKin575 as he's a new contributor

**Comment by EraKin575** [comment]
Thanks!

**Comment by EraKin575** [comment]
Wasn't this assigned to me?
