### ISSUE TITLE
[UI] Hover Effect at Used by Section

### ISSUE THREAD

**Issue by Harshu467** [meshery/meshery#8262]
#### Current Behavior

As of now in Used by Section all users company has been shown , for professional websites I have seen that , sponsors or company users are been hover when cursor and when click their websites are been open on new tab, but currently it is not there. And Also no hover effect on them in dark mode which is not proper
#### Desired Behavior

We can give hover effect to all the names of used by sections and when clicked on it the company website would open which enhance the website and it looks more professional.
#### Implementation

We  have yo add style on those users by giving specific style effect and also link their respective websites when clicked on it.
#### Acceptance Tests

When Feature is enhance we can close the issue
#### Mockups

![image](https://github.com/meshery/meshery/assets/89975347/80efcf7b-ac6b-4f1a-8b6b-99cb8fec9dc9)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by supzi-del** [comment]
I'd like to work on this.

**Comment by Harshu467** [comment]
I have created the issue , please assign it to me thank u

**Comment by Yashsharma1911** [comment]
Thanks for opening the issue @Harshu467, This issue is related to website please redirect it to [github.com/meshery/meshery.io](https://github.com/meshery/meshery.io)

**Comment by Yagi91** [comment]
Please assign this issue to me @Harshu467

**Comment by captain-Akshay** [comment]
hi @saurabh100ni please assign this to me

**Comment by saurabh100ni** [comment]
Go On @captain-Akshay 🥳🚀

**Comment by Mohith234** [comment]
This issue is not a part of meshery, it is a part of meshery.io so do transfer this issue to there

**Comment by Jaishree2310** [comment]
@Harshu467  @captain-Akshay  can you please assign this issue to me?
