### ISSUE TITLE
[UI] Show current status of deployment or undeployment for adapters extension

### ISSUE THREAD

**Issue by vaibhav135** [meshery/meshery#8276]
#### Current Behavior

For adapters extensions as of now to deploy or undeploy we toggle the switch and since the deployment and undeployment takes some time. There is  no feedback for what is really happening. All we know is that the operation is currently in progress.

#### Desired Behavior

It would be great if we could show a status chip and icon state for our adapter.

We can have the status icon like the below one (different color for different status)  :-

<img width="286" alt="image" src="https://github.com/meshery/meshery/assets/39329182/b4080875-18d7-4f1b-82a0-5af181883658">

The status could be one of 4 things:-
- Deploying (yellow)
- Undeploying (orange)
- Connected  (green)
- Disconnected (gray or red)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by punithnayak** [comment]
Hey  @vaibhav135 can you assign me I want to work o this

**Comment by Yana-Gupta** [comment]
@leecalcote @vaibhav135 Will you assign this issue to me.

**Comment by leecalcote** [comment]
@Yana-Gupta, correct. This is our initial goal with subsequent status indicators to follow after this. @abdullah1308 have you advanced the proposed connection statuses and their meanings?

**Comment by leecalcote** [comment]
@Yana-Gupta please press forward without a response from @abdullah1308

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta please press forward without a response from @abdullah1308

Yes 👍🏼
