### ISSUE TITLE
[UI] Extensions: Remove Meshery Adapter for Octarine card

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8289]
#### Current Behavior
This adapter has been archived and is no longer supported.

#### Desired Behavior
Remove its extension card entry under http://localhost:9081/extensions page in Meshery UI.

#### Screenshots/Logs
<img width="616" alt="Screenshot 2023-07-26 at 5 49 21 PM 1" src="https://github.com/meshery/meshery/assets/7570704/561f48ab-494e-4705-9e90-8a025635fa37">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by supzi-del** [comment]
Can I be assigned to work on this?

**Comment by abhijeetgauravm** [comment]
I want to work on this issue !

**Comment by leecalcote** [comment]
Thanks for volunteering!

**Comment by ShivangRawat30** [comment]
hey @leecalcote I've already fixed it, can I open a pull request ?

**Comment by abhijeetgauravm** [comment]
@supzi-del have u done?
