### ISSUE TITLE
Remove "above" from label-commenter-config.yml 

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery#8293]
Remove above from "DCO check above" on line 26 and 31

https://github.com/meshery/meshery/blob/9b373888409dec99418d2b32328533dacf26fbcc/.github/label-commenter-config.yml#L26

https://github.com/meshery/meshery/blob/9b373888409dec99418d2b32328533dacf26fbcc/.github/label-commenter-config.yml#L31

**Comment by abhijeetgauravm** [comment]
I want to work on this issue!

**Comment by singh1203** [comment]
Even i want to work on this may be i can review it.

**Comment by abhijeetgauravm** [comment]
@vishalvivekm  can u assigned me?

**Comment by iArchitSharma** [comment]
@vishalvivekm would it be possible for me to work on this issue? It seems like a great opportunity for me to start contributing to this project

**Comment by Savio629** [comment]
As we follow FCFS I'll assign @abhijeetgauravm the issue.
In meantime @singh1203 @iArchitSharma you guys can assist him or can check for some more good first issue in the project...
