### ISSUE TITLE
[Docs] Customization of MeshMap Snapshot

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8298]
#### Current State
Are users of [MeshMap Snapshot](https://github.com/layer5labs/meshmap-snapshot/) allowed to customize the trigger criteria for when the snapshot workflow runs? If so, are these customizations lost on upgrade to a new version of the MeshMap Snapshot Action?

#### Desired State
An update to the documentation that outlines this behavior - https://docs.meshery.io/extensions/snapshot

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by yash37158** [comment]
I would like to take up this issue @leecalcote

**Comment by yash37158** [comment]
Hey @Abhishek-kumar09 can you spread some light on this?

**Comment by Abhishek-kumar09** [comment]
@leecalcote , no they are not lost. The way user can customize the criteria for running the workflow. The upgrade should be happening just for the internal version of the MeshMap-Snapshot

Here is the ways in which the event can be triggered: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

**Comment by yash37158** [comment]
Hey @leecalcote, as I was working on this issue should add the triggers mentioned by @Abhishek-kumar09 in the docs. Also I was thinking to add steps to enable meshmap snapshot in the docs. let me know you views on this

**Comment by leecalcote** [comment]
@yash37158, great. Get it done. Your actions speak louder than good intentions. In the meantime, I'll open this up for others to help.
