### ISSUE TITLE
[Docs] Video feed in the "publishing a design page" is not responsive

### ISSUE THREAD

**Issue by Debjyoti0404** [meshery/meshery#8301]
Video feed present [here](https://docs.meshery.io/extensions/publishing-a-design#watch-a-turorial-on-how-to-publish-a-design) is not quite responsive as it is overflowing in mobile view.

#### Current State
![image](https://github.com/meshery/meshery/assets/103656712/3f3722db-2e9d-4865-95d3-24b6481fb37b)

#### Desired State
![image](https://github.com/meshery/meshery/assets/103656712/d3379e46-9951-4bea-9479-8e5b94128370)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Debjyoti0404** [comment]
Can I work on this issue?

**Comment by Chadha93** [comment]
@Debjyoti0404 You can replace the video with this one, and include an iframe, it will be responsive. https://www.youtube.com/watch?v=UCKS4eSB7AY
