### ISSUE TITLE
[UI]Overflowing of content at small width of playground.meshery.io

### ISSUE THREAD

**Issue by Modern-artist** [meshery/meshery#8303]
#### Current Behavior
Overflowing of content at small width.

#### Screenshots/Logs
<img width="1440" alt="Screenshot 2023-07-28 at 9 33 10 AM" src="https://github.com/meshery/meshery/assets/90668597/0a119349-1e2d-436e-a5df-2a8a090fd0bd">

#### Desired Behavior
It should not overflowing.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Modern-artist** [comment]
@leecalcote assign it to me.

**Comment by aabidsofi19** [comment]
There you go man :)

**Comment by leecalcote** [comment]
@Modern-artist were you able to figure this one out?

**Comment by Modern-artist** [comment]
@leecalcote  i had had figured it out. But i was busy in UI part of job. I will surly complete in a couple of days.

**Comment by aabidsofi19** [comment]
@Modern-artist  Whats the status here .

**Comment by Modern-artist** [comment]
@aabidsofi19 I am facing some issues which I have asked in slack. I have nearly solved this issue.
