### ISSUE TITLE
Remove and Archive OSM (Open Service Mesh) from Meshery

### ISSUE THREAD

**Issue by nebula-aac** [meshery/meshery#8305]
Currently, `osm` has been archived and is no longer in development.

Please see opened issue at `meshery-osm`: https://github.com/meshery/meshery-osm/issues/246

We will need to remove to every instance of `meshery-osm` and `osm` related.

- [ ] Archive https://github.com/meshery/meshery-osm
- [ ] Remove OSM from SMP proto
- [x] Remove OSM from golden template in `mesheryctl`
- [x] Remove OSM from default `meshconfig`
- [x] Remove OSM from docker extension

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ShivangRawat30** [comment]
@nebula-aac can you assign this issue to me ?

**Comment by EraKin575** [comment]
Please assign this to me

**Comment by Kansal002** [comment]
Can you assign me this issue ?

**Comment by leecalcote** [comment]
Folks, this isn't a good first issue. @nebula-aac or @Revolyssup will you be carrying this forward?
