### ISSUE TITLE
[Docs] Identify self-documenting and non-self-documenting portions of Meshery CLI

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8312]
<@U0499K1S4KY> , will you help ensure that the mesheryctl contributing docs highlight which part of the commands are self-documenting?

[Slack Message](https://layer5io.slack.com/archives/C0130BQ4L3T/p1690652929762569?thread_ts=1690642140.998719&cid=C0130BQ4L3T)

**Comment by Jagannathmaity110** [comment]
I am searching for some good first issue ,is this issue is solved??
