### ISSUE TITLE
[Docs] - Deploy Sample App Image Not aligned

### ISSUE THREAD

**Issue by vaibhav-xt** [meshery/meshery#8319]
#### Current State
Check out [Deploy Sample App](https://docs.meshery.io/guides/sample-apps), images are not aligned correctly. 
![Screenshot (53)](https://github.com/meshery/meshery/assets/90946899/2f83ffe5-9ff4-4668-b837-039f29913b7e)

#### Desired State
Must align horizontally. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by abhijeetgauravm** [comment]
I would like to work on this issue!

**Comment by EraKin575** [comment]
can I work on this issue?
