### ISSUE TITLE
[API Enhancement] - Enhance `api/filters` to return filtered catalog

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#8342]
#### Current Behavior

Currently, the endpoint `api/filter` returns all designs public, published, and private. 

#### Desired Behavior

Please enhance the endpoint to accept param `api/filter?visibility={visibility}` so that it returns only the requested visibility ie public, published or private.

#### Acceptance Tests

The endpoint should support pagination, search and sort. 

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
can I work on this? I am new and I wish to learn

**Comment by UsmanDev09** [comment]
Sure @EraKin575. Do you have the local development set up and running?

**Comment by EraKin575** [comment]
> Sure @EraKin575. Do you have the local development set up and running? 

Yes ! I have it set up and running

**Comment by UsmanDev09** [comment]
Alright. I am assigning it to you.

**Comment by EraKin575** [comment]
There are no endpoint named "/api/filters"

**Comment by EraKin575** [comment]
HI @UsmanDev09 ! Do I have to apply this parameter for both local and remote provider?

**Comment by UsmanDev09** [comment]
@EraKin575, yes

**Comment by theBeginner86** [comment]
@UsmanDev09 
I have updated the description to change `catalogType` to visibility considering that visibility relates public, published or private, while `catalogType` relates to type of config like design, filter etc.

Just to avoid confusion and improve intuition  from the param 👍

**Comment by EraKin575** [comment]
@theBeginner86 Can you check my local repo to see if I am heading in the right direction in this issue?

**Comment by Aritra8438** [comment]
If the PR is delayed, add me to the assignee queue! 😁
