### ISSUE TITLE
[UX] Design System Needed

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8347]
#### Current Behavior
Meshery UI has a design system that is in need of significant cleanup and definition in terms of the different UX paradigms employed in the projects, specifics of user interactions and expected behaviors. Consistency is key to a high quality experience.

#### Desired Behavior
A published design system available for reference and implementation audits.

#### Implementation
Building on the existing design system, complete a full design system in Figma. 

#### Acceptance Tests
1. Interactions around each component are documented.
2. Empty states defined

#### Mockups
See current "Meshery UI" design file.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by punithnayak** [comment]
Hey @leecalcote looks interesting I wanna be part of this

**Comment by Rajeevjewar** [comment]
> Hey @leecalcote looks interesting I want to be part of this

Hey, @punithnayak Can I also come up with you so we can do something interesting together?

**Comment by Veer0x1** [comment]
hello @leecalcote , I want to work on this project because I believe I have relevant skills for this project. I have previously worked with Figma, and I'm contributing Hyperledger Foundation in building design for their new website.

**Comment by 2004satwik** [comment]
interesting! looking forward to work with this project. @leecalcote

**Comment by leecalcote** [comment]
Very good. I encourage you to access and familiarize with the existing design system in the linked Figma design files above. Start participating in the project. We award internships to reinforce and support the impact a contributor is making.

**Comment by 2004satwik** [comment]
Sure! I'll definitely check out the files.

**Comment by goswamianshuman** [comment]
hey @leecalcote I just applied to the lfx mentorship program at Meshery and found this issue which is looking suitable for me to contribute. so can I also work on it? 😄

**Comment by Rajeevjewar** [comment]
Hi @leecalcote , I am working on it and completed the typography, colors, layouts/grid, shadows, and get started section of it's UX design system.
