### ISSUE TITLE
[Server] Package Meshery Catalog Artifacts as OCI Images

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8348]
### Description
Meshery Catalog content represents a schema-based description of cloud native infrastructure. Catalog content need to be portable between Meshery deployments as well as easily version-able in external repositories. 

References:

- https://github.com/kyverno/KDP/blob/main/proposals/store_kyverno_policies_in_oci_registries.md
- https://docs.kubewarden.io/distributing-policies/oci-registries-support.html
- https://docs.kubewarden.io/distributing-policies/publish-policy-to-artifact-hub

#### Implementation
Using Reactjs, Golang, GraphQL

#### Acceptance Tests

- Meshery clients (mesheryctl and Meshery UI) should be able to import/export Catalog content as OCI images.
- Meshery clients (mesheryctl and Meshery UI) should be able to push/pull from OCI-compatible registries.
- Stretch Goal: OCI image signing; Verify the authenticity of Catalog content using [cosign](https://github.com/sigstore/cosign).
- Target registries: Meshery Catalog (https://meshery.io/catalog), Artifact Hub.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by AryanSharma9917** [comment]
Hey @leecalcote, can I work on this issue?

**Comment by Yana-Gupta** [comment]
@leecalcote I will like to work on this issue. Will you assign me.

**Comment by leecalcote** [comment]
Excellent. Start by creating a design spec. Instructions for doing so are above.

**Comment by solo-daemon** [comment]
Hi @leecalcote . I am intereseted in working on this project.

**Comment by Adi9235** [comment]
Hey @leecalcote I am also interested on working on this issue

**Comment by leecalcote** [comment]
This is great. I can't wait to review a design spec draft. 👍

**Comment by nakulbh** [comment]
@leecalcote I am very intrested in working on this project.

**Comment by nakulbh** [comment]
@leecalcote, I would like to work on the design spec and I need some guidance in doing so.
I am having trouble in understanding the project completely
