### ISSUE TITLE
[mesheryctl] `perf` should not require connection to Kubernetes

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8364]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
```
$ mesheryctl perf
Error: Get "https://localhost:9443/api/v1/pods": dial tcp [::1]:9443: connect: connection refused.
The Kubernetes cluster is not accessible. Please confirm that the token is valid. See https://docs.meshery.io/installation/quick-start for additional instructions
```

#### Environment

- Meshery Client Version: stable-v0.6.115

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by parth721** [comment]
@lee I want to work on this

**Comment by leecalcote** [comment]
Thank you, @parth721. This is helpful.

**Comment by Freedisch** [comment]
@parth721, Just to know how it's going 👀

**Comment by parth721** [comment]
Working...

**Comment by EraKin575** [comment]
@leecalcote  can you assign me this issue? I have a PR ready on this

**Comment by leecalcote** [comment]
Thanks, guys.
