### ISSUE TITLE
[UI] Update components to be consistent and reusable

### ISSUE THREAD

**Issue by Avi-88** [meshery/meshery#8376]
#### Current Behavior

Components with same functionality aren't consistent across projects

#### Desired Behavior

Components having identical functionality should be consistent and reusable with the main reference being maintained in meshery cloud

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Yashsharma1911** [comment]
@Avi-88 Let's start with generic modal in meshery cloud also in meshery cloud we are using two standard modal instead of that we should only use one thoughts?
