### ISSUE TITLE
[mesheryctl] Error when running `make mesheryctl-*`

### ISSUE THREAD

**Issue by VaibhavMalik4187** [meshery/meshery#8378]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
```
$ make mesheryctl-linux-amd64 

CGO_ENABLED=0 GOARCH=amd64 GOOS=linux GO111MODULE=on go build -ldflags='"-w -s -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.version=v0.6.110 -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.commitsha=f6d61f5c84819bf3139976c407ac86502050e1f8 -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.releasechannel="edge""' -gcflags='' -o bin/mesheryctl-linux-amd64 ./cmd/mesheryctl/main.go
invalid value "\"-w -s -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.version=v0.6.110 -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.commitsha=f6d61f5c84819bf3139976c407ac86502050e1f8 -X github.com/layer5io/meshery/mesheryctl/internal/cli/root/constants.releasechannel=\"edge\"\"" for flag -ldflags: parameter may not start with quote character "
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
make: *** [Makefile:31: mesheryctl-linux-amd64] Error 2

```
- The behavior is same for all the `make mesheryctl-*` commands.

#### Desired Behavior
All the `make mesheryctl-*` commands run without failing.

#### Screenshots/Logs
![image](https://github.com/meshery/meshery/assets/34866732/a3d6327d-55c6-469d-9f7b-ee05e362cbaf)

#### Environment

- Host OS: Linux
- Meshery Client Version: v0.6.110

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by VaibhavMalik4187** [comment]
If somebody can just confirm the issue with the described steps, I have the fix ready, I'll make a PR.

**Comment by leecalcote** [comment]
@VaibhavMalik4187 I'm on macOS amd64 and have a similar experience:

```
 make mesheryctl-darwin-amd64

CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin GO111MODULE=on go build -ldflags='"-w -s -X github.com/meshery/meshery/mesheryctl/internal/cli/root/constants.version=v0.6.117 -X github.com/meshery/meshery/mesheryctl/internal/cli/root/constants.commitsha=6fb97c26912d69e2361d7a376fe942916027fcc8 -X github.com/meshery/meshery/mesheryctl/internal/cli/root/constants.releasechannel="edge""' -gcflags='' -o bin/mesheryctl-darwin-amd64 ./cmd/mesheryctl/main.go
invalid value "\"-w -s -X github.com/meshery/meshery/mesheryctl/internal/cli/root/constants.version=v0.6.117 -X github.com/meshery/meshery/mesheryctl/internal/cli/root/constants.commitsha=6fb97c26912d69e2361d7a376fe942916027fcc8 -X github.com/meshery/meshery/mesheryctl/internal/cli/root/constants.releasechannel=\"edge\"\"" for flag -ldflags: parameter may not start with quote character "
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
make: *** [mesheryctl-darwin-amd64] Error 2
```

**Comment by leecalcote** [comment]
Thanks for identifying and volunteering, @VaibhavMalik4187
