### ISSUE TITLE
Meshery Updater should push to docs.meshery.io

### ISSUE THREAD

**Issue by Boombag0607** [meshery/meshery#8381]
#### Current Behavior
Inside `/scripts`, the component updater is used to update components' metadata, such as SVGs, icons, and other details, for meshery.io and layer5.io

#### Desired Behavior
It should also have the ability to push the same to docs.meshery.io

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks!

**Comment by EraKin575** [comment]
Can I work on this? :)
