### ISSUE TITLE
Building Docker image heading isnt aligning with other headings

### ISSUE THREAD

**Issue by abhijeetgauravm** [meshery/meshery#8384]
#### Current Behavior

Building Docker image heading isnt aligning with other headings [here](https://docs.meshery.io/project/contributing/contributing-server#suggested-reading).
![image](https://github.com/meshery/meshery/assets/65087356/c60e4838-9a8e-4a9b-b94a-97734aeebe23)

#### Expected Behavior

It should be aligned with other headings.
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by abhijeetgauravm** [comment]
I would like to fix it!

**Comment by meaayush** [comment]
Can I work on this?

**Comment by abhijeetgauravm** [comment]
@thisiskaransgit would like to fix it!
