### ISSUE TITLE
Typo 'tabs' instead of 'tags'

### ISSUE THREAD

**Issue by abhijeetgauravm** [meshery/meshery#8385]
#### Current Behavior

 Typo 'tabs' instead of 'tags'

![image](https://github.com/meshery/meshery/assets/65087356/08a9a709-9bfc-4fe6-8176-79b72113a539)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by abhijeetgauravm** [comment]
I would like to fix it!

**Comment by zakisk** [comment]
@abhijeetgauravm which link isn't working?

**Comment by abhijeetgauravm** [comment]
@zakisk docker hub repo link for meshery adapter project  , i inspected there is slight error in href.

**Comment by zakisk** [comment]
@abhijeetgauravm in this https://hub.docker.com/r/layer5/meshery-<service-mesh> link, `<service-mesh>`  is a placeholder and its your that which service mesh's docker image you want to see, let say for isti the link is https://hub.docker.com/r/layer5/meshery-istio and thus for all service meshes that meshery supports.

**Comment by abhijeetgauravm** [comment]
ohh thanks @zakisk  i got it !  And  what abt the project service mesh performance which has link unlike other project?

**Comment by zakisk** [comment]
@abhijeetgauravm the link in the project column is for service mesh performance documentation and in the repository column it is for Layer5's SMP repo.

**Comment by abhijeetgauravm** [comment]
Okay @zakisk  i got confused at the time becoz in the project column rest of the project hasnt link and only there is linking in service mesh performance . So in your view wont be any irregularities in the table n ? So will close the issue! Though page has typo at one place for that i attached the screenshot!

**Comment by abhijeetgauravm** [comment]
@thisiskaransgit would like to fix it!
