### ISSUE TITLE
[mesheryctl] Switching Context Not Aborted

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#8387]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

While switching context, `mesheryctl` prompted that it would delete my current deployment so I refused to switch.
Then It prompted its aborted but still switched the context and my deployment

#### Desired Behavior

This misbehavior should be fixed and mesheryctl should abort if user gives an input of `n`.

#### Screenshots/Logs

![Screenshot 2023-08-05 at 9 54 00 PM](https://github.com/meshery/meshery/assets/73700530/8d814869-ebcb-4808-b6d6-0b222920ff1f)

#### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
Can you assign this issue to me?

**Comment by theBeginner86** [comment]
// @suhail34 @zakisk

**Comment by theBeginner86** [comment]
> Can you assign this issue to me?

Sure 👍
Have you been able to built and run mesheryctl locally?

**Comment by EraKin575** [comment]
yes, I have @theBeginner86
