### ISSUE TITLE
[UI] - Align Browse Button

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#8389]
#### Current Behavior

The browse buttons are places in new lines to input field. 

#### Desired Behavior

The buttons should be aligned to the input fields.
To reproduce, navigate to https://playground.meshery.io/performance/profiles and click on any profile card to view these buttons. 

#### Screenshots/Logs

![profiles](https://github.com/meshery/meshery/assets/31584129/b07f9f14-e1b6-47fb-87b5-8f4452dae5dd)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by 0x-chaitu** [comment]
Hi @UsmanDev09 I am working on it.
/assign

**Comment by Yana-Gupta** [comment]
Hello @UsmanDev09 I would like to work on this issue, if you would assign me.

**Comment by UsmanDev09** [comment]
I am assigning it to @0x-chaitu. 

@Yana-Gupta you can look out for other open issues.

**Comment by 0x-chaitu** [comment]
![image](https://github.com/meshery/meshery/assets/139210677/86fa9dbf-c541-468a-9a95-4a38d55a2a92)

![image](https://github.com/meshery/meshery/assets/139210677/c5310dcc-cf74-475c-b221-7d41e3d3cd45)

I did'nt find design for additonal options in figma.
If the above placements are fine I can make a PR.

**Comment by 0x-chaitu** [comment]
@UsmanDev09 There is one more issue, the certificate texfield is also not aligned with other texfields.

**Comment by UsmanDev09** [comment]
Please align it with other fields too. Width and height of these textfields should be the same. 

Regarding the button, it should be placed outside of textfield.

**Comment by 0x-chaitu** [comment]
Hi @UsmanDev09 
```
  1) Test if UI components are displayed on Index Page
       "after each" hook for "Left Navigation Panel":
     Error: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Proxy issue in Meshery-UI

```
I am not sure why this test is failing.

**Comment by sudhanshutech** [comment]
@0x-chaitu are you still tracking this, if not i have a pr open related to here so i will get a fix for it too

**Comment by abhinandanudupa** [comment]
This is the expected change right?:
![2023-08-21_09-46](https://github.com/meshery/meshery/assets/67597710/63eebac8-f975-4750-9c2b-9ee5e9ecb081)
