### ISSUE TITLE
[UI] - Perfomance Profile Certificate label wrongly updated

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#8390]
#### Current Behavior

When editing a profile which already has a certificate, when you upload a new cert, the name field is not updated, instead label is updated.

#### Desired Behavior

When editing a profile which already has a certificate, when you upload a new cert, the name field should be updated.

To reproduce, navigate to https://playground.meshery.io/performance/profiles, then click on a card which already has a certificate uploaded.
 
#### Screenshots/Logs

![label](https://github.com/meshery/meshery/assets/31584129/1ff87eb5-9cd5-4fd3-a62d-ebbe5b955438)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
please assign me

**Comment by UsmanDev09** [comment]
Sure. Go ahead @EraKin575

**Comment by EraKin575** [comment]
@UsmanDev09  what changes should I make in the label?

**Comment by UsmanDev09** [comment]
Label should be `Upload SSL Certificate eg. .crt file`

**Comment by sudhanshutech** [comment]
@EraKin575 i made here a quick fix since you already assigned to other issues
