### ISSUE TITLE
[mesheryctl] Shorten the User ID in `app list` command output

### ISSUE THREAD

**Issue by zakisk** [meshery/meshery#8394]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

in `mesheryctl app list` command user full UserID is shown.
```
APP ID          USER ID                                 NAME                                    CREATED         UPDATED   
1503c253        a550f4d6-d3bd-44f1-9b4c-167114452062    prometheus-elasticsearch-exporter-5.1.1 4-14-2023       8-4-2023 
e5965720        6a6ccef1-39d0-4ac4-8ae1-dc47d455d7ff    redis-deploy.yaml                       8-6-2023        8-6-2023 
b7d3e14b        6a6ccef1-39d0-4ac4-8ae1-dc47d455d7ff    currency-deploy.yaml                    7-8-2023        7-20-2023

   TOTAL                     3 
```

#### Desired Behavior

Show only first segment of User ID in output when `--verbose` flag isn't passed.
```
APP ID        USER ID       NAME                                            CREATED         UPDATED   
1503c253      a550f4d6      prometheus-elasticsearch-exporter-5.1.1         4-14-2023       8-4-2023 
e5965720      6a6ccef1      redis-deploy.yaml                               8-6-2023        8-6-2023 
b7d3e14b      6a6ccef1      currency-deploy.yaml                            7-8-2023        7-20-2023

   TOTAL                     3 
```
#### Implementation

this issue is same as #8250

#### Mockups

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gopivaibhav** [comment]
Can I work on this please?

**Comment by zakisk** [comment]
@gopivaibhav go ahead!

**Comment by gopivaibhav** [comment]
> @gopivaibhav go ahead!

Thank you @zakisk , I have made the PR :))
