### ISSUE TITLE
[mesheryctl] Remove args flag in subcommands

### ISSUE THREAD

**Issue by nebula-aac** [meshery/meshery#8400]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

`mesheryctl` has three subcommands that would benefit from removing the `args` flags to not require the user to provide a flag.

This makes the user experience a little bit jarring because when you go to navigate to certain subcommand, you expect the help menu to show up. On some of the subcommand, it didn't make sense to have `args` because there's already a help menu in place with other subcommands for that one.

Here is before with the list of subcommands that I found that I don't think needs the `args` flag set to require the user to provide a flag.

```bash
./mesheryctl system context
Error: please specify a flag or subcommand. Use 'mesheryctl system context --help' to display user guide.

See https://docs.meshery.io/reference/mesheryctl/system/context for usage details

./mesheryctl system channel
Error: please specify a flag or subcommand. Use 'mesheryctl system channel --help' to display user guide.

See https://docs.meshery.io/reference/mesheryctl/system/channel for usage details

./mesheryctl system token
Error: please specify a flag or subcommand. Use 'mesheryctl system token --help' to display user guide.

See https://docs.meshery.io/reference/mesheryctl/system/token for usage details
```

#### Desired Behavior

Remove the check if the input was not a flag, to instead show the help menu.

```bash
./mesheryctl system context
Configure and switch between different named Meshery server and component versions and deployments.

Usage:
  mesheryctl system context [command] [flags]
  mesheryctl system context [command]

Examples:

// Base command
mesheryctl system context


Available Commands:
  create      Create a new context (a named Meshery deployment)
  delete      delete context
  list        list contexts
  switch      switch context
  view        view current context

Flags:
  -c, --context string   (optional) temporarily change the current context.
  -h, --help             help for context

Global Flags:
      --config string   path to config file (default "/home/nebula-aac/.meshery/config.yaml")
  -v, --verbose         verbose output
  -y, --yes             (optional) assume yes for user interactive prompts.

Use "mesheryctl system context [command] --help" for more information about a command.
```

#### Implementation

This is already done in the PR: https://github.com/meshery/meshery/pull/8374

#### Mockups

---

#### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
If this issue is persisting, I would like to contribute to it

**Comment by nebula-aac** [comment]
This is already done, just waiting for PR to be reviewed and approved to be merged in. Thanks for checking @EraKin575

**Comment by nebula-aac** [comment]
completed
