### ISSUE TITLE
Show available Kubernetes context for uploaded kubeconfig.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#8401]
#### Current Behavior

When a kubeconfig is uploaded, meshery tries to connect to all available k8s_contexts.
#### Desired Behavior

When a kubeconfig is uploaded, instead of directly trying to connect to all, respond with available Kubernetes context in the kubeconfig and let the user choose which context to connect to.

(Bonus: Report back with connectivity status  for the available contexts inside the kubeconfig).
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by MUzairS15** [comment]
@zakisk Will you do the backend part and @UsmanDev09 the fronted part?

**Comment by zakisk** [comment]
Sure @MUzairS15, Thank you.

**Comment by UsmanDev09** [comment]
@zakisk please let me know when you are done with the backend.

**Comment by zakisk** [comment]
@MUzairS15 I have to make changes in kubernetes/register endpoint to return available contexts, yeah?

**Comment by zakisk** [comment]
@MUzairS15 and I need to create a new endpoint to connect to a context?

**Comment by zakisk** [comment]
@UsmanDev09 yes

**Comment by MUzairS15** [comment]
@Freedisch Can you take this up?

**Comment by Freedisch** [comment]
@MUzairS15, sure I'll dive in it

**Comment by MUzairS15** [comment]
Completed
