### ISSUE TITLE
[ Server ] - Enhance policies endpoints

### ISSUE THREAD

**Issue by Freedisch** [meshery/meshery#8418]
#### Current Behavior

We have 2 endpoints inside [the spreedsheat](https://docs.google.com/spreadsheets/d/1ABJCbfQRi0uN_YoP2kmHZ-lTI4S4QuvRk1_unomKNRE/edit#gid=1241442399) that has not yet been implementated
- [ ] `/api/meshmodels/models/{model}/policies`       
- [ ] `/api/meshmodels/models/{model}/policies/{policy}`    
#### Desired Behavior

 1 - Returns full defintion of a specific entity for the latest version
2 - Returns a list of registered policies within model scope
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
is this a beginner level issue? if yes,please assign me this

**Comment by clemenkok** [comment]
I would like to contribute to this. First time contributor, would love to get started

**Comment by Freedisch** [comment]
@clemenkok @EraKin575 please take a look at other open issues, this one is part of an enhancement process
