### ISSUE TITLE
[UI] Fix Search bar styles in configurations 

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#8419]
#### Current Behavior
The search bar has a blue label and unwanted bottom padding.
![image](https://github.com/meshery/meshery/assets/65453826/3e67cd59-e253-4706-837e-e8dd319ab130)

#### Desired Behavior
Change the label active and inactive color according to theme and this reference - https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=17282-40292&mode=design&t=CYTzY0i2w3npMrzR-0

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by meaayush** [comment]
can I work on this?

**Comment by Chadha93** [comment]
> can I work on this?

Sure @meaayush, quick check. have you built Meshery locally?

**Comment by meaayush** [comment]
@Chadha93 facing some issues with the build, I'm working on fixing it. 
You can assign this issue to someone else. Thank You.

**Comment by Yana-Gupta** [comment]
@Chadha93 I would like to work on this issue. Will you assign me.

**Comment by officialarmannqureshi** [comment]
@Chadha93 Hi,I would like to work on this issue.

**Comment by sudhanshutech** [comment]
@Chadha93 is this browser specific issue because its not visible on my side


https://github.com/meshery/meshery/assets/90546692/d849829e-8b2d-4812-8298-eccd11f8c55c

**Comment by anmolchhabra21** [comment]
Hi @Chadha93, if this is still pending can I work on this.

**Comment by UrjasweeChatterjee** [comment]
I'm interested to work on this issue. Can you assign me and i can see the figma file is restricted. Can you give me the permission?

**Comment by Chadha93** [comment]
> @Chadha93 is this browser specific issue because its not visible on my side
> 
>  Recording.2023-08-17.210239.mp4

Thanks all for volunteering to fix this issue. @anmolchhabra21 @UrjasweeChatterjee @officialarmannqureshi, you will want to confirm this first. You can do it from Meshery Playground - https://playground.meshery.io/. 

For Figma file view access, please check the description of #ux channel in slack.

**Comment by mikenrowland** [comment]
Hi @Chadha93 I see this issue is still unassigned after 5 days and I think it shouldn't be lingering for that long. Since no one has picked it up yet, please kindly assign to me. I confirm that I can and have fixed this using devtools on Meshery playground (see attached image) and I also have meshery UI set up locally. Thanks. 
<img width="1511" alt="Screenshot 2023-09-05 at 10 47 31" src="https://github.com/meshery/meshery/assets/54159746/61982d30-a4cc-4261-a85b-1f9f2632d76c">

**Comment by sudhanshutech** [comment]
This issue is not valid because we are having a standard toolbar , the search which is being is not longer used. We can close this
Thanks @mikenrowland for volunteering
