### ISSUE TITLE
[UI] Inconsistent toolbar UI between filter and design page 

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#8420]
#### Current Behavior

Currently, the toolbar section of Filter and Design has some inconsistency in its design, below are screenshot

![Screenshot 2023-08-09 at 6 56 35 PM](https://github.com/meshery/meshery/assets/71271069/39d9f06c-b3fa-46d0-9b67-912b48bd98d7)
![Screenshot 2023-08-09 at 6 54 48 PM](https://github.com/meshery/meshery/assets/71271069/a82be497-23cb-4956-bd1e-5a409448da5f)

#### Expected Behavior
Both pages are expected to have similar UI consistency. The design page has too much space between the card and the toolbar it should contain similar space like a filter and the application page have.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** 0.6.119

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
please assign me!

**Comment by Yashsharma1911** [comment]
sure go ahead @EraKin575
