### ISSUE TITLE
[CI] Send email notifications to support@layer5 on job failure

### ISSUE THREAD

**Issue by VaibhavMalik4187** [meshery/meshery#8430]
#### Current Behavior
No email notification is being sent.

#### Desired Behavior
If any job in this workflow fails, an email should be sent to [support@layer5.io](mailto:support@layer5.io) with details of the failure - https://github.com/meshery/meshery/blob/master/.github/workflows/build-and-release-stable.yml

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by leecalcote** [comment]
Thank you, @VaibhavMalik4187
