### ISSUE TITLE
[UI] Scrolling irregularities in Meshery Docs

### ISSUE THREAD

**Issue by abhijeetgauravm** [meshery/meshery#8432]
#### Current Behavior

Scrolling irregularities in Meshery Docs in Mobile and Tablet view. Won't able to scroll through whole content.
#### Screenshots/Logs

https://github.com/meshery/meshery/assets/65087356/445aa419-5bda-4d68-b8fe-744055845bc9

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by VamshiReddy02** [comment]
Can I work on this issue?

**Comment by Aayush987** [comment]
Hi, I will work on this issue. Please assign it to me.

**Comment by thisiskaransgit** [comment]
As discussed in the meeting @Aayush987, go ahead with this one 🚀
