### ISSUE TITLE
[UI] MeshModel Browser: Column Sorting not working

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8439]
#### Current Behavior
Under Settings --> MeshModel Browser, users are unable to sort table columns by clicking on the column headings

#### Screenshots/Logs
<img width="165" alt="Screenshot 2023-08-10 at 5 51 39 PM" src="https://github.com/meshery/meshery/assets/7570704/fd05e365-e3da-4448-8886-23fcc61519c6">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by premkirank** [comment]
@leecalcote I would like to work on this. Can you assign this to me?

**Comment by leecalcote** [comment]
Thanks, @premkirank

**Comment by vobanghia12** [comment]
@leecalcote Could I work on this ? Thanks

**Comment by leecalcote** [comment]
@UsmanDev09 has this issue been fixed, yet?

**Comment by vobanghia12** [comment]
I have just run the app on my local and it is still not working yet. It is currently only working for components and relationships

**Comment by aabidsofi19** [comment]
@vobanghia12 still up for this

**Comment by vobanghia12** [comment]
@aabidsofi19 Yes. I'm still up thanks

**Comment by aabidsofi19** [comment]
@vobanghia12 assigning it you .

**Comment by Kkotiswar** [comment]
@leecalcote I want to work on this issue, thanks?

**Comment by Kkotiswar** [comment]
also there are two columns named as "Model" in Settings -> Meshmodel Summary --> components --> show columns
![image](https://github.com/meshery/meshery/assets/76087446/ddf0a0e8-82da-47b6-84c8-172f14897f87)
in  show columns section 
![image](https://github.com/meshery/meshery/assets/76087446/be9895b1-b890-4adb-b443-c5bbea2ad116)
so is this also another issue??

**Comment by vobanghia12** [comment]
@Kkotiswar I'm currently working on this and update soon

**Comment by Kkotiswar** [comment]
Ok thanks for letting me know.

**Comment by phanithinks** [comment]
I was planing to take this task. But what I found is the backend rest api 

> api/meshmodels/models?page=1&pagesize=10

returning mesh models

but when 'order' query param added to the api call like below

> api/meshmodels/models?page=1&pagesize=10&sort=asc&order=displayName

its returning response as below
`{"page":1,"page_size":10,"total_count":112,"models":null}
`

Observe that  total_count in response is 112 but models is  null.

Need some guidance to fix this on golang (I am very new to golang)

**Comment by nick2432** [comment]
can i work on this?
