### ISSUE TITLE
[UI] MeshModel Browser: Relationships table row coloring

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8440]
#### Current Behavior
Under Settings --> MeshModel Browser:

1. Light mode: Relationships table row coloring is inconsistent with the Models and Components tables.
2. Dark mode: Relationships table row coloring - Lack of color contrast makes table illegible.

#### Screenshots/Logs
1. Light mode: 
<img width="1095" alt="Screenshot 2023-08-10 at 5 55 24 PM" src="https://github.com/meshery/meshery/assets/7570704/90ccf9df-2d52-4bdb-bb44-b299dcbb4e6b">

2. Dark mode:

<img width="1271" alt="Screenshot 2023-08-10 at 5 54 25 PM" src="https://github.com/meshery/meshery/assets/7570704/98241266-bca0-4729-82d2-70dbae63e67e">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by abhijeetgauravm** [comment]
I would like to work on it!

**Comment by abhishekmmgn** [comment]
It looks like both the foreground and text colors are light. The foreground color needs to be darker. I can work on this issue. Kindly assign this to me.

**Comment by majjikishore007** [comment]
@leecalcote   may I know is this issue still active

**Comment by leecalcote** [comment]
The existing light and dark mode theme styling needs to be applied.

**Comment by majjikishore007** [comment]
can i work on this issue @leecalcote

**Comment by leecalcote** [comment]
@majjikishore007, if @abhishekmmgn doesn't have a PR merged with 24 hours from right now, then, yes.

**Comment by majjikishore007** [comment]
sure thanks

**Comment by Yana-Gupta** [comment]
@leecalcote I would like to work on this issue, if noone is working now.

**Comment by leecalcote** [comment]
Thank you, @Yana-Gupta. Unless I have missed it, I haven’t seen an activity from @abhishekmmgn, yet.

**Comment by Yana-Gupta** [comment]
Thanks @leecalcote
