### ISSUE TITLE
[Server] Improve the formatting of  Deployment Errors 

### ISSUE THREAD

**Issue by aabidsofi19** [meshery/meshery#8454]
Currently the deployment errors are sent as a single string with no formatting from server . it makes them hard to read. 

![image](https://github.com/meshery/meshery/assets/65964225/7078507f-d8fb-4ddd-be6f-e8ba30ee6941)

There are a few regex tricks that we can employ here:
  -  Insert a period after every line break.
  -  Capitalize the first letter of every sentence.
  -  Insert `<ul>` and `,` for each line break 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by narharim** [comment]
@aabidsofi19 I would like to work on this

**Comment by aabidsofi19** [comment]
@narharim have you set up meshery locally?

**Comment by narharim** [comment]
Yes.

**Comment by aabidsofi19** [comment]
@narharim  you are good to go :)

**Comment by aabidsofi19** [comment]
@narharim  any progress here , or are you stuck on anything

**Comment by aabidsofi19** [comment]
assigned to you @Yana-Gupta
