### ISSUE TITLE
[UI] Inconsistent padding inside cards buttons.

### ISSUE THREAD

**Issue by priyanshu-kun** [meshery/meshery#8460]
### Current Behavior
All card Buttons in Meshery filter page have Inconsistent padding.

### Desired Behavior
Buttons should be look consistent.

### Screenshots/Logs

![Screenshot from 2023-08-13 19-42-38](https://github.com/meshery/meshery/assets/57032769/9e305855-efc1-461a-a2c6-5bf2dd42e33c)

### Environment

- Browser: Chrome, Firefox
- Host OS:  Linux Ubuntu 22.04
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Shreya111111** [comment]
@priyanshu-kun  kindly assign this issue to me

**Comment by abhishekmmgn** [comment]
Hey, there
I've already made changes in my local repo. I've chosen the padding .5px and 10px. 
Kindly assign this issue to me.

**Comment by priyanshu-kun** [comment]
> Hey, there I've already made changes in my local repo. I've chosen the padding .5px and 10px. Kindly assign this issue to me.

kindly raise a PR if you think your changes are good!

**Comment by hirentimbadiya** [comment]
@abhishekmmgn , please don't raise PR until the issue is not assigned to you.

**Comment by abhishekmmgn** [comment]
Ok.
I'll raise only if I get assigned.

**Comment by abhishekmmgn** [comment]
Okay. 🫡

**Comment by kituuu** [comment]
Can you assign this issue to me?

**Comment by Rajdip019** [comment]
I was assigned as a reviewer for this in the new comers meet this week.

**Comment by yash37158** [comment]
I think you tag wrong yash. ^^@Yashsharma1911

**Comment by Rajdip019** [comment]
> I think you tag wrong yash. ^^@Yashsharma1911

Oh sorry. Thanks for mentioning the right person XD.

**Comment by basimslam** [comment]
i was assigned to fix this issue. How to proceed?

**Comment by Ghat0tkach** [comment]
Thank you everyone for commenting , This issue was exclusively for newcomers call .
Why so? We do this to promote newcomers to find their first contribution !
There you go @basimslam 

Also if you do ran into any problem while setting up the repo or errors please feel free to ask on [discuss forum](https://discuss.meshery.io/)

**Comment by Rajdip019** [comment]
I will be assigned as a reviewer when he makes a PR right @Ghat0tkach ?

**Comment by Ghat0tkach** [comment]
@Rajdip019 , anyone can be a reviewer .😊

**Comment by Rajdip019** [comment]
Got it. I was assigned as a reviewer to this issue in the new comers' call so, that's why I am asking. If you have any other issue I can help with I will be happy to take that up. @Ghat0tkach

**Comment by anmolchhabra21** [comment]
Hi @priyanshu-kun, If this issue is still pending, I would like to contribute to it as a newcomer.

**Comment by Yagi91** [comment]
Can I get assigned to this isse?

**Comment by Yagi91** [comment]
@yash37158 can I get assigned to this bug?

**Comment by Harsha-10** [comment]
can i get assigned to this issue as i'm a newcomer....?

**Comment by Yashsharma1911** [comment]
Here you go @Yagi91 also can you confirm is the issues still happening before jumping in to fix it, yes then go ahead and raise the PR

@Harsha-10 thankyou for raising your hand, We have couple of other issues where you can help with this time let's go with @Yagi91 as we use First come First serve

**Comment by Yashsharma1911** [comment]
@Yagi91 any progress here? did you check if there is error?
