### ISSUE TITLE
search bar placeholder is cut off incorrectly

### ISSUE THREAD

**Issue by EraKin575** [meshery/meshery#8468]
### Current Behavior
![image](https://github.com/meshery/meshery/assets/100225222/fb43d433-cd7e-4c4c-a354-2a6a511d481c)
placeholder text is not shown correctly in search bar

### Desired Behavior
correctly configure placeholder dimensions 

### Environment

- Browser:  Firefox
- Host OS: Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Screenshot? // @sudhanshutech

**Comment by prashant235913** [comment]
I can work on this

**Comment by amRohitKumar** [comment]
@leecalcote can I work on this issue ?

**Comment by kituuu** [comment]
Can I work on this issue @EraKin575

**Comment by sudhanshutech** [comment]
@EraKin575 i don't see any cut off of placeholder in any where will you please confirm this issues still exist
![image](https://github.com/meshery/meshery/assets/90546692/ffe8f990-98e8-4616-ac1b-410724288657)

**Comment by EraKin575** [comment]
I think its a device problem. On my device,the upper part of placeholder text seems cut off . Please refer to screenshot

**Comment by helenrekha** [comment]
Could you please assign the issue to me ?

**Comment by helenrekha** [comment]
Could you please assign this issue to me?
Helen

**Comment by sudhanshutech** [comment]
Lets get Helen assign this as discussed in meet. Let get you folks assign other issues

**Comment by helenrekha** [comment]
Hi All,
I dont find the placeholder to be cut off in search bar. I checked with chrome, firefox and mobile phone. I haven't found this issue.
