### ISSUE TITLE
[UI] Make the card heights consisitent

### ISSUE THREAD

**Issue by aabidsofi19** [meshery/meshery#8470]
### Current Behavior

Presently, there exists an inconsistency in the heights of the cards within the configuration. To rectify this,  ensure that these cards dynamically adjust their heights based on the tallest component present, thus achieving uniformity in their appearance.

### Screenshots/Logs

![image](https://github.com/meshery/meshery/assets/65964225/a6e63bed-8acd-4b3e-bce2-dca6b14ef262)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
please assign me

**Comment by prashant235913** [comment]
I can work in this....

**Comment by aabidsofi19** [comment]
assigning to @EraKin575
