### ISSUE TITLE
[Endpoint Bug] - Meshmodel Browser Endpoints Sorting

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#8473]
### Current Behavior

1. For attribute `apiVersion` in case of components and relationships the endpoint returns null.

![apiVersionSort](https://github.com/meshery/meshery/assets/31584129/f3db2f28-fae5-49ea-bb3c-da7f9ffcd2e9)
![apiVersion](https://github.com/meshery/meshery/assets/31584129/c3cd8b76-6663-4e73-a178-5c783036f534)

 
2. For nested attributes, the endpoints does not sorts the result. For example, in case of `metadata` attribute we are displaying catergory name and model name but the data cannot be sorted. The attribute `metadata` is sorted correctly.

![metadata](https://github.com/meshery/meshery/assets/31584129/502449d9-be29-4c49-8ce5-f1d77bb897df)

### Expected Behavior

The data should be sorted on every attribute. Most importantly, for the following attributes that we are displaying on the meshmodel browser: 

**For Components:** 
1. Kind
2. Api Version
3. Sub category inside Metadata
4. Model inside Metadata 
5. Registrar (soon to be incorporated)

**For Models:**
1. Name
2. Version
3. Category Name inside Metadata

**For Relationships:**
1. KInd
2. Api Version
3. Model inside Metadata

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
The notion that `asc` and `desc` are appended without `sort=` or `sortby=` seems wrong, @UsmanDev09. This has me scratching my head.

**Comment by leecalcote** [comment]
Hmm. https://github.com/meshery/meshery/pull/8466#pullrequestreview-1578948014

**Comment by UsmanDev09** [comment]
You are right :+1:
