### ISSUE TITLE
[UI] Lifecycle Menu: Conditional display of menu items based on presence of Meshery Adapter

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8475]
### Current Behavior
See related issue https://github.com/meshery/meshery/issues/2855 and related PR - https://github.com/meshery/meshery/pull/4579

### Desired Behavior
The focus of what is needed is to not show the these service meshes in the left side menu unless their respective adapter is connected.

### Implementation
![screenshot_2023-08-15_at_11 41 38_am_720](https://github.com/meshery/meshery/assets/7570704/87631939-311e-4925-a858-959cc5382eb9)

### Acceptance Tests
1. Service mesh menu items under the Lifecycle menu are only displayed if their respective adapter is available/connected.
2. Continue to support multiple adapters of the same type being connected.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Debjyoti0404** [comment]
Can I work on this?

**Comment by leecalcote** [comment]
Oh, I missed your message and was just coming here to assign the issue to someone that volunteered in Slack. 

@Debjyoti0404, how about you offer review on their PR when it’s up?

**Comment by Debjyoti0404** [comment]
> Oh, I missed your message and was just coming here to assign the issue to someone that volunteered in Slack.
> 
> @Debjyoti0404, how about you offer review on their PR when it’s up?

Okay:thumbsup:

**Comment by leecalcote** [comment]
@aabidsofi19 do you recall if we're tracking any follow-up items here?

**Comment by aabidsofi19** [comment]
@leecalcote  yup i need to refactor this component and make the service mesh link render conditionally

**Comment by mashriram** [comment]
Good Day @leecalcote - I am a college student looking for my first Open Source contribution. Please assign this issue to me  if it is available. Thanks a lot
