### ISSUE TITLE
[UI]Missing Keppel Green active Color and Placeholder Text 'Search' in Configuration Search Box

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshery#8490]
### Current Behavior

![image](https://github.com/meshery/meshery/assets/59855919/1f27899e-085c-4f10-abf2-aef390096189)

When a user clicks over the search box in the Configuration section, the label-color should change to Keppel Green to indicate interactivity. Additionally, the search box shouldn't display the placeholder text "Search".
### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Shreya111111** [comment]
@Ghat0tkach  kindly assign this to me

**Comment by kituuu** [comment]
Can I work on this?

**Comment by kituuu** [comment]
I will review it.

**Comment by Ghat0tkach** [comment]
There you go @Shreya111111 and @kituuu

**Comment by rj2704** [comment]
This issue was assigned to me in today's newcomers call.

**Comment by Ghat0tkach** [comment]
@rj2704 , please comment below the issue from the very next time 😊
As I have already assigned someone , Will you please take care of the below issue?
https://github.com/meshery/learn-meshery/issues/91

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach Yes Sure👍. You can assign this to me.

Please comment on the below issue

**Comment by anmolchhabra21** [comment]
Hi @Ghat0tkach and @Shreya111111, if this is still in pending state, I would like to work on this issue.

**Comment by Shreya111111** [comment]
@anmolchhabra21  working on it

**Comment by Shreya111111** [comment]
will make pr in some days

**Comment by sudhanshutech** [comment]
Closing this issue @Ghat0tkach since this issue is no longer valid because we are using standard tool bar now .
Thanks for volunteering @Shreya111111 . You guys can offer feedback on current implementation
