### ISSUE TITLE
[UI] Expose Catalog Request Data

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#8493]
### Current Behavior

Currently, catalog request data is not exposed in Meshery UI. It's only shown when a user fills the form to publish.

![Screenshot 2023-08-16 at 9 27 14 PM](https://github.com/meshery/meshery/assets/73700530/ef609ecb-766f-4822-b14c-16e56cdfcfb7)

### Desired Behavior

Ensure that Catalog request data is exposed in readonly format on the back of the configuration card.

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by theBeginner86** [comment]
@Yashsharma1911 can you help here?

**Comment by kituuu** [comment]
Hey, can you assign me this issue

**Comment by singh1203** [comment]
@theBeginner86 If it's a beginner-friendly issue then I would like to work on it.
