### ISSUE TITLE
Add wrapper around JSON.parse

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#8496]
WIll you make a wrapper function around `JSON.parse` and use that wherever JSON.parse is used directly so that we don't need to add this same logic everywhere?

_Originally posted by @MUzairS15 in https://github.com/meshery/meshery/pull/8494#pullrequestreview-1581055156_

**Comment by EraKin575** [comment]
please assign

**Comment by EraKin575** [comment]
I have to apply the wrapper function in the whole codebase, right?

**Comment by MUzairS15** [comment]
Yes wherever JSON.parse is used.
