### ISSUE TITLE
[Server] Improve Error Message When Permissions to Read Kubeconfig are Lacking

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8500]
Meshery Server need to improve the logic and the reporting of what Meshery Server is doing when it connects or attempts to connect to Kubernetes contexts.

[Slack Message](https://layer5io.slack.com/archives/CFGG6U10E/p1692196537689409?thread_ts=1692196537.689409&cid=CFGG6U10E)

**Comment by Philip-21** [comment]
@leecalcote , @Chadha93 is this issue still open ?

**Comment by leecalcote** [comment]
@Philip-21, yes, @MUzairS15 has improved the eventing framework significantly and we're in need of taking full advantage of it. @zakisk is documenting portions of it now.

**Comment by leecalcote** [comment]
@Philip-21 much, much, much more context available here - https://github.com/meshery/meshery/issues/8507

**Comment by Philip-21** [comment]
> Checking in... it has been awhile since we've heard from you on this issue. Are you still working on it? Please let us know and please don't hesitate to contact a [MeshMate](https://meshery.io/community/meshmates/) or any other [community member](https://meshery.io/community/members) for assistance.
> 
> > Be sure to [join the community](https://slack.meshery.io), if you haven't yet and please leave a ⭐ [star on the project](../stargazers) 😄

I am On it
