### ISSUE TITLE
[UI] Fix K8s switcher not opening when clicking on notification circle on top of k8s logo

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#8502]
### Current Behavior
As you can see in the video when you hover on k8s switcher icon on Meshery UI header it gives a small animation and when you click on the k8s log, the switcher will slide down, but when you hover on the notification circle on top of k8s logo, animation will happen but when you click on that notification circle switcher will not slide down.

https://github.com/meshery/meshery/assets/71271069/de6d65bf-53cc-493c-afff-57874491c4d7

This current behavior of k8s switcher gives a bad user experience

### Desired Behavior
Desired behavior is whenever user click on k8s logo or notification circle on top of it, it should always slide down k8s switcher

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by akebu6** [comment]
@Yashsharma1911, the desired behaviour is to have the slider be displayed down upon clicking on the k8s logo and the notification icon correct?

**Comment by charu1603** [comment]
If this issue is still pending, @leecalcote can you please assign me this issue

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911, the desired behaviour is to have the slider be displayed down upon clicking on the k8s logo and the notification icon correct?
Yes, @akebu6 have you made any progress?

**Comment by Yashsharma1911** [comment]
> I would like to work on this pending issue. @leecalcote @Yashsharma1911, could you please assign me

Thanks for raising your hand @charu1603 let's wait for @akebu6's response for her progress if she will make PR it will be helpful if you can review it ^^

**Comment by akebu6** [comment]
I am still working on the issue, I just had a setback with my configurations but I should have a PR by today

**Comment by charu1603** [comment]
I would love to review this PR @akebu6

**Comment by akebu6** [comment]
@charu1603 I'm still working on it. Actually do you mind also helping me out? I reached out in the main slack channel but I haven't gotten any feedback yet

**Comment by charu1603** [comment]
> @charu1603 I'm still working on it. Actually do you mind also helping me out? I reached out in the main slack channel but I haven't gotten any feedback yet

Sure , lets connect on slack @akebu6

**Comment by akebu6** [comment]
@charu1603 you can ping me on slack, I use Akebu so it's easy to find me

**Comment by Yana-Gupta** [comment]
@Yashsharma1911 Shall I work on this issue, if noone is working on it.

**Comment by Yashsharma1911** [comment]
@Yana-Gupta yes please go ahead ^^

**Comment by Yana-Gupta** [comment]
@Yashsharma1911 The problem doesn't exist on the local development of the site. I have figured out that the problem is due to the '**transform**' CSS property of the slider. The '**transform**' CSS property is not working as desired; it is always set to 'none' when hovering or clicking the notification icon. It's hard to make any changes in the code on the local development environment, as it is working fine there.

**Comment by akebu6** [comment]
@Yana-Gupta that's the problem I faced, how to change it when it's working fine on the local. But hopefully you'll figure it out :⁠-⁠)

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta that's the problem I faced, how to change it when it's working fine on the local. But hopefully you'll figure it out :⁠-⁠)

@akebu6 Let's work on this together.

**Comment by Yana-Gupta** [comment]
> > @Yana-Gupta that's the problem I faced, how to change it when it's working fine on the local. But hopefully you'll figure it out :⁠-⁠)
> 
> @akebu6 Let's work on this together. Are you available to work together?

**Comment by akebu6** [comment]
@Yana-Gupta I'm still up for working with it. I'd like to know how it can be fixed honestly. When can we start?

**Comment by veryharsh123** [comment]
is anyone currently working on this? 
I've looked at the code and would like to help out/work on it.

**Comment by Yashsharma1911** [comment]
@veryharsh123 thanks for raising your hand this issue is fixed now, you can refer to other issues which are similar or if you need any help you can jump into slack and ask your question
