### ISSUE TITLE
[Server] Enhance error code, description, probable cause and suggested remediation for kubeconfig permission

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8507]
### Description

Users that deploy Meshery Server into a kubeadm deploy-d Kubernetes cluster, can find that Meshery Server doesn't have permission to read the `~/.kube/config`.

### Logs

```
meshery-meshery-1               | time="2023-05-31T15:09:30Z" level=error msg="Kubernetes cluster unreachable: error loading config file \"/home/appuser/.kube/config\": open /home/appuser/.kube/config: permission denied" app=meshery code=11081 probable-cause="Controller configuration may not be valid" severity=2 short-description="Error deploying meshery controller" suggested-remediation="Make sure the controller configuration is valid"
```

### Work-around
 I found the root cause is that when deploying Meshery docker, it will copy the `.kube` folder from host to docker's `/home/appuser/.kube` and continue to use the permission/owner from the host one. So, the docker's `appuser` user might not access the `.kube`.

The workaround is to set the permission of `.kube` before deploy Meshery:
```
chmod 777 -R .kube
```

### Acceptance Criteria
1. Ensure that this error/info notification is sent to /events.
2. Ensure that this error/info notification shows in Notification Center.
3. Inline docs to help users troubleshoot connections. Mockup:
<img width="436" alt="Screenshot 2023-08-17 at 12 23 42 PM" src="https://github.com/meshery/meshery/assets/7570704/56fdfa31-ef74-422b-917e-41fe37a2c5db">

#### Scenario: Kubeconfig not available on filesystem.
1. Kubeconfig not available on filesystem.
1. Kubeconfig available on filesystem. Lack of permission to access.
        1.  Severity: Informational.

#### Scenario: Uploaded kubeconfig invalid.
1. Uploaded kubeconfig malformed yaml.
1. Uploaded kubeconfg invalid. No clusters defined.
1. Uploaded kubeconfg valid. No credential available or invalid.
1. Uploaded kubeconfg valid. Certificates not available / not retrievable on filesystem.
    1. Severity: Warning

#### Scenario: Uploaded kubeconfg valid. 
1. Cluster and credentials defined, but cluster not reachable.
1. Cluster and credentials defined. Cluster reachable. Credential failed.
1. Cluster and credentials defined. One, but not all clusters reachable or credentials valid. 
    1. Severity: Warning

#### Suggested Remediations
1. Verify credentials.
1. Verify network reachability from Meshery Server.
1. Verify Kube API port availability.
1. Verify that the cluster is not already in an Ignored or Deleted state.

Connection States - https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g13d20fdaeef_1_53

_Originally posted by @gyohuangxin in https://github.com/meshery/meshery/issues/7165#issuecomment-1570461386_

**Comment by EraKin575** [comment]
please assign me
