### ISSUE TITLE
Move from SSE to GraphQL

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#8508]
### Current Behavior

The current implementation of SSE in meshery has bugs which leads to notifications getting lost or notifications getting routed incorrectly (sometimes to different active session)
### Expected Behavior

Move from SSE to GraphQL implementation. 
or make current SSE implementation robust.

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
@MUzairS15 can you assign this to me? I am currently working on implementing this on my local repo

**Comment by kundan766** [comment]
hey, @ MUzairS15  ,can you assign  me the issue
