### ISSUE TITLE
Connection table automatically starts paginating into an infinite loop

### ISSUE THREAD

**Issue by aabidsofi19** [meshery/meshery#8511]
<@U04TGEMEFDW> The connections table got stuck into an infinte loop automatically changes pages back and forth ,  the bug got triggered by clicking the next page quickly

[Slack Message](https://layer5io.slack.com/archives/C023QGMSH8D/p1692294078174919?thread_ts=1692294078.174919&cid=C023QGMSH8D)

**Comment by leecalcote** [comment]
@senali-d is this still an issue?

**Comment by senali-d** [comment]
> @senali-d is this still an issue?

Looking into this
