### ISSUE TITLE
[UI]  update Snackbar Calls to Use New Notification Hooks

### ISSUE THREAD

**Issue by aabidsofi19** [meshery/meshery#8512]
## Current State:
Throughout the codebase, the notistack snackbars are being used for notifications. However, we have recently improved the notification experience by developing our own custom hooks and components for handling notifications.

## Desired State:
We need to replace all previous snackBar calls with the new notification hooks that we have created.

## Previous Snackbar Usage:

```
handleClick() {
  // Previous snackBar call
  enqueueSnackbar(message, {
    variant: "info",
    action: <Button> </Button>
  });
}
```
## New Notification Hook Usage:

```
const { notify } = useNotification();

handleClick() {
  // New notification hook call
  notify({ message: "hello", event_type: EVENT_TYPES.INFO });
}
```
We also have created a withNotify HOC to use in class based components 

## Steps To Work On This :

- Identify instances where the old snackBar calls are being used throughout the codebase.
- Replace the old snackBar calls with the new notify hook calls, using the provided code snippet as a guide.
- Test the application thoroughly to ensure that notifications are being displayed correctly using the new notification hooks.
- Ensure that the useNotify hook is imported and used correctly in the components where notifications are triggered.

 

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
this seems to be a long one. Please assign this to me

**Comment by aabidsofi19** [comment]
Before you start hacking , give this document a proper read 
[Notification Center.pdf](https://github.com/meshery/meshery/files/12372578/Notification.Center.pdf)

**Comment by EraKin575** [comment]
@aabidsofi19 sure! Thanks!

**Comment by aabidsofi19** [comment]
here is a commit that does it for reference : https://github.com/meshery/meshery/pull/8510/commits/c87a468f9a419b092888a2038721c3788e62cb40

**Comment by leecalcote** [comment]
Regarding https://github.com/meshery/meshery/issues/8460#issuecomment-1682816343, @Rajdip019, there may or may not be a number of areas to breakout this issue into. @aabidsofi19 would know.

**Comment by Rajdip019** [comment]
I would love to take a look at this @leecalcote

**Comment by aabidsofi19** [comment]
@Rajdip019  take a look at the document and also the reference commit , if you feel confident i will assign a section of meshery codebase to you ( for implementing these changes )

**Comment by Rajdip019** [comment]
I have checked the issue, the document you provided and the reference implementation in the PR you have mentioned yesterday only. 

I am pretty confident that I can make the required changes to migrate from `notistick` to the custom hook. You can assign me a section of the codebase. @aabidsofi19

**Comment by aabidsofi19** [comment]
@Rajdip019  I am asssigning you the task of implementing these changes in class based components and @EraKin575  you will start on functional components

**Comment by aabidsofi19** [comment]
@EraKin575  you seem to have got a partner now

**Comment by EraKin575** [comment]
yeah!Lets do this

**Comment by aabidsofi19** [comment]
@EraKin575  @Rajdip019  I would love to review some commits by today evening  ..

**Comment by EraKin575** [comment]
@aabidsofi19 mine might be late, I am still in college.

**Comment by Rajdip019** [comment]
I am having this error can you help me out in this @aabidsofi19 

https://discuss.meshery.io/t/invalid-component-error-while-starting-meshery-system/3398
