### ISSUE TITLE
[UI] In the Meshry cloud design page - pagination UI at bottom overlapping the design card name.

### ISSUE THREAD

**Issue by csengineer1990** [meshery/meshery#8519]
### Current Behavior
In the Meshery Cloud dashboard, if we click on the design card, we go to the design page and at the bottom pagination UI overlaps the design card's name.
As I attached screen shoot for a clear understanding.

### Desired Behavior
In the desired behaviour it should not overlap the name of the design card and it should little below the design cards or align properly.

### Screenshots/Logs

![mesherydesign 1](https://github.com/meshery/meshery/assets/68468678/4da90682-181d-4375-a27f-1813c00c2dab)
![mesherydesign2](https://github.com/meshery/meshery/assets/68468678/7f2fa64d-b7bb-469b-945e-3f93ee9ae683)
![mesherydesign31](https://github.com/meshery/meshery/assets/68468678/c38dca2d-e3cb-4616-b165-73884fba8378)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by anmolchhabra21** [comment]
Hi @leecalcote and @csengineer1990, If this is not under progress, I would like to do this task.

**Comment by sudhanshutech** [comment]
@anmolchhabra21 this issue is regarding a private repo that has been fixed

@Avi-88 i guess this issue has been resolved. Please confirm and close the task
