### ISSUE TITLE
[Server] Add Support for filtering in Configuration endpoints 

### ISSUE THREAD

**Issue by aabidsofi19** [meshery/meshery#8547]
### Current Behavior
The configuration enpoints viz `api/pattern` , `api/filter` dont support filtering . we need to support filtering in these apis 
especially for the visibilty field it should be a enum 'private|public|published`

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
please assign me

**Comment by EraKin575** [comment]
actually @UsmanDev09  assigned me a issue similar to this https://github.com/meshery/meshery/issues/8342. I couldn't solve the issue at that time. If you assign me, I can retry a second time

**Comment by aabidsofi19** [comment]
@EraKin575  assigning this to you

**Comment by leecalcote** [comment]
@EraKin575 this is a golang-based enhancement.

**Comment by leecalcote** [comment]
@Aritra8438 …

**Comment by EraKin575** [comment]
@leecalcote yeah, I just learned Golang and bit of libraries used in Meshery. I was trying to get my hands dirty

**Comment by Aritra8438** [comment]
> @Aritra8438 …

Can assign it to me, @leecalcote.

**Comment by leecalcote** [comment]
> @leecalcote yeah, I just learned Golang and bit of libraries used in Meshery. I was trying to get my hands dirty

Makes much sense, @EraKin575. We're in need of seeing this completed relatively quickly.

**Comment by suhail34** [comment]
If there isn't anyone working here i can take this up

**Comment by Aritra8438** [comment]
Hi @suhail34, I'm working on this.
