### ISSUE TITLE
Docs: Broken Link in Meshery Documentation Build and Release Page

### ISSUE THREAD

**Issue by Mohiit70** [meshery/meshery#8552]
### Current State
The link in question is: https://docs.meshery.io/project/build-and-release. Clicking this link leads to a 404 error page with the message

![Screenshot layer](https://github.com/meshery/meshery/assets/120316966/70576bcf-17fc-4fe3-874f-c44097513bbd)

![Screenshot 2023-08-20 185120](https://github.com/meshery/meshery/assets/120316966/6b7c7283-2315-4f00-879e-d70fd6e045ad)

### Desired State

Clicking the link should take users to the correct documentation page on Meshery's build and release information.
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by shubhamku044** [comment]
Can I fix this?

**Comment by leecalcote** [comment]
@Mohiit70 were you wanting to work on this?

The correct link is - https://docs.meshery.io/project/contributing/build-and-release

**Comment by Mohiit70** [comment]
> @Mohiit70 were you wanting to work on this?
> 
> The correct link is - https://docs.meshery.io/project/contributing/build-and-release

Yes I'd like to work on this issue

**Comment by vishalvivekm** [comment]
@shubhamku044 Thanks for jumping in. 
While assigning issues we follow FCFS. Please be sure to review @Mohiit70 's PR.

 A list of good first and help wanted issues : https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by shubhamku044** [comment]
> @shubhamku044 Thanks for jumping in. While assigning issues we follow FCFS. Please be sure to review @Mohiit70 's PR.
> 
> A list of good first and help wanted issues : https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

sure. I will review it and also will try to contribute to other issues.

**Comment by Mohiit70** [comment]
@vishalvivekm Just to clarify, the broken link issue I reported is in the "service-mesh-performance" repository, not Meshery. I've opened a new issue there. Thanks!
