### ISSUE TITLE
[Server] Meshery Events

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8560]
### Current Behavior
Meshery Server has an events API for receiving events from Meshery Adapters. The message format is defined in the meshes protobuf.

### Desired Behavior
Meshery Server to expand the events construct for other systems and use cases, feeding Notification Center with highly detailed and structured information. Meshery Server to persist events.

### Implementation
1. Use new MeshKit library eventing features.
1. Define Golang Structs
1. Enhance Golang Handlers
1. DB: Enhance Local provider to persist events
1. New events subscription via GraphQL

### Acceptance Tests
1. Events are persisted in local database.
2. Events are schema-validated. 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@MUzairS15 done?

**Comment by MUzairS15** [comment]
Events are not validated against schema , all other done.
