### ISSUE TITLE
Add support for Environments construct in Meshery

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#8563]
### Desired Behavior
Environments require the following
1. A schema definition followed by a database table
2. API Handlers

Environments should have the standard data table fields, a name, and zero of more relationships to Connections and Workspaces.

Outside of a table for Environments, we need a Mapping table for Environments and all of its constituent Connections and Workspaces.

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by AryanSharma9917** [comment]
Hey @abdullah1308, am I correct with the ideology of the issue?
Define a schema for the Environment construct. This can include fields such as `name`, `created_at`, `updated_at`, etc.
Then implement `CRUD` operations for the environment, and setup routes for the API handlers.
then define relationships between Environments and Connections, as well as `Environments` and `Workspaces`, thus modifying database schema to include foreign key references to the `Workspace` and `Connections`.
Am I correct with this one?

**Comment by coder12git** [comment]
@abdullah1308 I would like to work on this :)

**Comment by saurabh100ni** [comment]
Go On @coder12git

**Comment by coder12git** [comment]
> Go On @coder12git

Thanks, please assign to :)

**Comment by sudhanshutech** [comment]
// @Yashsharma1911

**Comment by Yashsharma1911** [comment]
Environment construct is now added in meshery with all supported APIs
