### ISSUE TITLE
Change `CustomToolbar.js` from class based component to functional component

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8565]
### Current Behavior
`CustomToolbar.js` is a Class based component

### Desired Behavior
`CustomToolbar.js` as a functional react compoennt

### Implementation
Will convert the `CustomToolbar.js` to a modern functional component and will make the changes to incorporate those changes.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Rajdip019** [comment]
Hey @aabidsofi19 as we talked earlier can you assign me this issue?

**Comment by leecalcote** [comment]
Fixed.

**Comment by leecalcote** [comment]
Gentlemen,

It is most excellent to see this work being done. 👏

**Comment by Rajdip019** [comment]
I guess you have mistaken. The PR attached where is the previous one I am working on.

Migrating the Notification system.

I can see the CustomToolbar.js as a class component in the master branch.

I am working on it and will raise a PR by today.

Can you confirm please? @leecalcote

**Comment by leecalcote** [comment]
@Rajdip019, oh, I assumed that the linked PR (merged) above was the fix for this issue.

**Comment by leecalcote** [comment]
I retract my comment about the good work being done here. 😉
