### ISSUE TITLE
[meshkit] `unsafe.slice` issue in `meshkit`

### ISSUE THREAD

**Issue by nebula-aac** [meshery/meshery#8577]
### Current Behavior

Refer to https://github.com/meshery/meshery/actions/runs/5951888661/job/16142607426

meshkit `errorutil` is failing again due to the `unsafe.slice`, will be providing a fix sometime today

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Yay!

**Comment by suhail34** [comment]
Hey @nebula-aac if you are busy should i create a fix as the workflow is continuously failing

**Comment by suhail34** [comment]
I think we have to upgrade this package golang.org/x/sys in meshkit
