### ISSUE TITLE
[mesheryctl] system start command dysfunctional for latest kubectl version 

### ISSUE THREAD

**Issue by suhail34** [meshery/meshery#8590]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

For latest kubernetes version `mesheryctl system start -p kubernetes` is throwing error
![image](https://github.com/meshery/meshery/assets/77241166/78638cae-3fa8-4267-864b-591886a40384)

### Desired Behavior

mesheryctl should work with latest kubectl version

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by AugustasV** [comment]
I will take a look into that

**Comment by Philip-21** [comment]
> I will take a look into that

@AugustasV you still in or i should take it ?

**Comment by AugustasV** [comment]
@Philip-21 you can look into that

**Comment by suhail34** [comment]
https://github.com/meshery/meshery/pull/8602/files
This takes care of this

**Comment by leecalcote** [comment]
Fixed
