### ISSUE TITLE
[UI] Notification Center is missing Info tab.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8591]
### Current Behavior

<img width="558" alt="Screenshot 2023-08-24 at 4 01 10 PM" src="https://github.com/meshery/meshery/assets/7570704/a77082ed-29b5-4a72-86c2-186ee840bcc1">

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by kundan766** [comment]
can you assign me this issue ?

**Comment by Jougan-0** [comment]
@leecalcote found the issue its in
```meshery/ui/components/MesheryNotification.js```
Can you assign me this issue .

**Comment by Jougan-0** [comment]
@leecalcote found the issue its in
meshery/ui/components/MesheryNotification.js
Can you assign me this issue .
![image](https://github.com/meshery/meshery/assets/99207534/36d30e3e-4ba9-431f-a6dc-9b3307860c90)

**Comment by Jougan-0** [comment]
@leecalcote Can you assign me this issue .Fixed it locally on my device 
![image](https://github.com/meshery/meshery/assets/99207534/88b7030b-e0bf-4dcd-a053-39599e48272e)

**Comment by aabidsofi19** [comment]
Notification center is currently being migrated , so this is not needed now . @Jougan-0 @Jougan-0 we are migrating CBC's to functional components you might take a bite there :)
