### ISSUE TITLE
[UI] Misspelling in connections page

### ISSUE THREAD

**Issue by AugustasV** [meshery/meshery#8612]
### Current Behavior
There is misspelling on the connections page
![image](https://github.com/meshery/meshery/assets/7377334/a818aa63-863c-4d98-93ae-44a6e1956681)
It shows Server builsd SHA:
### Desired Behavior
Misspell fixed.

### Implementation

Commit changes, push to the fork, create a PR.

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vobanghia12** [comment]
@AugustasV Could I work on this ? Thanks

**Comment by tushh-codes** [comment]
Hey, is this issue still open ?
Can I work on this ?

**Comment by vobanghia12** [comment]
@tushh-codes I did my PR already
