### ISSUE TITLE
[UI] Change the `Dashboard` form class component to a functional component.

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8613]
### Current Behavior
Dashboard is a class-based component

### Desired Behavior
Make the dashboard a functional component

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Rajdip019** [comment]
@aabidsofi19 assign this to me.

**Comment by vobanghia12** [comment]
@Rajdip019 Could I work on this please ?

**Comment by kundan766** [comment]
@Rajdip019 please assign this issue to me

**Comment by Rajdip019** [comment]
Hey @kundan766 I am currently working on it. There are multiple open issues you can work on and as well as there are multiple components that need to be migrated from class to functional. You can work on them as well.

**Comment by Rajdip019** [comment]
@aabidsofi19 need some help on this from you. Have a lot of questions on how to handle some of the things while converting.

**Comment by aabidsofi19** [comment]
what are the issues you are facing

**Comment by Rajdip019** [comment]
> what are the issues you are facing

Basically there is a lot of states that are being are not defined as well as well there are some functions that uses self as a prop.

But those functions are used in other components and so on. If we can get on a call when ever you are free that will be a big help man.

**Comment by EraKin575** [comment]
@Rajdip019 will you coassign me this issue as we discussed?
