### ISSUE TITLE
[UI] K8s context switcher ping test is broken.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#8617]
### Current Behavior

When clicking `k8s` chip in context switcher no request is made to  perform connectivity/ping test.

https://github.com/meshery/meshery/assets/79860504/70ab0a3b-3d97-474b-968c-fdc6b06864f1

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ShailikaS** [comment]
I would like to work on this issue could you please assign it to me?
