### ISSUE TITLE
[UI] Infinite Loading on Pinging K8s Context

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#8623]
### Current Behavior

Currently, when I user clicks on k8s context in the context selector then user observe an infinite loading.

https://github.com/meshery/meshery/assets/73700530/bb051b34-a804-4b6c-846d-1fbc82d01b88

### Desired Behavior

Ensure this infinite loading is not observed and users should be able to ping it as they used to do.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
can you assign this to me?

**Comment by ShivangRawat30** [comment]
I would like to work on this issue.

**Comment by aabidsofi19** [comment]
@ShivangRawat30  assigning this to you , update me when its done

**Comment by leecalcote** [comment]
I'm bumping up the priority of this issue.

**Comment by leecalcote** [comment]
@ShivangRawat30, we're in need of an immediate fix.
