### ISSUE TITLE
[UI] Designs: Technology selection - Alphabetical sorting and support for multiple selections

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8642]
### Current Behavior
1. When publishing a design or adding metadata to a design, the long list of technology choices only allows the user to choose one technology at-a-time before the selector closes.

2. The list of technologies is not presented in alphabetical order.

### Screenshots

<img width="1520" alt="Screenshot 2023-09-01 at 4 52 04 PM" src="https://github.com/meshery/meshery/assets/7570704/fb234833-333a-4396-9087-a890feaa5a28">

 

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
please assign me this

**Comment by faishal882** [comment]
hey @leecalcote, i had forked the repo and ran it in local enviornment, since in meshery community issues are assigned, i would like to work on this issue, please assign this issue to me i am very interested to work on this issue

**Comment by ShivangRawat30** [comment]
I would like to work on this issue.

**Comment by Akhilbisht798** [comment]
Hey, I woruld like to work on this issue.

**Comment by kundan766** [comment]
hello @leecalcote can you assign me the issue

**Comment by ShatilKhan** [comment]
I would like to work on this issue.

**Comment by Yana-Gupta** [comment]
@leecalcote I will like to work on this issue. WIll you assign me.

**Comment by leecalcote** [comment]
Oh. my. word. I missed all of the other notifications. My apologies, everyone.

**Comment by Yana-Gupta** [comment]
@leecalcote Should I restrict users to selecting only one technology at a time, because now user is able to choose multiple selections simultaneously. Here's a screenshot for reference:

![image](https://github.com/meshery/meshery/assets/103108630/9a2568d5-2cb9-4416-aa61-85d55aff1b4d)

**Comment by Akhilbisht798** [comment]
@Yana-Gupta. No i  don't think we should restrict users to select only one technology at a time as this was why this issue was opened.

**Comment by leecalcote** [comment]
Yes, users should be allowed to select any number of technologies.

**Comment by Yana-Gupta** [comment]
Since user is able to choose multiple technologies as wanted should I just open the pull request to fix the sorting of the technologies.

**Comment by Yana-Gupta** [comment]
@leecalcote  Then should I just open the pull request for the second part of issue they are able to do so.

**Comment by leecalcote** [comment]
Yes
