### ISSUE TITLE
[UI] Connections: Status

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8657]
### Current Behavior
Column mismatch

### Screenshots/Logs

<img width="2328" alt="Screenshot 2023-09-05 at 7 54 48 AM 2" src="https://github.com/meshery/meshery/assets/7570704/af4c0b45-22e1-4075-80d5-7c2b257280fb">

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EraKin575** [comment]
i would like to work on this
