### ISSUE TITLE
[UI] Setup Prettier

### ISSUE THREAD

**Issue by nebula-aac** [meshery/meshery#8661]
In Meshery UI, we do not use `prettier`, which means our code looks different throughout each files.

Even though we have Next.js lint for its linting capabilities, the linting job is not doing all what it is supposed to do with the current rules on certain formatting. However, for a true formatter, we're not using prettier, and it would be great to set one up here in Meshery UI and also setup pre-commit hook for this.

Here is what being used in `Meshery Cloud`, but it can be improved.

Please note that making this change will create a large PR. So it would be necessary to check through all the files that will be formatted, and probably won't need to be formatted.

The referenced file is at https://github.com/layer5io/meshery-cloud/blob/master/ui/.prettierrc.yml

```yaml
arrowParens: avoid
tabWidth: 2
trailingComma: none
printWidth: 90
```

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by dhiraj0911** [comment]
Hey @nebula-aac, I'd like to work on this issue, can you assign this to me?

**Comment by Yana-Gupta** [comment]
@nebula-aac I would like to work on this issue. Would you assign me.

**Comment by ShatilKhan** [comment]
Hi @nebula-aac , I would like to understand this issue a bit more. What kind of changes are we looking for?
I have some front-end experience , if possible do assign this issue to me .

**Comment by aabidsofi19** [comment]
+1 @nebula-aac

**Comment by arpitghura** [comment]
Hey, I would like to work on this issue. Can you please assign it to me? @nebula-aac
