### ISSUE TITLE
Implement the use of Async await with axios for Api fetching

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#8671]
### Current Behavior

Currently we are using `dataFetch` component using `fetch` method for fetching data from apis which is ok but it is quite simple library and handling apis in such projects need robust error handling and rich feature library

### Desired Behavior

Use of async-await with axios is a good point to implement as we are using it in other repos consistently. 
It is feature rich library such as `request and response interceptors`,` automatic JSON parsing` and more.
It is also best for error handling and provides status code validation, making it easier to manage API errors.

### Implementation

Had replace dataFetch method with async await and had to move step by step so that none of pages crash

Simple example
```javascript
async function fetchData() {
  try {
    // Make a GET request using Axios
    const response = await axios.get('example api');
    
    // Assuming the API returns JSON data, you can access it as follows:
    const data = response.data;

    // Log the data
    console.log('API Response:', data);
  } catch (error) {
    // Handle any errors that may occur during the request
    console.error('Error:', error.message);
  }
}

// Call the async function to initiate the request
fetchData();
``` 

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Akhilbisht798** [comment]
Hey, I can do this. Can you assign me to this.

**Comment by CodesbyUnnati** [comment]
Hey, i am a new contributor, would like to work on this issue.

**Comment by sudhanshutech** [comment]
There would be many pages to implement. @EraKin575 you can start with few of them and partner with any other contributor to get this flow.
@Akhilbisht798 @CodesbyUnnati @ishashankmittal have you guys setup meshery in your system if yes you guys partner with @EraKin575 also

**Comment by sudhanshutech** [comment]
Are any of you guys following with this issue?

**Comment by Callitacodeitsmine** [comment]
@sudhanshutech i am new as a contributor and I would like to work on this issue. Can you co assign  it to me?

**Comment by Akhilbisht798** [comment]
@sudhanshutech hey i would like to partner with @EraKin575 to solve this issue.

**Comment by leecalcote** [comment]
@sudhanshutech, I believe that Meshery UI is transitioning away from Axios to RTK. Hopefully, we're not spinning peoples' wheels unnecessarily. @aabidsofi19 can you confirm?

**Comment by aabidsofi19** [comment]
Yup fellows we are moving towards use of rt-query  in meshery ui . So i believe any effort here will go in vain .

**Comment by leecalcote** [comment]
@lauquik, I apologize on @sudhanshutech's behalf. Let's get you engaged on another issue straight-away.

**Comment by Lauquik** [comment]
alright @leecalcote

**Comment by leecalcote** [comment]
@Lauquik have you jumped into the community Slack, yet? There are some new issues discussed there, too.

**Comment by sudhanshutech** [comment]
> @sudhanshutech, I believe that Meshery UI is transitioning away from Axios to RTK. Hopefully, we're not spinning peoples' wheels unnecessarily. @aabidsofi19 can you confirm?

oh yes i apologize , we don't need of axios or async when using rtk. I opened this issue thinking in meanwhile for use of better use case.
