### ISSUE TITLE
[UI] Convert `Index.js` and `settings.js` from class-based component to functional component

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8673]
### Current Behavior
`Index.js` and `settings.js` are class-based component

### Desired Behavior
`Index.js` and `settings.js` should be a class-based component

### Implementation
Here is a quick blog you can read : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Rajdip019** [comment]
@ShatilKhan you can contribute on this and make a PR against it.

**Comment by ShatilKhan** [comment]
Hey @Rajdip019,  Thank you so much for giving me the issue! 
Also thanks for providing the blog link.
You can go ahead and assign this to me.

**Comment by ShatilKhan** [comment]
Hey @Rajdip019 , I've made an intial PR, it's not complete yet. I'm still working on `settings.js`
I'd like you to check my code for `index.js` & let me know if it's alright.
