### ISSUE TITLE
[UI] Convert `MesherySettings.js` form Class-based to a functional component 

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8674]
### Current Behavior
`MesherySettings.js` is a Class-based component 

### Desired Behavior
`MesherySettings.js` should be a  Class-based component.

### Implementation
Here is a quick blog you can read : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Rajdip019** [comment]
@Cvr421 Comment on this issue to get assigned.

**Comment by EraKin575** [comment]
I would like to work on this issue!

**Comment by Cvr421** [comment]
ok @Rajdip019 /assign
