### ISSUE TITLE
[UI] Convert `smi_results.js` class-based components to functional component 

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8675]
### Current Behavior
`smi_results.js` is a class-based components.

### Desired Behavior
`smi_results.js` should be a functional component.

### Implementation
Here is a quick blog you can read : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Rajdip019** [comment]
@Layak Ali comment on this to get assigned. 

Checkout the blog to understand what to do. And to check if everything is working or not, you can see how the page was working before and it should work the same after the changes as well. 

Do let me know if you need any help with anything 😄

**Comment by ishashankmittal** [comment]
Hi, this is Shashank Mittal, I would like to contribute to this issue. Can you assign this to me? @Rajdip019

**Comment by Layak-Ali** [comment]
@Rajdip019 sure. Assign me this issue

@ishashankmittal  no you can't. You should comment on #8668 and select yourself a component if you want to contribute.

**Comment by EraKin575** [comment]
@Rajdip019 since @Layak-Ali  isn't  available right now, can you assign this to me so that I can quickly change this to functional component?

**Comment by Rajdip019** [comment]
Sure. That would be better @EraKin575

**Comment by EraKin575** [comment]
@Rajdip019  connections.js is not a react component and it is already a function. So changing smi_results.js is enough

**Comment by Rajdip019** [comment]
Got it.
