### ISSUE TITLE
[UI] Convert `/management/index.js` from class based functional component 

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8676]
### Current Behavior
`/management/index.js` is a class-based component. 

### Desired Behavior
`/management/index.js` should be a functional component 

### Implementation
Here is a quick blog that will help you get started with : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Rajdip019** [comment]
@sadamhussain-m comment on this issue I will assign you.

**Comment by ShivangRawat30** [comment]
I would like to work on this

**Comment by sadamhussain-m** [comment]
I would like to work on this issue.

**Comment by kundan766** [comment]
I want to work on this issue._

**Comment by dhiraj0911** [comment]
@Rajdip019
