### ISSUE TITLE
[UI] Convert `MesheryNotification` class-based component to functional component

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8677]
### Current Behavior
`MesheryNotification` is a class-based component.

### Desired Behavior
`MesheryNotification` is a functional component.

### Implementation
Here is a quick blog that will help you get started with : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rajdip019** [comment]
@ishashankmittal comment on the issue to get assigned.

**Comment by ishashankmittal** [comment]
@Rajdip019 assign me. Also let me know if there is a deadline.

**Comment by Rajdip019** [comment]
There is no such deadline. Do it when ever you are free. It's a small task might take 3 days max.

**Comment by Rajdip019** [comment]
@ishashankmittal are you still working on it?

**Comment by ishashankmittal** [comment]
> @ishashankmittal are you still working on it? 

Yes, i will make a PR by tomorrow.

**Comment by ishashankmittal** [comment]
@Rajdip019 Please review my PR #8809 .
