### ISSUE TITLE
[UI] Convert  `UserPreferences` and `preferences` form class-based to functional component  

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8687]
### Current Behavior
 `UserPreferences` and `preferences` are class-based  component  

### Desired Behavior
 `UserPreferences` and `preferences` should be a functional component  

### Implementation
Here is a quick blog that will help you get started with : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rajdip019** [comment]
@mukeshkuiry comment on this to get assigned.

**Comment by Lauquik** [comment]
@Rajdip019 can you assign this to me?

**Comment by mukeshkuiry** [comment]
> @mukeshkuiry comment on this to get assigned.

Yup!
Assign me @Rajdip019
