### ISSUE TITLE
Docs: Provide instructions on how to connect Prometheus and Grafana

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#869]
**Current State:**
The current set of documentation regarding Meshery's integration with Grafana and Prometheus (https://meshery.layer5.io/docs/mesh-management#grafana-and-meshery) needs enhanced.

**Desired State:**
There should be a separate section in the docs that covers how Meshery integrates with Grafana and Prometheus: 

- how users may connect and use these integrations 
- how to create a custom Prometheus query. 
- How to import Grafana boards and panels.
- How to create a custom Grafana panel. 

**Related issues:**
- https://github.com/layer5io/meshery/pull/856#issuecomment-616524906
- https://github.com/layer5io/meshery/issues/864

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@vijcheru you may want to knock this one out in the interim to changing the deployment behavior.

**Comment by DeveloperAspire** [comment]
Has this issue been resolved??

**Comment by vijcheru** [comment]
Lee, I will look into this and get back to you right away. I will give you
feedback as soon as possible.

**Comment by leecalcote** [comment]
@vijcheru thank you, thank you.
