### ISSUE TITLE
[mesheryctl] Permission denied error while deploying adapters in docker environment

### ISSUE THREAD

**Issue by zakisk** [meshery/meshery#8693]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

on Meshery Dashboard in Settings->Adapters when deploying an adapter getting below the `Permission denied` error in logs.
![problem](https://github.com/meshery/meshery/assets/49492007/9e971540-be02-4e97-a90b-b0e46afd6be1)

and the user is unable to deploy and connect to adapters.
### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Patish11** [comment]
> 
> 
> _See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._
> 
> 
> 
> on Meshery Dashboard in Settings->Adapters when deploying an adapter getting below the `Permission denied` error in logs.
> 
> ![problem](https://github.com/meshery/meshery/assets/49492007/9e971540-be02-4e97-a90b-b0e46afd6be1)
> 
> 
> 
> and the user is unable to deploy and connect to adapters.
> 
> ### Current Behavior
> 
> 
> 
> 
> 
> ### Desired Behavior
> 
> 
> 
> 
> 
> ### Screenshots/Logs
> 
> 
> 
> 
> 
> ### Environment
> 
> 
> 
> - Host OS: Mac Linux Windows
> 
> - Meshery Server Version: stable-v
> 
> - Meshery Client Version: stable-v
> 
> - Platform: Docker Kubernetes
> 
> 
> 
> ---
> 
> 
> 
> ### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
> 
> - 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
> 
> - 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
> 
> - ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
> 
> - ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
> 
> - 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
> 
>
