### ISSUE TITLE
[UI] K8s Context Switcher: Dark Mode Color

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8695]
### Current Behavior
The color of the K8s context switcher (the dropdown slider) matches that of the page's title bar.

### Desired Behavior
The color of the K8s context switcher (the dropdown slider) needs to be a shade slightly lighter than that of the page title background.

### Screenshots/Logs
<img width="285" alt="Screenshot 2023-09-08 at 5 25 08 PM" src="https://github.com/meshery/meshery/assets/7570704/05455ee3-cd0c-49fc-8cb3-a1b5f935d3d8">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by AkashKumar7902** [comment]
Hi @leecalcote 
Can you please assign me to this project ?

Thanks
Akash kumar

**Comment by ShailikaS** [comment]
@leecalcote I would like to work on it can you please Assign it?

**Comment by Vishrut19** [comment]
Hey! Is anyone working on it @leecalcote

**Comment by shadowrockzzz** [comment]
Hi @AkashKumar7902, do you need my help, as there seems to be a merge conflict? @leecalcote

**Comment by AkashKumar7902** [comment]
@shadowrockzzz yeah sure.

**Comment by shadowrockzzz** [comment]
Hi @leecalcote , Could you please add my name to the assignee list too... I am also working on it now
