### ISSUE TITLE
[UI] Position K8s Context Switcher Drawer under the page title bar

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8696]
### Current Behavior
Notice how the K8s context switcher drawer is on top of the green drop shadow from the page's title bar? Well, it is not supposed to be. 

### Desired Behavior
The K8s context switcher drawer should be at a layer lower such that the green drop shadow applies to this pulldown slider as well.

### Implementation
z-index...

### Acceptance Tests
1. The page bar's green drop shadow is visible on the K8s context switcher pulldown in both dark and light modes.

### Screenshot
<img width="285" alt="Screenshot 2023-09-08 at 5 25 08 PM" src="https://github.com/meshery/meshery/assets/7570704/1f5acec8-1c88-4d0d-9569-bc6f53b1a252">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ShailikaS** [comment]
Hey @leecalcote I would like to work on it.
just want some clarity that we need to perform changes to it.
![image](https://github.com/meshery/meshery/assets/107252411/d3827fe0-816d-4052-8675-0b52d8986e6d)
need to make it a Similar adjustment as drop k8 is?

**Comment by leecalcote** [comment]
@ShailikaS, thanks. Please rephrase your question.
