### ISSUE TITLE
[Performance] Failed to fetch profiles

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8713]
### Current Behavior

<img width="2172" alt="Screenshot 2023-09-11 at 8 49 07 AM" src="https://github.com/meshery/meshery/assets/7570704/7d44ffdf-f25f-4cef-9f60-13f410f3fb3f">

#### To Reproduce
1. Go to Performance page
2. Click on nothing

### Environment

- **Host OS:** Linux
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v0.6.138

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by EraKin575** [comment]
i would like to work on this

**Comment by cp-Coder** [comment]
I would like to work on this
