### ISSUE TITLE
[UI]Meshmap Icon doesn't move on hovering.

### ISSUE THREAD

**Issue by Modern-artist** [meshery/meshery#8717]
### Current Behavior
On the sidebar of Meshery when collapsed Meshmap Icon doesn't move on hover.

### Desired Behavior
The Meshmap Icon should move on hover similar to other icons.

### Screenshots/Logs
https://github.com/meshery/meshery/assets/90668597/ce6c3c23-62e7-499b-b7e5-f73ba2f75d8e

### Environment
- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Ishwar-Zatke** [comment]
@Modern-artist can you assign this task to me, I can look up to it?

**Comment by Modern-artist** [comment]
Go ahead @Ishwar-Zatke. @Jougan-0 you have to find a new issue.

**Comment by Jougan-0** [comment]
@Modern-artist is the issue fixed or can i have a go @Modern-artist

**Comment by siddanth-6365** [comment]
hey @Modern-artist @leecalcote can i work on this issue i think no one is working currently? or shouild i direclty edit and make pr

**Comment by Modern-artist** [comment]
@Ishwar-Zatke Any updates?

**Comment by ptdatta** [comment]
@Modern-artist @Ishwar-Zatke if you are not working on it. I would like to take it.

**Comment by Modern-artist** [comment]
@ptdatta go ahead.

**Comment by ptdatta** [comment]
@Modern-artist kindly review [this](https://github.com/meshery/meshery/pull/8989)
