### ISSUE TITLE
[UI] Convert `User.js` Class component to functional component

### ISSUE THREAD

**Issue by Mohith234** [meshery/meshery#8729]
### Current Behavior

`User.js` is a class-based component
### Desired Behavior

`User.js` should be a functional component

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Mohith234** [comment]
@aabidsofi19 Here is the issue

**Comment by sudhanshutech** [comment]
@Mohith234 is this a duplicate issue, @Rajdip019 can you confirm if this is done then we can close this issue

**Comment by Mohith234** [comment]
Hey @sudhanshutech this is not a duplicate one. I'm currently working on it

**Comment by sudhanshutech** [comment]
Okay sounds great @Mohith234
