### ISSUE TITLE
[UI] Convert `MesheryProgressBar.js` and `MeshAdapterConfigComponent.js` to functional component 

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8730]
### Current Behavior
MesheryProgressBar and MeshAdapterConfigComponent are class-based components. 

### Desired Behavior
MesheryProgressBar and MeshAdapterConfigComponent should be functional components. 

### Implementation

Convert all the Class-based components to new updated functional components. It is important here to convert a class-based component to a functional component you may need to convert some functions as well. Check if the function is used in other components or not.

Also, make sure to use the hooks while converting them. For example, you need to covert withNotify with useNotification hook. Please check if a hook for functional components is available and use that.

Here is a quick blog that will help you get started with : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rajdip019** [comment]
@suzy-g38 comment on this issue to get assigned.

**Comment by ishashankmittal** [comment]
If this issue is not fixed, i would like to contribute to this issue. Please assign @Rajdip019 @saurabh100ni . I previously converted MesheryNotification to functional.

**Comment by saurabh100ni** [comment]
@suzy-g38 do you have any updates about the issue ?

**Comment by suzy-g38** [comment]
@saurabh100ni I was going to create the pr but I am facing some issues regarding the linting error for the pull I took. That's why it is taking time.

Another thing I want to mention somebody else had already convert the MeshAdapterConfigComponent.js from class based to functional which was my work and I was assigned to the task. I found this when I took the pull some days ago. Still I made some changes in that component(very minor) which I found relevant in my logic.

**Comment by saurabh100ni** [comment]
I see,  it's cool if you are making progress with that ^ ^

**Comment by ishwar170695** [comment]
I checked the current codebase and both `MesheryProgressBar `and `MeshAdapterConfigComponent `are now implemented as functional components. This appears to satisfy the original goal of the issue. Unless there's remaining work not captured here, this looks ready to close.
