### ISSUE TITLE
[MeshModel] [UX]: Icon for Kubernetes Component - API Service

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#8732]
### Current Behavior
Meshery is a powerful platform that contains over [200 integrations](https://layer5.io/cloud-native-management/meshery/integrations) for managing cloud-native applications. MeshMap is an extension of Meshery that visually represents these integrations and components. Currently, most of the icons used in MeshMap have the default shape of a circle. However, to improve visual clarity and consistency, we need to design custom icons for MeshMap components.

### Desired Behavior
A new Icon for  **API Service** needs to be created. This issue calls for a volunteer to draft a new Icon.

### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer to the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes. 
1. Propose a specific shape, best-suited to visually represent the Component. Example - Deployment as a pentagon, DaemonSet as a skull icon etc.
3. Create two versions of the icon one is white and another one is colored
4.  Make a PR after adding the icon inside the [new-icon folder](https://github.com/meshery/meshery/tree/master/ui/assets/new-icons) present in the meshery repository
5. Provide the icon in SVG format
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- [MeshModel Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)
- 🖥 [MeshModel Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ShatilKhan** [comment]
I'd love to take this on, I've done logo & icon designs before. I use illustrator mostly.
Can you assign this one to me?

**Comment by ritiksaxena124** [comment]
Go ahead @ShatilKhan 👍. Assigning to you

**Comment by ShatilKhan** [comment]
Asking for suggestion
I found this icon on the official K8s icon pack,  since it's also API, can I just use it?
![api-128](https://github.com/meshery/meshery/assets/52494840/0980cd88-b329-426a-bbaa-06f4d0ede507)

**Comment by ritiksaxena124** [comment]
Closing this issue as the icon for API Service is already present. Thank you @ShatilKhan for taking this up. You can check other similar issues to work on
