### ISSUE TITLE
[meshmodels] [UX]: Icon for Meshmodel Prometheus Component - Thanos Ruler

### ISSUE THREAD

**Issue by Modern-artist** [meshery/meshery#8740]
### Current Behavior
Meshery is a powerful platform that contains over [200 integrations](https://layer5.io/cloud-native-management/meshery/integrations) for managing cloud-native applications. MeshMap is an extension of Meshery that visually represents these integrations and components. Currently, most of the icons used in MeshMap have the default shape of a circle. However, to improve visual clarity and consistency, we need to design custom icons for MeshMap components.
### Desired Behavior
A new Icon for  **Thanos Ruler** needs to be created. This issue calls for a volunteer to draft a new Icon.
### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer to the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes.
1. Propose a specific shape, best-suited to visually represent the Component. Example - Deployment as a pentagon, DaemonSet as a skull icon etc.
3. Create two versions of the icon one is white and another one is colored
4.  Make a PR after adding the icon inside the [new-icon folder](https://github.com/meshery/meshery/tree/master/ui/assets/new-icons) present in the meshery repository
5. Provide the icon in SVG format

**Comment by Ayush9026** [comment]
@Modern-artist  i will do this.

**Comment by saurabh100ni** [comment]
this task is completed now, Thanks to @ritiksaxena124 and @nwanduka
