### ISSUE TITLE
[MeshModel] [UX]: Icon for Kubernetes Component - Sidecar

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#8748]
### Current Behavior
Meshery is a powerful platform that contains over [200 integrations](https://layer5.io/cloud-native-management/meshery/integrations) for managing cloud-native applications. MeshMap is an extension of Meshery that visually represents these integrations and components. Currently, most of the icons used in MeshMap have the default shape of a circle. However, to improve visual clarity and consistency, we need to design custom icons for MeshMap components.

### Desired Behavior
A new Icon for  **Sidecar** needs to be created. This issue calls for a volunteer to draft a new Icon.

### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer to the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes. 
1. Propose a specific shape, best-suited to visually represent the Component. Example - Deployment as a pentagon, DaemonSet as a skull icon etc.
3. Create two versions of the icon one is white and another one is colored
4.  Make a PR after adding the icon inside the [new-icon folder](https://github.com/meshery/meshery/tree/master/ui/assets/new-icons) present in the meshery repository
5. Provide the icon in SVG format
6. Go to the [playground](https://playground.meshery.io/extension/meshmap) -> search for the component you are trying to design icon for and check whether the icon that you are designing is already present for another component or not if not then you can make a PR.
7. If you don't have access to Playground then you have to fill a [signup](https://play.meshery.io/) and get verified before you access the playground by the time you get access, you can go to [integrations](https://layer5.io/cloud-native-management/meshery/integrations) page in layer5.io site and search for the component and see whether an icon is already present or not.
8. Make sure icon for component is different from Model icon.
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- [MeshModel Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)
- 🖥 [MeshModel Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ShatilKhan** [comment]
Hey @ritiksaxena124 , I might need this icon for an issue I'm working on later. I've already made PR for another icon. I'll create this icon, so would bre great if you can assign me

**Comment by ShatilKhan** [comment]
Made a concept for this one
![image](https://github.com/meshery/meshery/assets/52494840/d3c1da09-dee4-4fdb-9e6b-59ac99ac7fbf)

**Comment by ritiksaxena124** [comment]
@ShatilKhan did you check whether an icon is already present for Sidecar or not in Kubernetes components repository?

**Comment by ShatilKhan** [comment]
PR is up @ritiksaxena124
