### ISSUE TITLE
[MeshModel] [UX]: Icon for Kubernetes Component - Pod Metrics

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#8749]
### Current Behavior
Meshery is a powerful platform that contains over [200 integrations](https://layer5.io/cloud-native-management/meshery/integrations) for managing cloud-native applications. MeshMap is an extension of Meshery that visually represents these integrations and components. Currently, most of the icons used in MeshMap have the default shape of a circle. However, to improve visual clarity and consistency, we need to design custom icons for MeshMap components.

### Desired Behavior
A new Icon for  **Pod Metrics** needs to be created. This issue calls for a volunteer to draft a new Icon.

### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer to the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes. 
1. Propose a specific shape, best-suited to visually represent the Component. Example - Deployment as a pentagon, DaemonSet as a skull icon etc.
3. Create two versions of the icon one is white and another one is colored
4.  Make a PR after adding the icon inside the [new-icon folder](https://github.com/meshery/meshery/tree/master/ui/assets/new-icons) present in the meshery repository
5. Provide the icon in SVG format
6. Go to the [playground](https://playground.meshery.io/extension/meshmap) -> search for the component you are trying to design icon for and check whether the icon that you are designing is already present for another component or not if not then you can make a PR.
7. If you don't have access to Playground then you have to fill a [signup](https://play.meshery.io/) and get verified before you access the playground by the time you get access, you can go to [integrations](https://layer5.io/cloud-native-management/meshery/integrations) page in layer5.io site and search for the component and see whether an icon is already present or not.
8. Make sure icon for component is different from Model icon.
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- [MeshModel Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)
- 🖥 [MeshModel Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Akshun-01** [comment]
Hey, I would like to work on this one. Can you assign this to me.

**Comment by ritiksaxena124** [comment]
go ahead @Akshun-01 👍

**Comment by Akshun-01** [comment]
Hi, I researched about 'Pod' and drafted some icons that we can use for it. Here are the prototypes, I would appreciate reviews and suggestions on this. 
@ritiksaxena124 @leecalcote 
![PodMetrics_Meshery-01](https://github.com/meshery/meshery/assets/93793691/6b38defd-44b0-45b1-b7bb-a94e096c52ea)
![PodMetrics_Meshery-02](https://github.com/meshery/meshery/assets/93793691/1dc59ba8-7dff-4597-adb6-23507eae8233)
![PodMetrics_Meshery-03](https://github.com/meshery/meshery/assets/93793691/43578843-e4db-4b3f-9fad-e24722d8283d)

**Comment by Akshun-01** [comment]
@ritiksaxena124 @leecalcote @Modern-artist 
guys I would really appreciate some feedback so that i can further work on this issue.

**Comment by leecalcote** [comment]
@Akshun-01, I'm pleased that you're contributing here. I think that you will ultimately be successful in creating a number of icons. Will you consider the following:

1. Switch to line chart as opposed to bar chart.
    - Perhaps, this bar chart is befitting for a different component. There are about ~2,000 components that need icons. So, if you remove two of the bars from the second draft, I think we'll have a winner - for a different component (not k8s pod metrics).
1. Increase padding between icon and shape. Actually, you can ignore the shape and simply focus on the icon.
1. Great icons are tend to be simple. Less is more. In this sense, the second and third drafts are best. The overlapping magnifying glass is difficult to discern (too complex).

**Comment by Akshun-01** [comment]
Sure, thanks for the feedback. I'll work on it and update here.
Also may I know which other component are you referring to in your first point.

**Comment by Akshun-01** [comment]
Hey, @leecalcote I worked on your suggestion and used a line chart to try to create a logo. 
![PodMetrics_Meshery-01](https://github.com/meshery/meshery/assets/93793691/5b4cb651-3369-4ce1-94c9-675b43d206b9)
![PodMetrics_Meshery-01](https://github.com/meshery/meshery/assets/93793691/85217f7d-1689-4651-9327-226612763ee6)

Also, we have the earlier iterations. How would you like me to proceed?
Any changes or feedback, or if you like anyone, would you like me to add it to the desired file?

**Comment by Akshun-01** [comment]
@ritiksaxena124 @leecalcote @Modern-artist any reviews on this issue ?

**Comment by leecalcote** [comment]
@Akshun-01, good work. I think you got it this time round. 👍

**Comment by leecalcote** [comment]
Crack open a PR at-will.
