### ISSUE TITLE
[meshmodels] [UX] : Icon for Meshmodel Postgres Component - Postgres Autoscaler

### ISSUE THREAD

**Issue by Modern-artist** [meshery/meshery#8750]
### Current Behavior
Meshery is a powerful platform that contains over [200 integrations](https://layer5.io/cloud-native-management/meshery/integrations) for managing cloud-native applications. MeshMap is an extension of Meshery that visually represents these integrations and components. Currently, most of the icons used in MeshMap have the default shape of a circle. However, to improve visual clarity and consistency, we need to design custom icons for MeshMap components.
### Desired Behavior
A new Icon for  **Postgres Autoscaler** needs to be created. This issue calls for a volunteer to draft a new Icon.
### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer to the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes.
1. Propose a specific shape, best-suited to visually represent the Component. Example - Deployment as a pentagon, DaemonSet as a skull icon etc.
3. Create two versions of the icon one is white and another one is colored
4.  Make a PR after adding the icon inside the [new-icon folder](https://github.com/meshery/meshery/tree/master/ui/assets/new-icons) present in the meshery repository
5. Provide the icon in SVG format

**Comment by Modern-artist** [comment]
Go ahead @Ayush9026

**Comment by Akshun-01** [comment]
Hey @ritiksaxena124 @Modern-artist @leecalcote 
I came up with a draft for this, please suggest changes or any suggestions!!

1.a
![image](https://github.com/meshery/meshery/assets/93793691/28f8fa22-cc67-4f31-8128-dbe28fa24143)
1.b
![image](https://github.com/meshery/meshery/assets/93793691/f9136381-6dd4-4f90-932f-2522c7840e14)

2.
![image](https://github.com/meshery/meshery/assets/93793691/d2d7098c-c165-4dbe-97f6-ab6d1341506e)

3.
![image](https://github.com/meshery/meshery/assets/93793691/8d567356-5ed4-4f45-bc3b-75eb7f82f43e)

**Comment by Akshun-01** [comment]
> 1.a. and 1.b. will do the trick, @Akshun-01. We'll need for these to be in SVG format.

yeah these are drafted in illustrator only, I just shared screenshot, because I only wanted feedback. I'll finalize them and export them in proper format. 

I like 1.b better, do you have any suggestions on these or some feedback?

**Comment by ritiksaxena124** [comment]
1.a looks good as 1.b has different curves than our other icon. @Akshun-01 Make the PR for 1.a icon.
