### ISSUE TITLE
[meshmodels] [UX] : Icon for Meshmodel Postgres Component - Postgres Database

### ISSUE THREAD

**Issue by Modern-artist** [meshery/meshery#8752]
### Current Behavior
Meshery is a powerful platform that contains over [200 integrations](https://layer5.io/cloud-native-management/meshery/integrations) for managing cloud-native applications. MeshMap is an extension of Meshery that visually represents these integrations and components. Currently, most of the icons used in MeshMap have the default shape of a circle. However, to improve visual clarity and consistency, we need to design custom icons for MeshMap components.
### Desired Behavior
A new Icon for  **Postgres Database** needs to be created. This issue calls for a volunteer to draft a new Icon.
### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer to the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes.
1. Propose a specific shape, best-suited to visually represent the Component. Example - Deployment as a pentagon, DaemonSet as a skull icon etc.
3. Create two versions of the icon one is white and another one is colored
4.  Make a PR after adding the icon inside the [new-icon folder](https://github.com/meshery/meshery/tree/master/ui/assets/new-icons) present in the meshery repository
5. Provide the icon in SVG format

**Comment by Ayush9026** [comment]
@Modern-artist i will solve this issue /assign.

**Comment by Akshun-01** [comment]
hey, I can try to work something up for this one... if it's free.

**Comment by Akshun-01** [comment]
Hey, @ritiksaxena124 @leecalcote 
while searching around for an icon for this one, I found these. Can we use one of them (tweaking a little if need) 
Open to suggestions!


![image](https://github.com/meshery/meshery/assets/93793691/30d86875-3004-420b-9cd9-9ffe3c436203)
![image](https://github.com/meshery/meshery/assets/93793691/fed1afd7-7f03-41ce-ae56-aa8695fe1d2f)
![image](https://github.com/meshery/meshery/assets/93793691/1caa96c1-b160-4445-a8d2-10217761a817)

**Comment by ritiksaxena124** [comment]
The first one looks good @Akshun-01 make the PR for that icon
