### ISSUE TITLE
[UI] Update styling of tabbed menu in validation modal

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#8760]
### Current Behavior
The tabbed menu in the validation modal needs to be changed. Currently, it looks like this 
![Screenshot 2023-09-13 233857](https://github.com/meshery/meshery/assets/51539117/d5268b91-9575-4617-bed8-c3610d3134a0)

### Desired Behavior
Convert the styling of the current tabbed menu in the validation modal (shown in the above image} with the tabbed menu using in meshery cloud
![image](https://github.com/meshery/meshery/assets/51539117/fbfc2aec-54d1-428e-92a0-cbd2b9b3a737)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Chadha93** [comment]
> Hey @ritiksaxena124 , this one seems like a good issue to get into Can I work on this one?

Sure @ShatilKhan

**Comment by ShatilKhan** [comment]
Sure! I'll finish up the other issues soon.

**Comment by mikenrowland** [comment]
@Chadha93 can I have this assigned to me? I currently don't have any assigned issue. Thanks.

**Comment by dhiraj0911** [comment]
@ritiksaxena124 can you assign this to me?

**Comment by siddanth-6365** [comment]
hey @ritiksaxena124 @leecalcote  can you please assign this to me or should i start working and raise pr ?

**Comment by ritiksaxena124** [comment]
@dhiraj0911 @siddanth-6365 Thank you guys but we follow first come first get assigned. So @mikenrowland go ahead you can start working on this issue 🙌. No sweat @dhiraj0911 and @siddanth-6365 we have multiple more issues and projects on which you guys can try your hands  😉

**Comment by mikenrowland** [comment]
Thanks @ritiksaxena124 I will get to it.

**Comment by leecalcote** [comment]
Thanks, @Aseem22 👍

**Comment by sudhanshutech** [comment]
this issue had been resolved, as we are using a stepper and from sistent. So if any enhancements needed then a issue in sistent make sense
