### ISSUE TITLE
[UI] WASM Filter Import Modal changing focus

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8763]
### Current Behavior
I can’t type a new name.
I can select a file to upload, but it never appears as a selected file.
As soon as I start to type a new config, the focus jumps somewhere else.

### Environment

- Browser: Safari
- Host OS: Mac 
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
PR fixes this issue #8787 #8825

**Comment by Yashsharma1911** [comment]
This issue is fixed
