### ISSUE TITLE
[CI] The error of CI step "Start Meshery server using mesheryctl" should be fixed

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery#8768]
### Current Behavior

Please look at these failed cases below. Most of repo's CI step "Start Meshery server using mesheryctl" were always failed. And this can make we feel not confident to merge PR. Even the PR is created by the Depedabot. So, we should fix it as soon as we can.

https://github.com/meshery/meshery-linkerd/actions/runs/6179418937/job/16774335746
https://github.com/meshery/meshery-istio/actions/runs/6110069448/job/16582493898
https://github.com/meshery/meshery-osm/actions/runs/6110073598/job/16582383944

### Desired Behavior

All the CI steps are passed. And the result should be as evidence to merge the PR.

### Acceptance Tests

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by Aisuko** [comment]
cc @leecalcote

**Comment by ptdatta** [comment]
Hey @Aisuko is it still open? If yes then can you please assign it to me?

**Comment by Aisuko** [comment]
Hi @ptdatta According to the comment here https://github.com/meshery/meshery-linkerd/pull/546#issuecomment-1719781467. Maybe this PR will be fixed by #8770. cc @theBeginner86

**Comment by ptdatta** [comment]
Yeah, I thought that it was fixed. Thank u @Aisuko
