### ISSUE TITLE
[UI]  Convert UserPreference.js From Class based to functional component 

### ISSUE THREAD

**Issue by Cvr421** [meshery/meshery#8777]
### Current Behavior

 UserPreference.js is a Class-based component.

 UserPreference - /ui/components/UserPreferences.js
### Desired Behavior

 UserPreference.js should be Functional component .

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Cvr421** [comment]
Hii @Rajdip019 could you please assign this issue to me . If anyone is not working on it . I have check their is no issue raised about   
this.

**Comment by siddanth-6365** [comment]
hi @leecalcote @Cvr421 can you please assign this to me ? or can i start and raise pr

**Comment by Cvr421** [comment]
@Rajdip019 This component has  already been converted into functional component a week ago . I am closing this issue . And please update as completed in this issue   #8668

**Comment by Rajdip019** [comment]
Done and dusted.

**Comment by Cvr421** [comment]
> Done and dusted. This is already updated on #8668

ok great
