### ISSUE TITLE
[UI] Convert `PromptComponent` class-based component to functional component

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8779]
### Current Behavior
PromptComponent is a class-based component.

### Desired Behavior
PromptComponents should be a functional component.

### Implementation
Convert all the Class-based components to new updated functional components. It is important here to convert a class-based component to a functional component you may need to convert some functions as well. Check if the function is used in other components or not.

Also, make sure to use the hooks while converting them. For example, you need to covert withNotify with useNotification, useRouter hook. Please check if a hook for functional components is available and use that.

Here is a quick blog that will help you get started with : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rajdip019** [comment]
@csengineer1990 comment on this to get assigned.

**Comment by Ishwar-Zatke** [comment]
Can you assign this to me?

**Comment by Rajdip019** [comment]
Hey @Ishwar-Zatke you can choose a component from here #8668

**Comment by Ishwar-Zatke** [comment]
Can I choose the PromptComponent from there, It is remaining i guess

**Comment by Rajdip019** [comment]
Hey, @@csengineer199 I am giving this component to @Ishwar-Zatke can you choose another component please?

**Comment by csengineer1990** [comment]
I chose promptComponent.js to convert because it's a little easier for me to work with. It's okay. I will find another component if there are any components left.
