### ISSUE TITLE
[Grammar Adjustment] Learn - content next to the "Get Early Access" form

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#8782]
**Current State:**

- Link to website: https://play.meshery.io/
- Currently, the text reads as follows: "Sign-up to receive a user account, entitled with perpetually free and full access the Playground environment."

**Desired State:**

- The suggested change is to add the word _to_ so it reads: "Sign-up to receive a user account, entitled with perpetually free and full access to the Playground environment."

---
**Screenshot**
![mesh](https://github.com/layer5io/layer5/assets/19821445/8619c001-0175-46d2-af9f-b472a55a56f6)

**Comment by VivekBaldha0712** [comment]
I would like to work on this issue

**Comment by ShatilKhan** [comment]
If you are having issues on meshery.io, I think the meshery.io repo would be a better place to raise this Issue.
[meshery.io repo](https://github.com/meshery/meshery.io)

**Comment by sandramsc** [comment]
> If you are having issues on meshery.io, I think the meshery.io repo would be a better place to raise this Issue. [meshery.io repo](https://github.com/meshery/meshery.io)

Thank you for the clarification!

**Comment by sandramsc** [comment]
Issue open in  [meshery.io](https://github.com/meshery/meshery.io)
