### ISSUE TITLE
[Grammar Adjustment] Learn - Frequently Asked Questions

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#8783]
**Current State:**

- Link to website: https://play.meshery.io/#signup-form
- Currently, the text in the 5th question reads as follows: "Are designs that I create in the Meshery Playground saved or will I look any work that I do in the playground?"

**Desired State:**

- The suggested change is to adjust the text so it reads: "Are designs that I create in the Meshery Playground saved or will I lose any work that I do in the playground?"

---
**Screenshot**

![mesh](https://github.com/layer5io/layer5/assets/19821445/3ab08b2b-85e7-4993-9f62-00a7812a19df)

**Comment by VivekBaldha0712** [comment]
I would like to work on this issue.. could you please assign it to me ?

**Comment by sandramsc** [comment]
Issue opened in [meshery.io](https://github.com/meshery/meshery.io/issues/)

**Comment by sandramsc** [comment]
Issue opened in [meshery.io](https://github.com/meshery/meshery.io/issues/)
