### ISSUE TITLE
[UI] WASM Filter Publish Modal mishaps

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8795]
### Current Behavior

https://github.com/meshery/meshery/assets/7570704/bc0a5f07-c525-40b1-b554-699e67a9f7d2

### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.6.139

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
I think this was same issue related to rerendering of rjsf modal this is already fixed, I checked it's working fine in playground, can you confirm where are you facing this problem in playground or locahost

https://github.com/meshery/meshery/assets/71271069/95efdb01-6687-46dc-ac7c-bef9be7a9f7e
