### ISSUE TITLE
[Docs] Improvement suggestion

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [meshery/meshery#8804]
### Current State

The file https://github.com/meshery/meshery/blob/master/docs/pages/concepts/architectural/architecture.md
has documentation issues (please correct me if I am wrong), I think the site URLs mentioned in the have not been hyperlinked with the site in markdown format.

### Desired State

Example,

[![Client architecture]({{ site.baseurl }}/assets/img/architecture/Meshery-client-architecture.svg)]({{ site.baseurl }}/assets/img/architecture/Meshery-client-architecture.svg)

This link should redirect me to the desired website mentioned but it is not being detected by markdown as a hyperlink.
Please respond to me on this and I will raise a PR on this.

Thank you.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by AYUSHd-GITHUB** [comment]
Hey Can I take this issue , I am good at documentation

**Comment by AYUSHd-GITHUB** [comment]
@ShubhamJagtap2000 please assign this issue to me

**Comment by ShubhamJagtap2000** [comment]
Hi @AYUSHd-GITHUB, let me pick this up, if anything, I will ping you here by then. Thanks.

**Comment by AYUSHd-GITHUB** [comment]
Okay , let me know if you need help

**Comment by vishalvivekm** [comment]
@ShubhamJagtap2000 
The source code located at https://github.com/meshery/meshery/blob/master/docs/pages/concepts/architectural/architecture.md serves as the content for https://docs.meshery.io/concepts/architecture page within the  [Meshery Docs](https://docs.meshery.io)

`{{ site.baseurl }}` is how you refer to the root directory in Jekyll filesystem and can be combined with other paths or filenames to generate absolute URLs for resources and assets like images and other files.

**Comment by leecalcote** [comment]
Please see - https://github.com/meshery/meshery/pull/8974#pullrequestreview-1653423029
