### ISSUE TITLE
[UI] Convert `MesheryAdapterPlayComponent` from class-based component to functional component

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8812]
### Current Behavior
`MesheryAdapterPlayComponent` is a class-based component.

### Desired Behavior
`MesheryAdapterPlayComponent` should be a functional component.

### Implementation
Convert all the Class-based components to new updated functional components. It is important here to convert a class-based component to a functional component you may need to convert some functions as well. Check if the function is used in other components or not.

Also, make sure to use the hooks while converting them. For example, you need to covert withNotify with useNotification, useRouter hook. Please check if a hook for functional components is available and use that.

Here is a quick blog that will help you get started with : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rajdip019** [comment]
Assigning you this. @toth2000

**Comment by kundan766** [comment]
can you assign me this issue ?

**Comment by toth2000** [comment]
I am working on this issue @kundan766
Please visit the link below to browse the list of available issues. If you are new to the community then consider looking for the 
`good first issue` tag.
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22good+first+issue%22

**Comment by ishwar170695** [comment]
I verified that `MesheryAdapterPlayComponent `is now a functional component using React hooks. This appears to satisfy the original request. Unless there are outstanding requirements, this issue looks ready to close.
