### ISSUE TITLE
[UI] Convert `MesheryPerformanceComponent` from class-based to functional component 

### ISSUE THREAD

**Issue by Rajdip019** [meshery/meshery#8814]
### Current Behavior
`MesheryPerformanceComponent` is a class-based component 

### Desired Behavior
`MesheryPerformanceComponent` should be a  functional component.

### Implementation
Convert all the Class-based components to new updated functional components. It is important here to convert a class-based component to a functional component you may need to convert some functions as well. Check if the function is used in other components or not.

Also, make sure to use the hooks while converting them. For example, you need to covert withNotify with useNotification, useRouter hook. Please check if a hook for functional components is available and use that.

Here is a quick blog that will help you get started with : [Link](https://www.digitalocean.com/community/tutorials/five-ways-to-convert-react-class-components-to-functional-components-with-react-hooks)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Rajdip019** [comment]
Just wanted to confirm. Do you have local up and running?

**Comment by subrajeet-maharana** [comment]
Currently no, will set it up soon.

**Comment by iArchitSharma** [comment]
@Rajdip019 Can i work on this!

**Comment by subrajeet-maharana** [comment]
> @Rajdip019 Can i work on this!

I am currently working on this. You could solve other issues in case you want.

**Comment by Rajdip019** [comment]
Hey @subrajeet-maharana , @iArchitSharma can work on this right now there are other issues you can tackle after setting up the local.

**Comment by subrajeet-maharana** [comment]
Local setup done.

**Comment by iArchitSharma** [comment]
> @iArchitSharma any updates?

I have started working on it, but my exams are going on, so I'll take some time

**Comment by captain-Akshay** [comment]
i would like to work on this @saurabh100ni

**Comment by ishashankmittal** [comment]
I would like to contribute to this issue, i previously converted MesheryNotification to functional, i think i can take up this issue. Please assign @Rajdip019

**Comment by saurabh100ni** [comment]
@iArchitSharma Best Wishes for your exams, and just so thinks go on hold , I'll be assigning this to @captain-Akshay .
And will be counting on you to take up new issue when you are done with exams

**Comment by saurabh100ni** [comment]
@ishashankmittal let's give chance to @captain-Akshay to have some experience too.
