### ISSUE TITLE
[UI] Scaling issues of icons in designs page

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#8817]
Scaling issues of icons for Designs page. Especially for action buttons.

![image](https://github.com/meshery/meshery/assets/73700530/81aadbfd-9f95-4433-95d0-8ac848b8d119)

<br>
Ensure that design icon scales well under different view sizes. Please make it consistent other icons under the Action Buttons.

Browser: Safari
Version: Latest

[Slack Message](https://layer5io.slack.com/archives/C023QGMSH8D/p1695048964361149)

**Comment by ShatilKhan** [comment]
Just curious, have you checked if this issue occurs in Chrome as well? 
Looks fairly simple to fix & shouldn't take time to fix up
if you want I can take a look at it @theBeginner86

**Comment by ShatilKhan** [comment]
I checked & found that The Action icons as you said aren't scaling properly, 
Mobile View:
![Screenshot 2023-09-18 231249](https://github.com/meshery/meshery/assets/52494840/15a95e8a-740f-417a-9869-8c76691ef8f6)

Web View (Screen Width 100%)
![Screenshot 2023-09-18 231317](https://github.com/meshery/meshery/assets/52494840/6f18d812-3173-477b-8292-2f9f42ff7503)

I have a suggestion, maybe we can add a Collapsible Action button?
That way it would create more space, We can add the Actions as list items on the collapsible button.

**Comment by abhisheksharma886** [comment]
Assign this to me, I'll take care of it

**Comment by ethan-byte** [comment]
We could work on it together, if more hands are still needed It could be assigned to me too

**Comment by ShatilKhan** [comment]
Great suggestion @ethan-byte 
I looked at the code last night. Looks like there's quite a bit that needs to be changed. We might need more hands to give it a proper look.

**Comment by Akshun-01** [comment]
If any extra help is needed, I too am free to work on it. 
@ShatilKhan we can discuss how to proceed with this and make it collapsable as you suggested or we can also make it a 2x2 layout for action buttons, that way they all would be visible at the same time, while also taking up less vertical space.

**Comment by ShatilKhan** [comment]
sounds good @Akshun-01 
I think we should discuss this on today's Dev Meeting, that we we'll understand it better.
What do you say?

**Comment by Akshun-01** [comment]
Yeah sounds good.

**Comment by ShatilKhan** [comment]
Me & @Akshun-01 have discussed this issue & are working on it.
@theBeginner86 can you assign it to the Two of us?

**Comment by ShatilKhan** [comment]
I have thought of making an initial mockup for the Actions button as a collapsible first

**Comment by theBeginner86** [comment]
> Me & @Akshun-01 have discussed this issue & are working on it.
> @theBeginner86 can you assign it to the Two of us?

Ohh, I see. 
Here you go....

**Comment by ShatilKhan** [comment]
All right just writing some updates here
We need to work in `ui\components\MesheryPatterns.js` to update the action icons @Akshun-01

**Comment by sudhanshutech** [comment]
the particular issue for which it has been opened has been solved. @ShatilKhan i guess we already has separate issue that consider the above points. Lets close this and you can work on that issue

**Comment by ShatilKhan** [comment]
Okay @sudhanshutech 
Make sure to assign me on the other issue please, so that I can work on it
