### ISSUE TITLE
[UI] Root UISchema incorrect: Labels and Annotations

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8819]
### Current Behavior
<img width="871" alt="Screenshot 2023-09-18 at 1 38 36 PM" src="https://github.com/meshery/meshery/assets/7570704/d212e43f-ddfc-48cf-b789-74c21988c4ff">

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
This is fixed
