### ISSUE TITLE
[Documentation] update the CONTRIBUTING.md with Issues & Pull Requests sections

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#8848]
Link to issue: [meshery](https://github.com/layer5io/layer5/issues/4932)

**Comment by sandramsc** [comment]
Hi, _(only if there's a need to do so in this case)_ can I have this issue assigned to me, please?

- currently working on this issue in the Meshery repo, creating a new issue in each repo mentioned so as to effectively maintain the procedure of creating an issue and thereafter a PR that closes it.

**Comment by saurabh100ni** [comment]
let's discuss this item on today's website meeting,
please add this agenda in the docs: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk
