### ISSUE TITLE
[UI] Issue in Selection in Navigation Menu

### ISSUE THREAD

**Issue by suzy-g38** [meshery/meshery#8871]
### Current Behavior
Currently, when an option in the navigation bar is selected, it remains highlighted even if another option is subsequently chosen.

### Desired Behavior
The desired functionality is that when an option is clicked, it should remain highlighted only until a different option is selected.

### Screenshots/Logs
![image](https://github.com/meshery/meshery/assets/62666287/60fba2fc-fa8a-4c4f-bca7-e855137f5971)

### Environment

- Browser: Chrome Edge Firefox
- Host OS: Linux
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Jougan-0** [comment]
I fixed the issue sending it in the next pr

**Comment by suzy-g38** [comment]
@saurabh100ni @Jougan-0 I think there is some miscommunication....As far as I checked, there was no issue related to navigation and I confirmed it from @leecalcote....he told me to raise the issue. So I would like to work on it.

**Comment by Jougan-0** [comment]
@suzy-g38  i am sorry didn't knew the issue was not assigned so i thought it was open so sent the fix @leecalcote can you please help us out

**Comment by Jougan-0** [comment]
@suzy-g38 as you can see in the image the submenu is not closing once you click on other option so the issue was in toggle

**Comment by suzy-g38** [comment]
> @suzy-g38 i am sorry didn't knew the issue was not assigned so i thought it was open so sent the fix @leecalcote can you please help us out

@Jougan-0  it's okay....as you have already raised the pr so it's fine.

**Comment by aabidsofi19** [comment]
@suzy-g38  , @Jougan-0   please guyz ,  only work on  the issues that are assigned to you . this prevents  potential conflicts and back and forth .   We assign issues on first come first serve basis so all you need is to comment and wait till a maintainer assigns it to you .  

While you wait for getting a issue assigned , you can add your valuable feedback and reviews on open pr's . it counts as a worthy contribution and no permission needed there  .

**Comment by aabidsofi19** [comment]
@saurabh100ni  //

**Comment by Jougan-0** [comment]
@aabidsofi19 it's my fault i knew but didn't asked I'll ask and wait for the issue to be assigned I am sorry @aabidsofi19

**Comment by suzy-g38** [comment]
> @suzy-g38 , @Jougan-0 please guyz , only work on the issues that are assigned to you . this prevents potential conflicts and back and forth . We assign issues on first come first serve basis so all you need is to comment and wait till a maintainer assigns it to you .
> 
> While you wait for getting a issue assigned , you can add your valuable feedback and reviews on open pr's . it counts as a worthy contribution and no permission needed there .

Okay got it....thanks @aabidsofi19

**Comment by aabidsofi19** [comment]
Thanks for your sincerity ,  guys .  There are lots of open issues to chew through 😉
