### ISSUE TITLE
[UI] Dynamic display of Connections metadata

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8879]
@aabidsofi19 @senali-d @Yashsharma1911 can we move away from this hardcoding, knowing that every connection type will have different metadata properties and interpret dynamically instead?

_Originally posted by @leecalcote in https://github.com/meshery/meshery/pull/8840#discussion_r1331924693_

**Comment by leecalcote** [comment]
@senali-d FYI

**Comment by nik132-eng** [comment]
@leecalcote  can you please assign me this issue? 

if I am thinking properly I have to remove that scrollbar which is not suitable for ui?

**Comment by aabidsofi19** [comment]
we are now managing the metadata dynamically
