### ISSUE TITLE
Meshery Filters Catalog description formatting is not right

### ISSUE THREAD

**Issue by dhamkirti21** [meshery/meshery#8882]
### Current Behavior

Currently the description that opens on clicking the filters has not a right formatting for reading purpose. 
also, multiple times " ** " is used to define titles that look odd.
-- Catalog-link: https://meshery.io/catalog
![image](https://github.com/meshery/meshery/assets/78336507/b5387261-8fb0-4a09-bcea-3b1c1be1016d)

also, when i open one of the  ByteVerse shecodes blog that also has a bad formatting
-- ByteVerse Blog link: https://meshery.io/catalog/deployment/76c9f25a-fb01-48d6-9f07-4c476c6104f9/
![image](https://github.com/meshery/meshery/assets/78336507/369ef998-a839-4a7f-adcb-81be18a427f8)

### Desired Behavior

I have added a suggestion that how should it look like in mockup. 
Formatting for the description should be readable not like cramping all the words in the paragraphs.  
keeps the description spacious.

### Screenshots / Mockups

https://github.com/meshery/meshery/assets/78336507/b5f1c5a0-859b-42f4-b61b-0a6171d07dbc

---
### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Narottamchy** [comment]
please assign this issue to me

**Comment by dhamkirti21** [comment]
Yaa you can assign it to @Narottamchy

**Comment by dhamkirti21** [comment]
I will work on it
