### ISSUE TITLE
the recent discussion section UI doesn't perform well in light mode.

### ISSUE THREAD

**Issue by dhamkirti21** [meshery/meshery#8883]
### Current Behavior

Links for the recent discussion in Meshery catalog details at the end of the page looks very bad in light color.

Reproduce Steps: 

- Head over to this link: https://meshery.io/catalog/deployment/76c9f25a-fb01-48d6-9f07-4c476c6104f9/#:~:text=Recent%20Discussions%20with%20%22meshery%22%20Tag
- then turn on light mode 

### Desired Behavior

For the Convention if you want to highlight a link or button in light mode you use dark color to highlight 
so we need a good design for it. 

### Screenshots/Logs

![image](https://github.com/meshery/meshery/assets/78336507/e299caa1-4c20-42e0-942c-bcdc66558b64)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Narottamchy** [comment]
please assign this issue to me

**Comment by abhijeetgauravm** [comment]
hey @dhamkirti21 this issue belongs to [meshery.io](https://github.com/meshery/meshery.io) repo.
