### ISSUE TITLE
[Server] Unable to ping MeshSync or Meshery Broker

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8895]
### Current Behavior
<img width="1255" alt="Screenshot 2023-09-23 at 7 06 19 PM" src="https://github.com/meshery/meshery/assets/7570704/362a99a0-66f1-42f9-8924-99161e6839ea">

### Expected Behavior
Click either chip and have hit respond positively.

### Environment

- **Host OS:** Mac
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v0.6.145
- **Meshery Client Version:** stable-v0.6.145

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by jamieplu** [comment]
Has this been fixed already?

**Comment by MUzairS15** [comment]
Yes @jamieplu this has been fixed.
