### ISSUE TITLE
[UI] Visualize button Overlap with Notification Tab in MeshMap 

### ISSUE THREAD

**Issue by ShatilKhan** [meshery/meshery#8905]
### Current Behavior

When the notifications tab is clicked, the visualize button overlaps the tab

### Desired Behavior

Visualize button shouldn't overlap.
We can make fix the overlapping or just make the notification Tab window smaller.

### Screenshots/Logs

https://github.com/meshery/meshery/assets/52494840/ea443fe7-83d7-4f58-a98d-0ba3f4bfd016

### Environment

- Browser: Chrome 
- Host OS: Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform:  Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by hemantmm** [comment]
Hi, @Ghat0tkach  can I work on this issue?

**Comment by ShailikaS** [comment]
Hi, @ShatilKhan  I would like to work on that.

**Comment by Alone-Y154** [comment]
Hi @ShatilKhan , I would like to work on this Issue, can you assign it to me
