### ISSUE TITLE
[Docs] Update docs regarding general info on `linting`/`formatting` in `ui`

### ISSUE THREAD

**Issue by nebula-aac** [meshery/meshery#8906]
### Current State
We just moved to use `prettier` with `eslint` for linting and formatting purposes.

However, the docs needs to be updated to reflect this for informational purposes.

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by akhilender-bongirwar** [comment]
@nebula-aac, I would like to work on this issue.

**Comment by Mohith234** [comment]
Go ahead @akhilender-bongirwar
