### ISSUE TITLE
[UI] 3 columns vs 2 column layout in wider browsers

### ISSUE THREAD

**Issue by hamza-mohd** [meshery/meshery#8909]
### Current Behavior
Currently, in the filters and applications, pages, when the user has a very large screen size, the number of columns in the great represented, is quite small, but could be made to a higher column count.

### Desired Behavior
I'm not sure if this is desired behavior or not, so I am raising it up as a potential UX concern.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ahsanfarooq210** [comment]
I want to work on this issue
