### ISSUE TITLE
[Docs] Tracking important topics across Discussion Forums 

### ISSUE THREAD

**Issue by ash-kamrip** [meshery/meshery#8910]
### Current State
Topics that might be deemed important  enough to be considered to be added to FAQs from the discussion forums are missing currently. ( to be precise we don't really track them)

### Desired State
I want discussions to be added into FAQs so that the no. of repetitive topics or questions asked on support forum is reduced.

**Comment by Zubiii333** [comment]
I would like to work on it. First could you please elaborate the issue? Like which topics do you think that should be added to FAQs?

**Comment by vishalvivekm** [comment]
@ash-kamrip 
Will you join today's websites call at 5:30 PM IST to discuss this Issue.
I've added it as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)
