### ISSUE TITLE
[Docs] typo 'visitior' 

### ISSUE THREAD

**Issue by abhijeetgauravm** [meshery/meshery#8911]
### Current State
![image](https://github.com/meshery/meshery/assets/65087356/9e400400-c568-403c-8c6d-2c7e21e27a75)
![image](https://github.com/meshery/meshery/assets/65087356/9feb43a5-bcfd-44b6-86b9-a1aece213db0)

typo 'visitior' in publishing a design page [here](https://docs.meshery.io/extensions/publishing-a-design) and sharing a design page [here](https://docs.meshery.io/extensions/sharing-a-design).

### Desired State
It should be 'visitor'

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Sumit21kumar** [comment]
can i fix?
