### ISSUE TITLE
[Server] Unable import latest Jaeger Helm Chart

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8917]
### Current Behavior
The following error message is shown upon attempting to import the latest Jaeger Tracing Helm Chart.
<img width="1013" alt="Screenshot 2023-09-25 at 1 00 46 PM" src="https://github.com/meshery/meshery/assets/7570704/dd48430e-0186-4a78-81fd-6da12cdca28b">

Chart: https://github.com/jaegertracing/helm-charts/releases/download/jaeger-0.71.14/jaeger-0.71.14.tgz

I am also not able to import via `mesheryctl`:

```
mesheryctl app import -f https://github.com/jaegertracing/helm-charts/releases/download/jaeger-0.71.14/jaeger-0.71.14.tgz -s helm
Error: Invalid application source type due to wrong type/passing
```

### Expected Behavior
Meshery should support late versions of Kubernetes and charts that depend upon late versions.

### Environment

- **Host OS:** Mac
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v.6.147
- **Meshery Client Version:** stable-v0.6.147

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@nebula-aac, do you know where this error is sourced from? Is there a dependent library that needs upgrading?

**Comment by nebula-aac** [comment]
> @nebula-aac, do you know where this error is sourced from? Is there a dependent library that needs upgrading?

Researching
