### ISSUE TITLE
[UI] dropdown menu button anomaly

### ISSUE THREAD

**Issue by captain-Akshay** [meshery/meshery#8921]
### Current Behavior
the cluster selection drop down menu have a select all button that doesn't work the way it's supposed to be 
### Desired Behavior
checking the select all should select all the cluster listed 
and unchecking the button should remove all the checked item!!

### Screenshots/Logs
[Screencast from 2023-09-26 08-07-06.webm](https://github.com/meshery/meshery/assets/59491379/dd802e71-4289-4994-a539-fdfae0c832a7)

### Environment

- Browser: Firefox
- Host OS: Linux 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by captain-Akshay** [comment]
I would like to work on this issue

**Comment by EraKin575** [comment]
@captain-Akshay  do you have meshery running locally?

**Comment by captain-Akshay** [comment]
Yes  @EraKin575

**Comment by captain-Akshay** [comment]
Yes  @EraKin575

**Comment by EraKin575** [comment]
here you go @captain-Akshay
