### ISSUE TITLE
[Docs] Multiple Typo in Contributing to Meshery UI

### ISSUE THREAD

**Issue by captain-Akshay** [meshery/meshery#8922]
### All the typo:-

GraphQL API Referencee: There's an extra "e" in "Referencee." It should be "Reference."

Addionally: Should be corrected to "Additionally."

duplicity: It should be "duplication."

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by captain-Akshay** [comment]
i would like to work on this issue

**Comment by captain-Akshay** [comment]
@EraKin575 
ScreenShot:-

![Screenshot from 2023-09-26 11-32-18](https://github.com/meshery/meshery/assets/59491379/f3c48e64-c65e-4f2b-8856-bd842e625fe4)

![Screenshot from 2023-09-26 11-32-40](https://github.com/meshery/meshery/assets/59491379/3ebd2ec7-c6d8-4f81-8932-9632f1bdf118)

![image](https://github.com/meshery/meshery/assets/59491379/184865db-9f78-4f69-ae04-1ed2d446bf8f)

**Comment by nwanduka** [comment]
I think “duplicity” is correct in the context. But the rest are definitely typos. Good eye @captain-Akshay .

**Comment by captain-Akshay** [comment]
@nwanduka thanks!

**Comment by VivekBaldha0712** [comment]
i would like to work on this issue. Can you please assign it to me
