### ISSUE TITLE
[Docs] Typo in Contributing to Meshery's End-to-End Tests using Cypress 

### ISSUE THREAD

**Issue by captain-Akshay** [meshery/meshery#8923]
## Typos

- ocassionally: Should be corrected to "occasionally."
- keep in mind that if running integration tests: Add a comma after "keep in mind."
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by captain-Akshay** [comment]
please assign this to me

**Comment by EraKin575** [comment]
Always include a screenshot

**Comment by captain-Akshay** [comment]
@EraKin575 sorry again!

![image](https://github.com/meshery/meshery/assets/59491379/65b54391-e10f-4393-b18e-120d73b8b8e2)

![Screenshot from 2023-09-26 11-26-05](https://github.com/meshery/meshery/assets/59491379/2a10bfaf-9e31-412d-b923-8928a0bfd6a8)

**Comment by nwanduka** [comment]
You’re right. Occasionally is spelt wrong. But for the second text you pointed out, I think it’s is correct. There shouldn’t be a comma between “keep in mind” and “that”.

You’re doing a good job spotting these typos.
