### ISSUE TITLE
[Docs] Typo in Contributing to Meshery Server

### ISSUE THREAD

**Issue by captain-Akshay** [meshery/meshery#8924]
### Typo
- "for the any issues" should be "for any issues."
- "Addionally" should be "Additionally."
- "explicitely" should be "explicitly."
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by captain-Akshay** [comment]
please assign this one to me !

**Comment by EraKin575** [comment]
Please upload a screenshot too!

**Comment by captain-Akshay** [comment]
@EraKin575 sorry i looked some other similar typo issue there were no screenshot so i did the same.My apologies!
here:-

![server1](https://github.com/meshery/meshery/assets/59491379/58556943-fe31-4a7b-b128-33023f00a0ab)
![server2](https://github.com/meshery/meshery/assets/59491379/607c074d-f194-4b1d-b563-4c99513fe3e9)

**Comment by EraKin575** [comment]
go ahead @captain-Akshay

**Comment by EraKin575** [comment]
@Ayush9026 please dont submit PR's for issues which arent assigned to you. It can lead to potential conflicts
