### ISSUE TITLE
Refactor Models Retrieval Handling to Reduce Latency and Improve Code Organization

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#8929]
### Current Behavior
At present, within our codebase, we are managing the acquisition of models through a single central handler defined in [component_handler.go](https://github.com/meshery/meshery/blob/master/server/handlers/component_handler.go#L38). Specifically, this handler encompasses the retrieval of mesh models and necessitates a loop through all components in order to obtain the identity model names. Regrettably, this approach has led to excessive utilization of the component handler across various use cases, which, in turn, has given rise to latency-related issues.

### Desired Behavior
Each meshmodel database table should have its dedicated handler, residing in a separate file. This segregation will not only improve code organization but also help mitigate latency problems

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
// @MUzairS15 @theBeginner86

**Comment by dhiraj0911** [comment]
@Yashsharma1911 can you assign it to me?
To address this issue we need to create separate handlers for each meshmodels and each handler in separate file for a better organization

**Comment by theBeginner86** [comment]
> @Yashsharma1911 can you assign it to me?
> To address this issue we need to create separate handlers for each meshmodels and each handler in separate file for a better organization

Thanks @dhiraj0911 for taking the initiative. This is kind of an urgent issue to fix the performance of the MeshModel Model handlers so that the Meshery users are able to publish their designs to catalog. So, I created quick fix.

Would you please have a look at the other open issues: https://github.com/meshery/meshery/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee? You can tag me on the one you'd like to work on and I'll assign you the issue.

**Comment by dhiraj0911** [comment]
@theBeginner86 👍

**Comment by theBeginner86** [comment]
> @theBeginner86 👍

You are most welcome to help review the above PRs 🙌

**Comment by dhiraj0911** [comment]
Thanks 🤝
