### ISSUE TITLE
[UI] Width Fix for Suboptions in Navbar

### ISSUE THREAD

**Issue by Abbhiishek** [meshery/meshery#8932]
### Current Behavior

Navlinks on the navbar are uneven. Checkout the below screenshot, the option has a logo and text however the logo and text doesn't maintain the same width in every option. Hovering over them can highlist the issue.

<img width="998" alt="image" src="https://github.com/meshery/meshery/assets/86338762/34950a1a-3218-438d-a9d8-1a8e0c9ca31d">

****
<img width="1018" alt="image" src="https://github.com/meshery/meshery/assets/86338762/d8eaa562-6f17-482e-8372-ed32400d3eeb">

### Desired Behavior

We can make the logo and text hold certain width so that all the option has uniform width.

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by EraKin575** [comment]
this issue is for websites page. Head over [here](https://github.com/meshery/meshery.io)

**Comment by Abbhiishek** [comment]
Thanks @EraKin575 for redirecting! Appreciated 😄
