### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshery#8942]
### Current State
Current meshery docs for contributing to Documentation page has some Installation issue kindly add a button for redirecting people to the discuss forum 
https://discuss.layer5.io/t/setting-up-meshery-docs-operating-system-ubuntu-23-04/3766

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by GLADI8R** [comment]
Hi @Jougan-0, can you assign me this issue?

**Comment by saurabh100ni** [comment]
Let's discuss this Item in tomorrow's website call, 
please add it as your agenda if you would: 
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by arunkarthicknm** [comment]
Can anyone close this issue please as it's resolved! :)

**Comment by Jougan-0** [comment]
@arunkarthicknm please ask in general on slack pranav or lee could help you with this
