### ISSUE TITLE
[UI/UX] Enhancement of Pattern & Filter Cards for Improved UI/UX

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#8954]
### Current Behavior
Currently, Meshery uses a card-based design to display patterns and filters. While this design has served its purpose well, as we continue to add more features and actions related to these patterns and filters cards, it's becoming increasingly challenging to accommodate all these functionalities within the existing card layout. 

This issue is primarily related to the user interface (UI) and user experience (UX) aspects of our application.

### Expected Behavior
We expect to enhance the design of these cards to effectively incorporate and streamline all the actions and features associated with patterns and filters.

The objective is to provide a more user-friendly and intuitive UI/UX for our application, ensuring that users can easily access and interact with the various functionalities while maintaining a cohesive and visually appealing design. 

### Screenshots/Logs
![Screenshot 2023-09-28 at 4 16 09 PM](https://github.com/meshery/meshery/assets/71271069/2204ff5c-f6da-428b-8548-ff050456f682)

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
// @ritiksaxena124

**Comment by ShatilKhan** [comment]
We were talking about something similar in #8817 
I have made a figma file on it. I have another contributor assisting me. would it be ok to work on? As these issues seem pretty much same?
Here's the figma file :
https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=20876-5611&mode=design&t=RYbHBVDpjDsNYd9R-0

**Comment by Yashsharma1911** [comment]
Good to know @ShatilKhan did we make any progress with mockup?

**Comment by ptdatta** [comment]
Please assign it to me.

**Comment by ShatilKhan** [comment]
@Yashsharma1911,  I'm working on it, I'll upload the mockup by tonight

**Comment by sudhanshutech** [comment]
@Rexford74 can you provide your thoughts or want to give a try

**Comment by Yashsharma1911** [comment]
Closing as completed
