### ISSUE TITLE
[Extensions] Unprivileged user loads published design; receives errors

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8961]
### Current Behavior
Signing in as an Org Admin and loading [this published design](http://localhost:9081/extension/meshmap?design=66f483b2-5ca5-457a-b149-46a661468c34), I receive the following unfriendly error messages upon attempts to change the design.

### Desired Behavior
Non-owners of published designs should be required to Clone designs before they are able load onto the canvas.

### Screenshots/Logs
<img width="1037" alt="Screenshot 2023-09-28 at 6 50 47 PM" src="https://github.com/meshery/meshery/assets/7570704/0c4edcf0-ef2f-4103-a809-3831bde36fbe">

### Environment

- Meshery Server Version: stable-v0.6.151

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@Yashs911, did you recently modify this logic, by chance?

**Comment by leecalcote** [comment]
@aabidsofi19 fyi

**Comment by Lakhaninawaz** [comment]
@leecalcote can you help after run ui in my local system how to get tokens and show it working ui. i click on get tokens so error show. 500 internel server error show

**Comment by theBeginner86** [comment]
> @leecalcote can you help after run ui in my local system how to get tokens and show it working ui. i click on get tokens so error show. 500 internel server error show

You might want to have a look at docs: https://docs.meshery.io/guides/mesheryctl/authenticate-with-meshery-via-cli

**Comment by Lakhaninawaz** [comment]
Ok. Thanks

**Comment by Lakhaninawaz** [comment]
> > @leecalcote can you help after run ui in my local system how to get tokens and show it working ui. i click on get tokens so error show. 500 internel server error show
> 
> You might want to have a look at docs: https://docs.meshery.io/guides/mesheryctl/authenticate-with-meshery-via-cli

Ok thanks

**Comment by theBeginner86** [comment]
This has been fixed in latest meshery-extension [release](https://github.com/layer5labs/meshery-extensions-packages/releases/tag/v0.6.153-2).
