### ISSUE TITLE
Relocate binding.rego

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#8991]
### Current Behavior
https://github.com/meshery/meshery/blob/master/binding.rego should not be in the root folder of the repo.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Shiva953** [comment]
can I take up this Issue?

**Comment by MUzairS15** [comment]
@Shiva953 Thanks for volunteering.

@leecalcote That particular policy was not used anywhere and was missed in the final cleanup before merging the PR.

**Comment by MUzairS15** [comment]
I have deleted the file
