### ISSUE TITLE
Twitter logo needs to be updated to X

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshery#8994]
### Description
in the footer of [docs.meshery.io](https://docs.meshery.io/) twitter's old logo is needs to be updated to X

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by joshijoe05** [comment]
Hello, I would like to work on this, Please assign to me

**Comment by saurabh100ni** [comment]
Go On @joshijoe05 😎🚀

**Comment by infiniteltd** [comment]
I would love to to take up this issue.

**Comment by saurabh100ni** [comment]
@infiniteltd there's similar issue on https://GitHub.com/meshery/meshery/issues you can work on that, as this issue is already assigned.

**Comment by saurabh100ni** [comment]
I updated that, now it will take you to the right place

**Comment by akagami-harsh** [comment]
i can see the pr is not merged yet , can i give it a try

**Comment by leecalcote** [comment]
Thanks, @akagami-harsh. 👍

**Comment by akagami-harsh** [comment]
thanks @leecalcote for assigning me, i have made some changes. can you please review it
