### ISSUE TITLE
[Docs] Create a "Contributing to Meshery.io site" page

### ISSUE THREAD

**Issue by shashank-kavli** [meshery/meshery#8996]
### Current State
In [Meshery Docs](https://meshery.io), the contributing and set-up guides can be found at : in https://docs.meshery.io/project/contributing page.
Currently, there's no "Contributing to Meshery.io site" page 

### Desired State
- Create and list a `Contributing to Meshery.io Site` page at https://docs.meshery.io/project/contributing that includes a setup (covering prerequisites, required dependencies, and steps to run the site locally) as well as a contributing guide.
 **Inspiration** - https://docs.meshery.io/project/contributing/contributing-docs
- Next, include a link to the page in [meshery/meshery.io/CONTRIBUTING.md](https://github.com/meshery/meshery.io/blob/master/CONTRIBUTING.md)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@shashank-kavli is there anything further that you would like to add to this description?

**Comment by vishalvivekm** [comment]
@leecalcote 
I included a description of the ask.

**Comment by shashank-kavli** [comment]
Thanks for the description @vishalvivekm , sorry i was away so couldnt respond earlier.
Btw ive make a guide and would love your opinion should i tag you on slack?

**Comment by nakulbh** [comment]
can i work on this ?

**Comment by Koushik1311** [comment]
Hello, I would like to work on this. I tried to set up Meshery on my local machine but I couldn't set up Meshery Documentation on my local machine can you guide me?

I can set up this one
![image](https://github.com/meshery/meshery/assets/120767897/df7742d3-dd1c-4393-9c65-0724b94fe200)

But not this one
![image](https://github.com/meshery/meshery/assets/120767897/5aa1c29a-c65b-4ec6-9f6a-5eea54b85d38)

**Comment by vishalvivekm** [comment]
> Thanks for the description @vishalvivekm , sorry i was away so couldnt respond earlier. Btw ive made a guide and would love your opinion should i tag you on slack?

@shashank-kavli 
will you join today's websites meeting ( starting in 6 minutes) to get feedback on your progress so far?
meeting link: https://meet.layer5.io/websites

**Comment by shashank-kavli** [comment]
> > Thanks for the description @vishalvivekm , sorry i was away so couldnt respond earlier. Btw ive made a guide and would love your opinion should i tag you on slack?
> 
> @shashank-kavli will you join today's websites meeting ( starting in 6 minutes) to get feedback on your progress so far? meeting link: https://meet.meshery.io/websites

sorry @vishalvivekm i was inactive for the last couple of weeks as i was not at home. is it okay if i join the meet next monday
