### ISSUE TITLE
[UI] Consolidate or remove duplicate `ErrorBoundary.js`

### ISSUE THREAD

**Issue by nebula-aac** [meshery/meshery#9002]
There are two `ErrorBoundary.js` files.

- `/ui/components/General/ErrorBoundary.js`
- `/ui/components/ErrorBoundary.js`

Need to decide where to keep one of the file in, and remove the other file.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by toth2000** [comment]
Can I look into this?

**Comment by nebula-aac** [comment]
@toth2000 Sure, but you will need to reach out in Slack to find out who was the last person to create the extra `ErrorBoundary.js` file and see what needs to be done to resolve this.

**Comment by toth2000** [comment]
@nebula-aac Okay, I will ask about it on Slack.

**Comment by coder12git** [comment]
@toth2000 any update on this? Are you still working on it?

**Comment by coder12git** [comment]
@nebula-aac I would like to work on this

**Comment by toth2000** [comment]
@coder12git I am sorry, I have been busy with some exam preparation. If you would like, you can take the issue and close it by making a PR.

**Comment by coder12git** [comment]
@sudhanshutech  assign this to me :)

**Comment by saurabh100ni** [comment]
Go on 😎🚀 @senali-d

**Comment by coder12git** [comment]
> Go on 😎🚀 @senali-d

It's `coder12git` @saurabh100ni
