### ISSUE TITLE
[Server] Controller Mutex Crash

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9003]
### Current Behavior
Meshery Server crashes when the Vizualizer extension is opened. 

[server-log.txt](https://github.com/meshery/meshery/files/12787952/server-log.txt)

### Environment

- **Host OS:** Mac
- **Platform:** local
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Shiva953** [comment]
According to me, this is the problematic snippet that seems to be causing the error

https://github.com/meshery/meshery/blob/5d79e68f0ba5acc77f7c002d3fd6c7026897894f/server/models/meshery_controllers.go#L127C1-L152C2

Not sure about the exact cause though.

**Comment by leecalcote** [comment]
@Shiva953 thank you for this. 👍
