### ISSUE TITLE
[Docs] Removing repeated sentence in Meshery Docs

### ISSUE THREAD

**Issue by aadityadike** [meshery/meshery#9017]
### Current State
Upon inspecting the documentation at [docs.meshery.io/project/contributing](https://docs.meshery.io/project/contributing), I noticed an opportunity to improve clarity and reduce repetition.

Under the "Prerequisites for building Meshery in your development environment:" section, the sentence "`golangci-lint` should be installed if you want to test Go code, for MacOS and linux users." is repeated twice.

### Desired State
Removing one of the duplicate sentences would help streamline the documentation and make it easier for contributors to follow

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Lymah123** [comment]
Hi, can I work on the issue?

**Comment by sandramsc** [comment]
@aadityadike I have assigned this to you.

**Comment by leecalcote** [comment]
Fixed by  #9047
