### ISSUE TITLE
[UI] Data Table: Misbehaving filter option

### ISSUE THREAD

**Issue by captain-Akshay** [meshery/meshery#9019]
### Current Behavior
[Screencast from 2023-10-04 20-08-02.webm](https://github.com/meshery/meshery/assets/59491379/bc902d50-f736-4e1b-979b-15c9ef7271d1)

### Desired Behavior
All filter options should be able to be clicked at all time 

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by captain-Akshay** [comment]
i would like to work on this @saurabh100ni

**Comment by saurabh100ni** [comment]
You got it @captain-Akshay 😎🚀
