### ISSUE TITLE
[Extensions] Cloud: Change Role count to Design count

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9020]
### Current Behavior

<img width="352" alt="Screenshot 2023-10-04 at 11 26 50 AM" src="https://github.com/meshery/meshery/assets/7570704/69e0e923-9864-42bf-979e-3a8cecb8f929">

### Desired Behavior
If the design count can be hyperlinked to see a list of that users designs, that would be good. A link to their User Profile with the Design tab in focus sounds about right.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by senali-d** [comment]
Completed.
