### ISSUE TITLE
Change heart color to Keppel green in dark mode

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#9022]
### Current Behavior
The heart in the footer in Meshery UI is in gray color in dark mode

![image](https://github.com/meshery/meshery/assets/51539117/7c02a5a8-15f6-4fce-99dc-745d2f345fb4)

### Desired Behavior
Change the color of the heart in the footer in Meshery UI to Keppel green

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by VivekBaldha0712** [comment]
I would like to work on it

**Comment by Neel-07** [comment]
hello @ritiksaxena124 , can this issue be assigned to me. I want to work on this issue.

**Comment by thepranavanand** [comment]
I am new to this project and I would like to work on it.

**Comment by Samaresh-Das** [comment]
I would like to work on this issue @ritiksaxena124

**Comment by fadkeabhi** [comment]
Hey @ritiksaxena124 I would like to work on this issue.

**Comment by ritiksaxena124** [comment]
Thank you all, the issues are assigned in chronological order so @VivekBaldha0712 you can go ahead and start working on this issue. 
No worries @Neel-07 @thepranavanand @Samaresh-Das @fadkeabhi  we have many good first issues that might interest you. Select from the number of [projects](https://layer5.io/community/handbook/repository-overview) we have to contribute.

**Comment by VivekBaldha0712** [comment]
@leecalcote will you please assign this issue

**Comment by leecalcote** [comment]
Thanks! Assigning in chronological order…
