### ISSUE TITLE
[UI] Performance: Table vs Grid icons need swapped on activity toolbar

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9023]
### Current Behavior
In the Performance Management section (http://<meshery-server/performance/profiles) When you are viewing a table, the activity toolbar shows the table icon, and when you are reviewing a great view, the activity toolbar shows the grid icon. 

### Desired Behavior
However, the states of these icons should be reversed.

### Screenshots/Logs
<img width="433" alt="Screenshot 2023-10-04 at 8 36 08 PM" src="https://github.com/meshery/meshery/assets/7570704/4430cb10-b0ae-4a0e-abe4-bca34e176557">

### Environment

- Browser: Chrome
- Host OS: Mac 
- Meshery Server Version: stable-v0.6.153
- Platform: Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by akhilender-bongirwar** [comment]
Hey @leecalcote, I want to work on this. Please assign me.

**Comment by akhilender-bongirwar** [comment]
@leecalcote @sudhanshutech , could you please add hacktoberfest label to this issue.

**Comment by leecalcote** [comment]
@akhilender-bongirwar the repo has the hacktoberfest topic and is all the is needed.
