### ISSUE TITLE
[UI] Settings Revise Models Browser

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9029]
### Current Behavior
The existing "MeshModels Browser" needs an uplift.

### Implementation
1. Rename to menu tab to "Models".
2. Implement two views as captured in the mockups below.
3. Use https://mui.com/x/react-tree-view/

### Acceptance Tests
1. Users can navigate between models.
2. Users can search for models or components.
4. Users can collapse/expand and scroll through registered models.

### Mockups
![MeshModel Browser](https://github.com/meshery/meshery/assets/7570704/6351dd78-b9fe-427c-9a1c-47db53b12a89)

![Wireframe - 1](https://github.com/meshery/meshery/assets/7570704/c638f282-7d3b-48ea-a1b2-a8be491e2ddc)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by VivekBaldha0712** [comment]
I would like to work on it

**Comment by shadowrockzzz** [comment]
Hi, 

I have recently joined here. I have past experience with React.js. Can I take this issue and make the mentioned changes?

**Comment by ptdatta** [comment]
@leecalcote Please assign it to me.

**Comment by leecalcote** [comment]
Hi @shadowrockzzz, thanks so much for volunteering. This particular issue is missing the "help wanted" and "good first issue" label, because it's a bit of a doozy. 

Thank you for volunteering! Let's get another issue assigned to you. Here's a very helpful search that lists all issues with the "[help wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+)" label assigned. I encourage to you inquire on issues even if they are assigned, if this issues don't have recent activity. A well-intended contributor might be accidentally squatting on an issue that they are no longer working on.

**Comment by shadowrockzzz** [comment]
Yes, thank you for the response. I will do as you say.
