### ISSUE TITLE
Fix: The console log error

### ISSUE THREAD

**Issue by ptdatta** [meshery/meshery#9030]
### Current Behavior
For every request in meshery cloud prints the `prevProps.k8sConfig ` object

### Screenshots/Logs
![image](https://github.com/meshery/meshery/assets/94271200/927a421f-a4ab-426d-a66d-5e6af8dbf168)

### Environment
- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ptdatta** [comment]
@yash37158 @ritiksaxena124 Please assign this to me.

**Comment by Adaminite** [comment]
@ptdatta Hi. Is this issue still being worked on? I could take a look at it.

**Comment by coder12git** [comment]
@leecalcote @aabidsofi19 here is that issue that i was talking in slack, would like to work on it.

**Comment by aabidsofi19** [comment]
@coder12git  here you go

**Comment by sandramsc** [comment]
I have some clarification questions regarding this issue...

1. What exactly is the desired output, taking a look at the PR (solution) which comments the error message out it's not particularly clear on my end why it's an issue that _every request in meshery cloud prints the prevProps.k8sConfig object_, perhaps updating the "Desired output" section in the description might clear this up?

2. In light of "first come first serve" on issue assignment, how come @ptdatta wasn't assigned the issue first when they asked for it first? -- just incase the issue assignment happens elsewhere as well i.e via Slack...
