### ISSUE TITLE
[Docs] Broken Links in MeshMap Documentation

### ISSUE THREAD

**Issue by ATREAY** [meshery/meshery#9032]
### Current State
In the MeshMap documentation's introduction, there are two links provided for "Designer" and "Visualizer." Unfortunately, these links do not redirect to any valid destinations. The documentation page where this issue is observed can be found here: https://docs.meshery.io/extensions/meshmap

### Desired State
To resolve this issue, we need to update the links in the documentation to direct users to the respective "Designer" and "Visualizer" sections of the Layer5 website.

**I would like to work on this issue if it is considered valid and within the scope of improvements needed for MeshMap documentation.**

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by nakulbh** [comment]
hey @ATREAY  can i work on it

**Comment by ATREAY** [comment]
hey @saurabh100ni, can I work on this issue if it is valid?

**Comment by saurabh100ni** [comment]
Go On @ATREAY 😎🚀

**Comment by ATREAY** [comment]
Hey @saurabh100ni, I've made the neccessary updates. Could you kindly review them when you have a moment?
