### ISSUE TITLE
[UI] Settings: Hide Credentials Menu

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9042]
### Current Behavior
The Credentials menu item (with the fingerprint icon) and the whole Credentials page is not ready for use and shouldn't be available to users.

### Desired Behavior
Comment out its display in the list of menu tabs.

<img width="1316" alt="Screenshot 2023-10-07 at 6 21 22 PM" src="https://github.com/meshery/meshery/assets/7570704/3a34e078-5ead-4656-8a58-2333c9ef800f">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by avinashji1302** [comment]
Please assign me this

**Comment by shreshthgoyal** [comment]
hey @leecalcote I would like to work on this issue. Can you please assign this to me ? 
Thanks!

**Comment by omesh-omg** [comment]
hello @leecalcote what is the update on this 👀 if no one is working on this I can work on it ?

**Comment by leecalcote** [comment]
Thank you very much for volunteering. I missed @avinashji1302's previous comment.

This issue was just addressed in this PR - https://github.com/meshery/meshery/actions/runs/6582981348
