### ISSUE TITLE
[UI] Settings: Rename "MeshModel Browser" to "Registry"

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9043]
### Request

1. Change the menu label and the menu id/name/anchor to "Registry"
2. Find and update any references to this anchor/tab throughout the rest of Meshery UI.

<img width="1307" alt="Screenshot 2023-10-07 at 6 22 44 PM" src="https://github.com/meshery/meshery/assets/7570704/aaec0b59-c70c-444c-9627-645301c9b525">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Adaminite** [comment]
@leecalcote I can try to attempt this issue
