### ISSUE TITLE
 [Link attachment] README.md - Cloud Native Lifecycle Management 

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#9050]
**Current State:**

- Link to website: https://github.com/meshery/meshery/blob/master/README.md
- Currently, the link in the README.md under sub-heading **Cloud Native Lifecycle Management** looks as follows: [catalog of curated design templates] (https://meshery.io/catalog)

**Desired State:**

- The suggested change is to adjust the link to properly attach to the _catalog of curated design templates_ text so it looks as follows: [catalog of curated design templates](https://meshery.io/catalog)

**Comment by MeenuyD** [comment]
Hello @sandramsc I would like to work on this issue can you please assign it to me.

**Comment by sandramsc** [comment]
@MeenuyD I have assigned this to you.
