### ISSUE TITLE
[Docs] Update AKS Documentation for Service-level Port Forwarding

### ISSUE THREAD

**Issue by aboobakersiddiqr63** [meshery/meshery#9055]
Issue Description:
The current documentation for AKS (Azure Kubernetes Service) in the Supported providers section contains instructions for port-forwarding that involve a complex process of identifying and selecting a specific pod. This process can be streamlined and improved to enhance user-friendliness.

Proposed Change:

Introduction of Service-level Port Forwarding: The documentation should be updated to include clear instructions on how to perform service-level port forwarding. This change will simplify the process for users and eliminate the need to manually identify and select individual pods.

### Current State
export POD_NAME=$(kubectl get pods --namespace meshery -l "app.kubernetes.io/name=meshery,app.kubernetes.io/instance=meshery" -o jsonpath="{.items[0].metadata.name}")
kubectl --namespace meshery port-forward $POD_NAME 9081:8080

### Desired State
kubectl port-forward svc/meshery --namespace meshery  9081:9081

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by shubhankar-mern** [comment]
@aboobakersiddiqr63  assign this to me

**Comment by aboobakersiddiqr63** [comment]
@shubhankar-mern contributor needs to review the proposal and should assign, I would request the assignee to assign this task to @shubhankar-mern :)

**Comment by leecalcote** [comment]
Thank you, gents. 👍
