### ISSUE TITLE
[UI] Dark/Light Mode Button Alignment in Navbar

### ISSUE THREAD

**Issue by ATREAY** [meshery/meshery#9060]
### Current Behavior
Currently, the dark/light mode button on the Meshary website is not properly aligned with the other elements in the navbar. 

### Desired Behavior
To enhance the aesthetics and user experience of the website, I propose aligning the dark/light mode button in the navbar with the other elements. This alignment will create a more visually appealing and cohesive appearance for site visitors.

### Screenshots/Logs
![light mode](https://github.com/meshery/meshery/assets/66585295/ed17b737-a641-40ae-9310-fe500c98c4dc)

![dark mode](https://github.com/meshery/meshery/assets/66585295/bbb4a546-5259-4e24-90dc-74531d61f762)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Layak-Ali** [comment]
@Ghat0tkach @leecalcote can you assign me this issue please? I can confirm that it is wrongly aligned.

**Comment by leecalcote** [comment]
Thanks! I believe this is a duplicate issue. Please confirm, @ATREAY

**Comment by leecalcote** [comment]
https://github.com/meshery/meshery.io/pull/1394

**Comment by leecalcote** [comment]
@ATREAY, no sweat. Better that you raise the issue and have it be a duplicate, than not raise the issue at all.
