### ISSUE TITLE
[UI] Error message is not properly shown

### ISSUE THREAD

**Issue by aboobakersiddiqr63** [meshery/meshery#9061]
### Current Behavior
While enabling the flush operator in the meshery I was thrown error but the error is not properly shown in the UI 

### Desired Behavior
Error should clear to the user of what is failing and the response should be precise for him to navigate to resolve the problem

### Screenshots/Logs

![image](https://github.com/meshery/meshery/assets/144536269/01670add-cc54-4436-a1b8-0d8a19056f8f)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by dhiraj0911** [comment]
@aboobakersiddiqr63 i would like to work on this issue

**Comment by Shiva953** [comment]
I would like to take up this issue
