### ISSUE TITLE
[Docs] Adding helm installation as a seperate readme and giving hyperlink to supported platform 

### ISSUE THREAD

**Issue by aboobakersiddiqr63** [meshery/meshery#9067]
### Current State
Currently docs for different cloud providers are different like helm installation is proposed for AKS same can proposed for GKE, EKS, kubernetes too.

### Desired State
Making a seperate readme for helm installation and adding the hyperlink to the supported platform so we can reduce the duplication of sentences and which help in better understanding and readability of the users

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by saurabh100ni** [comment]
Thanks for raising the PR, let's Discuss this in the Meshery Development Call today,
Please add this as an agenda in the Doc  : [Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit) 

The meeting is in 15 minutes.
you can check about meeting on [Community Calender](https://layer5.io/community/calendar)
