### ISSUE TITLE
[Docs] Add description of Docs capability for "alerts"

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9094]
### Current State
Meshery Docs has a common include file "alert.html" which offers formatting for notes, warnings, and other informational callouts to readers. This feature isn't documented in the Docs Contributing guide, though.

### Desired State
Enhance https://docs.meshery.io/project/contributing/contributing-docs which a section describing this feature and include an example.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MeenuyD** [comment]
Hello @leecalcote I would like to work on this issue can you please assign it to me.

**Comment by leecalcote** [comment]
Thanks, @MeenuyD. Yes, let's get you set up for success. Will you do me a favor and give a quick summary of the use of the `alert.html` include?

**Comment by MeenuyD** [comment]
This helps in maintaining a cohesive and uniform style throughout the documentation, making it more readable and user-friendly.

**Comment by leecalcote** [comment]
@MeenuyD, spot on. Will you take a moment to speak to your proposed implementation?

**Comment by leecalcote** [comment]
@MeenuyD I didn't realize that you have outstanding work to complete in this open PR - https://github.com/meshery/meshery/pull/9045. Please sign-off on your commits and confirm the eslint changes.

**Comment by Debaditya-Som** [comment]
@leecalcote , is this issue open? 
If it is open then i would love to work on this :)

**Comment by goldfishdolphin** [comment]
Is someone working on it?

**Comment by goldfishdolphin** [comment]
Do you want to work on this issue @Debaditya-Som?

**Comment by Debaditya-Som** [comment]
> Do you want to work on this issue @Debaditya-Som?

Yes surely, I would love to work on this issue if no one lese is working on it
