### ISSUE TITLE
[mesheryctl] Rework existing `mesheryctl` command ref docs script

### ISSUE THREAD

**Issue by alphaX86** [meshery/meshery#9104]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

Currently, the docs for the `mesheryctl` commands are auto-generated using Cobra library's inbuilt functionality which enables to generate pages from variables in the program. However, the functionality is limited and can't perform below functions:
- Protection from overwrite (if new content is manually added from page instead of program) 
- Command reference table generation when the script is run
 Because of this, the action is not fully automated and not reliable due to data overwrite possibility 

### Desired Behavior
Allow contributors to offer additive documentation to that of the auto-generated documentation without it getting overwritten and without having to edit Golang in order to enhance the docs. Instead, they can stay within markdown and add additional context, usage, examples, screenshots, videos, and so forth.

### Implementation
A simple approach to achieving this is to create a START and END designation - a section of each CLI reference page as being untouched by the auto-generated script. See the mockup for a simple designation that would work very well.

### Acceptance Tests
1. No loss of hand-written docs. The logic inside the script needs to be updated to touch anything between this section and the start of the next section. 
1. Meshery Docs needs to be updated to include instructions in the Contributing page for Meshery CLI. 
1. Each CLI reference page should have an Info alert that informs contributors of this framework and points them to the Meshery CLI contributing doc for an explanation.

### Mockup
```
<!-- ###########################################################################

                 START OF MANUAL DOCUMENTATION
IT IS SAFE TO ADD ADDITIONAL USAGE AND EXAMPLES BELOW THIS LINE.
MORE INFO: https://docs.meshery.io/project/contributing/contributing-cli

############################################################################ -->

### Sample Usage 

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

\`\`\`
mesheryctl version --config docker-compose.yaml
\`\`\`

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

![screenshot of meshery](https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/meshery/meshery-logo-dark-text-side.png)

<!-- ###########################################################################

                 END OF MANUAL DOCUMENTATION

############################################################################ -->

```

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

**Comment by aboobakersiddiqr63** [comment]
@alphaX86 @leecalcote I am having an suggestion. Before making modifications to the auto-generated documentation using Cobra, can we check whether any manual comments or content exist in the code (we can add comments before and after the manually added . If such comments exist, the tool should prevent the overwriting of manually added content. After other modifications are complete, these manual comments or content can be re-added to the documentation.

**Comment by aboobakersiddiqr63** [comment]
@alphaX86 @leecalcote is the approach valid ?

**Comment by leecalcote** [comment]
@aboobakersiddiqr63 yes, in fact, this sort of approach is ideal and relatively simple to create. It is ideal, because individuals who are offering additive documentation to that of the auto-generated documentation won't need to edit golang in order to enhance the docs. Instead, they can stay within markdown and add additional context, usage, examples, screenshots, videos, and so forth.

A simple approach to achieving this is to create a START and END designation - a section of each CLI reference page as being untouched by the auto-generated script. A simple designation like the following will work very well:

```
<!-- ###########################################################################

                 START OF MANUAL DOCUMENTATION
IT IS SAFE TO ADD ADDITIONAL USAGE AND EXAMPLES BELOW THIS LINE.
MORE INFO: https://docs.meshery.io/project/contributing/contributing-cli

############################################################################ -->

### Sample Usage 

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

\`\`\`
mesheryctl version --config docker-compose.yaml
\`\`\`

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

![screenshot of meshery](https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/meshery/meshery-logo-dark-text-side.png)

<!-- ###########################################################################

                 END OF MANUAL DOCUMENTATION

############################################################################ -->

```

The logic inside the script needs to be updated to touch anything between this section and the start of the next section.

**Comment by leecalcote** [comment]
Ok, I have updated the issue's description.

**Comment by leecalcote** [comment]
@zakisk fyi

**Comment by aboobakersiddiqr63** [comment]
@leecalcote can I work on it ?
