### ISSUE TITLE
[Docs] Fix Missing Meshery Server Version

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#9108]
### Current State
There is a workflow to test and publish docs for Meshery Adapters. Each adapter's E2E tests refers this [workflow](https://github.com/meshery/meshery/blob/master/.github/workflows/test_adaptersv2.yaml) file. 
Currently, its missing the Meshery version in one of the columns of compatibility matrix.

Example: 

![Screenshot 2023-10-14 at 10 15 10 PM](https://github.com/meshery/meshery/assets/73700530/d86d72df-4603-44be-9fe6-cbfb9871f3e0)

### Desired State
Ensure the correct Meshery Server is asserted properly in the published docs.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Debaditya-Som** [comment]
@theBeginner86 , if granted I would love to work on this issue?

**Comment by AbhijithGanesh** [comment]
I'd like to work on this. I've experimented with workflows before

**Comment by theBeginner86** [comment]
> @theBeginner86 , is this issue still open? If granted I would love to work on this issue

Yes, its open.
Here you go @Debaditya-Som 🚀

**Comment by theBeginner86** [comment]
> I'd like to work on this. I've experimented with workflows before

@AbhijithGanesh would you please have a look at other open issues?
Here's a list to pick from: https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Alayer5io+user%3Ameshery+no%3Aassignee+user%3Alayer5labs+user%3Aservice-mesh-performance

**Comment by leecalcote** [comment]
@Debaditya-Som how are you progressing here?

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som how are you progressing here?

Yes I am working on this issue, but I am having problem while accessing the server versions of each updates respectively

**Comment by theBeginner86** [comment]
> > @Debaditya-Som how are you progressing here?
> 
> Yes I am working on this issue, but I am having problem while accessing the server versions of each updates respectively

@Debaditya-Som 
Would you be joining today's CI call to discuss your progress? Here are the meeting minutes: https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit

**Comment by Debaditya-Som** [comment]
> > > @Debaditya-Som how are you progressing here?
> > 
> > 
> > Yes I am working on this issue, but I am having problem while accessing the server versions of each updates respectively
> 
> @Debaditya-Som Would you be joining today's CI call to discuss your progress? Here are the meeting minutes: https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit

Yes surely, I'm looking forward to join the meeting

**Comment by leecalcote** [comment]
@Debaditya-Som any progress here?

**Comment by leecalcote** [comment]
@AbhijithGanesh will you carry this forward?

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som how are you progressing here?

I am currently working on issue: #9094 , it would be better if you could assign @AbhijithGanesh for this issue

**Comment by theBeginner86** [comment]
@AbhijithGanesh can we discuss you progress today on CI call?
Meeting details available here: https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit

**Comment by AbhijithGanesh** [comment]
I'm sorry I skipped the CI call probably, I'll attend the next CI call

**Comment by theBeginner86** [comment]
> I'm sorry I skipped the CI call probably, I'll attend the next CI call

@AbhijithGanesh we are meeting in ~30 mins. Would you be around to share your progress?
Meeting details available here: https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit

**Comment by vishalvivekm** [comment]
@theBeginner86 can you please assign the issue to me?

**Comment by theBeginner86** [comment]
@AbhijithGanesh do signal if you are still working on this. Cleanup up assignments for now 👍

**Comment by AbhijithGanesh** [comment]
Heyy @theBeginner86 yep
