### ISSUE TITLE
[Extensions] Whiteboard: Style Color Swatch

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9130]
### Current Behavior
The single-color swatch icon could be livelier. 

### Implementation
Use this CSS to add colors to the color-picker SVG.
[swatch.html.zip](https://github.com/meshery/meshery/files/12919971/swatch.html.zip)

### Mockups

<img width="688" alt="Screenshot 2023-10-16 at 5 48 13 AM" src="https://github.com/meshery/meshery/assets/7570704/5adbc60d-103c-42ad-a7b3-9d6fdecb93fb">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ayushlohmod** [comment]
Hey i really wanted to work on this can assign this issue to me

**Comment by ayushlohmod** [comment]
Hey I really wanted to work on this can you assign this issue to me

**Comment by leecalcote** [comment]
Thank you very much, @ayushlohmod. My apologies - I meant to assign this straight-away as it is already spoken for.

**Comment by ayushlohmod** [comment]
OK @leecalcote  no worries

**Comment by leecalcote** [comment]
Implemented. Released in MeshMap v0.6.161-2
