### ISSUE TITLE
[Docs] TOC: Add section describing the use of children and grandchildren

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9165]
We need to document the use of the `grandchildren`<https://github.com/meshery/meshery/blob/03345f16a853f613b83b7d6e18c55552dd30b13e/docs/_data/toc.yml#L30-L31| stanza >that I added to the table of contents sidebar in the <https://docs.meshery.io/project/contributing/contributing-docs|Contributing to Docs> page.

[Slack Message](https://layer5io.slack.com/archives/C04LJS10VTL/p1697904313067449?thread_ts=1697904313.067449&cid=C04LJS10VTL)

**Comment by Kaushik080** [comment]
I would like to work on this, please assign me

**Comment by coder12git** [comment]
@Kaushik080 i am working on it, as this was assign to me via slack

**Comment by leecalcote** [comment]
@Kaushik080 thank you for volunteering!

**Comment by abhijeetgauravm** [comment]
> I would like to work on this, please assign me

@Kaushik080  Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.

**Comment by leecalcote** [comment]
@Kaushik080 signal if you don’t find a suitable issue.
