### ISSUE TITLE
[MeshModel] [UX]: Icon for Kubernetes Component - Who Am I

### ISSUE THREAD

**Issue by Akshun-01** [meshery/meshery#9181]
### Current Situation
Meshery is a powerful platform that contains over [200 integrations](https://layer5.io/cloud-native-management/meshery/integrations) for managing cloud-native applications. MeshMap is an extension of Meshery that visually represents these integrations and components. Currently, most of the icons used in MeshMap have the default shape of a circle. However, to improve visual clarity and consistency, we need to design custom icons for MeshMap components.

### Proposed Change
A new Icon for **Who Am I** needs to be created. This issue calls for a volunteer to draft a new Icon.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- [MeshModel Repository](https://github.com/meshery/meshery/tree/master/server/meshmodel)
- 🖥 [MeshModel Overview](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g226f5de5180_19_259)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### Instructions for Models
1. _Forthcoming_

### Instructions for Components
While the default shape for new components is a circle, each component should be considered for its best-fit shape.
1. Review and familiarize with the available set of predefined relationship types. Refer the Cytoscape [node types](https://js.cytoscape.org/demos/node-types/) for a list of possible shapes. 
1. Propose a specific shape, best-suited to visually represent the Component. Example - Deployment as a pentagon.
1. Proposee a specific icon, best-suited to visually represent the Component. Example - DaemonSet as a skull icon.

### Instructions for Relationships
1. Identify the relationship and any specific constraints to be enforced between the two specific components, their models or potentially other components, models, or environmental considerations.
1. Propose a specific visual representation for the relationship. Visual representation examples:
    - [Hierarchical](https://github.com/meshery/meshery/blob/master/.github/assets/images/hierarchical_relationship.png)
    - [Sibling](https://github.com/meshery/meshery/blob/master/.github/assets/images/sibling_relationship.png)
    - [Binding](https://github.com/meshery/meshery/blob/master/.github/assets/images/binding_relationship.png)
1. Prospose the appropriate relationship type, using one of the predefined set of relationship types or suggest a new relationship where an existing type does not fit.
1. Create a Relationship Definition (yaml). See the [Relationship Schema](https://github.com/meshery/meshery/tree/master/server/meshmodel/schemas) in MeshModel and [examples]([url](https://github.com/meshery/meshery/tree/master/server/meshmodel/relationships)).
1. Create a policy for evaluation of the relationship (rego). See examples.

### Instructions for Policies
1. _Forthcoming_

**Comment by Akshun-01** [comment]
I would like to work on this one.

**Comment by Akshun-01** [comment]
Hey, I came up with some designs for this icon. I would appreciate some feedback and review
@ritiksaxena124  @leecalcote 
![whoAmI_Layer5-01](https://github.com/meshery/meshery/assets/93793691/aa9f10b7-9fae-479a-a763-16dcd3010741)
![whoAmI_Layer5-02](https://github.com/meshery/meshery/assets/93793691/607a6288-a28f-4538-98bb-f7730b73d117)
![WhoAmI_Layer5-03](https://github.com/meshery/meshery/assets/93793691/0ab8dd2a-b9a7-4e97-9e1e-37b00765fc83)

**Comment by leecalcote** [comment]
@Modern-artist

**Comment by ritiksaxena124** [comment]
Thank you @Akshun-01 for taking this up. we can't use the 3rd one because it may give users a sense that the icon is missing when dropped on the canvas.  Suggestion, you can increase the person's height, set it to center, and have a question mark inside the head rather than adjacent to the person or using a question mark as a head.

**Comment by Akshun-01** [comment]
Hey @ritiksaxena124, these are some prototypes based on your feedback.
![WhoAmI_Layer5-01](https://github.com/meshery/meshery/assets/93793691/fc4c0bfc-75a9-411a-8466-5fb5b773b3c2)
![WhoAmI_Layer5-02](https://github.com/meshery/meshery/assets/93793691/65cf187e-4165-4812-89e0-142fcb4c5430)
![WhoAmI_Layer5-03](https://github.com/meshery/meshery/assets/93793691/d23e5576-cb10-469c-8e57-6aa5b29ca8a5)
![WhoAmI_Layer5-04](https://github.com/meshery/meshery/assets/93793691/0d4d2bda-e7b4-43b9-afff-9099c2d0c5d3)

**Comment by Akshun-01** [comment]
Hey @ritiksaxena124, thanks for the review. Here are some iterations based on your feedback.
![WhoAmI_Layer5-01](https://github.com/meshery/meshery/assets/93793691/233b87f3-4ef9-4368-8667-fc98f1f395e4)
![WhoAmI_Layer5-02](https://github.com/meshery/meshery/assets/93793691/4ab9c9fe-8002-41d9-8086-a95e7ae5cc36)
![WhoAmI_Layer5-03](https://github.com/meshery/meshery/assets/93793691/95a7e003-7a19-4965-b2bb-08184f2d0320)
![WhoAmI_Layer5-04](https://github.com/meshery/meshery/assets/93793691/47e6811c-e23a-44f3-8c08-4d1df73f280a)

**Comment by Akshun-01** [comment]
@ritiksaxena124 @Modern-artist @leecalcote 
Any reviews on this one?

**Comment by ritiksaxena124** [comment]
We can't go with the first and the last icons they look like they are asking users what the dish inside that container 😅. As there is not much difference in the second and the third icon other than the padding at the bottom we may go with the third one.

**Comment by Akshun-01** [comment]
ok, thanks for the feedback. So, how should I proceed now. Do some changes or add this to the req file?
