### ISSUE TITLE
[Docs] Removal of additional </div> from the home page

### ISSUE THREAD

**Issue by Debaditya-Som** [meshery/meshery#9182]
### Current State
There is an additional `</div>` in the home page of https://docs.meshery.io/

![Screenshot 2023-10-24 160426](https://github.com/meshery/meshery/assets/121785700/f151c54d-7af9-4aed-b0af-26eeeb528707)

### Desired State

Deletion of the unwanted </div> from the home page

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Debaditya-Som** [comment]
If granted, I would love to work on this issue

**Comment by yash37158** [comment]
Here you go @Debaditya-Som

**Comment by Debaditya-Som** [comment]
Thanks @yash37158 :)

**Comment by vishalvivekm** [comment]
@Debaditya-Som Thank you for opening this.
It's taken care of in a pr that's now merged : 
https://github.com/meshery/meshery/pull/9155#issuecomment-1776602350

Are we good to close this issue as completed @Debaditya-Som ?

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som Thank you for opening this.
> It's taken care of in a pr that's now merged : 
> https://github.com/meshery/meshery/pull/9155#issuecomment-1776602350
> 
> Are we good to close this issue as completed @Debaditya-Som ?

Okay cool
