### ISSUE TITLE
[UI] Dashboard card missing title and background 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9195]
### Current Behavior
On Meshery UI Dashboard:

<img width="1517" alt="Screenshot 2023-10-25 at 2 24 23 AM" src="https://github.com/meshery/meshery/assets/7570704/7f185542-f866-4ce7-851a-b2e19d9e7ced">

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
Have you able to built meshery @mrswastik-robot ?

**Comment by MeenuyD** [comment]
Hello @leecalcote I would like to work on this can you please assign it to me and I will add the card title as the resource and background like others background

**Comment by ksauravhash** [comment]
Hello @leecalcote. I am background in Full stack development in MERN stack. I would like you to assign me this issue.

**Comment by abhijeetgauravm** [comment]
Thanks for volunteering gents. @mrswastik-robot @ksauravhash You can help in reviewing the PR though. And here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.

**Comment by leecalcote** [comment]
@MeenuyD, progress? Should we allow @ksauravhash to take a shot at it?

**Comment by MeenuyD** [comment]
Hello @leecalcote sorry for the inconvenience due to some issue I could not do the work but now i will be working i have one question this UI is seen on the dashboard page right?
