### ISSUE TITLE
[Docs]- Flickering in Links

### ISSUE THREAD

**Issue by coder12git** [meshery/meshery#9196]
### Current Behavior

 Links that flickers in https://docs.meshery.io/ -
- https://docs.meshery.io/installation/mesheryctl
- https://docs.meshery.io/installation/compatibility-matrix
- https://docs.meshery.io/project/contributing

### Expected Behavior

There should be no occurrence of link flickering."

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by coder12git** [comment]
cc @leecalcote @vishalvivekm

**Comment by vishalvivekm** [comment]
Thanks for opening this @coder12git
