### ISSUE TITLE
[Components} New Polygon Shapes

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9204]
Roger, roger, <@U05BEE8DNPJ>

<@U05ESGV93GE> you’re on deck - <https://layer5io.slack.com/archives/C023QGMSH8D/p1697830195579319?thread_ts=1697829574.561679&amp;cid=C023QGMSH8D>. Source new shapes from the data.json included in this size, pretty please.

[Slack Message](https://layer5io.slack.com/archives/C023QGMSH8D/p1698255951449969?thread_ts=1698255579.640739&cid=C023QGMSH8D)

**Comment by leecalcote** [comment]
Yes or no, @Modern-artist ?

**Comment by leecalcote** [comment]
I think "yes", but...

**Comment by Modern-artist** [comment]
Yes
