### ISSUE TITLE
Broken link (Kubernetes-Minikube) in README

### ISSUE THREAD

**Issue by Kaushik080** [meshery/meshery#9210]
### Current Behavior
Minikube link in README redirects to invalid link ( 404 )

### Expected Behavior
It should redirect to correct link
### Screenshots/Logs
![image](https://github.com/meshery/meshery/assets/120493528/b60407ab-4b74-4510-b264-9ed2fe937dc1)
![image](https://github.com/meshery/meshery/assets/120493528/2eeb219f-b961-4ae6-9507-69f72c9fc504)

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Kaushik080** [comment]
I am working on this issue please assign it to me

**Comment by zakisk** [comment]
To which link will you redirect user?
