### ISSUE TITLE
[UI] Fix Workloads Widget

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#9240]
### Current Behavior

Unlike other widgets on Meshery Dashboard, Workloads widget is not using the white paper background. Thus, having a poor UX when no workload is discovered/registered by Meshery Server.

![Screenshot 2023-10-30 at 1 18 31 PM](https://github.com/meshery/meshery/assets/73700530/200cdbe0-0969-4931-80f5-35534764d426)

### Desired Behavior

Use exact same styling/classes for the "Workloads" widget.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ayushlohmod** [comment]
Hey I really wanted to work on this issue can you please assign this to me

**Comment by abhijeetgauravm** [comment]
@theBeginner86 seems like this [issue](https://github.com/meshery/meshery/issues/9195) is covering tthe current issue too.

**Comment by sudhanshutech** [comment]
duplicate issue
