### ISSUE TITLE
[Extensions] Cloned designs should be automatically loaded upon clone creation

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9256]
### Current Behavior

(audio included)

https://github.com/meshery/meshery/assets/7570704/19b0c00c-b977-446c-bb36-a77c78e3ba04

### Desired Behavior
1. Cloned designs should be automatically loaded upon clone creation.
2. Design owners should not be asked to clone their design even if that design is published.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
I wonder if this is in the docker extension, in Playground it's working for me

https://github.com/meshery/meshery/assets/71271069/8d46be23-9cf6-4f3e-8d5e-fd9ce724629c

**Comment by Yashsharma1911** [comment]
This issue is fixed

1. Design now loads on clone.
2. Owners are now allowed to load published design without clone.
