### ISSUE TITLE
[UI] Application import options missing "Meshery"

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9258]
### Current Behavior

<img width="632" alt="Screenshot 2023-10-31 at 9 07 32 PM" src="https://github.com/meshery/meshery/assets/7570704/2fa6d522-b545-4f60-8a75-2ce29bdf794d">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
This issue is fixed now
