### ISSUE TITLE
[UI] Design/Application Import Modal does not allow user to select application source type

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9260]
### Current Behavior

(audio included)

https://github.com/meshery/meshery/assets/7570704/afa1b837-0a86-402f-a6ca-514735726edc

### Desired Behavior
Users should be afforded the chance to select source type.
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
Issue is fixed in latest release
