### ISSUE TITLE
[Catalog] Published design information is missing Technology

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9262]
### Current Behavior
"Kubernetes" was technology that was selected at the time of submitting the publishing request for this design, however, once published the information modal does not reflect the technology designation.

### Screenshots/Logs
<img width="965" alt="Screenshot 2023-10-31 at 9 26 36 PM" src="https://github.com/meshery/meshery/assets/7570704/c7377bd9-0682-4f96-91ec-c8dc9d4ed80a">

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
The technology selected is missing here, too - https://meshery.meshery.io/catalog/287dc0fe-6497-4483-b54e-178eb8d65da8. @MUzairS15 @theBeginner86

**Comment by leecalcote** [comment]
Published designs are not being displayed in the Meshery.io catalog - https://meshery.io/catalog. I this a separate issue or an issue of the same root cause: a missing Technology value?

**Comment by theBeginner86** [comment]
> Published designs are not being displayed in the Meshery.io catalog - https://meshery.io/catalog. I this a separate issue or an issue of the same root cause: a missing Technology value?

Your design did get auto published to the Catalog. https://meshery.io/catalog/workloads/b4cf2b00-9a0e-4b2e-9ab6-43eb413aaad3/

Related commit: https://github.com/meshery/meshery.io/commit/88b891deeecceb3c169dddbfe162bee397dc0ed1

**Comment by theBeginner86** [comment]
Its most likely a UI issue for not displaying the selected technology.
