### ISSUE TITLE
[UI] Fix styling of Unauthenticated Modal

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#9283]
### Current Behavior

When users are unauthenticated then see a modal that is shown for few seconds until users are redirected to login screen.
But the styling of the modal is little off where the icon and the title are mis aligned.

<img width="691" alt="Screenshot 2023-11-01 at 9 49 43 PM" src="https://github.com/meshery/meshery/assets/73700530/d3c5fc74-702e-4116-a9ca-dae55139bda7">

### Desired Behavior

Improve styling of the title bar.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by captain-Akshay** [comment]
working on it!
