### ISSUE TITLE
[Docs] Meshery CRD Reference: MeshSyncs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9294]
### Current State

The Meshery CRDs are not included in Meshery Docs.

### Desired State
Create a "CRDs Reference" page in the "Reference" section of Meshery Docs. Include the following information:

# CRD Name
_description of the CRD's purpose_

## YAML Synopsis

```
apiVersion: core.meshery.io....
kind: MeshSync
metadata:
  name: 
spec:
.
.
.
```

## Fields

- **apiVersion** – API version being used. Must be v1alpha3 or later for this syntax.
- **kind** – Resource type. Must be set to MeshSync
- **metadata** -
- **name** – 
- **spec** -
  -

- **property** – description
- **property** – description
- **property** – description
- **property** – description

## Usage

_sample use scenario_

## Example Use

_explanaation of example_

```yaml
apiVersion: core.meshery.io....
kind: MeshSync
metadata:
  name: 
spec:
.
.
.

```

_explanaation of example_

## See Also
_link to other Meshery CRD_

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by KiptoonKipkurui** [comment]
@leecalcote Slow progress, but mainly because html css is not my strongest suite, if unable to in a day or so, I will communicate so that I can be paired with someone whose more at ease with html and css to quickly get it out of the gate
