### ISSUE TITLE
[Docker Extensions] Intercept for Redirecting to External Links

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#9300]
### Current Behavior

Currently, Meshery Docker Extension users are unable to click on any of the external links (e.g., a link to [error codes](https://docs.meshery.io/reference/error-codes) in https://docs.meshery.io)

![Screenshot 2023-11-02 at 10 42 04 PM](https://github.com/meshery/meshery/assets/73700530/1a7bf90c-5521-4e3a-9b33-bf605247fed7)

### Desired Behavior

Create an intercept that opens the link in a new browser window, similar to how Docker Desktop handles the user login process.

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
@humblenginr this is required i guess because if we want to click on to the design card we need to redirect them to that design in  cloud catalog page right?

**Comment by humblenginr** [comment]
@sudhanshutech we have the ability to open external links from Docker Desktop Extension. I don't understand this issue. We should be able to use `window.ddClient.openExternal` to open external links.
