### ISSUE TITLE
Convert Meshery Architecture Slides to SVG for Documentation

### ISSUE THREAD

**Issue by iArchitSharma** [meshery/meshery#9306]
**We're looking for assistance in converting the Meshery Architecture slides to SVG format and incorporating them into our documentation. Here are the details:**

### Task

- Visit the Meshery Architecture slides.
- Download ~1/2 of the slides to SVG format.
- Upload the SVG slides to a relevant page on our documentation site.

### Challenges
You might encounter a few technical hurdles along the way:

1. Too many / too large rasterized images: Be mindful of the number and size of rasterized images embedded in the SVG files.
2. Not curating the SVG or the slide for presentation in docs: The slides may require some editing and formatting to ensure they display effectively within our documentation. You can see an example of a well-curated slide [here](https://docs.layer5.io/cloud/security/roles/).
**Here is what the slide looks like for above example:**
![Provider Admin image](https://github.com/layer5io/docs/assets/74408634/a50fbc1d-d298-43a8-86af-6652bc2b1c65)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ShatilKhan** [comment]
I can help on this!

**Comment by iArchitSharma** [comment]
Hi @ShatilKhan
I have already made a [PR](https://github.com/layer5io/docs/pull/45) which is in draft. Some additional work is required based on the feedback. Would you like to collaborate?

**Comment by ShatilKhan** [comment]
@iArchitSharma sure!
I'll look into your PR
