### ISSUE TITLE
[Catalog] Encode HTML Entities

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9311]
Similarly, <@U04K72AGYBW>, the inclusion of

`Docker image:` and `Elasticsearch for Kubernetes:` causes the build to fail as well.

These characters should be allowed. Meshery Server and Cloud both need to encode html entities.

<@U04K72AGYBW> something that you can address?

[Slack Message](https://layer5io.slack.com/archives/CFGG6U10E/p1699052523444279?thread_ts=1699052459.529689&cid=CFGG6U10E)

**Comment by leecalcote** [comment]
Bump, poke, ping, pow

**Comment by Yashsharma1911** [comment]
This issue has been solved
