### ISSUE TITLE
[UI] Common toolbar having style issues

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#9320]
### Current Behavior
Toolbars in Meshery UI are having UI issues, please see attached screenshot

![Screenshot 2023-11-07 at 10 38 48 PM](https://github.com/meshery/meshery/assets/71271069/b0d9aa0b-60b7-4f6f-8b2a-f40d9faec1dd)

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
Note: I'm seeing this on every page

**Comment by Yashsharma1911** [comment]
// @ptdatta @sudhanshutech

**Comment by Cvr421** [comment]
@Yashsharma1911 Can I work on this issue.

**Comment by theBeginner86** [comment]
This was fixed in this PR. https://github.com/meshery/meshery/pull/9315 

Latest view in https://play.meshery.io
![Screenshot 2023-11-08 at 1 19 37 PM](https://github.com/meshery/meshery/assets/73700530/47ad0632-602f-4893-b5ac-2bb8bffc197b)
