### ISSUE TITLE
Meshery UI Bugs

### ISSUE THREAD

**Issue by ptdatta** [meshery/meshery#9322]
Fixes needed in Meshery UI.

* [x] [Common Toolbar #9320](https://github.com/meshery/meshery/issues/9320)
* [x] [Registry Mobile View #9344](https://github.com/meshery/meshery/pull/9344)
* [ ] Meshmap Mobile View
* [x] [Contrast Issues on Registry Dark mode #9328](https://github.com/meshery/meshery/pull/9328)
* [x] Styling Issues on Connections
---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Alwinseb01** [comment]
is this issue resolved or being worked upon? if not can I work on it?

**Comment by Yashsharma1911** [comment]
Thankyou @Alwinseb01 for raising your hand yes multiple people can work on it, can you confirm that you successfully able to run Meshery in your local system

**Comment by Alwinseb01** [comment]
hi, yes i have meshsery ui running successfully in my local system. Though i don't have any backend services running locally yet, so the UI isn't showing any data. Im trying to setup the local server

**Comment by Yashsharma1911** [comment]
Ohh good @Alwinseb01 if you run `make server` it will run both backend server and build UI server, though it will not show the changes you made in ui for that you need to run `make ui` after `make server` which will run on `:3000` port

Good please raise PR on these issues mentioned, @ptdatta please provide more description about these issues so that @Alwinseb01 can volunteer with the acceptance test, also have you made any progress with these issues?

**Comment by ptdatta** [comment]
@Alwinseb01 two of these issues are done and currently, I'm working on the registry mobile view. So you can work on any of the other two issues mentioned. Raise a PR  and comment the PR number here so we can track it.

**Comment by Alwinseb01** [comment]
@ptdatta could you provide more details about  Meshmap Mobile View? I can start working on it

**Comment by ptdatta** [comment]
@Alwinseb01 here is the detail [issue](https://github.com/meshery/meshery/issues/9347) for the Meshmap Mobile View. Good luck.

**Comment by ptdatta** [comment]
@Alwinseb01 The Meshmap mobile view needs a lot of fixes that's why I am assigning you to work on improving the connections  UI. Here is it's description [#9348](https://github.com/meshery/meshery/issues/9348). Good luck.

**Comment by Alwinseb01** [comment]
Sure. I'll work on it. Thank you
