### ISSUE TITLE
Slack Invite  Link Not Working

### ISSUE THREAD

**Issue by vaibhavpnimkar** [meshery/meshery#9333]
### Current State
The slack invite link  is not working

### Desired State
It supposed to let me join the slack channel of meshery 

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaibhavpnimkar** [comment]
![image](https://github.com/meshery/meshery/assets/128807866/935b08fc-3631-41ec-abea-da4acf688e9d)
Here is a screenshot

**Comment by Yashsharma1911** [comment]
Thankyou for creating issue @vaibhavpnimkar

**Comment by vishalvivekm** [comment]
fixed. 
@vaibhavpnimkar is it working for you now?

**Comment by Yashsharma1911** [comment]
Thankyou @vishalvivekm

**Comment by vaibhavpnimkar** [comment]
Yes it working now ThankYou @vishalvivekm  and @Yashsharma1911
