### ISSUE TITLE
[UI] Styling issues in Connections UI

### ISSUE THREAD

**Issue by ptdatta** [meshery/meshery#9348]
### Current Behavior

![image](https://github.com/meshery/meshery/assets/94271200/dd7dd044-5ea9-4a7e-9510-0ddabf190ad2)

### Desired Behavior
Fix the styling issues in connections.

### Implementation

1. Hide the scrollbars.
2. Make the expanded row respect flexbox.
3. Clean up the code a bit ( currently there are more 5 levels of nesting to just render the metadata )
4. Add your magic.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Alwinseb01** [comment]
working on it

**Comment by Alwinseb01** [comment]
Thanks for the clarification @sudhanshutech!
