### ISSUE TITLE
[UI] Refreshing on Connections page causes Adapter connection prompt

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9351]
### Current Behavior
While on http://localhost:9081/management/connections, when the page is refreshed, this happens:

https://github.com/meshery/meshery/assets/7570704/a5f2ba3e-63d6-48cd-8f17-e5a346ade96a

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@senali-d @aabidsofi19 routing issue..

**Comment by LakshyaSatpal** [comment]
would like to work on this. Please assign it to me.

**Comment by sudhanshutech** [comment]
This issue has been resolved @LakshyaSatpal , lets get you some issues
