### ISSUE TITLE
[UI] Opening information modal of design also opens edit design modal

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#9358]
### Current Behavior
In current behavior when you click on `info icon` to open the informational modal it also opens edit design modal which opens when you click on a row in table, most probably this can be an event bubbling issue and it should fix by adding event.stopPropagation()

Here is the attached video of the issue

https://github.com/meshery/meshery/assets/71271069/f77e5ff2-4b94-48c1-b6f0-76557f57e5ba

### Expected Behavior
On clicking info icon it should not open edit design modal it should only open info modal

### Environment

- **Host OS:** Mac
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** v0.6.175
- **Meshery Client Version:** v0.6.175

### To Reproduce
1. Go to 'design page'
2. Switch to table mode
3. Click on 'info icon'
5. See issue

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaibhavpnimkar** [comment]
hey i would like to work on this

**Comment by Yashsharma1911** [comment]
Awesome, go ahead @vaibhavpnimkar

**Comment by vaibhavpnimkar** [comment]
hey @Yashsharma1911 i think if the second page is editing one and that is causing issue then isnt this also a issue?
![image](https://github.com/meshery/meshery/assets/128807866/f1aeb27f-8624-46dd-ac64-f8fc7b5db057)

**Comment by vaibhavpnimkar** [comment]
i think i should not be able to edit this right?

**Comment by vaibhavpnimkar** [comment]
this is after me making the changes should i raise a PR@Yashsharma1911 
[Screencast from 14-11-23 09:39:57 PM IST.webm](https://github.com/meshery/meshery/assets/128807866/414c7094-e0a0-4024-a888-3fc8dfe667a4)
