### ISSUE TITLE
MeshSync Fingerprint Tier 1: GVK

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9363]
### Desired Behavior
1. In context of K8s,  GVK is referenced...

### Acceptance Tests
1. 

## _Future:_ 
_1. Run fingerprinting routine upon model import._
_1. MeshSync will reference Meshery Registry so as to offload tier 2, tier 3 fingerprinting from Meshery Server._

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MUzairS15** [comment]
@leecalcote close this?
