### ISSUE TITLE
[Meshery Docs] Quick Start - typo

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#9375]
### Description

Path: Meshery Docs - [Quick Start](https://docs.meshery.io/installation/quick-start)
This sentence has typo: "...Kubernetes API Server availabe in the control plane. "

### Expected Behavior

Fix spelling: "...Kubernetes API Server available in the control plane. "
### Screenshots

![imageedit_1_4153899375](https://github.com/layer5io/layer5/assets/19821445/bd2eca54-7bc0-41e1-ae8e-8eca050139e6)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sandramsc** [comment]
@Harsha-10 Since you asked for the issue to be assigned to you first before it was transfered to correct repo, you can go ahead.

**Comment by Harsha-10** [comment]
Okay

**Comment by Harsha-10** [comment]
@sandramsc  i am having issues in setting up locally.... can you please assign to someone else

**Comment by sandramsc** [comment]
> @sandramsc i am having issues in setting up locally.... can you please assign to someone else

I suggest giving yourself more time to find a solution (assignment was given less than a few hours ago), the [discussion forum](https://discuss.layer5.io/) and Slack channel are great places to ask for help from the community.

**Comment by vaibhavpnimkar** [comment]
are you getting this error:
![image](https://github.com/meshery/meshery/assets/128807866/7d4c4432-917b-41cb-a26f-8d6d7ee50707)
@Harsha-10

**Comment by sandramsc** [comment]
> are you getting this error: ![image](https://user-images.githubusercontent.com/128807866/283928456-7d4c4432-917b-41cb-a26f-8d6d7ee50707.png) @Harsha-10

Hi @vaibhavpnimkar please direct posts like this to the [discussion forum](https://discuss.layer5.io/), as the assignee has not specified the issue the issuee they encountered, this creates more noise than help for the assignee working on the issue.

**Comment by vaibhavpnimkar** [comment]
hey @sandramsc the is resolved already and it was common issue faced by everyone who was trying to run make-ui setup so sorry if i create more noisei was trying to help out
