### ISSUE TITLE
[UI] Dark Mode Bug in Kubernetes Config Modal

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#9384]
### Current Behavior

<img width="1183" alt="Screenshot 2023-11-17 at 7 09 36 PM" src="https://github.com/meshery/meshery/assets/73700530/d0f596f7-9888-422c-b2c2-9c8f13fd1e37">

### Desired Behavior

We should be using our standard dark mode styling for action buttons.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by vaibhavpnimkar** [comment]
hey @theBeginner86 i would like to work on this can you assign this to me?

**Comment by Yashsharma1911** [comment]
@vaibhavpnimkar you can go ahead

**Comment by Yashsharma1911** [comment]
For reference, you can use `focused` color from theme

**Comment by vaibhavpnimkar** [comment]
hey @Yashsharma1911 i am not able find code/styling for import button can you navigate me there plz?

**Comment by vaibhavpnimkar** [comment]
i have fixed the issue plz review @Yashsharma1911 @theBeginner86
