### ISSUE TITLE
[Extensions] Remove unwanted white line

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9393]
<img width="114" alt="Screenshot 2023-11-19 at 11 17 43 AM" src="https://github.com/meshery/meshery/assets/7570704/7acc4f86-7cae-4d72-ac9a-813572338329">

@coder12git, will you please see to making this white line no longer visible (getting rid of it)? What is it, by the way?

[Slack Message](https://layer5io.slack.com/archives/G01BD9056TD/p1700415542429869?thread_ts=1700415542.429869&cid=G01BD9056TD)

**Comment by coder12git** [comment]
@leecalcote can i know in which part of extension?

**Comment by coder12git** [comment]
![Uploading Screenshot 2023-11-20 072046.png…]()

**Comment by leecalcote** [comment]
Yes, you got it. Good work. 🙂

**Comment by coder12git** [comment]
// Completed
