### ISSUE TITLE
[UI] Kubernetes Config Modal Hovering Effect Deviation

### ISSUE THREAD

**Issue by vaibhavpnimkar** [meshery/meshery#9399]
### Current Behavior
[284250329-71a5d129-b84d-4628-a3e7-46aeb4e66716.webm](https://github.com/meshery/meshery/assets/128807866/395a1e07-ace0-489b-b42d-8948198435f6)

### Desired Behavior
We should be using our standard  styling for action buttons.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Raj100679** [comment]
Hey, I would love to work on this issue, Can you also provide me where the styling of buttons are present

**Comment by vaibhavpnimkar** [comment]
here you have to add :https://github.com/meshery/meshery/blob/master/ui/components/PromptComponent.js 
this line in inside hover:
`    backgroundColor: theme.palette.secondary.focused,`
plz ask  @yash37158 or any other member to assign this issue to you

**Comment by Raj100679** [comment]
Hey @Yashsharma1911 can you assign this issue to me?

**Comment by yash37158** [comment]
Here you go @Raj100679

**Comment by vaibhavpnimkar** [comment]
any updates @Raj100679 ??

**Comment by Raj100679** [comment]
@vaibhavpnimkar will work on it today, yesterday got stuck with setup

**Comment by vaibhavpnimkar** [comment]
okok you can ask me if you any difficulties ..

**Comment by Raj100679** [comment]
![Screenshot (130)](https://github.com/meshery/meshery/assets/85561967/00ed6748-707e-48ab-a05d-5fd57b3eb655)
@vaibhavpnimkar Have i done it right?

**Comment by vaibhavpnimkar** [comment]
make a PR on this issue
