### ISSUE TITLE
[Docs] - Fix alignment issue in left sidebar

### ISSUE THREAD

**Issue by coder12git** [meshery/meshery#9400]
### Current State
![Screenshot 2023-11-20 220232](https://github.com/meshery/meshery/assets/108334168/c17c153c-690c-49e1-80c6-e5315f4e9726)

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sandramsc** [comment]
Hi @coder12git Could you update the issue description with some more details (assuming this isn't one you'll be working on) as it would help anyone assigned understand it clearer i.e:

- adding a link to the page where the issue occurs
- adding content under #current state describing the current behaviour of the issue
- adding content under #desired state describing the effect of an optimal fix

**Comment by coder12git** [comment]
thanks for mentioning @sandramsc , i am working on this , forgot to assign myself :)

**Comment by abhijeetgauravm** [comment]
Hey @coder12git seems like its a duplicate of #9413 .

**Comment by leecalcote** [comment]
We can close my issue (as a duplicate). It offers a some additional color in terms of the bug being faced.
