### ISSUE TITLE
[UI] Dashboards: Need to be mobile friendly

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9461]
### Current Behavior

Dashbaords look like this and get cut off on smaller screens.

<img width="849" alt="Screenshot 2023-11-26 at 5 14 50 PM" src="https://github.com/meshery/meshery/assets/7570704/b68c82d7-f811-433f-8e31-7eb6967fab10">

### Desired Behavior
Easy to navigate and view pages on mobile screens.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Niksha29** [comment]
i want to fix this issue how to start??

**Comment by Niksha29** [comment]
I want to fix this issue . How to contribute ??

**Comment by hs7898753** [comment]
@leecalcote 
If no one on this issue . I would be happy to do it

**Comment by yash37158** [comment]
Hey @Niksha29, can you run Meshery locally? if not, you can checkout the documentation meshery [docs](https://docs.meshery.io/project)

**Comment by Raj100679** [comment]
Hey @leecalcote @yash37158  , Can I work on this issue?

**Comment by yash37158** [comment]
Hey @Raj100679, Would you be able to take a look at the issue queue? There are a few items that need to be assigned.

**Comment by leecalcote** [comment]
Hi All, thanks much for jumping in and volunteering. I missed the prior notifications. Here's what help guarantee both your success and assignment of the issue (and there are plenty more where this issue comes from):

1. Confirm that you're able to build the project, specifically, the components necessary to resolve this issue.
2. Confirm the approach you intend to take to resolve the issue.

**Comment by Raj100679** [comment]
@Yashsharma1911 @leecalcote  Sorry I missed the notifications, I will work on this

**Comment by sudhanshutech** [comment]
@lakshz

**Comment by lakshz** [comment]
@leecalcote @sudhanshutech I am unable to reproduce the issue. The dashboard looks mobile friendly to me, when I inspect. 

This is the mobile view with sidebar opened:
<img width="556" alt="Screenshot 2024-05-10 at 17 17 50" src="https://github.com/meshery/meshery/assets/81241551/e0c99cb1-dd9c-427c-aafb-a961c0e8b3f0">

**Comment by leecalcote** [comment]
Neither of these views are good. 

Also, visit the other screens in the Dashboard.

**Comment by lakshz** [comment]
> Dashbaords look like this and get cut off on smaller screens.
> 
> <img alt="Screenshot 2023-11-26 at 5 14 50 PM" width="849" src="https://private-user-images.githubusercontent.com/7570704/285689259-b68c82d7-f811-433f-8e31-7eb6967fab10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNTI4OTcsIm5iZiI6MTcxNTM1MjU5NywicGF0aCI6Ii83NTcwNzA0LzI4NTY4OTI1OS1iNjhjODJkNy1mODExLTQzM2YtOGUzMS03ZWI2OTY3ZmFiMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMTQ0OTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmZmZGJhYzY5NWQ1MGM4NzhlOTM5ZDJiZjRhN2M0ODVhNTgxNzA0ZTNhNmQ1OGU1ZWIyM2Q3YmM5OWUzMmI2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9E4qlPh8aC-1nLKZYzcCVbwyZlmjDJtMVWIJnjrNxh8">
`

**Comment by lakshz** [comment]
> Neither of these views are good.
Yes, Agreed. The current mobile views are not good. However to make it better, I need some design validation:
1.  
<img width="367" alt="Screenshot 2024-05-10 at 20 25 32" src="https://github.com/meshery/meshery/assets/81241551/184e3df3-a1ac-4630-aad8-a1dc125d8b48">
Should we replace the top navigation, to a `selection dropdown`? The current nav is not user friendly, and going with the mobile screen size.


2. The user preferences page needs work. Should we include it in the same issue? 
<img width="457" alt="Screenshot 2024-05-10 at 20 23 29" src="https://github.com/meshery/meshery/assets/81241551/8bc044b1-5a72-4980-8563-ece793f9eb99">
