### ISSUE TITLE
[UI] Infinite API calls when trying to search in the Registry UI.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#9494]
https://github.com/meshery/meshery/assets/7570704/66ebbba0-d6fe-4ca2-96f4-4a3c11a79bc2

[Slack Message](https://layer5io.slack.com/archives/C023QGMSH8D/p1701281565704769?thread_ts=1701281353.886169&cid=C023QGMSH8D)

**Comment by leecalcote** [comment]
Video capture added.

**Comment by VihasMakwana** [comment]
@leecalcote I'll have a crack at this. Can you assign this to me?

**Comment by leecalcote** [comment]
Thanks for jumping in @VihasMakwana 👏

**Comment by leecalcote** [comment]
A 2 or 3 second or so debounce on the search input will also be helpful. What really needs to happen is for the search to be server-side, not client-side, @VihasMakwana.

**Comment by VihasMakwana** [comment]
FIX PR: https://github.com/meshery/meshery/pull/9541

**Comment by VihasMakwana** [comment]
@leecalcote @MUzairS15 have a look at the behavior of pagination here:

<video controls="" width="800" height="500" muted="" loop="" autoplay="">
<source src="https://github.com/VihasMakwana/assets/raw/main/Screencast%202023-12-03%2000:56:10.mp4" type="video/mp4">
</video>

**Comment by leecalcote** [comment]
The behavior in the screencast is looking pretty good. 😊

**Comment by leecalcote** [comment]
Having said that, if it is doing this 14 records at a time… That’s no bueno.

**Comment by VihasMakwana** [comment]
That can be increased.
Should we do 50 at a time, maybe?

**Comment by VihasMakwana** [comment]
@leecalcote worth mentioning, 14 records at a time is default case for all the components in dashboard.
I'll probably raise another PR for this, as it will be a separate work.
How does it sound to you?

**Comment by leecalcote** [comment]
We must be speaking past each other. The APIs that support search should be a one-shot interaction for each query performed. Data for which the UI offers search needs to be backed by a search-supported API. Search is to be done server-side, not client-side. The same rule applies for filtering. 

@theBeginner86, am I missing something here?

**Comment by theBeginner86** [comment]
> We must be speaking past each other. The APIs that support search should be a one-shot interaction for each query performed. Data for which the UI offers search needs to be backed by a search-supported API. Search is to be done server-side, not client-side. The same rule applies for filtering.
> 
> @theBeginner86, am I missing something here?

Yes, you articulated it correctly.

Moreover, all these features (searching, filtering, sorting, etc.) of Meshery Models APIs are supported through the  [Modelfilters](https://github.com/meshery/meshkit/blob/master/models/meshmodel/core/v1alpha1/models.go#L15) construct. @VihasMakwana you might want to have a look at it if you haven't already. 👍

**Comment by VihasMakwana** [comment]
@leecalcote have a look at this behavior:

https://github.com/meshery/meshery/assets/121151420/48025487-ede8-4844-8979-486022f35bc4

The achieved latency is minimal and the infinite calls issue has been fixed.

**Comment by leecalcote** [comment]
> @leecalcote worth mentioning, 14 records at a time is default case for all the components in dashboard. I'll probably raise another PR for this, as it will be a separate work. How does it sound to you?

I sincerely hope not. Can you elaborate to demonstrate that this is true?

**Comment by leecalcote** [comment]
> That can be increased. Should we do 50 at a time, maybe?

No, sir. Architecturally, we simply want to avoid it altogether.

**Comment by MUzairS15** [comment]
@VihasMakwana I think we are overthinking here. We can add debounce to the search results and add lazy loading for components and relationships.

**Comment by VihasMakwana** [comment]
Hmm, that's true. But I don't think this will be a major impact. 
With debounce, we will still make API calls. 
I gave latency a greater priority over bandwidth because that's what users will need, searches to be faster.

Also, we only perform db matches if the parameters are specified in URL. In other cases, it's just as before.
Can you also review my meshery PR, you'll have a clear understanding of when we're performing some extra queries?

**Comment by VihasMakwana** [comment]
I can also add denouncing so we make as few api calls as possible.

I don't think adding these 2 indexes can have a major impact, it solves a bigger problem though.
"Too many indexes" can cause an issue if we have more writes/read ratio, which is not the case here. So, I went ahead with this way.

**Comment by VihasMakwana** [comment]
I will look into https://github.com/meshery/meshkit/pull/428#discussion_r1416162162.
We will achieve minimal latency with fewer bytes and minimal bandwidth. That way, everyone's happy😅.
