### ISSUE TITLE
[Docs] 404s for "Community" and "Contributing" links on /project

### ISSUE THREAD

**Issue by dmarcoux** [meshery/meshery#9496]
### Current State

In the screenshot below, both `Community` and `Contributing` links are 404s.

![404](https://github.com/meshery/meshery/assets/1102934/3e87db14-f1c5-445d-b0ca-40c244c36a6b)

### Desired State

Are they even supposed to be links? If so, then point to the correct URLs. If not, remove the links.

I believe the `Community` link should point to `https://docs.meshery.io/project/community`, not `https://docs.meshery.io/community`. This would however be a duplicate of the link `Meshery Community` just below.

As for `Contributing`, it seems like `https://docs.meshery.io/project/contributing` is the right link. However, that page is pretty much the same information as what we already see in the list below `Contributing`.

In the end, removing both links seems like the best solution.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by dmarcoux** [comment]
This is the file with the 404s: https://github.com/meshery/meshery/blob/master/docs/pages/project/index.md

**Comment by leecalcote** [comment]
Thank you very much, @dmarcoux 👍
