### ISSUE TITLE
[UI] Dashboard: Overview charts don't properly deep link to Registry

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9502]
### Current Behavior

https://github.com/meshery/meshery/assets/7570704/e1325d16-974d-453e-8b17-df219ac30c2b

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Amit0617** [comment]
All of the links that have `#` in them don't work perfectly. Probably it needs to have click simulated programmatically on the settings page according to the URL. Or simply routes should be like `/settings/registry`

**Comment by souravbhunia07** [comment]
@leecalcote can you please assign me this issue?

**Comment by RaunakScarlet** [comment]
@leecalcote I want to fix this issue, can u assign me this issue

**Comment by RaunakScarlet** [comment]
registry tabVal intended to be 2 but metrics is there
when made registry tabVal 2 it desired behaviour acheived


https://github.com/meshery/meshery/assets/86217548/6d5e5e70-b2bd-4480-8529-8f5d89b0795d



 about other switch cases : i am not getting what exactly 'environement' & 'service-mesh' do .
 Any lead is appreciated

**Comment by tushar-TD** [comment]
@leecalcote This issue has been resolve, I think it is working properly.

**Comment by leecalcote** [comment]
You're right, @tushar-TD. Thank you, @aabidsofi19.
