### ISSUE TITLE
[CI] Improve Build UI workflow

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#9566]
### Current Behavior

Currently, the build UI workflow is misleading considering the UI fails to build but the job shows as passed successfully

https://github.com/meshery/meshery/actions/runs/7085439825/job/19281862660#step:6:30

### Desired Behavior

Improve https://github.com/meshery/meshery/blob/master/.github/workflows/build-ui-and-server.yml to ensure that the UI is actually build and error errors are reported promptly.

### Acceptance Tests

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by leecalcote** [comment]
@Shiva953 comment for assignment, if you would.

**Comment by StarTrooper08** [comment]
Can I work on this?
I'm fluent with Github Actions and also done CI contributions earlier to Meshery and Layer5.
