### ISSUE TITLE
[UI] Environments

### ISSUE THREAD

**Issue by senali-d** [meshery/meshery#9571]
### Desired Behavior

Environments in meshery UI

### Implementation

_**Please assume following paradigms for implementing UI.**_
#### GET all environments

1. API: GET:/api/environments
2. Response:

```
{
  "page": 0,
  "page_size": 0,
  "total_count": 0,
  "environments": [
    {
      "ID": "3892eb50-4697-4c72-aadc-32b766bce3c0",
      "name": "string",
      "description": "string",
      "organization_id": "7c60d51f-b44e-4682-87d6-449835ea4de6",
      "owner": "string",
      "created_at": "2019-08-24T14:15:22Z",
      "updated_at": "2019-08-24T14:15:22Z",
      "deleted_at": {
        "time": "2019-08-24T14:15:22Z",
        "valid": true
      }
    }
  ]
}
```

3. Query Params: search, order, page, pagesize, orgID (required)

#### GET environment

1. API: GET:/api/environments/{environmentId}
2. Response:
```
{
  "ID": "3892eb50-4697-4c72-aadc-32b766bce3c0",
  "name": "string",
  "description": "string",
  "organization_id": "7c60d51f-b44e-4682-87d6-449835ea4de6",
  "owner": "string",
  "created_at": "2019-08-24T14:15:22Z",
  "updated_at": "2019-08-24T14:15:22Z",
  "deleted_at": {
    "time": "2019-08-24T14:15:22Z",
    "valid": true
  }
}
```
3. Path params: environmentId

#### Delete Environment 
1. API: DELETE:/api/environments/{environmentId}
2. Path param: environmentId

#### Update an Environment
1. API: PUT:/api/environments/{environmentId}
2. Path param: environmentId
3. Payload:
```
{
  "name": "string",
  "description": "string",
  "OrganizationID": "2d34b1c1-8109-40c1-88f9-fdcfb32ea178"
}
```

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
⚠️ @senali-d @theBeginner86 the Environments transfer modal is breaking tenancy, displaying environment names from organizations other than the user's current org.

**Comment by senali-d** [comment]
https://github.com/meshery/meshery/pull/9647
