### ISSUE TITLE
[Extensions] Grafana and Prometheus dashboard cannot be deleted

### ISSUE THREAD

**Issue by gyohuangxin** [meshery/meshery#9575]
### Current Behavior

The Grafana and Prometheus dashboard cannot be deleted from UI after the Grafana and Prometheus deployment are deleted in cluster, it seems that Meshery need to ping their urls before Meshery can delete them.

<img width="788" alt="image" src="https://github.com/meshery/meshery/assets/42127654/addca63a-5f54-4fc5-b5c4-f01523e02491">

<img width="776" alt="image" src="https://github.com/meshery/meshery/assets/42127654/373ee203-3167-4603-9d25-c83648a28ed3">

### Desired Behavior

Users can delete Grafana and Prometheus dashboard without communicating with Grafana and Prometheus.

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v0.7.0-beta-1
- Meshery Client Version: stable-v0.7.0-beta-1
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MUzairS15** [comment]
@gyohuangxin  This is because we have moved from how we persisted Prometheus and grafana connections. But the UI is not updated. The metrics tab should be using connection constructs instead of old preferences construct.

there is already an open issue to track this update.
https://github.com/meshery/meshery/issues/9490

**Comment by gyohuangxin** [comment]
@MUzairS15 Thanks, is there any way and workaround now to delete Prometheus and Grafana connections from UI? 

> there is already an open issue to track this update.
> https://github.com/meshery/meshery/issues/9490

I will close the issue if it's duplicate..

**Comment by MUzairS15** [comment]
An easy way is to downgrade meshery.

**Comment by gyohuangxin** [comment]
@MUzairS15 Can you provide an example about how to downgrade Meshery, and which version is recommended?

**Comment by MUzairS15** [comment]
Version: v0.6.181
If you are using docker compose to deploy then you can change the image version.

**Comment by gyohuangxin** [comment]
@MUzairS15 Thank you so much.
