### ISSUE TITLE
[UI] Fix build warnings for Meshery UI

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#9590]
### Current Behavior

Ensure that all the build warnings for Meshery UI are completely fixed.

![Screenshot 2023-12-07 at 12 01 45 AM](https://github.com/meshery/meshery/assets/73700530/f6122dca-1cd0-4ac3-a47d-a85dafa44236)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by theBeginner86** [comment]
@Pushkarm029 up for grab?

**Comment by Dananjay996** [comment]
@theBeginner86 Hey!, I solved this issue, can I give a Pull request?

**Comment by harshitkandpal** [comment]
is this issue resolved or can i work on it ?

**Comment by Pushkarm029** [comment]
I am working on it.

**Comment by Pushkarm029** [comment]
@theBeginner86  I think this issue may be already resolved, or am I not able to reproduce it.

**Comment by theBeginner86** [comment]
Yes, looks like all are fixed now.

Thank you @Pushkarm029 for confirming 👍
