### ISSUE TITLE
[UI] Registry tree should be full screen height

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9595]
### Current Behavior
In Settings, under Registry...
<img width="762" alt="Screenshot 2023-12-07 at 7 24 25 AM" src="https://github.com/meshery/meshery/assets/7570704/76902082-460a-4281-ae9f-b67aa8c4154b">

### Desired Behavior
Please make the registry section the full height of the window.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by gyancodes** [comment]
@leecalcote Can I get more insights on this? It wold be helpful.

**Comment by Dananjay996** [comment]
@leecalcote Hey!, I am not exactly able to recreate this issue locally. Can you give me a few more details on how to re-create this? My UI looks fine locally when I try to view Settings/Registry. Also Which view is it? Desktop or Mobile? I will attach a picture of what I'm seeing locally when I try to recreate this.  
<img width="1280" alt="image" src="https://github.com/meshery/meshery/assets/97737828/cf623191-f02c-4cf2-9a1e-8326cb632fb7">

**Comment by gyancodes** [comment]
@Dananjay996 similar on my localhost also

**Comment by leecalcote** [comment]
Desktop view. Try larger resolution size. Try Safari. Try zooming out if you don't have a screen with higher resolution. If you don't or you can't reproduce, please unassigned yourself from the issue.

**Comment by aabidsofi19** [comment]
@vaibhavpnimkar assigned to you

**Comment by vaibhavpnimkar** [comment]
ok alright!!

**Comment by sudhanshutech** [comment]
@Yashsharma1911 fixed right?

**Comment by leecalcote** [comment]
@sudhanshutech no, it's not fixed.
