### ISSUE TITLE
[Extensions] Comments: @mention highlight offset

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9600]
Note the offset @mention highlights.

[Slack Message](https://layer5io.slack.com/archives/C023QGMSH8D/p1701999247007689?thread_ts=1701999186.922719&cid=C023QGMSH8D)

**Comment by captain-Akshay** [comment]
assigning myself!

**Comment by captain-Akshay** [comment]
fixed with the latest commit on comments
