### ISSUE TITLE
Docs: Guide for invoking performance tests and interpreting results

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#961]
**Current State:**
Missing documentation of how to run performance tests

**Desired State:**
A guide to running performance tests and interpreting their results.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Vineet-Sharma29** [comment]
Would like work on it. But I don't know about performance tests and interpreting results. How should I about it?

**Comment by leecalcote** [comment]
@Vineet-Sharma29 Good question. The current report format needs improvement beyond documentation. Before we have a session to review this for documentation, I wonder if after @rubenlorenzo looks at the code in this section that we might be able to bring forth some enhancements while documenting how to interpret these. @rubenlorenzo, what do you think? These [performance results charts](https://raw.githubusercontent.com/layer5io/meshery.io/master/images/meshery_benchmark_screen.png) are done in billboardjs.

**Comment by rubenlorenzo** [comment]
I don't know about it either. How should I help?

**Comment by sb1975** [comment]
I think some simple steps on how to use the performance section of the dashboard and interpret the results would be good to start with. Even simple screenshot with minimal steps would make this section complete. I know its already there but we just missing in the little bit of documentation on this.

**Comment by navendu-pottekkat** [comment]
New issue opened to track this: https://github.com/meshery/meshery/issues/3972
