### ISSUE TITLE
[UI] Dashboards not mobile friendly

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9610]
### Current Behavior
The dashboards are not responsive / Mobile friendly. 

### Desired Behavior
All pages, including the dashboards should be more friendly 

### Screenshots/Logs

![image](https://github.com/meshery/meshery/assets/7570704/96ca52dc-c575-47ce-be7b-4875eead4722)
### Environment

- Browser:  Safari
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v0.7.0

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by avinashji1302** [comment]
please assgin me this
