### ISSUE TITLE
[Extensions] Shapes: Errant artifact on retrieval of config tooltip 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9615]
### Current Behavior

https://github.com/meshery/meshery/assets/7570704/164f3922-8a0d-4448-ad3e-e4551416f59c

### Desired Behavior
Small dot should not appear.

### Environment

- Host OS: Mac 
- Browser: Safari
- Meshery Server Version: stable-v0.7.0

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by tushar-TD** [comment]
@leecalcote while tried to solve this issue, I have come across the similar king to problems in some components.
API
1) In API gateway of the  black dot is arising,On click event is different not as earlier. The interface which we used to get, getting now on while duplicating the same component.

https://github.com/meshery/meshery/assets/136827623/c59abb6e-a45b-4a72-97ca-3989e391a00a

2) We get the resize Icon, even after deleting the component.

**Comment by tushar-TD** [comment]
Same is happening with some stroage components.

https://github.com/meshery/meshery/assets/136827623/6575b1ce-fe50-4091-a54a-d2e09599edc4
