### ISSUE TITLE
[Extensions] Design Review: Notify Design Owner upon creation of Comment

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9616]
### Current Behavior
<img width="376" alt="Screenshot 2023-12-10 at 7 38 13 PM" src="https://github.com/meshery/meshery/assets/7570704/c84691ad-5fee-46ec-94c6-6247d2ffc7d5">

### Desired Behavior
Without requiring a mention of the design owner.

<img width="358" alt="Screenshot 2023-12-10 at 7 39 07 PM" src="https://github.com/meshery/meshery/assets/7570704/3cdbf7ef-86e8-4adb-85b9-a8ba838b6573">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
Missed this will complete this today

**Comment by Yashsharma1911** [comment]
This issue is completed
