### ISSUE TITLE
[Docs] Add Meshery CLI to the list of architectural components

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9623]
### Current State
https://docs.meshery.io/concepts/architecture is missing an entry and description of mesheryctl.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by StarTrooper08** [comment]
can I work on this issue?

**Comment by Harshiths1** [comment]
I have added the following 
The missing entry where the component name and language is mentioned.
![image](https://github.com/meshery/meshery/assets/136854105/efcec64f-b63e-44c4-9a9e-a0fa62ca51a7)

and a brief description about it 
![image](https://github.com/meshery/meshery/assets/136854105/8312a129-fabc-4de1-afd9-b33c0921c09b)

Please let me know if anything further is to be done or improved in it

**Comment by helloabhii** [comment]
is this issue still open to work on?

**Comment by Harshiths1** [comment]
I think someone had already raised a PR even before me that's why I closed mine too . Please check the PR's for this.

**Comment by ANKITRAJ2403** [comment]
Hi @leecalcote , I would like to work on this issue!

**Comment by leecalcote** [comment]
Gosh, I missed these messages previously.

**Comment by ANKITRAJ2403** [comment]
![issue_9623](https://github.com/meshery/meshery/assets/117210344/3c5e5de2-9366-4acb-be67-728fa691b83a)

I have added the mesheryctl section and linked it to https://github.com/meshery/meshery/tree/master/mesheryctl

**Comment by lekaf974** [comment]
@leecalcote looks this is done now https://docs.meshery.io/concepts/architecture#meshery-cli we can close the issue ?

**Comment by leecalcote** [comment]
Good call, @lekaf974 👍

**Comment by leecalcote** [comment]
(and @ANKITRAJ2403 👍 )
