### ISSUE TITLE
[mesheryctl] New command: `exp components [list|view|search]` 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9625]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
Create an `exp components [list|view|search]` command similar to that of `exp model` command.

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

**Comment by yash37158** [comment]
I would like to take up this issue

**Comment by leecalcote** [comment]
> I would like to take up this issue

I don't seem to be able to get ahold of you in Slack.

**Comment by saurabh100ni** [comment]
there you go @sadath-12 🚀

**Comment by alphaX86** [comment]
Hi folks @sadath-12 @saurabh100ni, I apologize for very late reply into this issue. This issue needs to be taken care of as it's kind of priority one, so I suggest you to take a look on other issues.
