### ISSUE TITLE
[Server] Support AWS Controllers for Kubernetes (ACK) 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9630]
### Current Behavior
AWS is not a component-supported platform.

### Desired Behavior
Use AWS Controllers for Kubernetes (ACK) (https://aws-controllers-k8s.github.io/community/) to bring AWS platform support to Meshery.

### Implementation
1. Generate static components from source (e.g. https://github.com/aws-controllers-k8s/eks-controller/tree/main/helm/crds)

### Acceptance Tests
1. These components are registered at boot time of Meshery Server.

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by VihasMakwana** [comment]
I went ahead and took care of adding these "statically".
I think our sheet is not updated with this info, can you do that? I don't think I have access
