### ISSUE TITLE
[Extensions] Visualizer: loss of subscription; stale data

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9657]
### Current Behavior
1. Re-establish lost GraphQL subscriptions, particularly when invoking a deploy / undeploy operation. Need for reinitialization (w/o load on Provider).
1. Visualizer continues to show deleted resources (Meshery Server cache? not marking deleted?)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by yash37158** [comment]
Hey @MUzairS15 are you still working on this issue ?
