### ISSUE TITLE
[Extensions] Universally bypass hotkey capture when focus is on input field

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9663]
### Current Behavior
Among the various issues seen in our textbox component, one of them is that they disallow the forward slash character.  Comments don't allow use of the forward slash character either.  I assume that the search hotkey that uses forward slash is capturing the key even though it should not when focus is inside of an input field. We had this problem a year ago and are having it again now. We need a universal RJSF rule or XState prerequisite that prevents capture of this hotkey when focus is in an input field.

### Desired Behavior
We need a universal RJSF rule or XState prerequisite that prevents capture of this hotkey when focus is in an input field.

### Screenshots/Logs

<img width="413" alt="Screenshot 2023-12-18 at 3 01 51 PM" src="https://github.com/meshery/meshery/assets/7570704/6bbbcbb3-c90e-4558-bc8a-d4b01d0f5433">

### Environment

- Host OS: Mac 
- Meshery Server Version: stable-v0.7.2-rc-2
- -Browser: Safari

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@captain-Akshay @Yashsharma1911 @aabidsofi19

**Comment by LakshyaSatpal** [comment]
Can I take this?

**Comment by LakshyaSatpal** [comment]
Can I work on this?
