### ISSUE TITLE
[Extensions] Eliminated wasted space in Comments

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9664]
### Current Behavior

<img width="418" alt="Screenshot 2023-12-18 at 3 04 25 PM" src="https://github.com/meshery/meshery/assets/7570704/b030b415-3e9e-49d7-afdb-05e8aaeb2802">

### Desired Behavior

<img width="388" alt="Chat" src="https://github.com/meshery/meshery/assets/7570704/bbd05258-7045-483c-b7a6-68479a4ab83c">

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by captain-Akshay** [comment]
done!
