### ISSUE TITLE
[UI] Unwanted click-through effect on connection chips in K8s context switcher

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9676]
### Current Behavior
<img width="486" alt="Screenshot 2023-12-19 at 8 04 57 AM" src="https://github.com/meshery/meshery/assets/7570704/88002ae7-27c0-4376-9e55-7a07b167dab2">

### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.7.2
- Meshery Client Version: stable-v0.7.2

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MeenuyD** [comment]
Hello @leecalcote I would like to work on this issue can you please assign it to me?

**Comment by leecalcote** [comment]
Thank you for volunteering, @MeenuyD

**Comment by xmayukx** [comment]
Hey @leecalcote i would like to work on this issue. Is it available?

**Comment by MeenuyD** [comment]
Hello @xmayukx Thanks for your enthusiasm but I will create the pr on this week

**Comment by leecalcote** [comment]
@MeenuyD we haven't seen any movement here. Are you still working on this? If not, let's allow another contributor to move it forward.

**Comment by xmayukx** [comment]
Hey @leecalcote can u assign it to me if its open for grab?

**Comment by leecalcote** [comment]
@xmayukx sounds good. Have you built and run Meshery UI previously?

**Comment by xmayukx** [comment]
@leecalcote yes

**Comment by leecalcote** [comment]
@xmayukx excellent. Let's 👨‍🎤 and roll.

**Comment by sudhanshutech** [comment]
This issue is already solved. Thanks @xmayukx
