### ISSUE TITLE
[Docs] single column responsive view is too narrow

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9686]
### Current State
![image](https://github.com/meshery/meshery/assets/7570704/423fe407-88f1-4fc5-8572-cb4d74043a03)

### Desired State

Wider column to increase legibility. 

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by theavitw** [comment]
I can do this.

**Comment by theavitw** [comment]
Can you please describe more

**Comment by leecalcote** [comment]
@theavitw I saw your first comment and assigned the issue to you. Your second comment has me wondering if you're ready to undertake this CSS change, though.

**Comment by vishalvivekm** [comment]
> @theavitw I saw your first comment and assigned the issue to you. Your second comment has me wondering if you're ready to undertake this CSS change, though.
> 
> @vishalvivekm, if @theavitw isn't able to figure out the necessary change by this coming Friday, will you undertake this issue?

Sure @leecalcote

**Comment by Aniumbott** [comment]
@vishalvivekm are you still working on this issue? I would like to if not.
