### ISSUE TITLE
[Docs] Include the Playground in the Quick Start

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9688]
### Current State
The Playground is the fastest way to access a Meshery environment. This option is not represent on the Quick Start page for installing Meshery.

### Desired State
Prominently list the Playground as an option open to everyone.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by jaydee029** [comment]
Hi , @leecalcote i would like to work on this.

**Comment by jaydee029** [comment]
Hi , @leecalcote do we make changes to just the quickstart page or do we also add separate page under the supported platform heading ?.
