### ISSUE TITLE
[UI] Part of pop-up content is hidden in Meshery Dashboard

### ISSUE THREAD

**Issue by nwanduka** [meshery/meshery#9695]
### Current Behavior
When not in full screen, part of the text on pop-up is hidden underneath the top bar. To reproduce: login to meshery playground on your browser via [Dashboard | Meshery](https://playground.meshery.io/)

### Desired Behavior
User should be able to clearly view the message on the pop-up whether in full screen or not.

### Screenshots/Logs
This is how it looks when not in full screen
![image](https://github.com/meshery/meshery/assets/122698422/805ee770-b579-498c-805c-9003fb494335)

How it should look (whether in full screen or not)
![Screenshot (90)](https://github.com/meshery/meshery/assets/122698422/f5889b60-0997-433a-8153-fcfe3878748c)

### Environment

- Browser: Microsoft Edge
- Host OS: Windows

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by prabhjeevnijjar** [comment]
@nwanduka I would like to work on this issue

**Comment by Raj100679** [comment]
@nwanduka Can i work on this?

**Comment by aabidsofi19** [comment]
@prabhjeevnijjar  its yours

**Comment by prabhjeevnijjar** [comment]
@nwanduka

I have fixed the issue mentioned above locally.

I observed an inconsistency in UI:

When I get this popup as unregistered user.

The text says "Get early access to MeshMap!"

The close modal button shifts to the left side along with the text. 

This is a small bug should I fix it right now or do I create a new bug report?

PFA SS

<img width="1440" alt="Screenshot 2023-12-23 at 10 18 59 AM" src="https://github.com/meshery/meshery/assets/30125794/a494edf5-30d1-427f-aa1b-948ff0e8b440">

**Comment by nwanduka** [comment]
Thanks for working on this issue @prabhjeevnijjar. Nice job 👍🏽. And the UI issue you raised seems valid. Let's discuss it in the Websites call on Monday. [Check out the schedule](https://layer5.io/community/calendar) and add to your calendar if you haven't already done so.

Then [add this issue as an agenda item](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) for the call.

**Comment by nwanduka** [comment]
> @nwanduka
> 
> I have fixed the issue mentioned above locally.
> 
> I observed an inconsistency in UI:
> 
> When I get this popup as unregistered user.
> 
> The text says "Get early access to MeshMap!"
> 
> The close modal button shifts to the left side along with the text.
> 
> This is a small bug should I fix it right now or do I create a new bug report?
> 
> PFA SS
> 
> <img alt="Screenshot 2023-12-23 at 10 18 59 AM" width="1440" src="https://private-user-images.githubusercontent.com/30125794/292609093-a494edf5-30d1-427f-aa1b-948ff0e8b440.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MDE0MTQsIm5iZiI6MTcwMzgwMTExNCwicGF0aCI6Ii8zMDEyNTc5NC8yOTI2MDkwOTMtYTQ5NGVkZjUtMzBkMS00MjdmLWFhMWItOTQ4ZmYwZThiNDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDIyMDUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYjk2MTI1Zjg0Yzg3YTQxZWE4NzZkZDJmOGY3ZDA4MThkZDM0YTBhMGYzMzJjMDk5MzAwYTBlMGI5ZjFhYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PYxH7nT9KemCmjZhLB-U1L48zSe4TS5Z3S8ZuEj2cUU">

Did you raise a PR on this?

**Comment by prabhjeevnijjar** [comment]
> > @nwanduka
> > I have fixed the issue mentioned above locally.
> > I observed an inconsistency in UI:
> > When I get this popup as unregistered user.
> > The text says "Get early access to MeshMap!"
> > The close modal button shifts to the left side along with the text.
> > This is a small bug should I fix it right now or do I create a new bug report?
> > PFA SS
> > <img alt="Screenshot 2023-12-23 at 10 18 59 AM" width="1440" src="https://private-user-images.githubusercontent.com/30125794/292609093-a494edf5-30d1-427f-aa1b-948ff0e8b440.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MDE0MTQsIm5iZiI6MTcwMzgwMTExNCwicGF0aCI6Ii8zMDEyNTc5NC8yOTI2MDkwOTMtYTQ5NGVkZjUtMzBkMS00MjdmLWFhMWItOTQ4ZmYwZThiNDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDIyMDUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYjk2MTI1Zjg0Yzg3YTQxZWE4NzZkZDJmOGY3ZDA4MThkZDM0YTBhMGYzMzJjMDk5MzAwYTBlMGI5ZjFhYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PYxH7nT9KemCmjZhLB-U1L48zSe4TS5Z3S8ZuEj2cUU">
> 
> Did you raise a PR on this?

Will raise PR tommorow.

**Comment by prabhjeevnijjar** [comment]
Created PR @nwanduka

**Comment by nwanduka** [comment]
Awesome. Please jump on the Websites call on Monday so you can get feedback on your PR, and also share the UI issue you raised earlier. Let's get this merged as soon as possible.
