### ISSUE TITLE
[Extensions] Designs: Publish and Info modal issues

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9696]
### Current Behavior
1. The following to clips show the autosave feature causing loss of focus on the active field.

### Desired Behavior
1. Autosave should happen in the background.
2. Field ordering: Description should come before Caveats and Considerations
3. While the Publish modal needs to require all fields, the Info modal should not require any fields. Users should be able to update any of the values in these fields a la carte.

### Screenshots/Logs

https://github.com/meshery/meshery/assets/7570704/e558ba18-3fb6-4582-8f5c-ad24bdd2222b

https://github.com/meshery/meshery/assets/7570704/eb8746e4-e9be-4317-b2c5-b8f9fbd4644e

### Environment

- Browser: Safari
- Host OS: Mac 
- Meshery Server Version: stable-v0.7.3-patch.2

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
The technologies that I chose were not persisted.
![Screenshot 2023-12-21 at 5 43 12 PM](https://github.com/meshery/meshery/assets/7570704/9c4f1daa-703d-4ad5-aece-6569d1238bd6)

**Comment by ameeetgaikwad** [comment]
Would like to help! Can assign me.

**Comment by Yashsharma1911** [comment]
Thanks for raising your hand on this @ameeetgaikwad , I already fixed some of tasks related to this issue, and I'll recommend to check out more related issues, let us know if you didn't find one

**Comment by Yashsharma1911** [comment]
This issue is completed
