### ISSUE TITLE
[Docs] Add description and link to each Meshery schema

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9706]
### Current State
The Designs, Models, Components, Relationships, and other resources are schema-backed constructs in Meshery. 

### Desired State
Each should have a consistent blurb that points to their schema in https://github.com/meshery/schemas

Example:

-https://docs.meshery.io/concepts/connections should have a description of and link to its schema https://github.com/meshery/schemas/tree/master/openapi/schemas

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by LakshyaSatpal** [comment]
I would like to take this. Please assign this to me.

**Comment by goldfishdolphin** [comment]
@LakshyaSatpal you have been assigned the issue.

**Comment by leecalcote** [comment]
Thank you, @LakshyaSatpal, @goldfishdolphin.
