### ISSUE TITLE
[Docs] Jekyll logic showing through on Integrations page

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9749]
### Current State

On https://docs.meshery.io/integrations - - 

<img width="642" alt="Screenshot 2023-12-27 at 11 32 23 PM" src="https://github.com/meshery/meshery/assets/7570704/9dc119a8-5fb6-469b-bad2-06b51016213d">

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by rishidyno** [comment]
Hi @leecalcote, I would like to work on this issue, could you please assign me?

**Comment by leecalcote** [comment]
@rishidyno, you bet. 

Actually, this was just fixed by @MUzairS15 and @ripulhandoo

**Comment by leecalcote** [comment]
@rishidyno shall we find you another item to tackle?

**Comment by rishidyno** [comment]
Yes @leecalcote it would be great if you could assign me a newcomer issue.
