### ISSUE TITLE
[UI] Update style of cursor

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#9781]
### Current Behavior

Currently, when a user hovers over the **i button** on the widgets in dashboard, there is a tooltip that shows more info but doesn't update the cursor to pointer.

https://github.com/meshery/meshery/assets/73700530/10dc7c47-36a1-4966-8abb-50e6a143382d

### Desired Behavior

Ensure the styling of cursor is updated so that user understands the the **i button** is clickable.

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by OmAximani0** [comment]
Hello, can you please assign this to me

**Comment by kushagra-gupta01** [comment]
Please assign this task to me, as my approach would be to update the cursor property defined as the hover effect in the Dashboard.

**Comment by Paras-245** [comment]
Heyo I like to work on this issue. Kindly assign issue to me.

**Comment by aabidsofi19** [comment]
@OmAximani0  here you go ..

**Comment by Paras-245** [comment]
heyo could you tell how to run this locally because i cant find steps to run it.
Thx

**Comment by Yashsharma1911** [comment]
> heyo could you tell how to run this locally because i cant find steps to run it. Thx

@Paras-245 https://docs.meshery.io/project/contributing

**Comment by OmAximani0** [comment]
> heyo could you tell how to run this locally because i cant find steps to run it.
> Thx

Check out this [link](https://docs.meshery.io/project/contributing/contributing-ui)
