### ISSUE TITLE
[Docs]fix meshery docs navbar v0.6

### ISSUE THREAD

**Issue by Aniket-76** [meshery/meshery#9782]
### Current State
Redirecting Links in the navbar of v0.6 are not working 

![bug2](https://github.com/meshery/meshery/assets/92544172/8c9b9f8d-e37c-422d-bd37-fb2726cba4fb)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aniket-76** [comment]
@vishalvivekm I would like to fix this issue

**Comment by ALIPHATICHYD** [comment]
@vishalvivekm Can I be assigned to fix this issue

**Comment by vishalvivekm** [comment]
Hi folks, as discussed in the websites call, @Aniket-76 will be working to fix the issue.

**Comment by Aniket-76** [comment]
@vishalvivekm I am not getting code file for this 
Can you please help me?
