### ISSUE TITLE
[CI] Skip make targets if already invoked once

### ISSUE THREAD

**Issue by nitishm** [meshery/meshery#981]
**Current Behavior**
All makefile targets are run every time a top level `make` target is invoked. This can slow down the build process significantly and lead to issues in non-idempotent make target actions.

**Desired Behavior**

To skip prerun targets, that do not need to be run again, each target step should drop a turd (dummy artifact) or a real artifact. If the artifact exists, we can safely skip the step and continue onwards to other targets.

---
**Resources**
https://stackoverflow.com/questions/21745816/makefile-make-dependency-only-if-file-doesnt-exist

**Alternatives / Additional Context**
I am sure there are other ways to achieve the same goals but since my Makefile-fu is weak I cannot find a better way to do it.

CC @kanishkarj

**Comment by kushthedude** [comment]
Hi @nitishm, I don't get the issue. If you are saying to skip make command if dependency is already set-up then it is obsolete, as both npm & go-modules checks the manifest of the dependencies before actually fetching them.

**Comment by nitishm** [comment]
According to @kanishkarj there are a lot of targets that are rerun everytime you call a target with other dependencies. Since I am not to privy with the structure yet, I assumed that some dependencies being rebuilt can slow down the process.

**Comment by nitishm** [comment]
Also see - 10.4 Chains of Implicit Rules in https://www.gnu.org/software/make/manual/make.html#Chained-Rules

**Comment by kanishkarj** [comment]
@leecalcote Suggestions here?

**Comment by kushthedude** [comment]
> Also see - 10.4 Chains of Implicit Rules in https://www.gnu.org/software/make/manual/make.html#Chained-Rules

I still don't get it, only recurring make command is `go mod tidy` which is efficient not fetch deps everytime it's run and same for npm engine ?

**Comment by leecalcote** [comment]
Thanks for this, @nitishm! Whether its a reduction of duplicative command executions or a considerate organization of current command groups and their names, our Makefiles need some love.

**Comment by kanishkarj** [comment]
Do we want this instead ? 
https://stackoverflow.com/questions/31492675/node-build-from-makefile-only-if-source-changed

In this way what we'd have is if ran `make run-local`, we'll actually build only if the source files have been changed, if not we used the built version. It would be really helpful in the case of building ui too.

**Comment by leecalcote** [comment]
Makefile has been overhauled. It now includes a couple other Makefiles and help output.
