### ISSUE TITLE
[mesheryctl]Fix the grammatical error in the mesheryctl

### ISSUE THREAD

**Issue by Althaf66** [meshery/meshery#9810]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

![Screenshot 2024-01-02 150254](https://github.com/meshery/meshery/assets/114910365/f7d0e941-fe9f-494b-9726-ff5d4d749be7)

**Fix the grammatical error by 
   replacing '... is a invalid command' -----> '... is an invalid  command'.**

### Desired Behavior

![Screenshot 2024-01-02 153223](https://github.com/meshery/meshery/assets/114910365/1a18241a-b309-4f44-bc1d-4a579b37fd01)

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

**Comment by ALIPHATICHYD** [comment]
Hey there @Althaf66 Can I be assigned to work on this issue
