### ISSUE TITLE
[Docs] Relationships: Missing color for info/tip/note Alerts

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9818]
### Current State
See screenshot and this page - https://docs.meshery.io/concepts/relationships

<img width="897" alt="Screenshot 2024-01-02 at 2 02 13 PM" src="https://github.com/meshery/meshery/assets/7570704/9b332d76-75c5-40d0-95f3-4eb42882a52c">

### Desired State

Each type of `{% include alert.html %}` should have a `type` defined. See the guidance on this page - https://docs.meshery.io/project/contributing/contributing-docs#alerts

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by brandonkylely** [comment]
Hi, I gave this a shot and created a pull request. I noticed that the "models" page had a similar problem so I made changes to that as well.

https://github.com/meshery/meshery/pull/9823
