### ISSUE TITLE
[Docs] Contributing: Add debug level setting to Meshery Server contributing guide

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9819]
### Current State
The [Meshery Server Contributing Guide](https://docs.meshery.io/project/contributing/contributing-server) is missing documentation of how to adjust log levels.

### Desired State
The Server contributing guide should have a section detailing this feature - [[Server] Add support to change log levels at runtime #9815](https://github.com/meshery/meshery/pull/9815)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aayush2111** [comment]
I'm eager to contribute! Could you please assign this issue to me? I'd love to take it on. Thanks! @leecalcote

**Comment by leecalcote** [comment]
Thank you, @Aayush2111. Sounds good.

**Comment by Aayush2111** [comment]
The pull request for this task has already been created and merged into the codebase by @MUzairS15. You can review the changes in the following pull request:
https://github.com/meshery/meshery/pull/9827

Considering the completion of the pull request, I recommend marking this issue as completed.
@leecalcote
