### ISSUE TITLE
[UI] Issues in Environments and Workspaces

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#9840]
### Current Behavior

1. Couple of ui issues in environments and workspaces modals
2. while creating new Environments and workspaces the field `Name` has required`*` field set but then also the env and workspace gets created. And in that case , the transition modal have empty data 

https://github.com/meshery/meshery/assets/90546692/df4bf566-8810-46a0-8792-2f83338874eb

![image](https://github.com/meshery/meshery/assets/90546692/4e62e359-7864-4eb4-b0ae-6bcdc9ce8f6b)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by AjaxAueleke** [comment]
@sudhanshutech can I work on this?

**Comment by sudhanshutech** [comment]
here you go @AjaxAueleke , you have setup meshery right?

**Comment by AjaxAueleke** [comment]
yes I have setup meshery

**Comment by sudhanshutech** [comment]
@AjaxAueleke the second issue is related to rjsf let me know of you are comfortable until you quickly fix the first one asap

**Comment by Gauravjadhav22** [comment]
hi @sudhanshutech  if this task hasn't been assigned, may I work on it?

**Comment by AjaxAueleke** [comment]
@sudhanshutech  I've looked into the issue with the RJSF validation. According to the documentation, RJSF treats an empty string as a valid input for required fields, which is why rjsf validation isn't working as expected. I recommend modifying the schema to include a minLength constraint for the name field. This change will ensure that empty strings are not accepted as valid inputs. Additionally, I noticed that there's no validation on the backend, I think it'll be good to have some sort of validation in the backend as well.

**Comment by sudhanshutech** [comment]
Oh thats some nice points @AjaxAueleke , would you please open an issue regarding this `minLength ` to track . And regarding the ui issue it has already been resolved so if you like you can open the issue of `length` and will get you assigned
