### ISSUE TITLE
[Extensions] Enhance Shapes dock menu. Make consistent with Components dock menu

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9842]
### Current Behavior
The Shapes menu on the dock in MeshMap is a weaker version of the Components menu on the same dock.

### Implementation

1. Reuse the same menu component, if possible.
2. Style the same.
3. Incorporate the same features.

### Acceptance Tests
1. Menu separators have the same color and same with.
1. Chefs menu has the same search functionality. 
1. Menu items have the same font weight.

### Mockups
<img width="1045" alt="Screenshot 2024-01-05 at 7 35 47 PM" src="https://github.com/meshery/meshery/assets/7570704/38f5626a-ad39-4012-acea-b8324f4bc6cd">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by theavitw** [comment]
I can try.
