### ISSUE TITLE
[Extensions] Comment Notifications

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9843]
### Current Behavior
Users receive email notifications of their own comments, but shouldn't.

### Desired Behavior

**Rules:**
1. Only be concerned with one Comment (Component) at-at-time. Keep the scope of your logic to a single Comment at-a-time, irrespective of how many other Comments are in the Design.
1. Don’t notify the user who is making the comment (sending a message).
1. Always notify the design owner, unless the design owner is the individual making the comment. See #2.

**First process: Gather all implicated users.**
1. Automatically include the design owner.
1. Include all other users who have been “@mentioned”.

**Second process: Filter out people who should not be notified.**
1. Remove the user who is sending the message.
    - this includes the design owner
    - this includes the current user if they were previously “@mentioned”
1. Remove any user who’s preference is set to not be notified.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@vaibhavpnimkar, are you ready for this, yet?

**Comment by vaibhavpnimkar** [comment]
yes!

**Comment by vaibhavpnimkar** [comment]
I already have issues assigned, so I will start working after resolving those issues first.

**Comment by AjaxAueleke** [comment]
@leecalcote can I try this out while my other PR is getting reviewed?

**Comment by AjaxAueleke** [comment]
Removing myself from the assignee as Yash and Akshay are working on it.

**Comment by leecalcote** [comment]
Go ahead and assign them.

**Comment by AjaxAueleke** [comment]
I can't assign issues to users atm. I don't think I have the permission for it.

**Comment by leecalcote** [comment]
> I can't assign issues to users atm. I don't think I have the permission for it.

@AjaxAueleke, let's get that changed. 😉

**Comment by Yashsharma1911** [comment]
This issue is fixed
