### ISSUE TITLE
[mesheryctl] New command `exp relationship`

### ISSUE THREAD

**Issue by alphaX86** [meshery/meshery#9844]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Desired Behavior

Create an `exp relationship [list|view|search]` command similar to that of `exp model command.`
- [ ] Implement command to List Relationships
- [x] Implement command to  View Relationships
- [ ] Implement command to Search Relationships
- [ ] Develop test cases to ensure command functionality.

---

### Contributor Resources

- ⌨️ [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](http://discuss.meshery.io) and [Layer5 Community Slack](https://slack.meshery.io)

**Comment by alphaX86** [comment]
Hey @RipulHandoo that's great idea you've provided. I left it open because I need to deep dive on the API schema and decide the subcommands required. Anyway, we'll first look at completing `components` first, then we'll both work on this. What's your say? :)

**Comment by RipulHandoo** [comment]
> Hey @RipulHandoo that's great idea you've provided. I left it open because I need to deep dive on the API schema and decide the subcommands required. Anyway, we'll first look at completing `components` first, then we'll both work on this. What's your say? :)

@alphaX86 Sir, the `components` command is ready. If possible I'll give a demo for it in today's meeting. Here is the [PR](https://github.com/meshery/meshery/pull/9726) for it.

**Comment by saurabh100ni** [comment]
@alphaX86 you still working on this issue?

**Comment by alphaX86** [comment]
> @alphaX86 you still working on this issue?

Design spec not completed yet. This issue required a spec to be made

**Comment by sandramsc** [comment]
Hi @alphaX86 It's been some time since your last update. Are you still working on this issue?

**Comment by RipulHandoo** [comment]
@Aijeyomah Would you like to work on this issue?

**Comment by Aijeyomah** [comment]
> @Aijeyomah Would you like to work on this issue?
> 
> 
Yes, I'll love to work on it

**Comment by sandramsc** [comment]
@Aijeyomah I have assign this issue to you, remember to give regular updates to signal that you are still working on the issue and ask for community guidance in case you need it via the [discussion forum](https://discuss.layer5.io/).

**Comment by Aijeyomah** [comment]
> @Aijeyomah I have assigned this issue to you, remember to give regular updates to signal that you are still working on the issue and ask for community guidance in case you need it via the [discussion forum](https://discuss.layer5.io/). 

Alright

**Comment by Jougan-0** [comment]
@Aijeyomah you still working on this ?

**Comment by Aijeyomah** [comment]
> @Aijeyomah you still working on this ? 

Yes

**Comment by Jougan-0** [comment]
@Aijeyomah if you haven't started with the search command I would like to provide a hand already implemented the search myself .

**Comment by Aijeyomah** [comment]
> @Aijeyomah if you haven't started with the search command I would like to provide a hand already implemented the search myself .

I haven't started the it. You can go ahead👍
