### ISSUE TITLE
[Enhancement] Capitalize button text in Meshery UI modals

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#9846]
### Current Behavior
In some modals in Meshery, the button text is not capitalized and some modals have button text capitalized.

![image](https://github.com/meshery/meshery/assets/51539117/9453920b-a66a-4076-aeb2-2a6cad84d394)

![image](https://github.com/meshery/meshery/assets/51539117/79084a0c-d29f-489a-8422-49ecbdec445b)

### Desired Behavior
Capitalize the button text in all the modals

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aayush2111** [comment]
Would love to get started with this, if anyone is not working already.

**Comment by ritiksaxena124** [comment]
Go ahead @Aayush2111 👍

**Comment by Paras-245** [comment]
could you assign it i love to work on it
