### ISSUE TITLE
[Docs] Redirecting links of different version not working on localhost 

### ISSUE THREAD

**Issue by Aniket-76** [meshery/meshery#9847]
### Current State
404 error on localhost

[https://discuss.layer5.io/t/meshery-docs-navbar-error/4421](url)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aniket-76** [comment]
@leecalcote should I make changes in ` exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor, Makefile, v0.6, v0.5, v0.4] ` in _config_dev.yml?

**Comment by leecalcote** [comment]
you have a broken link in the description

**Comment by leecalcote** [comment]
@vishalvivekm can answer your question

**Comment by Aniket-76** [comment]
https://discuss.meshery.io/t/meshery-docs-navbar-error/4421

**Comment by vishalvivekm** [comment]
@Aniket-76 

>https://discuss.layer5.io/t/meshery-docs-navbar-error/4421/5?u=vishalvivekm : The past version of docs (i.e., v0.6, v0.5 and v0.4) are burried in time and seldom undergo changes. While they’re still crucial for live site, in dev environment we don’t expect modifications to be made in them. Not to mention, processing these huge past versions, will significantly add up to the overall build time resulting in even longer wait for recompiling and reflecting changes (currently takes about 15-20 seconds).

Hopefully this explains why we’ve exclude: [v0.6, v0.5, v0.4] in _config_dev.yml (config file for local build). If this makes sense, I think we can proceed with the closure of this issue, @Aniket-76

**Comment by Aniket-76** [comment]
Ok thanks for clarifying it.
