### ISSUE TITLE
Tab Indexing is not consistent in modals

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#9851]
### Current Behavior

The tab indexing lacks consistency; pressing the tab key should transition between fields uniformly. Currently, it changes for some fields but not for all.

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@Yashsharma1911 where are the schemas being stored now?

@MUzairS15 the state of our schemas is confusing. Can you rectify this? or can you @theBeginner86?

**Comment by Yashsharma1911** [comment]
> ...

@leecalcote We are currently sourcing schema from Meshkit, and here is schema link of the environment https://github.com/meshery/meshkit/blob/master/schemas/configuration/environment.json
