### ISSUE TITLE
[Enhancement] Label being cutoff in dashboard

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#9862]
### Current Behavior
On a smaller screen, the label of the tab menu in the dashboard is cut off
![image](https://github.com/meshery/meshery/assets/51539117/b13e5a33-935c-4c03-89a1-6d23ecc43cab)

### Desired Behavior
Label should not be cut-off in smaller screens

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
@vishalvivekm would like to take this one? or any other issue related to dashboard

**Comment by Aniket-76** [comment]
I would like to work on it

**Comment by vishalvivekm** [comment]
Apologies, I happened to miss this Shudhanshu. @sudhanshutech

**Comment by Aniket-76** [comment]
@vishalvivekm would you mind if I take this?
I actually solved it at my end.
