### ISSUE TITLE
[Enhancement][UI] Second tab in the dashboard not taking the whole width

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#9864]
### Current Behavior
On a smaller screen, the second tab in the dashboard does not take the whole width and the left and right arrows are not visible, making the second tab look like it is being cut off.
![image](https://github.com/meshery/meshery/assets/51539117/d36d9f17-60ef-4243-9389-de5820b5e8ce)

### Desired Behavior
1. Make the second tab take the whole width
2. Show the left and right arrows on both the end of the second tab as shown in the below image
![image](https://github.com/meshery/meshery/assets/51539117/67743261-7ef3-4b74-bb51-0ad1b7285aba)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aniket-76** [comment]
I would like to work on it
