### ISSUE TITLE
[UI]: Prevent overflow of dashboard tables on small screens

### ISSUE THREAD

**Issue by Paras-245** [meshery/meshery#9877]
### Current Behavior

On playground dashboard in workload and configuration tabs, UI become inconsistent with a sliding bar

### Desired Behavior

It should match with UI of other tabs and not overflow on sliding or should be handled accordingly

### Screenshots/Logs

![configuration](https://github.com/meshery/meshery/assets/86979565/8d7fcd1f-b03c-4462-a9e7-c7756bd89b09)
![workload](https://github.com/meshery/meshery/assets/86979565/13614265-1d62-457b-a5df-e5782f70ceea)

### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Don't forget to add a descriptive title, @Paras-245.

**Comment by Paras-245** [comment]
Sure from next time i take in mind.

**Comment by Paras-245** [comment]
i will try to fix it

**Comment by Yashsharma1911** [comment]
Good to go @Paras-245, Thanks for raising your hand @Vijaykv5, we have more similar issues you would like to look into

**Comment by leecalcote** [comment]
@Paras-245 thanks for your efforts. Let’s allow another contributor to carry this forward.

**Comment by sudhanshutech** [comment]
@AjaxAueleke are you tracking this? 
If not lets  @LakshyaSatpal have a crack on it. Would you @LakshyaSatpal ?

**Comment by AjaxAueleke** [comment]
@sudhanshutech nope, I am not atm. You can assign this to @LakshyaSatpal.

**Comment by LakshyaSatpal** [comment]
Yes. I can take this.

**Comment by LakshyaSatpal** [comment]
@sudhanshutech I'm not able to reproduce this issue. May I know the exact screen size?
