### ISSUE TITLE
[Extensions] Views: Notes missing undo and image support

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9888]
### Current Behavior
<img width="660" alt="Screenshot 2024-01-08 at 6 00 35 PM" src="https://github.com/meshery/meshery/assets/7570704/cb53363b-821e-4eea-a056-5127ca83562b">

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@aabidsofi19, I question whether its worth it to use this new/separate rich-text editor. CodeMirror (which we're already using with [collaborative editing](https://codemirror.net/examples/collab/) might be a better fit, assuming that we can find a [toolbar add-on](https://github.com/alterfan/cm-toolbar-addon).

**Comment by aabidsofi19** [comment]
@leecalcote  yeah , we should access that .. collaborative feature is great to have .
