### ISSUE TITLE
[UI] Hide Labels and Annotation in details page

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#9893]
### Current Behavior
Currently, we are showing the unique_id and kind columns under Labels and Annotation which are not providing much value to the users. 
![image](https://github.com/meshery/meshery/assets/51539117/ab2ff30e-81d1-42fb-a788-820d9fe2171c)

### Desired Behavior
Hide the uniquer_id and kind columns under Labels and Annotation

**How to Reproduce Issue?**
1. Go to the dashboard in Meshery UI
2. Under the Node tab, click on the name of any row. This will take you to the details page of the particular node
3. If you scroll down you will see the Labels and Annotation

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aayush2111** [comment]
I would like to work on this issue. Is it available? @ritiksaxena124

**Comment by ritiksaxena124** [comment]
Yup, go ahead @Aayush2111 👍.  Let's see if you can make it before tomorrow's Meshery Development Meeting at 8:30 PM IST.

more details: https://meet.meshery.io/

**Comment by sudhanshutech** [comment]
@Aayush2111 any updates?

**Comment by Aayush2111** [comment]
> @Aayush2111 any updates?

Finding it a little confusing to locate the file from where it's rendering further tables such as annotations and labels

**Comment by ANKITRAJ2403** [comment]
Hii @ritiksaxena124 , I want to work on this. I have setup Meshery locally , but how do I populate the data so that I can have some dummy data to work with ?

**Comment by Ashparshp** [comment]
@ANKITRAJ2403 You wanna work on this?

**Comment by ANKITRAJ2403** [comment]
Yes

**Comment by Ashparshp** [comment]
@sudhanshutech //
