### ISSUE TITLE
[UI] Light mode issue in node details page in the dashboard 

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#9894]
### Current Behavior
The wrong background color is used in some sections on the node details page
![image](https://github.com/meshery/meshery/assets/51539117/eee6c5f5-29b3-41a6-858b-5d4c9792d5eb)
### Desired Behavior
Fix the wrong background color and make it consistent

**How to Reproduce Issue?**

1. Go to the dashboard in Meshery UI
2. Under the Node tab, click on the name of any row. This will take you to the details page of the particular node
3. You will see the issue in light mode

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by syedbarimanjan** [comment]
This looks like a good start for me I would like to do this.

**Comment by Shreyc711** [comment]
can I do this? @ritiksaxena124

**Comment by syedbarimanjan** [comment]
> can I do this? @ritiksaxena124

I am working on it

**Comment by Shreyc711** [comment]
Not a problem. Good luck

**Comment by sudhanshutech** [comment]
@syedbarimanjan any updates or progress?

**Comment by syedbarimanjan** [comment]
> @syedbarimanjan any updates or progress?

So i wanted to ask should i change it to look like the other tables or is there some other design for it like the same hover states and all?

**Comment by sudhanshutech** [comment]
@syedbarimanjan any progress?

**Comment by syedbarimanjan** [comment]
> @syedbarimanjan any progress?

I am really sorry I am busy with something else.

**Comment by ritiksaxena124** [comment]
It's been a while @syedbarimanjan and there is no progress also you are busy with something else so let's unassign you from this task.

**Comment by leecalcote** [comment]
> > @syedbarimanjan any progress?
> 
> I am really sorry I am busy with something else.

@syedbarimanjan next time, please remove your assignment, so you don't hold up the project when you're not focus on contributing here.

**Comment by Shreyc711** [comment]
Following
