### ISSUE TITLE
[Docs] Update the documentation for removing Meshery as a Docker extension

### ISSUE THREAD

**Issue by KrishAryan** [meshery/meshery#9901]
### Current State
The commands for removing Meshery as a Docker extension are incorrect.

https://docs.meshery.io/installation/docker/docker-extension#remove-meshery-as-a-docker-extension

### Desired State
Update the documentation for removing Meshery as a Docker extension. This can be performed via mesheryctl, Meshery UI, Kubectl, or Helm cli. All should be documented. Once that is complete, update the Docker extensions page to include centralized instructions.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by KrishAryan** [comment]
According to me, the kubectl commands required to remove meshery completely after removing meshery docker extension are:

kubectl delete deployment meshery-meshsync meshery-operator -n meshery
kubectl delete statefulset meshery-broker  -n meshery
kubectl delete svc meshery-broker meshery-operator -n meshery
kubectl delete namespace meshery

If there are commands that I am missing please let me know

**Comment by leecalcote** [comment]
@KiptoonKipkurui

**Comment by Cioraz** [comment]
Hello, can I take up this issue if available?

**Comment by Snehaaa18** [comment]
please assign me this issue

**Comment by Nabanita29** [comment]
I can work on this if available!
