### ISSUE TITLE
Research on enhancing validation errors for component schemas

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#9910]
### Current Behavior
The current behavior of [RJSF](https://rjsf-team.github.io/react-jsonschema-form/docs/) errors lacks sufficient descriptiveness for users to easily comprehend. We are exploring the AJV validator to enhance the clarity of these errors.

Please note that although RJSF provides the customError prop for passing custom errors in the form, we are actively seeking a more practical solution. Our goal is to enable custom error descriptions within the schemas themselves. This involves defining custom errors directly in the schema, and during schema processing, prioritizing these custom validation errors embedded in the schema.

### Desired Behavior
Augment component-source schemas with enhanced descriptions(custom descriptions), if we able to "render" our enhanced descriptions with the sourced descriptions, preferring our enhanced descriptions.
1. Docs links
1. Errors
  1. Docs links
  1. AJV6 interceptor?
1. Lint check for valid Meshery Docs URLs in UI-schemas

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Akshaybagai52** [comment]
hey @Yashsharma1911 can i work on this issue

**Comment by Yashsharma1911** [comment]
> hey @Yashsharma1911 can i work on this issue

Thankyou @Akshaybagai52 for raising your hand, have you previously worked with RJSF or AJV by chance, if not no worries

FYI this issue is only to research and discuss possible solutions, If solution will be feasible we will proceed with implementation, I'll update the issue more for you to deep dive into it
