### ISSUE TITLE
[Docs] Extra whitespace in code terminals

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9913]
### Current State
See https://docs.meshery.io/installation/quick-start/ for an example.

### Desired State

<img width="881" alt="Screenshot 2024-01-10 at 12 55 54 PM" src="https://github.com/meshery/meshery/assets/7570704/384d76db-195e-4a59-841c-0c303b9be1ef">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by divyanshkul** [comment]
Hey! Can I work on this?

**Comment by sandramsc** [comment]
@divyanshkul I have assigned this to you.

**Comment by AkashMeheta** [comment]
Has anyone already fixed this?

**Comment by leecalcote** [comment]
@divyanshkul any luck so far? Given @AkashMeheta's PR, I wonder if we might find you a new issue to work on...

**Comment by leecalcote** [comment]
@divyanshkul a quick check-in...

**Comment by AkashMeheta** [comment]
> Given @AkashMeheta's PR

I submit a PR for this issue actually twitch first time I did not sign my commit but I fixed it at last PR

**Comment by AkashMeheta** [comment]
@leecalcote Of course I'm working on other issues
