### ISSUE TITLE
[Docs] Quick Start: Copy to clipboard not working

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9914]
### Current State

![image_720](https://github.com/meshery/meshery/assets/7570704/580ec732-46ee-4aa8-93cd-5bf2c9889c9c)

Page - 

### Desired State

Should copy 

```
curl -L https://meshery.io/install | PLATFORM=kubernetes bash -
```

No `$` included.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by gaus13** [comment]
@leecalcote please assign it to me 
I want to work on this issue

**Comment by UditaSaxena** [comment]
@leecalcote I may resolve it. please assign it to me!

**Comment by Shubh2025** [comment]
I will resolve this issue please assign it to me .

**Comment by gaus13** [comment]
I am working on this issue it's assigned to me, its almost done will make a PR by tomorrow

**Comment by UditaSaxena** [comment]
> I am working on this issue it's assigned to me, its almost done will make a PR by tomorrow

fine! all the best

**Comment by ranjeetxsingh** [comment]
@gaus13 did you finished it?? if not can it be assigned to me ? @leecalcote

**Comment by leecalcote** [comment]
@ranjeetxsingh first confirm whether or not this is still an issue. Go look… Is it?

**Comment by leecalcote** [comment]
Unassigning @gaus13 as this effort seems to have been abandoned.

**Comment by ranjeetxsingh** [comment]
@leecalcote  it is not same as demonstrated in the issue's current state image, the copy button is now not visible. However copy button is visible and functioning on the rest of the website. While opening quick-start.html file console is showing error in reading properties from terminal.js file which is causing this issue. I can work on it.

**Comment by ranjeetxsingh** [comment]
@leecalcote  I have created a PULL REQUEST for the issue, it has been fixed. Please review and merge the PR. Thankyou

**Comment by leecalcote** [comment]
Thanks, @ranjeetxsingh. 

@sandramsc would you like to review?
