### ISSUE TITLE
Service mesh docs redirect error

### ISSUE THREAD

**Issue by chiragbiradar** [meshery/meshery#9929]
### Current State
![image](https://github.com/meshery/meshery/assets/78417411/38c84cf4-140f-47c2-adc3-784be1d7c8c5)

Error url: https://docs.meshery.io/service-meshes

Got this error from https://docs.meshery.io/guides/infrastructure-management/sample-apps > Deploy a sample app on Meshery > 1. Go to the management page of any [service mesh](https://docs.meshery.io/service-meshes) and install any of its stable versions.
![image](https://github.com/meshery/meshery/assets/78417411/35efe8fe-995c-4d41-8518-792f484ab14a)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Please remove the broken hyperlink.

**Comment by chiragbiradar** [comment]
@leecalcote Sure, do I need to add another link instead or just remove the broken hyperlink?

**Comment by chiragbiradar** [comment]
@leecalcote https://github.com/meshery/meshery/pull/9930,
I have fixed the hyperlink

**Comment by leecalcote** [comment]
fixed
