### ISSUE TITLE
[CI]: Push to Protected Branch without Pull Request

### ISSUE THREAD

**Issue by RipulHandoo** [meshery/meshery#9932]
### Current Behavior

Currently, the GitHub Actions [workflow](https://github.com/meshery/meshery/blob/master/.github/workflows/build-and-release-edge.yml#L12-L46) is attempting to push changes directly to the master branch, which is a protected branch in the repository. This results in a rejection due to the branch protection rules, which require changes to be made through a pull request.

### Desired Behavior

The issue is to modify the GitHub Actions workflow to create a pull request instead of attempting to push changes directly to the protected master branch.

### Implementation

Modify the GitHub Actions workflow to create a new branch, commit the changes to that branch, and then create a pull request to merge the changes into the master branch. This approach aligns with best practices for code review and ensures that changes go through the proper review process.

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by leecalcote** [comment]
@RipulHandoo thanks for this. Is the workflow that you've mentioned failing?

**Comment by RipulHandoo** [comment]
> @RipulHandoo thanks for this. Is the workflow that you've mentioned failing? If not, please note that the point of the workflow is to automate necessary tasks for building and publishing an Edge release. Inserting manual review will break that automated process. The workflow and its actions are considered to be trusted and operating within the confines of its defined operating procedure.
> 
> I could be missing something here, though. I wonder if this was a topic discussed on today's Meshery CI meeting and I'm missing context for the issue.

Yes @leecalcote Sir this topic was discussed in today's Meshery CI meeting. @theBeginner86 asked me to raise an issue. So we can have a history/record of it.

**Comment by MarioArriaga92** [comment]
@RipulHandoo and anyone else interested, let's discuss options in in Layer5 discuss forum please:
https://discuss.meshery.io/t/meshery-build-and-release-jan-11th-2024/4491/4?u=marioarriaga92
