### ISSUE TITLE
[Docs] broken link

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery#9935]
### Current State
the link https://docs.meshery.io/guides/creating-a-meshery-design is broken

### Desired State
On [Creating a Meshery design](https://docs.meshery.io/guides/configuration-management/creating-a-meshery-design) page, a redirect from https://docs.meshery.io/guides/creating-a-meshery-design could be added to point to https://docs.meshery.io/guides/configuration-management/creating-a-meshery-design

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by officialrajdeepsingh** [comment]
The correct link is this [https://docs.meshery.io/guides/configuration-management/creating-a-meshery-design](https://docs.meshery.io/guides/configuration-management/creating-a-meshery-design)

**Comment by Souravpakhira** [comment]
Hey can I fix this issue it will be a great start for me to explore the repo as well

**Comment by jaymorelli96** [comment]
Not sure where the link is broken, from the [guides page](https://docs.meshery.io/guides) the link to [Creating a Meshery Design](https://docs.meshery.io/guides/configuration-management/creating-a-meshery-design) points to the right location

**Comment by MonalikaPatnaik** [comment]
Hi, @vishalvivekm can I work on this?

**Comment by prathyushmadhu** [comment]
You can access "Creating a Meshery Design" at "https://docs.meshery.io/guides/configuration-management/creating-a-meshery-design". Hope the issue gets closed.

**Comment by vishalvivekm** [comment]
Thank you, folks.

Following FCFS, 
@Souravpakhira, it will be helpful if you could raise a PR with the fix so it can be reviewed.

@MonalikaPatnaik Please find a bunch of good-first and help wanted issues that you might wanna work on:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by Souravpakhira** [comment]
> [creating-a-meshery-design](https://docs.meshery.io/guides/creating-a-meshery-design)

Can you please help me identify where the broken link is? Knowing the exact page will make my work easier.

**Comment by vishalvivekm** [comment]
> On [Creating a Meshery design](https://docs.meshery.io/guides/configuration-management/creating-a-meshery-design) page, a redirect from https://docs.meshery.io/guides/creating-a-meshery-design could be added to point to https://docs.meshery.io/guides/configuration-management/creating-a-meshery-design

@Souravpakhira adding `redirect_from: guides/creating-a-meshery-design`
in [guides/configuration-management/creating-a-meshery-design](https://github.com/meshery/meshery/blob/master/docs/pages/guides/configuration-management/creating-a-meshery-design.md) page's frontmatter will work.

**Comment by vishalvivekm** [comment]
when you google, `creating-a-meshery-design`, https://docs.meshery.io/guides/creating-a-meshery-design comes up as result and is broken.
