### ISSUE TITLE
[UX] Graphic Design: Create a Meshery CLI Cheatsheet

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9942]
### Current Behavior
The [Meshery CLI has many commands and subcommands](https://docs.meshery.io/reference/mesheryctl). Navigating it initially can be a challenge for users.

### Desired Behavior
Create and share a visual cheatsheet as an overview the Meshery's set of CLI commands.

### Implementation
Ideally, use vector graphics with either Figma (see community Figma files below) or Illustrator. 

### Mockups
Example:
<img width="554" alt="Screenshot 2024-01-12 at 1 23 41 PM" src="https://github.com/meshery/meshery/assets/7570704/2825165f-f5bf-4805-9d2d-0e7e5844a6f6">

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Dhanush0369** [comment]
@leecalcote I have understood the issue . And I have used figma before.I would love to work on this issue. Please assign it to me.

**Comment by leecalcote** [comment]
Sounds good, @Dhanush0369

**Comment by Dhanush0369** [comment]
![Frame 14 (5)](https://github.com/meshery/meshery/assets/111651814/0c5ec838-8d89-4d78-b348-b37588961d4e)
This is what i have made, Please look at it and give review .

**Comment by leecalcote** [comment]
@Dhanush0369 looking real good! Will you create a pull request with the source (SVG or AI)?

@nwanduka might attempt to spruce it up a little.

**Comment by Dhanush0369** [comment]
@leecalcote I have corrected the title and rearranged them for symmetry. Should i add the SVG file in the [meshery/docs/assets/img] directory or any other directory in the pull request.

**Comment by leecalcote** [comment]
Yes, that directory will work well.
