### ISSUE TITLE
[Extension][Cloud] - Helper icon for prompt component

### ISSUE THREAD

**Issue by senali-d** [meshery/meshery#9949]
### Current Behavior

<img width="475" alt="Screenshot 2024-01-13 at 9 02 35 PM" src="https://github.com/meshery/meshery/assets/52546856/422b807b-90ca-462f-8279-57234f770477">

### Desired Behavior

- Add helper icon for the prompt component.
- When hover over the icon tooltip message have to appear.

<img width="780" alt="Screenshot 2024-01-13 at 8 56 24 PM" src="https://github.com/meshery/meshery/assets/52546856/a661393c-d650-45d0-bf2c-12e96345b689">

<img width="496" alt="Screenshot 2024-01-13 at 9 00 28 PM" src="https://github.com/meshery/meshery/assets/52546856/b4f7e3a5-7cb9-47c6-b679-09a02a627bc4">

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by officialrajdeepsingh** [comment]
Assign me to fix this issue.

**Comment by jaymehta002** [comment]
assign me this issue

**Comment by leecalcote** [comment]
@Yashsharma1911, please track this and assist with verbiage as necessary.

@officialrajdeepsingh, please use the `layer5/sistent-svg` NPM package for the icon. // @nebula-aac

**Comment by leecalcote** [comment]
@officialrajdeepsingh, also delete the whitespace between "Environment" and "?" in the title: "Delete Environment ?"

**Comment by officialrajdeepsingh** [comment]
Hi, I follow the guidelines to install meshery locally. But I face an error when I'm running.

```bash
make ui-setup
```

Error is look like this.

```bash
❯ make ui-setup
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
cd ui; npm i; cd ..
make: /bin/bash: No such file or directory
make: *** [Makefile:252: ui-setup] Error 127

meshery on  master via 🐹 v1.21.4 
```

I already install the go and make CLI (gnumake42). 

```bash
> go version
go version go1.21.4 linux/amd64

> make -v
GNU Make 4.4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Current operating system NixOS.

```
# System Details Report
---

## Report details
- **Date generated:**                              2024-01-17 16:10:11

## Hardware Information:
- **Hardware Model:**                              HP HP Pavilion Laptop 15-eg2xxx
- **Memory:**                                      8.0 GiB
- **Processor:**                                   12th Gen Intel® Core™ i5-1240P × 16
- **Graphics:**                                    Intel® Graphics (ADL GT2)
- **Disk Capacity:**                               512.1 GB

## Software Information:
- **Firmware Version:**                            F.03
- **OS Name:**                                     NixOS 24.05 (Uakari)
- **OS Build:**                                    24.05.20231211.a9bf124
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.2
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.1.67
```

**Comment by PranitPatil03** [comment]
hey @senali-d 

What should the hover message be?

**Comment by anmolchhabra21** [comment]
@sudhanshutech, can you please assign me this issue, I will change the styles, as per the theme only, and will remove the `${environment.name}`, as said it was already shown in the modal.

**Comment by sudhanshutech** [comment]
These modals are now been replaced with sistent standard modals.Hence this is now a completed issue.
