### ISSUE TITLE
[Docs] Broken Links

### ISSUE THREAD

**Issue by MonalikaPatnaik** [meshery/meshery#9951]
### Current State
If u visit this link (https://docs.meshery.io/guides/configuration-management/working-with-designs) you see almost all the links are redirecting to 404 error page.

### Desired State
It should redirect to the correct url.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by neerajmanivarnan** [comment]
Can I work on this issue?

**Comment by MonalikaPatnaik** [comment]
Hi @leecalcote, I think the PR #9954 still not resolves this issue.
- the [designs](https://docs.meshery.io/guides/tasks/patterns.md) link is redirecting to 404 page. It should be written like `[designs](/tasks/pattern-management)` in [configuration-management line 25](https://github.com/meshery/meshery/blob/370bf384042671c384685fdb47c3c7e29cd84027/docs/pages/guides/configuration-management/configuration-management.md?plain=1#L25).
- [mesheryctl pattern subcommand section](https://docs.meshery.io/guides/reference/mesheryctl/#cloud-native-pattern-configuration-and-management) is redirecting to 404 page. It should be written like `[mesheryctl pattern subcommand section](../../reference/mesheryctl/#cloud-native-pattern-configuration-and-management)` in [configuration-management line 63](https://github.com/meshery/meshery/blob/370bf384042671c384685fdb47c3c7e29cd84027/docs/pages/guides/configuration-management/configuration-management.md?plain=1#L63C1-L63C1)
- [Imagehub](https://docs.meshery.io/guides/configuration-management/guides/deploying-sample-apps) is redirecting to 404 page. It should be written like `[ImageHub](../infrastructure-management/sample-apps#imagehub)` in [configuration-management line 77](https://github.com/meshery/meshery/blob/370bf384042671c384685fdb47c3c7e29cd84027/docs/pages/guides/configuration-management/configuration-management.md?plain=1#L77C1-L77C1)
- [sample applications](https://docs.meshery.io/guides/configuration-management/deploying-sample-apps.md) is redirecting to 404 page. It should be written like `[sample applications](../infrastructure-management/sample-apps)` in [configuration-management line 107](https://github.com/meshery/meshery/blob/370bf384042671c384685fdb47c3c7e29cd84027/docs/pages/guides/configuration-management/configuration-management.md?plain=1#L107)
- [Performance Management with Meshery](https://docs.meshery.io/guides/configuration-management/performance-management.md) is redirecting to 404 page. It should be written like `[Performance Management with Meshery](../performance/performance-management)` in [configuration-management line 121](https://github.com/meshery/meshery/blob/370bf384042671c384685fdb47c3c7e29cd84027/docs/pages/guides/configuration-management/configuration-management.md?plain=1#L121)

The above changes works fine on my machine. Let me know if I'm missing out anything.
Thanks!

**Comment by leecalcote** [comment]
Depending upon the change needed, please consider use of redirect_from as well, so that any external sites that might be linking to the old page location are redirected to the new page location.
