### ISSUE TITLE
[Docs] Broken Link 

### ISSUE THREAD

**Issue by neerajmanivarnan** [meshery/meshery#9957]
### Current State
Many of the links are still broken in this page  (https://docs.meshery.io/guides/configuration-management/working-with-designs)

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by neerajmanivarnan** [comment]
I am working on this issue right now.Please assign this to me

**Comment by Snehaaa18** [comment]
if this issue is open I would like to work on it
