### ISSUE TITLE
[Artifact Hub] Meshery Designs as a new Artifact Hub kind

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9967]
This is a child issue of https://github.com/meshery/meshery/issues/9966. See its description for more context.

### Current Behavior
[Meshery Designs](http://docs.meshery.io/concepts/logical/designs) are not a first-class artifact recognized in Artifact Hub.

### Desired Behavior
Artifact Hub to support and list [Meshery Designs](http://docs.meshery.io/concepts/logical/designs) as an artifact kind.

### Implementation
See this example as useful information about the [process of creating a new artifact kind](https://github.com/artifacthub/hub/issues/3350#issuecomment-1733796153).

### Acceptance Tests
1. Meshery Designs are listed on the https://artifacthub.io home page as a supported kind.
2. Users are able to search and list Meshery Designs.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by omerfsen** [comment]
I want to contribute to this

**Comment by leecalcote** [comment]
@omerfsen, I missed your message previously. If still interested, yes, please do.
