### ISSUE TITLE
[Server] Events for Seed content

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#9980]
### Desired Behavior

1. The events are transmitted to the UI.
2. In case of failure, the error logs are recorded on the disk log file.

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Anuragt1104** [comment]
hey , can i work on this issue?

**Comment by MUzairS15** [comment]
Are you familiar with sending events from Server to UI client?

**Comment by Anuragt1104** [comment]
Yes

**Comment by MUzairS15** [comment]
Outline your approach here, remember this issue isn't suitable for new contributors, better find other issues so that you get familiarised with the project before taking on such issues.

**Comment by leecalcote** [comment]
@MUzairS15 is a `willfix` appropriate?
