### ISSUE TITLE
[Docs Designs] Repeated phrase

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#9995]
### Current State
Link: [Meshery Docs](https://docs.meshery.io/concepts/logical/designs)

Currently the phrase "All the resources and their properties that you want for a single deployment written in..." has been duplicated within the same paragraph.

### Desired State

Remove the repeated phrase so the sentence reads as follows: "A Design describes all the resources and their properties that you want for a single deployment written in YAML based on Meshery’s declarative syntax (see [Meshery Schemas repo](https://docs.meshery.io/concepts/logical/(https://github.com/meshery/schemas)))."

#### Screenshots
![bug1](https://github.com/meshery/meshery/assets/19821445/3aca94ce-d915-421f-89d3-9a5ead2328af)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by ASK-03** [comment]
Hey @sandramsc! I would like to work on this issue. Please assign this to me.

**Comment by sandramsc** [comment]
Hi @ASK-03 I have assigned this to you.

**Comment by ASK-03** [comment]
@sandramsc, I have created a pull request for this issue. I hope, I have followed all the community guidelines correctly. Tell me if there are any changes : )
