### ISSUE TITLE
[Docs Designs] - List items descriptions are identicle

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#9996]
### Current Behavior

Link: [Meshery Docs](https://docs.meshery.io/concepts/logical/designs)

Currently the list items under "Suggested Reading" have identical descriptions.

### Expected Behavior

Listing the same description for each item appears repetitive and does not add value to the section.

- If the intention is to add a unique description for each listed item - then the appropriate/fitting content should be provided and added accordingly.
- If the intention is to have the current description for all the listed items - then the description should be added as a subheading, and list the items without a description.

### Screenshots/Logs

![Screenshot 2024-01-17 201314](https://github.com/meshery/meshery/assets/19821445/ddf0b3e2-c872-49a4-a4d8-65929ef02a4c)

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sandramsc** [comment]
CC: @leecalcote @VivekBaldha0712

**Comment by leecalcote** [comment]
Uh-oh. Bug!

@iArchitSharma

**Comment by sandramsc** [comment]
@Sarita-Singh This is a great point, please consider starting a thread on the [discussion forum](https://discuss.layer5.io/) related to the topic so the community at large can pitch in - remember to link the issue?

**Comment by iArchitSharma** [comment]
oh taking a look
