### ISSUE TITLE
[Docs Designs] Misplaced full stop

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#9997]
### Current State
Link: [Meshery Docs](https://docs.meshery.io/concepts/logical/designs)

Section: Design Relationships and Restrictions

Currently the sentence "Designs can be converted into reusable Patterns. Creating a Pattern. involves replacing the values of the variables in the design with the values provided by another user. " has a misplaced full stop.

### Desired State

Remove the full stop so the sentence reads as follows: "Designs can be converted into reusable Patterns. Creating a Pattern involves replacing the values of the variables in the design with the values provided by another user. "

#### Screenshot

![Screenshot 2024-01-17 201056](https://github.com/meshery/meshery/assets/19821445/07cef5c2-7563-43ca-a4c3-74aab1c36478)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by neerajmanivarnan** [comment]
Can I work on this issue?

**Comment by neerajmanivarnan** [comment]
I have made a PR but it is failing the meshmap screenshot check.Could you please help me with that?

**Comment by sandramsc** [comment]
> I have made a PR but it is failing the meshmap screenshot check.Could you please help me with that?

Hi @neerajmanivarnan thank you for the effort and eagerness to contribute. Please be reminded that you should only start to work on an issue after it has been assigned to you. In this instance, since you asked for assignment first (before another contributor) your PR is valid. I suggest you read our CONTRIBUTING.md if you haven't already, particularly the section ["Working on an Issue" point #3](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md).

**Comment by neerajmanivarnan** [comment]
> > I have made a PR but it is failing the meshmap screenshot check.Could you please help me with that?
> 
> Hi @neerajmanivarnan thank you for the effort and eagerness to contribute. Please be reminded that you should only start to work on an issue after it has been assigned to you. In this instance, since you asked for assignment first (before another contributor) your PR is valid. I suggest you read our CONTRIBUTING.md if you haven't already, particularly the section ["Working on an Issue" point #3](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md).

My apologies for the mistake .I am new to the open source community
