### ISSUE TITLE
[Docs Cloud Native app Configuration] - Grammar adjustment

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#9999]
### Current State
 Link: [Configuring your Cloud Native Infrastructure and Applications
](https://docs.meshery.io/guides/configuration-management/working-with-designs)

Section: Creating a Meshery Design

Currently, this sentence reads as follows: "You have your choice of how are you would like to create an infrastructure design."
### Desired State

For increased readability and user experience the sentence could read as follows: "You are free to choose how you would like to create an infrastructure design."

#### Screenshots
![Screenshot 2024-01-17 204918](https://github.com/meshery/meshery/assets/19821445/c409ff21-2d2d-468a-898a-dbd7d0385719)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by shourya2002-geek** [comment]
Hi @sandramsc , I would like to work on this issue!

**Comment by sandramsc** [comment]
Hi @shourya2002-geek I have assigned this to you.
